Pices: PicesInterface::PicesFeatureVector Class Reference
PicesInterface::PicesFeatureVector Class Reference
#include <PicesFeatureVector.h>
Public Member Functions
PicesFeatureVector (PicesFeatureVector^ picesFeatureVector)
Instantiates a new Creates a new PicesFeatureVector instance of picesFeatureVector by duplicating its contents.
PicesFeatureVector (System::Array^ raster, System::String^ imageFileName, PicesRunLog^ log)
"imageFileName" will be parsed to get SipperFileName, ScanLine, and ScanCol.
PicesFeatureVector (PicesRaster^ raster, System::String^ imageFileName, PicesRasterList^ intermediateImages, PicesRunLog^ log)
PicesFeatureVector (ImageFeaturesPtr _features)
PicesFeatureVector (String^ _imageFileName, PicesClass^ _mlClass, PicesRasterList^ _intermediateImages, PicesRunLog^ log)
void AddInstrumentData (System::Single^ depth, System::Single^ salinity, System::Single^ oxygen, System::Single^ fluorescence)
void AddInstrumentData (PicesInstrumentData^ pid)
String^ FeatureName (int featureNum)
ImageFeaturesPtr Features ()
double FeatureValue (int featureNum)
ImageFeaturesPtr UnManagedClass ()
Static Public Member Functions
static ParsedImageFileName^ ParseImageFileName (System::String^ fullFileName)
static void ParseImageFileName (String^ _fullFileName, String^ %_sipperFileName, uint% _scanLine, uint% _scanCol)
Protected Member Functions
!PicesFeatureVector ()
Properties
float AreaMMSquare [get]
float CentroidCol [get]
float CentroidRow [get]
String^ ClassName [get]
System::DateTime CtdDateTime [get]
float Depth [get, set]
String^ ExampleFileName [get, set]
bool FeatureDataMissing [get]
float FilledArea [get]
PicesClass^ MLClass [get, set]
int NumFeatures [get]
float OrigSize [get]
float Probability [get, set]
bool Validated [get, set]
Detailed Description
Definition at line 41 of file PicesFeatureVector.h.
Constructor & Destructor Documentation
PicesInterface::PicesFeatureVector::PicesFeatureVector (PicesFeatureVector^ picesFeatureVector)
Instantiates a new Creates a new PicesFeatureVector instance of picesFeatureVector by duplicating its contents.
summary> Computes a feature vector image that is in "raster". This is a wrapper class for MLL::ImageFeatures allowing the managed word to
Definition at line 51 of file PicesFeatureVector.cpp.
References Features(), PicesInterface::PicesClassList::GetUniqueClass(), MemPreasPerFV, and KKMLL::FeatureVector::MLClass().
Referenced by PicesFeatureVector().
PicesInterface::PicesFeatureVector::PicesFeatureVector (System::Array^ raster, System::String^ imageFileName, PicesRunLog^ log)
"imageFileName" will be parsed to get SipperFileName, ScanLine, and ScanCol.
/summary> param name='raster'> Raster in the form of a 2 dimensional byte array.
param name='imageFileName'> Name of image that is stored in 'raster'; should follow Sipper file name conventions.
param name='log'> logging file.
seealso cref='MLL::ImageFeatures::CalcFeatures'/> summary> Computes features from the image that is in "raster"; Features that are based off instrumentation data that will come from the IntrumentDataManager. The "imageFileName" will be parsed to get SipperFileName and ScanLine. /summary> seealso cref='MLL::ImageFeatures::CalcFeatures'/>.
Definition at line 96 of file PicesFeatureVector.cpp.
References PicesInterface::PicesRaster::BuildRasterObj(), KKB::Raster::FileName(), PicesInterface::PicesClassList::GetUnKnownClassStatic(), PicesInterface::PicesRunLog::Log(), MemPreasPerFV, PicesInterface::PicesKKStr::SystemStringToKKStr(), and PicesInterface::PicesClass::UnmanagedMLClass().
PicesInterface::PicesFeatureVector::PicesFeatureVector (PicesRaster^ raster, System::String^ imageFileName, PicesRasterList^ intermediateImages, PicesRunLog^ log)
Definition at line 63 of file PicesFeatureVector.cpp.
References PicesInterface::PicesRasterList::AddList(), KKB::Raster::FileName(), PicesInterface::PicesClassList::GetUnKnownClassStatic(), PicesInterface::PicesRunLog::Log(), MemPreasPerFV, PicesInterface::PicesKKStr::SystemStringToKKStr(), PicesInterface::PicesRaster::UnmanagedClass(), and PicesInterface::PicesClass::UnmanagedMLClass().
PicesInterface::PicesFeatureVector::PicesFeatureVector (ImageFeaturesPtr _features)
Definition at line 121 of file PicesFeatureVector.cpp.
References PicesInterface::PicesClassList::GetUniqueClass(), PicesInterface::PicesKKStr::KKStrToSystenStr(), MemPreasPerFV, and KKMLL::FeatureVector::MLClass().
PicesInterface::PicesFeatureVector::PicesFeatureVector (String^ _imageFileName, PicesClass^ _mlClass, PicesRasterList^ _intermediateImages, PicesRunLog^ log)
Definition at line 134 of file PicesFeatureVector.cpp.
References PicesInterface::PicesRasterList::AddList(), PicesInterface::PicesClassList::GetUnKnownClassStatic(), PicesInterface::PicesRunLog::Log(), MemPreasPerFV, PicesFeatureVector(), PicesInterface::PicesKKStr::SystemStringToKKStr(), and PicesInterface::PicesClass::UnmanagedMLClass().
PicesInterface::PicesFeatureVector::!PicesFeatureVector () protected
Definition at line 174 of file PicesFeatureVector.cpp.
References MLL::ImageFeatures::AreaMMSquare(), MLL::ImageFeatures::CentroidCol(), KKMLL::FeatureVector::ClassName(), MLL::ImageFeatures::CtdDateTime(), PicesInterface::PicesMethods::DateTimeKKUtoSystem(), MLL::ImageFeatures::Depth(), KKMLL::FeatureVector::ExampleFileName(), KKMLL::FeatureVector::FeatureData(), MLL::ImageFeatures::FilledArea(), PicesInterface::PicesClassList::GetUniqueClass(), PicesInterface::PicesClassList::GetUnKnownClassStatic(), PicesInterface::PicesKKStr::KKStrToSystenStr(), MemPreasPerFV, KKMLL::FeatureVector::MLClass(), PicesInterface::PicesClass::Name, KKMLL::FeatureVector::NumOfFeatures(), KKMLL::FeatureVector::OrigSize(), KKMLL::FeatureVector::Probability(), PicesInterface::PicesKKStr::SystemStringToKKStr(), PicesInterface::PicesClass::UnmanagedMLClass(), and KKMLL::FeatureVector::Validated().
Member Function Documentation
void PicesInterface::PicesFeatureVector::AddInstrumentData (System::Single^ depth, System::Single^ salinity, System::Single^ oxygen, System::Single^ fluorescence)
Definition at line 398 of file PicesFeatureVector.cpp.
References MLL::ImageFeatures::Depth(), MLL::ImageFeatures::Fluorescence(), MLL::ImageFeatures::Oxygen(), and MLL::ImageFeatures::Salinity().
Referenced by SipperFile.ImageViewer::ImageViewer(), SipperFile.ActiveTrainingLibraries::MakePredictions(), PicesInterface::TrainingModel2::PredictClass(), SipperFile.PredictionBreakDownDisplay::PredictionBreakDownDisplay(), SipperFile.PredictionBreakDownDisplayDual::PredictionBreakDownDisplayDual(), PicesInterface::TrainingModel2::PredictProbabilities(), and PicesCommander.ClassifierProcess::StartThread().
void PicesInterface::PicesFeatureVector::AddInstrumentData (PicesInstrumentData^ pid)
Definition at line 412 of file PicesFeatureVector.cpp.
References PicesInterface::PicesInstrumentData::Depth, MLL::ImageFeatures::Depth(), PicesInterface::PicesInstrumentData::FlowRate1, MLL::ImageFeatures::FlowRate1(), PicesInterface::PicesInstrumentData::FlowRate2, MLL::ImageFeatures::FlowRate2(), PicesInterface::PicesInstrumentData::Fluorescence, MLL::ImageFeatures::Fluorescence(), PicesInterface::PicesInstrumentData::Oxygen, MLL::ImageFeatures::Oxygen(), PicesInterface::PicesInstrumentData::Salinity, and MLL::ImageFeatures::Salinity().
String PicesInterface::PicesFeatureVector::FeatureName (int featureNum)
Definition at line 378 of file PicesFeatureVector.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr().
Referenced by SipperFile.FeatureDataDisplay::FeatureDataDisplay().
ImageFeaturesPtr PicesInterface::PicesFeatureVector::Features () inline
Definition at line 118 of file PicesFeatureVector.h.
Referenced by PicesInterface::TrainingModel2::BuildTrainingModel(), PicesInterface::PicesFeatureVectorList::CreateListForAGivenLevel(), PicesInterface::PicesDataBase::FeatureDataInsertRow(), PicesFeatureVector(), PicesInterface::TrainingModel2::PredictClass(), and PicesInterface::TrainingModel2::PredictProbabilities().
double PicesInterface::PicesFeatureVector::FeatureValue (int featureNum)
Definition at line 385 of file PicesFeatureVector.cpp.
References KKMLL::FeatureVector::FeatureData(), and KKMLL::FeatureVector::NumOfFeatures().
Referenced by SipperFile.FeatureDataDisplay::FeatureDataDisplay().
ParsedImageFileName PicesInterface::PicesFeatureVector::ParseImageFileName (System::String^ fullFileName) static
Definition at line 432 of file PicesFeatureVector.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by SipperFile.ActiveTrainingLibraries::MakePredictions(), PicesCommander.ReconcileImagesToDataBase::ReconcileImagesToDataBase(), and PicesCommander.SaveActiveTrainingModelFeatureData::SaveActiveTrainingModelFeatureData().
void PicesInterface::PicesFeatureVector::ParseImageFileName (String^ _fullFileName, String^ % _sipperFileName, uint% _scanLine, uint% _scanCol) static
Definition at line 452 of file PicesFeatureVector.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
ImageFeaturesPtr PicesInterface::PicesFeatureVector::UnManagedClass () inline
Definition at line 136 of file PicesFeatureVector.h.
Referenced by PicesInterface::PicesDataBase::FeatureDataUpdate(), PicesInterface::TrainingModel2::FindWorstSupportVectors(), PicesInterface::TrainingModel2::FindWorstSupportVectors2(), PicesInterface::TrainingModel2::PredictClass(), PicesInterface::TrainingModel2::ProbabilitiesByClassDual(), and PicesInterface::PicesFeatureVectorList::ToFeatureVectorList().
Property Documentation
float PicesInterface::PicesFeatureVector::AreaMMSquare get
Definition at line 92 of file PicesFeatureVector.h.
Referenced by SipperFile.ImageViewer::ImageViewer(), and PicesCommander.ClassifierProcess::StartThread().
float PicesInterface::PicesFeatureVector::CentroidCol get
Definition at line 93 of file PicesFeatureVector.h.
Referenced by PicesCommander.ImportImagesIntoDeployment::ImportImagesIntoDeployment(), and PicesCommander.ImportValidatdClass::ImportValidatdClass().
float PicesInterface::PicesFeatureVector::CentroidRow get
Definition at line 94 of file PicesFeatureVector.h.
Referenced by PicesCommander.ImportImagesIntoDeployment::ImportImagesIntoDeployment(), and PicesCommander.ImportValidatdClass::ImportValidatdClass().
String^ PicesInterface::PicesFeatureVector::ClassName get
Definition at line 95 of file PicesFeatureVector.h.
System:: DateTime PicesInterface::PicesFeatureVector::CtdDateTime get
Definition at line 96 of file PicesFeatureVector.h.
Referenced by PicesCommander.ClassifierProcess::StartThread().
float PicesInterface::PicesFeatureVector::Depth get set
Definition at line 97 of file PicesFeatureVector.h.
Referenced by PicesCommander.ClassificationStatus::CleanUpMemory(), PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets(), PicesCommander.SaveActiveTrainingModelFeatureData::SaveActiveTrainingModelFeatureData(), PicesCommander.SaveFeatureData::SaveFeatureData(), and PicesCommander.ClassifierProcess::StartThread().
String^ PicesInterface::PicesFeatureVector::ExampleFileName get set
Definition at line 101 of file PicesFeatureVector.h.
Referenced by PicesCommander.ClassificationStatus::CleanUpMemory(), PicesInterface::PicesFeatureVectorList::FeatureVectorComparitorByImageFileName::Compare(), PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets(), PicesCommander.ImportImagesIntoDeployment::ImportImagesIntoDeployment(), PicesCommander.ImportValidatdClass::ImportValidatdClass(), PicesCommander.SaveActiveTrainingModelFeatureData::SaveActiveTrainingModelFeatureData(), PicesCommander.SaveFeatureData::SaveFeatureData(), and PicesCommander.ClassifierProcess::StartThread().
bool PicesInterface::PicesFeatureVector::FeatureDataMissing get
Definition at line 98 of file PicesFeatureVector.h.
Referenced by PicesCommander.SaveFeatureData::SaveFeatureData(), and PicesCommander.ClassifierProcess::StartThread().
float PicesInterface::PicesFeatureVector::FilledArea get
Definition at line 99 of file PicesFeatureVector.h.
Referenced by SipperFile.ImageViewer::ImageViewer().
PicesClass^ PicesInterface::PicesFeatureVector::MLClass get set
Definition at line 100 of file PicesFeatureVector.h.
Referenced by PicesCommander.ClassificationStatus::CleanUpMemory(), PicesInterface::PicesFeatureVectorList::ExtractExamplesForAGivenClass(), PicesInterface::PicesFeatureVectorList::ExtractListOfClasses(), GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters(), and PicesCommander.ClassifierProcess::StartThread().
int PicesInterface::PicesFeatureVector::NumFeatures get
Definition at line 102 of file PicesFeatureVector.h.
Referenced by SipperFile.FeatureDataDisplay::FeatureDataDisplay().
float PicesInterface::PicesFeatureVector::OrigSize get
Definition at line 103 of file PicesFeatureVector.h.
Referenced by PicesCommander.ClassificationStatus::CleanUpMemory(), PicesCommander.ImportImagesIntoDeployment::ImportImagesIntoDeployment(), PicesCommander.ImportValidatdClass::ImportValidatdClass(), and PicesCommander.SaveFeatureData::SaveFeatureData().
float PicesInterface::PicesFeatureVector::Probability get set
Definition at line 104 of file PicesFeatureVector.h.
Referenced by PicesCommander.ClassificationStatus::CleanUpMemory(), PicesCommander.SaveFeatureData::SaveFeatureData(), and PicesCommander.ClassifierProcess::StartThread().
bool PicesInterface::PicesFeatureVector::Validated get set
Definition at line 105 of file PicesFeatureVector.h.
Referenced by PicesCommander.ClassifierProcess::StartThread().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesFeatureVector.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesFeatureVector.cpp