Pices: MLL::CTD_Plus_Data Class Reference
MLL::CTD_Plus_Data Class Reference
#include <CTD_Plus_Data.h>
Public Member Functions
CTD_Plus_Data (bool _checkCDOM)
CTD_Plus_Data (const KKStr &_txt, double _latitude, bool &valid, const KKStr &ext0CCode, const KKStr &ext1CCode, const KKStr &ext2CCode, const KKStr &ext3CCode)
~CTD_Plus_Data ()
float BatteryVoltage () const
float CdomFluorescence () const
float CdomFluorescenceSensor () const
float Conductivity () const
const KKB::DateTime & Date () const
float Density () const
float Depth () const
float Fluorescence () const
float FluorescenceSensor () const
CTD_Plus_Data & operator= (const CTD_Plus_Data &right)
float Oxygen () const
float OxygenSensor () const
float Pressure () const
float Salinity () const
float SoundVelocity () const
float Temperature () const
KKStr ToStrNoLabels () const
float Transmisivity () const
float TransmisivitySensor () const
float Turbidity () const
float TurbiditySensor () const
bool ValidData () const
Returns 'true' if the CTD data fields appear to be valid.
Static Public Member Functions
static KKStr Header1Str ()
static KKStr Header2Str ()
Detailed Description
Definition at line 11 of file CTD_Plus_Data.h.
Constructor & Destructor Documentation
CTD_Plus_Data::CTD_Plus_Data (bool _checkCDOM)
Definition at line 32 of file CTD_Plus_Data.cpp.
CTD_Plus_Data::CTD_Plus_Data (const KKStr & _txt, double _latitude, bool & valid, const KKStr & ext0CCode, const KKStr & ext1CCode, const KKStr & ext2CCode, const KKStr & ext3CCode)
Definition at line 134 of file CTD_Plus_Data.cpp.
References KKB::DateType::Day(), KKB::KKStr::Empty(), KKB::DateType::Month(), KKB::KKStr::Split(), ToFloat(), and KKB::DateType::Year().
CTD_Plus_Data::~CTD_Plus_Data ()
Definition at line 546 of file CTD_Plus_Data.cpp.
Member Function Documentation
float MLL::CTD_Plus_Data::BatteryVoltage () const inline
Definition at line 28 of file CTD_Plus_Data.h.
Referenced by MLL::InstrumentDataManager::CreateInstrumentData(), and MLL::InstrumentData::UpdateFromCtdData().
float MLL::CTD_Plus_Data::CdomFluorescence () const inline
Definition at line 36 of file CTD_Plus_Data.h.
Referenced by MLL::InstrumentDataManager::CreateInstrumentData(), and MLL::InstrumentData::UpdateFromCtdData().
float MLL::CTD_Plus_Data::CdomFluorescenceSensor () const inline
Definition at line 37 of file CTD_Plus_Data.h.
Referenced by MLL::InstrumentDataManager::CreateInstrumentData(), and MLL::InstrumentData::UpdateFromCtdData().
float MLL::CTD_Plus_Data::Conductivity () const inline
Definition at line 29 of file CTD_Plus_Data.h.
Referenced by MLL::InstrumentDataManager::CreateInstrumentData(), and MLL::InstrumentData::UpdateFromCtdData().
const KKB::DateTime& MLL::CTD_Plus_Data::Date () const inline
Definition at line 31 of file CTD_Plus_Data.h.
Referenced by MLL::InstrumentDataManager::CompReportLine(), and MLL::InstrumentDataManager::CreateInstrumentData().
float MLL::CTD_Plus_Data::Density () const inline
Definition at line 32 of file CTD_Plus_Data.h.
Referenced by MLL::InstrumentDataManager::CreateInstrumentData(), and MLL::InstrumentData::UpdateFromCtdData().
float MLL::CTD_Plus_Data::Depth () const inline
Definition at line 33 of file CTD_Plus_Data.h.
Referenced by MLL::InstrumentDataManager::CompReportLine(), MLL::InstrumentDataManager::CreateInstrumentData(), and MLL::InstrumentData::UpdateFromCtdData().
float MLL::CTD_Plus_Data::Fluorescence () const inline
Definition at line 34 of file CTD_Plus_Data.h.
Referenced by MLL::InstrumentDataManager::CreateInstrumentData(), and MLL::InstrumentData::UpdateFromCtdData().
float MLL::CTD_Plus_Data::FluorescenceSensor () const inline
Definition at line 35 of file CTD_Plus_Data.h.
Referenced by MLL::InstrumentDataManager::CreateInstrumentData(), and MLL::InstrumentData::UpdateFromCtdData().
KKStr CTD_Plus_Data::Header1Str () static
Definition at line 594 of file CTD_Plus_Data.cpp.
Referenced by MLL::InstrumentDataManager::InstrumentDataManager().
KKStr CTD_Plus_Data::Header2Str () static
Definition at line 623 of file CTD_Plus_Data.cpp.
Referenced by MLL::InstrumentDataManager::InstrumentDataManager().
CTD_Plus_Data & CTD_Plus_Data::operator= (const CTD_Plus_Data & right)
Definition at line 552 of file CTD_Plus_Data.cpp.
float MLL::CTD_Plus_Data::Oxygen () const inline
Definition at line 38 of file CTD_Plus_Data.h.
Referenced by MLL::InstrumentDataManager::CreateInstrumentData(), and MLL::InstrumentData::UpdateFromCtdData().
float MLL::CTD_Plus_Data::OxygenSensor () const inline
Definition at line 39 of file CTD_Plus_Data.h.
Referenced by MLL::InstrumentDataManager::CreateInstrumentData(), and MLL::InstrumentData::UpdateFromCtdData().
float MLL::CTD_Plus_Data::Pressure () const inline
Definition at line 40 of file CTD_Plus_Data.h.
Referenced by MLL::InstrumentDataManager::CreateInstrumentData(), and MLL::InstrumentData::UpdateFromCtdData().
float MLL::CTD_Plus_Data::Salinity () const inline
Definition at line 41 of file CTD_Plus_Data.h.
Referenced by MLL::InstrumentDataManager::CreateInstrumentData(), and MLL::InstrumentData::UpdateFromCtdData().
float MLL::CTD_Plus_Data::SoundVelocity () const inline
Definition at line 42 of file CTD_Plus_Data.h.
Referenced by MLL::InstrumentDataManager::CreateInstrumentData(), and MLL::InstrumentData::UpdateFromCtdData().
float MLL::CTD_Plus_Data::Temperature () const inline
Definition at line 43 of file CTD_Plus_Data.h.
Referenced by MLL::InstrumentDataManager::CreateInstrumentData(), and MLL::InstrumentData::UpdateFromCtdData().
KKStr CTD_Plus_Data::ToStrNoLabels () const
Definition at line 651 of file CTD_Plus_Data.cpp.
References KKB::StrFormatDouble().
Referenced by MLL::InstrumentDataManager::CompReportLine().
float MLL::CTD_Plus_Data::Transmisivity () const inline
Definition at line 44 of file CTD_Plus_Data.h.
Referenced by MLL::InstrumentDataManager::CreateInstrumentData(), and MLL::InstrumentData::UpdateFromCtdData().
float MLL::CTD_Plus_Data::TransmisivitySensor () const inline
Definition at line 45 of file CTD_Plus_Data.h.
Referenced by MLL::InstrumentDataManager::CreateInstrumentData(), and MLL::InstrumentData::UpdateFromCtdData().
float MLL::CTD_Plus_Data::Turbidity () const inline
Definition at line 46 of file CTD_Plus_Data.h.
Referenced by MLL::InstrumentDataManager::CreateInstrumentData(), and MLL::InstrumentData::UpdateFromCtdData().
float MLL::CTD_Plus_Data::TurbiditySensor () const inline
Definition at line 47 of file CTD_Plus_Data.h.
Referenced by MLL::InstrumentDataManager::CreateInstrumentData(), and MLL::InstrumentData::UpdateFromCtdData().
bool CTD_Plus_Data::ValidData () const
Returns 'true' if the CTD data fields appear to be valid.
Definition at line 680 of file CTD_Plus_Data.cpp.
References KKB::DateTime::Year().
Referenced by MLL::InstrumentDataManager::CTDdataPlus().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/CTD_Plus_Data.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/CTD_Plus_Data.cpp