Pices: PicesInterface::PicesMethods Class Reference
PicesInterface::PicesMethods Class Reference
#include <PicesMethods.h>
Public Member Functions
PicesMethods ()
Static Public Member Functions
static System::DateTime DateKKUtoSystem (const KKB::DateType &date)
static KKB::DateType DateSystemToKKU (System::DateTime dt)
static System::DateTime DateTimeKKUtoSystem (const KKB::DateTime &date)
static KKB::DateTime DateTimeSystemToKKU (System::DateTime dt)
static array< String^ >^ GetListOfSipperFiles (PicesRunLog^ log)
Returns a list of all known SIPPER files on the local PC; each entry includes the file path.
static System::String^ LatitudeLongitudeToString (double latitude, double longitude)
static System::String^ LatitudeToString (double latitude, int minDecimals)
static System::String^ LongitudeToString (double longitude, int minDecimals)
static String^ SipperFileNameFromImageFileName (String^ imageFileName)
static void StartMemoryLeakDetection ()
static System::TimeSpan TimeTypeKKUtoSystem (const KKB::TimeType &t)
Detailed Description
Definition at line 13 of file PicesMethods.h.
Constructor & Destructor Documentation
PicesMethods::PicesMethods ()
Definition at line 28 of file PicesMethods.cpp.
Member Function Documentation
System::DateTime PicesMethods::DateKKUtoSystem (const KKB::DateType & date) static
Definition at line 65 of file PicesMethods.cpp.
References KKB::DateType::Day(), KKB::DateType::Month(), and KKB::DateType::Year().
KKB::DateType PicesMethods::DateSystemToKKU (System::DateTime dt) static
Definition at line 71 of file PicesMethods.cpp.
System::DateTime PicesMethods::DateTimeKKUtoSystem (const KKB::DateTime & date) static
Definition at line 81 of file PicesMethods.cpp.
References KKB::DateTime::Date(), KKB::DateType::Day(), KKB::TimeType::Hour(), KKB::Max(), KKB::Min(), KKB::TimeType::Minute(), KKB::DateType::Month(), KKB::TimeType::Second(), KKB::DateTime::Time(), and KKB::DateType::Year().
Referenced by PicesInterface::PicesDataBaseLogEntry::!PicesDataBaseLogEntry(), PicesInterface::PicesFeatureVector::!PicesFeatureVector(), PicesInterface::PicesSipperDeployment::!PicesSipperDeployment(), PicesInterface::PicesSipperStation::!PicesSipperStation(), PicesInterface::PicesAbundanceCorrectionMatrix::DateTimeComputed(), and PicesInterface::PicesAbundanceCorrectionMatrix::PrintAdjustedResults().
KKB::DateTime PicesMethods::DateTimeSystemToKKU (System::DateTime dt) static
Definition at line 114 of file PicesMethods.cpp.
Referenced by PicesInterface::PicesDataBaseLogEntry::!PicesDataBaseLogEntry(), PicesInterface::PicesSipperDeployment::!PicesSipperDeployment(), PicesInterface::PicesSipperStation::!PicesSipperStation(), and PicesInterface::PicesDataBaseLogEntry::PicesDataBaseLogEntry().
array< String^ > PicesMethods::GetListOfSipperFiles (PicesRunLog^ log) static
Returns a list of all known SIPPER files on the local PC; each entry includes the file path.
Definition at line 36 of file PicesMethods.cpp.
References PicesInterface::PicesRunLog::Log().
System::String PicesMethods::LatitudeLongitudeToString (double latitude, double longitude) static
Definition at line 199 of file PicesMethods.cpp.
Referenced by PicesInterface::PicesSipperDeployment::!PicesSipperDeployment(), PicesInterface::PicesSipperStation::!PicesSipperStation(), PicesCommander.ChartGPS::ChartGPS(), and PicesCommander.ChartGPSByStation::ChartGPSByStation().
System::String PicesMethods::LatitudeToString (double latitude, int minDecimals) static
Definition at line 129 of file PicesMethods.cpp.
Referenced by PicesCommander.ChartGPS::ChartGPS(), and PicesCommander.ChartGPSByStation::ChartGPSByStation().
System::String PicesMethods::LongitudeToString (double longitude, int minDecimals) static
Definition at line 159 of file PicesMethods.cpp.
Referenced by PicesCommander.ChartGPS::ChartGPS(), and PicesCommander.ChartGPSByStation::ChartGPSByStation().
String PicesMethods::SipperFileNameFromImageFileName (String^ imageFileName) static
Definition at line 56 of file PicesMethods.cpp.
Referenced by PicesCommander.ClassificationStatus::CleanUpMemory(), and PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets().
void PicesMethods::StartMemoryLeakDetection () static
Definition at line 231 of file PicesMethods.cpp.
System::TimeSpan PicesMethods::TimeTypeKKUtoSystem (const KKB::TimeType & t) static
Definition at line 121 of file PicesMethods.cpp.
References KKB::TimeType::Hour(), KKB::TimeType::Minute(), and KKB::TimeType::Second().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesMethods.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesMethods.cpp