Pices: MLL::VolumeSampledStatList Class Reference
MLL::VolumeSampledStatList Class Reference
#include <VolumeSampledStat.h>
Public Types
typedef KKB::kkint32 kkint32
typedef VolumeSampledStatList * VolumeSampledStatListPtr
Public Member Functions
VolumeSampledStatList ()
~VolumeSampledStatList ()
void Add (const VolumeSampledStat &stat)
void Give (VolumeSampledStatPtr &stat)
Caller is giving ownership of 'stat' to this instance; upon return 'stat' may be set to NULL indicating that it was merged with an existing instance already in the list.
VolumeSampledStatPtr Locate (int binId)
VolumeSampledStatList & operator+= (const VolumeSampledStatList &right)
Detailed Description
Definition at line 58 of file VolumeSampledStat.h.
Member Typedef Documentation
typedef KKB::kkint32 MLL::VolumeSampledStatList::kkint32
Definition at line 61 of file VolumeSampledStat.h.
typedef VolumeSampledStatList* MLL::VolumeSampledStatList::VolumeSampledStatListPtr
Definition at line 62 of file VolumeSampledStat.h.
Constructor & Destructor Documentation
VolumeSampledStatList::VolumeSampledStatList ()
Definition at line 65 of file VolumeSampledStat.cpp.
VolumeSampledStatList::~VolumeSampledStatList ()
Definition at line 72 of file VolumeSampledStat.cpp.
Member Function Documentation
void VolumeSampledStatList::Add (const VolumeSampledStat & stat)
Definition at line 95 of file VolumeSampledStat.cpp.
References MLL::VolumeSampledStat::BinId(), Locate(), and MLL::VolumeSampledStat::VolumeSampled().
Referenced by MLL::DataBase::InstrumentDataDeploymentVolumeSampled(), and operator+=().
void VolumeSampledStatList::Give (VolumeSampledStatPtr & stat)
Caller is giving ownership of 'stat' to this instance; upon return 'stat' may be set to NULL indicating that it was merged with an existing instance already in the list.
Definition at line 110 of file VolumeSampledStat.cpp.
References MLL::VolumeSampledStat::AddToVolumeSampled(), MLL::VolumeSampledStat::BinId(), Locate(), and MLL::VolumeSampledStat::VolumeSampled().
Referenced by MLL::DataBase::InstrumentDataGetVolumePerMeterDepth().
VolumeSampledStatPtr VolumeSampledStatList::Locate (int binId)
Definition at line 83 of file VolumeSampledStat.cpp.
Referenced by Add(), Give(), and MLL::DataBase::ImagesSizeDistributionByDepth().
VolumeSampledStatList & VolumeSampledStatList::operator+= (const VolumeSampledStatList & right)
Definition at line 128 of file VolumeSampledStat.cpp.
References Add().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/VolumeSampledStat.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/VolumeSampledStat.cpp