Pices: ImageExtractionManager::FrameExtractorThread Class Reference
ImageExtractionManager::FrameExtractorThread Class Reference
#include <FrameExtractorThread.h>
Public Member Functions
FrameExtractorThread (ExtractionParms &_parms, ExtractionManagerPtr _extractionManager, const KKStr &_threadName, MsgQueuePtr _msgQueue, LogicalFrameQueuePtr _framePool, SipperFilePtr _sipperFileRec, SipperExtractionImageManagerPtr _imageManager, bool &_successful)
virtual ~FrameExtractorThread ()
InstrumentDataManagerPtr DataManager () const
kkuint32 FrameWidth () const
void GetRunTimeStats (kkuint64 &_bytesRead, kkuint32 &_framesRead)
virtual void Run ()
const KKStr & SipperBuffFileName () const
virtual ThreadTypes ThreadType ()
Public Member Functions inherited from ImageExtractionManager::ImageExtractionThread
ImageExtractionThread (ExtractionParms &_parms, ExtractionManagerPtr _extractionManager, const KKStr &_threadName, MsgQueuePtr _msgQueue)
virtual ~ImageExtractionThread ()
Public Member Functions inherited from KKB::KKThread
KKThread (const KKStr &_threadName, KKThreadManagerPtr _threadManager, MsgQueuePtr _msgQueue)
virtual ~KKThread ()
void AddShutdownPrerequistite (KKThreadPtr _thread)
Specify threads that must stop before this thread is started.
void AddStartPrerequistite (KKThreadPtr _thread)
Specify threads that must start before this thread is started.
VolConstBool & CancelFlag () const
Another name for 'TerminateFlag'.
bool Crashed () const
Signifies that this thread had to terminate on its own because of an abnormal situation; such as a memory corruption.
void Crashed (bool _crashed)
const KKStr & ExceptionText () const
If the overloaded 'Run' method of a derived class generates a exception that is not caught; then the ''ThreadStartCallBack' will catch it and store the related text in this field.
void ExceptionText (const KKStr &_exceptionText)
KKStrListPtr GetMsgs ()
void Kill ()
stops the running thread and frees the thread handle
kkint32 MemoryConsumedEstimated ()
KKB::MsgQueuePtr MsgQueue ()
bool OkToShutdown () const
Returns 'true' if all shutdown prerequisites are in the 'Stopped' status.
bool OkToStart () const
Returns 'true' if all start prerequisites are in the 'Running' status.
VolConstBool & ShutdownFlag () const
Indicates that the application wants this thread to complete what work is queued up for it top process.
void ShutdownThread ()
Call this method to have its thread finish what ever is in the queue and then exit.
void Start (ThreadPriority _priority, bool &successful)
Call this method to start thread; it will call the method "Run".
ThreadStatus Status () const
void Status (ThreadStatus _status)
const KKStr & StatusStr () const
VolConstBool & TerminateFlag () const
Indicates that thread is to stop processing ASAP, release any resources it holds and terminate.
virtual void TerminateFlagChanged ()
Will be called whenever the value of 'terminateFlag' is changed; derived classes should override this method if they need to be aware that the terminaeFlag has changed.
void TerminateThread ()
Call this method to have its thread stop right away and exit.
kkint32 ThreadId () const
const KKStr & ThreadName () const
bool ThreadStillProcessing () const
void WaitForThreadToStop (kkuint32 maxTimeToWait)
Called by separate thread; will stay in loop until the thread controlled by this instance shutdown or it waited the 'maxTimeToWait'.
Additional Inherited Members
Public Types inherited from ImageExtractionManager::ImageExtractionThread
enum ThreadTypes : int { ThreadTypes::FrameExtractor, ThreadTypes::FrameProcessor, ThreadTypes::DataBaseUpdater }
Public Types inherited from KKB::KKThread
typedef KKThread * KKThreadPtr
enum ThreadPriority : int { ThreadPriority::Null, ThreadPriority::Low, ThreadPriority::Normal, ThreadPriority::High }
enum ThreadStatus : int {
ThreadStatus::Null, ThreadStatus::NotStarted, ThreadStatus::Starting, ThreadStatus::Running,
ThreadStatus::Stopping, ThreadStatus::Stopped
}
Static Public Member Functions inherited from KKB::KKThread
static const KKStr & ThreadStatusToStr (ThreadStatus)
Protected Member Functions inherited from KKB::KKThread
void AddMsg (KKStrPtr msg)
Taking ownership of 'msg' and will append to 'msgQueue'.
void AddMsg (const KKStr &msg)
A copy of the message 'msg' will be added to the end of msgQueue.
bool ShutdownOrTerminateRequested ()
bool ThereIsACircularReferenceShutdown (KKThreadPtr _thread) const
bool ThereIsACircularReferenceStart (KKThreadPtr _thread) const
Protected Attributes inherited from ImageExtractionManager::ImageExtractionThread
ExtractionManagerPtr extractionManager
Pointer to instance that manages all the threads.
ExtractionParms & parms
Detailed Description
Definition at line 15 of file FrameExtractorThread.h.
Constructor & Destructor Documentation
FrameExtractorThread::FrameExtractorThread (ExtractionParms & _parms, ExtractionManagerPtr _extractionManager, const KKStr & _threadName, MsgQueuePtr _msgQueue, LogicalFrameQueuePtr _framePool, SipperFilePtr _sipperFileRec, SipperExtractionImageManagerPtr _imageManager, bool & _successful)
Definition at line 41 of file FrameExtractorThread.cpp.
References KKB::KKThread::AddMsg(), ImageExtractionManager::ExtractionParms::CameraNum(), KKB::endl(), ImageExtractionManager::ExtractionParms::FileFormat(), KKB::osAddSlash(), KKB::osGetRootName(), ImageExtractionManager::ExtractionParms::OutputRootDir(), ImageExtractionManager::ImageExtractionThread::parms, ImageExtractionManager::ExtractionParms::ScanLineEnd(), ImageExtractionManager::ExtractionParms::ScanLineStart(), ImageExtractionManager::ExtractionParms::SipperFileName(), and uint32_max.
FrameExtractorThread::~FrameExtractorThread () virtual
Definition at line 165 of file FrameExtractorThread.cpp.
References KKB::KKThread::AddMsg().
Member Function Documentation
InstrumentDataManagerPtr ImageExtractionManager::FrameExtractorThread::DataManager () const inline
Definition at line 39 of file FrameExtractorThread.h.
References Run().
Referenced by ImageExtractionManager::ExtractionManager::ManageTheExtraction().
kkuint32 ImageExtractionManager::FrameExtractorThread::FrameWidth () const inline
Definition at line 32 of file FrameExtractorThread.h.
void FrameExtractorThread::GetRunTimeStats (kkuint64 & _bytesRead, kkuint32 & _framesRead)
Definition at line 181 of file FrameExtractorThread.cpp.
References MLL::SipperBuff::ByteOffset(), ImageExtractionManager::ExtractionParms::Colorize(), MLL::SipperBuff::CurRow(), ImageExtractionManager::ExtractionParms::FramesOnly(), MLL::SipperBuff::GetNextLine(), KKB::Raster::Green(), ImageExtractionManager::ExtractionParms::IncrementLinesExtracted(), MaxArtifactLineWidth, ImageExtractionManager::ImageExtractionThread::parms, ImageExtractionManager::ExtractionParms::PreProcess(), MLL::SipperExtractionImageManager::SaveFrame(), ImageExtractionManager::ExtractionParms::SaveFrames(), ImageExtractionManager::ExtractionParms::SaveFramesAfter(), and KKB::StrFormatInt().
Referenced by ImageExtractionManager::ExtractionManager::GetRunTimeStats(), and SipperBuffFileName().
void FrameExtractorThread::Run () virtual
Reimplemented from KKB::KKThread.
Definition at line 546 of file FrameExtractorThread.cpp.
References ImageExtractionManager::LogicalFrameQueue::AddBackToAvailableFrames(), KKB::KKThread::AddMsg(), MLL::SipperBuff::ByteOffset(), ImageExtractionManager::ExtractionParms::BytesExtracted(), KKB::KKThread::CancelFlag(), ImageExtractionManager::ExtractionParms::FramesOnly(), ImageExtractionManager::LogicalFrameQueue::GetNextAvailaleFrame(), KKB::osGetLocalDateTime(), KKB::osGetSystemTimeUsed(), KKB::osSleep(), ImageExtractionManager::ImageExtractionThread::parms, ImageExtractionManager::LogicalFrame::PopulateFrame(), ImageExtractionManager::LogicalFrameQueue::QueueFrameToProcess(), KKB::KKThread::Running, KKB::KKThread::Starting, KKB::KKThread::Status(), KKB::KKThread::Stopped, and KKB::KKThread::Stopping.
Referenced by DataManager().
const KKStr& ImageExtractionManager::FrameExtractorThread::SipperBuffFileName () const inline
Definition at line 33 of file FrameExtractorThread.h.
References GetRunTimeStats().
Referenced by ImageExtractionManager::ExtractionManager::ManageTheExtraction().
virtual ThreadTypes ImageExtractionManager::FrameExtractorThread::ThreadType () inline virtual
Implements ImageExtractionManager::ImageExtractionThread.
Definition at line 30 of file FrameExtractorThread.h.
References ImageExtractionManager::ImageExtractionThread::FrameExtractor.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/ImageExtractionManager/FrameExtractorThread.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/ImageExtractionManager/FrameExtractorThread.cpp