Pices: PicesInterface::PicesFeatureVectorList Class Reference
PicesInterface::PicesFeatureVectorList Class Reference
#include <PicesFeatureVectorList.h>
Classes
class FeatureVectorComparitorByImageFileName
Public Member Functions
PicesFeatureVectorList ()
PicesFeatureVectorList (ImageFeaturesList &examples)
PicesFeatureVectorList (FeatureVectorList &examples)
Takes ownership of the contents of 'examples' and empties it.
void AddQueue (PicesFeatureVectorList^ subQueue)
void CancelLoad ()
summary>Creates a list of FeatureVectors where the class assignment will reflect the specified Hierarchy level specified by 'level'.
PicesFeatureVectorList^ CreateListForAGivenLevel (uint level, PicesRunLog^ runLog)
PicesFeatureVectorList^ ExtractDulicateExamples (PicesRunLog^ runLog)
Will return a list of examples that are duplicates, that is they have the same root file name.
PicesFeatureVectorList^ ExtractExamplesForAGivenClass (PicesClass^ mlClass)
PicesClassList^ ExtractListOfClasses ()
void LoadInSubDirectoryTree (String^ rootDir, bool useDirectoryNameForClassName, PicesRunLog^ log, bool rewiteRootFeatureFile)
PicesFeatureVector^ LookUpByImageFileName (String^ imageFileName)
void RandomizeOrder ()
void Save (String^ fileName, String^ fileFormat, PicesRunLog^ runLog)
void SortByImageFileName ()
PicesFeatureVectorList^ StratifyAmoungstClasses (int numOfFolds)
summary> Will create a "FeatureVectorList" object that will contain the unmanaged instances that are in this list.
FeatureVectorListPtr ToFeatureVectorList (PicesRunLog^ runLog)
Protected Member Functions
!PicesFeatureVectorList ()
Properties
uint NumExamplesWritten [get]
bool Owner [get, set]
Detailed Description
Definition at line 19 of file PicesFeatureVectorList.h.
Constructor & Destructor Documentation
PicesInterface::PicesFeatureVectorList::PicesFeatureVectorList ()
Definition at line 51 of file PicesFeatureVectorList.cpp.
Referenced by CreateListForAGivenLevel(), ExtractExamplesForAGivenClass(), PicesFeatureVectorList(), and StratifyAmoungstClasses().
PicesInterface::PicesFeatureVectorList::PicesFeatureVectorList (ImageFeaturesList & examples)
Definition at line 60 of file PicesFeatureVectorList.cpp.
References KKB::KKQueue< Entry >::Owner().
PicesInterface::PicesFeatureVectorList::PicesFeatureVectorList (FeatureVectorList & examples)
Takes ownership of the contents of 'examples' and empties it.
remarks> Will take ownership of "examples" contents and reduce it to empty list by popping all its contents off stack. will convert contents into instances of 'ImageFeatures'. If current contents are instances of 'FeatureVector' will delete them; so make sure that they are not being used anywhere else. /remarks>
Definition at line 80 of file PicesFeatureVectorList.cpp.
References PicesFeatureVectorList(), and KKB::KKQueue< Entry >::PopFromFront().
PicesInterface::PicesFeatureVectorList::!PicesFeatureVectorList () protected
Definition at line 116 of file PicesFeatureVectorList.cpp.
Member Function Documentation
void PicesInterface::PicesFeatureVectorList::AddQueue (PicesFeatureVectorList^ subQueue)
Definition at line 276 of file PicesFeatureVectorList.cpp.
void PicesInterface::PicesFeatureVectorList::CancelLoad ()
summary>Creates a list of FeatureVectors where the class assignment will reflect the specified Hierarchy level specified by 'level'.
remarks> Will create a list of FeatureVectors where the class assignment will reflect the specified Hierarchy level specified by 'level'. The hierarchy of a given class will be indicated by underscore characters in the class name. code> ex: Level 1: gelatinous Level 2: gelatinous_hydromedusae Level 3: gelatinous_hydromedusae_solmundella /code> /remarks>
Definition at line 133 of file PicesFeatureVectorList.cpp.
Referenced by GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters().
PicesFeatureVectorList PicesInterface::PicesFeatureVectorList::CreateListForAGivenLevel (uint level, PicesRunLog^ runLog)
Definition at line 153 of file PicesFeatureVectorList.cpp.
References PicesInterface::PicesFeatureVector::Features(), LoadInSubDirectoryTree(), KKMLL::FeatureVector::MLClass(), and PicesFeatureVectorList().
PicesFeatureVectorList PicesInterface::PicesFeatureVectorList::ExtractDulicateExamples (PicesRunLog^ runLog)
Will return a list of examples that are duplicates, that is they have the same root file name.
If no duplicates are found then 'nullptr' will be returned. /summary>
Definition at line 408 of file PicesFeatureVectorList.cpp.
PicesFeatureVectorList PicesInterface::PicesFeatureVectorList::ExtractExamplesForAGivenClass (PicesClass^ mlClass)
Definition at line 260 of file PicesFeatureVectorList.cpp.
References PicesInterface::PicesFeatureVector::MLClass, and PicesFeatureVectorList().
Referenced by PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets(), PicesCommander.SaveFeatureData::SaveFeatureData(), and StratifyAmoungstClasses().
PicesClassList PicesInterface::PicesFeatureVectorList::ExtractListOfClasses ()
Definition at line 230 of file PicesFeatureVectorList.cpp.
References KKB::KKQueue< Entry >::Add(), and PicesInterface::PicesFeatureVector::MLClass.
Referenced by PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets(), PicesCommander.SaveFeatureData::SaveFeatureData(), and StratifyAmoungstClasses().
void PicesInterface::PicesFeatureVectorList::LoadInSubDirectoryTree (String^ rootDir, bool useDirectoryNameForClassName, PicesRunLog^ log, bool rewiteRootFeatureFile)
Definition at line 176 of file PicesFeatureVectorList.cpp.
References PicesInterface::PicesRunLog::Log(), KKB::KKQueue< Entry >::Owner(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by CreateListForAGivenLevel(), and GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters().
PicesFeatureVector PicesInterface::PicesFeatureVectorList::LookUpByImageFileName (String^ imageFileName)
Definition at line 356 of file PicesFeatureVectorList.cpp.
References PicesInterface::OSservices::GetRootName(), and SortByImageFileName().
void PicesInterface::PicesFeatureVectorList::RandomizeOrder ()
Definition at line 244 of file PicesFeatureVectorList.cpp.
Referenced by PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets(), PicesCommander.SaveFeatureData::SaveFeatureData(), and StratifyAmoungstClasses().
void PicesInterface::PicesFeatureVectorList::Save (String^ fileName, String^ fileFormat, PicesRunLog^ runLog)
Definition at line 437 of file PicesFeatureVectorList.cpp.
References KKMLL::FeatureVectorList::AllFeatures(), PicesInterface::PicesRunLog::Log(), KKMLL::FeatureFileIO::SaveFeatureFile(), PicesInterface::PicesKKStr::SystemStringToKKStr(), and ToFeatureVectorList().
Referenced by PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets(), and PicesCommander.SaveActiveTrainingModelFeatureData::SaveActiveTrainingModelFeatureData().
void PicesInterface::PicesFeatureVectorList::SortByImageFileName ()
Definition at line 346 of file PicesFeatureVectorList.cpp.
Referenced by PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets(), LookUpByImageFileName(), and PicesCommander.SaveActiveTrainingModelFeatureData::SaveActiveTrainingModelFeatureData().
PicesFeatureVectorList PicesInterface::PicesFeatureVectorList::StratifyAmoungstClasses (int numOfFolds)
summary> Will create a "FeatureVectorList" object that will contain the unmanaged instances that are in this list.
it will not own these instances because the Managed objects that currently own them. And if you delete them it will cause memory problems. /summary>
Definition at line 285 of file PicesFeatureVectorList.cpp.
References ExtractExamplesForAGivenClass(), ExtractListOfClasses(), PicesFeatureVectorList(), and RandomizeOrder().
Referenced by PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets(), and GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters().
FeatureVectorListPtr PicesInterface::PicesFeatureVectorList::ToFeatureVectorList (PicesRunLog^ runLog)
Definition at line 396 of file PicesFeatureVectorList.cpp.
References PicesInterface::PicesFeatureVector::UnManagedClass().
Referenced by Save(), PicesInterface::PicesFeatureFileIO::SaveFeatureFile(), and PicesInterface::PicesFeatureFileIO::SaveFeatureFileNormalized().
Property Documentation
uint PicesInterface::PicesFeatureVectorList::NumExamplesWritten get
Definition at line 47 of file PicesFeatureVectorList.h.
bool PicesInterface::PicesFeatureVectorList::Owner get set
Definition at line 49 of file PicesFeatureVectorList.h.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesFeatureVectorList.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesFeatureVectorList.cpp