Pices: PicesInterface::ClassificationBiasMatrix Class Reference
PicesInterface::ClassificationBiasMatrix Class Reference
Assists in adjusting a Classifiers output for bias of a classifier.
#include <ClassificationBiasMatrix.h>
Public Member Functions
ClassificationBiasMatrix (PicesRunLog^ _runLog)
ClassificationBiasMatrix (String^ _configFileName, PicesClassList^ _classes, PicesRunLog^ _runLog)
Will constuct a BisMatrix instance from from the parametyer file for '_configFileName'.
!ClassificationBiasMatrix ()
~ClassificationBiasMatrix ()
void PerformAdjustmnts (array< double >^classifiedCounts, array< double >^&adjCounts, array< double >^&stdErrors)
void PrintAdjustedResults (StreamWriter^ sw, array< double >^classifiedCounts)
void PrintBiasMatrix (StreamWriter^ sw)
void TestPaperResults (StreamWriter^ sw)
bool Valid ()
Properties
System::DateTime DateTimeFileWritten [get, set]
Detailed Description
Assists in adjusting a Classifiers output for bias of a classifier.
See the paper:
"Estimating the Taxonomic composition of a sample when individules are classified with error"
by Andrew Solow, Cabll Davis, Qiao Hu
Woods Hole Ocanographic Institution, Woods Hole Massachusetts
Marine Ecology Progresss Series
published 2006-july-06;  vol 216:309-311
This class uses the results of a previous 10 fold cross validation confuision matrix to adjust the results of a classification run. The application CrossValidation will create a parameter file in the directory "${PicesHomeDir}\\DataFiles\\TrainingModels" that contains the confusion matrix. The option "-BiasMatrix" tells the CrossValidation program to generate this parameter file. It will have the same name as the Configuration file with the extension ".BiasMatrix.txt" appeneded to the end. There is a Unmanged version of this class in PicesLibrary called MLL::ClassificationBiasMatrix
Definition at line 35 of file ClassificationBiasMatrix.h.
Constructor & Destructor Documentation
ClassificationBiasMatrix::ClassificationBiasMatrix (PicesRunLog^ _runLog)
Definition at line 83 of file ClassificationBiasMatrix.cpp.
References TestPaperResults().
Referenced by ~ClassificationBiasMatrix().
ClassificationBiasMatrix::ClassificationBiasMatrix (String^ _configFileName, PicesClassList^ _classes, PicesRunLog^ _runLog)
Will constuct a BisMatrix instance from from the parametyer file for '_configFileName'.
Parameters
[in] _configFileName The name of the BiasMatrix file will be derived from the configuration file name. the term '_BiasMatrix.txt' will be apended onto the end.
[in] _classes List of classes that you are expecting to be in the 'BiasMatrix' file.
[in,out] _runLog Logging file to use.
Definition at line 36 of file ClassificationBiasMatrix.cpp.
References PicesInterface::OSservices::RemoveExtension(), and PicesInterface::PicesRunLog::Writeln().
ClassificationBiasMatrix::!ClassificationBiasMatrix ()
Definition at line 105 of file ClassificationBiasMatrix.cpp.
ClassificationBiasMatrix::~ClassificationBiasMatrix ()
Definition at line 114 of file ClassificationBiasMatrix.cpp.
References ClassificationBiasMatrix(), and PicesInterface::PicesClassList::GetUniqueClass().
Member Function Documentation
void ClassificationBiasMatrix::PerformAdjustmnts (array< double >^ classifiedCounts, array< double >^& adjCounts, array< double >^& stdErrors)
Definition at line 404 of file ClassificationBiasMatrix.cpp.
References KKB::endl(), KKB::Matrix::Inverse(), KKB::Matrix::NumOfCols(), KKB::Matrix::NumOfRows(), KKB::Matrix::Transpose(), and PicesInterface::PicesRunLog::Writeln().
Referenced by PrintAdjustedResults(), and TestPaperResults().
void ClassificationBiasMatrix::PrintAdjustedResults (StreamWriter^ sw, array< double >^ classifiedCounts)
Definition at line 629 of file ClassificationBiasMatrix.cpp.
References PicesInterface::PicesClassList::ExtractThreeTitleLines(), PerformAdjustmnts(), and PicesInterface::PicesRunLog::Writeln().
Referenced by PicesCommander.ClassificationStatus::CleanUpMemory().
void ClassificationBiasMatrix::PrintBiasMatrix (StreamWriter^ sw)
Definition at line 554 of file ClassificationBiasMatrix.cpp.
References PicesInterface::PicesClassList::ExtractThreeTitleLines(), and PicesInterface::PicesRunLog::Writeln().
Referenced by PicesCommander.ClassificationStatus::CleanUpMemory(), and TestPaperResults().
void ClassificationBiasMatrix::TestPaperResults (StreamWriter^ sw)
Definition at line 179 of file ClassificationBiasMatrix.cpp.
References PicesInterface::PicesClassList::CreateFromCommaDelStr(), PicesInterface::PicesClassList::GetUniqueClass(), PicesInterface::PicesClassList::LookUpIndex(), PicesInterface::PicesClass::Name, PerformAdjustmnts(), PrintBiasMatrix(), PicesInterface::PicesKKStr::StrToDateTime(), PicesInterface::PicesKKStr::StrToDouble(), and PicesInterface::PicesRunLog::Writeln().
Referenced by ClassificationBiasMatrix().
bool PicesInterface::ClassificationBiasMatrix::Valid () inline
Definition at line 73 of file ClassificationBiasMatrix.h.
Referenced by PicesCommander.ClassificationStatus::CleanUpMemory().
Property Documentation
System:: DateTime PicesInterface::ClassificationBiasMatrix::DateTimeFileWritten get set
Definition at line 57 of file ClassificationBiasMatrix.h.
Referenced by PicesCommander.ClassificationStatus::ClassificationStatus().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/ClassificationBiasMatrix.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/ClassificationBiasMatrix.cpp