Pices: GradeTrainingModel.ConfusionMatrix Class Reference
GradeTrainingModel.ConfusionMatrix Class Reference
Public Member Functions
ConfusionMatrix (PicesTrainingConfiguration _config, PicesClassList _classifierClasses, TrainingModel2 _trainingModel, String _modelName, String _groundTruthRootDir, uint _trainLevel, uint _predLevel)
void MakePrediction (PicesClass knownClass, PicesClass predictedClass, double predProb, PicesFeatureVector fv, TrainingModel2 trainModel)
void SetTrainingModel (TrainingModel2 _trainingModel)
void TallyPredictions ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Detailed Description
Definition at line 16 of file ConfusionMatrix.cs.
Constructor & Destructor Documentation
GradeTrainingModel.ConfusionMatrix.ConfusionMatrix (PicesTrainingConfiguration _config, PicesClassList _classifierClasses, TrainingModel2 _trainingModel, String _modelName, String _groundTruthRootDir, uint _trainLevel, uint _predLevel) inline
Parameters
_classifierClasses List of classes in origianl Classifier before reduction due to training level.
Definition at line 106 of file ConfusionMatrix.cs.
References PicesInterface::PicesTrainingConfiguration.OtherClass().
Member Function Documentation
override void GradeTrainingModel.ConfusionMatrix.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file ConfusionMatrix.Designer.cs.
void GradeTrainingModel.ConfusionMatrix.MakePrediction (PicesClass knownClass, PicesClass predictedClass, double predProb, PicesFeatureVector fv, TrainingModel2 trainModel) inline
Definition at line 498 of file ConfusionMatrix.cs.
References PicesInterface::PicesClassList.GetUniqueClass(), PicesInterface::PicesClassList.LookUpIndex(), and PicesInterface::PicesClass.Name.
Referenced by GradeTrainingModel.ConfusionMatrix.TallyPredictions().
void GradeTrainingModel.ConfusionMatrix.SetTrainingModel (TrainingModel2 _trainingModel) inline
Definition at line 137 of file ConfusionMatrix.cs.
References PicesInterface::PicesClassList.GetUniqueClass().
void GradeTrainingModel.ConfusionMatrix.TallyPredictions () inline
Definition at line 533 of file ConfusionMatrix.cs.
References GradeTrainingModel.ConfusionMatrix.MakePrediction(), and GradeTrainingModel.Prediction.prob.
The documentation for this class was generated from the following files:
E:/Users/kkramer/ProgProjects/Pices/Apps/GradeTrainingModel/ConfusionMatrix.cs
E:/Users/kkramer/ProgProjects/Pices/Apps/GradeTrainingModel/ConfusionMatrix.Designer.cs