Pices: FeatureSelectionApp::FeatureImpact Class Reference
FeatureSelectionApp::FeatureImpact Class Reference
#include <FeatureImpact.h>
Public Types
typedef FeatureImpact * FeatureImpactPtr
typedef KKB::uint uint
Public Member Functions
FeatureImpact (BinaryJobList &jobs)
~FeatureImpact ()
FeatureNumList FeatureThatDontHurt ()
void Report (ostream &r)
void ReportHTML (ostream &r)
void UpdateAccByFeatureSelList (AccByFeatureSelListPtr accByFeatureSelList, MLClassPtr class1, MLClassPtr class2)
Detailed Description
Definition at line 23 of file FeatureImpact.h.
Member Typedef Documentation
typedef FeatureImpact* FeatureSelectionApp::FeatureImpact::FeatureImpactPtr
Definition at line 27 of file FeatureImpact.h.
typedef KKB::uint FeatureSelectionApp::FeatureImpact::uint
Definition at line 26 of file FeatureImpact.h.
Constructor & Destructor Documentation
FeatureImpact::FeatureImpact (BinaryJobList & jobs)
Definition at line 40 of file FeatureImpact.cpp.
References FeatureSelectionApp::BinaryJob::Accuracy(), KKB::CalcMeanAndStdDev(), FeatureSelectionApp::BinaryJob::Features(), FeatureSelectionApp::BinaryJobList::FileDesc(), FeatureSelectionApp::BinaryJob::FMeasure(), FeatureSelectionApp::BinaryJobList::LookUpByJobId(), KKMLL::FileDesc::NumOfFields(), and FeatureSelectionApp::BinaryJob::ParentId().
FeatureImpact::~FeatureImpact ()
Definition at line 114 of file FeatureImpact.cpp.
Member Function Documentation
FeatureNumList FeatureImpact::FeatureThatDontHurt ()
Definition at line 190 of file FeatureImpact.cpp.
References KKMLL::FeatureNumList::AddFeature().
Referenced by FeatureSelectionApp::Processor::GetFeaturesRemoveHurtFul().
void FeatureImpact::Report (ostream & r)
Definition at line 167 of file FeatureImpact.cpp.
References KKB::endl(), and KKMLL::FileDesc::FieldName().
Referenced by CalcGrowthRate().
void FeatureImpact::ReportHTML (ostream & r)
Definition at line 121 of file FeatureImpact.cpp.
References KKB::endl(), and KKMLL::FileDesc::FieldName().
Referenced by CalcGrowthRate(), and FeatureSelectionApp::Processor::GetFeatureImpact().
void FeatureImpact::UpdateAccByFeatureSelList (AccByFeatureSelListPtr accByFeatureSelList, MLClassPtr class1, MLClassPtr class2)
Definition at line 204 of file FeatureImpact.cpp.
References KKB::endl(), KKB::RunLog::Level(), and KKB::KKQueue< Entry >::PushOnBack().
Referenced by ReportDataSpecs().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/Apps/FeatureSelection/FeatureImpact.h
C:/Users/Kurt/GitHub/Pices/Apps/FeatureSelection/FeatureImpact.cpp