Pices: PicesCommander.Harvester Class Reference
PicesCommander.Harvester Class Reference
Public Member Functions
Harvester (String _cruise, String _station, String _deployment, String _sipperFileName, PicesClass _selClass, char _classKeyToUse, int _sizeMin, int _sizeMax)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
bool CancelHarvesting [get, set]
String GroupNameSelected [get]
PicesDataBaseImageList HarvestedImages [get]
bool HarvestingRunning [get]
Detailed Description
Definition at line 20 of file Harvester.cs.
Constructor & Destructor Documentation
PicesCommander.Harvester.Harvester (String _cruise, String _station, String _deployment, String _sipperFileName, PicesClass _selClass, char _classKeyToUse, int _sizeMin, int _sizeMax) inline
Definition at line 68 of file Harvester.cs.
References PicesInterface::PicesMsgQueue.AddMsg(), PicesInterface::PicesDataBase.Close(), PicesInterface::PicesDataBaseImage.Depth, PicesInterface::PicesDataBase.GetGlobalDatabaseManagerNewInstance(), PicesInterface::PicesMsgQueue.GetNextMsg(), PicesInterface::PicesDataBase.ImageGroupDelete(), PicesInterface::PicesDataBase.ImageGroupEntriesInsert(), PicesInterface::PicesDataBaseImageGroup.ImageGroupId, PicesInterface::PicesDataBase.ImageGroupInsert(), PicesInterface::PicesDataBase.ImageGroupLoad(), PicesInterface::PicesDataBaseImage.ImageId, PicesInterface::PicesDataBase.ImageLoad(), PicesInterface::PicesDataBase.ImagesQuery(), PicesInterface::PicesDataBase.InstrumentDataLoad(), PicesInterface::PicesClass.Name, PicesInterface::PicesDataBase.SipperFileGetList(), PicesInterface::PicesKKStr.StrToFloat(), PicesInterface::PicesKKStr.StrToInt(), PicesInterface::PicesDataBase.ThreadEnd(), PicesInterface::PicesDataBase.ThreadInit(), PicesInterface::PicesDataBase.Valid(), and PicesInterface::PicesDataBaseImageGroup.ValidName().
Member Function Documentation
override void PicesCommander.Harvester.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file Harvester.Designer.cs.
Property Documentation
bool PicesCommander.Harvester.CancelHarvesting get set
Definition at line 61 of file Harvester.cs.
Referenced by PicesCommander.PicesCommander.ThumbnailDataGridView_CellContentDoubleClick().
String PicesCommander.Harvester.GroupNameSelected get
Definition at line 62 of file Harvester.cs.
Referenced by PicesCommander.PicesCommander.ThumbnailDataGridView_CellContentDoubleClick().
PicesDataBaseImageList PicesCommander.Harvester.HarvestedImages get
Definition at line 63 of file Harvester.cs.
Referenced by PicesCommander.PicesCommander.ThumbnailDataGridView_CellContentDoubleClick().
bool PicesCommander.Harvester.HarvestingRunning get
Definition at line 64 of file Harvester.cs.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/Harvester.cs
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/Harvester.Designer.cs