Pices: MLL::InstrumentDataManager Class Reference
MLL::InstrumentDataManager Class Reference
Manages instrumentation data supplied by SipperBuff derived classesforwarding to appropriate 'InstrumentDataReport' derived objects.
#include <InstrumentDataManager.h>
Public Types
typedef KKB::kkint32 kkint32
typedef KKB::kkuint32 kkuint32
Public Member Functions
InstrumentDataManager (const KKStr &_sipperFileName, SipperFilePtr _sipperFile, const KKStr &_reportDir, RunLog &_log)
Creates new instance,.
InstrumentDataManager (const KKStr &_sipperFileName, SipperFilePtr _sipperFile, RunLog &_log)
Use this constructor if you only need to parse out the data.
~InstrumentDataManager ()
void AssignSerialPorts (const SipperHeaderRecPtr sipperHeaderRec)
void BatteryData (kkint32 _scanLine, kkint32 _activeBattery, const VectorFloat &_batteryLevels)
void CompReportLine (kkint32 scanLine)
InstrumentDataPtr CreateInstrumentData () const
const CTD_Plus_Data & CtdData () const
void CTDdataPlus (kkint32 _scanLine, const CTD_Plus_Data &_ctdData)
bool CtdDataRead () const
float Depth () const
void FlowRates (kkint32 _scanLine, float _meter1FlowRate, float _meter2FlowRate)
float Fluorescence () const
const TimeType & GpsTime () const
SipperHeaderRecPtr HeaderRec () const
double Latitude () const
void Latitude (double _latitude)
void Location (kkint32 _scanLine, double _latitude, double _longitude, const TimeType &_gpsTime)
double Longitude () const
void Longitude (double _longitude)
void Meter1FlowRate (kkint32 _scanLine, float _meter1FlowRate)
float Meter1FlowRate () const
void Meter2FlowRate (kkint32 _scanLine, float _meter2FlowRate)
float Meter2FlowRate () const
float Oxygen () const
void PitchAndRollData (kkint32 _scanLine, float _pitch, float _roll)
float RecordRate () const
void RecordRate (float _recordRate)
void ReportInstrumentData (kkuint32 curScanLine, uchar instrumentId, bool text, uchar data)
When ever SipperBuff gets instrument data, reports thru this method.
float Salinity () const
VectorUlong * ScanLinesPerMeterDepth () const
SipperFilePtr SipperFile ()
const KKStr & SipperFileName () const
Detailed Description
Manages instrumentation data supplied by SipperBuff derived classesforwarding to appropriate 'InstrumentDataReport' derived objects.
Responsible for managing instrument data that is collected by SipperBuff or one of its decedents. Originally developed when SIPPER3 format came out. This format includes instrument data. Will maintain a list of 'InstrumentDataReport' instances. One for each Instrument/Sensor and Data or Text. SipperBuff will call the 'ReportInstrumentData' method which will decide the correct 'InstrumentdataReport' instance to send it to, and if necessary, create a new instance of one.
Definition at line 48 of file InstrumentDataManager.h.
Member Typedef Documentation
typedef KKB::kkint32 MLL::InstrumentDataManager::kkint32
Definition at line 51 of file InstrumentDataManager.h.
typedef KKB::kkuint32 MLL::InstrumentDataManager::kkuint32
Definition at line 52 of file InstrumentDataManager.h.
Constructor & Destructor Documentation
InstrumentDataManager::InstrumentDataManager (const KKStr & _sipperFileName, SipperFilePtr _sipperFile, const KKStr & _reportDir, RunLog & _log)
Creates new instance,.
Parameters
[in] _sipperFileName Name of Sipper file that is being processed.
[in] _sipperFile An instance of a SipperFile object that contains SIPPER configuration data for specific SIPPER file.
[in] _reportDir Directory where to place Instrument/Sensor data/text files.
[in] _log A log-file stream. All important events will be output to this stream
Definition at line 26 of file InstrumentDataManager.cpp.
References KKB::KKStr::Empty(), KKB::endl(), MLL::CTD_Plus_Data::Header1Str(), MLL::CTD_Plus_Data::Header2Str(), MaxNumOfInstruments, KKB::osAddSlash(), KKB::osCreateDirectoryPath(), KKB::osGetFileDateTime(), KKB::osGetLocalDateTime(), KKB::osGetRootName(), and KKB::KKStr::Str().
InstrumentDataManager::InstrumentDataManager (const KKStr & _sipperFileName, SipperFilePtr _sipperFile, RunLog & _log)
Use this constructor if you only need to parse out the data.
Parameters
[in] _sipperFileName Name of Sipper file that is being processed.
[in] _sipperFile An instance of a SipperFile object that contains SIPPER configuration data for specific SIPPER file.
[in] _log A log-file stream. All important events will be output to this stream
Definition at line 99 of file InstrumentDataManager.cpp.
References MaxNumOfInstruments.
InstrumentDataManager::~InstrumentDataManager ()
Definition at line 151 of file InstrumentDataManager.cpp.
References MLL::SipperFile::CruiseName(), KKB::KKStr::EqualIgnoreCase(), MLL::SipperFile::Latitude(), MaxNumOfInstruments, and KKB::KKStr::SubStrPart().
Member Function Documentation
void InstrumentDataManager::AssignSerialPorts (const SipperHeaderRecPtr sipperHeaderRec)
Definition at line 279 of file InstrumentDataManager.cpp.
Referenced by MLL::SipperBuff::AssignSerialPorts().
void InstrumentDataManager::BatteryData (kkint32 _scanLine, kkint32 _activeBattery, const VectorFloat & _batteryLevels)
Definition at line 372 of file InstrumentDataManager.cpp.
References CompReportLine().
Referenced by MLL::InstrumentDataBatteryMeter::ProcessBatteryData().
void InstrumentDataManager::CompReportLine (kkint32 scanLine)
Definition at line 302 of file InstrumentDataManager.cpp.
References MLL::CTD_Plus_Data::Date(), MLL::CTD_Plus_Data::Depth(), KKB::endl(), Min(), KKB::DateTime::Seconds(), KKB::StrFormatDouble(), KKB::StrFormatInt(), and MLL::CTD_Plus_Data::ToStrNoLabels().
Referenced by BatteryData(), CTDdataPlus(), FlowRates(), Location(), Meter1FlowRate(), Meter2FlowRate(), and PitchAndRollData().
InstrumentDataPtr InstrumentDataManager::CreateInstrumentData () const
Todo:
Need to maintain the files CropLeft, CropRight, ActiveColumns
Definition at line 232 of file InstrumentDataManager.cpp.
References MLL::CTD_Plus_Data::BatteryVoltage(), MLL::CTD_Plus_Data::CdomFluorescence(), MLL::CTD_Plus_Data::CdomFluorescenceSensor(), MLL::CTD_Plus_Data::Conductivity(), MLL::CTD_Plus_Data::Date(), MLL::CTD_Plus_Data::Density(), MLL::CTD_Plus_Data::Depth(), MLL::CTD_Plus_Data::Fluorescence(), MLL::CTD_Plus_Data::FluorescenceSensor(), MLL::CTD_Plus_Data::Oxygen(), MLL::CTD_Plus_Data::OxygenSensor(), MLL::CTD_Plus_Data::Pressure(), MLL::CTD_Plus_Data::Salinity(), MLL::CTD_Plus_Data::SoundVelocity(), MLL::CTD_Plus_Data::Temperature(), MLL::CTD_Plus_Data::Transmisivity(), MLL::CTD_Plus_Data::TransmisivitySensor(), MLL::CTD_Plus_Data::Turbidity(), and MLL::CTD_Plus_Data::TurbiditySensor().
Referenced by MLL::InstrumentDataList::CreateFromSipperFile().
const CTD_Plus_Data& MLL::InstrumentDataManager::CtdData () const inline
Definition at line 143 of file InstrumentDataManager.h.
void InstrumentDataManager::CTDdataPlus (kkint32 _scanLine, const CTD_Plus_Data & _ctdData)
Definition at line 352 of file InstrumentDataManager.cpp.
References CompReportLine(), and MLL::CTD_Plus_Data::ValidData().
Referenced by MLL::InstrumentDataCTDplus::~InstrumentDataCTDplus().
bool MLL::InstrumentDataManager::CtdDataRead () const inline
Definition at line 140 of file InstrumentDataManager.h.
float MLL::InstrumentDataManager::Depth () const inline
Definition at line 145 of file InstrumentDataManager.h.
void InstrumentDataManager::FlowRates (kkint32 _scanLine, float _meter1FlowRate, float _meter2FlowRate)
Definition at line 449 of file InstrumentDataManager.cpp.
References CompReportLine().
float MLL::InstrumentDataManager::Fluorescence () const inline
Definition at line 155 of file InstrumentDataManager.h.
const TimeType& MLL::InstrumentDataManager::GpsTime () const inline
Definition at line 147 of file InstrumentDataManager.h.
SipperHeaderRecPtr MLL::InstrumentDataManager::HeaderRec () const inline
Definition at line 157 of file InstrumentDataManager.h.
Referenced by MLL::InstrumentDataReport::CreateInstrumentDataReport().
double MLL::InstrumentDataManager::Latitude () const inline
Definition at line 148 of file InstrumentDataManager.h.
Referenced by MLL::InstrumentDataCTDplus::~InstrumentDataCTDplus().
void MLL::InstrumentDataManager::Latitude (double _latitude) inline
Definition at line 159 of file InstrumentDataManager.h.
void InstrumentDataManager::Location (kkint32 _scanLine, double _latitude, double _longitude, const TimeType & _gpsTime)
Definition at line 403 of file InstrumentDataManager.cpp.
References CompReportLine().
Referenced by MLL::InstrumentDataGPS::~InstrumentDataGPS().
double MLL::InstrumentDataManager::Longitude () const inline
Definition at line 149 of file InstrumentDataManager.h.
void MLL::InstrumentDataManager::Longitude (double _longitude) inline
Definition at line 160 of file InstrumentDataManager.h.
void InstrumentDataManager::Meter1FlowRate (kkint32 _scanLine, float _meter1FlowRate)
Definition at line 422 of file InstrumentDataManager.cpp.
References CompReportLine().
Referenced by MLL::InstrumentDataFlowMeter1::ReportInstrumentData().
float MLL::InstrumentDataManager::Meter1FlowRate () const inline
Definition at line 150 of file InstrumentDataManager.h.
void InstrumentDataManager::Meter2FlowRate (kkint32 _scanLine, float _meter2FlowRate)
Definition at line 435 of file InstrumentDataManager.cpp.
References CompReportLine().
Referenced by MLL::InstrumentDataFlowMeter1::ReportInstrumentData().
float MLL::InstrumentDataManager::Meter2FlowRate () const inline
Definition at line 151 of file InstrumentDataManager.h.
float MLL::InstrumentDataManager::Oxygen () const inline
Definition at line 154 of file InstrumentDataManager.h.
void InstrumentDataManager::PitchAndRollData (kkint32 _scanLine, float _pitch, float _roll)
Definition at line 387 of file InstrumentDataManager.cpp.
References CompReportLine().
Referenced by MLL::InstrumentDataPitchAndRoll::~InstrumentDataPitchAndRoll().
float MLL::InstrumentDataManager::RecordRate () const inline
Definition at line 152 of file InstrumentDataManager.h.
void MLL::InstrumentDataManager::RecordRate (float _recordRate) inline
Definition at line 161 of file InstrumentDataManager.h.
void InstrumentDataManager::ReportInstrumentData (kkuint32 curScanLine, uchar instrumentId, bool text, uchar data)
When ever SipperBuff gets instrument data, reports thru this method.
Parameters
[in] curScanLine Scan line that was last read when encountering this "InstrumentData".
[in] instrumentId Sensor/Instrument ID
[in] text Set to true = text data, false = binary data.
[in] data One byte of data from the SIPPER file.
Definition at line 465 of file InstrumentDataManager.cpp.
References MLL::InstrumentDataReport::CreateInstrumentDataReport(), KKB::endl(), KKB::RunLog::Level(), MaxNumOfInstruments, and MLL::InstrumentDataReport::ReportInstrumentData().
Referenced by MLL::SipperBuff::ReportInstrumentData().
float MLL::InstrumentDataManager::Salinity () const inline
Definition at line 153 of file InstrumentDataManager.h.
VectorUlong * InstrumentDataManager::ScanLinesPerMeterDepth () const
Definition at line 289 of file InstrumentDataManager.cpp.
Referenced by ImageExtractionManager::ExtractionManager::ManageTheExtraction().
SipperFilePtr MLL::InstrumentDataManager::SipperFile () inline
Definition at line 85 of file InstrumentDataManager.h.
Referenced by MLL::InstrumentDataCTDplus::~InstrumentDataCTDplus().
const KKStr& MLL::InstrumentDataManager::SipperFileName () const inline
Definition at line 163 of file InstrumentDataManager.h.
Referenced by MLL::InstrumentDataCTDplus::~InstrumentDataCTDplus().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/InstrumentDataManager.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/InstrumentDataManager.cpp