Pices: KKB::KKQueue< Entry > Class Template Reference
KKB::KKQueue< Entry > Class Template Reference
A typed container class/template that keeps track of entries via pointers only.
#include <KKQueue.h>
Public Types
typedef std::vector< Entry * >::const_iterator const_iterator
typedef std::vector< Entry * >::iterator iterator
Public Member Functions
KKQueue (bool _owner=true)
KKQueue (const KKQueue &q, bool _owner)
Constructor, similar to the Copy Constructor except that you can control whether it duplicates the contents.
virtual ~KKQueue ()
Virtual destructor; if owns its contents will also call the destructor on each one entry that it contains.
virtual void Add (EntryPtr _entry)
same as PushOnBack
virtual void AddFirst (EntryPtr _entry)
same as PushOnFront
virtual void AddQueue (const KKQueue &q)
Add the contents of a separate KKQueue container to this container.
EntryPtr BackOfQueue () const
Returns pointer of last element in the container without removing it.
void DeleteContents ()
Empties the container, if 'owner' is set to true will call the destructor on each element.
void DeleteEntry (EntryPtr _entry)
Removes from KKQueue the entry who's pointer = '_entry'.
void DeleteEntry (kkuint32 _idx)
Removes from KKQueue the entry who's index = '_idx'.
KKQueue * DuplicateListAndContents () const
Creates a new container including duplicating the contents, which also makes the new instance the owner of those contents.
template<typename Functor >
kkuint32 FindTheKthElement (kkuint32 k, Functor pred)
EntryPtr FrontOfQueue () const
Returns a pointer to the element that is at from of the queue with out removing it from the queue.
EntryPtr GetFirst () const
Same as FrontOfQueue.
EntryPtr GetLast () const
Same as BackOfQueue.
EntryPtr IdxToPtr (kkuint32 idx) const
Returns back a pointer to the element who's index is 'idx'.
kkint32 LocateEntry (EntryConstPtr _entry) const
Returns the index of the element who's address is '_entry'.
EntryPtr LookAtBack () const
Same as BackOfQueue.
EntryPtr LookAtFront () const
Same as FrontOfQueue.
bool operator!= (const KKQueue< Entry > &rightSide) const
returns False if NOT every entry in both containers point to the same elements
KKQueue & operator= (const KKQueue &q)
Assignment Operator.
bool operator== (const KKQueue< Entry > &rightSide) const
Returns True if every entry in both containers point to the same elements.
Entry & operator[] (kkuint32 i) const
Returns a reference to element indexed by 'i'; similar to IdxToPtr except tat it returns a reference rather than a pointer.0.
bool Owner () const
void Owner (bool _owner)
You can specify who owns the contents of the container.
virtual EntryPtr PopFromBack ()
Removes the last element in the container and returns its pointer.
virtual EntryPtr PopFromFront ()
Removes the first element in the container and returns its pointer.
kkint32 PtrToIdx (EntryConstPtr _entry) const
returns the index of the 'entry' that has the same pointer as '_entry', if none found returns -1
virtual void PushOnBack (EntryPtr _entry)
Adds '_entry' to the End of the container.
virtual void PushOnFront (EntryPtr _entry)
Adds '_entry' to the Front of the container.
kkint32 QueueSize () const
Same as calling vector<>::size(); returns the number of elements in KKQueue.
void RandomizeOrder ()
Randomizes the order of the vector.
void RandomizeOrder (kkint64 seed)
void RandomizeOrder (RandomNumGenerator &randomVariable)
Randomizes the order of the vector.
virtual EntryPtr RemoveFirst ()
same as PopFromFront
virtual EntryPtr RemoveLast ()
same as PopFromBack
void SetIdxToPtr (kkuint32 _idx, Entry *_ptr)
void SwapIndexes (size_t idx1, size_t idx2)
Protected Member Functions
KKQueue (const KKQueue &q)
Copy Constructor creating new instance; including duplicating contents if owner set to true.
Detailed Description
template<class Entry>
class KKB::KKQueue< Entry >
A typed container class/template that keeps track of entries via pointers only.
Will act as an Array, Queue or Stack structure. Items are added by the 'PushOnFront' and 'PushOnBack' methods. They are removed by the 'PopFromFront' and 'PopFromBack' methods. What is important to keep in mind is that it holds pointers to its contents, not the actual instances. It is important to keep track who owns the objects you put in an instance of KKQueue. KKQueue has a 'Owner' flag that you can set. If it is set to 'true' then it will call the destructor on all its contents when you call KKQueue's destructor or the 'DestroyContents' method. When you add an element to a KKQueue container you can not delete it separately until you either remove it from KKQueue or delete the KKQueue container. If the KKQueue derived container owned its contents and you call its destructor then there is no need to delete the contents separately.
KKQueue is sub-classed from vector<Entry*> so you can use any method that is available for the vector<> template.
Template Parameters
Entry The type of objects that are to be held in this container. When you add new instances of 'Entry', you need to add a pointer to it not the actual entry.
Definition at line 77 of file KKQueue.h.
Member Typedef Documentation
template<class Entry> typedef std::vector<Entry*>::const_iterator KKB::KKQueue< Entry >::const_iterator
Definition at line 89 of file KKQueue.h.
template<class Entry> typedef std::vector<Entry*>::iterator KKB::KKQueue< Entry >::iterator
Definition at line 88 of file KKQueue.h.
Constructor & Destructor Documentation
template<class Entry > KKQueue::KKQueue (bool _owner = true)
Definition at line 219 of file KKQueue.h.
template<class Entry > KKQueue::KKQueue (const KKQueue< Entry > & q) protected
Copy Constructor creating new instance; including duplicating contents if owner set to true.
If the parameter 'q' owns its contents then will create new instances of its contents. That is it will call the Copy Constructor for each one of the elements it contains. If 'q' does not own its contents it will just copy over the pointers from 'q', meaning that the new instance of KKQueue will point to the same locations as 'q' does.
Definition at line 227 of file KKQueue.h.
References KKB::KKQueue< Entry >::PushOnBack().
template<class Entry > KKQueue::KKQueue (const KKQueue< Entry > & q, bool _owner)
Constructor, similar to the Copy Constructor except that you can control whether it duplicates the contents.
If the '_owner' parameter is set to true then it will create new instances of the contents otherwise it will just point to the instances that already exist.
Definition at line 243 of file KKQueue.h.
References KKB::KKQueue< Entry >::PushOnBack().
template<class Entry > KKQueue::~KKQueue () virtual
Virtual destructor; if owns its contents will also call the destructor on each one entry that it contains.
Definition at line 280 of file KKQueue.h.
Member Function Documentation
template<class Entry > void KKQueue::Add (EntryPtr _entry) inline virtual
same as PushOnBack
Definition at line 339 of file KKQueue.h.
References KKB::KKQueue< Entry >::PushOnBack().
Referenced by KKB::ConvexHull::Draw(), PicesInterface::PicesFeatureVectorList::ExtractListOfClasses(), and KKB::ConvexHull::Store().
template<class Entry > void KKQueue::AddFirst (EntryPtr _entry) inline virtual
same as PushOnFront
Definition at line 347 of file KKQueue.h.
References KKB::KKQueue< Entry >::PushOnFront().
Referenced by KKB::ConvexHull::Store().
template<class Entry > void KKQueue::AddQueue (const KKQueue< Entry > & q) virtual
Add the contents of a separate KKQueue container to this container.
Be careful how the Owner flags are set; this method adds the pointers of 'q' to the end of its own container; it does not concern itself with the state of the 'Owner' flags. If you are not careful you can have both containers thinking they own the same entries. I suggest that after you add the contents of 'q' to this container that the caller set the 'owner' flag of 'q' to false.
Definition at line 355 of file KKQueue.h.
References KKB::KKQueue< Entry >::PushOnBack().
Referenced by MLL::DataBase::ImagesQuery(), MLL::DataBase::ImagesQueryDeploymentSizeRange(), and MLL::DataBase::InstrumentDataLoad().
template<class Entry > KKQueue< Entry >::EntryPtr KKQueue::BackOfQueue () const
Returns pointer of last element in the container without removing it.
If the container is empty will return NULL.
Definition at line 661 of file KKQueue.h.
Referenced by KKB::ConvexHull::Draw(), FeatureSelectionApp::ParmSearchResultsProcessor::GetBestCandidates(), KKB::KKQueue< Entry >::GetLast(), MLL::DataBase::MLClassLoad(), and FeatureSelectionApp::FeatureSelection::ProcessCmdLine().
template<class Entry > void KKQueue::DeleteContents ()
Empties the container, if 'owner' is set to true will call the destructor on each element.
Definition at line 321 of file KKQueue.h.
Referenced by KKB::KKQueue< Entry >::operator=(), SVM289_BFS::svm_model::Read(), SVM289_BFS::svm_train(), SVM289_MFS::svm_train(), and KKB::Raster::ThinContour().
template<class Entry > void KKQueue::DeleteEntry (EntryPtr _entry)
Removes from KKQueue the entry who's pointer = '_entry'.
Definition at line 684 of file KKQueue.h.
Referenced by MLL::FeatureFileIOPices::FeatureDataReSink(), KKMLL::FeatureFileIO::FeatureDataReSink(), and KKMLL::DuplicateImages::PurgeDuplicates().
template<class Entry > void KKQueue::DeleteEntry (kkuint32 _idx)
Removes from KKQueue the entry who's index = '_idx'.
Definition at line 715 of file KKQueue.h.
template<class Entry > KKQueue< Entry > * KKQueue::DuplicateListAndContents () const
Creates a new container including duplicating the contents, which also makes the new instance the owner of those contents.
Definition at line 263 of file KKQueue.h.
References KKB::KKQueue< Entry >::PushOnBack(), and KKB::KKQueue< Entry >::QueueSize().
template<class Entry > template<typename Functor > kkuint32 KKQueue::FindTheKthElement (kkuint32 k, Functor pred)
Definition at line 527 of file KKQueue.h.
References KKB::endl(), KKB::KKQueue< Entry >::IdxToPtr(), KKB::LRand48(), and KKB::KKQueue< Entry >::SwapIndexes().
template<class Entry > KKQueue< Entry >::EntryPtr KKQueue::FrontOfQueue () const
Returns a pointer to the element that is at from of the queue with out removing it from the queue.
Definition at line 673 of file KKQueue.h.
Referenced by MLL::InstrumentDataList::CreateFromSipperFile(), FeatureSelectionApp::BinaryJobList::CreateTestJobsForHighetsGradePerFeatureCount(), FeatureSelectionApp::Processor::GetBestParametersFromTestResults(), FeatureSelectionApp::Processor::GetFeaturesFromTestResults(), and KKB::KKQueue< Entry >::GetFirst().
template<class Entry > KKQueue< Entry >::EntryPtr KKQueue::GetFirst () const inline
Same as FrontOfQueue.
Definition at line 366 of file KKQueue.h.
References KKB::KKQueue< Entry >::FrontOfQueue().
template<class Entry > KKQueue< Entry >::EntryPtr KKQueue::GetLast () const inline
Same as BackOfQueue.
Definition at line 374 of file KKQueue.h.
References KKB::KKQueue< Entry >::BackOfQueue().
Referenced by KKB::ConvexHull::Draw().
template<class Entry > KKQueue< Entry >::EntryPtr KKQueue::IdxToPtr (kkuint32 idx) const
Returns back a pointer to the element who's index is 'idx'.
If 'idx' is less than 0 or >= QueueSize() will return NULL.
Definition at line 732 of file KKQueue.h.
Referenced by KKMLL::ConfusionMatrix2::AccuracyStr(), KKMLL::ConfusionMatrix2::AddIn(), MLL::AbundanceCorrectionMatrix::AdjustClassificationCounts(), KKMLL::DuplicateImage::AllTheSameClass(), KKMLL::SVMparam::AvgNumOfFeatures(), KKMLL::ClassificationBiasMatrix::BuildFromIstreamXML(), FeatureSelectionApp::FeatureSelection::BuildResultConfigFile(), CalcGrowthRate(), KKMLL::FileDesc::Cardinality(), KKMLL::TrainingConfiguration2::ConfigFileExists(), KKB::Configuration::Configuration(), KKMLL::FileDesc::CreateAAttributeTable(), MLL::InstrumentDataList::CreateFromSipperFile(), KKMLL::Orderings::CreateOrderingsObjFromFileIfAvaliable(), KKMLL::FileDesc::DisplayAttributeMappings(), FeatureSelectionApp::FeatureSelection::DisplayCommandUsage(), KKMLL::FeatureEncoder::EncodeIntoSparseMatrix(), FeatureSelectionApp::Processor::EndBlock(), KKMLL::FeatureVectorList::ExtractRandomSampling(), KKB::KKQueue< Entry >::FindTheKthElement(), FeatureSelectionApp::ParmSearchResultsProcessor::GetBestCandidates(), GetProcessId(), KKMLL::SizeDistribution::Increment(), KKMLL::FeatureFileIOColumn::LoadFile(), MLL::AbundanceCorrectionMatrix::LumpCounts(), FeatureSelectionApp::Processor::MergeKBestFeatureSelections(), KKMLL::MLClassList::MLClassList(), KKB::Configuration::NumOfSettings(), KKB::KKQueue< Entry >::operator==(), osFileNameMatchesSearchFields(), KKB::Tokenizer::Peek(), PicesInterface::TrainingModel2::PredictProbabilities(), KKMLL::ModelSvmBase::ProbabilitiesByClass(), KKMLL::ModelOldSVM::ProbabilitiesByClass(), KKMLL::Classifier2::ProbabilitiesByClass(), FeatureSelectionApp::FeatureSelection::ProcessCmdLine(), KKMLL::Model::ReduceTrainExamples(), ReportDataSpecs(), KKMLL::TrainingProcess2::ReportTraningClassStatistics(), KKMLL::ModelSvmBase::RetrieveCrossProbTable(), KKMLL::SVMModel::RetrieveCrossProbTable(), KKMLL::Model::RetrieveCrossProbTable(), KKMLL::CrossValidationVoting::RunCrossValidation(), KKMLL::CrossValidation::RunCrossValidation(), KKMLL::CrossValidationVoting::RunValidationOnly(), KKMLL::Orderings::Save(), PicesInterface::TrainingModel2::SaveConfiguration(), KKMLL::FeatureFileIORoberts::SaveFile(), KKMLL::FeatureFileIOUCI::SaveFile(), KKMLL::FeatureFileIOC45::SaveFile(), KKMLL::FeatureFileIOSparse::SaveFile(), KKB::Configuration::SectionLineNum(), KKB::Configuration::SectionName(), KKB::Configuration::SectionNum(), KKB::Configuration::SettingList::SettingList(), KKB::Configuration::SettingName(), KKB::Configuration::SettingValue(), KKB::Configuration::SettingValueToStr(), SplitImagesAmongstFolds(), svm_binary_svc_probability(), SVM289_BFS::svm_cross_validation(), SVM289_MFS::svm_cross_validation(), SVM289_BFS::svm_train(), SVM289_MFS::svm_train(), KKB::Raster::ThinContour(), KKMLL::TrainingConfiguration2::TrainingConfiguration2(), KKMLL::ModelSvmBase::TrainModel(), FeatureSelectionApp::Processor::Update(), and KKMLL::FeatureFileIOArff::~FeatureFileIOArff().
template<class Entry > kkint32 KKQueue::LocateEntry (EntryConstPtr _entry) const
Returns the index of the element who's address is '_entry'.
If not found in container will return back -1.
Definition at line 745 of file KKQueue.h.
Referenced by KKB::KKQueue< Entry >::PtrToIdx().
template<class Entry > KKQueue< Entry >::EntryPtr KKQueue::LookAtBack () const
Same as BackOfQueue.
Definition at line 627 of file KKQueue.h.
Referenced by KKB::ConvexHull::Draw().
template<class Entry > KKQueue< Entry >::EntryPtr KKQueue::LookAtFront () const
Same as FrontOfQueue.
Definition at line 638 of file KKQueue.h.
Referenced by KKB::ConvexHull::Draw().
template<class Entry> bool KKQueue::operator!= (const KKQueue< Entry > & rightSide) const
returns False if NOT every entry in both containers point to the same elements
Definition at line 457 of file KKQueue.h.
template<class Entry > KKQueue< Entry > & KKQueue::operator= (const KKQueue< Entry > & q)
Assignment Operator.
1) Destroy's its current contents by calling 'DeleteContents'.
2) If 'q' owns its contents
     create new instances of 'q's contents and add to its self  then set 'owner' flag to true.
   else
     Copy over 'q's pointers to self and then set 'owner' flag to false.
Definition at line 415 of file KKQueue.h.
References KKB::KKQueue< Entry >::DeleteContents(), and KKB::KKQueue< Entry >::Owner().
template<class Entry> bool KKQueue::operator== (const KKQueue< Entry > & rightSide) const
Returns True if every entry in both containers point to the same elements.
Definition at line 438 of file KKQueue.h.
References KKB::KKQueue< Entry >::IdxToPtr(), and KKB::KKQueue< Entry >::QueueSize().
template<class Entry > Entry & KKQueue::operator[] (kkuint32 i) const
Returns a reference to element indexed by 'i'; similar to IdxToPtr except tat it returns a reference rather than a pointer.0.
Definition at line 802 of file KKQueue.h.
References KKB::endl().
template<class Entry > bool KKQueue::Owner () const
Definition at line 305 of file KKQueue.h.
Referenced by PicesInterface::PicesPointList::AddList(), PicesInterface::PicesRasterList::AddList(), MLL::SipperFileOracle::AddSipperFileEntries(), CalcGrowthRate(), SVM289_MFS::Svm_Model::CleanUpMemory(), KKMLL::FeatureEncoder::CompressExamples(), KKMLL::FeatureVectorList::CreateListForAGivenLevel(), FeatureSelectionApp::BinaryJobList::CreateTestJobsForHighetsGradePerFeatureCount(), FeatureSelectionApp::BinaryJobList::ExtractByMinimumProcessintTime(), KKMLL::GrayScaleImagesFVList::ExtractDuplicatesByRootImageFileName(), MLL::ImageFeaturesList::ExtractDuplicatesByRootImageFileName(), KKMLL::GrayScaleImagesFVList::ExtractExamplesForAGivenClass(), MLL::ImageFeaturesList::ExtractExamplesForAGivenClass(), FeatureSelectionApp::BinaryJobList::ExtractHighestGrade(), FeatureSelectionApp::BinaryJobList::ExtractHighestTestGrade(), FeatureSelectionApp::BinaryJobList::ExtractJobsForAGivenFeatureCount(), FeatureSelectionApp::BinaryJobList::ExtractJobsWithSmallestDeltaAccProbForEachSvmParameterSet(), FeatureSelectionApp::BinaryJobList::ExtractLowDeltaProbAccuarcy(), FeatureSelectionApp::BinaryJobList::ExtractTestJobs(), KKMLL::TrainingProcess2::ExtractTrainingClassFeatures(), PicesInterface::PicesDataBase::FeatureDataForImageGroup(), PicesInterface::PicesDataBase::FeatureDataGetOneSipperFile(), FeatureSelectionApp::ParmSearchResultsProcessor::GetBestCandidates(), PicesInterface::PicesSipperFileList::GetListOfSipperFilesWeCanFind(), KKMLL::GrayScaleImagesFVList::GrayScaleImagesFVList(), MLL::ImageFeaturesList::ImageFeaturesList(), PicesInterface::PicesDataBase::ImageGroupEntriesLoad(), PicesInterface::PicesDataBase::ImagesQuery(), MLL::DataBase::ImagesQuery(), PicesInterface::PicesDataBase::ImagesQueryByGrouop(), PicesInterface::PicesDataBase::ImagesQueryDeploymentSizeRange(), MLL::DataBase::ImagesQueryDeploymentSizeRange(), PicesInterface::PicesDataBase::InstrumentDataLoad(), MLL::DataBase::InstrumentDataLoad(), PicesInterface::PicesTrainingConfigManaged::LoadFeatureDataFromTrainingLibraries(), KKMLL::TrainingConfiguration2::LoadFeatureDataFromTrainingLibraries(), PicesInterface::PicesFeatureFileIO::LoadFeatureFile(), PicesInterface::PicesFeatureVectorList::LoadInSubDirectoryTree(), MLL::FeatureFileIOPices::LoadInSubDirectoryTree(), KKMLL::FeatureFileIO::LoadInSubDirectoryTree(), FeatureSelectionApp::BinaryJobList::LookUpByParameters(), KKMLL::operator<<(), KKB::KKQueue< Entry >::operator=(), KKMLL::GrayScaleImagesFVList::OrderUsingNamesFromAFile(), MLL::ImageFeaturesList::OrderUsingNamesFromAFile(), PicesInterface::PicesDataBaseImageGroupEntryList::PicesDataBaseImageGroupEntryList(), PicesInterface::PicesDataBaseImageList::PicesDataBaseImageList(), PicesInterface::PicesFeatureVectorList::PicesFeatureVectorList(), PicesInterface::PicesInstrumentDataList::PicesInstrumentDataList(), PicesInterface::PicesRasterList::PicesRasterList(), PicesInterface::PicesSipperCruiseList::PicesSipperCruiseList(), PicesInterface::PicesSipperDeploymentList::PicesSipperDeploymentList(), PicesInterface::PicesSipperFileList::PicesSipperFileList(), PicesInterface::PicesTrainingClassList::PicesTrainingClassList(), KKMLL::DuplicateImages::PurgeDuplicates(), SVM289_BFS::svm_model::Read(), SVM289_MFS::Svm_Model::ReadXML(), KKMLL::Model::ReduceTrainExamples(), FeatureSelectionApp::Processor::Run(), FeatureSelectionApp::Processor::SetQuitRunningFlag(), PicesInterface::PicesDataBase::SipperCruiseLoadAllCruises(), PicesInterface::PicesDataBase::SipperDeploymentLoad(), PicesInterface::PicesDataBase::SipperDeploymentLoadByStation(), PicesInterface::PicesDataBase::SipperFileLoad(), MLL::DataBase::SipperFileLoadOracle(), MLL::RasterSipper::SplitImageIntoEqualParts(), KKMLL::GrayScaleImagesFVList::StratifyAmoungstClasses(), MLL::ImageFeaturesList::StratifyAmoungstClasses(), SVM289_BFS::svm_destroy_model(), SVM289_MFS::svm_destroy_model(), SVM289_BFS::svm_model::svm_model(), SVM289_MFS::Svm_Model::Svm_Model(), SVM289_BFS::svm_train(), SVM289_MFS::svm_train(), KKMLL::Model::TrainModel(), FeatureSelectionApp::Processor::Update(), and SVM289_BFS::svm_model::~svm_model().
template<class Entry > void KKQueue::Owner (bool _owner)
You can specify who owns the contents of the container.
'_owner' == true means when the container is deleted it will also call the destructor for each element it contains.
Definition at line 297 of file KKQueue.h.
template<class Entry > KKQueue< Entry >::EntryPtr KKQueue::PopFromBack () virtual
Removes the last element in the container and returns its pointer.
If the container is empty will return NULL.
Reimplemented in MLL::ImageFeaturesList, KKMLL::MLClassList, KKMLL::GrayScaleImagesFVList, and KKB::XmlAttributeList.
Definition at line 648 of file KKQueue.h.
Referenced by KKB::ConvexHull::Draw(), KKMLL::TrainingConfiguration2::EmptyTrainingClasses(), KKMLL::TrainingConfiguration2::GetFeatureNums(), ImageExtractionManager::FrameProcessorThread::GetRunTimeStats(), MLL::DataBase::ImageLoad(), MLL::DataBase::InstrumentDataGetByScanLine(), KKB::XmlAttributeList::PopFromBack(), KKMLL::TrainingConfiguration2::ReadXMLBaseToken(), KKB::KKQueue< Entry >::RemoveLast(), MLL::DataBase::SipperCruiseLoad(), MLL::DataBase::SipperDeploymentLoad(), and MLL::DataBase::SipperFileRecLoad().
template<class Entry > KKQueue< Entry >::EntryPtr KKQueue::PopFromFront () virtual
Removes the first element in the container and returns its pointer.
If the container is empty will return NULL.
Reimplemented in KKMLL::MLClassList.
Definition at line 596 of file KKQueue.h.
Referenced by KKB::ConvexHull::Draw(), KKB::Raster::FillRectangle(), KKB::Tokenizer::GetNextToken(), PicesInterface::PicesDataBaseLogEntryList::PicesDataBaseLogEntryList(), PicesInterface::PicesFeatureVectorList::PicesFeatureVectorList(), KKB::XmlAttributeList::PopFromFromt(), KKB::KKQueue< Entry >::RemoveFirst(), and KKB::Raster::ThinContour().
template<class Entry > kkint32 KKQueue::PtrToIdx (EntryConstPtr _entry) const
returns the index of the 'entry' that has the same pointer as '_entry', if none found returns -1
Definition at line 761 of file KKQueue.h.
References KKB::KKQueue< Entry >::LocateEntry().
Referenced by MLL::AbundanceCorrectionMatrix::AbundanceCorrectionMatrix(), KKMLL::ConfusionMatrix2::Accuracy(), KKMLL::FileDesc::AddClasses(), KKMLL::ConfusionMatrix2::AddIn(), KKMLL::DuplicateImage::AlreadyHaveExample(), KKMLL::ClassificationBiasMatrix::BuildFromIstreamXML(), KKMLL::SVMModel::CancelFlag(), KKMLL::MLClass::ChangeNameOfClass(), KKMLL::ConfusionMatrix2::ComputeFundamentalStats(), KKMLL::TrainingConfiguration2::ExtractFullHierachyOfClasses(), KKMLL::MLClassList::ExtractListOfClassesForAGivenHierarchialLevel(), KKMLL::ConfusionMatrix2::FactorCounts(), KKMLL::ConfusionMatrix2::FMeasure(), KKMLL::ConfusionMatrix2::Increment(), KKMLL::MLClassList::MergeClassList(), KKMLL::TrainingConfiguration2::NumHierarchialLevels(), KKMLL::MLClassList::operator-(), KKMLL::SVMModel::ProbabilitiesByClass(), FeatureSelectionApp::FeatureSelection::ProcessCmdLine(), KKMLL::TrainingConfiguration2::RootDirExpanded(), KKMLL::CrossValidationVoting::RunValidationOnly(), KKMLL::TrainingConfiguration2::Save(), MLL::AbundanceCorrectionMatrix::~AbundanceCorrectionMatrix(), and KKMLL::ConfusionMatrix2::~ConfusionMatrix2().
template<class Entry > void KKQueue::PushOnBack (EntryPtr _entry) virtual
Adds '_entry' to the End of the container.
Reimplemented in KKB::XmlAttributeList.
Definition at line 398 of file KKQueue.h.
References KKB::endl().
Referenced by KKB::KKQueue< Entry >::Add(), KKMLL::TrainingConfiguration2::AddATrainingClass(), KKB::KKQueue< Entry >::AddQueue(), KKB::KKStrMatrix::AddRow(), KKB::KKThread::AddShutdownPrerequistite(), KKMLL::DuplicateImages::AddSingleExample(), KKB::KKThread::AddStartPrerequistite(), KKB::KKThreadManager::AddThread(), MLL::PicesFVProducer::ComputeFeatureVector(), KKMLL::TrainingProcess2::ConfigFileFormatErrors(), KKB::ContourFollower::CreateFourierDescriptorBySampling(), MLL::InstrumentDataList::CreateFromSipperFile(), KKB::ContourFollower::CreatePointListFromFourier(), MLL::RasterSipper::DeriveImageLength(), KKB::Raster::DeriveImageLength(), KKB::ImageDirTree::Directories(), FeatureSelectionApp::FeatureSelection::DisplayCommandUsage(), KKB::ConvexHull::Draw(), KKB::KKQueue< Entry >::DuplicateListAndContents(), KKMLL::TrainingClassList::DuplicateListAndContents(), KKB::KKStrList::DuplicateListAndContents(), KKB::Tokenizer::EndOfFile(), KKMLL::FeatureVectorList::ExtractDuplicatesByExampleFileName(), MLL::DataBaseImageList::ExtractExamplesForAGivenClass(), KKMLL::TrainingConfiguration2::ExtractFullHierachyOfClasses(), MLL::DataBase::FeatureDataGetScanLinesPerMeterProfile(), KKB::Raster::FillRectangle(), KKB::PointList::FromDelStr(), KKB::ContourFollower::GenerateContourList(), KKB::MsgQueue::GetAllMsgs(), KKMLL::FileDesc::GetExistingFileDesc(), KKMLL::TrainingConfiguration2::GetFeatureNums(), MLL::SipperFileList::GetListOfSipperFilesWeCanFind(), KKB::KKThread::GetMsgs(), KKB::Tokenizer::GetNextTokens(), KKB::XmlTokenizer::GetNextTokens(), MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageGroupEntriesLoad(), PicesInterface::PicesDataBase::ImageInsert(), KKMLL::SizeDistribution::Increment(), MLL::DataBase::InstrumentDataBinByMeterDepth(), MLL::DataBase::InstrumentDataRetrieveGPSInfo(), KKB::KKQueue< Entry >::KKQueue(), MLL::SipperFileList::Load(), MLL::DataBaseUpdate::LoadSourceFile(), ImageExtractionManager::ExtractionManager::ManageTheExtraction(), KKB::osGetListOfDirectories(), KKB::osGetListOfFiles(), KKB::osGetListOfImageFiles(), osParseSearchSpec(), KKB::osValidFileNameErrors(), KKB::KKStrList::ParseDelimitedString(), KKMLL::Classifier2::ProbabilitiesByClassDual(), FeatureSelectionApp::FeatureSelection::ProcessCmdLine(), ImageExtractionManager::LogicalFrame::ProcessFrame(), KKB::XmlAttributeList::PushOnBack(), MLL::DataBase::QueryStatementKKStr(), MLL::DataBase::QueryStatementReturnAllColumns(), MLL::ImageFeatures::ResetVersion(), MLL::DataBase::SipperCruiseUpdate(), MLL::DataBase::SipperDeploymentDelete(), MLL::DataBase::SipperStationDelete(), MLL::DataBaseImage::SizeCoordinates(), MLL::DataBaseImage::SizeCoordinatesAdd(), KKB::Raster::SplitImageIntoEqualParts(), ImageExtractionManager::ExtractionManager::TerminateProcessing(), KKB::Raster::ThinContour(), FeatureSelectionApp::FinalResults::ToHTMLStr(), KKMLL::TrainingConfiguration2::TrainingConfiguration2(), FeatureSelectionApp::FeatureImpact::UpdateAccByFeatureSelList(), and KKMLL::GrayScaleImagesFVProducer::~GrayScaleImagesFVProducer().
template<class Entry > void KKQueue::PushOnFront (EntryPtr _entry) virtual
Adds '_entry' to the Front of the container.
Reimplemented in KKB::XmlAttributeList.
Definition at line 383 of file KKQueue.h.
References KKB::endl().
Referenced by KKB::KKQueue< Entry >::AddFirst(), MLL::InstrumentDataList::CreateFromSipperFile(), KKB::XmlAttributeList::PushOnFront(), and KKB::Tokenizer::PushTokenOnFront().
template<class Entry > kkint32 KKQueue::QueueSize () const
Same as calling vector<>::size(); returns the number of elements in KKQueue.
Definition at line 313 of file KKQueue.h.
Referenced by KKMLL::ConfusionMatrix2::AccuracyClassWeightedEqually(), KKMLL::FileDesc::AddAAttribute(), KKMLL::ConfusionMatrix2::AddIn(), KKB::KKStrMatrix::AddRow(), KKMLL::Model::AllocatePredictionVariables(), KKMLL::ClassificationBiasMatrix::BuildFromIstreamXML(), KKMLL::ConfusionMatrix2::BuildFromIstreamXML(), FeatureSelectionApp::FeatureSelection::BuildResultConfigFile(), KKMLL::TrainingConfiguration2::BuildTrainingClassListFromDirectoryStructure(), CalcGrowthRate(), FeatureSelectionApp::Processor::Class2Name(), KKMLL::ClassificationBiasMatrix::ClassificationBiasMatrix(), KKMLL::FeatureVectorList::ClassStatisticsStr(), KKMLL::ConfusionMatrix2::ComputeFundamentalStats(), KKMLL::TrainingConfiguration2::ConfigFileExists(), KKB::Configuration::Configuration(), KKB::ConvexHull::ConvexArea(), KKMLL::ConfusionMatrix2::Count(), KKMLL::FileDesc::CreateAAttributeTable(), KKMLL::FileDesc::CreateAttributeTypeTable(), KKMLL::FileDesc::CreateCardinalityTable(), KKB::ContourFollower::CreateFourierFromPointList(), MLL::InstrumentDataList::CreateFromSipperFile(), KKMLL::Orderings::CreateOrderingsObjFromFileIfAvaliable(), FeatureSelectionApp::BinaryJobList::CreateTestJobsForHighetsGradePerFeatureCount(), FeatureSelectionApp::FeatureSelection::DisplayCommandUsage(), KKB::ConvexHull::Draw(), KKB::KKQueue< Entry >::DuplicateListAndContents(), KKMLL::DuplicateImages::DuplicatesFound(), KKMLL::TrainingConfiguration2::EmptyTrainingClasses(), KKMLL::FeatureEncoder::EncodeIntoSparseMatrix(), FeatureSelectionApp::Processor::EndBlock(), KKB::Tokenizer::EndOfFile(), FeatureSelectionApp::JobValidation::EvaluateNode(), KKMLL::TrainingConfiguration2::ExtractFullHierachyOfClasses(), FeatureSelectionApp::BinaryJobList::ExtractHighestGrade(), KKMLL::FeatureVectorList::ExtractRandomSampling(), MLL::DataBase::FeatureDataRecLoad(), MLL::FeatureFileIOPices::FeatureDataReSink(), KKMLL::FeatureFileIO::FeatureDataReSink(), MLL::ImageFeaturesList::FeatureExtraction(), KKB::Raster::FillRectangle(), KKB::ConvexHull::Filter(), KKMLL::ConfusionMatrix2::FMeasure(), FeatureSelectionApp::Processor::GetBestParametersFromTestResults(), KKMLL::TrainingConfiguration2::GetFeatureNums(), FeatureSelectionApp::Processor::GetFeaturesFromTestResults(), PicesInterface::TrainingModel2::GetListOfTrainingModels(), KKMLL::FileDesc::GetMLClassPtr(), KKB::Tokenizer::GetNextToken(), ImageExtractionManager::FrameProcessorThread::GetRunTimeStats(), KKB::ContourFollower::HistogramDistanceFromAPointOfEdge(), PicesInterface::PicesDataBase::ImageGroupEntriesInsert(), MLL::DataBase::ImageLoad(), KKMLL::SizeDistribution::Increment(), MLL::DataBase::InstrumentDataGetByScanLine(), MLL::DataBase::InstrumentDataGetSpecificFields(), MLL::DataBase::MLClassInsertReturn(), KKMLL::MLClassList::MLClassList(), KKMLL::Model::Model(), KKMLL::FileDesc::NumOfFields(), KKB::Configuration::NumOfSections(), KKB::Configuration::NumOfSettings(), KKB::KKStrMatrix::operator()(), KKB::KKQueue< Entry >::operator==(), KKMLL::MLClassList::operator==(), KKMLL::GrayScaleImagesFVList::OrderUsingNamesFromAFile(), osFileNameMatchesSearchFields(), KKB::osValidFileNameErrors(), KKB::Tokenizer::Peek(), PicesInterface::PicesDataBaseLogEntryList::PicesDataBaseLogEntryList(), PicesInterface::TrainingModel2::PredictProbabilities(), KKMLL::FeatureVectorList::PrintClassStatistics(), KKMLL::ConfusionMatrix2::PrintTrueFalsePositivesTabDelimited(), KKMLL::ModelUsfCasCor::ProbabilitiesByClass(), KKMLL::ModelDual::ProbabilitiesByClass(), FeatureSelectionApp::FeatureSelection::ProcessCmdLine(), PicesInterface::PicesDataBase::QueryStatement(), SVM289_BFS::svm_model::Read(), SVM289_MFS::Svm_Model::ReadXML(), KKMLL::TrainingConfiguration2::ReadXMLBaseToken(), ReportDataSpecs(), KKMLL::DuplicateImages::ReportDuplicates(), KKMLL::TrainingProcess2::ReportTraningClassStatistics(), KKMLL::ModelDual::RetrieveCrossProbTable(), KKMLL::SVMModel::RetrieveCrossProbTable(), KKMLL::Model::RetrieveCrossProbTable(), KKMLL::CrossValidationVoting::RunCrossValidation(), KKMLL::CrossValidation::RunCrossValidation(), KKMLL::CrossValidationMxN::RunTrainAndTest(), KKMLL::CrossValidationVoting::RunValidationOnly(), KKMLL::CrossValidation::RunValidationOnly(), KKMLL::Orderings::Save(), PicesInterface::TrainingModel2::SaveConfiguration(), KKMLL::FeatureFileIO::SaveFeatureFileMultipleParts(), KKMLL::FeatureFileIOColumn::SaveFile(), KKMLL::FeatureFileIORoberts::SaveFile(), KKMLL::FeatureFileIOUCI::SaveFile(), KKMLL::FeatureFileIOC45::SaveFile(), KKMLL::FeatureFileIOSparse::SaveFile(), MLL::FeatureFileIOPices::SaveFile(), KKMLL::TrainingConfiguration2::SetModelParameters(), FeatureSelectionApp::Processor::SetQuitRunningFlag(), KKB::Configuration::SettingName(), KKB::Configuration::SettingValue(), SplitImagesAmongstFolds(), KKMLL::FeatureVectorList::StratifyAmoungstClasses(), SVM289_BFS::svm_problem::svm_problem(), SVM289_MFS::svm_problem::svm_problem(), KKMLL::SVMModel::SVMModel(), KKB::Raster::ThinContour(), KKMLL::TrainingConfiguration2::TrainingConfiguration2(), KKMLL::ModelSvmBase::TrainModel(), KKMLL::ModelOldSVM::TrainModel(), KKMLL::Model::TrainModel(), FeatureSelectionApp::Processor::Update(), KKMLL::ClassificationBiasMatrix::WriteXML(), MLL::AbundanceCorrectionMatrix::~AbundanceCorrectionMatrix(), KKMLL::ConfusionMatrix2::~ConfusionMatrix2(), KKMLL::CrossValidation::~CrossValidation(), KKMLL::CrossValidationVoting::~CrossValidationVoting(), KKMLL::FeatureFileIOArff::~FeatureFileIOArff(), SVM289_MFS::Kernel::~Kernel(), SVM289_BFS::Kernel::~Kernel(), and KKB::Tokenizer::~Tokenizer().
template<class Entry > void KKQueue::RandomizeOrder ()
Randomizes the order of the vector.
Implements the "Fisher-Yates Uniform Random Sort"; this implementation was done by Sergiy Fefilatyev (2011-01-27)
Definition at line 469 of file KKQueue.h.
References KKB::LRand48(), and KKB::KKQueue< Entry >::SwapIndexes().
Referenced by KKMLL::Orderings::CreateOrderingsObjFromFileIfAvaliable(), KKMLL::FeatureVectorList::ExtractRandomSampling(), KKMLL::TrainingProcess2::ExtractTrainingClassFeatures(), KKB::KKQueue< Entry >::RandomizeOrder(), KKMLL::Model::ReduceTrainExamples(), SplitImagesAmongstFolds(), and KKMLL::FeatureVectorList::StratifyAmoungstClasses().
template<class Entry > void KKQueue::RandomizeOrder (kkint64 seed)
Definition at line 490 of file KKQueue.h.
References KKB::KKQueue< Entry >::RandomizeOrder(), and KKB::SRand48().
template<class Entry > void KKQueue::RandomizeOrder (RandomNumGenerator & randomVariable)
Randomizes the order of the vector.
Implements the "Fisher-Yates Uniform Random Sort"; this implementation was done by Sergiy Fefilatyev (2011-01-27)
Definition at line 504 of file KKQueue.h.
References KKB::RandomNumGenerator::Next(), and KKB::KKQueue< Entry >::SwapIndexes().
template<class Entry > KKQueue< Entry >::EntryPtr KKQueue::RemoveFirst () inline virtual
same as PopFromFront
Definition at line 611 of file KKQueue.h.
References KKB::KKQueue< Entry >::PopFromFront().
template<class Entry > KKQueue< Entry >::EntryPtr KKQueue::RemoveLast () inline virtual
same as PopFromBack
Definition at line 619 of file KKQueue.h.
References KKB::KKQueue< Entry >::PopFromBack().
Referenced by KKB::ConvexHull::Draw().
template<class Entry> void KKQueue::SetIdxToPtr (kkuint32 _idx, Entry * _ptr)
Definition at line 700 of file KKQueue.h.
Referenced by KKB::Raster::ThinContour().
template<class Entry > void KKQueue::SwapIndexes (size_t idx1, size_t idx2)
Definition at line 769 of file KKQueue.h.
References KKB::endl().
Referenced by KKB::KKQueue< Entry >::FindTheKthElement(), and KKB::KKQueue< Entry >::RandomizeOrder().
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKQueue.h