Pices: C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/SipperFile.cpp File Reference
SipperFile.cpp File Reference
#include "FirstIncludes.h"
#include <stdlib.h>
#include <string.h>
#include <memory>
#include <string>
#include <iostream>
#include <fstream>
#include <vector>
#include <map>
#include "MemoryDebug.h"
#include "KKBaseTypes.h"
#include "GlobalGoalKeeper.h"
#include "KKStrParser.h"
#include "OSservices.h"
#include "KKStr.h"
#include "SipperFile.h"
#include "InstrumentDataFileManager.h"
Functions
kkint32 SearchFieldIdx (const KKStr searchField, const char *fieldNames[])
Function Documentation
kkint32 SearchFieldIdx (const KKStr searchField, const char * fieldNames[])
Definition at line 182 of file SipperFile.cpp.
References MLL::SipperFile::AssignCtdExternalInstruments(), MLL::SipperFile::CruiseName(), MLL::SipperFile::CtdExt0(), MLL::SipperFile::CtdExt1(), MLL::SipperFile::CtdExt2(), MLL::SipperFile::CtdExt3(), MLL::SipperFile::DateTimeStart(), MLL::SipperFile::DeploymentNum(), KKB::KKStr::EqualIgnoreCase(), KKB::KKStr::ExtractToken(), MLL::InstrumentDataFileManager::GetFullSipperFileName(), KKB::KKStrParser::GetNextToken(), KKB::KKStrParser::GetNextTokenChar(), KKB::KKStrParser::GetNextTokenDateTime(), KKB::KKStrParser::GetNextTokenDouble(), KKB::KKStrParser::GetNextTokenFloat(), KKB::KKStrParser::GetNextTokenInt(), KKB::KKStrParser::GetNextTokenLong(), KKB::KKStrParser::GetNextTokenUint(), KKB::KKStr::Len(), MLL::Instrument::LookUpByShortName(), KKB::KKStrParser::MoreTokens(), KKB::osGetFileDateTime(), KKB::osGetFileSize(), MLL::SipperFile::ParseTabDelStr(), MLL::SipperFile::ReFresh(), MLL::SipperFile::SizeInBytes(), MLL::SipperFile::Sp0(), MLL::SipperFile::Sp1(), MLL::SipperFile::Sp2(), MLL::SipperFile::StationName(), and KKB::KKStr::SubStrPart().