Pices: MLL::ImageFeaturesList Class Reference
MLL::ImageFeaturesList Class Reference
#include <ImageFeatures.h>
Classes
class const_iterator
class iterator
Public Types
typedef ImageFeaturesList * ImageFeaturesListPtr
typedef MLL::InstrumentDataListPtr InstrumentDataListPtr
typedef MLL::InstrumentDataPtr InstrumentDataPtr
typedef KKB::kkint32 kkint32
typedef KKB::kkuint32 kkuint32
Public Types inherited from KKMLL::FeatureVectorList
typedef FeatureVectorList * FeatureVectorListPtr
typedef float FVFloat
enum IFL_SortOrder {
IFL_SortOrder::IFL_UnSorted, IFL_SortOrder::IFL_ByName, IFL_SortOrder::IFL_ByProbability, IFL_SortOrder::IFL_ByBreakTie,
IFL_SortOrder::IFL_ByRootName, IFL_SortOrder::IFL_ByClassName
}
Represents the different orders that a list of FeatureVector instances in a FeatureVectorList object can be in.
Public Types inherited from KKB::KKQueue< FeatureVector >
typedef std::vector
< FeatureVector * >
::const_iterator const_iterator
typedef std::vector
< FeatureVector * >::iterator iterator
Public Member Functions
ImageFeaturesList (FileDescPtr _fileDesc, bool _owner, kkint32 _size=1000)
ImageFeaturesList (const ImageFeaturesList &images, bool _owner)
Constructs a duplicate list of ImageFeature objects and depending on '_owner' flag will either duplicate the ImageFeature instances or just point to the same instances.
ImageFeaturesList (const FeatureVectorList &featureVectorList, bool _owner)
ImageFeaturesList (RunLog &_log, MLClassPtr _mlClass, const KKStr &_dirName, const KKStr &_fileName)
Constructor that will extract a list of feature vectors for all the image files in the specified directory.
ImageFeaturesList (MLClassList &_mlClasses, ImageFeaturesList &_images)
constructor that will create a list of images from _images that are assigned one of the classes listed in _mlClasses.
ImageFeaturesList (const FeatureVectorList &featureVectorList)
virtual ~ImageFeaturesList ()
void AddQueue (ImageFeaturesList &imagesToAdd)
void AddSingleImageFeatures (ImageFeaturesPtr _imageFeatures)
ImageFeaturesPtr BackOfQueue ()
ImageFeaturesPtr BinarySearchByName (const KKStr &_imageFileName) const
VectorFloat CalculateDensitesByQuadrat (float scanRate, float quadratSize, float defaultFlowRate, const bool &cancelFlag, RunLog &log)
VectorInt CreateSpatialDistributionHistogram (InstrumentDataListPtr instrumentData, float defaultScanRate, float defaultFlowRate, float bucketSize)
virtual ImageFeaturesListPtr Duplicate (bool _owner) const
Creates a duplicate of list using the same container.
virtual ImageFeaturesListPtr DuplicateListAndContents () const
Creates a duplicate of list and also duplicates it contents.
ImageFeaturesListPtr ExtractDuplicatesByRootImageFileName ()
Returns: a list of 'ImageFeatures' objects that have duplicate root file names.
ImageFeaturesListPtr ExtractExamplesForAGivenClass (MLClassPtr _mlClass, kkint32 _maxToExtract=-1, FVFloat _minSize=-1.0f) const
VectorDouble ExtractPositionsByMeter (InstrumentDataListPtr instrumentData, float defaultScanRate, float defaultFlowRate)
Calculates the position in meters of each plankton Feature-Vector with respect to the first plankton particle in the SIPPER file.
void FeatureExtraction (const KKStr &_dirName, const KKStr &_fileName, MLClassPtr _mlClass, RunLog &_runLog)
void FixSipperFileScanLineAndColFields ()
Fixed the two fields sfCentroidCol & sfCentroidRow.
ImageFeaturesPtr IdxToPtr (kkint32 idx) const
ImageFeaturesPtr LookUpByImageFileName (const KKStr &_imageFileName) const
ImageFeaturesPtr LookUpByRootName (const KKStr &_rootName)
virtual ImageFeaturesListPtr ManufactureEmptyList (bool _owner) const
Creates an instance of a Empty FeatureVectorList.
ImageFeaturesListPtr OrderUsingNamesFromAFile (const KKStr &fileName, RunLog &runLog)
return a list of examples that consist and are in the same order as the list of ImageFileNames in the file 'fileName'.
ImageFeaturesPtr PopFromBack ()
Removes the last element in the container and returns its pointer.
void PrintSpatialHistogramReport (std::ostream &r, InstrumentDataListPtr instrumentData, float defaultScanRate, float defaultFlowRate, float bucketSize)
void RecalcFeatureValuesFromImagesInDirTree (KKStr rootDir, bool &successful, RunLog &runLog)
void SortBySpatialDistance ()
ImageFeaturesListPtr StratifyAmoungstClasses (kkint32 numOfFolds, RunLog &runLog)
ImageFeaturesListPtr StratifyAmoungstClasses (MLClassListPtr mlClasses, kkint32 maxImagesPerClass, kkint32 numOfFolds, RunLog &runLog)
short Version () const
void Version (short _version)
Public Member Functions inherited from KKMLL::FeatureVectorList
FeatureVectorList ()
When you use this constructor you need to define immediately provide the appropriate FileDesc instance via calling "ResetFileDesc" method.
FeatureVectorList (FileDescPtr _fileDesc, bool _owner)
Will create a new empty list of FeatureVector's.
FeatureVectorList (const FeatureVectorList &examples, bool _owner)
Create a duplicate list, depending on the '_owner' parameter may also duplicate the contents.
FeatureVectorList (MLClassList &_mlClasses, FeatureVectorList &_examples)
Will create a list of consisting of the subset of examples in '_examples' which are members of ImagesClasses.
virtual ~FeatureVectorList ()
void AddQueue (const FeatureVectorList &examplesToAdd)
Add the contents of 'examplesToAdd' to the end of this list.
void AddSingleExample (FeatureVectorPtr _imageFeatures)
Same as PushOnBack.
FeatureNumList AllFeatures ()
Will return a FeatureNumList instance with all features selected.
bool AllFieldsAreNumeric () const
Returns true if all fields are numeric, no nominal fields.
void AppendToFile (KKStr _fileName, FeatureFileIOPtr _driver, const FeatureNumList &_selFeatures)
FeatureVectorPtr BinarySearchByName (const KKStr &_imageFileName) const
Will search for the example with the same name as '_imageFileName'.
void CalcStatsForFeatureNum (kkint32 _featureNum, kkint32 &_count, float &_total, float &_mean, float &_var, float &_stdDev)
KKStr ClassStatisticsStr () const
KKMLL::AttributeTypeVector CreateAttributeTypeTable () const
vector< kkint32 > CreateCardinalityTable () const
FeatureVectorListPtr CreateListForAGivenLevel (kkint32 level)
Will create a list of FeatureVectors where the class assignment will reflect the specified Hierarchy level specified by 'level'.
IFL_SortOrder CurSortOrder () const
KKStrListPtr ExtractDuplicatesByExampleFileName ()
FeatureVectorListPtr ExtractDuplicatesByRootImageFileName ()
Returns: a list of 'FeatureVector' objects that have duplicate root file names.
FeatureVectorListPtr ExtractExamplesForAGivenClass (MLClassPtr _mlClass, kkint32 _maxToExtract=-1, float _minSize=-1.0f) const
FeatureVectorListPtr ExtractExamplesForClassList (MLClassListPtr classes)
FeatureVectorListPtr ExtractExamplesForHierarchyLevel (kkuint32 level)
Will create a list of FeatureVectors where the class assignment will reflect the specified Hierarchy level specified by 'level'.
MLClassListPtr ExtractListOfClasses () const
VectorDouble ExtractMeanFeatureValues ()
FeatureVectorListPtr ExtractRandomSampling (float percentage, kkint32 minClassCount)
Will return a random sampling by class of our FeatureVector's; with a minimum per class of 'minClassCount'.
kkint32 FeatureCardinality (kkint32 featureNum) const
Returns the number of values defined for a Nominal Field.
kkint32 FeatureCount () const
KKMLL::AttributeType FeatureType (kkint32 featureNum) const
Returns the type of attribute for specified 'featureNum'.
KKStr FeatureTypeStr (kkint32 featureNum) const
const KKStr & FieldName (kkint32 featureNum) const
Returns name of Attribute Field.
const FileDescPtr FileDesc () const
const KKStr & FileName () const
void FileName (const KKStr &_fileName)
kkint32 GetClassCount (MLClassPtr c) const
Returns number of examples for a specific Class (MLClass).
ClassProbListPtr GetClassDistribution () const
ClassStatisticListPtr GetClassStatistics () const
Returns the number of FeatureVectors per class.
FeatureVectorPtr LookUpByImageFileName (const KKStr &_imageFileName) const
Returns a pointer to the FeatureVector which has '_imageFileName'.
FeatureVectorPtr LookUpByRootName (const KKStr &_rootName)
Returns a pointer to the FeatureVector who's ExampleFileName rootname = _rootName *
float MajorityClassFraction () const
Return's the fraction that the majority class makes up in this list.
virtual kkint32 MemoryConsumedEstimated () const
bool MissingData () const
Returns true if 1 or more entries have missing data.
kkint32 NumEntriesOfAGivenClass (MLClassPtr mlClass) const
kkint32 NumOfFeatures () const
FeatureVectorListPtr OrderUsingNamesFromAFile (const KKStr &fileName, RunLog &log)
Using list of ImageFileNames in a file('fileName') create a new FeatureVectorList instance with examples in order based off contents of file.
void PrintClassStatistics (std::ostream &o) const
void PrintClassStatisticsHTML (std::ostream &o) const
void PrintFeatureStatisticsByClass (std::ostream &o) const
void PushOnBack (FeatureVectorPtr image)
Overloading the PushOnBack function in KKQueue so we can monitor the Version and Sort Order.
void PushOnFront (FeatureVectorPtr image)
Overloading the PushOnFront function in KKQueue so we can monitor the Version and Sort Order.
void RemoveDuplicateEntries (bool allowDupsInSameClass, RunLog &runLog)
void RemoveEntriesWithMissingFeatures (RunLog &log)
Will delete entries from list that have missing data.
void ResetFileDesc (FileDescPtr newFileDesc)
You would use this if youRecalc all the data to a newer version of the file.
void ResetNumOfFeaturs (kkint32 newNumOfFeatures)
void ReSyncSymbolicData (FileDescPtr newFileDesc)
bool SameExceptForSymbolicData (const FeatureVectorList &otherData, RunLog &log) const
void SaveOrderingOfImages (const KKStr &fileName, bool &successful)
Will save into a file the current ordering of FeatureVector instances in list.
void SortByBreakTie (bool reversedOrder=false)
void SortByClass (bool reversedOrder=false)
void SortByImageFileName (bool reversedOrder=false)
void SortByProbability (bool reversedOrder=false)
void SortByRootName (bool reversedOrder=false)
FeatureVectorListPtr StratifyAmoungstClasses (kkint32 numOfFolds, RunLog &log)
FeatureVectorListPtr StratifyAmoungstClasses (MLClassListPtr mlClasses, kkint32 maxImagesPerClass, kkint32 numOfFolds, RunLog &log)
void SynchronizeSymbolicData (FeatureVectorList &otherData, RunLog &log)
kkint16 Version () const
void Version (kkint16 _version)
Public Member Functions inherited from KKB::KKQueue< FeatureVector >
KKQueue (bool _owner=true)
KKQueue (const KKQueue &q, bool _owner)
Constructor, similar to the Copy Constructor except that you can control whether it duplicates the contents.
virtual ~KKQueue ()
void Add (EntryPtr _entry)
same as PushOnBack
void AddFirst (EntryPtr _entry)
same as PushOnFront
virtual void AddQueue (const KKQueue &q)
EntryPtr BackOfQueue () const
Returns pointer of last element in the container without removing it.
void Compress ()
No longer does anything.
void DeleteContents ()
Empties the container, if 'owner' is set to true will call the destructor on each element.
void DeleteEntry (EntryPtr _entry)
Removes from KKQueue the entry who's pointer = '_entry'.
void DeleteEntry (kkuint32 _idx)
Removes from KKQueue the entry who's index = '_idx'.
KKQueue * DuplicateListAndContents () const
Creates a new container including duplicating the contents, which also makes the new instance the owner of those contents.
kkuint32 FindTheKthElement (kkuint32 k, Functor pred)
EntryPtr FrontOfQueue () const
Returns a pointer to the element that is at from of the queue with out removing it from the queue.
EntryPtr GetFirst () const
EntryPtr GetLast () const
EntryPtr IdxToPtr (kkuint32 idx) const
Returns back a pointer to the element who's index is 'idx'.
kkint32 LocateEntry (EntryConstPtr _entry) const
Returns the index of the element who's address is '_entry'.
EntryPtr LookAtBack () const
Returns pointer to element at Back of container with out removing it from the container.
EntryPtr LookAtFront () const
Returns pointer to element at Front of container with out removing it from the container.
bool operator!= (const KKQueue< FeatureVector > &rightSide) const
returns False if NOT every entry in both containers point to the same elements
KKQueue & operator= (const KKQueue &q)
Assignment Operator.
bool operator== (const KKQueue< FeatureVector > &rightSide) const
Returns True if every entry in both containers point to the same elements.
FeatureVector & operator[] (kkuint32 i) const
Returns a reference to element indexed by 'i'.
bool Owner () const
void Owner (bool _owner)
You can specify who owns the contents of the container.
virtual EntryPtr PopFromFront ()
Removes the first element in the container and returns its pointer.
kkint32 PtrToIdx (EntryConstPtr _entry) const
returns the index of the 'entry' that has the same pointer as '_entry', if none found returns -1
virtual void PushOnBack (EntryPtr _entry)
Adds '_entry' to the End of the container.
virtual void PushOnFront (EntryPtr _entry)
Adds '_entry' to the Front of the container.
kkint32 QueueSize () const
Same as calling vector<>::size().
void RandomizeOrder ()
void RandomizeOrder (kkint64 seed)
void RandomizeOrder (RandomNumGenerator &randomVariable)
EntryPtr RemoveFirst ()
same as PopFromFront
EntryPtr RemoveLast ()
same as PopFromBack
void SetIdxToPtr (kkuint32 _idx, FeatureVector *_ptr)
void SwapIndexes (size_t idx1, size_t idx2)
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Protected Member Functions inherited from KKB::KKQueue< FeatureVector >
KKQueue (const KKQueue &q)
Copy Constructor, will create a new instance.
Detailed Description
Definition at line 338 of file ImageFeatures.h.
Member Typedef Documentation
typedef ImageFeaturesList* MLL::ImageFeaturesList::ImageFeaturesListPtr
Definition at line 341 of file ImageFeatures.h.
typedef MLL::InstrumentDataListPtr MLL::ImageFeaturesList::InstrumentDataListPtr
Definition at line 344 of file ImageFeatures.h.
typedef MLL::InstrumentDataPtr MLL::ImageFeaturesList::InstrumentDataPtr
Definition at line 343 of file ImageFeatures.h.
typedef KKB::kkint32 MLL::ImageFeaturesList::kkint32
Definition at line 346 of file ImageFeatures.h.
typedef KKB::kkuint32 MLL::ImageFeaturesList::kkuint32
Definition at line 347 of file ImageFeatures.h.
Constructor & Destructor Documentation
ImageFeaturesList::ImageFeaturesList (FileDescPtr _fileDesc, bool _owner, kkint32 _size = 1000)
Definition at line 1082 of file ImageFeatures.cpp.
Referenced by Duplicate(), DuplicateListAndContents(), ExtractDuplicatesByRootImageFileName(), ExtractExamplesForAGivenClass(), ManufactureEmptyList(), OrderUsingNamesFromAFile(), and StratifyAmoungstClasses().
ImageFeaturesList::ImageFeaturesList (const ImageFeaturesList & images, bool _owner)
Constructs a duplicate list of ImageFeature objects and depending on '_owner' flag will either duplicate the ImageFeature instances or just point to the same instances.
Will create a duplicate List of images, in the same order. If '_owner' = true will create new instances of contents and own them. If 'owner' = false, will copy over pointers of existing instances.
Definition at line 1130 of file ImageFeatures.cpp.
References KKB::KKQueue< FeatureVector >::Owner(), and KKMLL::FeatureVectorList::PushOnBack().
ImageFeaturesList::ImageFeaturesList (const FeatureVectorList & featureVectorList, bool _owner)
Will create a duplicate List of images, in the same order. If '_owner' = true will create new instances of contents and own them. If 'owner' = false, will copy over pointers to existing instances. If any of the existing instances do not have an underlying class of ImageFeatures; the function will throw an EXCEPTIION.
Definition at line 1149 of file ImageFeatures.cpp.
References KKB::endl(), KKMLL::FeatureVector::ExampleFileName(), KKMLL::FeatureVectorList::PushOnBack(), and Version().
ImageFeaturesList::ImageFeaturesList (RunLog & _log, MLClassPtr _mlClass, const KKStr & _dirName, const KKStr & _fileName)
Constructor that will extract a list of feature vectors for all the image files in the specified directory.
Will scan the directory _dirName for any image files. For each image found a new instance of ImageFeatures will be created who's features will be derived from the image. These ImageFeatures' objects will be assigned the class specified by '_mlClass'. A new data file containing the extracted features will be saved in fileName.
Parameters
[in] _log Log file to write messages to.
[in] _mlClass Class to assign to new 'ImageFeatures' objects.
[in] _dirName Directory to scan for images.
[in] _fileName Name of file to contain the extracted feature data. Will be og the Raw format.
Definition at line 1096 of file ImageFeatures.cpp.
References FeatureExtraction().
ImageFeaturesList::ImageFeaturesList (MLClassList & _mlClasses, ImageFeaturesList & _images)
constructor that will create a list of images from _images that are assigned one of the classes listed in _mlClasses.
Will Create a list of images that are a subset of the ones in _images. The subset will consist of the images who's mlClass is one of the ones in mlClasses. We will not own any the contents only point to the ones already in _images.
Parameters
[in] _mlClasses List of classes that we are interested in.
[in] _images Source examples that we want to scan.
Definition at line 1224 of file ImageFeatures.cpp.
ImageFeaturesList::ImageFeaturesList (const FeatureVectorList & featureVectorList)
This constructor is meant to create a list of 'ImageFeatures' objects from the FeatureVector objects contained in featureVectorList.
If  'featureVectorList' owns its contents (that is 'featureVectorList.Owner () == true'  then
   |  We will create new Instances of 'ImageFeatures' objects that we will own.
   |  The underlying class of the 'FeatureVector' objects will be converted to a
   |  'ImageFeatures'  class.
else
   |  all the 'FeatureVector' objects in 'featureVectorList' must have an underlying class of
   |  'ImageFeatures'. If one or more do not then the program will halt with a message to
   |  the log.
Definition at line 1236 of file ImageFeatures.cpp.
References KKB::endl(), KKMLL::FeatureVector::ExampleFileName(), KKB::KKQueue< Entry >::Owner(), KKMLL::FeatureVectorList::PushOnBack(), and Version().
ImageFeaturesList::~ImageFeaturesList () virtual
Definition at line 1298 of file ImageFeatures.cpp.
Member Function Documentation
void ImageFeaturesList::AddQueue (ImageFeaturesList & imagesToAdd)
Definition at line 1368 of file ImageFeatures.cpp.
References KKB::KKQueue< FeatureVector >::QueueSize(), and Version().
Referenced by MLL::FeatureFileIOPices::LoadInSubDirectoryTree().
void ImageFeaturesList::AddSingleImageFeatures (ImageFeaturesPtr _imageFeatures)
Definition at line 1321 of file ImageFeatures.cpp.
References KKMLL::FeatureVectorList::PushOnBack().
Referenced by DuplicateListAndContents().
ImageFeaturesPtr ImageFeaturesList::BackOfQueue ()
Definition at line 1328 of file ImageFeatures.cpp.
References KKB::endl().
ImageFeaturesPtr ImageFeaturesList::BinarySearchByName (const KKStr & _imageFileName) const
Definition at line 1392 of file ImageFeatures.cpp.
Referenced by MLL::FeatureFileIOPices::FeatureDataReSink().
VectorFloat ImageFeaturesList::CalculateDensitesByQuadrat (float scanRate, float quadratSize, float defaultFlowRate, const bool & cancelFlag, RunLog & log)
Parameters
scanRate Scan Lines per Sec.
quadratSize Meters.
defaultFlowRate Meters per Sec.
Definition at line 1907 of file ImageFeatures.cpp.
References KKB::endl(), KKMLL::FeatureVector::ExampleFileName(), MLL::InstrumentDataFileManager::GetClosestInstrumentData(), MLL::InstrumentDataFileManager::InitializePop(), MLL::InstrumentDataFileManager::InitializePush(), MLL::ImageFeatures::SfCentroidRow(), and SortBySpatialDistance().
VectorInt ImageFeaturesList::CreateSpatialDistributionHistogram (InstrumentDataListPtr instrumentData, float defaultScanRate, float defaultFlowRate, float bucketSize)
Parameters
defaultScanRate Scan rate to use if it can not be located from.
defaultFlowRate Flow rate to use if no instrumentation data.
bucketSize Size of each histogram bucket.
Definition at line 1600 of file ImageFeatures.cpp.
References ExtractPositionsByMeter().
Referenced by PrintSpatialHistogramReport().
ImageFeaturesListPtr ImageFeaturesList::Duplicate (bool _owner) const virtual
Creates a duplicate of list using the same container.
Reimplemented from KKMLL::FeatureVectorList.
Definition at line 1305 of file ImageFeatures.cpp.
References ImageFeaturesList().
ImageFeaturesListPtr ImageFeaturesList::DuplicateListAndContents () const virtual
Creates a duplicate of list and also duplicates it contents.
Returns
Duplicated list with hard copy of its contents.
Reimplemented from KKMLL::FeatureVectorList.
Definition at line 1705 of file ImageFeatures.cpp.
References AddSingleImageFeatures(), IdxToPtr(), ImageFeaturesList(), KKB::KKQueue< FeatureVector >::QueueSize(), and Version().
ImageFeaturesListPtr ImageFeaturesList::ExtractDuplicatesByRootImageFileName ()
Returns: a list of 'ImageFeatures' objects that have duplicate root file names.
Returns: a list of 'ImageFeatures' objects that have duplicate root file names. The returned list will not own these items. All instances of the duplicate objects will be returned. Ex: if three instances have the same ImageFileName all three will be returned.
Definition at line 1783 of file ImageFeatures.cpp.
References ImageFeaturesList(), and KKB::KKQueue< Entry >::Owner().
ImageFeaturesListPtr ImageFeaturesList::ExtractExamplesForAGivenClass (MLClassPtr _mlClass, kkint32 _maxToExtract = -1, FVFloat _minSize = -1.0f) const
Definition at line 1797 of file ImageFeatures.cpp.
References ImageFeaturesList(), and KKB::KKQueue< Entry >::Owner().
Referenced by PrintSpatialHistogramReport().
VectorDouble ImageFeaturesList::ExtractPositionsByMeter (InstrumentDataListPtr instrumentData, float defaultScanRate, float defaultFlowRate)
Calculates the position in meters of each plankton Feature-Vector with respect to the first plankton particle in the SIPPER file.
It is assumed that all the items in this list are from the same SIPPER file. Item(FeatureVector) will be assigned a position in meters with respect to the first particle in the file.
Parameters
[in] instrumentData Provides the flow rate from the instrument data will be used to calc distance traveled; otherwise 'defaultFlowRate' will be used.
[in] defaultScanRate Scan lines per second that the camera operates at, if <= 0 will assume 24950.0 scan lines/sec.
[in] defaultFlowRate Flow rate to use if none provided by 'instrumentData'. if <= 0.0 will default to 1.0 meters/sec.
Returns
A Vector of doubles where each element in it will represent the distance in meters from the first particle in the SIPPER file. There will be one entry for each "ImageFeatures" object in the list and it will be sorted from low to high.
Definition at line 1529 of file ImageFeatures.cpp.
References MLL::InstrumentData::FlowRate1(), MLL::InstrumentDataList::FrameOffsetsInMeters(), MLL::InstrumentDataList::SearchForNearestScanLine(), MLL::ImageFeatures::SfCentroidRow(), and SortBySpatialDistance().
Referenced by CreateSpatialDistributionHistogram().
void ImageFeaturesList::FeatureExtraction (const KKStr & _dirName, const KKStr & _fileName, MLClassPtr _mlClass, RunLog & _runLog)
Definition at line 1442 of file ImageFeatures.cpp.
References KKMLL::FeatureVectorList::AllFeatures(), CurrentFeatureFileVersionNum, MLL::FeatureFileIOPices::Driver(), KKB::endl(), KKMLL::FeatureVector::ExampleFileName(), KKB::RunLog::Level(), KKMLL::FeatureVector::OrigSize(), KKB::osAddSlash(), KKB::osDisplayWarning(), KKB::osGetListOfFiles(), KKMLL::FeatureVectorList::PushOnBack(), KKB::KKQueue< Entry >::QueueSize(), KKMLL::FeatureFileIO::SaveFeatureFile(), KKB::SupportedImageFileFormat(), and Version().
Referenced by ImageFeaturesList().
void ImageFeaturesList::FixSipperFileScanLineAndColFields ()
Fixed the two fields sfCentroidCol & sfCentroidRow.
This has to be done because the original calculations for them assumed that there would be no '_' characters in the sipper file name.
Definition at line 1857 of file ImageFeatures.cpp.
References MLL::ImageFeatures::CentroidCol(), MLL::ImageFeatures::CentroidRow(), KKMLL::FeatureVector::ExampleFileName(), KKB::KKStr::LocateLastOccurrence(), KKB::osGetRootName(), MLL::ImageFeatures::SfCentroidCol(), MLL::ImageFeatures::SfCentroidRow(), KKB::KKStr::Str(), and KKB::KKStr::SubStrPart().
ImageFeaturesPtr ImageFeaturesList::IdxToPtr (kkint32 idx) const
Definition at line 1313 of file ImageFeatures.cpp.
Referenced by DuplicateListAndContents(), and MLL::FeatureFileIOPices::SaveFile().
ImageFeaturesPtr ImageFeaturesList::LookUpByImageFileName (const KKStr & _imageFileName) const
Definition at line 1416 of file ImageFeatures.cpp.
ImageFeaturesPtr ImageFeaturesList::LookUpByRootName (const KKStr & _rootName)
Definition at line 1401 of file ImageFeatures.cpp.
ImageFeaturesListPtr ImageFeaturesList::ManufactureEmptyList (bool _owner) const virtual
Creates an instance of a Empty FeatureVectorList.
Reimplemented from KKMLL::FeatureVectorList.
Definition at line 1409 of file ImageFeatures.cpp.
References ImageFeaturesList().
ImageFeaturesListPtr ImageFeaturesList::OrderUsingNamesFromAFile (const KKStr & fileName, RunLog & runLog)
return a list of examples that consist and are in the same order as the list of ImageFileNames in the file 'fileName'.
Using list of ImageFileNames in a file('fileName') create a new ImageFeaturesList instance with images in order based off contents of file. If error occurs will return NULL.
Definition at line 1425 of file ImageFeatures.cpp.
References ImageFeaturesList(), and KKB::KKQueue< Entry >::Owner().
ImageFeaturesPtr ImageFeaturesList::PopFromBack () virtual
Removes the last element in the container and returns its pointer.
If the container is empty will return NULL.
Reimplemented from KKB::KKQueue< FeatureVector >.
Definition at line 1347 of file ImageFeatures.cpp.
References KKB::endl().
Referenced by MLL::DataBase::FeatureDataRecLoad().
void ImageFeaturesList::PrintSpatialHistogramReport (std::ostream & r, InstrumentDataListPtr instrumentData, float defaultScanRate, float defaultFlowRate, float bucketSize)
Parameters
defaultScanRate Scan rate to use if it can not be located from.
defaultFlowRate Flow rate to use if no instrumentation data.
Definition at line 1631 of file ImageFeatures.cpp.
References CreateSpatialDistributionHistogram(), KKB::endl(), ExtractExamplesForAGivenClass(), KKMLL::FeatureVectorList::ExtractListOfClasses(), KKB::Max(), and KKMLL::MLClassList::SortByName().
void ImageFeaturesList::RecalcFeatureValuesFromImagesInDirTree (KKStr rootDir, bool & successful, RunLog & runLog)
Definition at line 1725 of file ImageFeatures.cpp.
References MLL::ImageFeatures::CalcFeatures(), KKB::endl(), KKMLL::FeatureVector::ExampleFileName(), KKB::RunLog::Level(), KKB::ImageDirTree::LocateImage(), KKB::osAddLastSlash(), KKB::KKQueue< FeatureVector >::QueueSize(), and KKB::ImageDirTree::Size().
void ImageFeaturesList::SortBySpatialDistance ()
Definition at line 1886 of file ImageFeatures.cpp.
Referenced by CalculateDensitesByQuadrat(), and ExtractPositionsByMeter().
ImageFeaturesListPtr ImageFeaturesList::StratifyAmoungstClasses (kkint32 numOfFolds, RunLog & runLog)
Definition at line 1829 of file ImageFeatures.cpp.
References KKMLL::FeatureVectorList::ExtractListOfClasses(), ImageFeaturesList(), and KKB::KKQueue< Entry >::Owner().
ImageFeaturesListPtr ImageFeaturesList::StratifyAmoungstClasses (MLClassListPtr mlClasses, kkint32 maxImagesPerClass, kkint32 numOfFolds, RunLog & runLog)
Definition at line 1813 of file ImageFeatures.cpp.
References ImageFeaturesList(), and KKB::KKQueue< Entry >::Owner().
short MLL::ImageFeaturesList::Version () const inline
Definition at line 574 of file ImageFeatures.h.
Referenced by AddQueue(), DuplicateListAndContents(), MLL::FeatureFileIOPices::FeatureDataReSink(), FeatureExtraction(), ImageFeaturesList(), MLL::FeatureFileIOPices::LoadFile(), and MLL::FeatureFileIOPices::SaveFile().
void MLL::ImageFeaturesList::Version (short _version) inline
Definition at line 576 of file ImageFeatures.h.
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/ImageFeatures.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/ImageFeatures.cpp