Pices: ImageExtractionManager::LogicalFrameQueue Class Reference
ImageExtractionManager::LogicalFrameQueue Class Reference
#include <LogicalFrameQueue.h>
Public Member Functions
LogicalFrameQueue (const ExtractionParms &_parms, kkuint32 _maxSize, kkuint32 _frameHeightMax, kkuint32 _frameWidth, const bool &_cancelFlag)
~LogicalFrameQueue ()
void AddBackToAvailableFrames (LogicalFramePtr availableFrame)
void AddBackToFramesAwaitingProcessing (LogicalFramePtr frameAwaitingProcessing)
void FrameProcessed (LogicalFramePtr processedFrame)
'ImageProcessorThread; calls this method when it is done processing a frame.
kkuint32 FramesOnQueue ()
Returns the number frames awaiting processing.
LogicalFramePtr GetNextAvailaleFrame ()
Returns the a Frame that is not in use; if none are available will return NULL.
LogicalFramePtr GetNextFrameToProcess ()
Returns the next logical frame that needs to be processed.
kkint32 MemoryConsumedEstimated () const
void QueueFrameToProcess (LogicalFramePtr processedFrame)
The 'FrameExtractorThread' calls this method to add a frame that needs to be processed.
Detailed Description
Definition at line 21 of file LogicalFrameQueue.h.
Constructor & Destructor Documentation
LogicalFrameQueue::LogicalFrameQueue (const ExtractionParms & _parms, kkuint32 _maxSize, kkuint32 _frameHeightMax, kkuint32 _frameWidth, const bool & _cancelFlag)
Definition at line 25 of file LogicalFrameQueue.cpp.
LogicalFrameQueue::~LogicalFrameQueue ()
Definition at line 44 of file LogicalFrameQueue.cpp.
Member Function Documentation
void LogicalFrameQueue::AddBackToAvailableFrames (LogicalFramePtr availableFrame)
Definition at line 175 of file LogicalFrameQueue.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
Referenced by ImageExtractionManager::FrameExtractorThread::Run().
void LogicalFrameQueue::AddBackToFramesAwaitingProcessing (LogicalFramePtr frameAwaitingProcessing)
Definition at line 184 of file LogicalFrameQueue.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
Referenced by ImageExtractionManager::FrameProcessorThread::GetRunTimeStats().
void LogicalFrameQueue::FrameProcessed (LogicalFramePtr processedFrame)
'ImageProcessorThread; calls this method when it is done processing a frame.
This lets the queue know that the frame is available for use and can be used again by the 'FrameExtractorThread'.
Definition at line 108 of file LogicalFrameQueue.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
Referenced by ImageExtractionManager::FrameProcessorThread::Run().
kkuint32 LogicalFrameQueue::FramesOnQueue ()
Returns the number frames awaiting processing.
Definition at line 76 of file LogicalFrameQueue.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
Referenced by ImageExtractionManager::ExtractionManager::GetRunTimeStats().
LogicalFramePtr LogicalFrameQueue::GetNextAvailaleFrame ()
Returns the a Frame that is not in use; if none are available will return NULL.
Definition at line 120 of file LogicalFrameQueue.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
Referenced by ImageExtractionManager::FrameExtractorThread::Run().
LogicalFramePtr LogicalFrameQueue::GetNextFrameToProcess ()
Returns the next logical frame that needs to be processed.
If there are no frames that are ready to be processed will return NULL.
Definition at line 148 of file LogicalFrameQueue.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
Referenced by ImageExtractionManager::FrameProcessorThread::GetRunTimeStats().
kkint32 LogicalFrameQueue::MemoryConsumedEstimated () const
Definition at line 60 of file LogicalFrameQueue.cpp.
References ImageExtractionManager::LogicalFrame::MemoryConsumedEstimated().
void LogicalFrameQueue::QueueFrameToProcess (LogicalFramePtr processedFrame)
The 'FrameExtractorThread' calls this method to add a frame that needs to be processed.
Definition at line 166 of file LogicalFrameQueue.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
Referenced by ImageExtractionManager::FrameExtractorThread::Run().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/ImageExtractionManager/LogicalFrameQueue.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/ImageExtractionManager/LogicalFrameQueue.cpp