Pices: KKB::MorphOpDilation Class Reference
KKB::MorphOpDilation Class Reference
#include <MorphOpDilation.h>
Public Member Functions
MorphOpDilation (StructureType _structure, kkuint16 _structureSize)
virtual ~MorphOpDilation ()
kkint32 MemoryConsumedEstimated ()
virtual OperationType Operation () const
virtual RasterPtr PerformOperation (RasterConstPtr _image)
Public Member Functions inherited from KKB::MorphOpStruct
MorphOpStruct (StructureType _structure, kkuint16 _structureSize)
virtual ~MorphOpStruct ()
void BackgroundCountTH (kkint32 _backgroundCountTH)
void ForegroundCountTH (kkint32 _foregroundCountTH)
kkint32 MemoryConsumedEstimated ()
Public Member Functions inherited from KKB::MorphOp
MorphOp ()
virtual ~MorphOp ()
OperationType OperationTypeFromStr (const KKB::KKStr &_operationStr)
KKB::KKStr OperationTypeToStr (OperationType _operation)
virtual RasterPtr PerformOperation (Raster const *_image)=0
Additional Inherited Members
Public Types inherited from KKB::MorphOp
enum MaskTypes : int {
MaskTypes::CROSS3 = 0, MaskTypes::CROSS5 = 1, MaskTypes::SQUARE3 = 2, MaskTypes::SQUARE5 = 3,
MaskTypes::SQUARE7 = 4, MaskTypes::SQUARE9 = 5, MaskTypes::SQUARE11 = 6
}
enum OperationType {
OperationType::Null, OperationType::Binarize, OperationType::BmiFiltering, OperationType::ConvexHull,
OperationType::Dilation, OperationType::Erosion, OperationType::MaskExclude, OperationType::Stretcher
}
enum StructureType : int { StructureType::Null, StructureType::stCross, StructureType::stSquare }
Static Public Member Functions inherited from KKB::MorphOp
static kkint32 Biases (MaskTypes mt)
static StructureType MaskShapes (MaskTypes mt)
Protected Member Functions inherited from KKB::MorphOpStruct
bool Fit (kkint32 row, kkint32 col) const
bool FitBackgroundCount (kkint32 row, kkint32 col) const
uchar HitForegroundCount (kkint32 row, kkint32 col) const
Protected Attributes inherited from KKB::MorphOpStruct
kkint32 backgroundCountTH
If greater than zero; then pixel must have at least that many neighbors to be considered a fit.
kkint32 foregroundCountTH
StructureType structure
kkuint16 structureSize
Static Protected Attributes inherited from KKB::MorphOp
static kkint32 biases []
static StructureType maskShapes []
Detailed Description
Definition at line 24 of file MorphOpDilation.h.
Constructor & Destructor Documentation
MorphOpDilation::MorphOpDilation (StructureType _structure, kkuint16 _structureSize)
Definition at line 22 of file MorphOpDilation.cpp.
MorphOpDilation::~MorphOpDilation () virtual
Definition at line 31 of file MorphOpDilation.cpp.
Member Function Documentation
kkint32 MorphOpDilation::MemoryConsumedEstimated ()
Definition at line 37 of file MorphOpDilation.cpp.
virtual OperationType KKB::MorphOpDilation::Operation () const inline virtual
Reimplemented from KKB::MorphOpStruct.
Definition at line 33 of file MorphOpDilation.h.
RasterPtr MorphOpDilation::PerformOperation (RasterConstPtr _image) virtual
Implements KKB::MorphOpStruct.
Definition at line 45 of file MorphOpDilation.cpp.
References KKB::MorphOp::BackgroundPixel(), KKB::MorphOp::ForegroundPixel(), KKB::Raster::ForegroundPixelCount(), KKB::Raster::Green(), KKB::MorphOpStruct::HitForegroundCount(), KKB::MorphOp::SetSrcRaster(), KKB::MorphOp::srcGreen, KKB::MorphOp::srcHeight, KKB::MorphOp::srcRaster, and KKB::MorphOp::srcWidth.
Referenced by KKB::Raster::Dilation().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/KSquareLibraries/KKBase/MorphOpDilation.h
C:/Users/kurtk_000/GitHub/KSquareLibraries/KKBase/MorphOpDilation.cpp