Pices: MLL::PicesTrainingConfiguration Class Reference
MLL::PicesTrainingConfiguration Class Reference
#include <PicesTrainingConfiguration.h>
Public Types
typedef PicesTrainingConfiguration const PicesTrainingConfigurationConst
typedef PicesTrainingConfigurationConst * PicesTrainingConfigurationConstPtr
typedef PicesTrainingConfiguration * PicesTrainingConfigurationPtr
Public Types inherited from KKMLL::TrainingConfiguration2
typedef Model::ModelTypes ModelTypes
typedef TrainingConfiguration2 const TrainingConfiguration2Const
typedef TrainingConfiguration2Const * TrainingConfiguration2ConstPtr
typedef TrainingConfiguration2 * TrainingConfiguration2Ptr
Public Member Functions
PicesTrainingConfiguration ()
PicesTrainingConfiguration (const TrainingConfiguration2 &tc)
PicesTrainingConfiguration (const PicesTrainingConfiguration &tc)
PicesTrainingConfiguration (MLClassListPtr _mlClasses, KKStr _parameterStr, RunLog &_log)
Use this one if you want to create a default Configuration object.
~PicesTrainingConfiguration ()
virtual FactoryFVProducerPtr DefaultFeatureVectorProducer (RunLog &runLog) const
virtual PicesTrainingConfigurationPtr Duplicate () const
virtual void Load (const KKStr &_configFileName, bool _validateDirectories, RunLog &_log)
virtual void ReadXML (XmlStream &s, XmlTagConstPtr tag, VolConstBool &cancelFlag, RunLog &log)
virtual void Save (const KKStr &fileName) const
void WriteXML (const KKStr &varName, std::ostream &o) const
Public Member Functions inherited from KKMLL::TrainingConfiguration2
TrainingConfiguration2 ()
TrainingConfiguration2 (const TrainingConfiguration2 &tc)
TrainingConfiguration2 (MLClassListPtr _mlClasses, FactoryFVProducerPtr _fvFactoryProducer, const KKStr &_parameterStr, RunLog &_log)
Use this one if you want to create a default Configuration object.
TrainingConfiguration2 (MLClassListPtr _mlClasses, FileDescPtr _fileDesc, const KKStr &_parameterStr, RunLog &_log)
Use this one if you want to create a default Configuration object.
TrainingConfiguration2 (MLClassListPtr _mlClasses, FileDescPtr _fileDesc, ModelParamPtr _modelParameters, RunLog &_log)
Creates a configuration file using the parameters specified in '_modelParameters'; does not read from a configuration file.
virtual ~TrainingConfiguration2 ()
float A_Param () const
void A_Param (float _aParam)
void AddATrainingClass (TrainingClassPtr _trainClass)
Adds specified Training Class to list taking ownership of it.
void AddATrainingClass (MLClassPtr _newClass)
Will assume that images for this class will be saved off the RootDirectory using its own name for the subdirectory name.
float AvgNumOfFeatures () const
float AvgNumOfFeatures (FeatureVectorListPtr trainExamples) const
double C_Param () const
double C_Param (MLClassPtr class1, MLClassPtr class2) const
void C_Param (double _CCC)
void C_Param (MLClassPtr class1, MLClassPtr class2, double cParam)
const KKStr & ConfigFileNameSpecified () const
const KKStr & ConfigRootName () const
KKStr DirectoryPathForClass (MLClassPtr mlClass) const
Fully expanded directory path for specified class.
void EmptyTrainingClasses ()
Removes all training classes from the configuration; example use would be to remove all classes and then add the two needed by a Binary-Class-Pair classifier.
SVM_EncodingMethod EncodingMethod () const
void EncodingMethod (SVM_EncodingMethod _encodingMethod)
kkint32 ExamplesPerClass () const
void ExamplesPerClass (kkint32 _examplesPerClass)
MLClassListPtr ExtractClassList () const
Constructs new list of classes that caller will own.
MLClassListPtr ExtractFullHierachyOfClasses () const
Extracts the list of classes including ones from Sub-Classifiers.
MLClassListPtr ExtractListOfClassesForAGivenHierarchialLevel (kkuint32 level) const
virtual KKStr FactoryName () const
The name of the Factory class that produces an instance of this class.
FileDescPtr FileDesc () const
FactoryFVProducerPtr FvFactoryProducer (RunLog &log) const
bool FvFactoryProducerSpecified () const
double Gamma () const
void Gamma (double _gamma)
TrainingConfiguration2Ptr GenerateAConfiguraionForAHierarchialLevel (kkuint32 level, RunLog &log) const
BinaryClassParmsPtr GetBinaryClassParms (MLClassPtr class1, MLClassPtr class2)
if BinaryClass parms exist for the two specified classes will return otherwise NULL.
FeatureNumList GetFeatureNums () const
FeatureNumList GetFeatureNums (MLClassPtr class1, MLClassPtr class2)
Returns features selected for the specified class-pairIf none were specified for that pair will return global feature nums.
const BinaryClassParmsPtr GetParamtersToUseFor2ClassCombo (MLClassPtr class1, MLClassPtr class2) const
kkint32 ImagesPerClass () const
void ImagesPerClass (kkint32 _imagesPerClass)
SVM_KernalType KernalType () const
void KernalType (SVM_KernalType _kernalType)
FeatureVectorListPtr LoadFeatureDataFromTrainingLibraries (KKB::DateTime &latestImageTimeStamp, bool &changesMadeToTrainingLibraries, VolConstBool &cancelFlag, RunLog &log)
Load traning data from the trainig libraries.
FeatureVectorListPtr LoadOtherClasssExamples (RunLog &runLog)
TrainingClassPtr LocateByMLClassName (const KKStr &className)
SVM_MachineType MachineType () const
void MachineType (SVM_MachineType _machineType)
MLClassListPtr MlClasses () const
Model::ModelTypes ModelingMethod () const
KKStr ModelParameterCmdLine () const
ModelParamPtr ModelParameters () const
void ModelParameters (ModelParamPtr _modelParameters)
Model::ModelTypes ModelType () const
KKStr ModelTypeStr () const
MLClassPtr NoiseMLClass () const
const TrainingClassPtr NoiseTrainingClass () const
bool NormalizeNominalFeatures ()
kkint32 Number_of_rounds () const
void Number_of_rounds (kkint32 _number_of_rounds)
kkuint32 NumHierarchialLevels () const
returns back the number of hierarchical levels thereare in the trainingClass that has the most.
kkint32 NumOfFeaturesAfterEncoding (RunLog &log) const
kkint32 NumOfRounds () const
void NumOfRounds (kkint32 _numOfRounds)
MLClassPtr OtherClass () const
const KKStr & RootDir () const
The root directory where Training library images are stored.
void RootDir (const KKStr &_rootDir)
KKStr RootDirExpanded () const
virtual void Save (std::ostream &o) const
SVM_SelectionMethod SelectionMethod () const
void SelectionMethod (SVM_SelectionMethod _selectionMethod)
void SetBinaryClassFields (MLClassPtr class1, MLClassPtr class2, const SVM233::svm_parameter &_param, const FeatureNumList &_features, float _weight)
void SetFeatureNums (const FeatureNumList &features)
void SetFeatureNums (MLClassPtr class1, MLClassPtr class2, const FeatureNumList &_features, float _weight=-1)
void SetModelParameters (ModelParamPtr _svmParanters, kkint32 _examplesPerClass)
void SetTrainingClasses (TrainingClassListPtr _trainingClasses)
TrainingConfiguration2ListPtr SubClassifiers () const
const SVMparam & SVMparamREF (RunLog &log) const
const TrainingClassList & TrainingClasses () const
void WriteXML (const KKStr &varName, std::ostream &o) const
Public Member Functions inherited from KKB::Configuration
Configuration (const KKB::KKStr &_fileName, RunLog &_log)
Configuration ()
Configuration (const Configuration &c)
virtual ~Configuration ()
const KKB::KKStr & FileName () const
const VectorKKStr & FormatErrors () const
void FormatErrorsAdd (kkint32 lineNum, const KKStr &error)
void FormatErrorsClear ()
Call this to clear all format error messages.
const VectorInt & FormatErrorsLineNums () const
VectorKKStr FormatErrorsWithLineNumbers () const
bool FormatGood () const
void FormatGood (bool _formatGood)
void GetSetting (const char *sectiopnName, kkint32 settingNum, KKStrConstPtr &name, KKStrConstPtr &value, kkint32 &lineNum)
virtual void Load (const KKB::KKStr &_fileName, RunLog &_log)
void LoadFile (RunLog &log)
virtual kkint32 MemoryConsumedEstimated () const
kkint32 NumOfSections ()
kkint32 NumOfSettings (const KKB::KKStr &sectionName) const
kkint32 NumOfSettings (kkint32 sectionNum) const
Returns number of settings for the specified section,.
void PrintFormatErrors (std::ostream &o)
bool SectionDefined (const KKB::KKStr &sectionName) const
Returns true if the section is defined.
kkint32 SectionLineNum (kkint32 sectionNum) const
KKStrConstPtr SectionName (kkint32 sectionNum) const
Returns the name of the section for specified index, if index not defined will return NULL.
kkint32 SectionNum (const KKB::KKStr &sectionName) const
KKStrConstPtr SettingName (const KKB::KKStr &sectionName, kkint32 settingNum) const
KKStrConstPtr SettingName (kkint32 sectionNum, kkint32 settingNum) const
KKStrConstPtr SettingValue (const KKB::KKStr &sectionName, const KKB::KKStr &settingName, kkint32 &lineNum) const
KKStrConstPtr SettingValue (kkint32 sectionNum, const KKB::KKStr &settingName, kkint32 &lineNum) const
KKStrConstPtr SettingValue (kkint32 sectionNum, kkint32 settingNum, kkint32 &lineNum) const
KKStr SettingValueToStr (const KKB::KKStr &sectionName, const KKB::KKStr &settingName, kkint32 &lineNum) const
KKStr SettingValueToStr (kkint32 sectionNum, const KKB::KKStr &settingName, kkint32 &lineNum) const
Static Public Member Functions
static PicesTrainingConfiguration * CreateFromDirectoryStructure (const KKStr &_existingConfigFileName, const KKStr &_subDir, RunLog &_log, bool &_successful, KKStr &_errorMessage)
static PicesTrainingConfiguration * CreateFromFeatureVectorList (FeatureVectorList &_examples, RunLog &_log)
Static Public Member Functions inherited from KKMLL::TrainingConfiguration2
static bool ConfigFileExists (const KKStr &_configFileName)
static TrainingConfiguration2 * CreateFromDirectoryStructure (const KKStr &_existingConfigFileName, const KKStr &_subDir, FactoryFVProducerPtr _fvFactoryProducer, RunLog &_log, bool &_successful, KKStr &_errorMessage)
Will create a instance using a sub-directory tree to drive the TraningClassList.
static TrainingConfiguration2 * CreateFromFeatureVectorList (FeatureVectorList &_examples, FileDescPtr _fileDesc, const KKStr &_parameterStr, RunLog &_log)
static Factory * FactoryInstace ()
static KKStr GetEffectiveConfigFileName (const KKStr &configFileName)
Determine the correct csonfiguration file name.
static TrainingConfiguration2Ptr Manufacture (const KKStr &_className, const KKStr &_configFileName, bool _validateDirectories, RunLog &_log)
static ModelTypes ModelTypeFromStr (const KKStr &_modelTypeStr)
static KKStr ModelTypeToStr (ModelTypes _modelType)
static void RegisterFatory (const KKStr &className, Factory *factory)
Additional Inherited Members
Static Public Attributes inherited from KKMLL::TrainingConfiguration2
static Factory * factoryInstace = NULL
Protected Member Functions inherited from KKMLL::TrainingConfiguration2
void BuildTrainingClassListFromDirectoryStructure (const KKStr &_subDir, bool &_successful, KKStr &_errorMessage, RunLog &_log)
XmlTokenPtr ReadXMLBaseToken (XmlTokenPtr t, VolConstBool &cancelFlag, RunLog &log)
void ReadXMLPost (VolConstBool &cancelFlag, RunLog &log)
void WriteXMLFields (std::ostream &o) const
To be used by both Base Class and Derived classes to write fields that are specific to 'TrainingConfiguration2'.
Detailed Description
Definition at line 14 of file PicesTrainingConfiguration.h.
Member Typedef Documentation
typedef PicesTrainingConfiguration const MLL::PicesTrainingConfiguration::PicesTrainingConfigurationConst
Definition at line 18 of file PicesTrainingConfiguration.h.
typedef PicesTrainingConfigurationConst* MLL::PicesTrainingConfiguration::PicesTrainingConfigurationConstPtr
Definition at line 19 of file PicesTrainingConfiguration.h.
typedef PicesTrainingConfiguration* MLL::PicesTrainingConfiguration::PicesTrainingConfigurationPtr
Definition at line 17 of file PicesTrainingConfiguration.h.
Constructor & Destructor Documentation
PicesTrainingConfiguration::PicesTrainingConfiguration ()
Definition at line 36 of file PicesTrainingConfiguration.cpp.
Referenced by CreateFromDirectoryStructure(), CreateFromFeatureVectorList(), and Duplicate().
PicesTrainingConfiguration::PicesTrainingConfiguration (const TrainingConfiguration2 & tc)
Definition at line 53 of file PicesTrainingConfiguration.cpp.
PicesTrainingConfiguration::PicesTrainingConfiguration (const PicesTrainingConfiguration & tc)
Definition at line 64 of file PicesTrainingConfiguration.cpp.
PicesTrainingConfiguration::PicesTrainingConfiguration (MLClassListPtr _mlClasses, KKStr _parameterStr, RunLog & _log)
Use this one if you want to create a default Configuration object.
Definition at line 43 of file PicesTrainingConfiguration.cpp.
PicesTrainingConfiguration::~PicesTrainingConfiguration ()
Definition at line 72 of file PicesTrainingConfiguration.cpp.
Member Function Documentation
PicesTrainingConfigurationPtr PicesTrainingConfiguration::CreateFromDirectoryStructure (const KKStr & _existingConfigFileName, const KKStr & _subDir, RunLog & _log, bool & _successful, KKStr & _errorMessage) static
Definition at line 149 of file PicesTrainingConfiguration.cpp.
References KKMLL::TrainingConfiguration2::BuildTrainingClassListFromDirectoryStructure(), KKB::KKStr::Empty(), KKB::endl(), KKB::Configuration::FormatGood(), KKB::RunLog::Level(), Load(), KKB::osAddSlash(), KKB::osFileExists(), KKB::osGetRootNameOfDirectory(), PicesTrainingConfiguration(), KKMLL::TrainingConfiguration2::RootDir(), Save(), and MLL::PicesVariables::TrainingModelsConfigurationDir().
Referenced by CreateFromFeatureVectorList().
PicesTrainingConfigurationPtr PicesTrainingConfiguration::CreateFromFeatureVectorList (FeatureVectorList & _examples, RunLog & _log) static
Definition at line 121 of file PicesTrainingConfiguration.cpp.
References KKMLL::FeatureVectorList::AllFeatures(), CreateFromDirectoryStructure(), KKB::endl(), KKMLL::FeatureVectorList::ExtractListOfClasses(), KKMLL::FeatureVectorList::FileDesc(), KKB::RunLog::Level(), PicesTrainingConfiguration(), KKMLL::TrainingConfiguration2::SetFeatureNums(), and KKMLL::MLClassList::SortByName().
Referenced by Save().
FactoryFVProducerPtr PicesTrainingConfiguration::DefaultFeatureVectorProducer (RunLog & runLog) const virtual
Reimplemented from KKMLL::TrainingConfiguration2.
Definition at line 99 of file PicesTrainingConfiguration.cpp.
References MLL::PicesFVProducerFactory::Factory().
PicesTrainingConfigurationPtr PicesTrainingConfiguration::Duplicate () const virtual
Reimplemented from KKMLL::TrainingConfiguration2.
Definition at line 90 of file PicesTrainingConfiguration.cpp.
References PicesTrainingConfiguration().
void PicesTrainingConfiguration::Load (const KKStr & _configFileName, bool _validateDirectories, RunLog & _log) virtual
Parameters
_validateDirectories Used to default to 'true'.
Reimplemented from KKMLL::TrainingConfiguration2.
Definition at line 79 of file PicesTrainingConfiguration.cpp.
Referenced by PicesInterface::TrainingModel2::AddClass(), PicesInterface::TrainingModel2::AddImageToTrainingLibray(), PicesInterface::TrainingModel2::BuildNewTrainedModel(), PicesInterface::TrainingModel2::BuildTrainingModel(), CreateFromDirectoryStructure(), MLL::PicesApplication::InitalizeApplication(), PicesInterface::TrainingModel2::LoadTrainigLibrary(), PicesInterface::PicesTrainingConfigManaged::PicesTrainingConfigManaged(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void PicesTrainingConfiguration::ReadXML (XmlStream & s, XmlTagConstPtr tag, VolConstBool & cancelFlag, RunLog & log) virtual
Reimplemented from KKMLL::TrainingConfiguration2.
Definition at line 244 of file PicesTrainingConfiguration.cpp.
References KKB::XmlStream::GetNextToken(), KKMLL::TrainingConfiguration2::ReadXMLBaseToken(), KKMLL::TrainingConfiguration2::ReadXMLPost(), and KKB::XmlToken::VarName().
void PicesTrainingConfiguration::Save (const KKStr & fileName) const virtual
Reimplemented from KKMLL::TrainingConfiguration2.
Definition at line 106 of file PicesTrainingConfiguration.cpp.
References CreateFromFeatureVectorList(), and KKB::KKStr::Str().
Referenced by CreateFromDirectoryStructure(), and PicesInterface::PicesTrainingConfigManaged::Save().
void PicesTrainingConfiguration::WriteXML (const KKStr & varName, std::ostream & o) const
Definition at line 224 of file PicesTrainingConfiguration.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::endl(), KKB::XmlTag::WriteXML(), and KKMLL::TrainingConfiguration2::WriteXMLFields().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/PicesTrainingConfiguration.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/PicesTrainingConfiguration.cpp