Pices: MLL::SipperBuff4Bit Class Reference
MLL::SipperBuff4Bit Class Reference
Implements the KKLSC (Kurt Kramer Line-Scanner 4biit format).
#include <SipperBuff4Bit.h>
Classes
union OpRec
struct OpRecEndOfScanLine
struct OpRecInstrumentDataWord1
struct OpRecInstrumentDataWord2
OpCode 2.
struct OpRecInstrumentDataWord3
OpCode 2.
struct OpRecRaw1Pixel
struct OpRecRaw32Pixels
struct OpRecRaw513Pixels1
struct OpRecRaw513Pixels2
struct OpRecRun256Len1
struct OpRecRun256Len2
struct OpRecRunLen
struct OpRecTextBlock1
struct OpRecTextBlock2
struct RawPixelRec
Public Types
typedef SipperBuff4Bit * SipperBuff4BitPtr
Public Types inherited from MLL::SipperBuff
typedef KKB::kkint32 kkint32
typedef KKB::kkuint32 kkuint32
typedef SipperBuff * SipperBuffPtr
Public Member Functions
SipperBuff4Bit (InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
SipperBuff4Bit (const KKStr &_fileName, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
virtual ~SipperBuff4Bit ()
virtual SipperFileFormat FileFormat () const
bool FileFormatGood ()
virtual void GetNextLine (uchar *lineBuff, kkuint32 lineBuffSize, kkuint32 &lineSize, kkuint32 colCount[], kkuint32 &pixelsInRow, bool &flow)
kkuint32 PixelsPerScanLine () const
Public Member Functions inherited from MLL::SipperBuff
SipperBuff (InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
SipperBuff (const KKStr &_fileName, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
virtual ~SipperBuff ()
kkuint64 ByteOffset () const
kkuint32 BytesDropped () const
kkuint32 CurRow () const
kkuint64 CurRowByteOffset () const
void DetermineCropSettings (kkuint32 &cropLeft, kkuint32 &cropRght)
bool Eof () const
const KKStr & FileName () const
void InvalidLine (bool _invalidLine)
bool InvalidLine () const
virtual kkint32 LineWidth () const
Returns the width in pixels of the associated scanner file.
void Open (const KKStr &_fileName)
bool Opened () const
kkuint32 RecCount () const
void ReportInstrumentData (uchar sensorId, bool text, uchar sensorData)
void Reset ()
void ResetByteOffset (kkuint32 _byteOffset)
kkint32 ScanRate () const
void SkipOneByte ()
virtual void SkipToScanLine (kkuint32 scanLine)
virtual void SkipToScanLine (kkuint32 _scanLine, kkuint64 _byteOffset)
Static Public Member Functions
static const uchar * CompensationTable ()
Static Public Member Functions inherited from MLL::SipperBuff
static SipperBuffPtr CreateSipperBuff (SipperFileFormat _format, KKStr _fileName, kkint32 _cameraNum, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
static SipperBuffPtr CreateSipperBuff (KKStr _fileName, kkint32 _cameraNum, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
static SipperFileFormat GuessFormatOfFile (const KKStr &_fileName, kkint32 _cameraNum, RunLog &_log)
Additional Inherited Members
Protected Member Functions inherited from MLL::SipperBuff
void AssignSerialPorts (const SipperHeaderRecPtr sipperHeaderRec)
Static Protected Member Functions inherited from MLL::SipperBuff
static void DisplaySipperRec (SipperBuff::SipperRec &sr)
static SipperFileFormat GuessFormatOfNextLine (FILE *in, kkint32 _cameraNum, RunLog &_log)
Protected Attributes inherited from MLL::SipperBuff
kkuint64 byteOffset
kkuint32 bytesDropped
kkuint32 curRow
kkuint64 curRowByteOffset
bool eof
KKStr fileName
FILE * inFile
InstrumentDataManagerPtr instrumentDataManager
bool invalidLine
Set to true if invalid data is detected on a scan line.
bool iOwnInstrumentDataManager
RunLog & log
bool opened
kkuint32 recCount
Detailed Description
Implements the KKLSC (Kurt Kramer Line-Scanner 4biit format).
Coppied this code from the KKLSC library to allow the reading of 4bit scanner files.
  1) Records are or varying length.
  2) Each record starts with a 4 bit Op-Code.
  3) Records contain either Text or Imagery
  4) Imagery records can be eith Run-Length (Same Pixel repeating) or Raw-String(A sequence of pixels).
   Summary of Op-Codes:
   --------------------------------------------------------------------
   0: End-Of-Line:  Indicates that end of Scan-Line reached.
   1: Text-Block:
   2: InsrumentData
   3: Un-Used
   4: Run-Length (2 Pixels).
   5: Run-Length (3 Pixels).
   6: Run-Length (4 Pixels).
   7: Run-Length (5 Pixels).
   8: Run-Length (6 Pixels).
   9: Run-Length (7 Pixels).
  10: Run-Length (1 thru 256 Pixels).
  11: Raw-String (1 Pixel Length).
  12: Raw-String (Even length 2 thru 32).
  13: Raw-String (Odd Length 1 thru 513).
  14: Un-Used.
  15: Un-Used.
  Bits
  =====
  0 - 3:  OP-Code  (Values 0 thru 15)
----------------------------------------------------------
  Op-Code = 0   end of line
  4 - 7:  Ignore
----------------------------------------------------------
  Op-Code 1:   Test Block.
  4 -  4:  End of text block.
  5 -  7:  TextBlock Len HighEnd.
  8 - 15:  TextBlock Len LowEnd
    Text-Block-Len = HighEnd * 256 + LowEnd.
  Followed by 'Text-Block-Len' bytes.
----------------------------------------------------------
  Op-Code 2:  InstrumentData
  4 -  7:  InstrumentId
  8 - 39:  Scan-Line Number.
 40 - 71:  Instrument Data.
----------------------------------------------------------
  Op-Code = 4 thru 9:  Short-Run-Len
                       RunLen = OpCode - 2
  4 -  7: Pixel Value being repeated.
----------------------------------------------------------
 Op-Code = 10:   Run-length of range "1" thru "256"
                 Since there are no run-lengths of '0';  '0' will decode to Run-Lengrth = 1;
  4 -  7: Pixel Value being repeated.
  8 - 15: Runlen     0=1, 1=2, 2=3,... 254=255, 255=256
----------------------------------------------------------
 Op-Code = 11:   One Pixel Raw String.
  4 -  7:     PixelValue.
----------------------------------------------------------
 Op-Code = 12   Raw Pixel String of even length ranging from 2 to 32
                because each byte can fit two pixels it is best that Raw String lengths
                always be multiples of 2.
  4 -  7:     Len;   Num-Raw-Pixels = (Len + 1) * 2
              Len  0=(2 raw Pixels), 1=(4 raw pixels), 2=(6 raw pixels),,, 15=(32 raw pixles)
              Number of following bytes = (Len + 1).
----------------------------------------------------------
 Op-Code = 13  Odd number of raw pixels up to length of 513 pixels.
               We use the other 4 bits in the 1st byte to represent the high order bits of the length
               and the 1st 4 bits ibn the second byte for the low order;  that leaves room for one
               pixels in the second byte.  This is why odd length stings are supported.
   8 -  7:  LenHigh             String Length = 1 + 2 * (LenHigh * 16 + LenLow);
   8 - 11:  LenLow
  12 - 15:  First Raw Pixel.    Will be followed by ((LenHigh * 16 + LenLow) bytes with two pixels
                                in each one.
           Translation Tables
  ======================================
  4     8                              4
  Bit   Bit           8-Bit  Range   Bit
  ===   ===           ============   ===
  0       0           (  0 -  15):     0
  1      17           ( 16 -  31):     1
  2      34           ( 32 -  47):     2
  3      51           ( 48 -  63):     3
  4      68           ( 64 -  79):     4
  5      85           ( 80 -  95):     5
  6     102           ( 96 - 111):     6
  7     119           (112 - 127):     7
  8     136           (128 - 143):     8
  9     153           (144 - 159):     9
  10    170           (160 - 175):    10
  11    187           (176 - 191):    11
  12    204           (192 - 207):    12
  13    221           (208 - 223):    13
  14    238           (224 - 239):    14
  15    255           (240 - 255):    15
Definition at line 127 of file SipperBuff4Bit.h.
Member Typedef Documentation
typedef SipperBuff4Bit* MLL::SipperBuff4Bit::SipperBuff4BitPtr
Definition at line 130 of file SipperBuff4Bit.h.
Constructor & Destructor Documentation
SipperBuff4Bit::SipperBuff4Bit (InstrumentDataManagerPtr _instrumentDataManager, RunLog & _log)
Definition at line 196 of file SipperBuff4Bit.cpp.
SipperBuff4Bit::SipperBuff4Bit (const KKStr & _fileName, InstrumentDataManagerPtr _instrumentDataManager, RunLog & _log)
Definition at line 223 of file SipperBuff4Bit.cpp.
SipperBuff4Bit::~SipperBuff4Bit (void) virtual
Definition at line 289 of file SipperBuff4Bit.cpp.
References Min(), and PixelsPerScanLine().
Member Function Documentation
const uchar * SipperBuff4Bit::CompensationTable () static
Definition at line 401 of file SipperBuff4Bit.cpp.
virtual SipperFileFormat MLL::SipperBuff4Bit::FileFormat () const inline virtual
Definition at line 146 of file SipperBuff4Bit.h.
References FileFormatGood(), and MLL::sfSipper4Bit.
bool SipperBuff4Bit::FileFormatGood ()
Definition at line 426 of file SipperBuff4Bit.cpp.
References MLL::SipperBuff::curRow, KKB::endl(), MLL::SipperBuff::Eof(), MLL::SipperBuff::eof, MLL::SipperBuff4Bit::OpRecInstrumentDataWord1::idNum, MLL::SipperBuff::inFile, MLL::SipperBuff4Bit::OpRec::instrumentDataWord1, MLL::SipperBuff4Bit::OpRecRaw32Pixels::len, MLL::SipperBuff4Bit::OpRecRaw513Pixels1::lenHigh, MLL::SipperBuff4Bit::OpRecTextBlock1::lenHighBits, MLL::SipperBuff4Bit::OpRecRaw513Pixels2::lenLow, MLL::SipperBuff4Bit::OpRecTextBlock2::lenLowBits, MLL::SipperBuff4Bit::OpRecTextBlock1::opCode, MLL::SipperBuff::Opened(), MLL::SipperBuff4Bit::OpRecRaw513Pixels2::pix0, MLL::SipperBuff4Bit::RawPixelRec::pix0, MLL::SipperBuff4Bit::RawPixelRec::pix1, MLL::SipperBuff4Bit::OpRecRunLen::pixelValue, MLL::SipperBuff4Bit::OpRecRun256Len1::pixelValue, MLL::SipperBuff4Bit::OpRecRaw1Pixel::pixelValue, MLL::SipperBuff4Bit::OpRec::raw1Pixel, MLL::SipperBuff4Bit::OpRec::raw32Pixels, MLL::SipperBuff4Bit::OpRec::raw513Pixels1, MLL::SipperBuff4Bit::OpRec::raw513Pixels2, MLL::SipperBuff4Bit::OpRec::run256Len1, MLL::SipperBuff4Bit::OpRec::run256Len2, MLL::SipperBuff4Bit::OpRecRun256Len2::runLen, MLL::SipperBuff4Bit::OpRec::runLen, MLL::SipperBuff4Bit::OpRec::textBlock1, MLL::SipperBuff4Bit::OpRec::textBlock2, and MLL::SipperBuff4Bit::OpRec::textChar.
Referenced by FileFormat(), and MLL::SipperBuff::GuessFormatOfFile().
void SipperBuff4Bit::GetNextLine (uchar * lineBuff, kkuint32 lineBuffSize, kkuint32 & lineSize, kkuint32 colCount[], kkuint32 & pixelsInRow, bool & flow) virtual
Implements MLL::SipperBuff.
Definition at line 706 of file SipperBuff4Bit.cpp.
Referenced by PixelsPerScanLine().
kkuint32 MLL::SipperBuff4Bit::PixelsPerScanLine () const inline
Definition at line 151 of file SipperBuff4Bit.h.
References GetNextLine().
Referenced by ~SipperBuff4Bit().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/SipperBuff4Bit.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/SipperBuff4Bit.cpp