Pices: MLL::DataBaseImage Class Reference
MLL::DataBaseImage Class Reference
#include <DataBaseImage.h>
Public Types
typedef DataBaseImage * DataBaseImagePtr
typedef KKB::kkint32 kkint32
typedef KKB::kkuint32 kkuint32
typedef KKB::uchar uchar
typedef KKB::ulong ulong
Public Member Functions
DataBaseImage ()
~DataBaseImage ()
float BreakTie () const
osFilePos ByteOffset () const
void ByteOffset (osFilePos _byteOffset)
kkuint32 CentroidCol () const
void CentroidCol (kkuint32 _centroidCol)
kkuint32 CentroidRow () const
void CentroidRow (kkuint32 _centroidRow)
MLClassPtr Class1 () const
void Class1 (MLClassPtr _class1)
const KKStr & Class1Name () const
void Class1Name (const char *_class1Name)
float Class1Prob () const
void Class1Prob (float _class1Prob)
MLClassPtr Class2 () const
void Class2 (MLClassPtr _class2)
const KKStr & Class2Name () const
void Class2Name (const char *_class2Name)
float Class2Prob () const
void Class2Prob (float _class2Prob)
kkuint32 ClassLogEntryId () const
void ClassLogEntryId (kkuint32 _classLogEntryId)
uchar ConnectedPixelDist () const
void ConnectedPixelDist (uchar _connectedPixelDist)
float Depth () const
void Depth (float _depth)
const uchar * EncodedThumbnail () const
void EncodedThumbnail (uchar *_encodedThumbnail)
kkuint32 EncodedThumbnailLen () const
void EncodedThumbnailLen (kkuint32 _encodedThumbnailLen)
kkuint32 ExtractionLogEntryId () const
void ExtractionLogEntryId (kkuint32 _extractionLogEntryId)
RasterSipperPtr GetOrigImageFromSipperFile (RunLog &log) const
Will go to the original Sipper file and extract the image.
kkuint32 Height () const
void Height (kkuint32 _height)
KKStr ImageFileName () const
void ImageFileName (const KKStr &_imageFileName)
kkint32 ImageId () const
void ImageId (kkint32 _imageId)
float ImageSize () const
void ImageSize (float _imageSize)
kkuint32 PixelCount () const
void PixelCount (kkuint32 _pixelCount)
kkint32 SipperFileId () const
void SipperFileId (kkint32 _sipperFileId)
const KKStr & SipperFileName () const
void SipperFileName (const KKStr &_sipperFileName)
PointListPtr SizeCoordinates () const
void SizeCoordinates (PointListPtr _sizeCoordinates)
Giving ownership of '_sizeCoordinates' to this instance of 'DataBaseImage'.
void SizeCoordinates (const KKStr _sizeCoordinatesStr)
Giving ownership of '_sizeCoordinates' to this instance of 'DataBaseImage'.
void SizeCoordinatesAdd (const KKB::Point &_point)
Adds additional point to end of 'SizeCoordinates' list.
RasterSipperPtr ThumbNail (RunLog &log) const
kkuint32 TopLeftCol () const
void TopLeftCol (kkuint32 _topLeftCol)
kkuint32 TopLeftRow () const
void TopLeftRow (kkuint32 _topLeftRow)
MLClassPtr ValidatedClass () const
void ValidatedClass (MLClassPtr _validatedClass)
const KKStr & ValidatedClassName () const
void ValidatedClassName (const char *_validatedClassName)
kkuint32 Width () const
void Width (kkuint32 _width)
Detailed Description
Used for returning results of Queries against the Images table in the Pices database (See *
DataBase::ImagesQuery).                                                                    *
Definition at line 43 of file DataBaseImage.h.
Member Typedef Documentation
typedef DataBaseImage* MLL::DataBaseImage::DataBaseImagePtr
Definition at line 46 of file DataBaseImage.h.
typedef KKB::kkint32 MLL::DataBaseImage::kkint32
Definition at line 48 of file DataBaseImage.h.
typedef KKB::kkuint32 MLL::DataBaseImage::kkuint32
Definition at line 49 of file DataBaseImage.h.
typedef KKB::uchar MLL::DataBaseImage::uchar
Definition at line 51 of file DataBaseImage.h.
typedef KKB::ulong MLL::DataBaseImage::ulong
Definition at line 50 of file DataBaseImage.h.
Constructor & Destructor Documentation
DataBaseImage::DataBaseImage ()
Definition at line 33 of file DataBaseImage.cpp.
DataBaseImage::~DataBaseImage ()
Definition at line 63 of file DataBaseImage.cpp.
Member Function Documentation
float DataBaseImage::BreakTie () const
Definition at line 71 of file DataBaseImage.cpp.
Referenced by PicesInterface::PicesDataBaseImage::CompareBreakTie().
osFilePos MLL::DataBaseImage::ByteOffset () const inline
Definition at line 57 of file DataBaseImage.h.
Referenced by MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageUpdate(), and ImageExtractionManager::DataBaseUpdateThread::Run().
void MLL::DataBaseImage::ByteOffset (osFilePos _byteOffset) inline
Definition at line 90 of file DataBaseImage.h.
kkuint32 MLL::DataBaseImage::CentroidCol () const inline
Definition at line 58 of file DataBaseImage.h.
Referenced by MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageUpdate(), and ImageExtractionManager::DataBaseUpdateThread::Run().
void MLL::DataBaseImage::CentroidCol (kkuint32 _centroidCol) inline
Definition at line 91 of file DataBaseImage.h.
kkuint32 MLL::DataBaseImage::CentroidRow () const inline
Definition at line 59 of file DataBaseImage.h.
Referenced by MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageUpdate(), and ImageExtractionManager::DataBaseUpdateThread::Run().
void MLL::DataBaseImage::CentroidRow (kkuint32 _centroidRow) inline
Definition at line 92 of file DataBaseImage.h.
MLClassPtr MLL::DataBaseImage::Class1 () const inline
Definition at line 60 of file DataBaseImage.h.
Referenced by MLL::DataBaseImageList::ExtractExamplesForAGivenClass(), MLL::DataBaseImageList::ExtractListOfClasses(), and MLL::DataBase::ImageGetDepthStatistics().
void MLL::DataBaseImage::Class1 (MLClassPtr _class1) inline
Definition at line 93 of file DataBaseImage.h.
const KKStr & DataBaseImage::Class1Name () const
Definition at line 82 of file DataBaseImage.cpp.
Referenced by MLL::DataBase::ImageUpdate(), and PicesInterface::PicesDataBaseImage::Thumbnail().
void DataBaseImage::Class1Name (const char * _class1Name)
Definition at line 102 of file DataBaseImage.cpp.
float MLL::DataBaseImage::Class1Prob () const inline
Definition at line 62 of file DataBaseImage.h.
Referenced by MLL::DataBase::ImageGetDepthStatistics(), and MLL::DataBase::ImageUpdate().
void MLL::DataBaseImage::Class1Prob (float _class1Prob) inline
Definition at line 95 of file DataBaseImage.h.
MLClassPtr MLL::DataBaseImage::Class2 () const inline
Definition at line 63 of file DataBaseImage.h.
Referenced by MLL::DataBase::ImageGetDepthStatistics().
void MLL::DataBaseImage::Class2 (MLClassPtr _class2) inline
Definition at line 96 of file DataBaseImage.h.
const KKStr & DataBaseImage::Class2Name () const
Definition at line 92 of file DataBaseImage.cpp.
Referenced by PicesInterface::PicesDataBaseImage::CompareClass2(), MLL::DataBase::ImageUpdate(), and PicesInterface::PicesDataBaseImage::Thumbnail().
void DataBaseImage::Class2Name (const char * _class2Name)
Definition at line 117 of file DataBaseImage.cpp.
float MLL::DataBaseImage::Class2Prob () const inline
Definition at line 65 of file DataBaseImage.h.
Referenced by PicesInterface::PicesDataBaseImage::CompareClass2(), MLL::DataBase::ImageGetDepthStatistics(), and MLL::DataBase::ImageUpdate().
void MLL::DataBaseImage::Class2Prob (float _class2Prob) inline
Definition at line 98 of file DataBaseImage.h.
kkuint32 MLL::DataBaseImage::ClassLogEntryId () const inline
Definition at line 66 of file DataBaseImage.h.
Referenced by MLL::DataBase::ImageGetDepthStatistics(), and MLL::DataBase::ImageUpdate().
void MLL::DataBaseImage::ClassLogEntryId (kkuint32 _classLogEntryId) inline
Definition at line 99 of file DataBaseImage.h.
uchar MLL::DataBaseImage::ConnectedPixelDist () const inline
Definition at line 67 of file DataBaseImage.h.
Referenced by MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageUpdate(), and ImageExtractionManager::DataBaseUpdateThread::Run().
void MLL::DataBaseImage::ConnectedPixelDist (uchar _connectedPixelDist) inline
Definition at line 100 of file DataBaseImage.h.
float MLL::DataBaseImage::Depth () const inline
Definition at line 68 of file DataBaseImage.h.
Referenced by PicesInterface::PicesDataBaseImage::CompareDepth(), MLL::DataBase::ImageGetDepthStatistics(), and MLL::DataBase::ImageUpdate().
void MLL::DataBaseImage::Depth (float _depth) inline
Definition at line 101 of file DataBaseImage.h.
const uchar* MLL::DataBaseImage::EncodedThumbnail () const inline
Definition at line 69 of file DataBaseImage.h.
Referenced by MLL::DataBase::ImageGetDepthStatistics(), and PicesInterface::PicesDataBaseImage::Thumbnail().
void MLL::DataBaseImage::EncodedThumbnail (uchar * _encodedThumbnail) inline
Definition at line 102 of file DataBaseImage.h.
kkuint32 MLL::DataBaseImage::EncodedThumbnailLen () const inline
Definition at line 70 of file DataBaseImage.h.
Referenced by MLL::DataBase::ImageGetDepthStatistics(), and PicesInterface::PicesDataBaseImage::Thumbnail().
void MLL::DataBaseImage::EncodedThumbnailLen (kkuint32 _encodedThumbnailLen) inline
Definition at line 103 of file DataBaseImage.h.
kkuint32 MLL::DataBaseImage::ExtractionLogEntryId () const inline
Definition at line 71 of file DataBaseImage.h.
Referenced by MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageUpdate(), and ImageExtractionManager::DataBaseUpdateThread::Run().
void MLL::DataBaseImage::ExtractionLogEntryId (kkuint32 _extractionLogEntryId) inline
Definition at line 104 of file DataBaseImage.h.
RasterSipperPtr DataBaseImage::GetOrigImageFromSipperFile (RunLog & log) const
Will go to the original Sipper file and extract the image.
Definition at line 207 of file DataBaseImage.cpp.
References MLL::InstrumentDataFileManager::GetOrigSipperImage(), and KKB::osGetRootName().
Referenced by PicesInterface::PicesDataBaseImage::GetImageFromSipperFile(), and MLL::DataBase::ImageFullSizeFind().
kkuint32 MLL::DataBaseImage::Height () const inline
Definition at line 72 of file DataBaseImage.h.
Referenced by MLL::DataBase::ImageFullSizeFind(), MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageUpdate(), and ImageExtractionManager::DataBaseUpdateThread::Run().
void MLL::DataBaseImage::Height (kkuint32 _height) inline
Definition at line 105 of file DataBaseImage.h.
KKStr MLL::DataBaseImage::ImageFileName () const inline
Definition at line 73 of file DataBaseImage.h.
Referenced by MLL::DataBaseImageList::CalculateDensitesByQuadrat(), PicesInterface::PicesDataBaseImage::CompareSpatially(), MLL::DataBase::FeatureDataRecLoad(), MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageUpdate(), and PicesInterface::PicesDataBaseImage::Thumbnail().
void MLL::DataBaseImage::ImageFileName (const KKStr & _imageFileName) inline
Definition at line 106 of file DataBaseImage.h.
kkint32 MLL::DataBaseImage::ImageId () const inline
Definition at line 74 of file DataBaseImage.h.
Referenced by MLL::DataBase::FeatureDataUpdate(), MLL::DataBase::ImageGetDepthStatistics(), and MLL::DataBase::ImageUpdate().
void MLL::DataBaseImage::ImageId (kkint32 _imageId) inline
Definition at line 107 of file DataBaseImage.h.
float MLL::DataBaseImage::ImageSize () const inline
Definition at line 75 of file DataBaseImage.h.
Referenced by PicesInterface::PicesDataBaseImage::!PicesDataBaseImage(), and MLL::DataBase::ImageGetDepthStatistics().
void MLL::DataBaseImage::ImageSize (float _imageSize) inline
Definition at line 108 of file DataBaseImage.h.
kkuint32 MLL::DataBaseImage::PixelCount () const inline
Definition at line 76 of file DataBaseImage.h.
Referenced by MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageUpdate(), and ImageExtractionManager::DataBaseUpdateThread::Run().
void MLL::DataBaseImage::PixelCount (kkuint32 _pixelCount) inline
Definition at line 109 of file DataBaseImage.h.
kkint32 MLL::DataBaseImage::SipperFileId () const inline
Definition at line 77 of file DataBaseImage.h.
void MLL::DataBaseImage::SipperFileId (kkint32 _sipperFileId) inline
Definition at line 110 of file DataBaseImage.h.
const KKStr& MLL::DataBaseImage::SipperFileName () const inline
Definition at line 78 of file DataBaseImage.h.
Referenced by MLL::DataBaseImageList::CalculateDensitesByQuadrat(), MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageUpdate(), and MLL::DataBaseImageList::SpatialComparison::operator()().
void MLL::DataBaseImage::SipperFileName (const KKStr & _sipperFileName) inline
Definition at line 111 of file DataBaseImage.h.
PointListPtr MLL::DataBaseImage::SizeCoordinates () const inline
Definition at line 79 of file DataBaseImage.h.
Referenced by PicesInterface::PicesDataBaseImage::!PicesDataBaseImage(), and MLL::DataBase::ImageGetDepthStatistics().
void DataBaseImage::SizeCoordinates (PointListPtr _sizeCoordinates)
Giving ownership of '_sizeCoordinates' to this instance of 'DataBaseImage'.
Definition at line 158 of file DataBaseImage.cpp.
void DataBaseImage::SizeCoordinates (const KKStr _sizeCoordinatesStr)
Giving ownership of '_sizeCoordinates' to this instance of 'DataBaseImage'.
Definition at line 165 of file DataBaseImage.cpp.
References KKB::KKStr::Empty(), KKB::KKQueue< Entry >::PushOnBack(), and KKB::KKStr::Split().
void DataBaseImage::SizeCoordinatesAdd (const KKB::Point & _point)
Adds additional point to end of 'SizeCoordinates' list.
Definition at line 187 of file DataBaseImage.cpp.
References KKB::KKQueue< Entry >::PushOnBack().
RasterSipperPtr DataBaseImage::ThumbNail (RunLog & log) const
Definition at line 197 of file DataBaseImage.cpp.
References MLL::RasterSipper::FromSimpleCompression().
Referenced by MLL::DataBase::ImageFullSizeFind().
kkuint32 MLL::DataBaseImage::TopLeftCol () const inline
Definition at line 82 of file DataBaseImage.h.
Referenced by MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageUpdate(), and ImageExtractionManager::DataBaseUpdateThread::Run().
void MLL::DataBaseImage::TopLeftCol (kkuint32 _topLeftCol) inline
Definition at line 116 of file DataBaseImage.h.
kkuint32 MLL::DataBaseImage::TopLeftRow () const inline
Definition at line 81 of file DataBaseImage.h.
Referenced by MLL::DataBaseImageList::CalculateDensitesByQuadrat(), MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageUpdate(), MLL::DataBaseImageList::SpatialComparison::operator()(), and ImageExtractionManager::DataBaseUpdateThread::Run().
void MLL::DataBaseImage::TopLeftRow (kkuint32 _topLeftRow) inline
Definition at line 115 of file DataBaseImage.h.
MLClassPtr MLL::DataBaseImage::ValidatedClass () const inline
Definition at line 83 of file DataBaseImage.h.
Referenced by PicesInterface::PicesDataBaseImage::CompareClass2(), MLL::DataBaseImageList::ExtractExamplesForAGivenClass(), MLL::DataBaseImageList::ExtractListOfClasses(), MLL::DataBase::ImageGetDepthStatistics(), and PicesInterface::PicesDataBaseImage::Thumbnail().
void MLL::DataBaseImage::ValidatedClass (MLClassPtr _validatedClass) inline
Definition at line 117 of file DataBaseImage.h.
const KKStr & DataBaseImage::ValidatedClassName () const
Definition at line 131 of file DataBaseImage.cpp.
Referenced by MLL::DataBase::ImageUpdate(), and PicesInterface::PicesDataBaseImage::Thumbnail().
void DataBaseImage::ValidatedClassName (const char * _validatedClassName)
Definition at line 141 of file DataBaseImage.cpp.
kkuint32 MLL::DataBaseImage::Width () const inline
Definition at line 85 of file DataBaseImage.h.
Referenced by MLL::DataBase::ImageFullSizeFind(), MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageUpdate(), and ImageExtractionManager::DataBaseUpdateThread::Run().
void MLL::DataBaseImage::Width (kkuint32 _width) inline
Definition at line 119 of file DataBaseImage.h.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/DataBaseImage.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/DataBaseImage.cpp