Pices: SVM289_BFS::Solver_NU Class Reference
SVM289_BFS::Solver_NU Class Reference
Public Member Functions
Solver_NU ()
void Solve (kkint32 l, QMatrix &Q, const double *p, const schar *y, double *alpha, double Cp, double Cn, double eps, SolutionInfo *si, kkint32 shrinking)
Public Member Functions inherited from SVM289_BFS::Solver
Solver ()
virtual ~Solver ()
void Solve (kkint32 l, QMatrix &Q, const double *p_, const schar *y_, double *alpha_, double Cp, double Cn, double eps, SolutionInfo *si, kkint32 shrinking)
Additional Inherited Members
Protected Types inherited from SVM289_BFS::Solver
enum { LOWER_BOUND, UPPER_BOUND, FREE }
Protected Member Functions inherited from SVM289_BFS::Solver
double get_C (kkint32 i)
bool is_free (kkint32 i)
bool is_lower_bound (kkint32 i)
bool is_upper_bound (kkint32 i)
void reconstruct_gradient ()
void swap_index (kkint32 i, kkint32 j)
void update_alpha_status (kkint32 i)
Protected Attributes inherited from SVM289_BFS::Solver
kkint32 * active_set
kkint32 active_size
double * alpha
char * alpha_status
double Cn
double Cp
double eps
double * G
double * G_bar
kkint32 l
double * p
QMatrix * Q
const Qfloat * QD
bool unshrink
schar * y
Detailed Description
Definition at line 1890 of file svm289_BFS.cpp.
Constructor & Destructor Documentation
SVM289_BFS::Solver_NU::Solver_NU () inline
Definition at line 1893 of file svm289_BFS.cpp.
Member Function Documentation
void SVM289_BFS::Solver_NU::Solve (kkint32 l, QMatrix & Q, const double * p, const schar * y, double * alpha, double Cp, double Cn, double eps, SolutionInfo * si, kkint32 shrinking) inline
Definition at line 1895 of file svm289_BFS.cpp.
References SVM289_BFS::Solver::Solve().
Referenced by SVM289_BFS::solve_nu_svc(), and solve_nu_svr().
The documentation for this class was generated from the following file:
C:/Users/kurtk_000/GitHub/KSquareLibraries/KKMachineLearning/svm289_BFS.cpp