Pices: ImageExtractionManager::LogicalFrame Class Reference
ImageExtractionManager::LogicalFrame Class Reference
The Image extraction procedure will contain several threads perform various functions.
#include <LogicalFrame.h>
Public Member Functions
LogicalFrame (const ExtractionParms &_parms, kkuint32 _frameHeightMax, kkuint32 _frameWidth, const bool &_cancelFlag)
~LogicalFrame ()
kkuint32 FrameHeight () const
kkuint32 FrameNum () const
kkuint32 ImagesInFrame () const
kkint32 MemoryConsumedEstimated () const
void PopulateFrame (kkuint32 _frameNum, kkuint32 _frameHeight, uchar *_frameArea, kkuint32 _frameSipperRow, kkuint64 *_frameRowByteOffset, kkuint32 *_pixelsPerRow)
ExtractedImageListPtr ProcessFrame ()
Detailed Description
The Image extraction procedure will contain several threads perform various functions.
This will be the base class for each one of the different types of processing that Sipper Image processing will be done. Some of threads will Extract logical frames from Sipper files,
Definition at line 20 of file LogicalFrame.h.
Constructor & Destructor Documentation
LogicalFrame::LogicalFrame (const ExtractionParms & _parms, kkuint32 _frameHeightMax, kkuint32 _frameWidth, const bool & _cancelFlag)
Definition at line 124 of file LogicalFrame.cpp.
References ImageExtractionManager::ExtractionParms::FileFormat(), and MLL::sfSipper4Bit.
LogicalFrame::~LogicalFrame ()
Definition at line 177 of file LogicalFrame.cpp.
Member Function Documentation
kkuint32 ImageExtractionManager::LogicalFrame::FrameHeight () const inline
Definition at line 33 of file LogicalFrame.h.
Referenced by ImageExtractionManager::FrameProcessorThread::GetRunTimeStats().
kkuint32 ImageExtractionManager::LogicalFrame::FrameNum () const inline
Definition at line 34 of file LogicalFrame.h.
kkuint32 ImageExtractionManager::LogicalFrame::ImagesInFrame () const inline
Definition at line 35 of file LogicalFrame.h.
References PopulateFrame(), and ProcessFrame().
Referenced by ImageExtractionManager::FrameProcessorThread::GetRunTimeStats().
kkint32 LogicalFrame::MemoryConsumedEstimated () const
Definition at line 183 of file LogicalFrame.cpp.
References ImageExtractionManager::LogicalFrameBlob::AddNeighbor(), ImageExtractionManager::LogicalFrameBlob::colLeft, ImageExtractionManager::LogicalFrameBlob::colRight, KKB::KKStr::Empty(), KKB::endl(), ImageExtractionManager::SipperImage::Explore(), ImageExtractionManager::LogicalFrameBlob::Explored(), ImageExtractionManager::LogicalFrameBlob::explored, KKB::KKStr::ExtractToken(), ImageExtractionManager::SipperImage::Height(), ImageExtractionManager::LogicalFrameBlob::id, KKB::Max(), ImageExtractionManager::ExtractionParms::MaxImageSize(), KKB::Min(), ImageExtractionManager::ExtractionParms::MinImageSize(), ImageExtractionManager::ExtractionParms::MorphOperations(), ImageExtractionManager::LogicalFrameBlob::neighborIdLastAdded, ImageExtractionManager::LogicalFrameBlob::neighbors, ImageExtractionManager::SipperImage::PixelCount(), ImageExtractionManager::LogicalFrameBlob::pixelCount, ImageExtractionManager::ExtractionParms::PreProcess(), ImageExtractionManager::LogicalFrameBlob::rowBot, ImageExtractionManager::LogicalFrameBlob::rowTop, KKB::KKStr::Upper(), and ImageExtractionManager::SipperImage::Width().
Referenced by ImageExtractionManager::LogicalFrameQueue::MemoryConsumedEstimated().
void LogicalFrame::PopulateFrame (kkuint32 _frameNum, kkuint32 _frameHeight, uchar * _frameArea, kkuint32 _frameSipperRow, kkuint64 * _frameRowByteOffset, kkuint32 * _pixelsPerRow)
Definition at line 1135 of file LogicalFrame.cpp.
Referenced by ImagesInFrame(), and ImageExtractionManager::FrameExtractorThread::Run().
ExtractedImageListPtr LogicalFrame::ProcessFrame ()
Definition at line 1014 of file LogicalFrame.cpp.
References ImageExtractionManager::SipperImage::ByteOffset(), ImageExtractionManager::SipperImage::ColLeft(), ImageExtractionManager::SipperImage::ColRight(), ImageExtractionManager::SipperImage::Dialate(), ImageExtractionManager::ExtractionParms::FileFormat(), ImageExtractionManager::SipperImage::GetRaster(), ImageExtractionManager::SipperImage::PixelCount(), KKB::KKQueue< Entry >::PushOnBack(), ImageExtractionManager::SipperImage::RowBot(), ImageExtractionManager::SipperImage::RowTop(), and MLL::sfSipper4Bit.
Referenced by ImageExtractionManager::FrameProcessorThread::GetRunTimeStats(), and ImagesInFrame().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/ImageExtractionManager/LogicalFrame.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/ImageExtractionManager/LogicalFrame.cpp