Pices: PicesInterface::TrainingModel2 Class Reference
PicesInterface::TrainingModel2 Class Reference
#include <TrainingModel2.h>
Public Types
enum ModelTypes : int {
ModelTypes::Null = KKMLL::Model::ModelTypes::Null, ModelTypes::OldSVM = KKMLL::Model::ModelTypes::OldSVM, ModelTypes::SvmBase = KKMLL::Model::ModelTypes::SvmBase, ModelTypes::KNN = KKMLL::Model::ModelTypes::KNN,
ModelTypes::UsfCasCor = KKMLL::Model::ModelTypes::UsfCasCor, ModelTypes::Dual = KKMLL::Model::ModelTypes::Dual
}
Public Member Functions
TrainingModel2 (PicesRunLog^ _picesRunLog, System::String^ _modelName)
TrainingModel2 (PicesRunLog^ _picesRunLog, System::IO::DirectoryInfo^ _directoryInfo)
Builds a configuration using the directory structure pointed to by _directoryInfo .
TrainingModel2 (PicesRunLog^ _picesRunLog, PicesTrainingConfigManaged^ _config)
Constructor that utilizes _config .
TrainingModel2 (PicesRunLog^ _picesRunLog, TrainingProcess2Ptr _trainer)
Creates an instance to be used with an already existing instance of 'TrainingProcess2'.
void AddClass (PicesClass^ newClass)
void AddImageToTrainingLibray (String^ imageFileName, PicesRaster^ raster, PicesClass^ mlClass, bool onLine)
void AttachMsgQueueToRunLog (PicesMsgQueue^ msgQueue)
PicesPredictionList^ BinaryProbailitiesForClass (PicesClass^ leftClass)
void BuildNewTrainedModel ()
void BuildTrainingModel (PicesFeatureVectorList^ picesTrainingData)
summary> Sets the 'cancelFlag' to true; the load and training processes monitor this flag; if goes true process will exit at earliest convenience.
void CancelLoad ()
summary> Returns a duplicate list of classes that belong to this model; since a duplicated list caller can modify without impacting this TrainingModel.
void CleanUp ()
TrainingModel2^ CreateTrainingModelLeft ()
summary> When using a Dual classifier will return an instance of the second/right classifier.
TrainingModel2^ CreateTrainingModelRight ()
String^ DirectoryPathForClass (PicesClass^ mlClass)
Fully expanded directory path for specified class.
array< PicesInterface::ProbNamePair^ >^ FindWorstSupportVectors (PicesFeatureVector^ picesFeatureVector, int numToFind, PicesClass^ c1, PicesClass^ c2)
array< PicesInterface::ProbNamePair^ >^ FindWorstSupportVectors2 (PicesFeatureVector^ picesFeatureVector, int numToFind, PicesClass^ c1, PicesClass^ c2)
bool IncludesClass (PicesClass^ mlClass)
String^ LastRunLogTextLine ()
void LoadExistingModelOtherwiseBuild (PicesMsgQueue^ msgQueue)
Will attach message queue to runLog.
void LoadExistingTrainedModel ()
void LoadTrainigLibrary (bool forceRebuild)
void LoadTrainingModelForGivenLevel (uint level, PicesMsgQueue^ msgQueue)
PicesClassList^ MLClasses ()
PicesPrediction^ PredictClass (PicesFeatureVector^ example)
void PredictClass (PicesFeatureVector^ featureVector, PicesPrediction^ prediction1, PicesPrediction^ prediction2)
void PredictClass (System::String^ imageFileName, System::Array^ raster, System::Single^ depth, System::Single^ salinity, System::Single^ oxygen, System::Single^ florences, PicesPrediction^ prediction1, PicesPrediction^ prediction2)
summary> This call assumes that there was a successful call to PredictProbabilities before.
PicesPredictionList^ PredictProbabilities (System::String^ imageFileName, System::Array^ raster, System::Single^ depth, System::Single^ salinity, System::Single^ oxygen, System::Single^ florences)
PicesPredictionList^ PredictProbabilities (System::String^ imageFileName, PicesRasterList^ saveCalcImages)
PicesPredictionList^ PredictProbabilities (PicesFeatureVector^ picesFeatureVector)
void ProbabilitiesByClassDual (PicesFeatureVector^ picesFeatureVector, String^ %classifier1Desc, String^ %classifier2Desc, PicesPredictionList^ %classifier1Results, PicesPredictionList^ %classifier2Results)
void SaveConfiguration ()
array< String^ >^ SupportVectorNames (PicesClass^ c1, PicesClass^ c2)
Returns the names of the training examples that became support vectors in the binary classifier that was built for the class pair c1 and c2 .
Static Public Member Functions
static array< String^ >^ GetListOfTrainingModels ()
Protected Member Functions
!TrainingModel2 ()
Properties
System::DateTime BuildDateTime [get]
bool CancelFlag [get]
String^ ConfigFileName [get]
List< String^ >^ ErrorMsgs [get]
int ImagesPerClass [get]
String^ ModelName [get]
ModelTypes ModelType [get]
uint NumHierarchialLevels [get]
PicesClass^ OtherClass [get]
String^ ParameterStr [get]
String^ RootDir [get]
String^ RunLogFileName [get]
bool Valid [get]
summary> When using a Dual classifier will return an instance of the first/left classifier.
Detailed Description
Definition at line 51 of file TrainingModel2.h.
Member Enumeration Documentation
enum PicesInterface::TrainingModel2::ModelTypes : int strong
Enumerator
Null
OldSVM
SvmBase
KNN
UsfCasCor
Dual
Definition at line 54 of file TrainingModel2.h.
Constructor & Destructor Documentation
PicesInterface::TrainingModel2::TrainingModel2 (PicesRunLog^ _picesRunLog, System::String^ _modelName)
Definition at line 57 of file TrainingModel2.cpp.
References KKB::osRunAsABackGroundProcess().
Referenced by CreateTrainingModelLeft(), CreateTrainingModelRight(), and TrainingModel2().
PicesInterface::TrainingModel2::TrainingModel2 (PicesRunLog^ _picesRunLog, System::IO::DirectoryInfo^ _directoryInfo)
Builds a configuration using the directory structure pointed to by _directoryInfo .
Searches through the directory structure recursively using the directory names to define class names.
Parameters
_picesRunLog The pices run log.
_directoryInfo Root to subdirectory that contains training images with each child directory containing examples for a specific class.
Definition at line 146 of file TrainingModel2.cpp.
References KKMLL::TrainingConfiguration2::ExtractClassList(), PicesInterface::PicesKKStr::KKStrToSystenStr(), KKB::osAddSlash(), KKB::osGetRootNameOfDirectory(), KKB::osRunAsABackGroundProcess(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
PicesInterface::TrainingModel2::TrainingModel2 (PicesRunLog^ _picesRunLog, PicesTrainingConfigManaged^ _config)
Constructor that utilizes _config .
Parameters
_picesRunLog The pices run log.
_config The configuration.
Definition at line 101 of file TrainingModel2.cpp.
References PicesInterface::PicesTrainingConfigManaged::Config(), and KKB::osRunAsABackGroundProcess().
PicesInterface::TrainingModel2::TrainingModel2 (PicesRunLog^ _picesRunLog, TrainingProcess2Ptr _trainer)
Creates an instance to be used with an already existing instance of 'TrainingProcess2'.
I created this to get a break down of a prediction on a Dual class classifier.
Parameters
_picesRunLog The pices run log.
_trainer The trainer.
Definition at line 228 of file TrainingModel2.cpp.
References KKMLL::TrainingProcess2::Abort(), KKMLL::TrainingProcess2::Config(), KKB::Configuration::FileName(), PicesInterface::PicesKKStr::KKStrToSystenStr(), KKMLL::TrainingProcess2::MLClasses(), KKB::osGetRootName(), KKB::osRunAsABackGroundProcess(), and TrainingModel2().
PicesInterface::TrainingModel2::!TrainingModel2 () protected
Definition at line 296 of file TrainingModel2.cpp.
Member Function Documentation
void PicesInterface::TrainingModel2::AddClass (PicesClass^ newClass)
Definition at line 1792 of file TrainingModel2.cpp.
References KKMLL::TrainingConfiguration2::AddATrainingClass(), KKMLL::TrainingConfiguration2::DirectoryPathForClass(), KKB::KKStr::Empty(), MLL::PicesTrainingConfiguration::Load(), KKB::osAddSlash(), KKB::osCreateDirectoryPath(), KKMLL::TrainingConfiguration2::RootDir(), PicesInterface::PicesKKStr::SystemStringToKKStr(), and PicesInterface::PicesClass::UnmanagedMLClass().
Referenced by AddImageToTrainingLibray().
void PicesInterface::TrainingModel2::AddImageToTrainingLibray (String^ imageFileName, PicesRaster^ raster, PicesClass^ mlClass, bool onLine)
Definition at line 1825 of file TrainingModel2.cpp.
References AddClass(), KKMLL::TrainingProcess2::Config(), KKB::KKStr::Empty(), IncludesClass(), PicesInterface::PicesKKStr::KKStrToSystenStr(), MLL::PicesTrainingConfiguration::Load(), ModelName, PicesInterface::PicesClass::Name, KKB::osAddSlash(), KKB::osFileExists(), KKB::osGetRootName(), KKB::osValidDirectory(), SaveConfiguration(), KKB::SaveImageGrayscaleInverted8Bit(), PicesInterface::PicesKKStr::SystemStringToKKStr(), PicesInterface::PicesRaster::UnmanagedClass(), and PicesInterface::PicesClass::UnmanagedMLClass().
Referenced by SipperFile.ImageViewer::ImageViewer().
void PicesInterface::TrainingModel2::AttachMsgQueueToRunLog (PicesMsgQueue^ msgQueue)
Definition at line 433 of file TrainingModel2.cpp.
References PicesInterface::OSservices::AddSlash(), KKB::RunLog::AttachMsgQueue(), PicesInterface::OSservices::CreateDirectoryPath(), PicesInterface::OSservices::GetRootName(), PicesInterface::PicesMsgQueue::MsgQueue(), PicesInterface::PicesKKStr::SystemStringToKKStr(), and PicesInterface::PicesSipperVariables::TempDirectory().
Referenced by SipperFile.TrainingModelStatus::ForceCancelation().
PicesPredictionList PicesInterface::TrainingModel2::BinaryProbailitiesForClass (PicesClass^ leftClass)
Definition at line 1079 of file TrainingModel2.cpp.
References KKB::endl(), and PicesInterface::PicesClassList::LookUpIndex().
Referenced by GradeTrainingModel.ImageListDisplay::LoadImageGrid(), and SipperFile.PredictionBreakDownDisplay::PredictionBreakDownDisplay().
void PicesInterface::TrainingModel2::BuildNewTrainedModel ()
Todo:
There is a memory corruption when the process is canceled.
Definition at line 785 of file TrainingModel2.cpp.
References KKMLL::TrainingProcess2::Abort(), KKB::endl(), KKB::Configuration::FormatErrors(), KKB::Configuration::FormatGood(), MLL::PicesTrainingConfiguration::Load(), KKMLL::TrainingProcess2::MLClasses(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by LoadExistingModelOtherwiseBuild().
void PicesInterface::TrainingModel2::BuildTrainingModel (PicesFeatureVectorList^ picesTrainingData)
summary> Sets the 'cancelFlag' to true; the load and training processes monitor this flag; if goes true process will exit at earliest convenience.
/summary>
Definition at line 1017 of file TrainingModel2.cpp.
References KKMLL::TrainingProcess2::Abort(), KKB::endl(), PicesInterface::PicesFeatureVector::Features(), MLL::PicesTrainingConfiguration::Load(), KKMLL::MLClassList::SortByName(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters().
void PicesInterface::TrainingModel2::CancelLoad ()
summary> Returns a duplicate list of classes that belong to this model; since a duplicated list caller can modify without impacting this TrainingModel.
/summary>
Definition at line 1667 of file TrainingModel2.cpp.
Referenced by SipperFile.TrainingModelStatus::CancelLoad(), SipperFile.TrainingModelStatus::ForceCancelation(), and GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters().
void PicesInterface::TrainingModel2::CleanUp ()
Definition at line 304 of file TrainingModel2.cpp.
References KKB::RunLog::AttachMsgQueue(), KKB::endl(), KKB::RunLog::Level(), KKB::Configuration::MemoryConsumedEstimated(), KKMLL::Classifier2::MemoryConsumedEstimated(), KKMLL::TrainingProcess2::MemoryConsumedEstimated(), and KKMLL::MLClassList::MemoryConsumedEstimated().
Referenced by GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters().
TrainingModel2 PicesInterface::TrainingModel2::CreateTrainingModelLeft ()
summary> When using a Dual classifier will return an instance of the second/right classifier.
Definition at line 405 of file TrainingModel2.cpp.
References Dual, ModelType, TrainingModel2(), and KKMLL::TrainingProcess2::TrainingProcessLeft().
TrainingModel2 PicesInterface::TrainingModel2::CreateTrainingModelRight ()
Definition at line 419 of file TrainingModel2.cpp.
References Dual, ModelType, TrainingModel2(), and KKMLL::TrainingProcess2::TrainingProcessRight().
String PicesInterface::TrainingModel2::DirectoryPathForClass (PicesClass^ mlClass)
Fully expanded directory path for specified class.
Parameters
mlClass Class that we want to get directory path for training images.
Returns
Returns full path where images for mlClass are stored; directory path is fully expended; if class not defined in configuration will return nullptr.
Definition at line 1674 of file TrainingModel2.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr(), and PicesInterface::PicesClass::UnmanagedMLClass().
Referenced by SipperFile.PredictionBreakDownDisplay::PredictionBreakDownDisplay(), SipperFile.PredictionBreakDownDisplayDual::PredictionBreakDownDisplayDual(), SipperFile.PredictionBreakDownDisplay::ThumbnailCallback(), and PicesCommander.PicesCommander::UpdateLastClassesValidated().
array< PicesInterface::ProbNamePair^ > PicesInterface::TrainingModel2::FindWorstSupportVectors (PicesFeatureVector^ picesFeatureVector, int numToFind, PicesClass^ c1, PicesClass^ c2)
Definition at line 1467 of file TrainingModel2.cpp.
References KKMLL::Classifier2::FindWorstSupportVectors(), PicesInterface::PicesFeatureVector::UnManagedClass(), and PicesInterface::PicesClass::UnmanagedMLClass().
Referenced by SipperFile.PredictionBreakDownDisplay::ThumbnailCallback().
array< PicesInterface::ProbNamePair^ > PicesInterface::TrainingModel2::FindWorstSupportVectors2 (PicesFeatureVector^ picesFeatureVector, int numToFind, PicesClass^ c1, PicesClass^ c2)
Definition at line 1503 of file TrainingModel2.cpp.
References KKMLL::Classifier2::FindWorstSupportVectors2(), PicesInterface::PicesFeatureVector::UnManagedClass(), and PicesInterface::PicesClass::UnmanagedMLClass().
Referenced by SipperFile.PredictionBreakDownDisplay::ThumbnailCallback().
array< String^ > PicesInterface::TrainingModel2::GetListOfTrainingModels () static
Definition at line 1687 of file TrainingModel2.cpp.
References KKMLL::TrainingProcess2::Config(), KKB::KKStr::Empty(), PicesInterface::PicesKKStr::KKStrToSystenStr(), KKB::osAddSlash(), KKB::osGetListOfFiles(), KKMLL::TrainingProcess2::Parameters(), KKB::KKQueue< Entry >::QueueSize(), KKB::KKStr::Str(), and KKMLL::ModelParam::ToCmdLineStr().
Referenced by SipperFileViewer.AutoDetectionParamters::AutoDetectionParamters(), PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets(), GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters(), PicesCommander.PicesCommander::PicesCommander(), and PicesCommander.SaveActiveTrainingModelFeatureData::SaveActiveTrainingModelFeatureData().
bool PicesInterface::TrainingModel2::IncludesClass (PicesClass^ mlClass)
Definition at line 601 of file TrainingModel2.cpp.
References KKB::KKStr::Empty(), and PicesInterface::PicesClass::UnmanagedMLClass().
Referenced by AddImageToTrainingLibray(), and SipperFile.ImageViewer::ImageViewer().
String PicesInterface::TrainingModel2::LastRunLogTextLine ()
Definition at line 471 of file TrainingModel2.cpp.
References PicesInterface::OSservices::AddSlash(), KKMLL::TrainingProcess2::BuildDateTime(), KKMLL::TrainingProcess2::Config(), PicesInterface::OSservices::GetRootName(), PicesInterface::PicesClassList::GetUniqueClass(), PicesInterface::PicesSipperVariables::HomeDir(), PicesInterface::PicesKKStr::KKStrToSystenStr(), PicesInterface::OSservices::KKuDateTimeToSystemDateTime(), KKB::RunLog::LastLine(), KKB::RunLog::LineCount(), KKMLL::TrainingProcess2::ModelType(), Null, and KKMLL::TrainingConfiguration2::OtherClass().
void PicesInterface::TrainingModel2::LoadExistingModelOtherwiseBuild (PicesMsgQueue^ msgQueue)
Will attach message queue to runLog.
Definition at line 632 of file TrainingModel2.cpp.
References KKB::RunLog::AttachMsgQueue(), BuildNewTrainedModel(), LoadExistingTrainedModel(), and PicesInterface::PicesMsgQueue::MsgQueue().
Referenced by SipperFile.TrainingModelStatus::ForceCancelation(), GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters(), and PicesCommander.ClassifierProcess::StartThread().
void PicesInterface::TrainingModel2::LoadExistingTrainedModel ()
Definition at line 713 of file TrainingModel2.cpp.
References KKMLL::TrainingProcess2::Abort(), CancelFlag, KKB::endl(), KKMLL::TrainingProcess2::MLClasses(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by LoadExistingModelOtherwiseBuild().
void PicesInterface::TrainingModel2::LoadTrainigLibrary (bool forceRebuild)
Todo:
There is a memory corruption when the process is canceled.
Definition at line 889 of file TrainingModel2.cpp.
References KKMLL::TrainingProcess2::Abort(), KKMLL::TrainingProcess2::ConfigFileFormatErrors(), KKB::endl(), MLL::PicesTrainingConfiguration::Load(), KKMLL::TrainingProcess2::MLClasses(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by SipperFile.TrainingModelStatus::ForceCancelation().
void PicesInterface::TrainingModel2::LoadTrainingModelForGivenLevel (uint level, PicesMsgQueue^ msgQueue)
Parameters
msgQueue Will attach message queue to runLog
Definition at line 650 of file TrainingModel2.cpp.
References KKMLL::TrainingProcess2::Abort(), KKB::RunLog::AttachMsgQueue(), KKB::endl(), KKMLL::TrainingProcess2::MLClasses(), PicesInterface::PicesMsgQueue::MsgQueue(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters().
PicesClassList PicesInterface::TrainingModel2::MLClasses ()
Definition at line 622 of file TrainingModel2.cpp.
Referenced by PicesCommander.ClassificationStatus::ClassificationStatus(), PicesCommander.ClassifierProcess::ClassifierProcess(), PicesCommander.ClassificationStatus::CleanUpMemory(), SipperFile.ImageViewer::ImageViewer(), SipperFile.ActiveTrainingLibraries::Model1ListOfClasses(), and PicesCommander.PicesCommander::PicesCommander().
PicesPrediction PicesInterface::TrainingModel2::PredictClass (PicesFeatureVector^ example)
Definition at line 1176 of file TrainingModel2.cpp.
References KKMLL::Classifier2::ClassifyAExample(), PicesInterface::PicesFeatureVector::Features(), PicesInterface::PicesClassList::GetUniqueClass(), and PicesInterface::PicesClassList::LookUpByUnmanagedClass().
Referenced by GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters(), SipperFile.ActiveTrainingLibraries::MakePredictions(), PredictClass(), and PicesCommander.ClassifierProcess::StartThread().
void PicesInterface::TrainingModel2::PredictClass (PicesFeatureVector^ featureVector, PicesPrediction^ prediction1, PicesPrediction^ prediction2)
Definition at line 1229 of file TrainingModel2.cpp.
References KKMLL::Classifier2::ClassifyAExample(), PicesInterface::PicesClassList::GetUniqueClass(), PicesInterface::PicesPrediction::MLClass, PicesInterface::PicesPrediction::Probability, PicesInterface::PicesFeatureVector::UnManagedClass(), and PicesInterface::PicesPrediction::Votes.
void PicesInterface::TrainingModel2::PredictClass (System::String^ imageFileName, System::Array^ raster, System::Single^ depth, System::Single^ salinity, System::Single^ oxygen, System::Single^ florences, PicesPrediction^ prediction1, PicesPrediction^ prediction2)
summary> This call assumes that there was a successful call to PredictProbabilities before.
Definition at line 1291 of file TrainingModel2.cpp.
References PicesInterface::PicesFeatureVector::AddInstrumentData(), and PredictClass().
PicesPredictionList PicesInterface::TrainingModel2::PredictProbabilities (System::String^ imageFileName, System::Array^ raster, System::Single^ depth, System::Single^ salinity, System::Single^ oxygen, System::Single^ florences)
Definition at line 1633 of file TrainingModel2.cpp.
References PicesInterface::PicesFeatureVector::AddInstrumentData(), KKB::RunLog::FileName(), and PicesInterface::PicesKKStr::KKStrToSystenStr().
Referenced by GradeTrainingModel.ImageListDisplay::LoadImageGrid(), SipperFile.ActiveTrainingLibraries::MakePredictions(), SipperFile.PredictionBreakDownDisplay::PredictionBreakDownDisplay(), PredictProbabilities(), and PicesCommander.ClassifierProcess::StartThread().
PicesPredictionList PicesInterface::TrainingModel2::PredictProbabilities (System::String^ imageFileName, PicesRasterList^ saveCalcImages)
Parameters
saveCalcImages If Not NULL intermediate instances created during feature calculation will be appended to this list.
Definition at line 1354 of file TrainingModel2.cpp.
References PicesInterface::PicesFeatureVector::AddInstrumentData(), PicesInterface::PicesRasterList::AddList(), KKB::KKQueue< Entry >::IdxToPtr(), PredictProbabilities(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
PicesPredictionList PicesInterface::TrainingModel2::PredictProbabilities (PicesFeatureVector^ picesFeatureVector)
Definition at line 1112 of file TrainingModel2.cpp.
References PicesInterface::PicesFeatureVector::Features(), PicesInterface::PicesKKStr::KKStrToSystenStr(), KKMLL::Classifier2::ProbabilitiesByClass(), KKB::KKQueue< Entry >::QueueSize(), KKMLL::Classifier2::RetrieveCrossProbTable(), KKMLL::Classifier2::SelectionMethod(), PicesInterface::PicesPredictionList::SortByProbabilityHighToLow(), PicesInterface::PicesPredictionList::SortByVotingHighToLow(), and KKB::KKException::ToString().
void PicesInterface::TrainingModel2::ProbabilitiesByClassDual (PicesFeatureVector^ picesFeatureVector, String^ % classifier1Desc, String^ % classifier2Desc, PicesPredictionList^ % classifier1Results, PicesPredictionList^ % classifier2Results)
Definition at line 1317 of file TrainingModel2.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr(), KKMLL::Classifier2::ProbabilitiesByClassDual(), and PicesInterface::PicesFeatureVector::UnManagedClass().
Referenced by SipperFile.PredictionBreakDownDisplayDual::PredictionBreakDownDisplayDual().
void PicesInterface::TrainingModel2::SaveConfiguration ()
Definition at line 540 of file TrainingModel2.cpp.
References KKB::KKStr::Empty(), PicesInterface::PicesClassList::GetUniqueClass(), KKB::KKQueue< Entry >::IdxToPtr(), PicesInterface::PicesKKStr::KKStrToSystenStr(), KKB::osAddSlash(), KKB::osRunAsABackGroundProcess(), KKB::KKQueue< Entry >::QueueSize(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by AddImageToTrainingLibray().
array< String^ > PicesInterface::TrainingModel2::SupportVectorNames (PicesClass^ c1, PicesClass^ c2)
Returns the names of the training examples that became support vectors in the binary classifier that was built for the class pair c1 and c2 .
Parameters
c1 The first PicesClass.
c2 The second PicesClass.
Returns
nullptr if there is not a SVM for the pair of classes specified otherwise a list of the examples that are S/Vs.
Definition at line 1445 of file TrainingModel2.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr(), KKMLL::Classifier2::SupportVectorNames(), and PicesInterface::PicesClass::UnmanagedMLClass().
Referenced by SipperFile.PredictionBreakDownDisplay::ThumbnailCallback().
Property Documentation
System:: DateTime PicesInterface::TrainingModel2::BuildDateTime get
Definition at line 97 of file TrainingModel2.h.
Referenced by PicesCommander.ClassificationStatus::CleanUpMemory().
bool PicesInterface::TrainingModel2::CancelFlag get
Definition at line 98 of file TrainingModel2.h.
Referenced by LoadExistingTrainedModel().
String^ PicesInterface::TrainingModel2::ConfigFileName get
Definition at line 99 of file TrainingModel2.h.
Referenced by PicesCommander.ClassificationStatus::ClassificationStatus(), PicesCommander.ClassificationStatus::CleanUpMemory(), and GradeTrainingModel.ConfusionMatrix::TallyPredictions().
List< String^>^ PicesInterface::TrainingModel2::ErrorMsgs get
Definition at line 100 of file TrainingModel2.h.
Referenced by SipperFile.TrainingModelStatus::ForceCancelation().
int PicesInterface::TrainingModel2::ImagesPerClass get
Definition at line 101 of file TrainingModel2.h.
Referenced by PicesCommander.ClassificationStatus::CleanUpMemory().
String^ PicesInterface::TrainingModel2::ModelName get
Definition at line 102 of file TrainingModel2.h.
Referenced by AddImageToTrainingLibray(), PicesCommander.ClassifierProcess::ClassifierProcess(), PicesCommander.ClassificationStatus::CleanUpMemory(), SipperFile.ImageViewer::ImageViewer(), and PicesCommander.PicesCommander::PicesCommander().
ModelTypes PicesInterface::TrainingModel2::ModelType get
Definition at line 103 of file TrainingModel2.h.
Referenced by CreateTrainingModelLeft(), CreateTrainingModelRight(), SipperFile.ImageViewer::ImageViewer(), and SipperFile.PredictionBreakDownDisplayDual::PredictionBreakDownDisplayDual().
uint PicesInterface::TrainingModel2::NumHierarchialLevels get
Definition at line 104 of file TrainingModel2.h.
PicesClass^ PicesInterface::TrainingModel2::OtherClass get
Definition at line 105 of file TrainingModel2.h.
String^ PicesInterface::TrainingModel2::ParameterStr get
Definition at line 106 of file TrainingModel2.h.
Referenced by PicesCommander.ClassificationStatus::CleanUpMemory(), and GradeTrainingModel.ConfusionMatrix::TallyPredictions().
String^ PicesInterface::TrainingModel2::RootDir get
Definition at line 107 of file TrainingModel2.h.
Referenced by SipperFile.ImageViewer::ImageViewer(), and PicesCommander.PicesCommander::PicesCommander().
String^ PicesInterface::TrainingModel2::RunLogFileName get
Definition at line 109 of file TrainingModel2.h.
Referenced by SipperFile.TrainingModelStatus::ForceCancelation().
bool PicesInterface::TrainingModel2::Valid get
summary> When using a Dual classifier will return an instance of the first/left classifier.
Definition at line 111 of file TrainingModel2.h.
Referenced by PicesCommander.ClassificationStatus::ClassificationStatus(), PicesCommander.ClassificationStatus::CleanUpMemory(), SipperFile.TrainingModelStatus::ForceCancelation(), GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters(), and PicesCommander.PicesCommander::GetThumbnailImageAbort().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/TrainingModel2.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/TrainingModel2.cpp