Pices: ImageExtractionManager::ExtractionManager Class Reference
ImageExtractionManager::ExtractionManager Class Reference
Manages the extraction of images from a single Sipper File utilizing multiple threads.
#include <ExtractionManager.h>
Public Member Functions
ExtractionManager (const KKStr &_applicationName, ExtractionParms &_parms, kkuint32 _maxNumThreads, RunLog &_log)
~ExtractionManager ()
bool AllProcessorsTerminated (ImageExtractionThreadListPtr threads)
bool AnyProcessorsCrashed ()
const bool & CancelFlag () const
const bool & Crashed () const
const bool & DoneExecuting () const
FactoryFVProducerPtr FvProducerFactory () const
ClassStatisticListPtr GetClassStatistics () const
Returns a snapshot of the current class count statistics collected.
void GetRunTimeStats (ExtractionManagerStats &stats)
void GetRunTimeStats (kkuint64 &_bytesRead, kkuint32 &_framesRead, kkuint32 &_framesProcessed, kkuint32 &_scanLinesProcessed, kkuint32 &_imagesFound, kkuint32 &_imagesClassified, kkuint32 &_imagesUpdated, kkuint32 &_duplicatesDetected, kkuint32 &_updateFailures, kkuint32 &_framesOnQueue, kkuint32 &_imagesOnQueue)
RunLog & Log () const
kkuint32 LogEntryId () const
void ManageTheExtraction (bool &successful)
void ShutdownProcessing (ImageExtractionThreadListPtr threads)
void TerminateProcessing (kkint32 miliSecsToWait)
Detailed Description
Manages the extraction of images from a single Sipper File utilizing multiple threads.
Definition at line 33 of file ExtractionManager.h.
Constructor & Destructor Documentation
ExtractionManager::ExtractionManager (const KKStr & _applicationName, ExtractionParms & _parms, kkuint32 _maxNumThreads, RunLog & _log)
Definition at line 60 of file ExtractionManager.cpp.
References KKMLL::FactoryFVProducer::FileDesc().
ExtractionManager::~ExtractionManager ()
Definition at line 107 of file ExtractionManager.cpp.
Member Function Documentation
bool ExtractionManager::AllProcessorsTerminated (ImageExtractionThreadListPtr threads)
Definition at line 869 of file ExtractionManager.cpp.
References AnyProcessorsCrashed(), KKB::endl(), KKB::MsgQueue::GetNextMsg(), KKB::RunLog::Level(), KKB::osSleep(), ShutdownProcessing(), KKB::KKThread::Status(), and TerminateProcessing().
bool ExtractionManager::AnyProcessorsCrashed ()
Definition at line 845 of file ExtractionManager.cpp.
References KKB::KKThread::Crashed(), and KKB::KKThread::ThreadName().
Referenced by AllProcessorsTerminated(), and ManageTheExtraction().
const bool& ImageExtractionManager::ExtractionManager::CancelFlag () const inline
Definition at line 44 of file ExtractionManager.h.
Referenced by ManageTheExtraction(), and TerminateProcessing().
const bool& ImageExtractionManager::ExtractionManager::Crashed () const inline
Definition at line 45 of file ExtractionManager.h.
const bool& ImageExtractionManager::ExtractionManager::DoneExecuting () const inline
Definition at line 46 of file ExtractionManager.h.
FactoryFVProducerPtr ImageExtractionManager::ExtractionManager::FvProducerFactory () const inline
Definition at line 47 of file ExtractionManager.h.
Referenced by ImageExtractionManager::FrameProcessorThread::FrameProcessorThread().
ClassStatisticListPtr ExtractionManager::GetClassStatistics () const
Returns a snapshot of the current class count statistics collected.
Caller will get ownership of the instance of 'ClassStatisticList' so will be responsible for deleting when done.
Definition at line 834 of file ExtractionManager.cpp.
References MLL::SipperExtractionImageManager::ClassStats().
void ExtractionManager::GetRunTimeStats (ExtractionManagerStats & stats)
Definition at line 735 of file ExtractionManager.cpp.
References ImageExtractionManager::LogicalFrameQueue::FramesOnQueue(), ImageExtractionManager::FrameExtractorThread::GetRunTimeStats(), ImageExtractionManager::DataBaseUpdateThread::GetRunTimeStats(), ImageExtractionManager::FrameProcessorThread::GetRunTimeStats(), and ImageExtractionManager::ExtractedImageQueue::ImagesOnQueue().
Referenced by ManageTheExtraction().
void ExtractionManager::GetRunTimeStats (kkuint64 & _bytesRead, kkuint32 & _framesRead, kkuint32 & _framesProcessed, kkuint32 & _scanLinesProcessed, kkuint32 & _imagesFound, kkuint32 & _imagesClassified, kkuint32 & _imagesUpdated, kkuint32 & _duplicatesDetected, kkuint32 & _updateFailures, kkuint32 & _framesOnQueue, kkuint32 & _imagesOnQueue)
Definition at line 772 of file ExtractionManager.cpp.
References ImageExtractionManager::LogicalFrameQueue::FramesOnQueue(), ImageExtractionManager::FrameExtractorThread::GetRunTimeStats(), ImageExtractionManager::DataBaseUpdateThread::GetRunTimeStats(), ImageExtractionManager::FrameProcessorThread::GetRunTimeStats(), and ImageExtractionManager::ExtractedImageQueue::ImagesOnQueue().
RunLog& ImageExtractionManager::ExtractionManager::Log () const inline
Definition at line 48 of file ExtractionManager.h.
kkuint32 ImageExtractionManager::ExtractionManager::LogEntryId () const inline
Definition at line 49 of file ExtractionManager.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
void ExtractionManager::ManageTheExtraction (bool & successful)
Definition at line 947 of file ExtractionManager.cpp.
References AnyProcessorsCrashed(), ImageExtractionManager::ExtractionParms::CameraNum(), CancelFlag(), ImageExtractionManager::ExtractionParms::CmdLine(), ImageExtractionManager::ExtractionParms::ConnectedPixelDist(), ImageExtractionManager::ExtractionParms::CountOnly(), ImageExtractionManager::FrameExtractorThread::DataManager(), KKB::endl(), ImageExtractionManager::ExtractionParms::FileFormat(), MLL::SipperExtractionImageManager::Flush(), ImageExtractionManager::ExtractionParms::FramesOnly(), GetRunTimeStats(), KKB::DateTime::HH_MM_SS(), MLL::DataBaseImageValidatedEntry::ImageFileName(), MLL::DataBase::ImageLoad(), MLL::DataBaseImageValidatedEntry::ImageSize(), MLL::DataBase::ImagesUpdateImageSize(), MLL::DataBase::ImagesUpdateValidatedClass(), KKB::RunLog::Level(), MLL::DataBase::LogEntriesProcessEnd(), ImageExtractionManager::ExtractionParms::MaxImageSize(), ImageExtractionManager::ExtractionParms::MinImageSize(), ImageExtractionManager::ExtractionParms::MorphOperations(), KKB::osGetFileSize(), KKB::osGetLocalDateTime(), KKB::osGetRootName(), KKB::osGetSystemTimeUsed(), KKB::osRemoveExtension(), KKB::osRenameFile(), ImageExtractionManager::ExtractionParms::OutputRootDir(), KKB::KKQueue< Entry >::PushOnBack(), ImageExtractionManager::ExtractionParms::ReportFileName(), MLL::SipperExtractionImageManager::ReportStatistics(), MLL::SipperExtractionImageManager::ReportStatsByDepth(), ImageExtractionManager::ExtractionParms::ScanLineEnd(), MLL::InstrumentDataManager::ScanLinesPerMeterDepth(), ImageExtractionManager::ExtractionParms::ScanLineStart(), KKB::DateTime::Seconds(), MLL::DataBase::ServerDescription(), ImageExtractionManager::FrameExtractorThread::SipperBuffFileName(), MLL::SipperFileFormatToStr(), ImageExtractionManager::ExtractionParms::SipperFileName(), MLL::DataBase::SipperFilesUpdateExtractionStatus(), MLL::DataBase::SipperFileUpdateFileSizeStats(), MLL::DataBaseImageValidatedEntry::SizeCoordinates(), KKB::KKStr::Str(), KKB::StrFormatDouble(), KKB::StrFormatInt(), KKB::StrFormatInt64(), TerminateProcessing(), MLL::DataBase::Valid(), MLL::DataBaseImageValidatedEntry::ValidatedClass(), and MLL::DataBaseImageValidatedEntry::ValidatedClassName().
void ExtractionManager::ShutdownProcessing (ImageExtractionThreadListPtr threads)
Definition at line 128 of file ExtractionManager.cpp.
References KKB::KKThread::ShutdownThread().
Referenced by AllProcessorsTerminated().
void ExtractionManager::TerminateProcessing (kkint32 miliSecsToWait)
Definition at line 144 of file ExtractionManager.cpp.
References KKMLL::TrainingProcess2::Abort(), KKB::MsgQueue::AddMsg(), MLL::SipperFile::AssignCtdExternalInstruments(), KKB::RunLog::AttachFile(), ImageExtractionManager::ExtractionParms::CameraNum(), CancelFlag(), ImageExtractionManager::ExtractionParms::CmdLine(), ImageExtractionManager::ExtractionParms::ConfigFileName(), ImageExtractionManager::ExtractionParms::CountOnly(), KKB::KKThread::Crashed(), KKMLL::TrainingProcess2::CreateTrainingProcess(), MLL::SipperStation::CruiseName(), MLL::SipperDeployment::CruiseName(), MLL::SipperCruise::CruiseName(), MLL::SipperFile::CruiseName(), ImageExtractionManager::ExtractionParms::DataBaseServer(), MLL::SipperCruise::DateEnd(), MLL::SipperCruise::DateStart(), MLL::SipperDeployment::DateTimeEnd(), MLL::SipperStation::DateTimeStart(), MLL::SipperDeployment::DateTimeStart(), MLL::SipperFile::DateTimeStart(), MLL::SipperDeployment::DeploymentNum(), MLL::SipperFile::DeploymentNum(), MLL::SipperFile::Depth(), MLL::SipperStation::Description(), MLL::SipperDeployment::Description(), MLL::SipperCruise::Description(), MLL::SipperFile::Description(), KKB::KKStr::Empty(), KKB::endl(), ImageExtractionManager::ExtractionParms::ExtractFeatureData(), KKMLL::FactoryFVProducer::FileDesc(), ImageExtractionManager::ExtractionParms::FileFormat(), KKB::Configuration::FormatErrors(), KKB::Configuration::FormatGood(), KKMLL::TrainingConfiguration2::FvFactoryProducer(), MLL::DataBase::ImagesEraseSipperFileSizeRange(), ImageExtractionManager::ExtractionParms::ImagesPerDirectory(), MLL::DataBase::ImagesRetrieveValidatedClass(), MLL::DataBase::InstrumentDataSaveListForOneSipperFile(), MLL::SipperStation::Latitude(), MLL::SipperDeployment::Latitude(), MLL::SipperFile::Latitude(), KKB::RunLog::Level(), MLL::PicesTrainingConfiguration::Load(), MLL::SipperCruise::Location(), MLL::DataBase::LogEntriesProcessStart(), MLL::DataBaseLogEntry::LogEntryId(), MLL::SipperStation::Longitude(), MLL::SipperDeployment::Longitude(), MLL::SipperFile::Longitude(), KKB::Max(), ImageExtractionManager::ExtractionParms::MaxImageSize(), ImageExtractionManager::ExtractionParms::MinImageSize(), MLL::SipperCruise::Objective(), KKB::osAddSlash(), KKB::osCreateDirectoryPath(), KKB::osGetFileDateTime(), KKB::osGetFileSize(), KKB::osGetLocalDateTime(), KKB::osGetRootName(), KKB::osGetSystemTimeUsed(), KKB::osSleep(), ImageExtractionManager::ExtractionParms::OutputRootDir(), MLL::SipperCruise::Principal(), KKB::KKQueue< Entry >::PushOnBack(), ImageExtractionManager::ExtractionParms::RefreshDataBaseImages(), ImageExtractionManager::ExtractionParms::ReportFileName(), MLL::SipperCruise::ResearchOrg(), MLL::DataBaseImageValidatedEntryList::Save(), MLL::SipperFile::ScanRate(), MLL::DataBase::ServerDescription(), MLL::sfSipper4Bit, MLL::SipperCruise::ShipName(), KKB::KKThread::ShutdownThread(), MLL::DataBase::SipperCruiseInsert(), MLL::DataBase::SipperCruiseLoad(), MLL::DataBase::SipperDeploymentInsert(), MLL::DataBase::SipperDeploymentLoad(), MLL::DataBase::SipperFileInsert(), ImageExtractionManager::ExtractionParms::SipperFileName(), MLL::DataBase::SipperFileRecLoad(), MLL::DataBase::SipperFilesUpdateExtractionStatus(), MLL::DataBase::SipperStationInsert(), MLL::DataBase::SipperStationLoad(), MLL::SipperFile::SizeInBytes(), KKB::KKThread::Start(), MLL::SipperStation::StationName(), MLL::SipperDeployment::StationName(), MLL::SipperFile::StationName(), KKB::KKThread::Status(), ImageExtractionManager::ExtractionParms::StatusMessage(), KKB::KKStr::Str(), KKB::StrFormatInt(), MLL::SipperDeployment::SyncTimeStampActual(), MLL::SipperDeployment::SyncTimeStampCTD(), MLL::SipperDeployment::SyncTimeStampGPS(), KKB::KKThread::TerminateThread(), ImageExtractionManager::ExtractionParms::UpdateDataBase(), and MLL::DataBase::Valid().
Referenced by AllProcessorsTerminated(), and ManageTheExtraction().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/ImageExtractionManager/ExtractionManager.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/ImageExtractionManager/ExtractionManager.cpp