Pices: PicesInterface::PicesRaster Class Reference
PicesInterface::PicesRaster Class Reference
#include <PicesRaster.h>
Public Types
enum MaskType : int {
MaskType::CROSS3 = 0, MaskType::CROSS5 = 1, MaskType::SQUARE3 = 2, MaskType::SQUARE5 = 3,
MaskType::SQUARE7 = 4, MaskType::SQUARE9 = 5, MaskType::SQUARE11 = 6
}
enum OperationType {
OperationType::Null, OperationType::BandPass, OperationType::Binarize, OperationType::BinarizeTH,
OperationType::Closing, OperationType::ConnectedComponent, OperationType::ConvexHull, OperationType::Dilation,
OperationType::Edge, OperationType::Erosion, OperationType::FillHoles, OperationType::FourierTransform,
OperationType::Opening, OperationType::SmoothAveraging, OperationType::SmoothMedium, OperationType::Thinning
}
Public Member Functions
PicesRaster (int height, int width)
PicesRaster (System::Array^ _raster)
summary> Will take ownership of "_raster" and delete it when done.
PicesRaster (RasterSipperPtr _raster)
PicesRaster (String^ _fileName)
!PicesRaster ()
~PicesRaster ()
PicesRaster^ BandPass (float lowerFreqBound, float upperFreqBound, bool retainBackground)
PicesRaster^ Binarize ()
PicesRaster^ BinarizeByThreshold (uint min, uint max)
Bitmap^ BuildBitmap ()
System::Array^ BuildRasterArray ()
array< array< System::Byte >^ >^ BuildRasterArray2 ()
PicesRaster^ CloseImage (MaskType mt)
bool Color ()
PicesRaster^ ConnectedComponent (uchar connectedComponentDist)
PicesRaster^ ConvexHull ()
PicesPointList^ DeriveImageLength ()
PicesRaster^ DialateImage (MaskType mt)
void DrawGrid (float pixelsPerMinor, int minorsPerMajor, System::Drawing::Color hashColor, System::Drawing::Color gridColor)
PicesRaster^ EdgeImage ()
PicesRaster^ ErodeImage (MaskType mt)
PicesRaster^ FillHoles ()
PicesRaster^ FourierTransform ()
PicesRaster^ OpenImage (MaskType mt)
PicesRaster^ Padded (kkint32 padding)
Duplicates image with extract padding on all four sides.
PicesRaster^ RemoveZooscanBrackets ()
PicesRaster^ ReversedImage ()
void Save (String^ fileName)
PicesRaster^ SmoothAveraging (int maskSize)
PicesRaster^ SmoothMedium (int maskSize)
PicesRaster^ Thinning ()
PicesRaster^ ToColor ()
RasterSipperPtr UnmanagedClass ()
Static Public Member Functions
static RasterSipperPtr BuildRasterObj (System::Array^ raster)
summary> Will go back to the original SIPPER file and recover the source image.
static float ComputeSegmentLens (PicesPointList^ points, float heightFactor, float widthFactor)
static PicesRaster^ GetOrigSipperImage (String^ sipperFileRootName, kkuint64 byteOffset, uint topLeftRow, uint topLeftCol, uint height, uint width, uchar connectedComponentDist, PicesRunLog^ log)
static int MaskSize (MaskType mt)
static PicesRaster::MaskType MaskTypeFromStr (System::String^ mtStr)
static System::String^ MaskTypeToStr (MaskType mt)
static OperationType OperationTypeFromStr (System::String^ otStr)
static System::String^ OperationTypeToStr (OperationType ot)
Properties
String^ FileName [get, set]
int Height [get]
int Width [get]
Detailed Description
Definition at line 18 of file PicesRaster.h.
Member Enumeration Documentation
enum PicesInterface::PicesRaster::MaskType : int strong
Enumerator
CROSS3
CROSS5
SQUARE3
SQUARE5
SQUARE7
SQUARE9
SQUARE11
Definition at line 84 of file PicesRaster.h.
enum PicesInterface::PicesRaster::OperationType strong
Enumerator
Null
BandPass
Binarize
BinarizeTH
Closing
ConnectedComponent
ConvexHull
Dilation
Edge
Erosion
FillHoles
FourierTransform
Opening
SmoothAveraging
SmoothMedium
Thinning
Definition at line 63 of file PicesRaster.h.
Constructor & Destructor Documentation
PicesInterface::PicesRaster::PicesRaster (int height, int width)
Definition at line 62 of file PicesRaster.cpp.
References KKB::Raster::Color(), KKB::Raster::Height(), and KKB::Raster::Width().
Referenced by BandPass(), Binarize(), BinarizeByThreshold(), CloseImage(), ConnectedComponent(), ConvexHull(), DialateImage(), EdgeImage(), ErodeImage(), FillHoles(), FourierTransform(), GetOrigSipperImage(), OpenImage(), Padded(), PicesRaster(), PicesInterface::PicesRasterList::PicesRasterList(), RemoveZooscanBrackets(), ReversedImage(), SmoothAveraging(), SmoothMedium(), Thinning(), ToColor(), and ~PicesRaster().
PicesInterface::PicesRaster::PicesRaster (System::Array^ _raster)
summary> Will take ownership of "_raster" and delete it when done.
Definition at line 75 of file PicesRaster.cpp.
References BuildRasterObj(), KKB::Raster::Color(), KKB::Raster::Height(), MLL::RasterSipper::MemoryConsumedEstimated(), PicesRaster(), and KKB::Raster::Width().
PicesInterface::PicesRaster::PicesRaster (RasterSipperPtr _raster)
PicesInterface::PicesRaster::PicesRaster (String^ _fileName)
Definition at line 49 of file PicesRaster.cpp.
References KKB::Raster::FileName(), MLL::RasterSipper::MemoryConsumedEstimated(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
PicesInterface::PicesRaster::!PicesRaster ()
Definition at line 95 of file PicesRaster.cpp.
PicesInterface::PicesRaster::~PicesRaster ()
Definition at line 106 of file PicesRaster.cpp.
References KKB::Raster::FileName(), PicesInterface::PicesKKStr::KKStrToSystenStr(), PicesRaster(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Member Function Documentation
PicesRaster PicesInterface::PicesRaster::BandPass (float lowerFreqBound, float upperFreqBound, bool retainBackground)
Definition at line 413 of file PicesRaster.cpp.
References MLL::RasterSipper::BandPass(), and PicesRaster().
PicesRaster PicesInterface::PicesRaster::Binarize ()
Definition at line 423 of file PicesRaster.cpp.
References MLL::RasterSipper::BinarizeByThreshold(), and PicesRaster().
PicesRaster PicesInterface::PicesRaster::BinarizeByThreshold (uint min, uint max)
Definition at line 432 of file PicesRaster.cpp.
References MLL::RasterSipper::BinarizeByThreshold(), and PicesRaster().
Bitmap PicesInterface::PicesRaster::BuildBitmap ()
Definition at line 665 of file PicesRaster.cpp.
References KKB::Raster::Blue(), KKB::Raster::Color(), KKB::Raster::Green(), KKB::Raster::Height(), KKB::Raster::Red(), and KKB::Raster::Width().
Referenced by SipperFile.DisplayPicesImages::GetThumbnailImageAbort(), SipperFile.ImageViewer::ImageViewer(), Save(), PicesInterface::PicesDataBaseImage::Thumbnail(), and PicesCommander.PicesCommander::UpdateLastClassesValidated().
System::Array PicesInterface::PicesRaster::BuildRasterArray ()
Definition at line 332 of file PicesRaster.cpp.
References KKB::Raster::Green(), KKB::Raster::Height(), and KKB::Raster::Width().
array< array< System::Byte >^ > PicesInterface::PicesRaster::BuildRasterArray2 ()
Definition at line 363 of file PicesRaster.cpp.
References KKB::Raster::Green(), KKB::Raster::Height(), and KKB::Raster::Width().
Referenced by SipperFile.ImageEditor::ImageEditor().
RasterSipperPtr PicesInterface::PicesRaster::BuildRasterObj (System::Array^ raster) static
summary> Will go back to the original SIPPER file and recover the source image.
Definition at line 297 of file PicesRaster.cpp.
References KKB::Raster::GreenArea().
Referenced by PicesInterface::PicesFeatureVector::PicesFeatureVector(), and PicesRaster().
PicesRaster PicesInterface::PicesRaster::CloseImage (MaskType mt)
Definition at line 531 of file PicesRaster.cpp.
References MLL::RasterSipper::CreateDilatedRaster(), MLL::RasterSipper::CreateErodedImage(), and PicesRaster().
bool PicesInterface::PicesRaster::Color ()
Definition at line 407 of file PicesRaster.cpp.
References KKB::Raster::Color().
Referenced by PicesCommander.PicesCommander::UpdateLastClassesValidated().
float PicesInterface::PicesRaster::ComputeSegmentLens (PicesPointList^ points, float heightFactor, float widthFactor) static
Definition at line 552 of file PicesRaster.cpp.
References PicesInterface::PicesPointList::ComputeSegmentLens().
PicesRaster PicesInterface::PicesRaster::ConnectedComponent (uchar connectedComponentDist)
Definition at line 565 of file PicesRaster.cpp.
References KKB::Raster::ConnectedComponent(), and PicesRaster().
PicesRaster PicesInterface::PicesRaster::ConvexHull ()
Definition at line 542 of file PicesRaster.cpp.
References KKB::ConvexHull::Filter(), and PicesRaster().
PicesPointList PicesInterface::PicesRaster::DeriveImageLength ()
Definition at line 452 of file PicesRaster.cpp.
References MLL::RasterSipper::DeriveImageLength().
Referenced by SipperFile.ImageViewer::ImageViewer().
PicesRaster PicesInterface::PicesRaster::DialateImage (MaskType mt)
Definition at line 463 of file PicesRaster.cpp.
References MLL::RasterSipper::CreateDilatedRaster(), and PicesRaster().
void PicesInterface::PicesRaster::DrawGrid (float pixelsPerMinor, int minorsPerMajor, System::Drawing::Color hashColor, System::Drawing::Color gridColor)
Definition at line 283 of file PicesRaster.cpp.
References KKB::Raster::DrawGrid().
Referenced by PicesCommander.PicesCommander::UpdateLastClassesValidated().
PicesRaster PicesInterface::PicesRaster::EdgeImage ()
Definition at line 584 of file PicesRaster.cpp.
References KKB::Raster::Edge(), and PicesRaster().
PicesRaster PicesInterface::PicesRaster::ErodeImage (MaskType mt)
Definition at line 443 of file PicesRaster.cpp.
References MLL::RasterSipper::CreateErodedImage(), and PicesRaster().
PicesRaster PicesInterface::PicesRaster::FillHoles ()
Definition at line 575 of file PicesRaster.cpp.
References KKB::Raster::FillHole(), and PicesRaster().
PicesRaster PicesInterface::PicesRaster::FourierTransform ()
Definition at line 593 of file PicesRaster.cpp.
References MLL::RasterSipper::FastFourier(), and PicesRaster().
PicesRaster PicesInterface::PicesRaster::GetOrigSipperImage (String^ sipperFileRootName, kkuint64 byteOffset, uint topLeftRow, uint topLeftCol, uint height, uint width, uchar connectedComponentDist, PicesRunLog^ log) static
Definition at line 751 of file PicesRaster.cpp.
References PicesInterface::PicesRunLog::Log(), PicesRaster(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by SipperFile.ImageViewer::ImageViewer().
int PicesInterface::PicesRaster::MaskSize (MaskType mt) static
Definition at line 265 of file PicesRaster.cpp.
References CROSS3, CROSS5, SQUARE11, SQUARE3, SQUARE5, SQUARE7, and SQUARE9.
PicesRaster::MaskType PicesInterface::PicesRaster::MaskTypeFromStr (System::String^ mtStr) static
Definition at line 149 of file PicesRaster.cpp.
References CROSS3, CROSS5, SQUARE11, SQUARE3, SQUARE5, SQUARE7, and SQUARE9.
Referenced by SipperFile.ImageEditor::ImageEditor().
System::String PicesInterface::PicesRaster::MaskTypeToStr (MaskType mt) static
Definition at line 129 of file PicesRaster.cpp.
References CROSS3, CROSS5, SQUARE11, SQUARE3, SQUARE5, SQUARE7, and SQUARE9.
Referenced by SipperFile.ImageEditor::ImageEditor().
PicesRaster PicesInterface::PicesRaster::OpenImage (MaskType mt)
Definition at line 472 of file PicesRaster.cpp.
References MLL::RasterSipper::CreateDilatedRaster(), MLL::RasterSipper::CreateErodedImage(), and PicesRaster().
PicesRaster::OperationType PicesInterface::PicesRaster::OperationTypeFromStr (System::String^ otStr) static
Definition at line 210 of file PicesRaster.cpp.
References BandPass, Binarize, BinarizeTH, Closing, ConnectedComponent, ConvexHull, Dilation, Edge, Erosion, FillHoles, FourierTransform, Null, Opening, SmoothAveraging, SmoothMedium, and Thinning.
System::String PicesInterface::PicesRaster::OperationTypeToStr (OperationType ot) static
Definition at line 181 of file PicesRaster.cpp.
References BandPass, Binarize, BinarizeTH, Closing, ConnectedComponent, ConvexHull, Dilation, Edge, Erosion, FillHoles, FourierTransform, Opening, SmoothAveraging, SmoothMedium, and Thinning.
PicesRaster PicesInterface::PicesRaster::Padded (kkint32 padding)
Duplicates image with extract padding on all four sides.
Definition at line 482 of file PicesRaster.cpp.
References MLL::RasterSipper::Padded(), and PicesRaster().
Referenced by PicesCommander.ImportValidatdClass::ImportValidatdClass().
PicesRaster PicesInterface::PicesRaster::RemoveZooscanBrackets ()
Definition at line 490 of file PicesRaster.cpp.
References PicesRaster(), and MLL::RasterSipper::RemoveZooscanBrackets().
Referenced by PicesCommander.ImportImagesIntoDeployment::ImportImagesIntoDeployment().
PicesRaster PicesInterface::PicesRaster::ReversedImage ()
Definition at line 498 of file PicesRaster.cpp.
References PicesRaster(), and MLL::RasterSipper::ReversedImage().
Referenced by PicesCommander.PicesCommander::UpdateLastClassesValidated().
void PicesInterface::PicesRaster::Save (String^ fileName)
Definition at line 505 of file PicesRaster.cpp.
References BuildBitmap(), KKB::Raster::Color(), PicesInterface::OSservices::GetFileExtension(), KKB::SaveImage(), KKB::SaveImageGrayscaleInverted4Bit(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by SipperFile.DisplayPicesImages::GetThumbnailImageAbort(), PicesCommander.SaveFeatureData::SaveFeatureData(), PicesCommander.SaveImagesToDisk::SaveImagesToDisk(), PicesCommander.SaveImagesToDisk2::SaveImagesToDisk2(), PicesCommander.SavePlanktonData::SavePlanktonData(), and PicesCommander.PicesCommander::UpdateLastClassesValidated().
PicesRaster PicesInterface::PicesRaster::SmoothAveraging (int maskSize)
Definition at line 601 of file PicesRaster.cpp.
References MLL::RasterSipper::CreateSmoothImage(), and PicesRaster().
PicesRaster PicesInterface::PicesRaster::SmoothMedium (int maskSize)
Definition at line 609 of file PicesRaster.cpp.
References MLL::RasterSipper::CreateSmoothedMediumImage(), and PicesRaster().
PicesRaster PicesInterface::PicesRaster::Thinning ()
Definition at line 617 of file PicesRaster.cpp.
References PicesRaster(), and MLL::RasterSipper::ThinContour().
PicesRaster PicesInterface::PicesRaster::ToColor ()
Definition at line 637 of file PicesRaster.cpp.
References PicesRaster(), and MLL::RasterSipper::ToColor().
Referenced by PicesCommander.PicesCommander::UpdateLastClassesValidated().
RasterSipperPtr PicesInterface::PicesRaster::UnmanagedClass () inline
Definition at line 168 of file PicesRaster.h.
Referenced by PicesInterface::TrainingModel2::AddImageToTrainingLibray(), PicesInterface::PicesDataBase::ImageFullSizeSave(), PicesInterface::PicesDataBase::ImageInsert(), and PicesInterface::PicesFeatureVector::PicesFeatureVector().
Property Documentation
String^ PicesInterface::PicesRaster::FileName get set
Definition at line 58 of file PicesRaster.h.
Referenced by SipperFile.ImageEditor::ImageEditor(), and SipperFile.ActiveTrainingLibraries::MakePredictions().
int PicesInterface::PicesRaster::Height get
Definition at line 59 of file PicesRaster.h.
Referenced by SipperFile.ImageEditor::ImageEditor(), SipperFile.ImageViewer::ImageViewer(), PicesCommander.ImportImagesIntoDeployment::ImportImagesIntoDeployment(), and PicesCommander.ImportValidatdClass::ImportValidatdClass().
int PicesInterface::PicesRaster::Width get
Definition at line 60 of file PicesRaster.h.
Referenced by SipperFile.ImageEditor::ImageEditor(), SipperFile.ImageViewer::ImageViewer(), PicesCommander.ImportImagesIntoDeployment::ImportImagesIntoDeployment(), and PicesCommander.ImportValidatdClass::ImportValidatdClass().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesRaster.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesRaster.cpp