Pices: ImageExtractionManager::DataBaseUpdateThread Class Reference
ImageExtractionManager::DataBaseUpdateThread Class Reference
#include <DataBaseUpdateThread.h>
Public Member Functions
DataBaseUpdateThread (ExtractionParms &_parms, ExtractionManagerPtr _extractionManager, const KKStr &_threadName, MsgQueuePtr _msgQueue, ExtractedImageQueuePtr _imagesAwaitingUpdate, SipperExtractionImageManagerPtr _imageManager, FileDescPtr _fileDesc)
virtual ~DataBaseUpdateThread ()
kkuint32 DbUpdateFailures () const
void GetRunTimeStats (kkuint32 &_imagesUpdated, kkuint32 &_duplicatesDetected, kkuint32 &_updateFailures)
virtual void Run ()
virtual ThreadTypes ThreadType ()
Public Member Functions inherited from ImageExtractionManager::ImageExtractionThread
ImageExtractionThread (ExtractionParms &_parms, ExtractionManagerPtr _extractionManager, const KKStr &_threadName, MsgQueuePtr _msgQueue)
virtual ~ImageExtractionThread ()
Public Member Functions inherited from KKB::KKThread
KKThread (const KKStr &_threadName, KKThreadManagerPtr _threadManager, MsgQueuePtr _msgQueue)
virtual ~KKThread ()
void AddShutdownPrerequistite (KKThreadPtr _thread)
Specify threads that must stop before this thread is started.
void AddStartPrerequistite (KKThreadPtr _thread)
Specify threads that must start before this thread is started.
VolConstBool & CancelFlag () const
Another name for 'TerminateFlag'.
bool Crashed () const
Signifies that this thread had to terminate on its own because of an abnormal situation; such as a memory corruption.
void Crashed (bool _crashed)
const KKStr & ExceptionText () const
If the overloaded 'Run' method of a derived class generates a exception that is not caught; then the ''ThreadStartCallBack' will catch it and store the related text in this field.
void ExceptionText (const KKStr &_exceptionText)
KKStrListPtr GetMsgs ()
void Kill ()
stops the running thread and frees the thread handle
kkint32 MemoryConsumedEstimated ()
KKB::MsgQueuePtr MsgQueue ()
bool OkToShutdown () const
Returns 'true' if all shutdown prerequisites are in the 'Stopped' status.
bool OkToStart () const
Returns 'true' if all start prerequisites are in the 'Running' status.
VolConstBool & ShutdownFlag () const
Indicates that the application wants this thread to complete what work is queued up for it top process.
void ShutdownThread ()
Call this method to have its thread finish what ever is in the queue and then exit.
void Start (ThreadPriority _priority, bool &successful)
Call this method to start thread; it will call the method "Run".
ThreadStatus Status () const
void Status (ThreadStatus _status)
const KKStr & StatusStr () const
VolConstBool & TerminateFlag () const
Indicates that thread is to stop processing ASAP, release any resources it holds and terminate.
virtual void TerminateFlagChanged ()
Will be called whenever the value of 'terminateFlag' is changed; derived classes should override this method if they need to be aware that the terminaeFlag has changed.
void TerminateThread ()
Call this method to have its thread stop right away and exit.
kkint32 ThreadId () const
const KKStr & ThreadName () const
bool ThreadStillProcessing () const
void WaitForThreadToStop (kkuint32 maxTimeToWait)
Called by separate thread; will stay in loop until the thread controlled by this instance shutdown or it waited the 'maxTimeToWait'.
Additional Inherited Members
Public Types inherited from ImageExtractionManager::ImageExtractionThread
enum ThreadTypes : int { ThreadTypes::FrameExtractor, ThreadTypes::FrameProcessor, ThreadTypes::DataBaseUpdater }
Static Public Member Functions inherited from KKB::KKThread
static const KKStr & ThreadStatusToStr (ThreadStatus)
Protected Member Functions inherited from KKB::KKThread
void AddMsg (KKStrPtr msg)
Taking ownership of 'msg' and will append to 'msgQueue'.
void AddMsg (const KKStr &msg)
A copy of the message 'msg' will be added to the end of msgQueue.
bool ShutdownOrTerminateRequested ()
bool ThereIsACircularReferenceShutdown (KKThreadPtr _thread) const
bool ThereIsACircularReferenceStart (KKThreadPtr _thread) const
Protected Attributes inherited from ImageExtractionManager::ImageExtractionThread
ExtractionManagerPtr extractionManager
Pointer to instance that manages all the threads.
ExtractionParms & parms
Detailed Description
Definition at line 25 of file DataBaseUpdateThread.h.
Constructor & Destructor Documentation
DataBaseUpdateThread::DataBaseUpdateThread (ExtractionParms & _parms, ExtractionManagerPtr _extractionManager, const KKStr & _threadName, MsgQueuePtr _msgQueue, ExtractedImageQueuePtr _imagesAwaitingUpdate, SipperExtractionImageManagerPtr _imageManager, FileDescPtr _fileDesc)
Definition at line 47 of file DataBaseUpdateThread.cpp.
References ImageExtractionManager::ExtractionParms::ExtractFeatureData(), KKB::osAddSlash(), KKB::osCreateDirectoryPath(), KKB::osGetRootName(), ImageExtractionManager::ExtractionParms::OutputRootDir(), ImageExtractionManager::ImageExtractionThread::parms, and ImageExtractionManager::ExtractionParms::SipperFileName().
DataBaseUpdateThread::~DataBaseUpdateThread () virtual
Definition at line 85 of file DataBaseUpdateThread.cpp.
Member Function Documentation
kkuint32 ImageExtractionManager::DataBaseUpdateThread::DbUpdateFailures () const inline
Definition at line 48 of file DataBaseUpdateThread.h.
void DataBaseUpdateThread::GetRunTimeStats (kkuint32 & _imagesUpdated, kkuint32 & _duplicatesDetected, kkuint32 & _updateFailures)
Definition at line 94 of file DataBaseUpdateThread.cpp.
Referenced by ImageExtractionManager::ExtractionManager::GetRunTimeStats().
void DataBaseUpdateThread::Run () virtual
Reimplemented from KKB::KKThread.
Definition at line 123 of file DataBaseUpdateThread.cpp.
References MLL::SipperExtractionImageManager::AddImage(), KKB::KKThread::AddMsg(), KKMLL::DuplicateImages::AddSingleExample(), ImageExtractionManager::ExtractedImage::ByteOffsetFirstScanRow(), KKB::KKThread::CancelFlag(), MLL::ImageFeatures::CentroidCol(), MLL::ImageFeatures::CentroidRow(), ImageExtractionManager::ExtractionParms::Colorize(), ImageExtractionManager::ExtractionParms::ConnectedPixelDist(), KKB::KKThread::Crashed(), ImageExtractionManager::ExtractionParms::DataBaseServer(), ImageExtractionManager::ExtractedImage::Depth(), MLL::ImageFeatures::Depth(), KKB::KKStr::Empty(), KKMLL::FeatureVector::ExampleFileName(), ImageExtractionManager::ExtractionParms::ExtractFeatureData(), ImageExtractionManager::ImageExtractionThread::extractionManager, MLL::DataBase::FeatureDataInsertRow(), ImageExtractionManager::ExtractedImage::FeatureVectorGiveOwnership(), KKB::Raster::FileName(), KKMLL::DuplicateImage::FirstExampleAdded(), KKB::Raster::Height(), ImageExtractionManager::ExtractedImage::ImageGiveOwnership(), MLL::DataBase::ImageInsert(), MLL::DataBase::LastErrorDesc(), ImageExtractionManager::ExtractionManager::LogEntryId(), KKB::osAddSlash(), KKB::osDeleteFile(), KKB::osGetRootName(), KKB::osSleep(), ImageExtractionManager::ImageExtractionThread::parms, ImageExtractionManager::ExtractedImage::PixelCount(), ImageExtractionManager::ExtractedImage::PredClass1(), ImageExtractionManager::ExtractedImage::PredClass1Prob(), ImageExtractionManager::ExtractedImage::PredClass2(), ImageExtractionManager::ExtractedImage::PredClass2Prob(), KKMLL::FeatureVectorList::PushOnBack(), ImageExtractionManager::ExtractionParms::RefreshDataBaseImages(), KKB::SaveImageGrayscaleInverted4Bit(), KKB::KKThread::ShutdownFlag(), ImageExtractionManager::ExtractedImage::SipperFileScanCol(), ImageExtractionManager::ExtractedImage::SipperFileScanRow(), KKB::KKThread::Status(), ImageExtractionManager::ExtractionParms::UpdateDataBase(), MLL::DataBase::Valid(), and KKB::Raster::Width().
virtual ThreadTypes ImageExtractionManager::DataBaseUpdateThread::ThreadType () inline virtual
Implements ImageExtractionManager::ImageExtractionThread.
Definition at line 39 of file DataBaseUpdateThread.h.
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/ImageExtractionManager/DataBaseUpdateThread.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/ImageExtractionManager/DataBaseUpdateThread.cpp