Pices: MLL::ImageSizeDistributionRow Class Reference
MLL::ImageSizeDistributionRow Class Reference
#include <ImageSizeDistribution.h>
Public Member Functions
ImageSizeDistributionRow (const ImageSizeDistributionRow &row)
ImageSizeDistributionRow (float _depth, kkuint32 _numSizeBuckets, kkuint32 _imageCount, kkuint32 _totalPixels, kkuint32 _totalFilledArea, float _volumneSampled)
void AddData (kkuint32 _sizeIdx, kkuint32 _count)
void AddImageCountPixelCount (kkuint32 _imageCount, kkuint32 _pixelCount, kkuint32 _filledArea, float _volumneSampled)
void AddIn (const ImageSizeDistributionRow &right)
float Depth () const
const VectorUint32 & Distribution () const
kkuint32 ImageCount () const
void ImageCount (kkuint32 _imageCount)
kkuint32 TotalFilledArea () const
void TotalFilledArea (kkuint32 _totalFilledArea)
kkuint32 TotalPixels () const
void TotalPixels (kkuint32 _totalPixels)
float VolumneSampled () const
void VolumneSampled (float _volumneSampled)
Detailed Description
Definition at line 15 of file ImageSizeDistribution.h.
Constructor & Destructor Documentation
ImageSizeDistributionRow::ImageSizeDistributionRow (const ImageSizeDistributionRow & row)
Definition at line 39 of file ImageSizeDistribution.cpp.
MLL::ImageSizeDistributionRow::ImageSizeDistributionRow (float _depth, kkuint32 _numSizeBuckets, kkuint32 _imageCount, kkuint32 _totalPixels, kkuint32 _totalFilledArea, float _volumneSampled)
Member Function Documentation
void ImageSizeDistributionRow::AddData (kkuint32 _sizeIdx, kkuint32 _count)
Definition at line 68 of file ImageSizeDistribution.cpp.
Referenced by MLL::ImageSizeDistribution::AddData(), MLL::ImageSizeDistribution::AllDepths(), and VolumneSampled().
void ImageSizeDistributionRow::AddImageCountPixelCount (kkuint32 _imageCount, kkuint32 _pixelCount, kkuint32 _filledArea, float _volumneSampled)
Definition at line 53 of file ImageSizeDistribution.cpp.
Referenced by MLL::ImageSizeDistribution::DefineRow(), and VolumneSampled().
void ImageSizeDistributionRow::AddIn (const ImageSizeDistributionRow & right)
Definition at line 79 of file ImageSizeDistribution.cpp.
References Min().
Referenced by MLL::ImageSizeDistribution::AddIn(), MLL::ImageSizeDistribution::AllDepths(), and VolumneSampled().
float MLL::ImageSizeDistributionRow::Depth () const inline
Definition at line 29 of file ImageSizeDistribution.h.
const VectorUint32& MLL::ImageSizeDistributionRow::Distribution () const inline
Definition at line 34 of file ImageSizeDistribution.h.
Referenced by MLL::ImageSizeDistribution::DepthProfileForSizeBin(), MLL::ImageSizeDistribution::GetSizeBucketStats(), MLL::ImageSizeDistribution::IntegratedDensityDistribution(), and MLL::ImageSizeDistribution::VolumeSampledByDepthBucket().
kkuint32 MLL::ImageSizeDistributionRow::ImageCount () const inline
Definition at line 30 of file ImageSizeDistribution.h.
Referenced by MLL::ImageSizeDistribution::DefineRow().
void MLL::ImageSizeDistributionRow::ImageCount (kkuint32 _imageCount) inline
Definition at line 37 of file ImageSizeDistribution.h.
kkuint32 MLL::ImageSizeDistributionRow::TotalFilledArea () const inline
Definition at line 32 of file ImageSizeDistribution.h.
Referenced by MLL::ImageSizeDistribution::DefineRow().
void MLL::ImageSizeDistributionRow::TotalFilledArea (kkuint32 _totalFilledArea) inline
Definition at line 39 of file ImageSizeDistribution.h.
kkuint32 MLL::ImageSizeDistributionRow::TotalPixels () const inline
Definition at line 31 of file ImageSizeDistribution.h.
Referenced by MLL::ImageSizeDistribution::DefineRow().
void MLL::ImageSizeDistributionRow::TotalPixels (kkuint32 _totalPixels) inline
Definition at line 38 of file ImageSizeDistribution.h.
float MLL::ImageSizeDistributionRow::VolumneSampled () const inline
Definition at line 33 of file ImageSizeDistribution.h.
Referenced by MLL::ImageSizeDistribution::DefineRow(), MLL::ImageSizeDistribution::DepthProfileForSizeBin(), MLL::ImageSizeDistribution::IntegratedDensityDistribution(), and MLL::ImageSizeDistribution::VolumeSampledByDepthBucket().
void MLL::ImageSizeDistributionRow::VolumneSampled (float _volumneSampled) inline
Definition at line 40 of file ImageSizeDistribution.h.
References AddData(), AddImageCountPixelCount(), and AddIn().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/ImageSizeDistribution.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/ImageSizeDistribution.cpp