Pices: KKB::XmlAttributeList Class Reference
KKB::XmlAttributeList Class Reference
#include <XmlStream.h>
Public Member Functions
XmlAttributeList (bool _owner)
XmlAttributeList (const XmlAttributeList &attributes)
void AddAttribute (const KKStr &name, const KKStr &value)
KKStrConstPtr AttributeNameByIndex (kkuint32 index) const
KKStrConstPtr AttributeValueByIndex (kkuint32 index) const
KKStrConstPtr AttributeValueByName (const KKStr &name) const
DateTime AttributeValueDateTime (const KKStr &name) const
kkint32 AttributeValueInt32 (const KKStr &name) const
const KKStr & AttributeValueKKStr (const KKStr &name) const
XmlAttributePtr LookUpByName (const KKStr &name) const
virtual XmlAttributePtr PopFromBack ()
Removes the last element in the container and returns its pointer.
virtual XmlAttributePtr PopFromFromt ()
virtual void PushOnBack (XmlAttributePtr a)
Adds '_entry' to the End of the container.
virtual void PushOnFront (XmlAttributePtr a)
Adds '_entry' to the Front of the container.
Public Member Functions inherited from KKB::KKQueue< XmlAttribute >
KKQueue (bool _owner=true)
KKQueue (const KKQueue &q, bool _owner)
Constructor, similar to the Copy Constructor except that you can control whether it duplicates the contents.
virtual ~KKQueue ()
void Add (EntryPtr _entry)
same as PushOnBack
void AddFirst (EntryPtr _entry)
same as PushOnFront
virtual void AddQueue (const KKQueue &q)
EntryPtr BackOfQueue () const
Returns pointer of last element in the container without removing it.
void Compress ()
No longer does anything.
void DeleteContents ()
Empties the container, if 'owner' is set to true will call the destructor on each element.
void DeleteEntry (EntryPtr _entry)
Removes from KKQueue the entry who's pointer = '_entry'.
void DeleteEntry (kkuint32 _idx)
Removes from KKQueue the entry who's index = '_idx'.
KKQueue * DuplicateListAndContents () const
Creates a new container including duplicating the contents, which also makes the new instance the owner of those contents.
kkuint32 FindTheKthElement (kkuint32 k, Functor pred)
EntryPtr FrontOfQueue () const
Returns a pointer to the element that is at from of the queue with out removing it from the queue.
EntryPtr GetFirst () const
EntryPtr GetLast () const
EntryPtr IdxToPtr (kkuint32 idx) const
Returns back a pointer to the element who's index is 'idx'.
kkint32 LocateEntry (EntryConstPtr _entry) const
Returns the index of the element who's address is '_entry'.
EntryPtr LookAtBack () const
Returns pointer to element at Back of container with out removing it from the container.
EntryPtr LookAtFront () const
Returns pointer to element at Front of container with out removing it from the container.
bool operator!= (const KKQueue< XmlAttribute > &rightSide) const
returns False if NOT every entry in both containers point to the same elements
KKQueue & operator= (const KKQueue &q)
Assignment Operator.
bool operator== (const KKQueue< XmlAttribute > &rightSide) const
Returns True if every entry in both containers point to the same elements.
XmlAttribute & operator[] (kkuint32 i) const
Returns a reference to element indexed by 'i'.
bool Owner () const
void Owner (bool _owner)
You can specify who owns the contents of the container.
virtual EntryPtr PopFromFront ()
Removes the first element in the container and returns its pointer.
kkint32 PtrToIdx (EntryConstPtr _entry) const
returns the index of the 'entry' that has the same pointer as '_entry', if none found returns -1
kkint32 QueueSize () const
Same as calling vector<>::size().
void RandomizeOrder ()
void RandomizeOrder (kkint64 seed)
void RandomizeOrder (RandomNumGenerator &randomVariable)
EntryPtr RemoveFirst ()
same as PopFromFront
EntryPtr RemoveLast ()
same as PopFromBack
void SetIdxToPtr (kkuint32 _idx, XmlAttribute *_ptr)
void SwapIndexes (size_t idx1, size_t idx2)
Additional Inherited Members
Public Types inherited from KKB::KKQueue< XmlAttribute >
typedef std::vector
< XmlAttribute * >
::const_iterator const_iterator
typedef std::vector
< XmlAttribute * >::iterator iterator
Public Attributes inherited from std::vector< T >
T elements
STL member.
Protected Member Functions inherited from KKB::KKQueue< XmlAttribute >
KKQueue (const KKQueue &q)
Copy Constructor, will create a new instance.
Detailed Description
Definition at line 132 of file XmlStream.h.
Constructor & Destructor Documentation
XmlAttributeList::XmlAttributeList (bool _owner)
Definition at line 234 of file XmlStream.cpp.
XmlAttributeList::XmlAttributeList (const XmlAttributeList & attributes)
Definition at line 240 of file XmlStream.cpp.
References PushOnBack().
Member Function Documentation
void XmlAttributeList::AddAttribute (const KKStr & name, const KKStr & value)
Definition at line 365 of file XmlStream.cpp.
References PushOnBack().
Referenced by KKB::XmlTag::AddAtribute(), and KKB::XmlTag::XmlTag().
KKStrConstPtr XmlAttributeList::AttributeNameByIndex (kkuint32 index) const
Definition at line 319 of file XmlStream.cpp.
Referenced by KKB::XmlTag::AttributeNameByIndex().
KKStrConstPtr XmlAttributeList::AttributeValueByIndex (kkuint32 index) const
Definition at line 310 of file XmlStream.cpp.
Referenced by KKB::XmlTag::AttributeValueByIndex().
KKStrConstPtr XmlAttributeList::AttributeValueByName (const KKStr & name) const
Definition at line 300 of file XmlStream.cpp.
References LookUpByName(), and KKB::XmlAttribute::Value().
Referenced by KKB::XmlTag::AttributeValueByName(), AttributeValueDateTime(), AttributeValueInt32(), and AttributeValueKKStr().
DateTime XmlAttributeList::AttributeValueDateTime (const KKStr & name) const
Definition at line 351 of file XmlStream.cpp.
References AttributeValueByName().
Referenced by KKB::XmlTag::AttributeValueDateTime().
kkint32 XmlAttributeList::AttributeValueInt32 (const KKStr & name) const
Definition at line 340 of file XmlStream.cpp.
References AttributeValueByName(), and KKB::KKStr::ToInt32().
Referenced by KKB::XmlTag::AttributeValueInt32().
const KKStr & XmlAttributeList::AttributeValueKKStr (const KKStr & name) const
Definition at line 329 of file XmlStream.cpp.
References AttributeValueByName(), and KKB::KKStr::EmptyStr().
Referenced by KKB::XmlTag::AttributeValueKKStr().
XmlAttributePtr XmlAttributeList::LookUpByName (const KKStr & name) const
Definition at line 374 of file XmlStream.cpp.
Referenced by AttributeValueByName().
XmlAttributePtr XmlAttributeList::PopFromBack () virtual
Removes the last element in the container and returns its pointer.
If the container is empty will return NULL.
Reimplemented from KKB::KKQueue< XmlAttribute >.
Definition at line 263 of file XmlStream.cpp.
References KKB::KKQueue< Entry >::PopFromBack().
XmlAttributePtr XmlAttributeList::PopFromFromt () virtual
Definition at line 272 of file XmlStream.cpp.
References KKB::KKQueue< Entry >::PopFromFront().
void XmlAttributeList::PushOnBack (XmlAttributePtr _entry) virtual
Adds '_entry' to the End of the container.
Reimplemented from KKB::KKQueue< XmlAttribute >.
Definition at line 249 of file XmlStream.cpp.
References KKB::XmlAttribute::Name(), and KKB::KKQueue< Entry >::PushOnBack().
Referenced by AddAttribute(), and XmlAttributeList().
void XmlAttributeList::PushOnFront (XmlAttributePtr _entry) virtual
Adds '_entry' to the Front of the container.
Reimplemented from KKB::KKQueue< XmlAttribute >.
Definition at line 256 of file XmlStream.cpp.
References KKB::XmlAttribute::Name(), and KKB::KKQueue< Entry >::PushOnFront().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/KSquareLibraries/KKBase/XmlStream.h
C:/Users/kurtk_000/GitHub/KSquareLibraries/KKBase/XmlStream.cpp