Pices: PicesCommander.ReconcileImagesToDataBase Class Reference
PicesCommander.ReconcileImagesToDataBase Class Reference
Public Member Functions
ReconcileImagesToDataBase ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Detailed Description
Definition at line 17 of file ReconcileImagesToDataBase.cs.
Constructor & Destructor Documentation
PicesCommander.ReconcileImagesToDataBase.ReconcileImagesToDataBase () inline
Definition at line 46 of file ReconcileImagesToDataBase.cs.
References PicesInterface::OSservices.AddSlash(), PicesInterface::PicesDataBase.Close(), PicesInterface::OSservices.CreateDirectoryPath(), PicesInterface::PicesDataBaseServer.Description, PicesInterface::PicesRunLog.DisplayWithNoteBook(), PicesInterface::OSservices.GetFileExtension(), PicesInterface::PicesDataBase.GetGlobalDatabaseManagerNewInstance(), PicesInterface::OSservices.GetPathPartOfFile(), PicesInterface::OSservices.GetRootName(), PicesInterface::OSservices.GetRootNameOfDirectory(), PicesInterface::OSservices.GetRootNameWithExtension(), PicesInterface::PicesDataBase.ImageLoad(), PicesInterface::PicesFeatureVector.ParseImageFileName(), PicesInterface::PicesDataBase.QueryStatement(), PicesInterface::OSservices.RenameFile(), PicesInterface::PicesDataBase.Server, PicesInterface::PicesRunLog.SetLoggingLevel(), PicesInterface::PicesSipperVariables.TempDirectory(), and PicesInterface::PicesRunLog.Writeln().
Member Function Documentation
override void PicesCommander.ReconcileImagesToDataBase.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file ReconcileImagesToDataBase.Designer.cs.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/ReconcileImagesToDataBase.cs
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/ReconcileImagesToDataBase.Designer.cs