Pices: SipperFile.TimePlot Class Reference
SipperFile.TimePlot Class Reference
Public Member Functions
TimePlot (SipperConfigRec _sipperConfigRec, InstrumentDataList _history)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void OnClosing (CancelEventArgs e)
Detailed Description
Definition at line 18 of file TimePlot.cs.
Constructor & Destructor Documentation
SipperFile.TimePlot.TimePlot (SipperConfigRec _sipperConfigRec, InstrumentDataList _history) inline
Definition at line 67 of file TimePlot.cs.
References PicesInterface::OSservices.AddSlash(), PicesInterface::PicesSipperVariables.ConfigurationDirectory(), and PicesInterface::OSservices.CreateDirectory().
Member Function Documentation
override void SipperFile.TimePlot.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file TimePlot.Designer.cs.
Referenced by SipperFileViewer.SipperFileViewer.SipperFileViewerRegionAroundImage().
override void SipperFile.TimePlot.OnClosing (CancelEventArgs e) inline protected
Definition at line 85 of file TimePlot.cs.
References SipperFile.TimePlotParameters.ClearPlotArea(), SipperFile.TimePlotParameters.ComputeColFromTime(), SipperFile.TimePlotParameters.ComputeDateTimeFromPixelCol(), SipperFile.TimePlotParameters.ComputeParameters(), SipperFile.InstrumentData.Data(), SipperFile.InstrumentData.FieldName(), SipperFile.InstrumentDataList.FindClosestEntryByTime(), SipperFile.InstrumentData.GetFieldNameIndex(), SipperFile.TimePlotParameters.MakeTimeVisible(), max, min, SipperFile.InstrumentData.NumDataFields(), SipperFile.TimePlotParameters.PaintSelectedLine(), SipperFile.TimePlotParameters.PlotBackgroundColor, SipperFile.TimePlotParameters.PlotDataRow(), SipperFile.TimePlotParameters.SetNewTimeLeft(), PicesInterface::PicesKKStr.StrToBool(), PicesInterface::PicesKKStr.StrToFloat(), PicesInterface::PicesKKStr.StrToInt(), SipperFile.InstrumentData.Time, SipperFile.TimePlotParameters.TimeLeft(), SipperFile.InstrumentDataList.TimeMax(), SipperFile.InstrumentDataList.TimeMin(), SipperFile.TimePlotParameters.TimeRange, and SipperFile.TimePlotParameters.TimeRight().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/SipperFile/TimePlot.cs
C:/Users/Kurt/GitHub/Pices/PicesLibraries/SipperFile/TimePlot.Designer.cs