Pices: PicesCommander.PicesCommander Class Reference
PicesCommander.PicesCommander Class Reference
Public Member Functions
PicesCommander ()
bool GetThumbnailImageAbort ()
void ThumbnailDataGridView_CellContentDoubleClick (object sender, DataGridViewCellEventArgs e)
void UpdateLastClassesValidated (PicesClass updatedClass)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Detailed Description
Definition at line 24 of file PicesCommander.cs.
Constructor & Destructor Documentation
PicesCommander.PicesCommander.PicesCommander () inline
Definition at line 119 of file PicesCommander.cs.
References PicesInterface::PicesClassStatisticList.Add(), PicesInterface::OSservices.AddSlash(), PicesInterface::PicesSipperVariables.AllowUpdates(), PicesCommander.PlanktonDepthStatisticsLoader.CancelLoadWait(), PicesCommander.PlanktonClassStatisticsLoader.CancelLoadWait(), PicesInterface::PicesClassStatistic.ClassName, PicesInterface::PicesSipperVariables.ConfigurationDirectory(), PicesInterface::PicesClassStatistic.Count, PicesInterface::PicesClassStatisticList.CountTotal, PicesCommander.ThumbNailImageCell.DisplayClass1(), PicesCommander.ThumbNailImageCell.DisplayClass2(), PicesInterface::TrainingModel2.GetListOfTrainingModels(), PicesInterface::OSservices.GetRootName(), PicesInterface::PicesSipperVariables.HomeDir(), PicesInterface::PicesVolumeSampledStatList.Locate(), PicesInterface::PicesClassList.LookUpIndex(), PicesInterface::TrainingModel2.MLClasses(), SipperFile.ActiveTrainingLibraries.Model1(), SipperFile.ActiveTrainingLibraries.Model1Name, SipperFile.ActiveTrainingLibraries.Model2Name, PicesInterface::TrainingModel2.ModelName, PicesInterface::PicesDataBaseImageList.PopulateComboBoxWithSortOrderOptions(), PicesInterface::PicesClassStatisticList.RemoveNoiseClasses(), PicesInterface::TrainingModel2.RootDir, PicesInterface::PicesClassStatisticList.SortByClassName(), PicesInterface::PicesDataBaseImageList.SortOrderTypeToStr(), PicesInterface::PicesClassStatisticList.Summarize(), and PicesInterface::PicesVolumeSampledStat.VolumeSampled.
Member Function Documentation
override void PicesCommander.PicesCommander.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file PicesCommander.Designer.cs.
bool PicesCommander.PicesCommander.GetThumbnailImageAbort () inline
Definition at line 492 of file PicesCommander.cs.
References PicesInterface::PicesDataBase.Close(), PicesInterface::PicesDataBaseImageGroup.Count, PicesInterface::PicesSipperCruise.CruiseName, PicesInterface::PicesSipperDeployment.DeploymentNum, PicesInterface::PicesDataBase.GetGlobalDatabaseManagerNewInstance(), PicesInterface::PicesDataBase.ImageGroupLoad(), PicesInterface::PicesDataBase.MLClassLoadList(), PicesInterface::PicesDataBaseImageGroup.Name, PicesInterface::PicesClass.Name, PicesInterface::PicesDataBase.SelectNewDataBaseServer(), PicesInterface::PicesDataBase.ServerDescription(), SipperFile.ActiveTrainingLibraries.SetModel1(), SipperFile.ActiveTrainingLibraries.SetModel2(), PicesInterface::PicesDataBase.SipperCruiseLoadAllCruises(), PicesInterface::PicesDataBase.SipperDeploymentLoad(), PicesInterface::PicesDataBase.SipperFileLoad(), PicesInterface::PicesDataBase.SipperStationLoad(), PicesInterface::PicesSipperStation.StationName, PicesInterface::PicesKKStr.StrToFloat(), PicesInterface::PicesKKStr.StrToInt(), PicesInterface::TrainingModel2.Valid, PicesInterface::PicesDataBase.Valid(), and PicesInterface::PicesRunLog.Writeln().
void PicesCommander.PicesCommander.ThumbnailDataGridView_CellContentDoubleClick (object sender, DataGridViewCellEventArgs e) inline
Definition at line 2205 of file PicesCommander.cs.
References PicesInterface::PicesDataBaseImageList.AddList(), PicesInterface::OSservices.AddSlash(), PicesCommander.ImportGroupAssignments.CancelBackGround, PicesCommander.Harvester.CancelHarvesting, PicesCommander.ImportValidatdClass.CancelImporting, PicesCommander.PlanktonDepthStatisticsLoader.CancelLoad(), PicesCommander.PlanktonClassStatisticsLoader.CancelLoad(), PicesCommander.PlanktonImageLoader.CancelLoad(), SipperFile.ActiveTrainingLibraries.CancelLoads(), PicesCommander.PlanktonDepthStatisticsLoader.CancelLoadWait(), PicesCommander.PlanktonClassStatisticsLoader.CancelLoadWait(), PicesCommander.PlanktonImageLoader.CancelLoadWait(), SipperFile.ActiveTrainingLibraries.CancelLoadWait(), PicesCommander.ClassificationStatus.CleanUpMemory(), PicesInterface::PicesDataBase.Close(), PicesInterface::PicesDataBase.CloseGlobalDbConn(), PicesInterface::PicesSipperVariables.CmdLineProgDir(), PicesInterface::OSservices.CreateDirectoryPath(), PicesInterface::PicesDataBase.FinalCleanUp(), PicesInterface::OSservices.GetRootName(), PicesCommander.PlanktonDepthStatisticsLoader.GetStatsAlreadyLoadedIfNew(), PicesCommander.PlanktonClassStatisticsLoader.GetStatsAlreadyLoadedIfNew(), PicesInterface::PicesClassList.GetUniqueClass(), PicesCommander.ImportGroupAssignments.Group, PicesCommander.Harvester.GroupNameSelected, PicesCommander.Harvester.HarvestedImages, PicesCommander.PlanktonDepthStatisticsLoader.LoaderThreadRuning, PicesCommander.PlanktonClassStatisticsLoader.LoaderThreadRuning, SipperFile.ActiveTrainingLibraries.Model1Name, SipperFile.ActiveTrainingLibraries.Model2Name, PicesInterface::PicesDataBaseImageGroup.Name, PicesInterface::PicesSipperVariables.PicesReportDir(), PicesCommander.DepthPlotDisplay.Show(), PicesInterface::PicesDataBase.SipperDeploymentLoad(), PicesInterface::PicesDataBaseImageList.Sort(), PicesInterface::PicesDataBaseImageList.SortOrderTypeFromStr(), PicesCommander.PlanktonDepthStatisticsLoader.Status(), PicesCommander.PlanktonClassStatisticsLoader.Status(), PicesInterface::PicesSipperVariables.TempDirectory(), PicesInterface::PicesSipperVariables.UpdatesNotAllowed(), and PicesCommander.PlanktonDepthStatisticsLoader.VolumeWaterSampled.
void PicesCommander.PicesCommander.UpdateLastClassesValidated (PicesClass updatedClass) inline
Definition at line 1133 of file PicesCommander.cs.
References PicesInterface::PicesDataBaseImageList.AddList(), PicesInterface::OSservices.AddSlash(), PicesInterface::PicesRaster.BuildBitmap(), PicesCommander.PlanktonImageLoader.CancelLoadWait(), PicesInterface::PicesDataBaseImage.Class1, PicesCommander.PlanktonImageLoader.CleanUpMemory(), PicesInterface::PicesDataBase.Close(), PicesInterface::PicesDataBase.CloseGlobalDbConn(), PicesInterface::PicesRaster.Color(), PicesCommander.PlanktonImageLoader.CurSipperFileName, PicesInterface::PicesDataBaseServer.Description, PicesInterface::TrainingModel2.DirectoryPathForClass(), SipperFile.DisplayPicesImages.Dispose(), PicesInterface::PicesRaster.DrawGrid(), PicesCommander.PlanktonImageLoader.GetImagesAlreadyLoaded(), PicesInterface::PicesClassList.GetUniqueClass(), PicesInterface::PicesDataBaseImage.ImageFileName, PicesInterface::PicesDataBase.ImageFullSizeFind(), PicesInterface::PicesDataBase.ImageRemoveValidation(), PicesInterface::PicesDataBase.ImagesDeleteOneImage(), PicesCommander.PlanktonImageLoader.ImagesLoadedCount, PicesInterface::PicesDataBase.ImagesUpdateValidatedClass(), PicesInterface::PicesDataBase.LastErrorDesc(), PicesInterface::PicesDataBase.LastOpSuccessful, PicesCommander.PlanktonImageLoader.LoaderThreadRuning, PicesInterface::PicesDataBase.MLClassLoad(), SipperFile.ActiveTrainingLibraries.Model1(), SipperFile.ActiveTrainingLibraries.Model1Name, SipperFile.ActiveTrainingLibraries.Model2(), SipperFile.ActiveTrainingLibraries.Model2Name, PicesInterface::PicesDataBaseImageGroup.Name, PicesInterface::PicesClass.Name, PicesInterface::PicesRaster.ReversedImage(), PicesInterface::PicesRaster.Save(), KKB.SaveImage(), SipperFile.SelectAPicesClass.SelectedClass, SipperFile.SelectAPicesClass.SelectionMade, PicesInterface::PicesDataBase.SelectNewDataBaseServer(), PicesInterface::PicesDataBase.Server, PicesCommander.VerifyImagesDeletion.Show(), PicesInterface::PicesDataBaseImage.SipperFileName, PicesCommander.PlanktonImageLoader.SipperFilesCount, PicesCommander.PlanktonImageLoader.SipperFilesLoaded, SipperFileViewer.SipperFileViewer.SipperFileViewerRegionAroundImage(), PicesInterface::PicesDataBaseImageList.Sort(), PicesInterface::PicesKKStr.StrToFloat(), PicesInterface::PicesKKStr.StrToInt(), PicesInterface::PicesRaster.ToColor(), PicesInterface::PicesDataBase.Valid(), and PicesInterface::PicesDataBaseImage.ValidatedClass.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/PicesCommander.cs
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/PicesCommander.Designer.cs