Pices: MLL::SipperDeployment Class Reference
MLL::SipperDeployment Class Reference
#include <SipperDeployment.h>
Public Types
typedef SipperDeployment * SipperDeploymentPtr
Public Member Functions
SipperDeployment ()
~SipperDeployment ()
float ChamberWidth () const
Width of sampling caber in Mili-Meters.
void ChamberWidth (float _chamberWidth)
KKB::kkuint32 CropLeft () const
void CropLeft (KKB::kkuint32 _cropLeft)
KKB::kkuint32 CropRight () const
void CropRight (KKB::kkuint32 _cropRight)
const KKStr & CruiseName () const
void CruiseName (const KKStr &_cruiseName)
const KKB::DateTime & DateTimeEnd () const
void DateTimeEnd (const KKB::DateTime &_dateTimeEnd)
const KKB::DateTime & DateTimeStart () const
void DateTimeStart (const KKB::DateTime &_dateTimeStart)
const KKStr & DeploymentNum () const
void DeploymentNum (const KKStr &_deploymentNum)
const KKStr & Description () const
void Description (const KKStr &_description)
double Latitude () const
void Latitude (double _latitude)
double Longitude () const
void Longitude (double _longitude)
const KKStr & StationName () const
void StationName (const KKStr &_stationName)
const KKB::DateTime & SyncTimeStampActual () const
void SyncTimeStampActual (const KKB::DateTime &_syncTimeStampActual)
const KKB::DateTime & SyncTimeStampCTD () const
void SyncTimeStampCTD (const KKB::DateTime &_syncTimeStampCTD)
const KKB::DateTime & SyncTimeStampGPS () const
void SyncTimeStampGPS (const KKB::DateTime &_syncTimeStampGPS)
Detailed Description
Definition at line 11 of file SipperDeployment.h.
Member Typedef Documentation
typedef SipperDeployment* MLL::SipperDeployment::SipperDeploymentPtr
Definition at line 14 of file SipperDeployment.h.
Constructor & Destructor Documentation
SipperDeployment::SipperDeployment ()
Definition at line 23 of file SipperDeployment.cpp.
References KKB::osGetLocalDateTime().
SipperDeployment::~SipperDeployment ()
Definition at line 48 of file SipperDeployment.cpp.
Member Function Documentation
float MLL::SipperDeployment::ChamberWidth () const inline
Width of sampling caber in Mili-Meters.
Definition at line 32 of file SipperDeployment.h.
Referenced by MLL::DataBase::ImageGroupEntriesLoad(), MLL::DataBase::SipperDeploymentInsert(), and MLL::DataBase::SipperDeploymentUpdate().
void MLL::SipperDeployment::ChamberWidth (float _chamberWidth) inline
Definition at line 47 of file SipperDeployment.h.
KKB::kkuint32 MLL::SipperDeployment::CropLeft () const inline
Definition at line 30 of file SipperDeployment.h.
Referenced by MLL::DataBase::ImageGroupEntriesLoad(), MLL::DataBase::SipperDeploymentInsert(), and MLL::DataBase::SipperDeploymentUpdate().
void MLL::SipperDeployment::CropLeft (KKB::kkuint32 _cropLeft) inline
Definition at line 45 of file SipperDeployment.h.
KKB::kkuint32 MLL::SipperDeployment::CropRight () const inline
Definition at line 31 of file SipperDeployment.h.
Referenced by MLL::DataBase::ImageGroupEntriesLoad(), MLL::DataBase::SipperDeploymentInsert(), and MLL::DataBase::SipperDeploymentUpdate().
void MLL::SipperDeployment::CropRight (KKB::kkuint32 _cropRight) inline
Definition at line 46 of file SipperDeployment.h.
const KKStr& MLL::SipperDeployment::CruiseName () const inline
Definition at line 19 of file SipperDeployment.h.
Referenced by PicesInterface::PicesSipperDeployment::!PicesSipperDeployment(), MLL::DataBase::ImageGroupEntriesLoad(), PicesInterface::PicesSipperDeployment::PicesSipperDeployment(), MLL::DataBase::SipperDeploymentInsert(), MLL::DataBase::SipperDeploymentUpdate(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void MLL::SipperDeployment::CruiseName (const KKStr & _cruiseName) inline
Definition at line 34 of file SipperDeployment.h.
const KKB::DateTime& MLL::SipperDeployment::DateTimeEnd () const inline
Definition at line 26 of file SipperDeployment.h.
Referenced by PicesInterface::PicesSipperDeployment::!PicesSipperDeployment(), MLL::DataBase::ImageGroupEntriesLoad(), MLL::DataBase::SipperDeploymentInsert(), MLL::DataBase::SipperDeploymentUpdate(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void MLL::SipperDeployment::DateTimeEnd (const KKB::DateTime & _dateTimeEnd) inline
Definition at line 41 of file SipperDeployment.h.
const KKB::DateTime& MLL::SipperDeployment::DateTimeStart () const inline
Definition at line 25 of file SipperDeployment.h.
Referenced by PicesInterface::PicesSipperDeployment::!PicesSipperDeployment(), MLL::DataBase::ImageGroupEntriesLoad(), MLL::DataBase::SipperDeploymentInsert(), MLL::DataBase::SipperDeploymentUpdate(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void MLL::SipperDeployment::DateTimeStart (const KKB::DateTime & _dateTimeStart) inline
Definition at line 40 of file SipperDeployment.h.
const KKStr& MLL::SipperDeployment::DeploymentNum () const inline
Definition at line 21 of file SipperDeployment.h.
Referenced by PicesInterface::PicesSipperDeployment::!PicesSipperDeployment(), MLL::DataBase::ImageGroupEntriesLoad(), MLL::DataBase::SipperDeploymentInsert(), MLL::DataBase::SipperDeploymentUpdate(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void MLL::SipperDeployment::DeploymentNum (const KKStr & _deploymentNum) inline
Definition at line 36 of file SipperDeployment.h.
const KKStr& MLL::SipperDeployment::Description () const inline
Definition at line 22 of file SipperDeployment.h.
Referenced by PicesInterface::PicesSipperDeployment::!PicesSipperDeployment(), MLL::DataBase::ImageGroupEntriesLoad(), MLL::DataBase::SipperDeploymentInsert(), MLL::DataBase::SipperDeploymentUpdate(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void MLL::SipperDeployment::Description (const KKStr & _description) inline
Definition at line 37 of file SipperDeployment.h.
double MLL::SipperDeployment::Latitude () const inline
Definition at line 23 of file SipperDeployment.h.
Referenced by PicesInterface::PicesSipperDeployment::!PicesSipperDeployment(), MLL::DataBase::ImageGroupEntriesLoad(), MLL::DataBase::SipperDeploymentInsert(), MLL::DataBase::SipperDeploymentUpdate(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void MLL::SipperDeployment::Latitude (double _latitude) inline
Definition at line 38 of file SipperDeployment.h.
double MLL::SipperDeployment::Longitude () const inline
Definition at line 24 of file SipperDeployment.h.
Referenced by PicesInterface::PicesSipperDeployment::!PicesSipperDeployment(), MLL::DataBase::ImageGroupEntriesLoad(), MLL::DataBase::SipperDeploymentInsert(), MLL::DataBase::SipperDeploymentUpdate(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void MLL::SipperDeployment::Longitude (double _longitude) inline
Definition at line 39 of file SipperDeployment.h.
const KKStr& MLL::SipperDeployment::StationName () const inline
Definition at line 20 of file SipperDeployment.h.
Referenced by PicesInterface::PicesSipperDeployment::!PicesSipperDeployment(), MLL::DataBase::ImageGroupEntriesLoad(), PicesInterface::PicesSipperDeployment::PicesSipperDeployment(), MLL::DataBase::SipperDeploymentInsert(), MLL::DataBase::SipperDeploymentUpdate(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void MLL::SipperDeployment::StationName (const KKStr & _stationName) inline
Definition at line 35 of file SipperDeployment.h.
const KKB::DateTime& MLL::SipperDeployment::SyncTimeStampActual () const inline
Definition at line 27 of file SipperDeployment.h.
Referenced by PicesInterface::PicesSipperDeployment::!PicesSipperDeployment(), MLL::DataBase::ImageGroupEntriesLoad(), MLL::DataBase::SipperDeploymentInsert(), MLL::DataBase::SipperDeploymentUpdate(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void MLL::SipperDeployment::SyncTimeStampActual (const KKB::DateTime & _syncTimeStampActual) inline
Definition at line 42 of file SipperDeployment.h.
const KKB::DateTime& MLL::SipperDeployment::SyncTimeStampCTD () const inline
Definition at line 28 of file SipperDeployment.h.
Referenced by PicesInterface::PicesSipperDeployment::!PicesSipperDeployment(), MLL::DataBase::ImageGroupEntriesLoad(), MLL::DataBase::SipperDeploymentInsert(), MLL::DataBase::SipperDeploymentUpdate(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void MLL::SipperDeployment::SyncTimeStampCTD (const KKB::DateTime & _syncTimeStampCTD) inline
Definition at line 43 of file SipperDeployment.h.
const KKB::DateTime& MLL::SipperDeployment::SyncTimeStampGPS () const inline
Definition at line 29 of file SipperDeployment.h.
Referenced by PicesInterface::PicesSipperDeployment::!PicesSipperDeployment(), MLL::DataBase::ImageGroupEntriesLoad(), MLL::DataBase::SipperDeploymentInsert(), MLL::DataBase::SipperDeploymentUpdate(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void MLL::SipperDeployment::SyncTimeStampGPS (const KKB::DateTime & _syncTimeStampGPS) inline
Definition at line 44 of file SipperDeployment.h.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/SipperDeployment.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/SipperDeployment.cpp