Pices: MLL::InstrumentDataPitchAndRoll Class Reference
MLL::InstrumentDataPitchAndRoll Class Reference
#include <InstrumentDataPitchAndRoll.h>
Public Types
typedef
InstrumentDataPitchAndRoll * InstrumentDataPitchAndRollPtr
Public Types inherited from MLL::InstrumentDataReport
typedef InstrumentDataReport * InstrumentDataReportPtr
typedef KKB::kkint32 kkint32
typedef KKB::kkuint32 kkuint32
Public Member Functions
InstrumentDataPitchAndRoll (InstrumentDataManagerPtr _manager, const KKStr &_reportDir, bool _text, kkint32 _instrumentId)
virtual ~InstrumentDataPitchAndRoll ()
virtual void ReportInstrumentData (kkuint32 curScanLine, uchar sensorData)
Public Member Functions inherited from MLL::InstrumentDataReport
InstrumentDataReport (InstrumentDataManagerPtr _manager, const KKStr &_reportDir, bool _text, kkint32 _instrumentId, bool _useReportWithLineNumbers)
virtual ~InstrumentDataReport ()
const KKStr & CurTextLine ()
const KKStr & LastTextLine ()
Additional Inherited Members
Static Public Member Functions inherited from MLL::InstrumentDataReport
static InstrumentDataReportPtr CreateInstrumentDataReport (InstrumentDataManagerPtr _manager, const KKStr &_reportDir, bool _text, kkint32 _instrumentId)
A virtual Constructor for InstrumentDataReport instances.
Protected Member Functions inherited from MLL::InstrumentDataReport
KKStr InstrumentName ()
Protected Attributes inherited from MLL::InstrumentDataReport
KKStr curTextLine
Used where "text == true", Every time a character is read via 'ReportInstrumentData' will append to end of string.
kkint32 instrumentId
kkuint32 lastScanLineReported
KKStr lastTextLine
Used where "text == true", will keep an instance of last complete text line read.
InstrumentDataManagerPtr manager
ofstream report
KKStr reportFileName
KKStr reportFileNameWLN
ofstream reportWLN
bool text
bool useReportWithLineNumbers
Static Protected Attributes inherited from MLL::InstrumentDataReport
static const char * InstrumentNames []
Detailed Description
Definition at line 12 of file InstrumentDataPitchAndRoll.h.
Member Typedef Documentation
typedef InstrumentDataPitchAndRoll* MLL::InstrumentDataPitchAndRoll::InstrumentDataPitchAndRollPtr
Definition at line 15 of file InstrumentDataPitchAndRoll.h.
Constructor & Destructor Documentation
InstrumentDataPitchAndRoll::InstrumentDataPitchAndRoll (InstrumentDataManagerPtr _manager, const KKStr & _reportDir, bool _text, kkint32 _instrumentId)
Definition at line 24 of file InstrumentDataPitchAndRoll.cpp.
InstrumentDataPitchAndRoll::~InstrumentDataPitchAndRoll () virtual
Definition at line 40 of file InstrumentDataPitchAndRoll.cpp.
References MLL::InstrumentDataReport::report.
Member Function Documentation
void InstrumentDataPitchAndRoll::ReportInstrumentData (kkuint32 curScanLine, uchar sensorData) virtual
Reimplemented from MLL::InstrumentDataReport.
Definition at line 93 of file InstrumentDataPitchAndRoll.cpp.
References KKB::KKStr::Append(), KKB::KKStr::Empty(), KKB::endl(), and MLL::InstrumentDataReport::report.
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/InstrumentDataPitchAndRoll.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/InstrumentDataPitchAndRoll.cpp