Pices: PicesCommander.PlanktonImageLoader Class Reference
PicesCommander.PlanktonImageLoader Class Reference
Public Member Functions
PlanktonImageLoader (PicesDataBaseImageGroup _selectedImageGroup, String _cruiseName, String _stationName, String _deploymentNum, String _sipperFileName, PicesClass _mlClass, char _classKeyToUse, float _probMin, float _probMax, int _sizeMin, int _sizeMax, float _depthMin, float _depthMax, uint _restartImageId)
Starts the thread that loads images that are to be displayd on the thumbnail viewer.
delegate void AlertCompletion (PlanktonImageLoader sender)
void CancelLoad ()
void CancelLoadWait (int maxMilliSecsToWait)
void CleanUpMemory ()
PicesDataBaseImageList GetImagesAlreadyLoaded ()
Return to caller list of images that have been loaded so far by the LoadImagesThread.
Properties
bool CancelRequested [get]
AlertCompletion CompletionEvent [get, set]
String CurSipperFileName [get]
bool DoneLoading [get]
int ImagesLoadedCount [get]
bool LoaderThreadRuning [get]
int SipperFilesCount [get]
int SipperFilesLoaded [get]
Detailed Description
Definition at line 19 of file PlanktonImageLoader.cs.
Constructor & Destructor Documentation
PicesCommander.PlanktonImageLoader.PlanktonImageLoader (PicesDataBaseImageGroup _selectedImageGroup, String _cruiseName, String _stationName, String _deploymentNum, String _sipperFileName, PicesClass _mlClass, char _classKeyToUse, float _probMin, float _probMax, int _sizeMin, int _sizeMax, float _depthMin, float _depthMax, uint _restartImageId) inline
Starts the thread that loads images that are to be displayd on the thumbnail viewer.
Parameters
_selectedImageGroup
_cruiseName
_stationName
_deploymentNum
_sipperFileName
_mlClass
_classKeyToUse
_probMin
_probMax
_sizeMin
_sizeMax
_depthMin
_depthMax
_restartImageId
Definition at line 102 of file PlanktonImageLoader.cs.
Member Function Documentation
delegate void PicesCommander.PlanktonImageLoader.AlertCompletion (PlanktonImageLoader sender)
void PicesCommander.PlanktonImageLoader.CancelLoad () inline
Definition at line 154 of file PlanktonImageLoader.cs.
Referenced by PicesCommander.PlanktonImageLoader.CancelLoadWait(), and PicesCommander.PicesCommander.ThumbnailDataGridView_CellContentDoubleClick().
void PicesCommander.PlanktonImageLoader.CancelLoadWait (int maxMilliSecsToWait) inline
Definition at line 160 of file PlanktonImageLoader.cs.
References PicesCommander.PlanktonImageLoader.CancelLoad().
Referenced by PicesCommander.PlanktonImageLoader.CleanUpMemory(), PicesCommander.PicesCommander.ThumbnailDataGridView_CellContentDoubleClick(), and PicesCommander.PicesCommander.UpdateLastClassesValidated().
void PicesCommander.PlanktonImageLoader.CleanUpMemory () inline
Definition at line 143 of file PlanktonImageLoader.cs.
References PicesCommander.PlanktonImageLoader.CancelLoadWait(), and PicesInterface::PicesDataBaseImageList.CleanUpMemory().
Referenced by PicesCommander.PicesCommander.UpdateLastClassesValidated().
PicesDataBaseImageList PicesCommander.PlanktonImageLoader.GetImagesAlreadyLoaded () inline
Return to caller list of images that have been loaded so far by the LoadImagesThread.
Images are loaded by a seprate thread; these images are loaded into loadedImages . Images accumulate into it until ther are retrived by this method.
Returns
List of images loaded since the last call.
Definition at line 190 of file PlanktonImageLoader.cs.
References PicesInterface::PicesDataBase.Close(), PicesInterface::PicesGoalKeeper.EndBlock(), PicesInterface::PicesDataBase.GetGlobalDatabaseManagerNewInstance(), PicesInterface::PicesDataBaseImage.ImageId, PicesInterface::PicesDataBase.ImagesQuery(), PicesInterface::PicesDataBase.ImagesQueryByGrouop(), PicesInterface::PicesDataBase.SipperFileGetList(), PicesInterface::PicesGoalKeeper.StartBlock(), PicesInterface::PicesDataBase.ThreadEnd(), and PicesInterface::PicesDataBase.ThreadInit().
Referenced by PicesCommander.PicesCommander.UpdateLastClassesValidated().
Property Documentation
bool PicesCommander.PlanktonImageLoader.CancelRequested get
Definition at line 59 of file PlanktonImageLoader.cs.
AlertCompletion PicesCommander.PlanktonImageLoader.CompletionEvent get set
Definition at line 61 of file PlanktonImageLoader.cs.
String PicesCommander.PlanktonImageLoader.CurSipperFileName get
Definition at line 60 of file PlanktonImageLoader.cs.
Referenced by PicesCommander.PicesCommander.UpdateLastClassesValidated().
bool PicesCommander.PlanktonImageLoader.DoneLoading get
Definition at line 62 of file PlanktonImageLoader.cs.
int PicesCommander.PlanktonImageLoader.ImagesLoadedCount get
Definition at line 64 of file PlanktonImageLoader.cs.
Referenced by PicesCommander.PicesCommander.UpdateLastClassesValidated().
bool PicesCommander.PlanktonImageLoader.LoaderThreadRuning get
Definition at line 63 of file PlanktonImageLoader.cs.
Referenced by PicesCommander.PicesCommander.UpdateLastClassesValidated().
int PicesCommander.PlanktonImageLoader.SipperFilesCount get
Definition at line 66 of file PlanktonImageLoader.cs.
Referenced by PicesCommander.PicesCommander.UpdateLastClassesValidated().
int PicesCommander.PlanktonImageLoader.SipperFilesLoaded get
Definition at line 67 of file PlanktonImageLoader.cs.
Referenced by PicesCommander.PicesCommander.UpdateLastClassesValidated().
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/PlanktonImageLoader.cs