Pices: FeatureSelectionApp::RandomSplitResults Class Reference
FeatureSelectionApp::RandomSplitResults Class Reference
Where results for a JobRandomSplits are stored.
#include <RandomSplitResults.h>
Public Types
typedef RandomSplitResults * RandomSplitResultsPtr
Public Types inherited from FeatureSelectionApp::Results
typedef Results * ResultsPtr
Public Member Functions
RandomSplitResults (RunLog &_log)
RandomSplitResults (FinalResultType _resultType, TrainingConfiguration2Ptr _config, CrossValidationPtr _crossValidation, FeatureVectorListPtr _trainData, const KKStr &_hostName, JobRandomSplitPtr _job, RunLog &_log)
virtual ~RandomSplitResults ()
int SplitNum () const
void Write (ostream &o)
Public Member Functions inherited from FeatureSelectionApp::Results
Results (RunLog &_log)
Results (FinalResultType _resultType, TrainingConfiguration2Ptr _config, CrossValidationPtr _crossValidation, FeatureVectorListPtr _trainData, const KKStr &_hostName, BinaryJobPtr _job, RunLog &_log)
virtual ~Results ()
float Accuracy () const
VectorFloat AccuracyByClass () const
float AccuracyNorm () const
const KKStr & ConfigFileName () const
ConfusionMatrix2Ptr ConfusionMatrix () const
KKStr Description () const
const KKStr & HostName () const
int JobId () const
SVM_MachineType MachineType () const
KKStr MachineTypeStr () const
MLClassListPtr MLClasses () const
Creates a List of Classes from associated Confusion Matrix.
double NumFeatures () const
float NumFeaturesWeighted () const
double NumSupportVectors () const
double NumSVs () const
Results & operator+= (const Results &right)
Results & operator/= (float divisor)
Results & operator/= (int divisor)
FinalResultType ResultType () const
KKStr ResultTypeStr () const
SVM_SelectionMethod SelectionMethod () const
KKStr SelectionMethodStr () const
KKStr SvmParameters () const
double TestTime () const
double TotalNumSVs () const
double TrainingTime () const
Static Public Member Functions
static RandomSplitResultsPtr ConstructFromStream (istream &i, RunLog &log)
Static Public Member Functions inherited from FeatureSelectionApp::Results
static ResultsPtr ConstructFromStream (istream &i, RunLog &log)
Detailed Description
Where results for a JobRandomSplits are stored.
Used to store rsults from a single RandomSplit job (JobRandomSplit).   *
Will hold both ConfusionMatrix and CrossValiodation Results(such as)   *
TrainingTime, TestTime, Number Support Vectors, etc.                   *
These results will be written to a file by 'JobRandomSplit' as each    *
node is evaluated.                                                     *
Definition at line 26 of file RandomSplitResults.h.
Member Typedef Documentation
typedef RandomSplitResults* FeatureSelectionApp::RandomSplitResults::RandomSplitResultsPtr
Definition at line 29 of file RandomSplitResults.h.
Constructor & Destructor Documentation
RandomSplitResults::RandomSplitResults (RunLog & _log)
Definition at line 43 of file RandomSplitResults.cpp.
Referenced by ConstructFromStream().
RandomSplitResults::RandomSplitResults (FinalResultType _resultType, TrainingConfiguration2Ptr _config, CrossValidationPtr _crossValidation, FeatureVectorListPtr _trainData, const KKStr & _hostName, JobRandomSplitPtr _job, RunLog & _log)
Definition at line 50 of file RandomSplitResults.cpp.
References FeatureSelectionApp::JobRandomSplit::SplitNum().
RandomSplitResults::~RandomSplitResults () virtual
Definition at line 68 of file RandomSplitResults.cpp.
Member Function Documentation
RandomSplitResultsPtr RandomSplitResults::ConstructFromStream (istream & i, RunLog & log) static
Definition at line 114 of file RandomSplitResults.cpp.
References RandomSplitResults().
int FeatureSelectionApp::RandomSplitResults::SplitNum () const inline
Definition at line 50 of file RandomSplitResults.h.
void RandomSplitResults::Write (ostream & o) virtual
Reimplemented from FeatureSelectionApp::Results.
Definition at line 75 of file RandomSplitResults.cpp.
References KKB::endl(), and FeatureSelectionApp::Results::Write().
Referenced by FeatureSelectionApp::JobRandomSplit::EvaluateNode().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/Apps/FeatureSelection/RandomSplitResults.h
C:/Users/kurtk_000/GitHub/Pices/Apps/FeatureSelection/RandomSplitResults.cpp