Pices: KKB::RBTree< Entry, CompareNodes, KeyType > Class Template Reference
KKB::RBTree< Entry, CompareNodes, KeyType > Class Template Reference
#include <RBTree.h>
Public Types
typedef Entry * EntryPtr
typedef Iterator< Entry, CompareNodes, KeyType > * IteratorPtr
typedef RBnode< Entry > Node
typedef Node * NodePtr
typedef RBTree< Entry, CompareNodes, KeyType > Tree
typedef Tree * TreePtr
Public Member Functions
RBTree (CompareNodes &_comparator, bool _owner)
RBTree (RBTree &tree)
~RBTree ()
void CalcTreeStats ()
bool CompareToTree (TreePtr tree)
void DeleteCurrentNode ()
void DeleteEntry (EntryPtr e)
EntryPtr GetEqual (const KeyType &key)
EntryPtr GetFirst ()
EntryPtr GetGreater (const KeyType &key)
EntryPtr GetGreaterOrEqual (const KeyType &key)
EntryPtr GetLast ()
EntryPtr GetLess (const KeyType &key)
EntryPtr GetNext ()
EntryPtr GetPrev ()
EntryPtr Predecessor ()
NodePtr RBInsert (EntryPtr e)
kkuint32 Size ()
EntryPtr Successor ()
bool Validate ()
void WalkTree ()
Friends
class Iterator< Entry, CompareNodes, KeyType >
Detailed Description
template<class Entry, class CompareNodes, typename KeyType>
class KKB::RBTree< Entry, CompareNodes, KeyType >
Definition at line 69 of file RBTree.h.
Member Typedef Documentation
template<class Entry, class CompareNodes, typename KeyType> typedef Entry* KKB::RBTree< Entry, CompareNodes, KeyType >::EntryPtr
Definition at line 122 of file RBTree.h.
template<class Entry, class CompareNodes, typename KeyType> typedef Iterator<Entry,CompareNodes,KeyType>* KKB::RBTree< Entry, CompareNodes, KeyType >::IteratorPtr
Definition at line 176 of file RBTree.h.
template<class Entry, class CompareNodes, typename KeyType> typedef RBnode<Entry> KKB::RBTree< Entry, CompareNodes, KeyType >::Node
Definition at line 123 of file RBTree.h.
template<class Entry, class CompareNodes, typename KeyType> typedef Node* KKB::RBTree< Entry, CompareNodes, KeyType >::NodePtr
Definition at line 124 of file RBTree.h.
template<class Entry, class CompareNodes, typename KeyType> typedef RBTree<Entry,CompareNodes,KeyType> KKB::RBTree< Entry, CompareNodes, KeyType >::Tree
Definition at line 126 of file RBTree.h.
template<class Entry, class CompareNodes, typename KeyType> typedef Tree* KKB::RBTree< Entry, CompareNodes, KeyType >::TreePtr
Definition at line 128 of file RBTree.h.
Constructor & Destructor Documentation
template<class Entry , class CompareNodes, typename KeyType > KKB::RBTree< Entry, CompareNodes, KeyType >::RBTree (CompareNodes & _comparator, bool _owner)
Definition at line 298 of file RBTree.h.
References KKB::Black.
template<class Entry , class CompareNodes, typename KeyType > KKB::RBTree< Entry, CompareNodes, KeyType >::RBTree (RBTree< Entry, CompareNodes, KeyType > & tree)
Definition at line 319 of file RBTree.h.
References KKB::Black, KKB::RBnode< Entry >::Color(), KKB::RBnode< Entry >::Data(), KKB::RBnode< Entry >::Left(), and KKB::RBnode< Entry >::Right().
template<class Entry , class CompareNodes , typename KeyType > KKB::RBTree< Entry, CompareNodes, KeyType >::~RBTree ()
Definition at line 370 of file RBTree.h.
References KKB::RBnode< Entry >::Data(), KKB::RBnode< Entry >::Left(), and KKB::RBnode< Entry >::Right().
Member Function Documentation
template<class Entry , class CompareNodes , typename KeyType > void KKB::RBTree< Entry, CompareNodes, KeyType >::CalcTreeStats ()
Definition at line 1393 of file RBTree.h.
References KKB::endl(), INT_MAX, KKB::RBnode< Entry >::Left(), and KKB::RBnode< Entry >::Right().
template<class Entry , class CompareNodes , typename KeyType > bool KKB::RBTree< Entry, CompareNodes, KeyType >::CompareToTree (TreePtr tree)
Definition at line 409 of file RBTree.h.
References KKB::RBnode< Entry >::Data(), KKB::RBTree< Entry, CompareNodes, KeyType >::GetEqual(), KKB::RBnode< Entry >::Left(), and KKB::RBnode< Entry >::Right().
template<class Entry , class CompareNodes , typename KeyType > void KKB::RBTree< Entry, CompareNodes, KeyType >::DeleteCurrentNode ()
Definition at line 718 of file RBTree.h.
References KKB::RBnode< Entry >::Data(), KKB::endl(), KKB::RBTree< Entry, CompareNodes, KeyType >::Predecessor(), and KKB::RBTree< Entry, CompareNodes, KeyType >::Successor().
template<class Entry , class CompareNodes , typename KeyType > void KKB::RBTree< Entry, CompareNodes, KeyType >::DeleteEntry (EntryPtr e)
Definition at line 1382 of file RBTree.h.
template<class Entry , class CompareNodes , typename KeyType> Entry * KKB::RBTree< Entry, CompareNodes, KeyType >::GetEqual (const KeyType & key)
Definition at line 493 of file RBTree.h.
References KKB::RBnode< Entry >::Data(), KKB::RBTree< Entry, CompareNodes, KeyType >::GetGreater(), KKB::RBTree< Entry, CompareNodes, KeyType >::GetGreaterOrEqual(), KKB::RBnode< Entry >::Left(), and KKB::RBnode< Entry >::Right().
Referenced by KKMLL::DuplicateImages::AddSingleExample(), KKB::RBTree< Entry, CompareNodes, KeyType >::CompareToTree(), and KKMLL::DuplicateImages::ExampleInDetector().
template<class Entry , class CompareNodes , typename KeyType > Entry * KKB::RBTree< Entry, CompareNodes, KeyType >::GetFirst ()
Definition at line 763 of file RBTree.h.
References KKB::RBnode< Entry >::Data().
template<class Entry , class CompareNodes , typename KeyType> Entry * KKB::RBTree< Entry, CompareNodes, KeyType >::GetGreater (const KeyType & key)
Definition at line 598 of file RBTree.h.
References KKB::RBnode< Entry >::Data().
Referenced by KKB::RBTree< Entry, CompareNodes, KeyType >::GetEqual().
template<class Entry , class CompareNodes , typename KeyType> Entry * KKB::RBTree< Entry, CompareNodes, KeyType >::GetGreaterOrEqual (const KeyType & key)
Definition at line 608 of file RBTree.h.
References KKB::RBnode< Entry >::Data(), KKB::RBTree< Entry, CompareNodes, KeyType >::GetLess(), KKB::RBnode< Entry >::Left(), KKB::RBnode< Entry >::Right(), and KKB::RBTree< Entry, CompareNodes, KeyType >::Successor().
Referenced by KKB::RBTree< Entry, CompareNodes, KeyType >::GetEqual().
template<class Entry , class CompareNodes , typename KeyType > Entry * KKB::RBTree< Entry, CompareNodes, KeyType >::GetLast ()
Definition at line 776 of file RBTree.h.
References KKB::RBnode< Entry >::Data(), KKB::endl(), KKB::RBnode< Entry >::Left(), KKB::RBnode< Entry >::Parent(), KKB::RBTree< Entry, CompareNodes, KeyType >::Predecessor(), KKB::Red, KKB::RBnode< Entry >::Right(), and KKB::RBTree< Entry, CompareNodes, KeyType >::Successor().
template<class Entry , class CompareNodes , typename KeyType> Entry * KKB::RBTree< Entry, CompareNodes, KeyType >::GetLess (const KeyType & key)
Definition at line 669 of file RBTree.h.
References KKB::RBnode< Entry >::Data().
Referenced by KKB::RBTree< Entry, CompareNodes, KeyType >::GetGreaterOrEqual().
template<class Entry, class CompareNodes, typename KeyType> EntryPtr KKB::RBTree< Entry, CompareNodes, KeyType >::GetNext () inline
Definition at line 164 of file RBTree.h.
template<class Entry, class CompareNodes, typename KeyType> EntryPtr KKB::RBTree< Entry, CompareNodes, KeyType >::GetPrev () inline
Definition at line 166 of file RBTree.h.
template<class Entry , class CompareNodes , typename KeyType > Entry * KKB::RBTree< Entry, CompareNodes, KeyType >::Predecessor ()
Definition at line 682 of file RBTree.h.
References KKB::RBnode< Entry >::Data().
Referenced by KKB::RBTree< Entry, CompareNodes, KeyType >::DeleteCurrentNode(), and KKB::RBTree< Entry, CompareNodes, KeyType >::GetLast().
template<class Entry , class CompareNodes , typename KeyType > KKB::RBnode< Entry > * KKB::RBTree< Entry, CompareNodes, KeyType >::RBInsert (EntryPtr e)
Definition at line 1111 of file RBTree.h.
References KKB::Black, KKB::RBnode< Entry >::Color(), KKB::RBnode< Entry >::Data(), KKB::endl(), KKB::RBnode< Entry >::Left(), KKB::RBnode< Entry >::Parent(), KKB::Red, KKB::RBnode< Entry >::Right(), KKB::RBTree< Entry, CompareNodes, KeyType >::Successor(), and KKB::RBTree< Entry, CompareNodes, KeyType >::WalkTree().
Referenced by KKMLL::DuplicateImages::AddSingleExample().
template<class Entry, class CompareNodes, typename KeyType> kkuint32 KKB::RBTree< Entry, CompareNodes, KeyType >::Size () inline
Definition at line 140 of file RBTree.h.
template<class Entry , class CompareNodes , typename KeyType > Entry * KKB::RBTree< Entry, CompareNodes, KeyType >::Successor ()
Definition at line 700 of file RBTree.h.
References KKB::RBnode< Entry >::Data().
Referenced by KKB::RBTree< Entry, CompareNodes, KeyType >::DeleteCurrentNode(), KKB::RBTree< Entry, CompareNodes, KeyType >::GetGreaterOrEqual(), KKB::RBTree< Entry, CompareNodes, KeyType >::GetLast(), and KKB::RBTree< Entry, CompareNodes, KeyType >::RBInsert().
template<class Entry , class CompareNodes , typename KeyType > bool KKB::RBTree< Entry, CompareNodes, KeyType >::Validate ()
Definition at line 1483 of file RBTree.h.
References KKB::Black, KKB::RBnode< Entry >::Color(), KKB::RBnode< Entry >::Data(), KKB::endl(), KKB::RBnode< Entry >::Left(), KKB::RBnode< Entry >::Parent(), and KKB::RBnode< Entry >::Right().
template<class Entry, class CompareNodes, typename KeyType> void KKB::RBTree< Entry, CompareNodes, KeyType >::WalkTree () inline
Definition at line 142 of file RBTree.h.
Referenced by KKB::RBTree< Entry, CompareNodes, KeyType >::RBInsert(), and KKB::RBTree< FeatureVector, ExtractExampleFileName, KKStr >::WalkTree().
Friends And Related Function Documentation
template<class Entry, class CompareNodes, typename KeyType> friend class Iterator< Entry, CompareNodes, KeyType > friend
Definition at line 130 of file RBTree.h.
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/RBTree.h