Pices: PicesInterface::PicesMsgQueue Class Reference
PicesInterface::PicesMsgQueue Class Reference
#include <PicesMsgQueue.h>
Public Member Functions
PicesMsgQueue (String^ name)
!PicesMsgQueue ()
~PicesMsgQueue ()
void AddMsg (String^ msg)
void AddMsgs (List< String^ >^msgs)
void Close ()
summary> Returns a copy of the string last added to the message queue; will not effect the current copy of the message queue.
String^ GetCopyOfLastMsg ()
summary> Removes from the queue the oldest message added to the queue that has not been removed.
String^ GetNextMsg ()
MsgQueuePtr MsgQueue ()
Detailed Description
Definition at line 16 of file PicesMsgQueue.h.
Constructor & Destructor Documentation
PicesMsgQueue::PicesMsgQueue (String^ name)
Definition at line 32 of file PicesMsgQueue.cpp.
PicesMsgQueue::!PicesMsgQueue ()
Definition at line 39 of file PicesMsgQueue.cpp.
PicesMsgQueue::~PicesMsgQueue ()
Definition at line 45 of file PicesMsgQueue.cpp.
Member Function Documentation
void PicesMsgQueue::AddMsg (String^ msg)
Definition at line 92 of file PicesMsgQueue.cpp.
Referenced by PicesCommander.ChartAbundanceByDeployment::ChartAbundanceByDeployment(), PicesCommander.ChartAbundancePredictedAndValidated::ChartAbundancePredictedAndValidated(), PicesCommander.ChartDistribution::ChartDistribution(), PicesCommander.ChartGPS::ChartGPS(), PicesCommander.ChartGPSByStation::ChartGPSByStation(), PicesCommander.ChartHorizontalProfile::ChartHorizontalProfile(), PicesCommander.ChartSizeDistribution::ChartSizeDistribution(), PicesCommander.ClassDepthProfileChart::ClassDepthProfileChart(), SipperFile.TrainingModelStatus::ForceCancelation(), GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters(), PicesCommander.Harvester::Harvester(), PicesCommander.ImportGroupAssignments::ImportGroupAssignments(), PicesCommander.SaveActiveTrainingModelFeatureData::SaveActiveTrainingModelFeatureData(), SipperFile.SaveRawCTDData::SaveRawCTDData(), and SipperFile.Sipper3File::SaveRawCtdData().
void PicesMsgQueue::AddMsgs (List< String^ >^ msgs)
Definition at line 101 of file PicesMsgQueue.cpp.
Referenced by SipperFile.TrainingModelStatus::ForceCancelation().
void PicesMsgQueue::Close ()
summary> Returns a copy of the string last added to the message queue; will not effect the current copy of the message queue.
The returned string will be owned by the caller who will be responsible for deleting it. /summary>
Definition at line 53 of file PicesMsgQueue.cpp.
String PicesMsgQueue::GetCopyOfLastMsg ()
summary> Removes from the queue the oldest message added to the queue that has not been removed.
Definition at line 61 of file PicesMsgQueue.cpp.
String PicesMsgQueue::GetNextMsg ()
Definition at line 76 of file PicesMsgQueue.cpp.
Referenced by PicesCommander.ChartAbundanceByDeployment::ChartAbundanceByDeployment(), PicesCommander.ChartAbundancePredictedAndValidated::ChartAbundancePredictedAndValidated(), PicesCommander.ChartDistribution::ChartDistribution(), PicesCommander.ChartGPS::ChartGPS(), PicesCommander.ChartGPSByStation::ChartGPSByStation(), PicesCommander.ChartHorizontalProfile::ChartHorizontalProfile(), PicesCommander.ChartSizeDistribution::ChartSizeDistribution(), PicesCommander.ClassDepthProfileChart::ClassDepthProfileChart(), SipperFile.TrainingModelStatus::ForceCancelation(), GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters(), PicesCommander.Harvester::Harvester(), PicesCommander.ImportGroupAssignments::ImportGroupAssignments(), PicesCommander.ImportImagesIntoDeployment::ImportImagesIntoDeployment(), PicesCommander.SaveActiveTrainingModelFeatureData::SaveActiveTrainingModelFeatureData(), and SipperFile.SaveRawCTDData::SaveRawCTDData().
MsgQueuePtr PicesInterface::PicesMsgQueue::MsgQueue () inline
Definition at line 40 of file PicesMsgQueue.h.
Referenced by PicesInterface::TrainingModel2::AttachMsgQueueToRunLog(), PicesInterface::TrainingModel2::LoadExistingModelOtherwiseBuild(), PicesInterface::TrainingModel2::LoadTrainingModelForGivenLevel(), and PicesInterface::PicesRunLog::PicesRunLog().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesMsgQueue.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesMsgQueue.cpp