Pices: FeatureSelectionApp Namespace Reference
FeatureSelectionApp Namespace Reference
Classes
class AccByFeatureSel
class AccByFeatureSelList
class BinaryClass
class BinaryClassList
class BinaryJob
class BinaryJobList
class FeatureImpact
class FeatureSelection
class FinalResults
class JobRandomSplit
class JobValidation
class ParmSearchResultsProcessor
class Processor
class ProcessorCycles
class ProcessorList
class RandomSplitResults
Where results for a JobRandomSplits are stored.
class RandomSplitResultsList
class Results
class ValidationResults
Where inale Results for a validation run for a single configration are stored.
Typedefs
typedef AccByFeatureSelList * AccByFeatureSelListPtr
typedef
AccByFeatureSel::AccByFeatureSelPtr AccByFeatureSelPtr
typedef BinaryClassList * BinaryClassListPtr
typedef BinaryClass * BinaryClassPtr
typedef BinaryJobList * BinaryJobListPtr
typedef BinaryJob::BinaryJobPtr BinaryJobPtr
typedef
FeatureImpact::FeatureImpactPtr FeatureImpactPtr
typedef FeatureSelection * FeatureSelectionPtr
typedef FileDesc * FileDescPtr
typedef
FinalResults::FinalResultsPtr FinalResultsPtr
typedef
JobRandomSplit::JobRandomSplitPtr JobRandomSplitPtr
typedef
JobValidation::JobValidationPtr JobValidationPtr
typedef Processor * ProcessorPtr
typedef
RandomSplitResultsList::RandomSplitResultsListPtr RandomSplitResultsListPtr
typedef
RandomSplitResults::RandomSplitResultsPtr RandomSplitResultsPtr
typedef Results::ResultsPtr ResultsPtr
typedef
ValidationResults::ValidationResultsPtr ValidationResultsPtr
Enumerations
enum BinaryJobStatus {
BinaryJobStatus::Null, BinaryJobStatus::Open, BinaryJobStatus::Started, BinaryJobStatus::Done,
BinaryJobStatus::Expanded
}
enum FeatureCriteriaType : int {
FeatureCriteriaType::Null, FeatureCriteriaType::Merge2Best, FeatureCriteriaType::Merge3Best, FeatureCriteriaType::Merge4Best,
FeatureCriteriaType::Merge5Best, FeatureCriteriaType::Merge6Best, FeatureCriteriaType::Merge7Best, FeatureCriteriaType::BestTestSet,
FeatureCriteriaType::RemoveHurtful
}
enum FinalResultType : int {
FinalResultType::Null, FinalResultType::NoTuningAllFeatures, FinalResultType::MfsFeaturesSel, FinalResultType::MfsParmsTuned,
FinalResultType::MfsParmsTunedFeaturesSel, FinalResultType::BfsFeaturesSel, FinalResultType::BfsParmsTuned, FinalResultType::BfsFeaturesSelParmsTuned
}
enum GradingMethodType : int { GradingMethodType::Null, GradingMethodType::Accuracy, GradingMethodType::AccuracyNorm, GradingMethodType::FMeasure }
enum JobSelectionCriteria : int { JobSelectionCriteria::Null, JobSelectionCriteria::MostAccurate, JobSelectionCriteria::FastestFromBest, JobSelectionCriteria::BruitForce }
enum JobTypes { JobTypes::Null, JobTypes::BinaryCombo, JobTypes::RandomSplit, JobTypes::Validation }
enum MajorSteps : int {
MajorSteps::Null, MajorSteps::MfsParmTuningPre, MajorSteps::MfsFeatureSelection, MajorSteps::MfsParmTuningPost,
MajorSteps::BfsParmTuningPre, MajorSteps::BfsFeatureSelection, MajorSteps::BfsParmTuningPost, MajorSteps::GenerateFinalResults,
MajorSteps::FinalReport, MajorSteps::GenerateBruitSvmSearch, MajorSteps::Done
}
MajorSteps that need to be processed.
enum ProcessingOrders : int { ProcessingOrders::Null, ProcessingOrders::Standard, ProcessingOrders::Hall }
enum ProcessorStatus : int { ProcessorStatus::Null, ProcessorStatus::NotStarted, ProcessorStatus::Started, ProcessorStatus::Done }
enum SearchMethod : int {
SearchMethod::Null, SearchMethod::BestCaseNext, SearchMethod::Beam, SearchMethod::TestResults,
SearchMethod::PickTheBest, SearchMethod::Grid, SearchMethod::OnePassOnly
}
enum SearchTypes : int { SearchTypes::Null, SearchTypes::FeatureSelectionSearch, SearchTypes::ParameterSearch, SearchTypes::GeneratingFinalResults }
Functions
FeatureCriteriaType FeatureCriteriaFromStr (KKStr featureCriteriaStr)
KKStr FeatureCriteriaToStr (FeatureCriteriaType featureCriteria)
FinalResultType FinalResultTypeFromStr (const KKStr &s)
KKStr FinalResultTypeToStr (FinalResultType frt)
GradingMethodType GradingMethodFromStr (const KKStr &str)
KKStr GradingMethodToStr (GradingMethodType gm)
JobSelectionCriteria JobSelectionCriteriaFromStr (const KKStr &str)
KKStr JobSelectionCriteriaToStr (JobSelectionCriteria gm)
MajorSteps MajorStepFromStr (KKStr majorStepStr)
KKStr MajorStepToStr (MajorSteps step)
ProcessingOrders ProcessingOrderFromStr (const KKStr &procOrderStr)
KKStr ProcessingOrderToStr (ProcessingOrders order)
ProcessorStatus ProcessorStatusFromStr (const KKStr &processorStatusStr)
KKStr ProcessorStatusToStr (ProcessorStatus processorStatus)
SearchMethod SearchMethodFromStr (KKStr searchMethodStr)
KKStr SearchMethodToStr (SearchMethod searchMethod)
SearchTypes SearchTypeFromStr (KKStr searchTypeStr)
KKStr SearchTypeToStr (SearchTypes _searchType)
Typedef Documentation
typedef AccByFeatureSelList * FeatureSelectionApp::AccByFeatureSelListPtr
Definition at line 65 of file AccByFeatureSel.h.
typedef AccByFeatureSel * FeatureSelectionApp::AccByFeatureSelPtr
Definition at line 43 of file AccByFeatureSel.h.
typedef BinaryClassList* FeatureSelectionApp::BinaryClassListPtr
Definition at line 111 of file BinaryClass.h.
typedef BinaryClass* FeatureSelectionApp::BinaryClassPtr
Definition at line 98 of file BinaryClass.h.
typedef BinaryJobList * FeatureSelectionApp::BinaryJobListPtr
Definition at line 37 of file BinaryJob.h.
typedef BinaryJob * FeatureSelectionApp::BinaryJobPtr
Definition at line 242 of file BinaryJob.h.
typedef FeatureImpact * FeatureSelectionApp::FeatureImpactPtr
Definition at line 60 of file FeatureImpact.h.
typedef FeatureSelection * FeatureSelectionApp::FeatureSelectionPtr
Definition at line 383 of file FeatureSelection.h.
typedef FileDesc* FeatureSelectionApp::FileDescPtr
Definition at line 29 of file Processor.h.
typedef FinalResults::FinalResultsPtr FeatureSelectionApp::FinalResultsPtr
Definition at line 110 of file FinalResults.h.
typedef JobRandomSplit::JobRandomSplitPtr FeatureSelectionApp::JobRandomSplitPtr
Definition at line 83 of file JobRandomSplit.h.
typedef JobValidation::JobValidationPtr FeatureSelectionApp::JobValidationPtr
Definition at line 59 of file JobValidation.h.
typedef Processor * FeatureSelectionApp::ProcessorPtr
Definition at line 40 of file BinaryJob.h.
typedef RandomSplitResultsList::RandomSplitResultsListPtr FeatureSelectionApp::RandomSplitResultsListPtr
Definition at line 104 of file RandomSplitResults.h.
typedef RandomSplitResults::RandomSplitResultsPtr FeatureSelectionApp::RandomSplitResultsPtr
Definition at line 63 of file RandomSplitResults.h.
typedef Results::ResultsPtr FeatureSelectionApp::ResultsPtr
Definition at line 106 of file Results.h.
typedef ValidationResults::ValidationResultsPtr FeatureSelectionApp::ValidationResultsPtr
Definition at line 69 of file ValidationResults.h.
Enumeration Type Documentation
enum FeatureSelectionApp::BinaryJobStatus strong
Enumerator
Null
Open
Started
Done
Expanded
Definition at line 28 of file BinaryJob.h.
enum FeatureSelectionApp::FeatureCriteriaType : int strong
Enumerator
Null
Merge2Best
Merge3Best
Merge4Best
Merge5Best
Merge6Best
Merge7Best
BestTestSet
RemoveHurtful
Definition at line 112 of file FeatureSelectionTypes.h.
enum FeatureSelectionApp::FinalResultType : int strong
Enumerator
Null
NoTuningAllFeatures
MfsFeaturesSel
MfsParmsTuned
MfsParmsTunedFeaturesSel
BfsFeaturesSel
BfsParmsTuned
BfsFeaturesSelParmsTuned
Definition at line 66 of file FeatureSelectionTypes.h.
enum FeatureSelectionApp::GradingMethodType : int strong
Enumerator
Null
Accuracy
AccuracyNorm
FMeasure
Definition at line 10 of file FeatureSelectionTypes.h.
enum FeatureSelectionApp::JobSelectionCriteria : int strong
Enumerator
Null
MostAccurate
Select the job that has the highest Accuracy all other criteria is secondary.
FastestFromBest
Select the Fastest Job from the group of jobs that are most accurate,.
BruitForce
Perform a plain bruit force Grid Search.
Definition at line 19 of file FeatureSelectionTypes.h.
enum FeatureSelectionApp::JobTypes strong
Enumerator
Null
BinaryCombo
RandomSplit
Validation
Definition at line 19 of file BinaryJob.h.
enum FeatureSelectionApp::MajorSteps : int strong
MajorSteps that need to be processed.
Depending on the Processing Order the FeatureSelection experiment will follow a specific order of major steps.
Standard:   MajorSteps::MfsParmTuningPre,    MajorSteps::MfsFeatureSelection, MajorSteps::BfsFeatureSelection, MajorSteps::BfsParmTuningPost
Hall:       MajorSteps::MfsFeatureSelection, MajorSteps::MfsParmTuningPost,   MajorSteps::BfsParmTuningPre,    MajorSteps::BfsFeatureSelection, MajorSteps::BfsParmTuningPost
Enumerator
Null
MfsParmTuningPre
MfsFeatureSelection
MfsParmTuningPost
BfsParmTuningPre
BfsFeatureSelection
BfsParmTuningPost
GenerateFinalResults
FinalReport
GenerateBruitSvmSearch
Done
Definition at line 46 of file FeatureSelectionTypes.h.
enum FeatureSelectionApp::ProcessingOrders : int strong
Enumerator
Null
Standard
Hall
Definition at line 28 of file FeatureSelectionTypes.h.
enum FeatureSelectionApp::ProcessorStatus : int strong
Enumerator
Null
NotStarted
Started
Done
Definition at line 90 of file FeatureSelectionTypes.h.
enum FeatureSelectionApp::SearchMethod : int strong
Enumerator
Null
BestCaseNext
Beam
TestResults
PickTheBest
Grid
OnePassOnly
Definition at line 99 of file FeatureSelectionTypes.h.
enum FeatureSelectionApp::SearchTypes : int strong
Enumerator
Null
FeatureSelectionSearch
ParameterSearch
GeneratingFinalResults
Definition at line 80 of file FeatureSelectionTypes.h.
Function Documentation
FeatureCriteriaType FeatureSelectionApp::FeatureCriteriaFromStr (KKStr featureCriteriaStr)
Referenced by FeatureSelectionApp::FeatureSelection::ProcessCmdLine().
KKStr FeatureSelectionApp::FeatureCriteriaToStr (FeatureCriteriaType featureCriteria)
Definition at line 410 of file FeatureSelectionTypes.cpp.
FinalResultType FeatureSelectionApp::FinalResultTypeFromStr (const KKStr & s)
Referenced by FeatureSelectionApp::BinaryClass::ProcessStatusStr(), and FeatureSelectionApp::Results::Read().
KKStr FeatureSelectionApp::FinalResultTypeToStr (FinalResultType frt)
Definition at line 172 of file FeatureSelectionTypes.cpp.
Referenced by FeatureSelectionApp::Processor::Processor(), FeatureSelectionApp::Results::ResultTypeStr(), FeatureSelectionApp::BinaryClass::ToStr(), and FeatureSelectionApp::Results::Write().
GradingMethodType FeatureSelectionApp::GradingMethodFromStr (const KKStr & str)
Referenced by FeatureSelectionApp::FeatureSelection::ProcessCmdLine().
KKStr FeatureSelectionApp::GradingMethodToStr (GradingMethodType gm)
Definition at line 237 of file FeatureSelectionTypes.cpp.
JobSelectionCriteria FeatureSelectionApp::JobSelectionCriteriaFromStr (const KKStr & str)
Referenced by FeatureSelectionApp::FeatureSelection::ProcessCmdLine().
KKStr FeatureSelectionApp::JobSelectionCriteriaToStr (JobSelectionCriteria gm)
Definition at line 275 of file FeatureSelectionTypes.cpp.
MajorSteps FeatureSelectionApp::MajorStepFromStr (KKStr majorStepStr)
KKStr FeatureSelectionApp::MajorStepToStr (MajorSteps step)
Definition at line 107 of file FeatureSelectionTypes.cpp.
Referenced by FeatureSelectionApp::Processor::Processor(), and FeatureSelectionApp::FeatureSelection::Run().
ProcessingOrders FeatureSelectionApp::ProcessingOrderFromStr (const KKStr & procOrderStr)
Referenced by FeatureSelectionApp::FeatureSelection::ProcessCmdLine().
KKStr FeatureSelectionApp::ProcessingOrderToStr (ProcessingOrders order)
Definition at line 53 of file FeatureSelectionTypes.cpp.
Referenced by FeatureSelectionApp::Processor::Processor().
ProcessorStatus FeatureSelectionApp::ProcessorStatusFromStr (const KKStr & processorStatusStr)
KKStr FeatureSelectionApp::ProcessorStatusToStr (ProcessorStatus processorStatus)
Definition at line 376 of file FeatureSelectionTypes.cpp.
Referenced by FeatureSelectionApp::Processor::ProcessRestart(), and FeatureSelectionApp::Processor::Run().
SearchMethod FeatureSelectionApp::SearchMethodFromStr (KKStr searchMethodStr)
KKStr FeatureSelectionApp::SearchMethodToStr (SearchMethod searchMethod)
Definition at line 319 of file FeatureSelectionTypes.cpp.
SearchTypes FeatureSelectionApp::SearchTypeFromStr (KKStr searchTypeStr)
Referenced by FeatureSelectionApp::FeatureSelection::ProcessCmdLine().
KKStr FeatureSelectionApp::SearchTypeToStr (SearchTypes _searchType)
Definition at line 220 of file FeatureSelectionTypes.cpp.