Pices: KKB::HashTable< Entry > Class Template Reference
KKB::HashTable< Entry > Class Template Reference
#include <HashTable.h>
Public Types
typedef Entry * EntryPtr
Public Member Functions
HashTable (bool _owner, kkuint32 _tableSize, kkuint32 _keyLen)
Hash Table management template; developed to support BitReduction algorithm.
~HashTable ()
void AddEntry (EntryPtr entry)
bool DeleteEntry (EntryPtr _entry)
kkuint32 HashValue (const KKStr &str)
EntryPtr LocateEntry (const KKStr &str)
kkuint32 NumOfEntries ()
void Save (const KKStr &fileName)
HashEntryPtr * Table ()
kkuint32 TableSize ()
Detailed Description
template<class Entry>
class KKB::HashTable< Entry >
Definition at line 19 of file HashTable.h.
Member Typedef Documentation
template<class Entry> typedef Entry* KKB::HashTable< Entry >::EntryPtr
Definition at line 22 of file HashTable.h.
Constructor & Destructor Documentation
template<class Entry > KKB::HashTable< Entry >::HashTable (bool _owner, kkuint32 _tableSize, kkuint32 _keyLen)
Hash Table management template; developed to support BitReduction algorithm.
This template was originally written by Tong Luo to support his experiments in Bit reduction. It was later heavily modified by Kurt Kramer to conform to the PicesLibrary structure.
Definition at line 85 of file HashTable.h.
template<class Entry > KKB::HashTable< Entry >::~HashTable ()
Definition at line 118 of file HashTable.h.
Member Function Documentation
template<class Entry > void KKB::HashTable< Entry >::AddEntry (EntryPtr entry)
Definition at line 173 of file HashTable.h.
template<class Entry > bool KKB::HashTable< Entry >::DeleteEntry (EntryPtr _entry)
Definition at line 191 of file HashTable.h.
template<class Entry > kkuint32 KKB::HashTable< Entry >::HashValue (const KKStr & str)
Definition at line 230 of file HashTable.h.
References KKB::KKStr::Str().
template<class Entry > HashTable< Entry >::EntryPtr KKB::HashTable< Entry >::LocateEntry (const KKStr & str)
Definition at line 145 of file HashTable.h.
template<class Entry> kkuint32 KKB::HashTable< Entry >::NumOfEntries () inline
Definition at line 70 of file HashTable.h.
template<class Entry > void KKB::HashTable< Entry >::Save (const KKStr & fileName)
Definition at line 251 of file HashTable.h.
References KKB::endl(), and KKB::KKStr::Str().
template<class Entry> HashEntryPtr* KKB::HashTable< Entry >::Table () inline
Definition at line 72 of file HashTable.h.
template<class Entry> kkuint32 KKB::HashTable< Entry >::TableSize () inline
Definition at line 74 of file HashTable.h.
The documentation for this class was generated from the following file:
C:/Users/kurtk_000/GitHub/KSquareLibraries/KKBase/HashTable.h