Pices: ImageExtractionManager::ExtractionParms Class Reference
ImageExtractionManager::ExtractionParms Class Reference
#include <ExtractionParms.h>
Public Types
typedef MLL::SipperFileFormat SipperFileFormat
Public Member Functions
ExtractionParms (kkint32 argc, char **argv, bool _runningAsAWindowsApp, KKStr &errorMessage, bool &formatGood, RunLog &log)
ExtractionParms (KKStr progName, KKStr cmdLine, bool _runningAsAWindowsApp, KKStr &errorMessage, bool &formatGood, RunLog &log)
~ExtractionParms ()
kkuint64 BytesExtracted () const
void BytesExtracted (kkuint64 _bytesExtracted)
uchar CameraNum () const
ClassStatisticListPtr ClassStats () const
void ClassStats (ClassStatisticListPtr _classStats)
KKStr CmdLine () const
bool Colorize () const
const KKStr & ConfigFileName () const
const KKStr & ConfigFileNameSpecified () const
kkuint32 ConnectedPixelDist () const
bool CountOnly () const
DataBaseServerPtr DataBaseServer () const
KKStr DataBaseServerDesc () const
void DisplayExampleCmdLine ()
void DoneExecuting (bool _doneExecuting)
bool DoneExecuting () const
bool ExtractFeatureData () const
SipperFileFormat FileFormat () const
const KKStr & FlowRateFileName () const
bool FramesOnly () const
kkuint32 ImagesExtracted () const
void ImagesExtracted (kkuint32 _imagesExtracted)
kkuint32 ImagesPerDirectory () const
void ImagesPerDirectory (kkuint32 _imagesPerDirectory)
kkuint32 ImagesWritten () const
void ImagesWritten (kkuint32 _imagesWritten)
void IncrementBytesExtracted (kkuint32 _bytesExtracted)
kkuint32 IncrementImagesExtracted ()
kkuint32 IncrementImagesWritten ()
kkuint32 IncrementLinesExtracted ()
void IncrementPixelsRead (kkuint32 _pixelsRead)
void IncrementPixelsWritten (kkuint32 _pixelsWritten)
kkuint32 LinesExtracted () const
void LinesExtracted (kkuint32 _linesExtracted)
kkuint32 MaxImageSize () const
kkuint32 MinImageSize () const
const KKStr & MorphOperations () const
bool MultiThreaded () const
const KKStr & OutputRootDir () const
void ParseCmdLine (const CmdLineExpander &cmdLineExpander, KKStr &errorMessage, bool &formatGood, RunLog &log)
kkuint32 PixelsRead () const
void PixelsRead (kkuint32 _pixelsRead)
kkuint32 PixelsWritten () const
void PixelsWritten (kkuint32 _pixelsWritten)
bool PreProcess () const
bool RefreshDataBaseImages () const
const KKStr & ReportFileName () const
bool RunningAsAWindowsApp ()
bool SaveFrames () const
bool SaveFramesAfter () const
kkuint32 ScanLineEnd () const
kkuint32 ScanLineStart () const
const KKStr & SipperFileName () const
kkuint64 SipperFileSize () const
const KKStr & StatusMessage () const
void StatusMessage (const KKStr &_statusMessage)
KKStr & StatusMessageField ()
bool UpdateDataBase () const
Detailed Description
Definition at line 27 of file ExtractionParms.h.
Member Typedef Documentation
typedef MLL::SipperFileFormat ImageExtractionManager::ExtractionParms::SipperFileFormat
Definition at line 30 of file ExtractionParms.h.
Constructor & Destructor Documentation
ExtractionParms::ExtractionParms (kkint32 argc, char ** argv, bool _runningAsAWindowsApp, KKStr & errorMessage, bool & formatGood, RunLog & log)
Definition at line 95 of file ExtractionParms.cpp.
References DisplayExampleCmdLine(), KKB::CmdLineExpander::ParmsGood(), and ParseCmdLine().
ExtractionParms::ExtractionParms (KKStr progName, KKStr cmdLine, bool _runningAsAWindowsApp, KKStr & errorMessage, bool & formatGood, RunLog & log)
Definition at line 32 of file ExtractionParms.cpp.
References KKB::CmdLineExpander::ParmsGood(), and ParseCmdLine().
ExtractionParms::~ExtractionParms ()
Definition at line 167 of file ExtractionParms.cpp.
Member Function Documentation
kkuint64 ImageExtractionManager::ExtractionParms::BytesExtracted () const inline
Definition at line 99 of file ExtractionParms.h.
Referenced by ImageExtractionManager::FrameExtractorThread::Run().
void ImageExtractionManager::ExtractionParms::BytesExtracted (kkuint64 _bytesExtracted) inline
Definition at line 121 of file ExtractionParms.h.
uchar ImageExtractionManager::ExtractionParms::CameraNum () const inline
Definition at line 66 of file ExtractionParms.h.
Referenced by ImageExtractionManager::FrameExtractorThread::FrameExtractorThread().
ClassStatisticListPtr ImageExtractionManager::ExtractionParms::ClassStats () const inline
Definition at line 97 of file ExtractionParms.h.
void ExtractionParms::ClassStats (ClassStatisticListPtr _classStats)
Definition at line 811 of file ExtractionParms.cpp.
KKStr ExtractionParms::CmdLine () const
Definition at line 206 of file ExtractionParms.cpp.
References MLL::DataBaseServer::Description(), KKB::KKStr::Empty(), extractFeatureData, and MLL::SipperFileFormatToStr().
bool ImageExtractionManager::ExtractionParms::Colorize () const inline
Definition at line 67 of file ExtractionParms.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
const KKStr& ImageExtractionManager::ExtractionParms::ConfigFileName () const inline
Definition at line 68 of file ExtractionParms.h.
const KKStr& ImageExtractionManager::ExtractionParms::ConfigFileNameSpecified () const inline
Definition at line 69 of file ExtractionParms.h.
kkuint32 ImageExtractionManager::ExtractionParms::ConnectedPixelDist () const inline
Definition at line 70 of file ExtractionParms.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
bool ImageExtractionManager::ExtractionParms::CountOnly () const inline
Definition at line 71 of file ExtractionParms.h.
DataBaseServerPtr ImageExtractionManager::ExtractionParms::DataBaseServer () const inline
Definition at line 72 of file ExtractionParms.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
KKStr ExtractionParms::DataBaseServerDesc () const
Definition at line 175 of file ExtractionParms.cpp.
References MLL::DataBaseServer::Description().
void ExtractionParms::DisplayExampleCmdLine ()
Definition at line 271 of file ExtractionParms.cpp.
References KKB::endl().
Referenced by ExtractionParms(), and CImageExtractionWindowsApp::InitInstance().
void ImageExtractionManager::ExtractionParms::DoneExecuting (bool _doneExecuting) inline
Definition at line 55 of file ExtractionParms.h.
bool ImageExtractionManager::ExtractionParms::DoneExecuting () const inline
Definition at line 74 of file ExtractionParms.h.
bool ImageExtractionManager::ExtractionParms::ExtractFeatureData () const inline
Definition at line 75 of file ExtractionParms.h.
References extractFeatureData.
Referenced by ImageExtractionManager::DataBaseUpdateThread::DataBaseUpdateThread(), and ImageExtractionManager::DataBaseUpdateThread::Run().
SipperFileFormat ImageExtractionManager::ExtractionParms::FileFormat () const inline
Definition at line 76 of file ExtractionParms.h.
Referenced by ImageExtractionManager::FrameExtractorThread::FrameExtractorThread(), ImageExtractionManager::LogicalFrame::LogicalFrame(), and ImageExtractionManager::LogicalFrame::ProcessFrame().
const KKStr& ImageExtractionManager::ExtractionParms::FlowRateFileName () const inline
Definition at line 77 of file ExtractionParms.h.
bool ImageExtractionManager::ExtractionParms::FramesOnly () const inline
Definition at line 78 of file ExtractionParms.h.
Referenced by ImageExtractionManager::FrameExtractorThread::Run().
kkuint32 ImageExtractionManager::ExtractionParms::ImagesExtracted () const inline
Definition at line 101 of file ExtractionParms.h.
void ImageExtractionManager::ExtractionParms::ImagesExtracted (kkuint32 _imagesExtracted) inline
Definition at line 123 of file ExtractionParms.h.
kkuint32 ImageExtractionManager::ExtractionParms::ImagesPerDirectory () const inline
Definition at line 79 of file ExtractionParms.h.
void ImageExtractionManager::ExtractionParms::ImagesPerDirectory (kkuint32 _imagesPerDirectory) inline
Definition at line 117 of file ExtractionParms.h.
kkuint32 ImageExtractionManager::ExtractionParms::ImagesWritten () const inline
Definition at line 102 of file ExtractionParms.h.
void ImageExtractionManager::ExtractionParms::ImagesWritten (kkuint32 _imagesWritten) inline
Definition at line 124 of file ExtractionParms.h.
void ImageExtractionManager::ExtractionParms::IncrementBytesExtracted (kkuint32 _bytesExtracted) inline
Definition at line 118 of file ExtractionParms.h.
kkuint32 ImageExtractionManager::ExtractionParms::IncrementImagesExtracted () inline
Definition at line 113 of file ExtractionParms.h.
kkuint32 ImageExtractionManager::ExtractionParms::IncrementImagesWritten () inline
Definition at line 114 of file ExtractionParms.h.
kkuint32 ImageExtractionManager::ExtractionParms::IncrementLinesExtracted () inline
Definition at line 115 of file ExtractionParms.h.
void ImageExtractionManager::ExtractionParms::IncrementPixelsRead (kkuint32 _pixelsRead) inline
Definition at line 119 of file ExtractionParms.h.
void ImageExtractionManager::ExtractionParms::IncrementPixelsWritten (kkuint32 _pixelsWritten) inline
Definition at line 120 of file ExtractionParms.h.
kkuint32 ImageExtractionManager::ExtractionParms::LinesExtracted () const inline
Definition at line 100 of file ExtractionParms.h.
void ImageExtractionManager::ExtractionParms::LinesExtracted (kkuint32 _linesExtracted) inline
Definition at line 122 of file ExtractionParms.h.
kkuint32 ImageExtractionManager::ExtractionParms::MaxImageSize () const inline
Definition at line 81 of file ExtractionParms.h.
kkuint32 ImageExtractionManager::ExtractionParms::MinImageSize () const inline
Definition at line 80 of file ExtractionParms.h.
const KKStr& ImageExtractionManager::ExtractionParms::MorphOperations () const inline
Definition at line 82 of file ExtractionParms.h.
bool ImageExtractionManager::ExtractionParms::MultiThreaded () const inline
Definition at line 83 of file ExtractionParms.h.
const KKStr& ImageExtractionManager::ExtractionParms::OutputRootDir () const inline
Definition at line 84 of file ExtractionParms.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::DataBaseUpdateThread(), and ImageExtractionManager::FrameExtractorThread::FrameExtractorThread().
void ExtractionParms::ParseCmdLine (const CmdLineExpander & cmdLineExpander, KKStr & errorMessage, bool & formatGood, RunLog & log)
Definition at line 394 of file ExtractionParms.cpp.
References MLL::DataBaseServer::Description(), KKB::KKStr::Empty(), KKB::endl(), KKB::KKStr::EqualIgnoreCase(), KKB::CmdLineExpander::ExpandedParameters(), extractFeatureData, MLL::SipperFile::ExtractionScanLineEnd(), MLL::SipperFile::ExtractionScanLineStart(), KKB::osFileExists(), KKB::osGetFileSize(), KKB::osMakeFullFileName(), KKB::osParseFileSpec(), MLL::sfUnKnown, MLL::SipperFileFormatFromStr(), MLL::DataBase::SipperFileRecLoad(), KKB::KKStr::Str(), KKB::StrFormatInt(), KKB::KKStr::ToBool(), KKB::KKStr::ToInt32(), KKB::KKStr::Upper(), and MLL::DataBase::Valid().
Referenced by ExtractionParms().
kkuint32 ImageExtractionManager::ExtractionParms::PixelsRead () const inline
Definition at line 103 of file ExtractionParms.h.
void ImageExtractionManager::ExtractionParms::PixelsRead (kkuint32 _pixelsRead) inline
Definition at line 125 of file ExtractionParms.h.
kkuint32 ImageExtractionManager::ExtractionParms::PixelsWritten () const inline
Definition at line 104 of file ExtractionParms.h.
void ImageExtractionManager::ExtractionParms::PixelsWritten (kkuint32 _pixelsWritten) inline
Definition at line 126 of file ExtractionParms.h.
bool ImageExtractionManager::ExtractionParms::PreProcess () const inline
Definition at line 85 of file ExtractionParms.h.
bool ImageExtractionManager::ExtractionParms::RefreshDataBaseImages () const inline
Definition at line 87 of file ExtractionParms.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
const KKStr& ImageExtractionManager::ExtractionParms::ReportFileName () const inline
Definition at line 86 of file ExtractionParms.h.
bool ImageExtractionManager::ExtractionParms::RunningAsAWindowsApp () inline
Definition at line 57 of file ExtractionParms.h.
bool ImageExtractionManager::ExtractionParms::SaveFrames () const inline
Definition at line 88 of file ExtractionParms.h.
bool ImageExtractionManager::ExtractionParms::SaveFramesAfter () const inline
Definition at line 89 of file ExtractionParms.h.
kkuint32 ImageExtractionManager::ExtractionParms::ScanLineEnd () const inline
Definition at line 90 of file ExtractionParms.h.
Referenced by ImageExtractionManager::FrameExtractorThread::FrameExtractorThread().
kkuint32 ImageExtractionManager::ExtractionParms::ScanLineStart () const inline
Definition at line 91 of file ExtractionParms.h.
Referenced by ImageExtractionManager::FrameExtractorThread::FrameExtractorThread().
const KKStr& ImageExtractionManager::ExtractionParms::SipperFileName () const inline
Definition at line 92 of file ExtractionParms.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::DataBaseUpdateThread(), ImageExtractionManager::FrameExtractorThread::FrameExtractorThread(), and ImageExtractionManager::FrameProcessorThread::FrameProcessorThread().
kkuint64 ImageExtractionManager::ExtractionParms::SipperFileSize () const inline
Definition at line 105 of file ExtractionParms.h.
const KKStr& ImageExtractionManager::ExtractionParms::StatusMessage () const inline
Definition at line 106 of file ExtractionParms.h.
void ImageExtractionManager::ExtractionParms::StatusMessage (const KKStr & _statusMessage) inline
Definition at line 127 of file ExtractionParms.h.
KKStr& ImageExtractionManager::ExtractionParms::StatusMessageField () inline
Definition at line 107 of file ExtractionParms.h.
bool ImageExtractionManager::ExtractionParms::UpdateDataBase () const inline
Definition at line 93 of file ExtractionParms.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/ImageExtractionManager/ExtractionParms.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/ImageExtractionManager/ExtractionParms.cpp