Pices: ImageExtractionManager::ExtractionManagerStats Class Reference
ImageExtractionManager::ExtractionManagerStats Class Reference
#include <ExtractionManagerStats.h>
Public Member Functions
ExtractionManagerStats ()
ExtractionManagerStats (const ExtractionManagerStats &stats)
~ExtractionManagerStats ()
kkuint64 BytesRead () const
kkuint32 DuplicatesDetected () const
kkuint32 FramesOnQueue () const
kkuint32 FramesProcessed () const
kkuint32 FramesRead () const
kkuint32 ImagesClassified () const
kkuint32 ImagesFound () const
kkuint32 ImagesOnQueue () const
kkuint32 ImagesUpdated () const
kkuint32 ScanLinesProcessed () const
kkuint32 UpdateFailures () const
Friends
class ExtractionManager
Detailed Description
Definition at line 7 of file ExtractionManagerStats.h.
Constructor & Destructor Documentation
ExtractionManagerStats::ExtractionManagerStats ()
Definition at line 18 of file ExtractionManagerStats.cpp.
ExtractionManagerStats::ExtractionManagerStats (const ExtractionManagerStats & stats)
Definition at line 35 of file ExtractionManagerStats.cpp.
ExtractionManagerStats::~ExtractionManagerStats ()
Definition at line 51 of file ExtractionManagerStats.cpp.
Member Function Documentation
kkuint64 ImageExtractionManager::ExtractionManagerStats::BytesRead () const inline
Definition at line 15 of file ExtractionManagerStats.h.
Referenced by CImageExtractionWindowsDlg::OnTimer().
kkuint32 ImageExtractionManager::ExtractionManagerStats::DuplicatesDetected () const inline
Definition at line 22 of file ExtractionManagerStats.h.
kkuint32 ImageExtractionManager::ExtractionManagerStats::FramesOnQueue () const inline
Definition at line 24 of file ExtractionManagerStats.h.
kkuint32 ImageExtractionManager::ExtractionManagerStats::FramesProcessed () const inline
Definition at line 17 of file ExtractionManagerStats.h.
kkuint32 ImageExtractionManager::ExtractionManagerStats::FramesRead () const inline
Definition at line 16 of file ExtractionManagerStats.h.
kkuint32 ImageExtractionManager::ExtractionManagerStats::ImagesClassified () const inline
Definition at line 20 of file ExtractionManagerStats.h.
Referenced by CImageExtractionWindowsDlg::OnTimer().
kkuint32 ImageExtractionManager::ExtractionManagerStats::ImagesFound () const inline
Definition at line 19 of file ExtractionManagerStats.h.
kkuint32 ImageExtractionManager::ExtractionManagerStats::ImagesOnQueue () const inline
Definition at line 25 of file ExtractionManagerStats.h.
kkuint32 ImageExtractionManager::ExtractionManagerStats::ImagesUpdated () const inline
Definition at line 21 of file ExtractionManagerStats.h.
Referenced by CImageExtractionWindowsDlg::OnTimer().
kkuint32 ImageExtractionManager::ExtractionManagerStats::ScanLinesProcessed () const inline
Definition at line 18 of file ExtractionManagerStats.h.
Referenced by CImageExtractionWindowsDlg::OnTimer().
kkuint32 ImageExtractionManager::ExtractionManagerStats::UpdateFailures () const inline
Definition at line 23 of file ExtractionManagerStats.h.
Friends And Related Function Documentation
friend class ExtractionManager friend
Definition at line 10 of file ExtractionManagerStats.h.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/ImageExtractionManager/ExtractionManagerStats.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/ImageExtractionManager/ExtractionManagerStats.cpp