Pices: PicesCommander.ChartDistribution Class Reference
PicesCommander.ChartDistribution Class Reference
Public Member Functions
ChartDistribution (String _cruise, String _station, String _deployment, int _sizeMin, int _sizeMax, float _probMin, float _probMax, float _depthMin, float _depthMax, char _classKeyToUse, String _criteriaStr, PicesClassList _classes, PicesClassList _activeClasses, String _rootDir)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Detailed Description
Definition at line 16 of file ChartDistribution.cs.
Constructor & Destructor Documentation
PicesCommander.ChartDistribution.ChartDistribution (String _cruise, String _station, String _deployment, int _sizeMin, int _sizeMax, float _probMin, float _probMax, float _depthMin, float _depthMax, char _classKeyToUse, String _criteriaStr, PicesClassList _classes, PicesClassList _activeClasses, String _rootDir) inline
Definition at line 140 of file ChartDistribution.cs.
References PicesInterface::PicesMsgQueue.AddMsg(), PicesInterface::OSservices.AddSlash(), PicesInterface::PicesDataBase.CancelFlag, PicesInterface::PicesClass.Children, PicesInterface::PicesDataBase.Close(), PicesInterface::PicesSipperVariables.ConfigurationDirectory(), PicesInterface::PicesGoalKeeper.EndBlock(), PicesInterface::PicesInstrumentData.FieldFormatStr(), PicesInterface::PicesInstrumentData.FieldMinValue(), SipperFile.InstrumentData.FieldName(), PicesInterface::PicesInstrumentData.FieldUnitOfMeasure(), PicesInterface::PicesInstrumentData.GetFieldNum(), PicesInterface::PicesDataBase.GetGlobalDatabaseManagerNewInstance(), PicesInterface::PicesMsgQueue.GetNextMsg(), PicesInterface::PicesClassList.GetUniqueClass(), PicesInterface::PicesDataBase.ImageGetDepthStatistics(), PicesInterface::PicesDataBase.InstrumentDataGetSpecificFields(), PicesInterface::PicesDataBase.InstrumentDataGetVolumePerMeterDepth(), PicesInterface::PicesClass.IsInMySubTree(), PicesInterface::PicesClassList.LookUpByName(), max, min, PicesInterface::PicesClass.Name, SipperFile.InstrumentData.NumDataFields(), SipperFile.SelectAPicesClass.SelectedClass, SipperFile.SelectAPicesClass.SelectionMade, PicesInterface::PicesDataBase.SipperFileLoad(), PicesInterface::PicesSipperFile.SipperFileName, PicesInterface::PicesGoalKeeper.StartBlock(), PicesInterface::PicesKKStr.StrToBool(), PicesInterface::PicesKKStr.StrToFloat(), PicesInterface::PicesKKStr.StrToInt(), PicesInterface::PicesDataBase.ThreadEnd(), PicesInterface::PicesDataBase.ThreadInit(), and PicesInterface::PicesVolumeSampledStatList.ToArray().
Member Function Documentation
override void PicesCommander.ChartDistribution.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file ChartDistribution.Designer.cs.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/ChartDistribution.cs
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/ChartDistribution.Designer.cs