Pices: FeatureSelectionApp::BinaryClass Class Reference
FeatureSelectionApp::BinaryClass Class Reference
#include <BinaryClass.h>
Public Member Functions
BinaryClass (MLClassPtr _class1, MLClassPtr _class2, int _processorId)
BinaryClass (int _numProcessors, bool _finalReportJobs, MajorSteps _majorSetp)
BinaryClass (KKStr statusStr, MLClassListPtr mlClasses)
BinaryClass (int _numProcessors, FinalResultType _resultType, SVM_SelectionMethod _selectionMehod, const KKStr &_finalResultsFileName, const KKStr &_configFilename)
~BinaryClass ()
MLClassPtr Class1 () const
const KKStr & Class1Name () const
MLClassPtr Class2 () const
const KKStr & Class2Name () const
const KKStr & ConfigFileName () const
void DecrementNumProcessors ()
const KKStr & FinalResultsFileName () const
void IncrementNumProcessors ()
int NumProcessors () const
void NumProcessors (int _numProcessors)
void ProcessStatusStr (KKStr statusStr, MLClassListPtr mlClasses)
FinalResultType ResultType () const
SVM_SelectionMethod SelectionMethod () const
ClassPairStatus Status () const
void Status (ClassPairStatus _status)
virtual KKStr ToStr ()
Static Public Member Functions
static ClassPairStatus BinaryClassStatusFromStr (KKStr statusStr)
static KKStr BinaryClassStatusToStr (ClassPairStatus status)
Detailed Description
Definition at line 28 of file BinaryClass.h.
Constructor & Destructor Documentation
BinaryClass::BinaryClass (MLClassPtr _class1, MLClassPtr _class2, int _processorId)
Definition at line 30 of file BinaryClass.cpp.
FeatureSelectionApp::BinaryClass::BinaryClass (int _numProcessors, bool _finalReportJobs, MajorSteps _majorSetp)
BinaryClass::BinaryClass (KKStr statusStr, MLClassListPtr mlClasses)
Definition at line 68 of file BinaryClass.cpp.
References ProcessStatusStr().
BinaryClass::BinaryClass (int _numProcessors, FinalResultType _resultType, SVM_SelectionMethod _selectionMehod, const KKStr & _finalResultsFileName, const KKStr & _configFilename)
Definition at line 48 of file BinaryClass.cpp.
BinaryClass::~BinaryClass ()
Definition at line 122 of file BinaryClass.cpp.
Member Function Documentation
ClassPairStatus BinaryClass::BinaryClassStatusFromStr (KKStr statusStr) static
Definition at line 103 of file BinaryClass.cpp.
References FeatureSelectionApp::Done, NotStarted, Null, FeatureSelectionApp::Started, and KKB::KKStr::Upper().
Referenced by ProcessStatusStr().
KKStr BinaryClass::BinaryClassStatusToStr (ClassPairStatus status) static
Definition at line 86 of file BinaryClass.cpp.
References FeatureSelectionApp::Done, NotStarted, and FeatureSelectionApp::Started.
Referenced by ToStr().
MLClassPtr FeatureSelectionApp::BinaryClass::Class1 () const inline
Definition at line 55 of file BinaryClass.h.
Referenced by FeatureSelectionApp::FeatureSelection::BuildResultConfigFile(), CalcClassPairWeighted(), FeatureSelectionApp::FeatureSelection::LoadFeatureData(), and ReportDataSpecs().
const KKStr & BinaryClass::Class1Name () const
Definition at line 229 of file BinaryClass.cpp.
Referenced by FeatureSelectionApp::FeatureSelection::BuildResultConfigFile(), CalcClassPairWeighted(), and ReportDataSpecs().
MLClassPtr FeatureSelectionApp::BinaryClass::Class2 () const inline
Definition at line 56 of file BinaryClass.h.
Referenced by FeatureSelectionApp::FeatureSelection::BuildResultConfigFile(), CalcClassPairWeighted(), FeatureSelectionApp::FeatureSelection::LoadFeatureData(), and ReportDataSpecs().
const KKStr & BinaryClass::Class2Name () const
Definition at line 238 of file BinaryClass.cpp.
Referenced by FeatureSelectionApp::FeatureSelection::BuildResultConfigFile(), CalcClassPairWeighted(), and ReportDataSpecs().
const KKStr& FeatureSelectionApp::BinaryClass::ConfigFileName () const inline
Definition at line 63 of file BinaryClass.h.
Referenced by FeatureSelectionApp::Processor::FlagJobsForTesting(), and FeatureSelectionApp::Processor::Processor().
void BinaryClass::DecrementNumProcessors ()
Definition at line 255 of file BinaryClass.cpp.
Referenced by ReportDataSpecs().
const KKStr& FeatureSelectionApp::BinaryClass::FinalResultsFileName () const inline
Definition at line 64 of file BinaryClass.h.
Referenced by CalcClassPairWeighted(), FeatureSelectionApp::Processor::Processor(), and ReportDataSpecs().
void BinaryClass::IncrementNumProcessors ()
Definition at line 248 of file BinaryClass.cpp.
Referenced by ReportDataSpecs().
int FeatureSelectionApp::BinaryClass::NumProcessors () const inline
Definition at line 57 of file BinaryClass.h.
Referenced by AllBinaryClassesAreDone(), CalcClassPairWeighted(), and ReportDataSpecs().
void FeatureSelectionApp::BinaryClass::NumProcessors (int _numProcessors) inline
Definition at line 71 of file BinaryClass.h.
void BinaryClass::ProcessStatusStr (KKStr statusStr, MLClassListPtr mlClasses)
Definition at line 128 of file BinaryClass.cpp.
References BinaryClassStatusFromStr(), KKB::KKStr::CompareIgnoreCase(), KKB::KKStr::Empty(), KKB::endl(), KKB::KKStr::ExtractToken2(), KKB::KKStr::ExtractTokenInt(), FeatureSelectionApp::FinalResultTypeFromStr(), KKMLL::MLClassList::GetMLClassPtr(), KKMLL::SelectionMethodFromStr(), KKB::KKStr::TrimLeft(), KKB::KKStr::TrimRight(), and KKB::KKStr::Upper().
Referenced by BinaryClass().
FinalResultType FeatureSelectionApp::BinaryClass::ResultType () const inline
Definition at line 65 of file BinaryClass.h.
Referenced by FeatureSelectionApp::FeatureSelection::BuildResultConfigFile(), CalcClassPairWeighted(), FeatureSelectionApp::FeatureSelection::LoadFeatureData(), FeatureSelectionApp::Processor::Processor(), and ReportDataSpecs().
SVM_SelectionMethod FeatureSelectionApp::BinaryClass::SelectionMethod () const inline
Definition at line 66 of file BinaryClass.h.
Referenced by FeatureSelectionApp::Processor::Processor().
ClassPairStatus FeatureSelectionApp::BinaryClass::Status () const inline
Definition at line 58 of file BinaryClass.h.
Referenced by AllBinaryClassesAreDone(), CalcClassPairWeighted(), FeatureSelectionApp::FeatureSelection::LoadFeatureData(), and ReportDataSpecs().
void FeatureSelectionApp::BinaryClass::Status (ClassPairStatus _status) inline
Definition at line 72 of file BinaryClass.h.
KKStr BinaryClass::ToStr () virtual
Definition at line 194 of file BinaryClass.cpp.
References BinaryClassStatusToStr(), FeatureSelectionApp::FinalResultTypeToStr(), FeatureSelectionApp::Null, and KKMLL::SelectionMethodToStr().
Referenced by FeatureSelectionApp::FeatureSelection::DisplayCommandUsage().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/Apps/FeatureSelection/BinaryClass.h
C:/Users/Kurt/GitHub/Pices/Apps/FeatureSelection/BinaryClass.cpp