Pices: KKMLL::ModelParamSvmBase Class Reference
KKMLL::ModelParamSvmBase Class Reference
This class encapsulates general parameters that are common to all Machine Learning Models.
#include <ModelParamSvmBase.h>
Public Types
typedef ModelParamSvmBase * ModelParamSvmBasePtr
Public Types inherited from KKMLL::ModelParam
enum EncodingMethodType { EncodingMethodType::Null, EncodingMethodType::NoEncoding, EncodingMethodType::Binary, EncodingMethodType::Scaled }
Needs to be synchronized with SVMparam::SVM_EncodingMethod.
typedef ModelParam * ModelParamPtr
enum ModelParamTypes {
ModelParamTypes::Null, ModelParamTypes::Dual, ModelParamTypes::KNN, ModelParamTypes::OldSVM,
ModelParamTypes::SvmBase, ModelParamTypes::UsfCasCor
}
Public Member Functions
ModelParamSvmBase ()
ModelParamSvmBase (SVM_Type _svm_type, Kernel_Type _kernelType, double _cost, double _gamma)
ModelParamSvmBase (const ModelParamSvmBase &_param)
virtual ~ModelParamSvmBase ()
virtual void Cost (double _cost)
virtual double Cost () const
virtual ModelParamSvmBasePtr Duplicate () const
virtual void Gamma (double _gamma)
virtual double Gamma () const
virtual void KernalType (Kernel_Type _kernalType)
virtual Kernel_Type KernalType () const
virtual ModelParamTypes ModelParamType () const
virtual void ReadXML (XmlStream &s, XmlTagConstPtr tag, RunLog &log)
const SVM289_MFS::svm_parameter & SvmParam ()
virtual void SvmType (SVM_Type _svm_type)
virtual SVM_Type SvmType () const
virtual KKStr ToCmdLineStr () const
Creates a Command Line String that represents these parameters.
virtual void WriteXML (const KKStr &varName, ostream &o) const
Public Member Functions inherited from KKMLL::ModelParam
ModelParam ()
ModelParam (const ModelParam &_param)
virtual ~ModelParam ()
virtual float A_Param () const
virtual void A_Param (float _prob)
virtual float AvgMumOfFeatures () const
virtual double C_Param () const
virtual void C_Param (double _cost)
virtual EncodingMethodType EncodingMethod () const
virtual void EncodingMethod (EncodingMethodType _encodingMethod)
virtual KKStr EncodingMethodStr () const
virtual kkint32 ExamplesPerClass () const
virtual void ExamplesPerClass (kkint32 _examplesPerClass)
virtual const KKStr & FileName () const
virtual void FileName (const KKStr &_fileName)
virtual kkint32 MemoryConsumedEstimated () const
virtual KKStr ModelParamTypeStr () const
virtual bool NormalizeNominalFeatures () const
virtual kkint32 NumOfFeaturesAfterEncoding (FileDescPtr fileDesc, RunLog &log) const
virtual void ParseCmdLine (KKStr _cmdLineStr, bool &_validFormat, RunLog &_log)
virtual void ParseCmdLinePost (RunLog &log)
Called after 'ParseCmdLine' is completed.
virtual float Prob () const
virtual void Prob (float _prob)
XmlTokenPtr ReadXMLModelParamToken (XmlTokenPtr t)
Will process any tokens that belong to 'ModelParam' and return NULL ones that are not will be passed back.
virtual FeatureNumListConstPtr SelectedFeatures () const
virtual void SelectedFeatures (FeatureNumListConst &_selectedFeatures)
virtual bool ValidParam () const
virtual void ValidParam (bool _validParam)
void WriteXMLFields (ostream &o) const
Additional Inherited Members
Static Public Member Functions inherited from KKMLL::ModelParam
static EncodingMethodType EncodingMethodFromStr (const KKStr &encodingMethodStr)
static KKStr EncodingMethodToStr (EncodingMethodType encodingMethod)
static ModelParamTypes ModelParamTypeFromStr (const KKStr &_modelParamTypeStr)
static KKStr ModelParamTypeToStr (ModelParamTypes _modelParamType)
Detailed Description
This class encapsulates general parameters that are common to all Machine Learning Models.
See Also
Model
Definition at line 18 of file ModelParamSvmBase.h.
Member Typedef Documentation
typedef ModelParamSvmBase* KKMLL::ModelParamSvmBase::ModelParamSvmBasePtr
Definition at line 21 of file ModelParamSvmBase.h.
Constructor & Destructor Documentation
ModelParamSvmBase::ModelParamSvmBase ()
Definition at line 28 of file ModelParamSvmBase.cpp.
Referenced by Duplicate().
ModelParamSvmBase::ModelParamSvmBase (SVM_Type _svm_type, Kernel_Type _kernelType, double _cost, double _gamma)
Definition at line 38 of file ModelParamSvmBase.cpp.
References SVM289_MFS::svm_parameter::Cost(), SVM289_MFS::svm_parameter::Gamma(), SVM289_MFS::svm_parameter::KernalType(), and SVM289_MFS::svm_parameter::SvmType().
ModelParamSvmBase::ModelParamSvmBase (const ModelParamSvmBase & _param)
Definition at line 57 of file ModelParamSvmBase.cpp.
ModelParamSvmBase::~ModelParamSvmBase () virtual
Definition at line 65 of file ModelParamSvmBase.cpp.
Member Function Documentation
void ModelParamSvmBase::Cost (double _cost) virtual
Reimplemented from KKMLL::ModelParam.
Definition at line 77 of file ModelParamSvmBase.cpp.
References SVM289_MFS::svm_parameter::Cost(), and KKMLL::ModelParam::Cost().
double ModelParamSvmBase::Cost () const virtual
Reimplemented from KKMLL::ModelParam.
Definition at line 91 of file ModelParamSvmBase.cpp.
References SVM289_MFS::svm_parameter::Cost().
ModelParamSvmBasePtr ModelParamSvmBase::Duplicate () const virtual
Implements KKMLL::ModelParam.
Definition at line 70 of file ModelParamSvmBase.cpp.
References ModelParamSvmBase().
void ModelParamSvmBase::Gamma (double _gamma) virtual
Reimplemented from KKMLL::ModelParam.
Definition at line 84 of file ModelParamSvmBase.cpp.
References SVM289_MFS::svm_parameter::Gamma(), and KKMLL::ModelParam::Gamma().
double ModelParamSvmBase::Gamma () const virtual
Reimplemented from KKMLL::ModelParam.
Definition at line 97 of file ModelParamSvmBase.cpp.
References SVM289_MFS::svm_parameter::Gamma().
virtual void KKMLL::ModelParamSvmBase::KernalType (Kernel_Type _kernalType) inline virtual
Definition at line 45 of file ModelParamSvmBase.h.
virtual Kernel_Type KKMLL::ModelParamSvmBase::KernalType () const inline virtual
Definition at line 50 of file ModelParamSvmBase.h.
virtual ModelParamTypes KKMLL::ModelParamSvmBase::ModelParamType () const inline virtual
Implements KKMLL::ModelParam.
Definition at line 38 of file ModelParamSvmBase.h.
void ModelParamSvmBase::ReadXML (XmlStream & s, XmlTagConstPtr tag, RunLog & log) virtual
Implements KKMLL::ModelParam.
Definition at line 166 of file ModelParamSvmBase.cpp.
References KKB::KKStr::EqualIgnoreCase(), KKB::XmlStream::GetNextToken(), SVM289_MFS::svm_parameter::ParseTabDelStr(), KKMLL::ModelParam::ReadXMLModelParamToken(), and KKB::XmlToken::VarName().
const SVM289_MFS::svm_parameter& KKMLL::ModelParamSvmBase::SvmParam () inline
Definition at line 41 of file ModelParamSvmBase.h.
Referenced by KKMLL::ModelSvmBase::Description(), and KKMLL::ModelSvmBase::TrainModel().
virtual void KKMLL::ModelParamSvmBase::SvmType (SVM_Type _svm_type) inline virtual
Definition at line 46 of file ModelParamSvmBase.h.
virtual SVM_Type KKMLL::ModelParamSvmBase::SvmType () const inline virtual
Definition at line 51 of file ModelParamSvmBase.h.
KKStr ModelParamSvmBase::ToCmdLineStr () const virtual
Creates a Command Line String that represents these parameters.
Convert all parameters to a command line string.
All derived classes should implement this method. They should first call this method and then append there own parameters that are specific to their implementation.
Reimplemented from KKMLL::ModelParam.
Definition at line 131 of file ModelParamSvmBase.cpp.
References KKMLL::ModelParam::ToCmdLineStr(), and SVM289_MFS::svm_parameter::ToCmdLineStr().
void ModelParamSvmBase::WriteXML (const KKStr & varName, ostream & o) const virtual
Implements KKMLL::ModelParam.
Definition at line 142 of file ModelParamSvmBase.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::endl(), SVM289_MFS::svm_parameter::ToTabDelStr(), KKB::XmlTag::WriteXML(), KKB::KKStr::WriteXML(), and KKMLL::ModelParam::WriteXMLFields().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/KSquareLibraries/KKMachineLearning/ModelParamSvmBase.h
C:/Users/kurtk_000/GitHub/KSquareLibraries/KKMachineLearning/ModelParamSvmBase.cpp