Pices: KKMLL::TrainingClassList Class Reference
KKMLL::TrainingClassList Class Reference
#include <TrainingClass.h>
Public Member Functions
TrainingClassList ()
TrainingClassList (const KKStr &rootDir, bool owner)
TrainingClassList (const TrainingClassList &tcl, bool _owner)
void AddTrainingClass (TrainingClassPtr trainingClass)
TrainingClassList * DuplicateListAndContents () const
TrainingClassPtr LocateByDirectory (const KKStr &directory)
TrainingClassPtr LocateByMLClass (MLClassPtr _mlClass) const
TrainingClassPtr LocateByMLClassName (const KKStr &className)
virtual void ReadXML (XmlStream &s, XmlTagPtr tag, VolConstBool &cancelFlag, RunLog &log)
const KKStr & RootDir () const
void RootDir (const KKStr &_rootDir)
virtual void WriteXML (const KKStr &varName, std::ostream &o) const
Public Member Functions inherited from KKB::KKQueue< TrainingClass >
KKQueue (bool _owner=true)
KKQueue (const KKQueue &q, bool _owner)
Constructor, similar to the Copy Constructor except that you can control whether it duplicates the contents.
virtual ~KKQueue ()
Virtual destructor; if owns its contents will also call the destructor on each one entry that it contains.
virtual void Add (EntryPtr _entry)
same as PushOnBack
virtual void AddFirst (EntryPtr _entry)
same as PushOnFront
virtual void AddQueue (const KKQueue &q)
Add the contents of a separate KKQueue container to this container.
EntryPtr BackOfQueue () const
Returns pointer of last element in the container without removing it.
void DeleteContents ()
Empties the container, if 'owner' is set to true will call the destructor on each element.
void DeleteEntry (EntryPtr _entry)
Removes from KKQueue the entry who's pointer = '_entry'.
void DeleteEntry (kkuint32 _idx)
Removes from KKQueue the entry who's index = '_idx'.
KKQueue * DuplicateListAndContents () const
Creates a new container including duplicating the contents, which also makes the new instance the owner of those contents.
kkuint32 FindTheKthElement (kkuint32 k, Functor pred)
EntryPtr FrontOfQueue () const
Returns a pointer to the element that is at from of the queue with out removing it from the queue.
EntryPtr GetFirst () const
Same as FrontOfQueue.
EntryPtr GetLast () const
Same as BackOfQueue.
EntryPtr IdxToPtr (kkuint32 idx) const
Returns back a pointer to the element who's index is 'idx'.
kkint32 LocateEntry (EntryConstPtr _entry) const
Returns the index of the element who's address is '_entry'.
EntryPtr LookAtBack () const
Same as BackOfQueue.
EntryPtr LookAtFront () const
Same as FrontOfQueue.
bool operator!= (const KKQueue< TrainingClass > &rightSide) const
returns False if NOT every entry in both containers point to the same elements
KKQueue & operator= (const KKQueue &q)
Assignment Operator.
bool operator== (const KKQueue< TrainingClass > &rightSide) const
Returns True if every entry in both containers point to the same elements.
TrainingClass & operator[] (kkuint32 i) const
Returns a reference to element indexed by 'i'; similar to IdxToPtr except tat it returns a reference rather than a pointer.0.
bool Owner () const
void Owner (bool _owner)
You can specify who owns the contents of the container.
virtual EntryPtr PopFromBack ()
Removes the last element in the container and returns its pointer.
virtual EntryPtr PopFromFront ()
Removes the first element in the container and returns its pointer.
kkint32 PtrToIdx (EntryConstPtr _entry) const
returns the index of the 'entry' that has the same pointer as '_entry', if none found returns -1
virtual void PushOnBack (EntryPtr _entry)
Adds '_entry' to the End of the container.
virtual void PushOnFront (EntryPtr _entry)
Adds '_entry' to the Front of the container.
kkint32 QueueSize () const
Same as calling vector<>::size(); returns the number of elements in KKQueue.
void RandomizeOrder ()
Randomizes the order of the vector.
void RandomizeOrder (kkint64 seed)
void RandomizeOrder (RandomNumGenerator &randomVariable)
Randomizes the order of the vector.
virtual EntryPtr RemoveFirst ()
same as PopFromFront
virtual EntryPtr RemoveLast ()
same as PopFromBack
void SetIdxToPtr (kkuint32 _idx, TrainingClass *_ptr)
void SwapIndexes (size_t idx1, size_t idx2)
Additional Inherited Members
Public Types inherited from KKB::KKQueue< TrainingClass >
typedef std::vector< TrainingClass * >::const_iterator const_iterator
typedef std::vector< TrainingClass * >::iterator iterator
Protected Member Functions inherited from KKB::KKQueue< TrainingClass >
KKQueue (const KKQueue &q)
Copy Constructor creating new instance; including duplicating contents if owner set to true.
Detailed Description
Definition at line 142 of file TrainingClass.h.
Constructor & Destructor Documentation
TrainingClassList::TrainingClassList ()
Definition at line 288 of file TrainingClass.cpp.
Referenced by DuplicateListAndContents(), and TrainingClassList().
TrainingClassList::TrainingClassList (const KKStr & rootDir, bool owner)
Definition at line 296 of file TrainingClass.cpp.
References TrainingClassList().
TrainingClassList::TrainingClassList (const TrainingClassList & tcl, bool _owner)
Definition at line 314 of file TrainingClass.cpp.
Member Function Documentation
void TrainingClassList::AddTrainingClass (TrainingClassPtr trainingClass)
Definition at line 325 of file TrainingClass.cpp.
References KKB::KKQueue< TrainingClass >::PushOnBack().
Referenced by KKMLL::TrainingConfiguration2::GetFeatureNums(), ReadXML(), and KKMLL::TrainingConfiguration2::SetModelParameters().
TrainingClassListPtr TrainingClassList::DuplicateListAndContents () const
Definition at line 382 of file TrainingClass.cpp.
References KKB::KKQueue< Entry >::PushOnBack(), and TrainingClassList().
Referenced by KKMLL::TrainingConfiguration2::CreateFromDirectoryStructure(), and KKMLL::TrainingConfiguration2::ExtractFullHierachyOfClasses().
TrainingClassPtr TrainingClassList::LocateByDirectory (const KKStr & directory)
Definition at line 363 of file TrainingClass.cpp.
References KKMLL::TrainingClass::DirectoryCount(), KKB::KKStr::EqualIgnoreCase(), and KKMLL::TrainingClass::ExpandedDirectory().
Referenced by KKMLL::TrainingConfiguration2::CreateFromDirectoryStructure(), and KKMLL::TrainingConfiguration2::ExtractFullHierachyOfClasses().
TrainingClassPtr TrainingClassList::LocateByMLClass (MLClassPtr _mlClass) const
Definition at line 332 of file TrainingClass.cpp.
References KKMLL::TrainingClass::MLClass().
Referenced by KKMLL::TrainingConfiguration2::GetFeatureNums(), and KKMLL::TrainingConfiguration2::SetModelParameters().
TrainingClassPtr TrainingClassList::LocateByMLClassName (const KKStr & className)
Definition at line 346 of file TrainingClass.cpp.
Referenced by KKMLL::TrainingConfiguration2::GetFeatureNums(), and KKMLL::TrainingConfiguration2::LocateByMLClassName().
void TrainingClassList::ReadXML (XmlStream & s, XmlTagPtr tag, VolConstBool & cancelFlag, RunLog & log) virtual
Definition at line 429 of file TrainingClass.cpp.
References AddTrainingClass(), KKB::endl(), KKB::KKStr::EqualIgnoreCase(), KKB::XmlStream::GetNextToken(), KKB::RunLog::Level(), RootDir(), KKB::XmlElement::SectionName(), KKB::XmlElementTemplate< T >::TakeOwnership(), KKB::XmlToken::TokenType(), KKB::XmlElementTemplate< T >::Value(), and KKB::XmlElement::VarName().
const KKStr& KKMLL::TrainingClassList::RootDir () const inline
Definition at line 160 of file TrainingClass.h.
Referenced by ReadXML(), KKMLL::TrainingConfiguration2::RootDir(), and KKMLL::TrainingConfiguration2::Save().
void KKMLL::TrainingClassList::RootDir (const KKStr & _rootDir) inline
Definition at line 161 of file TrainingClass.h.
References KKMLL::TrainingClass::ReadXML(), and KKMLL::TrainingClass::WriteXML().
void TrainingClassList::WriteXML (const KKStr & varName, std::ostream & o) const virtual
Definition at line 398 of file TrainingClass.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::endl(), KKB::osSubstituteInEnvironmentVariables(), KKMLL::TrainingClass::WriteXML(), KKB::XmlTag::WriteXML(), and KKB::KKStr::WriteXML().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/TrainingClass.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/TrainingClass.cpp