Pices: MLL::DataBase Class Reference
MLL::DataBase Class Reference
DataBase connection management object.
#include <DataBase.h>
Public Types
typedef DataBase const * DataBaseConstPtr
typedef DataBase * DataBasePtr
typedef KKB::kkint32 kkint32
typedef KKB::kkint64 kkint64
typedef KKB::kkuint32 kkuint32
typedef KKB::kkuint64 kkuint64
typedef KKB::uchar uchar
typedef KKB::ulong ulong
Public Member Functions
DataBase (RunLog &_log)
DataBase (DataBaseServerConstPtr _server, RunLog &_log)
~DataBase ()
void Close ()
SipperDeploymentListPtr DeploymentLoadByStation (const KKStr &stationName)
bool DuplicateKey () const
void FeatureDataCreateTable ()
ImageFeaturesListPtr FeatureDataForImageGroup (const DataBaseImageGroupPtr imageGroup, MLClassPtr mlClass, char classKeyToUse, const bool &cancelFlag)
ImageFeaturesListPtr FeatureDataGetOneSipperFile (const KKStr &sipperFileRootName, MLClassPtr mlClass, char classKeyToUse, bool reExtractInstrumentData, bool &cancelFlag)
Returns a List of FeatureVector's for specified SipperFile and if specified for Specified ImaegClass.
std::vector< ulong > * FeatureDataGetScanLinesPerMeterProfile (const KKStr &sipperFileName)
void FeatureDataInsertRow (const KKStr &_sipperFileName, const ImageFeatures &example)
ImageFeaturesPtr FeatureDataRecLoad (DataBaseImagePtr image)
Retrieves FeatureData for a given 'DataBaseImage' object.
ImageFeaturesPtr FeatureDataRecLoad (const KKStr &imageFileName)
Retrieves FeatureData for a given ImageFileName It will also refresh the Instrument data fields of the 'ImageFeatures' objects from the 'InstruentData' table.
void FeatureDataUpdate (DataBaseImagePtr dataBaseImage, ImageFeaturesPtr example)
void FeatureDataUpdateInstrumentDataFields (const KKStr &imageFileName, InstrumentDataPtr instumentData)
void GpsDataDelete (const KKStr &cruiseName, const KKB::DateTime &utcDateTimeStart, const KKB::DateTime &utcDateTimeEnd)
void GpsDataInsert (const KKStr &cruiseName, const GPSDataPoint &gpsData)
GPSDataPointListPtr GpsDataQuery (const KKStr &cruiseName, const KKB::DateTime &utcDateTimeStart, const KKB::DateTime &utcDateTimeEnd)
GPSDataPointListPtr GpsDataQueryByIntervals (const KKStr &cruiseName, const KKB::DateTime &utcDateTimeStart, const KKB::DateTime &utcDateTimeEnd, kkint32 timeInterval)
Returns Summary GPSData for a specified Cruises and time range.
void ImageFullSizeDelete (const KKStr &imageFileName)
RasterSipperPtr ImageFullSizeFind (const KKStr &imageFileName)
Will locate a original size version of the image; it will try in order 3 different sources:
ThumbNail in Images Table.
RasterSipperPtr ImageFullSizeLoad (const KKStr &imageFileName)
RasterSipperPtr ImageFullSizeLoad (kkint32 imageId)
void ImageFullSizeSave (const KKStr &imageFileName, const RasterSipper &raster)
ClassStatisticListPtr ImageGetClassStatistics (DataBaseImageGroupPtr imageGroup, const KKStr &sipperFileName, MLClassPtr mlClass, char classKeyToUse, float minProb, float maxProb, kkint32 minSize, kkint32 maxSize, float minDepth, float maxDepth)
ClassStatisticListPtr ImageGetClassStatistics (DataBaseImageGroupPtr imageGroup, const KKStr &cruiseName, const KKStr &stationName, const KKStr &deploymentNum, MLClassPtr mlClass, char classKeyToUse, float minProb, float maxProb, kkint32 minSize, kkint32 maxSize, float minDepth, float maxDepth)
VectorUint * ImageGetDepthStatistics (DataBaseImageGroupPtr imageGroup, const KKStr &sipperFileName, float depthIncrements, MLClassPtr mlClass, char classKeyToUse, float minProb, float maxProb, kkint32 minSize, kkint32 maxSize)
Returns pointer to vector-of-unsigned-int instance that will contain counts by depth; each element in vector will represent a depth range as indicated by depthIncrements .
VectorUint * ImageGetDepthStatistics (DataBaseImageGroupPtr imageGroup, const KKStr &cruiseName, const KKStr &stationName, const KKStr &deploymentNum, float depthIncrements, MLClassPtr mlClass, char classKeyToUse, float minProb, float maxProb, kkint32 minSize, kkint32 maxSize, bool &cancelFlag)
void ImageGroupDelete (kkint32 imageGroupId)
void ImageGroupEntriesInsert (const DataBaseImageGroupEntry &imageGroupEntry)
void ImageGroupEntriesInsert (const DataBaseImageGroupEntryList &imageGroupList)
KKStrMatrixPtr ImageGroupEntriesInsert (kkint32 groupId, const VectorKKStr &imageFileNames)
DataBaseImageGroupEntryListPtr ImageGroupEntriesLoad (kkint32 groupId)
void ImageGroupInsert (DataBaseImageGroup &imageGroup)
DataBaseImageGroupListPtr ImageGroupLoad ()
DataBaseImageGroupPtr ImageGroupLoad (const KKStr &name)
void ImageInsert (const RasterSipper &image, const KKStr &imageFileName, const KKStr &sipperFileName, kkuint64 byteOffset, kkuint32 topLeftRow, kkuint32 topLeftCol, kkuint32 height, kkuint32 width, kkuint32 pixelCount, uchar connectedPixelDist, kkuint32 extractionLogEntryId, kkuint32 classLogEntryId, kkuint32 centroidRow, kkuint32 centroidCol, MLClassPtr class1, float class1Prob, MLClassPtr class2, float class2Prob, MLClassPtr validatedClass, float depth, float imageSize, PointListPtr sizeCoordinates, kkint32 &imageId, bool &successful)
Creates and entry in the Images table for 'image', if either dimension of 'image' exceeds 100 it will save a reduced version of it in the thumbNail field of 'Images' and a full size version in the ImagesFullSize table.
VectorKKStr * ImageListOfImageFileNamesByScanLineRange (const KKStr &sipperFileName, kkuint32 scanLineStart, kkuint32 scanLineEnd)
DataBaseImagePtr ImageLoad (kkuint32 imageId)
DataBaseImagePtr ImageLoad (const KKStr &imageFileName)
void ImageRemoveValidation (const KKStr &imageFileName)
void ImagesDeleteOneImage (const KKStr &imageFileName)
void ImagesEraseSipperFile (const KKStr &_sipperFileName)
Erases all data related to a single SipperFile except the entry in the SipperFiles table.
void ImagesEraseSipperFileSizeRange (const KKStr &_sipperFileName, kkuint32 _minSize, kkuint32 _maxSize)
Will remove all images and associated data for a specified SipperFile that are within the specified size range from the database.
void ImagesGetGpsData (const KKStr &imageRootName, double &latitude, double &longitude)
DataBaseImagePtr ImagesLocateClosestImage (const KKStr &imageFileName)
DataBaseImagePtr ImagesLocateClosestImage (const KKStr &sipperFileName, kkuint32 scanLine, kkuint32 scanCol)
DataBaseImageListPtr ImagesQuery (DataBaseImageGroupPtr group, bool includeThumbnail, const bool &cancelFlag)
DataBaseImageListPtr ImagesQuery (DataBaseImageGroupPtr imageGroup, const KKStr &sipperFileName, MLClassPtr mlClass, char classKeyToUse, float probMin, float probMax, kkint32 sizeMin, kkint32 sizeMax, float depthMin, float depthMax, kkuint32 restartImageId, kkint32 limit, bool includeThumbnail, const bool &cancelFlag)
DataBaseImageListPtr ImagesQuery (DataBaseImageGroupPtr imageGroup, const KKStr &cruiseName, const KKStr &stationName, const KKStr &deploymentNum, MLClassPtr mlClass, char classKeyToUse, float probMin, float probMax, kkint32 sizeMin, kkint32 sizeMax, float depthMin, float depthMax, kkuint32 restartImageId, kkint32 limit, bool includeThumbnail, const bool &cancelFlag)
DataBaseImageListPtr ImagesQuery (const KKStr &cruiseName, const KKStr &stationName, const KKStr &deploymentNum, MLClassPtr mlClass, char classKeyToUse, float minProb, float minSize, const KKStr &dataField1Name, float dataField1Min, float dataField1Max, const KKStr &dataField2Name, float dataField2Min, float dataField2Max, const KKStr &dataField3Name, float dataField3Min, float dataField3Max, kkuint32 restartImageId, kkint32 limit)
DataBaseImageListPtr ImagesQueryByGrouop (DataBaseImageGroupPtr imageGroup, const KKStr &cruiseName, const KKStr &stationName, const KKStr &deploymentNum, const KKStr &sipperFileName, MLClassPtr mlClass, char classKeyToUse, float probMin, float probMax, kkint32 sizeMin, kkint32 sizeMax, float depthMin, float depthMax, kkuint32 restartImageId, kkint32 limit, bool includeThumbnail)
DataBaseImageListPtr ImagesQueryDeploymentSizeRange (const KKStr &cruiseName, const KKStr &stationName, const KKStr &deploymentNum, MLClassPtr mlClass, char cast, char statistic, float sizeStart, float sizeEnd, float depthMin, float depthMax, kkint32 sampleQty, bool includeChildren, VolConstBool &cancelFlag)
DataBaseImageListPtr ImagesQueryForScanLineRange (const KKStr &sipperFileName, kkuint32 scanLineStart, kkuint32 scanLineEnd)
DataBaseImageValidatedEntryListPtr ImagesRetrieveValidatedClass (const KKStr &sipperFileName)
void ImagesSizeDistributionByDepth (const KKStr &cruiseName, const KKStr &stationName, const KKStr &deploymentNum, const KKStr &className, float maxDepth, float depthBinSize, char statistic, double initialValue, double growthRate, double endValue, ImageSizeDistributionPtr &downCast, ImageSizeDistributionPtr &upCast)
void ImagesUpdateImageSize (const KKStr &imageFileName, const PointListPtr sizeCoordinates, float imageSize)
void ImagesUpdatePredictions (const KKStr &imageFileName, MLClassPtr class1Pred, float class1Prob, MLClassPtr class2Pred, float class2Prob, kkuint32 logEntryId)
void ImagesUpdatePredictionsList (kkuint32 _logEntryId, const KKStr &_predictionList)
Updates prediction on multiple images at one time.
void ImagesUpdateValidatedAndPredictClass (const KKStr &imageFileName, MLClassPtr mlClass, float class1Prob)
Update both the Validates and Class1Name.
void ImagesUpdateValidatedClass (const KKStr &imageFileName, MLClassPtr mlClass)
void ImageUpdate (DataBaseImage &dbImage, RasterSipper &image)
void ImageUpdateInstrumentDataFields (InstrumentDataPtr instumentData, const KKStr &sipperFileName, kkuint32 scanLineStart, kkuint32 scanLineEnd)
void InsertCruise (const KKStr &shipName, const KKStr &description, const DateType &dateStart, const DateType &dateEnd, const KKStr &location, const KKStr &objective, const KKStr &principal, const KKStr &researchOrg)
InstrumentDataMeansListPtr InstrumentDataBinByMeterDepth (const KKStr &cruiseName, const KKStr &stationName, const KKStr &deploymentNum, float depthBinSize, const bool &cancelFlag)
void InstrumentDataDeploymentVolumeSampled (const KKStr &cruiseName, const KKStr &stationName, const KKStr &deploymentNum, float depthBinSize, VolumeSampledStatListPtr &downCast, VolumeSampledStatListPtr &upCast)
InstrumentDataPtr InstrumentDataGetByScanLine (const KKStr &sipperFileName, kkuint32 scanLine)
Retrieves the closest Instrument Data that precedes or equals 'ScanLine' but not more that 8192 scan-lines before.
VectorKKStr InstrumentDataGetFieldNames ()
Returns a list of all the field names in the Instrument Data table.
std::vector< std::vector< float > > * InstrumentDataGetSpecificFields (const KKStr &sipperFileName, const KKStrListPtr fieldNames, const KKB::DateTime &dateTimeStart, const KKB::DateTime &dateTimeEnd)
Returns 2d array consisting of the specific data fields from the Instrument data file for the specified SipperFile.
std::vector< std::vector< float > > * InstrumentDataGetSpecificFields (const KKStr &cruiseName, const KKStr &stationName, const KKStr &deploymentNum, const KKStrListPtr fieldNames, const KKB::DateTime &dateTimeStart, const KKB::DateTime &dateTimeEnd)
VolumeSampledStatListPtr InstrumentDataGetVolumePerMeterDepth (const KKStr &siperFileName, float depthBinSize)
Returns volume of water sampled, in cubic meters, by depth for a given sipper file.
VolumeSampledStatListPtr InstrumentDataGetVolumePerMeterDepth (const KKStr &cruiseName, const KKStr &stationName, const KKStr &deploymentNum, float depthBinSize, const bool &cancelFlag)
Returns volume of water sampled, in cubic meters, by depth for a complete deployment.
void InstrumentDataInsert (const KKStr &_sipperFileName, const InstrumentData &id)
InstrumentDataListPtr InstrumentDataLoad (const KKStr &sipperFileName, const bool &cancelFlag)
InstrumentDataListPtr InstrumentDataLoad (const KKStr &cruiseName, const KKStr &stationName, const KKStr &deploymentNum, const bool &cancelFlag)
void InstrumentDataLoadAllSipperFiles (const bool &cancelFlag)
Will extract Instrument Data from "ALL" known Sipper files and update the database tables.
void InstrumentDataReFreshSipperFile (const KKStr &sipperFileName, const bool &cancelFlag, char *msgBuff, kkint32 msgBuffLen)
Re-Extracts Instrument data from SIPPER file and updates DataBase tables to make sure they are correct.
GPSDataPointListPtr InstrumentDataRetrieveGPSInfo (const KKStr &cruiseName, const KKStr &stationName, const KKStr &deploymentNum, kkint32 timeInterval)
void InstrumentDataSaveListForOneSipperFile (const KKStr &_sipperFileName, const InstrumentDataList &instrumentData, const bool &_cancelFlag)
void InstrumentDataUpdateCropSettings (const KKStr &sipperFileName, kkuint32 scanLineStart, kkuint32 scanLineEnd, kkuint16 cropLeft, kkuint16 cropRight, kkuint16 activeColumns)
void InstrumentDataUpdateLatitudeAndLongitude (const KKB::DateTime &dateTimeStart, const KKB::DateTime &dateTimeEnd, double latitude, double longitude)
Update all InstrumentData entries that fall within the dateTime range with the specified Latitude and Longitude.
KKStr LastErrorDesc () const
void LogEntriesProcessEnd (DataBaseLogEntryPtr logEntry, float cpuTimeUsed, const KKStr &completionResult)
DataBaseLogEntryPtr LogEntriesProcessStart (const KKStr &progCode, const KKStr &progName, const KKB::DateTime &dateTimeCompiled, const KKStr &cmdLine, const KKStr &sipperFileName)
DataBaseLogEntryPtr LogEntriesSelect (kkuint32 _logEntryId)
void MLClassDelete (const KKStr &mlClassName)
void MLClassInsert (MLClass &mlClass, bool &successful)
void MLClassInsertReturn (MLClass &mlClass, bool &successful)
Inserts 'mlClass' into database if it is not already in it and then updates all the fields in 'mlClass' with the data in the database.
MLClassPtr MLClassLoad (const KKStr &className)
MLClassListPtr MLClassLoadChildren (const KKStr &className)
MLClassListPtr MLClassLoadList ()
void MLClassUpdate (const KKStr &oldClassName, const MLClass &mlClass, bool &successful)
kkint32 QueryStatement (const char *queryStr, kkint32 queryStrLen)
kkint32 QueryStatement (const KKStr &statement)
kkint32 QueryStatement2 (const char *queryStr, kkint32 queryStrLen)
Will make SQL Query call; if there is a disconnect from the database; it will not try to Reconnect like the other 'QueryStatement2' calls.
KKStrMatrixPtr QueryStatementKKStr (const KKStr &statement, ConstCharStarArray colsToReturn)
Will make MySQL call contained in 'statement'.
KKStrMatrixPtr QueryStatementReturnAllColumns (const char *statement, kkint32 statementLen, VectorKKStr &columnsReturned)
void ResultSetsClear ()
Call this method after you are done processing the results of the last query.
const DataBaseServerPtr Server () const
KKStr ServerDescription () const
return description of server that this instance is connected to.
void SipperCruiseDelete (const KKStr &cruiseName)
void SipperCruiseInsert (SipperCruisePtr cruise, bool &successful)
SipperCruisePtr SipperCruiseLoad (const KKStr &cruiseName)
SipperCruiseListPtr SipperCruiseLoadAllCruises ()
void SipperCruiseUpdate (SipperCruisePtr cruise, bool &successful)
void SipperDeploymentDelete (const KKStr &cruiseName, const KKStr &stationName, const KKStr &deploymentNum)
void SipperDeploymentInsert (const SipperDeployment &deployment)
SipperDeploymentListPtr SipperDeploymentLoad (const KKStr &cruiseName, const KKStr &stationName)
SipperDeploymentPtr SipperDeploymentLoad (const KKStr &cruiseName, const KKStr &stationName, const KKStr &deploymentNum)
void SipperDeploymentUpdate (const SipperDeployment &deployment)
VectorKKStr * SipperFileGetList (const KKStr &cruiseName, const KKStr &stationName, const KKStr &deploymentNum)
void SipperFileInsert (SipperFile &sipperFile)
SipperFileListPtr SipperFileLoad (const KKStr &cruiseName, const KKStr &stationName, const KKStr &deploymentNum)
void SipperFileLoadOracle ()
SipperFilePtr SipperFileRecLoad (const KKStr &_sipperFileName)
void SipperFilesDelete (const KKStr &_sipperFileName)
Delete a Sipper File and all its related data from all tables in database.
void SipperFilesGetCTDDateTime (const KKStr &_sipperFileName, kkint32 &_sipperFileId, kkuint32 &_numScanLines, KKB::DateTime &_CTDDateTimeStart, KKB::DateTime &_CTDDateTimeEnd)
void SipperFilesUpdateExtractionStatus (const KKStr &sipperFileName, char extractionStatus)
void SipperFilesUpdateExtractionStatusIfExpected (const KKStr &sipperFileName, char extractionStatusExpected, char extractionStatusNew, char &ExtractionStatusBeforeUpdate, char &extractionStatusResult, bool &extrtactionSatusUpdated)
Updates the ExtractionStatus only if the existing extractioStatus is what was expected.
void SipperFileUpdate (SipperFile &sipperFile)
void SipperFileUpdateFileSizeStats (const KKStr &_sipperFileName, kkint64 _sizeInBytes, kkuint32 _numScanLines)
void SipperStationDelete (const KKStr &cruiseName, const KKStr &stationName)
void SipperStationInsert (const SipperStation &station)
SipperStationListPtr SipperStationLoad (const KKStr &cruiseName)
SipperStationPtr SipperStationLoad (const KKStr &cruiseName, const KKStr &stationName)
SipperStationListPtr SipperStationsLoadByGpsRange (double latitudeMin, double latitudeMax, double longitudeMin, double longitudeMax)
void SipperStationUpdate (const SipperStation &station)
bool Valid () const
Static Public Member Functions
static bool EmbeddedServerRunning ()
Indicates that the Embedded server has been initialize and consuming resources.
static void ErrorLogMsg (const KKStr &msg)
static void FinalCleanUp ()
static DataBaseServerPtr GetDefaultServer (RunLog &_log)
Returns an instance of the current server; caller will own it.
static DataBaseServerListPtr GetListOfServers (RunLog &_log)
Returns a list of previously defined MySQL servers that we can connect to.
static DataBaseServerPtr GetServer (const KKStr &description, RunLog &_log)
returns an instance of the server with 'description'; caller will own it.
static void Initialization ()
static void ThreadEnd ()
Call just before thread terminates.
static bool ThreadInit ()
Call at start of new thread.
Detailed Description
DataBase connection management object.
All database communications will go through this class.
Author
Kurt Kramer
Date
Dec/01/2008
Definition at line 76 of file DataBase.h.
Member Typedef Documentation
typedef DataBase const* MLL::DataBase::DataBaseConstPtr
Definition at line 80 of file DataBase.h.
typedef DataBase* MLL::DataBase::DataBasePtr
Definition at line 79 of file DataBase.h.
typedef KKB::kkint32 MLL::DataBase::kkint32
Definition at line 84 of file DataBase.h.
typedef KKB::kkint64 MLL::DataBase::kkint64
Definition at line 86 of file DataBase.h.
typedef KKB::kkuint32 MLL::DataBase::kkuint32
Definition at line 85 of file DataBase.h.
typedef KKB::kkuint64 MLL::DataBase::kkuint64
Definition at line 87 of file DataBase.h.
typedef KKB::uchar MLL::DataBase::uchar
Definition at line 82 of file DataBase.h.
typedef KKB::ulong MLL::DataBase::ulong
Definition at line 83 of file DataBase.h.
Constructor & Destructor Documentation
DataBase::DataBase (RunLog & _log)
Definition at line 530 of file DataBase.cpp.
References MLL::PicesVariables::AllowUpdates(), KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
DataBase::DataBase (DataBaseServerConstPtr _server, RunLog & _log)
Parameters
_server Will make own local copy of "_server"
Definition at line 554 of file DataBase.cpp.
References MLL::PicesVariables::AllowUpdates(), KKB::GoalKeeper::EndBlock(), KKB::endl(), KKB::RunLog::Level(), and KKB::GoalKeeper::StartBlock().
DataBase::~DataBase ()
Definition at line 596 of file DataBase.cpp.
References Close(), KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
Member Function Documentation
void DataBase::Close ()
Definition at line 613 of file DataBase.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
Referenced by FinalCleanUp(), and ~DataBase().
SipperDeploymentListPtr DataBase::DeploymentLoadByStation (const KKStr & stationName)
Definition at line 5263 of file DataBase.cpp.
References QueryStatement(), and KKB::KKStr::QuotedStr().
bool MLL::DataBase::DuplicateKey () const inline
Definition at line 124 of file DataBase.h.
Referenced by PicesInterface::PicesDataBase::DuplicateKey().
bool DataBase::EmbeddedServerRunning () static
Indicates that the Embedded server has been initialize and consuming resources.
Definition at line 210 of file DataBase.cpp.
void DataBase::ErrorLogMsg (const KKStr & msg) static
Definition at line 226 of file DataBase.cpp.
References KKB::KKStr::Empty(), KKB::endl(), KKB::osAddSlash(), KKB::osCreateDirectoryPath(), KKB::osDisplayWarning(), KKB::osGetLocalDateTime(), KKB::osGetThreadId(), and KKB::osValidDirectory().
Referenced by DateToQuotedStr(), QueryStatement(), QueryStatement2(), ResultSetsClear(), ServerDescription(), and ThreadInit().
void DataBase::FeatureDataCreateTable ()
Definition at line 1768 of file DataBase.cpp.
References KKB::KKStr::Empty(), KKB::endl(), KKB::RunLog::Level(), MLL::FeatureFileIOPices::PlanktonFieldName(), MLL::FeatureFileIOPices::PlanktonMaxNumOfFields(), QueryStatement(), and ResultSetsClear().
ImageFeaturesListPtr DataBase::FeatureDataForImageGroup (const DataBaseImageGroupPtr imageGroup, MLClassPtr mlClass, char classKeyToUse, const bool & cancelFlag)
Definition at line 2178 of file DataBase.cpp.
References KKB::KKStr::Append(), KKB::endl(), MLL::DataBaseImageGroup::ImageGroupId(), KKB::RunLog::Level(), MLL::DataBaseImageGroup::Name(), QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
ImageFeaturesListPtr DataBase::FeatureDataGetOneSipperFile (const KKStr & sipperFileName, MLClassPtr mlClass, char classKeyToUse, bool reExtractInstrumentData, bool & cancelFlag)
Returns a List of FeatureVector's for specified SipperFile and if specified for Specified ImaegClass.
Loads all Images with related Feature data for the specified 'SipperFile'.
The retrieval is driven by the Images table and a Left-Join is done with the FeatureData table; so if there is no corresponding FeatureData table entry for a image the FeaterData will be filled with 0's.
Parameters
[in] classKeyToUse If equal to 'V' will only return Validated examples.
[in] reExtractInstrumentData If set to true will Re-Extract Instrument data from the SipperFile.
[in] sipperFileName Sipper file to retrieve feature data for.
[in] mlClass You are only interested in feature data for a specific class; whether predicted or validated class depends on 'classKeyToUse'.
[in] classKeyToUse Indicates which ClassId field to use for selecting feature data by class; 'V' = 'Images.ClassValidatedId' otherwise 'Images.Class1Id'.
[in] reExtractInstrumentData True indicates to re-extract feature data from the original SipperFile and update InmstrumentData tables.
[in] cancelFlag Flag will be monitored; if turns true the method will return at 1st chance.
Definition at line 2088 of file DataBase.cpp.
References KKB::KKStr::Append(), MLL::InstrumentData::Depth(), MLL::ImageFeatures::Depth(), MLL::InstrumentData::FlowRate1(), MLL::ImageFeatures::FlowRate1(), MLL::InstrumentData::FlowRate2(), MLL::ImageFeatures::FlowRate2(), MLL::InstrumentData::Fluorescence(), MLL::ImageFeatures::Fluorescence(), InstrumentDataSaveListForOneSipperFile(), MLL::InstrumentData::Latitude(), MLL::ImageFeatures::Latitude(), MLL::InstrumentData::Longitude(), MLL::ImageFeatures::Longitude(), KKB::Max(), KKB::osGetRootName(), MLL::InstrumentData::Oxygen(), MLL::ImageFeatures::Oxygen(), QueryStatement(), KKB::KKStr::QuotedStr(), MLL::InstrumentDataFileManager::ReExtractInstrumentDataForSipperFile(), ResultSetsClear(), MLL::InstrumentData::Salinity(), MLL::ImageFeatures::Salinity(), MLL::InstrumentDataList::SearchForNearestScanLine(), MLL::ImageFeatures::SfCentroidRow(), and SipperFileRecLoad().
vector< KKB::ulong > * DataBase::FeatureDataGetScanLinesPerMeterProfile (const KKStr & sipperFileName)
Definition at line 2288 of file DataBase.cpp.
References KKB::osGetRootName(), KKB::KKQueue< Entry >::PushOnBack(), QueryStatement(), and KKB::KKStr::QuotedStr().
void DataBase::FeatureDataInsertRow (const KKStr & _sipperFileName, const ImageFeatures & example)
Definition at line 1809 of file DataBase.cpp.
References KKMLL::FeatureVector::ExampleFileName(), KKMLL::FeatureVector::FeatureData(), IsFinite(), KKB::IsNaN(), KKMLL::FeatureVector::NumOfFeatures(), KKB::osGetRootName(), QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
ImageFeaturesPtr DataBase::FeatureDataRecLoad (DataBaseImagePtr image)
Retrieves FeatureData for a given 'DataBaseImage' object.
It will also refresh the Instrument data fields of the 'ImageFeatures' objects from the 'InstruentData' table
Definition at line 2071 of file DataBase.cpp.
References MLL::DataBaseImage::ImageFileName().
ImageFeaturesPtr DataBase::FeatureDataRecLoad (const KKStr & imageFileName)
Retrieves FeatureData for a given ImageFileName It will also refresh the Instrument data fields of the 'ImageFeatures' objects from the 'InstruentData' table.
Definition at line 1998 of file DataBase.cpp.
References MLL::ImageFeatures::Depth(), KKB::endl(), KKMLL::FeatureVector::ExampleFileName(), MLL::ImageFeatures::FlowRate1(), MLL::ImageFeatures::FlowRate2(), MLL::ImageFeatures::Fluorescence(), InstrumentDataGetByScanLine(), MLL::ImageFeatures::Latitude(), KKB::RunLog::Level(), MLL::ImageFeatures::Longitude(), KKB::Max(), KKB::osGetRootName(), MLL::ImageFeatures::Oxygen(), MLL::ImageFeaturesList::PopFromBack(), QueryStatement(), KKB::KKQueue< Entry >::QueueSize(), KKB::KKStr::QuotedStr(), ResultSetsClear(), MLL::ImageFeatures::Salinity(), MLL::ImageFeatures::SfCentroidRow(), and MLL::InstrumentDataFileManager::SipperFileRootNameFromSipperImageFileName().
void DataBase::FeatureDataUpdate (DataBaseImagePtr dataBaseImage, ImageFeaturesPtr example)
Definition at line 2224 of file DataBase.cpp.
References KKMLL::FeatureVector::ExampleFileName(), KKMLL::FeatureVector::FeatureData(), MLL::DataBaseImage::ImageId(), KKMLL::FeatureVector::NumOfFeatures(), KKB::osGetRootName(), MLL::FeatureFileIOPices::PlanktonFieldName(), QueryStatement(), and KKB::KKStr::QuotedStr().
void DataBase::FeatureDataUpdateInstrumentDataFields (const KKStr & imageFileName, InstrumentDataPtr instumentData)
Definition at line 2260 of file DataBase.cpp.
References MLL::InstrumentData::Depth(), MLL::InstrumentData::FlowRate1(), MLL::InstrumentData::FlowRate2(), MLL::InstrumentData::Fluorescence(), MLL::InstrumentData::Oxygen(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and MLL::InstrumentData::Salinity().
void DataBase::FinalCleanUp () static
When using Embedded server inside a ".net" application you need to call the "FinalCleanUp" method at the same level that the Initialization method gets called. If you wait until the "atexit function in "DateBase" gets called all the threads that the MySQL server create will be terminated and "mysql_library_end" will hang.
Definition at line 430 of file DataBase.cpp.
References Close(), KKB::endl(), initializeMySqlLibraryEmbeddedThreadId, and KKB::osGetThreadId().
DataBaseServerPtr DataBase::GetDefaultServer (RunLog & _log) static
Returns an instance of the current server; caller will own it.
Definition at line 672 of file DataBase.cpp.
References KKB::GoalKeeper::EndBlock(), MLL::DataBaseServerList::GetDefaultServer(), and KKB::GoalKeeper::StartBlock().
DataBaseServerListPtr DataBase::GetListOfServers (RunLog & _log) static
Returns a list of previously defined MySQL servers that we can connect to.
Definition at line 659 of file DataBase.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
Referenced by ServerDescription().
DataBaseServerPtr DataBase::GetServer (const KKStr & description, RunLog & _log) static
returns an instance of the server with 'description'; caller will own it.
Definition at line 694 of file DataBase.cpp.
References KKB::GoalKeeper::EndBlock(), MLL::DataBaseServerList::LookUpByDescription(), and KKB::GoalKeeper::StartBlock().
Referenced by MLL::PicesApplication::ProcessCmdLineParameter().
void DataBase::GpsDataDelete (const KKStr & cruiseName, const KKB::DateTime & utcDateTimeStart, const KKB::DateTime & utcDateTimeEnd)
Definition at line 2441 of file DataBase.cpp.
References KKMLL::MLClass::Description(), KKB::KKStr::Empty(), KKMLL::MLClass::Mandatory(), KKMLL::MLClass::Parent(), KKMLL::MLClassList::PushOnBack(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), KKMLL::MLClass::Summarize(), KKB::KKStr::TrimLeft(), KKB::KKStr::TrimRight(), and KKB::DateTime::YYYY_MM_DD_HH_MM_SS().
void DataBase::GpsDataInsert (const KKStr & cruiseName, const GPSDataPoint & gpsData)
Definition at line 2365 of file DataBase.cpp.
References MLL::GPSDataPoint::CourseOverGround(), MLL::GPSDataPoint::GpsUtcTime(), MLL::GPSDataPoint::Latitude(), MLL::GPSDataPoint::Longitude(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), MLL::GPSDataPoint::SpeedOverGround(), KKB::StrFormatDouble(), and KKB::DateTime::YYYY_MM_DD_HH_MM_SS().
GPSDataPointListPtr DataBase::GpsDataQuery (const KKStr & cruiseName, const KKB::DateTime & utcDateTimeStart, const KKB::DateTime & utcDateTimeEnd)
Definition at line 2392 of file DataBase.cpp.
References QueryStatement(), KKB::KKStr::QuotedStr(), and KKB::DateTime::YYYY_MM_DD_HH_MM_SS().
GPSDataPointListPtr DataBase::GpsDataQueryByIntervals (const KKStr & cruiseName, const KKB::DateTime & utcDateTimeStart, const KKB::DateTime & utcDateTimeEnd, kkint32 timeInterval)
Returns Summary GPSData for a specified Cruises and time range.
Each entry returned will be the average values for the range of entries that are with in 'timeInterval' seconds. This is done by grouping by using the function "Floor(Unix_Time(GpsUtcTime) / timeInterval)"
Definition at line 2414 of file DataBase.cpp.
References QueryStatement(), KKB::KKStr::QuotedStr(), KKB::StrFormatDouble(), and KKB::DateTime::YYYY_MM_DD_HH_MM_SS().
void DataBase::ImageFullSizeDelete (const KKStr & imageFileName)
Definition at line 4682 of file DataBase.cpp.
References QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
RasterSipperPtr DataBase::ImageFullSizeFind (const KKStr & imageFileName)
Will locate a original size version of the image; it will try in order 3 different sources:
ThumbNail in Images Table.
FullSizeImage in ImagesFullSize table
will go to SipperFile
Definition at line 4788 of file DataBase.cpp.
References KKB::Raster::FileName(), MLL::DataBaseImage::GetOrigImageFromSipperFile(), MLL::DataBaseImage::Height(), ImageFullSizeLoad(), ImageFullSizeSave(), ImageLoad(), KKB::Max(), MLL::DataBaseImage::ThumbNail(), KKB::KKException::ToString(), and MLL::DataBaseImage::Width().
RasterSipperPtr DataBase::ImageFullSizeLoad (const KKStr & imageFileName)
Definition at line 4659 of file DataBase.cpp.
References KKB::osGetRootName(), QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
Referenced by ImageFullSizeFind().
RasterSipperPtr MLL::DataBase::ImageFullSizeLoad (kkint32 imageId)
void DataBase::ImageFullSizeSave (const KKStr & imageFileName, const RasterSipper & raster)
Definition at line 4704 of file DataBase.cpp.
References KKB::endl(), KKB::RunLog::Level(), KKB::osGetRootName(), QueryStatement(), ResultSetsClear(), KKB::STRCAT(), KKB::STRCOPY(), and KKB::Raster::ToCompressor().
Referenced by ImageFullSizeFind(), ImageInsert(), and ImageUpdate().
ClassStatisticListPtr DataBase::ImageGetClassStatistics (DataBaseImageGroupPtr imageGroup, const KKStr & sipperFileName, MLClassPtr mlClass, char classKeyToUse, float minProb, float maxProb, kkint32 minSize, kkint32 maxSize, float minDepth, float maxDepth)
Definition at line 3074 of file DataBase.cpp.
References KKB::KKStr::Append(), MLL::DataBaseImageGroup::Name(), QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
Referenced by ImageGetClassStatistics().
ClassStatisticListPtr DataBase::ImageGetClassStatistics (DataBaseImageGroupPtr imageGroup, const KKStr & cruiseName, const KKStr & stationName, const KKStr & deploymentNum, MLClassPtr mlClass, char classKeyToUse, float minProb, float maxProb, kkint32 minSize, kkint32 maxSize, float minDepth, float maxDepth)
Definition at line 3124 of file DataBase.cpp.
References KKB::KKStr::Empty(), ImageGetClassStatistics(), and SipperFileGetList().
VectorUint * DataBase::ImageGetDepthStatistics (DataBaseImageGroupPtr imageGroup, const KKStr & sipperFileName, float depthIncrements, MLClassPtr mlClass, char classKeyToUse, float minProb, float maxProb, kkint32 minSize, kkint32 maxSize)
Returns pointer to vector-of-unsigned-int instance that will contain counts by depth; each element in vector will represent a depth range as indicated by depthIncrements .
Definition at line 3171 of file DataBase.cpp.
References KKB::KKStr::Append(), CharStarToUint32(), KKB::endl(), KKB::RunLog::Level(), MLL::DataBaseImageGroup::Name(), QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
Referenced by ImageGetDepthStatistics().
VectorUint * DataBase::ImageGetDepthStatistics (DataBaseImageGroupPtr imageGroup, const KKStr & cruiseName, const KKStr & stationName, const KKStr & deploymentNum, float depthIncrements, MLClassPtr mlClass, char classKeyToUse, float minProb, float maxProb, kkint32 minSize, kkint32 maxSize, bool & cancelFlag)
Definition at line 3244 of file DataBase.cpp.
References MLL::DataBaseImage::ByteOffset(), MLL::DataBaseImage::CentroidCol(), MLL::DataBaseImage::CentroidRow(), CharStarToFloat(), CharStarToInt32(), CharStarToInt64(), CharStarToUint32(), MLL::DataBaseImage::Class1(), MLL::DataBaseImage::Class1Prob(), MLL::DataBaseImage::Class2(), MLL::DataBaseImage::Class2Prob(), MLL::DataBaseImage::ClassLogEntryId(), KKB::KKStr::CompareIgnoreCase(), MLL::DataBaseImage::ConnectedPixelDist(), MLL::DataBaseImage::Depth(), KKB::KKStr::Empty(), MLL::DataBaseImage::EncodedThumbnail(), MLL::DataBaseImage::EncodedThumbnailLen(), KKB::endl(), KKB::KKStr::EqualIgnoreCase(), MLL::DataBaseImage::ExtractionLogEntryId(), MLL::DataBaseImage::Height(), MLL::DataBaseImage::ImageFileName(), ImageGetDepthStatistics(), MLL::DataBaseImage::ImageId(), MLL::DataBaseImage::ImageSize(), KKB::RunLog::Level(), MLL::DataBaseImage::PixelCount(), KKB::KKQueue< Entry >::PushOnBack(), SipperFileGetList(), MLL::DataBaseImage::SipperFileName(), MLL::DataBaseImage::SizeCoordinates(), KKB::StrFormatInt(), MLL::DataBaseImage::TopLeftCol(), MLL::DataBaseImage::TopLeftRow(), MLL::DataBaseImage::ValidatedClass(), and MLL::DataBaseImage::Width().
void DataBase::ImageGroupDelete (kkint32 imageGroupId)
Definition at line 4974 of file DataBase.cpp.
References QueryStatement(), ResultSetsClear(), and KKB::KKStr::Str().
void DataBase::ImageGroupEntriesInsert (const DataBaseImageGroupEntry & imageGroupEntry)
Definition at line 5001 of file DataBase.cpp.
References MLL::DataBaseImageGroupEntry::ImageFileName(), MLL::DataBaseImageGroupEntry::ImageGroupId(), QueryStatement(), KKB::KKStr::QuotedStr(), and KKB::KKStr::Str().
Referenced by ImageGroupEntriesInsert().
void DataBase::ImageGroupEntriesInsert (const DataBaseImageGroupEntryList & imageGroupList)
Definition at line 5014 of file DataBase.cpp.
References ImageGroupEntriesInsert().
KKStrMatrixPtr DataBase::ImageGroupEntriesInsert (kkint32 groupId, const VectorKKStr & imageFileNames)
Will insert a list of images into the same group in ImageGroupEntries. A list of ImageFileNames that failed to be inserted with a description of the error will be returned. If NULL is returned the insertion failed completely. A 2 x n matrix will be returned, One row for each image that failed insertion:
[0,0] = ImageFileName for row '0' that failed insertion
[0,1] = Description of error that caused insertion to fail.
Since there is a limitation on the length of the MySQL parameter of 64K we need to make sure that the length of all the imageFileNames will be less than 64K that is sum_i (ImageFileNamess[i].Len ()) + imageFileNams.size () less 64000.
Definition at line 5028 of file DataBase.cpp.
References KKB::KKStrMatrix::AddRow(), KKB::endl(), KKB::RunLog::Level(), KKB::Max(), Min(), QueryStatement(), and ResultSetsClear().
DataBaseImageGroupEntryListPtr DataBase::ImageGroupEntriesLoad (kkint32 groupId)
Definition at line 5100 of file DataBase.cpp.
References MLL::SipperDeployment::ChamberWidth(), MLL::SipperDeployment::CropLeft(), MLL::SipperDeployment::CropRight(), MLL::SipperDeployment::CruiseName(), MLL::SipperDeployment::DateTimeEnd(), MLL::SipperDeployment::DateTimeStart(), MLL::SipperDeployment::DeploymentNum(), MLL::SipperDeployment::Description(), KKB::endl(), MLL::SipperDeployment::Latitude(), KKB::RunLog::Level(), MLL::SipperDeployment::Longitude(), KKB::KKQueue< Entry >::PushOnBack(), QueryStatement(), ResultSetsClear(), MLL::SipperDeployment::StationName(), MLL::SipperDeployment::SyncTimeStampActual(), MLL::SipperDeployment::SyncTimeStampCTD(), MLL::SipperDeployment::SyncTimeStampGPS(), and KKB::DateTime::Year().
void DataBase::ImageGroupInsert (DataBaseImageGroup & imageGroup)
Definition at line 4850 of file DataBase.cpp.
References MLL::DataBaseImageGroup::Description(), MLL::DataBaseImageGroup::ImageGroupId(), MLL::DataBaseImageGroup::Name(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and KKB::KKStr::Str().
DataBaseImageGroupListPtr DataBase::ImageGroupLoad ()
Definition at line 4929 of file DataBase.cpp.
References KKB::endl(), KKB::RunLog::Level(), QueryStatement(), and ResultSetsClear().
DataBaseImageGroupPtr DataBase::ImageGroupLoad (const KKStr & name)
Definition at line 4887 of file DataBase.cpp.
References QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
void DataBase::ImageInsert (const RasterSipper & image, const KKStr & imageFileName, const KKStr & sipperFileName, kkuint64 byteOffset, kkuint32 topLeftRow, kkuint32 topLeftCol, kkuint32 height, kkuint32 width, kkuint32 pixelCount, uchar connectedPixelDist, kkuint32 extractionLogEntryId, kkuint32 classLogEntryId, kkuint32 centroidRow, kkuint32 centroidCol, MLClassPtr class1, float class1Prob, MLClassPtr class2, float class2Prob, MLClassPtr validatedClass, float depth, float imageSize, PointListPtr sizeCoordinates, kkint32 & imageId, bool & successful)
Creates and entry in the Images table for 'image', if either dimension of 'image' exceeds 100 it will save a reduced version of it in the thumbNail field of 'Images' and a full size version in the ImagesFullSize table.
Definition at line 2847 of file DataBase.cpp.
References KKB::KKStr::Append(), KKB::Point::Col(), KKB::Raster::Height(), ImageFullSizeSave(), KKB::Max(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), KKB::Point::Row(), and KKB::Raster::Width().
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
VectorKKStr * DataBase::ImageListOfImageFileNamesByScanLineRange (const KKStr & sipperFileName, kkuint32 scanLineStart, kkuint32 scanLineEnd)
Definition at line 3997 of file DataBase.cpp.
References QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and KKB::StrFormatInt().
DataBaseImagePtr DataBase::ImageLoad (kkuint32 imageId)
Definition at line 3625 of file DataBase.cpp.
References KKB::KKQueue< Entry >::PopFromBack(), QueryStatement(), KKB::KKQueue< Entry >::QueueSize(), and ResultSetsClear().
Referenced by ImageFullSizeFind(), ImagesLocateClosestImage(), and ImageExtractionManager::ExtractionManager::ManageTheExtraction().
DataBaseImagePtr DataBase::ImageLoad (const KKStr & imageFileName)
Definition at line 3651 of file DataBase.cpp.
References KKB::endl(), KKB::KKQueue< Entry >::PopFromBack(), QueryStatement(), KKB::KKQueue< Entry >::QueueSize(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
void DataBase::ImageRemoveValidation (const KKStr & imageFileName)
Definition at line 4147 of file DataBase.cpp.
References QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
void DataBase::ImagesDeleteOneImage (const KKStr & imageFileName)
Definition at line 4207 of file DataBase.cpp.
References QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
void DataBase::ImagesEraseSipperFile (const KKStr & _sipperFileName)
Erases all data related to a single SipperFile except the entry in the SipperFiles table.
Calls stored procedure 'ImagesEraseSipperFile' which will delete all data related to sipper file '_sipperFileName' from the tables 'ImagesFullSize', 'ImageGroupEntries', 'InstrumentData', 'FeatureData', and 'Images'.
Definition at line 2987 of file DataBase.cpp.
References KKB::osGetRootName(), QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
void DataBase::ImagesEraseSipperFileSizeRange (const KKStr & _sipperFileName, kkuint32 _minSize, kkuint32 _maxSize)
Will remove all images and associated data for a specified SipperFile that are within the specified size range from the database.
Will also delete all Instrument data for the specified SIPPER file on the assumption that the calling procedure is going to re-extract instrument data.
Definition at line 3011 of file DataBase.cpp.
References CharStarToInt32(), INT_MAX, KKB::osGetRootName(), KKMLL::ClassStatisticList::PushOnBack(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and KKB::StrFromUint32().
Referenced by ImageExtractionManager::ExtractionManager::TerminateProcessing().
void DataBase::ImagesGetGpsData (const KKStr & imageRootName, double & latitude, double & longitude)
Definition at line 4322 of file DataBase.cpp.
References QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
Referenced by MLL::FeatureFileIOPices::LoadInSubDirectoryTree().
DataBaseImagePtr DataBase::ImagesLocateClosestImage (const KKStr & imageFileName)
Definition at line 3582 of file DataBase.cpp.
References MLL::PicesVariables::ParseImageFileName().
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
DataBaseImagePtr DataBase::ImagesLocateClosestImage (const KKStr & sipperFileName, kkuint32 scanLine, kkuint32 scanCol)
Definition at line 3595 of file DataBase.cpp.
References ImageLoad(), KKB::KKStrMatrix::NumCols(), KKB::KKStrMatrix::NumRows(), QueryStatementKKStr(), KKB::KKStr::QuotedStr(), and KKB::StrFormatInt().
DataBaseImageListPtr DataBase::ImagesQuery (DataBaseImageGroupPtr group, bool includeThumbnail, const bool & cancelFlag)
Definition at line 3681 of file DataBase.cpp.
References MLL::DataBaseImageGroup::Name(), QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
Referenced by ImagesQuery().
DataBaseImageListPtr DataBase::ImagesQuery (DataBaseImageGroupPtr imageGroup, const KKStr & sipperFileName, MLClassPtr mlClass, char classKeyToUse, float probMin, float probMax, kkint32 sizeMin, kkint32 sizeMax, float depthMin, float depthMax, kkuint32 restartImageId, kkint32 limit, bool includeThumbnail, const bool & cancelFlag)
Parameters
classKeyToUse 'P' - Use Predicted Class Key, 'V' - Validated Class
Definition at line 3708 of file DataBase.cpp.
References KKB::KKStr::Append(), MLL::DataBaseImageGroup::Name(), QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
DataBaseImageListPtr DataBase::ImagesQuery (DataBaseImageGroupPtr imageGroup, const KKStr & cruiseName, const KKStr & stationName, const KKStr & deploymentNum, MLClassPtr mlClass, char classKeyToUse, float probMin, float probMax, kkint32 sizeMin, kkint32 sizeMax, float depthMin, float depthMax, kkuint32 restartImageId, kkint32 limit, bool includeThumbnail, const bool & cancelFlag)
Definition at line 3761 of file DataBase.cpp.
References KKB::KKQueue< Entry >::AddQueue(), ImagesQuery(), ImagesQueryByGrouop(), KKB::KKQueue< Entry >::Owner(), and SipperFileGetList().
DataBaseImageListPtr MLL::DataBase::ImagesQuery (const KKStr & cruiseName, const KKStr & stationName, const KKStr & deploymentNum, MLClassPtr mlClass, char classKeyToUse, float minProb, float minSize, const KKStr & dataField1Name, float dataField1Min, float dataField1Max, const KKStr & dataField2Name, float dataField2Min, float dataField2Max, const KKStr & dataField3Name, float dataField3Min, float dataField3Max, kkuint32 restartImageId, kkint32 limit)
DataBaseImageListPtr DataBase::ImagesQueryByGrouop (DataBaseImageGroupPtr imageGroup, const KKStr & cruiseName, const KKStr & stationName, const KKStr & deploymentNum, const KKStr & sipperFileName, MLClassPtr mlClass, char classKeyToUse, float probMin, float probMax, kkint32 sizeMin, kkint32 sizeMax, float depthMin, float depthMax, kkuint32 restartImageId, kkint32 limit, bool includeThumbnail)
Definition at line 3822 of file DataBase.cpp.
References KKB::KKStr::Append(), MLL::DataBaseImageGroup::Name(), QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
Referenced by ImagesQuery().
DataBaseImageListPtr DataBase::ImagesQueryDeploymentSizeRange (const KKStr & cruiseName, const KKStr & stationName, const KKStr & deploymentNum, MLClassPtr mlClass, char cast, char statistic, float sizeStart, float sizeEnd, float depthMin, float depthMax, kkint32 sampleQty, bool includeChildren, VolConstBool & cancelFlag)
Parameters
cast 'U' = UpCast, 'D' = DownCast, 'B' = Both'
statistic '0' = Area mm^2, '1' = Diameter, '2' = Spheroid Volume and '3' = EBv ((4/3)(Pie)(Major/2)(Minor/2)^2)
Definition at line 3905 of file DataBase.cpp.
References KKB::KKQueue< Entry >::AddQueue(), KKB::KKStr::Append(), MLClassLoadChildren(), KKB::KKQueue< Entry >::Owner(), QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
DataBaseImageListPtr DataBase::ImagesQueryForScanLineRange (const KKStr & sipperFileName, kkuint32 scanLineStart, kkuint32 scanLineEnd)
Definition at line 3883 of file DataBase.cpp.
References QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and KKB::StrFormatInt().
DataBaseImageValidatedEntryListPtr DataBase::ImagesRetrieveValidatedClass (const KKStr & sipperFileName)
Definition at line 4166 of file DataBase.cpp.
References KKB::KKStr::Empty(), KKB::osGetRootName(), QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
Referenced by ImageExtractionManager::ExtractionManager::TerminateProcessing().
void DataBase::ImagesSizeDistributionByDepth (const KKStr & cruiseName, const KKStr & stationName, const KKStr & deploymentNum, const KKStr & className, float maxDepth, float depthBinSize, char statistic, double initialValue, double growthRate, double endValue, ImageSizeDistributionPtr & downCast, ImageSizeDistributionPtr & upCast)
Definition at line 4425 of file DataBase.cpp.
References MLL::ImageSizeDistribution::AddData(), KKB::KKStr::Append(), MLL::ImageSizeDistribution::DefineRow(), KKB::endl(), KKB::KKStr::EqualIgnoreCase(), InstrumentDataDeploymentVolumeSampled(), KKB::KKStr::Len(), KKB::RunLog::Level(), MLL::VolumeSampledStatList::Locate(), KKB::Max(), KKB::KKStrMatrix::NumRows(), QueryStatementReturnAllColumns(), KKB::KKStr::QuotedStr(), KKB::KKStr::Str(), KKB::KKStr::SubStrPart(), KKB::KKStr::ToFloat(), and MLL::VolumeSampledStat::VolumeSampled().
void DataBase::ImagesUpdateImageSize (const KKStr & imageFileName, const PointListPtr sizeCoordinates, float imageSize)
Definition at line 4118 of file DataBase.cpp.
References QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and KKB::PointList::ToDelStr().
Referenced by ImageExtractionManager::ExtractionManager::ManageTheExtraction().
void DataBase::ImagesUpdatePredictions (const KKStr & imageFileName, MLClassPtr class1Pred, float class1Prob, MLClassPtr class2Pred, float class2Prob, kkuint32 logEntryId)
Definition at line 4033 of file DataBase.cpp.
References QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
void DataBase::ImagesUpdatePredictionsList (kkuint32 _logEntryId, const KKStr & _predictionList)
Updates prediction on multiple images at one time.
Parameters
[in] _logEntryId Log id of process that is doing the classification.
[in] _predictionList A tab delimited string that will contain the list of predictions. Each image will be separated by line feed line-feed characters while each field for each usage will be separated by tabs. So if there are two images with predictions the string will look like
ImageFileRootName | tab | Class1Name | tab |Class1Prob | tab |Class2Name | tab |Class2Prob | tab | ImageFileRootName | tab | Class1Name | tab |Class1Prob | tab | Class2Name | tab | Class2Prob"
Definition at line 4071 of file DataBase.cpp.
References KKB::KKStr::Len(), QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
void DataBase::ImagesUpdateValidatedAndPredictClass (const KKStr & imageFileName, MLClassPtr mlClass, float class1Prob)
Update both the Validates and Class1Name.
Definition at line 4353 of file DataBase.cpp.
References QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
void DataBase::ImagesUpdateValidatedClass (const KKStr & imageFileName, MLClassPtr mlClass)
Definition at line 4092 of file DataBase.cpp.
References QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
Referenced by ImageExtractionManager::ExtractionManager::ManageTheExtraction().
void DataBase::ImageUpdate (DataBaseImage & dbImage, RasterSipper & image)
Definition at line 4226 of file DataBase.cpp.
References KKB::KKStr::Append(), MLL::DataBaseImage::ByteOffset(), MLL::DataBaseImage::CentroidCol(), MLL::DataBaseImage::CentroidRow(), MLL::DataBaseImage::Class1Name(), MLL::DataBaseImage::Class1Prob(), MLL::DataBaseImage::Class2Name(), MLL::DataBaseImage::Class2Prob(), MLL::DataBaseImage::ClassLogEntryId(), MLL::DataBaseImage::ConnectedPixelDist(), MLL::DataBaseImage::Depth(), MLL::DataBaseImage::ExtractionLogEntryId(), MLL::DataBaseImage::Height(), MLL::DataBaseImage::ImageFileName(), ImageFullSizeSave(), MLL::DataBaseImage::ImageId(), KKB::Max(), MLL::DataBaseImage::PixelCount(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), MLL::DataBaseImage::SipperFileName(), KKB::StrFormatInt(), MLL::DataBaseImage::TopLeftCol(), MLL::DataBaseImage::TopLeftRow(), MLL::DataBaseImage::ValidatedClassName(), and MLL::DataBaseImage::Width().
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
void DataBase::ImageUpdateInstrumentDataFields (InstrumentDataPtr instumentData, const KKStr & sipperFileName, kkuint32 scanLineStart, kkuint32 scanLineEnd)
Definition at line 4379 of file DataBase.cpp.
References MLL::InstrumentData::Depth(), KKB::endl(), MLL::InstrumentData::FlowRate1(), MLL::InstrumentData::FlowRate2(), MLL::InstrumentData::Fluorescence(), KKB::RunLog::Level(), MLL::InstrumentData::Oxygen(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and MLL::InstrumentData::Salinity().
Referenced by InstrumentDataReFreshSipperFile().
void DataBase::Initialization () static
Definition at line 201 of file DataBase.cpp.
void DataBase::InsertCruise (const KKStr & shipName, const KKStr & description, const DateType & dateStart, const DateType & dateEnd, const KKStr & location, const KKStr & objective, const KKStr & principal, const KKStr & researchOrg)
Definition at line 7031 of file DataBase.cpp.
References DateToQuotedStr(), KKB::endl(), KKB::KKStr::Len(), QueryStatement(), KKB::KKStr::QuotedStr(), KKB::KKStr::Str(), and KKB::KKStr::SubStrPart().
InstrumentDataMeansListPtr DataBase::InstrumentDataBinByMeterDepth (const KKStr & cruiseName, const KKStr & stationName, const KKStr & deploymentNum, float depthBinSize, const bool & cancelFlag)
Definition at line 6741 of file DataBase.cpp.
References KKB::endl(), KKB::RunLog::Level(), KKB::KKQueue< Entry >::PushOnBack(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and KKB::StrFormatDouble().
void DataBase::InstrumentDataDeploymentVolumeSampled (const KKStr & cruiseName, const KKStr & stationName, const KKStr & deploymentNum, float depthBinSize, VolumeSampledStatListPtr & downCast, VolumeSampledStatListPtr & upCast)
Definition at line 6685 of file DataBase.cpp.
References MLL::VolumeSampledStatList::Add(), KKB::endl(), KKB::RunLog::Level(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and KKB::StrFormatDouble().
Referenced by ImagesSizeDistributionByDepth().
InstrumentDataPtr DataBase::InstrumentDataGetByScanLine (const KKStr & sipperFileName, kkuint32 scanLine)
Retrieves the closest Instrument Data that precedes or equals 'ScanLine' but not more that 8192 scan-lines before.
Definition at line 6076 of file DataBase.cpp.
References KKB::KKQueue< Entry >::PopFromBack(), QueryStatement(), KKB::KKQueue< Entry >::QueueSize(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and KKB::StrFormatInt().
Referenced by FeatureDataRecLoad(), MLL::FeatureFileIOPices::FeatureDataReSink(), and MLL::FeatureFileIOPices::LoadInSubDirectoryTree().
VectorKKStr DataBase::InstrumentDataGetFieldNames ()
Returns a list of all the field names in the Instrument Data table.
Definition at line 6260 of file DataBase.cpp.
References QueryStatement().
vector< vector< float > > * DataBase::InstrumentDataGetSpecificFields (const KKStr & sipperFileName, const KKStrListPtr fieldNames, const KKB::DateTime & dateTimeStart, const KKB::DateTime & dateTimeEnd)
Returns 2d array consisting of the specific data fields from the Instrument data file for the specified SipperFile.
Returns
2D float array where each row will represent a Instrument row and each column will represent a field specified in 'fieldNames'.
Definition at line 6397 of file DataBase.cpp.
References KKB::KKStr::Empty(), QueryStatement(), KKB::KKQueue< Entry >::QueueSize(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and KKB::DateTime::YYYY_MM_DD_HH_MM_SS().
vector< vector< float > > * DataBase::InstrumentDataGetSpecificFields (const KKStr & cruiseName, const KKStr & stationName, const KKStr & deploymentNum, const KKStrListPtr fieldNames, const KKB::DateTime & dateTimeStart, const KKB::DateTime & dateTimeEnd)
Definition at line 6456 of file DataBase.cpp.
References KKB::KKStr::Empty(), QueryStatement(), KKB::KKQueue< Entry >::QueueSize(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and KKB::DateTime::YYYY_MM_DD_HH_MM_SS().
VolumeSampledStatListPtr DataBase::InstrumentDataGetVolumePerMeterDepth (const KKStr & siperFileName, float depthBinSize)
Returns volume of water sampled, in cubic meters, by depth for a given sipper file.
Definition at line 6612 of file DataBase.cpp.
References MLL::VolumeSampledStat::BinDepth(), MLL::VolumeSampledStat::BinId(), KKB::endl(), MLL::VolumeSampledStatList::Give(), KKB::RunLog::Level(), KKB::osGetRootName(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and MLL::VolumeSampledStat::VolumeSampled().
Referenced by InstrumentDataGetVolumePerMeterDepth().
VolumeSampledStatListPtr DataBase::InstrumentDataGetVolumePerMeterDepth (const KKStr & cruiseName, const KKStr & stationName, const KKStr & deploymentNum, float depthBinSize, const bool & cancelFlag)
Returns volume of water sampled, in cubic meters, by depth for a complete deployment.
Definition at line 6650 of file DataBase.cpp.
References InstrumentDataGetVolumePerMeterDepth(), and SipperFileGetList().
void DataBase::InstrumentDataInsert (const KKStr & _sipperFileName, const InstrumentData & id)
Definition at line 6104 of file DataBase.cpp.
References KKB::osGetRootName(), QueryStatement(), and KKB::KKStr::QuotedStr().
Referenced by InstrumentDataSaveListForOneSipperFile().
InstrumentDataListPtr DataBase::InstrumentDataLoad (const KKStr & sipperFileName, const bool & cancelFlag)
Definition at line 6294 of file DataBase.cpp.
References QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), MLL::SipperFile::ScanRate(), MLL::InstrumentDataList::ScanRate(), and SipperFileRecLoad().
Referenced by InstrumentDataLoad().
InstrumentDataListPtr DataBase::InstrumentDataLoad (const KKStr & cruiseName, const KKStr & stationName, const KKStr & deploymentNum, const bool & cancelFlag)
Definition at line 6326 of file DataBase.cpp.
References KKB::KKQueue< Entry >::AddQueue(), InstrumentDataLoad(), KKB::KKQueue< Entry >::Owner(), and SipperFileGetList().
void DataBase::InstrumentDataLoadAllSipperFiles (const bool & cancelFlag)
Will extract Instrument Data from "ALL" known Sipper files and update the database tables.
For each known SIPPER file; will load instrument data from Sipper file and save into 'InstrumentData' table. useful in populating 'InstrumentData' table. Make sure that the Instrument assignments are correct in 'SipperFiles'.
Also make sure that all the Sipper Files are in one of the directory trees specified by 'SipperDirectoryList.txt' in "%PicesHomeDir%\DataFiles"
Definition at line 6231 of file DataBase.cpp.
References KKB::endl(), MLL::InstrumentDataFileManager::GetListOfSipperFiles(), InstrumentDataSaveListForOneSipperFile(), KKB::KKStr::Len(), KKB::osGetRootName(), MLL::InstrumentDataFileManager::ReExtractInstrumentDataForSipperFile(), and SipperFileRecLoad().
void DataBase::InstrumentDataReFreshSipperFile (const KKStr & sipperFileName, const bool & cancelFlag, char * msgBuff, kkint32 msgBuffLen)
Re-Extracts Instrument data from SIPPER file and updates DataBase tables to make sure they are correct.
This method re-extracts instrument data for the given SipperFile and updates the appropriate tables. This way all tables are in agreement with each other. For the Specified SIPPER File "siperFileName".
- 1) Extract Instrument Data from original SipperFile.
- 2) Replaces all entries in IntrumentData table for 'sipperFile' with what was just extracted.
- 3) Updates the InstrumentData fields in Images with data just extracted.
Parameters
[in] sipperFileName Name of Sipper files that instrument data is to be extracted from; the root name will be used.
[in] cancelFlag The method will monitor this flag; if it goes true it will exit gracefully and return to caller.
[in] msgBuff Pointer to message buffer that the method will write NULL terminated strings to this field indicating progress;
[in] msgBuffLen Length in characters of 'msgBuff'.
This method re-extracts instrument data for the given SipperFile and updates the appropriate tables. This way all tables are in agreement with each other. For the Specified SIPPER File "siperFileName". 1) Extract Instrument Data from original SipperFile. 2) Replaces all entries in IntrumentData table for 'sipperFile' with what was just extracted. 3) Updates the InstrumentData fields in Images with data just extracted.
Definition at line 6538 of file DataBase.cpp.
References KKB::endl(), ImageUpdateInstrumentDataFields(), InstrumentDataSaveListForOneSipperFile(), MLL::InstrumentDataFileManager::ReExtractInstrumentDataForSipperFile(), MLL::InstrumentData::ScanLine(), SipperFileRecLoad(), and KKB::KKStr::Str().
GPSDataPointListPtr DataBase::InstrumentDataRetrieveGPSInfo (const KKStr & cruiseName, const KKStr & stationName, const KKStr & deploymentNum, kkint32 timeInterval)
< GpsUtcTime
< Latitude
< Longitude
< CourseOverGround
< SpeedOverGround
Parameters
timeInterval Interval in seconds
Definition at line 6817 of file DataBase.cpp.
References KKB::endl(), KKB::RunLog::Level(), LogEntriesProcessStart(), KKB::KKQueue< Entry >::PushOnBack(), QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
void DataBase::InstrumentDataSaveListForOneSipperFile (const KKStr & _sipperFileName, const InstrumentDataList & instrumentData, const bool & _cancelFlag)
Definition at line 6192 of file DataBase.cpp.
References MLL::SipperFile::AssignCtdExternalInstruments(), InstrumentDataInsert(), KKB::osGetRootName(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), SipperFileInsert(), and SipperFileRecLoad().
Referenced by FeatureDataGetOneSipperFile(), InstrumentDataLoadAllSipperFiles(), InstrumentDataReFreshSipperFile(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void DataBase::InstrumentDataUpdateCropSettings (const KKStr & sipperFileName, kkuint32 scanLineStart, kkuint32 scanLineEnd, kkuint16 cropLeft, kkuint16 cropRight, kkuint16 activeColumns)
Definition at line 6161 of file DataBase.cpp.
References QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and KKB::StrFormatInt().
void DataBase::InstrumentDataUpdateLatitudeAndLongitude (const KKB::DateTime & dateTimeStart, const KKB::DateTime & dateTimeEnd, double latitude, double longitude)
Update all InstrumentData entries that fall within the dateTime range with the specified Latitude and Longitude.
Will update all InstrumentData entries that fall within the dateTime range with the Latitude and longitude.
Definition at line 6367 of file DataBase.cpp.
References QueryStatement(), ResultSetsClear(), and KKB::StrFormatDouble().
KKStr DataBase::LastErrorDesc () const
Definition at line 1312 of file DataBase.cpp.
References KKB::DateTime::Date(), KKB::KKStr::ExtractToken(), KKB::KKStr::ExtractTokenInt(), KKB::TimeType::HH_MM_SS(), KKB::DateTime::Time(), KKB::KKStr::ToInt(), KKB::KKStr::ToInt16(), and KKB::DateType::YYYY_MM_DD().
Referenced by MLL::DataBaseUpdate::LoadSourceFile(), MLL::PicesApplication::ProcessCmdLineParameter(), and ImageExtractionManager::DataBaseUpdateThread::Run().
void DataBase::LogEntriesProcessEnd (DataBaseLogEntryPtr logEntry, float cpuTimeUsed, const KKStr & completionResult)
Definition at line 6923 of file DataBase.cpp.
References MLL::DataBaseLogEntry::DateTimeEnd(), KKB::endl(), KKB::RunLog::Level(), MLL::DataBaseLogEntry::LogEntryId(), QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
Referenced by ImageExtractionManager::ExtractionManager::ManageTheExtraction().
DataBaseLogEntryPtr DataBase::LogEntriesProcessStart (const KKStr & progCode, const KKStr & progName, const KKB::DateTime & dateTimeCompiled, const KKStr & cmdLine, const KKStr & sipperFileName)
Parameters
sipperFileName Root name of Sipper file; only if specific to a single Sipper File
Definition at line 6871 of file DataBase.cpp.
References MLL::DataBaseLogEntry::DataBaseUserName(), MLL::DataBaseLogEntry::DateTimeStart(), MLL::DataBaseLogEntry::DateTimeStartUtc(), MLL::DataBaseLogEntry::LogEntryId(), KKB::KKStr::MaxLen(), KKB::osGetHostName(), KKB::osGetRootName(), KKB::osGetUserName(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and KKB::DateTime::YYYY_MM_DD_HH_MM_SS().
Referenced by InstrumentDataRetrieveGPSInfo(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
DataBaseLogEntryPtr DataBase::LogEntriesSelect (kkuint32 _logEntryId)
Definition at line 6965 of file DataBase.cpp.
References MLL::DataBaseLogEntry::CmdLine(), MLL::DataBaseLogEntry::CompletionStatus(), MLL::DataBaseLogEntry::CompName(), MLL::DataBaseLogEntry::CompUserName(), MLL::DataBaseLogEntry::CpuTimeUsed(), MLL::DataBaseLogEntry::DataBaseUserName(), MLL::DataBaseLogEntry::DateTimeCompiled(), MLL::DataBaseLogEntry::DateTimeEnd(), MLL::DataBaseLogEntry::DateTimeStart(), MLL::DataBaseLogEntry::DateTimeStartUtc(), MLL::DataBaseLogEntry::LogEntryId(), MLL::DataBaseLogEntry::ProgCode(), MLL::DataBaseLogEntry::ProgName(), QueryStatement(), ResultSetsClear(), and MLL::DataBaseLogEntry::SipperFileName().
void DataBase::MLClassDelete (const KKStr & mlClassName)
Definition at line 2786 of file DataBase.cpp.
References KKB::Raster::Height(), KKB::Max(), QueryStatement(), KKB::KKStr::QuotedStr(), MLL::RasterSipper::ReduceByFactor(), ResultSetsClear(), MLL::RasterSipper::SimpleCompression(), and KKB::Raster::Width().
void DataBase::MLClassInsert (MLClass & mlClass, bool & successful)
Definition at line 2664 of file DataBase.cpp.
References KKMLL::MLClass::Description(), KKMLL::MLClass::Mandatory(), MLClassLoad(), KKMLL::MLClass::ParentName(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and KKMLL::MLClass::Summarize().
void DataBase::MLClassInsertReturn (MLClass & mlClass, bool & successful)
Inserts 'mlClass' into database if it is not already in it and then updates all the fields in 'mlClass' with the data in the database.
Definition at line 2705 of file DataBase.cpp.
References KKMLL::MLClass::Mandatory(), KKMLL::MLClass::ParentName(), QueryStatement(), KKB::KKQueue< Entry >::QueueSize(), KKB::KKStr::QuotedStr(), and KKMLL::MLClass::Summarize().
MLClassPtr DataBase::MLClassLoad (const KKStr & className)
Definition at line 2519 of file DataBase.cpp.
References KKB::KKQueue< Entry >::BackOfQueue(), KKB::endl(), KKB::RunLog::Level(), QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
Referenced by MLClassInsert().
MLClassListPtr DataBase::MLClassLoadChildren (const KKStr & className)
Definition at line 2638 of file DataBase.cpp.
References KKB::endl(), KKB::RunLog::Level(), QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
Referenced by ImagesQueryDeploymentSizeRange().
MLClassListPtr DataBase::MLClassLoadList ()
Definition at line 2550 of file DataBase.cpp.
References KKMLL::MLClass::Description(), KKB::KKStr::Empty(), KKB::endl(), KKB::KKStr::EqualIgnoreCase(), KKMLL::MLClass::IsAnAncestor(), KKB::RunLog::Level(), KKMLL::MLClassList::LookUpByName(), KKMLL::MLClass::Mandatory(), KKMLL::MLClassList::PushOnBack(), QueryStatement(), ResultSetsClear(), KKMLL::MLClass::StoredOnDataBase(), and KKMLL::MLClass::Summarize().
void DataBase::MLClassUpdate (const KKStr & oldClassName, const MLClass & mlClass, bool & successful)
Definition at line 2750 of file DataBase.cpp.
References KKMLL::MLClass::Description(), KKMLL::MLClass::Mandatory(), KKMLL::MLClass::ParentName(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and KKMLL::MLClass::Summarize().
KKB::kkint32 DataBase::QueryStatement (const char * queryStr, kkint32 queryStrLen)
Definition at line 1467 of file DataBase.cpp.
References KKB::KKStr::Append(), KKB::endl(), ErrorLogMsg(), KKB::RunLog::Level(), KKB::osGetLocalDateTime(), and ResultSetsClear().
Referenced by DeploymentLoadByStation(), FeatureDataCreateTable(), FeatureDataForImageGroup(), FeatureDataGetOneSipperFile(), FeatureDataGetScanLinesPerMeterProfile(), FeatureDataInsertRow(), FeatureDataRecLoad(), FeatureDataUpdate(), FeatureDataUpdateInstrumentDataFields(), GpsDataDelete(), GpsDataInsert(), GpsDataQuery(), GpsDataQueryByIntervals(), ImageFullSizeDelete(), ImageFullSizeLoad(), ImageFullSizeSave(), ImageGetClassStatistics(), ImageGetDepthStatistics(), ImageGroupDelete(), ImageGroupEntriesInsert(), ImageGroupEntriesLoad(), ImageGroupInsert(), ImageGroupLoad(), ImageInsert(), ImageListOfImageFileNamesByScanLineRange(), ImageLoad(), ImageRemoveValidation(), ImagesDeleteOneImage(), ImagesEraseSipperFile(), ImagesEraseSipperFileSizeRange(), ImagesGetGpsData(), ImagesQuery(), ImagesQueryByGrouop(), ImagesQueryDeploymentSizeRange(), ImagesQueryForScanLineRange(), ImagesRetrieveValidatedClass(), ImagesUpdateImageSize(), ImagesUpdatePredictions(), ImagesUpdatePredictionsList(), ImagesUpdateValidatedAndPredictClass(), ImagesUpdateValidatedClass(), ImageUpdate(), ImageUpdateInstrumentDataFields(), InsertCruise(), InstrumentDataBinByMeterDepth(), InstrumentDataDeploymentVolumeSampled(), InstrumentDataGetByScanLine(), InstrumentDataGetFieldNames(), InstrumentDataGetSpecificFields(), InstrumentDataGetVolumePerMeterDepth(), InstrumentDataInsert(), InstrumentDataLoad(), InstrumentDataRetrieveGPSInfo(), InstrumentDataSaveListForOneSipperFile(), InstrumentDataUpdateCropSettings(), InstrumentDataUpdateLatitudeAndLongitude(), LogEntriesProcessEnd(), LogEntriesProcessStart(), LogEntriesSelect(), MLClassDelete(), MLClassInsert(), MLClassInsertReturn(), MLClassLoad(), MLClassLoadChildren(), MLClassLoadList(), MLClassUpdate(), QueryStatementKKStr(), QueryStatementReturnAllColumns(), SipperCruiseDelete(), SipperCruiseInsert(), SipperCruiseLoad(), SipperCruiseLoadAllCruises(), SipperCruiseUpdate(), SipperDeploymentDelete(), SipperDeploymentInsert(), SipperDeploymentLoad(), SipperDeploymentUpdate(), SipperFileGetList(), SipperFileInsert(), SipperFileLoad(), SipperFileRecLoad(), SipperFilesDelete(), SipperFilesGetCTDDateTime(), SipperFilesUpdateExtractionStatus(), SipperFilesUpdateExtractionStatusIfExpected(), SipperFileUpdate(), SipperFileUpdateFileSizeStats(), SipperStationDelete(), SipperStationInsert(), SipperStationLoad(), SipperStationsLoadByGpsRange(), and SipperStationUpdate().
KKB::kkint32 DataBase::QueryStatement (const KKStr & statement)
Definition at line 1613 of file DataBase.cpp.
References KKB::endl(), ErrorLogMsg(), KKB::KKStr::Len(), KKB::RunLog::Level(), ResultSetsClear(), and KKB::KKStr::Str().
KKB::kkint32 DataBase::QueryStatement2 (const char * queryStr, kkint32 queryStrLen)
Will make SQL Query call; if there is a disconnect from the database; it will not try to Reconnect like the other 'QueryStatement2' calls.
Definition at line 1563 of file DataBase.cpp.
References KKB::KKStr::Append(), KKB::endl(), ErrorLogMsg(), and KKB::osGetLocalDateTime().
KKStrMatrixPtr DataBase::QueryStatementKKStr (const KKStr & statement, ConstCharStarArray colsToReturn)
Will make MySQL call contained in 'statement'.
and return back results as a Vector List of KKStr objects. colsToReturn - A list of columns to return from the result set.
Definition at line 1693 of file DataBase.cpp.
References KKB::KKStrMatrix::AddRow(), KKB::KKStr::Len(), KKB::KKQueue< Entry >::PushOnBack(), QueryStatement(), ResultSetsClear(), and KKB::KKStr::Str().
Referenced by ImagesLocateClosestImage().
KKStrMatrixPtr DataBase::QueryStatementReturnAllColumns (const char * statement, kkint32 statementLen, VectorKKStr & columnsReturned)
Definition at line 1727 of file DataBase.cpp.
References KKB::KKStrMatrix::AddRow(), KKB::KKQueue< Entry >::PushOnBack(), QueryStatement(), and ResultSetsClear().
Referenced by ImagesSizeDistributionByDepth(), and MLL::DataBaseUpdate::LoadSourceFile().
void DataBase::ResultSetsClear ()
Call this method after you are done processing the results of the last query.
If you do not do this the next call may fail.
Definition at line 1064 of file DataBase.cpp.
References CharStarToDouble(), CharStarToFloat(), CharStarToInt32(), CharStarToInt64(), CharStarToUint16(), CharStarToUint32(), CharStarToUint64(), CharStarToUlong(), KKB::endl(), ErrorLogMsg(), MLL::RasterSipper::FromCompressor(), KKB::RunLog::Level(), KKB::STRICMP(), KKB::KKException::ToString(), and KKB::KKStr::Upper().
Referenced by FeatureDataCreateTable(), FeatureDataForImageGroup(), FeatureDataGetOneSipperFile(), FeatureDataInsertRow(), FeatureDataRecLoad(), FeatureDataUpdateInstrumentDataFields(), GpsDataDelete(), GpsDataInsert(), ImageFullSizeDelete(), ImageFullSizeLoad(), ImageFullSizeSave(), ImageGetClassStatistics(), ImageGetDepthStatistics(), ImageGroupDelete(), ImageGroupEntriesInsert(), ImageGroupEntriesLoad(), ImageGroupInsert(), ImageGroupLoad(), ImageInsert(), ImageListOfImageFileNamesByScanLineRange(), ImageLoad(), ImageRemoveValidation(), ImagesDeleteOneImage(), ImagesEraseSipperFile(), ImagesEraseSipperFileSizeRange(), ImagesGetGpsData(), ImagesQuery(), ImagesQueryByGrouop(), ImagesQueryDeploymentSizeRange(), ImagesQueryForScanLineRange(), ImagesRetrieveValidatedClass(), ImagesUpdateImageSize(), ImagesUpdatePredictions(), ImagesUpdatePredictionsList(), ImagesUpdateValidatedAndPredictClass(), ImagesUpdateValidatedClass(), ImageUpdate(), ImageUpdateInstrumentDataFields(), InstrumentDataBinByMeterDepth(), InstrumentDataDeploymentVolumeSampled(), InstrumentDataGetByScanLine(), InstrumentDataGetSpecificFields(), InstrumentDataGetVolumePerMeterDepth(), InstrumentDataLoad(), InstrumentDataRetrieveGPSInfo(), InstrumentDataSaveListForOneSipperFile(), InstrumentDataUpdateCropSettings(), InstrumentDataUpdateLatitudeAndLongitude(), LogEntriesProcessEnd(), LogEntriesProcessStart(), LogEntriesSelect(), MLClassDelete(), MLClassInsert(), MLClassLoad(), MLClassLoadChildren(), MLClassLoadList(), MLClassUpdate(), QueryStatement(), QueryStatementKKStr(), QueryStatementReturnAllColumns(), SipperCruiseDelete(), SipperCruiseLoad(), SipperCruiseLoadAllCruises(), SipperDeploymentDelete(), SipperDeploymentInsert(), SipperDeploymentUpdate(), SipperFileRecLoad(), SipperFilesDelete(), SipperFilesGetCTDDateTime(), SipperFilesUpdateExtractionStatusIfExpected(), SipperStationDelete(), SipperStationInsert(), and SipperStationUpdate().
const DataBaseServerPtr MLL::DataBase::Server () const inline
Definition at line 125 of file DataBase.h.
Referenced by MLL::PicesApplication::InitalizeApplication(), and MLL::PicesApplication::PicesApplication().
KKStr DataBase::ServerDescription () const
return description of server that this instance is connected to.
Definition at line 719 of file DataBase.cpp.
References MLL::DataBaseServer::DataBaseName(), MLL::DataBaseServer::Description(), KKB::endl(), KKB::KKStr::EqualIgnoreCase(), ErrorLogMsg(), MLL::DataBaseServerList::GetDefaultServer(), GetListOfServers(), MLL::DataBaseServer::HostName(), KKB::RunLog::Level(), MLL::DataBaseServer::PassWord(), MLL::DataBaseServer::ServerDescription(), KKB::KKStr::Str(), KKB::STRDUP(), MLL::DataBaseServer::UserName(), and Valid().
Referenced by ImageExtractionManager::ExtractionManager::ManageTheExtraction(), MLL::PicesApplication::PrintStandardHeaderInfo(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void DataBase::SipperCruiseDelete (const KKStr & cruiseName)
Definition at line 7070 of file DataBase.cpp.
References QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and KKB::KKStr::Str().
void DataBase::SipperCruiseInsert (SipperCruisePtr cruise, bool & successful)
Definition at line 7086 of file DataBase.cpp.
References MLL::SipperCruise::CruiseName(), MLL::SipperCruise::DateEnd(), MLL::SipperCruise::DateStart(), MLL::SipperCruise::Description(), KKB::endl(), MLL::SipperCruise::Location(), MLL::SipperCruise::Objective(), MLL::SipperCruise::Principal(), QueryStatement(), KKB::KKStr::QuotedStr(), MLL::SipperCruise::ResearchOrg(), MLL::SipperCruise::ShipName(), KKB::KKStr::Str(), and KKB::DateType::YYYY_MM_DD().
Referenced by ImageExtractionManager::ExtractionManager::TerminateProcessing().
SipperCruisePtr DataBase::SipperCruiseLoad (const KKStr & cruiseName)
Definition at line 7185 of file DataBase.cpp.
References KKB::KKQueue< Entry >::PopFromBack(), QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
Referenced by ImageExtractionManager::ExtractionManager::TerminateProcessing().
SipperCruiseListPtr DataBase::SipperCruiseLoadAllCruises ()
Definition at line 7207 of file DataBase.cpp.
References QueryStatement(), ResultSetsClear(), and MLL::SipperCruiseList::SortByCruiseName().
void DataBase::SipperCruiseUpdate (SipperCruisePtr cruise, bool & successful)
Definition at line 7121 of file DataBase.cpp.
References MLL::SipperCruise::CruiseName(), MLL::SipperCruise::DateEnd(), MLL::SipperCruise::DateStart(), MLL::SipperCruise::Description(), KKB::endl(), KKB::RunLog::Level(), MLL::SipperCruise::Location(), MLL::SipperCruise::Objective(), MLL::SipperCruise::Principal(), KKB::KKQueue< Entry >::PushOnBack(), QueryStatement(), KKB::KKStr::QuotedStr(), MLL::SipperCruise::ResearchOrg(), MLL::SipperCruise::ShipName(), KKB::KKStr::Str(), and KKB::DateType::YYYY_MM_DD().
void DataBase::SipperDeploymentDelete (const KKStr & cruiseName, const KKStr & stationName, const KKStr & deploymentNum)
Definition at line 5332 of file DataBase.cpp.
References MLL::SipperFile::CruiseName(), MLL::SipperFile::CtdExt0(), MLL::SipperFile::CtdExt1(), MLL::SipperFile::CtdExt2(), MLL::SipperFile::CtdExt3(), MLL::SipperFile::DateTimeStart(), MLL::SipperFile::DeploymentNum(), MLL::SipperFile::Depth(), MLL::SipperFile::Description(), MLL::SipperFile::ExtractionScanLineEnd(), MLL::SipperFile::ExtractionScanLineStart(), MLL::SipperFile::ExtractionStatus(), MLL::SipperFile::Latitude(), MLL::SipperFile::Longitude(), MLL::Instrument::LookUpByShortName(), MLL::SipperFile::NumScanLines(), KKB::KKQueue< Entry >::PushOnBack(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), MLL::SipperFile::ScanRate(), MLL::SipperFile::SipperFileId(), MLL::SipperFile::SizeInBytes(), MLL::SipperFile::Sp0(), MLL::SipperFile::Sp1(), MLL::SipperFile::Sp2(), MLL::SipperFile::Sp3(), and MLL::SipperFile::StationName().
void DataBase::SipperDeploymentInsert (const SipperDeployment & deployment)
Definition at line 5277 of file DataBase.cpp.
References MLL::SipperDeployment::ChamberWidth(), MLL::SipperDeployment::CropLeft(), MLL::SipperDeployment::CropRight(), MLL::SipperDeployment::CruiseName(), MLL::SipperDeployment::DateTimeEnd(), MLL::SipperDeployment::DateTimeStart(), MLL::SipperDeployment::DeploymentNum(), MLL::SipperDeployment::Description(), MLL::SipperDeployment::Latitude(), MLL::SipperDeployment::Longitude(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), MLL::SipperDeployment::StationName(), KKB::StrFormatDouble(), KKB::StrFormatInt(), MLL::SipperDeployment::SyncTimeStampActual(), MLL::SipperDeployment::SyncTimeStampCTD(), and MLL::SipperDeployment::SyncTimeStampGPS().
Referenced by ImageExtractionManager::ExtractionManager::TerminateProcessing().
SipperDeploymentListPtr DataBase::SipperDeploymentLoad (const KKStr & cruiseName, const KKStr & stationName)
Definition at line 5223 of file DataBase.cpp.
References QueryStatement(), and KKB::KKStr::QuotedStr().
Referenced by ImageExtractionManager::ExtractionManager::TerminateProcessing().
SipperDeploymentPtr DataBase::SipperDeploymentLoad (const KKStr & cruiseName, const KKStr & stationName, const KKStr & deploymentNum)
Definition at line 5239 of file DataBase.cpp.
References KKB::KKQueue< Entry >::PopFromBack(), QueryStatement(), and KKB::KKStr::QuotedStr().
void DataBase::SipperDeploymentUpdate (const SipperDeployment & deployment)
Definition at line 5301 of file DataBase.cpp.
References MLL::SipperDeployment::ChamberWidth(), MLL::SipperDeployment::CropLeft(), MLL::SipperDeployment::CropRight(), MLL::SipperDeployment::CruiseName(), MLL::SipperDeployment::DateTimeEnd(), MLL::SipperDeployment::DateTimeStart(), MLL::SipperDeployment::DeploymentNum(), MLL::SipperDeployment::Description(), MLL::SipperDeployment::Latitude(), MLL::SipperDeployment::Longitude(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), MLL::SipperDeployment::StationName(), KKB::StrFormatDouble(), KKB::StrFormatInt(), MLL::SipperDeployment::SyncTimeStampActual(), MLL::SipperDeployment::SyncTimeStampCTD(), and MLL::SipperDeployment::SyncTimeStampGPS().
VectorKKStr * DataBase::SipperFileGetList (const KKStr & cruiseName, const KKStr & stationName, const KKStr & deploymentNum)
Definition at line 5529 of file DataBase.cpp.
References KKB::KKStr::Empty(), KKB::endl(), KKB::RunLog::Level(), QueryStatement(), and KKB::KKStr::QuotedStr().
Referenced by ImageGetClassStatistics(), ImageGetDepthStatistics(), ImagesQuery(), InstrumentDataGetVolumePerMeterDepth(), and InstrumentDataLoad().
void DataBase::SipperFileInsert (SipperFile & sipperFile)
Definition at line 5639 of file DataBase.cpp.
References KKB::KKStr::Append(), MLL::SipperFile::CruiseName(), MLL::SipperFile::CtdExt0(), MLL::SipperFile::CtdExt1(), MLL::SipperFile::CtdExt2(), MLL::SipperFile::CtdExt3(), MLL::SipperFile::DateTimeStart(), MLL::SipperFile::DeploymentNum(), MLL::SipperFile::Depth(), MLL::SipperFile::Description(), KKB::endl(), MLL::SipperFile::ExtractionScanLineEnd(), MLL::SipperFile::ExtractionScanLineStart(), MLL::SipperFile::ExtractionStatus(), MLL::SipperFile::Latitude(), MLL::SipperFile::Longitude(), MLL::SipperFile::NumScanLines(), QueryStatement(), KKB::KKStr::QuotedStr(), MLL::SipperFile::ScanRate(), MLL::SipperFile::SipperFileId(), MLL::SipperFile::SipperFileName(), MLL::SipperFile::SizeInBytes(), MLL::SipperFile::Sp0ShortName(), MLL::SipperFile::Sp1ShortName(), MLL::SipperFile::Sp2ShortName(), MLL::SipperFile::Sp3ShortName(), MLL::SipperFile::StationName(), and KKB::KKStr::Str().
Referenced by InstrumentDataSaveListForOneSipperFile(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
SipperFileListPtr DataBase::SipperFileLoad (const KKStr & cruiseName, const KKStr & stationName, const KKStr & deploymentNum)
Definition at line 5601 of file DataBase.cpp.
References KKB::KKStr::Empty(), KKB::endl(), QueryStatement(), and KKB::KKStr::QuotedStr().
Referenced by SipperFileLoadOracle().
void DataBase::SipperFileLoadOracle ()
Definition at line 5420 of file DataBase.cpp.
References MLL::SipperFileOracle::AddSipperFileEntries(), KKB::KKQueue< Entry >::Owner(), and SipperFileLoad().
SipperFilePtr DataBase::SipperFileRecLoad (const KKStr & _sipperFileName)
Definition at line 5430 of file DataBase.cpp.
References KKB::osGetRootName(), KKB::KKQueue< Entry >::PopFromBack(), QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
Referenced by FeatureDataGetOneSipperFile(), InstrumentDataLoad(), InstrumentDataLoadAllSipperFiles(), InstrumentDataReFreshSipperFile(), InstrumentDataSaveListForOneSipperFile(), ImageExtractionManager::ExtractionParms::ParseCmdLine(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void DataBase::SipperFilesDelete (const KKStr & _sipperFileName)
Delete a Sipper File and all its related data from all tables in database.
Delete the contents of a single SIPPER file from the database from all tables such as Images, FeatureData, InstrumentData, etc.
Parameters
[in] _sipperFileName Name of SIPPER file to delete.
Definition at line 5805 of file DataBase.cpp.
References MLL::SipperStation::CruiseName(), MLL::SipperStation::DateTimeStart(), MLL::SipperStation::Description(), MLL::SipperStation::Latitude(), MLL::SipperStation::Longitude(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), MLL::SipperStation::StationName(), and KKB::KKStr::Str().
void DataBase::SipperFilesGetCTDDateTime (const KKStr & _sipperFileName, kkint32 & _sipperFileId, kkuint32 & _numScanLines, KKB::DateTime & _CTDDateTimeStart, KKB::DateTime & _CTDDateTimeEnd)
Definition at line 5765 of file DataBase.cpp.
References QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and KKB::KKStr::Str().
void DataBase::SipperFilesUpdateExtractionStatus (const KKStr & sipperFileName, char extractionStatus)
Definition at line 5454 of file DataBase.cpp.
References KKB::osGetRootName(), QueryStatement(), and KKB::KKStr::QuotedStr().
Referenced by ImageExtractionManager::ExtractionManager::ManageTheExtraction(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void DataBase::SipperFilesUpdateExtractionStatusIfExpected (const KKStr & sipperFileName, char extractionStatusExpected, char extractionStatusNew, char & ExtractionStatusBeforeUpdate, char & extractionStatusResult, bool & extrtactionSatusUpdated)
Updates the ExtractionStatus only if the existing extractioStatus is what was expected.
Parameters
[in] sipperFileName
[in] extractionStatusExpected Status of existing SipperFiles table entry; if not existing extractionStatus this value then no update will take place.
[in] extractionStatusNew The new ExtractionStatus the specified SipperFile will take on if current value equal extractionStatusExpected.
[out] ExtractionStatusBeforeUpdate Status found in table entry before update.
[out] extractionStatusResult The new value of ExtractedStatus.
[out] extrtactionSatusUpdated Indicates if the extraction status was updated.
Definition at line 5483 of file DataBase.cpp.
References KKB::osGetRootName(), QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
void DataBase::SipperFileUpdate (SipperFile & sipperFile)
Definition at line 5697 of file DataBase.cpp.
References KKB::KKStr::Append(), MLL::SipperFile::CruiseName(), MLL::SipperFile::CtdExt0(), MLL::SipperFile::CtdExt1(), MLL::SipperFile::CtdExt2(), MLL::SipperFile::CtdExt3(), MLL::SipperFile::DateTimeStart(), MLL::SipperFile::DeploymentNum(), MLL::SipperFile::Depth(), MLL::SipperFile::Description(), KKB::endl(), MLL::SipperFile::ExtractionScanLineEnd(), MLL::SipperFile::ExtractionScanLineStart(), MLL::SipperFile::ExtractionStatus(), MLL::SipperFile::Latitude(), MLL::SipperFile::Longitude(), MLL::SipperFile::NumScanLines(), QueryStatement(), KKB::KKStr::QuotedStr(), MLL::SipperFile::ScanRate(), MLL::SipperFile::SipperFileName(), MLL::SipperFile::SizeInBytes(), MLL::SipperFile::Sp0ShortName(), MLL::SipperFile::Sp1ShortName(), MLL::SipperFile::Sp2ShortName(), MLL::SipperFile::Sp3ShortName(), MLL::SipperFile::StationName(), and KKB::KKStr::Str().
void DataBase::SipperFileUpdateFileSizeStats (const KKStr & _sipperFileName, kkint64 _sizeInBytes, kkuint32 _numScanLines)
Definition at line 5742 of file DataBase.cpp.
References KKB::endl(), QueryStatement(), KKB::KKStr::QuotedStr(), and KKB::KKStr::Str().
Referenced by ImageExtractionManager::ExtractionManager::ManageTheExtraction().
void DataBase::SipperStationDelete (const KKStr & cruiseName, const KKStr & stationName)
Definition at line 5968 of file DataBase.cpp.
References KKB::KKQueue< Entry >::PushOnBack(), QueryStatement(), KKB::KKStr::QuotedStr(), and ResultSetsClear().
void DataBase::SipperStationInsert (const SipperStation & station)
Definition at line 5918 of file DataBase.cpp.
References MLL::SipperStation::CruiseName(), MLL::SipperStation::DateTimeStart(), MLL::SipperStation::Description(), MLL::SipperStation::Latitude(), MLL::SipperStation::Longitude(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and MLL::SipperStation::StationName().
Referenced by ImageExtractionManager::ExtractionManager::TerminateProcessing().
SipperStationListPtr DataBase::SipperStationLoad (const KKStr & cruiseName)
Definition at line 5848 of file DataBase.cpp.
References KKB::KKStr::Empty(), KKB::endl(), QueryStatement(), and KKB::KKStr::QuotedStr().
Referenced by ImageExtractionManager::ExtractionManager::TerminateProcessing().
SipperStationPtr DataBase::SipperStationLoad (const KKStr & cruiseName, const KKStr & stationName)
Definition at line 5867 of file DataBase.cpp.
References KKB::endl(), QueryStatement(), and KKB::KKStr::QuotedStr().
SipperStationListPtr DataBase::SipperStationsLoadByGpsRange (double latitudeMin, double latitudeMax, double longitudeMin, double longitudeMax)
Definition at line 5898 of file DataBase.cpp.
References QueryStatement().
void DataBase::SipperStationUpdate (const SipperStation & station)
Definition at line 5944 of file DataBase.cpp.
References MLL::SipperStation::CruiseName(), MLL::SipperStation::DateTimeStart(), MLL::SipperStation::Description(), MLL::SipperStation::Latitude(), MLL::SipperStation::Longitude(), QueryStatement(), KKB::KKStr::QuotedStr(), ResultSetsClear(), and MLL::SipperStation::StationName().
void DataBase::ThreadEnd () static
Call just before thread terminates.
Definition at line 652 of file DataBase.cpp.
bool DataBase::ThreadInit () static
Call at start of new thread.
Definition at line 630 of file DataBase.cpp.
References ErrorLogMsg().
bool MLL::DataBase::Valid () const inline
Definition at line 126 of file DataBase.h.
Referenced by MLL::PicesApplication::InitalizeApplication(), ImageExtractionManager::ExtractionManager::ManageTheExtraction(), ImageExtractionManager::ExtractionParms::ParseCmdLine(), MLL::PicesApplication::ProcessCmdLineParameter(), ImageExtractionManager::DataBaseUpdateThread::Run(), ServerDescription(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/DataBase.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/DataBase.cpp