Pices: KKB::XmlToken Class Reference
KKB::XmlToken Class Reference abstract
#include <XmlStream.h>
Public Types
enum TokenTypes { TokenTypes::tokNULL, TokenTypes::tokElement, TokenTypes::tokContent }
typedef XmlToken * XmlTokenPtr
Public Member Functions
XmlToken ()
virtual ~XmlToken ()
virtual const KKStr & SectionName () const
If derived class is from the XmlElement family will be the name from the StartTag(XmlTag::Name ()) otherwise KKStr::EmptyStr()
virtual TokenTypes TokenType ()=0
virtual const KKStr & VarName () const
If the derived class is form the 'XmlElement' line will return the 'VarName' from that derived class otherwise it will return back a empty string.
Detailed Description
Definition at line 252 of file XmlStream.h.
Member Typedef Documentation
typedef XmlToken* KKB::XmlToken::XmlTokenPtr
Definition at line 255 of file XmlStream.h.
Member Enumeration Documentation
enum KKB::XmlToken::TokenTypes strong
Enumerator
tokNULL
tokElement
tokContent
Definition at line 256 of file XmlStream.h.
Constructor & Destructor Documentation
XmlToken::XmlToken ()
Definition at line 740 of file XmlStream.cpp.
XmlToken::~XmlToken () virtual
Definition at line 745 of file XmlStream.cpp.
Member Function Documentation
virtual const KKStr& KKB::XmlToken::SectionName () const inline virtual
If derived class is from the XmlElement family will be the name from the StartTag(XmlTag::Name ()) otherwise KKStr::EmptyStr()
Reimplemented in KKB::XmlElement.
Definition at line 265 of file XmlStream.h.
References KKB::KKStr::EmptyStr().
Referenced by KKMLL::ModelKnn::ReadXML(), KKMLL::ModelUsfCasCor::ReadXML(), KKMLL::Attribute::ReadXML(), KKMLL::ModelSvmBase::ReadXML(), SVM233::SvmModel233::ReadXML(), KKMLL::ModelDual::ReadXML(), and KKMLL::ModelOldSVM::ReadXML().
virtual TokenTypes KKB::XmlToken::TokenType () pure virtual
Implemented in KKB::XmlContent, and KKB::XmlElement.
Referenced by GetProcessId(), KKB::VectorKKStr::ReadXML(), KKMLL::ModelParamUsfCasCor::ReadXML(), KKMLL::NormalizationParms::ReadXML(), KKMLL::FeatureEncoder::ReadXML(), KKMLL::TrainingClassList::ReadXML(), KKMLL::BinaryClassParmsList::ReadXML(), SVM233::SvmModel233::ReadXML(), KKMLL::ModelDual::ReadXML(), SVM289_MFS::Svm_Model::ReadXML(), KKMLL::FileDesc::ReadXML(), KKMLL::SVMModel::ReadXML(), KKMLL::TrainingProcess2::ReadXML(), KKB::KKStr::ReadXML(), KKB::KKStrList::ReadXML(), KKB::KKStrListIndexed::ReadXML(), KKMLL::TrainingConfiguration2::ReadXMLBaseToken(), KKMLL::ModelParam::ReadXMLModelParamToken(), KKMLL::Model::ReadXMLModelToken(), and KKB::XmlElementBool::XmlElementBool().
virtual const KKStr& KKB::XmlToken::VarName () const inline virtual
If the derived class is form the 'XmlElement' line will return the 'VarName' from that derived class otherwise it will return back a empty string.
Reimplemented in KKB::XmlElement.
Definition at line 269 of file XmlStream.h.
References KKB::KKStr::EmptyStr().
Referenced by KKMLL::ModelParamKnn::ReadXML(), KKMLL::ModelParamSvmBase::ReadXML(), MLL::PicesTrainingConfiguration::ReadXML(), KKMLL::ModelParamDual::ReadXML(), KKMLL::TrainingClass::ReadXML(), KKMLL::ModelKnn::ReadXML(), KKMLL::ModelUsfCasCor::ReadXML(), KKMLL::ModelSvmBase::ReadXML(), KKMLL::ModelParamOldSVM::ReadXML(), SVM233::SvmModel233::ReadXML(), KKMLL::ModelDual::ReadXML(), SVM289_MFS::Svm_Model::ReadXML(), KKMLL::SVMparam::ReadXML(), KKMLL::ModelOldSVM::ReadXML(), KKMLL::TrainingConfiguration2::ReadXMLBaseToken(), KKMLL::ModelParam::ReadXMLModelParamToken(), and KKMLL::Model::ReadXMLModelToken().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.cpp