Pices: GradeTrainingModel.GetRunTimeParameters Class Reference
GradeTrainingModel.GetRunTimeParameters Class Reference
Public Member Functions
GetRunTimeParameters ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Detailed Description
Definition at line 18 of file GetRunTimeParameters.cs.
Constructor & Destructor Documentation
GradeTrainingModel.GetRunTimeParameters.GetRunTimeParameters () inline
Definition at line 57 of file GetRunTimeParameters.cs.
References PicesInterface::PicesMsgQueue.AddMsg(), PicesInterface::OSservices.AddSlash(), PicesInterface::TrainingModel2.BuildTrainingModel(), PicesInterface::PicesTrainingConfigManaged.CancelLoad(), PicesInterface::PicesFeatureVectorList.CancelLoad(), PicesInterface::TrainingModel2.CancelLoad(), PicesInterface::TrainingModel2.CleanUp(), PicesInterface::PicesDataBase.Close(), PicesInterface::PicesSipperVariables.ConfigurationDirectory(), PicesInterface::PicesTrainingConfigManaged.ExtractClassList(), PicesInterface::PicesTrainingConfigManaged.GetEffectiveConfigFileName(), PicesInterface::PicesDataBase.GetGlobalDatabaseManagerNewInstance(), PicesInterface::TrainingModel2.GetListOfTrainingModels(), PicesInterface::PicesMsgQueue.GetNextMsg(), PicesInterface::PicesClassList.GetUniqueClass(), PicesInterface::TrainingModel2.LoadExistingModelOtherwiseBuild(), PicesInterface::PicesTrainingConfigManaged.LoadFeatureDataFromTrainingLibraries(), PicesInterface::PicesFeatureVectorList.LoadInSubDirectoryTree(), PicesInterface::PicesTrainingConfigManaged.LoadLogStream(), PicesInterface::TrainingModel2.LoadTrainingModelForGivenLevel(), GradeTrainingModel.ConfusionMatrix.MakePrediction(), PicesInterface::PicesPrediction.MLClass, PicesInterface::PicesFeatureVector.MLClass, PicesInterface::PicesTrainingConfigManaged.NumHierarchialLevels(), PicesInterface::PicesTrainingConfigManaged.OtherClass(), PicesInterface::TrainingModel2.PredictClass(), PicesInterface::PicesPrediction.Probability, PicesInterface::PicesTrainingConfigManaged.RootDir(), PicesInterface::PicesTrainingConfigManaged.RootDirExpanded(), GradeTrainingModel.ConfusionMatrix.SetTrainingModel(), PicesInterface::PicesDataBase.SipperFileLoadOracle(), PicesInterface::PicesFeatureVectorList.StratifyAmoungstClasses(), PicesInterface::PicesKKStr.StrToUint(), PicesInterface::PicesTrainingConfigManaged.Valid(), and PicesInterface::TrainingModel2.Valid.
Member Function Documentation
override void GradeTrainingModel.GetRunTimeParameters.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file GetRunTimeParameters.Designer.cs.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/Apps/GradeTrainingModel/GetRunTimeParameters.cs
C:/Users/Kurt/GitHub/Pices/Apps/GradeTrainingModel/GetRunTimeParameters.Designer.cs