Pices: FeatureSelectionApp::ValidationResults Class Reference
FeatureSelectionApp::ValidationResults Class Reference
Where inale Results for a validation run for a single configration are stored.
#include <ValidationResults.h>
Public Types
typedef ValidationResults * ValidationResultsPtr
Public Types inherited from FeatureSelectionApp::Results
typedef Results * ResultsPtr
Public Member Functions
ValidationResults (RunLog &_log)
ValidationResults (FinalResultType _resultType, TrainingConfiguration2Ptr _config, CrossValidationPtr _crossValidation, FeatureVectorListPtr _trainData, const KKStr &_hostName, int _classedCorrectlySize, bool *_classedCorrectly, JobValidationPtr _job, RunLog &_log)
virtual ~ValidationResults ()
const bool * ClassedCorrectly () const
int ClassedCorrectlySize () const
void Write (ostream &o)
Public Member Functions inherited from FeatureSelectionApp::Results
Results (RunLog &_log)
Results (FinalResultType _resultType, TrainingConfiguration2Ptr _config, CrossValidationPtr _crossValidation, FeatureVectorListPtr _trainData, const KKStr &_hostName, BinaryJobPtr _job, RunLog &_log)
virtual ~Results ()
float Accuracy () const
VectorFloat AccuracyByClass () const
float AccuracyNorm () const
const KKStr & ConfigFileName () const
ConfusionMatrix2Ptr ConfusionMatrix () const
KKStr Description () const
const KKStr & HostName () const
int JobId () const
SVM_MachineType MachineType () const
KKStr MachineTypeStr () const
MLClassListPtr MLClasses () const
Creates a List of Classes from associated Confusion Matrix.
double NumFeatures () const
float NumFeaturesWeighted () const
double NumSupportVectors () const
double NumSVs () const
Results & operator+= (const Results &right)
Results & operator/= (float divisor)
Results & operator/= (int divisor)
FinalResultType ResultType () const
KKStr ResultTypeStr () const
SVM_SelectionMethod SelectionMethod () const
KKStr SelectionMethodStr () const
KKStr SvmParameters () const
double TestTime () const
double TotalNumSVs () const
double TrainingTime () const
Static Public Member Functions
static ValidationResultsPtr ConstructFromStream (istream &i, RunLog &log)
Static Public Member Functions inherited from FeatureSelectionApp::Results
static ResultsPtr ConstructFromStream (istream &i, RunLog &log)
Detailed Description
Where inale Results for a validation run for a single configration are stored.
Used to store rsults from a single validation job (JobValidtaion).     *
Will hold both ConfusionMatrix and CrossValiodation Results(such as)   *
TrainingTime, TestTime, Number Support Vectors, etc.                   *
These results will be written to a file by 'JobRandomSplit' as each    *
node is evaluated.                                                     *
                                                                       *
this class was cloned from ValidationResults.  It will be used by     *
FinalResults to track the Validation results for a Training Model.    *
Definition at line 28 of file ValidationResults.h.
Member Typedef Documentation
typedef ValidationResults* FeatureSelectionApp::ValidationResults::ValidationResultsPtr
Definition at line 31 of file ValidationResults.h.
Constructor & Destructor Documentation
ValidationResults::ValidationResults (RunLog & _log)
Definition at line 43 of file ValidationResults.cpp.
Referenced by ConstructFromStream().
ValidationResults::ValidationResults (FinalResultType _resultType, TrainingConfiguration2Ptr _config, CrossValidationPtr _crossValidation, FeatureVectorListPtr _trainData, const KKStr & _hostName, int _classedCorrectlySize, bool * _classedCorrectly, JobValidationPtr _job, RunLog & _log)
Definition at line 51 of file ValidationResults.cpp.
ValidationResults::~ValidationResults () virtual
Definition at line 77 of file ValidationResults.cpp.
Member Function Documentation
const bool* FeatureSelectionApp::ValidationResults::ClassedCorrectly () const inline
Definition at line 54 of file ValidationResults.h.
Referenced by FeatureSelectionApp::FinalResults::ValidationClassedCorrectly().
int FeatureSelectionApp::ValidationResults::ClassedCorrectlySize () const inline
Definition at line 55 of file ValidationResults.h.
Referenced by FeatureSelectionApp::FinalResults::ValidationClassedCorrectlySize().
ValidationResultsPtr ValidationResults::ConstructFromStream (istream & i, RunLog & log) static
Definition at line 154 of file ValidationResults.cpp.
References ValidationResults().
void ValidationResults::Write (ostream & o) virtual
Reimplemented from FeatureSelectionApp::Results.
Definition at line 86 of file ValidationResults.cpp.
References KKB::endl(), and FeatureSelectionApp::Results::Write().
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/Apps/FeatureSelection/ValidationResults.h
C:/Users/kurtk_000/GitHub/Pices/Apps/FeatureSelection/ValidationResults.cpp