Pices: MLL::ImageSizeDistribution Class Reference
MLL::ImageSizeDistribution Class Reference
Used for returning results of call to "ImagesSizeSizeHistogramByDepth".
#include <ImageSizeDistribution.h>
Public Member Functions
ImageSizeDistribution (float _depthBinSize, float _initialValue, float _growtRate, float _endValue, const VectorFloat &_sizeStartValues, const VectorFloat &_sizeEndValues, RunLog &_runLog)
~ImageSizeDistribution ()
void AddData (float _depth, kkuint32 _sizeBucketIdx, kkuint32 _count)
void AddIn (const ImageSizeDistribution &right, RunLog &log)
ImageSizeDistributionRow & AllDepths () const
void DefineRow (float _depth, kkuint32 _imageCount, kkuint32 _totalPixelCount, kkuint32 _totalFilledArea, float _volumneSampled)
float DepthBinSize () const
VectorFloat DepthProfileForSizeBin (kkuint32 _sizeBucketIdx)
float EndValue () const
ImageSizeDistributionRowPtr GetDepthBin (kkuint32 depthBinIdx)
Returns pointer to ImageSizeDistributionRow that is index 'depthBinIdx'.
void GetSizeBucketStats (kkuint32 _sizeBucketIdx, kkuint32 &_count, float &_sizeStart, float &_sizeEnd)
float GrowthRate () const
kkint32 IdentifySizeBucket (float size)
float InitialValue () const
VectorFloat IntegratedDensityDistribution () const
kkuint32 NumDepthBins () const
kkuint32 NumSizeBuckets () const
const VectorFloat & SizeEndValues () const
const VectorFloat & SizeStartValues () const
VectorFloat VolumeSampledByDepthBucket ()
Detailed Description
Used for returning results of call to "ImagesSizeSizeHistogramByDepth".
Definition at line 68 of file ImageSizeDistribution.h.
Constructor & Destructor Documentation
ImageSizeDistribution::ImageSizeDistribution (float _depthBinSize, float _initialValue, float _growtRate, float _endValue, const VectorFloat & _sizeStartValues, const VectorFloat & _sizeEndValues, RunLog & _runLog)
Definition at line 98 of file ImageSizeDistribution.cpp.
References KKB::endl(), and KKB::RunLog::Level().
ImageSizeDistribution::~ImageSizeDistribution ()
Definition at line 128 of file ImageSizeDistribution.cpp.
Member Function Documentation
void ImageSizeDistribution::AddData (float _depth, kkuint32 _sizeBucketIdx, kkuint32 _count)
Definition at line 192 of file ImageSizeDistribution.cpp.
References MLL::ImageSizeDistributionRow::AddData().
Referenced by MLL::DataBase::ImagesSizeDistributionByDepth().
void ImageSizeDistribution::AddIn (const ImageSizeDistribution & right, RunLog & log)
Definition at line 206 of file ImageSizeDistribution.cpp.
References MLL::ImageSizeDistributionRow::AddIn(), KKB::endl(), and KKB::RunLog::Level().
ImageSizeDistributionRow& MLL::ImageSizeDistribution::AllDepths () const inline
Definition at line 94 of file ImageSizeDistribution.h.
References MLL::ImageSizeDistributionRow::AddData(), MLL::ImageSizeDistributionRow::AddIn(), and VectorFloat.
void ImageSizeDistribution::DefineRow (float _depth, kkuint32 _imageCount, kkuint32 _totalPixelCount, kkuint32 _totalFilledArea, float _volumneSampled)
Definition at line 170 of file ImageSizeDistribution.cpp.
References MLL::ImageSizeDistributionRow::AddImageCountPixelCount(), MLL::ImageSizeDistributionRow::ImageCount(), MLL::ImageSizeDistributionRow::TotalFilledArea(), MLL::ImageSizeDistributionRow::TotalPixels(), and MLL::ImageSizeDistributionRow::VolumneSampled().
Referenced by MLL::DataBase::ImagesSizeDistributionByDepth().
float MLL::ImageSizeDistribution::DepthBinSize () const inline
Definition at line 82 of file ImageSizeDistribution.h.
VectorFloat ImageSizeDistribution::DepthProfileForSizeBin (kkuint32 _sizeBucketIdx)
Definition at line 240 of file ImageSizeDistribution.cpp.
References MLL::ImageSizeDistributionRow::Distribution(), NumDepthBins(), and MLL::ImageSizeDistributionRow::VolumneSampled().
float MLL::ImageSizeDistribution::EndValue () const inline
Definition at line 85 of file ImageSizeDistribution.h.
ImageSizeDistributionRowPtr ImageSizeDistribution::GetDepthBin (kkuint32 depthBinIdx)
Returns pointer to ImageSizeDistributionRow that is index 'depthBinIdx'.
Caller will not own the entry; so do not delete it!
Definition at line 145 of file ImageSizeDistribution.cpp.
void ImageSizeDistribution::GetSizeBucketStats (kkuint32 _sizeBucketIdx, kkuint32 & _count, float & _sizeStart, float & _sizeEnd)
Definition at line 276 of file ImageSizeDistribution.cpp.
References MLL::ImageSizeDistributionRow::Distribution().
float MLL::ImageSizeDistribution::GrowthRate () const inline
Definition at line 84 of file ImageSizeDistribution.h.
kkint32 ImageSizeDistribution::IdentifySizeBucket (float size)
Definition at line 302 of file ImageSizeDistribution.cpp.
float MLL::ImageSizeDistribution::InitialValue () const inline
Definition at line 83 of file ImageSizeDistribution.h.
VectorFloat ImageSizeDistribution::IntegratedDensityDistribution () const
Definition at line 330 of file ImageSizeDistribution.cpp.
References MLL::ImageSizeDistributionRow::Distribution(), Min(), and MLL::ImageSizeDistributionRow::VolumneSampled().
kkuint32 MLL::ImageSizeDistribution::NumDepthBins () const inline
Definition at line 87 of file ImageSizeDistribution.h.
Referenced by DepthProfileForSizeBin().
kkuint32 MLL::ImageSizeDistribution::NumSizeBuckets () const inline
Definition at line 86 of file ImageSizeDistribution.h.
const VectorFloat& MLL::ImageSizeDistribution::SizeEndValues () const inline
Definition at line 92 of file ImageSizeDistribution.h.
const VectorFloat& MLL::ImageSizeDistribution::SizeStartValues () const inline
Definition at line 91 of file ImageSizeDistribution.h.
VectorFloat ImageSizeDistribution::VolumeSampledByDepthBucket ()
Definition at line 259 of file ImageSizeDistribution.cpp.
References MLL::ImageSizeDistributionRow::Distribution(), and MLL::ImageSizeDistributionRow::VolumneSampled().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/ImageSizeDistribution.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/ImageSizeDistribution.cpp