Pices: PicesInterface::PicesImageSizeDistributionRow Class Reference
PicesInterface::PicesImageSizeDistributionRow Class Reference
#include <PicesImageSizeDistribution.h>
Public Member Functions
PicesImageSizeDistributionRow (ImageSizeDistributionRowPtr _imageSizeDistributionRow, bool _willOwn)
void AddIn (PicesImageSizeDistributionRow^ right)
array< uint >^ Distribution ()
MLL::ImageSizeDistributionRowPtr UnmanagedClass ()
Protected Member Functions
!PicesImageSizeDistributionRow ()
Properties
float Depth [get]
uint ImageCount [get]
uint TotalFilledArea [get]
uint TotalPixels [get]
float VolumneSampled [get]
Detailed Description
Definition at line 15 of file PicesImageSizeDistribution.h.
Constructor & Destructor Documentation
PicesInterface::PicesImageSizeDistributionRow::PicesImageSizeDistributionRow (ImageSizeDistributionRowPtr _imageSizeDistributionRow, bool _willOwn)
Definition at line 36 of file PicesImageSizeDistribution.cpp.
PicesInterface::PicesImageSizeDistributionRow::!PicesImageSizeDistributionRow () protected
Definition at line 51 of file PicesImageSizeDistribution.cpp.
Member Function Documentation
void PicesInterface::PicesImageSizeDistributionRow::AddIn (PicesImageSizeDistributionRow^ right)
Definition at line 71 of file PicesImageSizeDistribution.cpp.
References UnmanagedClass().
array< uint > PicesInterface::PicesImageSizeDistributionRow::Distribution ()
Definition at line 59 of file PicesImageSizeDistribution.cpp.
References Distribution().
Referenced by Distribution().
MLL::ImageSizeDistributionRowPtr PicesInterface::PicesImageSizeDistributionRow::UnmanagedClass () inline
Definition at line 37 of file PicesImageSizeDistribution.h.
Referenced by AddIn().
Property Documentation
float PicesInterface::PicesImageSizeDistributionRow::Depth get
Definition at line 29 of file PicesImageSizeDistribution.h.
uint PicesInterface::PicesImageSizeDistributionRow::ImageCount get
Definition at line 30 of file PicesImageSizeDistribution.h.
uint PicesInterface::PicesImageSizeDistributionRow::TotalFilledArea get
Definition at line 32 of file PicesImageSizeDistribution.h.
uint PicesInterface::PicesImageSizeDistributionRow::TotalPixels get
Definition at line 31 of file PicesImageSizeDistribution.h.
float PicesInterface::PicesImageSizeDistributionRow::VolumneSampled get
Definition at line 33 of file PicesImageSizeDistribution.h.
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesInterface/PicesImageSizeDistribution.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesInterface/PicesImageSizeDistribution.cpp