Pices: SipperFile.ImageViewer Class Reference
SipperFile.ImageViewer Class Reference
Public Member Functions
ImageViewer (PicesRaster _raster, PicesDataBaseImage _image, PicesClassList _classes)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
PicesClass ClassUserValidatesAs [get]
Detailed Description
Definition at line 16 of file ImageViewer.cs.
Constructor & Destructor Documentation
SipperFile.ImageViewer.ImageViewer (PicesRaster _raster, PicesDataBaseImage _image, PicesClassList _classes) inline
Definition at line 69 of file ImageViewer.cs.
References PicesInterface::TrainingModel2.AddImageToTrainingLibray(), PicesInterface::PicesFeatureVector.AddInstrumentData(), PicesInterface::OSservices.AddSlash(), PicesInterface::PicesFeatureVector.AreaMMSquare, PicesInterface::PicesRaster.BuildBitmap(), PicesInterface::PicesDataBaseImage.ByteOffset, PicesInterface::PicesDataBaseImage.ClassLogEntryId, PicesInterface::PicesDataBase.Close(), PicesInterface::PicesPoint.Col, PicesInterface::PicesPointList.ComputeSegmentLens(), PicesInterface::PicesSipperVariables.ConfigurationDirectory(), PicesInterface::PicesDataBaseImage.ConnectedPixelDist, PicesInterface::PicesDataBaseLogEntry.DateTimeStart, PicesInterface::PicesRaster.DeriveImageLength(), PicesInterface::PicesDataBaseImage.ExtractionLogEntryId, PicesInterface::PicesDataBase.FeatureDataInsertRow(), PicesInterface::PicesDataBase.FeatureDataRecLoad(), PicesInterface::PicesInstrumentData.FieldName(), PicesInterface::PicesInstrumentData.FieldToStr(), PicesInterface::PicesFeatureVector.FilledArea, PicesInterface::PicesInstrumentData.GetFieldNum(), PicesInterface::PicesDataBase.GetGlobalDatabaseManagerNewInstance(), PicesInterface::PicesRaster.GetOrigSipperImage(), PicesInterface::PicesClassList.GetUniqueClass(), PicesInterface::PicesDataBaseImage.Height, PicesInterface::PicesRaster.Height, PicesInterface::PicesDataBaseImage.ImageFileName, PicesInterface::PicesDataBaseImage.ImageSize, PicesInterface::PicesDataBase.ImagesUpdateImageSize(), PicesInterface::PicesDataBase.ImagesUpdateValidatedClass(), PicesInterface::TrainingModel2.IncludesClass(), PicesInterface::PicesDataBase.InstrumentDataGetByScanLine(), PicesInterface::PicesDataBase.LogEntriesSelect(), SipperFile.ActiveTrainingLibraries.MakePredictions(), PicesInterface::TrainingModel2.MLClasses(), PicesInterface::PicesDataBase.MLClassLoadList(), SipperFile.ActiveTrainingLibraries.Model1(), SipperFile.ActiveTrainingLibraries.Model1Name, SipperFile.ActiveTrainingLibraries.Model2(), SipperFile.ActiveTrainingLibraries.Model2Name, PicesInterface::TrainingModel2.ModelName, SipperFile.ActiveTrainingLibraries.ModelsAreAvailable(), PicesInterface::TrainingModel2.ModelType, PicesInterface::PicesClass.Name, PicesInterface::PicesPointList.NotEqual(), PicesInterface::PicesDataBaseImage.PixelCount, PicesInterface::TrainingModel2.RootDir, PicesInterface::PicesPoint.Row, PicesInterface::PicesSipperFile.ScanRate, SipperFile.SelectAPicesClass.SelectedClass, SipperFile.SelectAInstrumentDataField.SelectedDataField, SipperFile.SelectAPicesClass.SelectionMade, PicesInterface::PicesDataBaseImage.SipperFileName, PicesInterface::PicesDataBase.SipperFileRecLoad(), PicesInterface::PicesDataBaseImage.SizeCoordinates, PicesInterface::PicesKKStr.StrToFloat(), PicesInterface::PicesDataBaseImage.TopLeftCol, PicesInterface::PicesDataBaseImage.TopLeftRow, PicesInterface::PicesDataBaseImage.ValidatedClass, PicesInterface::PicesDataBaseImage.ValidatedClassName, PicesInterface::PicesDataBaseImage.Width, and PicesInterface::PicesRaster.Width.
Member Function Documentation
override void SipperFile.ImageViewer.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file ImageViewer.Designer.cs.
Property Documentation
PicesClass SipperFile.ImageViewer.ClassUserValidatesAs get
Definition at line 66 of file ImageViewer.cs.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/SipperFile/ImageViewer.cs
C:/Users/Kurt/GitHub/Pices/PicesLibraries/SipperFile/ImageViewer.Designer.cs