Pices: SVM233::Solver_NU Class Reference
SVM233::Solver_NU Class Reference
Public Member Functions
Solver_NU ()
void Solve (kkint32 l, const Kernel &Q, const double *b, const schar *y, double *alpha, double Cp, double Cn, double eps, SolutionInfo *si, kkint32 shrinking)
Public Member Functions inherited from SVM233::Solver
Solver ()
virtual ~Solver ()
void Solve (kkint32 l, const Kernel &Q, const double *b_, const schar *y_, double *alpha_, double Cp, double Cn, double eps, SolutionInfo *si, kkint32 shrinking)
void Solve (kkint32 l, const Kernel &Q, const double *b_, const schar *y_, double *alpha_, double *C_, double eps, SolutionInfo *si, kkint32 shrinking)
Additional Inherited Members
Protected Types inherited from SVM233::Solver
enum { LOWER_BOUND, UPPER_BOUND, FREE }
Protected Member Functions inherited from SVM233::Solver
double get_C (kkint32 i)
bool is_free (kkint32 i)
bool is_lower_bound (kkint32 i)
bool is_upper_bound (kkint32 i)
void reconstruct_gradient ()
void swap_index (kkint32 i, kkint32 j)
void update_alpha_status (kkint32 i)
Protected Attributes inherited from SVM233::Solver
kkint32 * active_set
kkint32 active_size
double * alpha
char * alpha_status
double * b
double * C
double eps
double * G
double * G_bar
kkint32 l
const Kernel * Q
bool unshrinked
schar * y
Detailed Description
Definition at line 2382 of file svm.cpp.
Constructor & Destructor Documentation
SVM233::Solver_NU::Solver_NU () inline
Definition at line 2385 of file svm.cpp.
Member Function Documentation
void SVM233::Solver_NU::Solve (kkint32 l, const Kernel & Q, const double * b, const schar * y, double * alpha, double Cp, double Cn, double eps, SolutionInfo * si, kkint32 shrinking) inline
Definition at line 2386 of file svm.cpp.
References SVM233::Solver::Solve().
Referenced by SVM233::solve_nu_svc(), and SVM233::solve_nu_svr().
The documentation for this class was generated from the following file:
C:/Users/kurtk_000/GitHub/KSquareLibraries/KKMachineLearning/svm.cpp