Pices: SipperFile.SipperConfigForm Class Reference
SipperFile.SipperConfigForm Class Reference
Summary description for SipperConfigForm.
Public Member Functions
SipperConfigForm (SipperConfigRec _sipperConfigRec)
bool UserSavedDataToFile ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
CheckBox UseDataBase
Detailed Description
Summary description for SipperConfigForm.
Definition at line 19 of file SipperConfigForm.cs.
Constructor & Destructor Documentation
SipperFile.SipperConfigForm.SipperConfigForm (SipperConfigRec _sipperConfigRec) inline
Definition at line 99 of file SipperConfigForm.cs.
Member Function Documentation
override void SipperFile.SipperConfigForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Definition at line 114 of file SipperConfigForm.cs.
References SipperFile.SipperHeaderRec.AirTemp(), SipperFile.SipperHeaderRec.CruiseDateEnd(), SipperFile.SipperHeaderRec.CruiseDateStart(), SipperFile.SipperHeaderRec.CruiseLocation(), SipperFile.SipperHeaderRec.CtdExt0Code(), SipperFile.SipperHeaderRec.CtdExt1Code(), SipperFile.SipperHeaderRec.CtdExt2Code(), SipperFile.SipperHeaderRec.CtdExt3Code(), SipperFile.SipperHeaderRec.DeploymentVehicle(), SipperFile.Instrument.Description(), SipperFile.SipperConfigRec.HeaderRec(), SipperFile.SipperHeaderRec.HeaderStr(), Int32, SipperFile.SipperConfigRec.IpAddress(), SipperFile.SipperConfigRec.IpAddressStr(), SipperFile.SipperConfigRec.IpPort(), SipperFile.SipperHeaderRec.Latitude(), PicesInterface::PicesKKStr.LatitudeToStr(), SipperFile.SipperHeaderRec.Longitude(), PicesInterface::PicesKKStr.LongitudeToStr(), SipperFile.Instrument.LookUpByShortName(), SipperFile.SipperHeaderRec.MaxHeaderLen, SipperFile.SipperHeaderRec.MaxSipperFileNameLen, SipperFile.SipperHeaderRec.Objective(), SipperFile.Instrument.Other(), SipperFile.Instrument.PopulateComboBox(), SipperFile.SipperHeaderRec.Principal(), SipperFile.SipperHeaderRec.ResearchOrg(), SipperFile.SipperConfigRec.Save(), SipperFile.SipperHeaderRec.ScanRate(), SipperFile.SipperHeaderRec.SeaConditions(), SipperFile.SipperHeaderRec.SerialPort(), SipperFile.SipperHeaderRec.SerialPortDesc(), SipperFile.SipperHeaderRec.SerialPortShortName(), SipperFile.SipperHeaderRec.SipperFileName(), PicesInterface::PicesKKStr.StrToInt(), PicesInterface::PicesKKStr.StrToLatitude(), PicesInterface::PicesKKStr.StrToLongitude(), SipperFile.SipperConfigRec.UseDataBase(), SipperFile.SipperHeaderRec.WaveHeight(), and SipperFile.SipperHeaderRec.WeatherConditions().
bool SipperFile.SipperConfigForm.UserSavedDataToFile () inline
Definition at line 96 of file SipperConfigForm.cs.
Referenced by SipperFileViewer.SipperFileViewer.SipperFileViewerRegionAroundImage().
Member Data Documentation
CheckBox SipperFile.SipperConfigForm.UseDataBase protected
Definition at line 90 of file SipperConfigForm.cs.
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/SipperFile/SipperConfigForm.cs