Pices: PicesInterface::PicesKKStr Class Reference
PicesInterface::PicesKKStr Class Reference
#include <PicesKKStr.h>
Public Member Functions
PicesKKStr ()
Static Public Member Functions
static System::String^ KKStrToSystenStr (const KKB::KKStr &s)
static String^ LatitudeToStr (double latitude)
static String^ LongitudeToStr (double longitude)
static bool StrToBool (String^ s)
static System::Byte StrToByte (String^ s)
static char * StrToCharStar (String^ s)
static System::DateTime StrToDateTime (String^ s)
static double StrToDouble (String^ s)
static float StrToFloat (String^ s)
static int StrToInt (String^ s)
static System::Int64 StrToInt64 (String^ s)
static double StrToLatitude (String^ s)
static long StrToLong (String^ s)
static double StrToLongitude (String^ s)
static KKB::uint StrToUint (String^ s)
static System::UInt64 StrToUInt64 (String^ s)
static KKB::KKStrListPtr SystemStringArrayToKKStrListPtr (cli::array< String^ >^list)
static KKB::KKStrListPtr SystemStringListToKKStrListPtr (List< String^ >^list)
static KKB::KKStr SystemStringToKKStr (System::String^ s)
static KKB::KKStrPtr SystemStringToKKStrPtr (System::String^ s)
Detailed Description
Definition at line 14 of file PicesKKStr.h.
Constructor & Destructor Documentation
PicesKKStr::PicesKKStr ()
Definition at line 28 of file PicesKKStr.cpp.
Member Function Documentation
System::String PicesKKStr::KKStrToSystenStr (const KKB::KKStr & s) static
Definition at line 81 of file PicesKKStr.cpp.
References KKB::KKStr::Str().
Referenced by PicesInterface::PicesDataBaseImageGroup::!PicesDataBaseImageGroup(), PicesInterface::PicesDataBaseImageGroupEntry::!PicesDataBaseImageGroupEntry(), PicesInterface::PicesDataBaseLogEntry::!PicesDataBaseLogEntry(), PicesInterface::PicesFeatureVector::!PicesFeatureVector(), PicesInterface::PicesSipperDeployment::!PicesSipperDeployment(), PicesInterface::TrainingModel2::AddImageToTrainingLibray(), PicesInterface::TrainingModel2::DirectoryPathForClass(), PicesInterface::PicesRunLog::DisplayWithNoteBook(), PicesInterface::PicesTrainingClass::ExpandedDirectory(), PicesInterface::PicesFeatureVector::FeatureName(), PicesInterface::PicesRunLog::FileName(), PicesInterface::PicesTrainingConfigManaged::GetEffectiveConfigFileName(), PicesInterface::OSservices::GetFileExtension(), PicesInterface::TrainingModel2::GetListOfTrainingModels(), PicesInterface::OSservices::GetParentDirectoryOfDirPath(), PicesInterface::OSservices::GetPathPartOfFile(), PicesInterface::OSservices::GetRootName(), PicesInterface::OSservices::GetRootNameOfDirectory(), PicesInterface::OSservices::GetRootNameWithExtension(), PicesInterface::PicesClassList::GetUniqueClass(), PicesInterface::PicesRunLog::LastLine(), PicesInterface::TrainingModel2::LastRunLogTextLine(), PicesInterface::PicesFeatureFileIO::LoadFeatureFile(), PicesInterface::OSservices::LookForFile(), PicesInterface::PicesTrainingConfigManaged::ModelName(), PicesInterface::PicesFeatureVector::ParseImageFileName(), PicesInterface::PicesDataBaseServerList::PicesDataBaseServerList(), PicesInterface::PicesFeatureVector::PicesFeatureVector(), PicesInterface::PicesPredictionList::PicesPredictionList(), PicesInterface::TrainingModel2::PredictProbabilities(), PicesInterface::TrainingModel2::ProbabilitiesByClassDual(), PicesInterface::PicesFeatureFileIO::RegisteredDriverNames(), PicesInterface::OSservices::RemoveExtension(), PicesInterface::PicesTrainingConfigManaged::RootDir(), PicesInterface::PicesTrainingConfigManaged::RootDirExpanded(), PicesInterface::PicesRunLog::RunLogFileName(), PicesInterface::TrainingModel2::SaveConfiguration(), PicesInterface::PicesFeatureFileIO::SaveFeatureFile(), PicesInterface::PicesFeatureFileIO::SaveFeatureFileNormalized(), PicesInterface::TrainingModel2::SupportVectorNames(), PicesInterface::PicesDataBaseImage::Thumbnail(), ToKkuDateType(), PicesInterface::TrainingModel2::TrainingModel2(), PicesInterface::PicesTrainingClass::UnManagedClass(), PicesInterface::PicesSipperCruise::ValidateCruiseName(), PicesInterface::PicesFeatureFileIO::ValidDriverName(), PicesInterface::PicesDataBaseImageGroup::ValidName(), PicesInterface::PicesDataBaseServer::~PicesDataBaseServer(), and PicesInterface::PicesRaster::~PicesRaster().
String PicesKKStr::LatitudeToStr (double latitude) static
Definition at line 283 of file PicesKKStr.cpp.
Referenced by SipperFile.DeploymentDialog::DeploymentDialog(), SipperFile.SipperConfigForm::Dispose(), SipperFile.SipperFileDialog::SipperFileDialog(), and SipperFile.StationDialog::StationDialog().
String PicesKKStr::LongitudeToStr (double longitude) static
Definition at line 310 of file PicesKKStr.cpp.
Referenced by SipperFile.DeploymentDialog::DeploymentDialog(), SipperFile.SipperConfigForm::Dispose(), SipperFile.SipperFileDialog::SipperFileDialog(), and SipperFile.StationDialog::StationDialog().
bool PicesKKStr::StrToBool (String^ s) static
Definition at line 195 of file PicesKKStr.cpp.
Referenced by PicesCommander.ChartDistribution::ChartDistribution(), PicesCommander.ChartGPS::ChartGPS(), PicesCommander.ChartHorizontalProfile::ChartHorizontalProfile(), PicesCommander.ChartSizeDistribution::ChartSizeDistribution(), PicesCommander.ClassDepthProfileChart::ClassDepthProfileChart(), PicesCommander.ClassificationStatus::CleanUpMemory(), SipperFile.DepthPlot2::Dispose(), and SipperFile.TimePlot::OnClosing().
byte PicesKKStr::StrToByte (String^ s) static
Definition at line 88 of file PicesKKStr.cpp.
Referenced by SipperDiskUtilities.SipperDateStamp::SipperDateStamp(), and SipperDiskUtilities.SipperTimeStamp::SipperTimeStamp().
char * PicesKKStr::StrToCharStar (String^ s) static
Definition at line 98 of file PicesKKStr.cpp.
System::DateTime PicesKKStr::StrToDateTime (String^ s) static
Definition at line 238 of file PicesKKStr.cpp.
References PicesInterface::OSservices::KKuDateTimeToSystemDateTime().
Referenced by PicesCommander.ChartHorizontalProfile::ChartHorizontalProfile(), PicesCommander.ClassificationStatus::CleanUpMemory(), PicesInterface::ClassificationBiasMatrix::TestPaperResults(), and SipperFile.InstrumentData::WriteLine().
double PicesKKStr::StrToDouble (String^ s) static
Definition at line 227 of file PicesKKStr.cpp.
References StripOutCommas().
Referenced by SipperFile.InstrumentDataReportGPS::ParseTxtLine(), PicesInterface::ClassificationBiasMatrix::TestPaperResults(), and SipperFile.InstrumentData::WriteLine().
float PicesKKStr::StrToFloat (String^ s) static
Definition at line 206 of file PicesKKStr.cpp.
References StripOutCommas().
Referenced by SipperFile.ImageEditor::BuildBitmapFromRasterData(), PicesCommander.ChartAbundanceByDeployment::ChartAbundanceByDeployment(), PicesCommander.ChartAbundancePredictedAndValidated::ChartAbundancePredictedAndValidated(), PicesCommander.ChartDistribution::ChartDistribution(), PicesCommander.ChartGPS::ChartGPS(), PicesCommander.ChartGPSByStation::ChartGPSByStation(), PicesCommander.ChartHorizontalProfile::ChartHorizontalProfile(), PicesCommander.ChartSizeDistribution::ChartSizeDistribution(), PicesCommander.ClassDepthProfileChart::ClassDepthProfileChart(), PicesCommander.ClassificationStatus::CleanUpMemory(), PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets(), SipperFile.DeploymentDialog::DeploymentDialog(), PicesCommander.PicesCommander::GetThumbnailImageAbort(), PicesCommander.Harvester::Harvester(), SipperFile.ImageViewer::ImageViewer(), PicesCommander.InstrumentDataByDeploymentProfile::InstrumentDataByDeploymentProfile(), SipperFile.TimePlot::OnClosing(), SipperFile.InstrumentDataReportBatteryMeter::ParseTxtLine(), SipperFile.InstrumentDataReportInclination::ParseTxtLine(), SipperFile.InstrumentDataReportCTD::ParseTxtLine(), SipperFile.SipperFileDialog::SipperFileDialog(), PicesCommander.PicesCommander::UpdateLastClassesValidated(), and SipperFile.InstrumentData::WriteLine().
int PicesKKStr::StrToInt (String^ s) static
Definition at line 140 of file PicesKKStr.cpp.
References StripOutCommas().
Referenced by SipperFile.ImageEditor::BuildBitmapFromRasterData(), PicesCommander.ChartAbundanceByDeployment::ChartAbundanceByDeployment(), PicesCommander.ChartAbundancePredictedAndValidated::ChartAbundancePredictedAndValidated(), PicesCommander.ChartDistribution::ChartDistribution(), PicesCommander.ChartGPS::ChartGPS(), PicesCommander.ChartGPSByStation::ChartGPSByStation(), PicesCommander.ChartHorizontalProfile::ChartHorizontalProfile(), PicesCommander.ChartSizeDistribution::ChartSizeDistribution(), PicesCommander.ClassDepthProfileChart::ClassDepthProfileChart(), PicesCommander.ClassificationStatus::CleanUpMemory(), PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets(), SipperFile.SipperConfigForm::Dispose(), PicesCommander.PicesCommander::GetThumbnailImageAbort(), PicesCommander.Harvester::Harvester(), PicesCommander.InstrumentDataByDeploymentProfile::InstrumentDataByDeploymentProfile(), SipperFile.TimePlot::OnClosing(), SipperFile.InstrumentDataReportBatteryMeter::ParseTxtLine(), PicesCommander.SaveFeatureData::SaveFeatureData(), PicesCommander.SaveImagesToDisk::SaveImagesToDisk(), PicesCommander.SaveImagesToDisk2::SaveImagesToDisk2(), PicesCommander.SavePlanktonData::SavePlanktonData(), SipperFileViewer.SipperFileViewer::SipperFileViewerRegionAroundImage(), GradeTrainingModel.ConfusionMatrix::TallyPredictions(), PicesCommander.PicesCommander::UpdateLastClassesValidated(), and SipperFile.InstrumentData::WriteLine().
System::Int64 PicesKKStr::StrToInt64 (String^ s) static
Definition at line 176 of file PicesKKStr.cpp.
References StripOutCommas().
double PicesKKStr::StrToLatitude (String^ s) static
Definition at line 151 of file PicesKKStr.cpp.
References KKB::KKStr::ToLatitude().
Referenced by SipperFile.DeploymentDialog::DeploymentDialog(), SipperFile.SipperConfigForm::Dispose(), SipperFile.SipperFileDialog::SipperFileDialog(), and SipperFile.StationDialog::StationDialog().
long PicesKKStr::StrToLong (String^ s) static
Definition at line 166 of file PicesKKStr.cpp.
References StripOutCommas().
double PicesKKStr::StrToLongitude (String^ s) static
Definition at line 158 of file PicesKKStr.cpp.
References KKB::KKStr::ToLongitude().
Referenced by SipperFile.DeploymentDialog::DeploymentDialog(), SipperFile.SipperConfigForm::Dispose(), SipperFile.SipperFileDialog::SipperFileDialog(), and SipperFile.StationDialog::StationDialog().
uint PicesKKStr::StrToUint (String^ s) static
Definition at line 130 of file PicesKKStr.cpp.
References StripOutCommas().
Referenced by GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters(), SipperDiskUtilities.SipperDateStamp::SipperDateStamp(), SipperFile.SipperFileDialog::SipperFileDialog(), GradeTrainingModel.ConfusionMatrix::TallyPredictions(), and SipperFile.InstrumentData::WriteLine().
System::UInt64 PicesKKStr::StrToUInt64 (String^ s) static
Definition at line 185 of file PicesKKStr.cpp.
References StripOutCommas().
Referenced by SipperFile.InstrumentData::WriteLine().
KKB::KKStrListPtr PicesKKStr::SystemStringArrayToKKStrListPtr (cli::array< String^ >^ list) static
Definition at line 60 of file PicesKKStr.cpp.
KKB::KKStrListPtr PicesKKStr::SystemStringListToKKStrListPtr (List< String^ >^ list) static
Definition at line 70 of file PicesKKStr.cpp.
KKStr PicesKKStr::SystemStringToKKStr (System::String^ s) static
Definition at line 34 of file PicesKKStr.cpp.
References KKB::KKStr::Append().
Referenced by PicesInterface::PicesDataBaseImageGroup::!PicesDataBaseImageGroup(), PicesInterface::PicesDataBaseImageGroupEntry::!PicesDataBaseImageGroupEntry(), PicesInterface::PicesDataBaseLogEntry::!PicesDataBaseLogEntry(), PicesInterface::PicesFeatureVector::!PicesFeatureVector(), PicesInterface::PicesSipperDeployment::!PicesSipperDeployment(), PicesInterface::TrainingModel2::AddClass(), PicesInterface::TrainingModel2::AddImageToTrainingLibray(), PicesInterface::PicesRunLog::AttachFile(), PicesInterface::TrainingModel2::AttachMsgQueueToRunLog(), PicesInterface::TrainingModel2::BuildNewTrainedModel(), PicesInterface::TrainingModel2::BuildTrainingModel(), PicesInterface::PicesClass::ChangeNameOfClass(), PicesInterface::PicesClass::CreateAUnManagedClass(), PicesInterface::OSservices::CreateDirectory(), PicesInterface::OSservices::CreateDirectoryPath(), PicesInterface::OSservices::DirectoryExists(), PicesInterface::PicesTrainingClass::ExpandedDirectory(), PicesInterface::PicesTrainingConfigManaged::GetEffectiveConfigFileName(), PicesInterface::OSservices::GetFileExtension(), PicesInterface::PicesRaster::GetOrigSipperImage(), PicesInterface::OSservices::GetParentDirectoryOfDirPath(), PicesInterface::OSservices::GetPathPartOfFile(), PicesInterface::OSservices::GetRootName(), PicesInterface::OSservices::GetRootNameOfDirectory(), PicesInterface::OSservices::GetRootNameWithExtension(), PicesInterface::TrainingModel2::LoadExistingTrainedModel(), PicesInterface::PicesFeatureFileIO::LoadFeatureFile(), PicesInterface::PicesFeatureVectorList::LoadInSubDirectoryTree(), PicesInterface::TrainingModel2::LoadTrainigLibrary(), PicesInterface::TrainingModel2::LoadTrainingModelForGivenLevel(), PicesInterface::OSservices::LookForFile(), PicesInterface::PicesFeatureVector::ParseImageFileName(), PicesInterface::PicesAbundanceCorrectionMatrix::PicesAbundanceCorrectionMatrix(), PicesInterface::PicesClass::PicesClass(), PicesInterface::PicesDataBaseImageGroup::PicesDataBaseImageGroup(), PicesInterface::PicesDataBaseLogEntry::PicesDataBaseLogEntry(), PicesInterface::PicesFeatureFileIO::PicesFeatureFileIO(), PicesInterface::PicesFeatureVector::PicesFeatureVector(), PicesInterface::PicesRaster::PicesRaster(), PicesInterface::PicesRunLog::PicesRunLog(), PicesInterface::PicesSipperDeployment::PicesSipperDeployment(), PicesInterface::PicesTrainingConfigManaged::PicesTrainingConfigManaged(), PicesInterface::TrainingModel2::PredictProbabilities(), PicesInterface::OSservices::RemoveExtension(), PicesInterface::PicesTrainingConfigManaged::Save(), PicesInterface::PicesFeatureVectorList::Save(), PicesInterface::PicesRaster::Save(), PicesInterface::TrainingModel2::SaveConfiguration(), PicesInterface::PicesFeatureFileIO::SaveFeatureFile(), PicesInterface::PicesFeatureFileIO::SaveFeatureFileNormalized(), PicesInterface::PicesAbundanceCorrectionMatrix::SaveForConfigFileName(), ToKkuDateType(), PicesInterface::TrainingModel2::TrainingModel2(), PicesInterface::PicesTrainingClass::UnManagedClass(), PicesInterface::PicesClass::UnmanagedMLClass(), PicesInterface::PicesSipperCruise::ValidateCruiseName(), PicesInterface::PicesFeatureFileIO::ValidDriverName(), PicesInterface::PicesDataBaseImageGroup::ValidName(), PicesInterface::PicesRunLog::Write(), PicesInterface::PicesDataBaseServerList::WriteConfigFile(), PicesInterface::PicesRunLog::Writeln(), PicesInterface::PicesDataBaseServer::~PicesDataBaseServer(), and PicesInterface::PicesRaster::~PicesRaster().
KKStrPtr PicesKKStr::SystemStringToKKStrPtr (System::String^ s) static
Definition at line 46 of file PicesKKStr.cpp.
References KKB::KKStr::Append().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesKKStr.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesKKStr.cpp