Pices: MLL::SizeDistribution Class Reference
MLL::SizeDistribution Class Reference
#include <SizeDistribution.h>
Public Member Functions
SizeDistribution (kkint32 _bucketCount, kkint32 _bucketSize, RunLog &_log)
~SizeDistribution ()
void Increment (MLClassPtr mlClass, kkint32 size)
void PrintByClassCollumns (ostream &o, VectorUlong *scanLinesPerMeter) const
void PrintCSVDistributionMatrix (ostream &_outFile) const
void PrintFormatedDistributionMatrix (ostream &_outFile) const
void PrintTabDelDistributionMatrix (ostream &_outFile) const
Detailed Description
Definition at line 40 of file SizeDistribution.h.
Constructor & Destructor Documentation
SizeDistribution::SizeDistribution (kkint32 _bucketCount, kkint32 _bucketSize, RunLog & _log)
Definition at line 233 of file SizeDistribution.cpp.
References KKB::endl(), and KKB::RunLog::Level().
SizeDistribution::~SizeDistribution ()
Definition at line 253 of file SizeDistribution.cpp.
References KKMLL::MLClassList::PushOnBack(), and KKMLL::MLClassList::SortByName().
Member Function Documentation
void SizeDistribution::Increment (MLClassPtr mlClass, kkint32 size)
Definition at line 278 of file SizeDistribution.cpp.
References KKB::endl(), KKMLL::MLClassList::ExtractThreeTitleLines(), KKB::KKStr::LeftPad(), Min(), PrintByClassCollumns(), PrintCSVDistributionMatrix(), PrintFormatedDistributionMatrix(), and PrintTabDelDistributionMatrix().
Referenced by MLL::SipperExtractionImageManager::AddImage().
void MLL::SizeDistribution::PrintByClassCollumns (ostream & o, VectorUlong * scanLinesPerMeter) const
Referenced by Increment(), and MLL::SipperExtractionImageManager::ReportStatsByDepth().
void MLL::SizeDistribution::PrintCSVDistributionMatrix (ostream & _outFile) const
Referenced by Increment().
void MLL::SizeDistribution::PrintFormatedDistributionMatrix (ostream & _outFile) const
Referenced by Increment(), and MLL::SipperExtractionImageManager::ReportStatistics().
void MLL::SizeDistribution::PrintTabDelDistributionMatrix (ostream & _outFile) const
Referenced by Increment(), and MLL::SipperExtractionImageManager::ReportStatistics().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/SizeDistribution.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/SizeDistribution.cpp