Pices: PicesInterface::PicesSipperFileList Class Reference
PicesInterface::PicesSipperFileList Class Reference
#include <PicesSipperFile.h>
Public Types
typedef MLL::SipperFileListPtr SipperFileListPtr
Public Member Functions
PicesSipperFileList ()
PicesSipperFileList (SipperFileListPtr _sipperFileList)
Static Public Member Functions
static PicesSipperFileList^ GetListOfSipperFilesWeCanFind (PicesRunLog^ runLog)
Summary>Returns the earliest CTD DateTime in the list that is greater than 1999
Protected Member Functions
!PicesSipperFileList ()
Properties
System::DateTime DateTimeStart [get]
Detailed Description
Definition at line 82 of file PicesSipperFile.h.
Member Typedef Documentation
typedef MLL::SipperFileListPtr PicesInterface::PicesSipperFileList::SipperFileListPtr
Definition at line 85 of file PicesSipperFile.h.
Constructor & Destructor Documentation
PicesInterface::PicesSipperFileList::PicesSipperFileList ()
Definition at line 150 of file PicesSipperFile.cpp.
PicesInterface::PicesSipperFileList::PicesSipperFileList (SipperFileListPtr _sipperFileList)
Definition at line 161 of file PicesSipperFile.cpp.
References KKB::KKQueue< Entry >::Owner().
PicesInterface::PicesSipperFileList::!PicesSipperFileList () protected
Definition at line 183 of file PicesSipperFile.cpp.
Member Function Documentation
PicesSipperFileList PicesInterface::PicesSipperFileList::GetListOfSipperFilesWeCanFind (PicesRunLog^ runLog) static
Summary>Returns the earliest CTD DateTime in the list that is greater than 1999
Definition at line 189 of file PicesSipperFile.cpp.
References PicesInterface::PicesSipperFile::DateTimeStart, PicesInterface::PicesRunLog::Log(), and KKB::KKQueue< Entry >::Owner().
Property Documentation
System:: DateTime PicesInterface::PicesSipperFileList::DateTimeStart get
Definition at line 105 of file PicesSipperFile.h.
Referenced by PicesCommander.ChartHorizontalProfile::ChartHorizontalProfile().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesSipperFile.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesSipperFile.cpp