Pices: PicesCommander.AssignSelectedImagesToGroup Class Reference
PicesCommander.AssignSelectedImagesToGroup Class Reference
Public Member Functions
AssignSelectedImagesToGroup (PicesDataBaseImageList _selImages, String _suggestedGroupName)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
bool NewGroupCreated [get]
String NewGroupName [get]
Detailed Description
Definition at line 15 of file AssignSelectedImagesToGroup.cs.
Constructor & Destructor Documentation
PicesCommander.AssignSelectedImagesToGroup.AssignSelectedImagesToGroup (PicesDataBaseImageList _selImages, String _suggestedGroupName) inline
Definition at line 29 of file AssignSelectedImagesToGroup.cs.
References PicesInterface::PicesDataBase.GetGlobalDatabaseManagerNewInstance(), PicesInterface::PicesDataBase.ImageGroupEntriesInsert(), PicesInterface::PicesDataBaseImageGroup.ImageGroupId, PicesInterface::PicesDataBase.ImageGroupInsert(), PicesInterface::PicesDataBase.ImageGroupLoad(), PicesInterface::PicesDataBase.LastErrorDesc(), PicesInterface::PicesDataBase.Valid(), and PicesInterface::PicesDataBaseImageGroup.ValidName().
Member Function Documentation
override void PicesCommander.AssignSelectedImagesToGroup.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file AssignSelectedImagesToGroup.Designer.cs.
Property Documentation
bool PicesCommander.AssignSelectedImagesToGroup.NewGroupCreated get
Definition at line 24 of file AssignSelectedImagesToGroup.cs.
String PicesCommander.AssignSelectedImagesToGroup.NewGroupName get
Definition at line 26 of file AssignSelectedImagesToGroup.cs.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/AssignSelectedImagesToGroup.cs
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/AssignSelectedImagesToGroup.Designer.cs