Pices: SipperFileViewer.SipperFileViewer Class Reference
SipperFileViewer.SipperFileViewer Class Reference
Public Member Functions
SipperFileViewer ()
SipperFileViewer (string fileName)
SipperFileViewer (Stream stream, string _windowTitle, string _sipperFileName)
void CancelLoadingModels ()
static int SendMessage (IntPtr hwnd, [MarshalAs(UnmanagedType.U4)] int Msg, int wParam, [MarshalAs(System.Runtime.InteropServices.UnmanagedType.LPStr)] string lParam)
Static Public Member Functions
static void SipperFileViewerRegionAroundImage (PicesDataBaseImage image, PicesRunLog runLog)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void WndProc (ref Message m)
Properties
int BlobMinSize [get, set]
Detailed Description
Definition at line 22 of file SipperFileViewer.cs.
Constructor & Destructor Documentation
SipperFileViewer.SipperFileViewer.SipperFileViewer () inline
Definition at line 102 of file SipperFileViewer.cs.
SipperFileViewer.SipperFileViewer.SipperFileViewer (string fileName) inline
Definition at line 111 of file SipperFileViewer.cs.
SipperFileViewer.SipperFileViewer.SipperFileViewer (Stream stream, string _windowTitle, string _sipperFileName) inline
Definition at line 121 of file SipperFileViewer.cs.
Member Function Documentation
void SipperFileViewer.SipperFileViewer.CancelLoadingModels () inline
Definition at line 1625 of file SipperFileViewer.cs.
References SipperFile.ActiveTrainingLibraries.CancelLoads(), SipperFileViewer.SipperFileViewerParameters.Colorize, PicesInterface::PicesSipperFile.ExtractionScanLineEnd, PicesInterface::PicesSipperFile.ExtractionScanLineStart, SipperFile.InstrumentData.GetFieldNameIndex(), SipperFile.SipperFileBuffered.LargestKnownScanLine(), SipperFileViewer.SipperFileViewerParameters.PaintWholePanel(), SipperFileViewer.SipperFileViewerParameters.Ratio(), SipperFileViewer.SelectAInstrumentDataField.SelectedDataField, PicesInterface::PicesDataBase.SelectNewDataBaseServer(), SipperFileViewer.SipperFileViewerParameters.SetDataBase(), and SipperFile.SipperConfigRec.UseDataBase().
override void SipperFileViewer.SipperFileViewer.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file SipperFileViewer.Designer.cs.
static int SipperFileViewer.SipperFileViewer.SendMessage (IntPtr hwnd, [MarshalAs(UnmanagedType.U4)] int Msg, int wParam, [MarshalAs(System.Runtime.InteropServices.UnmanagedType.LPStr)] string lParam)
static void SipperFileViewer.SipperFileViewer.SipperFileViewerRegionAroundImage (PicesDataBaseImage image, PicesRunLog runLog) inline static
Definition at line 135 of file SipperFileViewer.cs.
References SipperFile.InstrumentDataReportText.AllMessages(), SipperFile.InstrumentDataManager.AssignReporter(), PicesInterface::PicesDataBase.Close(), SipperFileViewer.SipperFileViewerParameters.ColHistogram(), SipperFileViewer.SipperFileViewerParameters.ComputeParameters(), SipperFileViewer.SipperFileViewerParameters.CropColemnLeft(), SipperFileViewer.SipperFileViewerParameters.CropColemnRight(), PicesInterface::PicesSipperFile.CtdExt0, SipperFile.SipperHeaderRec.CtdExt0Code(), PicesInterface::PicesSipperFile.CtdExt1, SipperFile.SipperHeaderRec.CtdExt1Code(), PicesInterface::PicesSipperFile.CtdExt2, SipperFile.SipperHeaderRec.CtdExt2Code(), PicesInterface::PicesSipperFile.CtdExt3, SipperFile.SipperHeaderRec.CtdExt3Code(), SipperFile.InstrumentData.Data(), SipperFileViewer.SipperFileViewerParameters.DisplayRowBot(), SipperFileViewer.SipperFileViewerParameters.DisplayRowsToDisplay(), SipperFileViewer.SipperFileViewerParameters.DisplayRowTop(), SipperFile.ImageEditor.Dispose(), SipperFile.TimePlot.Dispose(), SipperFile.InstrumentDataReport.Dispose(), SipperFile.InstrumentDataLogger.Dispose(), SipperFile.InstrumentDataManager.Dispose(), SipperFile.SipperFileBuffered.Dispose(), SipperFile.DepthPlot2.Dispose(), SipperFile.InstrumentDataList.Dispose(), SipperFile.SipperFileBuffered.EofReached, SipperFileViewer.SipperFileViewerParameters.ExtractBlobs(), PicesInterface::PicesSipperFile.ExtractionScanLineEnd, PicesInterface::PicesSipperFile.ExtractionScanLineStart, SipperFile.InstrumentData.FieldName(), SipperFile.SipperFileBuffered.FrameBytesOffsetsUpdateThreadStart(), SipperFile.InstrumentData.GetField(), SipperFile.InstrumentData.GetFieldNameIndex(), PicesInterface::PicesDataBase.GetGlobalDatabaseManagerNewInstance(), PicesInterface::OSservices.GetRootName(), SipperFile.SipperConfigRec.HeaderRec(), PicesInterface::PicesDataBase.InstrumentDataGetByScanLine(), SipperFile.SipperFileBuffered.LargestKnowmFrameNum(), SipperFile.SipperFileBuffered.LargestKnownScanLine(), SipperFile.InstrumentData.NumDataFields(), SipperFileViewer.SipperFileViewerParameters.PaintFromBuffer(), SipperFileViewer.SipperFileViewerParameters.PaintTemporayRectangle(), SipperFileViewer.SipperFileViewerParameters.PaintWholePanel(), SipperFile.SipperFileBuffered.Ratio(), SipperFileViewer.SipperFileViewerParameters.Ratio(), SipperFile.SipperBaseFile.ScanLinesPerFrame, PicesInterface::PicesSipperFile.ScanRate, SipperFileViewer.SipperFileViewerParameters.ScrollRows2(), PicesInterface::PicesDataBase.SelectNewDataBaseServer(), SipperFile.SipperHeaderRec.SerialPortShortName(), PicesInterface::PicesDataBase.ServerDescription(), SipperFileViewer.SipperFileViewerParameters.SetCropColumnLeft(), SipperFileViewer.SipperFileViewerParameters.SetCropColumnRight(), SipperFileViewer.SipperFileViewerParameters.SetNewDisplayRowTop(), SipperFileViewer.SipperFileViewerParameters.SetSipperFile(), PicesInterface::PicesDataBase.SipperFileGetFullPath(), PicesInterface::PicesDataBaseImage.SipperFileName, PicesInterface::PicesDataBase.SipperFileRecLoad(), PicesInterface::PicesSipperVariables.SipperFilesDirectory(), PicesInterface::PicesSipperFile.Sp0, PicesInterface::PicesSipperFile.Sp1, PicesInterface::PicesSipperFile.Sp2, PicesInterface::PicesSipperFile.Sp3, PicesInterface::PicesKKStr.StrToInt(), PicesInterface::PicesDataBaseImage.TopLeftRow, SipperFile.SipperConfigRec.UseDataBase(), SipperFile.SipperConfigForm.UserSavedDataToFile(), and PicesInterface::PicesDataBase.Valid().
Referenced by PicesCommander.PicesCommander.UpdateLastClassesValidated().
override void SipperFileViewer.SipperFileViewer.WndProc (ref Message m) inline protected
Definition at line 1208 of file SipperFileViewer.cs.
References SipperFileViewer.SipperFileViewerParameters.AddUserSpecifiedBlob(), PicesInterface::PicesDataBase.Close(), SipperFileViewer.SipperFileViewerParameters.DisplayRowsToDisplay(), SipperFileViewer.SipperFileViewerParameters.DisplayRowTop(), SipperFileViewer.SipperFileViewerParameters.Dispose(), SipperFileViewer.SipperFileViewerParameters.ExtractBlobs(), SipperFileViewer.SipperFileViewerParameters.ExtractImageFromSipper(), SipperFile.InstrumentData.FieldName(), SipperFile.SipperFileBuffered.FrameBytesOffsetsUpdateThreadTerminate(), SipperFile.InstrumentData.GetFieldNameIndex(), PicesInterface::OSservices.GetRootName(), SipperFile.ActiveTrainingLibraries.ModelsAreLoading(), SipperFileViewer.SipperFileViewerParameters.PaintAllBlobs(), SipperFileViewer.AutoDetectionParamters.RebuildTrainingLibrary1, SipperFileViewer.AutoDetectionParamters.RebuildTrainingLibrary2, SipperFile.InstrumentDataList.Save(), SipperFileViewer.SipperFileViewerParameters.SelectedBlob(), and SipperFileViewer.SelectAInstrumentDataField.SelectedDataField.
Property Documentation
int SipperFileViewer.SipperFileViewer.BlobMinSize get set
Definition at line 87 of file SipperFileViewer.cs.
Referenced by SipperFileViewer.AutoDetectionParamters.AutoDetectionParamters().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/Apps/SipperFileViewer/SipperFileViewer.cs
C:/Users/Kurt/GitHub/Pices/Apps/SipperFileViewer/SipperFileViewer.Designer.cs