Pices: KKB::KK_DFT1D< DftType > Class Template Reference
KKB::KK_DFT1D< DftType > Class Template Reference
#include <kku_fftw.h>
Public Types
typedef std::complex< DftType > DftComplexType
Public Member Functions
KK_DFT1D (kkint32 _size, bool _forwardTransform)
~KK_DFT1D ()
DftComplexType ** FourierMask ()
void Transform (DftComplexType *src, DftComplexType *dest)
void Transform (KKB::uchar *src, DftComplexType *dest)
void TransformNR (DftComplexType *src)
Detailed Description
template<typename DftType>
class KKB::KK_DFT1D< DftType >
Definition at line 127 of file kku_fftw.h.
Member Typedef Documentation
template<typename DftType> typedef std::complex<DftType> KKB::KK_DFT1D< DftType >::DftComplexType
Definition at line 130 of file kku_fftw.h.
Constructor & Destructor Documentation
template<typename DftType > KKB::KK_DFT1D< DftType >::KK_DFT1D (kkint32 _size, bool _forwardTransform)
Definition at line 230 of file kku_fftw.h.
template<typename DftType > KKB::KK_DFT1D< DftType >::~KK_DFT1D ()
Definition at line 248 of file kku_fftw.h.
Member Function Documentation
template<typename DftType> DftComplexType** KKB::KK_DFT1D< DftType >::FourierMask () inline
Definition at line 150 of file kku_fftw.h.
template<typename DftType > void KKB::KK_DFT1D< DftType >::Transform (DftComplexType * src, DftComplexType * dest)
Definition at line 298 of file kku_fftw.h.
Referenced by KKB::ContourFollower::CreateFourierDescriptorBySampling(), KKB::ContourFollower::CreateFourierFromPointList(), KKB::ContourFollower::CreatePointListFromFourier(), KKB::ContourFollower::FollowContour(), KKB::Raster::FollowContour(), and KKB::ContourFollower::FollowContour2().
template<typename DftType > void KKB::KK_DFT1D< DftType >::Transform (KKB::uchar * src, DftComplexType * dest)
Definition at line 382 of file kku_fftw.h.
template<typename DftType > void KKB::KK_DFT1D< DftType >::TransformNR (DftComplexType * src)
Definition at line 428 of file kku_fftw.h.
References KKB::Swap(), and TwoPie.
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/kku_fftw.h