Pices: PicesInterface::PicesClass Class Reference
PicesInterface::PicesClass Class Reference
Represents a single 'Class' in the machine learning world.
#include <PicesClass.h>
Public Member Functions
PicesClass (String^ _name, PicesClass^ _parent)
PicesClass (String^ _name, String^ _parentName)
void AddAChild (PicesClass^ child)
List< PicesClass^ >^ BuildListOfDecendents ()
bool ChangeNameOfClass (String^ newName)
Will only change the name if no other instance of 'MLClass' is using the new name.
void CreateAUnManagedClass ()
void DeleteFromDisk (String^ directory)
bool IsEqual (PicesClass^ c)
bool IsInMySubTree (PicesClass^ candidate)
summary>Determines the number of generations between this class and the candidate class.
PicesClass^ MLClassForGivenHierarchialLevel (uint level)
int NumGenerations (PicesClass^ candidate)
int NumOfChildren ()
bool ParentLoopCheck (PicesClass^ startingClass)
void RemoveAChild (PicesClass^ child)
void Save (String^ directory)
PicesClass^ SearchFamilyTree (String^ _nameUpper, PicesClass^ _nodeSearchingFrom)
summary>Returns a pointer to the unmanaged version of this Class.
PicesClass^ SearchTree (String^ _nameUpper)
MLClassPtr UnmanagedMLClass ()
Static Public Member Functions
static void ChangeNameOfClass (PicesClass^ mlClass, String^ newName, bool% changeSuccessful)
static String^ GetClassNameFromDirName (String^ subDir)
summary>Will change the name of an existing class verifying that a duplicate does not get created; will also make sure that the new name is not in use by another class
Properties
List< PicesClass^ >^ Children [get]
int ClassId [get]
String^ Description [get, set]
bool Mandatory [get, set]
String^ Name [get]
String^ NameUpper [get]
bool NoiseClass [get]
kkuint16 NumHierarchialLevels [get]
PicesClass^ Parent [get, set]
String^ ParentName [get]
bool StoredOnDataBase [get, set]
bool Summarize [get, set]
bool UnDefined [get]
Inidicates that class undefined or Noise.
Detailed Description
Represents a single 'Class' in the machine learning world.
remarks> Machine Learning Class. Keep in mind that when we use the word 'class' in these comments we are referring the Machine Learning concept of 'class' and not the c++, java, or c# idea. The idea is that for any image or example(more general) a class can be assigned to them. This class is to indicate a grouping which will allow us to group like images/examples together.
PicesClass is the Managed Version of the unmanaged class 'MLL::MLClass'. For every instance of this class there will be a matching instance of a 'MLClass' object. Also just like 'MLClass' there can only be one instance of a class with the same name. This helps simplify other programming because we can compare pointers or handles directly to know if we are talking about the same class. To accomplish this, the creation of new Classes is done through a static method in the PicesClassList object called PicesClassList::GetUniqueClass.
Definition at line 41 of file PicesClass.h.
Constructor & Destructor Documentation
PicesInterface::PicesClass::PicesClass (String^ _name, PicesClass^ _parent)
Definition at line 71 of file PicesClass.cpp.
References KKMLL::MLClass::Parent(), PicesInterface::PicesKKStr::SystemStringToKKStr(), KKMLL::MLClass::UnDefined(), and UnmanagedMLClass().
PicesInterface::PicesClass::PicesClass (String^ _name, String^ _parentName)
Definition at line 95 of file PicesClass.cpp.
References PicesInterface::PicesClassList::GetUniqueClass(), KKMLL::MLClass::Parent(), PicesInterface::PicesKKStr::SystemStringToKKStr(), KKMLL::MLClass::UnDefined(), and UnmanagedMLClass().
Member Function Documentation
void PicesInterface::PicesClass::AddAChild (PicesClass^ child)
Definition at line 295 of file PicesClass.cpp.
References Name, and Parent.
Referenced by CreateAUnManagedClass(), PicesInterface::PicesClassList::CreateFromDirectoryStructure(), and PicesInterface::PicesDataBase::MLClassLoadList().
List< PicesClass^ > PicesInterface::PicesClass::BuildListOfDecendents ()
Definition at line 326 of file PicesClass.cpp.
References BuildListOfDecendents().
Referenced by BuildListOfDecendents().
bool PicesInterface::PicesClass::ChangeNameOfClass (String^ newName)
Will only change the name if no other instance of 'MLClass' is using the new name.
Definition at line 183 of file PicesClass.cpp.
References Name, and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by PicesCommander.ClassMaintenance::ClassMaintenance().
void PicesInterface::PicesClass::ChangeNameOfClass (PicesClass^ mlClass, String^ newName, bool% changeSuccessful) static
Definition at line 50 of file PicesClass.cpp.
References UnmanagedMLClass().
void PicesInterface::PicesClass::CreateAUnManagedClass ()
Definition at line 211 of file PicesClass.cpp.
References AddAChild(), KKMLL::MLClass::Description(), KKMLL::MLClass::Parent(), RemoveAChild(), KKMLL::MLClass::StoredOnDataBase(), PicesInterface::PicesKKStr::SystemStringToKKStr(), and UnmanagedMLClass().
void PicesInterface::PicesClass::DeleteFromDisk (String^ directory)
Definition at line 528 of file PicesClass.cpp.
References PicesInterface::OSservices::AddSlash().
String PicesInterface::PicesClass::GetClassNameFromDirName (String^ subDir) static
summary>Will change the name of an existing class verifying that a duplicate does not get created; will also make sure that the new name is not in use by another class
param name='mlClass'> Pointer to existing MLClass instance that you wish to rename.
param name='newName'> New name that you with to give instance of 'MLClass'
param name='changeSuccessful'> Will return'True' if change was successful, only reason it would not work is the name is already used.
Definition at line 41 of file PicesClass.cpp.
Referenced by PicesCommander.ImportValidatdClass::ImportValidatdClass().
bool PicesInterface::PicesClass::IsEqual (PicesClass^ c)
Definition at line 275 of file PicesClass.cpp.
bool PicesInterface::PicesClass::IsInMySubTree (PicesClass^ candidate)
summary>Determines the number of generations between this class and the candidate class.
remarks> We search all our children to determine if Candidate is one our descendent's. If it is not we return -1 otherwise we return the number of generations below us. Our immediate children will be considered 1 generation apart. /remarks> param name='candidate'>Candidate Class that we are searching for amongst out children.
returns> The number of generations between us and the candidate or -1 if not one of our descendent's.
Definition at line 444 of file PicesClass.cpp.
References IsInMySubTree().
Referenced by PicesCommander.ChartDistribution::ChartDistribution(), PicesCommander.ChartHorizontalProfile::ChartHorizontalProfile(), PicesCommander.ClassDepthProfileChart::ClassDepthProfileChart(), PicesCommander.ClassMaintenance::ClassMaintenance(), and IsInMySubTree().
PicesClass PicesInterface::PicesClass::MLClassForGivenHierarchialLevel (uint level)
Definition at line 544 of file PicesClass.cpp.
References PicesInterface::PicesClassList::GetUniqueClass().
Referenced by PicesInterface::PicesClassList::ExtractListOfClassesForAGivenHierarchialLevel(), PicesInterface::PicesClassStatisticList::Summarize(), and GradeTrainingModel.ConfusionMatrix::TallyPredictions().
int PicesInterface::PicesClass::NumGenerations (PicesClass^ candidate)
Definition at line 472 of file PicesClass.cpp.
References NumGenerations().
Referenced by PicesCommander.ClassificationStatus::CleanUpMemory(), NumGenerations(), and PicesCommander.ClassifierProcess::StartThread().
int PicesInterface::PicesClass::NumOfChildren ()
Definition at line 285 of file PicesClass.cpp.
bool PicesInterface::PicesClass::ParentLoopCheck (PicesClass^ startingClass)
Definition at line 373 of file PicesClass.cpp.
References ParentLoopCheck().
Referenced by ParentLoopCheck(), and SipperFile.SelectAPicesClass::SelectAPicesClass().
void PicesInterface::PicesClass::RemoveAChild (PicesClass^ child)
Definition at line 350 of file PicesClass.cpp.
Referenced by CreateAUnManagedClass().
void PicesInterface::PicesClass::Save (String^ directory)
Definition at line 492 of file PicesClass.cpp.
References PicesInterface::OSservices::AddSlash(), and Name.
Referenced by PicesInterface::PicesClassList::CreateFromDirectoryStructure().
PicesClass PicesInterface::PicesClass::SearchFamilyTree (String^ _nameUpper, PicesClass^ _nodeSearchingFrom)
summary>Returns a pointer to the unmanaged version of this Class.
Definition at line 413 of file PicesClass.cpp.
References SearchFamilyTree().
Referenced by SearchFamilyTree().
PicesClass PicesInterface::PicesClass::SearchTree (String^ _nameUpper)
Definition at line 391 of file PicesClass.cpp.
References SearchTree().
Referenced by SearchTree().
MLClassPtr PicesInterface::PicesClass::UnmanagedMLClass ()
Definition at line 120 of file PicesClass.cpp.
References KKMLL::MLClass::ClassId(), KKMLL::MLClass::Description(), KKMLL::MLClass::Mandatory(), Name, KKMLL::MLClass::NumHierarchialLevels(), KKMLL::MLClass::Summarize(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by PicesInterface::PicesFeatureVector::!PicesFeatureVector(), PicesInterface::TrainingModel2::AddClass(), PicesInterface::TrainingModel2::AddImageToTrainingLibray(), ChangeNameOfClass(), CreateAUnManagedClass(), PicesInterface::TrainingModel2::DirectoryPathForClass(), PicesInterface::PicesDataBase::FeatureDataForImageGroup(), PicesInterface::PicesDataBase::FeatureDataGetOneSipperFile(), PicesInterface::TrainingModel2::FindWorstSupportVectors(), PicesInterface::TrainingModel2::FindWorstSupportVectors2(), PicesInterface::PicesClassList::GetUniqueClass(), PicesInterface::PicesDataBase::ImageGetClassStatistics(), PicesInterface::PicesDataBase::ImageGetDepthStatistics(), PicesInterface::PicesDataBase::ImageInsert(), PicesInterface::PicesDataBase::ImagesQuery(), PicesInterface::PicesDataBase::ImagesQueryByGrouop(), PicesInterface::PicesDataBase::ImagesQueryDeploymentSizeRange(), PicesInterface::PicesDataBase::ImagesUpdatePredictions(), PicesInterface::PicesDataBase::ImagesUpdateValidatedAndPredictClass(), PicesInterface::PicesDataBase::ImagesUpdateValidatedClass(), PicesInterface::TrainingModel2::IncludesClass(), PicesInterface::PicesClassList::LookUpByUnmanagedClass(), PicesInterface::PicesDataBase::MLClassInsert(), PicesInterface::PicesDataBase::MLClassInsertReturn(), PicesInterface::PicesDataBase::MLClassUpdate(), PicesInterface::PicesAbundanceCorrectionMatrix::PicesAbundanceCorrectionMatrix(), PicesClass(), PicesInterface::PicesFeatureVector::PicesFeatureVector(), PicesInterface::PicesAbundanceCorrectionMatrix::Prediction(), PicesInterface::TrainingModel2::SupportVectorNames(), PicesInterface::PicesDataBaseImage::Thumbnail(), PicesInterface::PicesClassList::ToMLClassConstList(), PicesInterface::PicesClassStatisticList::ToUnmanagedClassStatisticList(), and PicesInterface::PicesTrainingClass::UnManagedClass().
Property Documentation
List< PicesClass^>^ PicesInterface::PicesClass::Children get
Definition at line 56 of file PicesClass.h.
Referenced by PicesCommander.ChartAbundanceByDeployment::ChartAbundanceByDeployment(), PicesCommander.ChartAbundancePredictedAndValidated::ChartAbundancePredictedAndValidated(), PicesCommander.ChartDistribution::ChartDistribution(), PicesCommander.ChartHorizontalProfile::ChartHorizontalProfile(), PicesCommander.ChartSizeDistribution::ChartSizeDistribution(), PicesCommander.ClassDepthProfileChart::ClassDepthProfileChart(), PicesCommander.ClassMaintenance::ClassMaintenance(), PicesInterface::PicesClassList::CreateFromDirectoryStructure(), PicesCommander.SizeDistribution2::ExtractFamilyOfClasses(), SipperFile.SelectAPicesClass::SelectAPicesClass(), PicesCommander.SizeDistribution2::SummarizeFamilyOfClasses(), PicesCommander.SizeDistribution::SumUpFamilyOfClasses(), and PicesCommander.SizeDistribution::SumUpFamilyOfClassesForBucket().
int PicesInterface::PicesClass::ClassId get
Definition at line 47 of file PicesClass.h.
Referenced by PicesCommander.ClassMaintenance::ClassMaintenance(), PicesCommander.ClassificationStatus::CleanUpMemory(), and PicesCommander.ClassifierProcess::StartThread().
String^ PicesInterface::PicesClass::Description get set
Definition at line 48 of file PicesClass.h.
Referenced by PicesCommander.ClassMaintenance::ClassMaintenance(), PicesCommander.ClassificationStatus::CleanUpMemory(), PicesInterface::PicesClassList::CreateFromDirectoryStructure(), PicesInterface::PicesDataBase::MLClassLoad(), and PicesCommander.ClassifierProcess::StartThread().
bool PicesInterface::PicesClass::Mandatory get set
Definition at line 49 of file PicesClass.h.
Referenced by PicesCommander.ClassMaintenance::ClassMaintenance(), PicesInterface::PicesClassList::ExtractMandatoryClasses(), PicesInterface::PicesDataBase::MLClassLoad(), and PicesInterface::PicesDataBase::MLClassLoadList().
String^ PicesInterface::PicesClass::Name get
Definition at line 50 of file PicesClass.h.
Referenced by PicesInterface::PicesFeatureVector::!PicesFeatureVector(), AddAChild(), PicesCommander.ClassStatSortedList::AddCount(), PicesInterface::TrainingModel2::AddImageToTrainingLibray(), PicesCommander.ClassStatSortedList::AddOne(), ChangeNameOfClass(), PicesCommander.ChartAbundanceByDeployment::ChartAbundanceByDeployment(), PicesCommander.ChartAbundancePredictedAndValidated::ChartAbundancePredictedAndValidated(), PicesCommander.ChartDistribution::ChartDistribution(), PicesCommander.ChartHorizontalProfile::ChartHorizontalProfile(), PicesCommander.ChartSizeDepthDistribution::ChartSizeDepthDistribution(), PicesCommander.ChartSizeDistribution::ChartSizeDistribution(), PicesCommander.ClassDepthProfileChart::ClassDepthProfileChart(), PicesCommander.ClassificationStatus::ClassificationStatus(), PicesCommander.ClassMaintenance::ClassMaintenance(), PicesCommander.ClassificationStatus::CleanUpMemory(), PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets(), PicesCommander.SizeDistribution2::ExtractFamilyOfClasses(), PicesInterface::PicesClassList::ExtractThreeTitleLines(), PicesInterface::PicesClassList::ExtractTwoTitleLines(), PicesCommander.PicesCommander::GetThumbnailImageAbort(), PicesCommander.Harvester::Harvester(), SipperFile.ImageViewer::ImageViewer(), PicesCommander.SizeDistribution::Increment(), PicesCommander.SizeDistribution2::Increment(), PicesCommander.SizeDistribution::InitiateClass(), PicesCommander.SizeDistribution2::InitiateClass(), PicesCommander.InstrumentDataByDeploymentProfile::InstrumentDataByDeploymentProfile(), GradeTrainingModel.ImageListDisplay::LoadImageGrid(), PicesInterface::PicesPredictionList::LookUpByClass(), GradeTrainingModel.ConfusionMatrix::MakePrediction(), PicesInterface::PicesDataBase::MLClassUpdate(), PicesInterface::PicesClassStatistic::PicesClassStatistic(), PicesInterface::PicesPrediction::PicesPrediction(), PicesInterface::PicesTrainingClass::PicesTrainingClass(), SipperFile.PredictionBreakDownDisplay::PredictionBreakDownDisplay(), PicesCommander.SizeDistribution::PrintByClassCollumns(), PicesCommander.SizeDistribution2::PrintTabDelDistributionMatrixesForSummaryClasses(), Save(), PicesCommander.SaveFeatureData::SaveFeatureData(), PicesCommander.SavePlanktonData::SavePlanktonData(), SipperFile.SelectAPicesClass::SelectAPicesClass(), GradeTrainingModel.ConfusionMatrix::SetTrainingModel(), PicesCommander.ClassifierProcess::StartThread(), PicesCommander.SizeDistribution2::SummarizeFamilyOfClasses(), PicesCommander.SizeDistribution::SumUpFamilyOfClasses(), PicesCommander.SizeDistribution::SumUpFamilyOfClassesForBucket(), GradeTrainingModel.ConfusionMatrix::TallyPredictions(), PicesInterface::ClassificationBiasMatrix::TestPaperResults(), PicesCommander.ClassStat::ToString(), PicesCommander.TrainingModelCreateFromDirectory::TrainingModelCreateFromDirectory(), UnmanagedMLClass(), and PicesCommander.PicesCommander::UpdateLastClassesValidated().
String^ PicesInterface::PicesClass::NameUpper get
Definition at line 51 of file PicesClass.h.
Referenced by PicesInterface::PicesClassList::ClassNameComparitor::Compare(), PicesInterface::PicesClassList::CreateFromDirectoryStructure(), PicesInterface::PicesClassList::LookUpByName(), and GradeTrainingModel.ConfusionMatrix::TallyPredictions().
bool PicesInterface::PicesClass::NoiseClass get
Definition at line 52 of file PicesClass.h.
Referenced by PicesCommander.ClassificationStatus::CleanUpMemory().
kkuint16 PicesInterface::PicesClass::NumHierarchialLevels get
Definition at line 53 of file PicesClass.h.
PicesClass^ PicesInterface::PicesClass::Parent get set
Definition at line 54 of file PicesClass.h.
Referenced by AddAChild(), PicesCommander.ClassMaintenance::ClassMaintenance(), PicesCommander.ClassificationStatus::CleanUpMemory(), PicesInterface::PicesClassList::CreateFromDirectoryStructure(), PicesInterface::PicesDataBase::MLClassLoad(), PicesInterface::PicesDataBase::MLClassLoadList(), PicesCommander.ClassifierProcess::StartThread(), and PicesInterface::PicesClassList::UpdateParent().
String^ PicesInterface::PicesClass::ParentName get
Definition at line 55 of file PicesClass.h.
Referenced by PicesCommander.ClassMaintenance::ClassMaintenance(), PicesCommander.ClassificationStatus::CleanUpMemory(), PicesInterface::PicesClassList::CreateFromDirectoryStructure(), and PicesCommander.ClassifierProcess::StartThread().
bool PicesInterface::PicesClass::StoredOnDataBase get set
Definition at line 57 of file PicesClass.h.
Referenced by PicesCommander.ClassMaintenance::ClassMaintenance().
bool PicesInterface::PicesClass::Summarize get set
Definition at line 58 of file PicesClass.h.
Referenced by PicesCommander.ClassMaintenance::ClassMaintenance(), PicesInterface::PicesClassList::ExtractSummarizeClasses(), PicesInterface::PicesDataBase::MLClassLoad(), and PicesInterface::PicesDataBase::MLClassLoadList().
bool PicesInterface::PicesClass::UnDefined get
Inidicates that class undefined or Noise.
Definition at line 59 of file PicesClass.h.
Referenced by GradeTrainingModel.ConfusionMatrix::TallyPredictions().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesClass.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesClass.cpp