Pices: KKB::MorphOpSobel Class Reference
KKB::MorphOpSobel Class Reference
#include <MorphOpSobel.h>
Public Member Functions
MorphOpSobel ()
~MorphOpSobel (void)
virtual OperationType Operation () const
virtual RasterPtr PerformOperation (Raster const *_image)
Public Member Functions inherited from KKB::MorphOp
MorphOp ()
virtual ~MorphOp ()
OperationType OperationTypeFromStr (const KKB::KKStr &_operationStr)
KKB::KKStr OperationTypeToStr (OperationType _operation)
Additional Inherited Members
Public Types inherited from KKB::MorphOp
enum MaskTypes : int {
MaskTypes::CROSS3 = 0, MaskTypes::CROSS5 = 1, MaskTypes::SQUARE3 = 2, MaskTypes::SQUARE5 = 3,
MaskTypes::SQUARE7 = 4, MaskTypes::SQUARE9 = 5, MaskTypes::SQUARE11 = 6
}
enum OperationType {
OperationType::Null, OperationType::Binarize, OperationType::BmiFiltering, OperationType::ConvexHull,
OperationType::Dilation, OperationType::Erosion, OperationType::MaskExclude, OperationType::SobelEdgeDetection,
OperationType::Stretcher
}
enum StructureType : int { StructureType::Null, StructureType::stCross, StructureType::stSquare }
Static Public Member Functions inherited from KKB::MorphOp
static kkint32 Biases (MaskTypes mt)
static StructureType MaskShapes (MaskTypes mt)
Protected Member Functions inherited from KKB::MorphOp
bool BackgroundPixel (uchar pixel) const
bool BackgroundPixel (kkint32 row, kkint32 col) const
bool ForegroundPixel (uchar pixel) const
bool ForegroundPixel (kkint32 row, kkint32 col) const
void SetSrcRaster (RasterConstPtr _srcRaster)
Protected Attributes inherited from KKB::MorphOp
uchar backgroundPixelTH
uchar backgroundPixelValue
uchar *const * srcBlue
uchar const * srcBlueArea
bool srcColor
uchar *const * srcGreen
uchar const * srcGreenArea
kkint32 srcHeight
RasterConstPtr srcRaster
uchar *const * srcRed
uchar const * srcRedArea
kkint32 srcWidth
Static Protected Attributes inherited from KKB::MorphOp
static kkint32 biases []
static StructureType maskShapes []
Detailed Description
Definition at line 18 of file MorphOpSobel.h.
Constructor & Destructor Documentation
MorphOpSobel::MorphOpSobel ()
Definition at line 23 of file MorphOpSobel.cpp.
MorphOpSobel::~MorphOpSobel (void)
Definition at line 29 of file MorphOpSobel.cpp.
References KKB::MorphOp::srcHeight, and KKB::MorphOp::srcWidth.
Member Function Documentation
virtual OperationType KKB::MorphOpSobel::Operation () const inline virtual
Implements KKB::MorphOp.
Definition at line 25 of file MorphOpSobel.h.
References KKB::MorphOp::SobelEdgeDetection.
RasterPtr MorphOpSobel::PerformOperation (Raster const * _image) virtual
Implements KKB::MorphOp.
Definition at line 62 of file MorphOpSobel.cpp.
References KKB::Raster::Color(), KKB::Raster::CreateGrayScaleKLT(), KKB::Raster::SetPixelValue(), KKB::MorphOp::SetSrcRaster(), KKB::MorphOp::srcGreen, KKB::MorphOp::srcHeight, and KKB::MorphOp::srcWidth.
Referenced by KKB::Raster::SobelEdgeDetector().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/MorphOpSobel.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/MorphOpSobel.cpp