Pices: SipperFile.TrainingModelStatus Class Reference
SipperFile.TrainingModelStatus Class Reference
Public Member Functions
TrainingModelStatus (String _trainingModelName, bool _forceRebuild, AlertCompletion _completionEvent)
delegate void AlertCompletion (TrainingModelStatus sender)
void CancelLoad ()
void CleanUpMemory ()
void ForceCancelation ()
TrainingModel2 TrainiedModel ()
bool TrainingModelRunning ()
bool ValidModel ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Detailed Description
Definition at line 23 of file TrainingModelStatus.cs.
Constructor & Destructor Documentation
SipperFile.TrainingModelStatus.TrainingModelStatus (String _trainingModelName, bool _forceRebuild, AlertCompletion _completionEvent) inline
Definition at line 45 of file TrainingModelStatus.cs.
Member Function Documentation
delegate void SipperFile.TrainingModelStatus.AlertCompletion (TrainingModelStatus sender)
void SipperFile.TrainingModelStatus.CancelLoad () inline
Definition at line 91 of file TrainingModelStatus.cs.
References PicesInterface::TrainingModel2.CancelLoad().
Referenced by SipperFile.ActiveTrainingLibraries.CancelLoads(), SipperFile.TrainingModelStatus.CleanUpMemory(), and SipperFile.TrainingModelStatus.ForceCancelation().
void SipperFile.TrainingModelStatus.CleanUpMemory () inline
Definition at line 64 of file TrainingModelStatus.cs.
References SipperFile.TrainingModelStatus.CancelLoad(), and SipperFile.TrainingModelStatus.ForceCancelation().
override void SipperFile.TrainingModelStatus.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file TrainingModelStatus.Designer.cs.
void SipperFile.TrainingModelStatus.ForceCancelation () inline
Definition at line 102 of file TrainingModelStatus.cs.
References PicesInterface::PicesMsgQueue.AddMsg(), PicesInterface::PicesMsgQueue.AddMsgs(), PicesInterface::TrainingModel2.AttachMsgQueueToRunLog(), SipperFile.TrainingModelStatus.CancelLoad(), PicesInterface::TrainingModel2.CancelLoad(), PicesInterface::TrainingModel2.ErrorMsgs, PicesInterface::PicesMsgQueue.GetNextMsg(), PicesInterface::TrainingModel2.LoadExistingModelOtherwiseBuild(), PicesInterface::TrainingModel2.LoadTrainigLibrary(), PicesInterface::TrainingModel2.RunLogFileName, PicesInterface::PicesDataBase.ThreadEnd(), PicesInterface::PicesDataBase.ThreadInit(), and PicesInterface::TrainingModel2.Valid.
Referenced by SipperFile.ActiveTrainingLibraries.CancelLoadWait(), and SipperFile.TrainingModelStatus.CleanUpMemory().
TrainingModel2 SipperFile.TrainingModelStatus.TrainiedModel () inline
Definition at line 58 of file TrainingModelStatus.cs.
Referenced by SipperFile.ActiveTrainingLibraries.SetModel2().
bool SipperFile.TrainingModelStatus.TrainingModelRunning () inline
Definition at line 59 of file TrainingModelStatus.cs.
bool SipperFile.TrainingModelStatus.ValidModel () inline
Definition at line 60 of file TrainingModelStatus.cs.
Referenced by SipperFile.ActiveTrainingLibraries.SetModel2().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/SipperFile/TrainingModelStatus.cs
C:/Users/Kurt/GitHub/Pices/PicesLibraries/SipperFile/TrainingModelStatus.Designer.cs