Pices: C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/DataBase.cpp File Reference
DataBase.cpp File Reference
#include <errmsg.h>
#include <my_global.h>
#include <my_sys.h>
#include <mysql.h>
#include "FirstIncludes.h"
#include <ctype.h>
#include <math.h>
#include <time.h>
#include <fstream>
#include <iostream>
#include <map>
#include <string>
#include <vector>
#include "MemoryDebug.h"
#include "KKBaseTypes.h"
#include "KKException.h"
#include "OSservices.h"
#include "RasterSipper.h"
#include "FileDesc.h"
#include "FeatureFileIOPices.h"
#include "ImageFeatures.h"
#include "DataBase.h"
#include "DataBaseServer.h"
#include "GPSDataPoint.h"
#include "InstrumentDataFileManager.h"
#include "SipperFile.h"
#include "SipperStation.h"
#include "PicesVariables.h"
#include "SipperCruise.h"
#include "VolumeSampledStat.h"
Functions
double CharStarToDouble (const char *s)
float CharStarToFloat (const char *s)
KKB::kkint32 CharStarToInt32 (const char *s)
KKB::kkint64 CharStarToInt64 (const char *s)
KKB::kkuint32 CharStarToUint16 (const char *s)
KKB::kkuint32 CharStarToUint32 (const char *s)
KKB::kkuint64 CharStarToUint64 (const char *s)
KKB::ulong CharStarToUlong (const char *s)
KKStr DateToQuotedStr (const DateType &d)
KKB::kkint32 LookUpFeatureDataField (const KKStr &fieldName)
Variables
KKB::kkint32 initializeMySqlLibraryEmbeddedThreadId = 0
Function Documentation
double CharStarToDouble (const char * s)
Definition at line 125 of file DataBase.cpp.
float CharStarToFloat (const char * s)
Definition at line 117 of file DataBase.cpp.
KKB::kkint32 CharStarToInt32 (const char * s)
Definition at line 57 of file DataBase.cpp.
KKB::kkint64 CharStarToInt64 (const char * s)
Definition at line 90 of file DataBase.cpp.
KKB::kkuint32 CharStarToUint16 (const char * s)
Definition at line 65 of file DataBase.cpp.
KKB::kkuint32 CharStarToUint32 (const char * s)
Definition at line 73 of file DataBase.cpp.
Referenced by MLL::DataBase::ImageGetDepthStatistics().
KKB::kkuint64 CharStarToUint64 (const char * s)
Definition at line 103 of file DataBase.cpp.
KKB::ulong CharStarToUlong (const char * s)
Definition at line 81 of file DataBase.cpp.
KKStr DateToQuotedStr (const DateType & d)
Definition at line 1372 of file DataBase.cpp.
References KKB::DateType::YYYY_MM_DD().
Referenced by MLL::DataBase::InsertCruise().
KKB::kkint32 LookUpFeatureDataField (const KKStr & fieldName)
Definition at line 1842 of file DataBase.cpp.
References MLL::FeatureFileIOPices::PlanktonFieldName(), and MLL::FeatureFileIOPices::PlanktonMaxNumOfFields().
Variable Documentation
KKB::kkint32 initializeMySqlLibraryEmbeddedThreadId = 0
Definition at line 314 of file DataBase.cpp.
Referenced by MLL::DataBase::FinalCleanUp().