Pices: MLL::InstrumentData Class Reference
MLL::InstrumentData Class Reference
#include <InstrumentData.h>
Public Types
typedef KKB::kkint32 kkint32
typedef KKB::kkint64 kkint64
typedef KKB::kkuint32 kkuint32
typedef KKB::kkuint64 kkuint64
Public Member Functions
InstrumentData ()
InstrumentData (const InstrumentData &id)
InstrumentData (KKStrParser &line, const VectorInt &fieldIndirections)
InstrumentData (kkuint32 _scanLine, kkuint32 _byteOffset, const KKB::DateTime &_ctdDate, char _activeBattery, double _latitude, double _longitude, float _ctdBattery, float _conductivity, float _density, float _depth, float _flowRate1, float _flowRate2, float _fluorescence, float _fluorescenceSensor, float _cdomFluorescence, float _cdomFluorescenceSensor, float _illumination, float _oxygen, float _oxygenSensor, float _pressure, float _recordRate, float _salinity, float _soundVelocity, float _temperature, float _transmisivity, float _transmisivitySensor, float _turbidity, float _turbiditySensor, float _pitch, float _roll, float _bat1Level, float _bat2Level, float _bat3Level, float _bat4Level, kkuint16 _cropLeft, kkuint16 _cropRight, kkuint16 _activeColumns)
~InstrumentData ()
kkint32 ActiveBattery () const
kkuint16 ActiveColumns () const
void ActiveColumns (kkuint16 _activeColumns)
float Bat1Level () const
float Bat2Level () const
float Bat3Level () const
float Bat4Level () const
KKB::kkuint64 ByteOffset () const
void ByteOffset (kkuint64 _byteOffset)
float CdomFluorescence () const
void CdomFluorescence (float _cdomFluorescence)
float CdomFluorescenceSensor () const
void CdomFluorescenceSensor (float _cdomFluorescenceSensor)
float Conductivity () const
void Conductivity (float _conductivity)
kkuint16 CropLeft () const
void CropLeft (kkuint16 _cropLeft)
kkuint16 CropRight () const
void CropRight (kkuint16 _cropRight)
float CTDBattery () const
void CTDBattery (float _ctdBattery)
const KKB::DateTime & CtdDate () const
void CtdDate (const KKB::DateTime &_ctdDate)
float Density () const
void Density (float _density)
float Depth () const
void Depth (float _depth)
KKStr FieldToStr (kkint32 fieldIndex) const
float FlowRate1 () const
void FlowRate1 (float _flowRate1)
float FlowRate2 () const
void FlowRate2 (float _flowRate2)
float Fluorescence () const
void Fluorescence (float _fluorescence)
float FluorescenceSensor () const
void FluorescenceSensor (float _fluorescenceSensor)
float Illumination () const
double Latitude () const
void Latitude (double _latitude)
double Longitude () const
void Longitude (double _longitude)
float Oxygen () const
void Oxygen (float _oxygen)
float OxygenSensor () const
void OxygenSensor (float _oxygenSensor)
float Pitch () const
void Pitch (float _pitch)
float Pressure () const
void Pressure (float _pressure)
float RecordRate () const
void RecordRate (float _recordRate)
void RefreshDataFields (const InstrumentData &id)
refreshes data fields from another 'InstrumentData' instance.
float Roll () const
void Roll (float _roll)
float Salinity () const
void Salinity (float _salinity)
kkuint32 ScanLine () const
void ScanLine (kkuint32 _scanLine)
float SoundVelocity () const
void SoundVelocity (float _soundVelocity)
float Temperature () const
void Temperature (float _temperature)
KKStr ToTabDelStr () const
float Transmisivity () const
void Transmisivity (float _transmisivity)
float TransmisivitySensor () const
void TransmisivitySensor (float _transmisivitySensor)
float Turbidity () const
void Turbidity (float _turbidity)
float TurbiditySensor () const
void TurbiditySensor (float _turbiditySensor)
void UpdateFromCtdData (const CTD_Plus_Data &ctdData)
Static Public Member Functions
static KKStr CdomFluorescenceUnit ()
static VectorIntPtr CreateDefaultFieldIndirectionList ()
static VectorIntPtr CreateFieldIndirectionVectorFromTabDelStr (KKStrParser &s)
static kkint32 CurrentFileVersion ()
static KKStr DensityUnit ()
static const KKStr & FieldFormatStr (kkint32 fieldIndex)
static float FieldMinValue (kkint32 fieldIndex)
static const KKStr & FieldName (kkint32 fieldIndex)
static const KKStr & FieldUnitOfMeasure (kkint32 fieldIndex)
static void FinalCleanUp ()
static KKStr FluorescenceUnit ()
static kkint32 GetFieldNum (const KKStr &s)
static kkint32 GetFieldNumFromShortName (const KKStr &s)
static kkint32 NumFields ()
static KKStr OxygenUnit ()
static KKStr SalinityUnit ()
static const KKStr & ShortFieldName (kkint32 fieldIndex)
static KKStr TemperatureUnit ()
static KKStr TransmisivityUnit ()
static KKStr TurbidityUnit ()
Detailed Description
Definition at line 16 of file InstrumentData.h.
Member Typedef Documentation
typedef KKB::kkint32 MLL::InstrumentData::kkint32
Definition at line 19 of file InstrumentData.h.
typedef KKB::kkint64 MLL::InstrumentData::kkint64
Definition at line 21 of file InstrumentData.h.
typedef KKB::kkuint32 MLL::InstrumentData::kkuint32
Definition at line 20 of file InstrumentData.h.
typedef KKB::kkuint64 MLL::InstrumentData::kkuint64
Definition at line 22 of file InstrumentData.h.
Constructor & Destructor Documentation
InstrumentData::InstrumentData ()
Definition at line 23 of file InstrumentData.cpp.
InstrumentData::InstrumentData (const InstrumentData & id)
Definition at line 41 of file InstrumentData.cpp.
InstrumentData::InstrumentData (KKStrParser & line, const VectorInt & fieldIndirections)
Definition at line 76 of file InstrumentData.cpp.
References KKB::KKStrParser::GetNextToken().
InstrumentData::InstrumentData (kkuint32 _scanLine, kkuint32 _byteOffset, const KKB::DateTime & _ctdDate, char _activeBattery, double _latitude, double _longitude, float _ctdBattery, float _conductivity, float _density, float _depth, float _flowRate1, float _flowRate2, float _fluorescence, float _fluorescenceSensor, float _cdomFluorescence, float _cdomFluorescenceSensor, float _illumination, float _oxygen, float _oxygenSensor, float _pressure, float _recordRate, float _salinity, float _soundVelocity, float _temperature, float _transmisivity, float _transmisivitySensor, float _turbidity, float _turbiditySensor, float _pitch, float _roll, float _bat1Level, float _bat2Level, float _bat3Level, float _bat4Level, kkuint16 _cropLeft, kkuint16 _cropRight, kkuint16 _activeColumns)
Definition at line 109 of file InstrumentData.cpp.
InstrumentData::~InstrumentData ()
Definition at line 223 of file InstrumentData.cpp.
Member Function Documentation
kkint32 MLL::InstrumentData::ActiveBattery () const inline
Definition at line 96 of file InstrumentData.h.
kkuint16 MLL::InstrumentData::ActiveColumns () const inline
Definition at line 97 of file InstrumentData.h.
void MLL::InstrumentData::ActiveColumns (kkuint16 _activeColumns) inline
Definition at line 152 of file InstrumentData.h.
float MLL::InstrumentData::Bat1Level () const inline
Definition at line 98 of file InstrumentData.h.
float MLL::InstrumentData::Bat2Level () const inline
Definition at line 99 of file InstrumentData.h.
float MLL::InstrumentData::Bat3Level () const inline
Definition at line 100 of file InstrumentData.h.
float MLL::InstrumentData::Bat4Level () const inline
Definition at line 101 of file InstrumentData.h.
KKB::kkuint64 MLL::InstrumentData::ByteOffset () const inline
Definition at line 92 of file InstrumentData.h.
Referenced by MLL::InstrumentDataList::CreateFromSipperFile().
void MLL::InstrumentData::ByteOffset (kkuint64 _byteOffset) inline
Definition at line 147 of file InstrumentData.h.
float MLL::InstrumentData::CdomFluorescence () const inline
Definition at line 112 of file InstrumentData.h.
void MLL::InstrumentData::CdomFluorescence (float _cdomFluorescence) inline
Definition at line 165 of file InstrumentData.h.
float MLL::InstrumentData::CdomFluorescenceSensor () const inline
Definition at line 113 of file InstrumentData.h.
void MLL::InstrumentData::CdomFluorescenceSensor (float _cdomFluorescenceSensor) inline
Definition at line 166 of file InstrumentData.h.
static KKStr MLL::InstrumentData::CdomFluorescenceUnit () inline static
Definition at line 140 of file InstrumentData.h.
float MLL::InstrumentData::Conductivity () const inline
Definition at line 103 of file InstrumentData.h.
void MLL::InstrumentData::Conductivity (float _conductivity) inline
Definition at line 158 of file InstrumentData.h.
VectorIntPtr InstrumentData::CreateDefaultFieldIndirectionList () static
Definition at line 506 of file InstrumentData.cpp.
References NumFields().
VectorIntPtr InstrumentData::CreateFieldIndirectionVectorFromTabDelStr (KKStrParser & s) static
Definition at line 479 of file InstrumentData.cpp.
References KKB::endl(), GetFieldNum(), NumFields(), and KKB::KKStrParser::Split().
kkuint16 MLL::InstrumentData::CropLeft () const inline
Definition at line 104 of file InstrumentData.h.
void MLL::InstrumentData::CropLeft (kkuint16 _cropLeft) inline
Definition at line 153 of file InstrumentData.h.
kkuint16 MLL::InstrumentData::CropRight () const inline
Definition at line 105 of file InstrumentData.h.
void MLL::InstrumentData::CropRight (kkuint16 _cropRight) inline
Definition at line 154 of file InstrumentData.h.
float MLL::InstrumentData::CTDBattery () const inline
Definition at line 102 of file InstrumentData.h.
Referenced by MLL::InstrumentDataList::CreateFromSipperFile().
void MLL::InstrumentData::CTDBattery (float _ctdBattery) inline
Definition at line 157 of file InstrumentData.h.
const KKB::DateTime& MLL::InstrumentData::CtdDate () const inline
Definition at line 94 of file InstrumentData.h.
Referenced by MLL::DataBaseImageList::CalculateDensitesByQuadrat(), and MLL::InstrumentDataList::CreateFromSipperFile().
void MLL::InstrumentData::CtdDate (const KKB::DateTime & _ctdDate) inline
Definition at line 145 of file InstrumentData.h.
static kkint32 MLL::InstrumentData::CurrentFileVersion () inline static
Definition at line 88 of file InstrumentData.h.
Referenced by MLL::InstrumentDataList::Save().
float MLL::InstrumentData::Density () const inline
Definition at line 107 of file InstrumentData.h.
void MLL::InstrumentData::Density (float _density) inline
Definition at line 160 of file InstrumentData.h.
static KKStr MLL::InstrumentData::DensityUnit () inline static
Definition at line 133 of file InstrumentData.h.
float MLL::InstrumentData::Depth () const inline
Definition at line 106 of file InstrumentData.h.
Referenced by MLL::InstrumentDataList::CreateFromSipperFile(), MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::DataBase::FeatureDataUpdateInstrumentDataFields(), MLL::InstrumentDataList::GetScanLinesPerMeterProfile(), MLL::InstrumentDataList::GetVolumePerMeterProfile(), MLL::DataBase::ImageUpdateInstrumentDataFields(), and MLL::FeatureFileIOPices::LoadFile().
void MLL::InstrumentData::Depth (float _depth) inline
Definition at line 159 of file InstrumentData.h.
const KKStr & InstrumentData::FieldFormatStr (kkint32 fieldIndex) static
Definition at line 391 of file InstrumentData.cpp.
References NumFields().
float InstrumentData::FieldMinValue (kkint32 fieldIndex) static
Definition at line 381 of file InstrumentData.cpp.
References NumFields().
const KKStr & InstrumentData::FieldName (kkint32 fieldIndex) static
Definition at line 352 of file InstrumentData.cpp.
References NumFields().
Referenced by MLL::InstrumentDataList::Save().
KKStr InstrumentData::FieldToStr (kkint32 fieldIndex) const
Definition at line 519 of file InstrumentData.cpp.
References KKB::DateTime::Date(), KKB::endl(), KKB::TimeType::HH_MM_SS(), KKB::SPRINTF(), KKB::StrFormatDouble(), KKB::StrFormatInt(), KKB::StrFromInt32(), KKB::StrFromUint32(), KKB::StrFromUint64(), KKB::DateTime::Time(), and KKB::DateType::YYYY_MM_DD().
Referenced by ToTabDelStr().
const KKStr & InstrumentData::FieldUnitOfMeasure (kkint32 fieldIndex) static
Definition at line 372 of file InstrumentData.cpp.
References NumFields().
void InstrumentData::FinalCleanUp () static
Definition at line 704 of file InstrumentData.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
Referenced by GetFieldNum().
float MLL::InstrumentData::FlowRate1 () const inline
Definition at line 108 of file InstrumentData.h.
Referenced by MLL::DataBaseImageList::CalculateDensitesByQuadrat(), MLL::InstrumentDataList::CreateFromSipperFile(), MLL::ImageFeaturesList::ExtractPositionsByMeter(), MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::DataBase::FeatureDataUpdateInstrumentDataFields(), FlowRate(), MLL::InstrumentDataList::FrameOffsetsInMeters(), MLL::DataBase::ImageUpdateInstrumentDataFields(), and MLL::FeatureFileIOPices::LoadFile().
void MLL::InstrumentData::FlowRate1 (float _flowRate1) inline
Definition at line 161 of file InstrumentData.h.
float MLL::InstrumentData::FlowRate2 () const inline
Definition at line 109 of file InstrumentData.h.
Referenced by MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::DataBase::FeatureDataUpdateInstrumentDataFields(), MLL::DataBase::ImageUpdateInstrumentDataFields(), and MLL::FeatureFileIOPices::LoadFile().
void MLL::InstrumentData::FlowRate2 (float _flowRate2) inline
Definition at line 162 of file InstrumentData.h.
float MLL::InstrumentData::Fluorescence () const inline
Definition at line 110 of file InstrumentData.h.
Referenced by MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::DataBase::FeatureDataUpdateInstrumentDataFields(), MLL::DataBase::ImageUpdateInstrumentDataFields(), and MLL::FeatureFileIOPices::LoadFile().
void MLL::InstrumentData::Fluorescence (float _fluorescence) inline
Definition at line 163 of file InstrumentData.h.
float MLL::InstrumentData::FluorescenceSensor () const inline
Definition at line 111 of file InstrumentData.h.
void MLL::InstrumentData::FluorescenceSensor (float _fluorescenceSensor) inline
Definition at line 164 of file InstrumentData.h.
static KKStr MLL::InstrumentData::FluorescenceUnit () inline static
Definition at line 134 of file InstrumentData.h.
kkint32 InstrumentData::GetFieldNum (const KKStr & s) static
Definition at line 416 of file InstrumentData.cpp.
References KKB::GoalKeeper::EndBlock(), FinalCleanUp(), NumFields(), KKB::GoalKeeper::StartBlock(), and KKB::KKStr::ToUpper().
Referenced by CreateFieldIndirectionVectorFromTabDelStr().
kkint32 InstrumentData::GetFieldNumFromShortName (const KKStr & s) static
Definition at line 451 of file InstrumentData.cpp.
References NumFields(), and KKB::KKStr::ToUpper().
float MLL::InstrumentData::Illumination () const inline
Definition at line 114 of file InstrumentData.h.
double MLL::InstrumentData::Latitude () const inline
Definition at line 117 of file InstrumentData.h.
Referenced by MLL::DataBase::FeatureDataGetOneSipperFile(), and MLL::FeatureFileIOPices::FeatureDataReSink().
void MLL::InstrumentData::Latitude (double _latitude) inline
Definition at line 148 of file InstrumentData.h.
double MLL::InstrumentData::Longitude () const inline
Definition at line 118 of file InstrumentData.h.
Referenced by MLL::DataBase::FeatureDataGetOneSipperFile(), and MLL::FeatureFileIOPices::FeatureDataReSink().
void MLL::InstrumentData::Longitude (double _longitude) inline
Definition at line 149 of file InstrumentData.h.
kkint32 InstrumentData::NumFields () static
Definition at line 401 of file InstrumentData.cpp.
Referenced by CreateDefaultFieldIndirectionList(), CreateFieldIndirectionVectorFromTabDelStr(), FieldFormatStr(), FieldMinValue(), FieldName(), FieldUnitOfMeasure(), GetFieldNum(), GetFieldNumFromShortName(), MLL::InstrumentDataList::Save(), ShortFieldName(), and ToTabDelStr().
float MLL::InstrumentData::Oxygen () const inline
Definition at line 115 of file InstrumentData.h.
Referenced by MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::DataBase::FeatureDataUpdateInstrumentDataFields(), MLL::DataBase::ImageUpdateInstrumentDataFields(), and MLL::FeatureFileIOPices::LoadFile().
void MLL::InstrumentData::Oxygen (float _oxygen) inline
Definition at line 168 of file InstrumentData.h.
float MLL::InstrumentData::OxygenSensor () const inline
Definition at line 116 of file InstrumentData.h.
void MLL::InstrumentData::OxygenSensor (float _oxygenSensor) inline
Definition at line 167 of file InstrumentData.h.
static KKStr MLL::InstrumentData::OxygenUnit () inline static
Definition at line 135 of file InstrumentData.h.
float MLL::InstrumentData::Pitch () const inline
Definition at line 130 of file InstrumentData.h.
void MLL::InstrumentData::Pitch (float _pitch) inline
Definition at line 179 of file InstrumentData.h.
float MLL::InstrumentData::Pressure () const inline
Definition at line 119 of file InstrumentData.h.
void MLL::InstrumentData::Pressure (float _pressure) inline
Definition at line 169 of file InstrumentData.h.
float MLL::InstrumentData::RecordRate () const inline
Definition at line 120 of file InstrumentData.h.
void MLL::InstrumentData::RecordRate (float _recordRate) inline
Definition at line 170 of file InstrumentData.h.
void InstrumentData::RefreshDataFields (const InstrumentData & id)
refreshes data fields from another 'InstrumentData' instance.
Definition at line 660 of file InstrumentData.cpp.
Referenced by MLL::InstrumentDataList::CreateFromSipperFile().
float MLL::InstrumentData::Roll () const inline
Definition at line 131 of file InstrumentData.h.
void MLL::InstrumentData::Roll (float _roll) inline
Definition at line 180 of file InstrumentData.h.
float MLL::InstrumentData::Salinity () const inline
Definition at line 121 of file InstrumentData.h.
Referenced by MLL::InstrumentDataList::CreateFromSipperFile(), MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::DataBase::FeatureDataUpdateInstrumentDataFields(), MLL::DataBase::ImageUpdateInstrumentDataFields(), and MLL::FeatureFileIOPices::LoadFile().
void MLL::InstrumentData::Salinity (float _salinity) inline
Definition at line 171 of file InstrumentData.h.
static KKStr MLL::InstrumentData::SalinityUnit () inline static
Definition at line 136 of file InstrumentData.h.
kkuint32 MLL::InstrumentData::ScanLine () const inline
Definition at line 122 of file InstrumentData.h.
Referenced by MLL::InstrumentDataList::CreateFromSipperFile(), MLL::InstrumentDataList::FrameOffsetsInMeters(), MLL::DataBase::InstrumentDataReFreshSipperFile(), and MLL::InstrumentDataList::SearchForNearestScanLine().
void MLL::InstrumentData::ScanLine (kkuint32 _scanLine) inline
Definition at line 150 of file InstrumentData.h.
const KKStr & InstrumentData::ShortFieldName (kkint32 fieldIndex) static
Definition at line 362 of file InstrumentData.cpp.
References NumFields().
float MLL::InstrumentData::SoundVelocity () const inline
Definition at line 123 of file InstrumentData.h.
void MLL::InstrumentData::SoundVelocity (float _soundVelocity) inline
Definition at line 172 of file InstrumentData.h.
float MLL::InstrumentData::Temperature () const inline
Definition at line 124 of file InstrumentData.h.
Referenced by MLL::InstrumentDataList::CreateFromSipperFile().
void MLL::InstrumentData::Temperature (float _temperature) inline
Definition at line 173 of file InstrumentData.h.
static KKStr MLL::InstrumentData::TemperatureUnit () inline static
Definition at line 137 of file InstrumentData.h.
KKStr InstrumentData::ToTabDelStr () const
Definition at line 642 of file InstrumentData.cpp.
References FieldToStr(), and NumFields().
Referenced by MLL::InstrumentDataList::Save().
float MLL::InstrumentData::Transmisivity () const inline
Definition at line 125 of file InstrumentData.h.
void MLL::InstrumentData::Transmisivity (float _transmisivity) inline
Definition at line 174 of file InstrumentData.h.
float MLL::InstrumentData::TransmisivitySensor () const inline
Definition at line 126 of file InstrumentData.h.
void MLL::InstrumentData::TransmisivitySensor (float _transmisivitySensor) inline
Definition at line 175 of file InstrumentData.h.
static KKStr MLL::InstrumentData::TransmisivityUnit () inline static
Definition at line 138 of file InstrumentData.h.
float MLL::InstrumentData::Turbidity () const inline
Definition at line 127 of file InstrumentData.h.
void MLL::InstrumentData::Turbidity (float _turbidity) inline
Definition at line 176 of file InstrumentData.h.
float MLL::InstrumentData::TurbiditySensor () const inline
Definition at line 128 of file InstrumentData.h.
void MLL::InstrumentData::TurbiditySensor (float _turbiditySensor) inline
Definition at line 177 of file InstrumentData.h.
static KKStr MLL::InstrumentData::TurbidityUnit () inline static
Definition at line 139 of file InstrumentData.h.
void InstrumentData::UpdateFromCtdData (const CTD_Plus_Data & ctdData)
Definition at line 680 of file InstrumentData.cpp.
References MLL::CTD_Plus_Data::BatteryVoltage(), MLL::CTD_Plus_Data::CdomFluorescence(), MLL::CTD_Plus_Data::CdomFluorescenceSensor(), MLL::CTD_Plus_Data::Conductivity(), MLL::CTD_Plus_Data::Density(), MLL::CTD_Plus_Data::Depth(), MLL::CTD_Plus_Data::Fluorescence(), MLL::CTD_Plus_Data::FluorescenceSensor(), MLL::CTD_Plus_Data::Oxygen(), MLL::CTD_Plus_Data::OxygenSensor(), MLL::CTD_Plus_Data::Pressure(), MLL::CTD_Plus_Data::Salinity(), MLL::CTD_Plus_Data::SoundVelocity(), MLL::CTD_Plus_Data::Temperature(), MLL::CTD_Plus_Data::Transmisivity(), MLL::CTD_Plus_Data::TransmisivitySensor(), MLL::CTD_Plus_Data::Turbidity(), and MLL::CTD_Plus_Data::TurbiditySensor().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/InstrumentData.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/InstrumentData.cpp