Pices: KKB::Blob Class Reference
KKB::Blob Class Reference
Used by the Raster object to identify a distinct blob; where it is in the raster and its unique id.
#include <Blob.h>
Public Member Functions
Blob (kkint32 _id)
~Blob ()
Point BotRight () const
Returns a point to the Bottom Right corner of the blob.
kkint32 ColLeft ()
Left most column in the raster object that this blob occupies.
kkint32 ColRight ()
Right most column in the raster object that this blob occupies.
kkint32 Height ()
Number of rows that the blob occupies.
kkint32 Id ()
The unique ID assigned to this blob.
void InitialzieAsNew (kkint32 _id)
kkint32 PixelCount ()
Number of pixels that are part of this blob.
kkint32 RowBot ()
Bottom row in the raster object that this blob occupies.
kkint32 RowTop ()
Top row in the raster object that this blob occupies.
Point TopLeft () const
Returns a point to the Top Left corner of the blob.
kkint32 Width ()
Number of columns that this blob occupies.
Public Attributes
kkint32 colLeft
kkint32 colRight
kkint32 id
kkint32 pixelCount
kkint32 rowBot
kkint32 rowTop
Friends
class BlobList
Detailed Description
Used by the Raster object to identify a distinct blob; where it is in the raster and its unique id.
It is used by the Raster object while performing a connected component analysis. For each distinct blob located an instance of this class will be created. Its location in the raster and its unique blob ID will be stored here. These blobs will later be able to be extracted from the image by referencing this blob.
The "id" field in this blob will be stored in a array in the associated Raster object. This allows the Raster object to identify the specific pixels that belong to this Blob. Using the fields "colLeft" "colRight", "rowBot", and "rowTop" the Raster object will be able to quickly locate the associated blob.
See Also
KKB::Raster
KKB::Raster::ExtractABlob
KKB::Raster::ExtractABlobTightly
Definition at line 32 of file Blob.h.
Constructor & Destructor Documentation
Blob::Blob (kkint32 _id)
Definition at line 22 of file Blob.cpp.
Blob::~Blob ()
Definition at line 35 of file Blob.cpp.
Member Function Documentation
Point KKB::Blob::BotRight () const inline
Returns a point to the Bottom Right corner of the blob.
Definition at line 59 of file Blob.h.
References colRight, and rowBot.
kkint32 KKB::Blob::ColLeft () inline
Left most column in the raster object that this blob occupies.
Definition at line 46 of file Blob.h.
References colLeft.
Referenced by KKB::Raster::CreateColorWithBlobsLabeldByColor(), KKB::Raster::CreateFromOrginalImageWithSpecifidBlobsOnly(), and KKB::Raster::FillBlob().
kkint32 KKB::Blob::ColRight () inline
Right most column in the raster object that this blob occupies.
Definition at line 47 of file Blob.h.
References colRight.
Referenced by KKB::Raster::CreateColorWithBlobsLabeldByColor(), KKB::Raster::CreateFromOrginalImageWithSpecifidBlobsOnly(), and KKB::Raster::FillBlob().
kkint32 KKB::Blob::Height () inline
Number of rows that the blob occupies.
Definition at line 49 of file Blob.h.
References rowBot, and rowTop.
Referenced by KKB::Raster::ExtractABlobTightly(), and KKB::BlobList::LocateMostComplete().
kkint32 KKB::Blob::Id () inline
The unique ID assigned to this blob.
See Also
BlobList::nextBlobId
Definition at line 44 of file Blob.h.
References id.
Referenced by KKB::Raster::ConnectedComponent(), KKB::Raster::ConnectedComponent8Conected(), KKB::Raster::CreateColorWithBlobsLabeldByColor(), KKB::Raster::CreateFromOrginalImageWithSpecifidBlobsOnly(), KKB::Raster::ExtractBlobs(), KKB::Raster::FillBlob(), KKB::BlobList::MergeBlobIds(), KKB::BlobList::MergeIntoSingleBlob(), KKB::BlobList::PushOnBack(), KKB::BlobList::PushOnFront(), and KKB::Raster::ReduceToMostCompleteBlob().
void Blob::InitialzieAsNew (kkint32 _id)
Definition at line 41 of file Blob.cpp.
References colLeft, colRight, pixelCount, rowBot, and rowTop.
Referenced by KKB::BlobList::NewBlob().
kkint32 KKB::Blob::PixelCount () inline
Number of pixels that are part of this blob.
Definition at line 56 of file Blob.h.
References pixelCount.
Referenced by KKMLL::GrayScaleImagesFVProducer::ComputeFeatureVector(), and KKB::BlobList::MergeIntoSingleBlob().
kkint32 KKB::Blob::RowBot () inline
Bottom row in the raster object that this blob occupies.
Definition at line 51 of file Blob.h.
References rowBot.
Referenced by KKB::Raster::CreateColorWithBlobsLabeldByColor(), KKB::Raster::CreateFromOrginalImageWithSpecifidBlobsOnly(), and KKB::Raster::FillBlob().
kkint32 KKB::Blob::RowTop () inline
Top row in the raster object that this blob occupies.
Definition at line 52 of file Blob.h.
References rowTop.
Referenced by KKB::Raster::CreateColorWithBlobsLabeldByColor(), KKB::Raster::CreateFromOrginalImageWithSpecifidBlobsOnly(), and KKB::Raster::FillBlob().
Point KKB::Blob::TopLeft () const inline
Returns a point to the Top Left corner of the blob.
Definition at line 58 of file Blob.h.
References colLeft, and rowTop.
kkint32 KKB::Blob::Width () inline
Number of columns that this blob occupies.
Definition at line 54 of file Blob.h.
References colLeft, and colRight.
Referenced by KKB::Raster::ExtractABlobTightly(), and KKB::BlobList::LocateMostComplete().
Friends And Related Function Documentation
friend class BlobList friend
Definition at line 34 of file Blob.h.
Member Data Documentation
kkint32 KKB::Blob::colLeft
Definition at line 61 of file Blob.h.
Referenced by ColLeft(), KKB::Raster::ConnectedComponent8Conected(), KKB::Raster::ExtractABlob(), KKB::Raster::ExtractABlobTightly(), KKB::Raster::ExtractBlobs(), InitialzieAsNew(), KKB::BlobList::MergeBlobIds(), KKB::BlobList::MergeIntoSingleBlob(), KKB::BlobList::NewBlob(), TopLeft(), and Width().
kkint32 KKB::Blob::colRight
Definition at line 62 of file Blob.h.
Referenced by BotRight(), ColRight(), KKB::Raster::ConnectedComponent8Conected(), KKB::Raster::ExtractBlobs(), InitialzieAsNew(), KKB::BlobList::MergeBlobIds(), KKB::BlobList::MergeIntoSingleBlob(), KKB::BlobList::NewBlob(), and Width().
kkint32 KKB::Blob::id
Definition at line 63 of file Blob.h.
Referenced by KKB::Raster::ConnectedComponent8Conected(), KKB::Raster::ExtractABlob(), KKB::Raster::ExtractABlobTightly(), KKB::Raster::ExtractBlobs(), and Id().
kkint32 KKB::Blob::pixelCount
Definition at line 64 of file Blob.h.
Referenced by KKB::Raster::ConnectedComponent8Conected(), KKB::Raster::ExtractBlobs(), InitialzieAsNew(), KKB::BlobList::LocateLargestBlob(), KKB::BlobList::MergeBlobIds(), KKB::BlobList::MergeIntoSingleBlob(), and PixelCount().
kkint32 KKB::Blob::rowBot
Definition at line 65 of file Blob.h.
Referenced by BotRight(), KKB::Raster::ConnectedComponent8Conected(), KKB::Raster::ExtractBlobs(), Height(), InitialzieAsNew(), KKB::BlobList::MergeBlobIds(), KKB::BlobList::MergeIntoSingleBlob(), KKB::BlobList::NewBlob(), and RowBot().
kkint32 KKB::Blob::rowTop
Definition at line 66 of file Blob.h.
Referenced by KKB::Raster::ConnectedComponent8Conected(), KKB::Raster::ExtractABlob(), KKB::Raster::ExtractABlobTightly(), KKB::Raster::ExtractBlobs(), Height(), InitialzieAsNew(), KKB::BlobList::MergeBlobIds(), KKB::BlobList::MergeIntoSingleBlob(), KKB::BlobList::NewBlob(), RowTop(), and TopLeft().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/KSquareLibraries/KKBase/Blob.h
C:/Users/kurtk_000/GitHub/KSquareLibraries/KKBase/Blob.cpp