Pices: MLL::InstrumentDataReport Class Reference
MLL::InstrumentDataReport Class Reference
#include <InstrumentDataReport.h>
Public Types
typedef InstrumentDataReport * InstrumentDataReportPtr
typedef KKB::kkint32 kkint32
typedef KKB::kkuint32 kkuint32
Public Member Functions
InstrumentDataReport (InstrumentDataManagerPtr _manager, const KKStr &_reportDir, bool _text, kkint32 _instrumentId, bool _useReportWithLineNumbers)
virtual ~InstrumentDataReport ()
const KKStr & CurTextLine ()
const KKStr & LastTextLine ()
virtual void ReportInstrumentData (kkuint32 curScanLine, uchar sensorData)
Static Public Member Functions
static InstrumentDataReportPtr CreateInstrumentDataReport (InstrumentDataManagerPtr _manager, const KKStr &_reportDir, bool _text, kkint32 _instrumentId)
A virtual Constructor for InstrumentDataReport instances.
Protected Member Functions
KKStr InstrumentName ()
Protected Attributes
KKStr curTextLine
Used where "text == true", Every time a character is read via 'ReportInstrumentData' will append to end of string.
kkint32 instrumentId
kkuint32 lastScanLineReported
KKStr lastTextLine
Used where "text == true", will keep an instance of last complete text line read.
InstrumentDataManagerPtr manager
ofstream report
KKStr reportFileName
KKStr reportFileNameWLN
ofstream reportWLN
bool text
bool useReportWithLineNumbers
Static Protected Attributes
static const char * InstrumentNames []
Detailed Description
Definition at line 15 of file InstrumentDataReport.h.
Member Typedef Documentation
typedef InstrumentDataReport* MLL::InstrumentDataReport::InstrumentDataReportPtr
Definition at line 18 of file InstrumentDataReport.h.
typedef KKB::kkint32 MLL::InstrumentDataReport::kkint32
Definition at line 19 of file InstrumentDataReport.h.
typedef KKB::kkuint32 MLL::InstrumentDataReport::kkuint32
Definition at line 20 of file InstrumentDataReport.h.
Constructor & Destructor Documentation
InstrumentDataReport::InstrumentDataReport (InstrumentDataManagerPtr _manager, const KKStr & _reportDir, bool _text, kkint32 _instrumentId, bool _useReportWithLineNumbers)
Definition at line 61 of file InstrumentDataReport.cpp.
References KKB::KKStr::Empty(), InstrumentName(), KKB::osAddSlash(), report, reportFileName, reportFileNameWLN, reportWLN, KKB::KKStr::Str(), text, and useReportWithLineNumbers.
Referenced by CreateInstrumentDataReport().
InstrumentDataReport::~InstrumentDataReport () virtual
Definition at line 91 of file InstrumentDataReport.cpp.
References report, and reportWLN.
Member Function Documentation
InstrumentDataReportPtr InstrumentDataReport::CreateInstrumentDataReport (InstrumentDataManagerPtr _manager, const KKStr & _reportDir, bool _text, kkint32 _instrumentId) static
A virtual Constructor for InstrumentDataReport instances.
Based on the parameters will instantiate an instance of the correct derived. In the future as different types of instruments are introduced we can make specialized versions of InstrumentDataReport.
Parameters
[in] _manager InstrumentDataManager instance that will this newly created instance will report to.
[in] _reportDir Directory where report file is to be placed.
[in] _text Set to true = text data, false = binary data.
[in] _instrumentId Sensor/Instrument ID
Definition at line 106 of file InstrumentDataReport.cpp.
References MLL::Instrument::CreateInstrumentDataReporter(), MLL::InstrumentDataManager::HeaderRec(), InstrumentDataReport(), and MLL::SipperHeaderRec::SerialPortAssignment().
Referenced by MLL::InstrumentDataManager::ReportInstrumentData().
const KKStr& MLL::InstrumentDataReport::CurTextLine () inline
Definition at line 32 of file InstrumentDataReport.h.
KKStr InstrumentDataReport::InstrumentName () protected
Definition at line 182 of file InstrumentDataReport.cpp.
References instrumentId, InstrumentNames, and KKB::StrFormatInt().
Referenced by InstrumentDataReport().
const KKStr& MLL::InstrumentDataReport::LastTextLine () inline
Definition at line 33 of file InstrumentDataReport.h.
void InstrumentDataReport::ReportInstrumentData (kkuint32 curScanLine, uchar sensorData) virtual
Reimplemented in MLL::InstrumentDataGPS, MLL::InstrumentDataFlowMeter1, MLL::InstrumentDataPitchAndRoll, MLL::InstrumentDataCTDplus, MLL::InstrumentDataUserMsgs, and MLL::InstrumentDataBatteryMeter.
Definition at line 198 of file InstrumentDataReport.cpp.
References KKB::KKStr::Append(), curTextLine, KKB::endl(), lastScanLineReported, lastTextLine, KKB::KKStr::Len(), report, reportWLN, text, and useReportWithLineNumbers.
Referenced by MLL::InstrumentDataManager::ReportInstrumentData().
Member Data Documentation
KKStr MLL::InstrumentDataReport::curTextLine protected
Used where "text == true", Every time a character is read via 'ReportInstrumentData' will append to end of string.
When a '
' is processed will move to 'lastTextLine' and then set to empty.
Definition at line 63 of file InstrumentDataReport.h.
Referenced by ReportInstrumentData().
kkint32 MLL::InstrumentDataReport::instrumentId protected
Definition at line 68 of file InstrumentDataReport.h.
Referenced by InstrumentName().
const char * InstrumentDataReport::InstrumentNames static protected
Initial value:
=
{
  "Synchronization_pulse",
  "Real-Time_Clock",
  "FIFO_Buffer_Status",
  "FireWire_Error",
  "Internal_Temperature",
  "Internal_Humidity",
  "User_Text_Message",
  "Other_Internal_Status",
  "CTD",
  "GPS",
  "Flow_meter_1",
  "Flow_meter_2",
  "OPC",
  "Fluorometer",
  "Transmissometer",
  "Camera_messages",
  "Serisl Port 0",
  "Serisl Port 1",
  "Serisl Port 2",
  "Serisl Port 3",
  NULL
}
Definition at line 61 of file InstrumentDataReport.h.
Referenced by InstrumentName().
kkuint32 MLL::InstrumentDataReport::lastScanLineReported protected
Definition at line 70 of file InstrumentDataReport.h.
Referenced by ReportInstrumentData().
KKStr MLL::InstrumentDataReport::lastTextLine protected
Used where "text == true", will keep an instance of last complete text line read.
Will come from curText line when ever a '
' character is read.
Definition at line 72 of file InstrumentDataReport.h.
Referenced by ReportInstrumentData().
InstrumentDataManagerPtr MLL::InstrumentDataReport::manager protected
Definition at line 77 of file InstrumentDataReport.h.
Referenced by MLL::InstrumentDataBatteryMeter::ProcessBatteryData(), and MLL::InstrumentDataFlowMeter1::ReportInstrumentData().
ofstream MLL::InstrumentDataReport::report protected
Definition at line 80 of file InstrumentDataReport.h.
Referenced by InstrumentDataReport(), MLL::InstrumentDataBatteryMeter::ReportInstrumentData(), MLL::InstrumentDataCTDplus::ReportInstrumentData(), MLL::InstrumentDataUserMsgs::ReportInstrumentData(), MLL::InstrumentDataPitchAndRoll::ReportInstrumentData(), MLL::InstrumentDataFlowMeter1::ReportInstrumentData(), MLL::InstrumentDataGPS::ReportInstrumentData(), ReportInstrumentData(), MLL::InstrumentDataBatteryMeter::~InstrumentDataBatteryMeter(), MLL::InstrumentDataCTDplus::~InstrumentDataCTDplus(), MLL::InstrumentDataGPS::~InstrumentDataGPS(), MLL::InstrumentDataPitchAndRoll::~InstrumentDataPitchAndRoll(), ~InstrumentDataReport(), and MLL::InstrumentDataUserMsgs::~InstrumentDataUserMsgs().
KKStr MLL::InstrumentDataReport::reportFileName protected
Definition at line 78 of file InstrumentDataReport.h.
Referenced by InstrumentDataReport().
KKStr MLL::InstrumentDataReport::reportFileNameWLN protected
Definition at line 79 of file InstrumentDataReport.h.
Referenced by InstrumentDataReport().
ofstream MLL::InstrumentDataReport::reportWLN protected
Definition at line 81 of file InstrumentDataReport.h.
Referenced by InstrumentDataReport(), ReportInstrumentData(), and ~InstrumentDataReport().
bool MLL::InstrumentDataReport::text protected
Definition at line 82 of file InstrumentDataReport.h.
Referenced by MLL::InstrumentDataFlowMeter1::InstrumentDataFlowMeter1(), InstrumentDataReport(), MLL::InstrumentDataFlowMeter1::ReportInstrumentData(), and ReportInstrumentData().
bool MLL::InstrumentDataReport::useReportWithLineNumbers protected
Definition at line 83 of file InstrumentDataReport.h.
Referenced by InstrumentDataReport(), and ReportInstrumentData().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/InstrumentDataReport.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/InstrumentDataReport.cpp