Pices: PicesInterface::PicesImageSizeDistribution Class Reference
PicesInterface::PicesImageSizeDistribution Class Reference
#include <PicesImageSizeDistribution.h>
Public Member Functions
PicesImageSizeDistribution (ImageSizeDistributionPtr _imageSizeDistributionPtr)
PicesImageSizeDistribution (PicesImageSizeDistribution^ _imageSizeDistribution)
void AddIn (PicesImageSizeDistribution^ right, PicesRunLog^ log)
PicesImageSizeDistributionRow^ AllDepths ()
array< float >^ DepthProfileForSizeBin (kkuint32 _sizeBucketIdx)
PicesImageSizeDistributionRow^ GetDepthBin (uint depthBinIdx)
void GetSizeBucketStats (uint _sizeBucketIdx, uint% _count, float% _sizeStart, float% _sizeEnd)
kkint32 IdentifySizeBucket (float size)
array< float >^ IntegratedDensityDistribution ()
array< float >^ SizeEndValues ()
array< float >^ SizeStartValues ()
MLL::ImageSizeDistributionPtr UnmanagedClass ()
array< float >^ VolumeSampledByDepthBucket ()
Protected Member Functions
!PicesImageSizeDistribution ()
Properties
float DepthBinSize [get]
float EndValue [get]
float GrowthRate [get]
float InitialValue [get]
int NumDepthBins [get]
int NumSizeBuckets [get]
Detailed Description
Definition at line 48 of file PicesImageSizeDistribution.h.
Constructor & Destructor Documentation
PicesInterface::PicesImageSizeDistribution::PicesImageSizeDistribution (ImageSizeDistributionPtr _imageSizeDistributionPtr)
PicesInterface::PicesImageSizeDistribution::PicesImageSizeDistribution (PicesImageSizeDistribution^ _imageSizeDistribution)
Definition at line 85 of file PicesImageSizeDistribution.cpp.
References UnmanagedClass().
PicesInterface::PicesImageSizeDistribution::!PicesImageSizeDistribution () protected
Definition at line 99 of file PicesImageSizeDistribution.cpp.
Member Function Documentation
void PicesInterface::PicesImageSizeDistribution::AddIn (PicesImageSizeDistribution^ right, PicesRunLog^ log)
Definition at line 130 of file PicesImageSizeDistribution.cpp.
References PicesInterface::PicesRunLog::Log(), and UnmanagedClass().
PicesImageSizeDistributionRow PicesInterface::PicesImageSizeDistribution::AllDepths ()
Definition at line 139 of file PicesImageSizeDistribution.cpp.
array< float > PicesInterface::PicesImageSizeDistribution::DepthProfileForSizeBin (kkuint32 _sizeBucketIdx)
Definition at line 192 of file PicesImageSizeDistribution.cpp.
Referenced by PicesCommander.ChartSizeDepthDistribution::ChartSizeDepthDistribution().
PicesImageSizeDistributionRow PicesInterface::PicesImageSizeDistribution::GetDepthBin (uint depthBinIdx)
Definition at line 146 of file PicesImageSizeDistribution.cpp.
void PicesInterface::PicesImageSizeDistribution::GetSizeBucketStats (uint _sizeBucketIdx, uint% _count, float% _sizeStart, float% _sizeEnd)
Definition at line 157 of file PicesImageSizeDistribution.cpp.
kkint32 PicesInterface::PicesImageSizeDistribution::IdentifySizeBucket (float size)
Definition at line 176 of file PicesImageSizeDistribution.cpp.
array< float > PicesInterface::PicesImageSizeDistribution::IntegratedDensityDistribution ()
Definition at line 182 of file PicesImageSizeDistribution.cpp.
array< float > PicesInterface::PicesImageSizeDistribution::SizeEndValues ()
Definition at line 118 of file PicesImageSizeDistribution.cpp.
Referenced by PicesCommander.ChartSizeDepthDistribution::ChartSizeDepthDistribution(), and SipperFile.DisplayPicesImages::DisplayPicesImages().
array< float > PicesInterface::PicesImageSizeDistribution::SizeStartValues ()
Definition at line 107 of file PicesImageSizeDistribution.cpp.
References SizeStartValues().
Referenced by PicesCommander.ChartSizeDepthDistribution::ChartSizeDepthDistribution(), SipperFile.DisplayPicesImages::DisplayPicesImages(), and SizeStartValues().
MLL::ImageSizeDistributionPtr PicesInterface::PicesImageSizeDistribution::UnmanagedClass () inline
Definition at line 69 of file PicesImageSizeDistribution.h.
Referenced by AddIn(), and PicesImageSizeDistribution().
array< float > PicesInterface::PicesImageSizeDistribution::VolumeSampledByDepthBucket ()
Definition at line 208 of file PicesImageSizeDistribution.cpp.
Referenced by PicesCommander.ChartSizeDepthDistribution::ChartSizeDepthDistribution().
Property Documentation
float PicesInterface::PicesImageSizeDistribution::DepthBinSize get
Definition at line 62 of file PicesImageSizeDistribution.h.
float PicesInterface::PicesImageSizeDistribution::EndValue get
Definition at line 65 of file PicesImageSizeDistribution.h.
float PicesInterface::PicesImageSizeDistribution::GrowthRate get
Definition at line 64 of file PicesImageSizeDistribution.h.
float PicesInterface::PicesImageSizeDistribution::InitialValue get
Definition at line 63 of file PicesImageSizeDistribution.h.
int PicesInterface::PicesImageSizeDistribution::NumDepthBins get
Definition at line 67 of file PicesImageSizeDistribution.h.
int PicesInterface::PicesImageSizeDistribution::NumSizeBuckets get
Definition at line 66 of file PicesImageSizeDistribution.h.
Referenced by PicesCommander.ChartSizeDepthDistribution::ChartSizeDepthDistribution().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesInterface/PicesImageSizeDistribution.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesInterface/PicesImageSizeDistribution.cpp