Pices: SipperFile.GroupMaintenance Class Reference
SipperFile.GroupMaintenance Class Reference
Public Member Functions
GroupMaintenance ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Detailed Description
Definition at line 12 of file GroupMaintenance.cs.
Constructor & Destructor Documentation
SipperFile.GroupMaintenance.GroupMaintenance () inline
Definition at line 19 of file GroupMaintenance.cs.
References PicesInterface::PicesSipperVariables.AllowUpdates(), PicesInterface::PicesDataBaseImageGroup.Count, PicesInterface::PicesDataBaseImageGroup.Description, PicesInterface::PicesDataBase.GetGlobalDatabaseManagerNewInstance(), PicesInterface::PicesDataBase.ImageGroupDelete(), PicesInterface::PicesDataBaseImageGroup.ImageGroupId, PicesInterface::PicesDataBase.ImageGroupLoad(), PicesInterface::PicesDataBaseImageGroup.Name, and PicesInterface::PicesSipperVariables.UpdatesNotAllowed().
Member Function Documentation
override void SipperFile.GroupMaintenance.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file GroupMaintenance.Designer.cs.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/SipperFile/GroupMaintenance.cs
C:/Users/Kurt/GitHub/Pices/PicesLibraries/SipperFile/GroupMaintenance.Designer.cs