Pices: FeatureSelectionApp::FinalResults Class Reference
FeatureSelectionApp::FinalResults Class Reference
#include <FinalResults.h>
Public Types
typedef FinalResults * FinalResultsPtr
typedef KKB::uint uint
Public Member Functions
FinalResults (const KKStr &_summaryResultsFileName, double _totalSearchTime, double _totalProcessingTime, double _elapsedClockTime, double _longestPath, int _jobCount, RunLog &_log)
~FinalResults ()
ConfusionMatrix2Ptr ConfusionMatrix ()
KKStr Description () const
KKStr LinkName () const
MLClassListPtr MLClasses () const
void PrintConfigParametersRandomSplitsHTML (HTMLReport &r)
void PrintConfigParametersValidationHTML (HTMLReport &r)
VectorFloat RandomSplitAccuracies () const
VectorFloat RandomSplitAccuracyByClass () const
VectorFloat RandomSplitClassCounts () const
KKStr SelectionMethodStr () const
KKStr ToHTMLStr () const
VectorFloat ValidationAccuracyByClass () const
VectorFloat ValidationClassCounts () const
const bool * ValidationClassedCorrectly () const
int ValidationClassedCorrectlySize () const
ConfusionMatrix2Ptr ValidationConfusionMatrix ()
Static Public Member Functions
static KKStr HeaderLineHTML1 ()
static KKStr HeaderLineHTML2 ()
static void PrintAccuraciesByClassSummary (vector< FinalResultsPtr > &results, HTMLReport &o, bool validationData)
Detailed Description
Definition at line 31 of file FinalResults.h.
Member Typedef Documentation
typedef FinalResults* FeatureSelectionApp::FinalResults::FinalResultsPtr
Definition at line 36 of file FinalResults.h.
typedef KKB::uint FeatureSelectionApp::FinalResults::uint
Definition at line 34 of file FinalResults.h.
Constructor & Destructor Documentation
FinalResults::FinalResults (const KKStr & _summaryResultsFileName, double _totalSearchTime, double _totalProcessingTime, double _elapsedClockTime, double _longestPath, int _jobCount, RunLog & _log)
Definition at line 60 of file FinalResults.cpp.
References FeatureSelectionApp::RandomSplitResultsList::Average(), FeatureSelectionApp::Results::ConfigFileName(), KKB::endl(), and KKB::RunLog::Level().
FinalResults::~FinalResults ()
Definition at line 112 of file FinalResults.cpp.
Member Function Documentation
ConfusionMatrix2Ptr FinalResults::ConfusionMatrix ()
Definition at line 121 of file FinalResults.cpp.
References FeatureSelectionApp::Results::ConfusionMatrix().
Referenced by PrintAccuraciesByClassSummary(), and ReportDataSpecs().
KKStr FinalResults::Description () const
Definition at line 156 of file FinalResults.cpp.
References FeatureSelectionApp::Results::Description().
Referenced by PrintAccuraciesByClassSummary(), and ReportDataSpecs().
KKStr FinalResults::HeaderLineHTML1 () static
Definition at line 301 of file FinalResults.cpp.
Referenced by ReportDataSpecs().
KKStr FinalResults::HeaderLineHTML2 () static
Definition at line 314 of file FinalResults.cpp.
Referenced by ReportDataSpecs().
KKStr FinalResults::LinkName () const
Definition at line 171 of file FinalResults.cpp.
References FeatureSelectionApp::Results::ConfigFileName(), KKB::osGetRootName(), and FeatureSelectionApp::Results::SelectionMethodStr().
Referenced by ReportDataSpecs(), and ToHTMLStr().
MLClassListPtr FinalResults::MLClasses () const
Definition at line 142 of file FinalResults.cpp.
References FeatureSelectionApp::Results::MLClasses().
void FinalResults::PrintAccuraciesByClassSummary (vector< FinalResultsPtr > & results, HTMLReport & o, bool validationData) static
Definition at line 516 of file FinalResults.cpp.
References KKMLL::ConfusionMatrix2::AccuracyByClass(), ConfusionMatrix(), KKMLL::ConfusionMatrix2::CountsByKnownClass(), Description(), KKB::endl(), KKB::KKStr::Parse(), KKB::StrFormatDouble(), and ValidationConfusionMatrix().
Referenced by ReportDataSpecs().
void FinalResults::PrintConfigParametersRandomSplitsHTML (HTMLReport & r)
Definition at line 294 of file FinalResults.cpp.
Referenced by ReportDataSpecs().
void FinalResults::PrintConfigParametersValidationHTML (HTMLReport & r)
Definition at line 288 of file FinalResults.cpp.
Referenced by ReportDataSpecs().
VectorFloat FinalResults::RandomSplitAccuracies () const
Definition at line 193 of file FinalResults.cpp.
References FeatureSelectionApp::Results::Accuracy().
Referenced by ReportDataSpecs().
VectorFloat FinalResults::RandomSplitAccuracyByClass () const
Definition at line 212 of file FinalResults.cpp.
References FeatureSelectionApp::Results::AccuracyByClass(), and VectorFloat.
VectorFloat FeatureSelectionApp::FinalResults::RandomSplitClassCounts () const
KKStr FeatureSelectionApp::FinalResults::SelectionMethodStr () const
KKStr FinalResults::ToHTMLStr () const
Definition at line 354 of file FinalResults.cpp.
References KKMLL::ConfusionMatrix2::Accuracy(), KKMLL::ConfusionMatrix2::AccuracyNorm(), KKMLL::ConfusionMatrix2::AvgPredProb(), KKB::KKStr::CompareIgnoreCase(), FeatureSelectionApp::Results::ConfusionMatrix(), FeatureSelectionApp::RandomSplitResults::ConstructFromStream(), FeatureSelectionApp::ValidationResults::ConstructFromStream(), FeatureSelectionApp::Results::Description(), KKB::endl(), KKB::KKStr::ExtractToken2(), KKB::RunLog::Level(), LinkName(), FeatureSelectionApp::Results::MachineTypeStr(), FeatureSelectionApp::Results::NumFeatures(), FeatureSelectionApp::Results::NumFeaturesWeighted(), FeatureSelectionApp::Results::NumSVs(), KKB::KKQueue< Entry >::PushOnBack(), FeatureSelectionApp::Results::SelectionMethodStr(), KKB::KKStr::Str(), KKB::StrFormatDouble(), KKB::StrFormatInt(), FeatureSelectionApp::Results::TestTime(), FeatureSelectionApp::Results::TotalNumSVs(), FeatureSelectionApp::Results::TrainingTime(), KKB::KKStr::TrimLeft(), and KKB::KKStr::TrimRight().
Referenced by ReportDataSpecs().
VectorFloat FinalResults::ValidationAccuracyByClass () const
Definition at line 244 of file FinalResults.cpp.
References FeatureSelectionApp::Results::AccuracyByClass(), FeatureSelectionApp::Results::Description(), KKB::endl(), FeatureSelectionApp::Results::MachineTypeStr(), FeatureSelectionApp::Results::NumFeatures(), FeatureSelectionApp::Results::NumSupportVectors(), FeatureSelectionApp::Results::SelectionMethodStr(), KKB::StrFormatDouble(), KKB::StrFormatInt(), FeatureSelectionApp::Results::TestTime(), FeatureSelectionApp::Results::TrainingTime(), and VectorFloat.
VectorFloat FeatureSelectionApp::FinalResults::ValidationClassCounts () const
const bool * FinalResults::ValidationClassedCorrectly () const
Definition at line 223 of file FinalResults.cpp.
References FeatureSelectionApp::ValidationResults::ClassedCorrectly().
Referenced by ReportDataSpecs().
int FinalResults::ValidationClassedCorrectlySize () const
Definition at line 233 of file FinalResults.cpp.
References FeatureSelectionApp::ValidationResults::ClassedCorrectlySize().
Referenced by ReportDataSpecs().
ConfusionMatrix2Ptr FinalResults::ValidationConfusionMatrix ()
Definition at line 132 of file FinalResults.cpp.
References FeatureSelectionApp::Results::ConfusionMatrix().
Referenced by PrintAccuraciesByClassSummary(), and ReportDataSpecs().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/Apps/FeatureSelection/FinalResults.h
C:/Users/Kurt/GitHub/Pices/Apps/FeatureSelection/FinalResults.cpp