Pices: MLL::PicesVariables Class Reference
MLL::PicesVariables Class Reference
Base class to All PICES applications.
#include <PicesVariables.h>
Static Public Member Functions
static bool AllowUpdates ()
'True' indicates that user is allowed to perform updates.
static KKStr CmdLineProgDir ()
Directory where you can Command Line programs such as "CrossValidation.exe".
static KKStr ConfigrationFileName ()
static KKStr ConfigurationDirectory ()
Where application configuration files go; NOT training models.
static KKStr DataFileDirectory ()
static KKStr DataFilesDirectory ()
static const KKStr & HomeDir ()
Pices Home Directory.
static void InitializeEnvironment ()
static KKStr InstrumentDataFilesDir ()
static KKStr InstrumentDataReportDir ()
static KKStr LatitudeToStr (double latitude)
static KKStr LongitudeToStr (double longitude)
static void ParseImageFileName (const KKStr &fullFileName, KKStr &sipperFileName, kkuint32 &scanLineNum, kkuint32 &scanCol)
static KKStr ReportDir ()
static void SetHomeDir (const KKB::KKStr &_homeDir)
static KKStr SipperDirectoryListFileName ()
static KKStr SipperFilesDefaultDir ()
static KKStr SipperInterfaceDir ()
static KKStr SipperInterfaceLogDir ()
static KKStr TempDirectory ()
static KKStr TrainingLibrariesDir ()
Directory where training library directories will be under.
static KKStr TrainingModelsConfigurationDir ()
Directory where all Training Model Configuration files are stored.
static KKStr TrainingModelsSaveFilesDir ()
Directory where all built trained models are stored.
static KKStr ValidationInfoDir ()
Detailed Description
Base class to All PICES applications.
Variables specific to PICES applications will be located in this class.
Author
Kurt Kramer
Definition at line 23 of file PicesVariables.h.
Member Function Documentation
bool PicesVariables::AllowUpdates () static
'True' indicates that user is allowed to perform updates.
Definition at line 309 of file PicesVariables.cpp.
Referenced by MLL::DataBase::DataBase().
KKStr PicesVariables::CmdLineProgDir () static
Directory where you can Command Line programs such as "CrossValidation.exe".
Definition at line 116 of file PicesVariables.cpp.
References KKB::osAddSlash().
KKStr PicesVariables::ConfigrationFileName () static
Definition at line 182 of file PicesVariables.cpp.
References KKB::osAddSlash().
KKStr PicesVariables::ConfigurationDirectory () static
Where application configuration files go; NOT training models.
Definition at line 174 of file PicesVariables.cpp.
References KKB::osAddSlash().
Referenced by MLL::DataBaseServerList::WriteConfigFile().
KKStr PicesVariables::DataFileDirectory () static
Definition at line 232 of file PicesVariables.cpp.
References KKB::osAddSlash().
KKStr PicesVariables::DataFilesDirectory () static
Definition at line 192 of file PicesVariables.cpp.
References KKB::osAddSlash().
const KKStr & PicesVariables::HomeDir () static
Pices Home Directory.
All other directories will be off this directory.
Definition at line 54 of file PicesVariables.cpp.
References KKB::osAddSlash(), KKB::osDisplayWarning(), KKB::osGetCurrentDirectory(), KKB::osGetEnvVariable(), KKB::osGetFullPathOfApplication(), KKB::osGetParentDirPath(), and KKB::osGetPathPartOfFile().
Referenced by MLL::InstrumentDataFileManager::InstrumentDataFileManager().
void PicesVariables::InitializeEnvironment () static
Definition at line 34 of file PicesVariables.cpp.
References KKB::osAddSlash(), and KKB::osValidDirectory().
Referenced by MLL::PicesApplication::PicesApplication().
KKStr PicesVariables::InstrumentDataFilesDir () static
Definition at line 123 of file PicesVariables.cpp.
References KKB::osAddSlash().
Referenced by MLL::InstrumentDataFileManager::InstrumentDataFileManager().
KKStr PicesVariables::InstrumentDataReportDir () static
Definition at line 131 of file PicesVariables.cpp.
References KKB::osAddSlash().
KKStr PicesVariables::LatitudeToStr (double latitude) static
Definition at line 252 of file PicesVariables.cpp.
References KKB::StrFormatDouble(), and KKB::StrFormatInt().
KKStr PicesVariables::LongitudeToStr (double longitude) static
Definition at line 281 of file PicesVariables.cpp.
References KKB::StrFormatDouble(), and KKB::StrFormatInt().
void PicesVariables::ParseImageFileName (const KKStr & fullFileName, KKStr & sipperFileName, kkuint32 & scanLineNum, kkuint32 & scanCol) static
Definition at line 318 of file PicesVariables.cpp.
References KKB::KKStr::Empty(), KKB::endl(), KKB::KKStr::EqualIgnoreCase(), KKB::KKStr::ExtractToken2(), KKB::KKStr::LocateLastOccurrence(), KKB::osAddSlash(), KKB::osFOPEN(), KKB::osGetRootName(), KKB::KKStr::Str(), KKB::KKStr::SubStrPart(), and KKB::KKStr::ToBool().
Referenced by MLL::ImageFeatures::CalcFeatures(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::InstrumentDataFileManager::GetClosestInstrumentData(), MLL::DataBase::ImagesLocateClosestImage(), and MLL::FeatureFileIOPices::LoadInSubDirectoryTree().
KKStr PicesVariables::ReportDir () static
Definition at line 225 of file PicesVariables.cpp.
References KKB::osAddSlash().
Referenced by MLL::SipperBuff::ReportInstrumentData().
void PicesVariables::SetHomeDir (const KKB::KKStr & _homeDir) static
Definition at line 109 of file PicesVariables.cpp.
KKStr PicesVariables::SipperDirectoryListFileName () static
Definition at line 158 of file PicesVariables.cpp.
References KKB::osAddSlash().
Referenced by MLL::InstrumentDataFileManager::GetClosestInstrumentData().
KKStr PicesVariables::SipperFilesDefaultDir () static
Definition at line 166 of file PicesVariables.cpp.
References KKB::osAddSlash().
Referenced by MLL::InstrumentDataFileManager::GetClosestInstrumentData().
KKStr PicesVariables::SipperInterfaceDir () static
Definition at line 137 of file PicesVariables.cpp.
References KKB::osAddSlash(), and KKB::osGetEnvVariable().
KKStr PicesVariables::SipperInterfaceLogDir () static
Definition at line 149 of file PicesVariables.cpp.
References KKB::osAddSlash().
KKStr PicesVariables::TempDirectory () static
Definition at line 239 of file PicesVariables.cpp.
References KKB::osAddSlash(), KKB::osCreateDirectoryPath(), and KKB::osValidDirectory().
KKStr PicesVariables::TrainingLibrariesDir () static
Directory where training library directories will be under.
Definition at line 212 of file PicesVariables.cpp.
KKStr PicesVariables::TrainingModelsConfigurationDir () static
Directory where all Training Model Configuration files are stored.
Definition at line 199 of file PicesVariables.cpp.
Referenced by MLL::PicesTrainingConfiguration::CreateFromDirectoryStructure().
KKStr PicesVariables::TrainingModelsSaveFilesDir () static
Directory where all built trained models are stored.
Definition at line 205 of file PicesVariables.cpp.
Referenced by MLL::AbundanceCorrectionMatrix::SaveForConfigFileName().
KKStr PicesVariables::ValidationInfoDir () static
Definition at line 218 of file PicesVariables.cpp.
References KKB::osAddSlash().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/PicesVariables.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/PicesVariables.cpp