Pices: KKMLL::FeatureFileIORoberts Class Reference
KKMLL::FeatureFileIORoberts Class Reference
Supports the writing of Feature Data to a file that can then be read by OpenDT.
#include <FeatureFileIORoberts.h>
Public Types
typedef FeatureFileIORoberts * FeatureFileIORobertsPtr
Public Types inherited from KKMLL::FeatureFileIO
typedef FeatureFileIO * FeatureFileIOPtr
Public Member Functions
FeatureFileIORoberts ()
~FeatureFileIORoberts ()
virtual FileDescPtr GetFileDesc (const KKStr &_fileName, istream &_in, MLClassListPtr _classList, kkint32 &_estSize, KKStr &_errorMessage, RunLog &_log)
virtual FeatureVectorListPtr LoadFile (const KKStr &_fileName, const FileDescPtr _fileDesc, MLClassList &_classes, istream &_in, kkint32 _maxCount, VolConstBool &_cancelFlag, bool &_changesMade, KKStr &_errorMessage, RunLog &_log)
virtual void SaveFile (FeatureVectorList &_data, const KKStr &_fileName, FeatureNumListConst &_selFeatures, ostream &_out, kkuint32 &_numExamplesWritten, VolConstBool &_cancelFlag, bool &_successful, KKStr &_errorMessage, RunLog &_log)
Public Member Functions inherited from KKMLL::FeatureFileIO
FeatureFileIO (const KKStr &_driverName, bool _canRead, bool _canWrite)
virtual ~FeatureFileIO ()
void AppendToFile (const KKStr &_fileName, FeatureNumListConst &_selFeatures, FeatureVectorList &_examples, kkuint32 &_numExamplesWritten, VolConstBool &_cancelFlag, bool &_successful, RunLog &log)
bool CanRead ()
bool CanWrite ()
const KKStr & DriverName ()
virtual FeatureVectorListPtr FeatureDataReSink (FactoryFVProducerPtr _fvProducerFactory, const KKStr &_dirName, const KKStr &_fileName, MLClassPtr _unknownClass, bool _useDirectoryNameForClassName, MLClassList &_mlClasses, VolConstBool &_cancelFlag, bool &_changesMade, KKB::DateTime &_timeStamp, RunLog &_log)
FeatureDataReSink.
virtual FileDescPtr GetFileDesc (const KKStr &_fileName, std::istream &_in, MLClassListPtr _classes, kkint32 &_estSize, KKStr &_errorMessage, RunLog &_log)=0
Create a FileDesc object from the input stream '_in'.
virtual FeatureVectorListPtr LoadFeatureFile (const KKStr &_fileName, MLClassList &_mlClasses, kkint32 _maxCount, VolConstBool &_cancelFlag, bool &_successful, bool &_changesMade, RunLog &_log)
Loads the contents of a feature data file and returns a ImageFeaturesList container object.
virtual FeatureVectorListPtr LoadFile (const KKStr &_fileName, const FileDescPtr _fileDesc, MLClassList &_classes, std::istream &_in, kkint32 _maxCount, VolConstBool &_cancelFlag, bool &_changesMade, KKStr &_errorMessage, RunLog &_log)=0
To be implemented by derived classes; loads the contents of a feature data file and returns a ImageFeaturesList container object.
FeatureVectorListPtr LoadInSubDirectoryTree (FactoryFVProducerPtr _fvProducerFactory, KKStr _rootDir, MLClassList &_mlClasses, bool _useDirectoryNameForClassName, VolConstBool &_cancelFlag, bool _rewiteRootFeatureFile, RunLog &_log)
LoadInSubDirectoryTree.
virtual void SaveFeatureFile (const KKStr &_fileName, FeatureNumListConst &_selFeatures, FeatureVectorList &_examples, kkuint32 &_numExamplesWritten, VolConstBool &_cancelFlag, bool &_successful, RunLog &_log)
SaveFeatureFile.
void SaveFeatureFileMultipleParts (const KKStr &_fileName, FeatureNumListConst &_selFeatures, FeatureVectorList &_examples, VolConstBool &_cancelFlag, bool &_successful, RunLog &_log)
Saves the feature file in multiple parts with no one single part larger that 64k examples.
virtual void SaveFile (FeatureVectorList &_data, const KKStr &_fileName, FeatureNumListConst &_selFeatures, std::ostream &_out, kkuint32 &_numExamplesWritten, VolConstBool &_cancelFlag, bool &_successful, KKStr &_errorMessage, RunLog &_log)=0
To be implemented by derived classes; save examples to output stream '_out'.
Static Public Member Functions
static FeatureFileIORobertsPtr Driver ()
Static Public Member Functions inherited from KKMLL::FeatureFileIO
static FeatureFileIOPtr FileFormatFromStr (const KKStr &_fileFormatStr)
static FeatureFileIOPtr FileFormatFromStr (const KKStr &_fileFormatStr, bool _canRead, bool _canWrite)
static KKStr FileFormatsReadAndWriteOptionsStr ()
static KKStr FileFormatsReadOptionsStr ()
static KKStr FileFormatsWrittenOptionsStr ()
static void FinalCleanUp ()
Before you terminate your application and after all FeatureFileIO activity is done call this method to destroy statically dynamically allocated data structures.
static VectorKKStr RegisteredDriverNames (bool canRead, bool canWrite)
static void RegisterFeatureFileIODriver (FeatureFileIOPtr _driver)
For each feature file format register the appropriate driver through this static method.
Additional Inherited Members
Protected Member Functions inherited from KKMLL::FeatureFileIO
void GetLine (std::istream &_in, KKStr &_line, bool &_eof)
void GetToken (std::istream &_in, const char *_delimiters, KKStr &_token, bool &_eof, bool &_eol)
Will retrieve the next token from the input stream.
Static Protected Member Functions inherited from KKMLL::FeatureFileIO
static void RegisterDriver (FeatureFileIOPtr driver)
Detailed Description
Supports the writing of Feature Data to a file that can then be read by OpenDT.
************************************************************************************************
*  FeatureFileIOSRoberts  Sub-classed from FeatureFileIO.  It supports the writing of a file   *
*  that can be read by OpenDT. http://opendt.sourceforge.net/.  This file format is similar to *
*  C45 except the contents of the names file are included in the data file.                    *
************************************************************************************************
See also
FeatureFileIO
Definition at line 24 of file FeatureFileIORoberts.h.
Member Typedef Documentation
typedef FeatureFileIORoberts* KKMLL::FeatureFileIORoberts::FeatureFileIORobertsPtr
Definition at line 30 of file FeatureFileIORoberts.h.
Constructor & Destructor Documentation
FeatureFileIORoberts::FeatureFileIORoberts ()
Definition at line 36 of file FeatureFileIORoberts.cpp.
FeatureFileIORoberts::~FeatureFileIORoberts (void)
Definition at line 41 of file FeatureFileIORoberts.cpp.
Member Function Documentation
static FeatureFileIORobertsPtr KKMLL::FeatureFileIORoberts::Driver () inline static
Definition at line 32 of file FeatureFileIORoberts.h.
References GetFileDesc(), LoadFile(), and SaveFile().
FileDescPtr FeatureFileIORoberts::GetFileDesc (const KKStr & _fileName, istream & _in, MLClassListPtr _classList, kkint32 & _estSize, KKStr & _errorMessage, RunLog & _log) virtual
Definition at line 47 of file FeatureFileIORoberts.cpp.
References KKB::endl(), and KKB::RunLog::Level().
Referenced by Driver().
FeatureVectorListPtr FeatureFileIORoberts::LoadFile (const KKStr & _fileName, const FileDescPtr _fileDesc, MLClassList & _classes, istream & _in, kkint32 _maxCount, VolConstBool & _cancelFlag, bool & _changesMade, KKStr & _errorMessage, RunLog & _log) virtual
Definition at line 67 of file FeatureFileIORoberts.cpp.
References KKB::endl(), and KKB::RunLog::Level().
Referenced by Driver().
void FeatureFileIORoberts::SaveFile (FeatureVectorList & _data, const KKStr & _fileName, FeatureNumListConst & _selFeatures, ostream & _out, kkuint32 & _numExamplesWritten, VolConstBool & _cancelFlag, bool & _successful, KKStr & _errorMessage, RunLog & _log) virtual
Definition at line 88 of file FeatureFileIORoberts.cpp.
References KKMLL::Attribute::Cardinality(), KKMLL::FeatureVector::ClassName(), KKMLL::FileDesc::CreateAAttributeTable(), KKB::endl(), KKMLL::FeatureVectorList::ExtractListOfClasses(), KKMLL::FeatureVector::FeatureData(), KKMLL::FeatureVectorList::FileDesc(), KKMLL::Attribute::GetNominalValue(), KKB::KKQueue< Entry >::IdxToPtr(), KKB::RunLog::Level(), KKMLL::Nominal, KKB::KKQueue< Entry >::QueueSize(), KKMLL::MLClassList::SortByName(), KKB::KKStr::Str(), KKMLL::Symbolic, and KKMLL::Attribute::Type().
Referenced by Driver().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureFileIORoberts.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureFileIORoberts.cpp