Pices: ImageExtractionManager::SipperImage Class Reference
ImageExtractionManager::SipperImage Class Reference
#include <SipperImage.h>
Public Types
typedef SipperImage * SipperImagePtr
Public Member Functions
SipperImage ()
SipperImage (LogicalFrameBlobPtr blob)
~SipperImage ()
void AddBlob (LogicalFrameBlobPtr _blob)
kkuint64 ByteOffset () const
kkuint32 ColLeft () const
kkuint32 ColRight () const
void Dialate (uchar **frame, int **blobIds, int size)
void Explore (LogicalFrameBlobPtr _blob)
RasterSipperPtr GetRaster (uchar **frame, int **blobIds, kkuint32 firstFrameRowScanLine, kkuint64 *frameRowByteOffsets)
kkuint32 Height () const
kkuint32 PixelCount () const
kkuint32 RowBot () const
kkuint32 RowTop () const
kkuint32 Width () const
Detailed Description
Definition at line 12 of file SipperImage.h.
Member Typedef Documentation
typedef SipperImage* ImageExtractionManager::SipperImage::SipperImagePtr
Definition at line 15 of file SipperImage.h.
Constructor & Destructor Documentation
SipperImage::SipperImage ()
Definition at line 27 of file SipperImage.cpp.
SipperImage::SipperImage (LogicalFrameBlobPtr blob)
Definition at line 40 of file SipperImage.cpp.
References ImageExtractionManager::LogicalFrameBlob::colLeft, ImageExtractionManager::LogicalFrameBlob::colRight, ImageExtractionManager::LogicalFrameBlob::Explored(), ImageExtractionManager::LogicalFrameBlob::explored, KKB::Max(), Min(), ImageExtractionManager::LogicalFrameBlob::Neighbors(), ImageExtractionManager::LogicalFrameBlob::pixelCount, ImageExtractionManager::LogicalFrameBlob::rowBot, and ImageExtractionManager::LogicalFrameBlob::rowTop.
SipperImage::~SipperImage ()
Definition at line 82 of file SipperImage.cpp.
Member Function Documentation
void SipperImage::AddBlob (LogicalFrameBlobPtr _blob)
Definition at line 90 of file SipperImage.cpp.
References ImageExtractionManager::LogicalFrameBlob::ColLeft(), ImageExtractionManager::LogicalFrameBlob::ColRight(), KKB::Max(), Min(), ImageExtractionManager::LogicalFrameBlob::PixelCount(), ImageExtractionManager::LogicalFrameBlob::RowBot(), and ImageExtractionManager::LogicalFrameBlob::RowTop().
Referenced by Explore().
kkuint64 ImageExtractionManager::SipperImage::ByteOffset () const inline
Definition at line 25 of file SipperImage.h.
Referenced by ImageExtractionManager::LogicalFrame::ProcessFrame().
kkuint32 ImageExtractionManager::SipperImage::ColLeft () const inline
Definition at line 26 of file SipperImage.h.
Referenced by ImageExtractionManager::LogicalFrame::ProcessFrame().
kkuint32 ImageExtractionManager::SipperImage::ColRight () const inline
Definition at line 27 of file SipperImage.h.
Referenced by ImageExtractionManager::LogicalFrame::ProcessFrame().
void SipperImage::Dialate (uchar ** frame, int ** blobIds, int size)
Definition at line 126 of file SipperImage.cpp.
References ImageExtractionManager::LogicalFrameBlob::DialateBlob().
Referenced by ImageExtractionManager::LogicalFrame::ProcessFrame().
void SipperImage::Explore (LogicalFrameBlobPtr _blob)
Definition at line 104 of file SipperImage.cpp.
References AddBlob(), ImageExtractionManager::LogicalFrameBlob::Explored(), and ImageExtractionManager::LogicalFrameBlob::Neighbors().
Referenced by ImageExtractionManager::LogicalFrame::MemoryConsumedEstimated().
RasterSipperPtr SipperImage::GetRaster (uchar ** frame, int ** blobIds, kkuint32 firstFrameRowScanLine, kkuint64 * frameRowByteOffsets)
Definition at line 142 of file SipperImage.cpp.
References ImageExtractionManager::LogicalFrameBlob::ColLeft(), ImageExtractionManager::LogicalFrameBlob::ColRight(), KKB::Raster::Green(), ImageExtractionManager::LogicalFrameBlob::Id(), ImageExtractionManager::LogicalFrameBlob::RowBot(), and ImageExtractionManager::LogicalFrameBlob::RowTop().
Referenced by ImageExtractionManager::LogicalFrame::ProcessFrame().
kkuint32 ImageExtractionManager::SipperImage::Height () const inline
Definition at line 33 of file SipperImage.h.
Referenced by ImageExtractionManager::LogicalFrame::MemoryConsumedEstimated().
kkuint32 ImageExtractionManager::SipperImage::PixelCount () const inline
Definition at line 28 of file SipperImage.h.
Referenced by ImageExtractionManager::LogicalFrame::MemoryConsumedEstimated(), and ImageExtractionManager::LogicalFrame::ProcessFrame().
kkuint32 ImageExtractionManager::SipperImage::RowBot () const inline
Definition at line 29 of file SipperImage.h.
Referenced by ImageExtractionManager::LogicalFrame::ProcessFrame().
kkuint32 ImageExtractionManager::SipperImage::RowTop () const inline
Definition at line 30 of file SipperImage.h.
Referenced by ImageExtractionManager::LogicalFrame::ProcessFrame().
kkuint32 ImageExtractionManager::SipperImage::Width () const inline
Definition at line 32 of file SipperImage.h.
Referenced by ImageExtractionManager::LogicalFrame::MemoryConsumedEstimated().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/ImageExtractionManager/SipperImage.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/ImageExtractionManager/SipperImage.cpp