Pices: PicesInterface::PicesPointList Class Reference
PicesInterface::PicesPointList Class Reference
#include <PicesPoint.h>
Public Member Functions
PicesPointList ()
summary> Construct a list of managed PicesPoint instances from the contents of the unmanaged list 'unmanagedImages'.
PicesPointList (PointListPtr &unmanagedPoints)
PicesPointList (const PointList &unmanagedPoints)
PicesPointList (PicesPointList^ points)
!PicesPointList ()
~PicesPointList ()
void AddList (PicesPointList^ list)
summary> Give ownership of the contents of 'list' to this Managed list.
void AddList (PointListPtr &list)
void CleanUpMemory ()
float ComputeSegmentLens (float heightFactor, float widthFactor)
bool Equal (PicesPointList^ right)
bool NotEqual (PicesPointList^ right)
KKB::PointListPtr ToUnmanaged ()
Detailed Description
Definition at line 54 of file PicesPoint.h.
Constructor & Destructor Documentation
PicesInterface::PicesPointList::PicesPointList ()
summary> Construct a list of managed PicesPoint instances from the contents of the unmanaged list 'unmanagedImages'.
remarks> Will take ownership of the instances of Raster in 'unmanagedImages'. The list will be deleted and the unmanaged code should not try to access any of 'unmanagedImages' contents after this call. /remarks> param name='unmanagedPoints'> List of unmanaged 'PicesPoint' objects; the ownership of these instances will be given over to the new Managed instance of 'PicesPointList'; will be deleted and set to NULL.
Definition at line 107 of file PicesPoint.cpp.
PicesInterface::PicesPointList::PicesPointList (PointListPtr & unmanagedPoints)
Definition at line 125 of file PicesPoint.cpp.
References PicesInterface::PicesPoint::PicesPoint().
PicesInterface::PicesPointList::PicesPointList (const PointList & unmanagedPoints)
Definition at line 112 of file PicesPoint.cpp.
References PicesInterface::PicesPoint::PicesPoint().
PicesInterface::PicesPointList::PicesPointList (PicesPointList^ points)
Definition at line 143 of file PicesPoint.cpp.
PicesInterface::PicesPointList::~PicesPointList ()
Definition at line 154 of file PicesPoint.cpp.
PicesInterface::PicesPointList::!PicesPointList ()
Definition at line 161 of file PicesPoint.cpp.
Member Function Documentation
void PicesInterface::PicesPointList::AddList (PicesPointList^ list)
summary> Give ownership of the contents of 'list' to this Managed list.
remarks> Will take ownership of the unmanaged instances of 'Raster' in 'list'. These instances will be deleted by the ".net" garabage collector so make sure that no unmanaged code makes use of these instances after making this call. /remarks> param name='list'> The list of 'Raster' objects to turn owneship of; will be deleted and be set to NULL; do not make use of any of these instances in the unmanaged code afetr making this call. /param>
Definition at line 172 of file PicesPoint.cpp.
void PicesInterface::PicesPointList::AddList (PointListPtr & list)
Definition at line 182 of file PicesPoint.cpp.
References KKB::KKQueue< Entry >::Owner().
void PicesInterface::PicesPointList::CleanUpMemory ()
Definition at line 167 of file PicesPoint.cpp.
float PicesInterface::PicesPointList::ComputeSegmentLens (float heightFactor, float widthFactor)
Definition at line 210 of file PicesPoint.cpp.
References PicesInterface::PicesPoint::Col, and PicesInterface::PicesPoint::Row.
Referenced by PicesInterface::PicesRaster::ComputeSegmentLens(), and SipperFile.ImageViewer::ImageViewer().
bool PicesInterface::PicesPointList::Equal (PicesPointList^ right)
Definition at line 235 of file PicesPoint.cpp.
References PicesInterface::PicesPoint::NotEqual().
bool PicesInterface::PicesPointList::NotEqual (PicesPointList^ right)
Definition at line 250 of file PicesPoint.cpp.
References PicesInterface::PicesPoint::NotEqual().
Referenced by SipperFile.ImageViewer::ImageViewer().
KKB::PointListPtr PicesInterface::PicesPointList::ToUnmanaged ()
Definition at line 199 of file PicesPoint.cpp.
References PicesInterface::PicesPoint::Col, and PicesInterface::PicesPoint::Row.
Referenced by PicesInterface::PicesDataBaseImage::!PicesDataBaseImage(), and PicesInterface::PicesDataBase::ImagesUpdateImageSize().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesPoint.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesPoint.cpp