Pices: PicesCommander.InstrumentDataByDeploymentProfile Class Reference
PicesCommander.InstrumentDataByDeploymentProfile Class Reference
Public Member Functions
InstrumentDataByDeploymentProfile (String _cruiseName, String _stationName, String _deploymentNum, PicesClass _mlClass)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
bool BackGroundRunning [get]
bool CancelBackGround [get, set]
Detailed Description
Definition at line 25 of file InstrumentDataByDeploymentProfile.cs.
Constructor & Destructor Documentation
PicesCommander.InstrumentDataByDeploymentProfile.InstrumentDataByDeploymentProfile (String _cruiseName, String _stationName, String _deploymentNum, PicesClass _mlClass) inline
Definition at line 56 of file InstrumentDataByDeploymentProfile.cs.
References SipperFile.InstrumentDataList.Add(), PicesInterface::OSservices.AddSlash(), PicesInterface::OSservices.CreateDirectoryPath(), PicesInterface::PicesSipperDeployment.CruiseName, PicesInterface::PicesInstrumentData.CtdDate, PicesInterface::PicesDataBaseServer.DataBaseName, PicesInterface::PicesSipperDeployment.DeploymentNum, PicesInterface::PicesInstrumentData.Depth, PicesInterface::PicesDataBaseServer.Description, PicesInterface::PicesGoalKeeper.EndBlock(), PicesInterface::PicesDataBase.GetGlobalDatabaseManagerNewInstance(), PicesInterface::PicesDataBase.InstrumentDataLoad(), PicesInterface::PicesDataBase.LastErrorDesc(), PicesInterface::PicesClass.Name, PicesInterface::PicesSipperVariables.PicesReportDir(), PicesInterface::PicesDataBase.QueryStatement(), PicesInterface::PicesSipperFile.ScanRate, PicesInterface::PicesDataBase.Server, PicesInterface::PicesDataBase.SipperDeploymentLoad(), PicesInterface::PicesDataBase.SipperFileLoad(), SipperFile.InstrumentDataList.SortByDepth(), PicesInterface::PicesGoalKeeper.StartBlock(), PicesInterface::PicesSipperDeployment.StationName, PicesInterface::PicesKKStr.StrToFloat(), PicesInterface::PicesKKStr.StrToInt(), PicesInterface::PicesSipperVariables.TempDirectory(), PicesInterface::PicesDataBase.ThreadEnd(), PicesInterface::PicesDataBase.ThreadInit(), and PicesInterface::PicesRunLog.Writeln().
Member Function Documentation
override void PicesCommander.InstrumentDataByDeploymentProfile.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file InstrumentDataByDeploymentProfile.Designer.cs.
Property Documentation
bool PicesCommander.InstrumentDataByDeploymentProfile.BackGroundRunning get
Definition at line 41 of file InstrumentDataByDeploymentProfile.cs.
bool PicesCommander.InstrumentDataByDeploymentProfile.CancelBackGround get set
Definition at line 40 of file InstrumentDataByDeploymentProfile.cs.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/InstrumentDataByDeploymentProfile.cs
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/InstrumentDataByDeploymentProfile.Designer.cs