Pices: MLL::RasterSipper Class Reference
MLL::RasterSipper Class Reference
A class that is used by to represent a single Sipper Image in memory.
#include <RasterSipper.h>
Public Types
typedef RasterSipper * RasterSipperPtr
typedef KKB::uchar uchar
Public Types inherited from KKB::Raster
typedef Raster const RasterConst
typedef Raster const RasterConst
typedef RasterConst * RasterConstPtr
typedef RasterConst * RasterConstPtr
typedef Raster * RasterPtr
typedef Raster * RasterPtr
Public Member Functions
RasterSipper ()
RasterSipper (const RasterSipper &_raster)
Copy Constructor.
RasterSipper (const Raster &_raster)
Copy Constructor.
RasterSipper (kkint32 _height, kkint32 _width)
Constructs a blank GrayScale image with given dimensions; all pixels will be initialized to 0.
RasterSipper (kkint32 _height, kkint32 _width, bool _color)
Constructs a blank image with given dimensions.
RasterSipper (const BmpImage &_bmpImage)
Constructs a RasterSipper from a BMP image loaded from disk.
RasterSipper (const RasterSipper &_raster, kkint32 _row, kkint32 _col, kkint32 _height, kkint32 _width)
Constructs a new RasterSipper using a subset of the specified RasterSipper as its source.
RasterSipper (const RasterSipper &_raster, MaskTypes _mask, kkint32 _row, kkint32 _col)
Constructs a RasterSipper that will be the same size as the specified '_mask' with the top left specified by '_row' and '_col'.
RasterSipper (const KKStr &fileName, bool &validFile)
Constructs a RasterSipper image from by reading an existing image File such as a BMP file.
RasterSipper (kkint32 _height, kkint32 _width, uchar *_grayScaleData, uchar **_grayScaleRows)
Construct a raster object that will utilize a image already in memory.
RasterSipper (kkint32 _height, kkint32 _width, const uchar *_grayScaleData)
Construct a Gray-scale RasterSipper object using provided raw data,.
RasterSipper (kkint32 _height, kkint32 _width, const uchar *_redChannel, const uchar *_greenChannel, const uchar *_blueChannel)
Construct a Color RasterSipper object using provided raw data,.
virtual ~RasterSipper ()
virtual RasterPtr AllocateARasterInstance (kkint32 height, kkint32 width, bool color) const
virtual RasterPtr AllocateARasterInstance (const Raster &r) const
virtual RasterPtr AllocateARasterInstance (const Raster &_raster, kkint32 _row, kkint32 _col, kkint32 _height, kkint32 _width)
RasterSipperPtr BandPass (float lowerFreqBound, float upperFreqBound, bool retainBackground)
Returns a image that is the result of a BandPass using Fourier Transforms.
RasterSipperPtr BinarizeByThreshold (uchar min, uchar max)
RasterSipperPtr CreateColorImageFromLabels ()
RasterSipperPtr CreateColorWithBlobsLabeldByColor (BlobListPtr blobs)
Only useful if 'ExtractBlobs' was performed on this instance, the returned image will be color with each blob labeled a different color.
RasterSipperPtr CreateDilatedRaster () const
RasterSipperPtr CreateDilatedRaster (MaskTypes mask) const
RasterSipperPtr CreateErodedImage (MaskTypes mask) const
RasterSipperPtr CreateFromOrginalImageWithSpecifidBlobsOnly (RasterSipperPtr origImage, BlobListPtr blobs)
Returns a copy of 'origImage' where only the blobs specified in 'blobs' are copied over.
RasterSipperPtr CreateGaussianSmoothedImage (float sigma) const
RasterSipperPtr CreateGrayScale () const
RasterSipperPtr CreateGrayScaleKLT () const
Creates a gray-scale image using a KLT Transform with the goal of weighting in favor the color channels with greatest amount of variance.
RasterSipperPtr CreateGrayScaleKLTOnMaskedArea (const RasterSipper &mask) const
Same as 'CreateGrayScaleKLT' except it will only take into account pixels specified by the 'mask' image.
RasterSipperPtr CreateSmoothedMediumImage (kkint32 maskSize) const
RasterSipperPtr CreateSmoothImage (kkint32 maskSize=3) const
PointListPtr DeriveImageLength () const
RasterSipperPtr ExtractABlob (const BlobPtr blob) const
Extracts a specified blob from this image; useful to extract individual detected blobs.
RasterSipperPtr ExtractABlobTightly (const BlobPtr blob, kkint32 padding) const
Extracts a specified blob from this image into a tightly bounded image.
RasterSipperPtr ExtractChannel (ColorChannels channel)
Will return a gray-scale image consisting of the specified color channel only.
RasterSipperPtr FastFourier () const
RasterSipperPtr FastFourierKK () const
RasterSipperPtr HalfSize ()
RasterSipperPtr HistogramEqualizedImage () const
RasterSipperPtr HistogramEqualizedImage (HistogramPtr equalizedHistogram) const
RasterSipperPtr HistogramGrayscaleImage () const
RasterSipperPtr HistogramImage (ColorChannels channel) const
kkint32 MemoryConsumedEstimated () const
RasterSipperPtr Padded (kkint32 padding)
RasterSipperPtr ReduceByEvenMultiple (kkint32 multiple) const
RasterSipperPtr ReduceByFactor (float factor) const
RasterSipperPtr RemoveZooscanBrackets () const
RasterSipperPtr ReversedImage ()
RasterSipperPtr Rotate (float turnAngle)
RasterSipperPtr SegmentImage (bool save=false)
uchar * SimpleCompression (kkuint32 &buffLen) const
RasterSipperPtr SobelEdgeDetector ()
RasterSipperListPtr SplitImageIntoEqualParts (kkint32 numColSplits, kkint32 numRowSplits) const
RasterSipperPtr SwapQuadrants () const
RasterSipperPtr ThinContour ()
RasterSipperPtr ThresholdInHSI (float thresholdH, float thresholdS, float thresholdI, float distance, const PixelValue &flagValue)
Thresholds image in HSI space.
RasterSipperPtr TightlyBounded (kkuint32 borderPixels) const
RasterSipperPtr ToColor () const
Public Member Functions inherited from KKB::Raster
Raster ()
Raster (const Raster &_raster)
Copy Constructor.
Raster ()
Raster (const Raster &_raster)
Copy Constructor.
Raster (kkint32 _height, kkint32 _width)
Constructs a blank image with given dimensions; all pixels will be initialized to 0.
Raster (kkint32 _height, kkint32 _width)
Constructs a blank GrayScale image with given dimensions; all pixels will be initialized to 0.
Raster (kkint32 _height, kkint32 _width, bool _color)
Constructs a blank image with given dimensions.
Raster (kkint32 _height, kkint32 _width, bool _color)
Constructs a blank image with given dimensions.
Raster (const BmpImage &_bmpImage)
Constructs a Raster from a BMP image loaded from disk.
Raster (const BmpImage &_bmpImage)
Constructs a Raster from a BMP image loaded from disk.
Raster (const Raster &_raster, kkint32 _row, kkint32 _col, kkint32 _height, kkint32 _width)
Constructs a new Raster using a subset of the specified Raster as its source.
Raster (const Raster &_raster, kkint32 _row, kkint32 _col, kkint32 _height, kkint32 _width)
Constructs a new Raster using a subset of the specified Raster as its source.
Raster (const Raster &_raster, MaskTypes _mask, kkint32 _row, kkint32 _col)
Constructs a Raster that will be the same size as the specified '_mask' with the top left specified by '_row' and '_col'.
Raster (const Raster &_raster, MaskTypes _mask, kkint32 _row, kkint32 _col)
Constructs a Raster that will be the same size as the specified '_mask' with the top left specified by '_row' and '_col'.
Raster (const KKStr &fileName, bool &validFile)
Constructs a Raster image from by reading an existing image File such as a BMP file.
Raster (const KKStr &fileName, bool &validFile)
Constructs a Raster image from by reading an existing image File such as a BMP file.
Raster (kkint32 _height, kkint32 _width, uchar *_Data, uchar **_Rows)
Construct a raster object that will utilize a image already in memory.
Raster (kkint32 _height, kkint32 _width, uchar *_grayScaleData, uchar **_grayScaleRows)
Construct a raster object that will utilize a image already in memory.
Raster (kkint32 _height, kkint32 _width, const uchar *_Data)
Construct a Raster object using provided raw data.
Raster (kkint32 _height, kkint32 _width, const uchar *_grayScaleData)
Construct a Grayscale Raster object using provided raw data.
Raster (kkint32 _height, kkint32 _width, const uchar *_redChannel, const uchar *_greenChannel, const uchar *_blueChannel)
Construct a Color Raster object using provided raw data,.
Raster (kkint32 _height, kkint32 _width, const uchar *_redChannel, const uchar *_greenChannel, const uchar *_blueChannel)
Construct a Color Raster object using provided raw data,.
virtual ~Raster ()
virtual ~Raster ()
virtual RasterPtr AllocateARasterInstance (const Raster &_raster, kkint32 _row, kkint32 _col, kkint32 _height, kkint32 _width) const
virtual RasterPtr AllocateARasterInstance (const Raster &_raster, kkint32 _row, kkint32 _col, kkint32 _height, kkint32 _width) const
bool AreThereEdgePixels (kkint32 edgeWidth)
returns true if there are any foreground pixels within 'edgeWidth' pixels of the top, bottom, left, or right edges of the image.
bool AreThereEdgePixels (kkint32 edgeWidth)
returns true if there are any forground pixels within 'edgeWidth' pixels of the top, bottom, left, or right edges of the image.
bool BackgroundPixel (kkint32 row, kkint32 col) const
bool BackgroundPixel (kkint32 row, kkint32 col) const
uchar BackgroundPixelTH () const
uchar BackgroundPixelTH () const
void BackgroundPixelTH (uchar _backgroundPixelTH)
void BackgroundPixelTH (uchar _backgroundPixelTH)
uchar BackgroundPixelValue () const
uchar BackgroundPixelValue () const
void BackgroundPixelValue (uchar _backgroundPixelValue)
void BackgroundPixelValue (uchar _backgroundPixelValue)
RasterPtr BandPass (float lowerFreqBound, float upperFreqBound, bool retainBackground)
Returns a image that is the result of a BandPass using Fourier Transforms.
RasterPtr BandPass (float lowerFreqBound, float upperFreqBound, bool retainBackground)
Returns a image that is the result of a BandPass using Fourier Transforms.
RasterPtr BinarizeByThreshold (uchar min, uchar max) const
RasterPtr BinarizeByThreshold (uchar min, uchar max) const
kkint32 BlobId (kkint32 row, kkint32 col) const
Return the ID of the blob that the specified pixel location belongs to.
kkint32 BlobId (kkint32 row, kkint32 col) const
Return the ID of the blob that the specified pixel location belongs to.
uchar ** Blue () const
returns a pointer to two dimensional array for 'Blue' color channel.
uchar ** Blue () const
returns a pointer to two dimensional array for 'Blue' color channel.
uchar * BlueArea () const
uchar * BlueArea () const
kkint32 CalcArea ()
kkint32 CalcArea ()
void CalcAreaAndIntensityFeatures (kkint32 &area, float &weightedSize, kkuint32 intensityHistBuckets[8], kkint32 &areaWithWhiteSpace, kkuint32 intensityHistBucketsWhiteSpace[8]) const
Calculates both Intensity Histograms, one not including internal background pixels and one with plus size and weighted size.
void CalcAreaAndIntensityFeatures (kkint32 &area, float &weightedSize, kkuint32 intensityHistBuckets[8], kkint32 &areaWithWhiteSpace, kkuint32 intensityHistBucketsWhiteSpace[8]) const
Calculates both Intensity Histograms, one not including internal background pixels and one with plus size and weighted size.
void CalcAreaAndIntensityFeatures (kkint32 &area, float &weightedSize, kkuint32 intensityHistBuckets[8]) const
Calculates both Intensity Histograms, one not including internal background pixels and one with plus size and weighted size.
void CalcAreaAndIntensityFeatures (kkint32 &area, float &weightedSize, kkuint32 intensityHistBuckets[8]) const
Calculates both Intensity Histograms, one not including internal background pixels and one with plus size and weighted size.
void CalcAreaAndIntensityFeatures16 (kkint32 &area, float &weighedSize, kkuint32 intensityHistBuckets[16])
void CalcAreaAndIntensityFeatures16 (kkint32 &area, float &weighedSize, kkuint32 intensityHistBuckets[16])
void CalcAreaAndIntensityHistogram (kkint32 &area, kkuint32 intensityHistBuckets[8]) const
Calculates the occurrence of different intensity levels.
void CalcAreaAndIntensityHistogram (kkint32 &area, kkuint32 intensityHistBuckets[8]) const
Calculates the occurrence of different intensity levels.
void CalcAreaAndIntensityHistogramWhite (kkint32 &area, kkuint32 intensityHistBuckets[8])
Calculates a Intensity Histogram including Background pixels in the image.
void CalcAreaAndIntensityHistogramWhite (kkint32 &area, kkuint32 intensityHistBuckets[8])
Calculates a Intensity Histogram including Background pixels in the image.
void CalcCentroid (kkint32 &size, kkint32 &weight, float &rowCenter, float &colCenter, float &rowCenterWeighted, float &colCenterWeighted) const
void CalcCentroid (kkint32 &size, kkint32 &weight, float &rowCenter, float &colCenter, float &rowCenterWeighted, float &colCenterWeighted)
void CalcOrientationAndEigerRatio (float &eigenRatio, float &orientationAngle)
void CalcOrientationAndEigerRatio (float &eigenRatio, float &orientationAngle)
float CalcWeightedArea () const
float CalcWeightedArea () const
double CenMoment (kkint32 colMoment, kkint32 rowMoment, double centerCol, double centerRow) const
double CenMoment (kkint32 colMoment, kkint32 rowMoment, double centerCol, double centerRow) const
float CenMomentWeighted (kkint32 p, kkint32 q, float ew, float eh) const
float CenMomentWeighted (kkint32 p, kkint32 q, float ew, float eh) const
void CentralMoments (float features[9]) const
returns in 'features' the 8 central moments as defined by Hu plus eccentricity in the eight bucket.
void CentralMoments (float features[9]) const
void CentralMomentsWeighted (float features[9]) const
Similar to 'CentralMoments' except each pixel position is weighted by its intensity value.
void CentralMomentsWeighted (float features[9]) const
float CentroidCol () const
float CentroidCol () const
float CentroidRow () const
float CentroidRow () const
void Closing ()
void Closing (MaskTypes mask)
void Closing ()
void Closing (MaskTypes mask)
bool Color () const
bool Color () const
void ComputeCentralMoments (kkint32 &foregroundPixelCount, float &weightedPixelCount, float centralMoments[9], float centralMomentsWeighted[9]) const
Computes central moments; one set where each pixel is treated as 1 or 0(Foreground/Background) and the other where each pixel is weighted by intensity value.
void ComputeCentralMoments (kkint32 &foregroundPixelCount, float &weightedPixelCount, float centralMoments[9], float centralMomentsWeighted[9]) const
Computes central moments; one set where each pixel is treated as 1 or 0(Forground/Background) and the other where each pixel is weighted by intensity value.
void ConnectedComponent (uchar connectedComponentDist)
void ConnectedComponent (uchar connectedComponentDist)
void ConnectedComponent8Conected ()
void ConnectedComponent8Conected ()
void ConnectedComponentOrig ()
RasterPtr CreateColor () const
RasterPtr CreateColor () const
RasterPtr CreateColorImageFromLabels ()
Produces a color image using the 'greenArea' channel, assuming that each unique value will be assigned a unique color.
RasterPtr CreateColorImageFromLabels ()
Produces a color image using the 'greenArea' channel, assuming that each unique value will be assigned a unique color.
RasterPtr CreateColorWithBlobsLabeldByColor (BlobListPtr blobs)
Returns image where each blob is labeled with a different color.
RasterPtr CreateColorWithBlobsLabeldByColor (BlobListPtr blobs)
Returns image where each blob is labeled with a different color.
RasterPtr CreateDialatedRaster () const
RasterPtr CreateDialatedRaster (MaskTypes mask) const
RasterPtr CreateDilatedRaster () const
RasterPtr CreateDilatedRaster (MaskTypes mask) const
RasterPtr CreateErodedImage (MaskTypes mask) const
RasterPtr CreateErodedImage (MaskTypes mask) const
RasterPtr CreateFromOrginalImageWithSpecifidBlobsOnly (RasterPtr origImage, BlobListPtr blobs)
Returns a copy of 'origImage' where only the blobs specified in 'blobs' are copied over.
RasterPtr CreateFromOrginalImageWithSpecifidBlobsOnly (RasterPtr origImage, BlobListPtr blobs)
Returns a copy of 'origImage' where only the blobs specified in 'blobs' are copied over.
RasterPtr CreateGaussianSmoothedImage (float sigma) const
RasterPtr CreateGaussianSmoothedImage (float sigma) const
RasterPtr CreateGrayScale () const
RasterPtr CreateGrayScale () const
RasterPtr CreateGrayScaleKLT () const
Creates a grayscale image using a KLT Transform with the goal of weighting in favor the color channels with greatest amount of variance.
RasterPtr CreateGrayScaleKLT () const
Creates a image using a KLT Transform with the goal of weighting in favor the color channels with greatest amount of variance.
RasterPtr CreateGrayScaleKLTOnMaskedArea (const Raster &mask) const
Same as 'CreateGrayScaleKLT' except it will only take into account pixels specified by the 'mask' image.
RasterPtr CreateGrayScaleKLTOnMaskedArea (const Raster &mask) const
Same as 'CreateKLT' except it will only take into account pixels specified by the 'mask' image.
RasterPtr CreateSmoothedMediumImage (kkint32 maskSize) const
RasterPtr CreateSmoothedMediumImage (kkint32 maskSize) const
RasterPtr CreateSmoothImage (kkint32 maskSize=3) const
RasterPtr CreateSmoothImage (kkint32 maskSize=3) const
PointListPtr DeriveImageLength () const
PointListPtr DeriveImageLength () const
void Dialation ()
void Dialation (RasterPtr dest) const
void Dialation (RasterPtr dest, MaskTypes mask) const
void Dialation (MaskTypes mask)
void Dilation ()
void Dilation (RasterPtr dest) const
void Dilation (MaskTypes mask)
void Dilation (RasterPtr dest, MaskTypes mask) const
void Dilation (MorphOp::StructureType _structure, kkuint16 _structureSize, kkint32 _foregroundCountTH)
kkint32 Divisor () const
kkint32 Divisor () const
void Divisor (kkint32 _divisor)
void Divisor (kkint32 _divisor)
void DrawCircle (const Point &point, kkint32 radius, const PixelValue &color)
Draw a circle who's center is at 'point' and radius in pixels is 'radius'using color 'color'.
void DrawCircle (const Point &point, kkint32 radius, const PixelValue &color)
Draw a circle who's center is at 'point' and radius in pixels is 'radius' using color 'color'.
void DrawCircle (float centerRow, float centerCol, float radius, const PixelValue &pixelValue)
void DrawCircle (float centerRow, float centerCol, float radius, const PixelValue &pixelValue)
void DrawCircle (float centerRow, float centerCol, float radius, float startAngle, float endAngle, const PixelValue &pixelValue)
void DrawCircle (float centerRow, float centerCol, float radius, float startAngle, float endAngle, const PixelValue &pixelValue)
void DrawConnectedPointList (Point offset, const PointList &borderPixs, const PixelValue &pixelValue, const PixelValue &linePixelValue)
void DrawConnectedPointList (Point offset, const PointList &borderPixs, const PixelValue &pixelValue, const PixelValue &linePixelValue)
void DrawDot (const Point &point, const PixelValue &color, kkint32 size)
void DrawDot (const Point &point, const PixelValue &color, kkint32 size)
void DrawFatLine (Point startPoint, Point endPoint, PixelValue pv, float alpha)
void DrawFatLine (Point startPoint, Point endPoint, PixelValue pv, float alpha)
void DrawGrid (float pixelsPerMinor, kkuint32 minorsPerMajor, const PixelValue &hashColor, const PixelValue &gridColor)
void DrawGrid (float pixelsPerMinor, kkuint32 minorsPerMajor, const PixelValue &hashColor, const PixelValue &gridColor)
void DrawLine (kkint32 bpRow, kkint32 bpCol, kkint32 epRow, kkint32 epCol)
void DrawLine (kkint32 bpRow, kkint32 bpCol, kkint32 epRow, kkint32 epCol)
void DrawLine (kkint32 bpRow, kkint32 bpCol, kkint32 epRow, kkint32 epCol, uchar pixelVal)
void DrawLine (kkint32 bpRow, kkint32 bpCol, kkint32 epRow, kkint32 epCol, uchar pixelVal)
void DrawLine (const Point &beginPoint, const Point &endPoint, uchar pixelVal)
void DrawLine (const Point &beginPoint, const Point &endPoint, uchar pixelVal)
void DrawLine (const Point &beginPoint, const Point &endPoint, const PixelValue &pixelVal)
void DrawLine (const Point &beginPoint, const Point &endPoint, const PixelValue &pixelVal)
void DrawLine (kkint32 bpRow, kkint32 bpCol, kkint32 epRow, kkint32 epCol, uchar r, uchar g, uchar b)
void DrawLine (kkint32 bpRow, kkint32 bpCol, kkint32 epRow, kkint32 epCol, uchar r, uchar g, uchar b)
void DrawLine (kkint32 bpRow, kkint32 bpCol, kkint32 epRow, kkint32 epCol, uchar r, uchar g, uchar b, float alpha)
void DrawLine (kkint32 bpRow, kkint32 bpCol, kkint32 epRow, kkint32 epCol, uchar r, uchar g, uchar b, float alpha)
void DrawLine (kkint32 bpRow, kkint32 bpCol, kkint32 epRow, kkint32 epCol, PixelValue pixelVal)
void DrawLine (kkint32 bpRow, kkint32 bpCol, kkint32 epRow, kkint32 epCol, PixelValue pixelVal)
void DrawLine (kkint32 bpRow, kkint32 bpCol, kkint32 epRow, kkint32 epCol, PixelValue pixelVal, float alpha)
void DrawLine (kkint32 bpRow, kkint32 bpCol, kkint32 epRow, kkint32 epCol, PixelValue pixelVal, float alpha)
void DrawPointList (const PointList &borderPixs, const PixelValue &pixelValue)
void DrawPointList (const PointList &borderPixs, const PixelValue &pixelValue)
void DrawPointList (Point offset, const PointList &borderPixs, const PixelValue &pixelValue)
void DrawPointList (Point offset, const PointList &borderPixs, const PixelValue &pixelValue)
void DrawPointList (const PointList &borderPixs, uchar redVal, uchar greenVal, uchar blueVal)
void DrawPointList (const PointList &borderPixs, uchar redVal, uchar greenVal, uchar blueVal)
void DrawPointList (Point offset, const PointList &borderPixs, uchar redVal, uchar greenVal, uchar blueVal)
void DrawPointList (Point offset, const PointList &borderPixs, uchar redVal, uchar greenVal, uchar blueVal)
void Edge ()
reduces image to edge pixels only.
void Edge (RasterPtr dest)
void Edge ()
reduces image to edge pixels only.
void Edge (RasterPtr dest)
void ErodeSpurs ()
removes spurs from image.
void ErodeSpurs ()
removes spurs from image.
void Erosion ()
void Erosion (MaskTypes mask)
void Erosion ()
void Erosion (MaskTypes mask)
void Erosion (MorphOp::StructureType _structure, kkuint16 _structureSize, kkint32 _backgroundCountTH)
void Erosion (RasterPtr dest) const
Place into destination a eroded version of this instances image.
void Erosion (RasterPtr dest, MaskTypes mask) const
void Erosion (RasterPtr dest) const
Place into destination a eroded version of this instances image.
void Erosion (RasterPtr dest, MaskTypes mask) const
void ErosionBoundary (MaskTypes mask, kkint32 blobrowstart, kkint32 blobrowend, kkint32 blobcolstart, kkint32 blobcolend)
void ErosionChanged (MaskTypes mask, kkint32 row, kkint32 col)
void ErosionChanged1 (MaskTypes mask, kkint32 row, kkint32 col)
RasterPtr ExtractABlob (const BlobPtr blob) const
Extracts a specified blob from this image; useful to extract individual detected blobs.
RasterPtr ExtractABlob (const BlobPtr blob) const
Extracts a specified blob from this image; useful to extract individual detected blobs.
RasterPtr ExtractABlobTightly (const BlobPtr blob, kkint32 padding) const
Extracts a specified blob from this image into a tightly bounded image.
RasterPtr ExtractABlobTightly (const BlobPtr blob, kkint32 padding) const
Extracts a specified blob from this image into a tightly bounded image.
BlobListPtr ExtractBlobs (kkint32 dist)
Will extract a list of connected components from this instance.
BlobListPtr ExtractBlobs (kkint32 dist)
Will extract a list of connected components from this instance.
RasterPtr ExtractChannel (ColorChannels channel)
Will return a grayscale image consisting of the specified color channel only.
RasterPtr ExtractChannel (ColorChannels channel)
Will return a gray-scale image consisting of the specified color channel only.
RasterPtr ExtractUsingMask (RasterPtr mask)
Extracts the pixel locations where the 'mask' images pixel location is a forground pixel.
RasterPtr ExtractUsingMask (RasterPtr mask)
Extracts the pixel locations where the 'mask' images pixel location is a foreground pixel.
RasterPtr FastFourier () const
RasterPtr FastFourier () const
RasterPtr FastFourierKK () const
RasterPtr FastFourierKK () const
const KKStr & FileName () const
const KKStr & FileName () const
void FileName (const KKStr &_fileName)
void FileName (const KKStr &_fileName)
void FillBlob (RasterPtr origImage, BlobPtr blob, PixelValue color)
Will paint the specified blob with the specified color.
void FillBlob (RasterPtr origImage, BlobPtr blob, PixelValue color)
Will paint the specified blob with the specified color.
void FillHole ()
void FillHole ()
void FillHole (RasterPtr mask)
Fills holes in the image using the 'mask' raster as a work area.
void FillHole (RasterPtr mask)
Fills holes in the image using the 'mask' raster as a work area.
void FillRectangle (kkint32 tlRow, kkint32 tlCol, kkint32 brRow, kkint32 brCol, const PixelValue &fillColor)
void FillRectangle (kkint32 tlRow, kkint32 tlCol, kkint32 brRow, kkint32 brCol, const PixelValue &fillColor)
void FindBoundingBox (kkint32 &tlRow, kkint32 &tlCol, kkint32 &brRow, kkint32 &brCol) const
void FindBoundingBox (kkint32 &tlRow, kkint32 &tlCol, kkint32 &brRow, kkint32 &brCol) const
RasterPtr FindMagnitudeDifferences (const Raster &r)
Returns an image that reflects the differences between this image and the image supplied in the parameter.
RasterPtr FindMagnitudeDifferences (const Raster &r)
Returns an image that reflects the differences between this image and the image supplied in the parameter.
void FollowContour (float countourFreq[5]) const
void FollowContour (float countourFreq[5]) const
bool ForegroundPixel (kkint32 row, kkint32 col) const
bool ForegroundPixel (kkint32 row, kkint32 col) const
kkint32 ForegroundPixelCount () const
kkint32 ForegroundPixelCount () const
void ForegroundPixelCount (kkint32 _foregroundPixelCount)
void ForegroundPixelCount (kkint32 _foregroundPixelCount)
uchar ForegroundPixelValue () const
uchar ForegroundPixelValue () const
void ForegroundPixelValue (uchar _foregroundPixelValue)
void ForegroundPixelValue (uchar _foregroundPixelValue)
void FourierExtractFeatures (float fourierFeatures[5]) const
void FourierExtractFeatures (float fourierFeatures[5]) const
float * FourierMagArea () const
float * FourierMagArea () const
uchar GetPixelValue (kkint32 row, kkint32 col) const
void GetPixelValue (kkint32 row, kkint32 col, uchar &r, uchar &g, uchar &b) const
uchar GetPixelValue (kkint32 row, kkint32 col) const
void GetPixelValue (kkint32 row, kkint32 col, uchar &r, uchar &g, uchar &b) const
void GetPixelValue (kkint32 row, kkint32 col, PixelValue &p) const
void GetPixelValue (kkint32 row, kkint32 col, PixelValue &p) const
uchar GetPixelValue (ColorChannels channel, kkint32 row, kkint32 col) const
uchar GetPixelValue (ColorChannels channel, kkint32 row, kkint32 col) const
uchar ** GetSubSet (uchar **_src, kkint32 _row, kkint32 _col, kkint32 _height, kkint32 _width) const
uchar ** GetSubSet (uchar **_src, kkint32 _row, kkint32 _col, kkint32 _height, kkint32 _width) const
Returns back a two dimension array that is a copy of the specified region in the image.
uchar ** Green () const
returns a pointer to two dimensional array for 'Green' color channel; note this is the same as 'Rows'.
uchar ** Green () const
returns a pointer to two dimensional array for 'Green' color channel; note this is the same as 'Rows'.
uchar * GreenArea () const
uchar * GreenArea () const
RasterPtr HalfSize ()
RasterPtr HalfSize ()
kkint32 Height () const
kkint32 Height () const
HistogramPtr Histogram (ColorChannels channel) const
HistogramPtr Histogram (ColorChannels channel) const
RasterPtr HistogramEqualizedImage () const
RasterPtr HistogramEqualizedImage (HistogramPtr equalizedHistogram) const
RasterPtr HistogramEqualizedImage () const
RasterPtr HistogramEqualizedImage (HistogramPtr equalizedHistogram) const
HistogramPtr HistogramGrayscale () const
HistogramPtr HistogramGrayscale () const
RasterPtr HistogramGrayscaleImage () const
RasterPtr HistogramGrayscaleImage () const
RasterPtr HistogramImage (ColorChannels channel) const
RasterPtr HistogramImage (ColorChannels channel) const
void Initialize (kkint32 _height, kkint32 _width, uchar *_Data, uchar **_Rows, bool _takeOwnership)
Sets an existing instance to specific Raster Data of a image.
void Initialize (kkint32 _height, kkint32 _width, uchar *_grayScaleData, uchar **_grayScaleRows, bool _takeOwnership)
Sets an existing instance to specific Raster Data of a grayscale image.
void Initialize (kkint32 _height, kkint32 _width, uchar *_redArea, uchar **_red, uchar *_greenArea, uchar **_green, uchar *_blueArea, uchar **_blue, bool _takeOwnership)
Sets an existing instance to specific Raster Data of a image.
void Initialize (kkint32 _height, kkint32 _width, uchar *_redArea, uchar **_red, uchar *_greenArea, uchar **_green, uchar *_blueArea, uchar **_blue, bool _takeOwnership)
Sets an existing instance to specific Raster Data of a grayscale image.
uchar MaxPixVal () const
The maximum pixel value encountered in the image.
uchar MaxPixVal () const
The maximum grayscale pixel value encountered in the image.
void MaxPixVal (uchar _maxPixVal)
void MaxPixVal (uchar _maxPixVal)
kkint32 MemoryConsumedEstimated () const
kkint32 MemoryConsumedEstimated () const
void Opening ()
void Opening (MaskTypes mask)
void Opening ()
void Opening (MaskTypes mask)
RasterPtr Padded (kkint32 padding)
RasterPtr Padded (kkint32 padding)
void PaintFatPoint (kkint32 row, kkint32 col, const PixelValue pv, float alpha)
void PaintFatPoint (kkint32 row, kkint32 col, const PixelValue pv, float alpha)
void PaintPoint (kkint32 row, kkint32 col, const PixelValue &pv, float alpha)
void PaintPoint (kkint32 row, kkint32 col, const PixelValue &pv, float alpha)
uchar ** Red () const
returns a pointer to two dimensional array for 'Red' color channel.
uchar ** Red () const
returns a pointer to two dimensional array for 'Red' color channel.
uchar * RedArea () const
uchar * RedArea () const
RasterPtr ReduceByEvenMultiple (kkint32 multiple) const
RasterPtr ReduceByEvenMultiple (kkint32 multiple) const
RasterPtr ReduceByFactor (float factor) const
RasterPtr ReduceByFactor (float factor) const
void ReduceToMostCompleteBlob (uchar connectedComponentDist)
Locates most complete blob; that is the one with the largest (Height x Width); and removes all other images from the blob.
void ReduceToMostCompleteBlob (uchar connectedComponentDist)
Locates most complete blob; that is the one with the largest (Height x Width); and removes all other images from the blob.
void ReSize (kkint32 _height, kkint32 _width, bool _color)
Lets you resize the raster dimensions; old image data will be lost.
void ReSize (kkint32 _height, kkint32 _width, bool _color)
Lets you resize the raster dimensions; old image data wil be lost.
RasterPtr ReversedImage ()
RasterPtr ReversedImage ()
void ReverseImage ()
void ReverseImage ()
RasterPtr Rotate (float turnAngle)
RasterPtr Rotate (float turnAngle)
Point RotateDerivePreRotatedPoint (kkint32 height, kkint32 width, Point &rotatedPoint, float turnAngle) const
Point RotateDerivePreRotatedPoint (kkint32 height, kkint32 width, Point &rotatedPoint, float turnAngle) const
uchar ** Rows () const
returns a pointer to a 2D array that allows the caller to access the raster data by row and column.
uchar ** Rows () const
returns a pointer to a 2D array that allows the caller to access the raster data by row and column.
RasterPtr SegmentImage (bool save=false)
RasterPtr SegmentImage (bool save=false)
void SetPixelValue (const Point &point, const PixelValue &pixVal)
void SetPixelValue (kkint32 row, kkint32 col, uchar pixVal)
void SetPixelValue (const Point &point, const PixelValue &pixVal)
void SetPixelValue (kkint32 row, kkint32 col, uchar pixVal)
void SetPixelValue (kkint32 row, kkint32 col, const PixelValue &pixVal)
void SetPixelValue (kkint32 row, kkint32 col, const PixelValue &pixVal)
void SetPixelValue (kkint32 row, kkint32 col, uchar r, uchar g, uchar b)
void SetPixelValue (kkint32 row, kkint32 col, uchar r, uchar g, uchar b)
void SetPixelValue (ColorChannels channel, kkint32 row, kkint32 col, uchar pixVal)
void SetPixelValue (ColorChannels channel, kkint32 row, kkint32 col, uchar pixVal)
uchar * SimpleCompression (kkuint32 &buffLen) const
Compresses the image in Raster using a simple Run length algorithm and returns a pointer to compressed data.
uchar * SimpleCompression (kkuint32 &buffLen) const
Compresses the image in Raster using a simple Run length algorithm and returns a pointer to compressed data.
RasterPtr SobelEdgeDetector ()
RasterPtr SobelEdgeDetector ()
RasterListPtr SplitImageIntoEqualParts (kkint32 numColSplits, kkint32 numRowSplits) const
RasterListPtr SplitImageIntoEqualParts (kkint32 numColSplits, kkint32 numRowSplits) const
RasterPtr StreatchImage (float rowFactor, float colFactor)
RasterPtr StreatchImage (float rowFactor, float colFactor)
RasterPtr SwapQuadrants () const
RasterPtr SwapQuadrants () const
void TakeOwnershipOfAnotherRastersData (Raster &otherRaster)
Will take ownership of 'otherRaster' raster dynamically allocated data and copy its non dynamically allocated data.
void TakeOwnershipOfAnotherRastersData (Raster &otherRaster)
Will take ownership of 'otherRaster' rasters synamicacly allocated data and copy its non dynanicacly allocated data.
RasterPtr ThinContour () const
RasterPtr ThinContour () const
RasterPtr ThresholdInHSI (float thresholdH, float thresholdS, float thresholdI, float distance, const PixelValue &flagValue)
Thresholds image in HSI space.
RasterPtr ThresholdInHSI (float thresholdH, float thresholdS, float thresholdI, float distance, const PixelValue &flagValue)
Thresholds image in HSI space.
RasterPtr TightlyBounded (kkuint32 borderPixels) const
RasterPtr TightlyBounded (kkuint32 borderPixels) const
const KKStr & Title () const
const KKStr & Title () const
void Title (const KKStr &_title)
void Title (const KKStr &_title)
RasterPtr ToColor () const
RasterPtr ToColor () const
uchar * ToCompressor (kkuint32 &compressedBuffLen) const
Compresses the image in Raster using zlib library and returns a pointer to compressed data.
uchar * ToCompressor (kkuint32 &compressedBuffLen) const
Compresses the image in Raster using zlib library and returns a pointer to compressed data.
kkint32 TotalBackgroundPixels () const
kkint32 TotalBackgroundPixels () const
kkint32 TotPixels () const
The total number of pixels (Height * Width).
kkint32 TotPixels () const
The total number of pixels (Height * Width).
RasterPtr Transpose () const
RasterPtr Transpose () const
void WeOwnRasterData (bool _weOwnRasterData)
void WeOwnRasterData (bool _weOwnRasterData)
void WhiteOutBackground ()
Sets all pixels that are in the Background Range ov values to BackgroundPixelValue.
kkint32 Width () const
kkint32 Width () const
Static Public Member Functions
static float ComputeSegmentLens (const PointListPtr points, float heightFactor, float widthFactor)
static RasterSipperPtr CreatePaddedRaster (BmpImage &image, kkint32 padding)
static RasterSipperPtr FromCompressor (const uchar *compressedBuff, kkuint32 compressedBuffLen)
Creates a new instance of RasterSipper object from zLib compressed data.
static RasterSipperPtr FromSimpleCompression (const uchar *compressedBuff, kkuint32 compressedBuffLen)
Creates a raster from a compressedBuff created by 'SimpleCompression'.
static RasterSipperPtr TurnIntoSipperRasterPtr (RasterPtr &r)
Turn an instance of 'Raster' into 'RasterSipper'.
Static Public Member Functions inherited from KKB::Raster
static MatrixPtr BuildGaussian2dKernel (float sigma)
Builds a 2d Gaussian kernel.
static MatrixPtr BuildGaussian2dKernel (float sigma)
Builds a 2d Gaussian kernel.
static RasterPtr CreatePaddedRaster (BmpImage &image, kkint32 padding)
static RasterPtr CreatePaddedRaster (BmpImage &image, kkint32 padding)
static RasterPtr FromCompressor (const uchar *compressedBuff, kkuint32 compressedBuffLen)
Creates a new instance of Raster object from zLib compressed data.
static RasterPtr FromCompressor (const uchar *compressedBuff, kkuint32 compressedBuffLen)
Creates a new instance of Raster object from zLib compressed data.
static RasterPtr FromSimpleCompression (const uchar *compressedBuff, kkuint32 compressedBuffLen)
Creates a raster from a compressedBuff created by 'SimpleCompression'.
static RasterPtr FromSimpleCompression (const uchar *compressedBuff, kkuint32 compressedBuffLen)
Creates a raster from a compressedBuff created by 'SimpleCompression'.
static void PrintOutListOfAllocatedrasterInstances ()
static void PrintOutListOfAllocatedrasterInstances ()
Additional Inherited Members
Static Protected Member Functions inherited from KKB::Raster
static void AddRasterInstance (const RasterPtr r)
static void AddRasterInstance (const RasterPtr r)
static void FinalCleanUp ()
static void FinaleCleanUp ()
static void Initialize ()
static void Initialize ()
static void RemoveRasterInstance (const RasterPtr r)
static void RemoveRasterInstance (const RasterPtr r)
Protected Attributes inherited from KKB::Raster
uchar backgroundPixelTH
Threshold used to split Background and foreground pixel/.
uchar backgroundPixelValue
kkint32 ** blobIds
Used when searching for connected components.
uchar ** blue
uchar * blueArea
float centroidCol
float centroidRow
bool color
kkint32 divisor
KKStr fileName
kkint32 foregroundPixelCount
uchar foregroundPixelValue
float ** fourierMag
Only used if image is result of a Fourier Transform.
float * fourierMagArea
Only used if image is result of a Fourier Transform.
uchar ** green
uchar * greenArea
kkint32 height
uchar maxPixVal
uchar ** red
uchar * redArea
KKStr title
Title such as 'Class" that can be assigned to an image.
kkint32 totPixels
bool weOwnRasterData
kkint32 width
Static Protected Attributes inherited from KKB::Raster
static std::map< RasterPtr,
RasterPtr > allocatedRasterInstances
Supports the tracking down of memory leaks in Raster; it will be called every time a new instance of a 'Raster' object is created.
static volatile GoalKeeperPtr goalKeeper = NULL
static volatile bool rasterInitialized = false
Detailed Description
A class that is used by to represent a single Sipper Image in memory.
A specialized RasterSipper object for managing Sipper Images.
See Also
Blob
ContourFollower
ConvexHull
PixelValue
Point
PointList
RasterSipperList()
Sobel
Definition at line 51 of file RasterSipper.h.
Member Typedef Documentation
typedef RasterSipper* MLL::RasterSipper::RasterSipperPtr
Definition at line 54 of file RasterSipper.h.
typedef KKB::uchar MLL::RasterSipper::uchar
Definition at line 55 of file RasterSipper.h.
Constructor & Destructor Documentation
RasterSipper::RasterSipper ()
Definition at line 38 of file RasterSipper.cpp.
Referenced by AllocateARasterInstance(), FromCompressor(), FromSimpleCompression(), RemoveZooscanBrackets(), and TurnIntoSipperRasterPtr().
RasterSipper::RasterSipper (const RasterSipper & _raster)
Copy Constructor.
Definition at line 76 of file RasterSipper.cpp.
RasterSipper::RasterSipper (const Raster & _raster)
Copy Constructor.
Definition at line 83 of file RasterSipper.cpp.
RasterSipper::RasterSipper (kkint32 _height, kkint32 _width)
Constructs a blank GrayScale image with given dimensions; all pixels will be initialized to 0.
When working with Gray-scale images pixel value of '0' = Background and '255'= foreground. The green channel will be used to represent the gray-scale value. When these raster images are saved to a image file such as a BMP file the pixel value of 0 will point to the color value of (255, 255, 255) and pixel value 255 will point to the color value of (0, 0, 0). This way when displaying the image background will appear as white.
Definition at line 43 of file RasterSipper.cpp.
RasterSipper::RasterSipper (kkint32 _height, kkint32 _width, bool _color)
Constructs a blank image with given dimensions.
The third parameter determines whether it will be a color or gray-scale image, if a Color image then all three color channel will be set to = 255 which stands for white. If Gray-scale the green channel will be set to 0.
Definition at line 52 of file RasterSipper.cpp.
RasterSipper::RasterSipper (const BmpImage & _bmpImage)
Constructs a RasterSipper from a BMP image loaded from disk.
If BMP Image is a gray-scale value pixel values will be reversed. See description of gray-scale constructor.
If BMP Image is a gray-scale value pixel values will be reversed. See description of gray-scale constructor.
Definition at line 67 of file RasterSipper.cpp.
RasterSipper::RasterSipper (const RasterSipper & _raster, kkint32 _row, kkint32 _col, kkint32 _height, kkint32 _width)
Constructs a new RasterSipper using a subset of the specified RasterSipper as its source.
The dimensions of the resultant raster will be '_height', and '_width'
Parameters
_raster Source RasterSipper
_row Starting Row in '_raster' to copy from.
_col Starting Col in '_raster' to copy from.
_height Height of resultant raster. Will start from '_row'
_width Width of resultant raster.
Definition at line 90 of file RasterSipper.cpp.
RasterSipper::RasterSipper (const RasterSipper & _raster, MaskTypes _mask, kkint32 _row, kkint32 _col)
Constructs a RasterSipper that will be the same size as the specified '_mask' with the top left specified by '_row' and '_col'.
The Height and Width of the resultant image will come from the bias of the specified mask. The Image data will come from the specified raster using '_row' and '_col' to specify the top left column.
Parameters
[in] _raster Source Raster to extract data from.
[in] _mask Used to derive height and with of resultant image.
[in] _row Starting row where image data is to be extracted from.
[in] _col Starting column where image data is to be extracted from.
See Also
KKB::MorphOp::MaskTypes
Definition at line 102 of file RasterSipper.cpp.
RasterSipper::RasterSipper (const KKStr & _fileName, bool & validFile)
Constructs a RasterSipper image from by reading an existing image File such as a BMP file.
Constructs a raster object from a Image File.
Will read from the specified file (fileName) the existing image. If the load fails then the contents of this object will be undefined.
Parameters
[in] fileName Name of Image file to read.
[out] validFile If image successfully loaded will be set to 'True' otherwise 'False'.
If a color image the pixel values will be reversed, see constructor for gray-scale images.
Parameters
_fileName
fileName name of image file to load/
validFile
validFile will return true if image successfully loaded.
Definition at line 118 of file RasterSipper.cpp.
RasterSipper::RasterSipper (kkint32 _height, kkint32 _width, uchar * _grayScaleData, uchar ** _grayScaleRows)
Construct a raster object that will utilize a image already in memory.
This instance will not own the raster data. It will only point to it.
Definition at line 129 of file RasterSipper.cpp.
RasterSipper::RasterSipper (kkint32 _height, kkint32 _width, const uchar * _grayScaleData)
Construct a Gray-scale RasterSipper object using provided raw data,.
Definition at line 141 of file RasterSipper.cpp.
RasterSipper::RasterSipper (kkint32 _height, kkint32 _width, const uchar * _redChannel, const uchar * _greenChannel, const uchar * _blueChannel)
Construct a Color RasterSipper object using provided raw data,.
Definition at line 150 of file RasterSipper.cpp.
RasterSipper::~RasterSipper () virtual
Definition at line 163 of file RasterSipper.cpp.
Member Function Documentation
RasterPtr RasterSipper::AllocateARasterInstance (kkint32 height, kkint32 width, bool color) const virtual
Reimplemented from KKB::Raster.
Definition at line 201 of file RasterSipper.cpp.
References RasterSipper().
RasterPtr RasterSipper::AllocateARasterInstance (const Raster & r) const virtual
Reimplemented from KKB::Raster.
Definition at line 212 of file RasterSipper.cpp.
References RasterSipper().
RasterPtr RasterSipper::AllocateARasterInstance (const Raster & _raster, kkint32 _row, kkint32 _col, kkint32 _height, kkint32 _width) virtual
Parameters
_raster Source Raster
_row Starting Row in '_raster' to copy from.
_col Starting Col in '_raster' to copy from.
_height Height of resultant raster. Will start from '_row'
_width Width of resultant raster.
Definition at line 220 of file RasterSipper.cpp.
References KKB::Raster::Raster(), and TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::BandPass (float lowerFreqBound, float upperFreqBound, bool retainBackground)
Returns a image that is the result of a BandPass using Fourier Transforms.
A 2D Fourier transform is performed. The range specified is from 0.0 to 1.0 where range is determined from the center of the image to the farthest corner where the center is 0.0 and the farthest corner is 1.0. Pixels in the resultant 2D Transform that are "NOT" in the specified range are set to 0.0. A reverse transform is then performed and the resultant image is returned.
Parameters
[in] lowerFreqBound Lower range of frequencies to retain; between 0.0 and 1.0.
[in] upperFreqBound Upper range of frequencies to retain; between 0.0 and 1.0.
[in] retainBackground Indicates whether pixes that don't meet the background-foreground threshold should be included as part of the Fourier transform; if set to false.
Returns
The result image.
Parameters
lowerFreqBound Number's between 0.0 and 1.0
upperFreqBound Represent percentage.
Definition at line 711 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
Referenced by PicesInterface::PicesRaster::BandPass().
RasterSipperPtr RasterSipper::BinarizeByThreshold (uchar min, uchar max)
Definition at line 623 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
Referenced by PicesInterface::PicesRaster::Binarize(), and PicesInterface::PicesRaster::BinarizeByThreshold().
float RasterSipper::ComputeSegmentLens (const PointListPtr points, float heightFactor, float widthFactor) static
Definition at line 633 of file RasterSipper.cpp.
References KKB::PointList::ComputeSegmentLens().
RasterSipperPtr RasterSipper::CreateColorImageFromLabels ()
Definition at line 966 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::CreateColorWithBlobsLabeldByColor (BlobListPtr blobs)
Only useful if 'ExtractBlobs' was performed on this instance, the returned image will be color with each blob labeled a different color.
Returns image where each blob is labeled with a different color.
Only useful if 'ExtractBlobs' was performed on this instance.
Definition at line 284 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::CreateDilatedRaster () const
Definition at line 252 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
Referenced by PicesInterface::PicesRaster::CloseImage(), PicesInterface::PicesRaster::DialateImage(), and PicesInterface::PicesRaster::OpenImage().
RasterSipperPtr RasterSipper::CreateDilatedRaster (MaskTypes mask) const
Definition at line 261 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::CreateErodedImage (MaskTypes mask) const
Definition at line 271 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
Referenced by PicesInterface::PicesRaster::CloseImage(), DeriveImageLength(), PicesInterface::PicesRaster::ErodeImage(), and PicesInterface::PicesRaster::OpenImage().
RasterSipperPtr RasterSipper::CreateFromOrginalImageWithSpecifidBlobsOnly (RasterSipperPtr origImage, BlobListPtr blobs)
Returns a copy of 'origImage' where only the blobs specified in 'blobs' are copied over.
Example:
    origImage = image that we want to segment and get list of discrete blobs from.
    RasterSipperPtr  segmentedImage = origImage->SegmentImage ();
    BlobListPtr  blobs = segmentedImage->ExtractBlobs (1);
    RasterSipperPtr  imageWithBlobOnly = segmentedImage->CreateFromOrginalImageWithSpecifidBlobsOnly (blobs);
Parameters
[in] origImage Image that this instance was derived for, must have same dimensions.
[in] blobs A list of Blob instances that you want copied to the new instance of 'RasterSipper' returned,
Returns
Image consisting of specified blobs only.
Definition at line 292 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::CreateGaussianSmoothedImage (float sigma) const
Definition at line 926 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::CreateGrayScale () const
Definition at line 370 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::CreateGrayScaleKLT () const
Creates a gray-scale image using a KLT Transform with the goal of weighting in favor the color channels with greatest amount of variance.
The idea is to weight each color channel by the amount of variance. This is accomplished by producing a covariance matrix of the three color channels and then taking the Eigen vector with the largest Eigen value and using its components to derive weights for each channel for the conversion from RGB to gray-scale.
Definition at line 949 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::CreateGrayScaleKLTOnMaskedArea (const RasterSipper & mask) const
Same as 'CreateGrayScaleKLT' except it will only take into account pixels specified by the 'mask' image.
Parameters
[in] mask RasterSipper object where pixels that are greater than 'backgroundPixelTH' are to be considered.
Definition at line 958 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::CreatePaddedRaster (BmpImage & image, kkint32 padding) static
Definition at line 233 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::CreateSmoothedMediumImage (kkint32 maskSize) const
Definition at line 427 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
Referenced by PicesInterface::PicesRaster::SmoothMedium().
RasterSipperPtr RasterSipper::CreateSmoothImage (kkint32 maskSize = 3) const
Definition at line 418 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
Referenced by PicesInterface::PicesRaster::SmoothAveraging().
PointListPtr RasterSipper::DeriveImageLength () const
Definition at line 975 of file RasterSipper.cpp.
References KKB::Raster::CalcOrientationAndEigerRatio(), KKB::Raster::ConnectedComponent(), CreateErodedImage(), KKB::Raster::Erosion(), KKB::Raster::FillHole(), KKB::Raster::FindBoundingBox(), KKB::Raster::Green(), KKB::Raster::height, KKB::Max(), KKB::KKQueue< Entry >::PushOnBack(), Rotate(), KKB::Raster::RotateDerivePreRotatedPoint(), TwoPie, and KKB::Raster::width.
Referenced by PicesInterface::PicesRaster::DeriveImageLength().
RasterSipperPtr RasterSipper::ExtractABlob (const BlobPtr blob) const
Extracts a specified blob from this image; useful to extract individual detected blobs.
The 'ExtractBlobs' method needs to have been performed on this instance first. You would use this method after calling 'ExtractBlobs'. The extracted image will be of the same dimensions as the original image except it will extract the pixels that belong to the specified blob only.
// Example of processing extracted blobs
void  ProcessIndividulConectedComponents (RasterSipperPtr  image)
{
  BlobListPtr blobs = image->ExtractBlobs (3);
  BlobList::iterator  idx;
  for  (idx = blobs->begin ();  idx != end ();  ++idx)
  {
    RasterSipperPtr  individuleBlob = image->ExtractABlob (*idx);
    DoSomethingWithIndividuleBlob (individuleBlob);
    delete  individuleBlob;
    individuleBlob = NULL;
  )
  delete  blobs;
  blobs = NULL;
}
Definition at line 318 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::ExtractABlobTightly (const BlobPtr blob, kkint32 padding) const
Extracts a specified blob from this image into a tightly bounded image.
Similar to 'ExtractABlob' except that the returned image will have the dimension necessary to contain the specified blob with the specified number of padded row and columns.
Definition at line 304 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::ExtractChannel (ColorChannels channel)
Will return a gray-scale image consisting of the specified color channel only.
Definition at line 647 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::FastFourier () const
Definition at line 341 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
Referenced by MLL::ImageFeatures::CalcFeatures(), and PicesInterface::PicesRaster::FourierTransform().
RasterSipperPtr RasterSipper::FastFourierKK () const
Definition at line 331 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::FromCompressor (const uchar * compressedBuff, kkuint32 compressedBuffLen) static
Creates a new instance of RasterSipper object from zLib compressed data.
Performs the inverse operation of RasterSipper::ToCompressor.
Parameters
[in] compressedBuff Pointer to buffer area containing compressed data originally created by 'ToCompressor'.
[in] compressedBuffLen Length in bytes of 'compressedBuff'.
Returns
If successful a pointer to a new instance of 'RasterSipper'; if there is an error will return NULL.
See Also
ToCompressor
Definition at line 828 of file RasterSipper.cpp.
References KKB::Raster::BlueArea(), KKB::Raster::blueArea, KKB::Raster::color, KKB::endl(), KKB::Raster::GreenArea(), KKB::Raster::greenArea, KKB::Raster::height, RasterSipper(), KKB::Raster::RedArea(), KKB::Raster::redArea, and KKB::Raster::width.
RasterSipperPtr RasterSipper::FromSimpleCompression (const uchar * compressedBuff, kkuint32 compressedBuffLen) static
Creates a raster from a compressedBuff created by 'SimpleCompression'.
Definition at line 746 of file RasterSipper.cpp.
References KKB::endl(), KKB::Raster::GreenArea(), KKB::Raster::greenArea, KKB::Raster::height, RasterSipper(), and KKB::Raster::width.
Referenced by MLL::DataBaseImage::ThumbNail().
RasterSipperPtr RasterSipper::HalfSize ()
Definition at line 436 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::HistogramEqualizedImage () const
Definition at line 380 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::HistogramEqualizedImage (HistogramPtr equalizedHistogram) const
Definition at line 390 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::HistogramGrayscaleImage () const
Definition at line 400 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::HistogramImage (ColorChannels channel) const
Definition at line 408 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
kkint32 RasterSipper::MemoryConsumedEstimated () const
Definition at line 169 of file RasterSipper.cpp.
Referenced by ImageExtractionManager::ExtractedImage::MemoryConsumedEstimated(), and PicesInterface::PicesRaster::PicesRaster().
RasterSipperPtr RasterSipper::Padded (kkint32 padding)
Definition at line 918 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
Referenced by PicesInterface::PicesRaster::Padded().
RasterSipperPtr RasterSipper::ReduceByEvenMultiple (kkint32 multiple) const
Definition at line 446 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
Referenced by MLL::ImageFeatures::CalcFeatures().
RasterSipperPtr RasterSipper::ReduceByFactor (float factor) const
Definition at line 455 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::RemoveZooscanBrackets () const
Definition at line 521 of file RasterSipper.cpp.
References KKB::Raster::Blue(), KKB::Raster::Color(), KKB::Raster::color, KKB::Raster::Green(), KKB::Raster::green, KKB::Raster::height, RasterSipper(), KKB::Raster::Red(), KKB::Raster::red, and KKB::Raster::width.
Referenced by PicesInterface::PicesRaster::RemoveZooscanBrackets().
RasterSipperPtr RasterSipper::ReversedImage ()
Definition at line 243 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
Referenced by MLL::ImageFeatures::CalcFeatures(), and PicesInterface::PicesRaster::ReversedImage().
RasterSipperPtr RasterSipper::Rotate (float turnAngle)
Definition at line 361 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
Referenced by MLL::ImageFeatures::CalcFeatures(), and DeriveImageLength().
RasterSipperPtr RasterSipper::SegmentImage (bool save = false)
Definition at line 660 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
uchar * RasterSipper::SimpleCompression (kkuint32 & buffLen) const
Definition at line 724 of file RasterSipper.cpp.
References KKB::SimpleCompressor::Add16BitInt(), KKB::SimpleCompressor::AddByte(), and KKB::SimpleCompressor::CreateCompressedBuffer().
RasterSipperPtr RasterSipper::SobelEdgeDetector ()
Definition at line 614 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperListPtr RasterSipper::SplitImageIntoEqualParts (kkint32 numColSplits, kkint32 numRowSplits) const
Definition at line 669 of file RasterSipper.cpp.
References KKB::KKQueue< Entry >::Owner().
RasterSipperPtr RasterSipper::SwapQuadrants () const
Definition at line 350 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::ThinContour ()
Definition at line 686 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
Referenced by MLL::ImageFeatures::CalcFeatures(), and PicesInterface::PicesRaster::Thinning().
RasterSipperPtr RasterSipper::ThresholdInHSI (float thresholdH, float thresholdS, float thresholdI, float distance, const PixelValue & flagValue)
Thresholds image in HSI space.
    Returns an image with only the pixels that are within a specified distance in HSI space to the
    supplied HSI parameters.  All pixels that are not within the specified distance will be set to
    'flagValue'.
Parameters
[in] thresholdH Hue in radians(0.0 <-> 2Pie).
[in] thresholdS Saturation (0.0 <-> 1.0).
[in] thresholdI Intensity (0.0 <-> 1.0).
[in] distance Threshold Distance (0.0 <-> 1.0) that a pixel must be within in HSI space to be included.
[in] flagValue PixelValue to set for pixels that are NOT within 'distance' of threshold.
Returns
A image where pixels that are within the threshold will retain their original pixel values and the ones that are not will be set to 'flagValue'.
Definition at line 935 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::TightlyBounded (kkuint32 borderPixels) const
Definition at line 695 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
RasterSipperPtr RasterSipper::ToColor () const
Definition at line 703 of file RasterSipper.cpp.
References TurnIntoSipperRasterPtr().
Referenced by PicesInterface::PicesRaster::ToColor().
RasterSipperPtr RasterSipper::TurnIntoSipperRasterPtr (RasterPtr & r) static
Turn an instance of 'Raster' into 'RasterSipper'.
Will utilize the dynamically allocated raster data of the 'Raster' instance 'r' to build a new instance of a 'SipperRaster'.If the underlying type of 'r' is a instance of 'RasterSipper' will then return a dynamic_cast<> of the pointer; otherwise will create a new instance of a 'RasterSipper' class and give it ownership of ALL dynamically allocated members of 'r'.
Parameters
[in,out] r The raster data of 'r' will be given to the new instance of 'RasterSipper' and 'r' will then be deleted and set to NULL.
Definition at line 176 of file RasterSipper.cpp.
References RasterSipper(), KKB::Raster::TakeOwnershipOfAnotherRastersData(), and KKB::Raster::WeOwnRasterData().
Referenced by AllocateARasterInstance(), BandPass(), BinarizeByThreshold(), MLL::ImageFeatures::CalcFeatures(), CreateColorImageFromLabels(), CreateColorWithBlobsLabeldByColor(), CreateDilatedRaster(), CreateErodedImage(), CreateFromOrginalImageWithSpecifidBlobsOnly(), CreateGaussianSmoothedImage(), CreateGrayScale(), CreateGrayScaleKLT(), CreateGrayScaleKLTOnMaskedArea(), CreatePaddedRaster(), CreateSmoothedMediumImage(), CreateSmoothImage(), ExtractABlob(), ExtractABlobTightly(), ExtractChannel(), FastFourier(), FastFourierKK(), HalfSize(), HistogramEqualizedImage(), HistogramGrayscaleImage(), HistogramImage(), Padded(), ReduceByEvenMultiple(), ReduceByFactor(), ReversedImage(), Rotate(), SegmentImage(), SobelEdgeDetector(), SwapQuadrants(), ThinContour(), ThresholdInHSI(), TightlyBounded(), and ToColor().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/RasterSipper.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/RasterSipper.cpp