Pices: MLL::SipperCruise Class Reference
MLL::SipperCruise Class Reference
#include <SipperCruise.h>
Public Types
typedef SipperCruise * SipperCruisePtr
Public Member Functions
SipperCruise ()
~SipperCruise ()
const KKStr & CruiseName () const
void CruiseName (const KKStr &_cruiseName)
const DateType & DateEnd () const
void DateEnd (const KKB::DateType &_dateEnd)
const DateType & DateStart () const
void DateStart (const KKB::DateType &_dateStart)
const KKStr & Description () const
void Description (const KKStr &_description)
const KKStr & Location () const
void Location (const KKStr &_location)
const KKStr & Objective () const
void Objective (const KKStr &_objective)
const KKStr & Principal () const
void Principal (const KKStr &_principal)
const KKStr & ResearchOrg () const
void ResearchOrg (const KKStr &_researchOrg)
const KKStr & ShipName () const
void ShipName (const KKStr &_shipName)
Static Public Member Functions
static KKStr ValidateCruiseName (const KKStr &_cruiseName)
Detailed Description
Definition at line 16 of file SipperCruise.h.
Member Typedef Documentation
typedef SipperCruise* MLL::SipperCruise::SipperCruisePtr
Definition at line 19 of file SipperCruise.h.
Constructor & Destructor Documentation
SipperCruise::SipperCruise ()
Definition at line 25 of file SipperCruise.cpp.
SipperCruise::~SipperCruise ()
Definition at line 38 of file SipperCruise.cpp.
Member Function Documentation
const KKStr& MLL::SipperCruise::CruiseName () const inline
Definition at line 25 of file SipperCruise.h.
Referenced by MLL::SipperCruiseList::CruiseNameComparator::operator()(), PicesInterface::PicesSipperStation::PicesSipperStation(), and MLL::DataBase::SipperCruiseInsert().
void MLL::SipperCruise::CruiseName (const KKStr & _cruiseName) inline
Definition at line 35 of file SipperCruise.h.
const DateType& MLL::SipperCruise::DateEnd () const inline
Definition at line 29 of file SipperCruise.h.
Referenced by MLL::DataBase::SipperCruiseInsert(), and MLL::DataBase::SipperCruiseUpdate().
void MLL::SipperCruise::DateEnd (const KKB::DateType & _dateEnd) inline
Definition at line 39 of file SipperCruise.h.
const DateType& MLL::SipperCruise::DateStart () const inline
Definition at line 28 of file SipperCruise.h.
Referenced by MLL::DataBase::SipperCruiseInsert(), and MLL::DataBase::SipperCruiseUpdate().
void MLL::SipperCruise::DateStart (const KKB::DateType & _dateStart) inline
Definition at line 38 of file SipperCruise.h.
const KKStr& MLL::SipperCruise::Description () const inline
Definition at line 27 of file SipperCruise.h.
Referenced by MLL::DataBase::SipperCruiseInsert(), and MLL::DataBase::SipperCruiseUpdate().
void MLL::SipperCruise::Description (const KKStr & _description) inline
Definition at line 37 of file SipperCruise.h.
const KKStr& MLL::SipperCruise::Location () const inline
Definition at line 30 of file SipperCruise.h.
Referenced by MLL::DataBase::SipperCruiseInsert(), and MLL::DataBase::SipperCruiseUpdate().
void MLL::SipperCruise::Location (const KKStr & _location) inline
Definition at line 40 of file SipperCruise.h.
const KKStr& MLL::SipperCruise::Objective () const inline
Definition at line 31 of file SipperCruise.h.
Referenced by MLL::DataBase::SipperCruiseInsert(), and MLL::DataBase::SipperCruiseUpdate().
void MLL::SipperCruise::Objective (const KKStr & _objective) inline
Definition at line 41 of file SipperCruise.h.
const KKStr& MLL::SipperCruise::Principal () const inline
Definition at line 32 of file SipperCruise.h.
Referenced by MLL::DataBase::SipperCruiseInsert(), and MLL::DataBase::SipperCruiseUpdate().
void MLL::SipperCruise::Principal (const KKStr & _principal) inline
Definition at line 42 of file SipperCruise.h.
const KKStr& MLL::SipperCruise::ResearchOrg () const inline
Definition at line 33 of file SipperCruise.h.
Referenced by MLL::DataBase::SipperCruiseInsert(), and MLL::DataBase::SipperCruiseUpdate().
void MLL::SipperCruise::ResearchOrg (const KKStr & _researchOrg) inline
Definition at line 43 of file SipperCruise.h.
const KKStr& MLL::SipperCruise::ShipName () const inline
Definition at line 26 of file SipperCruise.h.
Referenced by MLL::DataBase::SipperCruiseInsert(), and MLL::DataBase::SipperCruiseUpdate().
void MLL::SipperCruise::ShipName (const KKStr & _shipName) inline
Definition at line 36 of file SipperCruise.h.
KKStr SipperCruise::ValidateCruiseName (const KKStr & _cruiseName) static
Definition at line 57 of file SipperCruise.cpp.
References KKB::KKStr::Append(), KKB::KKStr::Empty(), and KKB::KKStr::Len().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/SipperCruise.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/SipperCruise.cpp