Pices: PicesInterface::PicesGoalKeeper Class Reference
PicesInterface::PicesGoalKeeper Class Reference
This class is used to managed synchronization between threads in the same application.
#include <PicesGoalKeeper.h>
Public Member Functions
PicesGoalKeeper (String^ _name)
summary>Initiates a Block so that no other thread can lock this instance of PicesGoalKeeper.
void EndBlock ()
void StartBlock ()
Properties
bool Blocked [get]
int NumBlockedThreads [get]
Indicates the number of threads waiting in 'StartBlock'.
Detailed Description
This class is used to managed synchronization between threads in the same application.
Definition at line 9 of file PicesGoalKeeper.h.
Constructor & Destructor Documentation
PicesGoalKeeper::PicesGoalKeeper (String^ _name)
summary>Initiates a Block so that no other thread can lock this instance of PicesGoalKeeper.
remarks> If this instance of PicesGoalKeeper is already locked (blocked = false) then will in this function sleeping until it is no longer blocked(blocked = false). If we are the thread that holds the block then we will be allowed to proceed. For each time a thread calls this method in a row the variable 'blockerDepth' will be incremented. The block will not be released until the thread that has the lock has called the method 'EndBlock' enough times to reduce 'blockerDepth' to zero. /remarks>
Definition at line 18 of file PicesGoalKeeper.cpp.
Member Function Documentation
void PicesGoalKeeper::EndBlock ()
Definition at line 118 of file PicesGoalKeeper.cpp.
Referenced by PicesCommander.ChartAbundanceByDeployment::ChartAbundanceByDeployment(), PicesCommander.ChartAbundancePredictedAndValidated::ChartAbundancePredictedAndValidated(), PicesCommander.ChartDistribution::ChartDistribution(), PicesCommander.ChartGPS::ChartGPS(), PicesCommander.ChartGPSByStation::ChartGPSByStation(), PicesCommander.ChartHorizontalProfile::ChartHorizontalProfile(), PicesCommander.ChartSizeDepthDistribution::ChartSizeDepthDistribution(), PicesCommander.ChartSizeDistribution::ChartSizeDistribution(), PicesCommander.ClassDepthProfileChart::ClassDepthProfileChart(), PicesCommander.ClassMaintenance::ClassMaintenance(), PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets(), PicesCommander.PlanktonImageLoader::GetImagesAlreadyLoaded(), PicesCommander.PlanktonDepthStatisticsLoader::GetStatsAlreadyLoaded(), PicesCommander.PlanktonClassStatisticsLoader::GetStatsAlreadyLoaded(), PicesCommander.PlanktonDepthStatisticsLoader::GetStatsAlreadyLoadedIfNew(), PicesCommander.PlanktonClassStatisticsLoader::GetStatsAlreadyLoadedIfNew(), PicesCommander.ImportValidatdClass::ImportValidatdClass(), PicesCommander.InstrumentDataByDeploymentProfile::InstrumentDataByDeploymentProfile(), SipperFile.ActiveTrainingLibraries::ModelsAreAvailable(), PicesCommander.SipperInstrumentDataExtraction::SipperInstrumentDataExtraction(), PicesCommander.PlanktonDepthStatisticsLoader::Status(), and PicesCommander.PlanktonClassStatisticsLoader::Status().
void PicesGoalKeeper::StartBlock ()
Definition at line 30 of file PicesGoalKeeper.cpp.
Referenced by PicesCommander.ChartAbundanceByDeployment::ChartAbundanceByDeployment(), PicesCommander.ChartAbundancePredictedAndValidated::ChartAbundancePredictedAndValidated(), PicesCommander.ChartDistribution::ChartDistribution(), PicesCommander.ChartGPS::ChartGPS(), PicesCommander.ChartGPSByStation::ChartGPSByStation(), PicesCommander.ChartHorizontalProfile::ChartHorizontalProfile(), PicesCommander.ChartSizeDepthDistribution::ChartSizeDepthDistribution(), PicesCommander.ChartSizeDistribution::ChartSizeDistribution(), PicesCommander.ClassDepthProfileChart::ClassDepthProfileChart(), PicesCommander.ClassMaintenance::ClassMaintenance(), PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets(), PicesCommander.PlanktonImageLoader::GetImagesAlreadyLoaded(), PicesCommander.PlanktonDepthStatisticsLoader::GetStatsAlreadyLoaded(), PicesCommander.PlanktonClassStatisticsLoader::GetStatsAlreadyLoaded(), PicesCommander.PlanktonDepthStatisticsLoader::GetStatsAlreadyLoadedIfNew(), PicesCommander.PlanktonClassStatisticsLoader::GetStatsAlreadyLoadedIfNew(), PicesCommander.ImportValidatdClass::ImportValidatdClass(), PicesCommander.InstrumentDataByDeploymentProfile::InstrumentDataByDeploymentProfile(), SipperFile.ActiveTrainingLibraries::ModelsAreAvailable(), PicesCommander.SipperInstrumentDataExtraction::SipperInstrumentDataExtraction(), PicesCommander.PlanktonDepthStatisticsLoader::Status(), and PicesCommander.PlanktonClassStatisticsLoader::Status().
Property Documentation
bool PicesInterface::PicesGoalKeeper::Blocked get
Definition at line 27 of file PicesGoalKeeper.h.
int PicesInterface::PicesGoalKeeper::NumBlockedThreads get
Indicates the number of threads waiting in 'StartBlock'.
Definition at line 28 of file PicesGoalKeeper.h.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesGoalKeeper.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesGoalKeeper.cpp