Pices: PicesInterface Namespace Reference
PicesInterface Namespace Reference
Classes that encapsulate Unmanaged code for use in the managed world of c# are located in this namepace.
Classes
class Class1
class ClassificationBiasMatrix
Assists in adjusting a Classifiers output for bias of a classifier.
class Cruise
class CruiseList
class FeatureFileNamePrompter
Summary for FeatureFileNamePrompter
class OSservices
The Managed version of the OSServices methods defined in BaseLibrary.
class ParsedImageFileName
class PicesAbundanceCorrectionMatrix
Assists in adjusting a Classifiers output for bias of a classifier.
class PicesClass
Represents a single 'Class' in the machine learning world.
class PicesClassList
class PicesClassStatistic
Used as a vehicle to return statistics for a goven class.
class PicesClassStatisticList
class PicesDataBase
All access to the MySQL database is done through this class.
class PicesDataBaseImage
class PicesDataBaseImageGroup
class PicesDataBaseImageGroupEntry
class PicesDataBaseImageGroupEntryList
class PicesDataBaseImageGroupList
class PicesDataBaseImageList
class PicesDataBaseLogEntry
class PicesDataBaseLogEntryList
class PicesDataBaseServer
class PicesDataBaseServerList
class PicesDataBaseServerPrompter
Summary for PicesDataBaseServerPrompter
class PicesFeatureFileIO
class PicesFeatureVector
class PicesFeatureVectorList
class PicesGoalKeeper
This class is used to managed synchronization between threads in the same application.
class PicesGPSDataPoint
class PicesGPSDataPointList
class PicesImageSizeDistribution
class PicesImageSizeDistributionRow
class PicesInstrumentData
class PicesInstrumentDataFileManager
class PicesInstrumentDataList
class PicesKKStr
class PicesMethods
class PicesMsgQueue
class PicesPoint
class PicesPointList
class PicesPrediction
class PicesPredictionList
class PicesRaster
class PicesRasterList
class PicesRunLog
class PicesSipperCruise
class PicesSipperCruiseList
class PicesSipperDeployment
class PicesSipperDeploymentList
class PicesSipperFile
class PicesSipperFileList
class PicesSipperStation
class PicesSipperStationList
class PicesSipperVariables
class PicesTrainingClass
class PicesTrainingClassList
class PicesTrainingConfigManaged
class PicesVolumeSampledStat
class PicesVolumeSampledStatList
class ProbNamePair
class TrainingModel2
Functions
RasterSipperPtr ApplyMask (RasterSipperPtr origImage, RasterSipperPtr maskImage)
char ClassKeyToUse (System::Char classKeyToUse)
int ComparePicesClassStatistic (PicesClassStatistic^ left, PicesClassStatistic^ right)
KKB::KKStr & operator<< (KKB::KKStr &left, System::String^ right)
String^ operator<< (String^ left, KKB::KKStr &right)
Detailed Description
Classes that encapsulate Unmanaged code for use in the managed world of c# are located in this namepace.
The c# Managed world can not make calls to unmanaged code. So that unmanaged classes that are usefull in BaseLibrary (KKB), SipperInstruments (MLL), and PicesLibrary (MLL) can not be directly used. A separate set of classes need to be defined that will encapsulate the unmanaged classes providing a managed interface need to be provided. Ex: 'PicesFeatureVector' encapsulates an instance of the unmanaged class 'ImageFeatures'.
Function Documentation
RasterSipperPtr PicesInterface::ApplyMask (RasterSipperPtr origImage, RasterSipperPtr maskImage)
Definition at line 646 of file PicesRaster.cpp.
References KKB::Raster::ForegroundPixel(), KKB::Raster::GetPixelValue(), KKB::Raster::Height(), KKB::Raster::SetPixelValue(), and KKB::Raster::Width().
char PicesInterface::ClassKeyToUse (System::Char classKeyToUse)
Definition at line 335 of file PicesDataBase.cpp.
Referenced by PicesInterface::PicesDataBase::FeatureDataForImageGroup(), PicesInterface::PicesDataBase::FeatureDataGetOneSipperFile(), PicesInterface::PicesDataBase::ImageGetClassStatistics(), PicesInterface::PicesDataBase::ImageGetDepthStatistics(), PicesInterface::PicesDataBase::ImagesQuery(), and PicesInterface::PicesDataBase::ImagesQueryByGrouop().
int PicesInterface::ComparePicesClassStatistic (PicesClassStatistic^ left, PicesClassStatistic^ right)
Definition at line 80 of file PicesClassStatistic.cpp.
References PicesInterface::PicesClassStatistic::ClassName.
Referenced by PicesInterface::PicesClassStatisticList::SortByClassName().
KKStr & PicesInterface::operator<< (KKB::KKStr & left, System::String^ right)
Definition at line 255 of file PicesKKStr.cpp.
References KKB::KKStr::Append().
String PicesInterface::operator<< (String^ left, KKB::KKStr & right)
Definition at line 272 of file PicesKKStr.cpp.