Pices: KKB::RunLog Class Reference
KKB::RunLog Class Reference
Used for logging messages.
#include <RunLog.h>
Public Member Functions
RunLog ()
Creates an instance were logging will go to the console.
RunLog (const char *_fileName)
Creates instance with a log messages written to file 'fileName'.
RunLog (const KKStr &_fileName)
Creates instance with a log messages written to file 'fileName'.
RunLog (std::ostream &errorLogStream)
Creates instance where logging messages are written to file stream specified by 'errorLogStream'.
RunLog (std::ostream *logStream)
Creates instance where logging messages are written to file stream pointed to by 'logStream'.
RunLog (MsgQueuePtr _msgQueue)
~RunLog ()
summary> Sets current message level you would normally call this method just before you wish to start logging a message.
void Append (const char *str)
Appends string to log; generally used by other Log methods but can be called by public.
void AttachFile (const KKStr &_fileName)
Call this method to start logging messages to a different file.
void AttachFile (std::ostream &_logFile)
Call this method to start logging messages to a specific file stream.
void AttachFileAppend (const KKStr &_fileName)
Call this method to start appending logging messages to a different file.
void AttachMsgQueue (MsgQueuePtr _msgQueue)
All activity that is written to the log file will be added as messages to '_msgQueue'.
void DetachFile ()
Closes out current log file and starts writing to stdout aka 'cout'.
KKStr FileName ()
void Flush ()
const KKStr & LastLine ()
Returns the last line of text written to the log file.
RunLog & Level (kkint32 _level)
kkint32 Level () const
kkint32 LineCount () const
kkint32 MemoryConsumedEstimated () const
RunLog & operator<< (bool right)
RunLog & operator<< (kkint16 right)
RunLog & operator<< (kkuint16 right)
RunLog & operator<< (kkint32 right)
RunLog & operator<< (kkuint32 right)
RunLog & operator<< (kkint64 right)
RunLog & operator<< (kkuint64 right)
RunLog & operator<< (double right)
RunLog & operator<< (char right)
RunLog & operator<< (const char *right)
RunLog & operator<< (const KKStr &right)
RunLog & operator<< (KKStrConstPtr right)
RunLog & operator<< (const VectorKKStr &right)
RunLog & operator<< (std::ostream &(*mf)(std::ostream &))
void SetLevel (kkint32 _level)
void SetLoggingLevel (kkint32 _loggingLevel)
void WriteLine (const KKStr &s)
Writes a line of text to log file; does not check logging level; and does not write any preview text such as DateTime or processId.
void WriteLine (const char *s)
Writes a line of text to log file; does not check logging level; and does not write any preview text such as DateTime or processId.
Detailed Description
Used for logging messages.
Has facilities to deal with different levels of logging. You use the normal insertion operators to write to this object. You can specify at any point a Logging level. If this level is less than or equal to a specified threshold the message will be recorded in the log. <br > The idea is that during normal production runs log level would be set to 10. But if there appears to be some issue then you would set the logging level to a higher level to get more details. The higher the level the more detail you will get.
Definition at line 49 of file RunLog.h.
Constructor & Destructor Documentation
RunLog::RunLog ()
Creates an instance were logging will go to the console.
Definition at line 32 of file RunLog.cpp.
Referenced by MemoryConsumedEstimated().
RunLog::RunLog (const char * _fileName)
Creates instance with a log messages written to file 'fileName'.
Definition at line 44 of file RunLog.cpp.
References KKB::KKStr::Str().
RunLog::RunLog (const KKStr & _fileName)
Creates instance with a log messages written to file 'fileName'.
Definition at line 57 of file RunLog.cpp.
References KKB::KKStr::Str().
RunLog::RunLog (std::ostream & errorLogStream)
Creates instance where logging messages are written to file stream specified by 'errorLogStream'.
Definition at line 70 of file RunLog.cpp.
RunLog::RunLog (std::ostream * logStream)
Creates instance where logging messages are written to file stream pointed to by 'logStream'.
Definition at line 83 of file RunLog.cpp.
RunLog::RunLog (MsgQueuePtr _msgQueue)
Definition at line 96 of file RunLog.cpp.
RunLog::~RunLog ()
summary> Sets current message level you would normally call this method just before you wish to start logging a message.
If you are not changing the level since previous call then no need to call. /summary>
Definition at line 108 of file RunLog.cpp.
Member Function Documentation
void RunLog::Append (const char * str)
Appends string to log; generally used by other Log methods but can be called by public.
Definition at line 253 of file RunLog.cpp.
References KKB::MsgQueue::AddMsg(), KKB::GlobalGoalKeeper::EndBlock(), Flush(), KKB::KKStr::Len(), KKB::osGetLocalDateTime(), KKB::osGetThreadId(), KKB::GlobalGoalKeeper::StartBlock(), and KKB::DateTime::Time().
Referenced by Level(), operator<<(), PicesInterface::PicesRunLog::Write(), WriteLine(), and PicesInterface::PicesRunLog::Writeln().
void RunLog::AttachFile (const KKStr & _fileName)
Call this method to start logging messages to a different file.
Will close out current log file and open new one specified by 'fileName'.
Definition at line 127 of file RunLog.cpp.
References KKB::KKStr::Str().
Referenced by PicesInterface::PicesRunLog::AttachFile(), FileInStack(), KKB::Application::InitalizeApplication(), Level(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void RunLog::AttachFile (std::ostream & _logFile)
Call this method to start logging messages to a specific file stream.
Will close out current log file and write to the specified '_logFile' in the future.
Definition at line 166 of file RunLog.cpp.
void RunLog::AttachFileAppend (const KKStr & _fileName)
Call this method to start appending logging messages to a different file.
Will close out current log file and open new one specified by 'fileName' with the append flag set.
Definition at line 143 of file RunLog.cpp.
References KKB::KKStr::Str().
Referenced by PicesInterface::PicesRunLog::DisplayWithNoteBook(), and Level().
void RunLog::AttachMsgQueue (MsgQueuePtr _msgQueue)
All activity that is written to the log file will be added as messages to '_msgQueue'.
Definition at line 159 of file RunLog.cpp.
Referenced by PicesInterface::TrainingModel2::AttachMsgQueueToRunLog(), PicesInterface::TrainingModel2::CleanUp(), Level(), PicesInterface::TrainingModel2::LoadExistingModelOtherwiseBuild(), PicesInterface::TrainingModel2::LoadTrainingModelForGivenLevel(), and PicesInterface::PicesRunLog::PicesRunLog().
void RunLog::DetachFile ()
Closes out current log file and starts writing to stdout aka 'cout'.
Definition at line 181 of file RunLog.cpp.
Referenced by PicesInterface::PicesRunLog::DetachFile(), PicesInterface::PicesRunLog::DisplayWithNoteBook(), and Level().
KKStr RunLog::FileName ()
Definition at line 193 of file RunLog.cpp.
References KKB::osGetProcessId().
Referenced by PicesInterface::PicesRunLog::DisplayWithNoteBook(), PicesInterface::PicesRunLog::FileName(), Level(), PicesInterface::TrainingModel2::PredictProbabilities(), and PicesInterface::PicesRunLog::RunLogFileName().
void RunLog::Flush ()
Definition at line 296 of file RunLog.cpp.
Referenced by Append(), LineCount(), and MLL::FeatureFileIOPices::LoadFile().
const KKStr& KKB::RunLog::LastLine () inline
Returns the last line of text written to the log file.
Definition at line 117 of file RunLog.h.
Referenced by PicesInterface::PicesRunLog::LastLine(), and PicesInterface::TrainingModel2::LastRunLogTextLine().
RunLog & RunLog::Level (kkint32 _level)
Definition at line 220 of file RunLog.cpp.
References Append(), KKB::osGetLocalDateTime(), and KKB::DateTime::Time().
Referenced by _(), MLL::AbundanceCorrectionMatrix::AbundanceCorrectionMatrix(), KKMLL::FileDesc::AddANominalValue(), KKMLL::TrainingConfiguration2::AddATrainingClass(), MLL::AbundanceCorrectionMatrix::AddIn(), MLL::ImageSizeDistribution::AddIn(), KKMLL::ClassAssignments::AddMLClass(), MLL::AbundanceCorrectionMatrix::AdjustClassificationCounts(), AllBinaryClassesAreDone(), ImageExtractionManager::ExtractionManager::AllProcessorsTerminated(), KKMLL::FeatureFileIO::AppendToFile(), JobManagment::JobManager::Block(), FeatureSelectionApp::Processor::Block(), FeatureSelectionApp::FeatureSelection::Block(), KKMLL::ClassificationBiasMatrix::BuildFromIstreamXML(), KKMLL::ConfusionMatrix2::BuildFromIstreamXML(), FeatureSelectionApp::FeatureSelection::BuildResultConfigFile(), KKMLL::TrainingProcess2::BuildTrainingProcess(), CalcClassPairWeighted(), CalcGrowthRate(), KKMLL::SVMModel::CancelFlag(), FeatureSelectionApp::Processor::Class2Name(), KKMLL::Classifier2::Classifier2(), PicesInterface::TrainingModel2::CleanUp(), KKMLL::GrayScaleImagesFVProducer::ComputeFeatureVector(), MLL::PicesFVProducer::ComputeFeatureVector(), MLL::PicesFVProducer::ComputeFeatureVectorFromImage(), KKMLL::FeatureVectorProducer::ComputeFeatureVectorFromImage(), KKMLL::TrainingProcess2::ConfigFileFormatErrors(), KKMLL::Model::CreateAModel(), KKMLL::FeatureEncoder2::CreateEncodedFileDesc(), MLL::PicesTrainingConfiguration::CreateFromDirectoryStructure(), KKMLL::TrainingConfiguration2::CreateFromDirectoryStructure(), MLL::PicesTrainingConfiguration::CreateFromFeatureVectorList(), KKMLL::TrainingConfiguration2::CreateFromFeatureVectorList(), MLL::InstrumentDataList::CreateFromSipperFile(), KKMLL::TrainingProcess2::CreateModelsFromTrainingData(), KKMLL::Orderings::CreateOrderingsObjFromFileIfAvaliable(), KKMLL::TrainingProcess2::CreateTrainingProcess(), KKMLL::TrainingProcess2::CreateTrainingProcessForLevel(), KKMLL::TrainingProcess2::CreateTrainingProcessFromTrainingExamples(), MLL::DataBase::DataBase(), DateToQuotedStr(), MLL::PicesApplication::DisplayCommandLineParameters(), FeatureSelectionApp::FeatureSelection::DisplayCommandUsage(), KKMLL::ModelParamDual::Duplicate(), KKMLL::DuplicateImages::DuplicateImages(), KKMLL::FeatureEncoder::EncodeIntoSparseMatrix(), JobManagment::JobManager::EndBlock(), FeatureSelectionApp::Processor::EndBlock(), FeatureSelectionApp::FeatureSelection::EndBlock(), FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), FeatureSelectionApp::BinaryJob::EvaluateNode(), FeatureSelectionApp::BinaryJob::ExpandBestCaseBackward(), FeatureSelectionApp::BinaryJob::ExpandBestCaseForward(), KKMLL::FeatureNumList::ExtractFeatureNumsFromStr(), KKMLL::TrainingConfiguration2::ExtractFullHierachyOfClasses(), KKMLL::TrainingProcess2::ExtractTrainingClassFeatures(), MLL::DataBase::FeatureDataCreateTable(), MLL::DataBase::FeatureDataForImageGroup(), MLL::DataBase::FeatureDataRecLoad(), MLL::FeatureFileIOPices::FeatureDataReSink(), KKMLL::FeatureFileIO::FeatureDataReSink(), MLL::ImageFeaturesList::FeatureExtraction(), FeatureSelectionApp::FeatureSelection::FeatureSelection(), FileInStack(), FeatureSelectionApp::FinalResults::FinalResults(), KKMLL::SVMModel::FindWorstSupportVectors2(), FeatureSelectionApp::Processor::FlagJobsForTesting(), MLL::SipperExtractionImageManager::Flush(), KKMLL::ConfusionMatrix2::FMeasure(), KKB::ContourFollower::FollowContour(), FeatureSelectionApp::Processor::GetBestParametersFromTestResults(), FeatureSelectionApp::Processor::GetFeatureImpact(), KKMLL::TrainingConfiguration2::GetFeatureNums(), FeatureSelectionApp::Processor::GetFeaturesFromTestResults(), KKMLL::FeatureFileIODstWeb::GetFileDesc(), KKMLL::FeatureFileIOColumn::GetFileDesc(), KKMLL::FeatureFileIOC45::GetFileDesc(), KKMLL::FeatureFileIORoberts::GetFileDesc(), KKMLL::FeatureFileIOUCI::GetFileDesc(), KKMLL::FeatureFileIOSparse::GetFileDesc(), MLL::FeatureFileIOPices::GetFileDesc(), KKB::XmlStream::GetNextToken(), GetProcessId(), MLL::InstrumentDataList::GetVolumePerMeterProfile(), MLL::DataBase::ImageFullSizeSave(), MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageGroupEntriesInsert(), MLL::DataBase::ImageGroupEntriesLoad(), MLL::DataBase::ImageGroupLoad(), MLL::ImageSizeDistribution::ImageSizeDistribution(), MLL::DataBase::ImagesSizeDistributionByDepth(), MLL::DataBase::ImageUpdateInstrumentDataFields(), KKMLL::ConfusionMatrix2::Increment(), MLL::PicesApplication::InitalizeApplication(), JobManagment::JobManager::InitilizeJobManager(), MLL::DataBase::InstrumentDataBinByMeterDepth(), MLL::DataBase::InstrumentDataDeploymentVolumeSampled(), MLL::DataBase::InstrumentDataGetVolumePerMeterDepth(), MLL::DataBase::InstrumentDataRetrieveGPSInfo(), JobManagment::JobManager::JobManager(), KKMLL::DuplicateImages::ListOfExamplesToDelete(), MLL::DataBaseImageValidatedEntryList::Load(), KKMLL::TrainingConfiguration2::Load(), FeatureSelectionApp::BinaryJobList::Load(), KKMLL::FeatureNumList::Load(), KKMLL::TrainingProcess2::LoadExistingTrainingProcess(), FeatureSelectionApp::FeatureSelection::LoadFeatureData(), KKMLL::FeatureFileIOC45::LoadFeatureFile(), KKMLL::FeatureFileIO::LoadFeatureFile(), KKMLL::FeatureFileIODstWeb::LoadFile(), KKMLL::FeatureFileIOColumn::LoadFile(), KKMLL::FeatureFileIORoberts::LoadFile(), KKMLL::FeatureFileIOUCI::LoadFile(), KKMLL::FeatureFileIOC45::LoadFile(), KKMLL::FeatureFileIOSparse::LoadFile(), MLL::FeatureFileIOPices::LoadFile(), KKB::Configuration::LoadFile(), MLL::FeatureFileIOPices::LoadInSubDirectoryTree(), KKMLL::FeatureFileIO::LoadInSubDirectoryTree(), MLL::DataBaseUpdate::LoadSourceFile(), MLL::DataBase::LogEntriesProcessEnd(), ImageExtractionManager::ExtractionManager::ManageTheExtraction(), KKMLL::TrainingConfiguration2::Manufacture(), KKMLL::NormalizationParms::Mean(), FeatureSelectionApp::Processor::MergeKBestFeatureSelections(), KKMLL::FileDesc::MergeSymbolicFields(), MLL::DataBase::MLClassLoad(), MLL::DataBase::MLClassLoadChildren(), MLL::DataBase::MLClassLoadList(), KKMLL::TrainingProcess2::Model3(), KKMLL::NormalizationParms::NormalizationParms(), KKMLL::NormalizationParms::NormalizeExamples(), KKMLL::operator<<(), KKMLL::Orderings::Orderings(), KKMLL::GrayScaleImagesFVList::OrderUsingNamesFromAFile(), KKMLL::FeatureVectorList::OrderUsingNamesFromAFile(), KKMLL::MLClassIndexList::ParseClassIndexList(), KKMLL::ModelParam::ParseCmdLine(), KKMLL::ModelParamOldSVM::ParseCmdLine(), KKMLL::SVMparam::ParseCmdLineParameter(), KKMLL::ClassificationBiasMatrix::PerformAdjustmnts(), KKMLL::ModelSvmBase::Predict(), KKMLL::ModelUsfCasCor::Predict(), KKMLL::ModelDual::Predict(), MLL::AbundanceCorrectionMatrix::Prediction(), KKMLL::Classifier2::PriorProbability(), KKMLL::ModelKnn::ProbabilitiesByClass(), KKMLL::ModelSvmBase::ProbabilitiesByClass(), KKMLL::ModelUsfCasCor::ProbabilitiesByClass(), KKMLL::ModelOldSVM::ProbabilitiesByClass(), KKMLL::ModelDual::ProbabilitiesByClass(), KKMLL::SVMModel::ProbabilitiesByClass(), KKMLL::ModelDual::ProbabilitiesByClassDual(), FeatureSelectionApp::FeatureSelection::ProcessCmdLine(), KKB::Application::ProcessCmdLineParameter(), MLL::PicesApplication::ProcessCmdLineParameter(), FeatureSelectionApp::Processor::Processor(), FeatureSelectionApp::Processor::ProcessRestart(), JobManagment::Job::ProcessStatusField(), FeatureSelectionApp::BinaryJob::ProcessStatusField(), FeatureSelectionApp::FeatureSelection::ProcessStatusFile(), FeatureSelectionApp::BinaryJob::ProcessStatusStr(), JobManagment::Job::ProcessStatusStr(), KKMLL::DuplicateImages::PurgeDuplicates(), JobManagment::JobList::PushOnBack(), MLL::DataBase::QueryStatement(), FeatureSelectionApp::FeatureSelection::RandomSplit(), SVM289_BFS::svm_model::Read(), KKMLL::AttributeTypeVector::ReadXML(), KKMLL::ModelParamUsfCasCor::ReadXML(), MLL::AbundanceCorrectionMatrix::ReadXml(), KKMLL::NormalizationParms::ReadXML(), KKMLL::ModelKnn::ReadXML(), KKMLL::ClassProbList::ReadXML(), KKMLL::FeatureEncoder::ReadXML(), KKMLL::ModelUsfCasCor::ReadXML(), KKMLL::ModelSvmBase::ReadXML(), KKMLL::ModelParamOldSVM::ReadXML(), KKMLL::FeatureNumList::ReadXML(), KKMLL::TrainingClassList::ReadXML(), SVM233::SvmModel233::ReadXML(), KKMLL::ModelDual::ReadXML(), SVM289_MFS::Svm_Model::ReadXML(), KKMLL::FileDesc::ReadXML(), KKMLL::SVMparam::ReadXML(), KKMLL::ModelOldSVM::ReadXML(), KKMLL::SVMModel::ReadXML(), KKMLL::TrainingProcess2::ReadXML(), KKMLL::Model::ReadXMLModelPost(), KKMLL::Model::ReadXMLModelToken(), KKMLL::GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree(), MLL::ImageFeaturesList::RecalcFeatureValuesFromImagesInDirTree(), KKMLL::ModelDual::ReconcilePredictions(), KKMLL::Model::ReduceTrainExamples(), FeatureSelectionApp::BinaryJob::ReFresh(), KKMLL::FactoryFVProducer::RegisterFactory(), KKMLL::FeatureVectorList::RemoveEntriesWithMissingFeatures(), ReportDataSpecs(), ReportError(), MLL::InstrumentDataManager::ReportInstrumentData(), MLL::SipperExtractionImageManager::ReportStatistics(), MLL::SipperExtractionImageManager::ReportStatsByDepth(), KKMLL::TrainingProcess2::ReportTraningClassStatistics(), MLL::DataBase::ResultSetsClear(), KKMLL::ModelSvmBase::RetrieveCrossProbTable(), KKMLL::ModelDual::RetrieveCrossProbTable(), KKMLL::SVMModel::RetrieveCrossProbTable(), KKMLL::Model::RetrieveCrossProbTable(), KKMLL::TrainingConfiguration2::RootDirExpanded(), JobManagment::JobManager::Run(), FeatureSelectionApp::FeatureSelection::Run(), FeatureSelectionApp::Processor::Run(), KKMLL::CrossValidationVoting::RunCrossValidation(), KKMLL::CrossValidation::RunCrossValidation(), KKMLL::CrossValidationVoting::RunValidationOnly(), KKMLL::CrossValidation::RunValidationOnly(), KKMLL::FileDesc::SameExceptForSymbolicData(), MLL::InstrumentDataList::Save(), MLL::DataBaseImageValidatedEntryList::Save(), FeatureSelectionApp::BinaryJobList::Save(), KKMLL::Orderings::Save(), KKMLL::FeatureNumList::Save(), KKMLL::FeatureFileIO::SaveFeatureFile(), KKMLL::FeatureFileIODstWeb::SaveFile(), KKMLL::FeatureFileIOColumn::SaveFile(), KKMLL::FeatureFileIORoberts::SaveFile(), KKMLL::FeatureFileIOSparse::SaveFile(), MLL::AbundanceCorrectionMatrix::SaveForConfigFileName(), KKMLL::TrainingProcess2::SaveTrainingProcess(), KKB::SegmentorOTSU::SegmentImage(), KKB::SegmentorOTSU::SegmentMaskedImage(), FeatureSelectionApp::BinaryJobList::SelectOneDoneJobAtRandomFromTop10Percent(), MLL::DataBase::ServerDescription(), JobManagment::JobManager::SetQuitRunningFlag(), FeatureSelectionApp::Processor::SetQuitRunningFlag(), KKMLL::NormalizationParms::Sigma(), MLL::DataBase::SipperCruiseUpdate(), MLL::SipperExtractionImageManager::SipperExtractionImageManager(), MLL::DataBase::SipperFileGetList(), KKMLL::SizeDistribution::SizeDistribution(), MLL::SizeDistribution::SizeDistribution(), JobManagment::JobManager::StatusFileProcessLine(), JobManagment::JobManager::StatusFileProcessLineJobStatusChange(), KKMLL::FeatureVectorList::StratifyAmoungstClasses(), KKMLL::ModelParamOldSVM::SVM_EncodingMethodToModelParamEncodingMethodType(), SVM233::Svm_Load_Model(), SVM289_BFS::svm_train_one(), SVM289_MFS::svm_train_one(), KKMLL::SVMModel::SVMModel(), KKMLL::FeatureVectorList::SynchronizeSymbolicData(), ImageExtractionManager::ExtractionManager::TerminateProcessing(), KKMLL::ModelParamKnn::ToCmdLineStr(), FeatureSelectionApp::FinalResults::ToHTMLStr(), JobManagment::JobManager::ToStatusStr(), KKMLL::TrainingConfiguration2::TrainingConfiguration2(), KKMLL::ModelKnn::TrainModel(), KKMLL::ModelUsfCasCor::TrainModel(), KKMLL::ModelSvmBase::TrainModel(), KKMLL::ModelDual::TrainModel(), KKMLL::ModelOldSVM::TrainModel(), KKMLL::Model::TrainModel(), FeatureSelectionApp::Processor::Update(), FeatureSelectionApp::FeatureImpact::UpdateAccByFeatureSelList(), MLL::DataBaseServerList::WriteConfigFile(), KKMLL::NormalizationParms::WriteToFile(), KKMLL::ClassificationBiasMatrix::WriteXML(), KKMLL::ConfusionMatrix2::~ConfusionMatrix2(), KKMLL::FeatureFileIOArff::~FeatureFileIOArff(), and FeatureSelectionApp::Processor::~Processor().
kkint32 KKB::RunLog::Level () const inline
Definition at line 78 of file RunLog.h.
References Append(), AttachFile(), AttachFileAppend(), AttachMsgQueue(), DetachFile(), and FileName().
kkint32 KKB::RunLog::LineCount () const inline
Definition at line 119 of file RunLog.h.
References Flush(), operator<<(), SetLoggingLevel(), and WriteLine().
Referenced by PicesInterface::TrainingModel2::LastRunLogTextLine(), and PicesInterface::PicesRunLog::LineCount().
kkint32 RunLog::MemoryConsumedEstimated () const
Definition at line 116 of file RunLog.cpp.
References KKB::KKStr::MemoryConsumedEstimated(), and RunLog().
Referenced by SetLevel().
RunLog & RunLog::operator<< (bool right)
Definition at line 305 of file RunLog.cpp.
References Append().
Referenced by LineCount().
RunLog & RunLog::operator<< (kkint16 right)
Definition at line 317 of file RunLog.cpp.
References Append(), KKB::KKStr::Str(), and KKB::StrFormatInt().
RunLog & RunLog::operator<< (kkuint16 right)
Definition at line 327 of file RunLog.cpp.
References Append(), KKB::KKStr::Str(), and KKB::StrFormatInt().
RunLog & RunLog::operator<< (kkint32 right)
Definition at line 337 of file RunLog.cpp.
References Append(), KKB::KKStr::AppendInt32(), and KKB::KKStr::Str().
RunLog & RunLog::operator<< (kkuint32 right)
Definition at line 347 of file RunLog.cpp.
References Append(), KKB::KKStr::AppendUInt32(), and KKB::KKStr::Str().
RunLog & RunLog::operator<< (kkint64 right)
Definition at line 357 of file RunLog.cpp.
References Append(), KKB::KKStr::Str(), and KKB::StrFormatInt64().
RunLog & RunLog::operator<< (kkuint64 right)
Definition at line 367 of file RunLog.cpp.
References Append(), KKB::KKStr::Str(), and KKB::StrFormatInt64().
RunLog & RunLog::operator<< (double right)
Definition at line 377 of file RunLog.cpp.
References Append().
RunLog & RunLog::operator<< (char right)
Definition at line 393 of file RunLog.cpp.
References Append().
RunLog & RunLog::operator<< (const char * right)
Definition at line 404 of file RunLog.cpp.
References Append().
RunLog & RunLog::operator<< (const KKStr & right)
Definition at line 412 of file RunLog.cpp.
References Append(), and KKB::KKStr::Str().
RunLog & RunLog::operator<< (KKStrConstPtr right)
Definition at line 420 of file RunLog.cpp.
References Append().
RunLog & RunLog::operator<< (const VectorKKStr & right)
Definition at line 429 of file RunLog.cpp.
References KKB::endl().
RunLog & RunLog::operator<< (std::ostream &(*)(std::ostream &) mf)
Definition at line 440 of file RunLog.cpp.
References Append().
void KKB::RunLog::SetLevel (kkint32 _level) inline
Definition at line 157 of file RunLog.h.
References MemoryConsumedEstimated().
Referenced by PicesInterface::PicesRunLog::Write(), and PicesInterface::PicesRunLog::Writeln().
void RunLog::SetLoggingLevel (kkint32 _loggingLevel)
Definition at line 211 of file RunLog.cpp.
Referenced by LineCount(), and PicesInterface::PicesRunLog::SetLoggingLevel().
void RunLog::WriteLine (const KKStr & s)
Writes a line of text to log file; does not check logging level; and does not write any preview text such as DateTime or processId.
If there is any data in Current-Line it will be write out first before writing this line of text.
Definition at line 453 of file RunLog.cpp.
References KKB::MsgQueue::AddMsg(), Append(), KKB::KKStr::Empty(), KKB::GlobalGoalKeeper::EndBlock(), KKB::endl(), KKB::KKStr::Len(), KKB::GlobalGoalKeeper::StartBlock(), and KKB::KKStr::Str().
Referenced by LineCount().
void RunLog::WriteLine (const char * s)
Writes a line of text to log file; does not check logging level; and does not write any preview text such as DateTime or processId.
If there is any data in Current-Line it will be write out first before writing this line of text.
Definition at line 479 of file RunLog.cpp.
References KKB::MsgQueue::AddMsg(), Append(), KKB::KKStr::Empty(), KKB::GlobalGoalKeeper::EndBlock(), KKB::endl(), and KKB::GlobalGoalKeeper::StartBlock().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/RunLog.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/RunLog.cpp