Pices: MLL::DataBaseLogEntry Class Reference
MLL::DataBaseLogEntry Class Reference
#include <DataBaseLogEntry.h>
Public Types
typedef DataBaseLogEntry * DataBaseLogEntryPtr
typedef KKB::kkint32 kkint32
typedef KKB::kkuint32 kkuint32
typedef KKB::uchar uchar
typedef KKB::ulong ulong
Public Member Functions
DataBaseLogEntry ()
DataBaseLogEntry (const KKStr &_progCode, const KKStr &_progName, const KKB::DateTime &_dateTimeCompiled, const KKStr &_cmdLine, const KKStr &_compName, const KKStr &_compUserName, const KKStr &_sipperFileName)
~DataBaseLogEntry ()
const KKStr & CmdLine () const
void CmdLine (const KKStr &_cmdLine)
const KKStr & CompletionStatus () const
void CompletionStatus (const KKStr &_completionStatus)
const KKStr & CompName () const
void CompName (const KKStr &_compName)
const KKStr & CompUserName () const
void CompUserName (const KKStr &_compUserName)
float CpuTimeUsed () const
void CpuTimeUsed (float _cpuTimeUsed)
const KKStr & DataBaseUserName () const
void DataBaseUserName (const KKStr &_dataBaseUserName)
KKB::DateTime DateTimeCompiled () const
void DateTimeCompiled (const KKB::DateTime &_dateTimeCompiled)
KKB::DateTime DateTimeEnd () const
void DateTimeEnd (const KKB::DateTime &_dateTimeEnd)
KKB::DateTime DateTimeStart () const
void DateTimeStart (const KKB::DateTime &_dateTimeStart)
KKB::DateTime DateTimeStartUtc () const
void DateTimeStartUtc (const KKB::DateTime &_dateTimeStartUtc)
kkuint32 LogEntryId () const
void LogEntryId (kkuint32 _logEntryId)
const KKStr & ProgCode () const
void ProgCode (const KKStr &_progCode)
const KKStr & ProgName () const
void ProgName (const KKStr &_progName)
const KKStr & SipperFileName () const
void SipperFileName (const KKStr &_sipperFileName)
Detailed Description
Used for Maintaining LogEntries; specifically is used to indicate when Processes started   *
and ended along with the command line used.  Each entry will be assigned a unique ID that  *
other elements can refer to.  For example each entry in the Images table can refer to the  *
log entry that generated the image.  Programs such as "GrayImageExtraction" and            *
"ImageClassification" will generate entries into this table.                               *
Definition at line 32 of file DataBaseLogEntry.h.
Member Typedef Documentation
typedef DataBaseLogEntry* MLL::DataBaseLogEntry::DataBaseLogEntryPtr
Definition at line 35 of file DataBaseLogEntry.h.
typedef KKB::kkint32 MLL::DataBaseLogEntry::kkint32
Definition at line 37 of file DataBaseLogEntry.h.
typedef KKB::kkuint32 MLL::DataBaseLogEntry::kkuint32
Definition at line 38 of file DataBaseLogEntry.h.
typedef KKB::uchar MLL::DataBaseLogEntry::uchar
Definition at line 40 of file DataBaseLogEntry.h.
typedef KKB::ulong MLL::DataBaseLogEntry::ulong
Definition at line 39 of file DataBaseLogEntry.h.
Constructor & Destructor Documentation
DataBaseLogEntry::DataBaseLogEntry ()
Definition at line 27 of file DataBaseLogEntry.cpp.
DataBaseLogEntry::DataBaseLogEntry (const KKStr & _progCode, const KKStr & _progName, const KKB::DateTime & _dateTimeCompiled, const KKStr & _cmdLine, const KKStr & _compName, const KKStr & _compUserName, const KKStr & _sipperFileName)
Parameters
_sipperFileName Root name of Sipper File
Definition at line 46 of file DataBaseLogEntry.cpp.
DataBaseLogEntry::~DataBaseLogEntry ()
Definition at line 76 of file DataBaseLogEntry.cpp.
Member Function Documentation
const KKStr& MLL::DataBaseLogEntry::CmdLine () const inline
Definition at line 59 of file DataBaseLogEntry.h.
Referenced by PicesInterface::PicesDataBaseLogEntry::!PicesDataBaseLogEntry(), and MLL::DataBase::LogEntriesSelect().
void MLL::DataBaseLogEntry::CmdLine (const KKStr & _cmdLine) inline
Definition at line 74 of file DataBaseLogEntry.h.
const KKStr& MLL::DataBaseLogEntry::CompletionStatus () const inline
Definition at line 67 of file DataBaseLogEntry.h.
Referenced by PicesInterface::PicesDataBaseLogEntry::!PicesDataBaseLogEntry(), and MLL::DataBase::LogEntriesSelect().
void MLL::DataBaseLogEntry::CompletionStatus (const KKStr & _completionStatus) inline
Definition at line 82 of file DataBaseLogEntry.h.
const KKStr& MLL::DataBaseLogEntry::CompName () const inline
Definition at line 60 of file DataBaseLogEntry.h.
Referenced by PicesInterface::PicesDataBaseLogEntry::!PicesDataBaseLogEntry(), and MLL::DataBase::LogEntriesSelect().
void MLL::DataBaseLogEntry::CompName (const KKStr & _compName) inline
Definition at line 75 of file DataBaseLogEntry.h.
const KKStr& MLL::DataBaseLogEntry::CompUserName () const inline
Definition at line 62 of file DataBaseLogEntry.h.
Referenced by PicesInterface::PicesDataBaseLogEntry::!PicesDataBaseLogEntry(), and MLL::DataBase::LogEntriesSelect().
void MLL::DataBaseLogEntry::CompUserName (const KKStr & _compUserName) inline
Definition at line 77 of file DataBaseLogEntry.h.
float MLL::DataBaseLogEntry::CpuTimeUsed () const inline
Definition at line 66 of file DataBaseLogEntry.h.
Referenced by PicesInterface::PicesDataBaseLogEntry::!PicesDataBaseLogEntry(), and MLL::DataBase::LogEntriesSelect().
void MLL::DataBaseLogEntry::CpuTimeUsed (float _cpuTimeUsed) inline
Definition at line 81 of file DataBaseLogEntry.h.
const KKStr& MLL::DataBaseLogEntry::DataBaseUserName () const inline
Definition at line 61 of file DataBaseLogEntry.h.
Referenced by PicesInterface::PicesDataBaseLogEntry::!PicesDataBaseLogEntry(), MLL::DataBase::LogEntriesProcessStart(), and MLL::DataBase::LogEntriesSelect().
void MLL::DataBaseLogEntry::DataBaseUserName (const KKStr & _dataBaseUserName) inline
Definition at line 76 of file DataBaseLogEntry.h.
KKB::DateTime MLL::DataBaseLogEntry::DateTimeCompiled () const inline
Definition at line 58 of file DataBaseLogEntry.h.
Referenced by PicesInterface::PicesDataBaseLogEntry::!PicesDataBaseLogEntry(), and MLL::DataBase::LogEntriesSelect().
void MLL::DataBaseLogEntry::DateTimeCompiled (const KKB::DateTime & _dateTimeCompiled) inline
Definition at line 73 of file DataBaseLogEntry.h.
KKB::DateTime MLL::DataBaseLogEntry::DateTimeEnd () const inline
Definition at line 65 of file DataBaseLogEntry.h.
Referenced by PicesInterface::PicesDataBaseLogEntry::!PicesDataBaseLogEntry(), MLL::DataBase::LogEntriesProcessEnd(), and MLL::DataBase::LogEntriesSelect().
void MLL::DataBaseLogEntry::DateTimeEnd (const KKB::DateTime & _dateTimeEnd) inline
Definition at line 80 of file DataBaseLogEntry.h.
KKB::DateTime MLL::DataBaseLogEntry::DateTimeStart () const inline
Definition at line 63 of file DataBaseLogEntry.h.
Referenced by PicesInterface::PicesDataBaseLogEntry::!PicesDataBaseLogEntry(), MLL::DataBase::LogEntriesProcessStart(), MLL::DataBase::LogEntriesSelect(), and MLL::DataBaseLogEntryList::ProgCodeComparison::operator()().
void MLL::DataBaseLogEntry::DateTimeStart (const KKB::DateTime & _dateTimeStart) inline
Definition at line 78 of file DataBaseLogEntry.h.
KKB::DateTime MLL::DataBaseLogEntry::DateTimeStartUtc () const inline
Definition at line 64 of file DataBaseLogEntry.h.
Referenced by PicesInterface::PicesDataBaseLogEntry::!PicesDataBaseLogEntry(), MLL::DataBase::LogEntriesProcessStart(), and MLL::DataBase::LogEntriesSelect().
void MLL::DataBaseLogEntry::DateTimeStartUtc (const KKB::DateTime & _dateTimeStartUtc) inline
Definition at line 79 of file DataBaseLogEntry.h.
kkuint32 MLL::DataBaseLogEntry::LogEntryId () const inline
Definition at line 55 of file DataBaseLogEntry.h.
Referenced by PicesInterface::PicesDataBaseLogEntry::!PicesDataBaseLogEntry(), MLL::DataBase::LogEntriesProcessEnd(), MLL::DataBase::LogEntriesProcessStart(), MLL::DataBase::LogEntriesSelect(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void MLL::DataBaseLogEntry::LogEntryId (kkuint32 _logEntryId) inline
Definition at line 70 of file DataBaseLogEntry.h.
const KKStr& MLL::DataBaseLogEntry::ProgCode () const inline
Definition at line 56 of file DataBaseLogEntry.h.
Referenced by PicesInterface::PicesDataBaseLogEntry::!PicesDataBaseLogEntry(), MLL::DataBase::LogEntriesSelect(), and MLL::DataBaseLogEntryList::ProgCodeComparison::operator()().
void MLL::DataBaseLogEntry::ProgCode (const KKStr & _progCode) inline
Definition at line 71 of file DataBaseLogEntry.h.
const KKStr& MLL::DataBaseLogEntry::ProgName () const inline
Definition at line 57 of file DataBaseLogEntry.h.
Referenced by PicesInterface::PicesDataBaseLogEntry::!PicesDataBaseLogEntry(), and MLL::DataBase::LogEntriesSelect().
void MLL::DataBaseLogEntry::ProgName (const KKStr & _progName) inline
Definition at line 72 of file DataBaseLogEntry.h.
const KKStr& MLL::DataBaseLogEntry::SipperFileName () const inline
Definition at line 68 of file DataBaseLogEntry.h.
Referenced by PicesInterface::PicesDataBaseLogEntry::!PicesDataBaseLogEntry(), and MLL::DataBase::LogEntriesSelect().
void MLL::DataBaseLogEntry::SipperFileName (const KKStr & _sipperFileName) inline
Definition at line 83 of file DataBaseLogEntry.h.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/DataBaseLogEntry.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/DataBaseLogEntry.cpp