Pices: PicesInterface::PicesClassList Class Reference
PicesInterface::PicesClassList Class Reference
#include <PicesClassList.h>
Classes
class ClassNameComparitor
Public Member Functions
PicesClassList ()
PicesClassList (String^ _directory)
PicesClassList (PicesClassList^ _classes)
PicesClassList (const MLClassListPtr _classes)
Does NOT take ownership of '_classes'.
PicesClassList^ ExtractListOfClassesForAGivenHierarchialLevel (uint level)
PicesClassList^ ExtractMandatoryClasses ()
PicesClassList^ ExtractSummarizeClasses ()
Returns list of classes that are in this container that have the 'Summarize' flag set to true; these are classes that need to have a summary column printed in the classification report for themselves and any descendants they have.
array< String^ >^ ExtractThreeTitleLines ()
Will generate an array of 3 String's.
array< String^ >^ ExtractTwoTitleLines ()
Will generate an array of 2 String's.
PicesClass^ LookUpByName (String^ className)
PicesClass^ LookUpByUnmanagedClass (MLClassPtr unmanagedClass)
int LookUpIndex (PicesClass^ c)
void Save (String^ _directory)
void SortByName ()
MLClassListPtr ToMLClassConstList ()
Constructs a unmanaged instance of 'MLClassList' that caller will own and be responsible for deleting.
Static Public Member Functions
static PicesClassList^ CreateARootedEmptyClassList ()
static PicesClassList^ CreateFromCommaDelStr (String^ s)
static PicesClassList^ CreateFromDirectoryStructure (String^ directoryName)
static PicesClassList^ GetAllKnownClasses ()
static PicesClass^ GetUniqueClass (String^ _name, String^ _parentName)
Using the "_name" parameter will search the global ClassList(allClassesInUniverse) for an existing instance of 'PicesClass' that has the same name.
static PicesClass^ GetUniqueClass (MLClassPtr mlClass)
Will locate a PicesClass instance that has the same unmanaged mlClass reference.
static PicesClass^ GetUnKnownClassStatic ()
static void PicesClassList::UpdateParent (PicesClass^ srcClass, PicesClass^ destClass)
Static method that is meant to only work on 'allClassesInUniverse'.
Protected Member Functions
!PicesClassList ()
Properties
String^ Directory [get]
PicesClass^ RootNode [get, set]
Detailed Description
Definition at line 22 of file PicesClassList.h.
Constructor & Destructor Documentation
PicesClassList::PicesClassList ()
Definition at line 48 of file PicesClassList.cpp.
Referenced by CreateARootedEmptyClassList(), CreateFromCommaDelStr(), CreateFromDirectoryStructure(), ExtractListOfClassesForAGivenHierarchialLevel(), ExtractMandatoryClasses(), ExtractSummarizeClasses(), GetAllKnownClasses(), and GetUniqueClass().
PicesClassList::PicesClassList (String^ _directory)
Definition at line 60 of file PicesClassList.cpp.
References GetUniqueClass().
PicesClassList::PicesClassList (PicesClassList^ _classes)
Definition at line 80 of file PicesClassList.cpp.
PicesClassList::PicesClassList (const MLClassListPtr _classes)
Does NOT take ownership of '_classes'.
Definition at line 93 of file PicesClassList.cpp.
References GetUniqueClass().
PicesClassList::!PicesClassList () protected
Definition at line 116 of file PicesClassList.cpp.
Member Function Documentation
PicesClassList PicesClassList::CreateARootedEmptyClassList () static
Definition at line 138 of file PicesClassList.cpp.
References GetUniqueClass(), PicesClassList(), and RootNode.
PicesClassList PicesClassList::CreateFromCommaDelStr (String^ s) static
Definition at line 150 of file PicesClassList.cpp.
References GetUniqueClass(), and PicesClassList().
PicesClassList PicesClassList::CreateFromDirectoryStructure (String^ directoryName) static
Definition at line 222 of file PicesClassList.cpp.
References PicesClassList(), and RootNode.
PicesClassList PicesClassList::ExtractListOfClassesForAGivenHierarchialLevel (uint level)
Definition at line 606 of file PicesClassList.cpp.
References PicesInterface::PicesClass::MLClassForGivenHierarchialLevel(), and PicesClassList().
PicesClassList PicesClassList::ExtractMandatoryClasses ()
Definition at line 579 of file PicesClassList.cpp.
References PicesInterface::PicesClass::Mandatory, and PicesClassList().
PicesClassList PicesClassList::ExtractSummarizeClasses ()
Returns list of classes that are in this container that have the 'Summarize' flag set to true; these are classes that need to have a summary column printed in the classification report for themselves and any descendants they have.
Example if the 'Crustacea_Copepod' class has this field then there will be a column in the report that sums up all the Crustacea_Copepod's and their children.
Definition at line 592 of file PicesClassList.cpp.
References PicesClassList(), and PicesInterface::PicesClass::Summarize.
Referenced by PicesCommander.SizeDistribution2::PrintTabDelDistributionMatrixesForSummaryClasses().
array< String^ > PicesClassList::ExtractThreeTitleLines ()
Will generate an array of 3 String's.
Each String will represent a separate line to be uses as a Class name Header. Classes will be separated by the "tab('\t')" character. The underscore('_') character in the Class name will be used to deliminate what goes on which line. Ex: The class name "Crustacean_Copepod_Oncea" will have "Crustacean" on the 1st line, "Copepod" on the second line, and "Oncea" on the third line.
Definition at line 758 of file PicesClassList.cpp.
References KKB::Max(), and PicesInterface::PicesClass::Name.
Referenced by PicesInterface::ClassificationBiasMatrix::PrintAdjustedResults(), PicesInterface::PicesAbundanceCorrectionMatrix::PrintAdjustedResults(), PicesInterface::ClassificationBiasMatrix::PrintBiasMatrix(), and PicesCommander.SizeDistribution::PrintByClassCollumns().
array< String^ > PicesClassList::ExtractTwoTitleLines ()
Will generate an array of 2 String's.
Each String will represent a separate line to be uses as a Class name Header. Classes will be separated by the "tab('\t')" character. The underscore('_') character in the Class name will be used to deliminate what goes on which line. Ex: The class name "Crustacean_Copepod_Oncea" will have "Crustacean" on the 1st line and "Copepod-Oncea" on the second line.
Definition at line 719 of file PicesClassList.cpp.
References PicesInterface::PicesClass::Name.
Referenced by PicesCommander.SizeDistribution::PrintByClassCollumns().
PicesClassList PicesClassList::GetAllKnownClasses () static
Definition at line 453 of file PicesClassList.cpp.
References PicesInterface::PicesGoalKeeper::EndBlock(), PicesClassList(), and PicesInterface::PicesGoalKeeper::StartBlock().
Referenced by PicesCommander.SizeDistribution2::PrintTabDelDistributionMatrixesForSummaryClasses().
PicesClass PicesClassList::GetUniqueClass (String^ _name, String^ _parentName) static
Using the "_name" parameter will search the global ClassList(allClassesInUniverse) for an existing instance of 'PicesClass' that has the same name.
If one is found that is what is returned to the caller; otherwise a new instance is created and returned to the caller. This new instance will also be added to 'allClassesInUniverse'.
Definition at line 477 of file PicesClassList.cpp.
References PicesInterface::PicesGoalKeeper::EndBlock(), PicesClassList(), PicesInterface::PicesGoalKeeper::StartBlock(), and PicesInterface::PicesClass::UnmanagedMLClass().
Referenced by CreateARootedEmptyClassList(), CreateFromCommaDelStr(), GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters(), GetUniqueClass(), GetUnKnownClassStatic(), GradeTrainingModel.ConfusionMatrix::MakePrediction(), PicesInterface::PicesClass::MLClassForGivenHierarchialLevel(), PicesInterface::PicesTrainingConfigManaged::OtherClass(), PicesInterface::PicesClass::PicesClass(), PicesClassList(), PicesInterface::PicesFeatureVector::PicesFeatureVector(), PicesInterface::PicesPredictionList::PicesPredictionList(), PicesInterface::TrainingModel2::PredictClass(), and GradeTrainingModel.ConfusionMatrix::SetTrainingModel().
PicesClass PicesClassList::GetUniqueClass (MLClassPtr mlClass) static
Will locate a PicesClass instance that has the same unmanaged mlClass reference.
if none exists then will create a new one and add to 'allClassesInUniverse'.
Definition at line 521 of file PicesClassList.cpp.
References PicesInterface::PicesGoalKeeper::EndBlock(), GetUniqueClass(), PicesInterface::PicesKKStr::KKStrToSystenStr(), KKMLL::MLClass::ParentName(), PicesClassList(), and PicesInterface::PicesGoalKeeper::StartBlock().
PicesClass PicesClassList::GetUnKnownClassStatic () static
Definition at line 551 of file PicesClassList.cpp.
References GetUniqueClass().
Referenced by PicesCommander.SizeDistribution::Increment(), PicesCommander.SizeDistribution2::Increment(), PicesCommander.SizeDistribution::InitiateClass(), PicesCommander.SizeDistribution2::InitiateClass(), and PicesInterface::PicesFeatureVector::PicesFeatureVector().
PicesClass PicesClassList::LookUpByName (String^ className)
Definition at line 183 of file PicesClassList.cpp.
References PicesInterface::PicesClass::NameUpper.
PicesClass PicesClassList::LookUpByUnmanagedClass (MLClassPtr unmanagedClass)
Definition at line 199 of file PicesClassList.cpp.
References PicesInterface::PicesClass::UnmanagedMLClass().
Referenced by PicesInterface::PicesDataBase::MLClassLoadList(), and PicesInterface::TrainingModel2::PredictClass().
int PicesClassList::LookUpIndex (PicesClass^ c)
Definition at line 170 of file PicesClassList.cpp.
Referenced by PicesInterface::TrainingModel2::BinaryProbailitiesForClass(), and GradeTrainingModel.ConfusionMatrix::MakePrediction().
static void PicesInterface::PicesClassList::PicesClassList::UpdateParent (PicesClass^ srcClass, PicesClass^ destClass) static
Static method that is meant to only work on 'allClassesInUniverse'.
Example use would be when deleting or merging classes. We would want to redirect any class that has the srcClass as a parent to the destClass.
void PicesClassList::Save (String^ _directory)
Definition at line 212 of file PicesClassList.cpp.
void PicesClassList::SortByName ()
Definition at line 445 of file PicesClassList.cpp.
Referenced by PicesCommander.SizeDistribution2::PrintTabDelDistributionMatrixesForSummaryClasses().
MLClassListPtr PicesClassList::ToMLClassConstList ()
Constructs a unmanaged instance of 'MLClassList' that caller will own and be responsible for deleting.
Definition at line 126 of file PicesClassList.cpp.
References PicesInterface::PicesClass::UnmanagedMLClass().
Referenced by PicesInterface::PicesAbundanceCorrectionMatrix::PicesAbundanceCorrectionMatrix().
Property Documentation
String^ PicesInterface::PicesClassList::Directory get
Definition at line 40 of file PicesClassList.h.
PicesClass^ PicesInterface::PicesClassList::RootNode get set
Definition at line 41 of file PicesClassList.h.
Referenced by CreateARootedEmptyClassList(), CreateFromDirectoryStructure(), PicesInterface::PicesDataBase::MLClassLoadList(), and SipperFile.SelectAPicesClass::SelectAPicesClass().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesInterface/PicesClassList.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesInterface/PicesClassList.cpp