Pices: PicesInterface::PicesSipperStation Class Reference
PicesInterface::PicesSipperStation Class Reference
#include <PicesSipperStation.h>
Public Member Functions
PicesSipperStation (SipperStationPtr _station)
PicesSipperStation (PicesSipperCruise^ _cruise)
Creating a new station that will belong to '_cruise'.
SipperStationPtr UnmanagedClass ()
Protected Member Functions
!PicesSipperStation ()
Properties
String^ CruiseName [get, set]
System::DateTime DateTimeStart [get, set]
String^ Description [get, set]
String^ GPSString [get]
double Latitude [get, set]
double Longitude [get, set]
String^ StationName [get, set]
Detailed Description
Definition at line 19 of file PicesSipperStation.h.
Constructor & Destructor Documentation
PicesSipperStation::PicesSipperStation (SipperStationPtr _station)
Definition at line 35 of file PicesSipperStation.cpp.
Referenced by PicesSipperStation().
PicesSipperStation::PicesSipperStation (PicesSipperCruise^ _cruise)
Creating a new station that will belong to '_cruise'.
Definition at line 42 of file PicesSipperStation.cpp.
References MLL::SipperStation::CruiseName(), MLL::SipperCruise::CruiseName(), PicesSipperStation(), and PicesInterface::PicesSipperCruise::UnmanagedSipperCruise().
PicesSipperStation::!PicesSipperStation () protected
Definition at line 57 of file PicesSipperStation.cpp.
References PicesInterface::PicesMethods::DateTimeKKUtoSystem(), MLL::SipperStation::DateTimeStart(), PicesInterface::PicesMethods::DateTimeSystemToKKU(), MLL::SipperStation::Latitude(), PicesInterface::PicesMethods::LatitudeLongitudeToString(), and MLL::SipperStation::Longitude().
Member Function Documentation
SipperStationPtr PicesInterface::PicesSipperStation::UnmanagedClass () inline
Definition at line 53 of file PicesSipperStation.h.
Referenced by PicesInterface::PicesDataBase::SipperStationInsert(), and PicesInterface::PicesDataBase::SipperStationUpdate().
Property Documentation
String^ PicesInterface::PicesSipperStation::CruiseName get set
Definition at line 38 of file PicesSipperStation.h.
Referenced by SipperFile.StationDialog::StationDialog(), SipperFile.TreeNodeStation::ToString(), and SipperFile.TreeNodeStation::TreeNodeStation().
System:: DateTime PicesInterface::PicesSipperStation::DateTimeStart get set
Definition at line 49 of file PicesSipperStation.h.
Referenced by SipperFile.StationDialog::StationDialog(), and SipperFile.TreeNodeStation::ToString().
String^ PicesInterface::PicesSipperStation::Description get set
Definition at line 42 of file PicesSipperStation.h.
Referenced by SipperFile.StationDialog::StationDialog(), and SipperFile.TreeNodeStation::ToString().
String^ PicesInterface::PicesSipperStation::GPSString get
Definition at line 51 of file PicesSipperStation.h.
Referenced by SipperFile.TreeNodeStation::ToString().
double PicesInterface::PicesSipperStation::Latitude get set
Definition at line 46 of file PicesSipperStation.h.
Referenced by PicesCommander.ChartGPS::ChartGPS(), PicesCommander.ChartGPSByStation::ChartGPSByStation(), SipperFile.StationDialog::StationDialog(), and SipperFile.TreeNodeStation::ToString().
double PicesInterface::PicesSipperStation::Longitude get set
Definition at line 47 of file PicesSipperStation.h.
Referenced by PicesCommander.ChartGPS::ChartGPS(), PicesCommander.ChartGPSByStation::ChartGPSByStation(), SipperFile.StationDialog::StationDialog(), and SipperFile.TreeNodeStation::ToString().
String^ PicesInterface::PicesSipperStation::StationName get set
Definition at line 34 of file PicesSipperStation.h.
Referenced by PicesCommander.ChartGPS::ChartGPS(), PicesCommander.ChartGPSByStation::ChartGPSByStation(), PicesCommander.PicesCommander::GetThumbnailImageAbort(), PicesCommander.ImportImagesIntoDeployment::ImportImagesIntoDeployment(), PicesInterface::PicesSipperStationList::LookUpByStationName(), SipperFile.StationDialog::StationDialog(), SipperFile.TreeNodeStation::ToString(), and SipperFile.TreeNodeStation::TreeNodeStation().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesSipperStation.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesSipperStation.cpp