Pices: C:/Users/Kurt/GitHub/Pices/Apps/FeatureSelection/FeatureSelection.cpp File Reference
FeatureSelection.cpp File Reference
#include "FirstIncludes.h"
#include <stdlib.h>
#include <crtdbg.h>
#include <stdio.h>
#include <ctype.h>
#include <time.h>
#include <fcntl.h>
#include <string>
#include <iomanip>
#include <iostream>
#include <fstream>
#include <map>
#include <vector>
#include <ostream>
#include "MemoryDebug.h"
#include <sys/types.h>
#include <io.h>
#include <windows.h>
#include "KKBaseTypes.h"
#include "HTMLReport.h"
#include "OSservices.h"
#include "RunLog.h"
#include "StatisticalFunctions.h"
#include "Instrument.h"
#include "InstrumentDataList.h"
#include "InstrumentDataFileManager.h"
#include "BinaryClassParms.h"
#include "ConfusionMatrix2.h"
#include "FeatureFileIO.h"
#include "NormalizationParms.h"
#include "FeatureFileIOPices.h"
#include "AccByFeatureSel.h"
#include "BinaryClass.h"
#include "BinaryJob.h"
#include "FeatureImpact.h"
#include "FinalResults.h"
#include "FeatureSelection.h"
#include "Processor.h"
Macros
#define _CRTDBG_MAP_ALLOC
Functions
bool AllBinaryClassesAreDone (BinaryClassListPtr binaryClasses)
void CalcClassPairWeighted (VectorDouble &counts, VectorInt &exampleCountPerClassPair, double &weightedCount)
int main (int argc, char **argv)
void ReportDataSpecs (ostream &r, const KKStr &fileName, FeatureVectorListPtr data)
void Test ()
Macro Definition Documentation
#define _CRTDBG_MAP_ALLOC
Definition at line 4 of file FeatureSelection.cpp.
Function Documentation
bool AllBinaryClassesAreDone (BinaryClassListPtr binaryClasses)
Definition at line 368 of file FeatureSelection.cpp.
References FeatureSelectionApp::BfsFeatureSelection, FeatureSelectionApp::BfsParmTuningPost, FeatureSelectionApp::BfsParmTuningPre, FeatureSelectionApp::Done, KKB::endl(), FeatureSelectionApp::FeatureSelectionSearch, FeatureSelectionApp::GenerateBruitSvmSearch, FeatureSelectionApp::GenerateFinalResults, KKB::RunLog::Level(), FeatureSelectionApp::MajorStepToStr(), FeatureSelectionApp::MfsFeatureSelection, FeatureSelectionApp::MfsParmTuningPost, FeatureSelectionApp::MfsParmTuningPre, FeatureSelectionApp::Null, FeatureSelectionApp::BinaryClass::NumProcessors(), KKB::osWaitForEnter(), FeatureSelectionApp::ParameterSearch, and FeatureSelectionApp::BinaryClass::Status().
Referenced by FeatureSelectionApp::FeatureSelection::ProcessStatusFile(), and ReportDataSpecs().
void CalcClassPairWeighted (VectorDouble & counts, VectorInt & exampleCountPerClassPair, double & weightedCount)
Definition at line 1837 of file FeatureSelection.cpp.
References KKMLL::TrainingConfiguration2::A_Param(), FeatureSelectionApp::ProcessorCycles::AddCycles(), KKMLL::BinaryClassParms::AParam(), FeatureSelectionApp::Processor::BeamSearchFeatureCount(), FeatureSelectionApp::BestCaseNext, FeatureSelectionApp::BfsParmTuningPost, KKMLL::BinaryClassParms::C(), KKMLL::TrainingConfiguration2::C_Param(), KKB::CalcVectorStats(), FeatureSelectionApp::BinaryClass::Class1(), FeatureSelectionApp::BinaryClass::Class1Name(), FeatureSelectionApp::BinaryClass::Class2(), FeatureSelectionApp::BinaryClass::Class2Name(), FeatureSelectionApp::Processor::CpuCyclesByProcId(), FeatureSelectionApp::Done, FeatureSelectionApp::FeatureSelection::EndBlock(), KKB::endl(), KKMLL::TrainingConfiguration2::ExtractClassList(), FeatureSelectionApp::FeatureSelectionSearch, FeatureSelectionApp::BinaryClass::FinalResultsFileName(), KKB::Configuration::FormatGood(), SVM233::svm_parameter::Gamma(), KKMLL::TrainingConfiguration2::Gamma(), FeatureSelectionApp::GenerateBruitSvmSearch, FeatureSelectionApp::GenerateFinalResults, KKMLL::TrainingConfiguration2::GetBinaryClassParms(), KKMLL::FeatureVectorList::GetClassCount(), FeatureSelectionApp::Processor::GetCpuCyclesByFeatureCount(), KKMLL::TrainingConfiguration2::GetFeatureNums(), FeatureSelectionApp::Processor::GetSmallestJobIdByFeatureCount(), INT_MAX, KKB::RunLog::Level(), KKMLL::TrainingConfiguration2::Load(), FeatureSelectionApp::FeatureSelection::LoadFeatureData(), max, FeatureSelectionApp::MfsFeatureSelection, FeatureSelectionApp::MfsParmTuningPre, min, FeatureSelectionApp::Processor::NextJobId(), NotStarted, FeatureSelectionApp::NotStarted, FeatureSelectionApp::Null, KKMLL::FileDesc::NumOfFields(), FeatureSelectionApp::BinaryClass::NumProcessors(), KKMLL::FeatureNumList::NumSelFeatures(), KKB::osDeleteFile(), KKB::osFOPEN(), KKB::osGetRootName(), KKMLL::BinaryClassParms::Param(), FeatureSelectionApp::ParameterSearch, FeatureSelectionApp::Processor::ProcessRestart(), FeatureSelectionApp::Processor::QuitRunning(), FeatureSelectionApp::ProcessorCycles::Report(), FeatureSelectionApp::BinaryClass::ResultType(), KKMLL::BinaryClassParms::SelectedFeatures(), FeatureSelectionApp::Started, FeatureSelectionApp::BinaryClass::Status(), FeatureSelectionApp::Processor::Status(), KKB::KKStr::Str(), and FeatureSelectionApp::Processor::TotalCpuTimeUsed().
int main (int argc, char ** argv)
Definition at line 4067 of file FeatureSelection.cpp.
References FeatureSelectionApp::FeatureSelection::FeatureSelection(), KKB::osRunAsABackGroundProcess(), FeatureSelectionApp::FeatureSelection::Run(), and Test().
void ReportDataSpecs (ostream & r, const KKStr & fileName, FeatureVectorListPtr data)
Definition at line 2714 of file FeatureSelection.cpp.
References AllBinaryClassesAreDone(), FeatureSelectionApp::AccByFeatureSel::AvgAccGain(), FeatureSelectionApp::BestCaseNext, FeatureSelectionApp::BfsFeatureSelection, FeatureSelectionApp::BfsParmTuningPost, FeatureSelectionApp::BfsParmTuningPre, FeatureSelectionApp::FeatureSelection::Block(), FeatureSelectionApp::FeatureSelection::BuildResultConfigFile(), FeatureSelectionApp::BinaryClass::Class1(), FeatureSelectionApp::Processor::Class1(), FeatureSelectionApp::AccByFeatureSel::Class1Name(), FeatureSelectionApp::BinaryClass::Class1Name(), FeatureSelectionApp::Processor::Class1Name(), FeatureSelectionApp::BinaryClass::Class2(), FeatureSelectionApp::Processor::Class2(), FeatureSelectionApp::AccByFeatureSel::Class2Name(), FeatureSelectionApp::BinaryClass::Class2Name(), FeatureSelectionApp::Processor::Class2Name(), KKB::HTMLReport::Close(), FeatureSelectionApp::FinalResults::ConfusionMatrix(), FeatureSelectionApp::BinaryClass::DecrementNumProcessors(), FeatureSelectionApp::FinalResults::Description(), FeatureSelectionApp::Done, KKB::KKStr::Empty(), FeatureSelectionApp::FeatureSelection::EndBlock(), KKB::endl(), KKMLL::TrainingConfiguration2::ExtractClassList(), FeatureSelectionApp::FeatureCriteriaToStr(), FeatureSelectionApp::AccByFeatureSel::FeatureNum(), KKMLL::FileDesc::FieldName(), FeatureSelectionApp::BinaryClass::FinalResultsFileName(), KKB::Configuration::FormatGood(), FeatureSelectionApp::GenerateBruitSvmSearch, FeatureSelectionApp::GenerateFinalResults, FeatureSelectionApp::Processor::GetFeatureImpact(), FeatureSelectionApp::GradingMethodToStr(), FeatureSelectionApp::Hall, FeatureSelectionApp::FinalResults::HeaderLineHTML1(), FeatureSelectionApp::FinalResults::HeaderLineHTML2(), KKB::KKQueue< Entry >::IdxToPtr(), FeatureSelectionApp::BinaryClass::IncrementNumProcessors(), FeatureSelectionApp::JobSelectionCriteriaToStr(), KKB::RunLog::Level(), FeatureSelectionApp::FinalResults::LinkName(), KKMLL::FeatureFileIO::LoadFeatureFile(), KKB::McNemarsTest(), FeatureSelectionApp::MfsFeatureSelection, FeatureSelectionApp::MfsParmTuningPost, FeatureSelectionApp::MfsParmTuningPre, KKMLL::NormalizationParms::NormalizeExamples(), NotStarted, FeatureSelectionApp::NotStarted, FeatureSelectionApp::Null, FeatureSelectionApp::BinaryClass::NumProcessors(), KKB::osGetCurrentDirectory(), KKB::osGetFileDateTime(), KKB::osGetFileSize(), KKB::osGetLocalDateTime(), KKB::osRemoveExtension(), KKB::osSleep(), KKB::HTMLReport::OStream(), KKB::osWaitForEnter(), KKB::PairedTTest(), FeatureSelectionApp::FinalResults::PrintAccuraciesByClassSummary(), KKMLL::ConfusionMatrix2::PrintAccuracyByProbByClassHTML(), KKMLL::FeatureVectorList::PrintClassStatistics(), KKMLL::FeatureVectorList::PrintClassStatisticsHTML(), FeatureSelectionApp::FinalResults::PrintConfigParametersRandomSplitsHTML(), FeatureSelectionApp::FinalResults::PrintConfigParametersValidationHTML(), KKMLL::ConfusionMatrix2::PrintConfusionMatrixAvgPredProbHTML(), KKMLL::ConfusionMatrix2::PrintConfusionMatrixHTML(), FeatureSelectionApp::ProcessingOrderToStr(), KKB::KKQueue< Entry >::QueueSize(), FeatureSelectionApp::FinalResults::RandomSplitAccuracies(), FeatureSelectionApp::BinaryClass::ResultType(), FeatureSelectionApp::AccByFeatureSelList::SortByFeatureNumThenByClassCombo(), FeatureSelectionApp::Standard, FeatureSelectionApp::Started, FeatureSelectionApp::BinaryClass::Status(), FeatureSelectionApp::AccByFeatureSel::StdDevAccGain(), KKB::StrFormatDouble(), FeatureSelectionApp::Processor::SummaryResultsFileName(), FeatureSelectionApp::FinalResults::ToHTMLStr(), FeatureSelectionApp::FeatureImpact::UpdateAccByFeatureSelList(), FeatureSelectionApp::FinalResults::ValidationClassedCorrectly(), FeatureSelectionApp::FinalResults::ValidationClassedCorrectlySize(), and FeatureSelectionApp::FinalResults::ValidationConfusionMatrix().
void Test ()
Definition at line 4029 of file FeatureSelection.cpp.
References KKB::endl().
Referenced by _(), GetProcessId(), and main().