Pices: PicesInterface::PicesDataBaseImageList Class Reference
PicesInterface::PicesDataBaseImageList Class Reference
#include <PicesDataBaseImage.h>
Public Types
enum SortOrderType {
SortOrderType::soNULL, SortOrderType::soBreakTie, SortOrderType::soClassName, SortOrderType::soDepth,
SortOrderType::soProbability, SortOrderType::soClass2, SortOrderType::soSize, SortOrderType::soSpatial,
SortOrderType::soValidatedClassName
}
Public Member Functions
PicesDataBaseImageList ()
PicesDataBaseImageList (DataBaseImageListPtr unmanagedImages)
!PicesDataBaseImageList ()
~PicesDataBaseImageList ()
void AddList (PicesDataBaseImageList^ list)
void CleanUpMemory ()
PicesDataBaseImageList^ ExtractExamplesForAGivenClass (PicesClass^ _class)
PicesClassList^ ExtractListOfClasses ()
void RandomizeOrder ()
void Sort (SortOrderType _sortOrder, bool _reverseSort)
Static Public Member Functions
static void PopulateComboBoxWithSortOrderOptions (ComboBox^ cb)
static SortOrderType SortOrderTypeFromStr (String^ s)
static array< SortOrderType >^ SortOrderTypeList ()
static String^ SortOrderTypeToStr (SortOrderType so)
Detailed Description
Definition at line 83 of file PicesDataBaseImage.h.
Member Enumeration Documentation
enum PicesInterface::PicesDataBaseImageList::SortOrderType strong
Enumerator
soNULL
soBreakTie
soClassName
soDepth
soProbability
soClass2
soSize
soSpatial
soValidatedClassName
Definition at line 93 of file PicesDataBaseImage.h.
Constructor & Destructor Documentation
PicesDataBaseImageList::PicesDataBaseImageList ()
Definition at line 261 of file PicesDataBaseImage.cpp.
PicesDataBaseImageList::PicesDataBaseImageList (DataBaseImageListPtr unmanagedImages)
Definition at line 267 of file PicesDataBaseImage.cpp.
References KKB::KKQueue< Entry >::Owner(), and PicesInterface::PicesDataBaseImage::PicesDataBaseImage().
PicesDataBaseImageList::~PicesDataBaseImageList ()
Definition at line 284 of file PicesDataBaseImage.cpp.
PicesDataBaseImageList::!PicesDataBaseImageList ()
Definition at line 290 of file PicesDataBaseImage.cpp.
Member Function Documentation
void PicesDataBaseImageList::AddList (PicesDataBaseImageList^ list)
Definition at line 304 of file PicesDataBaseImage.cpp.
Referenced by PicesCommander.PicesCommander::ThumbnailDataGridView_CellContentDoubleClick(), and PicesCommander.PicesCommander::UpdateLastClassesValidated().
void PicesDataBaseImageList::CleanUpMemory ()
Definition at line 297 of file PicesDataBaseImage.cpp.
Referenced by PicesCommander.PlanktonImageLoader::CleanUpMemory().
PicesDataBaseImageList PicesDataBaseImageList::ExtractExamplesForAGivenClass (PicesClass^ _class)
Definition at line 351 of file PicesDataBaseImage.cpp.
References PicesInterface::PicesDataBaseImage::Class1, PicesInterface::PicesDataBaseImage::Class1Name, PicesInterface::PicesDataBaseImage::Class1Prob, PicesInterface::PicesDataBaseImage::CompareBreakTie(), PicesInterface::PicesDataBaseImage::CompareClass2(), PicesInterface::PicesDataBaseImage::CompareDepth(), PicesInterface::PicesDataBaseImage::CompareSpatially(), PicesInterface::PicesDataBaseImage::PixelCount, PicesInterface::PicesDataBaseImage::SipperFileName, PicesInterface::PicesDataBaseImage::TopLeftRow, and PicesInterface::PicesDataBaseImage::ValidatedClassName.
Referenced by PicesCommander.SavePlanktonData::SavePlanktonData().
PicesClassList PicesDataBaseImageList::ExtractListOfClasses ()
Definition at line 314 of file PicesDataBaseImage.cpp.
References PicesInterface::PicesDataBaseImage::Class1.
Referenced by PicesCommander.SavePlanktonData::SavePlanktonData().
void PicesDataBaseImageList::PopulateComboBoxWithSortOrderOptions (ComboBox^ cb) static
Definition at line 494 of file PicesDataBaseImage.cpp.
Referenced by PicesCommander.PicesCommander::PicesCommander().
void PicesDataBaseImageList::RandomizeOrder ()
Definition at line 328 of file PicesDataBaseImage.cpp.
Referenced by PicesCommander.SavePlanktonData::SavePlanktonData().
void PicesDataBaseImageList::Sort (SortOrderType _sortOrder, bool _reverseSort)
Definition at line 423 of file PicesDataBaseImage.cpp.
Referenced by PicesCommander.SaveImagesToDisk::SaveImagesToDisk(), PicesCommander.SaveImagesToDisk2::SaveImagesToDisk2(), PicesCommander.SavePlanktonData::SavePlanktonData(), PicesCommander.PicesCommander::ThumbnailDataGridView_CellContentDoubleClick(), and PicesCommander.PicesCommander::UpdateLastClassesValidated().
PicesDataBaseImageList::SortOrderType PicesDataBaseImageList::SortOrderTypeFromStr (String^ s) static
Definition at line 457 of file PicesDataBaseImage.cpp.
Referenced by PicesCommander.PicesCommander::ThumbnailDataGridView_CellContentDoubleClick().
array< PicesDataBaseImageList::SortOrderType > PicesDataBaseImageList::SortOrderTypeList () static
Definition at line 476 of file PicesDataBaseImage.cpp.
String PicesDataBaseImageList::SortOrderTypeToStr (SortOrderType so) static
Definition at line 435 of file PicesDataBaseImage.cpp.
Referenced by PicesCommander.PicesCommander::PicesCommander().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesDataBaseImage.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesDataBaseImage.cpp