Pices: ImageExtractionManager::ExtractedImageQueue Class Reference
ImageExtractionManager::ExtractedImageQueue Class Reference
#include <ExtractedImage.h>
Public Member Functions
ExtractedImageQueue ()
~ExtractedImageQueue ()
void AddExtractedImage (ExtractedImagePtr extractedImage)
void AddExtractedImages (VectorExtractedImage &extractedImages)
ExtractedImagePtr GetNextExtractedImage ()
kkuint32 ImagesOnQueue ()
kkint32 MemoryConsumedEstimated () const
Detailed Description
Definition at line 95 of file ExtractedImage.h.
Constructor & Destructor Documentation
ExtractedImageQueue::ExtractedImageQueue ()
Definition at line 107 of file ExtractedImage.cpp.
ExtractedImageQueue::~ExtractedImageQueue ()
Definition at line 116 of file ExtractedImage.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
Member Function Documentation
void ExtractedImageQueue::AddExtractedImage (ExtractedImagePtr extractedImage)
Definition at line 151 of file ExtractedImage.cpp.
References KKB::GoalKeeper::EndBlock(), KKB::osSleep(), and KKB::GoalKeeper::StartBlock().
Referenced by ImageExtractionManager::FrameProcessorThread::GetRunTimeStats().
void ExtractedImageQueue::AddExtractedImages (VectorExtractedImage & extractedImages)
Definition at line 170 of file ExtractedImage.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
ExtractedImagePtr ExtractedImageQueue::GetNextExtractedImage ()
Definition at line 188 of file ExtractedImage.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
Referenced by ImageExtractionManager::DataBaseUpdateThread::GetRunTimeStats().
kkuint32 ExtractedImageQueue::ImagesOnQueue ()
Definition at line 203 of file ExtractedImage.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
Referenced by ImageExtractionManager::ExtractionManager::GetRunTimeStats().
kkint32 ExtractedImageQueue::MemoryConsumedEstimated () const
Definition at line 134 of file ExtractedImage.cpp.
References KKB::GoalKeeper::EndBlock(), ImageExtractionManager::ExtractedImage::MemoryConsumedEstimated(), and KKB::GoalKeeper::StartBlock().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/ImageExtractionManager/ExtractedImage.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/ImageExtractionManager/ExtractedImage.cpp