Pices: PicesInterface::PicesSipperVariables Class Reference
PicesInterface::PicesSipperVariables Class Reference
#include <PicesSipperVariables.h>
Public Member Functions
PicesSipperVariables ()
Static Public Member Functions
static bool AllowUpdates ()
'True' indicates that user is allowed to peofrom updates.
static String^ CmdLineProgDir ()
static String^ ConfigrationFileName ()
static String^ ConfigurationDirectory ()
static String^ DataFileDirectory ()
static String^ DataFilesDirectory ()
static String^ HomeDir ()
static void InitializeEnvironment ()
static String^ InstrumentDataFilesDir ()
static String^ PicesReportDir ()
static String^ SipperDirectoryListFileName ()
static String^ SipperFilesDefaultDir ()
static String^ SipperFilesDirectory ()
static String^ SipperInterfaceDir ()
static String^ SipperInterfaceLogDir ()
static String^ TempDirectory ()
static String^ TrainingModelsConfigurationDir ()
static void UpdatesNotAllowed (String^ caption)
Detailed Description
Definition at line 19 of file PicesSipperVariables.h.
Constructor & Destructor Documentation
PicesSipperVariables::PicesSipperVariables (void)
Definition at line 47 of file PicesSipperVariables.cpp.
Member Function Documentation
bool PicesSipperVariables::AllowUpdates () static
'True' indicates that user is allowed to peofrom updates.
Definition at line 60 of file PicesSipperVariables.cpp.
Referenced by PicesCommander.ClassificationStatus::ClassificationStatus(), PicesCommander.ClassMaintenance::ClassMaintenance(), SipperFile.CruiseDialog::CruiseDialog(), SipperFile.CruiseMaintenance::CruiseMaintenance(), SipperFile.DeploymentDialog::DeploymentDialog(), SipperFile.GroupMaintenance::GroupMaintenance(), PicesCommander.PicesCommander::PicesCommander(), SipperFile.SipperFileDialog::SipperFileDialog(), SipperFile.StationDialog::StationDialog(), SipperFile.TreeNodeCruise::ToString(), SipperFile.TreeNodeStation::ToString(), SipperFile.TreeNodeCruise::TreeNodeCruise(), SipperFile.TreeNodeDeployment::TreeNodeDeployment(), and SipperFile.TreeNodeStation::TreeNodeStation().
String PicesSipperVariables::CmdLineProgDir () static
Definition at line 93 of file PicesSipperVariables.cpp.
Referenced by PicesCommander.PicesCommander::ThumbnailDataGridView_CellContentDoubleClick().
String PicesSipperVariables::ConfigrationFileName () static
Definition at line 114 of file PicesSipperVariables.cpp.
Referenced by SipperFile.SipperConfigRec::SipperConfigRec().
String PicesSipperVariables::ConfigurationDirectory () static
Definition at line 86 of file PicesSipperVariables.cpp.
Referenced by PicesCommander.ChartAbundanceByDeployment::ChartAbundanceByDeployment(), PicesCommander.ChartAbundancePredictedAndValidated::ChartAbundancePredictedAndValidated(), PicesCommander.ChartDistribution::ChartDistribution(), PicesCommander.ChartGPS::ChartGPS(), PicesCommander.ChartGPSByStation::ChartGPSByStation(), PicesCommander.ChartHorizontalProfile::ChartHorizontalProfile(), PicesCommander.ChartSizeDistribution::ChartSizeDistribution(), PicesCommander.ClassDepthProfileChart::ClassDepthProfileChart(), SipperFile.DepthPlot2::DepthPlot2(), GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters(), SipperFile.ImageViewer::ImageViewer(), PicesCommander.ImportImagesIntoDeployment::ImportImagesIntoDeployment(), PicesCommander.PicesCommander::PicesCommander(), SipperFile.SipperConfigRec::SipperConfigRec(), and SipperFile.TimePlot::TimePlot().
String PicesSipperVariables::DataFileDirectory () static
Definition at line 100 of file PicesSipperVariables.cpp.
String PicesSipperVariables::DataFilesDirectory () static
Definition at line 107 of file PicesSipperVariables.cpp.
Referenced by PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets().
String PicesSipperVariables::HomeDir () static
Definition at line 80 of file PicesSipperVariables.cpp.
Referenced by PicesCommander.ImportGroupAssignments::ImportGroupAssignments(), PicesCommander.ImportImagesIntoDeployment::ImportImagesIntoDeployment(), PicesCommander.ImportValidatdClass::ImportValidatdClass(), PicesInterface::TrainingModel2::LastRunLogTextLine(), PicesCommander.PicesCommander::PicesCommander(), PicesCommander.SaveImagesToDisk::SaveImagesToDisk(), PicesCommander.SaveImagesToDisk2::SaveImagesToDisk2(), and PicesCommander.TrainingModelCreateFromDirectory::TrainingModelCreateFromDirectory().
void PicesSipperVariables::InitializeEnvironment () static
Definition at line 53 of file PicesSipperVariables.cpp.
String PicesSipperVariables::InstrumentDataFilesDir () static
Definition at line 73 of file PicesSipperVariables.cpp.
String PicesSipperVariables::PicesReportDir () static
Definition at line 121 of file PicesSipperVariables.cpp.
Referenced by PicesCommander.ChartSizeDistribution::ChartSizeDistribution(), PicesCommander.ClassificationStatus::ClassificationStatus(), PicesCommander.InstrumentDataByDeploymentProfile::InstrumentDataByDeploymentProfile(), PicesCommander.SaveFeatureData::SaveFeatureData(), PicesCommander.SavePlanktonData::SavePlanktonData(), and PicesCommander.PicesCommander::ThumbnailDataGridView_CellContentDoubleClick().
String PicesSipperVariables::SipperDirectoryListFileName () static
Definition at line 135 of file PicesSipperVariables.cpp.
String PicesSipperVariables::SipperFilesDefaultDir () static
Definition at line 141 of file PicesSipperVariables.cpp.
String PicesSipperVariables::SipperFilesDirectory () static
Definition at line 147 of file PicesSipperVariables.cpp.
Referenced by SipperFile.DeploymentDialog::DeploymentDialog(), and SipperFileViewer.SipperFileViewer::SipperFileViewerRegionAroundImage().
String PicesSipperVariables::SipperInterfaceDir () static
Definition at line 153 of file PicesSipperVariables.cpp.
Referenced by SipperFile.SipperConfigRec::Load(), and SipperFile.InstrumentDataList::StartNewDataFile().
String PicesSipperVariables::SipperInterfaceLogDir () static
Definition at line 159 of file PicesSipperVariables.cpp.
Referenced by SipperDiskUtilities.SipperDisk::SipperDisk().
String PicesSipperVariables::TempDirectory () static
Definition at line 128 of file PicesSipperVariables.cpp.
Referenced by PicesInterface::TrainingModel2::AttachMsgQueueToRunLog(), PicesInterface::PicesRunLog::CreateRunLog(), PicesCommander.ImportGroupAssignments::ImportGroupAssignments(), PicesCommander.InstrumentDataByDeploymentProfile::InstrumentDataByDeploymentProfile(), PicesCommander.ReconcileImagesToDataBase::ReconcileImagesToDataBase(), PicesCommander.SaveActiveTrainingModelFeatureData::SaveActiveTrainingModelFeatureData(), and PicesCommander.PicesCommander::ThumbnailDataGridView_CellContentDoubleClick().
String PicesSipperVariables::TrainingModelsConfigurationDir () static
Definition at line 167 of file PicesSipperVariables.cpp.
Referenced by PicesCommander.TrainingModelCreateFromDirectory::TrainingModelCreateFromDirectory().
void PicesSipperVariables::UpdatesNotAllowed (String^ caption) static
Definition at line 66 of file PicesSipperVariables.cpp.
Referenced by SipperFile.CruiseDialog::CruiseDialog(), SipperFile.DeploymentDialog::DeploymentDialog(), SipperFile.GroupMaintenance::GroupMaintenance(), SipperFile.SipperFileDialog::SipperFileDialog(), and PicesCommander.PicesCommander::ThumbnailDataGridView_CellContentDoubleClick().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesSipperVariables.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesSipperVariables.cpp