Pices: C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.cpp File Reference
XmlStream.cpp File Reference
#include "FirstIncludes.h"
#include <stdio.h>
#include <fstream>
#include <string.h>
#include <string>
#include <iostream>
#include <ostream>
#include <vector>
#include "MemoryDebug.h"
#include "BitString.h"
#include "GlobalGoalKeeper.h"
#include "KKBaseTypes.h"
#include "KKException.h"
#include "KKStrParser.h"
#include "XmlTokenizer.h"
#include "XmlStream.h"
Macros
#define XmlElementArray2DBody(T, TypeName, XmlElementToUse)
#define XmlElementArrayBody(T, TypeName, ParserNextTokenMethod)
#define XmlElementBuiltInTypeBody(T, TypeName, ParseMethod)
#define XmlElementVectorBody(T, TypeName, ParserNextTokenMethod)
Functions
void ExtractAttribute (KKStr &tagStr, KKStr &attributeName, KKStr &attributeValue)
void ReadWholeTag (istream &i, KKStr &tagStr)
ToInt32 ToDouble GetNextTokenUint XmlElementArrayBody (kkint32, ArrayInt32, GetNextTokenInt) XmlElementArrayBody(double
ToInt32 ToDouble GetNextTokenUint GetNextTokenDouble XmlElementArrayBody (float, ArrayFloat, GetNextTokenDouble) XmlElementArray2DBody(float
ToInt32 XmlElementBuiltInTypeBody (kkint64, Int64, ToInt64) XmlElementBuiltInTypeBody(float
ToInt32 ToDouble XmlElementBuiltInTypeBody (double, Double, ToDouble) XmlElementArrayBody(kkuint16
ToInt32 ToDouble GetNextTokenUint GetNextTokenDouble XmlElementArrayFloat XmlElementVectorBody (kkint32, VectorInt32, GetNextTokenInt) XmlElementVectorBody(float
XmlFactoryMacro (Bool) XmlElementUnKnown
XmlFactoryMacro (UnKnown) XmlFactoryPtr KKB
XmlFactoryMacro (DateTime) XmlElementKeyValuePairs
XmlFactoryMacro (KeyValuePairs) XmlElementArrayFloat2DVarying
XmlFactoryMacro (ArrayFloat2DVarying) XmlFactoryMacro(KKStr) XmlFactoryPtr KKB
XmlFactoryMacro (VectorKKStr) XmlFactoryMacro(KKStrList) XmlFactoryMacro(KKStrListIndexed) XmlElementBuiltInTypeBody(kkint32
Works with matching Marco (XmlElementBuiltInTypeHeader) defined in XmlStream.h.
Variables
ToInt32 ToDouble GetNextTokenUint ArrayDouble
ToInt32 ToDouble GetNextTokenUint GetNextTokenDouble ArrayFloat2D
ToInt32 ToDouble ArrayUint16
ToInt32 Float
Int32
ToInt32 ToDouble GetNextTokenUint GetNextTokenDouble XmlElementArrayFloat VectorFloat
kkint32 xmlLevel = 0
Macro Definition Documentation
#define XmlElementArray2DBody (T, TypeName, XmlElementToUse)
#define XmlElementArrayBody (T, TypeName, ParserNextTokenMethod)
#define XmlElementBuiltInTypeBody (T, TypeName, ParseMethod)
#define XmlElementVectorBody (T, TypeName, ParserNextTokenMethod)
Function Documentation
void ExtractAttribute (KKStr & tagStr, KKStr & attributeName, KKStr & attributeValue)
Definition at line 412 of file XmlStream.cpp.
References KKB::KKStr::Len(), and KKB::KKStr::SubStrPart().
Referenced by KKB::XmlTag::XmlTag().
void ReadWholeTag (istream & i, KKStr & tagStr)
Definition at line 390 of file XmlStream.cpp.
References KKB::KKStr::Append().
Referenced by KKB::XmlTag::XmlTag().
ToInt32 ToDouble GetNextTokenUint XmlElementArrayBody (kkint32 , ArrayInt32 , GetNextTokenInt)
ToInt32 ToDouble GetNextTokenUint GetNextTokenDouble XmlElementArrayBody (float , ArrayFloat , GetNextTokenDouble)
ToInt32 XmlElementBuiltInTypeBody (kkint64 , Int64 , ToInt64)
ToInt32 ToDouble XmlElementBuiltInTypeBody (double , Double , ToDouble)
ToInt32 ToDouble GetNextTokenUint GetNextTokenDouble XmlElementArrayFloat XmlElementVectorBody (kkint32 , VectorInt32 , GetNextTokenInt)
XmlFactoryMacro (Bool)
Definition at line 1048 of file XmlStream.cpp.
Referenced by XmlFactoryMacro().
XmlFactoryMacro (UnKnown)
Definition at line 1088 of file XmlStream.cpp.
XmlFactoryMacro (DateTime)
Definition at line 1127 of file XmlStream.cpp.
XmlFactoryMacro (KeyValuePairs)
Definition at line 1277 of file XmlStream.cpp.
References KKB::endl().
XmlFactoryMacro (ArrayFloat2DVarying)
Definition at line 1400 of file XmlStream.cpp.
References XmlFactoryMacro().
XmlFactoryMacro (VectorKKStr)
Works with matching Marco (XmlElementBuiltInTypeHeader) defined in XmlStream.h.
Works with corresponding macro (XmlElementArray2DHeader) defined in header file "XmlStream.h"
Parameters
T The Built-In type, examples: float, kkint32, double, ...
TypeName The name we give the type ex: "Int32", "Float", ....
XmlElementToUse the XmlElement derived class that will be used to process each row in the matrix.
Variable Documentation
ToInt32 ToDouble GetNextTokenUint ArrayDouble
Definition at line 1857 of file XmlStream.cpp.
ToInt32 ToDouble GetNextTokenUint GetNextTokenDouble ArrayFloat2D
Definition at line 1862 of file XmlStream.cpp.
ToInt32 ToDouble ArrayUint16
Definition at line 1853 of file XmlStream.cpp.
ToInt32 Float
Definition at line 1844 of file XmlStream.cpp.
Int32
Definition at line 1840 of file XmlStream.cpp.
Referenced by SipperFile.SipperConfigForm::Dispose(), and SipperDiskUtilities.PartitionTableEntry::PartitionTableEntry().
ToInt32 ToDouble GetNextTokenUint GetNextTokenDouble XmlElementArrayFloat VectorFloat
Definition at line 1869 of file XmlStream.cpp.
Referenced by FeatureSelectionApp::Results::AccuracyByClass(), MLL::ImageSizeDistribution::AllDepths(), MLL::InstrumentDataFileManager::GetVolumePerMeterProfile2(), FeatureSelectionApp::FinalResults::RandomSplitAccuracyByClass(), KKMLL::CrossValidationMxN::TrainingTimeStdDev(), KKMLL::CrossValidation::TrainTimeTotal(), and FeatureSelectionApp::FinalResults::ValidationAccuracyByClass().
kkint32 xmlLevel = 0
Definition at line 720 of file XmlStream.cpp.
Referenced by KKB::XmlTag::WriteXML().