Pices: KKMLL::FeatureFileIOSparse Class Reference
KKMLL::FeatureFileIOSparse Class Reference
Supports the reading and writing of Sparse feature files similar to the ones libSVM use.
#include <FeatureFileIOSparse.h>
Public Types
typedef FeatureFileIOSparse * FeatureFileIOSparsePtr
Public Types inherited from KKMLL::FeatureFileIO
typedef FeatureFileIO * FeatureFileIOPtr
Public Member Functions
FeatureFileIOSparse ()
~FeatureFileIOSparse ()
virtual FileDescPtr GetFileDesc (const KKStr &_fileName, istream &_in, MLClassListPtr _classList, kkint32 &_estSize, KKStr &_errorMessage, RunLog &_log)
Create a FileDesc object from the input stream '_in'.
virtual FeatureVectorListPtr LoadFile (const KKStr &_fileName, const FileDescPtr _fileDesc, MLClassList &_classes, istream &_in, kkint32 _maxCount, VolConstBool &_cancelFlag, bool &_changesMade, KKStr &_errorMessage, RunLog &_log)
To be implemented by derived classes; loads the contents of a feature data file and returns a ImageFeaturesList container object.
virtual void SaveFile (FeatureVectorList &_data, const KKStr &_fileName, FeatureNumListConst &_selFeatures, ostream &_out, kkuint32 &_numExamplesWritten, VolConstBool &_cancelFlag, bool &_successful, KKStr &_errorMessage, RunLog &_log)
To be implemented by derived classes; save examples to output stream '_out'.
Public Member Functions inherited from KKMLL::FeatureFileIO
FeatureFileIO (const KKStr &_driverName, bool _canRead, bool _canWrite)
virtual ~FeatureFileIO ()
void AppendToFile (const KKStr &_fileName, FeatureNumListConst &_selFeatures, FeatureVectorList &_examples, kkuint32 &_numExamplesWritten, VolConstBool &_cancelFlag, bool &_successful, RunLog &log)
bool CanRead ()
bool CanWrite ()
const KKStr & DriverName ()
virtual FeatureVectorListPtr FeatureDataReSink (FactoryFVProducerPtr _fvProducerFactory, const KKStr &_dirName, const KKStr &_fileName, MLClassPtr _unknownClass, bool _useDirectoryNameForClassName, MLClassList &_mlClasses, VolConstBool &_cancelFlag, bool &_changesMade, KKB::DateTime &_timeStamp, RunLog &_log)
FeatureDataReSink.
virtual FeatureVectorListPtr LoadFeatureFile (const KKStr &_fileName, MLClassList &_mlClasses, kkint32 _maxCount, VolConstBool &_cancelFlag, bool &_successful, bool &_changesMade, RunLog &_log)
Loads the contents of a feature data file and returns a ImageFeaturesList container object.
FeatureVectorListPtr LoadInSubDirectoryTree (FactoryFVProducerPtr _fvProducerFactory, KKStr _rootDir, MLClassList &_mlClasses, bool _useDirectoryNameForClassName, VolConstBool &_cancelFlag, bool _rewiteRootFeatureFile, RunLog &_log)
LoadInSubDirectoryTree.
virtual void SaveFeatureFile (const KKStr &_fileName, FeatureNumListConst &_selFeatures, FeatureVectorList &_examples, kkuint32 &_numExamplesWritten, VolConstBool &_cancelFlag, bool &_successful, RunLog &_log)
SaveFeatureFile.
void SaveFeatureFileMultipleParts (const KKStr &_fileName, FeatureNumListConst &_selFeatures, FeatureVectorList &_examples, VolConstBool &_cancelFlag, bool &_successful, RunLog &_log)
Saves the feature file in multiple parts with no one single part larger that 64k examples.
Static Public Member Functions
static FeatureFileIOSparsePtr Driver ()
Static Public Member Functions inherited from KKMLL::FeatureFileIO
static FeatureFileIOPtr FileFormatFromStr (const KKStr &_fileFormatStr)
static FeatureFileIOPtr FileFormatFromStr (const KKStr &_fileFormatStr, bool _canRead, bool _canWrite)
static KKStr FileFormatsReadAndWriteOptionsStr ()
static KKStr FileFormatsReadOptionsStr ()
static KKStr FileFormatsWrittenOptionsStr ()
static void FinalCleanUp ()
Before you terminate your application and after all FeatureFileIO activity is done call this method to destroy statically dynamically allocated data structures.
static VectorKKStr RegisteredDriverNames (bool canRead, bool canWrite)
static void RegisterFeatureFileIODriver (FeatureFileIOPtr _driver)
For each feature file format register the appropriate driver through this static method.
Additional Inherited Members
Protected Member Functions inherited from KKMLL::FeatureFileIO
void GetLine (std::istream &_in, KKStr &_line, bool &_eof)
void GetToken (std::istream &_in, const char *_delimiters, KKStr &_token, bool &_eof, bool &_eol)
Will retrieve the next token from the input stream.
Static Protected Member Functions inherited from KKMLL::FeatureFileIO
static void RegisterDriver (FeatureFileIOPtr driver)
Detailed Description
Supports the reading and writing of Sparse feature files similar to the ones libSVM use.
*************************************************************************************************
*  FeatureFileIOSparse  Sub-classed from FeatureFileIO.  It supports the reading and writing    *
*  of Sparse Files as used by the libSVM.                                                       *
*                                                                                               *
*  One example per row.                                                                         *
*  any row that starts with '//' is ignored.                                                    *
*  On each row there will be several fields separated by the space(' ') character. The first    *
*  field will be the class name followed by the attribute data.                                 *
*                                                                                               *
*   - First Field is the Class Name.  This differers from libSVM which assumes that class-names *
*     are integers.  We support alpha numeric class names.                                      *
*   - Attribute Fields will be of the following format.  <FeatureNum>:<Feature value>.          *
*                                                                                               *
*  ex:                                                                                          *
*     "0 0:12.12 4:87.1242 12:-65.63 15:0.872"                                                  *
*     "1 2:-76.92 12:65.882 26:76"                                                              *
*     "1 1:28.74 3:8.452 11:22.72"                                                              *
*                                                                                               *
*************************************************************************************************
See Also
FeatureFileIO
Definition at line 36 of file FeatureFileIOSparse.h.
Member Typedef Documentation
typedef FeatureFileIOSparse* KKMLL::FeatureFileIOSparse::FeatureFileIOSparsePtr
Definition at line 42 of file FeatureFileIOSparse.h.
Constructor & Destructor Documentation
FeatureFileIOSparse::FeatureFileIOSparse ()
Definition at line 35 of file FeatureFileIOSparse.cpp.
FeatureFileIOSparse::~FeatureFileIOSparse ()
Definition at line 42 of file FeatureFileIOSparse.cpp.
Member Function Documentation
static FeatureFileIOSparsePtr KKMLL::FeatureFileIOSparse::Driver () inline static
Definition at line 44 of file FeatureFileIOSparse.h.
FileDescPtr FeatureFileIOSparse::GetFileDesc (const KKStr & _fileName, istream & _in, MLClassListPtr _classes, kkint32 & _estSize, KKStr & _errorMessage, RunLog & _log) virtual
Create a FileDesc object from the input stream '_in'.
All derived classes must implement this method. It is called by 'LoadFeatureFile' before it starts reading in the feature data.
Parameters
[in] _fileName Name of file to read top get FileDesc data from. Ex in c45 this would be the names file.
[in] _in Input Stream t read from.
[out] _classes Must be pointing to a valid MLClassList object. As class names are encountered add them to this list.
[out] _estSize If you can drive the number of examples in the feature file populate this parameter.
[out] _errorMessage If a error in processing occurs; place a description of the error in this parameter.
_log
Implements KKMLL::FeatureFileIO.
Definition at line 48 of file FeatureFileIOSparse.cpp.
References KKMLL::FileDesc::AddAAttribute(), KKB::endl(), KKB::KKStr::ExtractToken(), KKMLL::MLClassList::GetMLClassPtr(), KKMLL::FeatureFileIO::GetToken(), int32_max, int32_min, KKB::RunLog::Level(), KKMLL::FileDesc::SparseMinFeatureNum(), KKB::KKStr::Str(), KKB::StrFormatInt(), and KKB::KKStr::SubStrPart().
FeatureVectorListPtr FeatureFileIOSparse::LoadFile (const KKStr & _fileName, const FileDescPtr _fileDesc, MLClassList & _classes, istream & _in, kkint32 _maxCount, VolConstBool & _cancelFlag, bool & _changesMade, KKStr & _errorMessage, RunLog & _log) virtual
To be implemented by derived classes; loads the contents of a feature data file and returns a ImageFeaturesList container object.
Parameters
[in] _fileName Feature file that is being loaded.
[in] _fileDesc Description of feature data that is to be loaded.
[in,out] _classes All classes encountered during the loading of the feature file will be added to this list.
[in] _in input stream that feature data is to be loaded/read from.
[in] _maxCount Maximum number of examples to load, -1 = load all
[in] _cancelFlag If this flag turns true the load will terminate and return to caller.
[out] _changesMade If the routine had loaded the feature data determined that it needed to make changes this flag will be set 'true'.
[out] _errorMessage If an error occurs during the loading a description of this error will be placed here.
[in] _log Where to send diagnostic messages to.
Returns
A ImageFeaturesList container object; this object will own all the examples loaded; if an error occurs NULL will be returned.
Implements KKMLL::FeatureFileIO.
Definition at line 124 of file FeatureFileIOSparse.cpp.
References KKMLL::FeatureVector::AddFeatureData(), KKB::endl(), KKMLL::FeatureVector::ExampleFileName(), KKB::KKStr::ExtractToken(), KKMLL::MLClassList::GetMLClassPtr(), KKMLL::FeatureFileIO::GetToken(), int32_max, KKB::RunLog::Level(), KKMLL::FeatureVector::MLClass(), KKMLL::FileDesc::NumOfFields(), KKB::osGetRootName(), KKMLL::FeatureVectorList::PushOnBack(), KKMLL::FileDesc::SparseMinFeatureNum(), KKB::KKStr::Str(), KKB::StrFormatInt(), and KKB::KKStr::SubStrPart().
void FeatureFileIOSparse::SaveFile (FeatureVectorList & _data, const KKStr & _fileName, FeatureNumListConst & _selFeatures, ostream & _out, kkuint32 & _numExamplesWritten, VolConstBool & _cancelFlag, bool & _successful, KKStr & _errorMessage, RunLog & _log) virtual
To be implemented by derived classes; save examples to output stream '_out'.
Parameters
[in] _data Examples that are to be written to saved to the output stream.
[in] _fileName Name of file top same examples/images to.
[in] _selFeatures Specify specific features to save, typically all features.
[out] _out Output stream to save feature data to.
[out] _numExamplesWritten Will reflect the number examples written, caller will be able to monitor.
[in] _cancelFlag If this flag turns true the writing of data will terminate and return to caller.
[out] _successful False will be returned if the save failed.
[out] _errorMessage If the save fails (_successful == false) then a description of the error will be placed here.
[in] _log log file to send messages to.
Implements KKMLL::FeatureFileIO.
Definition at line 221 of file FeatureFileIOSparse.cpp.
References KKMLL::FeatureVector::ClassName(), KKB::endl(), KKMLL::FeatureVector::FeatureData(), KKMLL::FeatureVectorList::FileDesc(), KKB::KKQueue< Entry >::IdxToPtr(), KKB::RunLog::Level(), KKB::KKQueue< Entry >::QueueSize(), and KKMLL::FileDesc::SparseMinFeatureNum().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/KSquareLibraries/KKMachineLearning/FeatureFileIOSparse.h
C:/Users/kurtk_000/GitHub/KSquareLibraries/KKMachineLearning/FeatureFileIOSparse.cpp