Pices: MLL::DataBaseUpdate Class Reference
MLL::DataBaseUpdate Class Reference
Routines used to update the MySql database to the current version.
#include <DataBaseUpdate.h>
Public Types
typedef DataBaseUpdate * DataBaseUpdatePtr
typedef KKB::kkint32 kkint32
typedef KKB::kkint64 kkint64
typedef KKB::kkuint32 kkuint32
typedef KKB::kkuint64 kkuint64
typedef KKB::uchar uchar
typedef KKB::ulong ulong
Public Member Functions
DataBaseUpdate (RunLog &_log)
~DataBaseUpdate ()
void LoadSourceFile (const KKStr &fileName, DataBasePtr dbConn, bool &successful, KKStrListPtr errorMsgs, RunLog &log)
Detailed Description
Routines used to update the MySql database to the current version.
DataBaseUpdate connection management object; all database communications will go through this class.
Author
Kurt Kramer
Date
Dec/01/2008
Definition at line 48 of file DataBaseUpdate.h.
Member Typedef Documentation
typedef DataBaseUpdate* MLL::DataBaseUpdate::DataBaseUpdatePtr
Definition at line 51 of file DataBaseUpdate.h.
typedef KKB::kkint32 MLL::DataBaseUpdate::kkint32
Definition at line 55 of file DataBaseUpdate.h.
typedef KKB::kkint64 MLL::DataBaseUpdate::kkint64
Definition at line 57 of file DataBaseUpdate.h.
typedef KKB::kkuint32 MLL::DataBaseUpdate::kkuint32
Definition at line 56 of file DataBaseUpdate.h.
typedef KKB::kkuint64 MLL::DataBaseUpdate::kkuint64
Definition at line 58 of file DataBaseUpdate.h.
typedef KKB::uchar MLL::DataBaseUpdate::uchar
Definition at line 53 of file DataBaseUpdate.h.
typedef KKB::ulong MLL::DataBaseUpdate::ulong
Definition at line 54 of file DataBaseUpdate.h.
Constructor & Destructor Documentation
DataBaseUpdate::DataBaseUpdate (RunLog & _log)
Definition at line 41 of file DataBaseUpdate.cpp.
DataBaseUpdate::~DataBaseUpdate ()
Definition at line 48 of file DataBaseUpdate.cpp.
Member Function Documentation
void DataBaseUpdate::LoadSourceFile (const KKStr & fileName, DataBasePtr dbConn, bool & successful, KKStrListPtr errorMsgs, RunLog & log)
Definition at line 56 of file DataBaseUpdate.cpp.
References KKB::endl(), MLL::DataBase::LastErrorDesc(), KKB::RunLog::Level(), KKB::osFOPEN(), KKB::osGetFileSize(), KKB::KKQueue< Entry >::PushOnBack(), MLL::DataBase::QueryStatementReturnAllColumns(), and KKB::KKStr::Str().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/DataBaseUpdate.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/DataBaseUpdate.cpp