Pices: FeatureSelectionApp::AccByFeatureSel Class Reference
FeatureSelectionApp::AccByFeatureSel Class Reference
#include <AccByFeatureSel.h>
Public Types
typedef AccByFeatureSel * AccByFeatureSelPtr
Public Member Functions
AccByFeatureSel (MLClassPtr class1, MLClassPtr class2, int featureNum, float avgAccGain, float stdDevAccGain)
~AccByFeatureSel ()
float AvgAccGain () const
MLClassPtr Class1 () const
const KKStr & Class1Name () const
MLClassPtr Class2 () const
const KKStr & Class2Name () const
int FeatureNum () const
float StdDevAccGain () const
Detailed Description
Definition at line 13 of file AccByFeatureSel.h.
Member Typedef Documentation
typedef AccByFeatureSel* FeatureSelectionApp::AccByFeatureSel::AccByFeatureSelPtr
Definition at line 16 of file AccByFeatureSel.h.
Constructor & Destructor Documentation
AccByFeatureSel::AccByFeatureSel (MLClassPtr class1, MLClassPtr class2, int featureNum, float avgAccGain, float stdDevAccGain)
Definition at line 48 of file AccByFeatureSel.cpp.
AccByFeatureSel::~AccByFeatureSel ()
Definition at line 63 of file AccByFeatureSel.cpp.
Member Function Documentation
float FeatureSelectionApp::AccByFeatureSel::AvgAccGain () const inline
Definition at line 32 of file AccByFeatureSel.h.
Referenced by ReportDataSpecs().
MLClassPtr FeatureSelectionApp::AccByFeatureSel::Class1 () const inline
Definition at line 27 of file AccByFeatureSel.h.
const KKStr & AccByFeatureSel::Class1Name () const
Definition at line 69 of file AccByFeatureSel.cpp.
Referenced by ReportDataSpecs().
MLClassPtr FeatureSelectionApp::AccByFeatureSel::Class2 () const inline
Definition at line 28 of file AccByFeatureSel.h.
const KKStr & AccByFeatureSel::Class2Name () const
Definition at line 78 of file AccByFeatureSel.cpp.
Referenced by ReportDataSpecs().
int FeatureSelectionApp::AccByFeatureSel::FeatureNum () const inline
Definition at line 31 of file AccByFeatureSel.h.
Referenced by FeatureSelectionApp::AccByFeatureSelList::AccByFeatureSelList(), and ReportDataSpecs().
float FeatureSelectionApp::AccByFeatureSel::StdDevAccGain () const inline
Definition at line 33 of file AccByFeatureSel.h.
Referenced by ReportDataSpecs().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/Apps/FeatureSelection/AccByFeatureSel.h
C:/Users/Kurt/GitHub/Pices/Apps/FeatureSelection/AccByFeatureSel.cpp