Pices: KKMLL::GrayScaleImagesFV Class Reference
KKMLL::GrayScaleImagesFV Class Reference
Specialized version of KKMLL::FeatureVector that will be used to represent the features of a Shrimp.
#include <GrayScaleImagesFV.h>
Public Types
typedef GrayScaleImagesFV * GrayScaleImagesFVPtr
typedef KKB::uchar uchar
Public Types inherited from KKMLL::FeatureVector
typedef FeatureVector * FeatureVectorPtr
typedef float FVFloat
Public Member Functions
GrayScaleImagesFV (kkint32 _numOfFeatures)
GrayScaleImagesFV (const GrayScaleImagesFV &_fv)
GrayScaleImagesFV (const FeatureVector &featureVector)
Smart copy constructor that will detect the underlying type of the source instance.
virtual ~GrayScaleImagesFV ()
void CentroidCol (float _centroidCol)
float CentroidCol () const
void CentroidRow (float _centroidRow)
float CentroidRow () const
virtual GrayScaleImagesFVPtr Duplicate () const
void NumOfEdgePixels (kkint32 _numOfEdgePixels)
kkint32 NumOfEdgePixels () const
Public Member Functions inherited from KKMLL::FeatureVector
FeatureVector (kkint32 _numOfFeatures)
FeatureVector (const FeatureVector &_example)
virtual ~FeatureVector ()
void AddFeatureData (kkint32 _featureNum, float _featureData)
void BreakTie (float _breakTie)
Update the BreakTie value.
float BreakTie () const
The difference in probability between the two most likely classes.
const KKStr & ClassName () const
Name of class that this example is assigned to.
void ExampleFileName (const KKStr &_exampleFileName)
Name of source of feature vector, ex: file name of image that the feature vector was computed from.
const KKStr & ExampleFileName () const
Name of file that this FeatureVector was computed from.
void FeatureData (kkint32 _featureNum, float _featureValue)
Assign a value to a specific feature number for the feature vector.
float FeatureData (kkint32 featureNum) const
const float * FeatureData () const
Returns as a pointer to the feature data itself.
float * FeatureDataAlter ()
Same as 'FeatureData() except you can modify the data.
const float * FeatureDataConst () const
bool FeatureDataValid ()
virtual kkint32 MemoryConsumedEstimated () const
void MissingData (bool _missingData)
True indicates that not all the feature data was present when this example was loaded from a data file.
bool MissingData () const
True indicates that one or more features were missing.
void MLClass (MLClassPtr _mlClass)
Assign a class to this example.
MLClassPtr MLClass () const
Class that is example is assigned to.
const KKStr & MLClassName () const
Name of class that this example is assigned to.
kkint32 NumOfFeatures () const
Number of features in this FeatureVector.
bool operator== (FeatureVector &other_example) const
void OrigSize (float _origSize)
The value of Feature[0] before normalization.
float OrigSize () const
The value of Feature[0] before normalization.
void PredictedClass (MLClassPtr _predictedClass)
MLClassPtr PredictedClass () const
const KKStr & PredictedClassName () const
void Probability (float _probability)
Assign a prediction probability to this example.
float Probability () const
The probability assigned by classifier to the predicted class.
void ResetNumOfFeatures (kkint32 newNumOfFeatures)
Used to reallocate memory for feature data.
float TotalOfFeatureData () const
Returns the total of all Feature Attributes for this feature vector.
void TrainWeight (float _trainWeight)
Assign a specific example a higher weight for training purposes.
float TrainWeight () const
void Validated (bool _validated)
Indicated whether an expert has validated the class assignment.
bool Validated () const
void Version (kkint16 _version)
kkint16 Version () const
Additional Inherited Members
Protected Member Functions inherited from KKMLL::FeatureVector
void AllocateFeatureDataArray ()
Used by container classes such as 'FeatureVectorList'.
Protected Attributes inherited from KKMLL::FeatureVector
float * featureData
kkint32 numOfFeatures
Detailed Description
Specialized version of KKMLL::FeatureVector that will be used to represent the features of a Shrimp.
Author
Kurt Kramer
Used for the representation of a Single Plankton Image. You create an instance of this object for each single image you need to keep track of. There is a specialized version of KKMLL::FeatureFileIO calculated KKMLL::FeatureFileIOKK that is used to write and read feature Data files. What makes this class of KKMLL::FeatureVector special are the additional fields that are Plankton specific such as centroidCol, centroidRow, latitude, longitude, numOfEdgePixels, centroid within SIPPEER file sfCentroidCol, sfCentroidRow and version.
The version number field is supposed to indicate which feature calculation routines were used. This way if there are changes the way features are calculated it can be detected during runtime if the features are up to date they need to be recomputed.
Definition at line 54 of file GrayScaleImagesFV.h.
Member Typedef Documentation
typedef GrayScaleImagesFV* KKMLL::GrayScaleImagesFV::GrayScaleImagesFVPtr
Definition at line 57 of file GrayScaleImagesFV.h.
typedef KKB::uchar KKMLL::GrayScaleImagesFV::uchar
Definition at line 58 of file GrayScaleImagesFV.h.
Constructor & Destructor Documentation
GrayScaleImagesFV::GrayScaleImagesFV (kkint32 _numOfFeatures)
Definition at line 53 of file GrayScaleImagesFV.cpp.
Referenced by Duplicate().
GrayScaleImagesFV::GrayScaleImagesFV (const GrayScaleImagesFV & _fv)
Definition at line 64 of file GrayScaleImagesFV.cpp.
GrayScaleImagesFV::GrayScaleImagesFV (const FeatureVector & featureVector)
Smart copy constructor that will detect the underlying type of the source instance.
This constructor will detect what the underlying type of 'featureVector' is.
If (underlying type is a 'GrayScaleImagesFV' object)  then
  | Information that is particular to a 'GrayScaleImagesFV' object will be extracted
  | from the 'FeatureVector' object.
else
  | Info that is particular to a 'GrayScaleImagesFV' object will be set to default
  | values.
Definition at line 78 of file GrayScaleImagesFV.cpp.
References CentroidCol(), CentroidRow(), and NumOfEdgePixels().
GrayScaleImagesFV::~GrayScaleImagesFV () virtual
Definition at line 99 of file GrayScaleImagesFV.cpp.
Member Function Documentation
void KKMLL::GrayScaleImagesFV::CentroidCol (float _centroidCol) inline
Definition at line 86 of file GrayScaleImagesFV.h.
Referenced by GrayScaleImagesFV(), and KKMLL::GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree().
float KKMLL::GrayScaleImagesFV::CentroidCol () const inline
Definition at line 91 of file GrayScaleImagesFV.h.
void KKMLL::GrayScaleImagesFV::CentroidRow (float _centroidRow) inline
Definition at line 87 of file GrayScaleImagesFV.h.
Referenced by GrayScaleImagesFV(), and KKMLL::GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree().
float KKMLL::GrayScaleImagesFV::CentroidRow () const inline
Definition at line 92 of file GrayScaleImagesFV.h.
GrayScaleImagesFVPtr GrayScaleImagesFV::Duplicate () const virtual
Reimplemented from KKMLL::FeatureVector.
Definition at line 106 of file GrayScaleImagesFV.cpp.
References GrayScaleImagesFV().
void KKMLL::GrayScaleImagesFV::NumOfEdgePixels (kkint32 _numOfEdgePixels) inline
Definition at line 88 of file GrayScaleImagesFV.h.
Referenced by GrayScaleImagesFV(), and KKMLL::GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree().
kkint32 KKMLL::GrayScaleImagesFV::NumOfEdgePixels () const inline
Definition at line 93 of file GrayScaleImagesFV.h.
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/KSquareLibraries/KKMachineLearning/GrayScaleImagesFV.h
C:/Users/kurtk_000/GitHub/KSquareLibraries/KKMachineLearning/GrayScaleImagesFV.cpp