Pices: KKMLL::SizeDistribution::ClassTotalsList Class Reference
KKMLL::SizeDistribution::ClassTotalsList Class Reference
Public Member Functions
ClassTotalsList (bool _owner)
ClassTotalsList (bool _owner)
~ClassTotalsList ()
~ClassTotalsList ()
ClassTotals::ClassTotalsPtr LookUp (KKStr _name)
ClassTotals::ClassTotalsPtr LookUp (KKStr _name)
Public Member Functions inherited from KKB::KKQueue< ClassTotals >
KKQueue (bool _owner=true)
KKQueue (const KKQueue &q, bool _owner)
Constructor, similar to the Copy Constructor except that you can control whether it duplicates the contents.
virtual ~KKQueue ()
Virtual destructor; if owns its contents will also call the destructor on each one entry that it contains.
virtual void Add (EntryPtr _entry)
same as PushOnBack
virtual void AddFirst (EntryPtr _entry)
same as PushOnFront
virtual void AddQueue (const KKQueue &q)
Add the contents of a separate KKQueue container to this container.
EntryPtr BackOfQueue () const
Returns pointer of last element in the container without removing it.
void DeleteContents ()
Empties the container, if 'owner' is set to true will call the destructor on each element.
void DeleteEntry (EntryPtr _entry)
Removes from KKQueue the entry who's pointer = '_entry'.
void DeleteEntry (kkuint32 _idx)
Removes from KKQueue the entry who's index = '_idx'.
KKQueue * DuplicateListAndContents () const
Creates a new container including duplicating the contents, which also makes the new instance the owner of those contents.
kkuint32 FindTheKthElement (kkuint32 k, Functor pred)
EntryPtr FrontOfQueue () const
Returns a pointer to the element that is at from of the queue with out removing it from the queue.
EntryPtr GetFirst () const
Same as FrontOfQueue.
EntryPtr GetLast () const
Same as BackOfQueue.
EntryPtr IdxToPtr (kkuint32 idx) const
Returns back a pointer to the element who's index is 'idx'.
kkint32 LocateEntry (EntryConstPtr _entry) const
Returns the index of the element who's address is '_entry'.
EntryPtr LookAtBack () const
Same as BackOfQueue.
EntryPtr LookAtFront () const
Same as FrontOfQueue.
bool operator!= (const KKQueue< ClassTotals > &rightSide) const
returns False if NOT every entry in both containers point to the same elements
KKQueue & operator= (const KKQueue &q)
Assignment Operator.
bool operator== (const KKQueue< ClassTotals > &rightSide) const
Returns True if every entry in both containers point to the same elements.
ClassTotals & operator[] (kkuint32 i) const
Returns a reference to element indexed by 'i'; similar to IdxToPtr except tat it returns a reference rather than a pointer.0.
bool Owner () const
void Owner (bool _owner)
You can specify who owns the contents of the container.
virtual EntryPtr PopFromBack ()
Removes the last element in the container and returns its pointer.
virtual EntryPtr PopFromFront ()
Removes the first element in the container and returns its pointer.
kkint32 PtrToIdx (EntryConstPtr _entry) const
returns the index of the 'entry' that has the same pointer as '_entry', if none found returns -1
virtual void PushOnBack (EntryPtr _entry)
Adds '_entry' to the End of the container.
virtual void PushOnFront (EntryPtr _entry)
Adds '_entry' to the Front of the container.
kkint32 QueueSize () const
Same as calling vector<>::size(); returns the number of elements in KKQueue.
void RandomizeOrder ()
Randomizes the order of the vector.
void RandomizeOrder (kkint64 seed)
void RandomizeOrder (RandomNumGenerator &randomVariable)
Randomizes the order of the vector.
virtual EntryPtr RemoveFirst ()
same as PopFromFront
virtual EntryPtr RemoveLast ()
same as PopFromBack
void SetIdxToPtr (kkuint32 _idx, ClassTotals *_ptr)
void SwapIndexes (size_t idx1, size_t idx2)
Additional Inherited Members
Public Types inherited from KKB::KKQueue< ClassTotals >
typedef std::vector< ClassTotals * >::const_iterator const_iterator
typedef std::vector< ClassTotals * >::iterator iterator
Protected Member Functions inherited from KKB::KKQueue< ClassTotals >
KKQueue (const KKQueue &q)
Copy Constructor creating new instance; including duplicating contents if owner set to true.
Detailed Description
Definition at line 118 of file SizeDistribution.cpp.
Constructor & Destructor Documentation
KKMLL::SizeDistribution::ClassTotalsList::ClassTotalsList (bool _owner) inline
Definition at line 121 of file SizeDistribution.cpp.
KKMLL::SizeDistribution::ClassTotalsList::~ClassTotalsList () inline
Definition at line 126 of file SizeDistribution.cpp.
KKMLL::SizeDistribution::ClassTotalsList::ClassTotalsList (bool _owner) inline
Definition at line 113 of file SizeDistribution.cpp.
KKMLL::SizeDistribution::ClassTotalsList::~ClassTotalsList () inline
Definition at line 118 of file SizeDistribution.cpp.
Member Function Documentation
ClassTotals::ClassTotalsPtr KKMLL::SizeDistribution::ClassTotalsList::LookUp (KKStr _name) inline
Definition at line 124 of file SizeDistribution.cpp.
References KKMLL::SizeDistribution::ClassTotals::AddIn(), KKB::endl(), KKB::KKStr::LeftPad(), KKMLL::SizeDistribution::ClassTotals::PrintCSVLine(), KKMLL::SizeDistribution::ClassTotals::PrintFormatedLine(), KKMLL::SizeDistribution::ClassTotals::PrintTabDelLine(), and KKB::KKStr::RightPad().
ClassTotals::ClassTotalsPtr KKMLL::SizeDistribution::ClassTotalsList::LookUp (KKStr _name) inline
Definition at line 132 of file SizeDistribution.cpp.
References KKMLL::SizeDistribution::ClassTotals::nameUpper, and KKB::KKStr::Upper().
Referenced by KKMLL::SizeDistribution::Increment().
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/SizeDistribution.cpp