Pices: PicesCommander.SizeDistribution2 Class Reference
PicesCommander.SizeDistribution2 Class Reference
Classes
class ClassTotals2
Public Member Functions
SizeDistribution2 (float _sizeInitial, float _sizeGrowthFactor, float _sizeEndRange)
void Add (SizeDistribution2 x)
Will add in the contents of another SizeDistribution2 instance into this instance.
void Add (ClassTotals2 x)
Will add in the contents of a ClassTotals2 instance into this instance of SizeDistribution2.
SizeDistribution2 ExtractFamilyOfClasses (PicesClass ancestor)
Returns an instance of 'ClassTotals' that contains the ClassTotals that belong to the family of 'ancestor'.
void Increment (PicesClass mlClass, float areaMM)
void InitiateClass (PicesClass mlClass)
Method used to guarantee that the specified class is included; even if none occur.
void PrintTabDelDistributionMatrix (System.IO.StreamWriter o, float volume)
void PrintTabDelDistributionMatrixesForSummaryClasses (System.IO.StreamWriter o, String majorTitle, float volume)
ClassTotals2 SummarizeFamilyOfClasses (PicesClass ancestor)
Returns an instance of 'ClassTotals' that contains a summary of the classes that are decedent of 'ancestor'.
Detailed Description
Definition at line 20 of file SizeDistribution2.cs.
Constructor & Destructor Documentation
PicesCommander.SizeDistribution2.SizeDistribution2 (float _sizeInitial, float _sizeGrowthFactor, float _sizeEndRange) inline
Definition at line 203 of file SizeDistribution2.cs.
Referenced by PicesCommander.SizeDistribution2.ExtractFamilyOfClasses().
Member Function Documentation
void PicesCommander.SizeDistribution2.Add (SizeDistribution2 x) inline
Will add in the contents of another SizeDistribution2 instance into this instance.
Parameters
x The other 'SizeDistribution2' instance to be accumulated to this instance.
Definition at line 341 of file SizeDistribution2.cs.
References PicesCommander.SizeDistribution2.ClassTotals2.AddIn(), and PicesCommander.SizeDistribution2.ClassTotals2.Name.
Referenced by PicesCommander.ClassifierProcess.UpdateClassificationStats().
void PicesCommander.SizeDistribution2.Add (ClassTotals2 x) inline
Will add in the contents of a ClassTotals2 instance into this instance of SizeDistribution2.
Parameters
x
Definition at line 382 of file SizeDistribution2.cs.
References PicesCommander.SizeDistribution2.ClassTotals2.SizeEndRange, PicesCommander.SizeDistribution2.ClassTotals2.SizeGrowthFactor, and PicesCommander.SizeDistribution2.ClassTotals2.SizeInitial.
SizeDistribution2 PicesCommander.SizeDistribution2.ExtractFamilyOfClasses (PicesClass ancestor) inline
Returns an instance of 'ClassTotals' that contains the ClassTotals that belong to the family of 'ancestor'.
The newly instantiated instance will point to the same instances of 'ClassTotals' that this instance points to. As a result you should only call this method after you are done accumulating data.
Parameters
ancestor
Returns
Definition at line 304 of file SizeDistribution2.cs.
References PicesCommander.SizeDistribution2.SizeDistribution2().
Referenced by PicesCommander.SizeDistribution2.PrintTabDelDistributionMatrixesForSummaryClasses().
void PicesCommander.SizeDistribution2.Increment (PicesClass mlClass, float areaMM) inline
Definition at line 435 of file SizeDistribution2.cs.
References PicesInterface::PicesClassList.GetUnKnownClassStatic(), PicesCommander.SizeDistribution2.ClassTotals2.Increment(), and PicesInterface::PicesClass.Name.
void PicesCommander.SizeDistribution2.InitiateClass (PicesClass mlClass) inline
Method used to guarantee that the specified class is included; even if none occur.
Parameters
mlClass Class to add
Definition at line 411 of file SizeDistribution2.cs.
References PicesInterface::PicesClassList.GetUnKnownClassStatic(), and PicesInterface::PicesClass.Name.
void PicesCommander.SizeDistribution2.PrintTabDelDistributionMatrix (System.IO.StreamWriter o, float volume) inline
Parameters
o Output stream to print report to.
volume If volume == 0.0 then prints units otherwise prints the density units/mm^3.
Definition at line 466 of file SizeDistribution2.cs.
References PicesCommander.SizeDistribution2.ClassTotals2.AddIn(), and PicesCommander.SizeDistribution2.ClassTotals2.PrintTabDelLine().
Referenced by PicesCommander.SizeDistribution2.PrintTabDelDistributionMatrixesForSummaryClasses().
void PicesCommander.SizeDistribution2.PrintTabDelDistributionMatrixesForSummaryClasses (System.IO.StreamWriter o, String majorTitle, float volume) inline
Definition at line 502 of file SizeDistribution2.cs.
References PicesCommander.SizeDistribution2.ExtractFamilyOfClasses(), PicesInterface::PicesClassList.ExtractSummarizeClasses(), PicesInterface::PicesClassList.GetAllKnownClasses(), PicesInterface::PicesClass.Name, PicesCommander.SizeDistribution2.PrintTabDelDistributionMatrix(), and PicesInterface::PicesClassList.SortByName().
ClassTotals2 PicesCommander.SizeDistribution2.SummarizeFamilyOfClasses (PicesClass ancestor) inline
Returns an instance of 'ClassTotals' that contains a summary of the classes that are decedent of 'ancestor'.
Parameters
ancestor
Returns
Definition at line 267 of file SizeDistribution2.cs.
References PicesInterface::PicesClass.Name.
The documentation for this class was generated from the following file:
C:/Users/kurtk_000/GitHub/Pices/Apps/PicesCommander/SizeDistribution2.cs