Pices: D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/OSservices.cpp File Reference
OSservices.cpp File Reference
#include "FirstIncludes.h"
#include <dirent.h>
#include <sys/types.h>
#include <sys/times.h>
#include <limits.h>
#include <unistd.h>
#include <sys/stat.h>
#include <ctype.h>
#include <errno.h>
#include <iostream>
#include <fstream>
#include <stdio.h>
#include <string.h>
#include <string>
#include <vector>
#include "MemoryDebug.h"
#include "OSservices.h"
#include "ImageIO.h"
Functions
int32 LocateEnvStrStart (const KKStr &str)
KKStrListPtr osDirectoryList (KKStr dirName)
bool osFileNameMatchesSearchFields (const KKStr &fileName, KKStrListPtr searchFields)
KKStrListPtr osParseSearchSpec (const KKStr &searchSpec)
Variables
bool backGroundProcess = false
Function Documentation
int32 LocateEnvStrStart (const KKStr & str)
Definition at line 2544 of file OSservices.cpp.
References KKU::KKStr::Len(), KKU::KKStr::Str(), and x.
Referenced by KKU::osSubstituteInEvironmentVariables(), and SipperHardware::SipperVariables::SubstituteInEvironmentVariables().
KKStrListPtr osDirectoryList (KKStr dirName)
Definition at line 1384 of file OSservices.cpp.
References KKU::KKStr::Empty(), KKU::osAddLastSlash(), KKU::osGetCurrentDirectory(), and KKU::KKStr::Str().
Referenced by KKU::osGetListOfFiles().
bool osFileNameMatchesSearchFields (const KKStr & fileName, KKStrListPtr searchFields)
Definition at line 146 of file OSservices.cpp.
References KKU::KKStr::Len(), and KKU::KKStr::Str().
Referenced by KKU::osGetListOfFiles().
KKStrListPtr osParseSearchSpec (const KKStr & searchSpec)
Definition at line 97 of file OSservices.cpp.
References KKU::KKStr::Empty(), and KKU::KKStr::Str().
Referenced by KKU::osGetListOfFiles().
Variable Documentation
bool backGroundProcess = false
Definition at line 1311 of file OSservices.cpp.
Referenced by KKU::osDisplayWarning(), KKU::osIsBackGroundProcess(), KKU::osRunAsABackGroundProcess(), and KKU::osWaitForEnter().