Pices: D:/Users/kkramer/IEC/SipperSoftware/Apps/CrossValidation/CrossValidation_TEmp.cpp File Reference
CrossValidation_TEmp.cpp File Reference
#include "FirstIncludes.h"
#include <string>
#include <ctype.h>
#include <stdio.h>
#include <time.h>
#include <unistd.h>
#include <iomanip>
#include <iostream>
#include <fstream>
#include <map>
#include <vector>
#include "MemoryDebug.h"
#include "BasicTypes.h"
#include "StatisticalFunctions.h"
#include "Instrument.h"
#include "InstrumentDataFileManager.h"
#include "BinaryClassParms.h"
#include "Classifier2.h"
#include "CmdLineExpander.h"
#include "CrossValidation.h"
#include "CrossValidationVoting.h"
#include "CrossValidationThreeWay.h"
#include "CrossValidationMxN.h"
#include "DuplicateImages.h"
#include "FeatureFileIO.h"
#include "FeatureFileIOC45.h"
#include "FeatureFileIOPices.h"
#include "FeatureNumList.h"
#include "Orderings.h"
#include "OSservices.h"
#include "TrainingProcess2.h"
#include "CrossValidationApp.h"
#include "ModelParamDual.h"
#include "DataBase.h"
Classes
class CrossValidationRun
class CrossValidationSortByAccuracy
class CrossValidationSortBySupportPoints
class CrossValidationSortByTrainTime
Macros
#define thresholdMed 1000
#define thresholdSmall 500
Typedefs
typedef CrossValidationRun * CrossValidationRunPtr
Functions
void CreateBfsFromMfs (const KKStr &mfsFileName, const KKStr &srcBfs1Name, const KKStr &srcBfs2Name, const KKStr &srcBfs3Name, const KKStr &srcBfs4Name, const KKStr &srcBfs5Name)
int main (int argc, char **argv)
void MarineSnowReport ()
void MarineSnowReportDeployment (SipperDeploymentPtr deployment, DataBase &db)
void SetNineClassesTrainAndTest ()
void SetUpJMLRDataSet ()
void SetUpLetterDataSet ()
void SplitUpETPdataSet ()
void SplitUpForestData ()
Macro Definition Documentation
#define thresholdMed 1000
Definition at line 1203 of file CrossValidation_TEmp.cpp.
#define thresholdSmall 500
Definition at line 1202 of file CrossValidation_TEmp.cpp.
Typedef Documentation
typedef CrossValidationRun* CrossValidationRunPtr
Definition at line 1857 of file CrossValidation_TEmp.cpp.
Function Documentation
void CreateBfsFromMfs (const KKStr & mfsFileName, const KKStr & srcBfs1Name, const KKStr & srcBfs2Name, const KKStr & srcBfs3Name, const KKStr & srcBfs4Name, const KKStr & srcBfs5Name)
Definition at line 3039 of file CrossValidation_TEmp.cpp.
References MLL::BinaryCombos, KKU::endl(), KKU::KKStr::EqualIgnoreCase(), MLL::TrainingConfiguration2::ExamplesPerClass(), MLL::TrainingConfiguration2::ExtractClassList(), CrossValidationApp::fileDesc, MLL::TrainingConfiguration2::GetBinaryClassParms(), KKU::KKStr::Len(), MLL::TrainingConfiguration2::MachineType(), KKU::osGetRootNameWithExtension(), KKU::osRemoveExtension(), MLL::ModelParamDual::OtherClass(), MLL::BinaryClassParms::Param(), MLL::TrainingConfiguration2::RootDir(), MLL::TrainingConfiguration2::Save(), MLL::SelectByProbability, MLL::BinaryClassParms::SelectedFeatures(), MLL::TrainingConfiguration2::SelectionMethod(), MLL::TrainingConfiguration2::SetBinaryClassFields(), MLL::TrainingConfiguration2::SetFeatureNums(), MLL::MLClassConstList::SortByName(), KKU::KKStr::SubStrPart(), KKU::KKStr::Tail(), and MLL::BinaryClassParms::Weight().
int main (int argc, char ** argv)
Definition at line 3390 of file CrossValidation_TEmp.cpp.
References CreateBfsFromMfs(), CrossValidationApp::CrossValidationApp(), CrossValidationApp::Main(), and MarineSnowReport().
void MarineSnowReport ()
Definition at line 3369 of file CrossValidation_TEmp.cpp.
References MarineSnowReportDeployment(), CrossValidationApp::runLog, and MLL::DataBase::SipperDeploymentLoad().
void MarineSnowReportDeployment (SipperDeploymentPtr deployment, DataBase & db)
Definition at line 3164 of file CrossValidation_TEmp.cpp.
References CrossValidationApp::cancelFlag, SipperHardware::SipperDeployment::CruiseName(), SipperHardware::InstrumentDataMeans::denisityMean, SipperHardware::SipperDeployment::DeploymentNum(), KKU::endl(), SipperHardware::InstrumentDataMeans::fluorescenceMean, SipperHardware::InstrumentDataMeans::fluorescenceSensorMean, MLL::DataBase::InstrumentDataBinByMeterDepth(), KKU::KKStr::Len(), SipperHardware::InstrumentDataMeansList::LookUp(), KKU::KKStrMatrix::NumCols(), KKU::KKStrMatrix::NumRows(), KKU::osGetHostName(), KKU::osGetLocalDateTime(), KKU::osGetProgName(), KKU::osGetUserName(), SipperHardware::InstrumentDataMeans::Oxygen_molPerKg_Mean(), SipperHardware::InstrumentDataMeans::oxygenMean, MLL::DataBase::QueryStatementReturnAllColumns(), KKU::KKStr::QuotedStr(), SipperHardware::InstrumentDataMeans::salinityMean, MLL::DataBase::ServerDescription(), SipperHardware::SipperDeployment::StationName(), KKU::KKStr::Str(), SipperHardware::InstrumentDataMeans::temperatureMean, SipperHardware::InstrumentDataMeans::transmisivityMean, SipperHardware::InstrumentDataMeans::turbidityMean, SipperHardware::InstrumentDataMeans::volumeSampled, and x.
void SetNineClassesTrainAndTest ()
Definition at line 2839 of file CrossValidation_TEmp.cpp.
References MLL::FeatureVectorList::AddQueue(), MLL::FeatureVectorList::AllFeatures(), CrossValidationApp::cancelFlag, KKU::endl(), MLL::FeatureVectorList::FileDesc(), MLL::FeatureVectorList::PushOnBack(), MLL::FeatureVectorList::StratifyAmoungstClasses(), and CrossValidationApp::validationData.
void SetUpJMLRDataSet ()
Definition at line 2633 of file CrossValidation_TEmp.cpp.
References MLL::FeatureVectorList::AllFeatures(), CrossValidationApp::cancelFlag, CrossValidationApp::config, KKU::endl(), MLL::FeatureVectorList::FileDesc(), KKU::osWaitForEnter(), MLL::FeatureVectorList::PushOnBack(), MLL::TrainingConfiguration2::Save(), and MLL::FeatureVectorList::StratifyAmoungstClasses().
void SetUpLetterDataSet ()
Definition at line 2809 of file CrossValidation_TEmp.cpp.
References MLL::FeatureVectorList::AddQueue(), MLL::FeatureVectorList::AllFeatures(), and CrossValidationApp::cancelFlag.
void SplitUpETPdataSet ()
Definition at line 2710 of file CrossValidation_TEmp.cpp.
References MLL::FeatureVectorList::AllFeatures(), CrossValidationApp::cancelFlag, CrossValidationApp::config, KKU::endl(), MLL::FeatureVectorList::FileDesc(), Min(), KKU::osWaitForEnter(), MLL::FeatureVectorList::PushOnBack(), MLL::TrainingConfiguration2::Save(), MLL::FeatureVectorList::StratifyAmoungstClasses(), and CrossValidationApp::validationData.
void SplitUpForestData ()
Definition at line 2943 of file CrossValidation_TEmp.cpp.
References MLL::FeatureVectorList::AllFeatures(), CrossValidationApp::cancelFlag, KKU::endl(), MLL::FeatureVectorList::FileDesc(), KKU::osWaitForEnter(), MLL::FeatureVectorList::PushOnBack(), MLL::FeatureVectorList::StratifyAmoungstClasses(), and CrossValidationApp::validationData.