Pices: D:/Users/kkramer/IEC/SipperSoftware/SipperLibraries/ImageExtractionManager/ImageExtractionThread.cpp File Reference
ImageExtractionThread.cpp File Reference
#include "FirstIncludes.h"
#include <fstream>
#include <iostream>
#include <map>
#include <ostream>
#include <string>
#include <vector>
#include "MemoryDebug.h"
#include <windows.h>
#include "MsgQueue.h"
#include "ImageExtractionThread.h"
#include "ExtractionManager.h"
Classes
struct tagTHREADNAME_INFO
Macros
#define MS_VC_EXCEPTION 0x406D1388
Typedefs
typedef struct tagTHREADNAME_INFO THREADNAME_INFO
Functions
void SetThreadName (DWORD dwThreadID, const char *threadName)
unsigned int ThreadStartCallBack (void *param)
Macro Definition Documentation
#define MS_VC_EXCEPTION 0x406D1388
Definition at line 31 of file ImageExtractionThread.cpp.
Referenced by SetThreadName().
Typedef Documentation
typedef struct tagTHREADNAME_INFO THREADNAME_INFO
Function Documentation
void SetThreadName (DWORD dwThreadID, const char * threadName)
Definition at line 43 of file ImageExtractionThread.cpp.
References tagTHREADNAME_INFO::dwFlags, tagTHREADNAME_INFO::dwThreadID, tagTHREADNAME_INFO::dwType, SVM233::info(), MS_VC_EXCEPTION, and tagTHREADNAME_INFO::szName.
Referenced by ImageExtractionManager::ImageExtractionThread::Start().
unsigned int ThreadStartCallBack (void * param)
Definition at line 147 of file ImageExtractionThread.cpp.
References KKU::KKThread::Run(), ImageExtractionManager::ImageExtractionThread::Run(), KKU::KKThread::Status(), ImageExtractionManager::ImageExtractionThread::Status(), ImageExtractionManager::tsStarting, KKU::KKThread::tsStarting, ImageExtractionManager::tsStopped, and KKU::KKThread::tsStopped.
Referenced by ImageExtractionManager::ImageExtractionThread::Start().