Pices: D:/Users/kkramer/IEC/SipperSoftware/Apps/ImageExtractionWindows/ImageExtractionWindowsDlg.cpp File Reference
ImageExtractionWindowsDlg.cpp File Reference
#include "StdAfx.h"
#include "FirstIncludes.h"
#include <time.h>
#include <string>
#include <iostream>
#include <fstream>
#include <map>
#include <vector>
#include "MemoryDebug.h"
#include "BasicTypes.h"
#include "ClassStatistic.h"
#include "OSservices.h"
#include "SipperImageExtractionParms.h"
#include "SipperImageExtraction.h"
#include "ExtractionManager.h"
#include "ExtractionManagerStats.h"
#include "ImageExtractionWindows.h"
#include "ImageExtractionWindowsDlg.h"
Classes
class CAboutDlg
Macros
#define ImageExtractionTimerID 100
Typedefs
typedef wchar_t WCHAR
Functions
UINT ImageExtractionMultiThreaded (LPVOID pParam)
UINT ImageExtractionSingleThreaded (LPVOID pParam)
Macro Definition Documentation
#define ImageExtractionTimerID 100
Definition at line 40 of file ImageExtractionWindowsDlg.cpp.
Referenced by CImageExtractionWindowsDlg::OnInitDialog(), and CImageExtractionWindowsDlg::OnTimer().
Typedef Documentation
typedef wchar_t WCHAR
Definition at line 19 of file ImageExtractionWindowsDlg.cpp.
Function Documentation
UINT ImageExtractionMultiThreaded (LPVOID pParam)
Definition at line 688 of file ImageExtractionWindowsDlg.cpp.
References CImageExtractionWindowsDlg::ManageImageExtractionMultiThreaded(), and KKU::osRunAsABackGroundProcess().
UINT ImageExtractionSingleThreaded (LPVOID pParam)
Definition at line 701 of file ImageExtractionWindowsDlg.cpp.
References CImageExtractionWindowsDlg::ExtractionCanceled(), CImageExtractionWindowsDlg::ExtractionCrashed(), CImageExtractionWindowsDlg::ExtractionStopped(), CImageExtractionWindowsDlg::ImageExtractionParms(), KKU::osDisplayWarning(), and KKU::osRunAsABackGroundProcess().