Pices: D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/SVMModel.cpp File Reference
SVMModel.cpp File Reference
#include "FirstIncludes.h"
#include <stdio.h>
#include <string>
#include <iostream>
#include <fstream>
#include <math.h>
#include <vector>
#include <sstream>
#include <iomanip>
#include <set>
#include "MemoryDebug.h"
#include "BasicTypes.h"
#include "OSservices.h"
#include "RunLog.h"
#include "Str.h"
#include "SVMModel.h"
#include "MLLTypes.h"
#include "BitReduction.h"
#include "BinaryClassParms.h"
#include "FeatureEncoder.h"
#include "FeatureNumList.h"
#include "FeatureVector.h"
#include "SvmWrapper.h"
Namespaces
MLL
Namespace for all Machine Learning and SIPPER specific code.
Constant Groups
MLL
Namespace for all Machine Learning and SIPPER specific code.
Functions
double AdjProb (double prob)
template<class T >
void GetMaxIndex (T *vote, int32 voteLength, int32 &maxIndex1, int32 &maxIndex2)
bool MLL::PairCompareOperator (ProbNamePair l, ProbNamePair r)
Function Documentation
double AdjProb (double prob)
Definition at line 106 of file SVMModel.cpp.
Referenced by MLL::SVMModel::FindWorstSupportVectors(), and MLL::SVMModel::FindWorstSupportVectors2().
template<class T > void GetMaxIndex (T * vote, int32 voteLength, int32 & maxIndex1, int32 & maxIndex2)
Definition at line 40 of file SVMModel.cpp.
Referenced by ComputeProb(), and GreaterVotes().