Pices: MLL::SVMparam Class Reference
MLL::SVMparam Class Reference
this class encapsulates are the information neccesary to build a SVMModel class.
#include <SVMparam.h>
Public Member Functions
SVMparam (KKStr &_cmdLineStr, const FeatureNumList &_selectedFeatures, FileDescPtr _fileDesc, RunLog &_log, bool &_validFormat)
SVMparam (FileDescPtr _fileDesc, RunLog &_log)
SVMparam (const SVMparam &_svmParam)
~SVMparam ()
float A_Param () const
void A_Param (float _A)
void AddBinaryClassParms (BinaryClassParmsPtr binaryClassParms)
void AddBinaryClassParms (MLClassConstPtr class1, MLClassConstPtr class2, const svm_parameter &_param, const FeatureNumList &_selectedFeatures, float _weight)
Add a Binary parameters using svm_parametr cmd line str.
float AvgMumOfFeatures ()
float AvgNumOfFeatures (FeatureVectorListPtr trainExamples) const
returns back the average number of features per training example.
const BinaryClassParmsListPtr BinaryParmsList () const
int32 BitsToReduceBy () const
void BitsToReduceBy (int32 _bitsToReduceBy)
double C_Param () const
double C_Param (MLClassConstPtr class1, MLClassConstPtr class2) const
void C_Param (double _CC)
void C_Param (MLClassConstPtr class1, MLClassConstPtr class2, double cParam)
SVM_CompressionMethod CompressionMethod () const
void CompressionMethod (SVM_CompressionMethod _compMethod)
SVM_EncodingMethod EncodingMethod () const
void EncodingMethod (SVM_EncodingMethod _encodingMethod)
float FeatureCountNet () const
double Gamma () const
void Gamma (double _gamma)
void Gamma_Param (double _gamma)
BinaryClassParmsPtr GetBinaryClassParms (MLClassConstPtr class1, MLClassConstPtr class2)
If binary class parms don't exist will return NULL.
const FeatureNumList & GetFeatureNums () const
const FeatureNumList & GetFeatureNums (MLClassConstPtr class1, MLClassConstPtr class2) const
BinaryClassParmsPtr GetParamtersToUseFor2ClassCombo (MLClassConstPtr class1, MLClassConstPtr class2)
SVM_KernalType KernalType () const
void KernalType (SVM_KernalType _kernalType)
void Load (ClassAssignments &_mlClasses, KKStr &_fileName, bool &_successful)
SVM_MachineType MachineType () const
void MachineType (SVM_MachineType _machineType)
int32 MemoryConsumedEstimated () const
int32 NumOfFeaturesAfterEncoding () const
const svm_parameter & Param () const
void ParseCmdLineParameter (const KKStr &parameter, const KKStr &value, bool &parameterUsed, bool &_validFormat)
void ProcessSvmParameter (svm_parameter &_param, KKStr cmd, KKStr value, double valueNum, bool &parmUsed)
void ReadXML (FILE *i)
void ReadXML (istream &i)
float SamplingRate () const
void SamplingRate (float _samplingRate)
void Save (KKStr &_fileName, bool &_successful)
const FeatureNumList & SelectedFeatures () const
void SelectedFeatures (const FeatureNumList &_selectedFeatures)
SVM_SelectionMethod SelectionMethod () const
void SelectionMethod (SVM_SelectionMethod _selectionMethod)
void SetBinaryClassFields (MLClassConstPtr class1, MLClassConstPtr class2, const svm_parameter &_param, const FeatureNumList &_features, float _weight)
void SetFeatureNums (const FeatureNumList &_features)
void SetFeatureNums (MLClassConstPtr class1, MLClassConstPtr class2, const FeatureNumList &_features, float _weight=-1)
KKStr SvmParamToString (const svm_parameter &_param) const
Convert a svm_parameter struct to a cmdline str.
KKStr ToString () const
Convert all parameters to a command line string.
int32 UnBalancedBits () const
void UnBalancedBits (int32 _unBalancedBits)
KKStr UnBalancedBitsStr () const
void UnBalancedBitsStr (const KKStr &_unBalancedBitsStr)
bool UseProbabilityToBreakTies () const
bool WeightBitReduction () const
void WeightBitReduction (bool _weightBitReduction)
void WriteXML (std::ostream &o) const
Detailed Description
this class encapsulates are the information neccesary to build a SVMModel class.
         *
See Also
SVMModel
SVM233
BinaryClassParms
Definition at line 63 of file SVMparam.h.
Constructor & Destructor Documentation
MLL::SVMparam::SVMparam (KKStr & _cmdLineStr, const FeatureNumList & _selectedFeatures, FileDescPtr _fileDesc, RunLog & _log, bool & _validFormat)
Referenced by MemoryConsumedEstimated().
MLL::SVMparam::SVMparam (FileDescPtr _fileDesc, RunLog & _log)
SVMparam::SVMparam (const SVMparam & _svmParam)
Definition at line 115 of file SVMparam.cpp.
References MLL::BinaryClassParmsList::DuplicateListAndContents().
SVMparam::~SVMparam ()
Definition at line 147 of file SVMparam.cpp.
Member Function Documentation
float MLL::SVMparam::A_Param () const inline
Definition at line 136 of file SVMparam.h.
Referenced by MLL::ModelParamOldSVM::A_Param(), and MLL::ModelParamOldSVM::ParseCmdLine().
void SVMparam::A_Param (float _A)
Definition at line 170 of file SVMparam.cpp.
References SVM233::svm_parameter::A.
void SVMparam::AddBinaryClassParms (BinaryClassParmsPtr binaryClassParms)
Definition at line 674 of file SVMparam.cpp.
Referenced by MLL::ModelParamOldSVM::AddBinaryClassParms(), AddBinaryClassParms(), C_Param(), SetBinaryClassFields(), and SetFeatureNums().
void SVMparam::AddBinaryClassParms (MLClassConstPtr class1, MLClassConstPtr class2, const svm_parameter & _param, const FeatureNumList & _selectedFeatures, float _weight)
Add a Binary parameters using svm_parametr cmd line str.
Typically used by TrainingConfiguration.
Definition at line 941 of file SVMparam.cpp.
References AddBinaryClassParms().
float SVMparam::AvgMumOfFeatures ()
Definition at line 684 of file SVMparam.cpp.
References MLL::BinaryCombos, MLL::FeatureNumList::NumOfFeatures(), and MLL::BinaryClassParms::SelectedFeatures().
Referenced by MLL::ModelParamOldSVM::AvgMumOfFeatures().
float SVMparam::AvgNumOfFeatures (FeatureVectorListPtr trainExamples) const
returns back the average number of features per training example.
Will calculate the average number of features per tyraining example. For each binary class combination, multiplies the number of training examples for that pair by the number of features for that pair. the sum of all class pairs are then divided by the total number of examples.
Parameters
[in] trainExamples List of traninig examples that were or are to be used to train with.
Definition at line 721 of file SVMparam.cpp.
References MLL::BinaryCombos, MLL::ClassStatistic::Count(), MLL::FeatureVectorList::GetClassStatistics(), GetFeatureNums(), MLL::ClassStatistic::MLClass(), MLL::FeatureNumList::NumOfFeatures(), and MLL::FeatureNumList::NumSelFeatures().
Referenced by MLL::TrainingConfiguration2::AvgNumOfFeatures().
const BinaryClassParmsListPtr MLL::SVMparam::BinaryParmsList () const inline
Definition at line 139 of file SVMparam.h.
Referenced by MLL::ModelParamOldSVM::BinaryParmsList().
int32 MLL::SVMparam::BitsToReduceBy () const inline
Definition at line 141 of file SVMparam.h.
Referenced by MLL::ModelParamOldSVM::BitsToReduceBy(), and MLL::ModelParamOldSVM::ParseCmdLine().
void MLL::SVMparam::BitsToReduceBy (int32 _bitsToReduceBy) inline
Definition at line 186 of file SVMparam.h.
double MLL::SVMparam::C_Param () const inline
Definition at line 143 of file SVMparam.h.
Referenced by MLL::ModelParamOldSVM::C_Param(), C_Param(), MLL::FeatureEncoder::Compress(), and MLL::ModelParamOldSVM::ParseCmdLine().
double SVMparam::C_Param (MLClassConstPtr class1, MLClassConstPtr class2) const
Definition at line 845 of file SVMparam.cpp.
References MLL::BinaryClassParms::C(), KKU::endl(), and MLL::BinaryClassParmsList::LookUp().
void SVMparam::C_Param (double _CC)
Definition at line 178 of file SVMparam.cpp.
References SVM233::svm_parameter::C.
void SVMparam::C_Param (MLClassConstPtr class1, MLClassConstPtr class2, double cParam)
Definition at line 874 of file SVMparam.cpp.
References AddBinaryClassParms(), MLL::BinaryClassParms::C(), SVM233::svm_parameter::C, C_Param(), KKU::endl(), MLL::BinaryClassParmsList::LookUp(), and SelectedFeatures().
SVM_CompressionMethod MLL::SVMparam::CompressionMethod () const inline
Definition at line 148 of file SVMparam.h.
Referenced by MLL::BitReduction::compress(), MLL::FeatureEncoder::FeatureEncoder(), and MLL::ModelParamOldSVM::ParseCmdLine().
void MLL::SVMparam::CompressionMethod (SVM_CompressionMethod _compMethod) inline
Definition at line 193 of file SVMparam.h.
SVM_EncodingMethod MLL::SVMparam::EncodingMethod () const inline
Definition at line 150 of file SVMparam.h.
Referenced by MLL::BitReduction::BitReduction(), MLL::TrainingConfiguration2::EncodingMethod(), MLL::ModelParamOldSVM::EncodingMethod(), MLL::FeatureEncoder::FeatureEncoder(), MLL::SVMModel::NormalizeNominalAttributes(), NumOfFeaturesAfterEncoding(), and MLL::ModelParamOldSVM::ParseCmdLine().
void MLL::SVMparam::EncodingMethod (SVM_EncodingMethod _encodingMethod) inline
Definition at line 194 of file SVMparam.h.
float MLL::SVMparam::FeatureCountNet () const
double MLL::SVMparam::Gamma () const inline
Definition at line 154 of file SVMparam.h.
Referenced by MLL::ModelParamOldSVM::Gamma(), MLL::ModelParamOldSVM::Gamma_Param(), and MLL::ModelParamOldSVM::ParseCmdLine().
void MLL::SVMparam::Gamma (double _gamma) inline
Definition at line 195 of file SVMparam.h.
void MLL::SVMparam::Gamma_Param (double _gamma) inline
Definition at line 196 of file SVMparam.h.
BinaryClassParmsPtr SVMparam::GetBinaryClassParms (MLClassConstPtr class1, MLClassConstPtr class2)
If binary class parms don't exist will return NULL.
Definition at line 632 of file SVMparam.cpp.
References MLL::BinaryClassParmsList::LookUp().
Referenced by MLL::TrainingConfiguration2::GetBinaryClassParms().
const FeatureNumList & SVMparam::GetFeatureNums () const
Definition at line 646 of file SVMparam.cpp.
Referenced by AvgNumOfFeatures(), MLL::FeatureEncoder::FeatureEncoder(), MLL::ModelParamOldSVM::GetFeatureNums(), and MLL::SVMModel::GetFeatureNums().
const FeatureNumList & SVMparam::GetFeatureNums (MLClassConstPtr class1, MLClassConstPtr class2) const
Definition at line 652 of file SVMparam.cpp.
References MLL::BinaryClassParmsList::LookUp(), and MLL::BinaryClassParms::SelectedFeatures().
BinaryClassParmsPtr SVMparam::GetParamtersToUseFor2ClassCombo (MLClassConstPtr class1, MLClassConstPtr class2)
Definition at line 603 of file SVMparam.cpp.
References MLL::BinaryClassParmsList::LookUp().
Referenced by MLL::TrainingConfiguration2::BinaryClassParms(), and MLL::ModelParamOldSVM::GetParamtersToUseFor2ClassCombo().
SVM_KernalType MLL::SVMparam::KernalType () const inline
Definition at line 156 of file SVMparam.h.
Referenced by MLL::TrainingConfiguration2::KernalType(), and MLL::ModelParamOldSVM::KernalType().
void MLL::SVMparam::KernalType (SVM_KernalType _kernalType) inline
Definition at line 197 of file SVMparam.h.
void SVMparam::Load (ClassAssignments & _mlClasses, KKStr & _fileName, bool & _successful)
Definition at line 574 of file SVMparam.cpp.
References KKU::endl(), KKU::RunLog::Level(), KKU::osFOPEN(), ReadXML(), and KKU::KKStr::Str().
SVM_MachineType MLL::SVMparam::MachineType () const inline
Definition at line 158 of file SVMparam.h.
Referenced by MLL::ModelOldSVM::Description(), MLL::SVMModel::DistanceFromDecisionBoundary(), MLL::SVMModel::FindWorstSupportVectors(), MLL::SVMModel::FindWorstSupportVectors2(), MLL::ModelParamOldSVM::MachineType(), MLL::SVMModel::NumOfSupportVectors(), MLL::SVMModel::ProbabilitiesByClass(), MLL::SVMModel::SupportVectorNames(), MLL::SVMModel::SupportVectorStatistics(), and MLL::SVMModel::Write().
void MLL::SVMparam::MachineType (SVM_MachineType _machineType) inline
Definition at line 199 of file SVMparam.h.
int32 SVMparam::MemoryConsumedEstimated () const
Definition at line 153 of file SVMparam.cpp.
References MLL::BinaryClassParmsList::MemoryConsumedEstimated(), MLL::FeatureNumList::MemoryConsumedEstimated(), KKU::KKStr::MemoryConsumedEstimated(), and SVMparam().
Referenced by MLL::SVMModel::MemoryConsumedEstimated().
int32 SVMparam::NumOfFeaturesAfterEncoding () const
Definition at line 772 of file SVMparam.cpp.
References MLL::BinaryEncoding, MLL::FileDesc::Cardinality(), EncodingMethod(), MLL::NoEncoding, MLL::NominalAttribute, MLL::FeatureNumList::NumOfFeatures(), MLL::ScaledEncoding, MLL::SymbolicAttribute, and MLL::FileDesc::Type().
Referenced by MLL::ModelParamOldSVM::NumOfFeaturesAfterEncoding().
const svm_parameter& MLL::SVMparam::Param () const inline
Definition at line 164 of file SVMparam.h.
Referenced by MLL::ModelParamOldSVM::Param().
void SVMparam::ParseCmdLineParameter (const KKStr & parameter, const KKStr & value, bool & parameterUsed, bool & _validFormat)
Definition at line 187 of file SVMparam.cpp.
References MLL::CompressionMethodFromStr(), KKU::KKStr::Empty(), MLL::EncodingMethodFromStr(), KKU::endl(), KKU::RunLog::Level(), MLL::MachineType_NULL, MLL::MachineTypeFromStr(), SVM233::svm_parameter::ProcessSvmParameter(), MLL::SelectionMethod_NULL, MLL::SelectionMethodFromStr(), KKU::KKStr::Str(), KKU::KKStr::ToDouble(), and KKU::KKStr::Upper().
void MLL::SVMparam::ProcessSvmParameter (svm_parameter & _param, KKStr cmd, KKStr value, double valueNum, bool & parmUsed)
void SVMparam::ReadXML (FILE * i)
Definition at line 521 of file SVMparam.cpp.
References MLL::BinaryClassParmsList::CreateFromXML(), KKU::endl(), MLL::FeatureNumList::ExtractFeatureNumsFromStr(), KKU::KKStr::ExtractQuotedStr(), KKU::RunLog::Level(), and KKU::KKStr::Upper().
Referenced by Load(), and MLL::ModelParamOldSVM::ReadSpecificImplementationXML().
void MLL::SVMparam::ReadXML (istream & i)
float MLL::SVMparam::SamplingRate () const inline
Definition at line 166 of file SVMparam.h.
Referenced by MLL::ModelParamOldSVM::SamplingRate().
void MLL::SVMparam::SamplingRate (float _samplingRate) inline
Definition at line 200 of file SVMparam.h.
void SVMparam::Save (KKStr & _fileName, bool & _successful)
Definition at line 437 of file SVMparam.cpp.
References KKU::endl(), KKU::RunLog::Level(), KKU::KKStr::Str(), and WriteXML().
const FeatureNumList& MLL::SVMparam::SelectedFeatures () const inline
Definition at line 168 of file SVMparam.h.
Referenced by C_Param(), and MLL::ModelParamOldSVM::SelectedFeatures().
void MLL::SVMparam::SelectedFeatures (const FeatureNumList & _selectedFeatures) inline
Definition at line 201 of file SVMparam.h.
SVM_SelectionMethod MLL::SVMparam::SelectionMethod () const inline
Definition at line 170 of file SVMparam.h.
Referenced by MLL::ModelOldSVM::Description(), MLL::ModelOldSVM::ProbabilitiesByClass(), MLL::ModelParamOldSVM::SelectionMethod(), and MLL::SVMModel::SelectionMethod().
void MLL::SVMparam::SelectionMethod (SVM_SelectionMethod _selectionMethod) inline
Definition at line 221 of file SVMparam.h.
void SVMparam::SetBinaryClassFields (MLClassConstPtr class1, MLClassConstPtr class2, const svm_parameter & _param, const FeatureNumList & _features, float _weight)
Definition at line 906 of file SVMparam.cpp.
References AddBinaryClassParms(), MLL::BinaryClassParmsList::LookUp(), MLL::BinaryClassParms::Param(), MLL::BinaryClassParms::SelectedFeatures(), and MLL::BinaryClassParms::Weight().
Referenced by MLL::ModelParamOldSVM::SetBinaryClassFields().
void SVMparam::SetFeatureNums (const FeatureNumList & _features)
Definition at line 838 of file SVMparam.cpp.
Referenced by MLL::ModelParamOldSVM::SetFeatureNums().
void SVMparam::SetFeatureNums (MLClassConstPtr class1, MLClassConstPtr class2, const FeatureNumList & _features, float _weight = -1)
Definition at line 805 of file SVMparam.cpp.
References AddBinaryClassParms(), MLL::BinaryClassParmsList::LookUp(), MLL::BinaryClassParms::SelectedFeatures(), and MLL::BinaryClassParms::Weight().
KKStr SVMparam::SvmParamToString (const svm_parameter & _param) const
Convert a svm_parameter struct to a cmdline str.
Definition at line 374 of file SVMparam.cpp.
References KKU::endl(), KKU::RunLog::Level(), and SVM233::svm_parameter::ToCmdLineStr().
Referenced by ToString().
KKStr SVMparam::ToString () const
Convert all parameters to a command line string.
Definition at line 391 of file SVMparam.cpp.
References MLL::BoostSVM, MLL::BRnoCompression, MLL::CompressionMethodStr(), KKU::KKStr::Empty(), MLL::EncodingMethodToStr(), KKU::endl(), KKU::RunLog::Level(), MLL::MachineTypeToStr(), MLL::NoEncoding, MLL::SelectionMethodToStr(), and SvmParamToString().
Referenced by MLL::ModelParamOldSVM::ToCmdLineStr(), and WriteXML().
int32 MLL::SVMparam::UnBalancedBits () const inline
Definition at line 174 of file SVMparam.h.
Referenced by MLL::ModelParamOldSVM::ParseCmdLine(), and MLL::ModelParamOldSVM::UnBalancedBits().
void MLL::SVMparam::UnBalancedBits (int32 _unBalancedBits) inline
Definition at line 202 of file SVMparam.h.
KKStr MLL::SVMparam::UnBalancedBitsStr () const inline
Definition at line 177 of file SVMparam.h.
Referenced by MLL::ModelParamOldSVM::ParseCmdLine(), MLL::ModelParamOldSVM::UnBalancedBitsStr(), and MLL::TrainingConfiguration2::UnBalancedBitsStr().
void MLL::SVMparam::UnBalancedBitsStr (const KKStr & _unBalancedBitsStr) inline
Definition at line 203 of file SVMparam.h.
bool MLL::SVMparam::UseProbabilityToBreakTies () const inline
Definition at line 172 of file SVMparam.h.
Referenced by MLL::ModelParamOldSVM::UseProbabilityToBreakTies().
bool MLL::SVMparam::WeightBitReduction () const inline
Definition at line 180 of file SVMparam.h.
Referenced by MLL::FeatureEncoder::Compress(), MLL::ModelParamOldSVM::ParseCmdLine(), and MLL::ModelParamOldSVM::WeightBitReduction().
void MLL::SVMparam::WeightBitReduction (bool _weightBitReduction) inline
Definition at line 204 of file SVMparam.h.
void SVMparam::WriteXML (std::ostream & o) const
Definition at line 457 of file SVMparam.cpp.
References KKU::endl(), KKU::RunLog::Level(), KKU::KKStr::QuotedStr(), ToString(), MLL::FeatureNumList::ToString(), and MLL::BinaryClassParmsList::WriteXML().
Referenced by Save(), MLL::SVMModel::Write(), and MLL::ModelParamOldSVM::WriteSpecificImplementationXML().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/SVMparam.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/SVMparam.cpp