Pices: SipperHardware::SipperBuff Class Reference
SipperHardware::SipperBuff Class Reference abstract
to be used for all the different Sipper File Formats.
#include <SipperBuff.h>
Classes
struct SipperRec
Public Types
typedef KKU::int32 int32
typedef SipperBuff * SipperBuffPtr
typedef KKU::uint32 uint32
Public Member Functions
SipperBuff (InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
SipperBuff (const KKStr &_fileName, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
virtual ~SipperBuff ()
uint64 ByteOffset () const
uint32 BytesDropped () const
uint32 CurRow () const
uint64 CurRowByteOffset () const
void DetermineCropSettings (uint32 &cropLeft, uint32 &cropRght)
bool Eof () const
const KKStr & FileName () const
virtual void GetNextLine (uchar *lineBuff, uint32 lineBuffSize, uint32 &lineSize, uint32 colCount[], uint32 &pixelsInRow, bool &flow)=0
void InvalidLine (bool _invalidLine)
bool InvalidLine () const
virtual int32 LineWidth () const
Returns the width in pixles of the associated scanner file.
void Open (const KKStr &_fileName)
bool Opened () const
uint32 RecCount () const
void ReportInstrumentData (uchar sensorId, bool text, uchar sensorData)
void Reset ()
void ResetByteOffset (uint32 _byteOffset)
int32 ScanRate () const
void SkipOneByte ()
void SkipToScanLine (uint32 scanLine)
void SkipToScanLine (uint32 _scanLine, uint64 _byteOffset)
Static Public Member Functions
static SipperBuffPtr CreateSipperBuff (SipperFileFormat _format, KKStr _fileName, int32 _cameraNum, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
static SipperBuffPtr CreateSipperBuff (KKStr _fileName, int32 _cameraNum, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
static SipperFileFormat GuessFormatOfFile (const KKStr &_fileName, int32 _cameraNum, RunLog &_log)
Protected Member Functions
void AssignSerialPorts (const SipperHeaderRecPtr sipperHeaderRec)
Static Protected Member Functions
static void DisplaySipperRec (SipperBuff::SipperRec &sr)
static SipperFileFormat GuessFormatOfNextLine (FILE *in, int32 _cameraNum, RunLog &_log)
Protected Attributes
uint64 byteOffset
uint32 bytesDropped
uint32 curRow
uint64 curRowByteOffset
bool eof
KKStr fileName
FILE * inFile
InstrumentDataManagerPtr instrumentDataManager
bool invalidLine
bool iOwnInstrumentDataManager
RunLog & log
bool opened
uint32 recCount
Detailed Description
to be used for all the different Sipper File Formats.
See Also
InstrumentDataManager
Definition at line 66 of file SipperBuff.h.
Member Typedef Documentation
typedef KKU::int32 SipperHardware::SipperBuff::int32
Definition at line 70 of file SipperBuff.h.
typedef SipperBuff* SipperHardware::SipperBuff::SipperBuffPtr
Definition at line 69 of file SipperBuff.h.
typedef KKU::uint32 SipperHardware::SipperBuff::uint32
Definition at line 71 of file SipperBuff.h.
Constructor & Destructor Documentation
SipperBuff::SipperBuff (InstrumentDataManagerPtr _instrumentDataManager, RunLog & _log)
Definition at line 39 of file SipperBuff.cpp.
SipperBuff::SipperBuff (const KKStr & _fileName, InstrumentDataManagerPtr _instrumentDataManager, RunLog & _log)
Definition at line 61 of file SipperBuff.cpp.
References fileName, and Open().
SipperBuff::~SipperBuff () virtual
Definition at line 85 of file SipperBuff.cpp.
References inFile, instrumentDataManager, iOwnInstrumentDataManager, and opened.
Referenced by SipperHardware::Sipper3RevBuff::~Sipper3RevBuff(), SipperHardware::SipperBuff3Bit::~SipperBuff3Bit(), and SipperHardware::SipperBuffBinary::~SipperBuffBinary().
Member Function Documentation
void SipperBuff::AssignSerialPorts (const SipperHeaderRecPtr sipperHeaderRec) protected
Definition at line 116 of file SipperBuff.cpp.
References SipperHardware::InstrumentDataManager::AssignSerialPorts(), and instrumentDataManager.
uint64 SipperHardware::SipperBuff::ByteOffset () const inline
Definition at line 92 of file SipperBuff.h.
Referenced by SipperHardware::InstrumentDataList::CreateFromSipperFile(), and ImageExtractionManager::FrameExtractorThread::Run().
uint32 SipperHardware::SipperBuff::BytesDropped () const inline
Definition at line 91 of file SipperBuff.h.
SipperBuffPtr SipperBuff::CreateSipperBuff (SipperFileFormat _format, KKStr _fileName, int32 _cameraNum, InstrumentDataManagerPtr _instrumentDataManager, RunLog & _log) static
Definition at line 533 of file SipperBuff.cpp.
References GuessFormatOfFile(), Opened(), SipperHardware::sf3Bit, SipperHardware::sfBinary, SipperHardware::sfSipper3, SipperHardware::sfSipper3Rev, SipperHardware::sfSipper4Bit, and SipperHardware::sfUnKnown.
Referenced by SipperHardware::InstrumentDataList::CreateFromSipperFile(), CreateSipperBuff(), and SipperHardware::InstrumentDataFileManager::GetOrigSipperImage().
SipperBuffPtr SipperBuff::CreateSipperBuff (KKStr _fileName, int32 _cameraNum, InstrumentDataManagerPtr _instrumentDataManager, RunLog & _log) static
Definition at line 519 of file SipperBuff.cpp.
References CreateSipperBuff(), and GuessFormatOfFile().
uint32 SipperHardware::SipperBuff::CurRow () const inline
Definition at line 94 of file SipperBuff.h.
Referenced by SipperHardware::InstrumentDataList::CreateFromSipperFile(), and SipperHardware::InstrumentDataFileManager::GetOrigSipperImage().
uint64 SipperHardware::SipperBuff::CurRowByteOffset () const inline
Definition at line 95 of file SipperBuff.h.
Referenced by SipperHardware::InstrumentDataList::CreateFromSipperFile().
void SipperBuff::DetermineCropSettings (uint32 & cropLeft, uint32 & cropRght)
Definition at line 578 of file SipperBuff.cpp.
References eof, GetNextLine(), SVM289_MFS::Max(), and x.
Referenced by DetermineCropSettingsForDeployment().
void SipperBuff::DisplaySipperRec (SipperBuff::SipperRec & sr) static protected
Definition at line 300 of file SipperBuff.cpp.
References SipperHardware::SipperBuff::SipperRec::cameraNum, KKU::endl(), SipperHardware::SipperBuff::SipperRec::eol, SipperHardware::SipperBuff::SipperRec::flow, SipperHardware::SipperBuff::SipperRec::pix0, SipperHardware::SipperBuff::SipperRec::pix1, SipperHardware::SipperBuff::SipperRec::pix10, SipperHardware::SipperBuff::SipperRec::pix11, SipperHardware::SipperBuff::SipperRec::pix2, SipperHardware::SipperBuff::SipperRec::pix3, SipperHardware::SipperBuff::SipperRec::pix4, SipperHardware::SipperBuff::SipperRec::pix5, SipperHardware::SipperBuff::SipperRec::pix6, SipperHardware::SipperBuff::SipperRec::pix7, SipperHardware::SipperBuff::SipperRec::pix8, SipperHardware::SipperBuff::SipperRec::pix9, and SipperHardware::SipperBuff::SipperRec::raw.
bool SipperHardware::SipperBuff::Eof () const inline
Definition at line 96 of file SipperBuff.h.
Referenced by SipperHardware::InstrumentDataList::CreateFromSipperFile(), SipperHardware::SipperBuff4Bit::FileFormatGood(), and SipperHardware::InstrumentDataFileManager::GetOrigSipperImage().
const KKStr& SipperHardware::SipperBuff::FileName () const inline
Definition at line 83 of file SipperBuff.h.
virtual void SipperHardware::SipperBuff::GetNextLine (uchar * lineBuff, uint32 lineBuffSize, uint32 & lineSize, uint32 colCount[], uint32 & pixelsInRow, bool & flow) pure virtual
Implemented in SipperHardware::SipperBuff4Bit, SipperHardware::Sipper3Buff, SipperHardware::SipperBuffBinary, SipperHardware::SipperBuff3Bit, and SipperHardware::Sipper3RevBuff.
Referenced by SipperHardware::InstrumentDataList::CreateFromSipperFile(), DetermineCropSettings(), SipperHardware::InstrumentDataFileManager::GetOrigSipperImage(), and SkipToScanLine().
SipperFileFormat SipperBuff::GuessFormatOfFile (const KKStr & _fileName, int32 _cameraNum, RunLog & _log) static
Definition at line 417 of file SipperBuff.cpp.
References KKU::endl(), SipperHardware::Sipper3Buff::FileFormatGood(), SipperHardware::SipperBuff4Bit::FileFormatGood(), GuessFormatOfNextLine(), Opened(), SipperHardware::Sipper3Buff::Opened(), KKU::osFOPEN(), SipperHardware::sfSipper3, SipperHardware::sfSipper4Bit, SipperHardware::sfUnKnown, and KKU::KKStr::Str().
Referenced by CreateSipperBuff().
SipperFileFormat SipperBuff::GuessFormatOfNextLine (FILE * in, int32 _cameraNum, RunLog & _log) static protected
Definition at line 339 of file SipperBuff.cpp.
References SipperHardware::SipperBuff::SipperRec::cameraNum, SipperHardware::SipperBuff::SipperRec::eol, SipperHardware::SipperBuff::SipperRec::pix0, SipperHardware::SipperBuff::SipperRec::pix1, SipperHardware::SipperBuff::SipperRec::pix10, SipperHardware::SipperBuff::SipperRec::pix11, SipperHardware::SipperBuff::SipperRec::pix2, SipperHardware::SipperBuff::SipperRec::pix3, SipperHardware::SipperBuff::SipperRec::pix4, SipperHardware::SipperBuff::SipperRec::pix5, SipperHardware::SipperBuff::SipperRec::pix6, SipperHardware::SipperBuff::SipperRec::pix7, SipperHardware::SipperBuff::SipperRec::pix8, SipperHardware::SipperBuff::SipperRec::pix9, SipperHardware::SipperBuff::SipperRec::raw, SipperHardware::sf3Bit, SipperHardware::sfBinary, SipperHardware::sfUnKnown, and SIPPERRECSIZE.
Referenced by GuessFormatOfFile().
void SipperHardware::SipperBuff::InvalidLine (bool _invalidLine) inline
Definition at line 87 of file SipperBuff.h.
bool SipperHardware::SipperBuff::InvalidLine () const inline
Definition at line 97 of file SipperBuff.h.
Referenced by SipperHardware::Sipper3Buff::GetNextLine().
virtual int32 SipperHardware::SipperBuff::LineWidth () const inline virtual
Returns the width in pixles of the associated scanner file.
Definition at line 103 of file SipperBuff.h.
References MAXLINELEN.
void SipperBuff::Open (const KKStr & _fileName)
Definition at line 125 of file SipperBuff.cpp.
References KKU::endl(), eof, fileName, inFile, opened, KKU::osFOPEN(), and KKU::KKStr::Str().
Referenced by SipperBuff().
bool SipperHardware::SipperBuff::Opened () const inline
Definition at line 98 of file SipperBuff.h.
Referenced by CreateSipperBuff(), SipperHardware::SipperBuff4Bit::FileFormatGood(), and GuessFormatOfFile().
uint32 SipperHardware::SipperBuff::RecCount () const inline
Definition at line 99 of file SipperBuff.h.
void SipperBuff::ReportInstrumentData (uchar sensorId, bool text, uchar sensorData)
Definition at line 671 of file SipperBuff.cpp.
References curRow, KKU::KKStr::Empty(), fileName, instrumentDataManager, iOwnInstrumentDataManager, log, KKU::osAddSlash(), KKU::osGetCurrentDirectory(), KKU::osGetPathPartOfFile(), SipperHardware::SipperVariables::PicesReportDir(), and SipperHardware::InstrumentDataManager::ReportInstrumentData().
void SipperBuff::Reset ()
Definition at line 102 of file SipperBuff.cpp.
References bytesDropped, curRow, eof, inFile, opened, and recCount.
Referenced by SipperHardware::Sipper3RevBuff::FileFormatGood(), and SipperHardware::Sipper3Buff::FileFormatGood().
void SipperBuff::ResetByteOffset (uint32 _byteOffset)
Definition at line 146 of file SipperBuff.cpp.
References byteOffset, KKU::endl(), and inFile.
int32 SipperHardware::SipperBuff::ScanRate () const inline
Definition at line 100 of file SipperBuff.h.
void SipperBuff::SkipOneByte ()
Definition at line 167 of file SipperBuff.cpp.
References byteOffset, KKU::endl(), and inFile.
void SipperBuff::SkipToScanLine (uint32 scanLine)
Definition at line 185 of file SipperBuff.cpp.
References curRow, and GetNextLine().
Referenced by SipperHardware::InstrumentDataFileManager::GetOrigSipperImage().
void SipperBuff::SkipToScanLine (uint32 _scanLine, uint64 _byteOffset)
Definition at line 208 of file SipperBuff.cpp.
References byteOffset, curRow, eof, and inFile.
Member Data Documentation
uint64 SipperHardware::SipperBuff::byteOffset protected
Definition at line 171 of file SipperBuff.h.
Referenced by SipperHardware::Sipper3Buff::GetNextLine(), ResetByteOffset(), SipperHardware::Sipper3Buff::Sipper3Buff(), SipperHardware::Sipper3RevBuff::Sipper3RevBuff(), SipperHardware::SipperBuff3Bit::SipperBuff3Bit(), SipperHardware::SipperBuffBinary::SipperBuffBinary(), SkipOneByte(), and SkipToScanLine().
uint32 SipperHardware::SipperBuff::bytesDropped protected
Definition at line 170 of file SipperBuff.h.
Referenced by SipperHardware::SipperBuff3Bit::GetNextLine(), and Reset().
uint32 SipperHardware::SipperBuff::curRow protected
Definition at line 172 of file SipperBuff.h.
Referenced by SipperHardware::Sipper3RevBuff::CurRow(), SipperHardware::SipperBuff3Bit::CurRow(), SipperHardware::Sipper3RevBuff::GetNextLine(), SipperHardware::SipperBuff3Bit::GetNextLine(), SipperHardware::SipperBuffBinary::GetNextLine(), SipperHardware::Sipper3Buff::GetNextLine(), ReportInstrumentData(), Reset(), and SkipToScanLine().
uint64 SipperHardware::SipperBuff::curRowByteOffset protected
Definition at line 173 of file SipperBuff.h.
Referenced by SipperHardware::Sipper3Buff::GetNextLine().
bool SipperHardware::SipperBuff::eof protected
Definition at line 174 of file SipperBuff.h.
Referenced by DetermineCropSettings(), SipperHardware::Sipper3RevBuff::Eof(), SipperHardware::SipperBuff3Bit::Eof(), SipperHardware::Sipper3RevBuff::GetNextLine(), SipperHardware::SipperBuff3Bit::GetNextLine(), SipperHardware::SipperBuffBinary::GetNextLine(), SipperHardware::Sipper3Buff::GetNextLine(), Open(), Reset(), and SkipToScanLine().
KKStr SipperHardware::SipperBuff::fileName protected
Definition at line 175 of file SipperBuff.h.
Referenced by SipperHardware::Sipper3RevBuff::FileName(), SipperHardware::SipperBuff3Bit::FileName(), Open(), ReportInstrumentData(), and SipperBuff().
FILE* SipperHardware::SipperBuff::inFile protected
Definition at line 177 of file SipperBuff.h.
Referenced by Open(), Reset(), ResetByteOffset(), SkipOneByte(), SkipToScanLine(), and ~SipperBuff().
InstrumentDataManagerPtr SipperHardware::SipperBuff::instrumentDataManager protected
Definition at line 178 of file SipperBuff.h.
Referenced by AssignSerialPorts(), ReportInstrumentData(), and ~SipperBuff().
bool SipperHardware::SipperBuff::invalidLine protected
Definition at line 179 of file SipperBuff.h.
bool SipperHardware::SipperBuff::iOwnInstrumentDataManager protected
Definition at line 176 of file SipperBuff.h.
Referenced by ReportInstrumentData(), and ~SipperBuff().
RunLog& SipperHardware::SipperBuff::log protected
Definition at line 181 of file SipperBuff.h.
Referenced by ReportInstrumentData().
bool SipperHardware::SipperBuff::opened protected
Definition at line 182 of file SipperBuff.h.
Referenced by Open(), SipperHardware::Sipper3RevBuff::Opened(), SipperHardware::SipperBuff3Bit::Opened(), Reset(), and ~SipperBuff().
uint32 SipperHardware::SipperBuff::recCount protected
Definition at line 183 of file SipperBuff.h.
Referenced by SipperHardware::Sipper3RevBuff::RecCount(), SipperHardware::SipperBuff3Bit::RecCount(), and Reset().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/SipperBuff.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/SipperBuff.cpp