Pices: KKU::Point Class Reference
KKU::Point Class Reference
Used by Raster class methods to denote a single pixel location in Raster image.
#include <Point.h>
Public Member Functions
Point ()
Point (const Point &point)
Point (int16 _row, int16 _col)
Point (int32 _row, int32 _col)
Point (float _row, float _col)
int32 Col () const
void Col (int32 _col)
Point DownOne () const
Point LeftOne () const
bool operator!= (const Point &r) const
Point operator+ (const Point &r) const
Point operator- (const Point &r) const
Point & operator= (const Point &r)
bool operator== (Point &r) const
Point RightOne () const
int32 Row () const
void Row (int32 _row)
Point UpOne () const
Detailed Description
Used by Raster class methods to denote a single pixel location in Raster image.
See Also
Raster
Definition at line 19 of file Point.h.
Constructor & Destructor Documentation
Point::Point ()
Definition at line 18 of file Point.cpp.
Referenced by DownOne(), LeftOne(), operator+(), operator-(), RightOne(), and UpOne().
Point::Point (const Point & point)
Definition at line 26 of file Point.cpp.
Point::Point (int16 _row, int16 _col)
Definition at line 34 of file Point.cpp.
Point::Point (int32 _row, int32 _col)
Definition at line 43 of file Point.cpp.
Point::Point (float _row, float _col)
Definition at line 52 of file Point.cpp.
Member Function Documentation
int32 KKU::Point::Col () const inline
Definition at line 39 of file Point.h.
Referenced by KKU::PointList::BoxCoordinites(), KKU::PointList::CalculateCenterPoint(), KKU::PointList::ComputeSegmentLens(), KKU::ContourFollower::CreateFourierDescriptorBySampling(), DerivePreRotatedPoint(), Distance(), DistanceSquare(), KKU::Raster::DrawCircle(), KKU::Raster::DrawConnectedPointList(), KKU::Raster::DrawDot(), KKU::Raster::DrawLine(), KKU::Raster::DrawPointList(), KKU::ContourFollower::HistogramDistanceFromAPointOfEdge(), MLL::DataBase::ImageInsert(), KKU::operator<<(), PicesInterface::PicesPoint::PicesPoint(), KKU::Raster::SetPixelValue(), KKU::Raster::ThinContour(), and KKU::PointList::ToDelStr().
void KKU::Point::Col (int32 _col) inline
Definition at line 42 of file Point.h.
Point KKU::Point::DownOne () const inline
Definition at line 45 of file Point.h.
References Point().
Point KKU::Point::LeftOne () const inline
Definition at line 46 of file Point.h.
References Point().
bool Point::operator!= (const Point & r) const
Definition at line 66 of file Point.cpp.
Point Point::operator+ (const Point & r) const
Definition at line 72 of file Point.cpp.
References Point().
Point Point::operator- (const Point & r) const
Definition at line 78 of file Point.cpp.
References Point().
Point & Point::operator= (const Point & r)
Definition at line 84 of file Point.cpp.
bool Point::operator== (Point & r) const
Definition at line 60 of file Point.cpp.
Point KKU::Point::RightOne () const inline
Definition at line 47 of file Point.h.
References Point().
int32 KKU::Point::Row () const inline
Definition at line 38 of file Point.h.
Referenced by KKU::PointList::BoxCoordinites(), KKU::PointList::CalculateCenterPoint(), KKU::PointList::ComputeSegmentLens(), KKU::ContourFollower::CreateFourierDescriptorBySampling(), DerivePreRotatedPoint(), Distance(), DistanceSquare(), KKU::Raster::DrawCircle(), KKU::Raster::DrawConnectedPointList(), KKU::Raster::DrawDot(), KKU::Raster::DrawLine(), KKU::Raster::DrawPointList(), KKU::ContourFollower::HistogramDistanceFromAPointOfEdge(), MLL::DataBase::ImageInsert(), KKU::operator<<(), PicesInterface::PicesPoint::PicesPoint(), KKU::Raster::SetPixelValue(), KKU::Raster::ThinContour(), and KKU::PointList::ToDelStr().
void KKU::Point::Row (int32 _row) inline
Definition at line 41 of file Point.h.
Point KKU::Point::UpOne () const inline
Definition at line 44 of file Point.h.
References Point().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Point.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Point.cpp