Pices: SipperHardware::InstrumentDataManager Class Reference
SipperHardware::InstrumentDataManager Class Reference
data supplied by SipperBuff classes forwarding to appropriate 'InstrumentDataReport' derived objects.
#include <InstrumentDataManager.h>
Public Types
typedef KKU::int32 int32
typedef KKU::uint32 uint32
Public Member Functions
InstrumentDataManager (const KKStr &_sipperFileName, SipperFilePtr _sipperFile, const KKStr &_reportDir, RunLog &_log)
Creates new instance,.
InstrumentDataManager (const KKStr &_sipperFileName, SipperFilePtr _sipperFile, RunLog &_log)
Use this constructor if you only need to parse out the data.
~InstrumentDataManager ()
void AssignSerialPorts (const SipperHeaderRecPtr sipperHeaderRec)
void BatteryData (int32 _scanLine, int32 _activeBattery, const VectorFloat &_batteryLevels)
void CompReportLine (int32 scanLine)
InstrumentDataPtr CreateInstrumentData () const
const CTD_Plus_Data & CtdData () const
void CTDdataPlus (int32 _scanLine, const CTD_Plus_Data &_ctdData)
bool CtdDataRead () const
float Depth () const
void FlowRates (int32 _scanLine, float _meter1FlowRate, float _meter2FlowRate)
float Fluorescence () const
const TimeType & GpsTime () const
SipperHeaderRecPtr HeaderRec () const
double Latitude () const
void Latitude (double _latitude)
void Location (int32 _scanLine, double _latitude, double _longitude, const TimeType &_gpsTime)
double Longitude () const
void Longitude (double _longitude)
void Meter1FlowRate (int32 _scanLine, float _meter1FlowRate)
float Meter1FlowRate () const
void Meter2FlowRate (int32 _scanLine, float _meter2FlowRate)
float Meter2FlowRate () const
float Oxygen () const
void PitchAndRollData (int32 _scanLine, float _pitch, float _roll)
float RecordRate () const
void RecordRate (float _recordRate)
void ReportInstrumentData (uint32 curScanLine, uchar instrumentId, bool text, uchar data)
When ever SipperBuff gets instrument data, reports thru this method.
float Salinity () const
VectorUlong * ScanLinesPerMeterDepth () const
SipperFilePtr SipperFile ()
const KKStr & SipperFileName () const
Detailed Description
data supplied by SipperBuff classes forwarding to appropriate 'InstrumentDataReport' derived objects.
Definition at line 61 of file InstrumentDataManager.h.
Member Typedef Documentation
typedef KKU::int32 SipperHardware::InstrumentDataManager::int32
Definition at line 64 of file InstrumentDataManager.h.
typedef KKU::uint32 SipperHardware::InstrumentDataManager::uint32
Definition at line 65 of file InstrumentDataManager.h.
Constructor & Destructor Documentation
InstrumentDataManager::InstrumentDataManager (const KKStr & _sipperFileName, SipperFilePtr _sipperFile, const KKStr & _reportDir, RunLog & _log)
Creates new instance,.
Parameters
[in] _sipperFileName Name of Sipper file that is being processed.
[in] _sipperFile An instance of a SipperFile object that contains SIPPER configuration data for specific SIPPER file.
[in] _reportDir Directory where to place Instrument/Sensor data/text files.
[in] _log A logfile stream. All important events will be output to this stream
Definition at line 26 of file InstrumentDataManager.cpp.
References KKU::KKStr::Empty(), KKU::endl(), SipperHardware::CTD_Plus_Data::Header1Str(), SipperHardware::CTD_Plus_Data::Header2Str(), MaxNumOfInstruments, KKU::osAddSlash(), KKU::osCreateDirectoryPath(), KKU::osGetFileDateTime(), KKU::osGetLocalDateTime(), KKU::osGetRootName(), KKU::KKStr::Str(), and x.
InstrumentDataManager::InstrumentDataManager (const KKStr & _sipperFileName, SipperFilePtr _sipperFile, RunLog & _log)
Use this constructor if you only need to parse out the data.
Parameters
[in] _sipperFileName Name of Sipper file that is being processed.
[in] _sipperFile An instance of a SipperFile object that contains SIPPER configuration data for specific SIPPER file.
[in] _log A log-file stream. All important events will be output to this stream
Definition at line 99 of file InstrumentDataManager.cpp.
References MaxNumOfInstruments, and x.
InstrumentDataManager::~InstrumentDataManager ()
Definition at line 151 of file InstrumentDataManager.cpp.
References MaxNumOfInstruments, and x.
Member Function Documentation
void InstrumentDataManager::AssignSerialPorts (const SipperHeaderRecPtr sipperHeaderRec)
Definition at line 273 of file InstrumentDataManager.cpp.
Referenced by SipperHardware::SipperBuff::AssignSerialPorts().
void InstrumentDataManager::BatteryData (int32 _scanLine, int32 _activeBattery, const VectorFloat & _batteryLevels)
Definition at line 366 of file InstrumentDataManager.cpp.
References CompReportLine().
Referenced by SipperHardware::InstrumentDataBatteryMeter::ProcessBatteryData().
void InstrumentDataManager::CompReportLine (int32 scanLine)
Definition at line 296 of file InstrumentDataManager.cpp.
References SipperHardware::CTD_Plus_Data::Date(), SipperHardware::CTD_Plus_Data::Depth(), KKU::endl(), Min(), KKU::DateTime::Seconds(), KKU::StrFormatDouble(), KKU::StrFormatInt(), SipperHardware::CTD_Plus_Data::ToStrNoLabels(), and x.
Referenced by BatteryData(), CTDdataPlus(), FlowRates(), Location(), Meter1FlowRate(), Meter2FlowRate(), and PitchAndRollData().
InstrumentDataPtr InstrumentDataManager::CreateInstrumentData () const
Definition at line 229 of file InstrumentDataManager.cpp.
References SipperHardware::CTD_Plus_Data::BatteryVoltage(), SipperHardware::CTD_Plus_Data::CdomFluorescence(), SipperHardware::CTD_Plus_Data::CdomFluorescenceSensor(), SipperHardware::CTD_Plus_Data::Conductivity(), SipperHardware::CTD_Plus_Data::Date(), SipperHardware::CTD_Plus_Data::Density(), SipperHardware::CTD_Plus_Data::Depth(), SipperHardware::CTD_Plus_Data::Fluorescence(), SipperHardware::CTD_Plus_Data::FluorescenceSensor(), SipperHardware::CTD_Plus_Data::Oxygen(), SipperHardware::CTD_Plus_Data::OxygenSensor(), SipperHardware::CTD_Plus_Data::Pressure(), SipperHardware::CTD_Plus_Data::Salinity(), SipperHardware::CTD_Plus_Data::SoundVelocity(), SipperHardware::CTD_Plus_Data::Temperature(), SipperHardware::CTD_Plus_Data::Transmisivity(), SipperHardware::CTD_Plus_Data::TransmisivitySensor(), SipperHardware::CTD_Plus_Data::Turbidity(), and SipperHardware::CTD_Plus_Data::TurbiditySensor().
Referenced by SipperHardware::InstrumentDataList::CreateFromSipperFile().
const CTD_Plus_Data& SipperHardware::InstrumentDataManager::CtdData () const inline
Definition at line 156 of file InstrumentDataManager.h.
void InstrumentDataManager::CTDdataPlus (int32 _scanLine, const CTD_Plus_Data & _ctdData)
Definition at line 346 of file InstrumentDataManager.cpp.
References CompReportLine(), and SipperHardware::CTD_Plus_Data::ValidData().
bool SipperHardware::InstrumentDataManager::CtdDataRead () const inline
Definition at line 153 of file InstrumentDataManager.h.
float SipperHardware::InstrumentDataManager::Depth () const inline
Definition at line 158 of file InstrumentDataManager.h.
void InstrumentDataManager::FlowRates (int32 _scanLine, float _meter1FlowRate, float _meter2FlowRate)
Definition at line 443 of file InstrumentDataManager.cpp.
References CompReportLine().
float SipperHardware::InstrumentDataManager::Fluorescence () const inline
Definition at line 168 of file InstrumentDataManager.h.
const TimeType& SipperHardware::InstrumentDataManager::GpsTime () const inline
Definition at line 160 of file InstrumentDataManager.h.
SipperHeaderRecPtr SipperHardware::InstrumentDataManager::HeaderRec () const inline
Definition at line 170 of file InstrumentDataManager.h.
Referenced by SipperHardware::InstrumentDataReport::CreateInstrumentDataReport().
double SipperHardware::InstrumentDataManager::Latitude () const inline
Definition at line 161 of file InstrumentDataManager.h.
void SipperHardware::InstrumentDataManager::Latitude (double _latitude) inline
Definition at line 172 of file InstrumentDataManager.h.
void InstrumentDataManager::Location (int32 _scanLine, double _latitude, double _longitude, const TimeType & _gpsTime)
Definition at line 397 of file InstrumentDataManager.cpp.
References CompReportLine().
double SipperHardware::InstrumentDataManager::Longitude () const inline
Definition at line 162 of file InstrumentDataManager.h.
void SipperHardware::InstrumentDataManager::Longitude (double _longitude) inline
Definition at line 173 of file InstrumentDataManager.h.
void InstrumentDataManager::Meter1FlowRate (int32 _scanLine, float _meter1FlowRate)
Definition at line 416 of file InstrumentDataManager.cpp.
References CompReportLine().
Referenced by SipperHardware::InstrumentDataFlowMeter1::ReportInstrumentData().
float SipperHardware::InstrumentDataManager::Meter1FlowRate () const inline
Definition at line 163 of file InstrumentDataManager.h.
void InstrumentDataManager::Meter2FlowRate (int32 _scanLine, float _meter2FlowRate)
Definition at line 429 of file InstrumentDataManager.cpp.
References CompReportLine().
Referenced by SipperHardware::InstrumentDataFlowMeter1::ReportInstrumentData().
float SipperHardware::InstrumentDataManager::Meter2FlowRate () const inline
Definition at line 164 of file InstrumentDataManager.h.
float SipperHardware::InstrumentDataManager::Oxygen () const inline
Definition at line 167 of file InstrumentDataManager.h.
void InstrumentDataManager::PitchAndRollData (int32 _scanLine, float _pitch, float _roll)
Definition at line 381 of file InstrumentDataManager.cpp.
References CompReportLine().
float SipperHardware::InstrumentDataManager::RecordRate () const inline
Definition at line 165 of file InstrumentDataManager.h.
void SipperHardware::InstrumentDataManager::RecordRate (float _recordRate) inline
Definition at line 174 of file InstrumentDataManager.h.
void InstrumentDataManager::ReportInstrumentData (uint32 curScanLine, uchar instrumentId, bool text, uchar data)
When ever SipperBuff gets instrument data, reports thru this method.
Parameters
[in] curScanLine Scan line that was last read when encountering this "Instrumentdata".
[in] InstrumentID Sensor/Instrument ID
[in] text Set to true = text data, false = binary data.
[in] data data from SIPPER file.
Definition at line 459 of file InstrumentDataManager.cpp.
References SipperHardware::InstrumentDataReport::CreateInstrumentDataReport(), KKU::endl(), KKU::RunLog::Level(), MaxNumOfInstruments, and SipperHardware::InstrumentDataReport::ReportInstrumentData().
Referenced by SipperHardware::SipperBuff::ReportInstrumentData().
float SipperHardware::InstrumentDataManager::Salinity () const inline
Definition at line 166 of file InstrumentDataManager.h.
VectorUlong * InstrumentDataManager::ScanLinesPerMeterDepth () const
Definition at line 283 of file InstrumentDataManager.cpp.
References x.
SipperFilePtr SipperHardware::InstrumentDataManager::SipperFile () inline
Definition at line 98 of file InstrumentDataManager.h.
const KKStr& SipperHardware::InstrumentDataManager::SipperFileName () const inline
Definition at line 176 of file InstrumentDataManager.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/InstrumentDataManager.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/InstrumentDataManager.cpp