Pices: KKU::KKThreadManager Class Reference
KKU::KKThreadManager Class Reference
#include <KKThreadManager.h>
Public Member Functions
KKThreadManager (const KKStr &_managerName, uint32 _maxNumThreads, MsgQueuePtr _msgQueue)
~KKThreadManager ()
void AddThread (KKThreadPtr _thread)
Add thread that is to be managed; will take ownership.
bool AllThreadsTerminated ()
bool AnyProcessorsCrashed ()
const bool & Crashed () const
const bool & DoneExecuting () const
void KillAllRunningThreads ()
Will STOP ALL running threads; NOT Gracefull;.
void ManageThreads (bool &successful)
void RequestShutdown ()
void RequestTerminate ()
virtual void Run ()
const bool & ShutdownFlag () const
void ShutdownProcessing (int32 miliSecsToWait)
Shutdown all threads in a orderly way; observing prerequisite ordering.
void TerminateProcessing ()
Flag all All running threads to Termninate ASAP and release all allocated resources.
Public Member Functions inherited from KKU::KKThread
KKThread (const KKStr &_threadName, KKThreadManagerPtr _threadManager, MsgQueuePtr _msgQueue)
virtual ~KKThread ()
void AddShutdownPrerequistite (KKThreadPtr _thread)
Specify threads that must stop before this thread is started.
void AddStartPrerequistite (KKThreadPtr _thread)
Specify threads that must start before this thread is started.
volatile const bool & CancelFlag () const
bool Crashed () const
void Crashed (bool _crashed)
void Kill ()
stops the running thread and frees the thread handle
bool OkToShutdown () const
Returns 'true' if all shutdown prerequisites are in the 'tsStopped' status.
bool OkToStart () const
Returns 'true' if all start prerequisites are in the 'tsRunning' status.
volatile const bool & ShutdownFlag () const
void ShutdownThread ()
Call this method to have its thread finish what ever is in the queue and then exit.
void Start (bool &successful)
Call this method to start thread; it will call the method "Run".
ThreadStatus Status () const
void Status (ThreadStatus _status)
void TerminateThread ()
Call this method to have its thread stop right away and exit.
const KKStr & ThreadName () const
Additional Inherited Members
Public Types inherited from KKU::KKThread
typedef KKThread * KKThreadPtr
enum ThreadStatus {
tsNotStarted, tsStarting, tsRunning, tsStopping,
tsStopped
}
Protected Member Functions inherited from KKU::KKThread
void AddMsg (KKStrPtr msg)
Taking ownership of 'msg' and will append to 'msgQueue'.
void AddMsg (const KKStr &msg)
A copy of the message 'msg' will be added to the end of msgQueue.
bool CancelOrTerminateRequested ()
bool ThereIsACircularReferenceShutdown (KKThreadPtr _thread) const
bool ThereIsACircularReferenceStart (KKThreadPtr _thread) const
Detailed Description
There are three ways to stop Thread processing with the forst being the most gracefull and the last being the most abrut.
1) 'ShutdownProcessing'  The preferred method;  each thread is flagged for 'Shutdown' after all its prerequisite shutdown threads
   have shutdown.
2) 'TerminateProcessing' Similar to 'ShutdownProcessing' except the prerequisites are not checked; each thread is imediatly flagged
   to Terminate which indicates to the thread that it is to cease all processing and exit while relasing all resources.
3) 'KillAllRunningThreads' A last resort;  you would call this if for some reason threads are not terminating on there own.
Definition at line 33 of file KKThreadManager.h.
Constructor & Destructor Documentation
KKThreadManager::KKThreadManager (const KKStr & _managerName, uint32 _maxNumThreads, MsgQueuePtr _msgQueue)
Definition at line 23 of file KKThreadManager.cpp.
KKThreadManager::~KKThreadManager ()
Definition at line 45 of file KKThreadManager.cpp.
Member Function Documentation
void KKThreadManager::AddThread (KKThreadPtr _thread)
Add thread that is to be managed; will take ownership.
Definition at line 53 of file KKThreadManager.cpp.
bool KKThreadManager::AllThreadsTerminated ()
Definition at line 278 of file KKThreadManager.cpp.
References KKU::KKThread::Status(), and KKU::KKThread::tsStopped.
bool KKThreadManager::AnyProcessorsCrashed ()
Definition at line 253 of file KKThreadManager.cpp.
References KKU::KKThread::Crashed().
Referenced by ManageThreads().
const bool& KKU::KKThreadManager::Crashed () const inline
Definition at line 44 of file KKThreadManager.h.
const bool& KKU::KKThreadManager::DoneExecuting () const inline
Definition at line 45 of file KKThreadManager.h.
void KKThreadManager::KillAllRunningThreads ()
Will STOP ALL running threads; NOT Gracefull;.
Definition at line 183 of file KKThreadManager.cpp.
References KKU::KKThread::Kill().
Referenced by ShutdownProcessing().
void KKThreadManager::ManageThreads (bool & successful)
Definition at line 303 of file KKThreadManager.cpp.
References KKU::KKThread::AddMsg(), AnyProcessorsCrashed(), KKU::osSleep(), ShutdownProcessing(), and TerminateProcessing().
void KKThreadManager::RequestShutdown ()
Definition at line 63 of file KKThreadManager.cpp.
void KKThreadManager::RequestTerminate ()
Definition at line 69 of file KKThreadManager.cpp.
void KKThreadManager::Run () virtual
Reimplemented from KKU::KKThread.
Definition at line 346 of file KKThreadManager.cpp.
const bool& KKU::KKThreadManager::ShutdownFlag () const inline
Definition at line 43 of file KKThreadManager.h.
void KKThreadManager::ShutdownProcessing (int32 miliSecsToWait)
Shutdown all threads in a orderly way; observing prerequisite ordering.
Definition at line 94 of file KKThreadManager.cpp.
References KillAllRunningThreads(), KKU::KKThread::OkToShutdown(), KKU::osSleep(), KKU::KKThread::ShutdownFlag(), KKU::KKThread::ShutdownThread(), KKU::KKThread::Status(), KKU::KKThread::tsNotStarted, KKU::KKThread::tsRunning, KKU::KKThread::tsStarting, KKU::KKThread::tsStopped, and KKU::KKThread::tsStopping.
Referenced by ManageThreads().
void KKThreadManager::TerminateProcessing ()
Flag all All running threads to Termninate ASAP and release all allocated resources.
Definition at line 77 of file KKThreadManager.cpp.
References KKU::KKThread::TerminateThread().
Referenced by ManageThreads().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/KKThreadManager.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/KKThreadManager.cpp