Pices: KKU::Raster Class Reference
KKU::Raster Class Reference
A class that is used by to represent a single image in memory.
#include <Raster.h>
Public Types
typedef Raster * RasterPtr
Public Member Functions
Raster ()
Raster (const Raster &_raster)
Copy Constructor.
Raster (int32 _height, int32 _width)
Constructs a blank GrayScale image with given dimensions; all pixels will be initialized to 0.
Raster (int32 _height, int32 _width, bool _color)
Constructs a blank image with given dimensions.
Raster (const BmpImage &_bmpImage)
Constructs a Raster from a BMP image loaded from disk.
Raster (const Raster &_raster, int32 _row, int32 _col, int32 _height, int32 _width)
Constructs a new Raster using a subset of the specified Raster as its source.
Raster (const Raster &_raster, MaskTypes _mask, int32 _row, int32 _col)
Constructs a Raster that will be as large as the specified '_mask' at the point specified by '_row' and '_col'.
Raster (const KKStr &fileName, bool &validFile)
Constructs a Raster image from by reading an existing image File such as a BMP file.
Raster (int32 _height, int32 _width, uchar *_grayScaleData, uchar **_grayScaleRows)
Construct a raster object that will utilize a image already in memory.
Raster (int32 _height, int32 _width, const uchar *_grayScaleData)
Construct a Grayscale Raster object using provided raw data,.
Raster (int32 _height, int32 _width, const uchar *_redChannel, const uchar *_greenChannel, const uchar *_blueChannel)
Construct a Color Raster object using provided raw data,.
virtual ~Raster ()
virtual RasterPtr AllocateARasterInstance (int32 height, int32 width, bool color) const
virtual RasterPtr AllocateARasterInstance (const Raster &r) const
virtual RasterPtr AllocateARasterInstance (const Raster &_raster, int32 _row, int32 _col, int32 _height, int32 _width) const
uchar BackgroundPixelTH () const
void BackgroundPixelTH (uchar _backgroundPixelTH)
uchar BackgroundPixelValue () const
void BackgroundPixelValue (uchar _backgroundPixelValue)
RasterPtr BandPass (float lowerFreqBound, float upperFreqBound)
Returns a image that is the result of a BandPass using Fourier Transforms.
RasterPtr BinarizeByThreshold (uchar min, uchar max)
int32 BlobId (int32 row, int32 col) const
Return the ID of the blob that the specified pixel location belongs to.
uchar ** Blue () const
returns a pointer to two dimensional array for 'Blue' color channel.
uchar * BlueArea () const
int32 CalcArea ()
void CalcAreaAndIntensityFeatures (int32 &area, float &weighedSize, uint32 intensityHistBuckets[8], int32 &areaWithWhiteSpace, uint32 intensityHistBucketsWhiteSpace[8])
Calculates both Intensity Histograms, one not including internal background pixels and one with plus size and weighted size.
void CalcAreaAndIntensityFeatures (int32 &area, float &weighedSize, uint32 intensityHistBuckets[8])
Calculates both Intensity Histograms, one not including internal background pixels and one with plus size and weighted size.
void CalcAreaAndIntensityHistogram (int32 &area, uint32 intensityHistBuckets[8])
Calculates the occurrence of different intensity levels.
void CalcAreaAndIntensityHistogramWhite (int32 &area, uint32 intensityHistBuckets[8])
Calculates a Intensity Histogram including Background pixels in the image.
void CalcCentroid (int32 &size, int32 &weight, float &rowCenter, float &colCenter, float &rowCenterWeighted, float &colCenterWeighted)
void CalcOrientationAndEigerRatio (float &eigenRatio, float &orientationAngle)
float CalcWeightedArea () const
float CenMoment (int32 p, int32 q, float ew, float eh) const
float CenMomentWeighted (int32 p, int32 q, float ew, float eh) const
void CentralMoments (float features[9]) const
void CentralMomentsWeighted (float features[9]) const
float CentroidCol ()
float CentroidRow ()
void Closing ()
void Closing (MaskTypes mask)
bool Color () const
void ConnectedComponent (uchar connectedComponentDist)
void ConnectedComponent8Conected ()
void ConnectedComponentOrig ()
RasterPtr CreateColorImageFromLabels ()
Produces a color image using the 'greenArea' channel, assuming that each unique value will be assigned a unique color.
RasterPtr CreateColorWithBlobsLabeldByColor (BlobListPtr blobs)
Returns image where each blob is labeled with a different color.
RasterPtr CreateDialatedRaster () const
RasterPtr CreateDialatedRaster (MaskTypes mask) const
RasterPtr CreateErodedImage (MaskTypes mask) const
RasterPtr CreateFromOrginalImageWithSpecifidBlobsOnly (RasterPtr origImage, BlobListPtr blobs)
Returns a copy of 'origImage' where only the blobs specified in 'blobs' are copied over.
RasterPtr CreateGaussianSmoothedImage (float sigma) const
RasterPtr CreateGrayScale () const
RasterPtr CreateGrayScaleKLT () const
Creates a grayscale image using a KLT Transform with the goal of weighting in favor the color channels with greatest amount of variance.
RasterPtr CreateGrayScaleKLTOnMaskedArea (const Raster &mask) const
Same as 'CreateGrayScaleKLT' except it will only take into account pixels specified by the 'mask' image.
RasterPtr CreateSmoothedMediumImage (int32 maskSize) const
RasterPtr CreateSmoothImage (int32 maskSize=3) const
void Dialation ()
void Dialation (MaskTypes mask)
void DrawCircle (const Point &point, int32 radius, const PixelValue &color)
Draw a circle who's center is at 'point' and radius in pixels is 'radius'using color 'color'.
void DrawCircle (float centerRow, float centerCol, float radius, const PixelValue &pixelValue)
void DrawCircle (float centerRow, float centerCol, float radius, float startAngle, float endAngle, const PixelValue &pixelValue)
void DrawConnectedPointList (Point offset, const PointList &borderPixs, const PixelValue &pixelValue, const PixelValue &linePixelValue)
void DrawDot (const Point &point, const PixelValue &color, int32 size)
void DrawGrid (float pixelsPerMinor, uint32 minorsPerMajor, const PixelValue &hashColor, const PixelValue &gridColor)
void DrawLine (int32 bpRow, int32 bpCol, int32 epRow, int32 epCol)
void DrawLine (int32 bpRow, int32 bpCol, int32 epRow, int32 epCol, uchar pixelVal)
void DrawLine (const Point &beginPoint, const Point &endPoint, uchar pixelVal)
void DrawLine (const Point &beginPoint, const Point &endPoint, const PixelValue &pixelVal)
void DrawLine (int32 bpRow, int32 bpCol, int32 epRow, int32 epCol, uchar r, uchar g, uchar b)
void DrawLine (int32 bpRow, int32 bpCol, int32 epRow, int32 epCol, uchar r, uchar g, uchar b, float alpha)
void DrawLine (int32 bpRow, int32 bpCol, int32 epRow, int32 epCol, PixelValue pixelVal)
void DrawLine (int32 bpRow, int32 bpCol, int32 epRow, int32 epCol, PixelValue pixelVal, float alpha)
void DrawPointList (const PointList &borderPixs, const PixelValue &pixelValue)
void DrawPointList (Point offset, const PointList &borderPixs, const PixelValue &pixelValue)
void DrawPointList (const PointList &borderPixs, uchar redVal, uchar greenVal, uchar blueVal)
void DrawPointList (Point offset, const PointList &borderPixs, uchar redVal, uchar greenVal, uchar blueVal)
void Edge ()
reduces image to edge pixels only.
void ErodeSpurs ()
removes spurs from image.
void Erosion ()
void Erosion (MaskTypes mask)
void ErosionBoundary (MaskTypes mask, int32 blobrowstart, int32 blobrowend, int32 blobcolstart, int32 blobcolend)
void ErosionChanged (MaskTypes mask, int32 row, int32 col)
void ErosionChanged1 (MaskTypes mask, int32 row, int32 col)
RasterPtr ExtractABlob (const BlobPtr blob) const
Extracts a specified blob from this image; useful to extract individual detected blobs.
RasterPtr ExtractABlobTightly (const BlobPtr blob, int32 padding) const
Extracts a specified blob from this image into a tightly bounded image.
BlobListPtr ExtractBlobs (int32 dist)
Will extract a list of connected components from this instance.
RasterPtr ExtractChannel (ColorChannels channel)
Will return a grayscale image consisting of the specified color channel only.
RasterPtr FastFourier () const
RasterPtr FastFourierKK () const
const KKStr & FileName () const
void FileName (const KKStr &_fileName)
void FillBlob (RasterPtr origImage, BlobPtr blob, PixelValue color)
Will paint the specified blob with the specified color.
void FillHole ()
void FillRectangle (int32 tlRow, int32 tlCol, int32 brRow, int32 brCol, const PixelValue &fillColor)
void FindBoundingBox (int32 &tlRow, int32 &tlCol, int32 &brRow, int32 &brCol) const
bool ForegroundPixel (int32 row, int32 col) const
int32 ForegroundPixelCount () const
void ForegroundPixelCount (int32 _foregroundPixelCount)
uchar ForegroundPixelValue () const
void ForegroundPixelValue (uchar _foregroundPixelValue)
void FourierExtractFeatures (float fourierFeatures[5]) const
float * FourierMagArea () const
uchar GetPixelValue (int32 row, int32 col) const
void GetPixelValue (int32 row, int32 col, uchar &r, uchar &g, uchar &b) const
void GetPixelValue (int32 row, int32 col, PixelValue &p) const
uchar GetPixelValue (ColorChannels channel, int32 row, int32 col) const
uchar ** GetSubSet (uchar **_src, int32 _row, int32 _col, int32 _height, int32 _width) const
Returns back a two dimension array that is a copy of the specified region.
uchar ** Green () const
returns a pointer to two dimensional array for 'Green' color channel.
uchar * GreenArea () const
RasterPtr HalfSize ()
int32 Height () const
HistogramPtr Histogram (ColorChannels channel) const
RasterPtr HistogramEqualizedImage () const
RasterPtr HistogramEqualizedImage (HistogramPtr equalizedHistogram) const
HistogramPtr HistogramGrayscale () const
RasterPtr HistogramGrayscaleImage () const
RasterPtr HistogramImage (ColorChannels channel) const
void Initialize (int32 _height, int32 _width, uchar *_grayScaleData, uchar **_grayScaleRows, bool _takeOwnership)
Sets an existing instance to specific Raster data of a grayscale image.
void Initialize (int32 _height, int32 _width, uchar *_redArea, uchar **_red, uchar *_greenArea, uchar **_green, uchar *_blueArea, uchar **_blue, bool _takeOwnership)
uchar MaxPixVal () const
void MaxPixVal (uchar _maxPixVal)
int32 MemoryConsumedEstimated () const
void Opening ()
void Opening (MaskTypes mask)
RasterPtr Padded (int32 padding)
uchar ** Red () const
returns a pointer to two dimensional array for 'Red' color channel.
uchar * RedArea () const
RasterPtr ReduceByEvenMultiple (int32 multiple) const
RasterPtr ReduceByFactor (float factor) const
void ReduceToMostCompleteBlob (uchar connectedComponentDist)
Locates most complete blob; that is the one with the largest (Height x Width); and removes all other images from the blob.
RasterPtr ReversedImage ()
void ReverseImage ()
RasterPtr Rotate (float turnAngle)
uchar ** Rows () const
RasterPtr SegmentImage (bool save=false)
void SetPixelValue (const Point &point, const PixelValue &pixVal)
void SetPixelValue (int32 row, int32 col, uchar pixVal)
void SetPixelValue (int32 row, int32 col, const PixelValue &pixVal)
void SetPixelValue (int32 row, int32 col, uchar r, uchar g, uchar b)
void SetPixelValue (ColorChannels channel, int32 row, int32 col, uchar pixVal)
RasterPtr SobelEdgeDetector ()
RasterListPtr SplitImageIntoEqualParts (int32 numColSplits, int32 numRowSplits) const
RasterPtr SwapQuadrants () const
RasterPtr ThinContour ()
RasterPtr ThresholdInHSI (float thresholdH, float thresholdS, float thresholdI, float distance, const PixelValue &flagValue)
Thresholds image in HSI space.
RasterPtr TightlyBounded (uint32 borderPixels) const
RasterPtr ToColor () const
uchar * ToCompressor (uint32 &compressedBuffLen) const
Compresses the image in Raster using zlib library and returns a pointer to compressed data.
int32 TotalBackgroundPixels () const
int32 TotPixels () const
void WeOwnRasterData (bool _weOwnRasterData)
int32 Width () const
Static Public Member Functions
static MatrixPtr BuildGaussian2dKernel (float sigma)
Builds a 2d Gaussian kernel.
static RasterPtr CreatePaddedRaster (BmpImage &image, int32 padding)
static void PrintOutListOfAllocatedrasterInstances ()
Static Protected Member Functions
static void AddRasterInstance (const RasterPtr r)
static void FinalCleanUp ()
static void Initialize ()
static void RemoveRasterInstance (const RasterPtr r)
Protected Attributes
uchar backgroundPixelTH
uchar backgroundPixelValue
int32 ** blobIds
uchar ** blue
uchar * blueArea
float centroidCol
float centroidRow
bool color
KKStr fileName
int32 foregroundPixelCount
uchar foregroundPixelValue
float ** fourierMag
Only used if image is result of a Fourier Transform.
float * fourierMagArea
Only used if image is result of a Fourier Transform.
uchar ** green
uchar * greenArea
int32 height
uchar maxPixVal
uchar ** red
uchar * redArea
int32 totPixels
bool weOwnRasterData
int32 width
Static Protected Attributes
static std::map< RasterPtr,
RasterPtr > allocatedRasterInstances
static volatile GoalKeeperPtr goalKeeper = NULL
static volatile bool rasterInitialized = false
Detailed Description
A class that is used by to represent a single image in memory.
It supports morphological operations and other tasks. It can handle either Grayscale or Color. By default it will use Grayscale unless specified otherwise. It will allocate one continuous block of memory for each channel (RGB). If the image is only grayscale the Green Channel (G) will be used leaving the Red and Blue channels set to NULL. You can access Individual pixels through access methods that will ensure memory integrity or you can also access the pixel data directly in memory.
See Also
Blob
ContourFollower
ConvexHull
PixelValue
Point
PointList
RasterList()
Sobel
Definition at line 105 of file Raster.h.
Member Typedef Documentation
typedef Raster* KKU::Raster::RasterPtr
Definition at line 108 of file Raster.h.
Constructor & Destructor Documentation
Raster::Raster ()
Definition at line 239 of file Raster.cpp.
Referenced by AllocateARasterInstance(), CreatePaddedRaster(), and SplitImageIntoEqualParts().
Raster::Raster (const Raster & _raster)
Copy Constructor.
Definition at line 408 of file Raster.cpp.
References AddRasterInstance(), blueArea, color, fourierMagArea, greenArea, redArea, and totPixels.
Raster::Raster (int32 _height, int32 _width)
Constructs a blank GrayScale image with given dimensions; all pixels will be initialized to 0.
When working with Grayscale images pixel value of '0' = Background and '255'= foreground. The green channel will be used to represent the grayscale value. When these raster images are saved to a image file such as a BMP file the pixel value of 0 will point to the color value of (255, 255, 255) and pixel value 255 will point to the color value of (0, 0, 0). This way when displaying the image background will appear as white.
Definition at line 269 of file Raster.cpp.
References AddRasterInstance().
Raster::Raster (int32 _height, int32 _width, bool _color)
Constructs a blank image with given dimensions.
The third parameter determines whether it will be a color or grayscale image, If a Color image then all three color channel will be set to = 255 which stands for white. If Grayscale the green channel will be set to 0.
Definition at line 305 of file Raster.cpp.
References AddRasterInstance(), backgroundPixelTH, backgroundPixelValue, color, and foregroundPixelValue.
Raster::Raster (const BmpImage & _bmpImage)
Constructs a Raster from a BMP image loaded from disk.
Constructs a Raster from a BMP image loadded from disk.
If BMP Image is a grayscale value pixel values will be reversed. See description of grayscale constructor.
If BMP Image is a grayscale value pixel values will be reveresed. See description of grayscale constructor.
Definition at line 355 of file Raster.cpp.
References AddRasterInstance(), blue, KKU::BmpImage::BlueRow(), KKU::BmpImage::Color(), color, green, height, KKU::BmpImage::ImageRow(), red, KKU::BmpImage::RedRow(), and width.
Raster::Raster (const Raster & _raster, int32 _row, int32 _col, int32 _height, int32 _width)
Constructs a new Raster using a subset of the specified Raster as its source.
The dimensions of the resultant raster will be '_height', and '_width'
Parameters
_raster Source Raster
_row Starting Row in '_raster' to copy from.
_col Starting Col in '_raster' to copy from.
_height Height of resultant raster. Will start from '_row'
_width Width of resultant raster.
Definition at line 457 of file Raster.cpp.
References AddRasterInstance(), blue, blueArea, color, GetSubSet(), green, greenArea, red, and redArea.
Raster::Raster (const Raster & _raster, MaskTypes _mask, int32 _row, int32 _col)
Constructs a Raster that will be as large as the specified '_mask' at the point specified by '_row' and '_col'.
See Also
MaskTypes
Parameters
_mask
See Also
MaskTyps Generated 'Raster' with be the of the mask.
Definition at line 507 of file Raster.cpp.
References AddRasterInstance(), biases, blue, blueArea, color, GetSubSet(), green, greenArea, height, red, redArea, and width.
Raster::Raster (const KKStr & _fileName, bool & validFile)
Constructs a Raster image from by reading an existing image File such as a BMP file.
Constructs a raster object from a Image File.
Will read from the specified file (fileName) the existing image. If the load fails then the contents of this object will be undefined.
Parameters
[in] fileName Name of Image file to read.
[out] validFile If image successfully loaded will be set to 'True' otherwise 'False'.
If a color image the pixel values will be reveresed, see constructor for grayscale images.
Parameters
_fileName
fileName name of image file to load/
validFile
validFile will return true if image successfully loaded.
Definition at line 562 of file Raster.cpp.
References AddRasterInstance(), Blue(), blue, blueArea, color, fileName, ForegroundPixelCount(), foregroundPixelCount, Green(), green, greenArea, Height(), height, MaxPixVal(), maxPixVal, KKU::ReadImage(), Red(), red, redArea, totPixels, weOwnRasterData, Width(), and width.
Raster::Raster (int32 _height, int32 _width, uchar * _grayScaleData, uchar ** _grayScaleRows)
Construct a raster object that will utilize a image already in memory.
This instance will not own the raster data. It will only point to it.
Definition at line 627 of file Raster.cpp.
References AddRasterInstance().
Raster::Raster (int32 _height, int32 _width, const uchar * _grayScaleData)
Construct a Grayscale Raster object using provided raw data,.
Definition at line 663 of file Raster.cpp.
References AddRasterInstance(), greenArea, and totPixels.
Raster::Raster (int32 _height, int32 _width, const uchar * _redChannel, const uchar * _greenChannel, const uchar * _blueChannel)
Construct a Color Raster object using provided raw data,.
Definition at line 699 of file Raster.cpp.
References AddRasterInstance(), blueArea, KKU::endl(), greenArea, redArea, and totPixels.
Raster::~Raster () virtual
Definition at line 749 of file Raster.cpp.
References RemoveRasterInstance().
Member Function Documentation
void Raster::AddRasterInstance (const RasterPtr r) static protected
Definition at line 71 of file Raster.cpp.
Referenced by Raster().
RasterPtr Raster::AllocateARasterInstance (int32 height, int32 width, bool color) const virtual
Reimplemented in KKU::RasterSipper.
Definition at line 878 of file Raster.cpp.
References Raster().
Referenced by BandPass(), BinarizeByThreshold(), CreateColorImageFromLabels(), CreateColorWithBlobsLabeldByColor(), CreateDialatedRaster(), CreateErodedImage(), CreateFromOrginalImageWithSpecifidBlobsOnly(), CreateGaussianSmoothedImage(), CreateGrayScale(), CreateGrayScaleKLT(), CreateGrayScaleKLTOnMaskedArea(), KKU::RasterList::CreateSmoothedFrame(), CreateSmoothedMediumImage(), CreateSmoothImage(), ExtractABlob(), ExtractABlobTightly(), ExtractChannel(), FastFourier(), FastFourierKK(), HalfSize(), HistogramEqualizedImage(), Padded(), ReduceByEvenMultiple(), ReduceByFactor(), ReversedImage(), Rotate(), SegmentImage(), SwapQuadrants(), ThinContour(), ThresholdInHSI(), TightlyBounded(), and ToColor().
RasterPtr Raster::AllocateARasterInstance (const Raster & r) const virtual
Reimplemented in KKU::RasterSipper.
Definition at line 888 of file Raster.cpp.
References Raster().
RasterPtr Raster::AllocateARasterInstance (const Raster & _raster, int32 _row, int32 _col, int32 _height, int32 _width) const virtual
Parameters
_raster Source Raster
_row Starting Row in '_raster' to copy from.
_col Starting Col in '_raster' to copy from.
_height Height of resultant raster. Will start from '_row'
_width Width of resultant raster.
Definition at line 895 of file Raster.cpp.
References Raster().
uchar KKU::Raster::BackgroundPixelTH () const inline
Definition at line 261 of file Raster.h.
References backgroundPixelTH.
Referenced by KKU::SegmentorOTSU::SegmentMaskedImage().
void KKU::Raster::BackgroundPixelTH (uchar _backgroundPixelTH) inline
Definition at line 267 of file Raster.h.
References backgroundPixelTH.
uchar KKU::Raster::BackgroundPixelValue () const inline
Definition at line 262 of file Raster.h.
References backgroundPixelValue.
Referenced by SegmentImage().
void KKU::Raster::BackgroundPixelValue (uchar _backgroundPixelValue) inline
Definition at line 268 of file Raster.h.
References backgroundPixelValue.
RasterPtr Raster::BandPass (float lowerFreqBound, float upperFreqBound)
Returns a image that is the result of a BandPass using Fourier Transforms.
A 2D Fourier transform is performed. The range specified is from 0.0 to 1.0 where range is determined from the center of the image to the farthest corner where the center is 0.0 and the farthest corner is 1.0. Pixels in the resultant 2D Transform that are "NOT" in the specified range are set to 0.0. A reverse transform is then performed and the resultant image is returned.
Parameters
[in] lowerFreqBound Lower range of frequencies to retain; between 0.0 and 1.0.
[in] upperFreqBound Upper range of frequencies to retain; between 0.0 and 1.0.
Returns
The result image.
Parameters
lowerFreqBound Number's between 0.0 and 1.0
upperFreqBound Represent fraction.
Definition at line 7161 of file Raster.cpp.
References AllocateARasterInstance(), backgroundPixelValue, blue, color, KKU::fftwCreateTwoDPlan(), KKU::fftwDestroyPlan(), green, greenArea, height, KKU::Min(), red, totPixels, and width.
Referenced by KKU::RasterSipper::BandPass().
RasterPtr Raster::BinarizeByThreshold (uchar min, uchar max)
Definition at line 6232 of file Raster.cpp.
References AllocateARasterInstance(), backgroundPixelValue, foregroundPixelValue, GreenArea(), greenArea, totPixels, and x.
Referenced by KKU::RasterSipper::BinarizeByThreshold().
int32 Raster::BlobId (int32 row, int32 col) const inline
Return the ID of the blob that the specified pixel location belongs to.
If a connected component (ExtractBlobs) was performed on this image then the pixels that belong to blobs were assigned a blob ID. These ID's are retained with the original image in 'blobIds'.
Parameters
[in] row Row in image.
[in] col Column in image.
Returns
BlobID of pixel location or -1 of does not belong to a blob.
See Also
ExtractBlobs
Definition at line 2441 of file Raster.cpp.
References blobIds.
uchar** KKU::Raster::Blue () const inline
returns a pointer to two dimensional array for 'Blue' color channel.
Definition at line 253 of file Raster.h.
References blue.
Referenced by KKU::BmpImage::BmpImage(), PicesInterface::PicesRaster::BuildBitmap(), CreateSmoothedMediumImage(), CreateSmoothImage(), Raster(), KKU::SaveImageInverted(), TightlyBounded(), and KKU::RasterSipper::TurnIntoSipperRasterPtr().
uchar* KKU::Raster::BlueArea () const inline
Definition at line 257 of file Raster.h.
References blueArea.
Referenced by KKU::SegmentorOTSU::ClassAverageRGB(), CreateColorImageFromLabels(), KKU::RasterList::CreateSmoothedFrame(), ExtractChannel(), KKU::RasterSipper::FromCompressor(), KKU::SegmentorOTSU::GetClassClosestToTargetColor(), KKU::ReadImagePNG(), ReduceByFactor(), KKU::SaveImagePNG(), ToColor(), and KKU::RasterSipper::TurnIntoSipperRasterPtr().
MatrixPtr Raster::BuildGaussian2dKernel (float sigma) static
Builds a 2d Gaussian kernel.
Determines the size of the gaussian kernel based off the specified sigma parameter. returns a 2D matrix representing the kernel which will have 'len' x 'len' dimensions. The caller will be responsible for deleting the kernel.
Parameters
[in] sigma parameter used to control the width of the gaussian kernel A 2 dimension matrix representing the gaussian kernel.
Definition at line 7498 of file Raster.cpp.
References PIE, and x.
Referenced by CreateGaussianSmoothedImage().
int32 Raster::CalcArea ()
Definition at line 3263 of file Raster.cpp.
References ForegroundPixel(), foregroundPixelCount, green, height, maxPixVal, and width.
void Raster::CalcAreaAndIntensityFeatures (int32 & area, float & weighedSize, uint32 intensityHistBuckets[8], int32 & areaWithWhiteSpace, uint32 intensityHistBucketsWhiteSpace[8])
Calculates both Intensity Histograms, one not including internal background pixels and one with plus size and weighted size.
    This method incorporates the functionality of several methods at once.  The idea being that while
    we are iterating through the raster image we might as well get all the data we can so as to save
    total overall processing time.
Histogram Ranges:
  0:   0  - 31    4: 128 - 159
  1:  31  - 63    5: 192 - 223
  2:  64  - 95    6: 192 - 223
  3:  96 - 127    7: 224 - 255
Parameters
[out] area Number of foreground pixels.
[out] weightedSize Area that takes intensity into account. The largest pixel will have a value of 1.0.
[out] intensityHistBuckets A 8 element array containing a histogram by intensity range.
[out] areaWithWhiteSpace Area including any whitespace enclosed inside the image.
[out] intensityHistBucketsWhiteSpace A 8 element array containing a histogram by intensity range, with enclosed whitespace pixels included.
Definition at line 3385 of file Raster.cpp.
References FillHole(), ForegroundPixel(), foregroundPixelCount, freqHistBucketIdx, GreenArea(), greenArea, maxPixVal, totPixels, and x.
void Raster::CalcAreaAndIntensityFeatures (int32 & area, float & weighedSize, uint32 intensityHistBuckets[8])
Calculates both Intensity Histograms, one not including internal background pixels and one with plus size and weighted size.
    This method incorporates the functionality of several methods at once.  The idea being that while
    we are iterating through the raster image we might as well get all the data we can so as to save
    total overall processing time.
Histogram Ranges:
  0:   0  - 31    4: 128 - 159
  1:  31  - 63    5: 192 - 223
  2:  64  - 95    6: 192 - 223
  3:  96 - 127    7: 224 - 255
Parameters
[out] area Number of foreground pixels.
[out] weightedSize Area that takes intensity into account. The largest pixel will have a value of 1.0.
[out] intensityHistBuckets A 8 element array containing a histogram by intensity range.
Definition at line 3447 of file Raster.cpp.
References foregroundPixelCount, freqHistBucketIdx, greenArea, maxPixVal, totPixels, and x.
void Raster::CalcAreaAndIntensityHistogram (int32 & area, uint32 intensityHistBuckets[8])
Calculates the occurrence of different intensity levels.
The pixel values 0-255 are split into 8 ranges. (0-31), (32-63), (64-95), (96-127), (128-159), (160-191), (192-223), (224-255). The background range (0-31) are not counted.
Parameters
[out] area Total number of foreground pixels in the image.
[out] intensityHistBuckets An array of 8 buckets where each bucket represents an intensity range.
Definition at line 3346 of file Raster.cpp.
References ForegroundPixel(), foregroundPixelCount, freqHistBucketIdx, green, height, maxPixVal, width, and x.
void Raster::CalcAreaAndIntensityHistogramWhite (int32 & area, uint32 intensityHistBuckets[8])
Calculates a Intensity Histogram including Background pixels in the image.
All background pixels that are inside the image will also be included in the counts. This is done by building a mask on the original image then performing a FillHole operation. This mask is then used to select pixels for inclusion in the histogram.
Definition at line 3299 of file Raster.cpp.
References FillHole(), ForegroundPixel(), freqHistBucketIdx, green, height, maxPixVal, width, and x.
void Raster::CalcCentroid (int32 & size, int32 & weight, float & rowCenter, float & colCenter, float & rowCenterWeighted, float & colCenterWeighted)
Definition at line 4725 of file Raster.cpp.
References centroidCol, centroidRow, green, height, and width.
Referenced by CalcOrientationAndEigerRatio(), CentroidCol(), and CentroidRow().
void Raster::CalcOrientationAndEigerRatio (float & eigenRatio, float & orientationAngle)
Definition at line 4352 of file Raster.cpp.
References CalcCentroid(), centroidCol, centroidRow, ForegroundPixel(), green, height, OneHalfPie, PIE, KKU::tqli(), KKU::Tred2(), and width.
Referenced by KKU::RasterSipper::DeriveImageLength().
float Raster::CalcWeightedArea () const
Definition at line 3488 of file Raster.cpp.
References ForegroundPixel(), green, height, maxPixVal, and width.
float Raster::CenMoment (int32 p, int32 q, float ew, float eh) const
Definition at line 3608 of file Raster.cpp.
References ForegroundPixel(), green, height, and width.
Referenced by CentralMoments().
float Raster::CenMomentWeighted (int32 p, int32 q, float ew, float eh) const
Definition at line 3755 of file Raster.cpp.
References ForegroundPixel(), green, height, maxPixVal, and width.
Referenced by CentralMomentsWeighted().
void Raster::CentralMoments (float features[9]) const
Definition at line 3518 of file Raster.cpp.
References CenMoment().
void Raster::CentralMomentsWeighted (float features[9]) const
Definition at line 3646 of file Raster.cpp.
References CenMomentWeighted().
float Raster::CentroidCol ()
Returns
returns the centroid's column
Definition at line 955 of file Raster.cpp.
References CalcCentroid(), centroidCol, centroidRow, and totPixels.
float Raster::CentroidRow ()
Returns
returns the centroid's row
Definition at line 971 of file Raster.cpp.
References CalcCentroid(), centroidCol, centroidRow, and totPixels.
void Raster::Closing ()
Definition at line 2304 of file Raster.cpp.
References Dialation(), and Erosion().
void Raster::Closing (MaskTypes mask)
Definition at line 2314 of file Raster.cpp.
References Dialation(), and Erosion().
bool KKU::Raster::Color () const inline
Definition at line 238 of file Raster.h.
References color.
Referenced by KKU::BmpImage::BmpImage(), PicesInterface::PicesRaster::BuildBitmap(), KKU::SegmentorOTSU::ClassAverageRGB(), PicesInterface::PicesRaster::Color(), KKU::RasterList::CreateSmoothedFrame(), KKU::SegmentorOTSU::GetClassClosestToTargetColor(), PicesInterface::PicesRaster::PicesRaster(), PicesInterface::PicesRaster::Save(), KKU::SaveImageInverted(), KKU::SaveImagePGM(), KKU::SaveImagePNG(), KKU::SegmentorOTSU::SegmentImage(), SegmentImage(), KKU::SegmentorOTSU::SegmentMaskedImage(), KKU::SegmentPolutionImage(), KKU::Sobel::Sobel(), and KKU::RasterSipper::TurnIntoSipperRasterPtr().
void Raster::ConnectedComponent (uchar connectedComponentDist)
Definition at line 2934 of file Raster.cpp.
References blobIds, ExtractBlobs(), green, greenArea, height, KKU::Blob::Id(), KKU::BlobList::LocateLargestBlob(), totPixels, and width.
Referenced by PicesInterface::PicesRaster::ConnectedComponent(), KKU::RasterSipper::DeriveImageLength(), and ThinContour().
void Raster::ConnectedComponent8Conected ()
Definition at line 3051 of file Raster.cpp.
References blobIds, KKU::Blob::colLeft, KKU::Blob::colRight, ForegroundPixel(), green, greenArea, height, KKU::Blob::Id(), KKU::Blob::id, KKU::BlobList::LocateLargestBlob(), KKU::BlobList::LookUpByBlobId(), KKU::Max(), KKU::BlobList::MergeBlobIds(), KKU::Min(), KKU::BlobList::NewBlob(), KKU::Blob::pixelCount, KKU::Blob::rowBot, KKU::Blob::rowTop, totPixels, and width.
void Raster::ConnectedComponentOrig ()
Definition at line 2782 of file Raster.cpp.
References blobIds, KKU::Blob::colLeft, KKU::Blob::colRight, ForegroundPixel(), green, greenArea, height, KKU::Blob::Id(), KKU::Blob::id, KKU::BlobList::LocateLargestBlob(), KKU::BlobList::LookUpByBlobId(), KKU::Max(), KKU::BlobList::MergeBlobIds(), KKU::Min(), KKU::BlobList::NewBlob(), KKU::Blob::pixelCount, KKU::Blob::rowBot, KKU::Blob::rowTop, totPixels, and width.
RasterPtr Raster::CreateColorImageFromLabels ()
Produces a color image using the 'greenArea' channel, assuming that each unique value will be assigned a unique color.
    Assuming that each value in the grayscale channel(GreenArea) will be assigned  a different color
    useful for image created by  "SegmentorOTSU::SegmentImage".
See Also
Raster::CreateGrayScaleKLT
Definition at line 7981 of file Raster.cpp.
References AllocateARasterInstance(), KKU::PixelValue::b, KKU::PixelValue::Black, BlueArea(), KKU::PixelValue::FromHSI(), KKU::PixelValue::g, GreenArea(), greenArea, KKU::PixelValue::r, RedArea(), totPixels, and x.
Referenced by KKU::RasterSipper::CreateColorImageFromLabels().
RasterPtr Raster::CreateColorWithBlobsLabeldByColor (BlobListPtr blobs)
Returns image where each blob is labeled with a different color.
Only useful if 'ExtractBlobs' was performed on this instance. Eight different colors are used and they are selected by the modules of the blobId(blobId % 8). Assignments are 0:Red, 1:Green, 2:Blue, 3:Yellow, 4:Orange, 5:Magenta, 6:Purple, 7:Teal.Only useful if 'ExtractBlobs' was performed on this instance, the returned image will be color with each blob labeled a different color.
Only useful if 'ExtractBlobs' was performed on this instance.
Definition at line 2646 of file Raster.cpp.
References AllocateARasterInstance(), blobIds, KKU::PixelValue::Blue, KKU::Blob::ColLeft(), color, KKU::Blob::ColRight(), KKU::PixelValue::Green, KKU::Blob::Id(), KKU::PixelValue::Magenta, KKU::Min(), KKU::PixelValue::Orange, KKU::PixelValue::Purple, KKU::PixelValue::Red, KKU::Blob::RowBot(), KKU::Blob::RowTop(), SetPixelValue(), KKU::PixelValue::Teal, and KKU::PixelValue::Yellow.
Referenced by KKU::RasterSipper::CreateColorWithBlobsLabeldByColor().
RasterPtr Raster::CreateDialatedRaster () const
Definition at line 1441 of file Raster.cpp.
References AllocateARasterInstance(), foregroundPixelCount, green, height, and width.
Referenced by KKU::RasterSipper::CreateDialatedRaster(), and Dialation().
RasterPtr Raster::CreateDialatedRaster (MaskTypes mask) const
Definition at line 1520 of file Raster.cpp.
References AllocateARasterInstance(), foregroundPixelCount, green, height, and width.
RasterPtr Raster::CreateErodedImage (MaskTypes mask) const
Definition at line 2248 of file Raster.cpp.
References AllocateARasterInstance(), backgroundPixelValue, ForegroundPixel(), foregroundPixelCount, Green(), green, height, and width.
Referenced by KKU::RasterSipper::CreateErodedImage().
RasterPtr Raster::CreateFromOrginalImageWithSpecifidBlobsOnly (RasterPtr origImage, BlobListPtr blobs)
Returns a copy of 'origImage' where only the blobs specified in 'blobs' are copied over.
Example:
    origImage = image that we want to segment and get list of discrete blobs from.
    RasterPtr  segmentedImage = origImage->SegmentImage ();
    BlobListPtr  blobs = segmentedImage->ExtractBlobs (1);
    RasterPtr  imageWithBlobOnly = segmentedImage->CreateFromOrginalImageWithSpecifidBlobsOnly (blobs);
Parameters
[in] origImage Image that this instance was derived for, must have same dimensions.
[in] blobs Blobs that you want copied over from.
Returns
Image consisting of specified blobs only.
Definition at line 2697 of file Raster.cpp.
References AllocateARasterInstance(), blobIds, KKU::Blob::ColLeft(), KKU::Blob::ColRight(), GetPixelValue(), KKU::Blob::Id(), KKU::Min(), KKU::Blob::RowBot(), KKU::Blob::RowTop(), and SetPixelValue().
Referenced by KKU::RasterSipper::CreateFromOrginalImageWithSpecifidBlobsOnly().
RasterPtr Raster::CreateGaussianSmoothedImage (float sigma) const
Definition at line 7600 of file Raster.cpp.
References AllocateARasterInstance(), blue, BuildGaussian2dKernel(), color, green, and red.
Referenced by KKU::RasterSipper::CreateGaussianSmoothedImage().
RasterPtr Raster::CreateGrayScale () const
Definition at line 4776 of file Raster.cpp.
References AllocateARasterInstance(), blueArea, color, GreenArea(), greenArea, height, redArea, totPixels, width, and x.
Referenced by KKU::RasterSipper::CreateGrayScale(), HistogramGrayscaleImage(), KKU::SaveImagePGM(), SegmentImage(), and KKU::SegmentPolutionImage().
RasterPtr Raster::CreateGrayScaleKLT () const
Creates a grayscale image using a KLT Transform with the goal of weighting in favor the color channels with greatest amount of variance.
The idea is to weight each color channel by the amount of variance. This is accomplished by producing a covariance matrix of the three color channels and then taking the Eigen vector with the largest eigen value and using its components to derive weights for each channel for the conversion from RGB to grayscale.
Definition at line 7670 of file Raster.cpp.
References AllocateARasterInstance(), blueArea, color, KKU::Matrix::EigenVectors(), KKU::endl(), KKU::Matrix::GetCol(), GreenArea(), greenArea, Height(), KKU::Min(), redArea, totPixels, Width(), and x.
Referenced by KKU::RasterSipper::CreateGrayScaleKLT(), KKU::SegmentorOTSU::SegmentImage(), KKU::SegmentorOTSU::SegmentMaskedImage(), and KKU::Sobel::Sobel().
RasterPtr Raster::CreateGrayScaleKLTOnMaskedArea (const Raster & mask) const
Same as 'CreateGrayScaleKLT' except it will only take into account pixels specified by the 'mask' image.
Parameters
[in] mask Raster object where pixels that are greater than 'backgroundPixelTH' are to be considered.
Definition at line 7810 of file Raster.cpp.
References AllocateARasterInstance(), backgroundPixelTH, blueArea, color, KKU::Matrix::EigenVectors(), KKU::endl(), KKU::Matrix::GetCol(), GreenArea(), greenArea, Height(), height, KKU::Min(), redArea, TotalBackgroundPixels(), totPixels, Width(), and width.
Referenced by KKU::RasterSipper::CreateGrayScaleKLTOnMaskedArea(), and KKU::SegmentorOTSU::SegmentMaskedImage().
RasterPtr Raster::CreatePaddedRaster (BmpImage & image, int32 padding) static
Definition at line 986 of file Raster.cpp.
References foregroundPixelCount, green, KKU::BmpImage::Height(), KKU::BmpImage::ImageRow(), Raster(), and KKU::BmpImage::Width().
Referenced by KKU::RasterSipper::CreatePaddedRaster().
RasterPtr Raster::CreateSmoothedMediumImage (int32 maskSize) const
Definition at line 5756 of file Raster.cpp.
References AllocateARasterInstance(), Blue(), color, FindKthValue(), Green(), green, height, KKU::Max(), KKU::Min(), Red(), and width.
Referenced by KKU::RasterSipper::CreateSmoothedMediumImage().
RasterPtr Raster::CreateSmoothImage (int32 maskSize = 3) const
Definition at line 5679 of file Raster.cpp.
References AllocateARasterInstance(), Blue(), blue, Green(), green, Red(), and red.
Referenced by KKU::RasterSipper::CreateSmoothImage(), and SegmentImage().
void Raster::Dialation ()
Definition at line 1499 of file Raster.cpp.
References CreateDialatedRaster(), foregroundPixelCount, green, and greenArea.
Referenced by Closing(), and Opening().
void Raster::Dialation (MaskTypes mask)
Definition at line 1573 of file Raster.cpp.
References CreateDialatedRaster(), foregroundPixelCount, green, and greenArea.
void Raster::DrawCircle (const Point & point, int32 radius, const PixelValue & color)
Draw a circle who's center is at 'point' and radius in pixels is 'radius'using color 'color'.
Definition at line 5608 of file Raster.cpp.
References KKU::Point::Col(), and KKU::Point::Row().
void Raster::DrawCircle (float centerRow, float centerCol, float radius, const PixelValue & pixelValue)
Definition at line 5518 of file Raster.cpp.
References SetPixelValue(), and x.
void Raster::DrawCircle (float centerRow, float centerCol, float radius, float startAngle, float endAngle, const PixelValue & pixelValue)
Parameters
startAngle Start and End angles should be given in radians
endAngle Where the angles are with respect to the compass
Definition at line 5557 of file Raster.cpp.
References height, SetPixelValue(), TwoPie, and width.
void Raster::DrawConnectedPointList (Point offset, const PointList & borderPixs, const PixelValue & pixelValue, const PixelValue & linePixelValue)
Definition at line 5424 of file Raster.cpp.
References KKU::PixelValue::b, blue, KKU::Point::Col(), color, DrawLine(), KKU::PixelValue::g, green, KKU::PixelValue::r, red, and KKU::Point::Row().
void Raster::DrawDot (const Point & point, const PixelValue & color, int32 size)
Definition at line 5475 of file Raster.cpp.
References KKU::Point::Col(), KKU::Max(), KKU::Min(), KKU::Point::Row(), and SetPixelValue().
Referenced by KKU::Chart::CreateRaster().
void Raster::DrawGrid (float pixelsPerMinor, uint32 minorsPerMajor, const PixelValue & hashColor, const PixelValue & gridColor)
Definition at line 1361 of file Raster.cpp.
References DrawLine(), FillRectangle(), and x.
Referenced by PicesInterface::PicesRaster::DrawGrid().
void Raster::DrawLine (int32 bpRow, int32 bpCol, int32 epRow, int32 epCol)
Definition at line 4951 of file Raster.cpp.
Referenced by KKU::Histogram::CreateGraph(), KKU::Chart::CreateRaster(), DrawConnectedPointList(), DrawGrid(), and DrawLine().
void Raster::DrawLine (int32 bpRow, int32 bpCol, int32 epRow, int32 epCol, uchar pixelVal)
Definition at line 4965 of file Raster.cpp.
References DrawLine().
void Raster::DrawLine (const Point & beginPoint, const Point & endPoint, uchar pixelVal)
Definition at line 5324 of file Raster.cpp.
References KKU::Point::Col(), DrawLine(), and KKU::Point::Row().
void Raster::DrawLine (const Point & beginPoint, const Point & endPoint, const PixelValue & pixelVal)
Definition at line 5337 of file Raster.cpp.
References KKU::Point::Col(), DrawLine(), and KKU::Point::Row().
void Raster::DrawLine (int32 bpRow, int32 bpCol, int32 epRow, int32 epCol, uchar r, uchar g, uchar b)
Definition at line 4976 of file Raster.cpp.
References blue, color, KKU::endl(), green, and red.
void Raster::DrawLine (int32 bpRow, int32 bpCol, int32 epRow, int32 epCol, uchar r, uchar g, uchar b, float alpha)
Definition at line 5144 of file Raster.cpp.
References blue, color, KKU::endl(), green, MergeAlpfaBeta(), and red.
void Raster::DrawLine (int32 bpRow, int32 bpCol, int32 epRow, int32 epCol, PixelValue pixelVal)
Definition at line 5301 of file Raster.cpp.
References KKU::PixelValue::b, DrawLine(), KKU::PixelValue::g, and KKU::PixelValue::r.
void Raster::DrawLine (int32 bpRow, int32 bpCol, int32 epRow, int32 epCol, PixelValue pixelVal, float alpha)
Definition at line 5312 of file Raster.cpp.
References KKU::PixelValue::b, DrawLine(), KKU::PixelValue::g, and KKU::PixelValue::r.
void Raster::DrawPointList (const PointList & borderPixs, const PixelValue & pixelValue)
Definition at line 5352 of file Raster.cpp.
References KKU::PixelValue::b, KKU::PixelValue::g, and KKU::PixelValue::r.
Referenced by DrawPointList().
void Raster::DrawPointList (Point offset, const PointList & borderPixs, const PixelValue & pixelValue)
Definition at line 5360 of file Raster.cpp.
References KKU::PixelValue::b, DrawPointList(), KKU::PixelValue::g, and KKU::PixelValue::r.
void Raster::DrawPointList (const PointList & borderPixs, uchar redVal, uchar greenVal, uchar blueVal)
Definition at line 5371 of file Raster.cpp.
References DrawPointList().
void Raster::DrawPointList (Point offset, const PointList & borderPixs, uchar redVal, uchar greenVal, uchar blueVal)
Definition at line 5383 of file Raster.cpp.
References blue, KKU::Point::Col(), color, green, red, and KKU::Point::Row().
void Raster::Edge ()
reduces image to edge pixels only.
Definition at line 2386 of file Raster.cpp.
References backgroundPixelValue, ForegroundPixel(), foregroundPixelCount, foregroundPixelValue, and green.
Referenced by PicesInterface::PicesRaster::EdgeImage().
void Raster::ErodeSpurs ()
removes spurs from image.
Definition at line 6564 of file Raster.cpp.
References backgroundPixelValue, ForegroundPixel(), and green.
Referenced by ThinContour().
void Raster::Erosion ()
Definition at line 1753 of file Raster.cpp.
References backgroundPixelTH, backgroundPixelValue, foregroundPixelCount, and green.
Referenced by Closing(), KKU::RasterSipper::DeriveImageLength(), and Opening().
void Raster::Erosion (MaskTypes mask)
Definition at line 1807 of file Raster.cpp.
References backgroundPixelValue, biases, ForegroundPixel(), foregroundPixelCount, Green(), green, height, maskShapes, Square, and width.
void Raster::ErosionBoundary (MaskTypes mask, int32 blobrowstart, int32 blobrowend, int32 blobcolstart, int32 blobcolend)
Definition at line 2129 of file Raster.cpp.
References backgroundPixelValue, biases, ForegroundPixel(), foregroundPixelCount, Green(), green, height, maskShapes, Square, and width.
void Raster::ErosionChanged (MaskTypes mask, int32 row, int32 col)
Definition at line 1900 of file Raster.cpp.
References backgroundPixelValue, biases, ForegroundPixel(), foregroundPixelCount, Green(), green, maskShapes, and Square.
void Raster::ErosionChanged1 (MaskTypes mask, int32 row, int32 col)
Definition at line 2013 of file Raster.cpp.
References backgroundPixelValue, biases, ForegroundPixel(), foregroundPixelCount, Green(), green, maskShapes, and Square.
RasterPtr Raster::ExtractABlob (const BlobPtr blob) const
Extracts a specified blob from this image; useful to extract individual detected blobs.
The 'ExtractBlobs' method needs to have been performed on this instance first. You would use this method after calling 'ExtractBlobs'. The extracted image will be of the same dimensions as the original image except it will extract the pixels that belong to the specified blob only.
// Example of processing extracted blobs
void  ProcessIndividulConectedComponents (RasterPtr  image)
{
  BlobListPtr blobs = image->ExtractBlobs (3);
  BlobList::iterator  idx;
  for  (idx = blobs->begin ();  idx != end ();  ++idx)
  {
    RasterPtr  individuleBlob = image->ExtractABlob (*idx);
    DoSomethingWithIndividuleBlob (individuleBlob);
    delete  individuleBlob;
    individuleBlob = NULL;
  )
  delete  blobs;
  blobs = NULL;
}
Definition at line 3235 of file Raster.cpp.
References AllocateARasterInstance(), blobIds, blue, KKU::Blob::colLeft, color, green, KKU::Blob::id, red, and KKU::Blob::rowTop.
Referenced by KKU::RasterSipper::ExtractABlob().
RasterPtr Raster::ExtractABlobTightly (const BlobPtr blob, int32 padding) const
Extracts a specified blob from this image into a tightly bounded image.
Similar to 'ExtractABlob' except that the returned image will have the dimension necessary to contain the specified blob with the specified number of padded row and columns.
Definition at line 3196 of file Raster.cpp.
References AllocateARasterInstance(), blobIds, blue, KKU::Blob::colLeft, color, green, KKU::Blob::Height(), KKU::Blob::id, red, KKU::Blob::rowTop, and KKU::Blob::Width().
Referenced by KKU::RasterSipper::ExtractABlobTightly().
BlobListPtr Raster::ExtractBlobs (int32 dist)
Will extract a list of connected components from this instance.
    Will perform a connected component analysis and label each individual blob.  A list of blob
    descriptors will be returned.  These blob descriptors can then be used to access individual
    blobs.  See 'ExtractABlob' for an example on how to use this method.  The 'ForegroundPixel'
    method is used to determine if a given pixel is foreground or background.
Parameters
[in] dist The distance in pixels that two different pixel locations have to be for them to be considered connected. "dist = 1" would indicate that two pixels have to be directly connected.
Returns
A list of Blob descriptor instances.
See Also
ExtractABlob, ExtractABlobTightly, Blob
Definition at line 2526 of file Raster.cpp.
References blobIds, KKU::Blob::colLeft, KKU::Blob::colRight, ForegroundPixel(), green, height, KKU::Blob::Id(), KKU::Blob::id, KKU::BlobList::LookUpByBlobId(), KKU::Max(), KKU::BlobList::MergeIntoSingleBlob(), KKU::Min(), KKU::BlobList::NewBlob(), KKU::Blob::pixelCount, KKU::Blob::rowBot, and KKU::Blob::rowTop.
Referenced by ConnectedComponent(), and ReduceToMostCompleteBlob().
RasterPtr Raster::ExtractChannel (ColorChannels channel)
Will return a grayscale image consisting of the specified color channel only.
Definition at line 6254 of file Raster.cpp.
References AllocateARasterInstance(), BlueArea(), color, FileName(), GreenArea(), KKU::GreenChannel, KKU::osGetRootName(), RedArea(), and KKU::RedChannel.
Referenced by KKU::RasterSipper::ExtractChannel(), and SegmentImage().
RasterPtr Raster::FastFourier () const
Definition at line 4057 of file Raster.cpp.
References AllocateARasterInstance(), KKU::endl(), KKU::fftwCreateTwoDPlan(), KKU::fftwDestroyPlan(), FileName(), fileName, fourierMagArea, green, greenArea, height, Initialize(), rasterInitialized, totPixels, and width.
Referenced by KKU::RasterSipper::FastFourier().
RasterPtr Raster::FastFourierKK () const
Definition at line 3981 of file Raster.cpp.
References AllocateARasterInstance(), KKU::KK_DFT2D< DftType >::AllocateAray(), KKU::endl(), fileName, fourierMagArea, green, greenArea, height, totPixels, KKU::KK_DFT2D< DftType >::Transform(), and width.
Referenced by KKU::RasterSipper::FastFourierKK().
const KKStr& KKU::Raster::FileName () const inline
Definition at line 241 of file Raster.h.
References fileName.
Referenced by ExtractChannel(), FastFourier(), KKU::ContourFollower::FollowContour(), MLL::DataBase::ImageFullSizeFind(), PicesInterface::PicesFeatureVector::PicesFeatureVector(), PicesInterface::PicesRaster::PicesRaster(), PrintOutListOfAllocatedrasterInstances(), and ImageExtractionManager::DataBaseUpdateThread::Run().
void KKU::Raster::FileName (const KKStr & _fileName) inline
Definition at line 271 of file Raster.h.
References fileName.
void Raster::FillBlob (RasterPtr origImage, BlobPtr blob, PixelValue color)
Will paint the specified blob with the specified color.
Example Use:
   BlobListPtr  blobs = srcImage->ExctractBlobs (1);
   RasterPtr  labeledColorImage = new Raster (srcImage->Height (), srcImage->Width (), true);
   BlobList::iterator  idx;
   for  (idx = blobs->begin ();  idx != blobs->end ();  ++idx)
   {
     BlobPtr  blob = *idx;
     labeledColorImage->FillBlob (srcImage, blob, PixelValue::Red);
   }
Parameters
[in] origImage The image where the blob was extracted from.
[in] blob The specific blob that you want to fill in/ paint.
[in] Color that is to be filled in.
Definition at line 8029 of file Raster.cpp.
References blobIds, KKU::Blob::ColLeft(), KKU::Blob::ColRight(), Height(), height, KKU::Blob::Id(), KKU::Min(), KKU::Blob::RowBot(), KKU::Blob::RowTop(), SetPixelValue(), Width(), and width.
void Raster::FillHole ()
Definition at line 1694 of file Raster.cpp.
References foregroundPixelCount, foregroundPixelValue, green, height, and width.
Referenced by CalcAreaAndIntensityFeatures(), CalcAreaAndIntensityHistogramWhite(), KKU::RasterSipper::DeriveImageLength(), and PicesInterface::PicesRaster::FillHoles().
void Raster::FillRectangle (int32 tlRow, int32 tlCol, int32 brRow, int32 brCol, const PixelValue & fillColor)
Definition at line 1593 of file Raster.cpp.
References KKU::PixelValue::b, blue, color, KKU::PixelValue::g, green, KKU::Min(), KKU::PixelValue::r, and red.
Referenced by DrawGrid().
void Raster::FinalCleanUp () static protected
Definition at line 60 of file Raster.cpp.
void Raster::FindBoundingBox (int32 & tlRow, int32 & tlCol, int32 & brRow, int32 & brCol) const
Definition at line 4571 of file Raster.cpp.
References ForegroundPixel(), green, and INT_MAX.
Referenced by KKU::RasterSipper::DeriveImageLength(), ThinContour(), and TightlyBounded().
bool Raster::ForegroundPixel (int32 row, int32 col) const
Definition at line 915 of file Raster.cpp.
References backgroundPixelTH, and green.
Referenced by PicesInterface::ApplyMask(), CalcArea(), CalcAreaAndIntensityFeatures(), CalcAreaAndIntensityHistogram(), CalcAreaAndIntensityHistogramWhite(), CalcOrientationAndEigerRatio(), CalcWeightedArea(), CenMoment(), CenMomentWeighted(), ConnectedComponent8Conected(), ConnectedComponentOrig(), CreateErodedImage(), Edge(), ErodeSpurs(), Erosion(), ErosionBoundary(), ErosionChanged(), ErosionChanged1(), ExtractBlobs(), FindBoundingBox(), and ThinContour().
int32 KKU::Raster::ForegroundPixelCount () const inline
Definition at line 243 of file Raster.h.
References foregroundPixelCount.
Referenced by Raster(), and ReduceByEvenMultiple().
void KKU::Raster::ForegroundPixelCount (int32 _foregroundPixelCount) inline
Definition at line 269 of file Raster.h.
References foregroundPixelCount.
uchar KKU::Raster::ForegroundPixelValue () const inline
Definition at line 263 of file Raster.h.
References foregroundPixelValue.
Referenced by SegmentImage().
void KKU::Raster::ForegroundPixelValue (uchar _foregroundPixelValue) inline
Definition at line 270 of file Raster.h.
References foregroundPixelValue.
void Raster::FourierExtractFeatures (float fourierFeatures[5]) const
Definition at line 4223 of file Raster.cpp.
References KKU::endl(), fourierMag, fourierMagArea, height, KKU::osWaitForEnter(), and x.
float* KKU::Raster::FourierMagArea () const inline
Definition at line 259 of file Raster.h.
References fourierMagArea.
uchar Raster::GetPixelValue (int32 row, int32 col) const
Definition at line 1132 of file Raster.cpp.
References KKU::endl(), and green.
Referenced by PicesInterface::ApplyMask(), CreateFromOrginalImageWithSpecifidBlobsOnly(), KKU::DisplayImage(), GetPixelValue(), Padded(), Rotate(), SegmentImage(), and ThresholdInHSI().
void Raster::GetPixelValue (int32 row, int32 col, uchar & r, uchar & g, uchar & b) const
Definition at line 1151 of file Raster.cpp.
References blue, color, KKU::endl(), green, and red.
void Raster::GetPixelValue (int32 row, int32 col, PixelValue & p) const
Definition at line 1186 of file Raster.cpp.
References KKU::PixelValue::b, KKU::PixelValue::g, GetPixelValue(), and KKU::PixelValue::r.
uchar Raster::GetPixelValue (ColorChannels channel, int32 row, int32 col) const
Definition at line 1199 of file Raster.cpp.
References blue, color, KKU::endl(), green, KKU::GreenChannel, red, and KKU::RedChannel.
uchar ** Raster::GetSubSet (uchar ** _src, int32 _row, int32 _col, int32 _height, int32 _width) const
Returns back a two dimension array that is a copy of the specified region.
The caller will take owneship of the two dimensional array creatd.
Definition at line 3803 of file Raster.cpp.
References KKU::endl().
Referenced by Raster().
uchar** KKU::Raster::Green () const inline
returns a pointer to two dimensional array for 'Green' color channel.
Definition at line 252 of file Raster.h.
References green.
Referenced by PicesInterface::PicesRaster::BuildBitmap(), PicesInterface::PicesRaster::BuildRasterArray(), PicesInterface::PicesRaster::BuildRasterArray2(), CreateErodedImage(), CreateSmoothedMediumImage(), CreateSmoothImage(), KKU::RasterSipper::DeriveImageLength(), Erosion(), ErosionBoundary(), ErosionChanged(), ErosionChanged1(), SipperHardware::InstrumentDataFileManager::GetOrigSipperImage(), ImageExtractionManager::SipperImage::GetRaster(), MLL::SipperBlob::GetRaster(), Raster(), ReduceByEvenMultiple(), KKU::SaveImageInverted(), KKU::Sobel::Sobel(), ThinContour(), TightlyBounded(), and KKU::RasterSipper::TurnIntoSipperRasterPtr().
uchar* KKU::Raster::GreenArea () const inline
Definition at line 256 of file Raster.h.
References greenArea.
Referenced by BinarizeByThreshold(), PicesInterface::PicesRaster::BuildRasterObj(), CalcAreaAndIntensityFeatures(), KKU::SegmentorOTSU::ClassAverageRGB(), CreateColorImageFromLabels(), CreateGrayScale(), CreateGrayScaleKLT(), CreateGrayScaleKLTOnMaskedArea(), KKU::RasterList::CreateSmoothedFrame(), ExtractChannel(), KKU::RasterSipper::FromCompressor(), KKU::RasterSipper::FromSimpleCompression(), KKU::SegmentorOTSU::GetClassClosestToTargetColor(), KKU::ReadImagePNG(), ReduceByFactor(), KKU::SaveImagePGM(), KKU::SaveImagePNG(), KKU::SegmentorOTSU::SegmentImage(), KKU::SegmentorOTSU::SegmentMaskedImage(), ToColor(), and KKU::RasterSipper::TurnIntoSipperRasterPtr().
RasterPtr Raster::HalfSize ()
Definition at line 5853 of file Raster.cpp.
References AllocateARasterInstance(), blue, KKU::BlueChannel, color, green, red, KKU::RedChannel, and SetPixelValue().
Referenced by KKU::RasterSipper::HalfSize().
int32 KKU::Raster::Height () const inline
Definition at line 245 of file Raster.h.
References height.
Referenced by PicesInterface::ApplyMask(), KKU::BmpImage::BmpImage(), PicesInterface::PicesRaster::BuildBitmap(), PicesInterface::PicesRaster::BuildRasterArray(), PicesInterface::PicesRaster::BuildRasterArray2(), CreateGrayScaleKLT(), CreateGrayScaleKLTOnMaskedArea(), KKU::RasterList::CreateSmoothedFrame(), KKU::DisplayImage(), FillBlob(), KKU::ConvexHull::Filter(), MLL::DataBase::ImageInsert(), PicesInterface::PicesRaster::PicesRaster(), PrintOutListOfAllocatedrasterInstances(), Raster(), Rotate(), ImageExtractionManager::DataBaseUpdateThread::Run(), KKU::SaveImageInverted(), KKU::SaveImagePGM(), KKU::SaveImagePNG(), KKU::SegmentorOTSU::SegmentImage(), SegmentImage(), KKU::SegmentorOTSU::SegmentMaskedImage(), KKU::Sobel::Sobel(), KKU::ConvexHull::Store(), and KKU::RasterSipper::TurnIntoSipperRasterPtr().
HistogramPtr Raster::Histogram (ColorChannels channel) const
Definition at line 4826 of file Raster.cpp.
References blueArea, KKU::BlueChannel, color, greenArea, KKU::GreenChannel, KKU::Histogram::Increment(), redArea, KKU::RedChannel, totPixels, and x.
Referenced by HistogramImage().
RasterPtr Raster::HistogramEqualizedImage () const
Definition at line 4854 of file Raster.cpp.
References KKU::Histogram::Equalized(), and HistogramGrayscale().
Referenced by KKU::RasterSipper::HistogramEqualizedImage().
RasterPtr Raster::HistogramEqualizedImage (HistogramPtr equalizedHistogram) const
Definition at line 4870 of file Raster.cpp.
References AllocateARasterInstance(), KKU::endl(), KKU::Histogram::EqualizedMapTable(), green, height, KKU::Histogram::NumOfBuckets(), KKU::osWaitForEnter(), Rows(), and width.
HistogramPtr Raster::HistogramGrayscale () const
Definition at line 4807 of file Raster.cpp.
References green, height, KKU::Histogram::Increment(), and width.
Referenced by HistogramEqualizedImage(), HistogramGrayscaleImage(), SegmentImage(), and KKU::SegmentPolutionImage().
RasterPtr Raster::HistogramGrayscaleImage () const
Definition at line 4915 of file Raster.cpp.
References color, KKU::Histogram::CreateGraph(), CreateGrayScale(), and HistogramGrayscale().
Referenced by KKU::RasterSipper::HistogramGrayscaleImage().
RasterPtr Raster::HistogramImage (ColorChannels channel) const
Definition at line 4939 of file Raster.cpp.
References KKU::Histogram::CreateGraph(), and Histogram().
Referenced by KKU::RasterSipper::HistogramImage().
void Raster::Initialize (int32 _height, int32 _width, uchar * _grayScaleData, uchar ** _grayScaleRows, bool _takeOwnership)
Sets an existing instance to specific Raster data of a grayscale image.
This instance of 'raster' will take ownership of '_grayScaleData' and '_grayScaleRows'.
Definition at line 820 of file Raster.cpp.
References color, green, greenArea, height, totPixels, weOwnRasterData, and width.
Referenced by KKU::RasterSipper::TurnIntoSipperRasterPtr().
void Raster::Initialize (int32 _height, int32 _width, uchar * _redArea, uchar ** _red, uchar * _greenArea, uchar ** _green, uchar * _blueArea, uchar ** _blue, bool _takeOwnership)
Definition at line 846 of file Raster.cpp.
References blue, blueArea, color, green, greenArea, height, red, redArea, totPixels, weOwnRasterData, and width.
void Raster::Initialize () static protected
Definition at line 45 of file Raster.cpp.
Referenced by FastFourier().
uchar KKU::Raster::MaxPixVal () const inline
Definition at line 246 of file Raster.h.
References maxPixVal.
Referenced by Raster(), and ReduceByEvenMultiple().
void KKU::Raster::MaxPixVal (uchar _maxPixVal) inline
Definition at line 272 of file Raster.h.
References maxPixVal.
int32 Raster::MemoryConsumedEstimated () const
Definition at line 787 of file Raster.cpp.
References blobIds, color, fileName, fourierMagArea, height, KKU::KKStr::MemoryConsumedEstimated(), and totPixels.
Referenced by KKU::RasterBuffer::AddRaster(), KKU::RasterBuffer::GetNextRaster(), and KKU::RasterSipper::MemoryConsumedEstimated().
void Raster::Opening ()
Definition at line 2287 of file Raster.cpp.
References Dialation(), and Erosion().
void Raster::Opening (MaskTypes mask)
Definition at line 2295 of file Raster.cpp.
References Dialation(), and Erosion().
RasterPtr Raster::Padded (int32 padding)
Definition at line 7475 of file Raster.cpp.
References AllocateARasterInstance(), GetPixelValue(), height, SetPixelValue(), and width.
Referenced by KKU::RasterSipper::Padded().
void Raster::PrintOutListOfAllocatedrasterInstances () static
Definition at line 118 of file Raster.cpp.
References KKU::endl(), FileName(), Height(), and Width().
uchar** KKU::Raster::Red () const inline
returns a pointer to two dimensional array for 'Red' color channel.
Definition at line 251 of file Raster.h.
References red.
Referenced by KKU::BmpImage::BmpImage(), PicesInterface::PicesRaster::BuildBitmap(), CreateSmoothedMediumImage(), CreateSmoothImage(), Raster(), KKU::SaveImageInverted(), TightlyBounded(), and KKU::RasterSipper::TurnIntoSipperRasterPtr().
uchar* KKU::Raster::RedArea () const inline
Definition at line 255 of file Raster.h.
References redArea.
Referenced by KKU::SegmentorOTSU::ClassAverageRGB(), CreateColorImageFromLabels(), KKU::RasterList::CreateSmoothedFrame(), ExtractChannel(), KKU::RasterSipper::FromCompressor(), KKU::SegmentorOTSU::GetClassClosestToTargetColor(), KKU::ReadImagePNG(), ReduceByFactor(), KKU::SaveImagePNG(), ToColor(), and KKU::RasterSipper::TurnIntoSipperRasterPtr().
RasterPtr Raster::ReduceByEvenMultiple (int32 multiple) const
Definition at line 5888 of file Raster.cpp.
References AllocateARasterInstance(), ForegroundPixelCount(), Green(), green, height, MaxPixVal(), and width.
Referenced by KKU::RasterSipper::ReduceByEvenMultiple().
RasterPtr Raster::ReduceByFactor (float factor) const
Definition at line 6000 of file Raster.cpp.
References AllocateARasterInstance(), blue, BlueArea(), color, green, GreenArea(), height, red, RedArea(), width, and x.
Referenced by KKU::RasterSipper::ReduceByFactor().
void Raster::ReduceToMostCompleteBlob (uchar connectedComponentDist)
Locates most complete blob; that is the one with the largest (Height x Width); and removes all other images from the blob.
Definition at line 2990 of file Raster.cpp.
References blobIds, ExtractBlobs(), green, greenArea, height, KKU::Blob::Id(), KKU::BlobList::LocateMostComplete(), totPixels, and width.
Referenced by SipperHardware::InstrumentDataFileManager::GetOrigSipperImage().
void Raster::RemoveRasterInstance (const RasterPtr r) static protected
Definition at line 94 of file Raster.cpp.
Referenced by ~Raster().
RasterPtr Raster::ReversedImage ()
Definition at line 1032 of file Raster.cpp.
References AllocateARasterInstance(), and ReverseImage().
Referenced by KKU::RasterSipper::ReversedImage().
void Raster::ReverseImage ()
Definition at line 1041 of file Raster.cpp.
References backgroundPixelTH, backgroundPixelValue, blueArea, color, foregroundPixelValue, greenArea, redArea, totPixels, and x.
Referenced by KKU::Histogram::CreateGraph(), and ReversedImage().
RasterPtr Raster::Rotate (float turnAngle)
Definition at line 4513 of file Raster.cpp.
References AllocateARasterInstance(), GetPixelValue(), Height(), height, SetPixelValue(), Width(), and width.
Referenced by KKU::RasterSipper::Rotate().
uchar** KKU::Raster::Rows () const inline
Definition at line 247 of file Raster.h.
References green.
Referenced by KKU::BmpImage::BmpImage(), HistogramEqualizedImage(), SegmentImage(), and KKU::ConvexHull::Store().
RasterPtr Raster::SegmentImage (bool save = false)
Definition at line 6297 of file Raster.cpp.
References AllocateARasterInstance(), KKU::Histogram::AverageOfMaxBucketInRange(), BackgroundPixelValue(), KKU::BlueChannel, Color(), CreateGrayScale(), CreateSmoothImage(), ExtractChannel(), fileName, ForegroundPixelValue(), GetPixelValue(), KKU::GreenChannel, Height(), HistogramGrayscale(), KKU::osAddLastSlash(), KKU::osCreateDirectoryPath(), KKU::osGetRootName(), KKU::RedChannel, Rows(), KKU::Histogram::Save(), KKU::Histogram::SaveGraphImage(), KKU::SaveImage(), SetPixelValue(), KKU::Histogram::Smooth(), KKU::StrFormatInt(), and Width().
Referenced by KKU::RasterSipper::SegmentImage().
void Raster::SetPixelValue (const Point & point, const PixelValue & pixVal)
Definition at line 1283 of file Raster.cpp.
References KKU::Point::Col(), and KKU::Point::Row().
Referenced by KKU::Sobel::AngleImage(), PicesInterface::ApplyMask(), CreateColorWithBlobsLabeldByColor(), CreateFromOrginalImageWithSpecifidBlobsOnly(), KKU::Histogram::CreateGraph(), DrawCircle(), DrawDot(), FillBlob(), HalfSize(), KKU::Sobel::MagnitudeImage(), Padded(), PicesInterface::PicesRaster::PicesRaster(), KKU::ReadImagePGM(), Rotate(), SegmentImage(), and ThresholdInHSI().
void Raster::SetPixelValue (int32 row, int32 col, uchar pixVal)
Definition at line 1233 of file Raster.cpp.
References KKU::endl(), and green.
void Raster::SetPixelValue (int32 row, int32 col, const PixelValue & pixVal)
Definition at line 1256 of file Raster.cpp.
References KKU::PixelValue::b, blue, color, KKU::endl(), KKU::PixelValue::g, green, KKU::PixelValue::r, and red.
void Raster::SetPixelValue (int32 row, int32 col, uchar r, uchar g, uchar b)
Definition at line 1293 of file Raster.cpp.
References blue, color, KKU::endl(), green, and red.
void Raster::SetPixelValue (ColorChannels channel, int32 row, int32 col, uchar pixVal)
Definition at line 1322 of file Raster.cpp.
References blue, color, KKU::endl(), green, KKU::GreenChannel, red, and KKU::RedChannel.
RasterPtr Raster::SobelEdgeDetector ()
Definition at line 6223 of file Raster.cpp.
References KKU::Sobel::MagnitudeImage().
Referenced by KKU::RasterSipper::SobelEdgeDetector().
RasterListPtr Raster::SplitImageIntoEqualParts (int32 numColSplits, int32 numRowSplits) const
Definition at line 6498 of file Raster.cpp.
References Raster().
Referenced by KKU::RasterSipper::SplitImageIntoEqualParts().
RasterPtr Raster::SwapQuadrants () const
Definition at line 4172 of file Raster.cpp.
References AllocateARasterInstance(), blue, fourierMag, green, and red.
Referenced by KKU::RasterSipper::SwapQuadrants().
RasterPtr Raster::ThinContour ()
Definition at line 6667 of file Raster.cpp.
References AllocateARasterInstance(), backgroundPixelValue, KKU::Point::Col(), ConnectedComponent(), KKU::endl(), ErodeSpurs(), FindBoundingBox(), ForegroundPixel(), Green(), height, k_ThinningCheckTransitions(), k_ThinningSearchNeighbors(), k_ThinningStep1cdTests(), k_ThinningStep2cdTests(), KKU::Max(), KKU::Min(), KKU::Point::Row(), width, and x.
Referenced by KKU::RasterSipper::ThinContour().
RasterPtr Raster::ThresholdInHSI (float thresholdH, float thresholdS, float thresholdI, float distance, const PixelValue & flagValue)
Thresholds image in HSI space.
    Returns an image with only the pixels that are within a specified distance in HSI space to the
    supplied HSI parameters.  All pixels that are not within the specified distance will be set to
    'flagValue'.
Parameters
[in] thresholdH Hue in radians(0.0 <-> 2Pie).
[in] thresholdS Saturation (0.0 <-> 1.0).
[in] thresholdI Intensity (0.0 <-> 1.0).
[in] distance Threshold Distance (0.0 <-> 1.0) that a pixel must be within in HSI space to be included.
[in] flagValue PixelValue to set for pixels that are NOT within 'distance' of threshold.
Returns
A image where pixels that are within the threshold will retain their original pixel values and the ones that are not will be set to 'flagValue'.
Definition at line 7622 of file Raster.cpp.
References AllocateARasterInstance(), color, GetPixelValue(), height, SetPixelValue(), KKU::PixelValue::ToHSI(), width, and x.
Referenced by KKU::RasterSipper::ThresholdInHSI().
RasterPtr Raster::TightlyBounded (uint32 borderPixels) const
Definition at line 7098 of file Raster.cpp.
References AllocateARasterInstance(), Blue(), blue, color, FindBoundingBox(), Green(), green, Red(), and red.
Referenced by KKU::RasterSipper::TightlyBounded().
RasterPtr Raster::ToColor () const
Definition at line 7147 of file Raster.cpp.
References AllocateARasterInstance(), BlueArea(), color, GreenArea(), greenArea, RedArea(), and totPixels.
Referenced by KKU::RasterSipper::ToColor().
uchar * Raster::ToCompressor (uint32 & compressedBuffLen) const
Compresses the image in Raster using zlib library and returns a pointer to compressed data.
Will first write Rater data to a buffer that will be compressed by the Compressor class using the zlib library.
Buffer Contents:
   0 - 3: Height:  high order to low order
   4 - 7:    Width:   high order to low order
   8 - 8:    Color    0 = Grayscale,  1 = Color
   9 -  :   Green Channel  (Height * Width bytes)
   xxxxx:   Red  Channel, if color image.
   xxxxx:   Blue Channel, if color image.
Parameters
[out] compressedBuffLen Length of the compressed buffer returned.
Returns
pointer to compressed data.
Definition at line 7419 of file Raster.cpp.
References blueArea, color, KKU::Compressor::CreateCompressedBuffer(), greenArea, redArea, totPixels, and x.
Referenced by MLL::DataBase::ImageFullSizeSave().
int32 Raster::TotalBackgroundPixels () const
Definition at line 941 of file Raster.cpp.
References backgroundPixelTH, greenArea, totPixels, and x.
Referenced by CreateGrayScaleKLTOnMaskedArea(), and KKU::SegmentorOTSU::SegmentMaskedImage().
int32 KKU::Raster::TotPixels () const inline
Definition at line 248 of file Raster.h.
References totPixels.
Referenced by KKU::SegmentorOTSU::ClassAverageRGB(), KKU::SegmentorOTSU::GetClassClosestToTargetColor(), KKU::SegmentorOTSU::SegmentImage(), and KKU::SegmentorOTSU::SegmentMaskedImage().
void KKU::Raster::WeOwnRasterData (bool _weOwnRasterData) inline
Definition at line 273 of file Raster.h.
References weOwnRasterData.
Referenced by KKU::RasterSipper::TurnIntoSipperRasterPtr().
int32 KKU::Raster::Width () const inline
Definition at line 249 of file Raster.h.
References width.
Referenced by PicesInterface::ApplyMask(), KKU::BmpImage::BmpImage(), PicesInterface::PicesRaster::BuildBitmap(), PicesInterface::PicesRaster::BuildRasterArray(), PicesInterface::PicesRaster::BuildRasterArray2(), CreateGrayScaleKLT(), CreateGrayScaleKLTOnMaskedArea(), KKU::RasterList::CreateSmoothedFrame(), KKU::DisplayImage(), FillBlob(), KKU::ConvexHull::Filter(), MLL::DataBase::ImageInsert(), PicesInterface::PicesRaster::PicesRaster(), PrintOutListOfAllocatedrasterInstances(), Raster(), Rotate(), ImageExtractionManager::DataBaseUpdateThread::Run(), KKU::SaveImageInverted(), KKU::SaveImagePGM(), KKU::SaveImagePNG(), KKU::SegmentorOTSU::SegmentImage(), SegmentImage(), KKU::SegmentorOTSU::SegmentMaskedImage(), KKU::Sobel::Sobel(), KKU::ConvexHull::Store(), and KKU::RasterSipper::TurnIntoSipperRasterPtr().
Member Data Documentation
map< RasterPtr, RasterPtr > Raster::allocatedRasterInstances static protected
Definition at line 1056 of file Raster.h.
uchar KKU::Raster::backgroundPixelTH protected
Definition at line 1025 of file Raster.h.
Referenced by BackgroundPixelTH(), CreateGrayScaleKLTOnMaskedArea(), Erosion(), ForegroundPixel(), Raster(), ReverseImage(), and TotalBackgroundPixels().
uchar KKU::Raster::backgroundPixelValue protected
Definition at line 1024 of file Raster.h.
Referenced by BackgroundPixelValue(), BandPass(), BinarizeByThreshold(), CreateErodedImage(), Edge(), ErodeSpurs(), Erosion(), ErosionBoundary(), ErosionChanged(), ErosionChanged1(), Raster(), ReverseImage(), and ThinContour().
int32** KKU::Raster::blobIds protected
Definition at line 1026 of file Raster.h.
Referenced by BlobId(), ConnectedComponent(), ConnectedComponent8Conected(), ConnectedComponentOrig(), CreateColorWithBlobsLabeldByColor(), CreateFromOrginalImageWithSpecifidBlobsOnly(), ExtractABlob(), ExtractABlobTightly(), ExtractBlobs(), FillBlob(), MemoryConsumedEstimated(), and ReduceToMostCompleteBlob().
uchar** KKU::Raster::blue protected
Definition at line 1052 of file Raster.h.
Referenced by BandPass(), Blue(), CreateGaussianSmoothedImage(), CreateSmoothImage(), DrawConnectedPointList(), DrawLine(), DrawPointList(), ExtractABlob(), ExtractABlobTightly(), FillRectangle(), GetPixelValue(), HalfSize(), Initialize(), Raster(), ReduceByFactor(), SetPixelValue(), SwapQuadrants(), and TightlyBounded().
uchar* KKU::Raster::blueArea protected
Definition at line 1043 of file Raster.h.
Referenced by BlueArea(), CreateGrayScale(), CreateGrayScaleKLT(), CreateGrayScaleKLTOnMaskedArea(), KKU::RasterList::CreateSmoothedFrame(), KKU::RasterSipper::FromCompressor(), Histogram(), Initialize(), Raster(), ReverseImage(), and ToCompressor().
float KKU::Raster::centroidCol protected
Definition at line 1027 of file Raster.h.
Referenced by CalcCentroid(), CalcOrientationAndEigerRatio(), CentroidCol(), and CentroidRow().
float KKU::Raster::centroidRow protected
Definition at line 1028 of file Raster.h.
Referenced by CalcCentroid(), CalcOrientationAndEigerRatio(), CentroidCol(), and CentroidRow().
bool KKU::Raster::color protected
Definition at line 1029 of file Raster.h.
Referenced by BandPass(), Color(), CreateColorWithBlobsLabeldByColor(), CreateGaussianSmoothedImage(), CreateGrayScale(), CreateGrayScaleKLT(), CreateGrayScaleKLTOnMaskedArea(), CreateSmoothedMediumImage(), DrawConnectedPointList(), DrawLine(), DrawPointList(), ExtractABlob(), ExtractABlobTightly(), ExtractChannel(), FillRectangle(), KKU::RasterSipper::FromCompressor(), GetPixelValue(), HalfSize(), Histogram(), HistogramGrayscaleImage(), Initialize(), MemoryConsumedEstimated(), Raster(), ReduceByFactor(), ReverseImage(), SetPixelValue(), ThresholdInHSI(), TightlyBounded(), ToColor(), and ToCompressor().
KKStr KKU::Raster::fileName protected
Definition at line 1030 of file Raster.h.
Referenced by FastFourier(), FastFourierKK(), FileName(), MemoryConsumedEstimated(), Raster(), and SegmentImage().
int32 KKU::Raster::foregroundPixelCount protected
Definition at line 1031 of file Raster.h.
Referenced by CalcArea(), CalcAreaAndIntensityFeatures(), CalcAreaAndIntensityHistogram(), CreateDialatedRaster(), CreateErodedImage(), CreatePaddedRaster(), Dialation(), Edge(), Erosion(), ErosionBoundary(), ErosionChanged(), ErosionChanged1(), FillHole(), ForegroundPixelCount(), and Raster().
uchar KKU::Raster::foregroundPixelValue protected
Definition at line 1032 of file Raster.h.
Referenced by BinarizeByThreshold(), Edge(), FillHole(), ForegroundPixelValue(), Raster(), and ReverseImage().
float** KKU::Raster::fourierMag protected
Only used if image is result of a Fourier Transform.
Definition at line 1033 of file Raster.h.
Referenced by FourierExtractFeatures(), and SwapQuadrants().
float* KKU::Raster::fourierMagArea protected
Only used if image is result of a Fourier Transform.
Definition at line 1034 of file Raster.h.
Referenced by FastFourier(), FastFourierKK(), FourierExtractFeatures(), FourierMagArea(), MemoryConsumedEstimated(), and Raster().
volatile GoalKeeperPtr Raster::goalKeeper = NULL static protected
Definition at line 1057 of file Raster.h.
uchar** KKU::Raster::green protected
Definition at line 1051 of file Raster.h.
Referenced by BandPass(), CalcArea(), CalcAreaAndIntensityHistogram(), CalcAreaAndIntensityHistogramWhite(), CalcCentroid(), CalcOrientationAndEigerRatio(), CalcWeightedArea(), CenMoment(), CenMomentWeighted(), ConnectedComponent(), ConnectedComponent8Conected(), ConnectedComponentOrig(), CreateDialatedRaster(), CreateErodedImage(), CreateGaussianSmoothedImage(), CreatePaddedRaster(), CreateSmoothedMediumImage(), CreateSmoothImage(), Dialation(), DrawConnectedPointList(), DrawLine(), DrawPointList(), Edge(), ErodeSpurs(), Erosion(), ErosionBoundary(), ErosionChanged(), ErosionChanged1(), ExtractABlob(), ExtractABlobTightly(), ExtractBlobs(), FastFourier(), FastFourierKK(), FillHole(), FillRectangle(), FindBoundingBox(), ForegroundPixel(), GetPixelValue(), Green(), HalfSize(), HistogramEqualizedImage(), HistogramGrayscale(), Initialize(), Raster(), ReduceByEvenMultiple(), ReduceByFactor(), ReduceToMostCompleteBlob(), Rows(), SetPixelValue(), SwapQuadrants(), and TightlyBounded().
uchar* KKU::Raster::greenArea protected
Definition at line 1042 of file Raster.h.
Referenced by BandPass(), BinarizeByThreshold(), CalcAreaAndIntensityFeatures(), ConnectedComponent(), ConnectedComponent8Conected(), ConnectedComponentOrig(), CreateColorImageFromLabels(), CreateGrayScale(), CreateGrayScaleKLT(), CreateGrayScaleKLTOnMaskedArea(), KKU::RasterList::CreateSmoothedFrame(), Dialation(), FastFourier(), FastFourierKK(), KKU::RasterSipper::FromCompressor(), KKU::RasterSipper::FromSimpleCompression(), GreenArea(), Histogram(), Initialize(), Raster(), ReduceToMostCompleteBlob(), ReverseImage(), ToColor(), ToCompressor(), and TotalBackgroundPixels().
int32 KKU::Raster::height protected
Definition at line 1035 of file Raster.h.
Referenced by BandPass(), CalcArea(), CalcAreaAndIntensityHistogram(), CalcAreaAndIntensityHistogramWhite(), CalcCentroid(), CalcOrientationAndEigerRatio(), CalcWeightedArea(), CenMoment(), CenMomentWeighted(), ConnectedComponent(), ConnectedComponent8Conected(), ConnectedComponentOrig(), CreateDialatedRaster(), CreateErodedImage(), CreateGrayScale(), CreateGrayScaleKLTOnMaskedArea(), KKU::RasterList::CreateSmoothedFrame(), CreateSmoothedMediumImage(), KKU::RasterSipper::DeriveImageLength(), DrawCircle(), Erosion(), ErosionBoundary(), ExtractBlobs(), FastFourier(), FastFourierKK(), FillBlob(), FillHole(), FourierExtractFeatures(), KKU::RasterSipper::FromCompressor(), KKU::RasterSipper::FromSimpleCompression(), Height(), HistogramEqualizedImage(), HistogramGrayscale(), Initialize(), MemoryConsumedEstimated(), Padded(), Raster(), ReduceByEvenMultiple(), ReduceByFactor(), ReduceToMostCompleteBlob(), Rotate(), ThinContour(), and ThresholdInHSI().
uchar KKU::Raster::maxPixVal protected
Definition at line 1036 of file Raster.h.
Referenced by CalcArea(), CalcAreaAndIntensityFeatures(), CalcAreaAndIntensityHistogram(), CalcAreaAndIntensityHistogramWhite(), CalcWeightedArea(), CenMomentWeighted(), MaxPixVal(), and Raster().
volatile bool Raster::rasterInitialized = false static protected
Definition at line 1058 of file Raster.h.
Referenced by FastFourier().
uchar** KKU::Raster::red protected
Definition at line 1050 of file Raster.h.
Referenced by BandPass(), CreateGaussianSmoothedImage(), CreateSmoothImage(), DrawConnectedPointList(), DrawLine(), DrawPointList(), ExtractABlob(), ExtractABlobTightly(), FillRectangle(), GetPixelValue(), HalfSize(), Initialize(), Raster(), Red(), ReduceByFactor(), SetPixelValue(), SwapQuadrants(), and TightlyBounded().
uchar* KKU::Raster::redArea protected
Definition at line 1041 of file Raster.h.
Referenced by CreateGrayScale(), CreateGrayScaleKLT(), CreateGrayScaleKLTOnMaskedArea(), KKU::RasterList::CreateSmoothedFrame(), KKU::RasterSipper::FromCompressor(), Histogram(), Initialize(), Raster(), RedArea(), ReverseImage(), and ToCompressor().
int32 KKU::Raster::totPixels protected
Definition at line 1037 of file Raster.h.
Referenced by BandPass(), BinarizeByThreshold(), CalcAreaAndIntensityFeatures(), CentroidCol(), CentroidRow(), ConnectedComponent(), ConnectedComponent8Conected(), ConnectedComponentOrig(), CreateColorImageFromLabels(), CreateGrayScale(), CreateGrayScaleKLT(), CreateGrayScaleKLTOnMaskedArea(), KKU::RasterList::CreateSmoothedFrame(), FastFourier(), FastFourierKK(), Histogram(), Initialize(), MemoryConsumedEstimated(), Raster(), ReduceToMostCompleteBlob(), ReverseImage(), ToColor(), ToCompressor(), TotalBackgroundPixels(), and TotPixels().
bool KKU::Raster::weOwnRasterData protected
Definition at line 1038 of file Raster.h.
Referenced by Initialize(), Raster(), and WeOwnRasterData().
int32 KKU::Raster::width protected
Definition at line 1039 of file Raster.h.
Referenced by BandPass(), CalcArea(), CalcAreaAndIntensityHistogram(), CalcAreaAndIntensityHistogramWhite(), CalcCentroid(), CalcOrientationAndEigerRatio(), CalcWeightedArea(), CenMoment(), CenMomentWeighted(), ConnectedComponent(), ConnectedComponent8Conected(), ConnectedComponentOrig(), CreateDialatedRaster(), CreateErodedImage(), CreateGrayScale(), CreateGrayScaleKLTOnMaskedArea(), KKU::RasterList::CreateSmoothedFrame(), CreateSmoothedMediumImage(), KKU::RasterSipper::DeriveImageLength(), DerivePreRotatedPoint(), DrawCircle(), Erosion(), ErosionBoundary(), FastFourier(), FastFourierKK(), FillBlob(), FillHole(), KKU::RasterSipper::FromCompressor(), KKU::RasterSipper::FromSimpleCompression(), HistogramEqualizedImage(), HistogramGrayscale(), Initialize(), Padded(), Raster(), ReduceByEvenMultiple(), ReduceByFactor(), ReduceToMostCompleteBlob(), Rotate(), ThinContour(), ThresholdInHSI(), and Width().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Raster.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Raster.cpp