Pices: MLL::FeatureFileIOUCI Class Reference
MLL::FeatureFileIOUCI Class Reference
Supports the reading and writting of Feature data from a file format commonly used by many datasets in the UCI repository.
#include <FeatureFileIOUCI.h>
Public Types
typedef FeatureFileIOUCI * FeatureFileIOUCIPtr
Public Types inherited from MLL::FeatureFileIO
typedef FeatureFileIO * FeatureFileIOPtr
typedef KKU::int32 int32
typedef KKU::uint32 uint32
Public Member Functions
FeatureFileIOUCI ()
~FeatureFileIOUCI ()
virtual FileDescPtr GetFileDesc (const KKStr &_fileName, istream &_in, MLClassConstListPtr _classList, int32 &_estSize, KKStr &_errorMessage, RunLog &_log)
virtual FeatureVectorListPtr LoadFile (const KKStr &_fileName, const FileDescPtr _fileDesc, MLClassConstList &_classes, istream &_in, long _maxCount, volatile const bool &_cancelFlag, bool &_changesMade, KKStr &_errorMessage, RunLog &_log)
virtual void SaveFile (FeatureVectorList &_data, const KKStr &_fileName, const FeatureNumList &_selFeatures, ostream &_out, uint32 &_numExamplesWritten, volatile const bool &_cancelFlag, bool &_successful, KKStr &_errorMessage, RunLog &_log)
Public Member Functions inherited from MLL::FeatureFileIO
FeatureFileIO (const KKStr &_driverName, bool _canRead, bool _canWrite)
virtual ~FeatureFileIO ()
void AppendToFile (const KKStr &_fileName, const FeatureNumList &_selFeatures, FeatureVectorList &_examples, uint32 &_numExamplesWritten, volatile const bool &_cancelFlag, bool &_successful, RunLog &log)
bool CanRead ()
bool CanWrite ()
const KKStr & DriverName ()
virtual FileDescPtr GetFileDesc (const KKStr &_fileName, std::istream &_in, MLClassConstListPtr _classes, int32 &_estSize, KKStr &_errorMessage, RunLog &_log)=0
Create a FileDesc object from the input stream '_in'.
virtual FeatureVectorListPtr LoadFeatureFile (const KKStr &_fileName, MLClassConstList &_mlClasses, long _maxCount, volatile const bool &_cancelFlag, bool &_successful, bool &_changesMade, RunLog &_log)
Loads the contents of a feature data file and returns a ImageFeaturesList container object.
virtual FeatureVectorListPtr LoadFile (const KKStr &_fileName, const FileDescPtr _fileDesc, MLClassConstList &_classes, std::istream &_in, long _maxCount, volatile const bool &_cancelFlag, bool &_changesMade, KKStr &_errorMessage, RunLog &_log)=0
To be implemented by derived classes; loads the contents of a feature data file and returns a ImageFeaturesList container object.
virtual void SaveFeatureFile (const KKStr &_fileName, const FeatureNumList &_selFeatures, FeatureVectorList &_examples, uint32 &_numExamplesWritten, volatile const bool &_cancelFlag, bool &_successful, RunLog &_log)
SaveFeatureFile.
void SaveFeatureFileMultipleParts (const KKStr &_fileName, const FeatureNumList &_selFeatures, FeatureVectorList &_examples, volatile const bool &_cancelFlag, bool &_successful, RunLog &_log)
Saves the feature file in multiple parts with no one single part larger that 64k examples.
virtual void SaveFile (FeatureVectorList &_data, const KKStr &_fileName, const FeatureNumList &_selFeatures, std::ostream &_out, uint32 &_numExamplesWritten, volatile const bool &_cancelFlag, bool &_successful, KKStr &_errorMessage, RunLog &_log)=0
To be implmenetd by derived classes; save examples to output stream '_out'.
Static Public Member Functions
static FeatureFileIOUCIPtr Driver ()
Static Public Member Functions inherited from MLL::FeatureFileIO
static FeatureFileIOPtr FileFormatFromStr (const KKStr &_fileFormatStr)
static FeatureFileIOPtr FileFormatFromStr (const KKStr &_fileFormatStr, bool _canRead, bool _canWrite)
static KKStr FileFormatsReadAndWriteOptionsStr ()
static KKStr FileFormatsReadOptionsStr ()
static KKStr FileFormatsWrittenOptionsStr ()
static void FinalCleanUp ()
Before you terminate your application and after all FeatureFileIO activity is done call this method to destroy statically dynamically allocated data structures.
static VectorKKStr RegisteredDriverNames (bool canRead, bool canWrite)
Additional Inherited Members
Protected Member Functions inherited from MLL::FeatureFileIO
void GetLine (std::istream &_in, KKStr &_line, bool &_eof)
void GetToken (std::istream &_in, const char *_delimiters, KKStr &_token, bool &_eof, bool &_eol)
Will retrieve the next token from the input stream.
Detailed Description
Supports the reading and writting of Feature data from a file format commonly used by many datasets in the UCI repository.
************************************************************************************************
*  FeatureFileIOUCI  Sub-classed from FeatureFileIO.  It supports the reading and writting     *
*  of many of the files found in the UCI repository.                                           *
*                                                                                              *
*  1) One example per row.                                                                     *
*  2) Each field is seperated by comma.                                                        *
*  3) Each row has the same number of fields.                                                  *
*  4) The last field is the ClassName.                                                         *
*  5) Each field is numeric except the last one which is the ClassName                         *
************************************************************************************************
See Also
FeatureFileIO
Definition at line 32 of file FeatureFileIOUCI.h.
Member Typedef Documentation
typedef FeatureFileIOUCI* MLL::FeatureFileIOUCI::FeatureFileIOUCIPtr
Definition at line 39 of file FeatureFileIOUCI.h.
Constructor & Destructor Documentation
FeatureFileIOUCI::FeatureFileIOUCI ()
Definition at line 35 of file FeatureFileIOUCI.cpp.
FeatureFileIOUCI::~FeatureFileIOUCI ()
Definition at line 42 of file FeatureFileIOUCI.cpp.
Member Function Documentation
static FeatureFileIOUCIPtr MLL::FeatureFileIOUCI::Driver () inline static
Definition at line 41 of file FeatureFileIOUCI.h.
FileDescPtr FeatureFileIOUCI::GetFileDesc (const KKStr & _fileName, istream & _in, MLClassConstListPtr _classList, int32 & _estSize, KKStr & _errorMessage, RunLog & _log) virtual
Definition at line 48 of file FeatureFileIOUCI.cpp.
References MLL::FileDesc::AddAAttribute(), KKU::KKStr::Empty(), KKU::endl(), KKU::KKStr::ExtractToken(), MLL::FeatureFileIO::GetLine(), MLL::MLClassConstList::GetMLClassPtr(), KKU::RunLog::Level(), SVM289_MFS::Max(), MLL::NumericAttribute, KKU::StrFormatInt(), KKU::KKStr::SubStrPart(), KKU::KKStr::TrimLeft(), and KKU::KKStr::TrimRight().
FeatureVectorListPtr FeatureFileIOUCI::LoadFile (const KKStr & _fileName, const FileDescPtr _fileDesc, MLClassConstList & _classes, istream & _in, long _maxCount, volatile const bool & _cancelFlag, bool & _changesMade, KKStr & _errorMessage, RunLog & _log) virtual
Definition at line 114 of file FeatureFileIOUCI.cpp.
References MLL::FeatureVector::AddFeatureData(), KKU::KKStr::Empty(), KKU::endl(), KKU::KKStr::ExtractToken(), MLL::FeatureFileIO::GetLine(), MLL::MLClassConstList::GetMLClassPtr(), MLL::FeatureVector::ImageFileName(), KKU::RunLog::Level(), MLL::FeatureVector::MLClass(), MLL::FileDesc::NumOfFields(), KKU::osGetRootName(), MLL::FeatureVectorList::PushOnBack(), KKU::KKStr::Str(), KKU::StrFormatInt(), KKU::KKStr::SubStrPart(), KKU::KKStr::TrimLeft(), and KKU::KKStr::TrimRight().
void FeatureFileIOUCI::SaveFile (FeatureVectorList & _data, const KKStr & _fileName, const FeatureNumList & _selFeatures, ostream & _out, uint32 & _numExamplesWritten, volatile const bool & _cancelFlag, bool & _successful, KKStr & _errorMessage, RunLog & _log) virtual
Definition at line 179 of file FeatureFileIOUCI.cpp.
References MLL::FeatureVector::ClassName(), KKU::endl(), MLL::FeatureVector::FeatureData(), MLL::FeatureNumList::NumOfFeatures(), and x.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/FeatureFileIOUCI.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/FeatureFileIOUCI.cpp