Pices: SipperFile.SipperFileSimple Class Reference
SipperFile.SipperFileSimple Class Reference
Public Member Functions
SipperFileSimple (string _fileName, InstrumentDataManager _instrumentDataManager)
SipperFileSimple (Stream _stream, InstrumentDataManager _instrumentDataManager)
override void Dispose ()
override int LengthNextScanLine ()
override void ReadNextScanLine (byte[] scanLine)
override void SkipNextScanLine ()
Public Member Functions inherited from SipperFile.SipperBaseFile
SipperBaseFile (Stream _stream, InstrumentDataManager _instrumentDataManager)
SipperBaseFile (string _fileName, InstrumentDataManager _instrumentDataManager)
byte[][] AllocateFrame ()
byte[][] CreateRatser (int scanLineStart, int numScanLines)
bool Eof ()
bool EofReached ()
virtual long EstimatedNumberOfScanLines ()
long FileSizeInBytes ()
void FrameBytesOffsetsUpdateThreadStart (InstrumentDataList _history)
void FrameBytesOffsetsUpdateThreadTerminate ()
void FrameRead (int frameNum, SipperFrame frame, ref bool found)
int LargestKnowmFrameNum ()
long LargestKnownScanLine ()
void ReadNextFrame (byte[][] frame)
virtual int ScanLineSize ()
bool ValidateFormat ()
Additional Inherited Members
Public Attributes inherited from SipperFile.SipperBaseFile
const int PixelsPerScanLine = 4096
const int ScanLinesPerFrame = 4096
Protected Member Functions inherited from SipperFile.SipperBaseFile
byte[] GetNextBuff (uint buffLen)
byte GetNextByte ()
ushort GetNextRecord ()
uint GetNextUint ()
Protected Attributes inherited from SipperFile.SipperBaseFile
bool eof = false
InstrumentDataManager instrumentDataManager = null
long lastScanLineNum = 0
Detailed Description
Definition at line 12 of file SipperFileSimple.cs.
Constructor & Destructor Documentation
SipperFile.SipperFileSimple.SipperFileSimple (string _fileName, InstrumentDataManager _instrumentDataManager) inline
Definition at line 14 of file SipperFileSimple.cs.
SipperFile.SipperFileSimple.SipperFileSimple (Stream _stream, InstrumentDataManager _instrumentDataManager) inline
Definition at line 22 of file SipperFileSimple.cs.
Member Function Documentation
override void SipperFile.SipperFileSimple.Dispose () inline virtual
Reimplemented from SipperFile.SipperBaseFile.
Definition at line 32 of file SipperFileSimple.cs.
override int SipperFile.SipperFileSimple.LengthNextScanLine () inline virtual
Reimplemented from SipperFile.SipperBaseFile.
Definition at line 41 of file SipperFileSimple.cs.
References SipperFile.SipperBaseFile.GetNextBuff(), and SipperFile.SipperBaseFile.GetNextUint().
override void SipperFile.SipperFileSimple.ReadNextScanLine (byte[] scanLine) inline virtual
Reimplemented from SipperFile.SipperBaseFile.
Definition at line 62 of file SipperFileSimple.cs.
References SipperFile.SipperBaseFile.GetNextByte(), SipperFile.SipperBaseFile.GetNextUint(), and x.
override void SipperFile.SipperFileSimple.SkipNextScanLine () inline virtual
Reimplemented from SipperFile.SipperBaseFile.
Definition at line 54 of file SipperFileSimple.cs.
References SipperFile.SipperBaseFile.GetNextBuff(), and SipperFile.SipperBaseFile.GetNextUint().
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperFile/SipperFileSimple.cs