Pices: MLL::FeatureEncoder2 Class Reference
MLL::FeatureEncoder2 Class Reference
#include <FeatureEncoder2.h>
Classes
struct FeatureVar2
class FeatureVar2List
class FeatureVarComparrison2
Public Types
typedef FeatureEncoder2 * FeatureEncoder2Ptr
enum FeWhatToDo { FeAsIs, FeBinary, FeScale }
typedef FeWhatToDo * FeWhatToDoPtr
Public Member Functions
FeatureEncoder2 (const ModelParam &_param, FileDescPtr _fileDesc, RunLog &_log)
FeatureEncoder2 (const FeatureEncoder2 &_encoder)
~FeatureEncoder2 ()
Frees any memory allocated by, and owned by the FeatureEncoder2.
int32 CodedNumOfFeatures () const
CompressionStats CompressExamples (const FeatureVectorListPtr srcImages, FeatureVectorListPtr &dest)
Attempts to reduce the number of images in the images_list via compression if no compression specified will just copy refrences to images to compressed list, and flag as Opwner(false).
FileDescPtr CreateEncodedFileDesc (ostream *o) const
If 'o' is not NULL will write out a table showing assignments from old to new.
FeatureVectorPtr EncodeAExample (FeatureVectorPtr src) const
FeatureVectorListPtr EncodeAllExamples (const FeatureVectorListPtr srcData)
FeatureVectorListPtr EncodedFeatureVectorList (const FeatureVectorList &srcData) const
int32 MemoryConsumedEstimated () const
int32 NumEncodedFeatures () const
void ReadXML (istream &i)
void WriteXML (istream &o)
Detailed Description
                     FeatureEncoder2                               *
                                                                   *
This will eventually replace "FeatureEncoder" when we shift over   *
to the new paradigm where all Machine Learning Algorithms will be  *
derived from 'Model'.                                              *
Definition at line 29 of file FeatureEncoder2.h.
Member Typedef Documentation
typedef FeatureEncoder2* MLL::FeatureEncoder2::FeatureEncoder2Ptr
Definition at line 32 of file FeatureEncoder2.h.
typedef FeWhatToDo* MLL::FeatureEncoder2::FeWhatToDoPtr
Definition at line 35 of file FeatureEncoder2.h.
Member Enumeration Documentation
enum MLL::FeatureEncoder2::FeWhatToDo
Enumerator
FeAsIs
FeBinary
FeScale
Definition at line 34 of file FeatureEncoder2.h.
Constructor & Destructor Documentation
MLL::FeatureEncoder2::FeatureEncoder2 (const ModelParam & _param, FileDescPtr _fileDesc, RunLog & _log)
Referenced by MemoryConsumedEstimated().
MLL::FeatureEncoder2::FeatureEncoder2 (const FeatureEncoder2 & _encoder)
Definition at line 139 of file FeatureEncoder2.cpp.
References KKU::endl(), KKU::RunLog::Level(), MLL::ModelParam::SelectedFeatures(), and x.
MLL::FeatureEncoder2::~FeatureEncoder2 ()
Frees any memory allocated by, and owned by the FeatureEncoder2.
Definition at line 185 of file FeatureEncoder2.cpp.
Member Function Documentation
int32 MLL::FeatureEncoder2::CodedNumOfFeatures () const inline
Definition at line 49 of file FeatureEncoder2.h.
CompressionStats MLL::FeatureEncoder2::CompressExamples (const FeatureVectorListPtr src, FeatureVectorListPtr & dest)
Attempts to reduce the number of images in the images_list via compression if no compression specified will just copy refrences to images to compressed list, and flag as Opwner(false).
Parameters
[in] images_list The list of images you want to attempt to reduce
[out] compressed_images_list The reduced list of images
Returns
a CompressionStats struct containing the details of the compression
Definition at line 404 of file FeatureEncoder2.cpp.
References MLL::FeatureVectorList::AddQueue(), MLL::ModelParam::BRcompressionPost, MLL::ModelParam::BRunBalancedSpecified, MLL::ModelParam::BRunBalancedVariance, MLL::CompressionStats::compression_ratio, MLL::CompressionStats::elapsed_cpu_time, KKU::endl(), KKU::RunLog::Level(), MLL::CompressionStats::num_images_after, MLL::CompressionStats::num_images_before, and KKU::osGetSystemTimeUsed().
Referenced by MLL::Model::TrainModel().
FileDescPtr MLL::FeatureEncoder2::CreateEncodedFileDesc (ostream * o) const
If 'o' is not NULL will write out a table showing assignments from old to new.
Definition at line 221 of file FeatureEncoder2.cpp.
References MLL::FileDesc::AddAAttribute(), KKU::endl(), FeAsIs, FeBinary, FeScale, MLL::FileDesc::FieldName(), MLL::FileDesc::GetExistingFileDesc(), MLL::FileDesc::GetNominalValue(), KKU::RunLog::Level(), MLL::NumericAttribute, KKU::osWaitForEnter(), KKU::StrFormatInt(), MLL::FileDesc::TypeStr(), and x.
FeatureVectorPtr MLL::FeatureEncoder2::EncodeAExample (FeatureVectorPtr src) const
Definition at line 321 of file FeatureEncoder2.cpp.
References MLL::FeatureVector::AddFeatureData(), FeAsIs, MLL::FeatureVector::FeatureData(), FeBinary, FeScale, MLL::FeatureVector::MLClass(), MLL::FeatureVector::PredictedClass(), MLL::FeatureVector::TrainWeight(), and x.
Referenced by EncodeAllExamples(), EncodedFeatureVectorList(), and MLL::Model::PrepExampleForPrediction().
FeatureVectorListPtr MLL::FeatureEncoder2::EncodeAllExamples (const FeatureVectorListPtr srcData)
Definition at line 371 of file FeatureEncoder2.cpp.
References EncodeAExample(), and MLL::FeatureVectorList::PushOnBack().
Referenced by MLL::Model::TrainModel().
FeatureVectorListPtr MLL::FeatureEncoder2::EncodedFeatureVectorList (const FeatureVectorList & srcData) const
Definition at line 454 of file FeatureEncoder2.cpp.
References MLL::FeatureVectorList::AllFieldsAreNumeric(), EncodeAExample(), MLL::FeatureVector::MLClass(), and MLL::FeatureVectorList::PushOnBack().
int32 MLL::FeatureEncoder2::MemoryConsumedEstimated () const
Definition at line 196 of file FeatureEncoder2.cpp.
References FeatureEncoder2(), and MLL::FileDesc::NumOfFields().
Referenced by MLL::Model::MemoryConsumedEstimated().
int32 MLL::FeatureEncoder2::NumEncodedFeatures () const
Definition at line 213 of file FeatureEncoder2.cpp.
References MLL::FileDesc::NumOfFields().
void MLL::FeatureEncoder2::ReadXML (istream & i)
void MLL::FeatureEncoder2::WriteXML (istream & o)
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/FeatureEncoder2.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/FeatureEncoder2.cpp