Pices: KKU::KKStrMatrix Class Reference
KKU::KKStrMatrix Class Reference
A two dimensional matrix of Strings.
#include <Str.h>
Public Types
typedef KKStrMatrix * KKStrMatrixPtr
typedef KKU::uint32 uint32
Public Member Functions
KKStrMatrix (uint32 _numCols)
KKStrMatrix (uint32 _numCols, uint32 _numRows)
~KKStrMatrix ()
void AddRow (KKStrListPtr newRowData)
Adds a list of Strings to the end of the Matrix.
void AddRow ()
Adds a row of empty string to the end of the matix.
uint32 NumCols () const
uint32 NumRows () const
KKStrList & operator() (uint32 row)
KKStr & operator() (uint32 row, uint32 col)
KKStrList & operator[] (uint32 row)
Detailed Description
A two dimensional matrix of Strings.
Definition at line 900 of file Str.h.
Member Typedef Documentation
typedef KKStrMatrix* KKU::KKStrMatrix::KKStrMatrixPtr
Definition at line 903 of file Str.h.
typedef KKU::uint32 KKU::KKStrMatrix::uint32
Definition at line 904 of file Str.h.
Constructor & Destructor Documentation
KKU::KKStrMatrix::KKStrMatrix (uint32 _numCols) inline
Definition at line 907 of file Str.h.
KKU::KKStrMatrix::KKStrMatrix (uint32 _numCols, uint32 _numRows) inline
Definition at line 914 of file Str.h.
References AddRow().
KKU::KKStrMatrix::~KKStrMatrix () inline
Definition at line 924 of file Str.h.
Member Function Documentation
void KKStrMatrix::AddRow (KKStrListPtr newRowData)
Adds a list of Strings to the end of the Matrix.
Add a row of 'KKStr' instances; will take ownership of newRowData.
Will add another row to the matrix and populate its contents with the String List being passed in.
Parameters
IN] newRowData Will take ownership of this String list.
Definition at line 495 of file Str.cpp.
Referenced by MLL::DataBase::ImageGroupEntriesInsert(), MLL::DataBase::QueryStatementKKStr(), and MLL::DataBase::QueryStatementReturnAllColumns().
void KKStrMatrix::AddRow ()
Adds a row of empty string to the end of the matix.
Definition at line 504 of file Str.cpp.
Referenced by KKStrMatrix().
uint32 KKU::KKStrMatrix::NumCols () const inline
Definition at line 930 of file Str.h.
Referenced by MLL::DataBase::ImagesLocateClosestImage(), and MarineSnowReportDeployment().
uint32 KKU::KKStrMatrix::NumRows () const inline
Definition at line 929 of file Str.h.
Referenced by PicesInterface::PicesDataBase::ImageGroupEntriesInsert(), MLL::DataBase::ImagesLocateClosestImage(), MarineSnowReportDeployment(), and PicesInterface::PicesDataBase::QueryStatement().
KKStrList & KKStrMatrix::operator() (uint32 row)
Definition at line 454 of file Str.cpp.
References KKU::endl(), and KKU::StrFormatInt().
KKStr & KKStrMatrix::operator() (uint32 row, uint32 col)
Definition at line 468 of file Str.cpp.
References KKU::endl(), and KKU::StrFormatInt().
KKStrList & KKStrMatrix::operator[] (uint32 row)
Definition at line 439 of file Str.cpp.
References KKU::endl(), and KKU::StrFormatInt().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Str.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Str.cpp