Pices: KKU::Blob Class Reference
KKU::Blob Class Reference
Used by the Raster object to identify a distinct blob; where it is in the raster and its unique id.
#include <Blob.h>
Public Member Functions
Blob (int32 _id)
~Blob ()
Point BotRight () const
Returns a point to the Bottom Right corner of the blob.
int32 ColLeft ()
Left most column in the raster object that this blob occupies.
int32 ColRight ()
Right most column in the raster object that this blob occupies.
int32 Height ()
Number of rows that the blob occupies.
int32 Id ()
The unique ID assigned to this blob.
int32 PixelCount ()
Number of pixels that are part of this blob.
int32 RowBot ()
Bottom row in the raster object that this blob occupies.
int32 RowTop ()
Top row in the raster object that this blob occupies.
Point TopLeft () const
Returns a point to the Top Left corner of the blob.
int32 Width ()
Number of columns that this blob occupies.
Public Attributes
int32 colLeft
int32 colRight
int32 id
int32 pixelCount
int32 rowBot
int32 rowTop
Friends
class BlobList
Detailed Description
Used by the Raster object to identify a distinct blob; where it is in the raster and its unique id.
It is used by the Raster object while performing a connected component analysis. For each distinct blob located an instance of this class will be created. Its location in the raster and its unique blob ID will be stored here. These blobs will later be able to be extracted from the image by referencing this blob.
The "id" field in this blob will be stored in a array in the associated Raster object. This allows the Raster object to identify the specific pixels that belong to this Blob. Using the fields "colLeft" "colRight", "rowBot", and "rowTop" the Raster object will be able to quickly locate the associated blob.
See Also
KKU::Raster
KKU::Raster::ExtractABlob
KKU::Raster::ExtractABlobTightly
Definition at line 32 of file Blob.h.
Constructor & Destructor Documentation
Blob::Blob (int32 _id)
Definition at line 22 of file Blob.cpp.
Blob::~Blob ()
Definition at line 35 of file Blob.cpp.
Member Function Documentation
Point KKU::Blob::BotRight () const inline
Returns a point to the Bottom Right corner of the blob.
Definition at line 56 of file Blob.h.
References colRight, and rowBot.
int32 KKU::Blob::ColLeft () inline
Left most column in the raster object that this blob occupies.
Definition at line 43 of file Blob.h.
References colLeft.
Referenced by KKU::Raster::CreateColorWithBlobsLabeldByColor(), KKU::Raster::CreateFromOrginalImageWithSpecifidBlobsOnly(), and KKU::Raster::FillBlob().
int32 KKU::Blob::ColRight () inline
Right most column in the raster object that this blob occupies.
Definition at line 44 of file Blob.h.
References colRight.
Referenced by KKU::Raster::CreateColorWithBlobsLabeldByColor(), KKU::Raster::CreateFromOrginalImageWithSpecifidBlobsOnly(), and KKU::Raster::FillBlob().
int32 KKU::Blob::Height () inline
Number of rows that the blob occupies.
Definition at line 46 of file Blob.h.
References rowBot, and rowTop.
Referenced by KKU::Raster::ExtractABlobTightly(), and KKU::BlobList::LocateMostComplete().
int32 KKU::Blob::Id () inline
The unique ID assigned to this blob.
See Also
BlobList::nextBlobId
Definition at line 41 of file Blob.h.
References id.
Referenced by KKU::Raster::ConnectedComponent(), KKU::Raster::ConnectedComponent8Conected(), KKU::Raster::ConnectedComponentOrig(), KKU::Raster::CreateColorWithBlobsLabeldByColor(), KKU::Raster::CreateFromOrginalImageWithSpecifidBlobsOnly(), KKU::Raster::ExtractBlobs(), KKU::Raster::FillBlob(), KKU::BlobList::MergeBlobIds(), KKU::BlobList::MergeIntoSingleBlob(), KKU::BlobList::PushOnBack(), KKU::BlobList::PushOnFront(), and KKU::Raster::ReduceToMostCompleteBlob().
int32 KKU::Blob::PixelCount () inline
Number of pixels that are part of this blob.
Definition at line 53 of file Blob.h.
References pixelCount.
Referenced by KKU::BlobList::MergeIntoSingleBlob().
int32 KKU::Blob::RowBot () inline
Bottom row in the raster object that this blob occupies.
Definition at line 48 of file Blob.h.
References rowBot.
Referenced by KKU::Raster::CreateColorWithBlobsLabeldByColor(), KKU::Raster::CreateFromOrginalImageWithSpecifidBlobsOnly(), and KKU::Raster::FillBlob().
int32 KKU::Blob::RowTop () inline
Top row in the raster object that this blob occupies.
Definition at line 49 of file Blob.h.
References rowTop.
Referenced by KKU::Raster::CreateColorWithBlobsLabeldByColor(), KKU::Raster::CreateFromOrginalImageWithSpecifidBlobsOnly(), and KKU::Raster::FillBlob().
Point KKU::Blob::TopLeft () const inline
Returns a point to the Top Left corner of the blob.
Definition at line 55 of file Blob.h.
References colLeft, and rowTop.
int32 KKU::Blob::Width () inline
Number of columns that this blob occupies.
Definition at line 51 of file Blob.h.
References colLeft, and colRight.
Referenced by KKU::Raster::ExtractABlobTightly(), and KKU::BlobList::LocateMostComplete().
Friends And Related Function Documentation
friend class BlobList friend
Definition at line 34 of file Blob.h.
Member Data Documentation
int32 KKU::Blob::colLeft
Definition at line 58 of file Blob.h.
Referenced by ColLeft(), KKU::Raster::ConnectedComponent8Conected(), KKU::Raster::ConnectedComponentOrig(), KKU::Raster::ExtractABlob(), KKU::Raster::ExtractABlobTightly(), KKU::Raster::ExtractBlobs(), KKU::BlobList::MergeBlobIds(), KKU::BlobList::MergeIntoSingleBlob(), KKU::BlobList::NewBlob(), TopLeft(), and Width().
int32 KKU::Blob::colRight
Definition at line 59 of file Blob.h.
Referenced by BotRight(), ColRight(), KKU::Raster::ConnectedComponent8Conected(), KKU::Raster::ConnectedComponentOrig(), KKU::Raster::ExtractBlobs(), KKU::BlobList::MergeBlobIds(), KKU::BlobList::MergeIntoSingleBlob(), KKU::BlobList::NewBlob(), and Width().
int32 KKU::Blob::id
Definition at line 60 of file Blob.h.
Referenced by KKU::Raster::ConnectedComponent8Conected(), KKU::Raster::ConnectedComponentOrig(), KKU::Raster::ExtractABlob(), KKU::Raster::ExtractABlobTightly(), KKU::Raster::ExtractBlobs(), and Id().
int32 KKU::Blob::pixelCount
Definition at line 61 of file Blob.h.
Referenced by KKU::Raster::ConnectedComponent8Conected(), KKU::Raster::ConnectedComponentOrig(), KKU::Raster::ExtractBlobs(), KKU::BlobList::LocateLargestBlob(), KKU::BlobList::MergeBlobIds(), KKU::BlobList::MergeIntoSingleBlob(), and PixelCount().
int32 KKU::Blob::rowBot
Definition at line 62 of file Blob.h.
Referenced by BotRight(), KKU::Raster::ConnectedComponent8Conected(), KKU::Raster::ConnectedComponentOrig(), KKU::Raster::ExtractBlobs(), Height(), KKU::BlobList::MergeBlobIds(), KKU::BlobList::MergeIntoSingleBlob(), KKU::BlobList::NewBlob(), and RowBot().
int32 KKU::Blob::rowTop
Definition at line 63 of file Blob.h.
Referenced by KKU::Raster::ConnectedComponent8Conected(), KKU::Raster::ConnectedComponentOrig(), KKU::Raster::ExtractABlob(), KKU::Raster::ExtractABlobTightly(), KKU::Raster::ExtractBlobs(), Height(), KKU::BlobList::MergeBlobIds(), KKU::BlobList::MergeIntoSingleBlob(), KKU::BlobList::NewBlob(), RowTop(), and TopLeft().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Blob.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Blob.cpp