Pices: KKU::DateType Class Reference
KKU::DateType Class Reference
Represents a calendar date consisting of three fields, Year, Month, and Day.
#include <DateTime.h>
Public Member Functions
DateType ()
DateType (const DateType &_date)
DateType (short _year, uchar _month, uchar _day)
DateType (int32 days)
Constructs a date from an integer that represents the total number of days since 1/1/0000.
DateType (KKStr s)
Constructs a date from a displayable string.
void AddDays (int32 _days)
Adds a number of days to the date.
void AddMonths (int32 _months)
uchar Day () const
int32 Days () const
Returns back the number of days since "1/1/0000".
uchar DaysThisMonth () const
returns the number of days in 'month' and if leapYear and february returns 29.
KKStr MM_DD_YY () const
KKStr MMM_DD_YYYY () const
Convert into displayable string; ex: May/02/2010.
uchar Month () const
bool operator!= (const DateType &right) const
DateType operator+ (const DateType &right) const
DateType operator+ (int32 right) const
DateType & operator++ ()
DateType operator- (int32 right) const
DateType operator- (const DateType &right) const
bool operator< (const DateType &right) const
bool operator<= (const DateType &right) const
DateType & operator= (const DateType &right)
bool operator== (const DateType &right) const
bool operator> (const DateType &right) const
bool operator>= (const DateType &right) const
uint64 Seconds () const
void SubtractDays (int32 _days)
uint32 ToDays () const
uint32 ToHours () const
uint64 ToSeconds () const
short Year () const
KKStr YY_MM_DD () const
Convert into displayable string; ex: 11/05/17.
KKStr YYYY_MM_DD () const
Convert into displayable string; ex: 20011/05/17.
KKStr YYYY_MMM_DD () const
Convert into displayable string; ex: 20011/May/17.
KKStr YYYYMMDD () const
Convert into displayable string; ex: 20110517.
Static Public Member Functions
static uchar DaysInTheMonth (int32 year, uchar month)
static int32 DaysYTDforMonth (int32 year, uchar month)
static uchar MonthFromStr (const KKStr &monthStr)
Friends
class DateTime
Detailed Description
Represents a calendar date consisting of three fields, Year, Month, and Day.
This date format will support operations that will allow you to determine the number of days between two dates; derive a new date by adding or subtracting Days, Months, or Years from an existing date, etc; and convert date into one of several displayable formats.
Definition at line 30 of file DateTime.h.
Constructor & Destructor Documentation
DateType::DateType ()
Definition at line 160 of file DateTime.cpp.
Referenced by operator+(), and operator-().
DateType::DateType (const DateType & _date)
Definition at line 169 of file DateTime.cpp.
DateType::DateType (short _year, uchar _month, uchar _day)
Definition at line 178 of file DateTime.cpp.
DateType::DateType (int32 days)
Constructs a date from an integer that represents the total number of days since 1/1/0000.
Definition at line 314 of file DateTime.cpp.
DateType::DateType (KKStr s)
Constructs a date from a displayable string.
Strings can be both all numeric or combination of alpha numeric. Each part of the date, (Year, Month, Day) can be separated by ' ', '/', '', '
', or ''. Examples of valid strings are "1997/02/25", "02/25/1997", "Feb 02 1997", "02/Feb/1997", "1997 February 02". The ordering of the numeric fields will be determined by context with one of three possible formats, mm/dd/yyyy, yyyy/mm/dd, and dd/mm/yyyy.
A flaw in this schema is that if the day of the month is in the range of (1<->12), an all numeric format is used, and the ordering is supposed to be "dd/mm/yyyy" this routine will assume that it is looking at "mm/dd/yyyy" with the result of swapping the "Month" and "Day" fields. As a rule I try to always use the alpha numeric version of the month.
Definition at line 190 of file DateTime.cpp.
References DaysInTheMonth(), KKU::KKStr::ExtractToken(), MonthFromStr(), and KKU::KKStr::Str().
Member Function Documentation
void DateType::AddDays (int32 _days)
Adds a number of days to the date.
Example:   Date d ("April 14 1962");  //  Sets the instance of 'd' to the date '1962/04/14'.
           d.AddDays (12);            //  'd' now contains the date '1962/04/24'.
           d.AddDays (-25);           //  'd' now contains the date '1962/03/30'.
Definition at line 384 of file DateTime.cpp.
References Days(), DaysThisMonth(), and SubtractDays().
Referenced by KKU::DateTime::AddDays(), and SubtractDays().
void DateType::AddMonths (int32 _months)
Definition at line 449 of file DateTime.cpp.
uchar KKU::DateType::Day () const inline
Definition at line 78 of file DateTime.h.
Referenced by SipperHardware::CTD_Plus_Data::CTD_Plus_Data(), PicesInterface::PicesMethods::DateKKUtoSystem(), PicesInterface::PicesMethods::DateTimeKKUtoSystem(), KKU::DateTime::Day(), MM_DD_YY(), MMM_DD_YYYY(), and ToSystemDateTime().
int32 DateType::Days () const
Returns back the number of days since "1/1/0000".
This can be used to determine the number of days between two different dates. For example you have two instances of 'DateType' 'd1' and 'd2'. The number of days between the two dates can be determined by "int deltaDays = d1.Days () - d2.Days ();".
Definition at line 478 of file DateTime.cpp.
References DaysYTDforMonth(), and x.
Referenced by AddDays(), operator+(), KKU::DateTime::operator+(), operator-(), KKU::DateTime::operator-(), Seconds(), SubtractDays(), ToDays(), KKU::DateTime::ToDays(), ToHours(), KKU::DateTime::ToHours(), ToSeconds(), and KKU::DateTime::ToSeconds().
uchar DateType::DaysInTheMonth (int32 year, uchar month) static
Definition at line 117 of file DateTime.cpp.
Referenced by DateType(), DaysThisMonth(), and operator++().
uchar DateType::DaysThisMonth () const
returns the number of days in 'month' and if leapYear and february returns 29.
Definition at line 320 of file DateTime.cpp.
References DaysInTheMonth().
Referenced by AddDays(), and SubtractDays().
int32 DateType::DaysYTDforMonth (int32 year, uchar month) static
Definition at line 135 of file DateTime.cpp.
References daysYTDforMonth.
Referenced by Days().
KKStr DateType::MM_DD_YY () const
Definition at line 670 of file DateTime.cpp.
References Day(), Month(), KKU::StrFormatInt(), and Year().
KKStr DateType::MMM_DD_YYYY () const
Convert into displayable string; ex: May/02/2010.
Definition at line 681 of file DateTime.cpp.
References Day(), KKU::StrFormatInt(), and Year().
uchar KKU::DateType::Month () const inline
Definition at line 77 of file DateTime.h.
Referenced by SipperHardware::CTD_Plus_Data::CTD_Plus_Data(), PicesInterface::PicesMethods::DateKKUtoSystem(), PicesInterface::PicesMethods::DateTimeKKUtoSystem(), MM_DD_YY(), KKU::DateTime::Month(), and ToSystemDateTime().
uchar DateType::MonthFromStr (const KKStr & monthStr) static
Definition at line 98 of file DateTime.cpp.
References KKU::KKStr::CompareIgnoreCase().
Referenced by DateType().
bool DateType::operator!= (const DateType & right) const
Definition at line 553 of file DateTime.cpp.
DateType DateType::operator+ (const DateType & right) const
Definition at line 626 of file DateTime.cpp.
References DateType(), and Days().
DateType DateType::operator+ (int32 right) const
Definition at line 633 of file DateTime.cpp.
References DateType(), and Days().
DateType & DateType::operator++ ()
Definition at line 652 of file DateTime.cpp.
References DaysInTheMonth().
DateType DateType::operator- (int32 right) const
Definition at line 639 of file DateTime.cpp.
References DateType(), and Days().
DateType DateType::operator- (const DateType & right) const
Definition at line 646 of file DateTime.cpp.
References DateType(), and Days().
bool DateType::operator< (const DateType & right) const
Definition at line 574 of file DateTime.cpp.
bool DateType::operator<= (const DateType & right) const
Definition at line 582 of file DateTime.cpp.
DateType & DateType::operator= (const DateType & right)
Definition at line 465 of file DateTime.cpp.
bool DateType::operator== (const DateType & right) const
Definition at line 547 of file DateTime.cpp.
bool DateType::operator> (const DateType & right) const
Definition at line 560 of file DateTime.cpp.
bool DateType::operator>= (const DateType & right) const
Definition at line 567 of file DateTime.cpp.
KKU::uint64 DateType::Seconds () const
Definition at line 505 of file DateTime.cpp.
References Days().
Referenced by KKU::DateTime::Seconds().
void DateType::SubtractDays (int32 _days)
Definition at line 417 of file DateTime.cpp.
References AddDays(), Days(), and DaysThisMonth().
Referenced by AddDays().
KKU::uint32 DateType::ToDays () const
Definition at line 513 of file DateTime.cpp.
References Days().
KKU::uint32 DateType::ToHours () const
Definition at line 514 of file DateTime.cpp.
References Days().
Referenced by KKU::DateTime::HH_MM_SS().
KKU::uint64 DateType::ToSeconds () const
Definition at line 515 of file DateTime.cpp.
References Days().
short KKU::DateType::Year () const inline
Definition at line 76 of file DateTime.h.
Referenced by SipperHardware::CTD_Plus_Data::CTD_Plus_Data(), PicesInterface::PicesMethods::DateKKUtoSystem(), PicesInterface::PicesMethods::DateTimeKKUtoSystem(), MM_DD_YY(), MMM_DD_YYYY(), ToSystemDateTime(), and KKU::DateTime::Year().
KKStr DateType::YY_MM_DD () const
Convert into displayable string; ex: 11/05/17.
Definition at line 696 of file DateTime.cpp.
References KKU::StrFormatInt().
KKStr DateType::YYYY_MM_DD () const
Convert into displayable string; ex: 20011/05/17.
Definition at line 706 of file DateTime.cpp.
References KKU::StrFormatInt().
Referenced by KKU::Application::BuildDate(), DateToQuotedStr(), SipperHardware::InstrumentData::FieldToStr(), KKU::operator<<(), MLL::DataBase::SipperCruiseInsert(), MLL::DataBase::SipperCruiseUpdate(), and KKU::DateTime::YYYY_MM_DD_HH_MM_SS().
KKStr DateType::YYYY_MMM_DD () const
Convert into displayable string; ex: 20011/May/17.
Definition at line 717 of file DateTime.cpp.
References KKU::StrFormatInt().
Referenced by KKU::operator<<().
KKStr DateType::YYYYMMDD () const
Convert into displayable string; ex: 20110517.
Definition at line 732 of file DateTime.cpp.
References KKU::StrFormatInt().
Referenced by KKU::DateTime::YYYYMMDDHHMMSS().
Friends And Related Function Documentation
friend class DateTime friend
Definition at line 144 of file DateTime.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/DateTime.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/DateTime.cpp