Pices: SipperHardware::VolumeSampledStatList Class Reference
SipperHardware::VolumeSampledStatList Class Reference
#include <VolumeSampledStat.h>
Public Types
typedef KKU::int32 int32
typedef VolumeSampledStatList * VolumeSampledStatListPtr
Public Member Functions
VolumeSampledStatList ()
~VolumeSampledStatList ()
void Add (const VolumeSampledStat &stat)
void Give (VolumeSampledStatPtr &stat)
Caller is giving ownership of 'stat' to this instance; upon return 'stat' may be set to NULL indicating that it was merged with an existing instance alrady in the list.
VolumeSampledStatList & operator+= (const VolumeSampledStatList &right)
VolumeSampledStatPtr VolumeSampledStatList::Locate (int binId)
Additional Inherited Members
Public Attributes inherited from std::map< K, T >
T elements
STL member.
K keys
STL member.
Detailed Description
Definition at line 58 of file VolumeSampledStat.h.
Member Typedef Documentation
typedef KKU::int32 SipperHardware::VolumeSampledStatList::int32
Definition at line 61 of file VolumeSampledStat.h.
typedef VolumeSampledStatList* SipperHardware::VolumeSampledStatList::VolumeSampledStatListPtr
Definition at line 62 of file VolumeSampledStat.h.
Constructor & Destructor Documentation
VolumeSampledStatList::VolumeSampledStatList ()
Definition at line 72 of file VolumeSampledStat.cpp.
VolumeSampledStatList::~VolumeSampledStatList ()
Definition at line 79 of file VolumeSampledStat.cpp.
Member Function Documentation
void VolumeSampledStatList::Add (const VolumeSampledStat & stat)
Definition at line 102 of file VolumeSampledStat.cpp.
References SipperHardware::VolumeSampledStat::BinId(), and SipperHardware::VolumeSampledStat::VolumeSampled().
Referenced by operator+=().
void VolumeSampledStatList::Give (VolumeSampledStatPtr & stat)
Caller is giving ownership of 'stat' to this instance; upon return 'stat' may be set to NULL indicating that it was merged with an existing instance alrady in the list.
Definition at line 117 of file VolumeSampledStat.cpp.
References SipperHardware::VolumeSampledStat::AddToVolumeSampled(), SipperHardware::VolumeSampledStat::BinId(), and SipperHardware::VolumeSampledStat::VolumeSampled().
Referenced by MLL::DataBase::InstrumentDataGetVolumePerMeterDepth().
VolumeSampledStatList & VolumeSampledStatList::operator+= (const VolumeSampledStatList & right)
Definition at line 135 of file VolumeSampledStat.cpp.
References Add().
VolumeSampledStatPtr SipperHardware::VolumeSampledStatList::VolumeSampledStatList::Locate (int binId)
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/VolumeSampledStat.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/VolumeSampledStat.cpp