Pices: KKU::XmlStream Class Reference
KKU::XmlStream Class Reference
I created these Xml classes 2010-02-22 to someday simplify the reading and writing of objects to disk.
#include <XmlStream.h>
Public Types
typedef XmlElementPtr(* XmlElementCreator)(XmlTagPtr tag, XmlStream &i)
typedef XmlStream * XmlStreamPtr
Public Member Functions
XmlStream (TokenizerPtr _tokenStream)
XmlStream ()
~XmlStream ()
XmlTokenPtr GetNextToken ()
Will return either a XmlElement or a XmlContent.
Static Public Member Functions
static void RegisterXmlElementCreator (const KKStr &elementName, XmlElementCreator creator)
Register a 'XmlElementCreator' function with its associated name.
Detailed Description
I created these Xml classes 2010-02-22 to someday simplify the reading and writing of objects to disk.
Right now it is more of an Idea Generator than anything usable.
Definition at line 127 of file XmlStream.h.
Member Typedef Documentation
typedef XmlElementPtr(* KKU::XmlStream::XmlElementCreator)(XmlTagPtr tag, XmlStream &i)
Definition at line 139 of file XmlStream.h.
typedef XmlStream* KKU::XmlStream::XmlStreamPtr
Definition at line 132 of file XmlStream.h.
Constructor & Destructor Documentation
XmlStream::XmlStream (TokenizerPtr _tokenStream)
Definition at line 28 of file XmlStream.cpp.
KKU::XmlStream::XmlStream ()
XmlStream::~XmlStream ()
Definition at line 35 of file XmlStream.cpp.
Member Function Documentation
XmlTokenPtr XmlStream::GetNextToken ()
Will return either a XmlElement or a XmlContent.
Definition at line 325 of file XmlStream.cpp.
References KKU::Tokenizer::EndOfFile(), and KKU::Tokenizer::Peek().
void XmlStream::RegisterXmlElementCreator (const KKStr & elementName, XmlElementCreator creator) static
Register a 'XmlElementCreator' function with its associated name.
if you try to register the same function with the same name will generate a warnming to cerr. If you try and register two different functions with the same name will throw an exception.
Definition at line 406 of file XmlStream.cpp.
References KKU::endl().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/XmlStream.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/XmlStream.cpp