Pices: SipperHardware::SipperVariables Class Reference
SipperHardware::SipperVariables Class Reference
Variables that specify where we can locate SIPPER and PICES directories and files are grouped here.
#include <SipperVariables.h>
Public Types
typedef KKU::int32 int32
typedef KKU::int64 int64
typedef KKU::uint32 uint32
typedef KKU::uint64 uint64
Public Member Functions
SipperVariables ()
~SipperVariables ()
Static Public Member Functions
static bool AllowUpdates ()
'True' indicates that user is allowed to peofrom updates.
static void FinalCleanUp ()
static KKU::KKStr InstrumentDataFilesDir ()
Directory where Instrument Data files are stored.
static KKU::KKStr InstrumentDataReportDir ()
Directory where Instrument Data Reports are written to.
static KKU::KKStr LatitudeToStr (double latitude)
static KKU::KKStr LongitudeToStr (double longitude)
static KKU::KKStr PicesCmdLineProgDir ()
Directory where you can Command Line programs such as "CrossValidation.exe".
static KKU::KKStr PicesConfigurationDirectory ()
Where application configuration files go; NOT training models.
static KKU::KKStr PicesDataFileDirectory ()
static KKU::KKStr PicesDataFilesDirectory ()
static KKU::KKStr PicesHomeDir ()
Pices Home Directory.
static KKU::KKStr PicesReportDir ()
static KKU::KKStr PicesTempDirectory ()
static void SetPicesHomeDir (const KKU::KKStr &_picesHomeDir)
static KKU::KKStr SipperConfigrationFileName ()
static KKU::KKStr SipperDirectoryListFileName ()
Specifies the file where we can list directories that containing Sipper Files.
static KKU::KKStr SipperFilesDefaultDir ()
static KKU::KKStr SipperInterfaceDir ()
static KKU::KKStr SipperInterfaceLogDir ()
Where the SipperInterface program will write its log files to.
static KKU::KKStr SubstituteInEvironmentVariables (const KKU::KKStr &src)
Expands the supplied string by substituting in Environment variable values.
static KKU::KKStr TrainingLibrariesDir ()
Directory where training library directories will be under.
static KKU::KKStr TrainingModelsConfigurationDir ()
Directory where all Training Model Configuration files are stored.
static KKU::KKStr TrainingModelsSaveFilesDir ()
Directory where all built trained models are stored.
static KKU::KKStr ValidationInfoDir ()
Directory where Validated Image File Names are stored during image extraction.
Static Public Attributes
static KKU::GoalKeeperPtr blocker = NULL
static KKU::KKStrPtr picesHomeDir = NULL
Detailed Description
Variables that specify where we can locate SIPPER and PICES directories and files are grouped here.
All methods and applications are to use these variables to locate files and directories that they need. This way all the knowledge or where to locate things is kept in this one class.
Definition at line 20 of file SipperVariables.h.
Member Typedef Documentation
typedef KKU::int32 SipperHardware::SipperVariables::int32
Definition at line 23 of file SipperVariables.h.
typedef KKU::int64 SipperHardware::SipperVariables::int64
Definition at line 25 of file SipperVariables.h.
typedef KKU::uint32 SipperHardware::SipperVariables::uint32
Definition at line 24 of file SipperVariables.h.
typedef KKU::uint64 SipperHardware::SipperVariables::uint64
Definition at line 26 of file SipperVariables.h.
Constructor & Destructor Documentation
SipperVariables::SipperVariables ()
Definition at line 29 of file SipperVariables.cpp.
SipperVariables::~SipperVariables ()
Definition at line 35 of file SipperVariables.cpp.
Member Function Documentation
bool SipperVariables::AllowUpdates () static
'True' indicates that user is allowed to peofrom updates.
Definition at line 406 of file SipperVariables.cpp.
void SipperVariables::FinalCleanUp () static
Definition at line 41 of file SipperVariables.cpp.
KKStr SipperVariables::InstrumentDataFilesDir () static
Directory where Instrument Data files are stored.
Definition at line 145 of file SipperVariables.cpp.
References KKU::osAddSlash().
Referenced by SipperHardware::InstrumentDataFileManager::InstrumentDataFileManager().
KKStr SipperVariables::InstrumentDataReportDir () static
Directory where Instrument Data Reports are written to.
Definition at line 153 of file SipperVariables.cpp.
References KKU::osAddSlash().
KKStr SipperVariables::LatitudeToStr (double latitude) static
Definition at line 349 of file SipperVariables.cpp.
References KKU::StrFormatDouble(), and KKU::StrFormatInt().
KKStr SipperVariables::LongitudeToStr (double longitude) static
Definition at line 378 of file SipperVariables.cpp.
References KKU::StrFormatDouble(), and KKU::StrFormatInt().
KKStr SipperVariables::PicesCmdLineProgDir () static
Directory where you can Command Line programs such as "CrossValidation.exe".
Definition at line 136 of file SipperVariables.cpp.
References KKU::osAddSlash().
KKStr SipperVariables::PicesConfigurationDirectory () static
Where application configuration files go; NOT training models.
Definition at line 181 of file SipperVariables.cpp.
References KKU::osAddSlash().
KKStr SipperVariables::PicesDataFileDirectory () static
Definition at line 255 of file SipperVariables.cpp.
References KKU::osAddSlash().
KKStr SipperVariables::PicesDataFilesDirectory () static
Definition at line 197 of file SipperVariables.cpp.
References KKU::osAddSlash().
KKStr SipperVariables::PicesHomeDir () static
Pices Home Directory.
All other directories will be off this directory.
Definition at line 67 of file SipperVariables.cpp.
References KKU::osDisplayWarning(), KKU::osGetCurrentDirectory(), KKU::osGetEnvVariable(), KKU::osGetFullPathOfApplication(), KKU::osGetParentDirPath(), and KKU::osGetPathPartOfFile().
Referenced by SipperHardware::InstrumentDataFileManager::InstrumentDataFileManager().
KKStr SipperVariables::PicesReportDir () static
Definition at line 248 of file SipperVariables.cpp.
References KKU::osAddSlash().
Referenced by SipperHardware::SipperBuff::ReportInstrumentData().
KKStr SipperVariables::PicesTempDirectory () static
Definition at line 262 of file SipperVariables.cpp.
References KKU::osAddSlash(), KKU::osCreateDirectoryPath(), and KKU::osValidDirectory().
void SipperVariables::SetPicesHomeDir (const KKU::KKStr & _picesHomeDir) static
Definition at line 129 of file SipperVariables.cpp.
KKStr SipperVariables::SipperConfigrationFileName () static
Definition at line 189 of file SipperVariables.cpp.
References KKU::osAddSlash().
KKStr SipperVariables::SipperDirectoryListFileName () static
Specifies the file where we can list directories that containing Sipper Files.
Definition at line 204 of file SipperVariables.cpp.
References KKU::osAddSlash().
KKStr SipperVariables::SipperFilesDefaultDir () static
Definition at line 212 of file SipperVariables.cpp.
References KKU::osAddSlash().
KKStr SipperVariables::SipperInterfaceDir () static
Definition at line 159 of file SipperVariables.cpp.
References KKU::osAddSlash(), and KKU::osGetEnvVariable().
KKStr SipperVariables::SipperInterfaceLogDir () static
Where the SipperInterface program will write its log files to.
Definition at line 171 of file SipperVariables.cpp.
References KKU::osAddSlash().
KKStr SipperVariables::SubstituteInEvironmentVariables (const KKU::KKStr & src) static
Expands the supplied string by substituting in Environment variable values.
Similar to the 'osSubstituteInEvironmentVariables' method defined in 'osServices' except that there is some special processing for 'PicesHomeDir'. If 'PicesHomeDir' is not defined then the default location "C:\\Pices" will be used. If a environment variable other than "PicesHomeDir" is not defined then the original string will be returned.
ex: "$(PicesHomeDir)\WFS\Copepod" will expand to: "c:\Pices\WFS\Copepod".
Parameters
[in] src String that is to be search for environment variables and expanded.
Returns
The expanded string.
Definition at line 300 of file SipperVariables.cpp.
References KKU::KKStr::EqualIgnoreCase(), KKU::KKStr::LocateCharacter(), LocateEnvStrStart(), KKU::osGetEnvVariable(), and KKU::KKStr::SubStrPart().
KKStr SipperVariables::TrainingLibrariesDir () static
Directory where training library directories will be under.
Definition at line 235 of file SipperVariables.cpp.
References KKU::osAddSlash().
KKStr SipperVariables::TrainingModelsConfigurationDir () static
Directory where all Training Model Configuration files are stored.
Definition at line 220 of file SipperVariables.cpp.
References KKU::osAddSlash().
KKStr SipperVariables::TrainingModelsSaveFilesDir () static
Directory where all built trained models are stored.
Definition at line 227 of file SipperVariables.cpp.
References KKU::osAddSlash().
KKStr SipperVariables::ValidationInfoDir () static
Directory where Validated Image File Names are stored during image extraction.
Definition at line 241 of file SipperVariables.cpp.
References KKU::osAddSlash().
Member Data Documentation
KKU::GoalKeeperPtr SipperVariables::blocker = NULL static
Definition at line 32 of file SipperVariables.h.
KKU::KKStrPtr SipperVariables::picesHomeDir = NULL static
Definition at line 31 of file SipperVariables.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/SipperVariables.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/SipperVariables.cpp