Pices: PicesInterface::PicesTrainingConfiguration Class Reference
PicesInterface::PicesTrainingConfiguration Class Reference
#include <PicesTrainingConfiguration.h>
Public Member Functions
PicesTrainingConfiguration (PicesRunLog^ _log)
PicesTrainingConfiguration (String^ _configFileName, PicesRunLog^ _log)
PicesTrainingConfiguration (DirectoryInfo^ di, PicesRunLog^ log)
void CancelLoad ()
TrainingConfiguration2Ptr Config ()
PicesClassList^ ExtractClassList ()
PicesFeatureVectorList^ LoadFeatureDataFromTrainingLibraries (bool^ changesMadeToTrainingLibraries)
String^ LoadLogStream ()
String^ ModelName ()
uint NumHierarchialLevels ()
PicesClass^ OtherClass ()
String^ RootDir ()
void Save (String^ configFileName)
PicesTrainingClassList^ TrainingClasses ()
Boolean Valid ()
Static Public Member Functions
static String^ GetEffectiveConfigFileName (String^ configFileName)
Protected Member Functions
!PicesTrainingConfiguration ()
Detailed Description
Definition at line 20 of file PicesTrainingConfiguration.h.
Constructor & Destructor Documentation
PicesInterface::PicesTrainingConfiguration::PicesTrainingConfiguration (PicesRunLog^ _log)
Definition at line 47 of file PicesTrainingConfiguration.cpp.
PicesInterface::PicesTrainingConfiguration::PicesTrainingConfiguration (String^ _configFileName, PicesRunLog^ _log)
Definition at line 62 of file PicesTrainingConfiguration.cpp.
References PicesInterface::PicesRunLog::Log(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
PicesInterface::PicesTrainingConfiguration::PicesTrainingConfiguration (DirectoryInfo^ di, PicesRunLog^ log)
Definition at line 85 of file PicesTrainingConfiguration.cpp.
References MLL::TrainingConfiguration2::ExtractClassList(), PicesInterface::PicesRunLog::Log(), KKU::osAddSlash(), KKU::osGetRootNameOfDirectory(), KKU::osRunAsABackGroundProcess(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
PicesInterface::PicesTrainingConfiguration::!PicesTrainingConfiguration () protected
Definition at line 138 of file PicesTrainingConfiguration.cpp.
Member Function Documentation
void PicesInterface::PicesTrainingConfiguration::CancelLoad ()
Definition at line 168 of file PicesTrainingConfiguration.cpp.
TrainingConfiguration2Ptr PicesInterface::PicesTrainingConfiguration::Config () inline
Definition at line 41 of file PicesTrainingConfiguration.h.
Referenced by PicesInterface::TrainingModel2::TrainingModel2().
PicesClassList PicesInterface::PicesTrainingConfiguration::ExtractClassList ()
Definition at line 212 of file PicesTrainingConfiguration.cpp.
References MLL::TrainingConfiguration2::ExtractClassList().
String PicesInterface::PicesTrainingConfiguration::GetEffectiveConfigFileName (String^ configFileName) static
Definition at line 228 of file PicesTrainingConfiguration.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
PicesFeatureVectorList PicesInterface::PicesTrainingConfiguration::LoadFeatureDataFromTrainingLibraries (bool^ changesMadeToTrainingLibraries)
Definition at line 252 of file PicesTrainingConfiguration.cpp.
References MLL::TrainingConfiguration2::LoadFeatureDataFromTrainingLibraries(), PicesInterface::PicesRunLog::Log(), and MLL::DuplicateImages::PurgeDuplicates().
String ^ PicesInterface::PicesTrainingConfiguration::LoadLogStream () inline
Definition at line 48 of file PicesTrainingConfiguration.h.
String PicesInterface::PicesTrainingConfiguration::ModelName ()
Definition at line 181 of file PicesTrainingConfiguration.cpp.
References MLL::TrainingConfiguration2::ConfigFileNameSpecified(), PicesInterface::PicesKKStr::KKStrToSystenStr(), and KKU::osGetRootNameWithExtension().
uint PicesInterface::PicesTrainingConfiguration::NumHierarchialLevels ()
Definition at line 201 of file PicesTrainingConfiguration.cpp.
References MLL::TrainingConfiguration2::NumHierarchialLevels().
PicesClass PicesInterface::PicesTrainingConfiguration::OtherClass ()
Definition at line 236 of file PicesTrainingConfiguration.cpp.
References PicesInterface::PicesClassList::GetUniqueClass(), and MLL::TrainingConfiguration2::OtherClass().
String PicesInterface::PicesTrainingConfiguration::RootDir ()
Definition at line 174 of file PicesTrainingConfiguration.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr(), and MLL::TrainingConfiguration2::RootDir().
void PicesInterface::PicesTrainingConfiguration::Save (String^ configFileName)
Definition at line 324 of file PicesTrainingConfiguration.cpp.
References MLL::TrainingConfiguration2::Save(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
PicesTrainingClassList PicesInterface::PicesTrainingConfiguration::TrainingClasses ()
Definition at line 305 of file PicesTrainingConfiguration.cpp.
References MLL::TrainingConfiguration2::TrainingClasses().
System::Boolean PicesInterface::PicesTrainingConfiguration::Valid ()
Definition at line 193 of file PicesTrainingConfiguration.cpp.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesTrainingConfiguration.h
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesTrainingConfiguration.cpp