Pices: PicesInterface::PicesSipperCruise Class Reference
PicesInterface::PicesSipperCruise Class Reference
#include <PicesSipperCruise.h>
Public Member Functions
PicesSipperCruise ()
PicesSipperCruise (SipperCruisePtr _cruise)
virtual String^ ToString () override
SipperCruisePtr UnmanagedSipperCruise ()
Static Public Member Functions
static String^ ValidateCruiseName (String^ _cruiseName)
Protected Member Functions
!PicesSipperCruise ()
Properties
String^ CruiseName [get, set]
System::DateTime DateEnd [get, set]
System::DateTime DateStart [get, set]
String^ Description [get, set]
String^ Location [get, set]
String^ Objective [get, set]
String^ Principal [get, set]
String^ ResearchOrg [get, set]
String^ ShipName [get, set]
Detailed Description
Definition at line 20 of file PicesSipperCruise.h.
Constructor & Destructor Documentation
PicesSipperCruise::PicesSipperCruise ()
Definition at line 29 of file PicesSipperCruise.cpp.
PicesSipperCruise::PicesSipperCruise (SipperCruisePtr _cruise)
Definition at line 37 of file PicesSipperCruise.cpp.
PicesSipperCruise::!PicesSipperCruise () protected
Definition at line 45 of file PicesSipperCruise.cpp.
Member Function Documentation
String PicesSipperCruise::ToString () override virtual
Definition at line 118 of file PicesSipperCruise.cpp.
References CruiseName, and DateStart.
SipperCruisePtr PicesInterface::PicesSipperCruise::UnmanagedSipperCruise () inline
Definition at line 34 of file PicesSipperCruise.h.
Referenced by PicesInterface::PicesSipperStation::PicesSipperStation(), PicesInterface::PicesDataBase::SipperCruiseInsert(), and PicesInterface::PicesDataBase::SipperCruiseUpdate().
String PicesSipperCruise::ValidateCruiseName (String^ _cruiseName) static
Definition at line 108 of file PicesSipperCruise.cpp.
References KKU::KKStr::Empty(), PicesInterface::PicesKKStr::KKStrToSystenStr(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Property Documentation
String^ PicesInterface::PicesSipperCruise::CruiseName get set
Definition at line 36 of file PicesSipperCruise.h.
Referenced by SipperFile.CruiseDialog::CruiseDialog(), PicesInterface::PicesSipperCruiseList::LookUpByName(), ToString(), and SipperFile.TreeNodeCruise::ToString().
System:: DateTime PicesInterface::PicesSipperCruise::DateEnd get set
Definition at line 41 of file PicesSipperCruise.h.
System:: DateTime PicesInterface::PicesSipperCruise::DateStart get set
Definition at line 40 of file PicesSipperCruise.h.
Referenced by ToString(), and SipperFile.TreeNodeCruise::ToString().
String^ PicesInterface::PicesSipperCruise::Description get set
Definition at line 38 of file PicesSipperCruise.h.
Referenced by SipperFile.TreeNodeCruise::ToString().
String^ PicesInterface::PicesSipperCruise::Location get set
Definition at line 43 of file PicesSipperCruise.h.
String^ PicesInterface::PicesSipperCruise::Objective get set
Definition at line 44 of file PicesSipperCruise.h.
String^ PicesInterface::PicesSipperCruise::Principal get set
Definition at line 45 of file PicesSipperCruise.h.
String^ PicesInterface::PicesSipperCruise::ResearchOrg get set
Definition at line 46 of file PicesSipperCruise.h.
String^ PicesInterface::PicesSipperCruise::ShipName get set
Definition at line 37 of file PicesSipperCruise.h.
Referenced by SipperFile.TreeNodeCruise::ToString().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesSipperCruise.h
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesSipperCruise.cpp