Pices: KKU::Configuration::ConfSectionList Class Reference
KKU::Configuration::ConfSectionList Class Reference
Public Member Functions
ConfSectionList ()
void AddConfSection (ConfSectionPtr section)
void AddConfSection (const KKStr &_name, int32 _lineNum)
ConfSectionPtr LookUp (const KKStr &_name)
int32 MemoryConsumedEstimated () const
Detailed Description
Definition at line 234 of file Configuration.cpp.
Constructor & Destructor Documentation
KKU::Configuration::ConfSectionList::ConfSectionList () inline
Definition at line 237 of file Configuration.cpp.
Member Function Documentation
void KKU::Configuration::ConfSectionList::AddConfSection (ConfSectionPtr section) inline
Definition at line 269 of file Configuration.cpp.
Referenced by KKU::Configuration::Configuration(), and KKU::Configuration::LoadFile().
void KKU::Configuration::ConfSectionList::AddConfSection (const KKStr & _name, int32 _lineNum) inline
Definition at line 275 of file Configuration.cpp.
ConfSectionPtr KKU::Configuration::ConfSectionList::LookUp (const KKStr & _name) inline
Definition at line 250 of file Configuration.cpp.
References KKU::KKStr::EqualIgnoreCase(), and KKU::Configuration::ConfSection::Name().
Referenced by KKU::Configuration::GetSetting(), KKU::Configuration::NumOfSettings(), KKU::Configuration::SectionDefined(), and KKU::Configuration::SettingName().
int32 KKU::Configuration::ConfSectionList::MemoryConsumedEstimated () const inline
Definition at line 240 of file Configuration.cpp.
Referenced by KKU::Configuration::MemoryConsumedEstimated().
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Configuration.cpp