Pices: KKU::MsgQueue Class Reference
KKU::MsgQueue Class Reference
Will manage a buffer that will allow multiple threads to add and remove messages to a queue.
#include <MsgQueue.h>
Public Types
typedef MsgQueue * MsgQueuePtr
Public Member Functions
MsgQueue (const KKStr &_name)
~MsgQueue ()
void AddMsg (KKStrPtr msg)
Take ownership of 'msg' and add to end of the queue.
void AddMsg (const KKStr &msg)
KKStrPtr GetCopyOfLastMsg ()
Returns a duplicate of the last string added to the message queue.
KKStrPtr GetNextMsg ()
Removes from the queue the oldest message added to the queue that has not been removed.
int32 MemoryConsumedEstimated ()
Returns an estimate of the amount of memory consumed in bytes by this instance.
Detailed Description
Will manage a buffer that will allow multiple threads to add and remove messages to a queue.
A 'GoalKeepeer' object 'gateKeeper' will be used to enforce integrity in the Multi-Threaded environment. It will guarantee that only one thread at a time can access the Queue.
Definition at line 19 of file MsgQueue.h.
Member Typedef Documentation
typedef MsgQueue* KKU::MsgQueue::MsgQueuePtr
Definition at line 22 of file MsgQueue.h.
Constructor & Destructor Documentation
MsgQueue::MsgQueue (const KKStr & _name)
Definition at line 28 of file MsgQueue.cpp.
References KKU::GoalKeeper::MemoryConsumedEstimated().
MsgQueue::~MsgQueue ()
Definition at line 40 of file MsgQueue.cpp.
Member Function Documentation
void MsgQueue::AddMsg (KKStrPtr msg)
Take ownership of 'msg' and add to end of the queue.
Parameters
[in] msg Pointer to message that is to be added to end of queue. The caller will pass ownership of this string to this instance of MsgQueue.Taking ownership of 'msg'
Definition at line 56 of file MsgQueue.cpp.
References KKU::GoalKeeper::EndBlock(), KKU::endl(), KKU::KKStr::Len(), and KKU::GoalKeeper::StartBlock().
Referenced by ImageExtractionManager::ImageExtractionThread::AddMsg(), KKU::KKThread::AddMsg(), and KKU::RunLog::Append().
void MsgQueue::AddMsg (const KKStr & msg)
Definition at line 74 of file MsgQueue.cpp.
References KKU::GoalKeeper::EndBlock(), KKU::KKStr::Len(), and KKU::GoalKeeper::StartBlock().
KKStrPtr MsgQueue::GetCopyOfLastMsg ()
Returns a duplicate of the last string added to the message queue.
This will not effect the current copy of the message queue. he returned string will be owned by the caller who will be responsible for deleting it.
Definition at line 113 of file MsgQueue.cpp.
References KKU::GoalKeeper::EndBlock(), and KKU::GoalKeeper::StartBlock().
KKStrPtr MsgQueue::GetNextMsg ()
Removes from the queue the oldest message added to the queue that has not been removed.
The caller will get ownership of the string and be responsible for deleting it.
Definition at line 84 of file MsgQueue.cpp.
References KKU::GoalKeeper::EndBlock(), KKU::KKStr::Len(), and KKU::GoalKeeper::StartBlock().
int32 MsgQueue::MemoryConsumedEstimated ()
Returns an estimate of the amount of memory consumed in bytes by this instance.
This will help managed objects keep track of how much memory they are using in the unmanaged world.
Definition at line 102 of file MsgQueue.cpp.
References KKU::GoalKeeper::EndBlock(), and KKU::GoalKeeper::StartBlock().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/MsgQueue.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/MsgQueue.cpp