Pices: PicesCommander.PlanktonDepthStatisticsLoader Class Reference
PicesCommander.PlanktonDepthStatisticsLoader Class Reference
Public Member Functions
PlanktonDepthStatisticsLoader (PicesDataBaseImageGroup _selectedImageGroup, String _cruiseName, String _stationName, String _deploymentNum, String _sipperFileName, float _depthIncrements, PicesClass _mlClass, char _classKeyToUse, float _probMin, float _probMax, int _sizeMin, int _sizeMax)
delegate void AlertCompletion (PlanktonDepthStatisticsLoader sender)
void CancelLoad ()
void CancelLoadWait (int maxMilliSecsToWait)
void CleanUpMemory ()
uint[] GetStatsAlreadyLoaded ()
uint[] GetStatsAlreadyLoadedIfNew ()
String Status ()
Properties
bool CancelRequested [get]
AlertCompletion CompletionEvent [get, set]
String CurSipperFileName [get]
bool DoneLoading [get]
uint ImageCountTotal [get]
bool LoaderThreadRuning [get]
int SipperFilesCount [get]
int SipperFilesLoaded [get]
PicesVolumeSampledStatList VolumeWaterSampled [get]
Detailed Description
Definition at line 19 of file PlanktonDepthStatisticsLoader.cs.
Constructor & Destructor Documentation
PicesCommander.PlanktonDepthStatisticsLoader.PlanktonDepthStatisticsLoader (PicesDataBaseImageGroup _selectedImageGroup, String _cruiseName, String _stationName, String _deploymentNum, String _sipperFileName, float _depthIncrements, PicesClass _mlClass, char _classKeyToUse, float _probMin, float _probMax, int _sizeMin, int _sizeMax) inline
Definition at line 75 of file PlanktonDepthStatisticsLoader.cs.
Member Function Documentation
delegate void PicesCommander.PlanktonDepthStatisticsLoader.AlertCompletion (PlanktonDepthStatisticsLoader sender)
void PicesCommander.PlanktonDepthStatisticsLoader.CancelLoad () inline
Definition at line 124 of file PlanktonDepthStatisticsLoader.cs.
Referenced by PicesCommander.PlanktonDepthStatisticsLoader.CancelLoadWait().
void PicesCommander.PlanktonDepthStatisticsLoader.CancelLoadWait (int maxMilliSecsToWait) inline
Definition at line 131 of file PlanktonDepthStatisticsLoader.cs.
References PicesCommander.PlanktonDepthStatisticsLoader.CancelLoad().
Referenced by PicesCommander.PlanktonDepthStatisticsLoader.CleanUpMemory().
void PicesCommander.PlanktonDepthStatisticsLoader.CleanUpMemory () inline
Definition at line 115 of file PlanktonDepthStatisticsLoader.cs.
References PicesCommander.PlanktonDepthStatisticsLoader.CancelLoadWait().
uint [] PicesCommander.PlanktonDepthStatisticsLoader.GetStatsAlreadyLoaded () inline
Definition at line 185 of file PlanktonDepthStatisticsLoader.cs.
References PicesInterface::PicesGoalKeeper.EndBlock(), PicesInterface::PicesGoalKeeper.StartBlock(), and x.
uint [] PicesCommander.PlanktonDepthStatisticsLoader.GetStatsAlreadyLoadedIfNew () inline
Definition at line 203 of file PlanktonDepthStatisticsLoader.cs.
References PicesInterface::PicesGoalKeeper.EndBlock(), PicesInterface::PicesGoalKeeper.StartBlock(), and x.
String PicesCommander.PlanktonDepthStatisticsLoader.Status () inline
Definition at line 158 of file PlanktonDepthStatisticsLoader.cs.
References PicesInterface::PicesGoalKeeper.EndBlock(), and PicesInterface::PicesGoalKeeper.StartBlock().
Property Documentation
bool PicesCommander.PlanktonDepthStatisticsLoader.CancelRequested get
Definition at line 62 of file PlanktonDepthStatisticsLoader.cs.
AlertCompletion PicesCommander.PlanktonDepthStatisticsLoader.CompletionEvent get set
Definition at line 64 of file PlanktonDepthStatisticsLoader.cs.
String PicesCommander.PlanktonDepthStatisticsLoader.CurSipperFileName get
Definition at line 63 of file PlanktonDepthStatisticsLoader.cs.
bool PicesCommander.PlanktonDepthStatisticsLoader.DoneLoading get
Definition at line 65 of file PlanktonDepthStatisticsLoader.cs.
uint PicesCommander.PlanktonDepthStatisticsLoader.ImageCountTotal get
Definition at line 66 of file PlanktonDepthStatisticsLoader.cs.
bool PicesCommander.PlanktonDepthStatisticsLoader.LoaderThreadRuning get
Definition at line 67 of file PlanktonDepthStatisticsLoader.cs.
int PicesCommander.PlanktonDepthStatisticsLoader.SipperFilesCount get
Definition at line 69 of file PlanktonDepthStatisticsLoader.cs.
int PicesCommander.PlanktonDepthStatisticsLoader.SipperFilesLoaded get
Definition at line 70 of file PlanktonDepthStatisticsLoader.cs.
PicesVolumeSampledStatList PicesCommander.PlanktonDepthStatisticsLoader.VolumeWaterSampled get
Definition at line 72 of file PlanktonDepthStatisticsLoader.cs.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/PicesCommander/PlanktonDepthStatisticsLoader.cs