Pices: SipperDiskUtilities.MasterBootRecord Class Reference
SipperDiskUtilities.MasterBootRecord Class Reference
Public Member Functions
MasterBootRecord (byte[] buffer, ref int nextIndex)
void Dispose ()
Int64 GetPartitionSectorByteOffset (int partitionNum)
Int64 GetSipperDirectoryByteOffset ()
PartitionTableEntry GetSipperPartitionTableEntry ()
Static Public Member Functions
static int BuffSpaceNeeded ()
Properties
long SipperPartitionBeginSector [get]
Detailed Description
Definition at line 8 of file MasterBootRecord.cs.
Constructor & Destructor Documentation
SipperDiskUtilities.MasterBootRecord.MasterBootRecord (byte[] buffer, ref int nextIndex) inline
Definition at line 34 of file MasterBootRecord.cs.
References x.
Member Function Documentation
static int SipperDiskUtilities.MasterBootRecord.BuffSpaceNeeded () inline static
Definition at line 59 of file MasterBootRecord.cs.
References SipperDiskUtilities.PartitionTable.BuffSpaceNeeded().
void SipperDiskUtilities.MasterBootRecord.Dispose () inline
Definition at line 52 of file MasterBootRecord.cs.
Referenced by SipperDiskUtilities.SipperDisk.Dispose().
Int64 SipperDiskUtilities.MasterBootRecord.GetPartitionSectorByteOffset (int partitionNum) inline
Definition at line 76 of file MasterBootRecord.cs.
References SipperDiskUtilities.PartitionTable.GetPartitionSectorByteOffset().
Referenced by SipperDiskUtilities.SipperDisk.AreWeTheSameDrive().
Int64 SipperDiskUtilities.MasterBootRecord.GetSipperDirectoryByteOffset () inline
Definition at line 85 of file MasterBootRecord.cs.
References SipperDiskUtilities.PartitionTable.GetSipperDirectoryByteOffset().
Referenced by SipperDiskUtilities.SipperDisk.ResetSipperDirectory().
PartitionTableEntry SipperDiskUtilities.MasterBootRecord.GetSipperPartitionTableEntry () inline
Definition at line 67 of file MasterBootRecord.cs.
References SipperDiskUtilities.PartitionTable.GetSipperPartitionTableEntry().
Referenced by SipperDiskUtilities.SipperDisk.GetSipperPartitionTableEntry(), and SipperDiskUtilities.SipperDisk.ResetSipperDirectory().
Property Documentation
long SipperDiskUtilities.MasterBootRecord.SipperPartitionBeginSector get
Definition at line 19 of file MasterBootRecord.cs.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperDiskUtilities/MasterBootRecord.cs