Pices: SipperHardware::InstrumentDataReport Class Reference
SipperHardware::InstrumentDataReport Class Reference
#include <InstrumentDataReport.h>
Public Types
typedef InstrumentDataReport * InstrumentDataReportPtr
typedef KKU::int32 int32
typedef KKU::uint32 uint32
Public Member Functions
InstrumentDataReport (InstrumentDataManagerPtr _manager, const KKStr &_reportDir, bool _text, int32 _instrumentId, bool _useReportWithLineNumbers)
virtual ~InstrumentDataReport ()
const KKStr & CurTextLine ()
const KKStr & LastTextLine ()
virtual void ReportInstrumentData (uint32 curScanLine, uchar sensorData)
Static Public Member Functions
static InstrumentDataReportPtr CreateInstrumentDataReport (InstrumentDataManagerPtr _manager, const KKStr &_reportDir, bool _text, int32 _instrumentId)
A virtual Constructor for InstrumentDataReport.
Protected Member Functions
KKStr InstrumentName ()
Protected Attributes
KKStr curTextLine
Used where "text == true", Every time a character is read via 'ReportInstrumentData' will append to end of string.
int32 instrumentId
uint32 lastScanLineReported
KKStr lastTextLine
Used where "text == true", will keep an instance of last complete text line read.
InstrumentDataManagerPtr manager
ofstream report
KKStr reportFileName
KKStr reportFileNameWLN
ofstream reportWLN
bool text
bool useReportWithLineNumbers
Static Protected Attributes
static const char * InstrumentNames []
Detailed Description
Definition at line 15 of file InstrumentDataReport.h.
Member Typedef Documentation
typedef InstrumentDataReport* SipperHardware::InstrumentDataReport::InstrumentDataReportPtr
Definition at line 18 of file InstrumentDataReport.h.
typedef KKU::int32 SipperHardware::InstrumentDataReport::int32
Definition at line 19 of file InstrumentDataReport.h.
typedef KKU::uint32 SipperHardware::InstrumentDataReport::uint32
Definition at line 20 of file InstrumentDataReport.h.
Constructor & Destructor Documentation
InstrumentDataReport::InstrumentDataReport (InstrumentDataManagerPtr _manager, const KKStr & _reportDir, bool _text, int32 _instrumentId, bool _useReportWithLineNumbers)
Definition at line 61 of file InstrumentDataReport.cpp.
References KKU::KKStr::Empty(), InstrumentName(), KKU::osAddSlash(), report, reportFileName, reportFileNameWLN, reportWLN, KKU::KKStr::Str(), text, and useReportWithLineNumbers.
Referenced by CreateInstrumentDataReport().
InstrumentDataReport::~InstrumentDataReport () virtual
Definition at line 91 of file InstrumentDataReport.cpp.
References report, and reportWLN.
Member Function Documentation
InstrumentDataReportPtr InstrumentDataReport::CreateInstrumentDataReport (InstrumentDataManagerPtr _manager, const KKStr & _reportDir, bool _text, int32 _instrumentId) static
A virtual Constructor for InstrumentDataReport.
Parameters
[in] _reportDir Directory where report file is to be placed.
[in] text,Set to true = text data, false = binary data.
[in] InstrumentID,Sensor/Instrument ID
In the future as different types of instruments are introduced we can make specialized versions of InstrumentDataReport.
Definition at line 106 of file InstrumentDataReport.cpp.
References SipperHardware::Instrument::CreateInstrumentDataReporter(), SipperHardware::InstrumentDataManager::HeaderRec(), InstrumentDataReport(), and SipperHardware::SipperHeaderRec::SerialPortAssignment().
Referenced by SipperHardware::InstrumentDataManager::ReportInstrumentData().
const KKStr& SipperHardware::InstrumentDataReport::CurTextLine () inline
Definition at line 32 of file InstrumentDataReport.h.
KKStr InstrumentDataReport::InstrumentName () protected
Definition at line 182 of file InstrumentDataReport.cpp.
References instrumentId, InstrumentNames, KKU::StrFormatInt(), and x.
Referenced by InstrumentDataReport().
const KKStr& SipperHardware::InstrumentDataReport::LastTextLine () inline
Definition at line 33 of file InstrumentDataReport.h.
void InstrumentDataReport::ReportInstrumentData (uint32 curScanLine, uchar sensorData) virtual
Reimplemented in SipperHardware::InstrumentDataGPS, SipperHardware::InstrumentDataPitchAndRoll, SipperHardware::InstrumentDataCTDplus, SipperHardware::InstrumentDataUserMsgs, and SipperHardware::InstrumentDataBatteryMeter.
Definition at line 198 of file InstrumentDataReport.cpp.
References KKU::KKStr::Append(), curTextLine, KKU::endl(), lastScanLineReported, lastTextLine, KKU::KKStr::Len(), report, reportWLN, text, and useReportWithLineNumbers.
Referenced by SipperHardware::InstrumentDataManager::ReportInstrumentData().
Member Data Documentation
KKStr SipperHardware::InstrumentDataReport::curTextLine protected
Used where "text == true", Every time a character is read via 'ReportInstrumentData' will append to end of string.
When a '
' is processed will move to 'lastTextLine' and then set to empty.
Definition at line 63 of file InstrumentDataReport.h.
Referenced by ReportInstrumentData().
int32 SipperHardware::InstrumentDataReport::instrumentId protected
Definition at line 68 of file InstrumentDataReport.h.
Referenced by InstrumentName().
const char * InstrumentDataReport::InstrumentNames static protected
Initial value:
=
{
  "Synchronization_pulse",
  "Real-Time_Clock",
  "FIFO_Buffer_Status",
  "FireWire_Error",
  "Internal_Temperature",
  "Internal_Humidity",
  "User_Text_Message",
  "Other_Internal_Status",
  "CTD",
  "GPS",
  "Flow_meter_1",
  "Flow_meter_2",
  "OPC",
  "Fluorometer",
  "Transmissometer",
  "Camera_messages",
  "Serisl Port 0",
  "Serisl Port 1",
  "Serisl Port 2",
  "Serisl Port 3",
  NULL
}
Definition at line 61 of file InstrumentDataReport.h.
Referenced by InstrumentName().
uint32 SipperHardware::InstrumentDataReport::lastScanLineReported protected
Definition at line 70 of file InstrumentDataReport.h.
Referenced by ReportInstrumentData().
KKStr SipperHardware::InstrumentDataReport::lastTextLine protected
Used where "text == true", will keep an instance of last complete text line read.
Will come from curText line when ever a '
' character is read.
Definition at line 72 of file InstrumentDataReport.h.
Referenced by ReportInstrumentData().
InstrumentDataManagerPtr SipperHardware::InstrumentDataReport::manager protected
Definition at line 77 of file InstrumentDataReport.h.
Referenced by SipperHardware::InstrumentDataBatteryMeter::ProcessBatteryData(), and SipperHardware::InstrumentDataFlowMeter1::ReportInstrumentData().
ofstream SipperHardware::InstrumentDataReport::report protected
Definition at line 80 of file InstrumentDataReport.h.
Referenced by InstrumentDataReport(), SipperHardware::InstrumentDataBatteryMeter::ReportInstrumentData(), SipperHardware::InstrumentDataCTDplus::ReportInstrumentData(), SipperHardware::InstrumentDataUserMsgs::ReportInstrumentData(), SipperHardware::InstrumentDataPitchAndRoll::ReportInstrumentData(), SipperHardware::InstrumentDataFlowMeter1::ReportInstrumentData(), SipperHardware::InstrumentDataGPS::ReportInstrumentData(), ReportInstrumentData(), SipperHardware::InstrumentDataBatteryMeter::~InstrumentDataBatteryMeter(), SipperHardware::InstrumentDataCTDplus::~InstrumentDataCTDplus(), SipperHardware::InstrumentDataGPS::~InstrumentDataGPS(), SipperHardware::InstrumentDataPitchAndRoll::~InstrumentDataPitchAndRoll(), ~InstrumentDataReport(), and SipperHardware::InstrumentDataUserMsgs::~InstrumentDataUserMsgs().
KKStr SipperHardware::InstrumentDataReport::reportFileName protected
Definition at line 78 of file InstrumentDataReport.h.
Referenced by InstrumentDataReport().
KKStr SipperHardware::InstrumentDataReport::reportFileNameWLN protected
Definition at line 79 of file InstrumentDataReport.h.
Referenced by InstrumentDataReport().
ofstream SipperHardware::InstrumentDataReport::reportWLN protected
Definition at line 81 of file InstrumentDataReport.h.
Referenced by InstrumentDataReport(), ReportInstrumentData(), and ~InstrumentDataReport().
bool SipperHardware::InstrumentDataReport::text protected
Definition at line 82 of file InstrumentDataReport.h.
Referenced by SipperHardware::InstrumentDataFlowMeter1::InstrumentDataFlowMeter1(), InstrumentDataReport(), SipperHardware::InstrumentDataFlowMeter1::ReportInstrumentData(), and ReportInstrumentData().
bool SipperHardware::InstrumentDataReport::useReportWithLineNumbers protected
Definition at line 83 of file InstrumentDataReport.h.
Referenced by InstrumentDataReport(), and ReportInstrumentData().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/InstrumentDataReport.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/InstrumentDataReport.cpp