Pices: SipperFile.DepthPlot2 Class Reference
SipperFile.DepthPlot2 Class Reference
Summary description for DataWindow.
Public Member Functions
DepthPlot2 (SipperConfigRec _sipperConfigRec, InstrumentDataList _history, String _title)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Detailed Description
Summary description for DataWindow.
Definition at line 22 of file DepthPlot2.cs.
Constructor & Destructor Documentation
SipperFile.DepthPlot2.DepthPlot2 (SipperConfigRec _sipperConfigRec, InstrumentDataList _history, String _title) inline
Definition at line 91 of file DepthPlot2.cs.
References PicesInterface::OSservices.AddSlash(), SipperFile.DepthPlot2Parameters.AssignSeriesToPlot(), SipperFile.InstrumentDataList.CalcMinMaxValues(), SipperFile.InstrumentData.FieldName(), SipperFile.InstrumentDataList.MaxValues(), SipperFile.InstrumentDataList.MinValues(), SipperFile.InstrumentData.NumDataFields(), SipperFile.InstrumentData.NumOfFields(), PicesInterface::PicesSipperVariables.PicesConfigurationDirectory(), SipperFile.DepthPlot2Parameters.UpdateMinMaxValues(), and x.
Member Function Documentation
override void SipperFile.DepthPlot2.Dispose (bool disposing) inline protected
Clean up any resources being used.
Definition at line 220 of file DepthPlot2.cs.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperFile/DepthPlot2.cs