Pices: MLL::FeatureNumList Class Reference
MLL::FeatureNumList Class Reference
Keeps track of selected features.
#include <FeatureNumList.h>
Public Types
typedef FeatureNumList * FeatureNumListPtr
enum FeatureSelectionType { IncludeFeatureNums, ExcludeFeatureNums }
typedef KKU::int32 int32
typedef KKU::uint16 uint16
typedef KKU::uint32 uint32
Public Member Functions
FeatureNumList (FileDescPtr _fileDesc)
FeatureNumList (FileDescPtr _fileDesc, const BitString &bitString)
Constructs a new 'FeatureNumList' instance using 'bitString' to select which features will be selected.
FeatureNumList (FileDescPtr _fileDesc, const KKStr &_featureListStr, bool &_valid)
Constructs a instance of 'FeatureNumList' where '_featureListStr' will consist of a list of features that are to be selected.
FeatureNumList (FileDescPtr _fileDesc, FeatureSelectionType _selectionType, const KKStr &_featureListStr, bool &_valid)
Constructs a instance of 'FeatureNumList' where '_featureListStr' provides a list of of features numbers that are to be included or excluded depending on '_selectionType'.
FeatureNumList (const FeatureNumList &featureNumList)
Copy constructor.
~FeatureNumList ()
void AddFeature (uint16 featureNum)
Adds 'featureNum' to the list of selected features; if it is already selected nothing happens.
bool AllFeaturesSelected () const
Returns true if all features are selected.
int32 Compare (const FeatureNumList &_features) const
Compare with another featureNumList returning -1, 0, and 1 indicating less-than, equal, or greater-than.
FeatureNumList Complement () const
Perform a complement of selected features.
uint16 * CreateFeatureNumArray () const
Allocates a array of int32's that is a copy of FeatureNums.
void ExtractFeatureNumsFromStr (KKStr featureListStr, bool &valid)
Will select the features specified in "featureListStr".
MLL::AttributeType FeatureAttributeType (int32 idx) const
const uint16 * FeatureNums () const
FileDescPtr FileDesc () const
bool InList (uint16 featureNum) const
Indicates whether '_featureNum' is selected.
bool IsSubSet (const FeatureNumList &z)
Returns true if 'z' is a subset of this instance.
void Load (const KKStr &_fileName, bool &_successful, RunLog &_log)
int32 MemoryConsumedEstimated () const
int32 NumOfFeatures () const
int32 NumSelFeatures () const
FeatureNumList operator* (const FeatureNumList &rightSide) const
FeatureNumList operator+ (const FeatureNumList &rightSide) const
Returns new FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList operator+ (uint16 rightSide) const
Returns new FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList & operator+= (const FeatureNumList &rightSide)
Returns this FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList & operator+= (uint16 featureNum)
Returns this FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList operator- (const FeatureNumList &rightSide) const
Removes features that are selected in 'rightSide' from this instance and returns the result.
FeatureNumList operator- (uint16 rightSide) const
Returns this instance with the feature specified by 'rightSide' removed.
FeatureNumList & operator-= (uint16 rightSide)
Remove the feature specified by 'rightSide' from this instance.
bool operator< (const FeatureNumList &_features) const
Indicates if the Left FeatureNumList instances is less than the right one.
FeatureNumList & operator= (const FeatureNumList &_features)
FeatureNumList & operator= (const FeatureNumListPtr _features)
bool operator== (const FeatureNumList &_features) const
Indicates if the two FeatureNumLiost instances have the same features selected.
bool operator> (const FeatureNumList &_features) const
Indicates if the Left FeatureNumList instances is greater than the right one.
uint16 operator[] (int32 idx) const
Allows you to access list of selected features like an array.
FeatureNumListPtr RandomlySelectFeatures (int32 numToKeep) const
Generates a new FeatureNumList object that will select at random 'numToKeep' features from this instance.
void Save (const KKStr &_fileName, bool &_successful, RunLog &_log)
void Save (std::ostream &o)
void SetAllFeatures ()
Selects all features except those flagged as 'IgnoreAttribute' in the associated FileDesc.
bool Test (uint16 _featureNum) const
Indicates whether feature '_featureNum' is selected.
void ToBitString (BitString &bitStr) const
KKStr ToCommaDelStr () const
KKStr ToHexString () const
KKStr ToString () const
Returns comma delimited list of all features selected; will make use of range specification.
void UnSet ()
Turns off all features so that no feature is selected.
void UnSet (uint16 featureNum)
Turns off specified feature 'featureNum'.
Static Public Member Functions
static FeatureNumList AllFeatures (FileDescPtr fileDesc)
Create a FeatureNumList with all features selected, except ones flagged as IgnoreAttribute in 'fileDesc'.
Detailed Description
Keeps track of selected features.
Used by SVMModel and the newer 'Model', 'ModelParam' based classes. Each instance of this class will have an associated 'FileDesc' instance. It is meant to keep track of selected features from that instance('FileDesc').
This class is meant to work with both the FeaureVector, Model, and ModelParm based classes. This will allow us to select specific features from the FeatureVector instances that are to be used.
At no time are feature numbers that are out of range of the associated FileDesc instance to be selected.
Two of the constructors allow you to specify a list of features in a string. The list can consist of single features and/or ranges of features. Ranges of features are specified by using the dash('-') character between two numbers. The comma(',') character will be used as a separator. "All" specifies all are to be selected except those that are flagged as 'IgnoreAttribute' in the associated FileDesc instance. The list should be in ascending order.
Example Strings:
  "1,2,3,10,20"    Selects [1,2,3,10, 20].
  "1,4-7,9-12,13"  Selects [1,4,,5,6,7,9,10,11,12,13]
  "All"            Selects all features that '_fileDesc' includes accept
                   those that are flagged as 'IgnoreAttribute' in the
                   associated FileDesc instance.
Definition at line 57 of file FeatureNumList.h.
Member Typedef Documentation
typedef FeatureNumList* MLL::FeatureNumList::FeatureNumListPtr
Definition at line 60 of file FeatureNumList.h.
typedef KKU::int32 MLL::FeatureNumList::int32
Definition at line 63 of file FeatureNumList.h.
typedef KKU::uint16 MLL::FeatureNumList::uint16
Definition at line 62 of file FeatureNumList.h.
typedef KKU::uint32 MLL::FeatureNumList::uint32
Definition at line 64 of file FeatureNumList.h.
Member Enumeration Documentation
enum MLL::FeatureNumList::FeatureSelectionType
Enumerator
IncludeFeatureNums
ExcludeFeatureNums
Definition at line 66 of file FeatureNumList.h.
Constructor & Destructor Documentation
FeatureNumList::FeatureNumList (FileDescPtr _fileDesc)
Definition at line 25 of file FeatureNumList.cpp.
References KKU::endl(), MLL::FileDesc::NumOfFields(), and KKU::osWaitForEnter().
MLL::FeatureNumList::FeatureNumList (FileDescPtr _fileDesc, const BitString & bitString)
Constructs a new 'FeatureNumList' instance using 'bitString' to select which features will be selected.
For each bit position in 'bitString' that is set to '1' the corresponding feature will be selected. So the bit string '0110111' which consists of bits 0, 1, 2, 5, and 6 will cause the features selected to be set to (0, 1, 2, 4, 6).
. This is a useful constructor when dealing with datasets that have a large number of features such as DNA based datasets.
Parameters
[in] _fileDesc Description of the feature data.
[in] bitString A bit string that indicates which features are selected. Bits that are set to 1 indicate that the corresponding feature is selected.
MLL::FeatureNumList::FeatureNumList (FileDescPtr _fileDesc, const KKStr & _featureListStr, bool & _valid)
Constructs a instance of 'FeatureNumList' where '_featureListStr' will consist of a list of features that are to be selected.
The list can consist of single features and/or ranges of features. Ranges of features are specified by using the dash('-') character between two numbers. The comma(',') character will be used as a separator. "All" specifies all ate to be selected except those that are flagged as 'IgnoreAttribute' in the associated FileDesc instance. The list should be in ascending order.
ex's:
  "1,2,3,10,20"    Selects [1,2,3,10, 20].
  "1,4-7,9-12,13"  Selects [1,4,,5,6,7,9,10,11,12,13]
  "All"            Selects all features that '_fileDesc' includes accept those that are
                   flagged as 'IgnoreAttribute' in the associated FileDesc instance.
See Also
ExtractFeatureNumsFromStr
Parameters
[in] _fileDesc FileDesc instance that the featureNumList is going to be based off of.
[in] _featureListStr String consisting of a list of features in ascending order that are to be selected.
[out] _valid Indicates if the format of '_featureListStr' was valid.
MLL::FeatureNumList::FeatureNumList (FileDescPtr _fileDesc, FeatureSelectionType _selectionType, const KKStr & _featureListStr, bool & _valid)
Constructs a instance of 'FeatureNumList' where '_featureListStr' provides a list of of features numbers that are to be included or excluded depending on '_selectionType'.
The list can consist of single features and/or ranges of features. Ranges of features are specified by using the ('-') character between two numbers. The comma(',') character will be used as a separator. The list should be in ascending order. The '_selectionType' parameter specifies weather we are going to select these features or exclude them form the list of all features(complement).
ex's:
  "1,2,3,10,20"    Selects [1,2,3,10, 20].
  "1,4-7,9-12,13"  Selects [1,4,,5,6,7,9,10,11,12,13]
  "All"            Selects all features that '_fileDesc' includes accept those that are
                   flagged as 'IgnoreAttribute' in the associated FileDesc instance.
Parameters
[in] _fileDesc FileDesc instance that the featureNumList is going to be based off of.
[in] _selectionType IncludeFeatureNums or ExcludeFeatureNums.
[in] _featureListStr String consisting of a list of features in ascending order that are to be selected.
[out] _valid Indicates if the format of '_featureListStr' was valid.
FeatureNumList::FeatureNumList (const FeatureNumList & featureNumList)
Copy constructor.
Definition at line 87 of file FeatureNumList.cpp.
References KKU::endl(), MLL::FileDesc::NumOfFields(), KKU::osWaitForEnter(), and x.
FeatureNumList::~FeatureNumList ()
Definition at line 210 of file FeatureNumList.cpp.
Member Function Documentation
void FeatureNumList::AddFeature (uint16 featureNum)
Adds 'featureNum' to the list of selected features; if it is already selected nothing happens.
Definition at line 336 of file FeatureNumList.cpp.
References KKU::endl(), InList(), MLL::FileDesc::NumOfFields(), and x.
Referenced by Complement(), ExtractFeatureNumsFromStr(), operator*(), operator+(), operator+=(), RandomlySelectFeatures(), and SetAllFeatures().
FeatureNumList FeatureNumList::AllFeatures (FileDescPtr fileDesc) static
Create a FeatureNumList with all features selected, except ones flagged as IgnoreAttribute in 'fileDesc'.
Definition at line 402 of file FeatureNumList.cpp.
Referenced by MLL::FeatureVectorList::AllFeatures(), MLL::FeatureFileIOPices::FeatureDataReSink(), and MLL::TrainingConfiguration2::GetFeatureNums().
bool FeatureNumList::AllFeaturesSelected () const
Returns true if all features are selected.
Definition at line 286 of file FeatureNumList.cpp.
References MLL::FileDesc::NumOfFields().
int32 FeatureNumList::Compare (const FeatureNumList & _features) const
Compare with another featureNumList returning -1, 0, and 1 indicating less-than, equal, or greater-than.
Definition at line 772 of file FeatureNumList.cpp.
References NumOfFeatures().
Referenced by operator<(), operator==(), and operator>().
FeatureNumList FeatureNumList::Complement () const
Perform a complement of selected features.
Definition at line 1121 of file FeatureNumList.cpp.
References AddFeature(), InList(), MLL::FileDesc::NumOfFields(), and x.
uint16 * FeatureNumList::CreateFeatureNumArray () const
Allocates a array of int32's that is a copy of FeatureNums.
The caller will own the array and is responsible for deleting it.
Returns
A dynamically allocated array that will consist of a list of selected features.
Definition at line 276 of file FeatureNumList.cpp.
void FeatureNumList::ExtractFeatureNumsFromStr (KKStr featureListStr, bool & valid)
Will select the features specified in "featureListStr".
The format is a comma delimited string, where each number represents a feature, ranges can be specified with a dash("-"). "All" will select all features that are not flagged as a 'IgnoreAttribute' in the associated FileDesc instance.
ex's:   String          Selected Features
       "1,2,3,10,20"    [1,2,3,10, 20].
       "1,4-7,9-12,23"  [1,4,5,6,7,9,10,11,12,23]
       "All"            Selects all features that '_fileDesc' includes accept those that are
                        flagged as 'IgnoreAttribute' in the associated FileDesc instance.
Definition at line 565 of file FeatureNumList.cpp.
References AddFeature(), KKU::KKStr::Empty(), KKU::KKStr::ExtractToken(), KKU::KKStr::ExtractTokenInt(), InList(), KKU::KKStr::LocateCharacter(), MLL::FileDesc::NumOfFields(), SetAllFeatures(), KKU::KKStr::Str(), KKU::KKStr::TrimLeft(), and KKU::KKStr::Upper().
Referenced by MLL::BinaryClassParms::CreateFromTabDelStr(), Load(), MLL::ModelParam::ParseCmdLine(), and MLL::SVMparam::ReadXML().
AttributeType FeatureNumList::FeatureAttributeType (int32 idx) const
Definition at line 1096 of file FeatureNumList.cpp.
References KKU::endl(), MLL::NULLAttribute, and MLL::FileDesc::Type().
const uint16* MLL::FeatureNumList::FeatureNums () const inline
Definition at line 188 of file FeatureNumList.h.
Referenced by MLL::UsfCasCor::_load_test_data(), MLL::UsfCasCor::_load_training_example(), and MLL::UsfCasCor::FilterOutExtremeExamples().
FileDescPtr MLL::FeatureNumList::FileDesc () const inline
Definition at line 190 of file FeatureNumList.h.
Referenced by operator*(), operator-(), and MLL::TrainingConfiguration2::SetFeatureNums().
bool FeatureNumList::InList (uint16 featureNum) const
Indicates whether '_featureNum' is selected.
Definition at line 439 of file FeatureNumList.cpp.
References x.
Referenced by AddFeature(), Complement(), ExtractFeatureNumsFromStr(), IsSubSet(), and Test().
bool FeatureNumList::IsSubSet (const FeatureNumList & z)
Returns true if 'z' is a subset of this instance.
Definition at line 423 of file FeatureNumList.cpp.
References InList(), and NumSelFeatures().
void FeatureNumList::Load (const KKStr & _fileName, bool & _successful, RunLog & _log)
Definition at line 643 of file FeatureNumList.cpp.
References KKU::endl(), ExtractFeatureNumsFromStr(), KKU::RunLog::Level(), MLL::FileDesc::NumOfFields(), KKU::osFOPEN(), and KKU::KKStr::Str().
int32 FeatureNumList::MemoryConsumedEstimated () const
Definition at line 217 of file FeatureNumList.cpp.
Referenced by MLL::ModelParam::MemoryConsumedEstimated(), MLL::BinaryClassParms::MemoryConsumedEstimated(), MLL::FeatureEncoder::MemoryConsumedEstimated(), and MLL::SVMparam::MemoryConsumedEstimated().
int32 MLL::FeatureNumList::NumOfFeatures () const inline
Definition at line 203 of file FeatureNumList.h.
Referenced by MLL::SVMparam::AvgMumOfFeatures(), MLL::ModelParam::AvgMumOfFeatures(), MLL::SVMparam::AvgNumOfFeatures(), Compare(), MLL::BitReduction::compress(), MLL::FeatureEncoder::FeatureEncoder(), MLL::UsfCasCor::FilterOutExtremeExamples(), MLL::UsfCasCor::load_namesfile(), MLL::ModelParam::NumOfFeaturesAfterEncoding(), MLL::SVMparam::NumOfFeaturesAfterEncoding(), operator-(), operator=(), CrossValidationApp::RandomlySelectedProcessResults(), CrossValidationApp::RandomlySelectedResults(), MLL::FeatureFileIORoberts::SaveFile(), MLL::FeatureFileIOUCI::SaveFile(), MLL::FeatureFileIOPices::SaveFile(), MLL::FeatureFileIOC45::SaveFile(), MLL::FeatureFileIOSparse::SaveFile(), MLL::ChainHashNode::SetSelectedFeatures(), and ToBitString().
int32 MLL::FeatureNumList::NumSelFeatures () const inline
Definition at line 205 of file FeatureNumList.h.
Referenced by MLL::UsfCasCor::_load_training_example(), MLL::SVMparam::AvgNumOfFeatures(), SVM289_MFS::Kernel::DotStatic(), SVM289_BFS::Kernel::DotStatic(), MLL::BinaryClassParmsList::FeatureCountNet(), IsSubSet(), SVM289_MFS::Kernel::k_function(), SVM289_BFS::Kernel::k_function(), SVM289_MFS::Kernel::Kernel(), and SVM289_BFS::Kernel::Kernel().
FeatureNumList FeatureNumList::operator* (const FeatureNumList & rightSide) const
Returns new instance that is the intersection of features.
Both FeatureNumList objects must be referening the same FileDesc instance otherwise an exception will be thrown.
Definition at line 846 of file FeatureNumList.cpp.
References AddFeature(), KKU::endl(), and FileDesc().
FeatureNumList FeatureNumList::operator+ (const FeatureNumList & rightSide) const
Returns new FeatureNumList that is a union of this instance and 'rightSide'.
Both FeatureNumList objects must be referening the same FileDesc instance otherwise an exception will be thrown.
Definition at line 889 of file FeatureNumList.cpp.
References AddFeature().
FeatureNumList FeatureNumList::operator+ (uint16 rightSide) const
Returns new FeatureNumList that is a union of this instance and 'rightSide'.
Both FeatureNumList objects must be referening the same FileDesc instance otherwise an exception will be thrown.
Definition at line 979 of file FeatureNumList.cpp.
References AddFeature(), KKU::endl(), and MLL::FileDesc::NumOfFields().
FeatureNumList & FeatureNumList::operator+= (const FeatureNumList & rightSide)
Returns this FeatureNumList that is a union of this instance and 'rightSide'.
Both FeatureNumList objects must be referening the same FileDesc instance otherwise an exception will be thrown.
Definition at line 903 of file FeatureNumList.cpp.
References Min(), and MLL::FileDesc::NumOfFields().
FeatureNumList & FeatureNumList::operator+= (uint16 featureNum)
Returns this FeatureNumList that is a union of this instance and 'rightSide'.
Both FeatureNumList objects must be referening the same FileDesc instance otherwise an exception will be thrown.
Definition at line 968 of file FeatureNumList.cpp.
References AddFeature().
FeatureNumList FeatureNumList::operator- (const FeatureNumList & rightSide) const
Removes features that are selected in 'rightSide' from this instance and returns the result.
Returns a new FeatureNumList instance that consists of the left side instance with the selected features in the right side removed.
Both FeatureNumList objects must be referening the same FileDesc instance otherwise an exception will be thrown.
Definition at line 1019 of file FeatureNumList.cpp.
References KKU::endl(), FileDesc(), NumOfFeatures(), UnSet(), and x.
FeatureNumList FeatureNumList::operator- (uint16 rightSide) const
Returns this instance with the feature specified by 'rightSide' removed.
Both FeatureNumList objects must be referening the same FileDesc instance otherwise an exception will be thrown.
Definition at line 997 of file FeatureNumList.cpp.
References KKU::endl(), MLL::FileDesc::NumOfFields(), and UnSet().
FeatureNumList & FeatureNumList::operator-= (uint16 rightSide)
Remove the feature specified by 'rightSide' from this instance.
Both FeatureNumList objects must be referening the same FileDesc instance otherwise an exception will be thrown.
Definition at line 1043 of file FeatureNumList.cpp.
References UnSet().
bool FeatureNumList::operator< (const FeatureNumList & _features) const
Indicates if the Left FeatureNumList instances is less than the right one.
See Also
compare
Definition at line 813 of file FeatureNumList.cpp.
References Compare().
FeatureNumList & FeatureNumList::operator= (const FeatureNumList & _features)
Definition at line 743 of file FeatureNumList.cpp.
References NumOfFeatures().
FeatureNumList & FeatureNumList::operator= (const FeatureNumListPtr _features)
Definition at line 764 of file FeatureNumList.cpp.
bool FeatureNumList::operator== (const FeatureNumList & _features) const
Indicates if the two FeatureNumLiost instances have the same features selected.
Definition at line 798 of file FeatureNumList.cpp.
References Compare().
bool FeatureNumList::operator> (const FeatureNumList & _features) const
Indicates if the Left FeatureNumList instances is greater than the right one.
See Also
compare
Definition at line 820 of file FeatureNumList.cpp.
References Compare().
uint16 FeatureNumList::operator[] (int32 _idx) const
Allows you to access list of selected features like an array.
Returns back the selected feature.
Parameters
[in] _idx The position in this instance that you want to return.
Returns
Selected feature at position '_idx'.
A FeatureNumList instance consists of an list of selected features. It is logically like an array of selected features that is the same length as the number of selected features.
Example code that scans the FeatureNumList object  'goodFeatures'
void  PrintSelectedFeatures (const FeatureNumList&  goodFeatures)
{
  cout << "Selected Features: ";
  for  (int32 x = 0;  x < goodFeatures.NumOfFeatures ();
  {
    if  (x > 0)  cout << ",";
    cout << goodFeatures[x];
  }
  cout << endl;
}
Parameters
[in] _idx The position in this inatnce that you want to return.
Returns
Selected feature at position '_idx'.
Definition at line 485 of file FeatureNumList.cpp.
References KKU::endl(), and KKU::osWaitForEnter().
FeatureNumListPtr FeatureNumList::RandomlySelectFeatures (int32 numToKeep) const
Generates a new FeatureNumList object that will select at random 'numToKeep' features from this instance.
Parameters
[in] numToKeep Number of features to select randomly from existing instance.
Returns
Dynamically allocated instance of a ImageFeaturesList with randomly selected features.
Definition at line 1051 of file FeatureNumList.cpp.
References AddFeature(), KKU::endl(), KKU::LRand48(), and x.
void MLL::FeatureNumList::Save (const KKStr & _fileName, bool & _successful, RunLog & _log)
void FeatureNumList::Save (std::ostream & o)
Definition at line 733 of file FeatureNumList.cpp.
References ToString().
void FeatureNumList::SetAllFeatures ()
Selects all features except those flagged as 'IgnoreAttribute' in the associated FileDesc.
Definition at line 411 of file FeatureNumList.cpp.
References AddFeature(), MLL::IgnoreAttribute, MLL::FileDesc::NumOfFields(), and MLL::FileDesc::Type().
Referenced by ExtractFeatureNumsFromStr().
bool FeatureNumList::Test (uint16 _featureNum) const
Indicates whether feature '_featureNum' is selected.
Definition at line 456 of file FeatureNumList.cpp.
References InList().
void FeatureNumList::ToBitString (BitString & bitStr) const
Definition at line 265 of file FeatureNumList.cpp.
References NumOfFeatures(), KKU::BitString::ReSet(), KKU::BitString::Set(), and x.
Referenced by ToHexString().
KKStr FeatureNumList::ToCommaDelStr () const
Definition at line 549 of file FeatureNumList.cpp.
References ToString().
Referenced by MLL::ModelParam::ToCmdLineStr(), and MLL::ModelParam::WriteXML().
KKStr FeatureNumList::ToHexString () const
Definition at line 556 of file FeatureNumList.cpp.
References MLL::FileDesc::NumOfFields(), and ToBitString().
KKStr FeatureNumList::ToString () const
Returns comma delimited list of all features selected; will make use of range specification.
Definition at line 503 of file FeatureNumList.cpp.
References KKU::KKStr::Empty(), and x.
Referenced by MLL::operator<<(), CrossValidationApp::RandomlySelectedResults(), CrossValidationApp::ReportConfigurationInfo(), MLL::TrainingConfiguration2::Save(), Save(), MLL::FeatureFileIOC45::SaveFile(), ToCommaDelStr(), MLL::BinaryClassParms::ToTabDelString(), MLL::SVMModel::Write(), and MLL::SVMparam::WriteXML().
void FeatureNumList::UnSet ()
Turns off all features so that no feature is selected.
Definition at line 295 of file FeatureNumList.cpp.
References x.
Referenced by operator-(), and operator-=().
void FeatureNumList::UnSet (uint16 featureNum)
Turns off specified feature 'featureNum'.
If 'featureNum' is not turned on then nothing happens.
Definition at line 309 of file FeatureNumList.cpp.
References x.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/FeatureNumList.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/FeatureNumList.cpp