Pices: SipperHardware::SipperBuff4Bit Class Reference
SipperHardware::SipperBuff4Bit Class Reference
Implements the KKLSC (Kurt Kramer Line-Scanner 4biit format).
#include <SipperBuff4Bit.h>
Classes
union OpRec
struct OpRecEndOfScanLine
struct OpRecInstrumentDataWord1
struct OpRecInstrumentDataWord2
OpCode 2.
struct OpRecInstrumentDataWord3
OpCode 2.
struct OpRecRaw1Pixel
struct OpRecRaw32Pixels
struct OpRecRaw513Pixels1
struct OpRecRaw513Pixels2
struct OpRecRun256Len1
struct OpRecRun256Len2
struct OpRecRunLen
struct OpRecTextBlock1
struct OpRecTextBlock2
struct RawPixelRec
Public Types
typedef SipperBuff4Bit * SipperBuff4BitPtr
Public Types inherited from SipperHardware::SipperBuff
typedef KKU::int32 int32
typedef SipperBuff * SipperBuffPtr
typedef KKU::uint32 uint32
Public Member Functions
SipperBuff4Bit (InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
SipperBuff4Bit (const KKStr &_fileName, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
virtual ~SipperBuff4Bit ()
virtual SipperFileFormat FileFormat () const
bool FileFormatGood ()
void GetNextLine (uchar *lineBuff, uint32 lineBuffSize, uint32 &lineSize, uint32 colCount[], uint32 &pixelsInRow, bool &flow)
uint32 PixelsPerScanLine () const
Public Member Functions inherited from SipperHardware::SipperBuff
SipperBuff (InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
SipperBuff (const KKStr &_fileName, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
virtual ~SipperBuff ()
uint64 ByteOffset () const
uint32 BytesDropped () const
uint32 CurRow () const
uint64 CurRowByteOffset () const
void DetermineCropSettings (uint32 &cropLeft, uint32 &cropRght)
bool Eof () const
const KKStr & FileName () const
void InvalidLine (bool _invalidLine)
bool InvalidLine () const
virtual int32 LineWidth () const
Returns the width in pixles of the associated scanner file.
void Open (const KKStr &_fileName)
bool Opened () const
uint32 RecCount () const
void ReportInstrumentData (uchar sensorId, bool text, uchar sensorData)
void Reset ()
void ResetByteOffset (uint32 _byteOffset)
int32 ScanRate () const
void SkipOneByte ()
void SkipToScanLine (uint32 scanLine)
void SkipToScanLine (uint32 _scanLine, uint64 _byteOffset)
Static Public Member Functions
static const uchar * CompensationTable ()
Static Public Member Functions inherited from SipperHardware::SipperBuff
static SipperBuffPtr CreateSipperBuff (SipperFileFormat _format, KKStr _fileName, int32 _cameraNum, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
static SipperBuffPtr CreateSipperBuff (KKStr _fileName, int32 _cameraNum, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
static SipperFileFormat GuessFormatOfFile (const KKStr &_fileName, int32 _cameraNum, RunLog &_log)
Additional Inherited Members
Protected Member Functions inherited from SipperHardware::SipperBuff
void AssignSerialPorts (const SipperHeaderRecPtr sipperHeaderRec)
Static Protected Member Functions inherited from SipperHardware::SipperBuff
static void DisplaySipperRec (SipperBuff::SipperRec &sr)
static SipperFileFormat GuessFormatOfNextLine (FILE *in, int32 _cameraNum, RunLog &_log)
Protected Attributes inherited from SipperHardware::SipperBuff
uint64 byteOffset
uint32 bytesDropped
uint32 curRow
uint64 curRowByteOffset
bool eof
KKStr fileName
FILE * inFile
InstrumentDataManagerPtr instrumentDataManager
bool invalidLine
bool iOwnInstrumentDataManager
RunLog & log
bool opened
uint32 recCount
Detailed Description
Implements the KKLSC (Kurt Kramer Line-Scanner 4biit format).
Coppied this code from the KKLSC library to allow the reading of 4bit scanner files.
  1) Records are or varying length.
  2) Each record starts with a 4 bit Op-Code.
  3) Records contain either Text or Imagery
  4) Imagery records can be eith Run-Length (Same Pixel repeating) or Raw-String(A sequence of pixels).
   Summary of Op-Codes:
   --------------------------------------------------------------------
   0: End-Of-Line:  Indicates that end of Scan-Line reached.
   1: Text-Block:
   2: InsrumentData
   3: Un-Used
   4: Run-Length (2 Pixels).
   5: Run-Length (3 Pixels).
   6: Run-Length (4 Pixels).
   7: Run-Length (5 Pixels).
   8: Run-Length (6 Pixels).
   9: Run-Length (7 Pixels).
  10: Run-Length (1 thru 256 Pixels).
  11: Raw-String (1 Pixel Length).
  12: Raw-String (Even length 2 thru 32).
  13: Raw-String (Odd Length 1 thru 513).
  14: Un-Used.
  15: Un-Used.
  Bits
  =====
  0 - 3:  OP-Code  (Values 0 thru 15)
----------------------------------------------------------
  Op-Code = 0   end of line
  4 - 7:  Ignore
----------------------------------------------------------
  Op-Code 1:   Test Block.
  4 -  4:  End of text block.
  5 -  7:  TextBlock Len HighEnd.
  8 - 15:  TextBlock Len LowEnd
    Text-Block-Len = HighEnd * 256 + LowEnd.
  Followed by 'Text-Block-Len' bytes.
----------------------------------------------------------
  Op-Code 2:  InstrumentData
  4 -  7:  InstrumentId
  8 - 39:  Scan-Line Number.
 40 - 71:  Instrument Data.
----------------------------------------------------------
  Op-Code = 4 thru 9:  Short-Run-Len
                       RunLen = OpCode - 2
  4 -  7: Pixel Value being repeated.
----------------------------------------------------------
 Op-Code = 10:   Run-length of range "1" thru "256"
                 Since there are no run-lengths of '0';  '0' will decode to Run-Lengrth = 1;
  4 -  7: Pixel Value being repeated.
  8 - 15: Runlen     0=1, 1=2, 2=3,... 254=255, 255=256
----------------------------------------------------------
 Op-Code = 11:   One Pixel Raw String.
  4 -  7:     PixelValue.
----------------------------------------------------------
 Op-Code = 12   Raw Pixel String of even length ranging from 2 to 32
                because each byte can fit two pixels it is best that Raw String lengths
                always be multiples of 2.
  4 -  7:     Len;   Num-Raw-Pixels = (Len + 1) * 2
              Len  0=(2 raw Pixels), 1=(4 raw pixels), 2=(6 raw pixels),,, 15=(32 raw pixles)
              Number of following bytes = (Len + 1).
----------------------------------------------------------
 Op-Code = 13  Odd number of raw pixels up to length of 513 pixels.
               We use the other 4 bits in the 1st byte to represent the high order bits of the length
               and the 1st 4 bits ibn the second byte for the low order;  that leaves room for one
               pixels in the second byte.  This is why odd length stings are supported.
   8 -  7:  LenHigh             String Length = 1 + 2 * (LenHigh * 16 + LenLow);
   8 - 11:  LenLow
  12 - 15:  First Raw Pixel.    Will be followed by ((LenHigh * 16 + LenLow) bytes with two pixels
                                in each one.
           Translation Tables
  ======================================
  4     8                              4
  Bit   Bit           8-Bit  Range   Bit
  ===   ===           ============   ===
  0       0           (  0 -  15):     0
  1      17           ( 16 -  31):     1
  2      34           ( 32 -  47):     2
  3      51           ( 48 -  63):     3
  4      68           ( 64 -  79):     4
  5      85           ( 80 -  95):     5
  6     102           ( 96 - 111):     6
  7     119           (112 - 127):     7
  8     136           (128 - 143):     8
  9     153           (144 - 159):     9
  10    170           (160 - 175):    10
  11    187           (176 - 191):    11
  12    204           (192 - 207):    12
  13    221           (208 - 223):    13
  14    238           (224 - 239):    14
  15    255           (240 - 255):    15
Definition at line 127 of file SipperBuff4Bit.h.
Member Typedef Documentation
typedef SipperBuff4Bit* SipperHardware::SipperBuff4Bit::SipperBuff4BitPtr
Definition at line 130 of file SipperBuff4Bit.h.
Constructor & Destructor Documentation
SipperBuff4Bit::SipperBuff4Bit (InstrumentDataManagerPtr _instrumentDataManager, RunLog & _log)
Definition at line 196 of file SipperBuff4Bit.cpp.
SipperBuff4Bit::SipperBuff4Bit (const KKStr & _fileName, InstrumentDataManagerPtr _instrumentDataManager, RunLog & _log)
Definition at line 223 of file SipperBuff4Bit.cpp.
SipperBuff4Bit::~SipperBuff4Bit (void) virtual
Definition at line 289 of file SipperBuff4Bit.cpp.
Member Function Documentation
const uchar * SipperBuff4Bit::CompensationTable () static
Definition at line 401 of file SipperBuff4Bit.cpp.
virtual SipperFileFormat SipperHardware::SipperBuff4Bit::FileFormat () const inline virtual
Definition at line 146 of file SipperBuff4Bit.h.
References SipperHardware::sfSipper4Bit.
bool SipperBuff4Bit::FileFormatGood ()
Definition at line 426 of file SipperBuff4Bit.cpp.
References SipperHardware::SipperBuff::Eof(), and SipperHardware::SipperBuff::Opened().
Referenced by SipperHardware::SipperBuff::GuessFormatOfFile().
void SipperBuff4Bit::GetNextLine (uchar * lineBuff, uint32 lineBuffSize, uint32 & lineSize, uint32 colCount[], uint32 & pixelsInRow, bool & flow) virtual
Implements SipperHardware::SipperBuff.
Definition at line 706 of file SipperBuff4Bit.cpp.
References x.
uint32 SipperHardware::SipperBuff4Bit::PixelsPerScanLine () const inline
Definition at line 151 of file SipperBuff4Bit.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/SipperBuff4Bit.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/SipperBuff4Bit.cpp