Pices: SipperDiskUtilities.SipperTimeStamp Class Reference
SipperDiskUtilities.SipperTimeStamp Class Reference
Public Member Functions
SipperTimeStamp (byte[] buffer, ref int nextIntex)
SipperTimeStamp (DateTime dt)
SipperTimeStamp (string timeStr)
void FillBuffer (byte[] buffer, ref int nextIndex)
bool Valid ()
Static Public Member Functions
static int BuffSpaceNeeded ()
Properties
int Hour [get]
int Minute [get]
int Second [get]
Detailed Description
Definition at line 8 of file SipperTimeStamp.cs.
Constructor & Destructor Documentation
SipperDiskUtilities.SipperTimeStamp.SipperTimeStamp (byte[] buffer, ref int nextIntex) inline
Definition at line 15 of file SipperTimeStamp.cs.
SipperDiskUtilities.SipperTimeStamp.SipperTimeStamp (DateTime dt) inline
Definition at line 26 of file SipperTimeStamp.cs.
SipperDiskUtilities.SipperTimeStamp.SipperTimeStamp (string timeStr) inline
Definition at line 35 of file SipperTimeStamp.cs.
References PicesInterface::PicesKKStr.StrToByte().
Member Function Documentation
static int SipperDiskUtilities.SipperTimeStamp.BuffSpaceNeeded () inline static
Definition at line 82 of file SipperTimeStamp.cs.
Referenced by SipperDiskUtilities.SipperDateTimeStamp.BuffSpaceNeeded().
void SipperDiskUtilities.SipperTimeStamp.FillBuffer (byte[] buffer, ref int nextIndex) inline
Definition at line 89 of file SipperTimeStamp.cs.
Referenced by SipperDiskUtilities.SipperDateTimeStamp.FillBuffer().
bool SipperDiskUtilities.SipperTimeStamp.Valid () inline
Definition at line 74 of file SipperTimeStamp.cs.
Referenced by SipperDiskUtilities.SipperDateTimeStamp.Valid().
Property Documentation
int SipperDiskUtilities.SipperTimeStamp.Hour get
Definition at line 69 of file SipperTimeStamp.cs.
int SipperDiskUtilities.SipperTimeStamp.Minute get
Definition at line 70 of file SipperTimeStamp.cs.
int SipperDiskUtilities.SipperTimeStamp.Second get
Definition at line 71 of file SipperTimeStamp.cs.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperDiskUtilities/SipperTimeStamp.cs