Pices: KKU::KKThread Class Reference
KKU::KKThread Class Reference
The base class to be used any thread.
#include <KKThread.h>
Public Types
typedef KKThread * KKThreadPtr
enum ThreadStatus {
tsNotStarted, tsStarting, tsRunning, tsStopping,
tsStopped
}
Public Member Functions
KKThread (const KKStr &_threadName, KKThreadManagerPtr _threadManager, MsgQueuePtr _msgQueue)
virtual ~KKThread ()
void AddShutdownPrerequistite (KKThreadPtr _thread)
Specify threads that must stop before this thread is started.
void AddStartPrerequistite (KKThreadPtr _thread)
Specify threads that must start before this thread is started.
volatile const bool & CancelFlag () const
bool Crashed () const
void Crashed (bool _crashed)
void Kill ()
stops the running thread and frees the thread handle
bool OkToShutdown () const
Returns 'true' if all shutdown prerequisites are in the 'tsStopped' status.
bool OkToStart () const
Returns 'true' if all start prerequisites are in the 'tsRunning' status.
virtual void Run ()
volatile const bool & ShutdownFlag () const
void ShutdownThread ()
Call this method to have its thread finish what ever is in the queue and then exit.
void Start (bool &successful)
Call this method to start thread; it will call the method "Run".
ThreadStatus Status () const
void Status (ThreadStatus _status)
void TerminateThread ()
Call this method to have its thread stop right away and exit.
const KKStr & ThreadName () const
Protected Member Functions
void AddMsg (KKStrPtr msg)
Taking ownership of 'msg' and will append to 'msgQueue'.
void AddMsg (const KKStr &msg)
A copy of the message 'msg' will be added to the end of msgQueue.
bool CancelOrTerminateRequested ()
bool ThereIsACircularReferenceShutdown (KKThreadPtr _thread) const
bool ThereIsACircularReferenceStart (KKThreadPtr _thread) const
Detailed Description
The base class to be used any thread.
This will be the base class for each one of the different types of processing.
Definition at line 23 of file KKThread.h.
Member Typedef Documentation
typedef KKThread* KKU::KKThread::KKThreadPtr
Definition at line 26 of file KKThread.h.
Member Enumeration Documentation
enum KKU::KKThread::ThreadStatus
Enumerator
tsNotStarted
tsStarting
tsRunning
tsStopping
tsStopped
Definition at line 28 of file KKThread.h.
Constructor & Destructor Documentation
KKThread::KKThread (const KKStr & _threadName, KKThreadManagerPtr _threadManager, MsgQueuePtr _msgQueue)
Definition at line 80 of file KKThread.cpp.
KKThread::~KKThread () virtual
Definition at line 106 of file KKThread.cpp.
Member Function Documentation
void KKThread::AddMsg (KKStrPtr msg) protected
Taking ownership of 'msg' and will append to 'msgQueue'.
Definition at line 114 of file KKThread.cpp.
References KKU::MsgQueue::AddMsg(), and KKU::endl().
Referenced by KKU::KKThreadManager::ManageThreads(), and Run().
void KKThread::AddMsg (const KKStr & msg) protected
A copy of the message 'msg' will be added to the end of msgQueue.
Definition at line 134 of file KKThread.cpp.
References KKU::MsgQueue::AddMsg(), and KKU::endl().
void KKThread::AddShutdownPrerequistite (KKThreadPtr _thread)
Specify threads that must stop before this thread is started.
This method can be called multiple times; the information is used by the 'KKTHreadManager' instance to control the orderly shutdown of the controling 'KKTHreadManager' instance.
Parameters
[in] _thread A thread that needs to be in the the 'tsStopped' status before this thread can be stutdown; we do NOT take ownership.
Definition at line 327 of file KKThread.cpp.
void KKThread::AddStartPrerequistite (KKThreadPtr _thread)
Specify threads that must start before this thread is started.
This method can be called multiple times; the information is used by the 'KKTHreadManager' instance to control the start of the thread.
Parameters
[in] _thread A thread that needs to be in the the 'tsRunning' status before this thread can start; we do NOT take ownership.
Definition at line 318 of file KKThread.cpp.
volatile const bool& KKU::KKThread::CancelFlag () const inline
Definition at line 44 of file KKThread.h.
bool KKU::KKThread::CancelOrTerminateRequested () inline protected
Definition at line 88 of file KKThread.h.
bool KKU::KKThread::Crashed () const inline
Definition at line 45 of file KKThread.h.
Referenced by KKU::KKThreadManager::AnyProcessorsCrashed().
void KKU::KKThread::Crashed (bool _crashed) inline
Definition at line 50 of file KKThread.h.
void KKThread::Kill ()
stops the running thread and frees the thread handle
Definition at line 254 of file KKThread.cpp.
Referenced by KKU::KKThreadManager::KillAllRunningThreads().
bool KKThread::OkToShutdown () const
Returns 'true' if all shutdown prerequisites are in the 'tsStopped' status.
Definition at line 336 of file KKThread.cpp.
References Status(), and tsStopped.
Referenced by KKU::KKThreadManager::ShutdownProcessing().
bool KKThread::OkToStart () const
Returns 'true' if all start prerequisites are in the 'tsRunning' status.
Definition at line 353 of file KKThread.cpp.
References Status(), and tsRunning.
void KKThread::Run () virtual
Reimplemented in KKU::KKThreadManager.
Definition at line 264 of file KKThread.cpp.
References AddMsg(), and KKU::endl().
Referenced by ImageExtractionManager::ThreadStartCallBack().
volatile const bool& KKU::KKThread::ShutdownFlag () const inline
Definition at line 47 of file KKThread.h.
Referenced by KKU::KKThreadManager::ShutdownProcessing().
void KKThread::ShutdownThread ()
Call this method to have its thread finish what ever is in the queue and then exit.
Definition at line 158 of file KKThread.cpp.
Referenced by KKU::KKThreadManager::ShutdownProcessing().
void KKThread::Start (bool & successful)
Call this method to start thread; it will call the method "Run".
Definition at line 217 of file KKThread.cpp.
References ThreadStartCallBack().
ThreadStatus KKU::KKThread::Status () const inline
Definition at line 46 of file KKThread.h.
Referenced by KKU::KKThreadManager::AllThreadsTerminated(), OkToShutdown(), OkToStart(), KKU::KKThreadManager::ShutdownProcessing(), and ImageExtractionManager::ThreadStartCallBack().
void KKU::KKThread::Status (ThreadStatus _status) inline
Definition at line 51 of file KKThread.h.
void KKThread::TerminateThread ()
Call this method to have its thread stop right away and exit.
Definition at line 151 of file KKThread.cpp.
Referenced by KKU::KKThreadManager::TerminateProcessing().
bool KKThread::ThereIsACircularReferenceShutdown (KKThreadPtr _thread) const protected
Definition at line 297 of file KKThread.cpp.
References ThereIsACircularReferenceStart().
bool KKThread::ThereIsACircularReferenceStart (KKThreadPtr _thread) const protected
Definition at line 276 of file KKThread.cpp.
References ThereIsACircularReferenceStart().
Referenced by ThereIsACircularReferenceShutdown(), and ThereIsACircularReferenceStart().
const KKStr& KKU::KKThread::ThreadName () const inline
Definition at line 48 of file KKThread.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/KKThread.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/KKThread.cpp