Pices: MLL::ChainHashNode Class Reference
MLL::ChainHashNode Class Reference
#include <ChainHash.h>
Public Types
typedef KKU::int32 int32
typedef KKU::uint32 uint32
Public Member Functions
ChainHashNode (int32 _example_index, svm_node_int *example_features, int32 _example_class_label)
ChainHashNode (const ChainHashNode &right)
ChainHashNode (int32 _example_index, int32 _example_class_label, FeatureVectorPtr _example, bool &_sucessfull)
~ChainHashNode ()
int32 getBucketListIndex () const
int32 getIndex () const
int32 hashKey () const
FeatureVectorPtr Image ()
bool operator== (const ChainHashNode &right) const
void setBucketListIndex (int32 pos)
Static Public Member Functions
static void init ()
static void SetBitsToReduceByFeature (const VectorInt32 &_bitsToReduceByFeature)
static void SetFeatureTypes (const MLL::AttributeTypeVector &_featureTypes)
static void setHashSize (int32 hs)
static void setLength (int32 len)
static void SetSelectedFeatures (const FeatureNumList &_selectedFeatures)
Detailed Description
Definition at line 88 of file ChainHash.h.
Member Typedef Documentation
typedef KKU::int32 MLL::ChainHashNode::int32
Definition at line 91 of file ChainHash.h.
typedef KKU::uint32 MLL::ChainHashNode::uint32
Definition at line 92 of file ChainHash.h.
Constructor & Destructor Documentation
ChainHashNode::ChainHashNode (int32 _example_index, svm_node_int * example_features, int32 _example_class_label)
Definition at line 24 of file ChainHash.cpp.
ChainHashNode::ChainHashNode (const ChainHashNode & right)
Definition at line 38 of file ChainHash.cpp.
ChainHashNode::ChainHashNode (int32 _example_index, int32 _example_class_label, FeatureVectorPtr _example, bool & _sucessfull)
Definition at line 53 of file ChainHash.cpp.
References MLL::FeatureVector::FeatureData(), MLL::NominalAttribute, and MLL::SymbolicAttribute.
ChainHashNode::~ChainHashNode ()
Definition at line 104 of file ChainHash.cpp.
Member Function Documentation
int32 MLL::ChainHashNode::getBucketListIndex () const inline
Definition at line 126 of file ChainHash.h.
int32 MLL::ChainHashNode::getIndex () const inline
Definition at line 116 of file ChainHash.h.
References index().
Referenced by MLL::ChainHash< T >::GetImageForIndexNum().
int32 ChainHashNode::hashKey () const
Definition at line 113 of file ChainHash.cpp.
FeatureVectorPtr MLL::ChainHashNode::Image () inline
Definition at line 128 of file ChainHash.h.
Referenced by MLL::ChainHash< T >::GetImageForIndexNum().
static void MLL::ChainHashNode::init () static
bool ChainHashNode::operator== (const ChainHashNode & right) const
Definition at line 132 of file ChainHash.cpp.
References MLL::FeatureVector::NumOfFeatures().
void ChainHashNode::SetBitsToReduceByFeature (const VectorInt32 & _bitsToReduceByFeature) static
Definition at line 192 of file ChainHash.cpp.
Referenced by MLL::BitReduction::compress().
void MLL::ChainHashNode::setBucketListIndex (int32 pos) inline
Definition at line 122 of file ChainHash.h.
void ChainHashNode::SetFeatureTypes (const MLL::AttributeTypeVector & _featureTypes) static
Definition at line 185 of file ChainHash.cpp.
Referenced by MLL::BitReduction::compress().
void ChainHashNode::setHashSize (int32 hs) static
Definition at line 165 of file ChainHash.cpp.
Referenced by MLL::BitReduction::compress().
void ChainHashNode::setLength (int32 len) static
Definition at line 158 of file ChainHash.cpp.
Referenced by MLL::BitReduction::compress().
void ChainHashNode::SetSelectedFeatures (const FeatureNumList & _selectedFeatures) static
Definition at line 172 of file ChainHash.cpp.
References MLL::FeatureNumList::NumOfFeatures(), and x.
Referenced by MLL::BitReduction::compress().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ChainHash.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ChainHash.cpp