Pices: JobManagment::JobManager Class Reference
JobManagment::JobManager Class Reference abstract
Responsable for keeping track of a list of jobs.
#include <JobManager.h>
Public Types
typedef JobManager * JobManagerPtr
Public Types inherited from JobManagment::Job
typedef map< KKStr,
ConstructorPtr > ConstructorIndex
typedef JobPtr(* ConstructorPtr)(JobManagerPtr _manager)
typedef Job * JobPtr
enum JobStatus {
jsNULL, jsOpen, jsStarted, jsDone,
jsExpanded
}
enum JobTypes { jtNULL, jtBinaryCombo, jtMultiClass, jtRandomSplit }
Public Member Functions
JobManager (const JobManager &j)
JobManager (JobManagerPtr _manager, int _jobId, int _parentId, int _numPorcessesAllowed, const KKStr &_managerName, int _numJobsAtATime, RunLog &_log)
~JobManager ()
int AllocateNextJobId ()
bool AreAllJobsDone ()
void Block ()
double CpuTimeTotalUsed () const
virtual JobPtr Duplicate () const =0
Create a duplicate instance.
void EndBlock ()
int ExpansionCount () const
int GetNextJobId ()
void InitilizeJobManager (bool &successful)
Initialize the JobManager object.
JobListPtr Jobs () const
virtual const char * JobType () const
Allows us to know which specific implementaion of 'Job' an instance really is.
const KKStr & ManagerName () const
int NextJobId () const
bool QuitRunning () const
void Restart ()
void Run ()
void SetQuitRunningFlag ()
bool SupportCompletedJobData () const
void SupportCompletedJobData (bool _supportCompletedJobData)
void Update (JobManagerPtr p)
Public Member Functions inherited from JobManagment::Job
Job (const Job &j)
Job (JobManagerPtr _manager, int _jobId, int _parentId, int _numPorcessesAllowed, RunLog &_log)
Job (JobManagerPtr _manager)
~Job ()
void AddPrerequisites (int _prerequisite)
void AddPrerequisites (VectorInt _prerequisites)
virtual void CompletedJobDataRead (istream &i)
virtual void CompletedJobDataWrite (ostream &o)
bool InPrerequisites (int _jobId)
int JobId () const
void JobId (int _jobId)
RunLog & Log ()
JobManagerPtr Manager () const
int ParentId () const
const VectorInt & Prerequisites () const
virtual void ProcessNode ()=0
virtual void ProcessStatusField (const KKStr &fieldName, const KKStr &fieldValue)
virtual void ReFresh (Job &j)
JobStatus Status () const
void Status (JobStatus _status)
KKStr StatusStr () const
Protected Member Functions
virtual void StatusFileProcessLine (const KKStr &ln, istream &statusFile)
virtual void StatusFileProcessLineJobStatusChange (KKStr &statusLineStr)
virtual KKStr ToStatusStr ()
Protected Member Functions inherited from JobManagment::Job
void PrerequisitesFromStr (const KKStr &s)
KKStr PrerequisitesToStr () const
void ProcessStatusStr (const KKStr &statusStr)
Additional Inherited Members
Static Public Member Functions inherited from JobManagment::Job
static JobPtr CallAppropriateConstructor (JobManagerPtr _manager, const KKStr &_jobTypeName, const KKStr &_statusStr)
static JobStatus JobStatusFromStr (const KKStr &statusStr)
static KKStr JobStatusToStr (JobStatus status)
static void JobTypeFromStr (const KKStr &s)
static KKStr JobTypeToStr (JobTypes jt)
static void RegisterConstructor (const KKStr &_name, ConstructorPtr _constructor)
Public Attributes inherited from JobManagment::Job
RunLog & log
Static Public Attributes inherited from JobManagment::Job
static ConstructorIndex registeredConstructors
Protected Attributes inherited from JobManagment::Job
int jobId
JobManagerPtr manager
int numPorcessesAllowed
int numProcessors
int parentId
VectorInt prerequisites
JobStatus status
Detailed Description
Responsable for keeping track of a list of jobs.
See the application called RandomSplitsJobManager. It is the first alplication to use this library. any class that is derived from this class are required to implement these methid "StatusFileProcessLine", "StatusFileProcessLineJobStatusChange", "ToStatusStr"
Definition at line 29 of file JobManager.h.
Member Typedef Documentation
typedef JobManager* JobManagment::JobManager::JobManagerPtr
Definition at line 32 of file JobManager.h.
Constructor & Destructor Documentation
JobManager::JobManager (const JobManager & j)
Definition at line 43 of file JobManager.cpp.
JobManagment::JobManager::JobManager (JobManagerPtr _manager, int _jobId, int _parentId, int _numPorcessesAllowed, const KKStr & _managerName, int _numJobsAtATime, RunLog & _log)
Parameters
_manager Ptr to job that is managing this 'JobManager'
_managerName Name of this 'JobManager' ; status and lock file will be based on it.
_numJobsAtATime The number of jobs that can be allocatd at one time for a single process to execute.
JobManager::~JobManager ()
Definition at line 126 of file JobManager.cpp.
Member Function Documentation
int JobManager::AllocateNextJobId ()
Definition at line 709 of file JobManager.cpp.
References JobManagment::Job::jobId.
bool JobManager::AreAllJobsDone ()
Definition at line 954 of file JobManager.cpp.
References JobManagment::JobList::AreAllJobsDone().
void JobManager::Block ()
Definition at line 191 of file JobManager.cpp.
References KKU::endl(), KKU::RunLog::Level(), JobManagment::Job::log, KKU::osSleep(), and KKU::KKStr::Str().
Referenced by InitilizeJobManager(), Run(), and SetQuitRunningFlag().
double JobManagment::JobManager::CpuTimeTotalUsed () const inline
Definition at line 65 of file JobManager.h.
virtual JobPtr JobManagment::JobManager::Duplicate () const pure virtual
Create a duplicate instance.
Implements JobManagment::Job.
void JobManager::EndBlock ()
Definition at line 235 of file JobManager.cpp.
References KKU::endl(), KKU::RunLog::Level(), JobManagment::Job::log, and KKU::KKStr::Str().
Referenced by InitilizeJobManager(), Run(), SetQuitRunningFlag(), and StatusFileProcessLineJobStatusChange().
int JobManagment::JobManager::ExpansionCount () const inline
Definition at line 66 of file JobManager.h.
int JobManager::GetNextJobId ()
Definition at line 292 of file JobManager.cpp.
void JobManager::InitilizeJobManager (bool & successful)
Initialize the JobManager object.
This is the first Method that needs to be called right after the object is constructed.
Definition at line 134 of file JobManager.cpp.
References Block(), EndBlock(), KKU::endl(), KKU::RunLog::Level(), JobManagment::Job::log, KKU::osFileExists(), and KKU::osGetSystemTimeUsed().
JobListPtr JobManagment::JobManager::Jobs () const inline
Definition at line 67 of file JobManager.h.
const char * JobManager::JobType () const virtual
Allows us to know which specific implementaion of 'Job' an instance really is.
Reimplemented from JobManagment::Job.
Definition at line 184 of file JobManager.cpp.
const KKStr& JobManagment::JobManager::ManagerName () const inline
Definition at line 68 of file JobManager.h.
int JobManagment::JobManager::NextJobId () const inline
Definition at line 69 of file JobManager.h.
bool JobManagment::JobManager::QuitRunning () const inline
Definition at line 70 of file JobManager.h.
void JobManagment::JobManager::Restart ()
void JobManager::Run ()
Definition at line 970 of file JobManager.cpp.
References Block(), JobManagment::Job::Duplicate(), EndBlock(), KKU::endl(), JobManagment::JobList::JobsStillRunning(), JobManagment::Job::jsDone, KKU::RunLog::Level(), JobManagment::Job::log, KKU::osSleep(), JobManagment::Job::ProcessNode(), JobManagment::JobList::PushOnBack(), JobManagment::Job::status, and JobManagment::Job::StatusStr().
void JobManager::SetQuitRunningFlag ()
Definition at line 785 of file JobManager.cpp.
References Block(), EndBlock(), and KKU::endl().
void JobManager::StatusFileProcessLine (const KKStr & ln, istream & statusFile) protected virtual
Definition at line 341 of file JobManager.cpp.
References JobManagment::Job::CallAppropriateConstructor(), KKU::KKStr::CompareIgnoreCase(), KKU::KKStr::Empty(), KKU::endl(), KKU::KKStr::EqualIgnoreCase(), KKU::KKStr::ExtractToken2(), KKU::KKStr::ExtractTokenDouble(), KKU::KKStr::ExtractTokenInt(), JobManagment::Job::JobId(), JobManagment::Job::JobStatusFromStr(), KKU::RunLog::Level(), JobManagment::Job::log, JobManagment::JobList::LookUpByJobId(), JobManagment::JobList::PushOnBack(), JobManagment::Job::ReFresh(), JobManagment::Job::status, StatusFileProcessLineJobStatusChange(), KKU::KKStr::SubStrPart(), KKU::KKStr::ToInt(), KKU::KKStr::TrimLeft(), and KKU::KKStr::TrimRight().
void JobManager::StatusFileProcessLineJobStatusChange (KKStr & statusLineStr) protected virtual
Definition at line 302 of file JobManager.cpp.
References EndBlock(), KKU::endl(), KKU::KKStr::ExtractToken2(), KKU::KKStr::ExtractTokenInt(), JobManagment::Job::JobStatusFromStr(), JobManagment::Job::jsNULL, KKU::RunLog::Level(), JobManagment::Job::log, JobManagment::JobList::LookUpByJobId(), KKU::osWaitForEnter(), JobManagment::Job::Status(), JobManagment::Job::status, KKU::KKStr::TrimLeft(), and KKU::KKStr::TrimRight().
Referenced by StatusFileProcessLine().
bool JobManagment::JobManager::SupportCompletedJobData () const inline
Definition at line 60 of file JobManager.h.
void JobManagment::JobManager::SupportCompletedJobData (bool _supportCompletedJobData) inline
Definition at line 62 of file JobManager.h.
KKStr JobManager::ToStatusStr () protected virtual
Reimplemented from JobManagment::Job.
Definition at line 728 of file JobManager.cpp.
References JobManagment::Job::JobStatusToStr(), JobManagment::Job::status, and JobManagment::Job::ToStatusStr().
void JobManager::Update (JobManagerPtr p)
Definition at line 719 of file JobManager.cpp.
References JobManagment::Job::status.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/JobManager/JobManager.h
D:/Users/kkramer/IEC/SipperSoftware/JobManager/JobManager.cpp