Pices: MLL::TrainingClass Class Reference
MLL::TrainingClass Class Reference
#include <TrainingClass.h>
Public Member Functions
TrainingClass (KKStr _directory, KKStr _name, KKStr _foreground, float _weight, MLClassConstList &mlClasses)
Constructor, Creates a new instance of TrainingClass and populates * fields with respective data from parameters.
TrainingClass (const TrainingClass &tc)
const KKStr & Directory () const
void Directory (const KKStr &_directory)
KKStr ExpandedDirectory (const KKStr &rootDir)
const KKStr & FeatureFileName () const
void FeatureFileName (const KKStr &_featureFileName)
const KKStr & Foreground () const
MLClassConstPtr MLClass () const
void MLClass (MLClassConstPtr _mlClass)
const KKStr & Name () const
float Weight () const
void Weight (float _weight)
Detailed Description
                         TrainingClass                             *
                                                                   *
 You create one instance of this object for each set of training   *
 data tou want to specify.  There will be a 'many to one' re-      *
 lationship between 'TrainingClass'  and  'MLClass'.  This is   *
 based on the assumption that there can be more than one set of    *
 training data that you can use for the same class.                *
                                                                   *
-------------------------------------------------------------------*
                                                                   *
  directory  - Directory where Training Images are stored.         *
                                                                   *
  foreground - Indicates which color will be the foreground color  *
               of images.                                          *
               "b" = Black Foreground.                             *
               "w" = White Foreground.                             *
                                                                   *
  featureFileName - Name of data file that is to contain feature   *
               data for this TrainingClass.                        *
                                                                   *
  mlClass - Pointer to MLClass that this TrainingClass is    *
               for.                                                *
Definition at line 57 of file TrainingClass.h.
Constructor & Destructor Documentation
MLL::TrainingClass::TrainingClass (KKStr _directory, KKStr _name, KKStr _foreground, float _weight, MLClassConstList & mlClasses)
Constructor, Creates a new instance of TrainingClass and populates * fields with respective data from parameters.
                     *
                                                                 *
mlClasses - list of MLClasses. Constructor will update this * set 'mlClass' to the MLClass in this list that * has the same name as '_name'. If one does not exist * it will create a new MLClass object and add it to * 'mlClasses'. *
TrainingClass::TrainingClass (const TrainingClass & tc)
Definition at line 48 of file TrainingClass.cpp.
Member Function Documentation
const KKStr& MLL::TrainingClass::Directory () const inline
Definition at line 84 of file TrainingClass.h.
Referenced by MLL::TrainingProcess2::ExtractTrainingClassFeatures(), MLL::TrainingConfiguration2::GenerateAConfiguraionForAHierarchialLevel(), CrossValidationApp::ReportConfigurationInfo(), and MLL::TrainingConfiguration2::Save().
void MLL::TrainingClass::Directory (const KKStr & _directory) inline
Definition at line 93 of file TrainingClass.h.
KKStr TrainingClass::ExpandedDirectory (const KKStr & rootDir)
Definition at line 68 of file TrainingClass.cpp.
References KKU::KKStr::Empty(), KKU::KKStr::LocateStr(), and KKU::osAddSlash().
Referenced by MLL::TrainingConfiguration2::CreateFromDirectoryStructure(), MLL::TrainingConfiguration2::DirectoryPathForClass(), PicesInterface::PicesTrainingClass::ExpandedDirectory(), MLL::TrainingConfiguration2::LoadFeatureDataFromTrainingLibraries(), and CrossValidationApp::LocateImageFileUsingConfigurationFile().
const KKStr& MLL::TrainingClass::FeatureFileName () const inline
Definition at line 86 of file TrainingClass.h.
Referenced by MLL::TrainingConfiguration2::CreateFromDirectoryStructure().
void MLL::TrainingClass::FeatureFileName (const KKStr & _featureFileName) inline
Definition at line 94 of file TrainingClass.h.
const KKStr& MLL::TrainingClass::Foreground () const inline
Definition at line 85 of file TrainingClass.h.
MLClassConstPtr MLL::TrainingClass::MLClass () const inline
Definition at line 87 of file TrainingClass.h.
Referenced by MLL::TrainingConfiguration2::CreateFromDirectoryStructure(), MLL::TrainingConfiguration2::DirectoryPathForClass(), MLL::TrainingConfiguration2::ExtractClassList(), MLL::TrainingConfiguration2::GenerateAConfiguraionForAHierarchialLevel(), MLL::TrainingClassList::LocateByMLClass(), CrossValidationApp::LocateImageFileUsingConfigurationFile(), and MLL::TrainingConfiguration2::NumHierarchialLevels().
void MLL::TrainingClass::MLClass (MLClassConstPtr _mlClass) inline
Definition at line 95 of file TrainingClass.h.
const KKStr & TrainingClass::Name () const
Definition at line 61 of file TrainingClass.cpp.
Referenced by MLL::TrainingProcess2::ExtractTrainingClassFeatures(), MLL::TrainingConfiguration2::LoadFeatureDataFromTrainingLibraries(), MLL::TrainingClassList::LocateByMLClassName(), CrossValidationApp::ReportConfigurationInfo(), and MLL::TrainingConfiguration2::Save().
float MLL::TrainingClass::Weight () const inline
Definition at line 89 of file TrainingClass.h.
Referenced by CrossValidationApp::ReportConfigurationInfo(), and MLL::TrainingConfiguration2::Save().
void MLL::TrainingClass::Weight (float _weight) inline
Definition at line 96 of file TrainingClass.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/TrainingClass.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/TrainingClass.cpp