Pices: MLL::FeatureVectorList Class Reference
MLL::FeatureVectorList Class Reference
Container class for FeatureVector derived objects.
#include <FeatureVector.h>
Classes
class BreakTieComparison
class BreakTieComparisonReversed
class ClassNameComparrison
class ClassNameComparrisonReversed
class ImageFileNameComparison
class ImageFileNameComparisonReversed
class ProbabilityComparison
class ProbabilityComparisonReversed
class RootNameComparrison
class RootNameComparrisonReversed
Public Types
typedef FeatureVectorList * FeatureVectorListPtr
enum IFL_SortOrder {
IFL_UnSorted, IFL_ByName, IFL_ByProbability, IFL_ByBreakTie,
IFL_ByRootName, IFL_ByClassName
}
Represents the different orders that a list of imageFeatures in an instance of FeatureVectorList object can be in.
typedef KKU::int32 int32
typedef KKU::uint32 uint32
Public Member Functions
FeatureVectorList (FileDescPtr _fileDesc, bool _owner, RunLog &_log, int32 _size=1000)
Will create a new empty list of FeatureVector's.
FeatureVectorList (const FeatureVectorList &examples, bool _owner)
Create a duplicate list, depending on the '_owner' parameter may also duplicate the contents.
FeatureVectorList (MLClassConstList &_mlClasses, FeatureVectorList &_examples, RunLog &_log)
Will Create a construct list from _examples who's belong to one of the ImagesClasses in '_mlClasses'.
virtual ~FeatureVectorList ()
void AddQueue (const FeatureVectorList &examplesToAdd)
Add the contents of 'examplesToAdd' to the end of this list.
void AddSingleExample (FeatureVectorPtr _imageFeatures)
Same as PushOnBack.
FeatureNumList AllFeatures ()
Will return a FeatureNumList instance with all features selected.
bool AllFieldsAreNumeric () const
Returns true if all fields are numeric, no nominal fields.
void AppendToFile (KKStr _fileName, FeatureFileIOPtr _driver, const FeatureNumList &_selFeatures)
FeatureVectorPtr BinarySearchByName (const KKStr &_imageFileName) const
Will search forthe example with the same nam as '_imageFileName'.
void CalcStatsForFeatureNum (int32 _featureNum, int32 &_count, float &_total, float &_mean, float &_var, float &_stdDev)
KKStr ClassStatisticsStr () const
MLL::AttributeTypeVector CreateAttributeTypeTable () const
vector< int32 > CreateCardinalityTable () const
FeatureVectorListPtr ExtractExamplesForHierarchyLevel (uint32 level)
Will create a list of FeatureVectors where the class assignment will refect the specified Hierarhy level specified by 'level'.
MLClassConstListPtr ExtractMLClassConstList () const
int32 FeatureCardinality (int32 featureNum) const
Returns the number of values defined for a Nommnal Field.
int32 FeatureCount () const
MLL::AttributeType FeatureType (int32 featureNum) const
Returns the type of attribute for specified 'featureNum'.
KKStr FeatureTypeStr (int32 featureNum) const
const KKStr & FieldName (int32 featureNum) const
Returns name of Attribute Field.
const FileDescPtr FileDesc () const
const KKStr & FileName () const
void FileName (const KKStr &_fileName)
void FixSipperFileScanLineAndColFields ()
int32 GetClassCount (MLClassConstPtr c) const
Returns number of examples for a specific Class (MLClass).
ClassStatisticListPtr GetClassStatistics () const
Returns the number of FeatureVectors per class.
RunLog & Log ()
FeatureVectorPtr LookUpByImageFileName (const KKStr &_imageFileName) const
Returns a pointer to the FeatureVector which has '_imageFileName'.
FeatureVectorPtr LookUpByRootName (const KKStr &_rootName)
Returns a pointer to the FeatureVector who's ImageFileName rootname = _rootName *
float MajorityClassFraction () const
Return's the fraction that the majority class makes up in this list.
virtual int32 MemoryConsumedEstimated () const
bool MissingData () const
int32 NumEntriesOfAGivenClass (MLClassConstPtr mlClass) const
int32 NumOfFeatures () const
Returns true if 1 or more entries have missing data.
FeatureVectorListPtr OrderUsingNamesFromAFile (const KKStr &fileName)
Using list of ImageFileNames in a file('fileName') create a new FeatureVectorList instance with examples in order based off contents of file.
void PrintClassStatistics (std::ostream &o) const
void PrintClassStatisticsHTML (std::ostream &o) const
void PrintFeatureStatisticsByClass (std::ostream &o) const
void PushOnBack (FeatureVectorPtr image)
Overloading the PushOnBack function in KKQueue so we can monitor the Version and Sort Order.
void PushOnFront (FeatureVectorPtr image)
Overloading the PushOnFront function in KKQueue so we can monitor the Version and Sort Order.
void RemoveDuplicateEntries ()
void RemoveEntriesWithMissingFeatures ()
void ResetFileDesc (FileDescPtr newFileDesc)
You would use this if youRecalc all the data to a newer version of the file.
void ResetNumOfFeaturs (int32 newNumOfFeatures)
void ReSyncSymbolicData (FileDescPtr newFileDesc)
bool SameExceptForSymbolicData (const FeatureVectorList &otherData) const
Will delete entries from list that have missing data.
void SaveOrderingOfImages (const KKStr &fileName, bool &successful)
Will save into a file the current ordering of FeatureVector instances in list.
void SortByBreakTie (bool reversedOrder=false)
void SortByClass (bool reversedOrder=false)
void SortByImageFileName (bool reversedOrder=false)
void SortByProbability (bool reversedOrder=false)
void SortByRootName (bool reversedOrder=false)
FeatureVectorListPtr StratifyAmoungstClasses (int32 numOfFolds)
FeatureVectorListPtr StratifyAmoungstClasses (MLClassConstListPtr mlClasses, int32 maxImagesPerClass, int32 numOfFolds)
void SynchronizeSymbolicData (FeatureVectorList &otherData)
virtual const char * UnderlyingClass () const
Public Attributes
RunLog & log
Detailed Description
Container class for FeatureVector derived objects.
Supports various functions with respect to maintaing a list of FeatureVector's. These include randomizing there order creating a stratified list by class, extracting a list of classes, sorting by various criteria.
Definition at line 207 of file FeatureVector.h.
Member Typedef Documentation
typedef FeatureVectorList* MLL::FeatureVectorList::FeatureVectorListPtr
Definition at line 210 of file FeatureVector.h.
typedef KKU::int32 MLL::FeatureVectorList::int32
Definition at line 212 of file FeatureVector.h.
typedef KKU::uint32 MLL::FeatureVectorList::uint32
Definition at line 213 of file FeatureVector.h.
Member Enumeration Documentation
enum MLL::FeatureVectorList::IFL_SortOrder
Represents the different orders that a list of imageFeatures in an instance of FeatureVectorList object can be in.
Enumerator
IFL_UnSorted
IFL_ByName
IFL_ByProbability
IFL_ByBreakTie
IFL_ByRootName
IFL_ByClassName
Definition at line 269 of file FeatureVector.h.
Constructor & Destructor Documentation
MLL::FeatureVectorList::FeatureVectorList (FileDescPtr _fileDesc, bool _owner, RunLog & _log, int32 _size = 1000)
Will create a new empty list of FeatureVector's.
Parameters
[in] _fileDesc Describes the feature data such as number of features and their attributes.
[in] _owner True indicates that this list willown its contents and when this list is deleted it will call the destrctor for all its contents.
[out] _log Log file to send messages to.
[in] _size No longer used; used to cause the preallocation of space.
Referenced by ExtractExamplesForHierarchyLevel(), MemoryConsumedEstimated(), OrderUsingNamesFromAFile(), and StratifyAmoungstClasses().
FeatureVectorList::FeatureVectorList (const FeatureVectorList & examples, bool _owner)
Create a duplicate list, depending on the '_owner' parameter may also duplicate the contents.
Constructor that create a duplicate list of FeatureVectors;.
If '_owner' = true will create new instancs of contents and own them. If 'owner' = false, will copy over pointers to existing instances.
Parameters
[in] examples Existing list of examples that we are going to copy.
[in] _owner If set to true will make a duplicate of the FeatureVectors in 'examples' and own then otherwise will just point to the same existing examples and not own them.
if (owner == true)  then will also
   1) duplicate the cotents.  That is each example in the list will be
      duplicated by calling the copy constructor.
   2) And the new list will own these newly created examples.
Definition at line 358 of file FeatureVector.cpp.
MLL::FeatureVectorList::FeatureVectorList (MLClassConstList & _mlClasses, FeatureVectorList & _examples, RunLog & _log)
Will Create a construct list from _examples who's belong to one of the ImagesClasses in '_mlClasses'.
The subset will consist of the examples who's mlClass is one of the ones in _mlClasses. We will not own these examples.
Parameters
[in] _mlClasses List of classes that we want to include.
[in] _examples Source of feature Vectors to extract from.
[out] _log Log file to send messages to.
FeatureVectorList::~FeatureVectorList () virtual
Definition at line 408 of file FeatureVector.cpp.
Member Function Documentation
void FeatureVectorList::AddQueue (const FeatureVectorList & examplesToAdd)
Add the contents of 'examplesToAdd' to the end of this list.
Definition at line 726 of file FeatureVector.cpp.
References KKU::endl(), KKU::RunLog::Level(), log, and NumOfFeatures().
Referenced by CrossValidationApp::CheckForDuplicates(), MLL::FeatureEncoder2::CompressExamples(), MLL::TrainingConfiguration2::LoadFeatureDataFromTrainingLibraries(), MLL::Model::ReduceTrainExamples(), MLL::CrossValidationThreeWay::RunValidationOnly(), SetNineClassesTrainAndTest(), SetUpLetterDataSet(), and StratifyAmoungstClasses().
void FeatureVectorList::AddSingleExample (FeatureVectorPtr _imageFeatures)
Same as PushOnBack.
Definition at line 708 of file FeatureVector.cpp.
References IFL_UnSorted, and PushOnBack().
Referenced by SplitImagesAmongstFolds().
FeatureNumList FeatureVectorList::AllFeatures ()
Will return a FeatureNumList instance with all features selected.
Definition at line 552 of file FeatureVector.cpp.
References MLL::FeatureNumList::AllFeatures().
Referenced by MLL::TrainingConfiguration2::CreateFromFeatureVectorList(), MLL::SipperExtractionImageManager::Flush(), MLL::FeatureFileIOPices::LoadInSubDirectoryTree(), CrossValidationApp::Main(), PicesInterface::PicesFeatureVectorList::Save(), PicesInterface::PicesFeatureFileIO::SaveFeatureFile(), PicesInterface::PicesFeatureFileIO::SaveFeatureFileNormalized(), SetNineClassesTrainAndTest(), SetUpJMLRDataSet(), SetUpLetterDataSet(), SplitUpETPdataSet(), and SplitUpForestData().
bool FeatureVectorList::AllFieldsAreNumeric () const
Returns true if all fields are numeric, no nominal fields.
Definition at line 491 of file FeatureVector.cpp.
References MLL::FileDesc::AllFieldsAreNumeric().
Referenced by MLL::FeatureEncoder::CreateEncodedFeatureVector(), and MLL::FeatureEncoder2::EncodedFeatureVectorList().
void MLL::FeatureVectorList::AppendToFile (KKStr _fileName, FeatureFileIOPtr _driver, const FeatureNumList & _selFeatures)
FeatureVectorPtr FeatureVectorList::BinarySearchByName (const KKStr & _imageFileName) const
Will search forthe example with the same nam as '_imageFileName'.
If the list is already sorted in name order will use a Binary Search otherwis a linear search. The method 'SortByImageFileName' will set a flag 'curSortOrder' indicating if the examples are sorted. The idea is that if you know that will will be doing many searches then for performance reasons you should call 'SortByImageFileName' first. The methods 'PushOnBack', 'PushOnFront', and 'AddSingleExample' will reset 'curSortOrder' to unsorted.
Definition at line 886 of file FeatureVector.cpp.
References KKU::endl(), IFL_ByName, IFL_ByRootName, MLL::FeatureVector::ImageFileName(), and KKU::osDisplayWarning().
Referenced by LookUpByImageFileName().
void FeatureVectorList::CalcStatsForFeatureNum (int32 _featureNum, int32 & _count, float & _total, float & _mean, float & _var, float & _stdDev)
Definition at line 1303 of file FeatureVector.cpp.
References KKU::endl(), MLL::FeatureVector::FeatureData(), KKU::RunLog::Level(), log, and NumOfFeatures().
Referenced by PrintFeatureStatisticsByClass().
KKStr FeatureVectorList::ClassStatisticsStr () const
Definition at line 1144 of file FeatureVector.cpp.
References MLL::ClassStatistic::Count(), KKU::endl(), GetClassStatistics(), and MLL::ClassStatistic::Name().
Referenced by CrossValidationApp::Main().
AttributeTypeVector FeatureVectorList::CreateAttributeTypeTable () const
Definition at line 533 of file FeatureVector.cpp.
References MLL::FileDesc::CreateAttributeTypeTable().
vector< int32 > FeatureVectorList::CreateCardinalityTable () const
Definition at line 542 of file FeatureVector.cpp.
References MLL::FileDesc::CreateCardinalityTable().
FeatureVectorListPtr FeatureVectorList::ExtractExamplesForHierarchyLevel (uint32 level)
Will create a list of FeatureVectors where the class assignment will refect the specified Hierarhy level specified by 'level'.
The hierarchy of a given class will be indicated by underscore characters in the class name.
       ex:   Level 1:  gelatinous
             Level 2:  gelatinous_hydromedusae
             Level 3:  gelatinous_hydromedusae_solmundella
       If the 'level' parameter is set to 1 then all FeatureVectors who's class name starts with 'gelatinous' will be grouped
       together under the class name 'gelatinous_hydromedusae'.
  endcode
  /
FeatureVectorListPtr      CreateListForAGivenLevel (int32  level);
IFL_SortOrder             CurSortOrder ()  const  {return  curSortOrder;}
FeatureVectorListPtr      DuplicateListAndContents ()  const;
KKStrListPtr              ExtractDuplicatesByImageFileName ();
/**
  @brief  Returns: a list of 'FeatureVector' objects that have duplicate root file names.
  @details The returned list will not own these items.  All instances of the duplicate objects will be returned.
          Ex:  if three instances have the same ImageFileName all three will be returned.
  /
FeatureVectorListPtr      ExtractDuplicatesByRootImageFileName ();
FeatureVectorListPtr      ExtractImagesForAGivenClass (MLClassConstPtr  _mlClass,
                                                       int32               _maxToExtract = -1,
                                                       FFLOAT              _minSize      = -1.0f
                                                      )  const;
VectorDouble              ExtractMeanFeatureValues ();
/**
  @brief  Will return a random sampling by class of our FeatureVector's; with a minumum per class of 'minClassCount'.
  @param[in] percentage  Percentage between 0.0 and 100.0 of each class to randomly sample.
  @param[in] minClassCount The minimum per class to keep.
  /
FeatureVectorListPtr      ExtractRandomSampling (float  percentage,    /**<  A percentage between 0.0 and 100.0 */
                                                 int32    minClassCount
                                                );
/**
  @brief Will create a list of FeatureVectors where the class assignment will refect the specified Hierarhy level specified by 'level'.
  @details The hierarchy of a given class will be indicated by underscore characters in the class name.
  @code
       ex:   Level 1:  gelatinous
             Level 2:  gelatinous_hydromedusae
             Level 3:  gelatinous_hydromedusae_solmundella
       If the 'level' parameter is set to 1 then all FeatureVectors whow's class name starts with 'gelatinous' will be
       grouped together under the class name 'gelatinous_hydromedusae'.
Bug:
This method appears to be a suplicate of 'CreateListForAGivenLevel'; We should verify this and get rid of one of them.
Definition at line 759 of file FeatureVector.cpp.
References FeatureVectorList(), log, MLL::FeatureVector::MLClass(), and PushOnBack().
MLClassConstListPtr FeatureVectorList::ExtractMLClassConstList () const
Definition at line 675 of file FeatureVector.cpp.
References MLL::FeatureVector::MLClass(), and MLL::MLClassConstList::PushOnBack().
Referenced by MLL::TrainingConfiguration2::CreateFromFeatureVectorList(), MLL::UsfCasCor::load_namesfile(), PrintFeatureStatisticsByClass(), CrossValidationApp::ProcessCmdLineParameters(), CrossValidationApp::RandomSplitsIntoTrainAndTest(), MLL::FeatureFileIORoberts::SaveFile(), MLL::FeatureFileIOC45::SaveFile(), StratifyAmoungstClasses(), MLL::ModelOldSVM::TrainModel(), MLL::Model::TrainModel(), and MLL::UsfCasCor::TrainNewClassifier().
int32 FeatureVectorList::FeatureCardinality (int32 featureNum) const
Returns the number of values defined for a Nommnal Field.
See Also
FileDesc::Cardinality
Definition at line 524 of file FeatureVector.cpp.
References MLL::FileDesc::Cardinality(), and log.
int32 MLL::FeatureVectorList::FeatureCount () const inline
Definition at line 392 of file FeatureVector.h.
AttributeType FeatureVectorList::FeatureType (int32 featureNum) const
Returns the type of attribute for specified 'featureNum'.
See Also
FileDesc
Definition at line 507 of file FeatureVector.cpp.
References MLL::FileDesc::Type().
KKStr FeatureVectorList::FeatureTypeStr (int32 featureNum) const
Definition at line 516 of file FeatureVector.cpp.
References MLL::AttributeTypeToStr(), and MLL::FileDesc::Type().
Referenced by PrintFeatureStatisticsByClass().
const KKStr & FeatureVectorList::FieldName (int32 featureNum) const
Returns name of Attribute Field.
Definition at line 498 of file FeatureVector.cpp.
References MLL::FileDesc::FieldName().
Referenced by PrintFeatureStatisticsByClass().
const FileDescPtr MLL::FeatureVectorList::FileDesc () const inline
Definition at line 393 of file FeatureVector.h.
Referenced by MLL::FeatureFileIO::AppendToFile(), MLL::BitReduction::compress(), MLL::TrainingConfiguration2::CreateFromFeatureVectorList(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::UsfCasCor::FilterOutExtremeExamples(), CrossValidationApp::ProcessCmdLineParameters(), CrossValidationApp::RandomSplitsIntoTrainAndTest(), MLL::CrossValidationThreeWay::RunValidation(), MLL::CrossValidationThreeWay::RunValidationOnly(), SameExceptForSymbolicData(), MLL::FeatureFileIO::SaveFeatureFile(), MLL::FeatureFileIO::SaveFeatureFileMultipleParts(), MLL::FeatureFileIOColumn::SaveFile(), MLL::FeatureFileIORoberts::SaveFile(), MLL::FeatureFileIOPices::SaveFile(), MLL::FeatureFileIOC45::SaveFile(), MLL::FeatureFileIOSparse::SaveFile(), SetNineClassesTrainAndTest(), SetUpJMLRDataSet(), SplitUpETPdataSet(), SplitUpForestData(), svm_binary_svc_probability(), and SynchronizeSymbolicData().
const KKStr& MLL::FeatureVectorList::FileName () const inline
Definition at line 491 of file FeatureVector.h.
Referenced by CrossValidationApp::CheckForDuplicates(), MLL::BitReduction::compress(), MLL::Orderings::CreateOrderingsObjFromFileIfAvaliable(), and MLL::Orderings::Orderings().
void MLL::FeatureVectorList::FileName (const KKStr & _fileName) inline
Definition at line 493 of file FeatureVector.h.
void MLL::FeatureVectorList::FixSipperFileScanLineAndColFields ()
int32 FeatureVectorList::GetClassCount (MLClassConstPtr c) const
Returns number of examples for a specific Class (MLClass).
Definition at line 743 of file FeatureVector.cpp.
Referenced by NumEntriesOfAGivenClass().
ClassStatisticListPtr FeatureVectorList::GetClassStatistics () const
Returns the number of FeatureVectors per class.
See Also
ClassStatisticList
Definition at line 1171 of file FeatureVector.cpp.
References MLL::ClassStatistic::Increment(), MLL::ClassStatistic::MLClass(), MLL::FeatureVector::MLClass(), MLL::ClassStatisticList::PushOnBack(), MLL::ClassStatisticList::SortByClassName(), and x.
Referenced by MLL::SVMparam::AvgNumOfFeatures(), ClassStatisticsStr(), MajorityClassFraction(), PrintClassStatistics(), PrintClassStatisticsHTML(), MLL::Model::ReduceTrainExamples(), MLL::FeatureFileIOPices::SaveFile(), and MLL::FeatureFileIOC45::SaveFile().
RunLog& MLL::FeatureVectorList::Log () inline
Definition at line 399 of file FeatureVector.h.
References log.
Referenced by MLL::Orderings::CreateOrderingsObjFromFileIfAvaliable().
FeatureVectorPtr FeatureVectorList::LookUpByImageFileName (const KKStr & _imageFileName) const
Returns a pointer to the FeatureVector which has '_imageFileName'.
If the list is currently sorted by ImageFileName (curSortOrder == IFL_ByName) then a Binary Search is performed otherwise a sequential search is performed.
Definition at line 993 of file FeatureVector.cpp.
References BinarySearchByName(), IFL_ByName, and MLL::FeatureVector::ImageFileName().
Referenced by OrderUsingNamesFromAFile(), and CrossValidationApp::RemoveDuplicateImages().
FeatureVectorPtr FeatureVectorList::LookUpByRootName (const KKStr & _rootName)
Returns a pointer to the FeatureVector who's ImageFileName rootname = _rootName *
If the list is currently sorted by ImageFileName (curSortOrder == IFL_ByRootName) then a Binary Search is performed otherwise a sequential search is performed. The parameter _rootName is assumed to be just the root name of the file. that is you used osGetRootName to et the root part.
Definition at line 934 of file FeatureVector.cpp.
References KKU::endl(), IFL_ByRootName, MLL::FeatureVector::ImageFileName(), KKU::RunLog::Level(), log, and KKU::osGetRootName().
float FeatureVectorList::MajorityClassFraction () const
Return's the fraction that the majority class makes up in this list.
Definition at line 1453 of file FeatureVector.cpp.
References MLL::ClassStatistic::Count(), and GetClassStatistics().
int32 FeatureVectorList::MemoryConsumedEstimated () const virtual
Definition at line 414 of file FeatureVector.cpp.
References FeatureVectorList(), MLL::FeatureVector::MemoryConsumedEstimated(), and KKU::KKStr::MemoryConsumedEstimated().
Referenced by SVM289_MFS::svm_model::MemoryConsumedEstimated(), MLL::Model::MemoryConsumedEstimated(), and MLL::TrainingProcess2::MemoryConsumedEstimated().
bool FeatureVectorList::MissingData () const
Definition at line 1693 of file FeatureVector.cpp.
References MLL::FeatureVector::MissingData().
int32 MLL::FeatureVectorList::NumEntriesOfAGivenClass (MLClassConstPtr mlClass) const inline
Definition at line 428 of file FeatureVector.h.
References GetClassCount().
int32 MLL::FeatureVectorList::NumOfFeatures () const inline
Returns true if 1 or more entries have missing data.
Definition at line 426 of file FeatureVector.h.
Referenced by AddQueue(), CalcStatsForFeatureNum(), MLL::NormalizationParms::NormalizeImages(), and PrintFeatureStatisticsByClass().
FeatureVectorListPtr FeatureVectorList::OrderUsingNamesFromAFile (const KKStr & fileName)
Using list of ImageFileNames in a file('fileName') create a new FeatureVectorList instance with examples in order based off contents of file.
If error occurs will return NULL.
Parameters
[in] fileName Name of file that contains a list of ImageFileName's with one entry per line.
Returns
A new list of FeatureVector instancs in the order dictated by 'fileName'.
Definition at line 1021 of file FeatureVector.cpp.
References KKU::endl(), KKU::KKStr::ExtractToken(), FeatureVectorList(), KKU::RunLog::Level(), log, LookUpByImageFileName(), KKU::osFOPEN(), PushOnBack(), KKU::KKStr::Str(), and KKU::KKStr::SubStrPart().
void FeatureVectorList::PrintClassStatistics (std::ostream & o) const
Definition at line 1485 of file FeatureVector.cpp.
References KKU::endl(), GetClassStatistics(), and index().
Referenced by MLL::TrainingProcess2::ReportTraningClassStatistics().
void FeatureVectorList::PrintClassStatisticsHTML (std::ostream & o) const
Definition at line 1512 of file FeatureVector.cpp.
References MLL::ClassStatistic::Count(), KKU::endl(), GetClassStatistics(), index(), and MLL::ClassStatistic::Name().
void FeatureVectorList::PrintFeatureStatisticsByClass (std::ostream & o) const
Definition at line 1560 of file FeatureVector.cpp.
References CalcStatsForFeatureNum(), KKU::endl(), ExtractMLClassConstList(), FeatureTypeStr(), FieldName(), and NumOfFeatures().
void FeatureVectorList::PushOnBack (FeatureVectorPtr image)
Overloading the PushOnBack function in KKQueue so we can monitor the Version and Sort Order.
Definition at line 600 of file FeatureVector.cpp.
References KKU::endl(), IFL_UnSorted, MLL::FeatureVector::NumOfFeatures(), and KKU::osWaitForEnter().
Referenced by MLL::DuplicateImage::AddADuplicate(), MLL::SipperExtractionImageManager::AddImage(), AddSingleExample(), MLL::BitReduction::compress(), MLL::FeatureEncoder::CreateEncodedFeatureVector(), MLL::DuplicateImage::DuplicateImage(), MLL::FeatureEncoder2::EncodeAllExamples(), MLL::FeatureEncoder::EncodeAllExamples(), MLL::FeatureEncoder2::EncodedFeatureVectorList(), ExtractExamplesForHierarchyLevel(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::UsfCasCor::FilterOutExtremeExamples(), MLL::DuplicateImages::ListOfExamplesToDelete(), MLL::FeatureFileIODstWeb::LoadFile(), MLL::FeatureFileIOColumn::LoadFile(), MLL::FeatureFileIOUCI::LoadFile(), MLL::FeatureFileIOPices::LoadFile(), MLL::FeatureFileIOC45::LoadFile(), MLL::FeatureFileIOSparse::LoadFile(), CrossValidationApp::Main(), OrderUsingNamesFromAFile(), CrossValidationApp::RandomlySampleData(), CrossValidationApp::RandomSplitsIntoTrainAndTest(), MLL::Model::ReduceTrainExamples(), ImageExtractionManager::DataBaseUpdateThread::Run(), MLL::CrossValidation::RunCrossValidation(), MLL::CrossValidationVoting::RunCrossValidation(), MLL::CrossValidationMxN::RunTrainAndTest(), MLL::CrossValidationThreeWay::RunValidation(), MLL::FeatureFileIO::SaveFeatureFileMultipleParts(), SetNineClassesTrainAndTest(), SetUpJMLRDataSet(), SplitUpETPdataSet(), SplitUpForestData(), svm_binary_svc_probability(), svm_load_model(), SVM289_MFS::svm_load_model_XML_SupportVectorSection(), SVM289_BFS::svm_load_model_XML_SupportVectorSection(), and PicesInterface::PicesFeatureVectorList::ToFeatureVectorList().
void FeatureVectorList::PushOnFront (FeatureVectorPtr image)
Overloading the PushOnFront function in KKQueue so we can monitor the Version and Sort Order.
Definition at line 620 of file FeatureVector.cpp.
References KKU::endl(), IFL_UnSorted, MLL::FeatureVector::NumOfFeatures(), and KKU::osWaitForEnter().
void FeatureVectorList::RemoveDuplicateEntries ()
Definition at line 716 of file FeatureVector.cpp.
References log, and MLL::DuplicateImages::PurgeDuplicates().
void FeatureVectorList::RemoveEntriesWithMissingFeatures ()
Definition at line 441 of file FeatureVector.cpp.
References KKU::endl(), KKU::RunLog::Level(), log, MLL::FeatureVector::MissingData(), and x.
Referenced by CrossValidationApp::ProcessCmdLineParameters().
void FeatureVectorList::ResetFileDesc (FileDescPtr newFileDesc)
You would use this if youRecalc all the data to a newer version of the file.
Definition at line 573 of file FeatureVector.cpp.
References KKU::endl(), MLL::FileDesc::NumOfFields(), KKU::osWaitForEnter(), and MLL::FeatureVector::ResetNumOfFeatures().
void FeatureVectorList::ResetNumOfFeaturs (int32 newNumOfFeatures)
Definition at line 559 of file FeatureVector.cpp.
References MLL::FeatureVector::ResetNumOfFeatures().
void FeatureVectorList::ReSyncSymbolicData (FileDescPtr newFileDesc)
Definition at line 1715 of file FeatureVector.cpp.
References MLL::FeatureVector::AddFeatureData(), MLL::FileDesc::Cardinality(), KKU::endl(), MLL::FeatureVector::FeatureData(), MLL::FileDesc::FieldName(), MLL::FileDesc::GetNominalValue(), KKU::RunLog::Level(), log, MLL::FileDesc::LookUpNominalCode(), MLL::FileDesc::NumOfFields(), KKU::osWaitForEnter(), MLL::SymbolicAttribute, MLL::FileDesc::Type(), and x.
Referenced by SynchronizeSymbolicData().
bool FeatureVectorList::SameExceptForSymbolicData (const FeatureVectorList & otherData) const
Will delete entries from list that have missing data.
Determines if the other FeatreVectorList has the same underlining layout; that is each field is of the same type and meaning. This way we can determine if one list contains Apples while the other contains Oranges.
Definition at line 434 of file FeatureVector.cpp.
References FileDesc(), log, and MLL::FileDesc::SameExceptForSymbolicData().
void FeatureVectorList::SaveOrderingOfImages (const KKStr & fileName, bool & successful)
Will save into a file the current ordering of FeatureVector instances in list.
This file can then be used at a later time to reproduce the exact same ordereing of FeatureVector objects from a file.
See Also
OrderUsingNamesFromAFile
Parameters
[in] fileName Name of file where ImagFileNames will be writen to.
[out] successful Wll indicate of list is successfuly written.
Definition at line 1084 of file FeatureVector.cpp.
References KKU::endl(), KKU::RunLog::Level(), log, KKU::osGetLocalDateTime(), and KKU::KKStr::Str().
void FeatureVectorList::SortByBreakTie (bool reversedOrder = false)
Definition at line 2161 of file FeatureVector.cpp.
References IFL_ByBreakTie.
void FeatureVectorList::SortByClass (bool reversedOrder = false)
Definition at line 2122 of file FeatureVector.cpp.
References IFL_ByClassName.
void FeatureVectorList::SortByImageFileName (bool reversedOrder = false)
Definition at line 2181 of file FeatureVector.cpp.
References IFL_ByName.
void FeatureVectorList::SortByProbability (bool reversedOrder = false)
Definition at line 2142 of file FeatureVector.cpp.
References IFL_ByProbability.
void FeatureVectorList::SortByRootName (bool reversedOrder = false)
Definition at line 2104 of file FeatureVector.cpp.
References IFL_ByRootName.
Referenced by MLL::FeatureFileIOPices::FeatureDataReSink().
FeatureVectorListPtr FeatureVectorList::StratifyAmoungstClasses (int32 numOfFolds)
Definition at line 1365 of file FeatureVector.cpp.
References ExtractMLClassConstList().
Referenced by CrossValidationApp::DistributesImagesRandomlyWithInFolds(), SetNineClassesTrainAndTest(), SetUpJMLRDataSet(), SplitUpETPdataSet(), and SplitUpForestData().
FeatureVectorListPtr FeatureVectorList::StratifyAmoungstClasses (MLClassConstListPtr mlClasses, int32 maxImagesPerClass, int32 numOfFolds)
Definition at line 1379 of file FeatureVector.cpp.
References AddQueue(), KKU::endl(), FeatureVectorList(), KKU::RunLog::Level(), log, KKU::osDisplayWarning(), KKU::osIsBackGroundProcess(), SplitImagesAmongstFolds(), and x.
void FeatureVectorList::SynchronizeSymbolicData (FeatureVectorList & otherData)
Definition at line 1776 of file FeatureVector.cpp.
References KKU::endl(), FileDesc(), KKU::RunLog::Level(), log, MLL::FileDesc::MergeSymbolicFields(), KKU::osWaitForEnter(), ReSyncSymbolicData(), and MLL::FileDesc::SameExceptForSymbolicData().
virtual const char* MLL::FeatureVectorList::UnderlyingClass () const inline virtual
Reimplemented in MLL::ImageFeaturesList.
Definition at line 496 of file FeatureVector.h.
Referenced by MLL::FeatureFileIOPices::FeatureDataReSink(), and MLL::FeatureFileIOPices::SaveFile().
Member Data Documentation
RunLog& MLL::FeatureVectorList::log
Definition at line 501 of file FeatureVector.h.
Referenced by AddQueue(), CalcStatsForFeatureNum(), ExtractExamplesForHierarchyLevel(), FeatureCardinality(), Log(), LookUpByRootName(), OrderUsingNamesFromAFile(), RemoveDuplicateEntries(), RemoveEntriesWithMissingFeatures(), ReSyncSymbolicData(), SameExceptForSymbolicData(), SaveOrderingOfImages(), StratifyAmoungstClasses(), and SynchronizeSymbolicData().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/FeatureVector.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/FeatureVector.cpp