Pices: KKU::BmpImage::CodedPixels Class Reference
KKU::BmpImage::CodedPixels Class Reference
This object is used to help encode the data storred in BMPImage::image into 8 or 4 bit compressed formats used by BMP files.
Public Member Functions
CodedPixels (int32 _height, int32 _width)
~CodedPixels ()
void AddPixel (uchar pixel)
This method is called once for each pixel in the BMP image.
uchar * CreatePixelDataStructure4Bit (int32 &len)
Creates the appropriate compressed data structure for the BMP 4-bit compressed file format.
uchar * CreatePixelDataStructure8Bit (int32 &len)
Creates the appropriate compressed data structure for the BMP 8-bit compressed file format.
void EOL ()
This is called once at the end of each row of pixels.
Detailed Description
This object is used to help encode the data storred in BMPImage::image into 8 or 4 bit compressed formats used by BMP files.
Definition at line 162 of file BMPImage.cpp.
Constructor & Destructor Documentation
KKU::BmpImage::CodedPixels::CodedPixels (int32 _height, int32 _width)
Definition at line 199 of file BMPImage.cpp.
References KKU::BmpImage::CodedPixels::CodedPixels().
Referenced by KKU::BmpImage::CodedPixels::CodedPixels().
KKU::BmpImage::CodedPixels::~CodedPixels ()
Definition at line 214 of file BMPImage.cpp.
References KKU::BmpImage::CodedPixels::~CodedPixels().
Referenced by KKU::BmpImage::CodedPixels::~CodedPixels().
Member Function Documentation
void KKU::BmpImage::CodedPixels::AddPixel (uchar pixel)
This method is called once for each pixel in the BMP image.
Definition at line 222 of file BMPImage.cpp.
References KKU::BmpImage::CodedPixels::AddPixel(), and KKU::endl().
Referenced by KKU::BmpImage::CodedPixels::AddPixel(), KKU::BmpImage::SaveGrayscaleInverted4Bit(), and KKU::BmpImage::SaveGrayscaleInverted8Bit().
uchar * KKU::BmpImage::CodedPixels::CreatePixelDataStructure4Bit (int32 & len)
Creates the appropriate compressed data structure for the BMP 4-bit compressed file format.
The length of the structure created will be returned in the 'len' parameter. The caller will be responsible for deleting the returned data structure.
Definition at line 276 of file BMPImage.cpp.
References KKU::BmpImage::CodedPixels::CreatePixelDataStructure4Bit().
Referenced by KKU::BmpImage::CodedPixels::CreatePixelDataStructure4Bit(), and KKU::BmpImage::SaveGrayscaleInverted4Bit().
uchar * KKU::BmpImage::CodedPixels::CreatePixelDataStructure8Bit (int32 & len)
Creates the appropriate compressed data structure for the BMP 8-bit compressed file format.
The length of the structure created will be returned in the 'len' parameter. The caller will be responsible for deleting the returned data structure.
Definition at line 357 of file BMPImage.cpp.
References KKU::BmpImage::CodedPixels::CreatePixelDataStructure8Bit(), and KKU::endl().
Referenced by KKU::BmpImage::CodedPixels::CreatePixelDataStructure8Bit(), and KKU::BmpImage::SaveGrayscaleInverted8Bit().
void KKU::BmpImage::CodedPixels::EOL ()
This is called once at the end of each row of pixels.
Definition at line 265 of file BMPImage.cpp.
Referenced by KKU::BmpImage::SaveGrayscaleInverted4Bit(), and KKU::BmpImage::SaveGrayscaleInverted8Bit().
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/BMPImage.cpp