Pices: KKU::HTMLReport Class Reference
KKU::HTMLReport Class Reference
#include <HTMLReport.h>
Public Types
enum AlignmentType { Left, Center, Right }
typedef HTMLReport * HTMLReportPtr
Public Member Functions
HTMLReport (KKStr _fileName, KKStr _title, AlignmentType _alignment)
~HTMLReport ()
void Append (const char *str)
void Close ()
ostream & OStream ()
Friends
HTMLReport & endl (HTMLReport &_outs)
HTMLReport & operator<< (HTMLReport &htmlReport, int32 right)
HTMLReport & operator<< (HTMLReport &htmlReport, uint32 right)
HTMLReport & operator<< (HTMLReport &htmlReport, int64 right)
HTMLReport & operator<< (HTMLReport &htmlReport, uint64 right)
HTMLReport & operator<< (HTMLReport &htmlReport, double right)
HTMLReport & operator<< (HTMLReport &htmlReport, char right)
HTMLReport & operator<< (HTMLReport &htmlReport, const char *right)
HTMLReport & operator<< (HTMLReport &htmlReport, const KKStr &right)
HTMLReport & operator<< (HTMLReport &htmlReport, KKStrConstPtr right)
HTMLReport & operator<< (HTMLReport &htmlReport, const DateTime &dateTime)
Detailed Description
Definition at line 16 of file HTMLReport.h.
Member Typedef Documentation
typedef HTMLReport* KKU::HTMLReport::HTMLReportPtr
Definition at line 19 of file HTMLReport.h.
Member Enumeration Documentation
enum KKU::HTMLReport::AlignmentType
Enumerator
Left
Center
Right
Definition at line 20 of file HTMLReport.h.
Constructor & Destructor Documentation
HTMLReport::HTMLReport (KKStr _fileName, KKStr _title, AlignmentType _alignment)
Definition at line 35 of file HTMLReport.cpp.
References KKU::endl(), and KKU::KKStr::Str().
HTMLReport::~HTMLReport (void)
Definition at line 80 of file HTMLReport.cpp.
References Close().
Member Function Documentation
void HTMLReport::Append (const char * str)
Definition at line 88 of file HTMLReport.cpp.
Referenced by KKU::endl(), and KKU::operator<<().
void HTMLReport::Close ()
Definition at line 95 of file HTMLReport.cpp.
Referenced by ~HTMLReport().
ostream& KKU::HTMLReport::OStream () inline
Definition at line 33 of file HTMLReport.h.
Friends And Related Function Documentation
HTMLReport& endl (HTMLReport & _outs) friend
HTMLReport& operator<< (HTMLReport & htmlReport, int32 right) friend
HTMLReport& operator<< (HTMLReport & htmlReport, uint32 right) friend
HTMLReport& operator<< (HTMLReport & htmlReport, int64 right) friend
HTMLReport& operator<< (HTMLReport & htmlReport, uint64 right) friend
HTMLReport& operator<< (HTMLReport & htmlReport, double right) friend
HTMLReport& operator<< (HTMLReport & htmlReport, char right) friend
HTMLReport& operator<< (HTMLReport & htmlReport, const char * right) friend
HTMLReport& operator<< (HTMLReport & htmlReport, const KKStr & right) friend
HTMLReport& operator<< (HTMLReport & htmlReport, KKStrConstPtr right) friend
HTMLReport& operator<< (HTMLReport & htmlReport, const DateTime & dateTime) friend
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/HTMLReport.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/HTMLReport.cpp