Pices: MLL::ModelDual Class Reference
MLL::ModelDual Class Reference
Will implement the Dual Classifoer Model.
#include <ModelDual.h>
Public Types
typedef ModelDual * ModelDualPtr
Public Types inherited from MLL::Model
typedef Model * ModelPtr
enum ModelTypes {
mtNULL = 0, mtOldSVM = 1, mtSvmBase = 2, mtKNN = 3,
mtUsfCasCor = 4, mtDual = 5
}
Public Member Functions
ModelDual (FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
ModelDual (const KKStr &_name, const ModelParamDual &_param, FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
ModelDual (const ModelDual &_model)
virtual ~ModelDual ()
Frees any memory allocated by, and owned by the ModelDual.
virtual KKStr Description () const
Return short user readable description of model.
virtual ModelDualPtr Duplicate () const
virtual int32 MemoryConsumedEstimated () const
virtual ModelTypes ModelType () const
virtual int32 NumOfSupportVectors () const
ModelParamDualPtr Param ()
virtual MLClassConstPtr Predict (FeatureVectorPtr image)
virtual void Predict (FeatureVectorPtr example, MLClassConstPtr knownClass, MLClassConstPtr &predClass1, MLClassConstPtr &predClass2, int32 &predClass1Votes, int32 &predClass2Votes, double &probOfKnownClass, double &predClass1Prob, double &predClass2Prob, double &compact, int32 &numOfWinners, bool &knownClassOneOfTheWinners, double &breakTie)
virtual ClassProbListPtr ProbabilitiesByClass (FeatureVectorPtr example)
virtual void ProbabilitiesByClass (FeatureVectorPtr example, const MLClassConstList &_mlClasses, int32 *_votes, double *_probabilities)
virtual void ProbabilitiesByClass (FeatureVectorPtr _example, const MLClassConstList &_mlClasses, double *_probabilities)
Derives predicted probabilities by class.
virtual void ProbabilitiesByClassDual (FeatureVectorPtr example, KKStr &classifier1Desc, KKStr &classifier2Desc, ClassProbListPtr &classifier1Results, ClassProbListPtr &classifier2Results)
Only applied to ModelDual classifier.
virtual void ReadSpecificImplementationXML (istream &i, bool &_successful)
virtual void RetrieveCrossProbTable (MLClassConstList &classes, double **crossProbTable)
TrainingProcess2Ptr Trainer1 ()
TrainingProcess2Ptr Trainer2 ()
virtual void TrainModel (FeatureVectorListPtr _trainExamples, bool _alreadyNormalized, bool _takeOwnership)
Performs operations such as BitReduction, FeatureEncoding, and Normailization.
virtual void WriteSpecificImplementationXML (ostream &o)
Public Member Functions inherited from MLL::Model
Model (FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
Use this when you are planning on creating a empty model without parameters.
Model (const KKStr &_name, const ModelParam &_param, FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
Construct a instance of 'Model' using the parameters specified in '_param'.
Model (const Model &_madel)
Copy Constructor.
virtual ~Model ()
Frees any memory allocated by, and owned by the Model.
bool AlreadyNormalized () const
const KKStr & BitReductionByFeature () const
int32 BitsToReduceBy () const
const CompressionStats & Compression_Stats () const
const FeatureEncoder2 & Encoder () const
virtual const FeatureNumList & GetFeatureNums () const
void Load (const KKStr &_rootFileName, bool &_successful)
virtual KKStr ModelTypeStr () const
const KKStr & Name () const
void Name (const KKStr &_name)
virtual bool NormalizeNominalAttributes () const
Return true, if nominal fields need to be normalized.
ModelParamPtr Param () const
virtual FeatureVectorPtr PrepExampleForPrediction (FeatureVectorPtr fv, bool &newExampleCreated)
Every prediction method in every class that is inherited from this class should call this method before performing there prediction.
virtual void ReadXML (istream &i, bool &_successful)
Expects to read in the entire contents of a previously trainied model into this instance.
int32 ReductionPostExampleCount () const
int32 ReductionPreExampleCount () const
float ReductionRatio () const
double ReductionTime () const
const KKStr & RootFileName () const
void RootFileName (const KKStr &_rootFileName)
void Save (const KKStr &_rootFileName, bool &_successful)
virtual const FeatureNumList & SelectedFeatures () const
const KKU::DateTime & TimeSaved () const
double TrainingTime () const
void TrainingTimeEnd ()
Derived classes call this method to stop the clock for 'trainingTime'.
void TrainingTimeStart ()
Derived classes call this method to start the clock for 'trainingTime'.
double TrianingPrepTime () const
bool ValidModel () const
virtual void WriteXML (ostream &o)
Protected Member Functions
void DeleteExistingClassifiers ()
MLClassConstPtr ReconcilePredictions (MLClassConstPtr pred1, MLClassConstPtr pred2)
void ReconcileProbAndVotes (Classifier2Ptr classifier, MLClassConstPtr predClass, FeatureVectorPtr encodedExample, double &predClassProb, int32 &predClassVotes)
Protected Member Functions inherited from MLL::Model
void AllocatePredictionVariables ()
void DeAllocateSpace ()
void Read (istream &i, bool &_successful)
void ReadSkipToSection (istream &i, KKStr sectName, bool &sectionFound)
void ReduceTrainExamples ()
Reduces the Training Images down to the size dictated by the 'examplesPerClass' parameter.
Protected Attributes
Classifier2Ptr classifier1
Classifier2Ptr classifier2
TrainingConfiguration2Ptr config1
TrainingConfiguration2Ptr config2
ModelParamDualPtr param
We will NOT own this instance.
TrainingProcess2Ptr trainer1
KKStr trainer1StatusMsg
TrainingProcess2Ptr trainer2
KKStr trainer2StatusMsg
Protected Attributes inherited from MLL::Model
bool alreadyNormalized
volatile const bool & cancelFlag
MLClassConstListPtr classes
ClassIndexListPtr classesIndex
double * classProbs
CompressionStats compression_stats
double ** crossClassProbTable
Probabilities between Binary Classes From last Prediction.
int32 crossClassProbTableSize
FeatureEncoder2Ptr encoder
FileDescPtr fileDesc
RunLog & log
NormalizationParmsPtr normParms
int32 numOfClasses
Number of Classes defined in crossClassProbTable.
ModelParamPtr param
Will own this instance.
KKStr rootFileName
This is the root name to be used by all component objects; such as svm_model, mlClasses, and svmParam(including selected features).
FeatureVectorListPtr trainExamples
bool validModel
int32 * votes
bool weOwnTrainExamples
Indicates if we own the 'trainExamples'.
Additional Inherited Members
Static Public Member Functions inherited from MLL::Model
static ModelPtr CreateAModel (ModelTypes _modelType, const KKStr &_name, const ModelParam &_param, FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
A factory method that will instantiate the appropriate class of training model based off '_modelType'.
static ModelPtr CreateFromStream (istream &i, FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
A factory method that will instantiate the appropriate class of training model based off the contents of the istream "i".
static ModelTypes ModelTypeFromStr (const KKStr &_modelingTypeStr)
static KKStr ModelTypeToStr (ModelTypes _modelingType)
Detailed Description
Will implement the Dual Classifoer Model.
This model will actually load two differenttraining models specified in the parameters field. It wil utilize both classifiers for to make a prediction. Unknow examples will be submitted to both classifiers. The returned class will be the common part of the class hierarchy of the two predictions. If there is nothing in common between th etwo predictions then it wil return th e"Other class.
Definition at line 67 of file ModelDual.h.
Member Typedef Documentation
typedef ModelDual* MLL::ModelDual::ModelDualPtr
Definition at line 71 of file ModelDual.h.
Constructor & Destructor Documentation
MLL::ModelDual::ModelDual (FileDescPtr _fileDesc, volatile const bool & _cancelFlag, RunLog & _log)
Referenced by Duplicate().
MLL::ModelDual::ModelDual (const KKStr & _name, const ModelParamDual & _param, FileDescPtr _fileDesc, volatile const bool & _cancelFlag, RunLog & _log)
ModelDual::ModelDual (const ModelDual & _model)
Definition at line 75 of file ModelDual.cpp.
References param, and MLL::Model::param.
ModelDual::~ModelDual () virtual
Frees any memory allocated by, and owned by the ModelDual.
Definition at line 95 of file ModelDual.cpp.
References classifier1, classifier2, config1, config2, DeleteExistingClassifiers(), trainer1, and trainer2.
Member Function Documentation
void ModelDual::DeleteExistingClassifiers () protected
Definition at line 152 of file ModelDual.cpp.
References classifier1, classifier2, config1, config2, trainer1, and trainer2.
Referenced by TrainModel(), and ~ModelDual().
KKStr ModelDual::Description () const virtual
Return short user readable description of model.
Reimplemented from MLL::Model.
Definition at line 121 of file ModelDual.cpp.
References config1, config2, MLL::TrainingProcess2::ConfigFileName(), MLL::TrainingConfiguration2::ModelTypeStr(), MLL::TrainingProcess2::ModelTypeStr(), MLL::Model::Name(), KKU::osGetRootName(), trainer1, and trainer2.
ModelDualPtr ModelDual::Duplicate () const virtual
Implements MLL::Model.
Definition at line 139 of file ModelDual.cpp.
References ModelDual().
int32 ModelDual::MemoryConsumedEstimated () const virtual
Reimplemented from MLL::Model.
Definition at line 109 of file ModelDual.cpp.
References classifier1, classifier2, MLL::Classifier2::MemoryConsumedEstimated(), MLL::Model::MemoryConsumedEstimated(), MLL::TrainingProcess2::MemoryConsumedEstimated(), trainer1, and trainer2.
virtual ModelTypes MLL::ModelDual::ModelType () const inline virtual
Implements MLL::Model.
Definition at line 97 of file ModelDual.h.
References MLL::Model::mtDual.
int32 ModelDual::NumOfSupportVectors () const virtual
Definition at line 1024 of file ModelDual.cpp.
References MLL::TrainingProcess2::NumOfSupportVectors(), trainer1, and trainer2.
ModelParamDualPtr ModelDual::Param ()
Definition at line 146 of file ModelDual.cpp.
References param.
MLClassConstPtr ModelDual::Predict (FeatureVectorPtr image) virtual
Todo:
ModelDual::Predict Make sure that the call to the first classifier does not modify the encodedExample.
Implements MLL::Model.
Definition at line 450 of file ModelDual.cpp.
References classifier1, classifier2, MLL::Classifier2::ClassifyAImage(), KKU::endl(), KKU::RunLog::Level(), MLL::Model::log, MLL::Model::PrepExampleForPrediction(), and ReconcilePredictions().
virtual void MLL::ModelDual::Predict (FeatureVectorPtr example, MLClassConstPtr knownClass, MLClassConstPtr & predClass1, MLClassConstPtr & predClass2, int32 & predClass1Votes, int32 & predClass2Votes, double & probOfKnownClass, double & predClass1Prob, double & predClass2Prob, double & compact, int32 & numOfWinners, bool & knownClassOneOfTheWinners, double & breakTie) virtual
Implements MLL::Model.
ClassProbListPtr ModelDual::ProbabilitiesByClass (FeatureVectorPtr example) virtual
Implements MLL::Model.
Definition at line 614 of file ModelDual.cpp.
References MLL::Model::classes, classifier1, classifier2, KKU::endl(), KKU::RunLog::Level(), MLL::Model::log, MLL::Model::PrepExampleForPrediction(), MLL::Classifier2::ProbabilitiesByClass(), and MLL::Model::votes.
virtual void MLL::ModelDual::ProbabilitiesByClass (FeatureVectorPtr example, const MLClassConstList & _mlClasses, int32 * _votes, double * _probabilities) virtual
Implements MLL::Model.
void ModelDual::ProbabilitiesByClass (FeatureVectorPtr _example, const MLClassConstList & _mlClasses, double * _probabilities) virtual
Derives predicted probabilities by class.
Will get the probabilities assigned to each class by the classifier. The '_mlClasses' parameter dictates the order of the classes. That is the probabilities for any goven index in '_probabilities' will be for the class specifid in the same index in '_mlClasses'.
Parameters
[in] _example FeatureVector object to calculate predivcted probabilities for.
[in] _mlClasses List image classes that caller is aware of. This should be the same list that was used when consttructing this Model object. The list must be the same but not nessasarily in the same order as when Model was 1st constructed.
[out] _probabilities An array that must be as big as the number of classes as in mlClasses. The probability of class in mlClasses[x] will be returned in probabilities[x].
Implements MLL::Model.
Definition at line 763 of file ModelDual.cpp.
References classifier1, classifier2, KKU::endl(), KKU::RunLog::Level(), MLL::Model::log, MLL::Model::PrepExampleForPrediction(), and MLL::Classifier2::ProbabilitiesByClass().
void ModelDual::ProbabilitiesByClassDual (FeatureVectorPtr example, KKStr & classifier1Desc, KKStr & classifier2Desc, ClassProbListPtr & classifier1Results, ClassProbListPtr & classifier2Results) virtual
Only applied to ModelDual classifier.
Reimplemented from MLL::Model.
Definition at line 662 of file ModelDual.cpp.
References classifier1, classifier2, KKU::endl(), KKU::RunLog::Level(), MLL::Model::log, MLL::TrainingProcess2::ModelDescription(), MLL::Model::PrepExampleForPrediction(), MLL::Classifier2::ProbabilitiesByClass(), trainer1, and trainer2.
void ModelDual::ReadSpecificImplementationXML (istream & i, bool & _successful) virtual
Implements MLL::Model.
Definition at line 855 of file ModelDual.cpp.
References MLL::TrainingProcess2::Abort(), MLL::Model::cancelFlag, classifier1, classifier2, MLL::TrainingProcess2::ConfigFileName(), MLL::ModelParamDual::ConfigFileName1(), MLL::ModelParamDual::ConfigFileName2(), KKU::endl(), KKU::KKStr::EqualIgnoreCase(), KKU::KKStr::ExtractQuotedStr(), MLL::Model::fileDesc, KKU::RunLog::Level(), MLL::Model::log, KKU::osGetRootName(), param, MLL::Model::param, MLL::Model::ReadXML(), trainer1, trainer1StatusMsg, trainer2, trainer2StatusMsg, KKU::KKStr::Upper(), and MLL::Model::validModel.
MLClassConstPtr ModelDual::ReconcilePredictions (MLClassConstPtr pred1, MLClassConstPtr pred2) protected
Definition at line 336 of file ModelDual.cpp.
References KKU::KKStr::Append(), MLL::ModelParamDual::ConfigFileName1(), MLL::ModelParamDual::ConfigFileName2(), MLL::MLClass::CreateNewMLClass(), KKU::KKStr::Empty(), KKU::endl(), KKU::KKStr::ExtractToken2(), MLL::ModelParamDual::FullHierarchyMustMatch(), KKU::KKStr::Len(), KKU::RunLog::Level(), MLL::Model::log, Min(), MLL::ModelParamDual::OtherClass(), and param.
Referenced by Predict().
void ModelDual::ReconcileProbAndVotes (Classifier2Ptr classifier, MLClassConstPtr predClass, FeatureVectorPtr encodedExample, double & predClassProb, int32 & predClassVotes) protected
Definition at line 411 of file ModelDual.cpp.
References MLL::Model::classes, MLL::Classifier2::ProbabilitiesByClass(), MLL::Model::votes, and x.
void ModelDual::RetrieveCrossProbTable (MLClassConstList & classes, double ** crossProbTable) virtual
Reimplemented from MLL::Model.
Definition at line 809 of file ModelDual.cpp.
References classifier1, classifier2, KKU::endl(), KKU::RunLog::Level(), MLL::Model::log, MLL::Classifier2::RetrieveCrossProbTable(), and x.
TrainingProcess2Ptr MLL::ModelDual::Trainer1 () inline
Definition at line 102 of file ModelDual.h.
References trainer1.
TrainingProcess2Ptr MLL::ModelDual::Trainer2 () inline
Definition at line 104 of file ModelDual.h.
References trainer2.
void ModelDual::TrainModel (FeatureVectorListPtr _trainExamples, bool _alreadyNormalized, bool _takeOwnership) virtual
Performs operations such as BitReduction, FeatureEncoding, and Normailization.
The actual training of models occurs in the specific implementation of 'Model'.
< _reportFile,
< 'true' = Feature data already normalized.
< 'true' = Feature data already normalized.
Parameters
_takeOwnership Model will take ownership of these examples
Reimplemented from MLL::Model.
Definition at line 165 of file ModelDual.cpp.
References MLL::TrainingProcess2::Abort(), MLL::Model::cancelFlag, classifier1, classifier2, config1, config2, MLL::TrainingConfiguration2::ConfigFileExists(), MLL::ModelParamDual::ConfigFileName1(), MLL::ModelParamDual::ConfigFileName2(), MLL::TrainingProcess2::CreateModelsFromTrainingData(), DeleteExistingClassifiers(), KKU::endl(), MLL::Model::fileDesc, MLL::ModelParam::FileName(), KKU::RunLog::Level(), MLL::Model::log, param, KKU::KKStrException::ToString(), trainer1, trainer1StatusMsg, trainer2, trainer2StatusMsg, MLL::Model::trainExamples, MLL::Model::TrainingTimeEnd(), MLL::Model::TrainingTimeStart(), MLL::Model::TrainModel(), and MLL::Model::validModel.
void ModelDual::WriteSpecificImplementationXML (ostream & o) virtual
Implements MLL::Model.
Definition at line 998 of file ModelDual.cpp.
References KKU::endl(), KKU::RunLog::Level(), MLL::Model::log, trainer1, trainer2, and MLL::TrainingProcess2::WriteXml().
Member Data Documentation
Classifier2Ptr MLL::ModelDual::classifier1 protected
Definition at line 212 of file ModelDual.h.
Referenced by DeleteExistingClassifiers(), MemoryConsumedEstimated(), Predict(), ProbabilitiesByClass(), ProbabilitiesByClassDual(), ReadSpecificImplementationXML(), RetrieveCrossProbTable(), TrainModel(), and ~ModelDual().
Classifier2Ptr MLL::ModelDual::classifier2 protected
Definition at line 213 of file ModelDual.h.
Referenced by DeleteExistingClassifiers(), MemoryConsumedEstimated(), Predict(), ProbabilitiesByClass(), ProbabilitiesByClassDual(), ReadSpecificImplementationXML(), RetrieveCrossProbTable(), TrainModel(), and ~ModelDual().
TrainingConfiguration2Ptr MLL::ModelDual::config1 protected
Definition at line 206 of file ModelDual.h.
Referenced by DeleteExistingClassifiers(), Description(), TrainModel(), and ~ModelDual().
TrainingConfiguration2Ptr MLL::ModelDual::config2 protected
Definition at line 207 of file ModelDual.h.
Referenced by DeleteExistingClassifiers(), Description(), TrainModel(), and ~ModelDual().
ModelParamDualPtr MLL::ModelDual::param protected
We will NOT own this instance.
It will point to same instance defined in parent class Model.
Definition at line 218 of file ModelDual.h.
Referenced by ModelDual(), Param(), ReadSpecificImplementationXML(), ReconcilePredictions(), and TrainModel().
TrainingProcess2Ptr MLL::ModelDual::trainer1 protected
Definition at line 209 of file ModelDual.h.
Referenced by DeleteExistingClassifiers(), Description(), MemoryConsumedEstimated(), NumOfSupportVectors(), ProbabilitiesByClassDual(), ReadSpecificImplementationXML(), Trainer1(), TrainModel(), WriteSpecificImplementationXML(), and ~ModelDual().
KKStr MLL::ModelDual::trainer1StatusMsg protected
Definition at line 215 of file ModelDual.h.
Referenced by ReadSpecificImplementationXML(), and TrainModel().
TrainingProcess2Ptr MLL::ModelDual::trainer2 protected
Definition at line 210 of file ModelDual.h.
Referenced by DeleteExistingClassifiers(), Description(), MemoryConsumedEstimated(), NumOfSupportVectors(), ProbabilitiesByClassDual(), ReadSpecificImplementationXML(), Trainer2(), TrainModel(), WriteSpecificImplementationXML(), and ~ModelDual().
KKStr MLL::ModelDual::trainer2StatusMsg protected
Definition at line 216 of file ModelDual.h.
Referenced by ReadSpecificImplementationXML(), and TrainModel().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ModelDual.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ModelDual.cpp