Pices: MLL::BinaryClassParms Class Reference
MLL::BinaryClassParms Class Reference
Machine Learning parameters to be used by a pair of classes.
#include <BinaryClassParms.h>
Public Types
typedef BinaryClassParms * BinaryClassParmsPtr
typedef SVM233::svm_parameter svm_parameter
Public Member Functions
BinaryClassParms (MLClassConstPtr _class1, MLClassConstPtr _class2, const svm_parameter &_param, const FeatureNumList &_selectedFeatures, float _weight)
Constructor for 'BinaryClassParms' where caller supplies the two classes and parameters for that specific class pair.
BinaryClassParms (const BinaryClassParms &binaryClassParms)
~BinaryClassParms ()
double AParam () const
double C () const
void C (double _c)
MLClassConstPtr Class1 () const
KKStr Class1Name () const
MLClassConstPtr Class2 () const
KKStr Class2Name () const
void Gamma (double _gamma)
int32 MemoryConsumedEstimated () const
const svm_parameter & Param () const
void Param (const svm_parameter &_param)
const FeatureNumList & SelectedFeatures () const
void SelectedFeatures (const FeatureNumList &_selectedFeatures)
KKStr ToTabDelString () const
float Weight () const
void Weight (float _weight)
Static Public Member Functions
static BinaryClassParmsPtr CreateFromTabDelStr (const KKStr &_str, FileDescPtr _fileDesc, RunLog &_log)
Detailed Description
Machine Learning parameters to be used by a pair of classes.
Author
Kurt Kramer
 Written by: Kurt Kramer                                           *
        For: Research Work, Plankton recognition System            *
-------------------------------------------------------------------*
  History                                                          *
                                                                   *
    date     Programmer   Description                              *
                                                                   *
  May-2004  Kurt Kramer  Original Development.                     *
-------------------------------------------------------------------*
 Was developed to support Feature Selection for each binary class  *
 combination.  This way each two class combination can have SVM    *
 and feature parameters that are specific to them.                 *
See Also
MLL::SVMparam, MLL::ModelParamOldSVM, MLL::SVM233
Definition at line 41 of file BinaryClassParms.h.
Member Typedef Documentation
typedef BinaryClassParms* MLL::BinaryClassParms::BinaryClassParmsPtr
Definition at line 44 of file BinaryClassParms.h.
typedef SVM233::svm_parameter MLL::BinaryClassParms::svm_parameter
Definition at line 46 of file BinaryClassParms.h.
Constructor & Destructor Documentation
BinaryClassParms::BinaryClassParms (MLClassConstPtr _class1, MLClassConstPtr _class2, const svm_parameter & _param, const FeatureNumList & _selectedFeatures, float _weight)
Constructor for 'BinaryClassParms' where caller supplies the two classes and parameters for that specific class pair.
Definition at line 27 of file BinaryClassParms.cpp.
Referenced by CreateFromTabDelStr().
BinaryClassParms::BinaryClassParms (const BinaryClassParms & binaryClassParms)
Definition at line 44 of file BinaryClassParms.cpp.
BinaryClassParms::~BinaryClassParms ()
Definition at line 55 of file BinaryClassParms.cpp.
Member Function Documentation
double MLL::BinaryClassParms::AParam () const inline
Definition at line 67 of file BinaryClassParms.h.
References SVM233::svm_parameter::A.
double MLL::BinaryClassParms::C () const inline
Definition at line 70 of file BinaryClassParms.h.
References SVM233::svm_parameter::C.
Referenced by MLL::ModelParamOldSVM::C_Param(), and MLL::SVMparam::C_Param().
void MLL::BinaryClassParms::C (double _c) inline
Definition at line 76 of file BinaryClassParms.h.
References SVM233::svm_parameter::C.
MLClassConstPtr MLL::BinaryClassParms::Class1 () const inline
Definition at line 68 of file BinaryClassParms.h.
Referenced by MLL::SVMModel::FindWorstSupportVectors(), MLL::SVMModel::FindWorstSupportVectors2(), MLL::BinaryClassParmsList::LookUp(), and MLL::SVMModel::SupportVectorNames().
KKStr BinaryClassParms::Class1Name () const
Definition at line 60 of file BinaryClassParms.cpp.
Referenced by MLL::TrainingConfiguration2::Save(), ToTabDelString(), and MLL::SVMModel::Write().
MLClassConstPtr MLL::BinaryClassParms::Class2 () const inline
Definition at line 69 of file BinaryClassParms.h.
Referenced by MLL::SVMModel::FindWorstSupportVectors(), MLL::SVMModel::FindWorstSupportVectors2(), MLL::BinaryClassParmsList::LookUp(), and MLL::SVMModel::SupportVectorNames().
KKStr BinaryClassParms::Class2Name () const
Definition at line 70 of file BinaryClassParms.cpp.
Referenced by MLL::TrainingConfiguration2::Save(), ToTabDelString(), and MLL::SVMModel::Write().
BinaryClassParmsPtr BinaryClassParms::CreateFromTabDelStr (const KKStr & _str, FileDescPtr _fileDesc, RunLog & _log) static
Definition at line 94 of file BinaryClassParms.cpp.
References BinaryClassParms(), MLL::MLClass::CreateNewMLClass(), KKU::KKStr::Empty(), MLL::FeatureNumList::ExtractFeatureNumsFromStr(), KKU::KKStr::ExtractQuotedStr(), KKU::KKStr::Str(), and KKU::KKStr::Upper().
void MLL::BinaryClassParms::Gamma (double _gamma) inline
Definition at line 77 of file BinaryClassParms.h.
References SVM233::svm_parameter::gamma.
int32 BinaryClassParms::MemoryConsumedEstimated () const
Definition at line 148 of file BinaryClassParms.cpp.
References SVM233::svm_parameter::MemoryConsumedEstimated(), and MLL::FeatureNumList::MemoryConsumedEstimated().
const svm_parameter& MLL::BinaryClassParms::Param () const inline
Definition at line 71 of file BinaryClassParms.h.
Referenced by CreateBfsFromMfs(), MLL::SVMModel::FindWorstSupportVectors(), MLL::SVMModel::FindWorstSupportVectors2(), MLL::TrainingConfiguration2::Save(), and MLL::SVMparam::SetBinaryClassFields().
void MLL::BinaryClassParms::Param (const svm_parameter & _param) inline
Definition at line 78 of file BinaryClassParms.h.
const FeatureNumList& MLL::BinaryClassParms::SelectedFeatures () const inline
Definition at line 72 of file BinaryClassParms.h.
Referenced by MLL::SVMparam::AvgMumOfFeatures(), CreateBfsFromMfs(), MLL::BinaryClassParmsList::FeatureCountNet(), MLL::SVMparam::GetFeatureNums(), MLL::TrainingConfiguration2::Save(), MLL::SVMparam::SetBinaryClassFields(), and MLL::SVMparam::SetFeatureNums().
void MLL::BinaryClassParms::SelectedFeatures (const FeatureNumList & _selectedFeatures) inline
Definition at line 79 of file BinaryClassParms.h.
KKStr BinaryClassParms::ToTabDelString () const
Definition at line 80 of file BinaryClassParms.cpp.
References Class1Name(), Class2Name(), SVM233::svm_parameter::ToCmdLineStr(), and MLL::FeatureNumList::ToString().
float MLL::BinaryClassParms::Weight () const inline
Definition at line 73 of file BinaryClassParms.h.
Referenced by CreateBfsFromMfs(), MLL::TrainingConfiguration2::Save(), MLL::SVMparam::SetBinaryClassFields(), and MLL::SVMparam::SetFeatureNums().
void MLL::BinaryClassParms::Weight (float _weight) inline
Definition at line 80 of file BinaryClassParms.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/BinaryClassParms.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/BinaryClassParms.cpp