Pices: MLL::DataBaseImageGroup Class Reference
MLL::DataBaseImageGroup Class Reference
#include <DataBaseImageGroup.h>
Public Types
typedef DataBaseImageGroup * DataBaseImageGroupPtr
typedef KKU::int32 int32
typedef KKU::uint32 uint32
Public Member Functions
DataBaseImageGroup (int32 _imageGroupId, const KKStr &_name, const KKStr &_description, uint32 _count)
DataBaseImageGroup (const DataBaseImageGroup &_dataBaseImageGroup)
~DataBaseImageGroup ()
uint32 Count () const
void Count (uint32 _count)
const KKStr & Description () const
void Description (const KKStr &_description)
int32 ImageGroupId () const
void ImageGroupId (int32 _imageGroupId)
const KKStr & Name () const
void Name (const KKStr &_name)
Static Public Member Functions
static bool ValidName (const KKStr &name)
static void ValidName (KKStr &_name, KKStr &_errorDesc, bool &_valid)
determines if '_name' is a valid ImageGroupName, will return back description of any errors
Detailed Description
Definition at line 12 of file DataBaseImageGroup.h.
Member Typedef Documentation
typedef DataBaseImageGroup* MLL::DataBaseImageGroup::DataBaseImageGroupPtr
Definition at line 15 of file DataBaseImageGroup.h.
typedef KKU::int32 MLL::DataBaseImageGroup::int32
Definition at line 17 of file DataBaseImageGroup.h.
typedef KKU::uint32 MLL::DataBaseImageGroup::uint32
Definition at line 18 of file DataBaseImageGroup.h.
Constructor & Destructor Documentation
MLL::DataBaseImageGroup::DataBaseImageGroup (int32 _imageGroupId, const KKStr & _name, const KKStr & _description, uint32 _count)
DataBaseImageGroup::DataBaseImageGroup (const DataBaseImageGroup & _dataBaseImageGroup)
Definition at line 37 of file DataBaseImageGroup.cpp.
DataBaseImageGroup::~DataBaseImageGroup ()
Definition at line 48 of file DataBaseImageGroup.cpp.
Member Function Documentation
uint32 MLL::DataBaseImageGroup::Count () const inline
Definition at line 35 of file DataBaseImageGroup.h.
void MLL::DataBaseImageGroup::Count (uint32 _count) inline
Definition at line 40 of file DataBaseImageGroup.h.
const KKStr& MLL::DataBaseImageGroup::Description () const inline
Definition at line 34 of file DataBaseImageGroup.h.
Referenced by MLL::DataBase::ImageGroupInsert().
void MLL::DataBaseImageGroup::Description (const KKStr & _description) inline
Definition at line 39 of file DataBaseImageGroup.h.
int32 MLL::DataBaseImageGroup::ImageGroupId () const inline
Definition at line 32 of file DataBaseImageGroup.h.
Referenced by MLL::DataBase::FeatureDataForImageGroup(), and MLL::DataBase::ImageGroupInsert().
void MLL::DataBaseImageGroup::ImageGroupId (int32 _imageGroupId) inline
Definition at line 37 of file DataBaseImageGroup.h.
const KKStr& MLL::DataBaseImageGroup::Name () const inline
Definition at line 33 of file DataBaseImageGroup.h.
Referenced by MLL::DataBase::FeatureDataForImageGroup(), MLL::DataBase::ImageGetClassStatistics(), MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageGroupInsert(), MLL::DataBase::ImagesQuery(), and MLL::DataBase::ImagesQueryByGrouop().
void MLL::DataBaseImageGroup::Name (const KKStr & _name) inline
Definition at line 38 of file DataBaseImageGroup.h.
static bool MLL::DataBaseImageGroup::ValidName (const KKStr & name) static
static void MLL::DataBaseImageGroup::ValidName (KKStr & _name, KKStr & _errorDesc, bool & _valid) static
determines if '_name' is a valid ImageGroupName, will return back description of any errors
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/DataBaseImageGroup.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/DataBaseImageGroup.cpp