Pices: SVM289_BFS::Solver Class Reference
SVM289_BFS::Solver Class Reference
Classes
struct SolutionInfo
Public Member Functions
Solver ()
virtual ~Solver ()
void Solve (int32 l, QMatrix &Q, const double *p_, const schar *y_, double *alpha_, double Cp, double Cn, double eps, SolutionInfo *si, int32 shrinking)
Protected Types
enum { LOWER_BOUND, UPPER_BOUND, FREE }
Protected Member Functions
virtual double calculate_rho ()
virtual void do_shrinking ()
double get_C (int32 i)
bool is_free (int32 i)
bool is_lower_bound (int32 i)
bool is_upper_bound (int32 i)
void reconstruct_gradient ()
virtual int32 select_working_set (int32 &i, int32 &j)
void swap_index (int32 i, int32 j)
void update_alpha_status (int32 i)
Protected Attributes
int32 * active_set
int32 active_size
double * alpha
char * alpha_status
double Cn
double Cp
double eps
double * G
double * G_bar
int32 l
double * p
QMatrix * Q
const Qfloat * QD
bool unshrink
schar * y
Detailed Description
Definition at line 1184 of file svm289_BFS.cpp.
Member Enumeration Documentation
anonymous enum protected
Enumerator
LOWER_BOUND
UPPER_BOUND
FREE
Definition at line 1213 of file svm289_BFS.cpp.
Constructor & Destructor Documentation
SVM289_BFS::Solver::Solver () inline
Definition at line 1186 of file svm289_BFS.cpp.
virtual SVM289_BFS::Solver::~Solver () inline virtual
Definition at line 1187 of file svm289_BFS.cpp.
Member Function Documentation
double SVM289_BFS::Solver::calculate_rho () protected virtual
Definition at line 1846 of file svm289_BFS.cpp.
References INF, SVM289_BFS::Max(), and SVM289_BFS::Min().
void Solver::do_shrinking () protected virtual
Definition at line 1778 of file svm289_BFS.cpp.
References active_size, eps, G, INF, info(), is_lower_bound(), is_upper_bound(), l, reconstruct_gradient(), swap_index(), and unshrink.
double SVM289_BFS::Solver::get_C (int32 i) inline protected
Definition at line 1228 of file svm289_BFS.cpp.
bool SVM289_BFS::Solver::is_free (int32 i) inline protected
Definition at line 1248 of file svm289_BFS.cpp.
bool SVM289_BFS::Solver::is_lower_bound (int32 i) inline protected
Definition at line 1247 of file svm289_BFS.cpp.
Referenced by do_shrinking().
bool SVM289_BFS::Solver::is_upper_bound (int32 i) inline protected
Definition at line 1246 of file svm289_BFS.cpp.
Referenced by do_shrinking().
void SVM289_BFS::Solver::reconstruct_gradient () protected
Definition at line 1285 of file svm289_BFS.cpp.
References info().
Referenced by do_shrinking().
int32 SVM289_BFS::Solver::select_working_set (int32 & i, int32 & j) protected virtual
Definition at line 1637 of file svm289_BFS.cpp.
References INF, and TAU.
void SVM289_BFS::Solver::Solve (int32 l, QMatrix & Q, const double * p_, const schar * y_, double * alpha_, double Cp, double Cn, double eps, SolutionInfo * si, int32 shrinking)
Definition at line 1338 of file svm289_BFS.cpp.
References SVM289_BFS::clone(), SVM289_BFS::QMatrix::get_Q(), SVM289_BFS::QMatrix::get_QD(), info(), SVM289_BFS::Min(), SVM289_BFS::Solver::SolutionInfo::obj, SVM289_BFS::Solver::SolutionInfo::rho, TAU, SVM289_BFS::Solver::SolutionInfo::upper_bound_n, and SVM289_BFS::Solver::SolutionInfo::upper_bound_p.
Referenced by SVM289_BFS::Solver_NU::Solve(), SVM289_BFS::solve_c_svc(), SVM289_BFS::solve_epsilon_svr(), and SVM289_BFS::solve_one_class().
void SVM289_BFS::Solver::swap_index (int32 i, int32 j) protected
Definition at line 1271 of file svm289_BFS.cpp.
References SVM289_BFS::swap().
Referenced by do_shrinking().
void SVM289_BFS::Solver::update_alpha_status (int32 i) inline protected
Definition at line 1234 of file svm289_BFS.cpp.
Member Data Documentation
int32* SVM289_BFS::Solver::active_set protected
Definition at line 1222 of file svm289_BFS.cpp.
int32 SVM289_BFS::Solver::active_size protected
Definition at line 1210 of file svm289_BFS.cpp.
Referenced by do_shrinking().
double* SVM289_BFS::Solver::alpha protected
Definition at line 1215 of file svm289_BFS.cpp.
char* SVM289_BFS::Solver::alpha_status protected
Definition at line 1214 of file svm289_BFS.cpp.
double SVM289_BFS::Solver::Cn protected
Definition at line 1220 of file svm289_BFS.cpp.
double SVM289_BFS::Solver::Cp protected
Definition at line 1219 of file svm289_BFS.cpp.
double SVM289_BFS::Solver::eps protected
Definition at line 1218 of file svm289_BFS.cpp.
Referenced by do_shrinking().
double* SVM289_BFS::Solver::G protected
Definition at line 1212 of file svm289_BFS.cpp.
Referenced by do_shrinking().
double* SVM289_BFS::Solver::G_bar protected
Definition at line 1223 of file svm289_BFS.cpp.
int32 SVM289_BFS::Solver::l protected
Definition at line 1224 of file svm289_BFS.cpp.
Referenced by do_shrinking().
double* SVM289_BFS::Solver::p protected
Definition at line 1221 of file svm289_BFS.cpp.
QMatrix* SVM289_BFS::Solver::Q protected
Definition at line 1216 of file svm289_BFS.cpp.
const Qfloat* SVM289_BFS::Solver::QD protected
Definition at line 1217 of file svm289_BFS.cpp.
bool SVM289_BFS::Solver::unshrink protected
Definition at line 1225 of file svm289_BFS.cpp.
Referenced by do_shrinking().
schar* SVM289_BFS::Solver::y protected
Definition at line 1211 of file svm289_BFS.cpp.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/svm289_BFS.cpp