Pices: SipperFile.TimePlotParameters Class Reference
SipperFile.TimePlotParameters Class Reference
Public Member Functions
TimePlotParameters (Panel _panel, int[] _fieldIdxs, float[] _minValues, float[] _maxValues, float[] _rowScaleFactors, bool[] _plotDataSeries, SolidBrush[] _plotBrushes, DataSeries[] _plottedSeries)
void ClearPlotArea ()
int ComputeColFromTime (DateTime t)
DateTime ComputeDateTimeFromPixelCol (int pixelCol)
void ComputeParameters ()
int CurCol ()
void DrawXAxisWithLabels ()
void MakeTimeVisible (DateTime t)
void PaintSelectedLine (DateTime dt, Brush b)
int PlotBotRow ()
void PlotDataRow (InstrumentData dr)
int PlotTopRow ()
void ScrollPlotAreaRightOneCol ()
void SetCurCollumn (DateTime t)
void SetNewTimeLeft (DateTime _timeLeft)
DateTime TimeLeft ()
DateTime TimeRight ()
Properties
Color PlotBackgroundColor [get]
int TimeRange [get, set]
Detailed Description
Definition at line 15 of file TimePlotParameters.cs.
Constructor & Destructor Documentation
SipperFile.TimePlotParameters.TimePlotParameters (Panel _panel, int[] _fieldIdxs, float[] _minValues, float[] _maxValues, float[] _rowScaleFactors, bool[] _plotDataSeries, SolidBrush[] _plotBrushes, DataSeries[] _plottedSeries) inline
Definition at line 86 of file TimePlotParameters.cs.
Member Function Documentation
void SipperFile.TimePlotParameters.ClearPlotArea () inline
Definition at line 167 of file TimePlotParameters.cs.
References SipperFile.TimePlotParameters.DrawXAxisWithLabels().
int SipperFile.TimePlotParameters.ComputeColFromTime (DateTime t) inline
Definition at line 197 of file TimePlotParameters.cs.
Referenced by SipperFile.TimePlotParameters.DrawXAxisWithLabels(), SipperFile.TimePlotParameters.MakeTimeVisible(), SipperFile.TimePlotParameters.ScrollPlotAreaRightOneCol(), and SipperFile.TimePlotParameters.SetCurCollumn().
DateTime SipperFile.TimePlotParameters.ComputeDateTimeFromPixelCol (int pixelCol) inline
Definition at line 377 of file TimePlotParameters.cs.
void SipperFile.TimePlotParameters.ComputeParameters () inline
Definition at line 132 of file TimePlotParameters.cs.
Referenced by SipperFile.TimePlotParameters.SetNewTimeLeft().
int SipperFile.TimePlotParameters.CurCol () inline
Definition at line 112 of file TimePlotParameters.cs.
void SipperFile.TimePlotParameters.DrawXAxisWithLabels () inline
Definition at line 220 of file TimePlotParameters.cs.
References SipperFile.TimePlotParameters.ComputeColFromTime().
Referenced by SipperFile.TimePlotParameters.ClearPlotArea().
void SipperFile.TimePlotParameters.MakeTimeVisible (DateTime t) inline
Definition at line 302 of file TimePlotParameters.cs.
References SipperFile.TimePlotParameters.ComputeColFromTime(), and SipperFile.TimePlotParameters.ScrollPlotAreaRightOneCol().
void SipperFile.TimePlotParameters.PaintSelectedLine (DateTime dt, Brush b) inline
Definition at line 365 of file TimePlotParameters.cs.
References SipperFile.TimePlotParameters.SetCurCollumn().
int SipperFile.TimePlotParameters.PlotBotRow () inline
Definition at line 52 of file TimePlotParameters.cs.
void SipperFile.TimePlotParameters.PlotDataRow (InstrumentData dr) inline
Definition at line 333 of file TimePlotParameters.cs.
References SipperFile.InstrumentData.Data(), SipperFile.TimePlotParameters.SetCurCollumn(), SipperFile.InstrumentData.Time, and x.
int SipperFile.TimePlotParameters.PlotTopRow () inline
Definition at line 51 of file TimePlotParameters.cs.
void SipperFile.TimePlotParameters.ScrollPlotAreaRightOneCol () inline
Definition at line 252 of file TimePlotParameters.cs.
References SipperFile.TimePlotParameters.ComputeColFromTime().
Referenced by SipperFile.TimePlotParameters.MakeTimeVisible().
void SipperFile.TimePlotParameters.SetCurCollumn (DateTime t) inline
Definition at line 325 of file TimePlotParameters.cs.
References SipperFile.TimePlotParameters.ComputeColFromTime().
Referenced by SipperFile.TimePlotParameters.PaintSelectedLine(), and SipperFile.TimePlotParameters.PlotDataRow().
void SipperFile.TimePlotParameters.SetNewTimeLeft (DateTime _timeLeft) inline
Definition at line 177 of file TimePlotParameters.cs.
References SipperFile.TimePlotParameters.ComputeParameters().
DateTime SipperFile.TimePlotParameters.TimeLeft () inline
Definition at line 113 of file TimePlotParameters.cs.
DateTime SipperFile.TimePlotParameters.TimeRight () inline
Definition at line 114 of file TimePlotParameters.cs.
Property Documentation
Color SipperFile.TimePlotParameters.PlotBackgroundColor get
Definition at line 81 of file TimePlotParameters.cs.
int SipperFile.TimePlotParameters.TimeRange get set
Definition at line 118 of file TimePlotParameters.cs.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperFile/TimePlotParameters.cs