Pices: MLL::MLClass Class Reference
MLL::MLClass Class Reference
Represents a "Class" in the Machine Learnining Sense.
#include <MLClass.h>
Public Types
typedef KKU::int32 int32
typedef KKU::uint32 uint32
Public Member Functions
int32 ClassId () const
void ClassId (int32 _classId)
void Description (const KKStr &_description)
const KKStr & Description () const
bool IsAnAncestor (MLClassConstPtr c) const
Returns true if 'c' is an ancestor.
MLClassPtr MLClassForGivenHierarchialLevel (KKU::uint16 level) const
const KKStr & Name () const
KKU::uint16 NumHierarchialLevels () const
MLClassConstPtr Parent () const
void Parent (MLClassConstPtr _parent)
const KKStr & ParentName () const
void ProcessRawData (KKStr &data)
Parses 'data' and populates this instance.
bool StoredOnDataBase () const
void StoredOnDataBase (bool _storedOnDataBase)
KKStr ToString () const
Returns a KKStr representing this instance.
bool UnDefined () const
void UnDefined (bool _unDefined)
const KKStr & UpperName () const
Returns name capitalized.
void WriteXML (std::ostream &o) const
Static Public Member Functions
static MLClassConstListPtr BuildListOfDecendents (MLClassConstPtr parent)
static void ChangeNameOfClass (MLClassPtr mlClass, const KKStr &newName, bool &successful)
Changes the name of an existing class verifying that a duplicate does not get created.
static MLClassPtr CreateNewMLClass (const KKStr &_name, int32 _classId=-1)
Static method used to create a new instance of a MLClass object.
static void FinalCleanUp ()
Call this as the last thing the application does, will delete all existing instances of 'MLClass'.
static MLClassConstPtr GetByClassId (int32 _classId)
static KKStr GetClassNameFromDirName (const KKStr &subDir)
static MLClassConstPtr GetUnKnownClassStatic ()
static MLClassListPtr GlobalClassList ()
static void ResetAllParentsToAllClasses ()
Friends
class KKQueue< MLClass >
class MLClassList
Detailed Description
Represents a "Class" in the Machine Learnining Sense.
Represents a "Class" in the Machine Learning Sense.
Author
Kurt Kramer
                          MLClass                                *
                                                                 *
Each instance of this class represents a single Class as used in *
Machine Learning sense.  Each instance of 'FeatureVector' class  *
will point to an instance of this class.  There can only be one  *
instance of each Class in memory.  Specifically the 'name' field *
will be unique.  This is enforced by making the constructor and  *
destructor private.  The only way to create a new instance of a  *
'MLClass' object is to call one of the the static methods of     *
'CreateNewMLClass'.  These methods will look for a instance   *
of 'MLClass' that already exists.  If one does not they will     *
then create a new one.                                           *
                                                                 *
Please refer to MLClassList at bottom of file.  That class is    *
the object you will most be using when dealing with Images.      *
classes.                                                         *
                                                                 *
PicesClass
There is a special relationship between this class  and a class  *
called 'PicesClass' in the 'PicesInterface' library'.  PicesClass*
is a managed c++ version of this class.  There is a one-to-one   *
correspondence between the two classes.  When ever a instance    *
of 'PicesClass' gets created it will automatically call the      *
the static method 'MLClass::CreateNewMLClass' to get the      *
unmanaged version of the class.                                  *
                                                                 *
                                                                 *
classId   - A unique number that is assigned by the Pices        *
            DataBase when a new class is added to it.            *
                                                                 *
name      - Name of class; This name will be unique for the      *
            process. Underscore characters have special meaning  *
            to several methods in PicesLibrary.  They help       *
            separate the name into multiple class levels.        *
                                                                 *
num       - Used by SVMModel when creating Training Models and   *
            Classifying an instance of a imageFeatures           *
                                                                 *
parent    - Pointer to a instance of 'MLClass' that is the       *
            parent to this instance. And example would be a      *
            class called 'Copepod_Calanoid' will have a parent   *
            called 'Copepod'.  The parent class to all classes   *
            is "AllClasses"                                      *
                                                                 *
unDefined - When set to true indicates that this class is not    *
            a Plankton or has not yet been classified as a       *
            Plankton.  This is set automatically when name is    *
            set. Names such as NOISE, UNKNOWN, UNDEFINED, NOISY, *
            and NONPLANKTON will be set to true  otherwise       *
            false.  The names are NOT case sensitive so for      *
            example  Noise, UnKnown, and noisy  would set  it    *
            false.                                               *
See Also
MLL::MLClassList, MLL::FeatureVector, PicesInterface::PicesClass
MLL::DataBase::MLClassLoad, MLL::DataBase::ImageInsert
Definition at line 91 of file MLClass.h.
Member Typedef Documentation
typedef KKU::int32 MLL::MLClass::int32
Definition at line 102 of file MLClass.h.
typedef KKU::uint32 MLL::MLClass::uint32
Definition at line 103 of file MLClass.h.
Member Function Documentation
MLClassConstListPtr MLClass::BuildListOfDecendents (MLClassConstPtr parent) static
Definition at line 151 of file MLClass.cpp.
References MLL::MLClassConstList::PushOnBack().
void MLClass::ChangeNameOfClass (MLClassPtr mlClass, const KKStr & newName, bool & successful) static
Changes the name of an existing class verifying that a duplicate does not get created.
Since the class name can not be duplicated and there are nameIndex structures maintained by each 'MLClassList' instances we need to make sure the name is not already in use by another instance of 'mlClass'. This is done by first trying to update the 'nameIndex' in 'existingMLClasses' (list of all 'inageClass' instances in existance); if tjs is sucessful will then change the name in 'mlClass' and update all existing 'MLClassList' instances 'nameIndex' structures.
Parameters
[in,out] mlClass Class having its name changed; upon entry should contain its original name; if no other class already has its name it will be updated to the value in 'newName'.
[in] newName The new name that 'mlClass' is to receive.
[in] successful Returns 'true' if name was changed; if set to false then the 'name' field in 'mlClass' will not be changed.
Definition at line 189 of file MLClass.cpp.
References KKU::endl().
int32 MLL::MLClass::ClassId () const inline
Definition at line 184 of file MLClass.h.
Referenced by CreateNewMLClass(), MLL::MLClassList::LookUpByClassId(), and MLL::DataBase::MLClassLoad().
void MLL::MLClass::ClassId (int32 _classId) inline
Definition at line 185 of file MLClass.h.
MLClassPtr MLClass::CreateNewMLClass (const KKStr & _name, int32 _classId = -1) static
Static method used to create a new instance of a MLClass object.
Used to get pointer to existing MLClass object that already      *
exists in 'existingMLClasses'.  If one does not exist then a new *
MLClass object with this name will be created.                   *
                                                                    *
This is the only method that can actually create a MLClass       *
instance.  The idea is that there is only one MLClass object     *
ever created for each class.  All MLClassList container objects  *
will point to instances that are in 'existingMLClasses.          *
Parameters
[in] _name Name of class to be created.
Returns
Pointer to an instance of 'MLClass' that will have the name '_name'.
Definition at line 106 of file MLClass.cpp.
References ClassId(), MLL::MLClassList::LookUpByName(), and KKU::KKStr::ToUpper().
Referenced by MLL::DataBaseImage::Class1Name(), MLL::DataBaseImage::Class2Name(), MLL::BinaryClassParms::CreateFromTabDelStr(), MLL::MLClassConstList::GetMLClassPtr(), MLL::MLClassList::GetMLClassPtr(), MLL::MLClassConstList::GetUnKnownClass(), MLL::MLClassList::GetUnKnownClass(), MLL::DataBase::ImagesRetrieveValidatedClass(), MLL::ClassAssignments::Load(), MLL::DataBaseImageValidatedEntryList::Load(), MLL::MLClassList::Load(), MLClassForGivenHierarchialLevel(), MLL::DataBase::MLClassLoad(), MLL::DataBase::MLClassLoadList(), MLL::ClassIndexList::ParseClassIndexList(), MLL::ClassAssignments::ParseToString(), MLL::TrainingProcess2::Read(), MLL::ModelParamDual::ReadSpecificImplementationXML(), MLL::ModelDual::ReconcilePredictions(), MLL::SipperExtractionImageManager::SaveFrame(), MLL::SipperExtractionImageManager::SipperExtractionImageManager(), and MLL::DataBaseImage::ValidatedClassName().
void MLL::MLClass::Description (const KKStr & _description) inline
Definition at line 187 of file MLClass.h.
Referenced by PicesInterface::PicesClass::CreateAUnManagedClass(), MLL::DataBase::MLClassInsert(), MLL::DataBase::MLClassLoad(), MLL::DataBase::MLClassLoadList(), and MLL::DataBase::MLClassUpdate().
const KKStr& MLL::MLClass::Description () const inline
Definition at line 189 of file MLClass.h.
void MLClass::FinalCleanUp () static
Call this as the last thing the application does, will delete all existing instances of 'MLClass'.
Call this at very end of program to clean up existingMLClasses.
Definition at line 276 of file MLClass.cpp.
MLClassConstPtr MLClass::GetByClassId (int32 _classId) static
Definition at line 143 of file MLClass.cpp.
KKStr MLClass::GetClassNameFromDirName (const KKStr & subDir) static
Definition at line 395 of file MLClass.cpp.
References KKU::KKStr::Len(), KKU::KKStr::LocateLastOccurrence(), KKU::osGetRootNameOfDirectory(), and KKU::KKStr::SubStrPart().
Referenced by MLL::FeatureFileIOPices::LoadInSubDirectoryTree().
MLClassConstPtr MLClass::GetUnKnownClassStatic () static
Definition at line 268 of file MLClass.cpp.
Referenced by MLL::FeatureFileIOPices::FeatureDataReSink(), and MLL::SipperExtractionImageManager::SaveFrame().
MLClassListPtr MLClass::GlobalClassList () static
Definition at line 55 of file MLClass.cpp.
bool MLClass::IsAnAncestor (MLClassConstPtr c) const
Returns true if 'c' is an ancestor.
Definition at line 428 of file MLClass.cpp.
MLClassPtr MLClass::MLClassForGivenHierarchialLevel (KKU::uint16 level) const
Definition at line 467 of file MLClass.cpp.
References CreateNewMLClass(), and KKU::KKStr::Split().
Referenced by MLL::MLClassList::ExtractListOfClassesForAGivenHierarchialLevel().
const KKStr& MLL::MLClass::Name () const inline
Definition at line 197 of file MLClass.h.
uint16 MLClass::NumHierarchialLevels () const
Definition at line 442 of file MLClass.cpp.
References KKU::KKStr::InstancesOfChar().
MLClassConstPtr MLL::MLClass::Parent () const inline
Definition at line 200 of file MLClass.h.
Referenced by PicesInterface::PicesClass::CreateAUnManagedClass(), MLL::DataBase::MLClassLoad(), PicesInterface::PicesClass::PicesClass(), and ResetAllParentsToAllClasses().
void MLL::MLClass::Parent (MLClassConstPtr _parent) inline
Definition at line 201 of file MLClass.h.
const KKStr & MLClass::ParentName () const
Definition at line 358 of file MLClass.cpp.
Referenced by MLL::DataBase::MLClassInsert(), MLL::DataBase::MLClassInsertReturn(), and MLL::DataBase::MLClassUpdate().
void MLClass::ProcessRawData (KKStr & data)
Parses 'data' and populates this instance.
Extracts name of class from first field in 'data' using whitespace ',', ' ', '
', '', or '' as delimiter. Data will have this name removed from the beginning of it.
Definition at line 377 of file MLClass.cpp.
References KKU::KKStr::Empty(), KKU::KKStr::ExtractToken(), KKU::KKStr::TrimLeft(), KKU::KKStr::TrimRight(), and KKU::KKStr::Upper().
void MLClass::ResetAllParentsToAllClasses () static
Definition at line 237 of file MLClass.cpp.
References MLL::globalClassList, MLL::MLClassList::LookUpByName(), and Parent().
Referenced by MLL::DataBase::MLClassLoadList().
bool MLL::MLClass::StoredOnDataBase () const inline
Definition at line 210 of file MLClass.h.
Referenced by MLL::DataBase::MLClassLoadList().
void MLL::MLClass::StoredOnDataBase (bool _storedOnDataBase) inline
Definition at line 212 of file MLClass.h.
KKStr MLClass::ToString () const
Returns a KKStr representing this instance.
This string will later be written to a file.
Definition at line 368 of file MLClass.cpp.
Referenced by MLL::MLClassList::Save().
bool MLL::MLClass::UnDefined () const inline
Definition at line 219 of file MLClass.h.
Referenced by MLL::MLClassList::GetNoiseClass(), MLL::MLClassList::Load(), and PicesInterface::PicesClass::PicesClass().
void MLL::MLClass::UnDefined (bool _unDefined) inline
Definition at line 221 of file MLClass.h.
const KKStr& MLL::MLClass::UpperName () const inline
Returns name capitalized.
Definition at line 198 of file MLClass.h.
Referenced by MLL::MLClassList::mlClassNameComparison::operator()(), MLL::MLClassList::PopFromBack(), and MLL::MLClassList::PopFromFront().
void MLClass::WriteXML (std::ostream & o) const
Definition at line 450 of file MLClass.cpp.
References KKU::endl(), and KKU::KKStr::QuotedStr().
Friends And Related Function Documentation
friend class KKQueue< MLClass > friend
Definition at line 166 of file MLClass.h.
friend class MLClassList friend
Definition at line 167 of file MLClass.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/MLClass.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/MLClass.cpp