Pices: MLL::ImageFeaturesNodeKey Class Reference
MLL::ImageFeaturesNodeKey Class Reference
#include <ImageFeaturesDataIndexed.h>
Public Member Functions
ImageFeaturesNodeKey (FeatureVectorPtr _image)
int32 CompareTwoImages (const FeatureVectorPtr i1, const FeatureVectorPtr i2) const
bool operator< (const ImageFeaturesNodeKey &rightNode) const
bool operator== (const ImageFeaturesNodeKey &rightNode) const
bool operator> (const ImageFeaturesNodeKey &rightNode) const
Public Attributes
FeatureVectorPtr image
Detailed Description
Definition at line 53 of file ImageFeaturesDataIndexed.h.
Constructor & Destructor Documentation
ImageFeaturesNodeKey::ImageFeaturesNodeKey (FeatureVectorPtr _image)
Definition at line 96 of file ImageFeaturesDataIndexed.cpp.
Member Function Documentation
int32 ImageFeaturesNodeKey::CompareTwoImages (const FeatureVectorPtr i1, const FeatureVectorPtr i2) const
Definition at line 121 of file ImageFeaturesDataIndexed.cpp.
References MLL::FeatureVector::FeatureDataConst(), MLL::FeatureVector::NumOfFeatures(), and x.
Referenced by operator<(), operator==(), and operator>().
bool ImageFeaturesNodeKey::operator< (const ImageFeaturesNodeKey & rightNode) const
Definition at line 109 of file ImageFeaturesDataIndexed.cpp.
References CompareTwoImages(), and image.
bool ImageFeaturesNodeKey::operator== (const ImageFeaturesNodeKey & rightNode) const
Definition at line 104 of file ImageFeaturesDataIndexed.cpp.
References CompareTwoImages(), and image.
bool ImageFeaturesNodeKey::operator> (const ImageFeaturesNodeKey & rightNode) const
Definition at line 114 of file ImageFeaturesDataIndexed.cpp.
References CompareTwoImages(), and image.
Member Data Documentation
FeatureVectorPtr MLL::ImageFeaturesNodeKey::image
Definition at line 66 of file ImageFeaturesDataIndexed.h.
Referenced by operator<(), operator==(), and operator>().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ImageFeaturesDataIndexed.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ImageFeaturesDataIndexed.cpp