Pices: MLL::ClassificationBiasMatrix Class Reference
MLL::ClassificationBiasMatrix Class Reference
Assists in adjusting a Classifiers output for the bias of a classifier.
#include <ClassificationBiasMatrix.h>
Public Types
typedef ClassificationBiasMatrix * ClassificationBiasMatrixPtr
typedef KKU::DateTime DateTime
typedef KKU::KKStr KKStr
typedef KKU::Matrix Matrix
typedef KKU::MatrixPtr MatrixPtr
typedef KKU::RunLog RunLog
Public Member Functions
ClassificationBiasMatrix (RunLog &_runLog)
Will construct an instance as defined in the Paper.
ClassificationBiasMatrix (const ClassificationBiasMatrix &cbm)
ClassificationBiasMatrix (MLClassConstList &classes, RunLog &_runLog)
ClassificationBiasMatrix (const KKStr &_configFileName, MLClassConstList &_classes, RunLog &_runLog)
Construct a ClassificationBiasMatrix instance from from the parameter file for '_configFileName'.
ClassificationBiasMatrix (const ConfusionMatrix2 &cm, RunLog &_runLog)
Construct a ClassificationBiasMatrix instance from a ConfusionMatrix object.
~ClassificationBiasMatrix ()
DateTime DateTimeFileWritten () const
void PerformAdjustmnts (const VectorDouble &classifiedCounts, VectorDouble &adjCounts, VectorDouble &stdErrors)
void PrintAdjustedResults (ostream &sw, const VectorDouble &classifiedCounts)
void PrintBiasMatrix (ostream &sw)
void TestPaperResults (ostream &sw)
void WriteXML (ostream &o)
Static Public Member Functions
static ClassificationBiasMatrixPtr BuildFromIstreamXML (istream &f, MLClassConstList &classes, RunLog &log)
Will construct a ClassificationBiasMatrix instance from a input stream.
Detailed Description
Assists in adjusting a Classifiers output for the bias of a classifier.
See the paper:
"Estimating the Taxonomic composition of a sample when individuals are classified with error"
by Andrew Solow, Cabll Davis, Qiao Hu
Woods Hole Oceanographic Institution, Woods Hole Massachusetts
Marine Ecology Progress Series
published 2006-july-06;  vol 216:309-311
This class uses the results of a previous 10 fold cross validation confusion matrix to adjust the results of a classification run. The application CrossValidation will create a parameter file in the directory "${PicesHomeDir}\\DataFiles\\TrainingModels" that contains the confusion matrix. The option "-BiasMatrix" tells the CrossValidation program to generate this parameter file. It will have the same name as the Configuration file with the extension ".BiasMatrix.txt" appended to the end. There is a managed version of this class in PicesInterface called PicesInterface::ClassificationBiasMatrix
Definition at line 43 of file ClassificationBiasMatrix.h.
Member Typedef Documentation
typedef ClassificationBiasMatrix* MLL::ClassificationBiasMatrix::ClassificationBiasMatrixPtr
Definition at line 46 of file ClassificationBiasMatrix.h.
typedef KKU::DateTime MLL::ClassificationBiasMatrix::DateTime
Definition at line 50 of file ClassificationBiasMatrix.h.
typedef KKU::KKStr MLL::ClassificationBiasMatrix::KKStr
Definition at line 49 of file ClassificationBiasMatrix.h.
typedef KKU::Matrix MLL::ClassificationBiasMatrix::Matrix
Definition at line 51 of file ClassificationBiasMatrix.h.
typedef KKU::MatrixPtr MLL::ClassificationBiasMatrix::MatrixPtr
Definition at line 52 of file ClassificationBiasMatrix.h.
typedef KKU::RunLog MLL::ClassificationBiasMatrix::RunLog
Definition at line 48 of file ClassificationBiasMatrix.h.
Constructor & Destructor Documentation
ClassificationBiasMatrix::ClassificationBiasMatrix (RunLog & _runLog)
Will construct an instance as defined in the Paper.
Definition at line 159 of file ClassificationBiasMatrix.cpp.
Referenced by BuildFromIstreamXML().
ClassificationBiasMatrix::ClassificationBiasMatrix (const ClassificationBiasMatrix & cbm)
Definition at line 84 of file ClassificationBiasMatrix.cpp.
ClassificationBiasMatrix::ClassificationBiasMatrix (MLClassConstList & classes, RunLog & _runLog)
Definition at line 136 of file ClassificationBiasMatrix.cpp.
ClassificationBiasMatrix::ClassificationBiasMatrix (const KKStr & _configFileName, MLClassConstList & _classes, RunLog & _runLog)
Construct a ClassificationBiasMatrix instance from from the parameter file for '_configFileName'.
Parameters
[in] _configFileName The name of the BiasMatrix file will be derived from the configuration file name. the term '_BiasMatrix.txt' will be appended onto the end.
[in] _classes List of classes that you are expecting to be in the 'BiasMatrix' file.
[in,out] _runLog Logging file to use.
Definition at line 34 of file ClassificationBiasMatrix.cpp.
References KKU::osRemoveExtension(), and KKU::KKStr::Str().
ClassificationBiasMatrix::ClassificationBiasMatrix (const ConfusionMatrix2 & cm, RunLog & _runLog)
Construct a ClassificationBiasMatrix instance from a ConfusionMatrix object.
Parameters
[in] cm Confusion Matrix to get parameters from.
[in,out] _runLog Logging file to use.
Definition at line 112 of file ClassificationBiasMatrix.cpp.
References MLL::ConfusionMatrix2::MLClasses().
ClassificationBiasMatrix::~ClassificationBiasMatrix ()
Definition at line 183 of file ClassificationBiasMatrix.cpp.
Member Function Documentation
ClassificationBiasMatrixPtr ClassificationBiasMatrix::BuildFromIstreamXML (istream & f, MLClassConstList & classes, RunLog & log) static
Will construct a ClassificationBiasMatrix instance from a input stream.
Parameters
[in] f Input Stream.
[in] classes List of classes we expect to find in the input stream f.
[in,out] log Logging File.
Definition at line 195 of file ClassificationBiasMatrix.cpp.
References ClassificationBiasMatrix().
DateTime MLL::ClassificationBiasMatrix::DateTimeFileWritten () const inline
Definition at line 104 of file ClassificationBiasMatrix.h.
void MLL::ClassificationBiasMatrix::PerformAdjustmnts (const VectorDouble & classifiedCounts, VectorDouble & adjCounts, VectorDouble & stdErrors)
void MLL::ClassificationBiasMatrix::PrintAdjustedResults (ostream & sw, const VectorDouble & classifiedCounts)
void MLL::ClassificationBiasMatrix::PrintBiasMatrix (ostream & sw)
void MLL::ClassificationBiasMatrix::TestPaperResults (ostream & sw)
void ClassificationBiasMatrix::WriteXML (ostream & o)
Definition at line 490 of file ClassificationBiasMatrix.cpp.
References KKU::endl(), KKU::RunLog::Level(), KKU::Matrix::NumOfRows(), KKU::StrFormatDouble(), and MLL::MLClassConstList::ToCommaDelimitedStr().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ClassificationBiasMatrix.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ClassificationBiasMatrix.cpp
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/ClassificationBiasMatrix.cpp