Pices: SipperFile.InstrumentDataList Class Reference
SipperFile.InstrumentDataList Class Reference
Summary description for DataRowList.
Public Types
enum DataOrder { DataOrder.NoOrder, DataOrder.TimeOrder, DataOrder.DepthOrder }
Public Member Functions
InstrumentDataList ()
InstrumentDataList (PicesInstrumentDataList dbInstData)
Will cunstruct a InstrumentDataList from a PicesInstrumenDataBase.
InstrumentDataList (string _fileName, StreamWriter logFile)
virtual int Add (InstrumentData row)
void CalcMinMaxValues (DateTime startTime, DateTime endTime)
InstrumentData CurrentDataRow ()
DataOrder CurrentOrder ()
float DepthMax ()
float DepthMin ()
void Dispose ()
InstrumentData FindClosestEntryByTime (DateTime date)
int GetByTimeGreaterOrEqual (DateTime t)
float[] MaxValues ()
float[] MinValues ()
void Save (string _fileName)
void SortByDepth ()
void SortByTime ()
void StartNewDataFile (string sipperFileName)
DateTime TimeMax ()
DateTime TimeMin ()
Detailed Description
Summary description for DataRowList.
Definition at line 15 of file InstrumentDataList.cs.
Member Enumeration Documentation
enum SipperFile.InstrumentDataList.DataOrder
Enumerator
NoOrder
TimeOrder
DepthOrder
Definition at line 17 of file InstrumentDataList.cs.
Constructor & Destructor Documentation
SipperFile.InstrumentDataList.InstrumentDataList () inline
Definition at line 51 of file InstrumentDataList.cs.
SipperFile.InstrumentDataList.InstrumentDataList (PicesInstrumentDataList dbInstData) inline
Will cunstruct a InstrumentDataList from a PicesInstrumenDataBase.
Keep in kind that PicesInstrumentData is a managed wrapper class for the unmanaged class 'InstrumentData' from the 'SipperInstruments' library.
Parameters
dbInstData
Definition at line 66 of file InstrumentDataList.cs.
References SipperFile.InstrumentDataList.Add().
SipperFile.InstrumentDataList.InstrumentDataList (string _fileName, StreamWriter logFile) inline
Definition at line 79 of file InstrumentDataList.cs.
Member Function Documentation
virtual int SipperFile.InstrumentDataList.Add (InstrumentData row) inline virtual
Definition at line 399 of file InstrumentDataList.cs.
References SipperFile.InstrumentData.Depth(), SipperFile.InstrumentData.Time, and SipperFile.InstrumentData.WriteLine().
Referenced by SipperFile.InstrumentDataList.InstrumentDataList().
void SipperFile.InstrumentDataList.CalcMinMaxValues (DateTime startTime, DateTime endTime) inline
Definition at line 443 of file InstrumentDataList.cs.
References SipperFile.InstrumentData.Data(), SipperFile.InstrumentData.NumDataFields(), SipperFile.InstrumentData.Time, and x.
Referenced by SipperFile.DepthPlot2.DepthPlot2().
InstrumentData SipperFile.InstrumentDataList.CurrentDataRow () inline
Definition at line 428 of file InstrumentDataList.cs.
DataOrder SipperFile.InstrumentDataList.CurrentOrder () inline
Definition at line 136 of file InstrumentDataList.cs.
float SipperFile.InstrumentDataList.DepthMax () inline
Definition at line 44 of file InstrumentDataList.cs.
float SipperFile.InstrumentDataList.DepthMin () inline
Definition at line 43 of file InstrumentDataList.cs.
void SipperFile.InstrumentDataList.Dispose () inline
Definition at line 377 of file InstrumentDataList.cs.
References x.
InstrumentData SipperFile.InstrumentDataList.FindClosestEntryByTime (DateTime date) inline
Definition at line 542 of file InstrumentDataList.cs.
References SipperFile.InstrumentData.Time.
int SipperFile.InstrumentDataList.GetByTimeGreaterOrEqual (DateTime t) inline
Definition at line 279 of file InstrumentDataList.cs.
References SipperFile.InstrumentDataList.SortByTime(), and SipperFile.InstrumentData.Time.
float [] SipperFile.InstrumentDataList.MaxValues () inline
Definition at line 33 of file InstrumentDataList.cs.
Referenced by SipperFile.DepthPlot2.DepthPlot2().
float [] SipperFile.InstrumentDataList.MinValues () inline
Definition at line 32 of file InstrumentDataList.cs.
Referenced by SipperFile.DepthPlot2.DepthPlot2().
void SipperFile.InstrumentDataList.Save (string _fileName) inline
Definition at line 344 of file InstrumentDataList.cs.
References SipperFile.InstrumentData.CreateCurrentFieldIndexList(), SipperFile.InstrumentData.WriteFieldList(), SipperFile.InstrumentData.WriteLine(), and x.
void SipperFile.InstrumentDataList.SortByDepth () inline
Definition at line 532 of file InstrumentDataList.cs.
void SipperFile.InstrumentDataList.SortByTime () inline
Definition at line 522 of file InstrumentDataList.cs.
Referenced by SipperFile.InstrumentDataList.GetByTimeGreaterOrEqual().
void SipperFile.InstrumentDataList.StartNewDataFile (string sipperFileName) inline
Definition at line 104 of file InstrumentDataList.cs.
DateTime SipperFile.InstrumentDataList.TimeMax () inline
Definition at line 47 of file InstrumentDataList.cs.
DateTime SipperFile.InstrumentDataList.TimeMin () inline
Definition at line 46 of file InstrumentDataList.cs.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperFile/InstrumentDataList.cs