Pices: KKU::Configuration::SettingList Class Reference
KKU::Configuration::SettingList Class Reference
Public Member Functions
SettingList ()
SettingList (const SettingList &sl)
void AddSetting (SettingPtr setting)
void AddSetting (const KKStr &_name, const KKStr &_value, int32 _lineNum)
SettingPtr LookUp (const KKStr &name)
int32 LookUpLineNum (const KKStr &name) const
int32 MemoryConsumedEstimated () const
Detailed Description
Definition at line 62 of file Configuration.cpp.
Constructor & Destructor Documentation
KKU::Configuration::SettingList::SettingList () inline
Definition at line 65 of file Configuration.cpp.
KKU::Configuration::SettingList::SettingList (const SettingList & sl) inline
Definition at line 67 of file Configuration.cpp.
References x.
Member Function Documentation
void KKU::Configuration::SettingList::AddSetting (SettingPtr setting) inline
Definition at line 120 of file Configuration.cpp.
void KKU::Configuration::SettingList::AddSetting (const KKStr & _name, const KKStr & _value, int32 _lineNum) inline
Definition at line 126 of file Configuration.cpp.
SettingPtr KKU::Configuration::SettingList::LookUp (const KKStr & name) inline
Definition at line 88 of file Configuration.cpp.
References KKU::KKStr::EqualIgnoreCase(), and KKU::Configuration::Setting::Name().
int32 KKU::Configuration::SettingList::LookUpLineNum (const KKStr & name) const inline
Definition at line 107 of file Configuration.cpp.
References KKU::Configuration::Setting::LineNum(), and KKU::Configuration::Setting::Name().
int32 KKU::Configuration::SettingList::MemoryConsumedEstimated () const inline
Definition at line 78 of file Configuration.cpp.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Configuration.cpp