Pices: SipperFile.Sipper3DecodeRec Class Reference
SipperFile.Sipper3DecodeRec Class Reference
This class aids in the decoding of SIPPER 3 data files.
Public Member Functions
Sipper3DecodeRec (ushort d)
Sipper3DecodeRec Constructor.
void AddToScanLine (byte[] scanLine, ref int idx)
Add the image data stored in the SIPPER 3 data record to a scanLine.
void Dispose ()
bool Eol ()
bool GrayScale ()
bool ImageData ()
int PixelSpaceNeeded ()
determines the number of pixels that will be needed in the scan line to accomidate this decoded SipperRec.
char SensorData ()
byte SensorNum ()
bool Text ()
Detailed Description
This class aids in the decoding of SIPPER 3 data files.
For each record extracted from the SIPPEr file you create an instance of this class. You can then use the provide access methods to retrieve the decoded version. 'Sipper3File' will create an array of these classes. One for each possible bit combination (65536).
Definition at line 13 of file Sipper3DecodeRec.cs.
Constructor & Destructor Documentation
SipperFile.Sipper3DecodeRec.Sipper3DecodeRec (ushort d) inline
Sipper3DecodeRec Constructor.
Will decode 'd' parameter.Sipper3DecodeRec class.
Parameters
d An unsigned short that represents a Sipper3File record.
Definition at line 47 of file Sipper3DecodeRec.cs.
References x.
Member Function Documentation
void SipperFile.Sipper3DecodeRec.AddToScanLine (byte[] scanLine, ref int idx) inline
Add the image data stored in the SIPPER 3 data record to a scanLine.
If the SIPPER3 rec a Instrument data record then nothing will happen. The 'idx' parameter will be adjused t its new position,
Parameters
scanLine Scanline to add image data to.
idx The next index in ScanLin to append image data to.
Definition at line 200 of file Sipper3DecodeRec.cs.
References x.
Referenced by SipperFile.Sipper3File.ReadNextScanLine().
void SipperFile.Sipper3DecodeRec.Dispose () inline
Definition at line 106 of file Sipper3DecodeRec.cs.
bool SipperFile.Sipper3DecodeRec.Eol () inline
Definition at line 35 of file Sipper3DecodeRec.cs.
Referenced by SipperFile.Sipper3File.LengthNextScanLine(), SipperFile.Sipper3File.ReadNextScanLine(), and SipperFile.Sipper3File.SkipNextScanLine().
bool SipperFile.Sipper3DecodeRec.GrayScale () inline
Definition at line 37 of file Sipper3DecodeRec.cs.
Referenced by SipperFile.Sipper3File.ReadNextScanLine().
bool SipperFile.Sipper3DecodeRec.ImageData () inline
Definition at line 36 of file Sipper3DecodeRec.cs.
Referenced by SipperFile.Sipper3File.LengthNextScanLine(), SipperFile.Sipper3File.ReadNextScanLine(), SipperFile.Sipper3File.SaveRawCtdData(), and SipperFile.Sipper3File.SkipNextScanLine().
int SipperFile.Sipper3DecodeRec.PixelSpaceNeeded () inline
determines the number of pixels that will be needed in the scan line to accomidate this decoded SipperRec.
You would call this method before calling 'AddToScanLine' to make sure there is enough romm in can line. AddToScanLine
Returns
Number of pixels required on scan line.
Definition at line 179 of file Sipper3DecodeRec.cs.
Referenced by SipperFile.Sipper3File.LengthNextScanLine().
char SipperFile.Sipper3DecodeRec.SensorData () inline
Definition at line 38 of file Sipper3DecodeRec.cs.
Referenced by SipperFile.InstrumentDataManager.ReportData(), and SipperFile.Sipper3File.SaveRawCtdData().
byte SipperFile.Sipper3DecodeRec.SensorNum () inline
Definition at line 39 of file Sipper3DecodeRec.cs.
Referenced by SipperFile.InstrumentDataManager.ReportData(), and SipperFile.Sipper3File.SaveRawCtdData().
bool SipperFile.Sipper3DecodeRec.Text () inline
Definition at line 40 of file Sipper3DecodeRec.cs.
Referenced by SipperFile.InstrumentDataManager.ReportData(), and SipperFile.Sipper3File.SaveRawCtdData().
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperFile/Sipper3DecodeRec.cs