Pices: JobManagment::JobList Class Reference
JobManagment::JobList Class Reference
#include <Job.h>
Public Types
typedef JobList * JobListPtr
Public Member Functions
JobList (const JobList &jobs)
JobList (JobManagerPtr _manager)
JobList (JobManagerPtr _manager, KKStr _fileName)
bool AllPrequisitesDone (JobPtr job)
bool AreAllJobsDone ()
bool JobsStillRunning ()
JobPtr LocateOpenJob ()
RunLog & Log ()
JobPtr LookUpByJobId (int jobId)
void PushOnBack (JobPtr j)
Detailed Description
Definition at line 206 of file Job.h.
Member Typedef Documentation
typedef JobList* JobManagment::JobList::JobListPtr
Definition at line 209 of file Job.h.
Constructor & Destructor Documentation
JobList::JobList (const JobList & jobs)
Definition at line 354 of file Job.cpp.
References JobManagment::Job::Duplicate(), and PushOnBack().
JobList::JobList (JobManagerPtr _manager)
Definition at line 343 of file Job.cpp.
JobManagment::JobList::JobList (JobManagerPtr _manager, KKStr _fileName)
Member Function Documentation
bool JobList::AllPrequisitesDone (JobPtr job)
Definition at line 388 of file Job.cpp.
References JobManagment::Job::jsDone, JobManagment::Job::jsExpanded, LookUpByJobId(), JobManagment::Job::Prerequisites(), and JobManagment::Job::Status().
bool JobList::AreAllJobsDone ()
Definition at line 420 of file Job.cpp.
References JobManagment::Job::jsDone, JobManagment::Job::jsExpanded, JobManagment::Job::Status(), and x.
Referenced by JobManagment::JobManager::AreAllJobsDone().
bool JobList::JobsStillRunning ()
Definition at line 466 of file Job.cpp.
References JobManagment::Job::jsStarted, and JobManagment::Job::Status().
Referenced by JobManagment::JobManager::Run().
JobPtr JobList::LocateOpenJob ()
Definition at line 404 of file Job.cpp.
References JobManagment::Job::jsOpen, JobManagment::Job::Status(), and x.
RunLog& JobManagment::JobList::Log () inline
Definition at line 227 of file Job.h.
JobPtr JobList::LookUpByJobId (int jobId)
Definition at line 375 of file Job.cpp.
Referenced by AllPrequisitesDone(), JobManagment::JobManager::StatusFileProcessLine(), and JobManagment::JobManager::StatusFileProcessLineJobStatusChange().
void JobList::PushOnBack (JobPtr j)
Definition at line 440 of file Job.cpp.
References KKU::endl(), JobManagment::Job::JobId(), KKU::RunLog::Level(), and KKU::osWaitForEnter().
Referenced by JobList(), JobManagment::JobManager::Run(), and JobManagment::JobManager::StatusFileProcessLine().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/JobManager/Job.h
D:/Users/kkramer/IEC/SipperSoftware/JobManager/Job.cpp