Pices: KKU::KKStrList Class Reference
KKU::KKStrList Class Reference
#include <Str.h>
Classes
class StringComparison
Public Types
typedef KKStrList * KKStrListPtr
Public Member Functions
KKStrList (bool owner=false, int32 initSize=5)
KKStrList (const char *s[])
Creates a list from a NULL terminated list of (char*) strings.
void AddString (KKStrPtr str)
KKStrPtr BinarySearch (const KKStr &searchStr)
KKStrListPtr DuplicateListAndContents () const
int32 MemoryConsumedEstimated () const
void Sort (bool _reversedOrder)
bool StringInList (KKStr &str)
Static Public Member Functions
static KKStrListPtr ParseDelimitedString (const KKStr &str, const char *delChars=",\t\n\r")
Detailed Description
Definition at line 782 of file Str.h.
Member Typedef Documentation
typedef KKStrList* KKU::KKStrList::KKStrListPtr
Definition at line 785 of file Str.h.
Constructor & Destructor Documentation
KKStrList::KKStrList (bool owner = false, int32 initSize = 5)
Definition at line 3960 of file Str.cpp.
Referenced by DuplicateListAndContents(), MemoryConsumedEstimated(), and ParseDelimitedString().
KKStrList::KKStrList (const char * s[])
Creates a list from a NULL terminated list of (char*) strings.
The last entry in the list has to be NULL.
const char* zed[] = {"This", "is", "a", "test", NULL};
KKStrList  wordList (zed);
Definition at line 3969 of file Str.cpp.
References x.
Member Function Documentation
void KKStrList::AddString (KKStrPtr str)
Definition at line 4059 of file Str.cpp.
KKStrPtr KKStrList::BinarySearch (const KKStr & searchStr)
Definition at line 4012 of file Str.cpp.
References KKU::endl().
KKStrListPtr KKStrList::DuplicateListAndContents () const
Definition at line 4187 of file Str.cpp.
References KKStrList().
int32 KKStrList::MemoryConsumedEstimated () const
Definition at line 3987 of file Str.cpp.
References KKStrList().
KKStrListPtr KKStrList::ParseDelimitedString (const KKStr & str, const char * delChars = ",\t\n\r") static
Definition at line 4067 of file Str.cpp.
References KKStrList(), KKU::KKStr::Str(), and KKU::KKStr::TrimRight().
void KKStrList::Sort (bool _reversedOrder)
Definition at line 4178 of file Str.cpp.
Referenced by MLL::FeatureFileIOPices::FeatureDataReSink().
bool KKStrList::StringInList (KKStr & str)
Definition at line 3998 of file Str.cpp.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Str.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Str.cpp