Pices: SipperHardware::CTD_Plus_Data Class Reference
SipperHardware::CTD_Plus_Data Class Reference
#include <CTD_Plus_Data.h>
Public Types
typedef KKU::int32 int32
typedef KKU::int64 int64
typedef KKU::uint32 uint32
typedef KKU::uint64 uint64
Public Member Functions
CTD_Plus_Data (bool _checkCDOM)
CTD_Plus_Data (const KKStr &_txt, double _latitude, bool &valid, const KKStr &ext0CCode, const KKStr &ext1CCode, const KKStr &ext2CCode, const KKStr &ext3CCode)
~CTD_Plus_Data ()
float BatteryVoltage () const
float CdomFluorescence () const
float CdomFluorescenceSensor () const
float Conductivity () const
const KKU::DateTime & Date () const
float Density () const
float Depth () const
float Fluorescence () const
float FluorescenceSensor () const
CTD_Plus_Data & operator= (const CTD_Plus_Data &right)
float Oxygen () const
float OxygenSensor () const
float Pressure () const
float Salinity () const
float SoundVelocity () const
float Temperature () const
KKStr ToStrNoLabels () const
float Transmisivity () const
float TransmisivitySensor () const
float Turbidity () const
float TurbiditySensor () const
bool ValidData () const
Returns 'true' if the CTD data fields appear to be valid.
Static Public Member Functions
static KKStr Header1Str ()
static KKStr Header2Str ()
Detailed Description
Definition at line 11 of file CTD_Plus_Data.h.
Member Typedef Documentation
typedef KKU::int32 SipperHardware::CTD_Plus_Data::int32
Definition at line 14 of file CTD_Plus_Data.h.
typedef KKU::int64 SipperHardware::CTD_Plus_Data::int64
Definition at line 16 of file CTD_Plus_Data.h.
typedef KKU::uint32 SipperHardware::CTD_Plus_Data::uint32
Definition at line 15 of file CTD_Plus_Data.h.
typedef KKU::uint64 SipperHardware::CTD_Plus_Data::uint64
Definition at line 17 of file CTD_Plus_Data.h.
Constructor & Destructor Documentation
CTD_Plus_Data::CTD_Plus_Data (bool _checkCDOM)
Definition at line 32 of file CTD_Plus_Data.cpp.
CTD_Plus_Data::CTD_Plus_Data (const KKStr & _txt, double _latitude, bool & valid, const KKStr & ext0CCode, const KKStr & ext1CCode, const KKStr & ext2CCode, const KKStr & ext3CCode)
Definition at line 134 of file CTD_Plus_Data.cpp.
References KKU::DateType::Day(), KKU::KKStr::Empty(), KKU::DateType::Month(), KKU::KKStr::Split(), ToFloat(), x, and KKU::DateType::Year().
CTD_Plus_Data::~CTD_Plus_Data ()
Definition at line 543 of file CTD_Plus_Data.cpp.
Member Function Documentation
float SipperHardware::CTD_Plus_Data::BatteryVoltage () const inline
Definition at line 33 of file CTD_Plus_Data.h.
Referenced by SipperHardware::InstrumentDataManager::CreateInstrumentData(), and SipperHardware::InstrumentData::UpdateFromCtdData().
float SipperHardware::CTD_Plus_Data::CdomFluorescence () const inline
Definition at line 41 of file CTD_Plus_Data.h.
Referenced by SipperHardware::InstrumentDataManager::CreateInstrumentData(), and SipperHardware::InstrumentData::UpdateFromCtdData().
float SipperHardware::CTD_Plus_Data::CdomFluorescenceSensor () const inline
Definition at line 42 of file CTD_Plus_Data.h.
Referenced by SipperHardware::InstrumentDataManager::CreateInstrumentData(), and SipperHardware::InstrumentData::UpdateFromCtdData().
float SipperHardware::CTD_Plus_Data::Conductivity () const inline
Definition at line 34 of file CTD_Plus_Data.h.
Referenced by SipperHardware::InstrumentDataManager::CreateInstrumentData(), and SipperHardware::InstrumentData::UpdateFromCtdData().
const KKU::DateTime& SipperHardware::CTD_Plus_Data::Date () const inline
Definition at line 36 of file CTD_Plus_Data.h.
Referenced by SipperHardware::InstrumentDataManager::CompReportLine(), and SipperHardware::InstrumentDataManager::CreateInstrumentData().
float SipperHardware::CTD_Plus_Data::Density () const inline
Definition at line 37 of file CTD_Plus_Data.h.
Referenced by SipperHardware::InstrumentDataManager::CreateInstrumentData(), and SipperHardware::InstrumentData::UpdateFromCtdData().
float SipperHardware::CTD_Plus_Data::Depth () const inline
Definition at line 38 of file CTD_Plus_Data.h.
Referenced by SipperHardware::InstrumentDataManager::CompReportLine(), SipperHardware::InstrumentDataManager::CreateInstrumentData(), and SipperHardware::InstrumentData::UpdateFromCtdData().
float SipperHardware::CTD_Plus_Data::Fluorescence () const inline
Definition at line 39 of file CTD_Plus_Data.h.
Referenced by SipperHardware::InstrumentDataManager::CreateInstrumentData(), and SipperHardware::InstrumentData::UpdateFromCtdData().
float SipperHardware::CTD_Plus_Data::FluorescenceSensor () const inline
Definition at line 40 of file CTD_Plus_Data.h.
Referenced by SipperHardware::InstrumentDataManager::CreateInstrumentData(), and SipperHardware::InstrumentData::UpdateFromCtdData().
KKStr CTD_Plus_Data::Header1Str () static
Definition at line 591 of file CTD_Plus_Data.cpp.
Referenced by SipperHardware::InstrumentDataManager::InstrumentDataManager().
KKStr CTD_Plus_Data::Header2Str () static
Definition at line 620 of file CTD_Plus_Data.cpp.
Referenced by SipperHardware::InstrumentDataManager::InstrumentDataManager().
CTD_Plus_Data & CTD_Plus_Data::operator= (const CTD_Plus_Data & right)
Definition at line 549 of file CTD_Plus_Data.cpp.
float SipperHardware::CTD_Plus_Data::Oxygen () const inline
Definition at line 43 of file CTD_Plus_Data.h.
Referenced by SipperHardware::InstrumentDataManager::CreateInstrumentData(), and SipperHardware::InstrumentData::UpdateFromCtdData().
float SipperHardware::CTD_Plus_Data::OxygenSensor () const inline
Definition at line 44 of file CTD_Plus_Data.h.
Referenced by SipperHardware::InstrumentDataManager::CreateInstrumentData(), and SipperHardware::InstrumentData::UpdateFromCtdData().
float SipperHardware::CTD_Plus_Data::Pressure () const inline
Definition at line 45 of file CTD_Plus_Data.h.
Referenced by SipperHardware::InstrumentDataManager::CreateInstrumentData(), and SipperHardware::InstrumentData::UpdateFromCtdData().
float SipperHardware::CTD_Plus_Data::Salinity () const inline
Definition at line 46 of file CTD_Plus_Data.h.
Referenced by SipperHardware::InstrumentDataManager::CreateInstrumentData(), and SipperHardware::InstrumentData::UpdateFromCtdData().
float SipperHardware::CTD_Plus_Data::SoundVelocity () const inline
Definition at line 47 of file CTD_Plus_Data.h.
Referenced by SipperHardware::InstrumentDataManager::CreateInstrumentData(), and SipperHardware::InstrumentData::UpdateFromCtdData().
float SipperHardware::CTD_Plus_Data::Temperature () const inline
Definition at line 48 of file CTD_Plus_Data.h.
Referenced by SipperHardware::InstrumentDataManager::CreateInstrumentData(), and SipperHardware::InstrumentData::UpdateFromCtdData().
KKStr CTD_Plus_Data::ToStrNoLabels () const
Definition at line 648 of file CTD_Plus_Data.cpp.
References KKU::StrFormatDouble().
Referenced by SipperHardware::InstrumentDataManager::CompReportLine().
float SipperHardware::CTD_Plus_Data::Transmisivity () const inline
Definition at line 49 of file CTD_Plus_Data.h.
Referenced by SipperHardware::InstrumentDataManager::CreateInstrumentData(), and SipperHardware::InstrumentData::UpdateFromCtdData().
float SipperHardware::CTD_Plus_Data::TransmisivitySensor () const inline
Definition at line 50 of file CTD_Plus_Data.h.
Referenced by SipperHardware::InstrumentDataManager::CreateInstrumentData(), and SipperHardware::InstrumentData::UpdateFromCtdData().
float SipperHardware::CTD_Plus_Data::Turbidity () const inline
Definition at line 51 of file CTD_Plus_Data.h.
Referenced by SipperHardware::InstrumentDataManager::CreateInstrumentData(), and SipperHardware::InstrumentData::UpdateFromCtdData().
float SipperHardware::CTD_Plus_Data::TurbiditySensor () const inline
Definition at line 52 of file CTD_Plus_Data.h.
Referenced by SipperHardware::InstrumentDataManager::CreateInstrumentData(), and SipperHardware::InstrumentData::UpdateFromCtdData().
bool CTD_Plus_Data::ValidData () const
Returns 'true' if the CTD data fields appear to be valid.
Definition at line 677 of file CTD_Plus_Data.cpp.
References KKU::DateTime::Year().
Referenced by SipperHardware::InstrumentDataManager::CTDdataPlus().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/CTD_Plus_Data.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/CTD_Plus_Data.cpp