Pices: KKU::Sobel Class Reference
KKU::Sobel Class Reference
#include <Sobel.h>
Public Member Functions
Sobel (const RasterPtr _raster)
~Sobel (void)
RasterPtr AngleImage () const
RasterPtr MagnitudeImage () const
Detailed Description
Definition at line 16 of file Sobel.h.
Constructor & Destructor Documentation
Sobel::Sobel (const RasterPtr _raster)
Definition at line 24 of file Sobel.cpp.
References KKU::Raster::Color(), KKU::Raster::CreateGrayScaleKLT(), KKU::Raster::Green(), KKU::Raster::Height(), and KKU::Raster::Width().
Sobel::~Sobel (void)
Definition at line 92 of file Sobel.cpp.
Member Function Documentation
RasterPtr Sobel::AngleImage () const
Definition at line 225 of file Sobel.cpp.
References KKU::PixelValue::Black, FourThirdsPie, OneThirdPie, KKU::Raster::SetPixelValue(), TwoPie, and TwoThirdsPie.
RasterPtr Sobel::MagnitudeImage () const
Definition at line 176 of file Sobel.cpp.
References KKU::Raster::SetPixelValue().
Referenced by KKU::Raster::SobelEdgeDetector().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Sobel.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Sobel.cpp