Pices: MLL::SipperExtractionImageManager Class Reference
MLL::SipperExtractionImageManager Class Reference
#include <SipperExtractionImageManager.h>
Classes
class ImageEntry
class ManagedClass
class ManagedClasssesSortByClassName
Public Types
typedef map< MLClassConstPtr,
ManagedClassPtr > ManagedClassList
typedef ManagedClassList * ManagedClassListPtr
typedef ManagedClass * ManagedClassPtr
Public Member Functions
SipperExtractionImageManager (FileDescPtr _fileDesc, const KKStr &_rootDir, bool _saveFeatureData, int32 _veryLargeImageSize, bool _imagesAreClassified, bool _countOnly, uint32 _imagesPerDirectory, RunLog &_log)
~SipperExtractionImageManager ()
void AddImage (const KKStr &fileName, MLClassConstPtr predClass, int32 size, float depth, ImageFeaturesPtr example, RasterPtr raster, bool colorize)
ClassStatisticListPtr ClassStats () const
void Flush ()
void ReportStatistics (ostream &r) const
void ReportStatsByDepth (ostream &r, VectorUlong *scanLinesPerMeterDepth) const
void SaveFrame (const KKStr &_fileName, RasterPtr _raster, bool colorize)
vector< ManagedClassPtr > SortByClassName () const
Detailed Description
Definition at line 31 of file SipperExtractionImageManager.h.
Member Typedef Documentation
typedef map<MLClassConstPtr,ManagedClassPtr> MLL::SipperExtractionImageManager::ManagedClassList
Definition at line 36 of file SipperExtractionImageManager.h.
typedef ManagedClassList* MLL::SipperExtractionImageManager::ManagedClassListPtr
Definition at line 37 of file SipperExtractionImageManager.h.
typedef ManagedClass* MLL::SipperExtractionImageManager::ManagedClassPtr
Definition at line 34 of file SipperExtractionImageManager.h.
Constructor & Destructor Documentation
MLL::SipperExtractionImageManager::SipperExtractionImageManager (FileDescPtr _fileDesc, const KKStr & _rootDir, bool _saveFeatureData, int32 _veryLargeImageSize, bool _imagesAreClassified, bool _countOnly, uint32 _imagesPerDirectory, RunLog & _log)
Definition at line 116 of file SipperExtractionImageManager.cpp.
References MLL::MLClass::CreateNewMLClass(), KKU::endl(), and KKU::RunLog::Level().
MLL::SipperExtractionImageManager::~SipperExtractionImageManager ()
Definition at line 173 of file SipperExtractionImageManager.cpp.
Member Function Documentation
void MLL::SipperExtractionImageManager::AddImage (const KKStr & fileName, MLClassConstPtr predClass, int32 size, float depth, ImageFeaturesPtr example, RasterPtr raster, bool colorize)
Definition at line 305 of file SipperExtractionImageManager.cpp.
References MLL::SipperExtractionImageManager::ManagedClass::AddImage(), MLL::SizeDistribution::Increment(), and MLL::FeatureVectorList::PushOnBack().
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
ClassStatisticListPtr MLL::SipperExtractionImageManager::ClassStats () const
Definition at line 430 of file SipperExtractionImageManager.cpp.
References MLL::SipperExtractionImageManager::ManagedClass::ImageCount(), MLL::SipperExtractionImageManager::ManagedClass::MLClass(), MLL::ClassStatisticList::PushOnBack(), and MLL::ClassStatisticList::SortByCount().
Referenced by ImageExtractionManager::ExtractionManager::GetClassStatistics().
void MLL::SipperExtractionImageManager::Flush ()
Definition at line 340 of file SipperExtractionImageManager.cpp.
References MLL::FeatureVectorList::AllFeatures(), MLL::FeatureFileIOPices::Driver(), KKU::endl(), KKU::RunLog::Level(), KKU::osAddSlash(), KKU::osGetRootNameOfDirectory(), and MLL::FeatureFileIO::SaveFeatureFileMultipleParts().
Referenced by ImageExtractionManager::ExtractionManager::ManageTheExtraction().
void MLL::SipperExtractionImageManager::ReportStatistics (ostream & r) const
Definition at line 189 of file SipperExtractionImageManager.cpp.
References KKU::endl(), KKU::RunLog::Level(), MLL::SizeDistribution::PrintFormatedDistributionMatrix(), and MLL::SizeDistribution::PrintTabDelDistributionMatrix().
void MLL::SipperExtractionImageManager::ReportStatsByDepth (ostream & r, VectorUlong * scanLinesPerMeterDepth) const
Definition at line 255 of file SipperExtractionImageManager.cpp.
References KKU::endl(), KKU::RunLog::Level(), and MLL::SizeDistribution::PrintByClassCollumns().
void MLL::SipperExtractionImageManager::SaveFrame (const KKStr & _fileName, RasterPtr _raster, bool colorize)
Definition at line 370 of file SipperExtractionImageManager.cpp.
References MLL::MLClass::CreateNewMLClass(), MLL::MLClass::GetUnKnownClassStatic(), and MLL::SipperExtractionImageManager::ManagedClass::SaveFrame().
vector< SipperExtractionImageManager::ManagedClassPtr > MLL::SipperExtractionImageManager::SortByClassName () const
Definition at line 409 of file SipperExtractionImageManager.cpp.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/SipperExtractionImageManager.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/SipperExtractionImageManager.cpp