Pices: PicesInterface::PicesRunLog Class Reference
PicesInterface::PicesRunLog Class Reference
#include <PicesRunLog.h>
Public Member Functions
PicesRunLog ()
PicesRunLog (PicesMsgQueue^ msgQueue)
PicesRunLog (String^ logFileName)
!PicesRunLog ()
~PicesRunLog ()
void AttachFile (String^ runLogFileName)
void AttachFile (const KKU::KKStr &runLogFileName)
void Close ()
void DetachFile ()
void DisplayWithNoteBook ()
String^ FileName ()
String^ LastLine ()
int LineCount ()
RunLog & Log ()
String^ RunLogFileName ()
void SetLoggingLevel (int _loggingLevel)
void Write (String^ s)
void Write (int level, String^ s)
void Writeln (String^ s)
void Writeln (int level, String^ s)
Static Public Member Functions
static PicesRunLog^ CreateRunLog (String^ rootName)
Will create a RunLog with a file in the 'PicesTempDirectory' Starting with 'rootName' with the Date and Time appended to end.
Detailed Description
Definition at line 16 of file PicesRunLog.h.
Constructor & Destructor Documentation
PicesRunLog::PicesRunLog ()
Definition at line 36 of file PicesRunLog.cpp.
Referenced by CreateRunLog(), and ~PicesRunLog().
PicesRunLog::PicesRunLog (PicesMsgQueue^ msgQueue)
Definition at line 45 of file PicesRunLog.cpp.
References KKU::RunLog::AttachMsgQueue(), and PicesInterface::PicesMsgQueue::MsgQueue().
PicesRunLog::PicesRunLog (String^ logFileName)
Definition at line 60 of file PicesRunLog.cpp.
References KKU::KKStr::Str(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
PicesRunLog::!PicesRunLog ()
Definition at line 71 of file PicesRunLog.cpp.
PicesRunLog::~PicesRunLog ()
Definition at line 77 of file PicesRunLog.cpp.
References PicesRunLog().
Member Function Documentation
void PicesRunLog::AttachFile (String^ runLogFileName)
Definition at line 106 of file PicesRunLog.cpp.
References KKU::RunLog::AttachFile(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
void PicesRunLog::AttachFile (const KKU::KKStr & runLogFileName)
Definition at line 114 of file PicesRunLog.cpp.
References KKU::RunLog::AttachFile().
void PicesRunLog::Close ()
Definition at line 98 of file PicesRunLog.cpp.
PicesRunLog PicesRunLog::CreateRunLog (String^ rootName) static
Will create a RunLog with a file in the 'PicesTempDirectory' Starting with 'rootName' with the Date and Time appended to end.
Definition at line 85 of file PicesRunLog.cpp.
References PicesInterface::OSservices::AddSlash(), PicesInterface::OSservices::CreateDirectoryPath(), PicesRunLog(), and PicesInterface::PicesSipperVariables::PicesTempDirectory().
void PicesRunLog::DetachFile ()
Definition at line 120 of file PicesRunLog.cpp.
References KKU::RunLog::DetachFile().
void PicesRunLog::DisplayWithNoteBook ()
Definition at line 217 of file PicesRunLog.cpp.
References KKU::RunLog::AttachFileAppend(), KKU::RunLog::DetachFile(), KKU::KKStr::Empty(), KKU::RunLog::FileName(), and PicesInterface::PicesKKStr::KKStrToSystenStr().
String PicesRunLog::FileName ()
Definition at line 128 of file PicesRunLog.cpp.
References KKU::RunLog::FileName(), and PicesInterface::PicesKKStr::KKStrToSystenStr().
String PicesRunLog::LastLine ()
Definition at line 138 of file PicesRunLog.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr(), and KKU::RunLog::LastLine().
int PicesRunLog::LineCount ()
Definition at line 163 of file PicesRunLog.cpp.
References KKU::RunLog::LineCount().
RunLog& PicesInterface::PicesRunLog::Log () inline
Definition at line 41 of file PicesRunLog.h.
Referenced by PicesInterface::PicesAbundanceCorrectionMatrix::AddIn(), PicesInterface::PicesAbundanceCorrectionMatrix::AdjustClassificationCounts(), PicesInterface::PicesDataBaseImage::GetImageFromSipperFile(), PicesInterface::PicesMethods::GetListOfSipperFiles(), PicesInterface::PicesSipperFileList::GetListOfSipperFilesWeCanFind(), PicesInterface::PicesRaster::GetOrigSipperImage(), PicesInterface::PicesTrainingConfiguration::LoadFeatureDataFromTrainingLibraries(), PicesInterface::PicesFeatureFileIO::LoadFeatureFile(), PicesInterface::PicesFeatureVectorList::LoadInSubDirectoryTree(), PicesInterface::PicesAbundanceCorrectionMatrix::PicesAbundanceCorrectionMatrix(), PicesInterface::PicesDataBaseServerList::PicesDataBaseServerList(), PicesInterface::PicesTrainingConfiguration::PicesTrainingConfiguration(), PicesInterface::PicesAbundanceCorrectionMatrix::Prediction(), PicesInterface::PicesInstrumentDataFileManager::ReExtractInstrumentDataForSipperFile(), PicesInterface::PicesFeatureVectorList::Save(), PicesInterface::PicesFeatureFileIO::SaveFeatureFile(), PicesInterface::PicesFeatureFileIO::SaveFeatureFileNormalized(), PicesInterface::PicesFeatureVectorList::ToFeatureVectorList(), and PicesInterface::PicesDataBaseServerList::WriteConfigFile().
String PicesRunLog::RunLogFileName ()
Definition at line 148 of file PicesRunLog.cpp.
References KKU::RunLog::FileName(), and PicesInterface::PicesKKStr::KKStrToSystenStr().
void PicesRunLog::SetLoggingLevel (int _loggingLevel)
Definition at line 155 of file PicesRunLog.cpp.
References KKU::RunLog::SetLoggingLevel().
void PicesRunLog::Write (String^ s)
Definition at line 172 of file PicesRunLog.cpp.
References KKU::RunLog::Append(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
void PicesRunLog::Write (int level, String^ s)
Definition at line 191 of file PicesRunLog.cpp.
References KKU::RunLog::Append(), KKU::RunLog::SetLevel(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
void PicesRunLog::Writeln (String^ s)
Definition at line 180 of file PicesRunLog.cpp.
References KKU::RunLog::Append(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by PicesInterface::ClassificationBiasMatrix::ClassificationBiasMatrix(), PicesInterface::PicesFeatureFileIO::LoadFeatureFile(), PicesInterface::ClassificationBiasMatrix::PrintAdjustedResults(), PicesInterface::ClassificationBiasMatrix::PrintBiasMatrix(), PicesInterface::PicesFeatureFileIO::SaveFeatureFile(), and PicesInterface::PicesFeatureFileIO::SaveFeatureFileNormalized().
void PicesRunLog::Writeln (int level, String^ s)
Definition at line 203 of file PicesRunLog.cpp.
References KKU::RunLog::Append(), KKU::RunLog::SetLevel(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesRunLog.h
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesRunLog.cpp