Pices: MLL::DuplicateImage Class Reference
MLL::DuplicateImage Class Reference
#include <DuplicateImages.h>
Public Member Functions
DuplicateImage (FileDescPtr _fileDesc, FeatureVectorPtr _image1, FeatureVectorPtr _image2, RunLog &_log)
~DuplicateImage ()
void AddADuplicate (FeatureVectorPtr image)
bool AllTheSameClass ()
bool AlreadyHaveImage (FeatureVectorPtr image)
const FeatureVectorListPtr DuplicatedImages ()
FeatureVectorPtr FirstImageAdded ()
FeatureVectorPtr ImageWithSmallestScanLine ()
Detailed Description
Definition at line 125 of file DuplicateImages.h.
Constructor & Destructor Documentation
DuplicateImage::DuplicateImage (FileDescPtr _fileDesc, FeatureVectorPtr _image1, FeatureVectorPtr _image2, RunLog & _log)
Definition at line 348 of file DuplicateImages.cpp.
References MLL::FeatureVectorList::PushOnBack().
DuplicateImage::~DuplicateImage ()
Definition at line 362 of file DuplicateImages.cpp.
Member Function Documentation
void DuplicateImage::AddADuplicate (FeatureVectorPtr image)
Definition at line 367 of file DuplicateImages.cpp.
References MLL::FeatureVectorList::PushOnBack().
Referenced by MLL::DuplicateImages::AddSingleImage().
bool DuplicateImage::AllTheSameClass ()
Definition at line 376 of file DuplicateImages.cpp.
Referenced by MLL::DuplicateImages::ListOfExamplesToDelete(), and MLL::DuplicateImages::PurgeDuplicates().
bool DuplicateImage::AlreadyHaveImage (FeatureVectorPtr image)
Definition at line 397 of file DuplicateImages.cpp.
Referenced by MLL::DuplicateImageList::LocateByImage().
const FeatureVectorListPtr MLL::DuplicateImage::DuplicatedImages () inline
Definition at line 143 of file DuplicateImages.h.
Referenced by MLL::DuplicateImages::ListOfExamplesToDelete(), MLL::DuplicateImages::PurgeDuplicates(), and MLL::DuplicateImages::ReportDuplicates().
FeatureVectorPtr MLL::DuplicateImage::FirstImageAdded () inline
Definition at line 145 of file DuplicateImages.h.
Referenced by MLL::DuplicateImages::ListOfExamplesToDelete(), MLL::DuplicateImages::PurgeDuplicates(), and ImageExtractionManager::DataBaseUpdateThread::Run().
FeatureVectorPtr DuplicateImage::ImageWithSmallestScanLine ()
Definition at line 405 of file DuplicateImages.cpp.
References MLL::FeatureVector::ImageFileName(), KKU::KKStr::LocateLastOccurrence(), KKU::osGetRootName(), KKU::KKStr::Str(), KKU::KKStr::SubStrPart(), KKU::KKStr::Upper(), and x.
Referenced by MLL::DuplicateImages::ListOfExamplesToDelete(), and MLL::DuplicateImages::PurgeDuplicates().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/DuplicateImages.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/DuplicateImages.cpp