Pices: SipperFile.Sipper2DecodeRec Class Reference
SipperFile.Sipper2DecodeRec Class Reference
Public Member Functions
Sipper2DecodeRec (ushort d)
void AddToScanLine (byte[] scanLine, ref int idx)
byte CameraNum ()
void Dispose ()
bool Eol ()
int PixelSpaceNeeded ()
Detailed Description
Definition at line 7 of file Sipper2DecodeRec.cs.
Constructor & Destructor Documentation
SipperFile.Sipper2DecodeRec.Sipper2DecodeRec (ushort d) inline
Definition at line 47 of file Sipper2DecodeRec.cs.
Member Function Documentation
void SipperFile.Sipper2DecodeRec.AddToScanLine (byte[] scanLine, ref int idx) inline
Definition at line 192 of file Sipper2DecodeRec.cs.
References x.
Referenced by SipperFile.Sipper2File.ReadNextScanLine().
byte SipperFile.Sipper2DecodeRec.CameraNum () inline
Definition at line 42 of file Sipper2DecodeRec.cs.
void SipperFile.Sipper2DecodeRec.Dispose () inline
Definition at line 97 of file Sipper2DecodeRec.cs.
bool SipperFile.Sipper2DecodeRec.Eol () inline
Definition at line 43 of file Sipper2DecodeRec.cs.
Referenced by SipperFile.Sipper2File.LengthNextScanLine(), SipperFile.Sipper2File.ReadNextScanLine(), and SipperFile.Sipper2File.SkipNextScanLine().
int SipperFile.Sipper2DecodeRec.PixelSpaceNeeded () inline
Definition at line 179 of file Sipper2DecodeRec.cs.
Referenced by SipperFile.Sipper2File.LengthNextScanLine().
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperFile/Sipper2DecodeRec.cs