Pices: SipperHardware::PortAssignment Class Reference
SipperHardware::PortAssignment Class Reference
#include <SipperHeaderRec.h>
Public Types
typedef PortAssignment * PortAssignmentPtr
Public Member Functions
PortAssignment (InstrumentPtr _instrument, const KKStr &_desc)
PortAssignment (const KKStr &_shortName, const KKStr &_desc)
PortAssignment (const PortAssignment &_portAssignment)
const KKStr & Desc () const
KKStr HeaderStr () const
const InstrumentPtr Instrument () const
const KKStr & ShortName () const
Detailed Description
Definition at line 20 of file SipperHeaderRec.h.
Member Typedef Documentation
typedef PortAssignment* SipperHardware::PortAssignment::PortAssignmentPtr
Definition at line 23 of file SipperHeaderRec.h.
Constructor & Destructor Documentation
PortAssignment::PortAssignment (InstrumentPtr _instrument, const KKStr & _desc)
Definition at line 27 of file SipperHeaderRec.cpp.
PortAssignment::PortAssignment (const KKStr & _shortName, const KKStr & _desc)
Definition at line 36 of file SipperHeaderRec.cpp.
References SipperHardware::Instrument::LookUpByShortName().
PortAssignment::PortAssignment (const PortAssignment & _portAssignment)
Definition at line 48 of file SipperHeaderRec.cpp.
Member Function Documentation
const KKStr& SipperHardware::PortAssignment::Desc () const inline
Definition at line 35 of file SipperHeaderRec.h.
KKStr PortAssignment::HeaderStr () const
Definition at line 57 of file SipperHeaderRec.cpp.
References SipperHardware::Instrument::Other(), and SipperHardware::Instrument::ShortName().
const InstrumentPtr SipperHardware::PortAssignment::Instrument () const inline
Definition at line 37 of file SipperHeaderRec.h.
const KKStr & PortAssignment::ShortName () const
Definition at line 69 of file SipperHeaderRec.cpp.
References SipperHardware::Instrument::ShortName().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/SipperHeaderRec.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/SipperHeaderRec.cpp