Pices: KKU::KKStrListIndexed Class Reference
KKU::KKStrListIndexed Class Reference
Maintains a list of ordered KKStr instances that can be recalled by eithe string of index.
#include <Str.h>
Public Member Functions
KKStrListIndexed (bool _owner, bool _caseSensitive)
KKStrListIndexed (const KKStrListIndexed &list)
~KKStrListIndexed ()
int32 Add (KKStrPtr s)
int32 Add (const KKStr &s)
int32 Delete (KKStr &s)
int32 LookUp (const KKStr &s) const
int32 LookUp (KKStrPtr s) const
const KKStrConstPtr LookUp (int32 x)
int32 MemoryConsumedEstimated () const
bool operator!= (const KKStrListIndexed &right)
bool operator== (const KKStrListIndexed &right)
uint32 size () const
Detailed Description
Maintains a list of ordered KKStr instances that can be recalled by eithe string of index.
Definition at line 838 of file Str.h.
Constructor & Destructor Documentation
KKStrListIndexed::KKStrListIndexed (bool _owner, bool _caseSensitive)
Definition at line 4729 of file Str.cpp.
KKStrListIndexed::KKStrListIndexed (const KKStrListIndexed & list)
Definition at line 4745 of file Str.cpp.
References Add().
KKStrListIndexed::~KKStrListIndexed ()
Definition at line 4768 of file Str.cpp.
Member Function Documentation
int32 KKStrListIndexed::Add (KKStrPtr s)
Definition at line 4844 of file Str.cpp.
References index(), and KKU::KKStr::MemoryConsumedEstimated().
Referenced by MLL::Attribute::AddANominalValue(), and KKStrListIndexed().
int32 KKU::KKStrListIndexed::Add (const KKStr & s)
int32 KKStrListIndexed::Delete (KKStr & s)
Definition at line 4865 of file Str.cpp.
References index(), and KKU::KKStr::MemoryConsumedEstimated().
int32 KKStrListIndexed::LookUp (const KKStr & s) const
Definition at line 4894 of file Str.cpp.
Referenced by MLL::Attribute::GetNominalCode(), and MLL::Attribute::GetNominalValue().
int32 KKStrListIndexed::LookUp (KKStrPtr s) const
Definition at line 4908 of file Str.cpp.
const KKStrConstPtr KKStrListIndexed::LookUp (int32 x)
Definition at line 4920 of file Str.cpp.
int32 KKStrListIndexed::MemoryConsumedEstimated () const
Definition at line 4792 of file Str.cpp.
Referenced by MLL::Attribute::MemoryConsumedEstimated().
bool KKStrListIndexed::operator!= (const KKStrListIndexed & right)
Definition at line 4837 of file Str.cpp.
bool KKStrListIndexed::operator== (const KKStrListIndexed & right)
Definition at line 4800 of file Str.cpp.
uint32 KKStrListIndexed::size () const
Definition at line 4785 of file Str.cpp.
Referenced by MLL::Attribute::Cardinality().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Str.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Str.cpp