Pices: MLL::CrossValidationMxN Class Reference
MLL::CrossValidationMxN Class Reference
#include <CrossValidationMxN.h>
Public Member Functions
CrossValidationMxN (TrainingConfiguration2Ptr _comfig, uint32 _numOfOrderings, uint32 _numOfFolds, FeatureVectorListPtr _data, bool &_cancelFlag)
CrossValidationMxN (TrainingConfiguration2Ptr _comfig, OrderingsPtr _data, bool &_cancelFlag)
~CrossValidationMxN ()
const VectorFloat & Accuracies () const
float AccuracyMean () const
float AccuracyStdDev () const
const ConfusionMatrix2Ptr ConfussionMatrix () const
int32 NumOfFolds () const
int32 NumOfOrderings () const
float ReductionRatioMean () const
const VectorFloat & ReductionRatios () const
float ReductionRatioStdDev () const
double ReductionTimeMean () const
const VectorDouble & ReductionTimes () const
double ReductionTimeStdDev () const
void RunTrainAndTest (int32 numExamplsToUseForTraining)
Will run M number of Train then Test passes.
void RunValidations ()
const VectorFloat & SupportPoints () const
float SupportPointsMean () const
float SupportPointsStdDev () const
double TestTimeMean () const
const VectorDouble & TestTimes () const
double TestTimeStdDev () const
double TrainingTimeMean () const
const VectorDouble & TrainingTimes () const
double TrainingTimeStdDev () const
Detailed Description
Definition at line 74 of file CrossValidationMxN.h.
Constructor & Destructor Documentation
CrossValidationMxN::CrossValidationMxN (TrainingConfiguration2Ptr _comfig, uint32 _numOfOrderings, uint32 _numOfFolds, FeatureVectorListPtr _data, bool & _cancelFlag)
Definition at line 32 of file CrossValidationMxN.cpp.
CrossValidationMxN::CrossValidationMxN (TrainingConfiguration2Ptr _comfig, OrderingsPtr _data, bool & _cancelFlag)
Definition at line 69 of file CrossValidationMxN.cpp.
CrossValidationMxN::~CrossValidationMxN ()
Definition at line 100 of file CrossValidationMxN.cpp.
Member Function Documentation
const VectorFloat& MLL::CrossValidationMxN::Accuracies () const inline
Definition at line 102 of file CrossValidationMxN.h.
float MLL::CrossValidationMxN::AccuracyMean () const inline
Definition at line 103 of file CrossValidationMxN.h.
float MLL::CrossValidationMxN::AccuracyStdDev () const inline
Definition at line 104 of file CrossValidationMxN.h.
const ConfusionMatrix2Ptr CrossValidationMxN::ConfussionMatrix () const
Definition at line 304 of file CrossValidationMxN.cpp.
int32 MLL::CrossValidationMxN::NumOfFolds () const inline
Definition at line 100 of file CrossValidationMxN.h.
int32 MLL::CrossValidationMxN::NumOfOrderings () const inline
Definition at line 99 of file CrossValidationMxN.h.
float MLL::CrossValidationMxN::ReductionRatioMean () const inline
Definition at line 107 of file CrossValidationMxN.h.
const VectorFloat& MLL::CrossValidationMxN::ReductionRatios () const inline
Definition at line 106 of file CrossValidationMxN.h.
float MLL::CrossValidationMxN::ReductionRatioStdDev () const inline
Definition at line 108 of file CrossValidationMxN.h.
double MLL::CrossValidationMxN::ReductionTimeMean () const inline
Definition at line 111 of file CrossValidationMxN.h.
const VectorDouble& MLL::CrossValidationMxN::ReductionTimes () const inline
Definition at line 110 of file CrossValidationMxN.h.
double MLL::CrossValidationMxN::ReductionTimeStdDev () const inline
Definition at line 112 of file CrossValidationMxN.h.
void CrossValidationMxN::RunTrainAndTest (int32 numExamplsToUseForTraining)
Will run M number of Train then Test passes.
Parameters
[in] numExamplsToUseForTraining The number examples in each ordering(group) that are to be used for training, teh remainding examples will be used as test data.
Definition at line 206 of file CrossValidationMxN.cpp.
References MLL::CrossValidation::Accuracy(), MLL::ConfusionMatrix2::AddIn(), KKU::CalcMeanAndStdDev(), MLL::CrossValidation::ConfussionMatrix(), MLL::ConfusionMatrix2::FactorCounts(), MLL::Orderings::MLClasses(), MLL::CrossValidation::NumOfSupportVectors(), MLL::Orderings::Ordering(), MLL::FeatureVectorList::PushOnBack(), MLL::CrossValidation::ReductionRatio(), MLL::CrossValidation::ReductionTime(), MLL::CrossValidation::RunValidationOnly(), MLL::CrossValidation::TestTimeTotal(), and MLL::CrossValidation::TrainTimeTotal().
void CrossValidationMxN::RunValidations ()
Definition at line 144 of file CrossValidationMxN.cpp.
References MLL::CrossValidation::Accuracy(), MLL::ConfusionMatrix2::AddIn(), KKU::CalcMeanAndStdDev(), MLL::CrossValidation::ConfussionMatrix(), MLL::ConfusionMatrix2::FactorCounts(), MLL::Orderings::MLClasses(), MLL::CrossValidation::NumOfSupportVectors(), MLL::Orderings::Ordering(), MLL::CrossValidation::ReductionRatio(), MLL::CrossValidation::ReductionTime(), MLL::CrossValidation::RunCrossValidation(), MLL::CrossValidation::TestTimeTotal(), and MLL::CrossValidation::TrainTimeTotal().
const VectorFloat& MLL::CrossValidationMxN::SupportPoints () const inline
Definition at line 114 of file CrossValidationMxN.h.
float MLL::CrossValidationMxN::SupportPointsMean () const inline
Definition at line 115 of file CrossValidationMxN.h.
float MLL::CrossValidationMxN::SupportPointsStdDev () const inline
Definition at line 116 of file CrossValidationMxN.h.
double MLL::CrossValidationMxN::TestTimeMean () const inline
Definition at line 119 of file CrossValidationMxN.h.
const VectorDouble& MLL::CrossValidationMxN::TestTimes () const inline
Definition at line 118 of file CrossValidationMxN.h.
double MLL::CrossValidationMxN::TestTimeStdDev () const inline
Definition at line 120 of file CrossValidationMxN.h.
double MLL::CrossValidationMxN::TrainingTimeMean () const inline
Definition at line 123 of file CrossValidationMxN.h.
const VectorDouble& MLL::CrossValidationMxN::TrainingTimes () const inline
Definition at line 122 of file CrossValidationMxN.h.
double MLL::CrossValidationMxN::TrainingTimeStdDev () const inline
Definition at line 124 of file CrossValidationMxN.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/CrossValidationMxN.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/CrossValidationMxN.cpp