Pices: KKU::KKStrParser Class Reference
KKU::KKStrParser Class Reference
Class that manages the extraction of tokens from a String without being destructive to the original string.
#include <KKStrParser.h>
Public Member Functions
KKStrParser (const KKStrParser &_strParser)
KKStrParser (const char *_str)
KKStrParser (const KKStr &_str)
~KKStrParser ()
KKStr GetNextToken (const char *delStr="\n\t\r ")
Extract next Token from string, each delimiter will separate tokens.
bool GetNextTokenBool (const char *delStr="\n\t\r ")
char GetNextTokenChar (const char *delStr="\n\t\r ")
KKU::DateTime GetNextTokenDateTime (const char *delStr="\n\t\r ")
double GetNextTokenDouble (const char *delStr="\n\t\r ")
float GetNextTokenFloat (const char *delStr="\n\t\r ")
int32 GetNextTokenInt (const char *delStr="\n\t\r ")
long GetNextTokenLong (const char *delStr="\n\t\r ")
uint32 GetNextTokenUint (const char *delStr="\n\t\r ")
KKStr GetRestOfLine ()
KKStr GetRestOfStr ()
bool MoreTokens () const
void Reset ()
void SkipWhiteSpace (const char *whiteSpace=" ")
VectorKKStr Split (const char *delStr="\n\t\r ")
const char * Str () const
KKStr SubStrPart (uint32 firstChar, uint32 lastChar) const
void TrimWhiteSpace (const char *_whiteSpace=" ")
After this call all leading and trailing whitespace will be trimmed from tokens.
Detailed Description
Class that manages the extraction of tokens from a String without being destructive to the original string.
Definition at line 18 of file KKStrParser.h.
Constructor & Destructor Documentation
KKStrParser::KKStrParser (const KKStrParser & _strParser)
Definition at line 34 of file KKStrParser.cpp.
References KKU::STRDUP().
KKStrParser::KKStrParser (const char * _str)
Definition at line 57 of file KKStrParser.cpp.
KKStrParser::KKStrParser (const KKStr & _str)
Definition at line 47 of file KKStrParser.cpp.
KKStrParser::~KKStrParser ()
Definition at line 69 of file KKStrParser.cpp.
Member Function Documentation
KKStr KKStrParser::GetNextToken (const char * delStr = "\n\t\r ")
Extract next Token from string, each delimiter will separate tokens.
Removes next Token from string. The token will be terminated by end of string or the first occurrence of a delimiter character. If no more tokens left will return a Empty KKStr.
Parameters
[in] delStr List of delimiting characters.
Returns
Extracted Token.
Definition at line 122 of file KKStrParser.cpp.
References KKU::KKStr::EmptyStr().
Referenced by KKU::DateTime::DateTime(), GetNextTokenBool(), GetNextTokenChar(), GetNextTokenDateTime(), GetNextTokenDouble(), GetNextTokenFloat(), GetNextTokenInt(), GetNextTokenLong(), GetNextTokenUint(), SipperHardware::InstrumentData::InstrumentData(), SipperHardware::SipperFileList::Load(), and Split().
bool KKStrParser::GetNextTokenBool (const char * delStr = "\n\t\r ")
Definition at line 209 of file KKStrParser.cpp.
References GetNextToken(), and KKU::KKStr::ToBool().
char KKStrParser::GetNextTokenChar (const char * delStr = "\n\t\r ")
Definition at line 159 of file KKStrParser.cpp.
References GetNextToken().
KKU::DateTime KKStrParser::GetNextTokenDateTime (const char * delStr = "\n\t\r ")
Definition at line 168 of file KKStrParser.cpp.
References GetNextToken().
double KKStrParser::GetNextTokenDouble (const char * delStr = "\n\t\r ")
Definition at line 189 of file KKStrParser.cpp.
References GetNextToken(), and KKU::KKStr::ToDouble().
float KKStrParser::GetNextTokenFloat (const char * delStr = "\n\t\r ")
Definition at line 195 of file KKStrParser.cpp.
References GetNextToken(), and KKU::KKStr::ToFloat().
int32 KKStrParser::GetNextTokenInt (const char * delStr = "\n\t\r ")
Definition at line 175 of file KKStrParser.cpp.
References GetNextToken(), and KKU::KKStr::ToInt().
long KKStrParser::GetNextTokenLong (const char * delStr = "\n\t\r ")
Definition at line 182 of file KKStrParser.cpp.
References GetNextToken(), and KKU::KKStr::ToLong().
KKU::uint32 KKStrParser::GetNextTokenUint (const char * delStr = "\n\t\r ")
Definition at line 202 of file KKStrParser.cpp.
References GetNextToken(), and KKU::KKStr::ToUint().
KKStr KKStrParser::GetRestOfLine ()
Definition at line 216 of file KKStrParser.cpp.
References KKU::KKStr::Append(), KKU::KKStr::EmptyStr(), and KKU::KKStr::TrimRight().
KKStr KKStrParser::GetRestOfStr ()
Definition at line 265 of file KKStrParser.cpp.
References KKU::KKStr::Append(), KKU::KKStr::EmptyStr(), and KKU::KKStr::TrimRight().
bool KKU::KKStrParser::MoreTokens () const inline
Definition at line 48 of file KKStrParser.h.
Referenced by Split().
void KKStrParser::Reset ()
Definition at line 291 of file KKStrParser.cpp.
void KKStrParser::SkipWhiteSpace (const char * whiteSpace = " ")
Definition at line 93 of file KKStrParser.cpp.
VectorKKStr KKStrParser::Split (const char * delStr = "\n\t\r ")
Definition at line 103 of file KKStrParser.cpp.
References GetNextToken(), and MoreTokens().
Referenced by SipperHardware::InstrumentData::CreateFieldIndirectionVectorFromTabDelStr().
const char* KKU::KKStrParser::Str () const inline
Definition at line 56 of file KKStrParser.h.
KKStr KKStrParser::SubStrPart (uint32 firstChar, uint32 lastChar) const
Definition at line 299 of file KKStrParser.cpp.
References KKU::KKStr::Append(), and KKU::KKStr::EmptyStr().
Referenced by SipperHardware::SipperFileList::Load().
void KKStrParser::TrimWhiteSpace (const char * _whiteSpace = " ")
After this call all leading and trailing whitespace will be trimmed from tokens.
Definition at line 79 of file KKStrParser.cpp.
References KKU::STRDUP().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/KKStrParser.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/KKStrParser.cpp