Pices: KKU::XmlTag Class Reference
KKU::XmlTag Class Reference
#include <XmlStream.h>
Public Types
enum TagTypes { tagNULL, tagStart, tagEnd, tagEmpty }
typedef XmlTag * XmlTagPtr
Public Member Functions
XmlTag (TokenizerPtr _tokenStream)
XmlTag (istream &i)
Will construct a generix XML tag from the following characters in the stream.
int32 AttributeCount () const
const KKStr & AttributeName (int32 _attributeNum) const
const KKStr & AttributeValue (int32 _attributeNum) const
const KKStr & AttributeValue (const KKStr &attributeName) const
const KKStr & AttributeValue (const char *attributeName) const
const KKStr & Name () const
TagTypes TagType () const
Detailed Description
Definition at line 43 of file XmlStream.h.
Member Typedef Documentation
typedef XmlTag* KKU::XmlTag::XmlTagPtr
Definition at line 46 of file XmlStream.h.
Member Enumeration Documentation
enum KKU::XmlTag::TagTypes
Enumerator
tagNULL
tagStart
tagEnd
tagEmpty
Definition at line 47 of file XmlStream.h.
Constructor & Destructor Documentation
XmlTag::XmlTag (TokenizerPtr _tokenStream)
Definition at line 189 of file XmlStream.cpp.
References KKU::Tokenizer::GetNextTokens(), tagEmpty, tagEnd, and tagStart.
KKU::XmlTag::XmlTag (istream & i)
Will construct a generix XML tag from the following characters in the stream.
It sis assumed that the next chracter read from the input strem "i" will be '<'; if not then it is assumed that the next chracter is the one imediately following the '<'.
Member Function Documentation
int32 KKU::XmlTag::AttributeCount () const inline
Definition at line 60 of file XmlStream.h.
const KKStr& KKU::XmlTag::AttributeName (int32 _attributeNum) const
const KKStr& KKU::XmlTag::AttributeValue (int32 _attributeNum) const
const KKStr & XmlTag::AttributeValue (const KKStr & attributeName) const
Definition at line 292 of file XmlStream.cpp.
References KKU::KKStr::EmptyStr().
const KKStr & XmlTag::AttributeValue (const char * attributeName) const
Definition at line 307 of file XmlStream.cpp.
References KKU::KKStr::EmptyStr().
const KKStr& KKU::XmlTag::Name () const inline
Definition at line 58 of file XmlStream.h.
TagTypes KKU::XmlTag::TagType () const inline
Definition at line 59 of file XmlStream.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/XmlStream.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/XmlStream.cpp