Pices: MLL::ConfusionMatrix2 Class Reference
MLL::ConfusionMatrix2 Class Reference
A confusion matrix object that is used to record the results from a CrossValidation.
#include <ConfusionMatrix2.h>
Public Types
typedef ConfusionMatrix2 * ConfusionMatrix2Ptr
Public Member Functions
ConfusionMatrix2 (const MLClassConstList &_classes)
ConfusionMatrix2 (const ConfusionMatrix2 &cm)
ConfusionMatrix2 (const MLClassConstList &_classes, istream &f, int32 _bucketSize, int32 _numOfBuckets, int32 _numOfProbBuckets, int32 _probBucketSize, RunLog &_log)
~ConfusionMatrix2 ()
double Accuracy ()
double Accuracy (MLClassConstPtr mlClass)
VectorFloat AccuracyByClass () const
float AccuracyClassWeightedEqually ()
float AccuracyNorm ()
KKStr AccuracyStr ()
void AddIn (const ConfusionMatrix2 &cm, RunLog &log)
double AvgPredProb () const
int32 ClassCount () const
void ComputeFundamentalStats (MLClassConstPtr ic, double &truePositives, double &trueNegatives, double &falsePositives, double &falseNegatives) const
double Count (MLClassConstPtr mlClass)
double CountsByKnownClass (int32 knownClassIdx) const
const VectorDouble & CountsByKnownClass () const
void FactorCounts (double factor)
Will multiply all counts by 'factor' You would use this in conjunction with 'AddIn'.
float FMeasure (MLClassConstPtr positiveClass, RunLog &log) const
void Increment (MLClassConstPtr _knownClass, MLClassConstPtr _predClass, int32 _size, double _probability, RunLog &_log)
const MLClassConstList & MLClasses () const
VectorDouble PredictedCounts () const
double PredictedCountsCM (int32 knownClassIdx, int32 predClassIdx) const
void PrintAccuracyByProbByClassHTML (ostream &o)
void PrintConfusionMatrix (ostream &_outFile)
void PrintConfusionMatrixAvgPredProbHTML (ostream &o)
void PrintConfusionMatrixHTML (const char *title, ostream &file)
void PrintConfusionMatrixHTML (ostream &outFile)
void PrintConfusionMatrixLatexTable (ostream &outFile)
void PrintConfusionMatrixNarrow (ostream &outFile)
void PrintConfusionMatrixTabDelimited (ostream &outFile)
void PrintErrorByProb (ostream &outFile)
void PrintErrorByProbByRows (ostream &outFile)
void PrintErrorBySize (ostream &outFile)
void PrintErrorBySizeByRows (ostream &outFile)
void PrintErrorBySizeReduced (ostream &outFile)
void PrintProbDistributionTitle (ostream &outFile)
void PrintProbDistributionTotalCount (ostream &outFile)
void PrintProbDistributionTotalError (ostream &outFile)
void PrintTrueFalsePositivesTabDelimited (ostream &outFile)
double TotalCount ()
void WriteSimpleConfusionMatrix (ostream &f) const
void WriteXML (ostream &f) const
Static Public Member Functions
static ConfusionMatrix2Ptr BuildFromIstreamXML (istream &f, RunLog &log)
Detailed Description
A confusion matrix object that is used to record the results from a CrossValidation.
<seealso cref="CrossValidation"
Definition at line 34 of file ConfusionMatrix2.h.
Member Typedef Documentation
typedef ConfusionMatrix2* MLL::ConfusionMatrix2::ConfusionMatrix2Ptr
Definition at line 37 of file ConfusionMatrix2.h.
Constructor & Destructor Documentation
ConfusionMatrix2::ConfusionMatrix2 (const MLClassConstList & _classes)
Definition at line 64 of file ConfusionMatrix2.cpp.
Referenced by BuildFromIstreamXML().
ConfusionMatrix2::ConfusionMatrix2 (const ConfusionMatrix2 & cm)
Definition at line 93 of file ConfusionMatrix2.cpp.
MLL::ConfusionMatrix2::ConfusionMatrix2 (const MLClassConstList & _classes, istream & f, int32 _bucketSize, int32 _numOfBuckets, int32 _numOfProbBuckets, int32 _probBucketSize, RunLog & _log)
ConfusionMatrix2::~ConfusionMatrix2 ()
Definition at line 132 of file ConfusionMatrix2.cpp.
Member Function Documentation
double ConfusionMatrix2::Accuracy ()
Definition at line 2492 of file ConfusionMatrix2.cpp.
Referenced by MLL::CrossValidation::Accuracy(), and MLL::CrossValidationVoting::Accuracy().
double ConfusionMatrix2::Accuracy (MLClassConstPtr mlClass)
Definition at line 2515 of file ConfusionMatrix2.cpp.
VectorFloat ConfusionMatrix2::AccuracyByClass () const
Definition at line 2534 of file ConfusionMatrix2.cpp.
float ConfusionMatrix2::AccuracyClassWeightedEqually ()
Definition at line 2555 of file ConfusionMatrix2.cpp.
Referenced by AccuracyNorm().
float MLL::ConfusionMatrix2::AccuracyNorm () inline
Definition at line 62 of file ConfusionMatrix2.h.
References AccuracyClassWeightedEqually().
Referenced by MLL::CrossValidation::AccuracyNorm().
KKStr ConfusionMatrix2::AccuracyStr ()
Definition at line 2450 of file ConfusionMatrix2.cpp.
References KKU::StrFormatDouble(), and x.
Referenced by MLL::CrossValidationThreeWay::AccuracyStr().
void ConfusionMatrix2::AddIn (const ConfusionMatrix2 & cm, RunLog & log)
Definition at line 2809 of file ConfusionMatrix2.cpp.
Referenced by MLL::ConfussionMatrix2List::DeriveAverageConfusionMatrix(), MLL::CrossValidationMxN::RunTrainAndTest(), and MLL::CrossValidationMxN::RunValidations().
double ConfusionMatrix2::AvgPredProb () const
Definition at line 2503 of file ConfusionMatrix2.cpp.
ConfusionMatrix2Ptr ConfusionMatrix2::BuildFromIstreamXML (istream & f, RunLog & log) static
Definition at line 3034 of file ConfusionMatrix2.cpp.
References MLL::MLClassList::BuildListFromDelimtedStr(), KKU::KKStr::CompareIgnoreCase(), ConfusionMatrix2(), KKU::endl(), KKU::KKStr::ExtractToken2(), KKU::KKStr::ExtractTokenInt(), KKU::RunLog::Level(), and KKU::KKStr::TrimLeft().
int32 MLL::ConfusionMatrix2::ClassCount () const inline
Definition at line 76 of file ConfusionMatrix2.h.
void ConfusionMatrix2::ComputeFundamentalStats (MLClassConstPtr ic, double & truePositives, double & trueNegatives, double & falsePositives, double & falseNegatives) const
Definition at line 1817 of file ConfusionMatrix2.cpp.
References x.
double ConfusionMatrix2::Count (MLClassConstPtr mlClass)
Definition at line 2578 of file ConfusionMatrix2.cpp.
double MLL::ConfusionMatrix2::CountsByKnownClass (int32 knownClassIdx) const
const VectorDouble & ConfusionMatrix2::CountsByKnownClass () const
Definition at line 367 of file ConfusionMatrix2.cpp.
void ConfusionMatrix2::FactorCounts (double factor)
Will multiply all counts by 'factor' You would use this in conjunction with 'AddIn'.
Definition at line 2604 of file ConfusionMatrix2.cpp.
References x.
Referenced by MLL::ConfussionMatrix2List::DeriveAverageConfusionMatrix(), MLL::CrossValidationMxN::RunTrainAndTest(), and MLL::CrossValidationMxN::RunValidations().
float ConfusionMatrix2::FMeasure (MLClassConstPtr positiveClass, RunLog & log) const
Definition at line 1853 of file ConfusionMatrix2.cpp.
References KKU::endl(), and KKU::RunLog::Level().
void ConfusionMatrix2::Increment (MLClassConstPtr _knownClass, MLClassConstPtr _predClass, int32 _size, double _probability, RunLog & _log)
Definition at line 375 of file ConfusionMatrix2.cpp.
References KKU::endl(), and KKU::RunLog::Level().
Referenced by CrossValidationApp::CrossValidate(), CrossValidationApp::PrintSizeHistogram(), and CrossValidationApp::ValidationProcess().
const MLClassConstList& MLL::ConfusionMatrix2::MLClasses () const inline
Definition at line 99 of file ConfusionMatrix2.h.
Referenced by MLL::ClassificationBiasMatrix::ClassificationBiasMatrix(), and MLL::ConfussionMatrix2List::DeriveAverageConfusionMatrix().
VectorDouble ConfusionMatrix2::PredictedCounts () const
Definition at line 338 of file ConfusionMatrix2.cpp.
double ConfusionMatrix2::PredictedCountsCM (int32 knownClassIdx, int32 predClassIdx) const
Definition at line 323 of file ConfusionMatrix2.cpp.
void ConfusionMatrix2::PrintAccuracyByProbByClassHTML (ostream & o)
Definition at line 1223 of file ConfusionMatrix2.cpp.
References KKU::endl(), and KKU::StrFormatDouble().
void ConfusionMatrix2::PrintConfusionMatrix (ostream & _outFile)
Definition at line 930 of file ConfusionMatrix2.cpp.
References KKU::endl(), MLL::MLClassConstList::ExtractThreeTitleLines(), and x.
void ConfusionMatrix2::PrintConfusionMatrixAvgPredProbHTML (ostream & o)
Definition at line 1139 of file ConfusionMatrix2.cpp.
References KKU::endl(), MLL::MLClassConstList::ExtractHTMLTableHeader(), and KKU::StrFormatDouble().
void MLL::ConfusionMatrix2::PrintConfusionMatrixHTML (const char * title, ostream & file)
void MLL::ConfusionMatrix2::PrintConfusionMatrixHTML (ostream & outFile)
void ConfusionMatrix2::PrintConfusionMatrixLatexTable (ostream & outFile)
Definition at line 1471 of file ConfusionMatrix2.cpp.
References KKU::endl(), KKU::StrFormatDouble(), and x.
Referenced by CrossValidationApp::Main().
void ConfusionMatrix2::PrintConfusionMatrixNarrow (ostream & outFile)
Definition at line 1567 of file ConfusionMatrix2.cpp.
References KKU::endl(), KKU::KKStr::LeftPad(), and x.
void ConfusionMatrix2::PrintConfusionMatrixTabDelimited (ostream & outFile)
Definition at line 1335 of file ConfusionMatrix2.cpp.
References KKU::endl(), MLL::MLClassConstList::ExtractThreeTitleLines(), KKU::StrFormatDouble(), and x.
Referenced by CrossValidationApp::Main(), and CrossValidationApp::ValidationProcess().
void ConfusionMatrix2::PrintErrorByProb (ostream & outFile)
Definition at line 1941 of file ConfusionMatrix2.cpp.
References KKU::endl().
Referenced by CrossValidationApp::ValidationProcess().
void ConfusionMatrix2::PrintErrorByProbByRows (ostream & outFile)
Definition at line 2090 of file ConfusionMatrix2.cpp.
References KKU::endl(), and x.
Referenced by CrossValidationApp::Main().
void ConfusionMatrix2::PrintErrorBySize (ostream & outFile)
Definition at line 1901 of file ConfusionMatrix2.cpp.
References KKU::endl().
Referenced by CrossValidationApp::PrintSizeHistogram().
void ConfusionMatrix2::PrintErrorBySizeByRows (ostream & outFile)
Definition at line 1993 of file ConfusionMatrix2.cpp.
References KKU::endl().
Referenced by CrossValidationApp::Main(), and CrossValidationApp::PrintSizeHistogram().
void ConfusionMatrix2::PrintErrorBySizeReduced (ostream & outFile)
Definition at line 2342 of file ConfusionMatrix2.cpp.
References KKU::endl().
Referenced by CrossValidationApp::Main().
void ConfusionMatrix2::PrintProbDistributionTitle (ostream & outFile)
Definition at line 2205 of file ConfusionMatrix2.cpp.
References KKU::endl().
void ConfusionMatrix2::PrintProbDistributionTotalCount (ostream & outFile)
Definition at line 2223 of file ConfusionMatrix2.cpp.
References KKU::endl().
void ConfusionMatrix2::PrintProbDistributionTotalError (ostream & outFile)
Definition at line 2270 of file ConfusionMatrix2.cpp.
References KKU::endl().
void ConfusionMatrix2::PrintTrueFalsePositivesTabDelimited (ostream & outFile)
Definition at line 1689 of file ConfusionMatrix2.cpp.
References KKU::endl(), MLL::MLClassConstList::ExtractTwoTitleLines(), PercentOf(), KKU::StrFormatDouble(), and x.
double MLL::ConfusionMatrix2::TotalCount () inline
Definition at line 147 of file ConfusionMatrix2.h.
void ConfusionMatrix2::WriteSimpleConfusionMatrix (ostream & f) const
Definition at line 3248 of file ConfusionMatrix2.cpp.
References KKU::endl(), KKU::StrFormatDouble(), and MLL::MLClassList::ToCommaDelimitedStr().
Referenced by CrossValidationApp::WriteABiasMatrix().
void ConfusionMatrix2::WriteXML (ostream & f) const
Definition at line 2983 of file ConfusionMatrix2.cpp.
References ArrayToDelimitedDelimitedStr(), KKU::endl(), and MLL::MLClassConstList::ToCommaDelimitedStr().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ConfusionMatrix2.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ConfusionMatrix2.cpp