Pices: MLL::MLClassList Class Reference
MLL::MLClassList Class Reference
Maintains a list of MLClass instances.
#include <MLClass.h>
Classes
class mlClassNameComparison
Public Types
typedef KKU::int32 int32
typedef KKU::uint32 uint32
Public Member Functions
MLClassList ()
MLClassList (const MLClassList &_mlClasses)
Copy constructor; will copy list but not own the contents.
MLClassList (const KKStr &fileName, bool &successfull)
Construct a MLClassList object from the contents of a file.
virtual ~MLClassList ()
virtual void AddMLClass (MLClassPtr _mlClass)
virtual void Clear ()
Clears the contens of this list and updates nameIndex structure.
KKStr ExtractHTMLTableHeader () const
Will generate a HTML formated string that can be used in a HTML table.
MLClassListPtr ExtractListOfClassesForAGivenHierarchialLevel (int32 level)
void ExtractThreeTitleLines (KKStr &titleLine1, KKStr &titleLine2, KKStr &titleLine3) const
Using the class names create three title lines where we split names by "_" characters between the three lines.
void ExtractThreeTitleLines (KKStr &titleLine1, KKStr &titleLine2, KKStr &titleLine3, int32 fieldWidth) const
void ExtractTwoTitleLines (KKStr &titleLine1, KKStr &titleLine2) const
Using the class names create two title lines where we split names by "_" characters between the two lines.
virtual MLClassPtr GetMLClassPtr (const KKStr &_name)
return pointer to instance with '_name'; if none exists, create one and add to list.
MLClassPtr GetNoiseClass () const
MLClassPtr GetUnKnownClass ()
Return a pointer to the MLClass object that represents the unknown Class in the list.
void Load (const KKStr &_fileName, bool &_successfull)
virtual MLClassPtr LookUpByClassId (int32 _classId) const
virtual MLClassPtr LookUpByName (const KKStr &_name) const
Returns a pointer of MLClass object with name (_name); if none in list will then return NULL.
int32 MemoryConsumedEstimated () const
KKU::uint16 NumHierarchialLevels () const
bool operator!= (const MLClassList &right) const
MLClassList & operator+= (const MLClassList &right)
add all classes that are in the 'right' parameter
MLClassList operator- (const MLClassList &right) const
remove all classes that in the 'right' parameter
MLClassList & operator-= (const MLClassList &right)
remove all classes that in the 'right' parameter
MLClassList & operator= (const MLClassList &right)
bool operator== (const MLClassList &right) const
virtual MLClassPtr PopFromBack ()
virtual MLClassPtr PopFromFront ()
virtual void PushOnBack (MLClassPtr mlClass)
virtual void PushOnFront (MLClassPtr mlClass)
void Save (KKStr _fileName, bool &_successfull)
void SortByName ()
KKStr ToCommaDelimitedStr () const
KKStr ToString () const
KKStr ToTabDelimitedStr () const
void WriteXML (std::ostream &o) const
Static Public Member Functions
static MLClassListPtr BuildListFromDelimtedStr (const KKStr &s, char delimiter)
static MLClassListPtr MergeClassList (const MLClassList &list1, const MLClassList &list2)
Friends
class MLClass
Detailed Description
Maintains a list of MLClass instances.
There will be only one instance of each MLClass by name and these instances will be owned by MLClass::existingMLClasses.
Definition at line 258 of file MLClass.h.
Member Typedef Documentation
typedef KKU::int32 MLL::MLClassList::int32
Definition at line 261 of file MLClass.h.
typedef KKU::uint32 MLL::MLClassList::uint32
Definition at line 262 of file MLClass.h.
Constructor & Destructor Documentation
MLClassList::MLClassList ()
Definition at line 489 of file MLClass.cpp.
Referenced by BuildListFromDelimtedStr(), ExtractListOfClassesForAGivenHierarchialLevel(), MemoryConsumedEstimated(), and MergeClassList().
MLClassList::MLClassList (const MLClassList & _mlClasses)
Copy constructor; will copy list but not own the contents.
Definition at line 499 of file MLClass.cpp.
References AddMLClass(), and x.
MLL::MLClassList::MLClassList (const KKStr & fileName, bool & successfull)
Construct a MLClassList object from the contents of a file.
MLClassList::~MLClassList () virtual
Definition at line 538 of file MLClass.cpp.
Member Function Documentation
void MLClassList::AddMLClass (MLClassPtr _mlClass) virtual
Definition at line 682 of file MLClass.cpp.
References KKU::endl().
Referenced by ExtractListOfClassesForAGivenHierarchialLevel(), GetMLClassPtr(), Load(), MergeClassList(), and MLClassList().
MLClassListPtr MLClassList::BuildListFromDelimtedStr (const KKStr & s, char delimiter) static
Definition at line 1150 of file MLClass.cpp.
References GetMLClassPtr(), MLClassList(), and KKU::KKStr::Split().
Referenced by MLL::ConfusionMatrix2::BuildFromIstreamXML().
void MLClassList::Clear () virtual
Clears the contens of this list and updates nameIndex structure.
Definition at line 552 of file MLClass.cpp.
Referenced by operator=().
KKStr MLClassList::ExtractHTMLTableHeader () const
Will generate a HTML formated string that can be used in a HTML table.
Using the class names create one header line for a HTML table. The underscore character ("_") will be used to separate levels
Definition at line 1077 of file MLClass.cpp.
References x.
MLClassListPtr MLClassList::ExtractListOfClassesForAGivenHierarchialLevel (int32 level)
Definition at line 1105 of file MLClass.cpp.
References AddMLClass(), MLL::MLClass::MLClassForGivenHierarchialLevel(), MLClassList(), and SortByName().
void MLL::MLClassList::ExtractThreeTitleLines (KKStr & titleLine1, KKStr & titleLine2, KKStr & titleLine3) const
Using the class names create three title lines where we split names by "_" characters between the three lines.
void MLL::MLClassList::ExtractThreeTitleLines (KKStr & titleLine1, KKStr & titleLine2, KKStr & titleLine3, int32 fieldWidth) const
void MLClassList::ExtractTwoTitleLines (KKStr & titleLine1, KKStr & titleLine2) const
Using the class names create two title lines where we split names by "_" characters between the two lines.
Definition at line 917 of file MLClass.cpp.
References KKU::KKStr::LocateCharacter(), KKU::KKStr::SubStrPart(), and x.
MLClassPtr MLClassList::GetMLClassPtr (const KKStr & _name) virtual
return pointer to instance with '_name'; if none exists, create one and add to list.
Definition at line 788 of file MLClass.cpp.
References AddMLClass(), MLL::MLClass::CreateNewMLClass(), and LookUpByName().
Referenced by BuildListFromDelimtedStr().
MLClassPtr MLClassList::GetNoiseClass () const
Definition at line 804 of file MLClass.cpp.
References MLL::MLClass::UnDefined(), and x.
MLClassPtr MLClassList::GetUnKnownClass ()
Return a pointer to the MLClass object that represents the unknown Class in the list.
That is the one with the name 'UNKNOWN'. If none is found then one will be created and added to the list.
Definition at line 824 of file MLClass.cpp.
References MLL::MLClass::CreateNewMLClass(), LookUpByName(), and PushOnBack().
void MLClassList::Load (const KKStr & _fileName, bool & _successfull)
Definition at line 610 of file MLClass.cpp.
References AddMLClass(), MLL::MLClass::CreateNewMLClass(), KKU::endl(), KKU::osFOPEN(), KKU::KKStr::Str(), KKU::KKStr::TrimRight(), and MLL::MLClass::UnDefined().
MLClassPtr MLClassList::LookUpByClassId (int32 _classId) const virtual
Definition at line 770 of file MLClass.cpp.
References MLL::MLClass::ClassId().
MLClassPtr MLClassList::LookUpByName (const KKStr & _name) const virtual
Returns a pointer of MLClass object with name (_name); if none in list will then return NULL.
Parameters
[in] _name Name of MLClass to search for.
Returns
Pointer to MLClass or NULL if not Found.
Definition at line 756 of file MLClass.cpp.
References KKU::KKStr::ToUpper().
Referenced by MLL::MLClass::CreateNewMLClass(), GetMLClassPtr(), GetUnKnownClass(), operator==(), and MLL::MLClass::ResetAllParentsToAllClasses().
int32 MLClassList::MemoryConsumedEstimated () const
Definition at line 545 of file MLClass.cpp.
References MLClassList().
MLClassListPtr MLClassList::MergeClassList (const MLClassList & list1, const MLClassList & list2) static
Definition at line 1127 of file MLClass.cpp.
References AddMLClass(), and MLClassList().
uint16 MLClassList::NumHierarchialLevels () const
Definition at line 597 of file MLClass.cpp.
References SVM289_MFS::Max().
bool MLClassList::operator!= (const MLClassList & right) const
Definition at line 1202 of file MLClass.cpp.
MLClassList & MLClassList::operator+= (const MLClassList & right)
add all classes that are in the 'right' parameter
Definition at line 1232 of file MLClass.cpp.
References PushOnBack().
MLClassList MLClassList::operator- (const MLClassList & right) const
remove all classes that in the 'right' parameter
Definition at line 1270 of file MLClass.cpp.
References PushOnBack().
MLClassList & MLClassList::operator-= (const MLClassList & right)
remove all classes that in the 'right' parameter
Definition at line 1210 of file MLClass.cpp.
References PopFromBack().
MLClassList & MLClassList::operator= (const MLClassList & right)
Definition at line 1251 of file MLClass.cpp.
References Clear(), and PushOnBack().
bool MLClassList::operator== (const MLClassList & right) const
Definition at line 1183 of file MLClass.cpp.
References LookUpByName().
MLClassPtr MLClassList::PopFromBack () virtual
Definition at line 694 of file MLClass.cpp.
References MLL::MLClass::UpperName().
Referenced by operator-=().
MLClassPtr MLClassList::PopFromFront () virtual
Definition at line 709 of file MLClass.cpp.
References MLL::MLClass::UpperName().
void MLClassList::PushOnBack (MLClassPtr mlClass) virtual
Definition at line 724 of file MLClass.cpp.
References KKU::endl().
Referenced by MLL::DataBaseImageList::ExtractListOfClasses(), MLL::ClassAssignments::GetMLClasses(), GetUnKnownClass(), operator+=(), operator-(), and operator=().
void MLClassList::PushOnFront (MLClassPtr mlClass) virtual
Definition at line 737 of file MLClass.cpp.
References KKU::endl().
void MLClassList::Save (KKStr _fileName, bool & _successfull)
Definition at line 649 of file MLClass.cpp.
References KKU::endl(), KKU::KKStr::Str(), and MLL::MLClass::ToString().
void MLClassList::SortByName ()
Definition at line 858 of file MLClass.cpp.
Referenced by ExtractListOfClassesForAGivenHierarchialLevel().
KKStr MLClassList::ToCommaDelimitedStr () const
Definition at line 902 of file MLClass.cpp.
Referenced by MLL::ConfusionMatrix2::WriteSimpleConfusionMatrix().
KKStr MLClassList::ToString () const
Definition at line 869 of file MLClass.cpp.
Referenced by MLL::operator<<().
KKStr MLClassList::ToTabDelimitedStr () const
Definition at line 887 of file MLClass.cpp.
void MLClassList::WriteXML (std::ostream & o) const
Definition at line 1167 of file MLClass.cpp.
References KKU::endl().
Friends And Related Function Documentation
friend class MLClass friend
Definition at line 413 of file MLClass.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/MLClass.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/MLClass.cpp