Pices: MLL::AbundanceCorrectionMatrix Class Reference
MLL::AbundanceCorrectionMatrix Class Reference
Confusion matrix used to compute adjustment vectors used to make adjustments to classification results.
#include <AbundanceCorrectionMatrix.h>
Public Member Functions
AbundanceCorrectionMatrix (MLClassConstList &_classes, MLClassConstPtr _otherClass, RunLog &_log)
Constructor.
AbundanceCorrectionMatrix (const KKStr &configFileName, RunLog &_log)
~AbundanceCorrectionMatrix ()
void AddIn (const AbundanceCorrectionMatrix &matrix, RunLog &_log)
ClassStatisticListPtr AdjustClassificationCounts (const ClassStatisticList &inputCounts, RunLog &log)
Compute and return abundance adjusted counts.
template<typename T >
void AllocateVector (vector< T > &v, uint32 len)
void ComputeStatistics ()
computing probOfDetection and probOfFalseAlarm(Specifiity)
const KKU::DateTime & DateTimeComputed () const
ClassStatisticListPtr LumpCounts (const ClassStatisticList &inputCounts)
Will lump all counts in 'inputCounts' into classes that match this instance 'classList' and 'otherClass' grouping.
void Prediction (MLClassConstPtr knownClass, MLClassConstPtr predClass, RunLog &log)
void PrintConfusionMatrixTabDelimited (ostream &outFile)
const VectorFloat & ProbOfDetection () const
const VectorFloat & ProbOfFalseAlarm () const
template<typename T >
void ReadArray (uint32 len, T *&a, istream &i)
template<typename T >
istream & ReadVector (vector< T > &v, istream &i)
void ReadXml (istream &i, RunLog &log)
void SaveForConfigFileName (const KKStr &configFileName)
bool Valid () const
template<typename T >
KKStr VectorToStr (vector< T > &v)
void WriteXml (ostream &o)
Detailed Description
Confusion matrix used to compute adjustment vectors used to make adjustments to classification results.
From Paper: "Accurate automatic quantification of taxa-specific plankton abundance using dual classification with correction"
        by: Qiao Hu, Cabell Davis
Definition at line 28 of file AbundanceCorrectionMatrix.h.
Constructor & Destructor Documentation
MLL::AbundanceCorrectionMatrix::AbundanceCorrectionMatrix (MLClassConstList & _classes, MLClassConstPtr _otherClass, RunLog & _log)
Constructor.
The matrix will contain one row and one column for each entry in '_classes' and one additional row and column for '_otherClass'.
Parameters
[in] _classes Classes that are to be part of matrix but should not include '_otherClass'; will create a local instance.
[in] _otherClass This is the class that predictions to any class that is not in '_otherClass' will go to.
MLL::AbundanceCorrectionMatrix::AbundanceCorrectionMatrix (const KKStr & configFileName, RunLog & _log)
AbundanceCorrectionMatrix::~AbundanceCorrectionMatrix ()
Definition at line 89 of file AbundanceCorrectionMatrix.cpp.
Member Function Documentation
void AbundanceCorrectionMatrix::AddIn (const AbundanceCorrectionMatrix & matrix, RunLog & _log)
Definition at line 528 of file AbundanceCorrectionMatrix.cpp.
References KKU::endl(), KKU::RunLog::Level(), and x.
Referenced by PicesInterface::PicesAbundanceCorrectionMatrix::AddIn().
ClassStatisticListPtr AbundanceCorrectionMatrix::AdjustClassificationCounts (const ClassStatisticList & inputCounts, RunLog & log)
Compute and return abundance adjusted counts.
Will treat all classes from 'inputCounts' that are not in the internal 'classes' or 'otherClass' as a 'otherClass'. The adjusted counts will be computed using the stats earlier computed and saved in 'probOfDetection' and 'probOfFalseAlarm'. AdjustedCount = InputCount * probOfFalseAlarm / probOfDetection;
Parameters
[in] inputCounts List of counts retuned from the classifier; each entry will consist of the classification and its respective count.
Definition at line 690 of file AbundanceCorrectionMatrix.cpp.
References MLL::ClassStatistic::Count(), KKU::endl(), KKU::RunLog::Level(), MLL::ClassStatistic::MLClass(), and MLL::ClassStatisticList::PushOnBack().
template<typename T > void MLL::AbundanceCorrectionMatrix::AllocateVector (vector< T > & v, uint32 len)
Definition at line 197 of file AbundanceCorrectionMatrix.cpp.
void AbundanceCorrectionMatrix::ComputeStatistics ()
computing probOfDetection and probOfFalseAlarm(Specifiity)
Using confusion matrix already built will compute probOfDetection(Sensitivity) and probOfFalseAlarm(Specifiity).
Definition at line 207 of file AbundanceCorrectionMatrix.cpp.
References x.
Referenced by PicesInterface::PicesAbundanceCorrectionMatrix::ComputeStatistics().
const KKU::DateTime& MLL::AbundanceCorrectionMatrix::DateTimeComputed () const inline
Definition at line 51 of file AbundanceCorrectionMatrix.h.
Referenced by PicesInterface::PicesAbundanceCorrectionMatrix::DateTimeComputed(), and PicesInterface::PicesAbundanceCorrectionMatrix::PrintAdjustedResults().
ClassStatisticListPtr AbundanceCorrectionMatrix::LumpCounts (const ClassStatisticList & inputCounts)
Will lump all counts in 'inputCounts' into classes that match this instance 'classList' and 'otherClass' grouping.
Definition at line 659 of file AbundanceCorrectionMatrix.cpp.
References MLL::ClassStatistic::Count(), MLL::ClassStatistic::MLClass(), and MLL::ClassStatisticList::PushOnBack().
Referenced by PicesInterface::PicesAbundanceCorrectionMatrix::LumpCounts().
void AbundanceCorrectionMatrix::Prediction (MLClassConstPtr knownClass, MLClassConstPtr predClass, RunLog & log)
Definition at line 157 of file AbundanceCorrectionMatrix.cpp.
References KKU::endl(), and KKU::RunLog::Level().
Referenced by PicesInterface::PicesAbundanceCorrectionMatrix::Prediction().
void AbundanceCorrectionMatrix::PrintConfusionMatrixTabDelimited (ostream & outFile)
Definition at line 557 of file AbundanceCorrectionMatrix.cpp.
References KKU::endl(), MLL::MLClassConstList::ExtractThreeTitleLines(), MLL::MLClassConstList::PushOnBack(), KKU::StrFormatDouble(), and x.
Referenced by PicesInterface::PicesAbundanceCorrectionMatrix::PrintConfusionMatrixTabDelimited().
const VectorFloat& MLL::AbundanceCorrectionMatrix::ProbOfDetection () const inline
Definition at line 52 of file AbundanceCorrectionMatrix.h.
Referenced by PicesInterface::PicesAbundanceCorrectionMatrix::ProbOfDetection().
const VectorFloat& MLL::AbundanceCorrectionMatrix::ProbOfFalseAlarm () const inline
Definition at line 53 of file AbundanceCorrectionMatrix.h.
Referenced by PicesInterface::PicesAbundanceCorrectionMatrix::ProbOfFalseAlarm().
template<typename T > void MLL::AbundanceCorrectionMatrix::ReadArray (uint32 len, T *& a, istream & i)
Definition at line 333 of file AbundanceCorrectionMatrix.cpp.
References KKU::osReadNextToken(), and KKU::KKStr::ToDouble().
template<typename T > istream& MLL::AbundanceCorrectionMatrix::ReadVector (vector< T > & v, istream & i)
Definition at line 299 of file AbundanceCorrectionMatrix.cpp.
References KKU::osReadNextToken(), and KKU::KKStr::ToDouble().
void AbundanceCorrectionMatrix::ReadXml (istream & i, RunLog & log)
Definition at line 390 of file AbundanceCorrectionMatrix.cpp.
References KKU::KKStr::Empty(), KKU::endl(), KKU::KKStr::EqualIgnoreCase(), KKU::RunLog::Level(), KKU::osReadNextToken(), and KKU::KKStr::ToInt().
void AbundanceCorrectionMatrix::SaveForConfigFileName (const KKStr & configFileName)
Definition at line 246 of file AbundanceCorrectionMatrix.cpp.
References KKU::osAddSlash(), KKU::osCreateDirectoryPath(), KKU::osGetRootName(), and KKU::KKStr::Str().
Referenced by PicesInterface::PicesAbundanceCorrectionMatrix::SaveForConfigFileName().
bool MLL::AbundanceCorrectionMatrix::Valid () const inline
Definition at line 54 of file AbundanceCorrectionMatrix.h.
Referenced by PicesInterface::PicesAbundanceCorrectionMatrix::Valid().
template<typename T > KKStr MLL::AbundanceCorrectionMatrix::VectorToStr (vector< T > & v)
Definition at line 285 of file AbundanceCorrectionMatrix.cpp.
References x.
void AbundanceCorrectionMatrix::WriteXml (ostream & o)
Definition at line 357 of file AbundanceCorrectionMatrix.cpp.
References KKU::endl(), and x.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/AbundanceCorrectionMatrix.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/AbundanceCorrectionMatrix.cpp