Pices: ImageExtractionManager::ImageExtractionThread Class Reference
ImageExtractionManager::ImageExtractionThread Class Reference abstract
The base class to be used by all Extraction Manager threads.
#include <ImageExtractionThread.h>
Public Member Functions
ImageExtractionThread (ExtractionParms &_parms, ExtractionManagerPtr _extractionManager, const KKStr &_threadName, MsgQueuePtr _msgQueue)
virtual ~ImageExtractionThread ()
volatile const bool & CancelFlag () const
void CancelThread ()
Call this method to have its thread stop right away and exit.
bool Crashed () const
void Crashed (bool _crashed)
virtual void Run ()=0
void Start ()
Call this method to start thread; it will call the method "Run".
ThreadStatus Status () const
void Status (ThreadStatus _status)
void Stop ()
stop() stops the running thread and frees the thread handle
volatile const bool & TerminateFlag () const
void TerminateThread ()
Call this method to have its thread finish what ever is in the queue and then exit.
const KKStr & ThreadName () const
virtual ThreadTypes ThreadType ()=0
Protected Member Functions
void AddMsg (KKStrPtr msg)
Taking ownership of 'msg' and will append to 'msgQueue'.
void AddMsg (const KKStr &msg)
A copy of the message 'msg' will be added to the end of msgQueue.
bool CancelOrTerminateRequested ()
Protected Attributes
ExtractionManagerPtr extractionManager
Pointer to instance that manges all the threads.
ExtractionParms & parms
Detailed Description
The base class to be used by all Extraction Manager threads.
This will be the base class for each one of the different types of processing that Sipper Image processing will be done. Soem of threads will Extract logical frames from Sipper files,
Definition at line 32 of file ImageExtractionThread.h.
Constructor & Destructor Documentation
ImageExtractionThread::ImageExtractionThread (ExtractionParms & _parms, ExtractionManagerPtr _extractionManager, const KKStr & _threadName, MsgQueuePtr _msgQueue)
Definition at line 68 of file ImageExtractionThread.cpp.
ImageExtractionThread::~ImageExtractionThread () virtual
Definition at line 88 of file ImageExtractionThread.cpp.
Member Function Documentation
void ImageExtractionThread::AddMsg (KKStrPtr msg) protected
Taking ownership of 'msg' and will append to 'msgQueue'.
Definition at line 94 of file ImageExtractionThread.cpp.
References KKU::MsgQueue::AddMsg(), and KKU::endl().
Referenced by ImageExtractionManager::FrameExtractorThread::FrameExtractorThread(), ImageExtractionManager::FrameProcessorThread::FrameProcessorThread(), ImageExtractionManager::FrameExtractorThread::Run(), ImageExtractionManager::DataBaseUpdateThread::Run(), ImageExtractionManager::FrameProcessorThread::Run(), ImageExtractionManager::FrameExtractorThread::~FrameExtractorThread(), and ImageExtractionManager::FrameProcessorThread::~FrameProcessorThread().
void ImageExtractionThread::AddMsg (const KKStr & msg) protected
A copy of the message 'msg' will be added to the end of msgQueue.
Definition at line 114 of file ImageExtractionThread.cpp.
References KKU::MsgQueue::AddMsg(), and KKU::endl().
volatile const bool& ImageExtractionManager::ImageExtractionThread::CancelFlag () const inline
Definition at line 45 of file ImageExtractionThread.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run(), ImageExtractionManager::FrameExtractorThread::Run(), and ImageExtractionManager::FrameProcessorThread::Run().
bool ImageExtractionManager::ImageExtractionThread::CancelOrTerminateRequested () inline protected
Definition at line 67 of file ImageExtractionThread.h.
void ImageExtractionThread::CancelThread ()
Call this method to have its thread stop right away and exit.
Definition at line 130 of file ImageExtractionThread.cpp.
Referenced by ImageExtractionManager::ExtractionManager::CancelProcessing().
bool ImageExtractionManager::ImageExtractionThread::Crashed () const inline
Definition at line 46 of file ImageExtractionThread.h.
Referenced by ImageExtractionManager::ExtractionManager::AnyProcessorsCrashed(), ImageExtractionManager::ExtractionManager::CancelProcessing(), and ImageExtractionManager::DataBaseUpdateThread::Run().
void ImageExtractionManager::ImageExtractionThread::Crashed (bool _crashed) inline
Definition at line 51 of file ImageExtractionThread.h.
virtual void ImageExtractionManager::ImageExtractionThread::Run () pure virtual
Implemented in ImageExtractionManager::FrameProcessorThread, ImageExtractionManager::DataBaseUpdateThread, and ImageExtractionManager::FrameExtractorThread.
Referenced by ThreadStartCallBack().
void ImageExtractionThread::Start ()
Call this method to start thread; it will call the method "Run".
Definition at line 160 of file ImageExtractionThread.cpp.
References SetThreadName(), KKU::KKStr::Str(), and ImageExtractionManager::ThreadStartCallBack().
ThreadStatus ImageExtractionManager::ImageExtractionThread::Status () const inline
Definition at line 47 of file ImageExtractionThread.h.
Referenced by ImageExtractionManager::ExtractionManager::AllProcessorsTerminated(), ImageExtractionManager::ExtractionManager::CancelProcessing(), ImageExtractionManager::DataBaseUpdateThread::Run(), ImageExtractionManager::FrameExtractorThread::Run(), ImageExtractionManager::FrameProcessorThread::Run(), and ThreadStartCallBack().
void ImageExtractionManager::ImageExtractionThread::Status (ThreadStatus _status) inline
Definition at line 52 of file ImageExtractionThread.h.
void ImageExtractionThread::Stop ()
stop() stops the running thread and frees the thread handle
Definition at line 187 of file ImageExtractionThread.cpp.
Referenced by ImageExtractionManager::ExtractionManager::CancelProcessing().
volatile const bool& ImageExtractionManager::ImageExtractionThread::TerminateFlag () const inline
Definition at line 48 of file ImageExtractionThread.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run(), and ImageExtractionManager::FrameProcessorThread::Run().
void ImageExtractionThread::TerminateThread ()
Call this method to have its thread finish what ever is in the queue and then exit.
Definition at line 137 of file ImageExtractionThread.cpp.
Referenced by ImageExtractionManager::ExtractionManager::TerminateProcessing().
const KKStr& ImageExtractionManager::ImageExtractionThread::ThreadName () const inline
Definition at line 49 of file ImageExtractionThread.h.
Referenced by ImageExtractionManager::ExtractionManager::AnyProcessorsCrashed(), and ImageExtractionManager::FrameProcessorThread::Run().
virtual ThreadTypes ImageExtractionManager::ImageExtractionThread::ThreadType () pure virtual
Implemented in ImageExtractionManager::FrameProcessorThread, ImageExtractionManager::DataBaseUpdateThread, and ImageExtractionManager::FrameExtractorThread.
Member Data Documentation
ExtractionManagerPtr ImageExtractionManager::ImageExtractionThread::extractionManager protected
Pointer to instance that manges all the threads.
Definition at line 69 of file ImageExtractionThread.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
ExtractionParms& ImageExtractionManager::ImageExtractionThread::parms protected
Definition at line 71 of file ImageExtractionThread.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::DataBaseUpdateThread(), ImageExtractionManager::FrameExtractorThread::FrameExtractorThread(), ImageExtractionManager::FrameProcessorThread::FrameProcessorThread(), ImageExtractionManager::DataBaseUpdateThread::Run(), and ImageExtractionManager::FrameExtractorThread::Run().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperLibraries/ImageExtractionManager/ImageExtractionThread.h
D:/Users/kkramer/IEC/SipperSoftware/SipperLibraries/ImageExtractionManager/ImageExtractionThread.cpp