Pices: PicesInterface::PicesSipperDeployment Class Reference
PicesInterface::PicesSipperDeployment Class Reference
#include <PicesSipperDeployment.h>
Public Member Functions
PicesSipperDeployment (String^ _cruiseName, String^ _stationName)
PicesSipperDeployment (SipperDeploymentPtr _deployment)
SipperDeploymentPtr UnManagedClass ()
Protected Member Functions
!PicesSipperDeployment ()
Properties
uint32 CropLeft [get, set]
uint32 CropRight [get, set]
String^ CruiseName [get, set]
System::DateTime DateTimeEnd [get, set]
System::DateTime DateTimeStart [get, set]
String^ DeploymentNum [get, set]
String^ Description [get, set]
String^ GPSString [get]
double Latitude [get, set]
double Longitude [get, set]
String^ StationName [get, set]
System::DateTime SyncTimeStampActual [get, set]
System::DateTime SyncTimeStampCTD [get, set]
System::DateTime SyncTimeStampGPS [get, set]
Detailed Description
Definition at line 20 of file PicesSipperDeployment.h.
Constructor & Destructor Documentation
PicesSipperDeployment::PicesSipperDeployment (String^ _cruiseName, String^ _stationName)
Definition at line 30 of file PicesSipperDeployment.cpp.
References SipperHardware::SipperDeployment::CruiseName(), SipperHardware::SipperDeployment::StationName(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
PicesSipperDeployment::PicesSipperDeployment (SipperDeploymentPtr _deployment)
Definition at line 43 of file PicesSipperDeployment.cpp.
PicesSipperDeployment::!PicesSipperDeployment () protected
Definition at line 55 of file PicesSipperDeployment.cpp.
Member Function Documentation
SipperDeploymentPtr PicesInterface::PicesSipperDeployment::UnManagedClass () inline
Definition at line 57 of file PicesSipperDeployment.h.
Referenced by PicesInterface::PicesDataBase::SipperDeploymentInsert(), and PicesInterface::PicesDataBase::SipperDeploymentUpdate().
Property Documentation
uint32 PicesInterface::PicesSipperDeployment::CropLeft get set
Definition at line 47 of file PicesSipperDeployment.h.
uint32 PicesInterface::PicesSipperDeployment::CropRight get set
Definition at line 48 of file PicesSipperDeployment.h.
String^ PicesInterface::PicesSipperDeployment::CruiseName get set
Definition at line 36 of file PicesSipperDeployment.h.
Referenced by SipperFile.TreeNodeDeployment::ToString().
System:: DateTime PicesInterface::PicesSipperDeployment::DateTimeEnd get set
Definition at line 42 of file PicesSipperDeployment.h.
Referenced by SipperFile.TreeNodeDeployment::ToString().
System:: DateTime PicesInterface::PicesSipperDeployment::DateTimeStart get set
Definition at line 41 of file PicesSipperDeployment.h.
Referenced by SipperFile.TreeNodeDeployment::ToString().
String^ PicesInterface::PicesSipperDeployment::DeploymentNum get set
Definition at line 37 of file PicesSipperDeployment.h.
Referenced by SipperFile.TreeNodeDeployment::ToString().
String^ PicesInterface::PicesSipperDeployment::Description get set
Definition at line 39 of file PicesSipperDeployment.h.
Referenced by SipperFile.TreeNodeDeployment::ToString().
String^ PicesInterface::PicesSipperDeployment::GPSString get
Definition at line 55 of file PicesSipperDeployment.h.
Referenced by SipperFile.TreeNodeDeployment::ToString().
double PicesInterface::PicesSipperDeployment::Latitude get set
Definition at line 45 of file PicesSipperDeployment.h.
double PicesInterface::PicesSipperDeployment::Longitude get set
Definition at line 46 of file PicesSipperDeployment.h.
String^ PicesInterface::PicesSipperDeployment::StationName get set
Definition at line 38 of file PicesSipperDeployment.h.
Referenced by SipperFile.TreeNodeDeployment::ToString().
System:: DateTime PicesInterface::PicesSipperDeployment::SyncTimeStampActual get set
Definition at line 50 of file PicesSipperDeployment.h.
System:: DateTime PicesInterface::PicesSipperDeployment::SyncTimeStampCTD get set
Definition at line 51 of file PicesSipperDeployment.h.
System:: DateTime PicesInterface::PicesSipperDeployment::SyncTimeStampGPS get set
Definition at line 52 of file PicesSipperDeployment.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesSipperDeployment.h
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesSipperDeployment.cpp