Pices: MLL::TrainingProcess2 Class Reference
MLL::TrainingProcess2 Class Reference
#include <TrainingProcess2.h>
Public Types
typedef KKU::int32 int32
typedef TrainingProcess2 * TrainingProcess2Ptr
typedef KKU::uint32 uint32
typedef KKU::ulong ulong
Public Member Functions
TrainingProcess2 (const KKStr &_configFileName, FeatureVectorListPtr _excludeList, FileDescPtr _fileDesc, RunLog &_log, std::ostream *_report, bool _forceRebuild, bool _checkForDuplicates, volatile const bool &_cancelFlag, KKStr &_statusMessage)
Constructor that is driven by contents of configuration file.
TrainingProcess2 (const KKStr &_configFileName, FeatureVectorListPtr _excludeList, FileDescPtr _fileDesc, RunLog &_log, uint32 _level, volatile const bool &_cancelFlag, KKStr &_statusMessage)
Build a new model from scratch for the specified class level.
TrainingProcess2 (const KKStr &_configFileName, FileDescPtr _fileDesc, RunLog &_log, bool _featuresAlreadyNormalized, volatile const bool &_cancelFlag, KKStr &_statusMessage)
Constructor Will use existing built model; will not check to see if it is up-to-date.
TrainingProcess2 (istream &_in, FileDescPtr _fileDesc, RunLog &_log, bool _featuresAlreadyNormalized, volatile const bool &_cancelFlag, KKStr &_statusMessage)
Constructor Will read existing built model from provided input stream.
TrainingProcess2 (TrainingConfiguration2Ptr _config, FeatureVectorListPtr _trainingExamples, std::ostream *_reportFile, FileDescPtr _fileDesc, RunLog &_log, bool _featuresAlreadyNormalized, volatile const bool &_cancelFlag, KKStr &_statusMessage)
Constructor that gets its training data from a list of examples provided in one of the parameters.
~TrainingProcess2 ()
bool Abort () const
void Abort (bool _abort)
const KKStr & BitReductionByFeature () const
const KKU::DateTime & BuildDateTime () const
const CompressionStats & CompStats () const
TrainingConfiguration2Ptr Config ()
VectorKKStr ConfigFileFormatErrors () const
If there is a config file; will return a list of its FormatErrors ().
const KKStr & ConfigFileName () const
void CreateModelsFromTrainingData ()
int32 DuplicateDataCount () const
void ExtractTrainingClassFeatures (KKU::DateTime &latestImageTimeStamp, bool &changesMadeToTrainingLibraries)
bool FeaturesAlreadyNormalized ()
FeatureVectorListPtr Images ()
void LoadPrevTrainedOtherwiseRebuild (bool _forceRebuild, bool _checkForDuplicates)
RunLog & Log ()
int32 MemoryConsumedEstimated () const
MLClassConstListPtr MLClasses ()
SVMModelPtr Model3 ()
KKStr ModelDescription () const
Model::ModelTypes ModelType () const
KKStr ModelTypeStr () const
int32 NumOfSupportVectors () const
ModelOldSVMPtr OldSVMModel () const
ModelParamPtr Parameters () const
void Read (istream &in, bool &successful)
int32 ReductionPostExampleCount () const
int32 ReductionPreExampleCount () const
float ReductionRatio () const
double ReductionTime () const
void ReportTraningClassStatistics (std::ostream &report)
void SaveResults ()
void SupportVectorStatistics (int32 &numSVs, int32 &totalNumSVs)
ModelPtr TrainedModel () const
TrainingProcess2Ptr TrainingProcessLeft ()
Returns back pointer to 1st classifier of Dual Classifier.
TrainingProcess2Ptr TrainingProcessRight ()
Returns back pointer to 2nd classifier of Dual Classifier.
double TrainingTime () const
void ValidateConfiguration ()
void WriteXml (ostream &o)
Detailed Description
Definition at line 54 of file TrainingProcess2.h.
Member Typedef Documentation
typedef KKU::int32 MLL::TrainingProcess2::int32
Definition at line 59 of file TrainingProcess2.h.
typedef TrainingProcess2* MLL::TrainingProcess2::TrainingProcess2Ptr
Definition at line 57 of file TrainingProcess2.h.
typedef KKU::uint32 MLL::TrainingProcess2::uint32
Definition at line 60 of file TrainingProcess2.h.
typedef KKU::ulong MLL::TrainingProcess2::ulong
Definition at line 61 of file TrainingProcess2.h.
Constructor & Destructor Documentation
MLL::TrainingProcess2::TrainingProcess2 (const KKStr & _configFileName, FeatureVectorListPtr _excludeList, FileDescPtr _fileDesc, RunLog & _log, std::ostream * _report, bool _forceRebuild, bool _checkForDuplicates, volatile const bool & _cancelFlag, KKStr & _statusMessage)
Constructor that is driven by contents of configuration file.
If no changes to config file or training data, will utilize an existing built model that was saved to disk earlier; otherwise will train from data in training library and save resultant training classifier to disk.
Todo:
I need to make a stucture that would contain variables required to perform prediction The idea is that we should only need to create one instance of "TrainingProcess2" for use by multiple threads. Since diferent classifiers will require different structures "TrainingProcess2" wil have a factory method for creating instances of these structures. These structures woul dthen have their own predict methods.
Parameters
[in] _configFileName Configuration file name where classes and SVM parameters are specified. The directories where example images for each class will be specified.
[in] _excludeList List of Feature Vectors that are to be excluded from the TrainingData. If will check by both ImageFileName and FeatureValues. If this param- is not equal to NULL then will not save the Training model. Will NOT take ownership of list or its contents. Caller still owns it.
[in] _fileDesc Description of the Feature Data, how many features, types, etc.
[in,out] _log Logging file.
[in] _report if not set to NULL will write statistics of the training process to stream.
[in] _forceRebuild If set to true will ignore existing training model and rebuild and save new one.
[in] _checkForDuplicates If set to true will look for duplicates in the training data. Two FeatureVectors will be considered duplicate if they have the Same ImageFileName or the save Feature Values. If duplicates are in the same class then all all but one will be removes. If they are in more then one class then they will both be removed.
[in] _cancelFlag Will be monitored by training process. If this flag turns true will return to caller as soon as convenient.
[out] _statusMessage Caller can monitor this field for messages that can be displayed to the user as a way of letting them know what is happening.
Referenced by MemoryConsumedEstimated().
MLL::TrainingProcess2::TrainingProcess2 (const KKStr & _configFileName, FeatureVectorListPtr _excludeList, FileDescPtr _fileDesc, RunLog & _log, uint32 _level, volatile const bool & _cancelFlag, KKStr & _statusMessage)
Build a new model from scratch for the specified class level.
Will also remove duplicates.
Using the parameter '_level' will construct a classifier that groups classes together by group. Underscore characters in the class name will be used to deliminate group levels. Ex: Crustacean_Copepod_Calanoid has three levels of grouping where 'Crustacean' belongs to level 1.
Parameters
[in] _configFileName Configuration file name where classes and SVM parameters are specified. The directories where example images for each class will be specified.
[in] _excludeList List of Feature Vectors that are to be excluded from the TrainingData. If will check by both ImageFileName and FeatureValues. If this param- is not equal to NULL then will not save the Training model. Will NOT take ownership of list or its contents. Caller still owns it.
[in] _fileDesc Description of the Feature Data, how many features, types, etc.
[in,out] _log Logging file.
[in] <em>level The grouping level to build a classifier for. Ex: if _level = 2 is specified and referring to the class name "Crustacean_Copepod_Calanoid" above all classes that start with "Crustacean_Copepod</em>" will be combined as one logical class.
[in] _cancelFlag Will be monitored by training process. If this flag turns true will return to caller as soon as convenient.
[out] _statusMessage Caller can monitor this field for messages that can be displayed to the user as a way of letting them know what is happening.
MLL::TrainingProcess2::TrainingProcess2 (const KKStr & _configFileName, FileDescPtr _fileDesc, RunLog & _log, bool _featuresAlreadyNormalized, volatile const bool & _cancelFlag, KKStr & _statusMessage)
Constructor Will use existing built model; will not check to see if it is up-to-date.
If no changes to config file or training data, will utilize an existing built model that was saved to disk earlier; otherwise will train from data in training library and save resultant training classifier to disk.
Parameters
[in] _configFileName Configuration file name where classes and SVM parameters are specified. The directories where example images for each class will be specified.
[in] _fileDesc Description of the Feature Data, how many features, types, etc.
[in,out] _log Logging file.
[in] _featuresAlreadyNormalized If set to true will assume that all features in the training data are normalized.
[in] _cancelFlag Will be monitored by training process. If this flag turns true will return to caller as soon as convenient.
[out] _statusMessage Caller can monitor this field for messages that can be displayed to the user as a way of letting them know what is happening.
MLL::TrainingProcess2::TrainingProcess2 (istream & _in, FileDescPtr _fileDesc, RunLog & _log, bool _featuresAlreadyNormalized, volatile const bool & _cancelFlag, KKStr & _statusMessage)
Constructor Will read existing built model from provided input stream.
Parameters
[in] _in Input stream that contains trainingProcess instance; will process until first line containing "</TrainingProcess2>" is encountered.
[in] _fileDesc Description of the Feature Data, how many features, types, etc.
[in,out] _log Logging file.
[in] _featuresAlreadyNormalized If set to true will assume that all features in the training data are normalized.
[in] _cancelFlag Will be monitored by training process. If this flag turns true will return to caller as soon as convenient.
[out] _statusMessage Caller can monitor this field for messages that can be displayed to the user as a way of letting them know what is happening.
MLL::TrainingProcess2::TrainingProcess2 (TrainingConfiguration2Ptr _config, FeatureVectorListPtr _trainingExamples, std::ostream * _reportFile, FileDescPtr _fileDesc, RunLog & _log, bool _featuresAlreadyNormalized, volatile const bool & _cancelFlag, KKStr & _statusMessage)
Constructor that gets its training data from a list of examples provided in one of the parameters.
Parameters
[in] _config A configuration that is already loaded in memory.
[in] _trainingExamples Training data to train classifier with.
[in] _mlClasses Class list.
[in] _reportFile if not set to NULL will write statistics of the training process to stream.
[in] _fileDesc Description of the Feature Data, how many features, types, etc.
[in,out] _log Logging file.
[in] _featuresAlreadyNormalized If set to true will assume that all features in the training data are normalized.
[in] _cancelFlag Will be monitored by training process. If this flag turns true will return to caller as soon as convenient.
[out] _statusMessage Caller can monitor this field for messages that can be displayed to the user as a way of letting them know what is happening.
MLL::TrainingProcess2::~TrainingProcess2 ()
Definition at line 604 of file TrainingProcess2.cpp.
References KKU::endl(), and KKU::RunLog::Level().
Member Function Documentation
bool MLL::TrainingProcess2::Abort () const inline
Definition at line 267 of file TrainingProcess2.h.
Referenced by PicesInterface::TrainingModel2::BuildTrainingModel(), MLL::Classifier2::Classifier2(), CreateModelsFromTrainingData(), ExtractTrainingClassFeatures(), PicesInterface::TrainingModel2::LoadExistingTrainedModel(), PicesInterface::TrainingModel2::LoadTrainigLibrary(), PicesInterface::TrainingModel2::LoadTrainingModelForGivenLevel(), MLL::ModelDual::ReadSpecificImplementationXML(), PicesInterface::TrainingModel2::TrainingModel2(), and MLL::ModelDual::TrainModel().
void MLL::TrainingProcess2::Abort (bool _abort) inline
Definition at line 327 of file TrainingProcess2.h.
const KKStr & MLL::TrainingProcess2::BitReductionByFeature () const
Definition at line 1275 of file TrainingProcess2.cpp.
References MLL::Model::BitReductionByFeature().
Referenced by CrossValidationApp::CrossValidate().
const KKU::DateTime& MLL::TrainingProcess2::BuildDateTime () const inline
Definition at line 269 of file TrainingProcess2.h.
const CompressionStats & MLL::TrainingProcess2::CompStats () const
Definition at line 1285 of file TrainingProcess2.cpp.
References MLL::Model::Compression_Stats().
TrainingConfiguration2Ptr MLL::TrainingProcess2::Config () inline
Definition at line 273 of file TrainingProcess2.h.
Referenced by PicesInterface::TrainingModel2::TrainingModel2().
VectorKKStr MLL::TrainingProcess2::ConfigFileFormatErrors () const
If there is a config file; will return a list of its FormatErrors ().
Definition at line 1342 of file TrainingProcess2.cpp.
Referenced by PicesInterface::TrainingModel2::LoadTrainigLibrary().
const KKStr& MLL::TrainingProcess2::ConfigFileName () const inline
Definition at line 275 of file TrainingProcess2.h.
Referenced by MLL::ModelDual::Description(), MLL::ModelDual::ReadSpecificImplementationXML(), and SaveResults().
void MLL::TrainingProcess2::CreateModelsFromTrainingData ()
Definition at line 1125 of file TrainingProcess2.cpp.
References Abort(), MLL::Model::CreateAModel(), KKU::endl(), KKU::RunLog::Level(), MLL::TrainingConfiguration2::ModelingMethod(), MLL::TrainingConfiguration2::ModelParameters(), KKU::osGetLocalDateTime(), KKU::osGetRootName(), KKU::KKStrException::ToString(), MLL::Model::TrainModel(), and MLL::Model::ValidModel().
Referenced by PicesInterface::TrainingModel2::BuildTrainingModel(), CrossValidationApp::CrossValidate(), MLL::ModelDual::TrainModel(), and CrossValidationApp::ValidationProcess().
int32 MLL::TrainingProcess2::DuplicateDataCount () const
Definition at line 1332 of file TrainingProcess2.cpp.
void MLL::TrainingProcess2::ExtractTrainingClassFeatures (KKU::DateTime & latestImageTimeStamp, bool & changesMadeToTrainingLibraries)
Definition at line 1014 of file TrainingProcess2.cpp.
References Abort(), MLL::TrainingClass::Directory(), KKU::endl(), KKU::RunLog::Level(), MLL::TrainingClass::Name(), MLL::TrainingConfiguration2::NoiseTrainingClass(), and MLL::TrainingConfiguration2::TrainingClasses().
bool MLL::TrainingProcess2::FeaturesAlreadyNormalized () inline
Definition at line 281 of file TrainingProcess2.h.
Referenced by MLL::Classifier2::Classifier2().
FeatureVectorListPtr MLL::TrainingProcess2::Images () inline
Definition at line 285 of file TrainingProcess2.h.
void MLL::TrainingProcess2::LoadPrevTrainedOtherwiseRebuild (bool _forceRebuild, bool _checkForDuplicates)
RunLog& MLL::TrainingProcess2::Log () inline
Definition at line 289 of file TrainingProcess2.h.
int32 MLL::TrainingProcess2::MemoryConsumedEstimated () const
Definition at line 638 of file TrainingProcess2.cpp.
References MLL::Model::MemoryConsumedEstimated(), MLL::MLClassConstList::MemoryConsumedEstimated(), KKU::KKStr::MemoryConsumedEstimated(), MLL::FeatureVectorList::MemoryConsumedEstimated(), and TrainingProcess2().
Referenced by MLL::ModelDual::MemoryConsumedEstimated().
MLClassConstListPtr MLL::TrainingProcess2::MLClasses () inline
Definition at line 287 of file TrainingProcess2.h.
Referenced by MLL::Classifier2::Classifier2(), PicesInterface::TrainingModel2::LoadExistingModelOtherwiseBuild(), PicesInterface::TrainingModel2::LoadExistingTrainedModel(), PicesInterface::TrainingModel2::LoadTrainigLibrary(), PicesInterface::TrainingModel2::LoadTrainingModelForGivenLevel(), and PicesInterface::TrainingModel2::TrainingModel2().
SVMModelPtr MLL::TrainingProcess2::Model3 ()
Definition at line 702 of file TrainingProcess2.cpp.
References OldSVMModel(), and MLL::ModelOldSVM::SvmModel().
KKStr MLL::TrainingProcess2::ModelDescription () const
Definition at line 672 of file TrainingProcess2.cpp.
References MLL::Model::Description().
Referenced by MLL::ModelDual::ProbabilitiesByClassDual().
Model::ModelTypes MLL::TrainingProcess2::ModelType () const
Definition at line 682 of file TrainingProcess2.cpp.
References MLL::Model::ModelType(), and MLL::Model::mtNULL.
KKStr MLL::TrainingProcess2::ModelTypeStr () const
Definition at line 692 of file TrainingProcess2.cpp.
References MLL::Model::ModelTypeStr().
Referenced by MLL::ModelDual::Description().
int32 MLL::TrainingProcess2::NumOfSupportVectors () const
Definition at line 1220 of file TrainingProcess2.cpp.
References MLL::ModelOldSVM::NumOfSupportVectors(), and OldSVMModel().
Referenced by CrossValidationApp::CrossValidate(), MLL::ModelDual::NumOfSupportVectors(), and CrossValidationApp::ValidationProcess().
ModelOldSVMPtr MLL::TrainingProcess2::OldSVMModel () const
Definition at line 662 of file TrainingProcess2.cpp.
References MLL::Model::ModelType(), and MLL::Model::mtOldSVM.
Referenced by Model3(), NumOfSupportVectors(), and SupportVectorStatistics().
ModelParamPtr MLL::TrainingProcess2::Parameters () const
Definition at line 1209 of file TrainingProcess2.cpp.
References MLL::Model::Param().
void MLL::TrainingProcess2::Read (istream & in, bool & successful)
Definition at line 749 of file TrainingProcess2.cpp.
References MLL::Model::CreateFromStream(), MLL::MLClass::CreateNewMLClass(), KKU::endl(), KKU::KKStr::EqualIgnoreCase(), KKU::KKStr::ExtractToken2(), KKU::RunLog::Level(), MLL::MLClassConstList::PushOnBack(), KKU::KKStrException::ToString(), KKU::KKStr::TrimLeft(), KKU::KKStr::TrimRight(), and KKU::KKStr::Upper().
int32 MLL::TrainingProcess2::ReductionPostExampleCount () const
Definition at line 1302 of file TrainingProcess2.cpp.
References MLL::Model::ReductionPostExampleCount().
Referenced by CrossValidationApp::CrossValidate(), and CrossValidationApp::ValidationProcess().
int32 MLL::TrainingProcess2::ReductionPreExampleCount () const
Definition at line 1292 of file TrainingProcess2.cpp.
References MLL::Model::ReductionPreExampleCount().
Referenced by CrossValidationApp::CrossValidate(), and CrossValidationApp::ValidationProcess().
float MLL::TrainingProcess2::ReductionRatio () const
Definition at line 1312 of file TrainingProcess2.cpp.
References MLL::Model::ReductionRatio().
Referenced by CrossValidationApp::ValidationProcess().
double MLL::TrainingProcess2::ReductionTime () const
Definition at line 1266 of file TrainingProcess2.cpp.
References MLL::Model::ReductionTime().
Referenced by CrossValidationApp::CrossValidate(), and CrossValidationApp::ValidationProcess().
void MLL::TrainingProcess2::ReportTraningClassStatistics (std::ostream & report)
Definition at line 1077 of file TrainingProcess2.cpp.
References KKU::endl(), and MLL::FeatureVectorList::PrintClassStatistics().
void MLL::TrainingProcess2::SaveResults ()
Definition at line 1189 of file TrainingProcess2.cpp.
References ConfigFileName(), KKU::endl(), KKU::RunLog::Level(), KKU::osGetRootName(), MLL::Model::RootFileName(), KKU::KKStr::Str(), and WriteXml().
void MLL::TrainingProcess2::SupportVectorStatistics (int32 & numSVs, int32 & totalNumSVs)
Definition at line 1231 of file TrainingProcess2.cpp.
References OldSVMModel(), and MLL::ModelOldSVM::SupportVectorStatistics().
ModelPtr MLL::TrainingProcess2::TrainedModel () const inline
Definition at line 317 of file TrainingProcess2.h.
Referenced by MLL::Classifier2::Classifier2().
TrainingProcess2Ptr MLL::TrainingProcess2::TrainingProcessLeft ()
Returns back pointer to 1st classifier of Dual Classifier.
If not a Dual classifier will return back NULL. Keep in mind that you will not won this classifier and that ot can be deleted at any time.
Definition at line 1245 of file TrainingProcess2.cpp.
References MLL::Model::ModelType(), and MLL::Model::mtDual.
Referenced by PicesInterface::TrainingModel2::CreateTrainingModelLeft().
TrainingProcess2Ptr MLL::TrainingProcess2::TrainingProcessRight ()
Returns back pointer to 2nd classifier of Dual Classifier.
If not a Dual classifier will return back NULL.
Definition at line 1254 of file TrainingProcess2.cpp.
References MLL::Model::ModelType(), and MLL::Model::mtDual.
Referenced by PicesInterface::TrainingModel2::CreateTrainingModelRight().
double MLL::TrainingProcess2::TrainingTime () const
Definition at line 1322 of file TrainingProcess2.cpp.
References MLL::Model::TrainingTime().
Referenced by CrossValidationApp::CrossValidate().
void MLL::TrainingProcess2::ValidateConfiguration ()
void MLL::TrainingProcess2::WriteXml (ostream & o)
Definition at line 712 of file TrainingProcess2.cpp.
References KKU::endl(), KKU::RunLog::Level(), KKU::KKStrException::ToString(), MLL::MLClassConstList::ToTabDelimitedStr(), and MLL::Model::WriteXML().
Referenced by SaveResults(), and MLL::ModelDual::WriteSpecificImplementationXML().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/TrainingProcess2.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/TrainingProcess2.cpp