Pices: KKU::Chart Class Reference
KKU::Chart Class Reference
Used to Create chart's from defined series of data.
#include <Chart.h>
Classes
class PlotPoint
class Series
class XLabel
Public Types
typedef PlotPoint * PlotPointPtr
typedef vector< SeriesPtr > SeriesList
typedef Series * SeriesPtr
Public Member Functions
Chart (KKStr _title)
~Chart ()
void AddAValue (uint32 _seriesIDX, FFLOAT _xVal, FFLOAT _yVal)
RasterPtr CreateRaster ()
void DefineASeries (KKStr _name)
void DefineASeries (KKStr _name, PixelValue _color)
void DefineAXLabel (FFLOAT _xVal, KKStr _name)
int32 NumOfSeries ()
void Save (KKStr _fileName)
void SaveAsImage (KKStr _fileName)
Detailed Description
Used to Create chart's from defined series of data.
This class is meant to allow you to define multiple series, their x and y ranges and the data for each series.
Todo:
This class Chart has not been used as of yet so requires testing.
Definition at line 22 of file Chart.h.
Member Typedef Documentation
typedef PlotPoint* KKU::Chart::PlotPointPtr
Definition at line 31 of file Chart.h.
typedef vector<SeriesPtr> KKU::Chart::SeriesList
Definition at line 30 of file Chart.h.
typedef Series* KKU::Chart::SeriesPtr
Definition at line 27 of file Chart.h.
Constructor & Destructor Documentation
KKU::Chart::Chart (KKStr _title)
Definition at line 142 of file Chart.cpp.
KKU::Chart::~Chart ()
Definition at line 155 of file Chart.cpp.
References x.
Member Function Documentation
void KKU::Chart::AddAValue (uint32 _seriesIDX, FFLOAT _xVal, FFLOAT _yVal)
Definition at line 167 of file Chart.cpp.
References KKU::endl().
RasterPtr Chart::CreateRaster ()
Definition at line 270 of file Chart.cpp.
References KKU::Raster::DrawDot(), and KKU::Raster::DrawLine().
Referenced by SaveAsImage().
void KKU::Chart::DefineASeries (KKStr _name)
Definition at line 228 of file Chart.cpp.
References defaultColors, and numOfDefinedDefaultColors.
void KKU::Chart::DefineASeries (KKStr _name, PixelValue _color)
Definition at line 236 of file Chart.cpp.
void KKU::Chart::DefineAXLabel (FFLOAT _xVal, KKStr _name)
Definition at line 246 of file Chart.cpp.
int32 KKU::Chart::NumOfSeries () inline
Definition at line 38 of file Chart.h.
Referenced by Save().
void Chart::Save (KKStr _fileName)
Definition at line 470 of file Chart.cpp.
References KKU::endl(), KKU::Chart::XLabel::Name(), NumOfSeries(), KKU::KKStr::Str(), x, KKU::Chart::PlotPoint::XVal(), KKU::Chart::XLabel::XVal(), and KKU::Chart::PlotPoint::YVal().
void Chart::SaveAsImage (KKStr _fileName)
Definition at line 428 of file Chart.cpp.
References CreateRaster(), and KKU::SaveImage().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Chart.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Chart.cpp