Pices: SipperFile.SipperHeaderRec Class Reference
SipperFile.SipperHeaderRec Class Reference
Summary description for SipperConfigRec.
Public Member Functions
SipperHeaderRec ()
void AirTemp (string _airTemp)
string AirTemp ()
void CruiseDateEnd (DateTime _cruiseDateEnd)
DateTime CruiseDateEnd ()
void CruiseDateStart (DateTime _cruiseDateStart)
DateTime CruiseDateStart ()
void CruiseLocation (string _cruiseLocation)
string CruiseLocation ()
void CtdExt0Code (string _ctdExt0Code)
string CtdExt0Code ()
void CtdExt1Code (string _ctdExt1Code)
string CtdExt1Code ()
void CtdExt2Code (string _ctdExt2Code)
string CtdExt2Code ()
void CtdExt3Code (string _ctdExt3Code)
string CtdExt3Code ()
void DeploymentVehicle (string _deploymentVehicle)
string DeploymentVehicle ()
string HeaderStr ()
Instrument InclinationMeter (ref int inclinationSerailPort)
void Latitude (double _latitude)
double Latitude ()
void Longitude (double _longitude)
double Longitude ()
void Objective (string _objective)
string Objective ()
void ParseHeaderStr (string s)
PortAssignment[] PortAssignments ()
void Principal (string _principal)
string Principal ()
void ProcessNameAndDataStrings (string fieldName, string fieldValue, ref bool found)
void ResearchOrg (string _researchOrg)
string ResearchOrg ()
void Save (StreamWriter w)
void ScanRate (int _scanRate)
int ScanRate ()
void SeaConditions (string _seaConditions)
string SeaConditions ()
void SerialPort (int serialPortNum, string shortName, string description)
string SerialPortDesc (int serialPortNum)
string SerialPortShortName (int serialPortNum)
void SipperFileName (string _sipperFileName)
string SipperFileName ()
void WaveHeight (string _waveHeight)
string WaveHeight ()
void WeatherConditions (string _weatherConditions)
string WeatherConditions ()
Public Attributes
const int MaxHeaderLen = 455
const int MaxSipperFileNameLen = 30
Detailed Description
Summary description for SipperConfigRec.
Used for the SipperFileHeader record. It will have the ability to code and decode the information thatwill be stored at the very beginning of a SipperFile.
Definition at line 12 of file SipperHeaderRec.cs.
Constructor & Destructor Documentation
SipperFile.SipperHeaderRec.SipperHeaderRec () inline
Definition at line 43 of file SipperHeaderRec.cs.
Member Function Documentation
void SipperFile.SipperHeaderRec.AirTemp (string _airTemp) inline
Definition at line 333 of file SipperHeaderRec.cs.
string SipperFile.SipperHeaderRec.AirTemp () inline
Definition at line 368 of file SipperHeaderRec.cs.
void SipperFile.SipperHeaderRec.CruiseDateEnd (DateTime _cruiseDateEnd) inline
Definition at line 328 of file SipperHeaderRec.cs.
DateTime SipperFile.SipperHeaderRec.CruiseDateEnd () inline
Definition at line 363 of file SipperHeaderRec.cs.
void SipperFile.SipperHeaderRec.CruiseDateStart (DateTime _cruiseDateStart) inline
Definition at line 327 of file SipperHeaderRec.cs.
DateTime SipperFile.SipperHeaderRec.CruiseDateStart () inline
Definition at line 362 of file SipperHeaderRec.cs.
void SipperFile.SipperHeaderRec.CruiseLocation (string _cruiseLocation) inline
Definition at line 323 of file SipperHeaderRec.cs.
string SipperFile.SipperHeaderRec.CruiseLocation () inline
Definition at line 358 of file SipperHeaderRec.cs.
void SipperFile.SipperHeaderRec.CtdExt0Code (string _ctdExt0Code) inline
Definition at line 338 of file SipperHeaderRec.cs.
Referenced by SipperFile.InstrumentDataReportCTD.InstrumentDataReportCTD().
string SipperFile.SipperHeaderRec.CtdExt0Code () inline
Definition at line 374 of file SipperHeaderRec.cs.
void SipperFile.SipperHeaderRec.CtdExt1Code (string _ctdExt1Code) inline
Definition at line 339 of file SipperHeaderRec.cs.
Referenced by SipperFile.InstrumentDataReportCTD.InstrumentDataReportCTD().
string SipperFile.SipperHeaderRec.CtdExt1Code () inline
Definition at line 375 of file SipperHeaderRec.cs.
void SipperFile.SipperHeaderRec.CtdExt2Code (string _ctdExt2Code) inline
Definition at line 340 of file SipperHeaderRec.cs.
Referenced by SipperFile.InstrumentDataReportCTD.InstrumentDataReportCTD().
string SipperFile.SipperHeaderRec.CtdExt2Code () inline
Definition at line 376 of file SipperHeaderRec.cs.
void SipperFile.SipperHeaderRec.CtdExt3Code (string _ctdExt3Code) inline
Definition at line 341 of file SipperHeaderRec.cs.
Referenced by SipperFile.InstrumentDataReportCTD.InstrumentDataReportCTD().
string SipperFile.SipperHeaderRec.CtdExt3Code () inline
Definition at line 377 of file SipperHeaderRec.cs.
void SipperFile.SipperHeaderRec.DeploymentVehicle (string _deploymentVehicle) inline
Definition at line 329 of file SipperHeaderRec.cs.
string SipperFile.SipperHeaderRec.DeploymentVehicle () inline
Definition at line 364 of file SipperHeaderRec.cs.
string SipperFile.SipperHeaderRec.HeaderStr () inline
Definition at line 86 of file SipperHeaderRec.cs.
References SipperFile.PortAssignment.HeaderStr(), and x.
Instrument SipperFile.SipperHeaderRec.InclinationMeter (ref int inclinationSerailPort) inline
Definition at line 405 of file SipperHeaderRec.cs.
References SipperFile.PortAssignment.Instrument(), and x.
void SipperFile.SipperHeaderRec.Latitude (double _latitude) inline
Definition at line 334 of file SipperHeaderRec.cs.
double SipperFile.SipperHeaderRec.Latitude () inline
Definition at line 369 of file SipperHeaderRec.cs.
void SipperFile.SipperHeaderRec.Longitude (double _longitude) inline
Definition at line 335 of file SipperHeaderRec.cs.
double SipperFile.SipperHeaderRec.Longitude () inline
Definition at line 370 of file SipperHeaderRec.cs.
void SipperFile.SipperHeaderRec.Objective (string _objective) inline
Definition at line 324 of file SipperHeaderRec.cs.
string SipperFile.SipperHeaderRec.Objective () inline
Definition at line 359 of file SipperHeaderRec.cs.
void SipperFile.SipperHeaderRec.ParseHeaderStr (string s) inline
Definition at line 121 of file SipperHeaderRec.cs.
References SipperFile.SipperHeaderRec.ProcessNameAndDataStrings(), and x.
PortAssignment [] SipperFile.SipperHeaderRec.PortAssignments () inline
Definition at line 80 of file SipperHeaderRec.cs.
Referenced by SipperFile.InstrumentDataManager.InstrumentDataManager().
void SipperFile.SipperHeaderRec.Principal (string _principal) inline
Definition at line 325 of file SipperHeaderRec.cs.
string SipperFile.SipperHeaderRec.Principal () inline
Definition at line 360 of file SipperHeaderRec.cs.
void SipperFile.SipperHeaderRec.ProcessNameAndDataStrings (string fieldName, string fieldValue, ref bool found) inline
Definition at line 149 of file SipperHeaderRec.cs.
Referenced by SipperFile.SipperHeaderRec.ParseHeaderStr().
void SipperFile.SipperHeaderRec.ResearchOrg (string _researchOrg) inline
Definition at line 326 of file SipperHeaderRec.cs.
string SipperFile.SipperHeaderRec.ResearchOrg () inline
Definition at line 361 of file SipperHeaderRec.cs.
void SipperFile.SipperHeaderRec.Save (StreamWriter w) inline
Definition at line 285 of file SipperHeaderRec.cs.
References SipperFile.PortAssignment.HeaderStr(), and x.
Referenced by SipperFile.SipperConfigRec.Save().
void SipperFile.SipperHeaderRec.ScanRate (int _scanRate) inline
Definition at line 336 of file SipperHeaderRec.cs.
int SipperFile.SipperHeaderRec.ScanRate () inline
Definition at line 371 of file SipperHeaderRec.cs.
void SipperFile.SipperHeaderRec.SeaConditions (string _seaConditions) inline
Definition at line 330 of file SipperHeaderRec.cs.
string SipperFile.SipperHeaderRec.SeaConditions () inline
Definition at line 365 of file SipperHeaderRec.cs.
void SipperFile.SipperHeaderRec.SerialPort (int serialPortNum, string shortName, string description) inline
Definition at line 343 of file SipperHeaderRec.cs.
string SipperFile.SipperHeaderRec.SerialPortDesc (int serialPortNum) inline
Definition at line 393 of file SipperHeaderRec.cs.
References SipperFile.PortAssignment.Desc().
string SipperFile.SipperHeaderRec.SerialPortShortName (int serialPortNum) inline
Definition at line 381 of file SipperHeaderRec.cs.
References SipperFile.PortAssignment.ShortName().
void SipperFile.SipperHeaderRec.SipperFileName (string _sipperFileName) inline
Definition at line 337 of file SipperHeaderRec.cs.
string SipperFile.SipperHeaderRec.SipperFileName () inline
Definition at line 372 of file SipperHeaderRec.cs.
void SipperFile.SipperHeaderRec.WaveHeight (string _waveHeight) inline
Definition at line 331 of file SipperHeaderRec.cs.
string SipperFile.SipperHeaderRec.WaveHeight () inline
Definition at line 366 of file SipperHeaderRec.cs.
void SipperFile.SipperHeaderRec.WeatherConditions (string _weatherConditions) inline
Definition at line 332 of file SipperHeaderRec.cs.
string SipperFile.SipperHeaderRec.WeatherConditions () inline
Definition at line 367 of file SipperHeaderRec.cs.
Member Data Documentation
const int SipperFile.SipperHeaderRec.MaxHeaderLen = 455
Definition at line 16 of file SipperHeaderRec.cs.
const int SipperFile.SipperHeaderRec.MaxSipperFileNameLen = 30
Definition at line 19 of file SipperHeaderRec.cs.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperFile/SipperHeaderRec.cs