Pices: KKU::DateTime Class Reference
KKU::DateTime Class Reference
represents Date and Time, consists of two member classes DateType & TimeType.
#include <DateTime.h>
Public Member Functions
DateTime ()
DateTime (const DateTime &dateTime)
DateTime (const DateType &_date, const TimeType &_time)
DateTime (short _year, uchar _month, uchar _day, uchar _hour, uchar _minute, uchar _second)
DateTime (const KKStr &s)
void AddDays (int32 _days)
void AddHours (int32 _hours)
void AddMinutes (int32 _mins)
void AddSeconds (long _secs)
const KKU::DateType & Date () const
uchar Day () const
KKStr HH_MM_SS () const
The date part will be converted into hours.
void HoursAdd (int32 hours)
Add _hours to DateTime, will adjust date to accommodate 24 hour clock.
void MinutesAdd (int32 _mins)
uchar Month () const
bool operator!= (const DateTime &right) const
DateTime operator+ (const DateTime &right) const
DateTime operator- (const DateTime &right) const
bool operator< (const DateTime &right) const
bool operator<= (const DateTime &right) const
DateTime & operator= (const DateTime &right)
bool operator== (const DateTime &right) const
bool operator> (const DateTime &right) const
bool operator>= (const DateTime &right) const
uint64 Seconds () const
void SecondsAdd (long _secs)
const TimeType & Time () const
uint32 ToDays () const
double ToHours () const
uint64 ToSeconds () const
short Year () const
KKStr YYYY_MM_DD_HH_MM_SS () const
KKStr YYYYMMDDHHMMSS () const
Detailed Description
represents Date and Time, consists of two member classes DateType & TimeType.
See Also
osGetFileDateTime
osGetLocalDateTime
Definition at line 215 of file DateTime.h.
Constructor & Destructor Documentation
DateTime::DateTime ()
Definition at line 1002 of file DateTime.cpp.
Referenced by operator+(), and operator-().
DateTime::DateTime (const DateTime & dateTime)
Definition at line 1011 of file DateTime.cpp.
DateTime::DateTime (const DateType & _date, const TimeType & _time)
Definition at line 1021 of file DateTime.cpp.
DateTime::DateTime (short _year, uchar _month, uchar _day, uchar _hour, uchar _minute, uchar _second)
Definition at line 1033 of file DateTime.cpp.
DateTime::DateTime (const KKStr & s)
Definition at line 1048 of file DateTime.cpp.
References KKU::KKStr::Empty(), and KKU::KKStrParser::GetNextToken().
Member Function Documentation
void DateTime::AddDays (int32 _days)
Definition at line 1095 of file DateTime.cpp.
References KKU::DateType::AddDays().
void DateTime::AddHours (int32 _hours)
Definition at line 1101 of file DateTime.cpp.
References KKU::TimeType::Hour().
Referenced by HoursAdd().
void DateTime::AddMinutes (int32 _mins)
Definition at line 1126 of file DateTime.cpp.
References HoursAdd(), and KKU::TimeType::Minute().
Referenced by MinutesAdd().
void DateTime::AddSeconds (long _secs)
Definition at line 1146 of file DateTime.cpp.
References MinutesAdd(), and KKU::TimeType::Second().
Referenced by SecondsAdd().
const KKU::DateType& KKU::DateTime::Date () const inline
Definition at line 242 of file DateTime.h.
Referenced by PicesInterface::PicesMethods::DateTimeKKUtoSystem(), SipperHardware::InstrumentData::FieldToStr(), PicesInterface::OSservices::KKuDateTimeToSystemDateTime(), and KKU::operator<<().
uchar KKU::DateTime::Day () const inline
Definition at line 254 of file DateTime.h.
References KKU::DateType::Day().
KKStr DateTime::HH_MM_SS () const
The date part will be converted into hours.
Definition at line 1209 of file DateTime.cpp.
References KKU::TimeType::Hour(), KKU::TimeType::Minute(), KKU::TimeType::Second(), KKU::StrFormatInt(), and KKU::DateType::ToHours().
void DateTime::HoursAdd (int32 hours)
Add _hours to DateTime, will adjust date to accommodate 24 hour clock.
Definition at line 1173 of file DateTime.cpp.
References AddHours().
Referenced by AddMinutes().
void DateTime::MinutesAdd (int32 _mins)
Definition at line 1181 of file DateTime.cpp.
References AddMinutes().
Referenced by AddSeconds().
uchar KKU::DateTime::Month () const inline
Definition at line 253 of file DateTime.h.
References KKU::DateType::Month().
bool DateTime::operator!= (const DateTime & right) const
Definition at line 1235 of file DateTime.cpp.
DateTime DateTime::operator+ (const DateTime & right) const
Definition at line 1268 of file DateTime.cpp.
References DateTime(), KKU::DateType::Days(), and KKU::TimeType::Seconds().
DateTime DateTime::operator- (const DateTime & right) const
Definition at line 1280 of file DateTime.cpp.
References DateTime(), KKU::DateType::Days(), and KKU::TimeType::Seconds().
bool DateTime::operator< (const DateTime & right) const
Definition at line 1255 of file DateTime.cpp.
bool DateTime::operator<= (const DateTime & right) const
Definition at line 1261 of file DateTime.cpp.
DateTime & DateTime::operator= (const DateTime & right)
Definition at line 1218 of file DateTime.cpp.
bool DateTime::operator== (const DateTime & right) const
Definition at line 1228 of file DateTime.cpp.
bool DateTime::operator> (const DateTime & right) const
Definition at line 1242 of file DateTime.cpp.
bool DateTime::operator>= (const DateTime & right) const
Definition at line 1249 of file DateTime.cpp.
KKU::uint64 DateTime::Seconds () const
Definition at line 1082 of file DateTime.cpp.
References KKU::DateType::Seconds(), and KKU::TimeType::Seconds().
Referenced by MLL::DataBaseImageList::CalculateDensitesByQuadrat(), SipperHardware::InstrumentDataManager::CompReportLine(), CrossValidationApp::Main(), and CrossValidationApp::ValidationProcess().
void DateTime::SecondsAdd (long _secs)
Definition at line 1189 of file DateTime.cpp.
References AddSeconds().
const TimeType& KKU::DateTime::Time () const inline
Definition at line 244 of file DateTime.h.
Referenced by PicesInterface::PicesMethods::DateTimeKKUtoSystem(), SipperHardware::InstrumentData::FieldToStr(), PicesInterface::OSservices::KKuDateTimeToSystemDateTime(), and KKU::operator<<().
KKU::uint32 DateTime::ToDays () const
Definition at line 1090 of file DateTime.cpp.
References KKU::DateType::Days().
double DateTime::ToHours () const
Definition at line 1091 of file DateTime.cpp.
References KKU::DateType::Days(), and KKU::TimeType::ToHours().
KKU::uint64 DateTime::ToSeconds () const
Definition at line 1092 of file DateTime.cpp.
References KKU::DateType::Days(), and KKU::TimeType::Seconds().
short KKU::DateTime::Year () const inline
Definition at line 252 of file DateTime.h.
References KKU::DateType::Year().
Referenced by SipperHardware::InstrumentDataList::CreateFromSipperFile(), and SipperHardware::CTD_Plus_Data::ValidData().
KKStr DateTime::YYYY_MM_DD_HH_MM_SS () const
Definition at line 1203 of file DateTime.cpp.
References KKU::TimeType::HH_MM_SS(), and KKU::DateType::YYYY_MM_DD().
Referenced by MLL::DataBase::GpsDataDelete(), MLL::DataBase::GpsDataInsert(), MLL::DataBase::GpsDataQuery(), MLL::DataBase::InstrumentDataGetSpecificFields(), and MLL::DataBase::LogEntriesProcessStart().
KKStr DateTime::YYYYMMDDHHMMSS () const
Definition at line 1196 of file DateTime.cpp.
References KKU::TimeType::HHMMSS(), and KKU::DateType::YYYYMMDD().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/DateTime.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/DateTime.cpp