Pices: MLL::DuplicateImages Class Reference
MLL::DuplicateImages Class Reference
Detects duplicate images in a given FeaureVectorList objects.
#include <DuplicateImages.h>
Public Member Functions
DuplicateImages (FeatureVectorListPtr _examples, RunLog &_log)
You would use this instance to search for duplicates in the list of 'examples'.
DuplicateImages (FileDescPtr _fileDesc, RunLog &_log)
~DuplicateImages ()
bool AddExamples (FeatureVectorListPtr examples)
Will add all the examples; be carefull of ownership.
DuplicateImagePtr AddSingleImage (FeatureVectorPtr image)
Add one more FeatureVector to the list.
DuplicateImageListPtr DupImages () const
int32 DuplicateCount () const
int32 DuplicateDataCount () const
int32 DuplicateNameCount () const
bool DuplicatesFound () const
bool ExampleInDetector (FeatureVectorPtr fv)
FeatureVectorListPtr ListOfExamplesToDelete ()
void PurgeDuplicates (FeatureVectorListPtr examples, ostream *report)
if not equal NULL will list examles being purged.
void ReportDuplicates (ostream &o)
Detailed Description
Detects duplicate images in a given FeaureVectorList objects.
Author
Kurt Kramer
Will derive a list of duplicate FeatureVector objects in a given list. It will use both the Image File Name and feature data to detect duplicates. A duplicate can be detected in two ways. If two or more entries have the same ImageFileName or FeatureData.
The simplest way to use this object is to create an instance with a FeatureVectorList object that you are concerend with. Then call the method DupImages (), which will return the list of dupliactes found via a structure called DuplicateImageList.
Definition at line 55 of file DuplicateImages.h.
Constructor & Destructor Documentation
MLL::DuplicateImages::DuplicateImages (FeatureVectorListPtr _examples, RunLog & _log)
You would use this instance to search for duplicates in the list of 'examples'.
You can still call 'AddExamples' and 'AddSingleImage';
MLL::DuplicateImages::DuplicateImages (FileDescPtr _fileDesc, RunLog & _log)
DuplicateImages::~DuplicateImages (void)
Definition at line 72 of file DuplicateImages.cpp.
Member Function Documentation
bool DuplicateImages::AddExamples (FeatureVectorListPtr examples)
Will add all the examples; be carefull of ownership.
Definition at line 94 of file DuplicateImages.cpp.
References AddSingleImage().
DuplicateImagePtr DuplicateImages::AddSingleImage (FeatureVectorPtr image)
Add one more FeatureVector to the list.
Will add one more image to list and if it turns out to be a duplicate will return pointer to a "DuplicateImage" structure that will contain a list of all imags that it is duplicate to.
Will add one more image to list and if it turns out to be a duplicate will return pointer to a "DuplicateImage" structure that will contain a list of all images that it is duplicate to. If no duplicate found will then return a NULL pointer.
Parameters
[in] image FeatureVecvtor that you want to add to the list.
If no duplicate found will then return a NULL pointer.
Definition at line 118 of file DuplicateImages.cpp.
References MLL::DuplicateImage::AddADuplicate(), KKU::KKStr::Empty(), MLL::ImageFeaturesDataIndexed::GetEqual(), MLL::FeatureVector::ImageFileName(), MLL::DuplicateImageList::LocateByImage(), KKU::osGetRootName(), and MLL::ImageFeaturesDataIndexed::RBInsert().
Referenced by AddExamples(), and ImageExtractionManager::DataBaseUpdateThread::Run().
DuplicateImageListPtr MLL::DuplicateImages::DupImages () const inline
Definition at line 87 of file DuplicateImages.h.
Referenced by ListOfExamplesToDelete(), and PurgeDuplicates().
int32 MLL::DuplicateImages::DuplicateCount () const inline
Definition at line 89 of file DuplicateImages.h.
Referenced by CrossValidationApp::CheckForDuplicates().
int32 MLL::DuplicateImages::DuplicateDataCount () const inline
Definition at line 90 of file DuplicateImages.h.
int32 MLL::DuplicateImages::DuplicateNameCount () const inline
Definition at line 91 of file DuplicateImages.h.
bool DuplicateImages::DuplicatesFound () const
Definition at line 341 of file DuplicateImages.cpp.
Referenced by CrossValidationApp::CheckForDuplicates(), and CrossValidationApp::Main().
bool DuplicateImages::ExampleInDetector (FeatureVectorPtr fv)
Definition at line 81 of file DuplicateImages.cpp.
References MLL::ImageFeaturesDataIndexed::GetEqual(), and MLL::FeatureVector::ImageFileName().
FeatureVectorListPtr DuplicateImages::ListOfExamplesToDelete ()
Definition at line 254 of file DuplicateImages.cpp.
References MLL::DuplicateImage::AllTheSameClass(), DupImages(), MLL::DuplicateImage::DuplicatedImages(), KKU::endl(), MLL::DuplicateImage::FirstImageAdded(), MLL::FeatureVector::ImageFileName(), MLL::DuplicateImage::ImageWithSmallestScanLine(), KKU::RunLog::Level(), and MLL::FeatureVectorList::PushOnBack().
Referenced by CrossValidationApp::Main().
void DuplicateImages::PurgeDuplicates (FeatureVectorListPtr examples, ostream * report)
if not equal NULL will list examles being purged.
Delete duplicate examples from FeatureVectorList structure provided in constructor.
If duplicates are in more than one class then all will be deleted. if duplicates are in a single class then one with smallest scan line will be kept while all others will be deleted.
Definition at line 202 of file DuplicateImages.cpp.
References MLL::DuplicateImage::AllTheSameClass(), DupImages(), MLL::DuplicateImage::DuplicatedImages(), KKU::endl(), MLL::DuplicateImage::FirstImageAdded(), MLL::FeatureVector::ImageFileName(), MLL::DuplicateImage::ImageWithSmallestScanLine(), KKU::RunLog::Level(), and MLL::FeatureVector::MLClassName().
Referenced by PicesInterface::PicesTrainingConfiguration::LoadFeatureDataFromTrainingLibraries(), and MLL::FeatureVectorList::RemoveDuplicateEntries().
void DuplicateImages::ReportDuplicates (ostream & o)
Definition at line 302 of file DuplicateImages.cpp.
References MLL::DuplicateImage::DuplicatedImages(), KKU::endl(), MLL::FeatureVector::ImageFileName(), and MLL::FeatureVector::MLClassName().
Referenced by CrossValidationApp::CheckForDuplicates(), and CrossValidationApp::Main().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/DuplicateImages.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/DuplicateImages.cpp