Pices: KKU::ConvexHull Class Reference
KKU::ConvexHull Class Reference
#include <ConvexHull.h>
Public Member Functions
ConvexHull ()
~ConvexHull ()
int32 ConvexArea ()
void Draw (Raster &output)
RasterPtr Filter (Raster &src)
void Store (Raster &input)
Detailed Description
Definition at line 37 of file ConvexHull.h.
Constructor & Destructor Documentation
ConvexHull::ConvexHull ()
Definition at line 34 of file ConvexHull.cpp.
ConvexHull::~ConvexHull ()
Definition at line 43 of file ConvexHull.cpp.
Member Function Documentation
int32 ConvexHull::ConvexArea ()
Definition at line 122 of file ConvexHull.cpp.
void ConvexHull::Draw (Raster & output)
Definition at line 379 of file ConvexHull.cpp.
RasterPtr ConvexHull::Filter (Raster & src)
Definition at line 61 of file ConvexHull.cpp.
References KKU::Raster::Height(), and KKU::Raster::Width().
Referenced by PicesInterface::PicesRaster::ConvexHull().
void ConvexHull::Store (Raster & input)
Definition at line 681 of file ConvexHull.cpp.
References KKU::Raster::Height(), KKU::Raster::Rows(), and KKU::Raster::Width().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/ConvexHull.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/ConvexHull.cpp