Pices: SipperHardware::SipperCruise Class Reference
SipperHardware::SipperCruise Class Reference
#include <SipperCruise.h>
Public Types
typedef SipperCruise * SipperCruisePtr
Public Member Functions
SipperCruise ()
~SipperCruise ()
const KKStr & CruiseName () const
void CruiseName (const KKStr &_cruiseName)
const DateType & DateEnd () const
void DateEnd (const KKU::DateType &_dateEnd)
const DateType & DateStart () const
void DateStart (const KKU::DateType &_dateStart)
const KKStr & Description () const
void Description (const KKStr &_description)
const KKStr & Location () const
void Location (const KKStr &_location)
const KKStr & Objective () const
void Objective (const KKStr &_objective)
const KKStr & Principal () const
void Principal (const KKStr &_principal)
const KKStr & ResearchOrg () const
void ResearchOrg (const KKStr &_researchOrg)
const KKStr & ShipName () const
void ShipName (const KKStr &_shipName)
Static Public Member Functions
static KKStr ValidateCruiseName (const KKStr &_cruiseName)
Detailed Description
Definition at line 16 of file SipperCruise.h.
Member Typedef Documentation
typedef SipperCruise* SipperHardware::SipperCruise::SipperCruisePtr
Definition at line 19 of file SipperCruise.h.
Constructor & Destructor Documentation
SipperCruise::SipperCruise ()
Definition at line 25 of file SipperCruise.cpp.
SipperCruise::~SipperCruise ()
Definition at line 38 of file SipperCruise.cpp.
Member Function Documentation
const KKStr& SipperHardware::SipperCruise::CruiseName () const inline
Definition at line 25 of file SipperCruise.h.
Referenced by DetermineCropSettings(), SipperHardware::SipperCruiseList::CruiseNameComparator::operator()(), PicesInterface::PicesSipperStation::PicesSipperStation(), and MLL::DataBase::SipperCruiseInsert().
void SipperHardware::SipperCruise::CruiseName (const KKStr & _cruiseName) inline
Definition at line 35 of file SipperCruise.h.
const DateType& SipperHardware::SipperCruise::DateEnd () const inline
Definition at line 29 of file SipperCruise.h.
Referenced by MLL::DataBase::SipperCruiseInsert(), and MLL::DataBase::SipperCruiseUpdate().
void SipperHardware::SipperCruise::DateEnd (const KKU::DateType & _dateEnd) inline
Definition at line 39 of file SipperCruise.h.
const DateType& SipperHardware::SipperCruise::DateStart () const inline
Definition at line 28 of file SipperCruise.h.
Referenced by MLL::DataBase::SipperCruiseInsert(), and MLL::DataBase::SipperCruiseUpdate().
void SipperHardware::SipperCruise::DateStart (const KKU::DateType & _dateStart) inline
Definition at line 38 of file SipperCruise.h.
const KKStr& SipperHardware::SipperCruise::Description () const inline
Definition at line 27 of file SipperCruise.h.
Referenced by MLL::DataBase::SipperCruiseInsert(), and MLL::DataBase::SipperCruiseUpdate().
void SipperHardware::SipperCruise::Description (const KKStr & _description) inline
Definition at line 37 of file SipperCruise.h.
const KKStr& SipperHardware::SipperCruise::Location () const inline
Definition at line 30 of file SipperCruise.h.
Referenced by MLL::DataBase::SipperCruiseInsert(), and MLL::DataBase::SipperCruiseUpdate().
void SipperHardware::SipperCruise::Location (const KKStr & _location) inline
Definition at line 40 of file SipperCruise.h.
const KKStr& SipperHardware::SipperCruise::Objective () const inline
Definition at line 31 of file SipperCruise.h.
Referenced by MLL::DataBase::SipperCruiseInsert(), and MLL::DataBase::SipperCruiseUpdate().
void SipperHardware::SipperCruise::Objective (const KKStr & _objective) inline
Definition at line 41 of file SipperCruise.h.
const KKStr& SipperHardware::SipperCruise::Principal () const inline
Definition at line 32 of file SipperCruise.h.
Referenced by MLL::DataBase::SipperCruiseInsert(), and MLL::DataBase::SipperCruiseUpdate().
void SipperHardware::SipperCruise::Principal (const KKStr & _principal) inline
Definition at line 42 of file SipperCruise.h.
const KKStr& SipperHardware::SipperCruise::ResearchOrg () const inline
Definition at line 33 of file SipperCruise.h.
Referenced by MLL::DataBase::SipperCruiseInsert(), and MLL::DataBase::SipperCruiseUpdate().
void SipperHardware::SipperCruise::ResearchOrg (const KKStr & _researchOrg) inline
Definition at line 43 of file SipperCruise.h.
const KKStr& SipperHardware::SipperCruise::ShipName () const inline
Definition at line 26 of file SipperCruise.h.
Referenced by MLL::DataBase::SipperCruiseInsert(), and MLL::DataBase::SipperCruiseUpdate().
void SipperHardware::SipperCruise::ShipName (const KKStr & _shipName) inline
Definition at line 36 of file SipperCruise.h.
KKStr SipperCruise::ValidateCruiseName (const KKStr & _cruiseName) static
Definition at line 57 of file SipperCruise.cpp.
References KKU::KKStr::Append(), KKU::KKStr::Empty(), KKU::KKStr::Len(), and x.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/SipperCruise.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/SipperCruise.cpp