Pices: SipperHardware::Sipper3RevBuff Class Reference
SipperHardware::Sipper3RevBuff Class Reference
#include <Sipper3RevBuff.h>
Public Member Functions
Sipper3RevBuff (InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
Sipper3RevBuff (const KKStr &_fileName, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
~Sipper3RevBuff ()
uint32 CurRow ()
bool Eof ()
bool FileFormatGood ()
const KKStr & FileName ()
void GetNextLine (uchar *lineBuff, uint32 lineBuffSize, uint32 &lineSize, uint32 colCount[], uint32 &pixelsInRow, bool &flow)
bool Opened ()
uint32 RecCount ()
void SkipToScanLine (uint32 scanLine)
Public Member Functions inherited from SipperHardware::SipperBuff
SipperBuff (InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
SipperBuff (const KKStr &_fileName, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
virtual ~SipperBuff ()
uint64 ByteOffset () const
uint32 BytesDropped () const
uint32 CurRow () const
uint64 CurRowByteOffset () const
void DetermineCropSettings (uint32 &cropLeft, uint32 &cropRght)
bool Eof () const
const KKStr & FileName () const
void InvalidLine (bool _invalidLine)
bool InvalidLine () const
virtual int32 LineWidth () const
Returns the width in pixles of the associated scanner file.
void Open (const KKStr &_fileName)
bool Opened () const
uint32 RecCount () const
void ReportInstrumentData (uchar sensorId, bool text, uchar sensorData)
void Reset ()
void ResetByteOffset (uint32 _byteOffset)
int32 ScanRate () const
void SkipOneByte ()
void SkipToScanLine (uint32 scanLine)
void SkipToScanLine (uint32 _scanLine, uint64 _byteOffset)
Additional Inherited Members
Public Types inherited from SipperHardware::SipperBuff
typedef KKU::int32 int32
typedef SipperBuff * SipperBuffPtr
typedef KKU::uint32 uint32
Static Public Member Functions inherited from SipperHardware::SipperBuff
static SipperBuffPtr CreateSipperBuff (SipperFileFormat _format, KKStr _fileName, int32 _cameraNum, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
static SipperBuffPtr CreateSipperBuff (KKStr _fileName, int32 _cameraNum, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
static SipperFileFormat GuessFormatOfFile (const KKStr &_fileName, int32 _cameraNum, RunLog &_log)
Protected Member Functions inherited from SipperHardware::SipperBuff
void AssignSerialPorts (const SipperHeaderRecPtr sipperHeaderRec)
Static Protected Member Functions inherited from SipperHardware::SipperBuff
static void DisplaySipperRec (SipperBuff::SipperRec &sr)
static SipperFileFormat GuessFormatOfNextLine (FILE *in, int32 _cameraNum, RunLog &_log)
Protected Attributes inherited from SipperHardware::SipperBuff
uint64 byteOffset
uint32 bytesDropped
uint32 curRow
uint64 curRowByteOffset
bool eof
KKStr fileName
FILE * inFile
InstrumentDataManagerPtr instrumentDataManager
bool invalidLine
bool iOwnInstrumentDataManager
RunLog & log
bool opened
uint32 recCount
Detailed Description
Definition at line 10 of file Sipper3RevBuff.h.
Constructor & Destructor Documentation
Sipper3RevBuff::Sipper3RevBuff (InstrumentDataManagerPtr _instrumentDataManager, RunLog & _log)
Definition at line 47 of file Sipper3RevBuff.cpp.
References SipperHardware::SipperBuff::byteOffset.
Sipper3RevBuff::Sipper3RevBuff (const KKStr & _fileName, InstrumentDataManagerPtr _instrumentDataManager, RunLog & _log)
Definition at line 57 of file Sipper3RevBuff.cpp.
References SipperHardware::SipperBuff::byteOffset.
Sipper3RevBuff::~Sipper3RevBuff ()
Definition at line 72 of file Sipper3RevBuff.cpp.
References SipperHardware::SipperBuff::~SipperBuff().
Member Function Documentation
uint32 SipperHardware::Sipper3RevBuff::CurRow () inline
Definition at line 27 of file Sipper3RevBuff.h.
References SipperHardware::SipperBuff::curRow.
bool SipperHardware::Sipper3RevBuff::Eof () inline
Definition at line 29 of file Sipper3RevBuff.h.
References SipperHardware::SipperBuff::eof.
Referenced by FileFormatGood().
bool Sipper3RevBuff::FileFormatGood ()
Definition at line 445 of file Sipper3RevBuff.cpp.
References Eof(), Opened(), and SipperHardware::SipperBuff::Reset().
const KKStr& SipperHardware::Sipper3RevBuff::FileName () inline
Definition at line 25 of file Sipper3RevBuff.h.
References SipperHardware::SipperBuff::fileName.
void Sipper3RevBuff::GetNextLine (uchar * lineBuff, uint32 lineBuffSize, uint32 & lineSize, uint32 colCount[], uint32 & pixelsInRow, bool & flow) virtual
Implements SipperHardware::SipperBuff.
Definition at line 181 of file Sipper3RevBuff.cpp.
References SipperHardware::SipperBuff::curRow, KKU::endl(), SipperHardware::SipperBuff::eof, and x.
bool SipperHardware::Sipper3RevBuff::Opened () inline
Definition at line 31 of file Sipper3RevBuff.h.
References SipperHardware::SipperBuff::opened.
Referenced by FileFormatGood().
uint32 SipperHardware::Sipper3RevBuff::RecCount () inline
Definition at line 33 of file Sipper3RevBuff.h.
References SipperHardware::SipperBuff::recCount.
void SipperHardware::Sipper3RevBuff::SkipToScanLine (uint32 scanLine)
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/Sipper3RevBuff.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/Sipper3RevBuff.cpp