Pices: MLL::CrossValidationThreeWay Class Reference
MLL::CrossValidationThreeWay Class Reference
#include <CrossValidationThreeWay.h>
Public Member Functions
CrossValidationThreeWay (TrainingConfiguration2Ptr _config, bool useConfigAsIs, FeatureVectorListPtr _examples, MLClassConstListPtr _mlClasses, MLClassConstPtr _class1, MLClassConstPtr _class2, int32 _numOfFolds, bool _featuresAlreadyNormalized, bool _stratify, float _punishmentFactor, RunLog &_log)
~CrossValidationThreeWay (void)
float Accuracy ()
KKStr AccuracyStr ()
void CalculateAccuracyAndGrade ()
void CalculateThirdClassDecisiveProbability (float &mean, float &stdDev)
void CalculateThirdClassDecisiveProbability (FeatureVectorListPtr testData, float &mean, float &stdDev)
double ClassificationTime () const
void CreateDistanceReport (ostream &r)
void CreateProbabilityReport (ostream &r)
float FoldAccuracy (int32 foldNum)
KKStr FoldStr () const
float Grade () const
float NumOfSupportVectors () const
void RunValidation (void)
void RunValidationOnly (FeatureVectorListPtr validationData, bool *classedCorrectly)
double TrainingTime () const
Detailed Description
Definition at line 67 of file CrossValidationThreeWay.h.
Constructor & Destructor Documentation
CrossValidationThreeWay::CrossValidationThreeWay (TrainingConfiguration2Ptr _config, bool useConfigAsIs, FeatureVectorListPtr _examples, MLClassConstListPtr _mlClasses, MLClassConstPtr _class1, MLClassConstPtr _class2, int32 _numOfFolds, bool _featuresAlreadyNormalized, bool _stratify, float _punishmentFactor, RunLog & _log)
Definition at line 49 of file CrossValidationThreeWay.cpp.
References MLL::TrainingConfiguration2::AddATrainingClass(), MLL::TrainingConfiguration2::EmptyTrainingClasses(), and MLL::MLClassConstList::PushOnBack().
CrossValidationThreeWay::~CrossValidationThreeWay (void)
Definition at line 117 of file CrossValidationThreeWay.cpp.
Member Function Documentation
float MLL::CrossValidationThreeWay::Accuracy () inline
Definition at line 85 of file CrossValidationThreeWay.h.
KKStr CrossValidationThreeWay::AccuracyStr ()
Definition at line 614 of file CrossValidationThreeWay.cpp.
References MLL::ConfusionMatrix2::AccuracyStr().
void CrossValidationThreeWay::CalculateAccuracyAndGrade ()
Definition at line 218 of file CrossValidationThreeWay.cpp.
Referenced by RunValidation(), and RunValidationOnly().
void CrossValidationThreeWay::CalculateThirdClassDecisiveProbability (float & mean, float & stdDev)
Definition at line 625 of file CrossValidationThreeWay.cpp.
References MLL::FeatureVector::MLClass(), and MLL::FeatureVector::Probability().
void CrossValidationThreeWay::CalculateThirdClassDecisiveProbability (FeatureVectorListPtr testData, float & mean, float & stdDev)
Definition at line 668 of file CrossValidationThreeWay.cpp.
References MLL::FeatureVector::MLClass(), and MLL::FeatureVector::Probability().
double MLL::CrossValidationThreeWay::ClassificationTime () const inline
Definition at line 103 of file CrossValidationThreeWay.h.
void CrossValidationThreeWay::CreateDistanceReport (ostream & r)
Definition at line 369 of file CrossValidationThreeWay.cpp.
References KKU::Histogram::Bucket(), KKU::Histogram::BucketSize(), KKU::endl(), MLL::MLClassConstList::ExtractThreeTitleLines(), MLL::TrainingConfiguration2::GetFeatureNums(), KKU::Histogram::Increment(), SVM289_MFS::Max(), KKU::Histogram::MinValue(), MLL::FeatureVector::Probability(), KKU::StrFormatDouble(), and x.
void CrossValidationThreeWay::CreateProbabilityReport (ostream & r)
Definition at line 490 of file CrossValidationThreeWay.cpp.
References KKU::Histogram::Bucket(), KKU::Histogram::BucketSize(), KKU::endl(), MLL::MLClassConstList::ExtractThreeTitleLines(), MLL::TrainingConfiguration2::GetFeatureNums(), KKU::Histogram::Increment(), SVM289_MFS::Max(), KKU::Histogram::MinValue(), KKU::Histogram::NumOfBuckets(), MLL::FeatureVector::PredictedClass(), MLL::FeatureVector::Probability(), KKU::StrFormatDouble(), and x.
float CrossValidationThreeWay::FoldAccuracy (int32 foldNum)
Definition at line 756 of file CrossValidationThreeWay.cpp.
References KKU::endl(), KKU::RunLog::Level(), and KKU::osWaitForEnter().
KKStr CrossValidationThreeWay::FoldStr () const
Definition at line 787 of file CrossValidationThreeWay.cpp.
References x.
float MLL::CrossValidationThreeWay::Grade () const inline
Definition at line 113 of file CrossValidationThreeWay.h.
float MLL::CrossValidationThreeWay::NumOfSupportVectors () const inline
Definition at line 115 of file CrossValidationThreeWay.h.
void CrossValidationThreeWay::RunValidation (void)
Definition at line 160 of file CrossValidationThreeWay.cpp.
References CalculateAccuracyAndGrade(), MLL::FeatureVectorList::FileDesc(), MLL::FeatureVector::MLClass(), and MLL::FeatureVectorList::PushOnBack().
void CrossValidationThreeWay::RunValidationOnly (FeatureVectorListPtr validationData, bool * classedCorrectly)
Definition at line 714 of file CrossValidationThreeWay.cpp.
References MLL::FeatureVectorList::AddQueue(), CalculateAccuracyAndGrade(), KKU::endl(), MLL::FeatureVectorList::FileDesc(), and KKU::RunLog::Level().
double MLL::CrossValidationThreeWay::TrainingTime () const inline
Definition at line 123 of file CrossValidationThreeWay.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/CrossValidationThreeWay.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/CrossValidationThreeWay.cpp