Pices: CrossValidationApp Class Reference
CrossValidationApp Class Reference
#include <CrossValidationApp.h>
Public Types
typedef KKU::uint uint
Public Member Functions
CrossValidationApp ()
~CrossValidationApp ()
void CheckForDuplicates ()
void CmdLineHelp ()
void CrossValidate (FeatureVectorListPtr testImages, FeatureVectorListPtr trainingImages, ConfusionMatrix2 &cm, ConfusionMatrix2 &cm2cdGuess, ConfusionMatrix2 &cmSmall, ConfusionMatrix2 &cmMed, ConfusionMatrix2 &cmLarge, int &foldCount, double &foldAccuracy, int foldNum, double &trainingTime, double &classificationTime, int &reductionPreImageCount, int &reductionPostImageCount, double &reductionTime, int &supportPoints, KKStr &bitReductionByFeature)
void CrossValidationsByHierarchy ()
void DistributesImagesRandomlyWithInFolds (int imagesPerClass, bool &successful)
KKStr LocateImageFileUsingConfigurationFile (const KKStr &fileName, MLClassConstPtr knownClass)
int Main (int argc, char **argv)
void PerformBinaryClassCrossValidations ()
void PerformTrueBinaryClassCrossValidations ()
void PostMisclassifiedImage (KKStr fileName, MLClassConstPtr knownClass, MLClassConstPtr predictedClass)
void PrintSizeHistogram ()
void ProcessCmdLineParameter (KKStr parmSwitch, KKStr parmValue)
void ProcessCmdLineParameters (int argc, char **argv)
FeatureVectorListPtr RandomlySampleData (const FeatureVectorListPtr data, float percentToKeep, double &samplingTime)
void RandomlySelectedProcessResults (vector< CrossValidationRunPtr > &crossValidations, int numToCombine, KKStr order)
void RandomlySelectedResults (vector< CrossValidationRunPtr > &crossValidations, KKStr order)
void RandomSplitsIntoTrainAndTest (FeatureVectorListPtr splitData, FeatureVectorListPtr &splitDataTrain, FeatureVectorListPtr &splitDataTest)
void RemoveDuplicateImages (FeatureVectorList &examples)
void ReportCmdLineParameters ()
void ReportConfigurationInfo ()
void TestBitreductionPerformance ()
void TestRandomSamplingTimings ()
void TryEachFeature (FeatureVectorListPtr trainingImages, ostream &r)
void ValidationProcess ()
void WriteABiasMatrix (ConfusionMatrix2 &cm)
Public Attributes
bool cancelFlag
TrainingConfiguration2Ptr config
KKStr configFileName
bool copyMissClassedImages
bool crossValidationByHierarcy
KKStr directory
bool doRandomSplits
DateTime endTime
FeatureVectorListPtr examples
bool featuresAreNormalizedAlready
FileDescPtr fileDesc
bool generateBiasMatrix
FeatureFileIOPtr inputFormat
KKStr loadFileName
KKStr missedClassedDir
MLClassConstListPtr mlClasses
MLClassConstPtr noiseMLClass
int numOfFolds
int numRandomSplits
ofstream * predictionReport
KKStr predictionReportName
ofstream * probReport
KKStr probReportName
float punishmentFactor
int randomFeatures
bool randomizeInputData
FeatureNumListPtr randomlySelectedFeatureNums
int randomSetWidth
double reduction_time
ostream * report
KKStr reportFileName
ofstream * reportFileStream
RunLog runLog
KKStr saveFileName
float splitPercentage
DateTime startTime
bool tryEachFeature
FeatureVectorListPtr validationData
KKStr validationFileName
Detailed Description
Definition at line 26 of file CrossValidationApp.h.
Member Typedef Documentation
typedef KKU::uint CrossValidationApp::uint
Definition at line 29 of file CrossValidationApp.h.
Constructor & Destructor Documentation
CrossValidationApp::CrossValidationApp ()
Definition at line 458 of file CrossValidation.cpp.
References mlClasses.
Referenced by main().
CrossValidationApp::~CrossValidationApp ()
Definition at line 493 of file CrossValidation.cpp.
References config, examples, mlClasses, probReport, reportFileStream, and validationData.
Member Function Documentation
void CrossValidationApp::CheckForDuplicates ()
Definition at line 2049 of file CrossValidation.cpp.
References MLL::FeatureVectorList::AddQueue(), MLL::DuplicateImages::DuplicateCount(), MLL::DuplicateImages::DuplicatesFound(), KKU::endl(), examples, MLL::FeatureVectorList::FileName(), KKU::osWaitForEnter(), report, MLL::DuplicateImages::ReportDuplicates(), runLog, and validationData.
Referenced by Main().
void CrossValidationApp::CmdLineHelp ()
Definition at line 562 of file CrossValidation.cpp.
References KKU::endl().
Referenced by ProcessCmdLineParameter(), and ProcessCmdLineParameters().
void CrossValidationApp::CrossValidate (FeatureVectorListPtr testImages, FeatureVectorListPtr trainingImages, ConfusionMatrix2 & cm, ConfusionMatrix2 & cm2cdGuess, ConfusionMatrix2 & cmSmall, ConfusionMatrix2 & cmMed, ConfusionMatrix2 & cmLarge, int & foldCount, double & foldAccuracy, int foldNum, double & trainingTime, double & classificationTime, int & reductionPreImageCount, int & reductionPostImageCount, double & reductionTime, int & supportPoints, KKStr & bitReductionByFeature)
Definition at line 1306 of file CrossValidation.cpp.
References MLL::TrainingProcess2::BitReductionByFeature(), MLL::Classifier2::ClassifyAImage(), MLL::TrainingProcess2::CreateModelsFromTrainingData(), KKU::endl(), MLL::FeatureVector::ImageFileName(), MLL::ConfusionMatrix2::Increment(), MLL::FeatureVector::MLClass(), MLL::TrainingProcess2::NumOfSupportVectors(), MLL::FeatureVector::OrigSize(), KKU::osGetRootName(), KKU::osGetSystemTimeUsed(), MLL::Classifier2::ProbabilitiesByClass(), MLL::TrainingProcess2::ReductionPostExampleCount(), MLL::TrainingProcess2::ReductionPreExampleCount(), MLL::TrainingProcess2::ReductionTime(), KKU::StrFormatDouble(), thresholdMed, thresholdSmall, and MLL::TrainingProcess2::TrainingTime().
Referenced by Main().
void CrossValidationApp::CrossValidationsByHierarchy ()
void CrossValidationApp::DistributesImagesRandomlyWithInFolds (int imagesPerClass, bool & successful)
Definition at line 543 of file CrossValidation.cpp.
References KKU::endl(), examples, KKU::RunLog::Level(), mlClasses, numOfFolds, runLog, and MLL::FeatureVectorList::StratifyAmoungstClasses().
Referenced by Main(), and ProcessCmdLineParameters().
KKStr CrossValidationApp::LocateImageFileUsingConfigurationFile (const KKStr & fileName, MLClassConstPtr knownClass)
Definition at line 1218 of file CrossValidation.cpp.
References config, KKU::KKStr::Empty(), MLL::TrainingClass::ExpandedDirectory(), MLL::TrainingClass::MLClass(), KKU::osLookForFile(), MLL::TrainingConfiguration2::RootDir(), and MLL::TrainingConfiguration2::TrainingClasses().
int CrossValidationApp::Main (int argc, char ** argv)
Definition at line 2230 of file CrossValidation.cpp.
References MLL::FeatureVectorList::AllFeatures(), cancelFlag, CheckForDuplicates(), MLL::FeatureVectorList::ClassStatisticsStr(), config, CrossValidate(), DistributesImagesRandomlyWithInFolds(), MLL::DuplicateImages::DuplicatesFound(), KKU::KKStr::Empty(), KKU::endl(), endTime, examples, fileDesc, generateBiasMatrix, MLL::TrainingConfiguration2::ImagesPerClass(), inputFormat, KKU::RunLog::Level(), MLL::DuplicateImages::ListOfExamplesToDelete(), mlClasses, numOfFolds, KKU::osGetKernalTimeUsed(), KKU::osGetLocalDateTime(), KKU::osGetUserTimeUsed(), KKU::osWaitForEnter(), predictionReport, predictionReportName, MLL::ConfusionMatrix2::PrintConfusionMatrixLatexTable(), MLL::ConfusionMatrix2::PrintConfusionMatrixTabDelimited(), MLL::ConfusionMatrix2::PrintErrorByProbByRows(), MLL::ConfusionMatrix2::PrintErrorBySizeByRows(), MLL::ConfusionMatrix2::PrintErrorBySizeReduced(), PrintSizeHistogram(), ProcessCmdLineParameters(), MLL::FeatureVectorList::PushOnBack(), randomizeInputData, reduction_time, report, ReportCmdLineParameters(), ReportConfigurationInfo(), MLL::DuplicateImages::ReportDuplicates(), reportFileName, reportFileStream, runLog, MLL::FeatureFileIO::SaveFeatureFile(), saveFileName, KKU::DateTime::Seconds(), startTime, KKU::KKStr::Str(), KKU::StrFormatDouble(), validationData, validationFileName, ValidationProcess(), WriteABiasMatrix(), and x.
Referenced by main().
void CrossValidationApp::PerformBinaryClassCrossValidations ()
void CrossValidationApp::PerformTrueBinaryClassCrossValidations ()
void CrossValidationApp::PostMisclassifiedImage (KKStr fileName, MLClassConstPtr knownClass, MLClassConstPtr predictedClass)
Definition at line 1260 of file CrossValidation.cpp.
References DS, KKU::KKStr::Empty(), KKU::endl(), KKU::KKStr::LocateLastOccurrence(), missedClassedDir, KKU::osAddSlash(), KKU::osCopyFileBetweenDirectories(), KKU::osCreateDirectoryPath(), KKU::osLookForFile(), and KKU::KKStr::SubStrPart().
Referenced by ValidationProcess().
void CrossValidationApp::PrintSizeHistogram ()
Definition at line 1792 of file CrossValidation.cpp.
References examples, MLL::ConfusionMatrix2::Increment(), MLL::FeatureVector::MLClass(), mlClasses, MLL::FeatureVector::OrigSize(), MLL::ConfusionMatrix2::PrintErrorBySize(), MLL::ConfusionMatrix2::PrintErrorBySizeByRows(), report, runLog, and x.
Referenced by Main().
void CrossValidationApp::ProcessCmdLineParameter (KKStr parmSwitch, KKStr parmValue)
Definition at line 598 of file CrossValidation.cpp.
References KKU::RunLog::AttachFile(), CmdLineHelp(), configFileName, copyMissClassedImages, directory, KKU::KKStr::Empty(), KKU::endl(), featuresAreNormalizedAlready, generateBiasMatrix, inputFormat, KKU::RunLog::Level(), loadFileName, missedClassedDir, numOfFolds, KKU::osValidDirectory(), KKU::osWaitForEnter(), predictionReportName, probReportName, randomizeInputData, reportFileName, runLog, saveFileName, splitPercentage, KKU::KKStr::Str(), KKU::KKStr::ToPercentage(), KKU::KKStr::Upper(), and validationFileName.
Referenced by ProcessCmdLineParameters().
void CrossValidationApp::ProcessCmdLineParameters (int argc, char ** argv)
Definition at line 873 of file CrossValidation.cpp.
References cancelFlag, CmdLineHelp(), config, configFileName, directory, DistributesImagesRandomlyWithInFolds(), KKU::KKStr::Empty(), KKU::endl(), examples, KKU::CmdLineExpander::ExpandedParameters(), MLL::TrainingConfiguration2::ExtractClassList(), MLL::FeatureVectorList::ExtractMLClassConstList(), fileDesc, MLL::FeatureVectorList::FileDesc(), generateBiasMatrix, inputFormat, KKU::RunLog::Level(), MLL::TrainingConfiguration2::LoadFeatureDataFromTrainingLibraries(), MLL::FeatureFileIO::LoadFeatureFile(), loadFileName, mlClasses, KKU::osFileExists(), KKU::osRemoveExtension(), KKU::osWaitForEnter(), KKU::CmdLineExpander::ParmsGood(), ProcessCmdLineParameter(), RemoveDuplicateImages(), MLL::FeatureVectorList::RemoveEntriesWithMissingFeatures(), runLog, MLL::TrainingConfiguration2::Save(), MLL::MLClassConstList::SortByName(), validationData, validationFileName, and x.
Referenced by Main().
FeatureVectorListPtr CrossValidationApp::RandomlySampleData (const FeatureVectorListPtr data, float percentToKeep, double & samplingTime)
Definition at line 2020 of file CrossValidation.cpp.
References endTime, fileDesc, KKU::osGetSystemTimeUsed(), MLL::FeatureVectorList::PushOnBack(), runLog, startTime, and x.
void CrossValidationApp::RandomlySelectedProcessResults (vector< CrossValidationRunPtr > & crossValidations, int numToCombine, KKStr order)
Definition at line 1971 of file CrossValidation.cpp.
References config, KKU::KKStr::Empty(), KKU::endl(), CrossValidationRun::features, fileDesc, CrossValidationRun::id, MLL::FeatureNumList::NumOfFeatures(), report, MLL::TrainingConfiguration2::SetFeatureNums(), and x.
void CrossValidationApp::RandomlySelectedResults (vector< CrossValidationRunPtr > & crossValidations, KKStr order)
Definition at line 1925 of file CrossValidation.cpp.
References MLL::CrossValidation::Accuracy(), CrossValidationRun::cv, KKU::endl(), CrossValidationRun::features, CrossValidationRun::id, MLL::FeatureNumList::NumOfFeatures(), MLL::CrossValidation::NumOfSupportVectors(), report, MLL::CrossValidation::TestTimeTotal(), MLL::FeatureNumList::ToString(), and MLL::CrossValidation::TrainTimeTotal().
void CrossValidationApp::RandomSplitsIntoTrainAndTest (FeatureVectorListPtr splitData, FeatureVectorListPtr & splitDataTrain, FeatureVectorListPtr & splitDataTest)
Definition at line 2148 of file CrossValidation.cpp.
References KKU::endl(), MLL::FeatureVectorList::ExtractMLClassConstList(), MLL::FeatureVectorList::FileDesc(), KKU::RunLog::Level(), MLL::FeatureVectorList::PushOnBack(), runLog, and splitPercentage.
void CrossValidationApp::RemoveDuplicateImages (FeatureVectorList & examples)
Definition at line 507 of file CrossValidation.cpp.
References MLL::FeatureVector::ClassName(), KKU::endl(), KKU::RunLog::Level(), MLL::FeatureVectorList::LookUpByImageFileName(), and runLog.
Referenced by ProcessCmdLineParameters().
void CrossValidationApp::ReportCmdLineParameters ()
Definition at line 846 of file CrossValidation.cpp.
References configFileName, directory, MLL::FeatureFileIO::DriverName(), KKU::KKStr::Empty(), KKU::endl(), featuresAreNormalizedAlready, KKU::RunLog::FileName(), inputFormat, loadFileName, numOfFolds, predictionReportName, probReportName, report, reportFileName, runLog, saveFileName, and validationFileName.
Referenced by Main().
void CrossValidationApp::ReportConfigurationInfo ()
Definition at line 1816 of file CrossValidation.cpp.
References config, MLL::TrainingClass::Directory(), KKU::endl(), MLL::TrainingConfiguration2::GetFeatureNums(), MLL::TrainingConfiguration2::ModelingMethod(), MLL::TrainingConfiguration2::ModelParameters(), MLL::TrainingClass::Name(), report, MLL::TrainingConfiguration2::RootDir(), MLL::ModelParam::ToCmdLineStr(), MLL::FeatureNumList::ToString(), MLL::TrainingConfiguration2::TrainingClasses(), and MLL::TrainingClass::Weight().
Referenced by Main().
void CrossValidationApp::TestBitreductionPerformance ()
void CrossValidationApp::TestRandomSamplingTimings ()
void CrossValidationApp::TryEachFeature (FeatureVectorListPtr trainingImages, ostream & r)
void CrossValidationApp::ValidationProcess ()
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! changed probs to votes
Definition at line 1552 of file CrossValidation.cpp.
References cancelFlag, MLL::Classifier2::ClassifyAImage(), config, copyMissClassedImages, MLL::TrainingProcess2::CreateModelsFromTrainingData(), KKU::KKStr::Empty(), KKU::endl(), endTime, examples, featuresAreNormalizedAlready, fileDesc, MLL::MLClassConstList::GetNoiseClass(), MLL::FeatureVector::ImageFileName(), MLL::ConfusionMatrix2::Increment(), KKU::RunLog::Level(), MLL::FeatureVector::MLClass(), mlClasses, noiseMLClass, MLL::TrainingProcess2::NumOfSupportVectors(), MLL::FeatureVector::OrigSize(), KKU::osGetLocalDateTime(), KKU::osGetRootName(), KKU::osGetSystemTimeUsed(), KKU::osWaitForEnter(), PostMisclassifiedImage(), predictionReport, MLL::ConfusionMatrix2::PrintConfusionMatrixTabDelimited(), MLL::ConfusionMatrix2::PrintErrorByProb(), MLL::Classifier2::ProbabilitiesByClass(), probReport, probReportName, reduction_time, MLL::TrainingProcess2::ReductionPostExampleCount(), MLL::TrainingProcess2::ReductionPreExampleCount(), MLL::TrainingProcess2::ReductionRatio(), MLL::TrainingProcess2::ReductionTime(), report, runLog, KKU::DateTime::Seconds(), startTime, KKU::KKStr::Str(), KKU::StrFormatDouble(), and validationData.
Referenced by Main().
void CrossValidationApp::WriteABiasMatrix (ConfusionMatrix2 & cm)
Definition at line 2185 of file CrossValidation.cpp.
References config, configFileName, KKU::KKStr::Empty(), KKU::endl(), KKU::RunLog::Level(), KKU::osGetFileDateTime(), KKU::osGetLocalDateTime(), KKU::osRemoveExtension(), runLog, KKU::KKStr::Str(), and MLL::ConfusionMatrix2::WriteSimpleConfusionMatrix().
Referenced by Main().
Member Data Documentation
bool CrossValidationApp::cancelFlag
Definition at line 39 of file CrossValidationApp.h.
Referenced by Main(), MarineSnowReportDeployment(), ProcessCmdLineParameters(), SetNineClassesTrainAndTest(), SetUpJMLRDataSet(), SetUpLetterDataSet(), SplitUpETPdataSet(), SplitUpForestData(), and ValidationProcess().
TrainingConfiguration2Ptr CrossValidationApp::config
Definition at line 41 of file CrossValidationApp.h.
Referenced by LocateImageFileUsingConfigurationFile(), Main(), ProcessCmdLineParameters(), RandomlySelectedProcessResults(), ReportConfigurationInfo(), SetUpJMLRDataSet(), SplitUpETPdataSet(), ValidationProcess(), WriteABiasMatrix(), and ~CrossValidationApp().
KKStr CrossValidationApp::configFileName
Definition at line 42 of file CrossValidationApp.h.
Referenced by ProcessCmdLineParameter(), ProcessCmdLineParameters(), ReportCmdLineParameters(), and WriteABiasMatrix().
bool CrossValidationApp::copyMissClassedImages
Definition at line 44 of file CrossValidationApp.h.
Referenced by ProcessCmdLineParameter(), and ValidationProcess().
bool CrossValidationApp::crossValidationByHierarcy
Definition at line 46 of file CrossValidationApp.h.
KKStr CrossValidationApp::directory
Definition at line 48 of file CrossValidationApp.h.
Referenced by ProcessCmdLineParameter(), ProcessCmdLineParameters(), and ReportCmdLineParameters().
bool CrossValidationApp::doRandomSplits
Definition at line 50 of file CrossValidationApp.h.
DateTime CrossValidationApp::endTime
Definition at line 52 of file CrossValidationApp.h.
Referenced by Main(), RandomlySampleData(), and ValidationProcess().
FeatureVectorListPtr CrossValidationApp::examples
Definition at line 58 of file CrossValidationApp.h.
Referenced by CheckForDuplicates(), DistributesImagesRandomlyWithInFolds(), Main(), PrintSizeHistogram(), ProcessCmdLineParameters(), ValidationProcess(), and ~CrossValidationApp().
bool CrossValidationApp::featuresAreNormalizedAlready
Definition at line 54 of file CrossValidationApp.h.
Referenced by ProcessCmdLineParameter(), ReportCmdLineParameters(), and ValidationProcess().
FileDescPtr CrossValidationApp::fileDesc
Definition at line 56 of file CrossValidationApp.h.
Referenced by CreateBfsFromMfs(), Main(), ProcessCmdLineParameters(), RandomlySampleData(), RandomlySelectedProcessResults(), and ValidationProcess().
bool CrossValidationApp::generateBiasMatrix
Definition at line 35 of file CrossValidationApp.h.
Referenced by Main(), ProcessCmdLineParameter(), and ProcessCmdLineParameters().
FeatureFileIOPtr CrossValidationApp::inputFormat
Definition at line 62 of file CrossValidationApp.h.
Referenced by Main(), ProcessCmdLineParameter(), ProcessCmdLineParameters(), and ReportCmdLineParameters().
KKStr CrossValidationApp::loadFileName
Definition at line 64 of file CrossValidationApp.h.
Referenced by ProcessCmdLineParameter(), ProcessCmdLineParameters(), and ReportCmdLineParameters().
KKStr CrossValidationApp::missedClassedDir
Definition at line 66 of file CrossValidationApp.h.
Referenced by PostMisclassifiedImage(), and ProcessCmdLineParameter().
MLClassConstListPtr CrossValidationApp::mlClasses
Definition at line 60 of file CrossValidationApp.h.
Referenced by CrossValidationApp(), DistributesImagesRandomlyWithInFolds(), Main(), PrintSizeHistogram(), ProcessCmdLineParameters(), ValidationProcess(), and ~CrossValidationApp().
MLClassConstPtr CrossValidationApp::noiseMLClass
Definition at line 69 of file CrossValidationApp.h.
Referenced by ValidationProcess().
int CrossValidationApp::numOfFolds
Definition at line 71 of file CrossValidationApp.h.
Referenced by DistributesImagesRandomlyWithInFolds(), Main(), ProcessCmdLineParameter(), and ReportCmdLineParameters().
int CrossValidationApp::numRandomSplits
Definition at line 73 of file CrossValidationApp.h.
ofstream* CrossValidationApp::predictionReport
Definition at line 75 of file CrossValidationApp.h.
Referenced by Main(), and ValidationProcess().
KKStr CrossValidationApp::predictionReportName
Definition at line 77 of file CrossValidationApp.h.
Referenced by Main(), ProcessCmdLineParameter(), and ReportCmdLineParameters().
ofstream* CrossValidationApp::probReport
Definition at line 79 of file CrossValidationApp.h.
Referenced by ValidationProcess(), and ~CrossValidationApp().
KKStr CrossValidationApp::probReportName
Definition at line 81 of file CrossValidationApp.h.
Referenced by ProcessCmdLineParameter(), ReportCmdLineParameters(), and ValidationProcess().
float CrossValidationApp::punishmentFactor
Definition at line 83 of file CrossValidationApp.h.
int CrossValidationApp::randomFeatures
Definition at line 88 of file CrossValidationApp.h.
bool CrossValidationApp::randomizeInputData
Definition at line 91 of file CrossValidationApp.h.
Referenced by Main(), and ProcessCmdLineParameter().
FeatureNumListPtr CrossValidationApp::randomlySelectedFeatureNums
Definition at line 96 of file CrossValidationApp.h.
int CrossValidationApp::randomSetWidth
Definition at line 98 of file CrossValidationApp.h.
double CrossValidationApp::reduction_time
Definition at line 100 of file CrossValidationApp.h.
Referenced by Main(), and ValidationProcess().
ostream* CrossValidationApp::report
Definition at line 104 of file CrossValidationApp.h.
Referenced by CheckForDuplicates(), Main(), PrintSizeHistogram(), RandomlySelectedProcessResults(), RandomlySelectedResults(), ReportCmdLineParameters(), ReportConfigurationInfo(), and ValidationProcess().
KKStr CrossValidationApp::reportFileName
Definition at line 102 of file CrossValidationApp.h.
Referenced by Main(), ProcessCmdLineParameter(), and ReportCmdLineParameters().
ofstream* CrossValidationApp::reportFileStream
Definition at line 106 of file CrossValidationApp.h.
Referenced by Main(), and ~CrossValidationApp().
RunLog CrossValidationApp::runLog
Definition at line 108 of file CrossValidationApp.h.
Referenced by CheckForDuplicates(), DistributesImagesRandomlyWithInFolds(), Main(), MarineSnowReport(), PrintSizeHistogram(), ProcessCmdLineParameter(), ProcessCmdLineParameters(), RandomlySampleData(), RandomSplitsIntoTrainAndTest(), RemoveDuplicateImages(), ReportCmdLineParameters(), ValidationProcess(), and WriteABiasMatrix().
KKStr CrossValidationApp::saveFileName
Definition at line 110 of file CrossValidationApp.h.
Referenced by Main(), ProcessCmdLineParameter(), and ReportCmdLineParameters().
float CrossValidationApp::splitPercentage
Definition at line 113 of file CrossValidationApp.h.
Referenced by ProcessCmdLineParameter(), and RandomSplitsIntoTrainAndTest().
DateTime CrossValidationApp::startTime
Definition at line 115 of file CrossValidationApp.h.
Referenced by Main(), RandomlySampleData(), and ValidationProcess().
bool CrossValidationApp::tryEachFeature
Definition at line 117 of file CrossValidationApp.h.
FeatureVectorListPtr CrossValidationApp::validationData
Definition at line 120 of file CrossValidationApp.h.
Referenced by CheckForDuplicates(), Main(), ProcessCmdLineParameters(), SetNineClassesTrainAndTest(), SplitUpETPdataSet(), SplitUpForestData(), ValidationProcess(), and ~CrossValidationApp().
KKStr CrossValidationApp::validationFileName
Definition at line 122 of file CrossValidationApp.h.
Referenced by Main(), ProcessCmdLineParameter(), ProcessCmdLineParameters(), and ReportCmdLineParameters().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/Apps/CrossValidation/CrossValidationApp.h
D:/Users/kkramer/IEC/SipperSoftware/Apps/CrossValidation/CrossValidation.cpp
D:/Users/kkramer/IEC/SipperSoftware/Apps/CrossValidation/CrossValidation_TEmp.cpp