Pices: MLL::ClassIndexList Class Reference
MLL::ClassIndexList Class Reference
Maintains a list of classes and their associated integer index.
#include <MLClass.h>
Public Types
typedef ClassIndexList * ClassIndexListPtr
typedef KKU::int32 int32
typedef KKU::uint32 uint32
Public Member Functions
ClassIndexList ()
ClassIndexList (const ClassIndexList &_list)
ClassIndexList (const MLClassList &_classes)
ClassIndexList (const MLClassConstList &_classes)
void AddClass (MLClassConstPtr _ic, bool &_dupEntry)
void AddClassIndexAssignment (MLClassConstPtr _ic, short _classIndex, bool &_dupEntry)
virtual void Clear ()
short GetClassIndex (MLClassConstPtr c)
Returns the corresponding index to the class 'c'; if not in list will return -1.
MLClassConstPtr GetMLClass (short classIndex)
Locates the MLClass that was assigned classIndex.
int32 MemoryConsumedEstimated () const
void ParseClassIndexList (const KKStr &s)
KKStr ToCommaDelString ()
Detailed Description
Maintains a list of classes and their associated integer index.
Multiple Classes can have the same index but a class may only appear once in the list. The primary purpose of this class is to allow the quick access to classes by numerical indexes. This comes in useful when communicating with another library that does not recognize alpha numeric strings for class names such libSVM which only uses integers class names.
See Also
MLL::Model
MLL::FeatureEncoder2::compress
Definition at line 478 of file MLClass.h.
Member Typedef Documentation
typedef ClassIndexList* MLL::ClassIndexList::ClassIndexListPtr
Definition at line 481 of file MLClass.h.
typedef KKU::int32 MLL::ClassIndexList::int32
Definition at line 483 of file MLClass.h.
typedef KKU::uint32 MLL::ClassIndexList::uint32
Definition at line 484 of file MLClass.h.
Constructor & Destructor Documentation
ClassIndexList::ClassIndexList ()
Definition at line 1310 of file MLClass.cpp.
Referenced by MemoryConsumedEstimated().
ClassIndexList::ClassIndexList (const ClassIndexList & _list)
Definition at line 1316 of file MLClass.cpp.
References AddClassIndexAssignment().
ClassIndexList::ClassIndexList (const MLClassList & _classes)
Definition at line 1328 of file MLClass.cpp.
ClassIndexList::ClassIndexList (const MLClassConstList & _classes)
Definition at line 1342 of file MLClass.cpp.
Member Function Documentation
void ClassIndexList::AddClass (MLClassConstPtr _ic, bool & _dupEntry)
Definition at line 1377 of file MLClass.cpp.
References index().
void ClassIndexList::AddClassIndexAssignment (MLClassConstPtr _ic, short _classIndex, bool & _dupEntry)
Definition at line 1399 of file MLClass.cpp.
Referenced by ClassIndexList(), ParseClassIndexList(), and MLL::FeatureFileIOPices::SaveFile().
void ClassIndexList::Clear () virtual
Definition at line 1359 of file MLClass.cpp.
Referenced by ParseClassIndexList().
short ClassIndexList::GetClassIndex (MLClassConstPtr c)
Returns the corresponding index to the class 'c'; if not in list will return -1.
Definition at line 1422 of file MLClass.cpp.
References index().
Referenced by MLL::ModelSvmBase::ProbabilitiesByClass(), MLL::ModelSvmBase::RetrieveCrossProbTable(), MLL::Model::RetrieveCrossProbTable(), MLL::FeatureFileIOPices::SaveFile(), and MLL::ModelSvmBase::TrainModel().
MLClassConstPtr ClassIndexList::GetMLClass (short classIndex)
Locates the MLClass that was assigned classIndex.
If not found then returns NULL. If more than one class has the same classIndex will return the first one added.
Definition at line 1437 of file MLClass.cpp.
Referenced by MLL::ModelSvmBase::Predict(), MLL::ModelKnn::ProbabilitiesByClass(), and MLL::ModelSvmBase::ProbabilitiesByClass().
int32 ClassIndexList::MemoryConsumedEstimated () const
Definition at line 1370 of file MLClass.cpp.
References ClassIndexList().
Referenced by MLL::Model::MemoryConsumedEstimated().
void ClassIndexList::ParseClassIndexList (const KKStr & s)
Definition at line 1449 of file MLClass.cpp.
References AddClassIndexAssignment(), Clear(), MLL::MLClass::CreateNewMLClass(), KKU::KKStr::ExtractToken2(), KKU::KKStr::ExtractTokenInt(), index(), KKU::KKStr::Split(), and x.
Referenced by MLL::Model::ReadXML().
KKStr ClassIndexList::ToCommaDelString ()
Definition at line 1470 of file MLClass.cpp.
References KKU::KKStr::Empty().
Referenced by MLL::Model::WriteXML().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/MLClass.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/MLClass.cpp