Pices: SipperHardware::Instrument Class Reference
SipperHardware::Instrument Class Reference abstract
#include <Instrument.h>
Public Types
typedef Instrument * InstrumentPtr
typedef KKU::int32 int32
typedef KKU::int64 int64
typedef KKU::uint32 uint32
typedef KKU::uint64 uint64
Public Member Functions
Instrument (const KKStr &_shortName, const KKStr &_description)
virtual ~Instrument ()
virtual InstrumentDataReportPtr CreateInstrumentDataReporter (InstrumentDataManagerPtr _manager, const KKStr &_reportDir, int32 _instrumentId)=0
const KKStr & Description () const
virtual bool Other () const
const KKStr & ShortName () const
Static Public Member Functions
static void FinalCleanUp ()
Deletes objects pointed to by 'instruments[]'; this way the don't confuse the memory dump that occurs at the end of a program in Debug Mode.
static InstrumentPtr LookUpByShortName (const KKStr &_shortName)
static InstrumentPtr OtherInstrument ()
Detailed Description
Definition at line 24 of file Instrument.h.
Member Typedef Documentation
typedef Instrument* SipperHardware::Instrument::InstrumentPtr
Definition at line 32 of file Instrument.h.
typedef KKU::int32 SipperHardware::Instrument::int32
Definition at line 27 of file Instrument.h.
typedef KKU::int64 SipperHardware::Instrument::int64
Definition at line 29 of file Instrument.h.
typedef KKU::uint32 SipperHardware::Instrument::uint32
Definition at line 28 of file Instrument.h.
typedef KKU::uint64 SipperHardware::Instrument::uint64
Definition at line 30 of file Instrument.h.
Constructor & Destructor Documentation
Instrument::Instrument (const KKStr & _shortName, const KKStr & _description)
Definition at line 45 of file Instrument.cpp.
Instrument::~Instrument () virtual
Definition at line 55 of file Instrument.cpp.
Member Function Documentation
virtual InstrumentDataReportPtr SipperHardware::Instrument::CreateInstrumentDataReporter (InstrumentDataManagerPtr _manager, const KKStr & _reportDir, int32 _instrumentId) pure virtual
Implemented in SipperHardware::InstrumentOther, SipperHardware::InstrumentBatteryMeters, SipperHardware::InstrumentInclinationMeter, SipperHardware::InstrumentGPS, and SipperHardware::InstrumentCTD.
Referenced by SipperHardware::InstrumentDataReport::CreateInstrumentDataReport().
const KKStr& SipperHardware::Instrument::Description () const inline
Definition at line 41 of file Instrument.h.
void Instrument::FinalCleanUp () static
Deletes objects pointed to by 'instruments[]'; this way the don't confuse the memory dump that occurs at the end of a program in Debug Mode.
Definition at line 97 of file Instrument.cpp.
References x.
Referenced by SipperHardware::InstrumentOther::InstrumentOther().
InstrumentPtr Instrument::LookUpByShortName (const KKStr & _shortName) static
Definition at line 68 of file Instrument.cpp.
References ShortName(), KKU::KKStr::ToUpper(), and x.
Referenced by OtherInstrument(), and SipperHardware::PortAssignment::PortAssignment().
bool Instrument::Other () const virtual
Definition at line 61 of file Instrument.cpp.
Referenced by SipperHardware::PortAssignment::HeaderStr().
InstrumentPtr Instrument::OtherInstrument () static
Definition at line 90 of file Instrument.cpp.
References LookUpByShortName().
const KKStr& SipperHardware::Instrument::ShortName () const inline
Definition at line 40 of file Instrument.h.
Referenced by SipperHardware::PortAssignment::HeaderStr(), LookUpByShortName(), and SipperHardware::PortAssignment::ShortName().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/Instrument.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/Instrument.cpp