Pices: SipperFile.SipperConfigRec Class Reference
SipperFile.SipperConfigRec Class Reference
Summary description for SipperConfigRec.
Public Member Functions
SipperConfigRec ()
SipperHeaderRec HeaderRec ()
void HeaderRec (SipperHeaderRec _headerRec)
IPAddress IpAddress ()
void IpAddress (IPAddress _ipAddress)
void IpAddress (string _addrStr)
string IpAddressStr ()
int IpPort ()
void IpPort (int _ipPort)
void Load ()
bool LoadedFromConfigFile ()
void Save ()
bool UseDataBase ()
void UseDataBase (bool _useDataBase)
Detailed Description
Summary description for SipperConfigRec.
Definition at line 12 of file SipperConfigRec.cs.
Constructor & Destructor Documentation
SipperFile.SipperConfigRec.SipperConfigRec () inline
Definition at line 22 of file SipperConfigRec.cs.
References PicesInterface::OSservices.CreateDirectory(), SipperFile.SipperConfigRec.Load(), PicesInterface::PicesSipperVariables.PicesConfigurationDirectory(), and PicesInterface::PicesSipperVariables.SipperConfigrationFileName().
Member Function Documentation
SipperHeaderRec SipperFile.SipperConfigRec.HeaderRec () inline
Definition at line 32 of file SipperConfigRec.cs.
Referenced by SipperFile.InstrumentDataManager.InstrumentDataManager(), and SipperFile.InstrumentDataReportCTD.InstrumentDataReportCTD().
void SipperFile.SipperConfigRec.HeaderRec (SipperHeaderRec _headerRec) inline
Definition at line 38 of file SipperConfigRec.cs.
IPAddress SipperFile.SipperConfigRec.IpAddress () inline
Definition at line 33 of file SipperConfigRec.cs.
void SipperFile.SipperConfigRec.IpAddress (IPAddress _ipAddress) inline
Definition at line 39 of file SipperConfigRec.cs.
void SipperFile.SipperConfigRec.IpAddress (string _addrStr) inline
Definition at line 42 of file SipperConfigRec.cs.
string SipperFile.SipperConfigRec.IpAddressStr () inline
Definition at line 34 of file SipperConfigRec.cs.
int SipperFile.SipperConfigRec.IpPort () inline
Definition at line 35 of file SipperConfigRec.cs.
void SipperFile.SipperConfigRec.IpPort (int _ipPort) inline
Definition at line 54 of file SipperConfigRec.cs.
void SipperFile.SipperConfigRec.Load () inline
Definition at line 57 of file SipperConfigRec.cs.
References PicesInterface::PicesSipperVariables.SipperInterfaceDir().
Referenced by SipperFile.SipperConfigRec.SipperConfigRec().
bool SipperFile.SipperConfigRec.LoadedFromConfigFile () inline
Definition at line 30 of file SipperConfigRec.cs.
void SipperFile.SipperConfigRec.Save () inline
Definition at line 129 of file SipperConfigRec.cs.
References PicesInterface::OSservices.RemoveExtension(), PicesInterface::OSservices.RenameFile(), and SipperFile.SipperHeaderRec.Save().
bool SipperFile.SipperConfigRec.UseDataBase () inline
Definition at line 36 of file SipperConfigRec.cs.
void SipperFile.SipperConfigRec.UseDataBase (bool _useDataBase) inline
Definition at line 40 of file SipperConfigRec.cs.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperFile/SipperConfigRec.cs