Pices: SipperHardware::VolumeSampledStat Class Reference
SipperHardware::VolumeSampledStat Class Reference
#include <VolumeSampledStat.h>
Public Types
typedef KKU::int32 int32
typedef VolumeSampledStat * VolumeSampledStatPtr
Public Member Functions
VolumeSampledStat ()
VolumeSampledStat (const VolumeSampledStat &_stat)
VolumeSampledStat (int32 _binId, float _binDepth, float _volumeSampled)
~VolumeSampledStat ()
void AddToVolumeSampled (float _volumeSampled)
float BinDepth () const
void BinDepth (float _binDepth)
int32 BinId () const
void BinId (int32 _binId)
float VolumeSampled () const
void VolumeSampled (float _volumeSampled)
Detailed Description
Definition at line 22 of file VolumeSampledStat.h.
Member Typedef Documentation
typedef KKU::int32 SipperHardware::VolumeSampledStat::int32
Definition at line 25 of file VolumeSampledStat.h.
typedef VolumeSampledStat* SipperHardware::VolumeSampledStat::VolumeSampledStatPtr
Definition at line 26 of file VolumeSampledStat.h.
Constructor & Destructor Documentation
VolumeSampledStat::VolumeSampledStat ()
Definition at line 28 of file VolumeSampledStat.cpp.
VolumeSampledStat::VolumeSampledStat (const VolumeSampledStat & _stat)
Definition at line 36 of file VolumeSampledStat.cpp.
VolumeSampledStat::VolumeSampledStat (int32 _binId, float _binDepth, float _volumeSampled)
Definition at line 44 of file VolumeSampledStat.cpp.
VolumeSampledStat::~VolumeSampledStat ()
Definition at line 58 of file VolumeSampledStat.cpp.
Member Function Documentation
void VolumeSampledStat::AddToVolumeSampled (float _volumeSampled)
Definition at line 64 of file VolumeSampledStat.cpp.
Referenced by SipperHardware::VolumeSampledStatList::Give().
float SipperHardware::VolumeSampledStat::BinDepth () const inline
Definition at line 40 of file VolumeSampledStat.h.
Referenced by MLL::DataBase::InstrumentDataGetVolumePerMeterDepth().
void SipperHardware::VolumeSampledStat::BinDepth (float _binDepth) inline
Definition at line 44 of file VolumeSampledStat.h.
int32 SipperHardware::VolumeSampledStat::BinId () const inline
Definition at line 39 of file VolumeSampledStat.h.
Referenced by SipperHardware::VolumeSampledStatList::Add(), SipperHardware::VolumeSampledStatList::Give(), and MLL::DataBase::InstrumentDataGetVolumePerMeterDepth().
void SipperHardware::VolumeSampledStat::BinId (int32 _binId) inline
Definition at line 43 of file VolumeSampledStat.h.
float SipperHardware::VolumeSampledStat::VolumeSampled () const inline
Definition at line 41 of file VolumeSampledStat.h.
Referenced by SipperHardware::VolumeSampledStatList::Add(), SipperHardware::VolumeSampledStatList::Give(), and MLL::DataBase::InstrumentDataGetVolumePerMeterDepth().
void SipperHardware::VolumeSampledStat::VolumeSampled (float _volumeSampled) inline
Definition at line 45 of file VolumeSampledStat.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/VolumeSampledStat.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/VolumeSampledStat.cpp