Pices: MLL::ChainHash< T > Class Template Reference
MLL::ChainHash< T > Class Template Reference
#include <ChainHash.h>
Public Member Functions
ChainHash (const T &notFound, int32 size=10007)
ChainHash (const T &notFound)
~ChainHash ()
void DoSomeStats ()
T * find (const T &x) const
vector< list< int32 > > & getBucketList ()
FeatureVectorPtr GetImageForIndexNum (int32 indexNum)
ChainHashNodePtr GetNodeForExample (FeatureVectorPtr example)
vector< vector< KKStr > > * GroupExamples ()
void insert (T *x)
void makeEmpty ()
void remove (const T &x)
Detailed Description
template<class T>
class MLL::ChainHash< T >
Definition at line 38 of file ChainHash.h.
Constructor & Destructor Documentation
template<class T > MLL::ChainHash< T >::ChainHash (const T & notFound, int32 size = 10007)
Definition at line 173 of file ChainHash.h.
template<class T > MLL::ChainHash< T >::ChainHash (const T & notFound)
Definition at line 186 of file ChainHash.h.
template<class T > MLL::ChainHash< T >::~ChainHash ()
Definition at line 195 of file ChainHash.h.
Member Function Documentation
template<class T > void MLL::ChainHash< T >::DoSomeStats ()
Definition at line 315 of file ChainHash.h.
References KKU::endl(), KKU::StrFormatDouble(), and x.
Referenced by MLL::BitReduction::compress().
template<class T > T * MLL::ChainHash< T >::find (const T & x) const
Definition at line 209 of file ChainHash.h.
References index().
template<class T > vector< list< int32 > > & MLL::ChainHash< T >::getBucketList ()
Definition at line 403 of file ChainHash.h.
Referenced by MLL::BitReduction::compress().
template<class T > FeatureVectorPtr MLL::ChainHash< T >::GetImageForIndexNum (int32 indexNum)
Definition at line 428 of file ChainHash.h.
References MLL::ChainHashNode::getIndex(), and MLL::ChainHashNode::Image().
template<class T > ChainHashNodePtr MLL::ChainHash< T >::GetNodeForExample (FeatureVectorPtr example)
Definition at line 410 of file ChainHash.h.
template<class T > vector< vector< KKStr > > * MLL::ChainHash< T >::GroupExamples ()
Definition at line 447 of file ChainHash.h.
References KKU::endl(), and MLL::FeatureVector::ImageFileName().
template<class T > void MLL::ChainHash< T >::insert (T * x)
Definition at line 251 of file ChainHash.h.
References KKU::endl(), index(), and KKU::osWaitForEnter().
Referenced by MLL::BitReduction::compress().
template<class T > void MLL::ChainHash< T >::makeEmpty ()
Definition at line 232 of file ChainHash.h.
template<class T > void MLL::ChainHash< T >::remove (const T & x)
Definition at line 383 of file ChainHash.h.
References index().
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ChainHash.h