Pices: SipperDiskUtilities.PartitionTable Class Reference
SipperDiskUtilities.PartitionTable Class Reference
Public Member Functions
PartitionTable (byte[] buffer, ref int nextIndex)
Constructs a Partition Table by reading in each of the 4 partition table entries from a supplied buffer.
Int64 GetPartitionSectorByteOffset (int partitionNum)
Int64 GetSipperDirectoryByteOffset ()
PartitionTableEntry GetSipperPartitionTableEntry ()
Static Public Member Functions
static int BuffSpaceNeeded ()
Detailed Description
Definition at line 8 of file PartitionTable.cs.
Constructor & Destructor Documentation
SipperDiskUtilities.PartitionTable.PartitionTable (byte[] buffer, ref int nextIndex) inline
Constructs a Partition Table by reading in each of the 4 partition table entries from a supplied buffer.
Parameters
[in] buff Buffer to read data from.
[in,out] nextIndex Next byte from the buffer to be read. Upon retun the caller can use this as the starting point for the next data structure.
Definition at line 19 of file PartitionTable.cs.
References x.
Member Function Documentation
static int SipperDiskUtilities.PartitionTable.BuffSpaceNeeded () inline static
Definition at line 30 of file PartitionTable.cs.
References SipperDiskUtilities.PartitionTableEntry.BuffSpaceNeeded().
Referenced by SipperDiskUtilities.MasterBootRecord.BuffSpaceNeeded().
Int64 SipperDiskUtilities.PartitionTable.GetPartitionSectorByteOffset (int partitionNum) inline
Definition at line 44 of file PartitionTable.cs.
References SipperDiskUtilities.PartitionTableEntry.GetPartitionSectorByteOffset().
Referenced by SipperDiskUtilities.MasterBootRecord.GetPartitionSectorByteOffset().
Int64 SipperDiskUtilities.PartitionTable.GetSipperDirectoryByteOffset () inline
Definition at line 51 of file PartitionTable.cs.
References SipperDiskUtilities.PartitionTableEntry.GetSipperDirectoryByteOffset(), and SipperDiskUtilities.Constants.SIPPER_PARTITION.
Referenced by SipperDiskUtilities.MasterBootRecord.GetSipperDirectoryByteOffset().
PartitionTableEntry SipperDiskUtilities.PartitionTable.GetSipperPartitionTableEntry () inline
Definition at line 37 of file PartitionTable.cs.
References SipperDiskUtilities.Constants.SIPPER_PARTITION.
Referenced by SipperDiskUtilities.MasterBootRecord.GetSipperPartitionTableEntry().
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperDiskUtilities/PartitionTable.cs