Pices: PicesInterface::PicesVolumeSampledStatList Class Reference
PicesInterface::PicesVolumeSampledStatList Class Reference
#include <PicesVolumeSampledStat.h>
Public Member Functions
PicesVolumeSampledStatList ()
PicesVolumeSampledStatList (const VolumeSampledStatList &stats)
Construct a list of managed PicesVolumeSampledStat instances from the contents of the unmanaged list 'unmanagedImages'.
!PicesVolumeSampledStatList ()
~PicesVolumeSampledStatList ()
void AddList (PicesVolumeSampledStatList^ list)
Duplicates the contsts of 'list' and adds to this instance.
void AddList (const VolumeSampledStatList &stats)
void CleanUpMemory ()
int LargestBinId ()
PicesVolumeSampledStat^ Locate (int binId)
Returns reference to instance that has 'binId' or 'nullptr' if no instance with that 'binId'.
void MergeIn (PicesVolumeSampledStatList^ right)
Adds the Volume values of 'right' into this instance.
array< float >^ ToArray ()
Detailed Description
Definition at line 41 of file PicesVolumeSampledStat.h.
Constructor & Destructor Documentation
PicesInterface::PicesVolumeSampledStatList::PicesVolumeSampledStatList ()
Definition at line 69 of file PicesVolumeSampledStat.cpp.
Referenced by ~PicesVolumeSampledStatList().
PicesInterface::PicesVolumeSampledStatList::PicesVolumeSampledStatList (const VolumeSampledStatList & stats)
Construct a list of managed PicesVolumeSampledStat instances from the contents of the unmanaged list 'unmanagedImages'.
Will NOT take ownership of the instances of 'VolumeSampledStat' in 'stats but will create managed copies.
Parameters
[in] stats List of unmanaged 'VolumeSampledStat' objects; new Managed instances of 'VolumeSampledStat' will be created and added to list.
Definition at line 74 of file PicesVolumeSampledStat.cpp.
PicesInterface::PicesVolumeSampledStatList::~PicesVolumeSampledStatList ()
Definition at line 82 of file PicesVolumeSampledStat.cpp.
References PicesVolumeSampledStatList().
PicesInterface::PicesVolumeSampledStatList::!PicesVolumeSampledStatList ()
Definition at line 89 of file PicesVolumeSampledStat.cpp.
Member Function Documentation
void PicesInterface::PicesVolumeSampledStatList::AddList (PicesVolumeSampledStatList^ list)
Duplicates the contsts of 'list' and adds to this instance.
Definition at line 96 of file PicesVolumeSampledStat.cpp.
void PicesInterface::PicesVolumeSampledStatList::AddList (const VolumeSampledStatList & stats)
Definition at line 105 of file PicesVolumeSampledStat.cpp.
void PicesInterface::PicesVolumeSampledStatList::CleanUpMemory ()
Definition at line 113 of file PicesVolumeSampledStat.cpp.
int PicesInterface::PicesVolumeSampledStatList::LargestBinId ()
Definition at line 129 of file PicesVolumeSampledStat.cpp.
References PicesInterface::PicesVolumeSampledStat::BinId.
Referenced by ToArray().
PicesVolumeSampledStat PicesInterface::PicesVolumeSampledStatList::Locate (int binId)
Returns reference to instance that has 'binId' or 'nullptr' if no instance with that 'binId'.
Definition at line 118 of file PicesVolumeSampledStat.cpp.
References PicesInterface::PicesVolumeSampledStat::BinId.
Referenced by MergeIn().
void PicesInterface::PicesVolumeSampledStatList::MergeIn (PicesVolumeSampledStatList^ right)
Adds the Volume values of 'right' into this instance.
Each instance in 'right' will be added to the instance of 'PicesVolumeSampledStat' that has the same binId. If no instance exists will then create a new instance with this BinId.
Definition at line 156 of file PicesVolumeSampledStat.cpp.
References PicesInterface::PicesVolumeSampledStat::BinId, Locate(), and PicesInterface::PicesVolumeSampledStat::VolumeSampled.
array< float > PicesInterface::PicesVolumeSampledStatList::ToArray ()
Definition at line 142 of file PicesVolumeSampledStat.cpp.
References PicesInterface::PicesVolumeSampledStat::BinId, LargestBinId(), and PicesInterface::PicesVolumeSampledStat::VolumeSampled.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesVolumeSampledStat.h
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesVolumeSampledStat.cpp