Pices: SipperFile.InstrumentData Class Reference
SipperFile.InstrumentData Class Reference
Summary description for DataRow.
Public Member Functions
InstrumentData ()
InstrumentData (float[] _data, double _latitude, double _longitude, DateTime _time)
InstrumentData (InstrumentData r)
InstrumentData (string s, int[] fieldIndexes, ref bool valid)
InstrumentData (PicesInstrumentData picesData)
int ActiveBattery ()
bool BatteryDataChanged (InstrumentData o)
string BatteryStatuses ()
float CdomFluorescence ()
float CdomFluorescenceSensor ()
DateTime CTDdate ()
float[] Data ()
float Density ()
float Depth ()
void Dispose ()
bool Equals (InstrumentData o)
float Fluorescence ()
float FluorescenceSensor ()
string GetField (int idx)
double Latitude ()
double Longitude ()
float Oxygen ()
float OxygenSensor ()
float Pitch ()
float Roll ()
float Salinity ()
float Temperature ()
float Transmissivity ()
float TransmissivitySensor ()
float Turbidity ()
float TurbiditySensor ()
void UpdateBatteryPack (ChartControls.BatteryPack bp)
void UpdateCTDDataFields (float _batteryVolt, float _conductivity, float _density, float _depth, float _fluorescence, float _fluorescenceSensor, float _cdomFluorescence, float _cdomFluorescenceSensor, float _oxygen, float _oxygenSensor, float _pressure, float _salinity, float _soundVelocity, float _temperature, float _transmisivity, float _transmisivitySensor, float _turbidity, float _turbiditySensor, DateTime _ctdDate)
void UpdateGPS (double _latitude, double _longitude, DateTime _gpsTime)
void UpdateLatitudeAndLongitude (double _latitude, double _longitude)
void UpdatePitchAndRoll (float _pitch, float _roll)
void UpdateRecordingRate (float _recordingRate)
void UpdateSipperBatteries (int _activeBattery, float[] _batteryLevels, string _batteryStatuses)
void WriteLine (StreamWriter w, int[] fieldIndexes)
Static Public Member Functions
static int[] BuildFieldNameList (string[] fields)
static int[] CreateCurrentFieldIndexList ()
static string FieldName (int idx)
static int GetFieldNameIndex (string fieldName)
static int NumDataFields ()
static int NumOfFields ()
static void WriteFieldList (StreamWriter w)
Public Attributes
const int PitchIndex = 22
const int RollIndex = 23
Properties
UInt64 ByteOffset [get, set]
float FlowRate1 [get, set]
float FlowRate2 [get, set]
float Illumination [get, set]
float RecordingRate [get, set]
int ScanLine [get, set]
DateTime Time [get, set]
bool UpdatedFlag [get, set]
Detailed Description
Summary description for DataRow.
Definition at line 13 of file InstrumentData.cs.
Constructor & Destructor Documentation
SipperFile.InstrumentData.InstrumentData () inline
Definition at line 304 of file InstrumentData.cs.
SipperFile.InstrumentData.InstrumentData (float[] _data, double _latitude, double _longitude, DateTime _time) inline
Definition at line 312 of file InstrumentData.cs.
References x.
SipperFile.InstrumentData.InstrumentData (InstrumentData r) inline
Definition at line 336 of file InstrumentData.cs.
References x.
SipperFile.InstrumentData.InstrumentData (string s, int[] fieldIndexes, ref bool valid) inline
Definition at line 356 of file InstrumentData.cs.
SipperFile.InstrumentData.InstrumentData (PicesInstrumentData picesData) inline
Definition at line 369 of file InstrumentData.cs.
References PicesInterface::PicesInstrumentData.ActiveBattery, PicesInterface::PicesInstrumentData.Bat1Level, PicesInterface::PicesInstrumentData.Bat2Level, PicesInterface::PicesInstrumentData.Bat3Level, PicesInterface::PicesInstrumentData.Bat4Level, PicesInterface::PicesInstrumentData.ByteOffset, PicesInterface::PicesInstrumentData.CdomFluorescence, PicesInterface::PicesInstrumentData.CdomFluorescenceSensor, PicesInterface::PicesInstrumentData.Conductivity, PicesInterface::PicesInstrumentData.CTDBattery, PicesInterface::PicesInstrumentData.CtdDate, PicesInterface::PicesInstrumentData.Density, PicesInterface::PicesInstrumentData.Depth, PicesInterface::PicesInstrumentData.FlowRate1, SipperFile.InstrumentData.FlowRate1, PicesInterface::PicesInstrumentData.FlowRate2, SipperFile.InstrumentData.FlowRate2, PicesInterface::PicesInstrumentData.Fluorescence, PicesInterface::PicesInstrumentData.FluorescenceSensor, PicesInterface::PicesInstrumentData.Illumination, PicesInterface::PicesInstrumentData.Latitude, PicesInterface::PicesInstrumentData.Longitude, PicesInterface::PicesInstrumentData.Oxygen, PicesInterface::PicesInstrumentData.OxygenSensor, PicesInterface::PicesInstrumentData.Pitch, SipperFile.InstrumentData.PitchIndex, PicesInterface::PicesInstrumentData.Pressure, SipperFile.InstrumentData.RecordingRate, PicesInterface::PicesInstrumentData.RecordRate, PicesInterface::PicesInstrumentData.Roll, SipperFile.InstrumentData.RollIndex, PicesInterface::PicesInstrumentData.Salinity, PicesInterface::PicesInstrumentData.ScanLine, PicesInterface::PicesInstrumentData.SoundVelocity, PicesInterface::PicesInstrumentData.Temperature, PicesInterface::PicesInstrumentData.Transmissivity, PicesInterface::PicesInstrumentData.TransmissivitySensor, PicesInterface::PicesInstrumentData.Turbidity, PicesInterface::PicesInstrumentData.TurbiditySensor, and SipperFile.InstrumentData.UpdateCTDDataFields().
Member Function Documentation
int SipperFile.InstrumentData.ActiveBattery () inline
Definition at line 222 of file InstrumentData.cs.
bool SipperFile.InstrumentData.BatteryDataChanged (InstrumentData o) inline
Definition at line 572 of file InstrumentData.cs.
string SipperFile.InstrumentData.BatteryStatuses () inline
Definition at line 223 of file InstrumentData.cs.
static int [] SipperFile.InstrumentData.BuildFieldNameList (string[] fields) inline static
Definition at line 180 of file InstrumentData.cs.
References SipperFile.InstrumentData.GetFieldNameIndex(), and x.
float SipperFile.InstrumentData.CdomFluorescence () inline
Definition at line 230 of file InstrumentData.cs.
float SipperFile.InstrumentData.CdomFluorescenceSensor () inline
Definition at line 231 of file InstrumentData.cs.
static int [] SipperFile.InstrumentData.CreateCurrentFieldIndexList () inline static
Definition at line 126 of file InstrumentData.cs.
References x.
Referenced by SipperFile.InstrumentDataList.Save().
DateTime SipperFile.InstrumentData.CTDdate () inline
Definition at line 224 of file InstrumentData.cs.
float [] SipperFile.InstrumentData.Data () inline
Definition at line 225 of file InstrumentData.cs.
Referenced by SipperFile.DataRowList.CalcMinMaxValues(), SipperFile.InstrumentDataList.CalcMinMaxValues(), and SipperFile.TimePlotParameters.PlotDataRow().
float SipperFile.InstrumentData.Density () inline
Definition at line 226 of file InstrumentData.cs.
float SipperFile.InstrumentData.Depth () inline
Definition at line 227 of file InstrumentData.cs.
Referenced by SipperFile.DataRowList.Add(), SipperFile.InstrumentDataList.Add(), SipperFile.ActiveTrainingLibraries.MakePredictions(), and SipperFile.DepthPlot2Parameters.PaintCurrentRow().
void SipperFile.InstrumentData.Dispose () inline
Definition at line 420 of file InstrumentData.cs.
bool SipperFile.InstrumentData.Equals (InstrumentData o) inline
Definition at line 546 of file InstrumentData.cs.
References x.
static string SipperFile.InstrumentData.FieldName (int idx) inline static
Definition at line 68 of file InstrumentData.cs.
Referenced by SipperFile.DepthPlot2.DepthPlot2().
float SipperFile.InstrumentData.Fluorescence () inline
Definition at line 228 of file InstrumentData.cs.
Referenced by SipperFile.ActiveTrainingLibraries.MakePredictions().
float SipperFile.InstrumentData.FluorescenceSensor () inline
Definition at line 229 of file InstrumentData.cs.
string SipperFile.InstrumentData.GetField (int idx) inline
Definition at line 427 of file InstrumentData.cs.
Referenced by SipperFile.InstrumentData.WriteLine().
static int SipperFile.InstrumentData.GetFieldNameIndex (string fieldName) inline static
Definition at line 138 of file InstrumentData.cs.
References x.
Referenced by SipperFile.InstrumentData.BuildFieldNameList().
double SipperFile.InstrumentData.Latitude () inline
Definition at line 232 of file InstrumentData.cs.
double SipperFile.InstrumentData.Longitude () inline
Definition at line 233 of file InstrumentData.cs.
static int SipperFile.InstrumentData.NumDataFields () inline static
Definition at line 64 of file InstrumentData.cs.
Referenced by SipperFile.DataRowList.CalcMinMaxValues(), SipperFile.InstrumentDataList.CalcMinMaxValues(), and SipperFile.DepthPlot2.DepthPlot2().
static int SipperFile.InstrumentData.NumOfFields () inline static
Definition at line 66 of file InstrumentData.cs.
Referenced by SipperFile.DepthPlot2.DepthPlot2().
float SipperFile.InstrumentData.Oxygen () inline
Definition at line 234 of file InstrumentData.cs.
Referenced by SipperFile.ActiveTrainingLibraries.MakePredictions().
float SipperFile.InstrumentData.OxygenSensor () inline
Definition at line 235 of file InstrumentData.cs.
float SipperFile.InstrumentData.Pitch () inline
Definition at line 236 of file InstrumentData.cs.
References SipperFile.InstrumentData.PitchIndex.
float SipperFile.InstrumentData.Roll () inline
Definition at line 237 of file InstrumentData.cs.
References SipperFile.InstrumentData.RollIndex.
float SipperFile.InstrumentData.Salinity () inline
Definition at line 238 of file InstrumentData.cs.
Referenced by SipperFile.ActiveTrainingLibraries.MakePredictions().
float SipperFile.InstrumentData.Temperature () inline
Definition at line 239 of file InstrumentData.cs.
float SipperFile.InstrumentData.Transmissivity () inline
Definition at line 240 of file InstrumentData.cs.
float SipperFile.InstrumentData.TransmissivitySensor () inline
Definition at line 241 of file InstrumentData.cs.
float SipperFile.InstrumentData.Turbidity () inline
Definition at line 242 of file InstrumentData.cs.
float SipperFile.InstrumentData.TurbiditySensor () inline
Definition at line 243 of file InstrumentData.cs.
void SipperFile.InstrumentData.UpdateBatteryPack (ChartControls.BatteryPack bp) inline
Definition at line 475 of file InstrumentData.cs.
void SipperFile.InstrumentData.UpdateCTDDataFields (float _batteryVolt, float _conductivity, float _density, float _depth, float _fluorescence, float _fluorescenceSensor, float _cdomFluorescence, float _cdomFluorescenceSensor, float _oxygen, float _oxygenSensor, float _pressure, float _salinity, float _soundVelocity, float _temperature, float _transmisivity, float _transmisivitySensor, float _turbidity, float _turbiditySensor, DateTime _ctdDate) inline
Definition at line 591 of file InstrumentData.cs.
Referenced by SipperFile.InstrumentData.InstrumentData(), and SipperFile.InstrumentDataReportCTD.ParseTxtLine().
void SipperFile.InstrumentData.UpdateGPS (double _latitude, double _longitude, DateTime _gpsTime) inline
Definition at line 661 of file InstrumentData.cs.
void SipperFile.InstrumentData.UpdateLatitudeAndLongitude (double _latitude, double _longitude) inline
Definition at line 644 of file InstrumentData.cs.
void SipperFile.InstrumentData.UpdatePitchAndRoll (float _pitch, float _roll) inline
Definition at line 635 of file InstrumentData.cs.
References SipperFile.InstrumentData.PitchIndex, and SipperFile.InstrumentData.RollIndex.
Referenced by SipperFile.InstrumentDataReportInclination.ParseTxtLine().
void SipperFile.InstrumentData.UpdateRecordingRate (float _recordingRate) inline
Definition at line 653 of file InstrumentData.cs.
void SipperFile.InstrumentData.UpdateSipperBatteries (int _activeBattery, float[] _batteryLevels, string _batteryStatuses) inline
Definition at line 673 of file InstrumentData.cs.
Referenced by SipperFile.InstrumentDataReportBatteryMeter.ParseTxtLine().
static void SipperFile.InstrumentData.WriteFieldList (StreamWriter w) inline static
Definition at line 164 of file InstrumentData.cs.
References x.
Referenced by SipperFile.DataRowList.Save(), and SipperFile.InstrumentDataList.Save().
void SipperFile.InstrumentData.WriteLine (StreamWriter w, int[] fieldIndexes) inline
Definition at line 483 of file InstrumentData.cs.
References SipperFile.InstrumentData.GetField(), and x.
Referenced by SipperFile.DataRowList.Add(), SipperFile.InstrumentDataList.Add(), SipperFile.DataRowList.Save(), and SipperFile.InstrumentDataList.Save().
Member Data Documentation
const int SipperFile.InstrumentData.PitchIndex = 22
Definition at line 101 of file InstrumentData.cs.
Referenced by SipperFile.InstrumentData.InstrumentData(), SipperFile.InstrumentData.Pitch(), and SipperFile.InstrumentData.UpdatePitchAndRoll().
const int SipperFile.InstrumentData.RollIndex = 23
Definition at line 102 of file InstrumentData.cs.
Referenced by SipperFile.InstrumentData.InstrumentData(), SipperFile.InstrumentData.Roll(), and SipperFile.InstrumentData.UpdatePitchAndRoll().
Property Documentation
UInt64 SipperFile.InstrumentData.ByteOffset get set
Definition at line 249 of file InstrumentData.cs.
float SipperFile.InstrumentData.FlowRate1 get set
Definition at line 255 of file InstrumentData.cs.
Referenced by SipperFile.InstrumentData.InstrumentData(), and SipperFile.InstrumentDataReportFlowMeter.ReportData().
float SipperFile.InstrumentData.FlowRate2 get set
Definition at line 261 of file InstrumentData.cs.
Referenced by SipperFile.InstrumentData.InstrumentData(), and SipperFile.InstrumentDataReportFlowMeter.ReportData().
float SipperFile.InstrumentData.Illumination get set
Definition at line 268 of file InstrumentData.cs.
Referenced by SipperFile.InstrumentDataReportIllumination.ReportData().
float SipperFile.InstrumentData.RecordingRate get set
Definition at line 275 of file InstrumentData.cs.
Referenced by SipperFile.InstrumentData.InstrumentData().
int SipperFile.InstrumentData.ScanLine get set
Definition at line 282 of file InstrumentData.cs.
DateTime SipperFile.InstrumentData.Time get set
Definition at line 289 of file InstrumentData.cs.
Referenced by SipperFile.DataRowList.Add(), SipperFile.InstrumentDataList.Add(), SipperFile.DataRowList.CalcMinMaxValues(), SipperFile.InstrumentDataList.CalcMinMaxValues(), SipperFile.InstrumentDataList.FindClosestEntryByTime(), SipperFile.DataRowList.GetByTimeGreaterOrEqual(), SipperFile.InstrumentDataList.GetByTimeGreaterOrEqual(), and SipperFile.TimePlotParameters.PlotDataRow().
bool SipperFile.InstrumentData.UpdatedFlag get set
Definition at line 297 of file InstrumentData.cs.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperFile/InstrumentData.cs