Pices: MLL::FeatureEncoder Class Reference
MLL::FeatureEncoder Class Reference
#include <FeatureEncoder.h>
Public Member Functions
FeatureEncoder (const SVMparam &_svmParam, FileDescPtr _fileDesc, MLL::AttributeTypeVector &_attributeTypes, VectorInt &_cardinalityTable, MLClassConstPtr _class1, MLClassConstPtr _class2, RunLog &_log)
Constructs a Feature Encoder object.
~FeatureEncoder ()
Frees any memory allocated by, and owned by the FeatureEncoder.
MLClassConstPtr Class1 () const
MLClassConstPtr Class2 () const
int32 CodedNumOfFeatures () const
CompressionStats Compress (FeatureVectorListPtr src, ClassAssignments &assignments, XSpacePtr &xSpace, int32 &totalxSpaceUsed, struct svm_problem &prob)
Compresses 'src' images, allocating new 'xSpace' data structure.
FeatureVectorListPtr CreateEncodedFeatureVector (FeatureVectorList &srcData)
FileDescPtr CreateEncodedFileDesc (ostream *o)
XSpacePtr EncodeAImage (FeatureVectorPtr image)
Converts a single image into the svm_problem format, using the method specified by the EncodingMethod() value returned by svmParam.
void EncodeAImage (FeatureVectorPtr image, svm_node *xSpace, int32 &xSpaceUsed)
FeatureVectorPtr EncodeAImage (FileDescPtr encodedFileDesc, FeatureVectorPtr src)
FeatureVectorListPtr EncodeAllExamples (const FeatureVectorListPtr srcData)
int32 MemoryConsumedEstimated () const
int32 XSpaceNeededPerImage ()
Detailed Description
Definition at line 44 of file FeatureEncoder.h.
Constructor & Destructor Documentation
FeatureEncoder::FeatureEncoder (const SVMparam & _svmParam, FileDescPtr _fileDesc, MLL::AttributeTypeVector & _attributeTypes, VectorInt & _cardinalityTable, MLClassConstPtr _class1, MLClassConstPtr _class2, RunLog & _log)
Constructs a Feature Encoder object.
Parameters
[in] _svmParam
[in] _fileDesc
[in] _class1
[in] _class2
[in] _log A logfile stream. All important events will be ouput to this stream
Definition at line 42 of file FeatureEncoder.cpp.
References MLL::FileDesc::Attributes(), MLL::BinaryEncoding, MLL::SVMparam::CompressionMethod(), MLL::SVMparam::EncodingMethod(), KKU::endl(), MLL::FeAsIs, MLL::FeBinary, MLL::FeScale, MLL::SVMparam::GetFeatureNums(), MLL::Attribute::GetNominalValue(), KKU::RunLog::Level(), MLL::Attribute::Name(), MLL::FileDesc::NewContinuousDataOnly(), MLL::NoEncoding, MLL::NominalAttribute, MLL::FeatureNumList::NumOfFeatures(), MLL::ScaledEncoding, MLL::SymbolicAttribute, and x.
Referenced by MemoryConsumedEstimated().
FeatureEncoder::~FeatureEncoder ()
Frees any memory allocated by, and owned by the FeatureEncoder.
Definition at line 167 of file FeatureEncoder.cpp.
Member Function Documentation
MLClassConstPtr MLL::FeatureEncoder::Class1 () const inline
Definition at line 63 of file FeatureEncoder.h.
Referenced by MLL::SVMModel::DistanceFromDecisionBoundary().
MLClassConstPtr MLL::FeatureEncoder::Class2 () const inline
Definition at line 64 of file FeatureEncoder.h.
Referenced by MLL::SVMModel::DistanceFromDecisionBoundary().
int32 MLL::FeatureEncoder::CodedNumOfFeatures () const inline
Definition at line 60 of file FeatureEncoder.h.
CompressionStats FeatureEncoder::Compress (FeatureVectorListPtr src, ClassAssignments & assignments, XSpacePtr & xSpace, int32 & totalxSpaceUsed, struct svm_problem & prob)
Compresses 'src' images, allocating new 'xSpace' data structure.
Parameters
[in] src Images that are to be compressed
[in] assignments Class Assignments
[in] xSpace will allocate enough xSpace nodes and place compresed results in this structure.
[out] totalxSpaceUsed number nodes used in xSpace
Parameters
[out] prob Data Structure that is used by SVMLib
Definition at line 517 of file FeatureEncoder.cpp.
References MLL::BRcompressionPost, MLL::BRunBalancedVariance, MLL::SVMparam::C_Param(), MLL::CompressionStats::compression_ratio, MLL::CompressionStats::elapsed_cpu_time, EncodeAImage(), KKU::endl(), SVM233::svm_problem::exampleNames, MLL::ClassAssignments::GetNumForClass(), MLL::FeatureVector::ImageFileName(), SVM233::svm_problem::index, SVM233::svm_problem::l, KKU::RunLog::Level(), MLL::FeatureVector::MLClass(), MLL::CompressionStats::num_images_after, MLL::CompressionStats::num_images_before, KKU::osGetRootName(), MLL::FeatureVector::TrainWeight(), SVM233::svm_problem::W, MLL::SVMparam::WeightBitReduction(), SVM233::svm_problem::x, and SVM233::svm_problem::y.
FeatureVectorListPtr FeatureEncoder::CreateEncodedFeatureVector (FeatureVectorList & srcData)
Definition at line 716 of file FeatureEncoder.cpp.
References MLL::FeatureVector::AddFeatureData(), MLL::FeatureVectorList::AllFieldsAreNumeric(), EncodeAImage(), index(), MLL::FeatureVector::MLClass(), and MLL::FeatureVectorList::PushOnBack().
FileDescPtr FeatureEncoder::CreateEncodedFileDesc (ostream * o)
Definition at line 197 of file FeatureEncoder.cpp.
References MLL::FileDesc::AddAAttribute(), KKU::endl(), MLL::FeAsIs, MLL::FeBinary, MLL::FeScale, MLL::FileDesc::FieldName(), MLL::FileDesc::GetNominalValue(), KKU::RunLog::Level(), MLL::NumericAttribute, KKU::osWaitForEnter(), KKU::StrFormatInt(), MLL::FileDesc::TypeStr(), and x.
Referenced by EncodeAllExamples().
XSpacePtr FeatureEncoder::EncodeAImage (FeatureVectorPtr image)
Converts a single image into the svm_problem format, using the method specified by the EncodingMethod() value returned by svmParam.
Parameters
[in] image That we're converting
Definition at line 300 of file FeatureEncoder.cpp.
Referenced by Compress(), CreateEncodedFeatureVector(), MLL::SVMModel::DistanceFromDecisionBoundary(), EncodeAllExamples(), MLL::SVMModel::FindWorstSupportVectors(), MLL::SVMModel::FindWorstSupportVectors2(), and MLL::SVMModel::ProbabilitiesByClass().
void MLL::FeatureEncoder::EncodeAImage (FeatureVectorPtr image, svm_node * xSpace, int32 & xSpaceUsed)
FeatureVectorPtr FeatureEncoder::EncodeAImage (FileDescPtr encodedFileDesc, FeatureVectorPtr src)
Definition at line 312 of file FeatureEncoder.cpp.
References MLL::FeatureVector::AddFeatureData(), MLL::FeAsIs, MLL::FeatureVector::FeatureData(), MLL::FeBinary, MLL::FeScale, MLL::FeatureVector::MLClass(), MLL::FeatureVector::PredictedClass(), MLL::FeatureVector::TrainWeight(), and x.
FeatureVectorListPtr FeatureEncoder::EncodeAllExamples (const FeatureVectorListPtr srcData)
Definition at line 365 of file FeatureEncoder.cpp.
References CreateEncodedFileDesc(), EncodeAImage(), and MLL::FeatureVectorList::PushOnBack().
int32 FeatureEncoder::MemoryConsumedEstimated () const
Definition at line 177 of file FeatureEncoder.cpp.
References FeatureEncoder(), and MLL::FeatureNumList::MemoryConsumedEstimated().
Referenced by MLL::SVMModel::MemoryConsumedEstimated().
int32 MLL::FeatureEncoder::XSpaceNeededPerImage () inline
Definition at line 101 of file FeatureEncoder.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/FeatureEncoder.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/FeatureEncoder.cpp