Pices: KKU::RunLog Class Reference
KKU::RunLog Class Reference
Used for logging messages.
#include <RunLog.h>
Public Member Functions
RunLog ()
Creates an instance were logging will go to the console.
RunLog (const char *_fileName)
RunLog (const KKStr &_fileName)
RunLog (std::ostream &errorLogStream)
Creates instance where logging messages are written to file stream specified by 'errorLogStream'.
RunLog (std::ostream *logStream)
Creates instance where logging messages are written to file stream pointed to by 'logStream'.
~RunLog ()
void Append (const char *str)
Appends string to log; generally used by other Log methods but can be called by public.
void AttachFile (const KKStr &_fileName)
Call this method to start logging messages to a different file.
void AttachFile (std::ostream &_logFile)
Call this method to start logging messages to a specific file stream.
void AttachFileAppend (const KKStr &_fileName)
Call this method to start appending logging messages to a different file.
void AttachMsgQueue (MsgQueuePtr _msgQueue)
All activity that is wriiten to the log file will be added as messages to '_msgQueue'.
void DetachFile ()
Closes out current log file and starts writing to stdout aka 'cout'.
KKStr FileName ()
void Flush ()
const KKStr & LastLine ()
Returns the last line of text written to the log file.
RunLog & Level (int32 _level)
Sets current message level.
int32 Level () const
int32 LineCount () const
int32 MemoryConsumedEstimated () const
RunLog & operator<< (int16 right)
RunLog & operator<< (uint16 right)
RunLog & operator<< (int32 right)
RunLog & operator<< (uint32 right)
RunLog & operator<< (int64 right)
RunLog & operator<< (uint64 right)
RunLog & operator<< (double right)
RunLog & operator<< (char right)
RunLog & operator<< (const char *right)
RunLog & operator<< (const KKStr &right)
RunLog & operator<< (KKStrConstPtr right)
RunLog & operator<< (ostream &(*mf)(ostream &))
void SetLevel (int32 _level)
void SetLoggingLevel (int32 _loggingLevel)
Detailed Description
Used for logging messages.
Has facilities to deal with different levels of logging. You use the normal insertion operators to write to this object. You can specify at any point a Logging level. If this level is less than or equal to a specified threshold the the message will be recorded in the log. <br > The idea is that during normal production runs log level would be set to 10. But if there appears to be some issue then you would set the logging level to a higher level to get more details. The higher the level the more detail you will get.
Definition at line 49 of file RunLog.h.
Constructor & Destructor Documentation
RunLog::RunLog ()
Creates an instance were logging will go to the console.
Definition at line 30 of file RunLog.cpp.
Referenced by MemoryConsumedEstimated().
RunLog::RunLog (const char * _fileName)
Creates instance with a log messages written to file 'fileName'.
Definition at line 42 of file RunLog.cpp.
References KKU::KKStr::Str().
RunLog::RunLog (const KKStr & _fileName)
Creates instance with a log messages written to file 'fileName'.
Definition at line 55 of file RunLog.cpp.
References KKU::KKStr::Str().
RunLog::RunLog (std::ostream & errorLogStream)
Creates instance where logging messages are written to file stream specified by 'errorLogStream'.
Definition at line 68 of file RunLog.cpp.
RunLog::RunLog (std::ostream * logStream)
Creates instance where logging messages are written to file stream pointed to by 'logStream'.
Definition at line 81 of file RunLog.cpp.
RunLog::~RunLog ()
Definition at line 94 of file RunLog.cpp.
Member Function Documentation
void RunLog::Append (const char * str)
Appends string to log; generally used by other Log methods but can be called by public.
Definition at line 239 of file RunLog.cpp.
References KKU::MsgQueue::AddMsg(), and Flush().
Referenced by Level(), operator<<(), PicesInterface::PicesRunLog::Write(), and PicesInterface::PicesRunLog::Writeln().
void RunLog::AttachFile (const KKStr & _fileName)
Call this method to start logging messages to a different file.
Will close out current log file and open new one specified by 'fileName'.
Definition at line 113 of file RunLog.cpp.
References KKU::KKStr::Str().
Referenced by KKU::Application::Application(), PicesInterface::PicesRunLog::AttachFile(), and CrossValidationApp::ProcessCmdLineParameter().
void RunLog::AttachFile (std::ostream & _logFile)
Call this method to start logging messages to a specific file stream.
Will close out current log file and write to the specified '_logFile' in the future.
Definition at line 152 of file RunLog.cpp.
void RunLog::AttachFileAppend (const KKStr & _fileName)
Call this method to start appending logging messages to a different file.
Will close out current log file and open new one specified by 'fileName' with the append flag set.
Definition at line 129 of file RunLog.cpp.
References KKU::KKStr::Str().
Referenced by PicesInterface::PicesRunLog::DisplayWithNoteBook().
void RunLog::AttachMsgQueue (MsgQueuePtr _msgQueue)
All activity that is wriiten to the log file will be added as messages to '_msgQueue'.
Definition at line 145 of file RunLog.cpp.
Referenced by PicesInterface::TrainingModel2::LoadExistingModelOtherwiseBuild(), PicesInterface::TrainingModel2::LoadTrainingModelForGivenLevel(), and PicesInterface::PicesRunLog::PicesRunLog().
void RunLog::DetachFile ()
Closes out current log file and starts writing to stdout aka 'cout'.
Definition at line 167 of file RunLog.cpp.
Referenced by PicesInterface::PicesRunLog::DetachFile(), and PicesInterface::PicesRunLog::DisplayWithNoteBook().
KKStr RunLog::FileName ()
Definition at line 179 of file RunLog.cpp.
Referenced by PicesInterface::PicesRunLog::DisplayWithNoteBook(), PicesInterface::PicesRunLog::FileName(), CrossValidationApp::ReportCmdLineParameters(), and PicesInterface::PicesRunLog::RunLogFileName().
void RunLog::Flush ()
Definition at line 273 of file RunLog.cpp.
Referenced by Append(), and MLL::FeatureFileIOPices::LoadFile().
const KKStr& KKU::RunLog::LastLine () inline
Returns the last line of text written to the log file.
Definition at line 120 of file RunLog.h.
Referenced by PicesInterface::PicesRunLog::LastLine(), and PicesInterface::TrainingModel2::LastRunLogTextLine().
RunLog & RunLog::Level (int32 _level)
Sets current message level.
You would normally call this method just before you wish to start logging a message. If you are not changing the level since previous call then no need to call.
log.Level (20) << "ClassName::MethodName Message" << endl;
Definition at line 206 of file RunLog.cpp.
References Append().
Referenced by MLL::UsfCasCor::_load_training_example(), MLL::AbundanceCorrectionMatrix::AddIn(), MLL::ClassAssignments::AddMLClass(), MLL::FeatureVectorList::AddQueue(), MLL::AbundanceCorrectionMatrix::AdjustClassificationCounts(), MLL::UsfCasCor::allocate_network(), MLL::Model::AllocatePredictionVariables(), MLL::FeatureFileIO::AppendToFile(), JobManagment::JobManager::Block(), MLL::ConfusionMatrix2::BuildFromIstreamXML(), MLL::FeatureVectorList::CalcStatsForFeatureNum(), MLL::FileDesc::Cardinality(), MLL::Classifier2::Classifier2(), MLL::FeatureEncoder::Compress(), MLL::FeatureEncoder2::CompressExamples(), MLL::FeatureEncoder2::CreateEncodedFileDesc(), MLL::FeatureEncoder::CreateEncodedFileDesc(), MLL::TrainingConfiguration2::CreateFromDirectoryStructure(), MLL::TrainingConfiguration2::CreateFromFeatureVectorList(), SipperHardware::InstrumentDataList::CreateFromSipperFile(), MLL::Model::CreateFromStream(), MLL::ModelParam::CreateModelParam(), MLL::TrainingProcess2::CreateModelsFromTrainingData(), MLL::Orderings::CreateOrderingsObjFromFileIfAvaliable(), MLL::DataBase::DataBase(), DetermineCropSettings(), DetermineCropSettingsForDeployment(), MLL::SVMModel::DistanceFromDecisionBoundary(), CrossValidationApp::DistributesImagesRandomlyWithInFolds(), JobManagment::JobManager::EndBlock(), MLL::TrainingProcess2::ExtractTrainingClassFeatures(), MLL::DataBase::FeatureDataCreateTable(), MLL::DataBase::FeatureDataForImageGroup(), MLL::DataBase::FeatureDataRecLoad(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::FeatureEncoder::FeatureEncoder(), MLL::FeatureEncoder2::FeatureEncoder2(), MLL::SVMModel::FindWorstSupportVectors(), MLL::SVMModel::FindWorstSupportVectors2(), MLL::SipperExtractionImageManager::Flush(), MLL::ConfusionMatrix2::FMeasure(), MLL::CrossValidationThreeWay::FoldAccuracy(), MLL::CrossValidation::FoldAccuracy(), MLL::CrossValidationVoting::FoldAccuracy(), MLL::CrossValidation::FoldAccuracysToStr(), KKU::ContourFollower::FollowContour(), MLL::TrainingConfiguration2::GenerateAConfiguraionForAHierarchialLevel(), SipperHardware::InstrumentDataFileManager::GetClosestInstrumentData(), MLL::FeatureFileIODstWeb::GetFileDesc(), MLL::FeatureFileIOC45::GetFileDesc(), MLL::FeatureFileIOColumn::GetFileDesc(), MLL::FeatureFileIORoberts::GetFileDesc(), MLL::FeatureFileIOUCI::GetFileDesc(), MLL::FeatureFileIOPices::GetFileDesc(), MLL::FeatureFileIOSparse::GetFileDesc(), SipperHardware::InstrumentDataList::GetVolumePerMeterProfile(), MLL::DataBase::ImageFullSizeSave(), MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageGroupEntriesInsert(), MLL::DataBase::ImageGroupEntriesLoad(), MLL::DataBase::ImageGroupLoad(), MLL::DataBase::ImageUpdateInstrumentDataFields(), MLL::ConfusionMatrix2::Increment(), JobManagment::JobManager::InitilizeJobManager(), MLL::UsfCasCor::INSTALL_NEW_UNIT(), MLL::DataBase::InstrumentDataBinByMeterDepth(), MLL::DataBase::InstrumentDataGetVolumePerMeterDepth(), MLL::DataBase::InstrumentDataRetrieveGPSInfo(), MLL::DuplicateImages::ListOfExamplesToDelete(), MLL::ClassAssignments::Load(), MLL::DataBaseImageValidatedEntryList::Load(), MLL::SVMparam::Load(), MLL::FeatureNumList::Load(), MLL::Model::Load(), MLL::UsfCasCor::load_data(), MLL::TrainingConfiguration2::LoadFeatureDataFromTrainingLibraries(), MLL::FeatureFileIOC45::LoadFeatureFile(), MLL::FeatureFileIO::LoadFeatureFile(), MLL::FeatureFileIODstWeb::LoadFile(), MLL::FeatureFileIOColumn::LoadFile(), MLL::FeatureFileIORoberts::LoadFile(), MLL::FeatureFileIOUCI::LoadFile(), MLL::FeatureFileIOPices::LoadFile(), MLL::FeatureFileIOC45::LoadFile(), MLL::FeatureFileIOSparse::LoadFile(), KKU::Configuration::LoadFile(), MLL::FeatureFileIOPices::LoadInSubDirectoryTree(), MLL::DataBaseUpdate::LoadSourceFile(), MLL::DataBase::LogEntriesProcessEnd(), MLL::FeatureVectorList::LookUpByRootName(), CrossValidationApp::Main(), MLL::FileDesc::MergeSymbolicFields(), MLL::DataBase::MLClassLoad(), MLL::DataBase::MLClassLoadList(), MLL::NormalizationParms::NormalizeImages(), MLL::Orderings::Ordering(), MLL::Orderings::Orderings(), MLL::FeatureVectorList::OrderUsingNamesFromAFile(), MLL::ModelOldSVM::Param(), MLL::ModelParam::ParseCmdLine(), MLL::ModelParamOldSVM::ParseCmdLine(), MLL::SVMparam::ParseCmdLineParameter(), MLL::ModelUsfCasCor::Predict(), MLL::ModelSvmBase::Predict(), MLL::ModelDual::Predict(), MLL::AbundanceCorrectionMatrix::Prediction(), MLL::ModelKnn::ProbabilitiesByClass(), MLL::ModelUsfCasCor::ProbabilitiesByClass(), MLL::ModelSvmBase::ProbabilitiesByClass(), MLL::ModelOldSVM::ProbabilitiesByClass(), MLL::ModelDual::ProbabilitiesByClass(), MLL::SVMModel::ProbabilitiesByClass(), MLL::ModelDual::ProbabilitiesByClassDual(), MLL::UsfCasCor::process_line(), CrossValidationApp::ProcessCmdLineParameter(), CrossValidationApp::ProcessCmdLineParameters(), JobManagment::Job::ProcessStatusField(), JobManagment::Job::ProcessStatusStr(), MLL::DuplicateImages::PurgeDuplicates(), JobManagment::JobList::PushOnBack(), MLL::DataBase::QueryStatement(), CrossValidationApp::RandomSplitsIntoTrainAndTest(), MLL::NormalizationParms::Read(), MLL::TrainingProcess2::Read(), MLL::Model::ReadSkipToSection(), MLL::ModelParamKnn::ReadSpecificImplementationXML(), MLL::ModelParamDual::ReadSpecificImplementationXML(), MLL::ModelParamOldSVM::ReadSpecificImplementationXML(), MLL::ModelParamSvmBase::ReadSpecificImplementationXML(), MLL::ModelParamUsfCasCor::ReadSpecificImplementationXML(), MLL::ModelUsfCasCor::ReadSpecificImplementationXML(), MLL::ModelSvmBase::ReadSpecificImplementationXML(), MLL::ModelDual::ReadSpecificImplementationXML(), MLL::ModelOldSVM::ReadSpecificImplementationXML(), MLL::AbundanceCorrectionMatrix::ReadXml(), MLL::SVMparam::ReadXML(), MLL::Model::ReadXML(), MLL::ModelDual::ReconcilePredictions(), MLL::Model::ReduceTrainExamples(), CrossValidationApp::RemoveDuplicateImages(), MLL::FeatureVectorList::RemoveEntriesWithMissingFeatures(), ReportError(), SipperHardware::InstrumentDataManager::ReportInstrumentData(), MLL::SipperExtractionImageManager::ReportStatistics(), MLL::SipperExtractionImageManager::ReportStatsByDepth(), MLL::FeatureVectorList::ReSyncSymbolicData(), MLL::ModelDual::RetrieveCrossProbTable(), MLL::SVMModel::RetrieveCrossProbTable(), MLL::Model::RetrieveCrossProbTable(), JobManagment::JobManager::Run(), MLL::CrossValidation::RunCrossValidation(), MLL::CrossValidationVoting::RunCrossValidation(), MLL::CrossValidation::RunValidationOnly(), MLL::CrossValidationVoting::RunValidationOnly(), MLL::CrossValidationThreeWay::RunValidationOnly(), MLL::FileDesc::SameExceptForSymbolicData(), SipperHardware::InstrumentDataList::Save(), MLL::DataBaseImageValidatedEntryList::Save(), MLL::ClassAssignments::Save(), MLL::SVMparam::Save(), MLL::NormalizationParms::Save(), MLL::Orderings::Save(), MLL::Model::Save(), MLL::SVMModel::Save(), MLL::FeatureFileIO::SaveFeatureFile(), MLL::FeatureFileIODstWeb::SaveFile(), MLL::FeatureFileIOColumn::SaveFile(), MLL::FeatureFileIORoberts::SaveFile(), MLL::FeatureFileIOSparse::SaveFile(), MLL::FeatureVectorList::SaveOrderingOfImages(), MLL::TrainingProcess2::SaveResults(), KKU::SegmentorOTSU::SegmentImage(), KKU::SegmentorOTSU::SegmentMaskedImage(), MLL::TrainingConfiguration2::SetFeatureNums(), MLL::UsfCasCor::setup_network(), MLL::SipperExtractionImageManager::SipperExtractionImageManager(), MLL::DataBase::SipperFileGetList(), JobManagment::JobManager::StatusFileProcessLine(), JobManagment::JobManager::StatusFileProcessLineJobStatusChange(), MLL::FeatureVectorList::StratifyAmoungstClasses(), MLL::SVMModel::SupportVectorNames(), SVM289_MFS::svm_load_model_XML_SupportVectorSection(), SVM289_BFS::svm_load_model_XML_SupportVectorSection(), SVM289_BFS::svm_train_one(), SVM289_MFS::svm_train_one(), MLL::TrainingConfiguration2::SVMparamREF(), MLL::ModelParamOldSVM::SvmParamToString(), MLL::SVMparam::SvmParamToString(), MLL::FeatureVectorList::SynchronizeSymbolicData(), MLL::UsfCasCor::TEST_EPOCH(), MLL::ModelParamDual::ToCmdLineStr(), MLL::ModelParamSvmBase::ToCmdLineStr(), MLL::ModelParam::ToCmdLineStr(), MLL::ModelParamOldSVM::ToCmdLineStr(), MLL::SVMparam::ToString(), MLL::UsfCasCor::TRAIN(), MLL::UsfCasCor::train_network(), MLL::ModelKnn::TrainModel(), MLL::ModelUsfCasCor::TrainModel(), MLL::ModelSvmBase::TrainModel(), MLL::ModelOldSVM::TrainModel(), MLL::ModelDual::TrainModel(), MLL::Model::TrainModel(), MLL::UsfCasCor::TrainNewClassifier(), CrossValidationApp::ValidationProcess(), MLL::SVMModel::Write(), CrossValidationApp::WriteABiasMatrix(), MLL::DataBaseServerList::WriteConfigFile(), MLL::ModelParamOldSVM::WriteSpecificImplementationXML(), MLL::ModelParamSvmBase::WriteSpecificImplementationXML(), MLL::ModelParamUsfCasCor::WriteSpecificImplementationXML(), MLL::ModelParamDual::WriteSpecificImplementationXML(), MLL::ModelKnn::WriteSpecificImplementationXML(), MLL::ModelUsfCasCor::WriteSpecificImplementationXML(), MLL::ModelSvmBase::WriteSpecificImplementationXML(), MLL::ModelOldSVM::WriteSpecificImplementationXML(), MLL::ModelDual::WriteSpecificImplementationXML(), MLL::SVMparam::WriteXML(), MLL::ModelParam::WriteXML(), MLL::ClassificationBiasMatrix::WriteXML(), MLL::Model::WriteXML(), MLL::TrainingProcess2::WriteXml(), MLL::ModelOldSVM::~ModelOldSVM(), MLL::SVMModel::~SVMModel(), and MLL::TrainingProcess2::~TrainingProcess2().
int32 KKU::RunLog::Level () const inline
Definition at line 81 of file RunLog.h.
int32 KKU::RunLog::LineCount () const inline
Definition at line 122 of file RunLog.h.
Referenced by PicesInterface::TrainingModel2::LastRunLogTextLine(), and PicesInterface::PicesRunLog::LineCount().
int32 RunLog::MemoryConsumedEstimated () const
Definition at line 102 of file RunLog.cpp.
References KKU::KKStr::MemoryConsumedEstimated(), and RunLog().
RunLog & RunLog::operator<< (int16 right)
Definition at line 285 of file RunLog.cpp.
References Append(), KKU::KKStr::Str(), and KKU::StrFormatInt().
RunLog & RunLog::operator<< (uint16 right)
Definition at line 295 of file RunLog.cpp.
References Append(), KKU::KKStr::Str(), and KKU::StrFormatInt().
RunLog & RunLog::operator<< (int32 right)
Definition at line 305 of file RunLog.cpp.
References Append(), KKU::KKStr::AppendInt32(), and KKU::KKStr::Str().
RunLog & RunLog::operator<< (uint32 right)
Definition at line 315 of file RunLog.cpp.
References Append(), KKU::KKStr::AppendUInt32(), and KKU::KKStr::Str().
RunLog & RunLog::operator<< (int64 right)
Definition at line 325 of file RunLog.cpp.
References Append(), KKU::KKStr::Str(), and KKU::StrFormatInt64().
RunLog & RunLog::operator<< (uint64 right)
Definition at line 335 of file RunLog.cpp.
References Append(), KKU::KKStr::Str(), and KKU::StrFormatInt64().
RunLog & RunLog::operator<< (double right)
Definition at line 345 of file RunLog.cpp.
References Append(), and KKU::SPRINTF().
RunLog & RunLog::operator<< (char right)
Definition at line 355 of file RunLog.cpp.
References Append().
RunLog & RunLog::operator<< (const char * right)
Definition at line 366 of file RunLog.cpp.
References Append().
RunLog & RunLog::operator<< (const KKStr & right)
Definition at line 374 of file RunLog.cpp.
References Append(), and KKU::KKStr::Str().
RunLog & RunLog::operator<< (KKStrConstPtr right)
Definition at line 382 of file RunLog.cpp.
References Append().
RunLog& KKU::RunLog::operator<< (ostream &(*)(ostream &) mf)
void KKU::RunLog::SetLevel (int32 _level) inline
Definition at line 146 of file RunLog.h.
Referenced by PicesInterface::PicesRunLog::Write(), and PicesInterface::PicesRunLog::Writeln().
void RunLog::SetLoggingLevel (int32 _loggingLevel)
Definition at line 197 of file RunLog.cpp.
Referenced by PicesInterface::PicesRunLog::SetLoggingLevel().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/RunLog.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/RunLog.cpp