Pices: SipperDiskUtilities.SipperPartitionSector Class Reference
SipperDiskUtilities.SipperPartitionSector Class Reference
Public Member Functions
SipperPartitionSector (byte[] buffer, ref int nextIndex)
SipperPartitionSector (PartitionTableEntry sipperPartition)
bool Equals (SipperPartitionSector other)
void FillBuffer (byte[] buffer, ref int nextIndex)
bool IsASipperPartion ()
void Write (FileStream fs)
Static Public Member Functions
static int BuffSpaceNeeded ()
static SipperPartitionSector CreateFromFileStream (FileStream fs)
Properties
long DiskSizeBytes [get]
UInt32 EndSector [get, set]
UInt32 FileDataSector [get, set]
UInt32 NextFcbSector [get, set]
UInt32 NextFileHandle [get, set]
UInt32 TotalSectors [get, set]
Detailed Description
Definition at line 8 of file SipperPartitionSector.cs.
Constructor & Destructor Documentation
SipperDiskUtilities.SipperPartitionSector.SipperPartitionSector (byte[] buffer, ref int nextIndex) inline
Definition at line 47 of file SipperPartitionSector.cs.
References SipperDiskUtilities.Constants.LOGICAL_BLOCK_SIZE, SipperDiskUtilities.Constants.SIPPER_PARTITION_ID_SIZE, and x.
Referenced by SipperDiskUtilities.SipperPartitionSector.CreateFromFileStream().
SipperDiskUtilities.SipperPartitionSector.SipperPartitionSector (PartitionTableEntry sipperPartition) inline
Definition at line 78 of file SipperPartitionSector.cs.
References SipperDiskUtilities.Constants.LOGICAL_BLOCK_SIZE, SipperDiskUtilities.Constants.MAX_SIPPER_FILES, SipperDiskUtilities.PartitionTableEntry.RelativeSector, SipperDiskUtilities.Constants.SIPPER_PARITION_ID, SipperDiskUtilities.Constants.SIPPER_PARTITION_ID_SIZE, SipperDiskUtilities.PartitionTableEntry.TotalSectors, and x.
Member Function Documentation
static int SipperDiskUtilities.SipperPartitionSector.BuffSpaceNeeded () inline static
Definition at line 108 of file SipperPartitionSector.cs.
References SipperDiskUtilities.Constants.LOGICAL_BLOCK_SIZE.
Referenced by SipperDiskUtilities.SipperPartitionSector.CreateFromFileStream(), SipperDiskUtilities.PartitionTableEntry.GetSipperDirectoryByteOffset(), and SipperDiskUtilities.SipperPartitionSector.Write().
static SipperPartitionSector SipperDiskUtilities.SipperPartitionSector.CreateFromFileStream (FileStream fs) inline static
Definition at line 153 of file SipperPartitionSector.cs.
References SipperDiskUtilities.SipperPartitionSector.BuffSpaceNeeded(), and SipperDiskUtilities.SipperPartitionSector.SipperPartitionSector().
Referenced by SipperDiskUtilities.SipperDisk.AreWeTheSameDrive().
bool SipperDiskUtilities.SipperPartitionSector.Equals (SipperPartitionSector other) inline
Definition at line 30 of file SipperPartitionSector.cs.
References SipperDiskUtilities.SipperPartitionSector.TotalSectors.
Referenced by SipperDiskUtilities.SipperDisk.AreWeTheSameDrive().
void SipperDiskUtilities.SipperPartitionSector.FillBuffer (byte[] buffer, ref int nextIndex) inline
Definition at line 117 of file SipperPartitionSector.cs.
References SipperDiskUtilities.Constants.FillBuffer(), SipperDiskUtilities.Constants.SIPPER_PARTITION_ID_SIZE, and x.
Referenced by SipperDiskUtilities.SipperPartitionSector.Write().
bool SipperDiskUtilities.SipperPartitionSector.IsASipperPartion () inline
Definition at line 144 of file SipperPartitionSector.cs.
References SipperDiskUtilities.Constants.SIPPER_PARITION_ID.
void SipperDiskUtilities.SipperPartitionSector.Write (FileStream fs) inline
Definition at line 164 of file SipperPartitionSector.cs.
References SipperDiskUtilities.SipperPartitionSector.BuffSpaceNeeded(), and SipperDiskUtilities.SipperPartitionSector.FillBuffer().
Property Documentation
long SipperDiskUtilities.SipperPartitionSector.DiskSizeBytes get
Definition at line 19 of file SipperPartitionSector.cs.
UInt32 SipperDiskUtilities.SipperPartitionSector.EndSector get set
Definition at line 24 of file SipperPartitionSector.cs.
UInt32 SipperDiskUtilities.SipperPartitionSector.FileDataSector get set
Definition at line 23 of file SipperPartitionSector.cs.
Referenced by SipperDiskUtilities.SipperDisk.ResetSipperDirectory().
UInt32 SipperDiskUtilities.SipperPartitionSector.NextFcbSector get set
Definition at line 25 of file SipperPartitionSector.cs.
Referenced by SipperDiskUtilities.SipperDisk.ResetSipperDirectory().
UInt32 SipperDiskUtilities.SipperPartitionSector.NextFileHandle get set
Definition at line 26 of file SipperPartitionSector.cs.
Referenced by SipperDiskUtilities.SipperDisk.ResetSipperDirectory().
UInt32 SipperDiskUtilities.SipperPartitionSector.TotalSectors get set
Definition at line 22 of file SipperPartitionSector.cs.
Referenced by SipperDiskUtilities.SipperPartitionSector.Equals().
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperDiskUtilities/SipperPartitionSector.cs