Pices: MLL::ClassStatisticList Class Reference
MLL::ClassStatisticList Class Reference
#include <ClassStatistic.h>
Classes
class ClassStatisticSortComparrison
class ClassStatSortByCount
Public Types
typedef KKU::int32 int32
typedef KKU::uint32 uint32
Public Member Functions
ClassStatisticList (bool _owner)
ClassStatisticPtr LookUpByImageClass (MLClassConstPtr mlClass) const
const ClassStatisticList & operator+= (const ClassStatisticList &right)
int32 operator[] (MLClassConstPtr mlClass)
void PrintReport (ostream &r)
void PushOnBack (ClassStatisticPtr stat)
void PushOnFront (ClassStatisticPtr stat)
void SortByClassName ()
void SortByCount ()
Detailed Description
Definition at line 45 of file ClassStatistic.h.
Member Typedef Documentation
typedef KKU::int32 MLL::ClassStatisticList::int32
Definition at line 50 of file ClassStatistic.h.
typedef KKU::uint32 MLL::ClassStatisticList::uint32
Definition at line 51 of file ClassStatistic.h.
Constructor & Destructor Documentation
ClassStatisticList::ClassStatisticList (bool _owner)
Definition at line 67 of file ClassStatistic.cpp.
Member Function Documentation
ClassStatisticPtr ClassStatisticList::LookUpByImageClass (MLClassConstPtr mlClass) const
Definition at line 112 of file ClassStatistic.cpp.
Referenced by operator+=().
const ClassStatisticList & ClassStatisticList::operator+= (const ClassStatisticList & right)
Definition at line 91 of file ClassStatistic.cpp.
References LookUpByImageClass(), MLL::ClassStatistic::MLClass(), and PushOnBack().
int32 ClassStatisticList::operator[] (MLClassConstPtr mlClass)
Definition at line 201 of file ClassStatistic.cpp.
void ClassStatisticList::PrintReport (ostream & r)
Definition at line 185 of file ClassStatistic.cpp.
References MLL::ClassStatistic::Count(), KKU::endl(), MLL::ClassStatistic::Name(), and SortByClassName().
void ClassStatisticList::PushOnBack (ClassStatisticPtr stat)
Definition at line 74 of file ClassStatistic.cpp.
References MLL::ClassStatistic::MLClass().
Referenced by MLL::AbundanceCorrectionMatrix::AdjustClassificationCounts(), MLL::SipperExtractionImageManager::ClassStats(), MLL::FeatureVectorList::GetClassStatistics(), MLL::AbundanceCorrectionMatrix::LumpCounts(), and operator+=().
void ClassStatisticList::PushOnFront (ClassStatisticPtr stat)
Definition at line 82 of file ClassStatistic.cpp.
References MLL::ClassStatistic::MLClass().
void ClassStatisticList::SortByClassName ()
Definition at line 166 of file ClassStatistic.cpp.
Referenced by MLL::FeatureVectorList::GetClassStatistics(), and PrintReport().
void ClassStatisticList::SortByCount ()
Definition at line 176 of file ClassStatistic.cpp.
Referenced by MLL::SipperExtractionImageManager::ClassStats().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ClassStatistic.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ClassStatistic.cpp