Pices: JobManagment::Job Class Reference
JobManagment::Job Class Reference abstract
#include <Job.h>
Public Types
typedef map< KKStr,
ConstructorPtr > ConstructorIndex
typedef JobPtr(* ConstructorPtr)(JobManagerPtr _manager)
typedef Job * JobPtr
enum JobStatus {
jsNULL, jsOpen, jsStarted, jsDone,
jsExpanded
}
enum JobTypes { jtNULL, jtBinaryCombo, jtMultiClass, jtRandomSplit }
Public Member Functions
Job (const Job &j)
Job (JobManagerPtr _manager, int _jobId, int _parentId, int _numPorcessesAllowed, RunLog &_log)
Job (JobManagerPtr _manager)
~Job ()
void AddPrerequisites (int _prerequisite)
void AddPrerequisites (VectorInt _prerequisites)
virtual void CompletedJobDataRead (istream &i)
virtual void CompletedJobDataWrite (ostream &o)
virtual JobPtr Duplicate () const =0
bool InPrerequisites (int _jobId)
int JobId () const
void JobId (int _jobId)
virtual const char * JobType () const
RunLog & Log ()
JobManagerPtr Manager () const
int ParentId () const
const VectorInt & Prerequisites () const
virtual void ProcessNode ()=0
virtual void ProcessStatusField (const KKStr &fieldName, const KKStr &fieldValue)
virtual void ReFresh (Job &j)
JobStatus Status () const
void Status (JobStatus _status)
KKStr StatusStr () const
virtual KKStr ToStatusStr ()
Static Public Member Functions
static JobPtr CallAppropriateConstructor (JobManagerPtr _manager, const KKStr &_jobTypeName, const KKStr &_statusStr)
static JobStatus JobStatusFromStr (const KKStr &statusStr)
static KKStr JobStatusToStr (JobStatus status)
static void JobTypeFromStr (const KKStr &s)
static KKStr JobTypeToStr (JobTypes jt)
static void RegisterConstructor (const KKStr &_name, ConstructorPtr _constructor)
Public Attributes
RunLog & log
Static Public Attributes
static ConstructorIndex registeredConstructors
Protected Member Functions
void PrerequisitesFromStr (const KKStr &s)
KKStr PrerequisitesToStr () const
void ProcessStatusStr (const KKStr &statusStr)
Protected Attributes
int jobId
JobManagerPtr manager
int numPorcessesAllowed
int numProcessors
int parentId
VectorInt prerequisites
JobStatus status
Detailed Description
Definition at line 54 of file Job.h.
Member Typedef Documentation
typedef map<KKStr, ConstructorPtr> JobManagment::Job::ConstructorIndex
Definition at line 84 of file Job.h.
typedef JobPtr(* JobManagment::Job::ConstructorPtr)(JobManagerPtr _manager)
Definition at line 82 of file Job.h.
typedef Job* JobManagment::Job::JobPtr
Definition at line 61 of file Job.h.
Member Enumeration Documentation
enum JobManagment::Job::JobStatus
Enumerator
jsNULL
jsOpen
jsStarted
jsDone
jsExpanded
Definition at line 57 of file Job.h.
enum JobManagment::Job::JobTypes
Enumerator
jtNULL
jtBinaryCombo
jtMultiClass
jtRandomSplit
Definition at line 59 of file Job.h.
Constructor & Destructor Documentation
Job::Job (const Job & j)
Definition at line 41 of file Job.cpp.
JobManagment::Job::Job (JobManagerPtr _manager, int _jobId, int _parentId, int _numPorcessesAllowed, RunLog & _log)
Job::Job (JobManagerPtr _manager)
Definition at line 81 of file Job.cpp.
Job::~Job ()
Definition at line 96 of file Job.cpp.
Member Function Documentation
void JobManagment::Job::AddPrerequisites (int _prerequisite)
void JobManagment::Job::AddPrerequisites (VectorInt _prerequisites)
JobPtr Job::CallAppropriateConstructor (JobManagerPtr _manager, const KKStr & _jobTypeName, const KKStr & _statusStr) static
Definition at line 128 of file Job.cpp.
References ProcessStatusStr(), and registeredConstructors.
Referenced by JobManagment::JobManager::StatusFileProcessLine().
void Job::CompletedJobDataRead (istream & i) virtual
Definition at line 335 of file Job.cpp.
void Job::CompletedJobDataWrite (ostream & o) virtual
Definition at line 328 of file Job.cpp.
virtual JobPtr JobManagment::Job::Duplicate () const pure virtual
Implemented in JobManagment::JobManager.
Referenced by JobManagment::JobList::JobList(), and JobManagment::JobManager::Run().
bool JobManagment::Job::InPrerequisites (int _jobId)
int JobManagment::Job::JobId () const inline
Definition at line 103 of file Job.h.
References jobId.
Referenced by JobManagment::JobList::PushOnBack(), and JobManagment::JobManager::StatusFileProcessLine().
void JobManagment::Job::JobId (int _jobId) inline
Definition at line 111 of file Job.h.
References jobId.
Job::JobStatus Job::JobStatusFromStr (const KKStr & statusStr) static
Definition at line 182 of file Job.cpp.
References KKU::KKStr::CompareIgnoreCase(), jsDone, jsExpanded, jsNULL, jsOpen, and jsStarted.
Referenced by ProcessStatusStr(), JobManagment::JobManager::StatusFileProcessLine(), and JobManagment::JobManager::StatusFileProcessLineJobStatusChange().
KKStr Job::JobStatusToStr (JobStatus status) static
Definition at line 162 of file Job.cpp.
References jsDone, jsExpanded, jsOpen, and jsStarted.
Referenced by StatusStr(), and JobManagment::JobManager::ToStatusStr().
const char * Job::JobType () const virtual
Reimplemented in JobManagment::JobManager.
Definition at line 103 of file Job.cpp.
static void JobManagment::Job::JobTypeFromStr (const KKStr & s) static
static KKStr JobManagment::Job::JobTypeToStr (JobTypes jt) static
RunLog& JobManagment::Job::Log () inline
Definition at line 107 of file Job.h.
References log.
JobManagerPtr JobManagment::Job::Manager () const inline
Definition at line 105 of file Job.h.
References manager.
int JobManagment::Job::ParentId () const inline
Definition at line 104 of file Job.h.
References parentId.
const VectorInt& JobManagment::Job::Prerequisites () const inline
Definition at line 106 of file Job.h.
References prerequisites.
Referenced by JobManagment::JobList::AllPrequisitesDone().
void Job::PrerequisitesFromStr (const KKStr & s) protected
Definition at line 227 of file Job.cpp.
References KKU::KKStr::CompareIgnoreCase(), prerequisites, KKU::KKStr::Split(), and x.
Referenced by ProcessStatusStr().
KKStr Job::PrerequisitesToStr () const protected
Definition at line 209 of file Job.cpp.
References prerequisites, and x.
Referenced by ToStatusStr().
virtual void JobManagment::Job::ProcessNode () pure virtual
Referenced by JobManagment::JobManager::Run().
void Job::ProcessStatusField (const KKStr & fieldName, const KKStr & fieldValue) virtual
Definition at line 318 of file Job.cpp.
References KKU::endl(), KKU::RunLog::Level(), and log.
Referenced by ProcessStatusStr().
void Job::ProcessStatusStr (const KKStr & statusStr) protected
Definition at line 262 of file Job.cpp.
References KKU::KKStr::CompareIgnoreCase(), KKU::endl(), jobId, JobStatusFromStr(), KKU::RunLog::Level(), log, numPorcessesAllowed, numProcessors, parentId, PrerequisitesFromStr(), ProcessStatusField(), KKU::KKStr::Split(), status, KKU::KKStr::Str(), KKU::KKStr::ToInt(), KKU::KKStr::TrimLeft(), KKU::KKStr::TrimRight(), and KKU::KKStr::Upper().
Referenced by CallAppropriateConstructor().
void Job::ReFresh (Job & j) virtual
Definition at line 146 of file Job.cpp.
References jobId, manager, numPorcessesAllowed, numProcessors, parentId, prerequisites, and status.
Referenced by JobManagment::JobManager::StatusFileProcessLine().
void Job::RegisterConstructor (const KKStr & _name, ConstructorPtr _constructor) static
Definition at line 118 of file Job.cpp.
References registeredConstructors.
JobStatus JobManagment::Job::Status () const inline
Definition at line 108 of file Job.h.
References status.
Referenced by JobManagment::JobList::AllPrequisitesDone(), JobManagment::JobList::AreAllJobsDone(), JobManagment::JobList::JobsStillRunning(), JobManagment::JobList::LocateOpenJob(), and JobManagment::JobManager::StatusFileProcessLineJobStatusChange().
void JobManagment::Job::Status (JobStatus _status) inline
Definition at line 112 of file Job.h.
References status.
KKStr Job::StatusStr () const
Definition at line 202 of file Job.cpp.
References JobStatusToStr(), and status.
Referenced by JobManagment::JobManager::Run(), and ToStatusStr().
KKStr Job::ToStatusStr () virtual
Reimplemented in JobManagment::JobManager.
Definition at line 245 of file Job.cpp.
References jobId, numPorcessesAllowed, numProcessors, parentId, PrerequisitesToStr(), and StatusStr().
Referenced by JobManagment::JobManager::ToStatusStr().
Member Data Documentation
int JobManagment::Job::jobId protected
Definition at line 183 of file Job.h.
Referenced by JobManagment::JobManager::AllocateNextJobId(), JobId(), ProcessStatusStr(), ReFresh(), and ToStatusStr().
RunLog& JobManagment::Job::log
Definition at line 174 of file Job.h.
Referenced by JobManagment::JobManager::Block(), JobManagment::JobManager::EndBlock(), JobManagment::JobManager::InitilizeJobManager(), Log(), ProcessStatusField(), ProcessStatusStr(), JobManagment::JobManager::Run(), JobManagment::JobManager::StatusFileProcessLine(), and JobManagment::JobManager::StatusFileProcessLineJobStatusChange().
JobManagerPtr JobManagment::Job::manager protected
Definition at line 185 of file Job.h.
Referenced by Manager(), and ReFresh().
int JobManagment::Job::numPorcessesAllowed protected
Definition at line 189 of file Job.h.
Referenced by ProcessStatusStr(), ReFresh(), and ToStatusStr().
int JobManagment::Job::numProcessors protected
Definition at line 186 of file Job.h.
Referenced by ProcessStatusStr(), ReFresh(), and ToStatusStr().
int JobManagment::Job::parentId protected
Definition at line 184 of file Job.h.
Referenced by ParentId(), ProcessStatusStr(), ReFresh(), and ToStatusStr().
VectorInt JobManagment::Job::prerequisites protected
Definition at line 192 of file Job.h.
Referenced by Prerequisites(), PrerequisitesFromStr(), PrerequisitesToStr(), and ReFresh().
map< KKStr, Job::ConstructorPtr > Job::registeredConstructors static
Definition at line 86 of file Job.h.
Referenced by CallAppropriateConstructor(), and RegisterConstructor().
JobStatus JobManagment::Job::status protected
Definition at line 195 of file Job.h.
Referenced by ProcessStatusStr(), ReFresh(), JobManagment::JobManager::Run(), Status(), JobManagment::JobManager::StatusFileProcessLine(), JobManagment::JobManager::StatusFileProcessLineJobStatusChange(), StatusStr(), JobManagment::JobManager::ToStatusStr(), and JobManagment::JobManager::Update().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/JobManager/Job.h
D:/Users/kkramer/IEC/SipperSoftware/JobManager/Job.cpp