Pices: KKU::BmpImage Class Reference
KKU::BmpImage Class Reference
Used to encode and decode BMP Images.
#include <BMPImage.h>
Classes
struct Bmp1BitRec
struct Bmp4BitRecs
struct BMP_24BitPixel
class CodedPixels
This object is used to help encode the data storred in BMPImage::image into 8 or 4 bit compressed formats used by BMP files.
struct CodePair
union DWordParts
union LongParts
class PalletBuilder
union WordParts
Public Types
typedef CodePair * CodePairPtr
Public Member Functions
BmpImage (int32 _height, int32 _width, int32 _numOfColors)
BmpImage (const KKStr &_fileName, bool &successfull)
Constructs a BMP image from the file specified by '_fileName'.
BmpImage (const Raster &raster)
Constructs a BMPImage instance from a Raster image; this is one way to save a Raster image to disk.
~BmpImage ()
void AddPixel (uint32 row, uint32 col, uchar pixValue)
bool AreThereEdgePixels ()
void Binarize ()
const uchar * BlueRow (int32 row) const
Returns the specified Row from the Blue Channel.
void ClearImage ()
bool Color () const
Returns true if a Color image.
void DoubleSize ()
void DownSize ()
void EliminateVerticalLines ()
const KKStr & FileName () const
bool FourBitUncompressed ()
uint32 Height () const
uchar ** Image ()
Returns back two dimension matrix of image; if color it will be the green channel.
const uchar * ImageRow (int32 row) const
Returns the specified Row from the Green Channel.
void InitializeFields (int32 _height, int32 _width)
uchar MaxPixVal () const
uchar & Pixel (int32 row, int32 col)
void Print ()
void ReAllocateForBiggerScreen ()
Used to expand dimensions of image by 6 pixels so as to make sure that no image is along the edge.
const uchar * RedRow (int32 row) const
Returns the specified Row from the Red Channel.
void Save (const KKStr &fileName)
void SaveGrayscaleInverted4Bit (const KKStr &_fileName)
Saves image using 4 bit compressed grayscale where Background = 255 and foreground = 0.
void SaveGrayscaleInverted8Bit (const KKStr &_fileName)
Saves image using compressed grayscale where Background = 255 and foreground = 0.
void Set16Colors ()
void Set256Colors ()
void SetPaletteEntry (int32 palletIndex, const PixelValue &pixValue)
void SetPixelValue (int32 row, int32 col, int32 pixel)
Will set the pixel value of the specified row and col to 'pixel'.
uint32 Width () const
Detailed Description
Used to encode and decode BMP Images.
Purpose of this class it to facilitate the loading and saving of BMP Image files. Not all formats are supported, but the compressed version is, which most others don't support. As a result this class will write considerably smaller BMP files than other utilities that I have tried. This results in faster writing images due to less disk-io.
This object was originally designed to work in conjunction with Image Extraction. It requires no other libraries and can read and write BMP files.
When ImageExtraction creates a Bmp file it will provide pixel values between 0 and 7, where 0 is the background and 7 is the foreground. This is a result of the SIPPER 2 and 3 Formats and may change in the future. When saving the BMP file BMPImage will map these values through the palette to 0=255, 1=219, 2=182, 3=146, 4=109, 5=73, 6=36, 7=0 resulting in a white background and a Black foreground.
Definition at line 49 of file BMPImage.h.
Member Typedef Documentation
typedef CodePair* KKU::BmpImage::CodePairPtr
Definition at line 214 of file BMPImage.h.
Constructor & Destructor Documentation
BmpImage::BmpImage (int32 _height, int32 _width, int32 _numOfColors)
Definition at line 692 of file BMPImage.cpp.
References InitializeFields().
BmpImage::BmpImage (const KKStr & _fileName, bool & successfull)
Constructs a BMP image from the file specified by '_fileName'.
Parameters
[in] _fileName Name of file to load BMP image from.
[out] successful Returns true if file successful in loading.
Definition at line 448 of file BMPImage.cpp.
References BI_RGB, BI_RLE4, BI_RLE8, KKU::endl(), KKU::osFOPEN(), KKU::KKStr::Str(), and x.
BmpImage::BmpImage (const Raster & raster)
Constructs a BMPImage instance from a Raster image; this is one way to save a Raster image to disk.
Definition at line 711 of file BMPImage.cpp.
References KKU::Raster::Blue(), KKU::Raster::Color(), KKU::Raster::Height(), InitializeFields(), KKU::Raster::Red(), KKU::Raster::Rows(), and KKU::Raster::Width().
BmpImage::~BmpImage ()
Definition at line 748 of file BMPImage.cpp.
Member Function Documentation
void BmpImage::AddPixel (uint32 row, uint32 col, uchar pixValue)
Definition at line 2671 of file BMPImage.cpp.
Referenced by MLL::SipperBlob::Save().
bool BmpImage::AreThereEdgePixels ()
Definition at line 2046 of file BMPImage.cpp.
References Height(), and Width().
void BmpImage::Binarize ()
Definition at line 2232 of file BMPImage.cpp.
const uchar * BmpImage::BlueRow (int32 row) const
Returns the specified Row from the Blue Channel.
Definition at line 2693 of file BMPImage.cpp.
References KKU::endl(), and Height().
Referenced by KKU::Raster::Raster().
void BmpImage::ClearImage ()
Definition at line 2681 of file BMPImage.cpp.
bool KKU::BmpImage::Color () const inline
Returns true if a Color image.
Definition at line 118 of file BMPImage.h.
Referenced by KKU::Raster::Raster().
void KKU::BmpImage::DoubleSize ()
void BmpImage::DownSize ()
Definition at line 1959 of file BMPImage.cpp.
void BmpImage::EliminateVerticalLines ()
Definition at line 2105 of file BMPImage.cpp.
References x.
const KKStr& KKU::BmpImage::FileName () const inline
Definition at line 121 of file BMPImage.h.
bool BmpImage::FourBitUncompressed ()
Definition at line 2743 of file BMPImage.cpp.
References BI_RGB.
uint32 KKU::BmpImage::Height () const inline
Definition at line 125 of file BMPImage.h.
Referenced by AreThereEdgePixels(), BlueRow(), KKU::Raster::CreatePaddedRaster(), ImageRow(), and RedRow().
uchar** KKU::BmpImage::Image () inline
Returns back two dimension matrix of image; if color it will be the green channel.
Definition at line 130 of file BMPImage.h.
const uchar * BmpImage::ImageRow (int32 row) const
Returns the specified Row from the Green Channel.
Definition at line 2710 of file BMPImage.cpp.
References KKU::endl(), and Height().
Referenced by KKU::Raster::CreatePaddedRaster(), and KKU::Raster::Raster().
void BmpImage::InitializeFields (int32 _height, int32 _width)
Definition at line 1065 of file BMPImage.cpp.
References BI_RLE4, and BI_RLE8.
Referenced by BmpImage().
uchar KKU::BmpImage::MaxPixVal () const inline
Definition at line 138 of file BMPImage.h.
uchar & BmpImage::Pixel (int32 row, int32 col)
Definition at line 2000 of file BMPImage.cpp.
void BmpImage::Print ()
Definition at line 2211 of file BMPImage.cpp.
References KKU::endl(), KKU::Min(), and x.
void BmpImage::ReAllocateForBiggerScreen ()
Used to expand dimensions of image by 6 pixels so as to make sure that no image is along the edge.
Definition at line 1360 of file BMPImage.cpp.
const uchar * BmpImage::RedRow (int32 row) const
Returns the specified Row from the Red Channel.
Definition at line 2727 of file BMPImage.cpp.
References KKU::endl(), and Height().
Referenced by KKU::Raster::Raster().
void BmpImage::Save (const KKStr & fileName)
Definition at line 2374 of file BMPImage.cpp.
References KKU::endl(), KKU::osFOPEN(), and KKU::KKStr::Str().
Referenced by MLL::SipperExtractionImageManager::ManagedClass::AddImage(), MLL::SipperBlob::Save(), MLL::SipperExtractionImageManager::ManagedClass::SaveFrame(), and KKU::SaveImage().
void BmpImage::SaveGrayscaleInverted4Bit (const KKStr & _fileName)
Saves image using 4 bit compressed grayscale where Background = 255 and foreground = 0.
If image is color will convert to grayscale 1st. Palette will be set to 0 = 255, 1 = 238, 2 = 221, 3 = 204... 255 = 0.
Definition at line 2250 of file BMPImage.cpp.
References KKU::BmpImage::CodedPixels::AddPixel(), BI_RLE4, KKU::BmpImage::CodedPixels::CreatePixelDataStructure4Bit(), KKU::endl(), KKU::BmpImage::CodedPixels::EOL(), KKU::osFOPEN(), KKU::KKStr::Str(), and x.
Referenced by MLL::SipperExtractionImageManager::ManagedClass::AddImage(), MLL::SipperBlob::Save(), and KKU::SaveImageGrayscaleInverted4Bit().
void BmpImage::SaveGrayscaleInverted8Bit (const KKStr & _fileName)
Saves image using compressed grayscale where Background = 255 and foreground = 0.
If image is color will convert to grayscale 1st. Palette will be set to 0 = 255, 1 = 254, 2 = 253, ... 255 = 0.
Definition at line 2311 of file BMPImage.cpp.
References KKU::BmpImage::CodedPixels::AddPixel(), BI_RLE8, KKU::BmpImage::CodedPixels::CreatePixelDataStructure8Bit(), KKU::endl(), KKU::BmpImage::CodedPixels::EOL(), KKU::osFOPEN(), KKU::KKStr::Str(), and x.
Referenced by KKU::SaveImageGrayscaleInverted8Bit().
void BmpImage::Set16Colors ()
Definition at line 1236 of file BMPImage.cpp.
void BmpImage::Set256Colors ()
Definition at line 1250 of file BMPImage.cpp.
void BmpImage::SetPaletteEntry (int32 palletIndex, const PixelValue & pixValue)
Definition at line 973 of file BMPImage.cpp.
References KKU::PixelValue::b, KKU::endl(), KKU::PixelValue::g, and KKU::PixelValue::r.
Referenced by MLL::SipperExtractionImageManager::ManagedClass::AddImage(), MLL::SipperBlob::Save(), and MLL::SipperExtractionImageManager::ManagedClass::SaveFrame().
void BmpImage::SetPixelValue (int32 row, int32 col, int32 pixel)
Will set the pixel value of the specified row and col to 'pixel'.
Definition at line 2009 of file BMPImage.cpp.
References KKU::endl().
uint32 KKU::BmpImage::Width () const inline
Definition at line 140 of file BMPImage.h.
Referenced by AreThereEdgePixels(), and KKU::Raster::CreatePaddedRaster().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/BMPImage.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/BMPImage.cpp