Pices: PicesCommander.PlanktonClassStatisticsLoader Class Reference
PicesCommander.PlanktonClassStatisticsLoader Class Reference
Public Member Functions
PlanktonClassStatisticsLoader (PicesDataBaseImageGroup _selectedImageGroup, String _cruiseName, String _stationName, String _deploymentNum, String _sipperFileName, PicesClass _mlClass, char _classKeyToUse, float _probMin, float _probMax, int _sizeMin, int _sizeMax, float _depthMin, float _depthMax)
delegate void AlertCompletion (PlanktonClassStatisticsLoader sender)
void CancelLoad ()
void CancelLoadWait (int maxMilliSecsToWait)
void CleanUpMemory ()
PicesClassStatisticList GetStatsAlreadyLoaded ()
PicesClassStatisticList GetStatsAlreadyLoadedIfNew ()
String Status ()
Properties
bool CancelRequested [get]
int ClassesLoadedCount [get]
AlertCompletion CompletionEvent [get, set]
String CurSipperFileName [get]
bool DoneLoading [get]
uint ImageCountTotal [get]
bool LoaderThreadRuning [get]
int SipperFilesCount [get]
int SipperFilesLoaded [get]
PicesVolumeSampledStatList VolumeWaterSampled [get]
Detailed Description
Definition at line 19 of file PlanktonClassStatisticsLoader.cs.
Constructor & Destructor Documentation
PicesCommander.PlanktonClassStatisticsLoader.PlanktonClassStatisticsLoader (PicesDataBaseImageGroup _selectedImageGroup, String _cruiseName, String _stationName, String _deploymentNum, String _sipperFileName, PicesClass _mlClass, char _classKeyToUse, float _probMin, float _probMax, int _sizeMin, int _sizeMax, float _depthMin, float _depthMax) inline
Definition at line 95 of file PlanktonClassStatisticsLoader.cs.
Member Function Documentation
delegate void PicesCommander.PlanktonClassStatisticsLoader.AlertCompletion (PlanktonClassStatisticsLoader sender)
void PicesCommander.PlanktonClassStatisticsLoader.CancelLoad () inline
Definition at line 146 of file PlanktonClassStatisticsLoader.cs.
Referenced by PicesCommander.PlanktonClassStatisticsLoader.CancelLoadWait().
void PicesCommander.PlanktonClassStatisticsLoader.CancelLoadWait (int maxMilliSecsToWait) inline
Definition at line 153 of file PlanktonClassStatisticsLoader.cs.
References PicesCommander.PlanktonClassStatisticsLoader.CancelLoad().
Referenced by PicesCommander.PlanktonClassStatisticsLoader.CleanUpMemory().
void PicesCommander.PlanktonClassStatisticsLoader.CleanUpMemory () inline
Definition at line 137 of file PlanktonClassStatisticsLoader.cs.
References PicesCommander.PlanktonClassStatisticsLoader.CancelLoadWait().
PicesClassStatisticList PicesCommander.PlanktonClassStatisticsLoader.GetStatsAlreadyLoaded () inline
Definition at line 207 of file PlanktonClassStatisticsLoader.cs.
References PicesInterface::PicesClassStatisticList.Add(), PicesInterface::PicesGoalKeeper.EndBlock(), and PicesInterface::PicesGoalKeeper.StartBlock().
PicesClassStatisticList PicesCommander.PlanktonClassStatisticsLoader.GetStatsAlreadyLoadedIfNew () inline
Definition at line 225 of file PlanktonClassStatisticsLoader.cs.
References PicesInterface::PicesClassStatisticList.Add(), PicesInterface::PicesGoalKeeper.EndBlock(), and PicesInterface::PicesGoalKeeper.StartBlock().
String PicesCommander.PlanktonClassStatisticsLoader.Status () inline
Definition at line 180 of file PlanktonClassStatisticsLoader.cs.
References PicesInterface::PicesGoalKeeper.EndBlock(), and PicesInterface::PicesGoalKeeper.StartBlock().
Property Documentation
bool PicesCommander.PlanktonClassStatisticsLoader.CancelRequested get
Definition at line 64 of file PlanktonClassStatisticsLoader.cs.
int PicesCommander.PlanktonClassStatisticsLoader.ClassesLoadedCount get
Definition at line 79 of file PlanktonClassStatisticsLoader.cs.
AlertCompletion PicesCommander.PlanktonClassStatisticsLoader.CompletionEvent get set
Definition at line 66 of file PlanktonClassStatisticsLoader.cs.
String PicesCommander.PlanktonClassStatisticsLoader.CurSipperFileName get
Definition at line 65 of file PlanktonClassStatisticsLoader.cs.
bool PicesCommander.PlanktonClassStatisticsLoader.DoneLoading get
Definition at line 67 of file PlanktonClassStatisticsLoader.cs.
uint PicesCommander.PlanktonClassStatisticsLoader.ImageCountTotal get
Definition at line 68 of file PlanktonClassStatisticsLoader.cs.
bool PicesCommander.PlanktonClassStatisticsLoader.LoaderThreadRuning get
Definition at line 69 of file PlanktonClassStatisticsLoader.cs.
int PicesCommander.PlanktonClassStatisticsLoader.SipperFilesCount get
Definition at line 71 of file PlanktonClassStatisticsLoader.cs.
int PicesCommander.PlanktonClassStatisticsLoader.SipperFilesLoaded get
Definition at line 72 of file PlanktonClassStatisticsLoader.cs.
PicesVolumeSampledStatList PicesCommander.PlanktonClassStatisticsLoader.VolumeWaterSampled get
Definition at line 74 of file PlanktonClassStatisticsLoader.cs.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/PicesCommander/PlanktonClassStatisticsLoader.cs