Pices: PicesInterface::PicesRasterList Class Reference
PicesInterface::PicesRasterList Class Reference
#include <PicesRaster.h>
Public Member Functions
PicesRasterList ()
PicesRasterList (RasterSipperListPtr &unmanagedImages)
Construct a list of managed PicesRaster instances from the contents of the unmanaged list 'unmanagedImages'.
!PicesRasterList ()
~PicesRasterList ()
void AddList (PicesRasterList^ list)
void AddList (RasterSipperListPtr &list)
Give ownership of the contents of 'list' to this Managed list.
void CleanUpMemory ()
Detailed Description
Definition at line 189 of file PicesRaster.h.
Constructor & Destructor Documentation
PicesInterface::PicesRasterList::PicesRasterList ()
Definition at line 803 of file PicesRaster.cpp.
PicesInterface::PicesRasterList::PicesRasterList (RasterSipperListPtr & unmanagedImages)
Construct a list of managed PicesRaster instances from the contents of the unmanaged list 'unmanagedImages'.
Will take ownership of the instances of Raster in 'unmanagedImages'. The list will be deleted and the unmanaged code should not try to access any of 'unmanagedImages' contents after this call.
Parameters
[in,out] unmanagedImages List of unmanaged 'Raster' objects; the ownership of these instances will be given over to the new Managed instance of 'PicesRasterList'; will be deleted and set to NULL.
Definition at line 808 of file PicesRaster.cpp.
PicesInterface::PicesRasterList::~PicesRasterList ()
Definition at line 826 of file PicesRaster.cpp.
References CleanUpMemory().
PicesInterface::PicesRasterList::!PicesRasterList ()
Definition at line 832 of file PicesRaster.cpp.
Member Function Documentation
void PicesInterface::PicesRasterList::AddList (PicesRasterList^ list)
Definition at line 844 of file PicesRaster.cpp.
Referenced by PicesInterface::PicesFeatureVector::PicesFeatureVector(), and PicesInterface::TrainingModel2::PredictProbabilities().
void PicesInterface::PicesRasterList::AddList (RasterSipperListPtr & list)
Give ownership of the contents of 'list' to this Managed list.
Will take ownership of the unmanaged instances of 'Raster' in 'list'. These instances will be deleted by the ".net" garabage collector so make sure that no unmanaged code makes use of these instances after making this call.
Parameters
[in,out] list The list of 'Raster' objects to turn owneship of; will be deleted and be set to NULL; do not make use of any of these instances in the unmanaged code afetr making this call.
Definition at line 854 of file PicesRaster.cpp.
void PicesInterface::PicesRasterList::CleanUpMemory ()
Definition at line 838 of file PicesRaster.cpp.
Referenced by ~PicesRasterList().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesRaster.h
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesRaster.cpp