Pices: PicesInterface::PicesDataBaseImage Class Reference
PicesInterface::PicesDataBaseImage Class Reference
#include <PicesDataBaseImage.h>
Public Member Functions
PicesDataBaseImage ()
PicesDataBaseImage (DataBaseImagePtr _image)
int CompareBreakTie (PicesDataBaseImage^ right)
int CompareClass2 (PicesDataBaseImage^ right)
int CompareDepth (PicesDataBaseImage^ right)
int CompareSpatially (PicesDataBaseImage^ right)
PicesRaster^ GetImageFromSipperFile (PicesRunLog^ runLog)
Image^ Thumbnail ()
DataBaseImagePtr UnManagedDataBaseImage ()
Protected Member Functions
!PicesDataBaseImage ()
Properties
float BreakTie [get]
uint64 ByteOffset [get]
PicesClass^ Class1 [get]
String^ Class1Name [get]
float Class1Prob [get]
PicesClass^ Class2 [get]
String^ Class2Name [get]
float Class2Prob [get]
uint ClassLogEntryId [get]
uchar ConnectedPixelDist [get]
float Depth [get]
uint ExtractionLogEntryId [get]
uint Height [get]
String^ ImageFileName [get]
uint ImageId [get]
float ImageSize [get, set]
uint PixelCount [get]
String^ SipperFileName [get]
PicesPointList^ SizeCoordinates [get, set]
uint TopLeftCol [get]
uint TopLeftRow [get]
PicesClass^ ValidatedClass [get, set]
String^ ValidatedClassName [get]
uint Width [get]
Detailed Description
Definition at line 23 of file PicesDataBaseImage.h.
Constructor & Destructor Documentation
PicesDataBaseImage::PicesDataBaseImage ()
Definition at line 39 of file PicesDataBaseImage.cpp.
PicesDataBaseImage::PicesDataBaseImage (DataBaseImagePtr _image)
Definition at line 47 of file PicesDataBaseImage.cpp.
PicesDataBaseImage::!PicesDataBaseImage () protected
Definition at line 62 of file PicesDataBaseImage.cpp.
Member Function Documentation
int PicesDataBaseImage::CompareBreakTie (PicesDataBaseImage^ right)
Definition at line 228 of file PicesDataBaseImage.cpp.
References MLL::DataBaseImage::BreakTie(), CompareSpatially(), and UnManagedDataBaseImage().
int PicesDataBaseImage::CompareClass2 (PicesDataBaseImage^ right)
Definition at line 198 of file PicesDataBaseImage.cpp.
References MLL::DataBaseImage::Class2Name(), MLL::DataBaseImage::Class2Prob(), KKU::KKStr::CompareTo(), UnManagedDataBaseImage(), and MLL::DataBaseImage::ValidatedClass().
int PicesDataBaseImage::CompareDepth (PicesDataBaseImage^ right)
Definition at line 240 of file PicesDataBaseImage.cpp.
References CompareSpatially(), MLL::DataBaseImage::Depth(), and UnManagedDataBaseImage().
int PicesDataBaseImage::CompareSpatially (PicesDataBaseImage^ right)
Definition at line 254 of file PicesDataBaseImage.cpp.
References KKU::KKStr::CompareTo(), MLL::DataBaseImage::ImageFileName(), and UnManagedDataBaseImage().
Referenced by CompareBreakTie(), and CompareDepth().
PicesRaster PicesDataBaseImage::GetImageFromSipperFile (PicesRunLog^ runLog)
Definition at line 184 of file PicesDataBaseImage.cpp.
References MLL::DataBaseImage::GetOrigImageFromSipperFile(), and PicesInterface::PicesRunLog::Log().
Image PicesDataBaseImage::Thumbnail ()
Definition at line 103 of file PicesDataBaseImage.cpp.
References PicesInterface::PicesRaster::BuildBitmap(), MLL::DataBaseImage::EncodedThumbnail(), MLL::DataBaseImage::EncodedThumbnailLen(), Height, ImageFileName, and Width.
Referenced by PicesCommander.ThumbNailImageCell::Paint().
DataBaseImagePtr PicesInterface::PicesDataBaseImage::UnManagedDataBaseImage () inline
Definition at line 69 of file PicesDataBaseImage.h.
Referenced by CompareBreakTie(), CompareClass2(), CompareDepth(), CompareSpatially(), PicesInterface::PicesDataBase::FeatureDataRecLoad(), and PicesInterface::PicesDataBase::FeatureDataUpdate().
Property Documentation
float PicesInterface::PicesDataBaseImage::BreakTie get
Definition at line 36 of file PicesDataBaseImage.h.
Referenced by PicesCommander.ThumbNailImageCell::Paint().
uint64 PicesInterface::PicesDataBaseImage::ByteOffset get
Definition at line 37 of file PicesDataBaseImage.h.
Referenced by SipperFile.ImageViewer::ImageViewer().
PicesClass^ PicesInterface::PicesDataBaseImage::Class1 get
Definition at line 38 of file PicesDataBaseImage.h.
Referenced by PicesInterface::PicesDataBaseImageList::ExtractImagesForAGivenClass(), and PicesInterface::PicesDataBaseImageList::ExtractListOfClasses().
String^ PicesInterface::PicesDataBaseImage::Class1Name get
Definition at line 39 of file PicesDataBaseImage.h.
Referenced by PicesCommander.ThumbNailImageCell::Paint().
float PicesInterface::PicesDataBaseImage::Class1Prob get
Definition at line 40 of file PicesDataBaseImage.h.
Referenced by PicesCommander.ThumbNailImageCell::Paint().
PicesClass^ PicesInterface::PicesDataBaseImage::Class2 get
Definition at line 41 of file PicesDataBaseImage.h.
String^ PicesInterface::PicesDataBaseImage::Class2Name get
Definition at line 42 of file PicesDataBaseImage.h.
Referenced by PicesCommander.ThumbNailImageCell::Paint().
float PicesInterface::PicesDataBaseImage::Class2Prob get
Definition at line 43 of file PicesDataBaseImage.h.
uint PicesInterface::PicesDataBaseImage::ClassLogEntryId get
Definition at line 44 of file PicesDataBaseImage.h.
Referenced by SipperFile.ImageViewer::ImageViewer().
uchar PicesInterface::PicesDataBaseImage::ConnectedPixelDist get
Definition at line 45 of file PicesDataBaseImage.h.
Referenced by SipperFile.ImageViewer::ImageViewer().
float PicesInterface::PicesDataBaseImage::Depth get
Definition at line 46 of file PicesDataBaseImage.h.
Referenced by PicesCommander.ThumbNailImageCell::Paint().
uint PicesInterface::PicesDataBaseImage::ExtractionLogEntryId get
Definition at line 47 of file PicesDataBaseImage.h.
Referenced by SipperFile.ImageViewer::ImageViewer().
uint PicesInterface::PicesDataBaseImage::Height get
Definition at line 48 of file PicesDataBaseImage.h.
Referenced by SipperFile.ImageViewer::ImageViewer(), and Thumbnail().
String^ PicesInterface::PicesDataBaseImage::ImageFileName get
Definition at line 49 of file PicesDataBaseImage.h.
Referenced by PicesInterface::PicesDataBase::ImageGroupEntriesInsert(), SipperFile.ImageViewer::ImageViewer(), SipperFile.PredictionBreakDownDisplay::PredictionBreakDownDisplay(), SipperFile.PredictionBreakDownDisplayDual::PredictionBreakDownDisplayDual(), and Thumbnail().
uint PicesInterface::PicesDataBaseImage::ImageId get
Definition at line 50 of file PicesDataBaseImage.h.
float PicesInterface::PicesDataBaseImage::ImageSize get set
Definition at line 51 of file PicesDataBaseImage.h.
uint PicesInterface::PicesDataBaseImage::PixelCount get
Definition at line 54 of file PicesDataBaseImage.h.
Referenced by PicesCommander.ThumbNailImageCell::Paint().
String^ PicesInterface::PicesDataBaseImage::SipperFileName get
Definition at line 55 of file PicesDataBaseImage.h.
Referenced by SipperFile.ImageViewer::ImageViewer(), SipperFile.PredictionBreakDownDisplay::PredictionBreakDownDisplay(), and SipperFile.PredictionBreakDownDisplayDual::PredictionBreakDownDisplayDual().
PicesPointList^ PicesInterface::PicesDataBaseImage::SizeCoordinates get set
Definition at line 57 of file PicesDataBaseImage.h.
Referenced by SipperFile.ImageViewer::ImageViewer().
uint PicesInterface::PicesDataBaseImage::TopLeftCol get
Definition at line 53 of file PicesDataBaseImage.h.
Referenced by SipperFile.ImageViewer::ImageViewer().
uint PicesInterface::PicesDataBaseImage::TopLeftRow get
Definition at line 52 of file PicesDataBaseImage.h.
Referenced by SipperFile.ImageViewer::ImageViewer(), SipperFile.PredictionBreakDownDisplay::PredictionBreakDownDisplay(), and SipperFile.PredictionBreakDownDisplayDual::PredictionBreakDownDisplayDual().
PicesClass^ PicesInterface::PicesDataBaseImage::ValidatedClass get set
Definition at line 59 of file PicesDataBaseImage.h.
String^ PicesInterface::PicesDataBaseImage::ValidatedClassName get
Definition at line 60 of file PicesDataBaseImage.h.
Referenced by PicesCommander.ThumbNailImageCell::Paint().
uint PicesInterface::PicesDataBaseImage::Width get
Definition at line 61 of file PicesDataBaseImage.h.
Referenced by SipperFile.ImageViewer::ImageViewer(), PicesCommander.ThumbNailImageCell::Paint(), and Thumbnail().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesDataBaseImage.h
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesDataBaseImage.cpp