Pices: PicesInterface::PicesDataBaseImageGroup Class Reference
PicesInterface::PicesDataBaseImageGroup Class Reference
#include <PicesDataBaseImageGroup.h>
Public Member Functions
PicesDataBaseImageGroup ()
PicesDataBaseImageGroup (DataBaseImageGroupPtr _imageGroup)
PicesDataBaseImageGroup (int _groupId, String^ _name, String^ _description, uint _count)
DataBaseImageGroupPtr UnManagedClass ()
Static Public Member Functions
static void ValidName (String^ %_name, String^ %_errorDesc, bool% _valid)
Protected Member Functions
!PicesDataBaseImageGroup ()
Properties
uint Count [get, set]
String^ Description [get, set]
int ImageGroupId [get, set]
String^ Name [get, set]
Detailed Description
Definition at line 21 of file PicesDataBaseImageGroup.h.
Constructor & Destructor Documentation
PicesDataBaseImageGroup::PicesDataBaseImageGroup ()
Definition at line 35 of file PicesDataBaseImageGroup.cpp.
PicesDataBaseImageGroup::PicesDataBaseImageGroup (DataBaseImageGroupPtr _imageGroup)
Definition at line 42 of file PicesDataBaseImageGroup.cpp.
PicesDataBaseImageGroup::PicesDataBaseImageGroup (int _groupId, String^ _name, String^ _description, uint _count)
Definition at line 49 of file PicesDataBaseImageGroup.cpp.
References PicesInterface::PicesKKStr::SystemStringToKKStr().
PicesDataBaseImageGroup::!PicesDataBaseImageGroup () protected
Definition at line 67 of file PicesDataBaseImageGroup.cpp.
Member Function Documentation
DataBaseImageGroupPtr PicesInterface::PicesDataBaseImageGroup::UnManagedClass () inline
Definition at line 47 of file PicesDataBaseImageGroup.h.
Referenced by PicesInterface::PicesDataBase::FeatureDataForImageGroup(), PicesInterface::PicesDataBase::ImageGetClassStatistics(), PicesInterface::PicesDataBase::ImageGetDepthStatistics(), PicesInterface::PicesDataBase::ImageGroupInsert(), PicesInterface::PicesDataBase::ImagesQuery(), and PicesInterface::PicesDataBase::ImagesQueryByGrouop().
void PicesDataBaseImageGroup::ValidName (String^ % _name, String^ % _errorDesc, bool% _valid) static
Definition at line 163 of file PicesDataBaseImageGroup.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Property Documentation
uint PicesInterface::PicesDataBaseImageGroup::Count get set
Definition at line 45 of file PicesDataBaseImageGroup.h.
String^ PicesInterface::PicesDataBaseImageGroup::Description get set
Definition at line 44 of file PicesDataBaseImageGroup.h.
int PicesInterface::PicesDataBaseImageGroup::ImageGroupId get set
Definition at line 42 of file PicesDataBaseImageGroup.h.
String^ PicesInterface::PicesDataBaseImageGroup::Name get set
Definition at line 43 of file PicesDataBaseImageGroup.h.
Referenced by PicesCommander.ChartAbundancePredictedAndValidated::ChartAbundancePredictedAndValidated(), and PicesCommander.ClassificationStatus::ClassificationStatus().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesDataBaseImageGroup.h
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesDataBaseImageGroup.cpp