Pices: SipperDiskUtilities.SipperDiskFile Class Reference
SipperDiskUtilities.SipperDiskFile Class Reference
Public Member Functions
SipperDiskFile (SipperFileControlBlock _fcb, SipperDisk _sipperDisk)
override void Close ()
override void Flush ()
override int Read (byte[] buffer, int offset, int count)
override int ReadByte ()
override long Seek (long offset, SeekOrigin origin)
override void SetLength (long value)
override void Write (byte[] buffer, int offset, int count)
Protected Member Functions
override void Dispose (bool disposing)
new void Dispose ()
Properties
override bool CanRead [get]
override bool CanSeek [get]
override bool CanWrite [get]
override long Length [get]
override long Position [get, set]
Detailed Description
Definition at line 10 of file SipperDiskFile.cs.
Constructor & Destructor Documentation
SipperDiskUtilities.SipperDiskFile.SipperDiskFile (SipperFileControlBlock _fcb, SipperDisk _sipperDisk) inline
Definition at line 26 of file SipperDiskFile.cs.
References SipperDiskUtilities.SipperFileControlBlock.FileSizeInBytes, and SipperDiskUtilities.SipperFileControlBlock.FileSizeInSectores.
Member Function Documentation
override void SipperDiskUtilities.SipperDiskFile.Close () inline
Definition at line 62 of file SipperDiskFile.cs.
References SipperDiskUtilities.SipperDisk.CloseSipperDiskFile().
Referenced by SipperDiskUtilities.SipperDiskFile.Dispose(), and SipperDiskUtilities.SipperDisk.Dispose().
override void SipperDiskUtilities.SipperDiskFile.Dispose (bool disposing) inline protected
Definition at line 45 of file SipperDiskFile.cs.
References SipperDiskUtilities.SipperDiskFile.Close().
Referenced by SipperDiskUtilities.SipperDisk.Dispose().
new void SipperDiskUtilities.SipperDiskFile.Dispose () inline protected
Definition at line 53 of file SipperDiskFile.cs.
References SipperDiskUtilities.SipperDiskFile.Close().
override void SipperDiskUtilities.SipperDiskFile.Flush () inline
Definition at line 152 of file SipperDiskFile.cs.
override int SipperDiskUtilities.SipperDiskFile.Read (byte[] buffer, int offset, int count) inline
Definition at line 205 of file SipperDiskFile.cs.
References SipperDiskUtilities.SipperDisk.BlockEnd(), SipperDiskUtilities.SipperDisk.BlockStart(), SipperDiskUtilities.SipperFileControlBlock.FileName, SipperDiskUtilities.SipperDisk.FSposition, SipperDiskUtilities.SipperDisk.FSread(), and SipperDiskUtilities.SipperDisk.FSseek().
Referenced by SipperDiskUtilities.SipperDiskFile.ReadByte().
override int SipperDiskUtilities.SipperDiskFile.ReadByte () inline
Definition at line 191 of file SipperDiskFile.cs.
References SipperDiskUtilities.SipperDiskFile.Read().
override long SipperDiskUtilities.SipperDiskFile.Seek (long offset, SeekOrigin origin) inline
Definition at line 158 of file SipperDiskFile.cs.
override void SipperDiskUtilities.SipperDiskFile.SetLength (long value) inline
Definition at line 185 of file SipperDiskFile.cs.
override void SipperDiskUtilities.SipperDiskFile.Write (byte[] buffer, int offset, int count) inline
Definition at line 311 of file SipperDiskFile.cs.
Property Documentation
override bool SipperDiskUtilities.SipperDiskFile.CanRead get
Definition at line 133 of file SipperDiskFile.cs.
override bool SipperDiskUtilities.SipperDiskFile.CanSeek get
Definition at line 134 of file SipperDiskFile.cs.
override bool SipperDiskUtilities.SipperDiskFile.CanWrite get
Definition at line 135 of file SipperDiskFile.cs.
override long SipperDiskUtilities.SipperDiskFile.Length get
Definition at line 136 of file SipperDiskFile.cs.
override long SipperDiskUtilities.SipperDiskFile.Position get set
Definition at line 141 of file SipperDiskFile.cs.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperDiskUtilities/SipperDiskFile.cs