Pices: KKU::Histogram Class Reference
KKU::Histogram Class Reference
Used to manage the construction of a Histogram.
#include <Histogram.h>
Public Member Functions
Histogram (float _minValue, int32 _numOfBuckets, float _bucketSize, bool _wrapArround)
~Histogram ()
int32 AreaInRange (int32 minBucket, int32 maxBucket) const
float AreaInRangePercent (int32 minBucket, int32 maxBucket) const
float AverageOfMaxBucket () const
float AverageOfMaxBucketExcludingRange (int32 minBucket, int32 maxBucket) const
float AverageOfMaxBucketInRange (int32 firstBucket, int32 lastBucket) const
float AverageOfMinBucketInRange (int32 minBucket, int32 maxBucket) const
float Bucket (int32 bucket) const
float BucketSize () const
void CalculatePeaks (int32 threshold)
float CountOfMaxBucket () const
RasterPtr CreateGraph () const
RasterPtr CreateGraph (int32 barSize) const
Histogram * Equalized ()
int32 * EqualizedMapTable ()
float GetPeakAvgByHighestOrder (int32 peakNum)
int32 GetPeakBucket (int32 peakNum)
int32 GetPeakByHighestOrder (int32 peakNum)
void GetStats (float &min, float &max, float &mean, float &variance)
void Increment (float val)
bool IsBucketAPeak (int32 bucket, int32 tolerance) const
int32 MaxBucketIdx () const
float MinValue () const
int32 NumOfBuckets () const
void PrintTable (ostream &o)
void Save (KKStr fileName) const
void SaveGraphImage (const KKStr &fileName) const
void SaveGraphImage (const KKStr &fileName, int32 barSize) const
Histogram * Smooth (int32 smoothWidth)
float TotalCount () const
Detailed Description
Used to manage the construction of a Histogram.
Definition at line 24 of file Histogram.h.
Constructor & Destructor Documentation
Histogram::Histogram (float _minValue, int32 _numOfBuckets, float _bucketSize, bool _wrapArround)
Definition at line 36 of file Histogram.cpp.
References KKU::endl(), and x.
Referenced by Equalized(), and Smooth().
Histogram::~Histogram ()
Definition at line 77 of file Histogram.cpp.
Member Function Documentation
int32 Histogram::AreaInRange (int32 minBucket, int32 maxBucket) const
Definition at line 1032 of file Histogram.cpp.
References KKU::endl().
Referenced by AreaInRangePercent().
float Histogram::AreaInRangePercent (int32 minBucket, int32 maxBucket) const
Definition at line 1058 of file Histogram.cpp.
References AreaInRange().
float Histogram::AverageOfMaxBucket () const
Definition at line 111 of file Histogram.cpp.
References MaxBucketIdx().
float Histogram::AverageOfMaxBucketExcludingRange (int32 minBucket, int32 maxBucket) const
Definition at line 989 of file Histogram.cpp.
References KKU::endl().
float Histogram::AverageOfMaxBucketInRange (int32 firstBucket, int32 lastBucket) const
Definition at line 913 of file Histogram.cpp.
References KKU::endl().
Referenced by KKU::Raster::SegmentImage().
float Histogram::AverageOfMinBucketInRange (int32 minBucket, int32 maxBucket) const
Definition at line 952 of file Histogram.cpp.
References KKU::endl().
float Histogram::Bucket (int32 bucket) const
Definition at line 135 of file Histogram.cpp.
References KKU::endl().
Referenced by MLL::CrossValidationThreeWay::CreateDistanceReport(), and MLL::CrossValidationThreeWay::CreateProbabilityReport().
float KKU::Histogram::BucketSize () const inline
Definition at line 60 of file Histogram.h.
Referenced by MLL::CrossValidationThreeWay::CreateDistanceReport(), and MLL::CrossValidationThreeWay::CreateProbabilityReport().
void Histogram::CalculatePeaks (int32 threshold)
Definition at line 777 of file Histogram.cpp.
References IsBucketAPeak().
Referenced by GetPeakBucket(), and GetPeakByHighestOrder().
float Histogram::CountOfMaxBucket () const
Definition at line 126 of file Histogram.cpp.
References MaxBucketIdx().
RasterPtr Histogram::CreateGraph () const
Definition at line 175 of file Histogram.cpp.
References KKU::Raster::DrawLine(), KKU::endl(), IsBucketAPeak(), KKU::Min(), KKU::Raster::ReverseImage(), KKU::Raster::SetPixelValue(), and x.
Referenced by KKU::Raster::HistogramGrayscaleImage(), KKU::Raster::HistogramImage(), and SaveGraphImage().
RasterPtr Histogram::CreateGraph (int32 barSize) const
Definition at line 350 of file Histogram.cpp.
References KKU::Raster::DrawLine(), KKU::endl(), IsBucketAPeak(), KKU::Min(), KKU::Raster::ReverseImage(), KKU::Raster::SetPixelValue(), and x.
HistogramPtr Histogram::Equalized ()
Definition at line 870 of file Histogram.cpp.
References Histogram(), and x.
Referenced by KKU::Raster::HistogramEqualizedImage().
int32* KKU::Histogram::EqualizedMapTable () inline
Definition at line 72 of file Histogram.h.
Referenced by KKU::Raster::HistogramEqualizedImage().
float Histogram::GetPeakAvgByHighestOrder (int32 peakNum)
Definition at line 842 of file Histogram.cpp.
References KKU::endl(), GetPeakByHighestOrder(), and x.
int32 Histogram::GetPeakBucket (int32 peakNum)
Definition at line 792 of file Histogram.cpp.
References CalculatePeaks().
int32 Histogram::GetPeakByHighestOrder (int32 peakNum)
Definition at line 806 of file Histogram.cpp.
References CalculatePeaks(), and x.
Referenced by GetPeakAvgByHighestOrder().
void Histogram::GetStats (float & min, float & max, float & mean, float & variance)
Definition at line 1093 of file Histogram.cpp.
void Histogram::Increment (float val)
Definition at line 150 of file Histogram.cpp.
References KKU::endl().
Referenced by MLL::CrossValidationThreeWay::CreateDistanceReport(), MLL::CrossValidationThreeWay::CreateProbabilityReport(), KKU::Raster::Histogram(), and KKU::Raster::HistogramGrayscale().
bool Histogram::IsBucketAPeak (int32 bucket, int32 tolerance) const
Definition at line 724 of file Histogram.cpp.
References x.
Referenced by CalculatePeaks(), and CreateGraph().
int32 Histogram::MaxBucketIdx () const
Definition at line 89 of file Histogram.cpp.
Referenced by AverageOfMaxBucket(), and CountOfMaxBucket().
float KKU::Histogram::MinValue () const inline
Definition at line 94 of file Histogram.h.
Referenced by MLL::CrossValidationThreeWay::CreateDistanceReport(), and MLL::CrossValidationThreeWay::CreateProbabilityReport().
int32 KKU::Histogram::NumOfBuckets () const inline
Definition at line 96 of file Histogram.h.
Referenced by MLL::CrossValidationThreeWay::CreateProbabilityReport(), and KKU::Raster::HistogramEqualizedImage().
void Histogram::PrintTable (ostream & o)
Definition at line 1070 of file Histogram.cpp.
References KKU::endl(), and x.
void Histogram::Save (KKStr fileName) const
Definition at line 550 of file Histogram.cpp.
References KKU::endl(), and KKU::KKStr::Str().
Referenced by KKU::Raster::SegmentImage(), and KKU::SegmentPolutionImage().
void Histogram::SaveGraphImage (const KKStr & fileName) const
Definition at line 531 of file Histogram.cpp.
References CreateGraph(), and KKU::SaveImage().
Referenced by KKU::Raster::SegmentImage(), and KKU::SegmentPolutionImage().
void Histogram::SaveGraphImage (const KKStr & fileName, int32 barSize) const
Definition at line 539 of file Histogram.cpp.
References CreateGraph(), and KKU::SaveImage().
HistogramPtr Histogram::Smooth (int32 smoothWidth)
Definition at line 606 of file Histogram.cpp.
References Histogram().
Referenced by KKU::Raster::SegmentImage(), and KKU::SegmentPolutionImage().
float KKU::Histogram::TotalCount () const inline
Definition at line 110 of file Histogram.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Histogram.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Histogram.cpp