Pices: MLL::Attribute Class Reference
MLL::Attribute Class Reference
describes a single Feature, Type and possible values.
#include <Attribute.h>
Public Types
typedef KKU::int32 int32
typedef KKU::uint32 uint32
Public Member Functions
Attribute (const KKStr &_name, AttributeType _type, int32 _fieldNum)
Attribute (const Attribute &a)
~Attribute ()
void AddANominalValue (const KKStr &nominalValue, bool &alreadyExists)
Adds a allowable Nominal value to the Nominal or Symbolic field that this attribute represents.
int32 Cardinality ()
Returns back the cardinality of the attribute; the number of possible values it can take.
int32 FieldNum () const
int32 GetNominalCode (const KKStr &nominalValue) const
const KKStr & GetNominalValue (int32 code) const
Returns the nominal value for the given ordinal value.
int32 MemoryConsumedEstimated () const
const KKStr & Name () const
const KKStr & NameUpper () const
bool operator!= (const Attribute &rightSide) const
Attribute & operator= (const Attribute &right)
bool operator== (const Attribute &rightSide) const
AttributeType Type () const
KKStr TypeStr () const
Detailed Description
describes a single Feature, Type and possible values.
Author
Kurt Kramer
Used to support 'FileDesc', 'FeatureVector', and 'ImageFeatures' classes. FileDesc will maintain a list of 'Attribute' objects to describe each separate field in a given FeatureFile. A given Feature can be one of several types, Numeric, Nominal, Ordinal, and Symbolic.
Numeric  - Any floating point value.
Nominal  - Feature must be one of a specified possible values.  The Attribute class will
           maintain a list of possible values.  This will be saved as a integer value from
           in the FeatureVector object.  When training a classifier it would be best to
           bit encode these features.  See the FeatureEncoder class.
Ordinal  - Similar to Nominal except there is a definite ordering of value.
Symbolic - Similar to Nominal except you do not know all the possible values this attribute
           can take on.
See Also
MLL::FeatureEncoder, MLL::FeatureVector, MLL::FeatureFileIO
Definition at line 50 of file Attribute.h.
Member Typedef Documentation
typedef KKU::int32 MLL::Attribute::int32
Definition at line 53 of file Attribute.h.
typedef KKU::uint32 MLL::Attribute::uint32
Definition at line 54 of file Attribute.h.
Constructor & Destructor Documentation
MLL::Attribute::Attribute (const KKStr & _name, AttributeType _type, int32 _fieldNum)
Referenced by MemoryConsumedEstimated().
Attribute::Attribute (const Attribute & a)
Definition at line 57 of file Attribute.cpp.
References MLL::NominalAttribute, and MLL::SymbolicAttribute.
Attribute::~Attribute ()
Definition at line 74 of file Attribute.cpp.
Member Function Documentation
void Attribute::AddANominalValue (const KKStr & nominalValue, bool & alreadyExists)
Adds a allowable Nominal value to the Nominal or Symbolic field that this attribute represents.
To only be used by instances of 'Attribute' that represent Nominal or Symbolic type attributes. If the Attribute type is not s 'Nominal' or 'Symbolic' then this method will throw am exception
Parameters
[in] nominalValue A possible value that this instance of 'Attribute' could represent.
[out] alreadyExists Indicates if this instance of 'Attribute' already contains a nominal value called 'nominalValue'.
Definition at line 109 of file Attribute.cpp.
References KKU::KKStrListIndexed::Add(), and GetNominalCode().
Referenced by MLL::FeatureFileIOC45::LoadFile().
int32 Attribute::Cardinality ()
Returns back the cardinality of the attribute; the number of possible values it can take.
Only attributes with type NominalAttribute or SymbolicAttribute have a fixed number of possible values all others will return 999999999.
Definition at line 160 of file Attribute.cpp.
References MLL::NominalAttribute, KKU::KKStrListIndexed::size(), and MLL::SymbolicAttribute.
Referenced by MLL::FileDesc::Cardinality(), MLL::FileDesc::DisplayAttributeMappings(), MLL::FeatureFileIORoberts::SaveFile(), and MLL::FeatureFileIOC45::SaveFile().
int32 MLL::Attribute::FieldNum () const inline
Definition at line 83 of file Attribute.h.
Referenced by MLL::FileDesc::GetFieldNumFromAttributeName().
int32 Attribute::GetNominalCode (const KKStr & nominalValue) const
Definition at line 170 of file Attribute.cpp.
References KKU::KKStrListIndexed::LookUp().
Referenced by AddANominalValue(), MLL::FileDesc::DisplayAttributeMappings(), MLL::FeatureFileIODstWeb::LoadFile(), MLL::FeatureFileIOC45::LoadFile(), and MLL::FileDesc::LookUpNominalCode().
const KKStr & Attribute::GetNominalValue (int32 code) const
Returns the nominal value for the given ordinal value.
For example: you could have a Attribute called DayOfTheWeek that would be type 'NominalAttribute' where its possible values are "Sun", "Mon", "Tue", "Wed", "Thur", "Fri", and "Sat". In this case a call to this method where 'code' == 3 would return "Wed".
Definition at line 129 of file Attribute.cpp.
References KKU::endl(), and KKU::KKStrListIndexed::LookUp().
Referenced by MLL::FileDesc::DisplayAttributeMappings(), MLL::FeatureEncoder::FeatureEncoder(), MLL::FeatureFileIORoberts::SaveFile(), and MLL::FeatureFileIOC45::SaveFile().
int32 Attribute::MemoryConsumedEstimated () const
Definition at line 80 of file Attribute.cpp.
References Attribute(), KKU::KKStr::MemoryConsumedEstimated(), and KKU::KKStrListIndexed::MemoryConsumedEstimated().
const KKStr& MLL::Attribute::Name () const inline
Definition at line 99 of file Attribute.h.
Referenced by MLL::FeatureEncoder::FeatureEncoder(), and MLL::FeatureFileIOC45::SaveFile().
const KKStr& MLL::Attribute::NameUpper () const inline
Definition at line 102 of file Attribute.h.
bool Attribute::operator!= (const Attribute & rightSide) const
Definition at line 196 of file Attribute.cpp.
Attribute & Attribute::operator= (const Attribute & right)
Definition at line 205 of file Attribute.cpp.
bool Attribute::operator== (const Attribute & rightSide) const
Definition at line 179 of file Attribute.cpp.
References MLL::NominalAttribute, MLL::SymbolicAttribute, and Type().
AttributeType MLL::Attribute::Type () const inline
Definition at line 104 of file Attribute.h.
Referenced by MLL::FileDesc::AddAAttribute(), MLL::FileDesc::Cardinality(), MLL::FileDesc::DisplayAttributeMappings(), MLL::FileDesc::LookUpNominalCode(), operator==(), MLL::FeatureFileIORoberts::SaveFile(), and MLL::FeatureFileIOC45::SaveFile().
KKStr Attribute::TypeStr () const
Definition at line 224 of file Attribute.cpp.
References MLL::AttributeTypeToStr().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/Attribute.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/Attribute.cpp