Pices: KKU::Configuration::ConfSection Class Reference
KKU::Configuration::ConfSection Class Reference
Public Member Functions
ConfSection (const KKStr &_name, int32 _lineNum)
ConfSection (const Configuration::ConfSection &cs)
void AddSetting (const KKStr &_name, const KKStr &_value, int32 _lineNum)
void GetSettings (int32 settingNum, KKStrConstPtr &name, KKStrConstPtr &value, int32 &lineNum)
int32 LineNum () const
KKStrConstPtr LookUpValue (KKStr _name, int32 &lineNum)
int32 MemoryConsumedEstimated () const
KKStrConstPtr Name ()
int32 NumOfSettings ()
KKStrConstPtr SettingName (int32 settingNum) const
KKStrConstPtr SettingValue (int32 settingNum, int32 &lineNum) const
Detailed Description
Definition at line 138 of file Configuration.cpp.
Constructor & Destructor Documentation
KKU::Configuration::ConfSection::ConfSection (const KKStr & _name, int32 _lineNum) inline
Definition at line 141 of file Configuration.cpp.
KKU::Configuration::ConfSection::ConfSection (const Configuration::ConfSection & cs) inline
Definition at line 149 of file Configuration.cpp.
Member Function Documentation
void KKU::Configuration::ConfSection::AddSetting (const KKStr & _name, const KKStr & _value, int32 _lineNum) inline
Definition at line 205 of file Configuration.cpp.
Referenced by KKU::Configuration::LoadFile().
void KKU::Configuration::ConfSection::GetSettings (int32 settingNum, KKStrConstPtr & name, KKStrConstPtr & value, int32 & lineNum) inline
Definition at line 183 of file Configuration.cpp.
References KKU::Configuration::Setting::LineNum(), KKU::Configuration::Setting::Name(), and KKU::Configuration::Setting::Value().
Referenced by KKU::Configuration::GetSetting().
int32 KKU::Configuration::ConfSection::LineNum () const inline
Definition at line 156 of file Configuration.cpp.
Referenced by KKU::Configuration::SectionLineNum().
KKStrConstPtr KKU::Configuration::ConfSection::LookUpValue (KKStr _name, int32 & lineNum) inline
Definition at line 214 of file Configuration.cpp.
References KKU::Configuration::Setting::LineNum(), and KKU::Configuration::Setting::Value().
Referenced by KKU::Configuration::SettingValue().
int32 KKU::Configuration::ConfSection::MemoryConsumedEstimated () const inline
Definition at line 160 of file Configuration.cpp.
KKStrConstPtr KKU::Configuration::ConfSection::Name () inline
Definition at line 158 of file Configuration.cpp.
Referenced by KKU::Configuration::ConfSectionList::LookUp(), and KKU::Configuration::SectionName().
int32 KKU::Configuration::ConfSection::NumOfSettings () inline
Definition at line 165 of file Configuration.cpp.
Referenced by KKU::Configuration::NumOfSettings().
KKStrConstPtr KKU::Configuration::ConfSection::SettingName (int32 settingNum) const inline
Definition at line 168 of file Configuration.cpp.
Referenced by KKU::Configuration::SettingName().
KKStrConstPtr KKU::Configuration::ConfSection::SettingValue (int32 settingNum, int32 & lineNum) const inline
Definition at line 175 of file Configuration.cpp.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Configuration.cpp