Pices: MLL::Classifier2 Class Reference
MLL::Classifier2 Class Reference
#include <Classifier2.h>
Public Member Functions
Classifier2 (TrainingProcess2Ptr _trainer, RunLog &_log)
virtual ~Classifier2 ()
bool Abort ()
MLClassConstPtr ClassifyAImage (FeatureVector &example)
void ClassifyAImage (FeatureVector &example, MLClassConstPtr &predClass1, MLClassConstPtr &predClass2, int32 &predClass1Votes, int32 &predClass2Votes, double &knownClassProb, double &predClass1Prob, double &predClass2Prob, int32 &numOfWinners, double &breakTie, double &compact)
MLClassConstPtr ClassifyAImage (FeatureVector &example, int32 &numOfWinners, bool &knownClassOneOfTheWinners)
MLClassConstPtr ClassifyAImage (FeatureVector &example, double &probability, int32 &numOfWinners, bool &knownClassOneOfTheWinners, double &breakTie)
vector< ProbNamePair > FindWorstSupportVectors (FeatureVectorPtr example, int32 numToFind, MLClassConstPtr c1, MLClassConstPtr c2)
For a given two class pair return the names of the 'numToFind' worst S/V's.
vector< ProbNamePair > FindWorstSupportVectors2 (FeatureVectorPtr example, int32 numToFind, MLClassConstPtr c1, MLClassConstPtr c2)
For a given two class pair return the names of the 'numToFind' worst S/V's.
virtual int32 MemoryConsumedEstimated () const
void ProbabilitiesByClass (const MLClassConstList &classes, FeatureVectorPtr example, int32 *votes, double *probabilities)
For a given feature vector return back the probabilities and votes for each class.
ClassProbListPtr ProbabilitiesByClass (FeatureVectorPtr example)
void ProbabilitiesByClassDual (FeatureVectorPtr example, KKStr &classifier1Desc, KKStr &classifier2Desc, ClassProbListPtr &classifier1Results, ClassProbListPtr &classifier2Results)
void RetrieveCrossProbTable (MLClassConstList &classes, double **crossProbTable)
SVM_SelectionMethod SelectionMethod () const
vector< KKStr > SupportVectorNames (MLClassConstPtr c1, MLClassConstPtr c2)
Detailed Description
Definition at line 64 of file Classifier2.h.
Constructor & Destructor Documentation
Classifier2::Classifier2 (TrainingProcess2Ptr _trainer, RunLog & _log)
Definition at line 41 of file Classifier2.cpp.
References MLL::TrainingProcess2::Abort(), KKU::endl(), MLL::TrainingProcess2::FeaturesAlreadyNormalized(), MLL::MLClassConstList::GetNoiseClass(), MLL::MLClassConstList::GetUnKnownClass(), KKU::RunLog::Level(), MLL::TrainingProcess2::MLClasses(), MLL::Model::ModelType(), MLL::Model::mtOldSVM, MLL::ModelOldSVM::SvmModel(), MLL::TrainingProcess2::TrainedModel(), and MLL::Model::ValidModel().
Classifier2::~Classifier2 () virtual
Definition at line 104 of file Classifier2.cpp.
Member Function Documentation
bool MLL::Classifier2::Abort () inline
Definition at line 75 of file Classifier2.h.
MLClassConstPtr Classifier2::ClassifyAImage (FeatureVector & example)
Definition at line 331 of file Classifier2.cpp.
Referenced by CrossValidationApp::CrossValidate(), MLL::ModelDual::Predict(), PicesInterface::TrainingModel2::PredictClass(), and CrossValidationApp::ValidationProcess().
void MLL::Classifier2::ClassifyAImage (FeatureVector & example, MLClassConstPtr & predClass1, MLClassConstPtr & predClass2, int32 & predClass1Votes, int32 & predClass2Votes, double & knownClassProb, double & predClass1Prob, double & predClass2Prob, int32 & numOfWinners, double & breakTie, double & compact)
MLClassConstPtr MLL::Classifier2::ClassifyAImage (FeatureVector & example, int32 & numOfWinners, bool & knownClassOneOfTheWinners)
MLClassConstPtr MLL::Classifier2::ClassifyAImage (FeatureVector & example, double & probability, int32 & numOfWinners, bool & knownClassOneOfTheWinners, double & breakTie)
vector< ProbNamePair > Classifier2::FindWorstSupportVectors (FeatureVectorPtr example, int32 numToFind, MLClassConstPtr c1, MLClassConstPtr c2)
For a given two class pair return the names of the 'numToFind' worst S/V's.
This method will iterate through all the S/V's removing them one at a time and recompute the decision boundary and probability. It will then return the S/V's that when removed improve the probability in 'c1's the most.
Parameters
[in] example Example that was classified incorrectly.
[in] numToFind The number of the worst examples you are looking for.
[in] c1 Class that the 'example; parameter should have been classed as.
[in] c2 Class that it was classified as.
Definition at line 360 of file Classifier2.cpp.
References MLL::SVMModel::FindWorstSupportVectors().
Referenced by PicesInterface::TrainingModel2::FindWorstSupportVectors().
vector< ProbNamePair > Classifier2::FindWorstSupportVectors2 (FeatureVectorPtr example, int32 numToFind, MLClassConstPtr c1, MLClassConstPtr c2)
For a given two class pair return the names of the 'numToFind' worst S/V's.
This method will iterate through all the S/V's removing them one at a time and rebuild a new SVM then submit example for testing.
Parameters
[in] example Example that was classified incorrectly.
[in] numToFind The number of the worst examples you are looking for.
[in] c1 Class that the 'example; parameter should have been classed as.
[in] c2 Class that it was classified as.
Definition at line 378 of file Classifier2.cpp.
References MLL::SVMModel::FindWorstSupportVectors2().
Referenced by PicesInterface::TrainingModel2::FindWorstSupportVectors2().
int32 Classifier2::MemoryConsumedEstimated () const virtual
Definition at line 110 of file Classifier2.cpp.
References MLL::MLClassConstList::MemoryConsumedEstimated().
Referenced by MLL::ModelDual::MemoryConsumedEstimated().
void MLL::Classifier2::ProbabilitiesByClass (const MLClassConstList & classes, FeatureVectorPtr example, int32 * votes, double * probabilities)
For a given feature vector return back the probabilities and votes for each class.
Parameters
classes [in] List of classes that we can be predicted for The ordering of 'votes' and 'probabilities' will be dictated by this list.
example [in] Feature Vector to make prediction on.
votes [out] Pointer to list of ints, must be as large as 'classes' The number of votes for each corresponding class will be stored hear.
probabilities [out] Pointer to list of double's, must be as large as 'classes' The probability for each corresponding class will be stored hear.
Referenced by CrossValidationApp::CrossValidate(), PicesInterface::TrainingModel2::PredictProbabilities(), MLL::ModelDual::ProbabilitiesByClass(), MLL::ModelDual::ProbabilitiesByClassDual(), MLL::ModelDual::ReconcileProbAndVotes(), and CrossValidationApp::ValidationProcess().
ClassProbListPtr Classifier2::ProbabilitiesByClass (FeatureVectorPtr example)
Definition at line 411 of file Classifier2.cpp.
References MLL::Model::ProbabilitiesByClass().
void Classifier2::ProbabilitiesByClassDual (FeatureVectorPtr example, KKStr & classifier1Desc, KKStr & classifier2Desc, ClassProbListPtr & classifier1Results, ClassProbListPtr & classifier2Results)
Definition at line 433 of file Classifier2.cpp.
References MLL::Model::ProbabilitiesByClassDual().
Referenced by PicesInterface::TrainingModel2::ProbabilitiesByClassDual().
void Classifier2::RetrieveCrossProbTable (MLClassConstList & classes, double ** crossProbTable)
Definition at line 422 of file Classifier2.cpp.
References MLL::Model::RetrieveCrossProbTable().
Referenced by PicesInterface::TrainingModel2::PredictProbabilities(), and MLL::ModelDual::RetrieveCrossProbTable().
SVM_SelectionMethod Classifier2::SelectionMethod () const
Definition at line 119 of file Classifier2.cpp.
References MLL::ModelOldSVM::SelectionMethod(), and MLL::SelectionMethod_NULL.
Referenced by PicesInterface::TrainingModel2::PredictProbabilities().
vector< KKStr > Classifier2::SupportVectorNames (MLClassConstPtr c1, MLClassConstPtr c2)
Definition at line 341 of file Classifier2.cpp.
References MLL::SVMModel::SupportVectorNames().
Referenced by PicesInterface::TrainingModel2::SupportVectorNames().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/Classifier2.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/Classifier2.cpp