Pices: MLL::FeatureVector Class Reference
MLL::FeatureVector Class Reference
Represents a Feature Vector of a single example, labeled or unlabele.
#include <FeatureVector.h>
Public Types
typedef KKU::int32 int32
typedef KKU::uint32 uint32
Public Member Functions
FeatureVector (int32 _numOfFeatures)
FeatureVector (const FeatureVector &_example)
virtual ~FeatureVector ()
void AddFeatureData (int32 _featureNum, FFLOAT _featureData)
void BreakTie (float _breakTie)
Update the BreatTie value.
float BreakTie () const
The difference in probability between the two most likely classes.
const KKStr & ClassName () const
Name of class that this example is assigne to.
void FeatureData (int32 _featureNum, FFLOAT _featureValue)
Assign a value to a specific feature number for the feature vector.
FFLOAT FeatureData (int32 featureNum) const
const FFLOAT * FeatureData () const
FFLOAT * FeatureDataAlter ()
Returns as a pointer to the feature data itself.
const FFLOAT * FeatureDataConst () const
ame as 'FeatureData() except you can modify the data.
bool FeatureDataValid ()
void ImageFileName (const KKStr &_imageFileName)
Name of source of feature vectpr, ex: file name of image that the veature vector was computed from.
const KKStr & ImageFileName () const
Name of file that this FeatureVector was computed from.
virtual int32 MemoryConsumedEstimated () const
void MissingData (bool _missingData)
True indicates that not all the feature data was preseant when this example was loaded from a data file.
bool MissingData () const
True indicates that one or more features were missing.
void MLClass (MLClassConstPtr _mlClass)
Assign a class to this example.
MLClassConstPtr MLClass () const
Class that is example is assigned to.
const KKStr & MLClassName () const
Name of class that this example is assigned to.
int32 NumOfFeatures () const
Number of features in this FeatureVector.
bool operator== (FeatureVector &other_example) const
void OrigSize (FFLOAT _origSize)
The value of Feature[0] before normalization.
FFLOAT OrigSize () const
The value of Feature[0] before normalization.
void PredictedClass (MLClassConstPtr _predictedClass)
MLClassConstPtr PredictedClass () const
const KKStr & PredictedClassName () const
void Probability (FFLOAT _probability)
Assign a prediction probability to this example.
FFLOAT Probability () const
The probability assigned by classifer to the predicted class.
void ResetNumOfFeatures (int32 newNumOfFeatures)
Used to reallocate memory for feature data.
float TotalOfFeatureData () const
Returns the total of all Feature Attributes for this feature vector.
void TrainWeight (float _trainWeight)
Assign a specific example a higher weight for training purposes.
float TrainWeight () const
virtual const char * UnderlyingClass () const
Used by container classes such as 'FeatureVectorList'.
void Validated (bool _validated)
Indicated wheather an expert has validated the class assignment.
bool Validated () const
Protected Member Functions
void AllocateFeatureDataArray ()
Protected Attributes
FFLOAT * featureData
int32 numOfFeatures
Detailed Description
Represents a Feature Vector of a single example, labeled or unlabele.
Author
Kurt Kramer
Used for the representation of a Single example. You create an instance of this object for each single feature vector. You can subclass from this Class to make a specialized FeatureVector as in the ImageFeatures class. Besides keeping track of feature data this class will also track other fields such as ImageFileName which should indicate where the FeatureVector was derived from, probability, breakTie, and others. code
                          FeatureVector                                     *
                                                                            *
Used for the representation of a Single example. You create an instance of * this object for each single feature vector. *
This class was split from "ImageFeatures"; such that "ImageFeatures" is now * derived from this class and contains code that is specialized for the SIPPER * system. *
See Also
FeatureVectorList
ImageFeatures
FeatureFileIO
Used for the representation of a Single example. You create an instance of this object for each single feature vector. You can subclass from this Class to make a specialized FeatureVector as in the ImageFeatures class. Besides keeping track of feature data this class will also track other fields such as ImageFileName which should indicate where the FeatureVector was derived from, probability, breakTie, and others.
See Also
FeatureVectorList
ImageFeatures
FeatureFileIO
Definition at line 68 of file FeatureVector.h.
Member Typedef Documentation
typedef KKU::int32 MLL::FeatureVector::int32
Definition at line 71 of file FeatureVector.h.
typedef KKU::uint32 MLL::FeatureVector::uint32
Definition at line 72 of file FeatureVector.h.
Constructor & Destructor Documentation
FeatureVector::FeatureVector (int32 _numOfFeatures)
Definition at line 36 of file FeatureVector.cpp.
References AllocateFeatureDataArray().
Referenced by MemoryConsumedEstimated().
FeatureVector::FeatureVector (const FeatureVector & _example)
Definition at line 56 of file FeatureVector.cpp.
References AllocateFeatureDataArray(), featureData, numOfFeatures, and x.
FeatureVector::~FeatureVector () virtual
Definition at line 84 of file FeatureVector.cpp.
References featureData.
Member Function Documentation
void FeatureVector::AddFeatureData (int32 _featureNum, FFLOAT _featureData)
Parameters
_featureNum Indicates which feature number to update.
_featureData New value to assign to '_featureNum'.
Definition at line 224 of file FeatureVector.cpp.
References KKU::endl(), featureData, numOfFeatures, and KKU::osWaitForEnter().
Referenced by MLL::FeatureEncoder::CreateEncodedFeatureVector(), MLL::FeatureEncoder2::EncodeAExample(), MLL::FeatureEncoder::EncodeAImage(), MLL::FeatureFileIODstWeb::LoadFile(), MLL::FeatureFileIOColumn::LoadFile(), MLL::FeatureFileIOUCI::LoadFile(), MLL::FeatureFileIOPices::LoadFile(), MLL::FeatureFileIOC45::LoadFile(), MLL::FeatureFileIOSparse::LoadFile(), MLL::FeatureVectorList::ReSyncSymbolicData(), and svm_load_model().
void FeatureVector::AllocateFeatureDataArray () protected
Definition at line 134 of file FeatureVector.cpp.
References featureData, numOfFeatures, and x.
Referenced by FeatureVector().
void MLL::FeatureVector::BreakTie (float _breakTie) inline
Update the BreatTie value.
Definition at line 82 of file FeatureVector.h.
Referenced by MLL::FeatureFileIOPices::LoadFile(), MLL::FeatureVectorList::BreakTieComparison::operator()(), MLL::FeatureVectorList::BreakTieComparisonReversed::operator()(), and MLL::FeatureFileIOPices::SaveFile().
float MLL::FeatureVector::BreakTie () const inline
The difference in probability between the two most likely classes.
Definition at line 121 of file FeatureVector.h.
const KKStr & FeatureVector::ClassName () const
Name of class that this example is assigne to.
Definition at line 200 of file FeatureVector.cpp.
References KKU::endl().
Referenced by CrossValidationApp::RemoveDuplicateImages(), MLL::FeatureFileIORoberts::SaveFile(), MLL::FeatureFileIOUCI::SaveFile(), MLL::FeatureFileIOPices::SaveFile(), MLL::FeatureFileIOC45::SaveFile(), and MLL::FeatureFileIOSparse::SaveFile().
void MLL::FeatureVector::FeatureData (int32 _featureNum, FFLOAT _featureValue)
Assign a value to a specific feature number for the feature vector.
This method will validate that '_featureNum' is not out of range (0 - 'numOfFeatures'). This will prevent the caller from corrupting memory.
Parameters
[in] _featureNum Feature Num to assign '_featureValue' to.
[in] _featureValue Value to assign to feature '_featureNum'.
Referenced by MLL::UsfCasCor::_load_test_data(), MLL::UsfCasCor::_load_training_example(), MLL::FeatureVectorList::CalcStatsForFeatureNum(), MLL::ChainHashNode::ChainHashNode(), SVM289_MFS::Kernel::DotStatic(), SVM289_BFS::Kernel::DotStatic(), MLL::FeatureEncoder2::EncodeAExample(), MLL::FeatureEncoder::EncodeAImage(), MLL::DataBase::FeatureDataInsertRow(), MLL::DataBase::FeatureDataUpdate(), PicesInterface::PicesFeatureVector::FeatureValue(), MLL::UsfCasCor::FilterOutExtremeExamples(), SVM289_MFS::Kernel::k_function(), SVM289_BFS::Kernel::k_function(), MLL::FeatureFileIOPices::LoadFile(), MLL::FeatureVectorList::ReSyncSymbolicData(), MLL::FeatureFileIORoberts::SaveFile(), MLL::FeatureFileIOUCI::SaveFile(), MLL::FeatureFileIOPices::SaveFile(), MLL::FeatureFileIOC45::SaveFile(), MLL::FeatureFileIOSparse::SaveFile(), SVM289_MFS::svm_load_model_XML_SupportVectorSection(), and SVM289_BFS::svm_load_model_XML_SupportVectorSection().
FFLOAT FeatureVector::FeatureData (int32 featureNum) const
Definition at line 150 of file FeatureVector.cpp.
References KKU::endl(), featureData, and NumOfFeatures().
const FFLOAT* MLL::FeatureVector::FeatureData () const inline
Returns
The value of 'featureNum'
Definition at line 137 of file FeatureVector.h.
References featureData.
FFLOAT* MLL::FeatureVector::FeatureDataAlter () inline
Returns as a pointer to the feature data itself.
Definition at line 138 of file FeatureVector.h.
References featureData.
Referenced by MLL::NormalizationParms::NormalizeAImage(), and MLL::NormalizationParms::ToNormalized().
const FFLOAT* MLL::FeatureVector::FeatureDataConst () const inline
ame as 'FeatureData() except you can modify the data.
Definition at line 140 of file FeatureVector.h.
References featureData.
Referenced by MLL::ImageFeaturesNodeKey::CompareTwoImages().
bool FeatureVector::FeatureDataValid ()
Definition at line 247 of file FeatureVector.cpp.
References featureData, FFLOAT_MAX, FFLOAT_MIN, and numOfFeatures.
void MLL::FeatureVector::ImageFileName (const KKStr & _imageFileName) inline
Name of source of feature vectpr, ex: file name of image that the veature vector was computed from.
Definition at line 84 of file FeatureVector.h.
Referenced by MLL::SipperExtractionImageManager::ManagedClass::AddImage(), MLL::DuplicateImages::AddSingleImage(), MLL::FeatureVectorList::BinarySearchByName(), MLL::SipperExtractionImageManager::ManagedClass::CloseOutCurDirectory(), MLL::FeatureEncoder::Compress(), CrossValidationApp::CrossValidate(), MLL::DuplicateImages::ExampleInDetector(), MLL::ExtractImageFileName::ExtractKey(), MLL::DataBase::FeatureDataInsertRow(), MLL::DataBase::FeatureDataRecLoad(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::DataBase::FeatureDataUpdate(), MLL::ChainHash< T >::GroupExamples(), MLL::DuplicateImage::ImageWithSmallestScanLine(), MLL::DuplicateImages::ListOfExamplesToDelete(), MLL::FeatureFileIODstWeb::LoadFile(), MLL::FeatureFileIOColumn::LoadFile(), MLL::FeatureFileIOUCI::LoadFile(), MLL::FeatureFileIOPices::LoadFile(), MLL::FeatureFileIOC45::LoadFile(), MLL::FeatureFileIOSparse::LoadFile(), MLL::FeatureFileIOPices::LoadInSubDirectoryTree(), MLL::FeatureVectorList::LookUpByImageFileName(), MLL::FeatureVectorList::LookUpByRootName(), MLL::FeatureVectorList::ImageFileNameComparison::operator()(), MLL::FeatureVectorList::ImageFileNameComparisonReversed::operator()(), MLL::FeatureVectorList::RootNameComparrison::operator()(), MLL::FeatureVectorList::RootNameComparrisonReversed::operator()(), MLL::FeatureVectorList::ClassNameComparrison::operator()(), MLL::FeatureVectorList::ClassNameComparrisonReversed::operator()(), MLL::DuplicateImages::PurgeDuplicates(), MLL::DuplicateImages::ReportDuplicates(), ImageExtractionManager::DataBaseUpdateThread::Run(), MLL::FeatureFileIOPices::SaveFile(), MLL::FeatureFileIOC45::SaveFile(), SVM289_MFS::svm_load_model_XML_SupportVectorSection(), SVM289_BFS::svm_load_model_XML_SupportVectorSection(), and CrossValidationApp::ValidationProcess().
const KKStr& MLL::FeatureVector::ImageFileName () const inline
Name of file that this FeatureVector was computed from.
Definition at line 125 of file FeatureVector.h.
int32 FeatureVector::MemoryConsumedEstimated () const virtual
Reimplemented in MLL::ImageFeatures.
Definition at line 91 of file FeatureVector.cpp.
References featureData, FeatureVector(), KKU::KKStr::MemoryConsumedEstimated(), and numOfFeatures.
Referenced by MLL::FeatureVectorList::MemoryConsumedEstimated().
void MLL::FeatureVector::MissingData (bool _missingData) inline
True indicates that not all the feature data was preseant when this example was loaded from a data file.
Definition at line 85 of file FeatureVector.h.
Referenced by MLL::FeatureFileIOC45::LoadFile(), MLL::FeatureVectorList::MissingData(), and MLL::FeatureVectorList::RemoveEntriesWithMissingFeatures().
bool MLL::FeatureVector::MissingData () const inline
True indicates that one or more features were missing.
Definition at line 126 of file FeatureVector.h.
void MLL::FeatureVector::MLClass (MLClassConstPtr _mlClass) inline
Assign a class to this example.
Definition at line 83 of file FeatureVector.h.
Referenced by MLL::UsfCasCor::_load_training_example(), MLL::CrossValidationThreeWay::CalculateThirdClassDecisiveProbability(), MLL::FeatureEncoder::Compress(), MLL::BitReduction::compress(), MLL::FeatureEncoder::CreateEncodedFeatureVector(), PicesInterface::PicesFeatureVectorList::CreateListForAGivenLevel(), CrossValidationApp::CrossValidate(), MLL::FeatureEncoder2::EncodeAExample(), MLL::FeatureEncoder::EncodeAImage(), MLL::FeatureEncoder2::EncodedFeatureVectorList(), MLL::FeatureVectorList::ExtractExamplesForHierarchyLevel(), MLL::FeatureVectorList::ExtractMLClassConstList(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::FeatureVectorList::GetClassStatistics(), MLL::FeatureFileIODstWeb::LoadFile(), MLL::FeatureFileIOColumn::LoadFile(), MLL::FeatureFileIOUCI::LoadFile(), MLL::FeatureFileIOPices::LoadFile(), MLL::FeatureFileIOC45::LoadFile(), MLL::FeatureFileIOSparse::LoadFile(), MLL::FeatureVectorList::ClassNameComparrison::operator()(), MLL::FeatureVectorList::ClassNameComparrisonReversed::operator()(), PicesInterface::PicesFeatureVector::PicesFeatureVector(), CrossValidationApp::PrintSizeHistogram(), MLL::CrossValidationThreeWay::RunValidation(), MLL::FeatureFileIOPices::SaveFile(), SVM289_MFS::svm_load_model_XML_SupportVectorSection(), SVM289_BFS::svm_load_model_XML_SupportVectorSection(), and CrossValidationApp::ValidationProcess().
MLClassConstPtr MLL::FeatureVector::MLClass () const inline
Class that is example is assigned to.
Definition at line 123 of file FeatureVector.h.
const KKStr & FeatureVector::MLClassName () const
Name of class that this example is assigned to.
Definition at line 275 of file FeatureVector.cpp.
Referenced by MLL::DuplicateImages::PurgeDuplicates(), and MLL::DuplicateImages::ReportDuplicates().
int32 MLL::FeatureVector::NumOfFeatures () const inline
Number of features in this FeatureVector.
Definition at line 127 of file FeatureVector.h.
References numOfFeatures.
Referenced by MLL::ImageFeaturesNodeKey::CompareTwoImages(), FeatureData(), MLL::DataBase::FeatureDataInsertRow(), MLL::DataBase::FeatureDataUpdate(), PicesInterface::PicesFeatureVector::FeatureValue(), MLL::ChainHashNode::operator==(), MLL::FeatureVectorList::PushOnBack(), MLL::FeatureVectorList::PushOnFront(), and TotalOfFeatureData().
bool FeatureVector::operator== (FeatureVector & other_example) const
Definition at line 286 of file FeatureVector.cpp.
References featureData, and numOfFeatures.
void MLL::FeatureVector::OrigSize (FFLOAT _origSize) inline
The value of Feature[0] before normalization.
Definition at line 86 of file FeatureVector.h.
Referenced by CrossValidationApp::CrossValidate(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::FeatureFileIOPices::LoadFile(), CrossValidationApp::PrintSizeHistogram(), MLL::FeatureFileIOPices::SaveFile(), and CrossValidationApp::ValidationProcess().
FFLOAT MLL::FeatureVector::OrigSize () const inline
The value of Feature[0] before normalization.
Definition at line 128 of file FeatureVector.h.
void MLL::FeatureVector::PredictedClass (MLClassConstPtr _predictedClass) inline
Definition at line 87 of file FeatureVector.h.
Referenced by MLL::CrossValidationThreeWay::CreateProbabilityReport(), MLL::FeatureEncoder2::EncodeAExample(), MLL::FeatureEncoder::EncodeAImage(), MLL::FeatureFileIOPices::LoadFile(), and MLL::FeatureFileIOPices::SaveFile().
MLClassConstPtr MLL::FeatureVector::PredictedClass () const inline
Definition at line 129 of file FeatureVector.h.
const KKStr & FeatureVector::PredictedClassName () const
Definition at line 264 of file FeatureVector.cpp.
Referenced by MLL::FeatureFileIOPices::SaveFile().
void MLL::FeatureVector::Probability (FFLOAT _probability) inline
Assign a prediction probability to this example.
Definition at line 88 of file FeatureVector.h.
Referenced by MLL::CrossValidationThreeWay::CalculateThirdClassDecisiveProbability(), MLL::CrossValidationThreeWay::CreateDistanceReport(), MLL::CrossValidationThreeWay::CreateProbabilityReport(), MLL::FeatureFileIOPices::LoadFile(), MLL::FeatureVectorList::ProbabilityComparison::operator()(), MLL::FeatureVectorList::ProbabilityComparisonReversed::operator()(), and MLL::FeatureFileIOPices::SaveFile().
FFLOAT MLL::FeatureVector::Probability () const inline
The probability assigned by classifer to the predicted class.
Definition at line 131 of file FeatureVector.h.
void FeatureVector::ResetNumOfFeatures (int32 newNumOfFeatures)
Used to reallocate memory for feature data.
Definition at line 104 of file FeatureVector.cpp.
References KKU::endl(), featureData, numOfFeatures, KKU::osWaitForEnter(), and x.
Referenced by MLL::FeatureVectorList::ResetFileDesc(), and MLL::FeatureVectorList::ResetNumOfFeaturs().
float FeatureVector::TotalOfFeatureData () const
Returns the total of all Feature Attributes for this feature vector.
Definition at line 186 of file FeatureVector.cpp.
References featureData, NumOfFeatures(), and x.
Referenced by MLL::UsfCasCor::PredictClass(), MLL::UsfCasCor::PredictClassConfidences(), and MLL::UsfCasCor::PredictConfidences().
void MLL::FeatureVector::TrainWeight (float _trainWeight) inline
Assign a specific example a higher weight for training purposes.
The SVM will multiply the cost parameter by this amount when training the classifier for this specific example. This was introduced when we implemented BitReduction.
Definition at line 114 of file FeatureVector.h.
Referenced by MLL::FeatureEncoder::Compress(), MLL::BitReduction::compress(), MLL::FeatureEncoder2::EncodeAExample(), and MLL::FeatureEncoder::EncodeAImage().
float MLL::FeatureVector::TrainWeight () const inline
Definition at line 132 of file FeatureVector.h.
virtual const char* MLL::FeatureVector::UnderlyingClass () const inline virtual
Used by container classes such as 'FeatureVectorList'.
This way they can determine real underlyimg class.
Reimplemented in MLL::ImageFeatures.
Definition at line 153 of file FeatureVector.h.
Referenced by PicesInterface::PicesFeatureVectorList::PicesFeatureVectorList().
void MLL::FeatureVector::Validated (bool _validated) inline
Indicated wheather an expert has validated the class assignment.
Definition at line 118 of file FeatureVector.h.
bool MLL::FeatureVector::Validated () const inline
Definition at line 133 of file FeatureVector.h.
Member Data Documentation
FFLOAT* MLL::FeatureVector::featureData protected
Definition at line 159 of file FeatureVector.h.
Referenced by AddFeatureData(), AllocateFeatureDataArray(), FeatureData(), FeatureDataAlter(), FeatureDataConst(), FeatureDataValid(), FeatureVector(), MemoryConsumedEstimated(), operator==(), ResetNumOfFeatures(), TotalOfFeatureData(), and ~FeatureVector().
int32 MLL::FeatureVector::numOfFeatures protected
Definition at line 160 of file FeatureVector.h.
Referenced by AddFeatureData(), AllocateFeatureDataArray(), FeatureDataValid(), FeatureVector(), MemoryConsumedEstimated(), NumOfFeatures(), operator==(), and ResetNumOfFeatures().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/FeatureVector.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/FeatureVector.cpp