Pices: PicesInterface::PicesAbundanceCorrectionMatrix Class Reference
PicesInterface::PicesAbundanceCorrectionMatrix Class Reference
Assists in adjusting a Classifiers output for bias of a classifier.
#include <PicesAbundanceCorrectionMatrix.h>
Public Member Functions
PicesAbundanceCorrectionMatrix (PicesClassList^ _classes, PicesClass^ _otherClass, PicesRunLog^ _runLog)
Will constuct a instance from from the parameter file for '_configFileName'.
PicesAbundanceCorrectionMatrix (String^ _configFileName, PicesRunLog^ _runLog)
!PicesAbundanceCorrectionMatrix ()
~PicesAbundanceCorrectionMatrix ()
void AddIn (PicesAbundanceCorrectionMatrix^ matrix, PicesRunLog^ runLog)
PicesClassStatisticList^ AdjustClassificationCounts (PicesClassStatisticList^ inputCounts, PicesRunLog^ log)
void ComputeStatistics ()
computing probOfDetection and probOfFalseAlarm(Specifiity)
System::DateTime DateTimeComputed ()
PicesClassStatisticList^ LumpCounts (PicesClassStatisticList^ inputCounts)
void Prediction (PicesClass^ knownClass, PicesClass^ predClass, PicesRunLog^ log)
void PrintAdjustedResults (StreamWriter^ sw, PicesClassStatisticList^ classifiedCounts, PicesRunLog^ runLog)
void PrintConfusionMatrixTabDelimited (StreamWriter^ outFile)
array< float >^ ProbOfDetection ()
array< float >^ ProbOfFalseAlarm ()
void SaveForConfigFileName (String^ configFileName)
bool Valid ()
Detailed Description
Assists in adjusting a Classifiers output for bias of a classifier.
See the paper:
"Accurate automatic quantification of taxa-specific plankton abundance using dual classification with correction"
by: Qiao Hu, Cabell Davis
Date: 2006-01-11
http://darchive.mblwhoilibrary.org:8080/handle/1912/4501
This class uses the results of a n-fold cross validation to compute parameters that are used to adjust the results of a classification run. The application "AbundanceCorrectionStatsBuilder" will create a parameter file in the directory "${PicesHomeDir}\\DataFiles\\TrainingModels\\SaveFiles" that contains the parameters.
Definition at line 34 of file PicesAbundanceCorrectionMatrix.h.
Constructor & Destructor Documentation
PicesAbundanceCorrectionMatrix::PicesAbundanceCorrectionMatrix (PicesClassList^ _classes, PicesClass^ _otherClass, PicesRunLog^ _runLog)
Will constuct a instance from from the parameter file for '_configFileName'.
Parameters
[in] _configFileName The name of the BiasMatrix file will be derived from the configuration file name. Se the code for 'the term 'PicesAbundanceCorrectionMatrix' in PicesLibrary'.
[in,out] _runLog Logging file to use.
Definition at line 45 of file PicesAbundanceCorrectionMatrix.cpp.
References PicesInterface::PicesRunLog::Log(), PicesInterface::PicesClassList::ToMLClassConstList(), and PicesInterface::PicesClass::UnmanagedMLClass().
Referenced by ~PicesAbundanceCorrectionMatrix().
PicesAbundanceCorrectionMatrix::PicesAbundanceCorrectionMatrix (String^ _configFileName, PicesRunLog^ _runLog)
Definition at line 59 of file PicesAbundanceCorrectionMatrix.cpp.
References PicesInterface::PicesRunLog::Log(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
PicesAbundanceCorrectionMatrix::!PicesAbundanceCorrectionMatrix ()
Definition at line 69 of file PicesAbundanceCorrectionMatrix.cpp.
PicesAbundanceCorrectionMatrix::~PicesAbundanceCorrectionMatrix ()
Definition at line 76 of file PicesAbundanceCorrectionMatrix.cpp.
References PicesAbundanceCorrectionMatrix().
Member Function Documentation
void PicesAbundanceCorrectionMatrix::AddIn (PicesAbundanceCorrectionMatrix^ matrix, PicesRunLog^ runLog)
Definition at line 120 of file PicesAbundanceCorrectionMatrix.cpp.
References MLL::AbundanceCorrectionMatrix::AddIn(), and PicesInterface::PicesRunLog::Log().
PicesClassStatisticList PicesAbundanceCorrectionMatrix::AdjustClassificationCounts (PicesClassStatisticList^ inputCounts, PicesRunLog^ log)
Definition at line 177 of file PicesAbundanceCorrectionMatrix.cpp.
References PicesInterface::PicesRunLog::Log(), and PicesInterface::PicesClassStatisticList::ToUnmanagedClassStatisticList().
Referenced by PrintAdjustedResults().
void PicesAbundanceCorrectionMatrix::ComputeStatistics ()
computing probOfDetection and probOfFalseAlarm(Specifiity)
Definition at line 128 of file PicesAbundanceCorrectionMatrix.cpp.
References MLL::AbundanceCorrectionMatrix::ComputeStatistics().
System::DateTime PicesAbundanceCorrectionMatrix::DateTimeComputed ()
Definition at line 82 of file PicesAbundanceCorrectionMatrix.cpp.
References MLL::AbundanceCorrectionMatrix::DateTimeComputed(), and PicesInterface::PicesMethods::DateTimeKKUtoSystem().
PicesClassStatisticList PicesAbundanceCorrectionMatrix::LumpCounts (PicesClassStatisticList^ inputCounts)
Definition at line 163 of file PicesAbundanceCorrectionMatrix.cpp.
References MLL::AbundanceCorrectionMatrix::LumpCounts(), and PicesInterface::PicesClassStatisticList::ToUnmanagedClassStatisticList().
Referenced by PrintAdjustedResults().
void PicesAbundanceCorrectionMatrix::Prediction (PicesClass^ knownClass, PicesClass^ predClass, PicesRunLog^ log)
Definition at line 134 of file PicesAbundanceCorrectionMatrix.cpp.
References PicesInterface::PicesRunLog::Log(), MLL::AbundanceCorrectionMatrix::Prediction(), and PicesInterface::PicesClass::UnmanagedMLClass().
void PicesAbundanceCorrectionMatrix::PrintAdjustedResults (StreamWriter^ sw, PicesClassStatisticList^ classifiedCounts, PicesRunLog^ runLog)
Definition at line 194 of file PicesAbundanceCorrectionMatrix.cpp.
References AdjustClassificationCounts(), MLL::AbundanceCorrectionMatrix::DateTimeComputed(), PicesInterface::PicesMethods::DateTimeKKUtoSystem(), PicesInterface::PicesClassList::ExtractThreeTitleLines(), LumpCounts(), ProbOfDetection(), ProbOfFalseAlarm(), and PicesInterface::PicesClassStatisticList::ToPicesClassList().
void PicesAbundanceCorrectionMatrix::PrintConfusionMatrixTabDelimited (StreamWriter^ outFile)
Definition at line 143 of file PicesAbundanceCorrectionMatrix.cpp.
References MLL::AbundanceCorrectionMatrix::PrintConfusionMatrixTabDelimited().
array< float > PicesAbundanceCorrectionMatrix::ProbOfDetection ()
Definition at line 88 of file PicesAbundanceCorrectionMatrix.cpp.
References MLL::AbundanceCorrectionMatrix::ProbOfDetection(), and x.
Referenced by PrintAdjustedResults().
array< float > PicesAbundanceCorrectionMatrix::ProbOfFalseAlarm ()
Definition at line 100 of file PicesAbundanceCorrectionMatrix.cpp.
References MLL::AbundanceCorrectionMatrix::ProbOfFalseAlarm(), and x.
Referenced by PrintAdjustedResults().
void PicesAbundanceCorrectionMatrix::SaveForConfigFileName (String^ configFileName)
Definition at line 156 of file PicesAbundanceCorrectionMatrix.cpp.
References MLL::AbundanceCorrectionMatrix::SaveForConfigFileName(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
bool PicesAbundanceCorrectionMatrix::Valid ()
Definition at line 110 of file PicesAbundanceCorrectionMatrix.cpp.
References MLL::AbundanceCorrectionMatrix::Valid().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesAbundanceCorrectionMatrix.h
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesAbundanceCorrectionMatrix.cpp