Pices: SipperHardware::InstrumentDataFileManager Class Reference
SipperHardware::InstrumentDataFileManager Class Reference
#include <InstrumentDataFileManager.h>
Public Types
typedef KKU::int32 int32
typedef KKU::int64 int64
typedef KKU::uint32 uint32
typedef KKU::uint64 uint64
Public Member Functions
InstrumentDataFileManager ()
~InstrumentDataFileManager ()
void GetClosestInstrumentData (const KKStr &imageFileName, InstrumentDataPtr &instrumentData, volatile const bool &cancelFlag, RunLog &log)
VectorUlong GetScanLinesPerMeterProfile2 (const KKStr &sipperFileName, SipperFilePtr sipperFile, volatile bool &cancelFlag, RunLog &log)
VectorFloat GetVolumePerMeterProfile2 (const KKStr &sipperFileName, SipperFilePtr sipperFile, volatile bool &cancelFlag, RunLog &log)
Static Public Member Functions
static void FinalCleanUp ()
static InstrumentDataPtr GetClosestInstrumentData (const KKStr &imageFileName, volatile const bool &cancelFlag, RunLog &log)
static KKStr GetFullSipperFileName (const KKStr &rootName)
static InstrumentDataListPtr GetInstrumentDataForSipperFile (const KKStr &sipperFileName, SipperFilePtr sipperFile, bool forceReExtract, volatile bool &cancelFlag, RunLog &log)
static VectorKKStr GetListOfSipperFiles (RunLog &log)
Returns a list of all known SIPPER files on the local PC; each entry includes the file path.
static RasterSipperPtr GetOrigSipperImage (const KKStr &sipperFileRootName, KKU::uint64 byteOffset, uint32 topLeftRow, uint32 tooLeftCol, uint32 height, uint32 width, KKU::uchar connectedComponentDist, RunLog &log)
static VectorUlong GetScanLinesPerMeterProfile (const KKStr &sipperFileName, SipperFilePtr sipperFile, volatile bool &cancelFlag, RunLog &log)
static VectorFloat GetVolumePerMeterProfile (const KKStr &sipperFileName, SipperFilePtr sipperFile, volatile bool &cancelFlag, RunLog &log)
static void Initialize ()
static bool Initialized ()
static void InitializePop ()
static void InitializePush ()
static InstrumentDataListPtr ReExtractInstrumentDataForSipperFile (const KKStr &sipperFileName, SipperFilePtr sipperFile, volatile const bool &cancelFlag, RunLog &log)
static KKStr SipperFileRootNameFromSipperImageFileName (const KKStr &sipperFileName)
Detailed Description
Author
Kurt Kramer
 @author Kurt Kramer                                                                                        *
                                                                                                            *
 Developer:   Kurt Kramer                                                                                   *
 Date:        2007-10                                                                                       *
 Place:       Eastern Tropical Pacific (ETP)  aboard the Seward Johnson.                                    *
                                                                                                            *
 Purpose                                                                                                    *
 =======                                                                                                    *
 My purpose in life is to provide a means for getting instrument data for a specified Plankton image. Given *
 an image file name we can derive the original SIPPER file that it came from and the scan line from within  *
 this file where the image was extracted from.                                                              *
                                                                                                            *
 I will maintain InstrumentDataList objects; one for each SIPPER file that I am queried about.  When I get  *
 an image to look up If I do not already have its related 'InstrumentDataList' object I will:               *
    1) Look to see if a InstrumentData file already exists with this data.                                  *
    2) If no file available I will then go to the Original SIPPER file for the data and build a file that    *
       can be used the next time rather than scanning the whole SIPPER file.                                *
                                                                                                            *
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - *
                                                                                                            *
 HOW TO USE:                                                                                                *
 "InitializePush" -  Before using any functions call this static method.  It will create the necessary data *
                   structures needed.  Then for each SIPPER image file that you need Instrument data for    *
                   call the static method "GetClosestInstrumentData".                                       *
                                                                                                            *
 "InitializePop"  -  Before the application terminates call this static method to free up allocated memory. *
                                                                                                            *
 "GetClosestInstrumentData" - Call this static method to get the instrument data that is closest to the     *
                   SIPPER image file provided.                                                              *
                                                                                                            *
 "InitializePush"  and  "IniailizePop" replace "Initialize" and "CleanUp" respectively.   The "Push" and    *
                   "Pop" describe the additional functionality provided.  This way you no longer need to    *
                   worry if a caller has already initialized "IntrumenDdataFileNamager".                    *
                                                                                                            *
                                                                                                            *
 Sipper File Directories.                                                                                   *
 ========================                                                                                   *
 This module will automatically look in a default directory "%PicesHomeDir%\SipperFiles".  If you want it   *
 to search other directories for SipperFiles you need to create a text file "SipperDirectoryList.txt"       *
 in "%PicesHomeDir%\DataFiles\".  Create one text line for each additional SubDirectory structure that you  *
 want this module to search for SipperFiles.                                                                *
                                                                                                            *
Definition at line 93 of file InstrumentDataFileManager.h.
Member Typedef Documentation
typedef KKU::int32 SipperHardware::InstrumentDataFileManager::int32
Definition at line 96 of file InstrumentDataFileManager.h.
typedef KKU::int64 SipperHardware::InstrumentDataFileManager::int64
Definition at line 98 of file InstrumentDataFileManager.h.
typedef KKU::uint32 SipperHardware::InstrumentDataFileManager::uint32
Definition at line 97 of file InstrumentDataFileManager.h.
typedef KKU::uint64 SipperHardware::InstrumentDataFileManager::uint64
Definition at line 99 of file InstrumentDataFileManager.h.
Constructor & Destructor Documentation
InstrumentDataFileManager::InstrumentDataFileManager ()
Definition at line 42 of file InstrumentDataFileManager.cpp.
References KKU::GoalKeeper::EndBlock(), SipperHardware::SipperVariables::InstrumentDataFilesDir(), KKU::osCreateDirectoryPath(), SipperHardware::SipperVariables::PicesHomeDir(), and KKU::GoalKeeper::StartBlock().
Referenced by InitializePush().
InstrumentDataFileManager::~InstrumentDataFileManager ()
Definition at line 67 of file InstrumentDataFileManager.cpp.
References KKU::GoalKeeper::EndBlock(), and KKU::GoalKeeper::StartBlock().
Member Function Documentation
void InstrumentDataFileManager::FinalCleanUp () static
Definition at line 109 of file InstrumentDataFileManager.cpp.
References InitializePop().
void InstrumentDataFileManager::GetClosestInstrumentData (const KKStr & imageFileName, InstrumentDataPtr & instrumentData, volatile const bool & cancelFlag, RunLog & log)
Definition at line 258 of file InstrumentDataFileManager.cpp.
References KKU::GoalKeeper::EndBlock(), KKU::endl(), KKU::RunLog::Level(), KKU::KKStr::LocateLastOccurrence(), KKU::Max(), KKU::osGetRootName(), SipperHardware::InstrumentDataList::SearchForNearestScanLine(), SipperHardware::InstrumentDataList::SipperFileName(), KKU::GoalKeeper::StartBlock(), KKU::KKStr::SubStrPart(), KKU::KKStr::ToLong(), and x.
Referenced by GetClosestInstrumentData().
InstrumentDataPtr InstrumentDataFileManager::GetClosestInstrumentData (const KKStr & imageFileName, volatile const bool & cancelFlag, RunLog & log) static
Definition at line 242 of file InstrumentDataFileManager.cpp.
References GetClosestInstrumentData().
KKStr InstrumentDataFileManager::GetFullSipperFileName (const KKStr & rootName) static
Definition at line 168 of file InstrumentDataFileManager.cpp.
References KKU::GoalKeeper::EndBlock(), and KKU::GoalKeeper::StartBlock().
InstrumentDataListPtr InstrumentDataFileManager::GetInstrumentDataForSipperFile (const KKStr & sipperFileName, SipperFilePtr sipperFile, bool forceReExtract, volatile bool & cancelFlag, RunLog & log) static
Definition at line 429 of file InstrumentDataFileManager.cpp.
References Initialize(), and KKU::osGetRootName().
VectorKKStr InstrumentDataFileManager::GetListOfSipperFiles (RunLog & log) static
Returns a list of all known SIPPER files on the local PC; each entry includes the file path.
Definition at line 198 of file InstrumentDataFileManager.cpp.
References KKU::GoalKeeper::EndBlock(), Initialize(), and KKU::GoalKeeper::StartBlock().
Referenced by SipperHardware::SipperFileList::GetListOfSipperFilesWeCanFind().
RasterSipperPtr InstrumentDataFileManager::GetOrigSipperImage (const KKStr & sipperFileRootName, KKU::uint64 byteOffset, uint32 topLeftRow, uint32 tooLeftCol, uint32 height, uint32 width, KKU::uchar connectedComponentDist, RunLog & log) static
Parameters
connectedComponentDist Siize of structure used by Connected Component Analysis
Definition at line 643 of file InstrumentDataFileManager.cpp.
References SipperHardware::SipperBuff::CreateSipperBuff(), SipperHardware::SipperBuff::CurRow(), KKU::KKStr::Empty(), SipperHardware::SipperBuff::Eof(), SipperHardware::SipperBuff::GetNextLine(), KKU::Raster::Green(), Initialize(), KKU::Raster::ReduceToMostCompleteBlob(), and SipperHardware::SipperBuff::SkipToScanLine().
VectorUlong InstrumentDataFileManager::GetScanLinesPerMeterProfile (const KKStr & sipperFileName, SipperFilePtr sipperFile, volatile bool & cancelFlag, RunLog & log) static
Definition at line 627 of file InstrumentDataFileManager.cpp.
References GetScanLinesPerMeterProfile2(), and Initialize().
VectorUlong InstrumentDataFileManager::GetScanLinesPerMeterProfile2 (const KKStr & sipperFileName, SipperFilePtr sipperFile, volatile bool & cancelFlag, RunLog & log)
Definition at line 584 of file InstrumentDataFileManager.cpp.
References SipperHardware::InstrumentDataList::GetScanLinesPerMeterProfile(), KKU::osGetRootName(), and SipperHardware::InstrumentDataList::SipperFileName().
Referenced by GetScanLinesPerMeterProfile().
VectorFloat InstrumentDataFileManager::GetVolumePerMeterProfile (const KKStr & sipperFileName, SipperFilePtr sipperFile, volatile bool & cancelFlag, RunLog & log) static
Definition at line 612 of file InstrumentDataFileManager.cpp.
References GetVolumePerMeterProfile2(), and Initialize().
VectorFloat InstrumentDataFileManager::GetVolumePerMeterProfile2 (const KKStr & sipperFileName, SipperFilePtr sipperFile, volatile bool & cancelFlag, RunLog & log)
Definition at line 556 of file InstrumentDataFileManager.cpp.
References SipperHardware::InstrumentDataList::GetVolumePerMeterProfile(), KKU::osGetRootName(), and SipperHardware::InstrumentDataList::SipperFileName().
Referenced by GetVolumePerMeterProfile().
void InstrumentDataFileManager::Initialize () static
Definition at line 102 of file InstrumentDataFileManager.cpp.
References InitializePush().
Referenced by GetInstrumentDataForSipperFile(), GetListOfSipperFiles(), GetOrigSipperImage(), GetScanLinesPerMeterProfile(), GetVolumePerMeterProfile(), and ReExtractInstrumentDataForSipperFile().
bool InstrumentDataFileManager::Initialized () static
Definition at line 121 of file InstrumentDataFileManager.cpp.
void InstrumentDataFileManager::InitializePop () static
Definition at line 149 of file InstrumentDataFileManager.cpp.
References KKU::GoalKeeper::EndBlock(), and KKU::GoalKeeper::StartBlock().
Referenced by FinalCleanUp().
void InstrumentDataFileManager::InitializePush () static
Definition at line 128 of file InstrumentDataFileManager.cpp.
References KKU::GoalKeeper::EndBlock(), InstrumentDataFileManager(), and KKU::GoalKeeper::StartBlock().
Referenced by Initialize().
InstrumentDataListPtr InstrumentDataFileManager::ReExtractInstrumentDataForSipperFile (const KKStr & sipperFileName, SipperFilePtr sipperFile, volatile const bool & cancelFlag, RunLog & log) static
Definition at line 448 of file InstrumentDataFileManager.cpp.
References Initialize(), and KKU::osGetRootName().
KKStr InstrumentDataFileManager::SipperFileRootNameFromSipperImageFileName (const KKStr & sipperFileName) static
Definition at line 222 of file InstrumentDataFileManager.cpp.
References KKU::KKStr::LocateLastOccurrence(), KKU::osGetRootName(), KKU::KKStr::SubStrPart(), and x.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/InstrumentDataFileManager.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/InstrumentDataFileManager.cpp