Pices: SipperFile.DataRowList Class Reference
SipperFile.DataRowList Class Reference
Summary description for DataRowList.
Public Types
enum DataOrder { DataOrder.NoOrder, DataOrder.TimeOrder, DataOrder.DepthOrder }
Public Member Functions
DataRowList ()
DataRowList (string _fileName, StreamWriter logFile)
DataRowList (SipperConfigRec sipperConfigRec, StreamWriter logFile)
virtual int Add (InstrumentData row)
void CalcMinMaxValues (DateTime startTime, DateTime endTime)
InstrumentData CurrentDataRow ()
DataOrder CurrentOrder ()
float DepthMax ()
float DepthMin ()
void Dispose ()
int GetByTimeGreaterOrEqual (DateTime t)
float[] MaxValues ()
float[] MinValues ()
void Save (string _fileName)
void SortByDepth ()
void SortByTime ()
DateTime TimeMax ()
DateTime TimeMin ()
Detailed Description
Summary description for DataRowList.
Definition at line 13 of file DataRowList.cs.
Member Enumeration Documentation
enum SipperFile.DataRowList.DataOrder
Enumerator
NoOrder
TimeOrder
DepthOrder
Definition at line 15 of file DataRowList.cs.
Constructor & Destructor Documentation
SipperFile.DataRowList.DataRowList () inline
Definition at line 49 of file DataRowList.cs.
SipperFile.DataRowList.DataRowList (string _fileName, StreamWriter logFile) inline
Definition at line 57 of file DataRowList.cs.
SipperFile.DataRowList.DataRowList (SipperConfigRec sipperConfigRec, StreamWriter logFile) inline
Definition at line 67 of file DataRowList.cs.
Member Function Documentation
virtual int SipperFile.DataRowList.Add (InstrumentData row) inline virtual
Definition at line 349 of file DataRowList.cs.
References SipperFile.InstrumentData.Depth(), SipperFile.InstrumentData.Time, and SipperFile.InstrumentData.WriteLine().
void SipperFile.DataRowList.CalcMinMaxValues (DateTime startTime, DateTime endTime) inline
Definition at line 390 of file DataRowList.cs.
References SipperFile.InstrumentData.Data(), SipperFile.InstrumentData.NumDataFields(), SipperFile.InstrumentData.Time, and x.
InstrumentData SipperFile.DataRowList.CurrentDataRow () inline
Definition at line 375 of file DataRowList.cs.
DataOrder SipperFile.DataRowList.CurrentOrder () inline
Definition at line 113 of file DataRowList.cs.
float SipperFile.DataRowList.DepthMax () inline
Definition at line 42 of file DataRowList.cs.
float SipperFile.DataRowList.DepthMin () inline
Definition at line 41 of file DataRowList.cs.
void SipperFile.DataRowList.Dispose () inline
Definition at line 327 of file DataRowList.cs.
References x.
int SipperFile.DataRowList.GetByTimeGreaterOrEqual (DateTime t) inline
Definition at line 232 of file DataRowList.cs.
References SipperFile.DataRowList.SortByTime(), and SipperFile.InstrumentData.Time.
float [] SipperFile.DataRowList.MaxValues () inline
Definition at line 31 of file DataRowList.cs.
float [] SipperFile.DataRowList.MinValues () inline
Definition at line 30 of file DataRowList.cs.
void SipperFile.DataRowList.Save (string _fileName) inline
Definition at line 297 of file DataRowList.cs.
References SipperFile.InstrumentData.WriteFieldList(), SipperFile.InstrumentData.WriteLine(), and x.
void SipperFile.DataRowList.SortByDepth () inline
Definition at line 479 of file DataRowList.cs.
void SipperFile.DataRowList.SortByTime () inline
Definition at line 469 of file DataRowList.cs.
Referenced by SipperFile.DataRowList.GetByTimeGreaterOrEqual().
DateTime SipperFile.DataRowList.TimeMax () inline
Definition at line 45 of file DataRowList.cs.
DateTime SipperFile.DataRowList.TimeMin () inline
Definition at line 44 of file DataRowList.cs.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperFile/DataRowList.cs