var hierarchy =
[
    [ "ArrayList", null, [
      [ "SipperFile.DataRowList", "class_sipper_file_1_1_data_row_list.html", null ],
      [ "SipperFile.InstrumentDataList", "class_sipper_file_1_1_instrument_data_list.html", null ]
    ] ],
    [ "MLL::BitReduction::FeatureVar", "struct_bit_reduction_1_1_feature_var.html", null ],
    [ "MLL::BitReduction::FeatureVarComparrison", "class_bit_reduction_1_1_feature_var_comparrison.html", null ],
    [ "KKU::BmpImage::Bmp1BitRec", "struct_bmp_image_1_1_bmp1_bit_rec.html", null ],
    [ "KKU::BmpImage::Bmp4BitRecs", "struct_bmp_image_1_1_bmp4_bit_recs.html", null ],
    [ "KKU::BmpImage::BMP_24BitPixel", "struct_bmp_image_1_1_b_m_p__24_bit_pixel.html", null ],
    [ "KKU::BmpImage::CodedPixels", "class_bmp_image_1_1_coded_pixels.html", null ],
    [ "KKU::BmpImage::CodePair", "struct_bmp_image_1_1_code_pair.html", null ],
    [ "KKU::BmpImage::DWordParts", "union_bmp_image_1_1_d_word_parts.html", null ],
    [ "KKU::BmpImage::LongParts", "union_bmp_image_1_1_long_parts.html", null ],
    [ "KKU::BmpImage::PalletBuilder", "class_bmp_image_1_1_pallet_builder.html", null ],
    [ "KKU::BmpImage::PalletBuilder::RGBQUAD_Pred", "class_bmp_image_1_1_pallet_builder_1_1_r_g_b_q_u_a_d___pred.html", null ],
    [ "KKU::BmpImage::WordParts", "union_bmp_image_1_1_word_parts.html", null ],
    [ "CDialog", null, [
      [ "CAboutDlg", "class_c_about_dlg.html", null ],
      [ "CImageExtractionWindowsDlg", "class_c_image_extraction_windows_dlg.html", null ]
    ] ],
    [ "MLL::ClassProbList::ProbabilityComparer", "class_class_prob_list_1_1_probability_comparer.html", null ],
    [ "MLL::ClassProbList::VotesComparer", "class_class_prob_list_1_1_votes_comparer.html", null ],
    [ "MLL::ClassStatisticList::ClassStatisticSortComparrison", "class_class_statistic_list_1_1_class_statistic_sort_comparrison.html", null ],
    [ "MLL::ClassStatisticList::ClassStatSortByCount", "class_class_statistic_list_1_1_class_stat_sort_by_count.html", null ],
    [ "Configuration", null, [
      [ "MLL::TrainingConfiguration2", "class_m_l_l_1_1_training_configuration2.html", null ]
    ] ],
    [ "CrossValidationApp", "class_cross_validation_app.html", null ],
    [ "CrossValidationRun", "class_cross_validation_run.html", null ],
    [ "CrossValidationSortByAccuracy", "class_cross_validation_sort_by_accuracy.html", null ],
    [ "CrossValidationSortBySupportPoints", "class_cross_validation_sort_by_support_points.html", null ],
    [ "CrossValidationSortByTrainTime", "class_cross_validation_sort_by_train_time.html", null ],
    [ "CWinApp", null, [
      [ "CImageExtractionWindowsApp", "class_c_image_extraction_windows_app.html", null ]
    ] ],
    [ "MLL::DataBaseImageList::SpatialComparison", "class_data_base_image_list_1_1_spatial_comparison.html", null ],
    [ "MLL::DataBaseLogEntryList::ProgCodeComparison", "class_data_base_log_entry_list_1_1_prog_code_comparison.html", null ],
    [ "DataGridViewCell", null, [
      [ "PicesCommander.ThumbNailImageCell", "class_pices_commander_1_1_thumb_nail_image_cell.html", null ]
    ] ],
    [ "DataGridViewColumn", null, [
      [ "PicesCommander.ThumbNailImageColumn", "class_pices_commander_1_1_thumb_nail_image_column.html", null ]
    ] ],
    [ "MLL::FeatureFileIODstWeb::AttrDescLine", "class_feature_file_i_o_dst_web_1_1_attr_desc_line.html", null ],
    [ "MLL::FeatureFileIODstWeb::AttrDescLineComparator", "class_feature_file_i_o_dst_web_1_1_attr_desc_line_comparator.html", null ],
    [ "MLL::FeatureVectorList::BreakTieComparison", "class_feature_vector_list_1_1_break_tie_comparison.html", null ],
    [ "MLL::FeatureVectorList::BreakTieComparisonReversed", "class_feature_vector_list_1_1_break_tie_comparison_reversed.html", null ],
    [ "MLL::FeatureVectorList::ClassNameComparrison", "class_feature_vector_list_1_1_class_name_comparrison.html", null ],
    [ "MLL::FeatureVectorList::ClassNameComparrisonReversed", "class_feature_vector_list_1_1_class_name_comparrison_reversed.html", null ],
    [ "MLL::FeatureVectorList::ImageFileNameComparison", "class_feature_vector_list_1_1_image_file_name_comparison.html", null ],
    [ "MLL::FeatureVectorList::ImageFileNameComparisonReversed", "class_feature_vector_list_1_1_image_file_name_comparison_reversed.html", null ],
    [ "MLL::FeatureVectorList::ProbabilityComparison", "class_feature_vector_list_1_1_probability_comparison.html", null ],
    [ "MLL::FeatureVectorList::ProbabilityComparisonReversed", "class_feature_vector_list_1_1_probability_comparison_reversed.html", null ],
    [ "MLL::FeatureVectorList::RootNameComparrison", "class_feature_vector_list_1_1_root_name_comparrison.html", null ],
    [ "MLL::FeatureVectorList::RootNameComparrisonReversed", "class_feature_vector_list_1_1_root_name_comparrison_reversed.html", null ],
    [ "Form", null, [
      [ "PicesCommander.AboutBox", "class_pices_commander_1_1_about_box.html", null ],
      [ "PicesCommander.AssignSelectedImagesToGroup", "class_pices_commander_1_1_assign_selected_images_to_group.html", null ],
      [ "PicesCommander.ChartAbundanceByDeployment", "class_pices_commander_1_1_chart_abundance_by_deployment.html", null ],
      [ "PicesCommander.ChartAbundancePredictedAndValidated", "class_pices_commander_1_1_chart_abundance_predicted_and_validated.html", null ],
      [ "PicesCommander.ChartDistribution", "class_pices_commander_1_1_chart_distribution.html", null ],
      [ "PicesCommander.ChartGPS", "class_pices_commander_1_1_chart_g_p_s.html", null ],
      [ "PicesCommander.ChartHorizontalProfile", "class_pices_commander_1_1_chart_horizontal_profile.html", null ],
      [ "PicesCommander.ClassDepthProfileChart", "class_pices_commander_1_1_class_depth_profile_chart.html", null ],
      [ "PicesCommander.ClassificationStatus", "class_pices_commander_1_1_classification_status.html", null ],
      [ "PicesCommander.ClassMaintenance", "class_pices_commander_1_1_class_maintenance.html", null ],
      [ "PicesCommander.CreateFeatureSelectionDataSets", "class_pices_commander_1_1_create_feature_selection_data_sets.html", null ],
      [ "PicesCommander.Harvester", "class_pices_commander_1_1_harvester.html", null ],
      [ "PicesCommander.ImportGroupAssignments", "class_pices_commander_1_1_import_group_assignments.html", null ],
      [ "PicesCommander.ImportValidatdClass", "class_pices_commander_1_1_import_validatd_class.html", null ],
      [ "PicesCommander.InstrumentDataByDeploymentProfile", "class_pices_commander_1_1_instrument_data_by_deployment_profile.html", null ],
      [ "PicesCommander.PicesCommander", "class_pices_commander_1_1_pices_commander.html", null ],
      [ "PicesCommander.ReconcileImagesToDataBase", "class_pices_commander_1_1_reconcile_images_to_data_base.html", null ],
      [ "PicesCommander.SaveActiveTrainingModelFeatureData", "class_pices_commander_1_1_save_active_training_model_feature_data.html", null ],
      [ "PicesCommander.SaveFeatureData", "class_pices_commander_1_1_save_feature_data.html", null ],
      [ "PicesCommander.SaveImagesToDisk", "class_pices_commander_1_1_save_images_to_disk.html", null ],
      [ "PicesCommander.SaveImagesToDisk2", "class_pices_commander_1_1_save_images_to_disk2.html", null ],
      [ "PicesCommander.SavePlanktonData", "class_pices_commander_1_1_save_plankton_data.html", null ],
      [ "PicesCommander.SipperInstrumentDataExtraction", "class_pices_commander_1_1_sipper_instrument_data_extraction.html", null ],
      [ "PicesCommander.SpatialAnalysis", "class_pices_commander_1_1_spatial_analysis.html", null ],
      [ "PicesCommander.TrainingModelCreateFromDirectory", "class_pices_commander_1_1_training_model_create_from_directory.html", null ],
      [ "PicesCommander.VerifyImagesDeletion", "class_pices_commander_1_1_verify_images_deletion.html", null ],
      [ "SipperFile.CruiseDialog", "class_sipper_file_1_1_cruise_dialog.html", null ],
      [ "SipperFile.CruiseMaintenance", "class_sipper_file_1_1_cruise_maintenance.html", null ],
      [ "SipperFile.DataRowListLoadStatus", "class_sipper_file_1_1_data_row_list_load_status.html", null ],
      [ "SipperFile.DeploymentDialog", "class_sipper_file_1_1_deployment_dialog.html", null ],
      [ "SipperFile.DisplayPicesImages", "class_sipper_file_1_1_display_pices_images.html", null ],
      [ "SipperFile.FeatureDataDisplay", "class_sipper_file_1_1_feature_data_display.html", null ],
      [ "SipperFile.GroupMaintenance", "class_sipper_file_1_1_group_maintenance.html", null ],
      [ "SipperFile.ImageEditor", "class_sipper_file_1_1_image_editor.html", null ],
      [ "SipperFile.ImageViewer", "class_sipper_file_1_1_image_viewer.html", null ],
      [ "SipperFile.InstrumentDataFieldSelect", "class_sipper_file_1_1_instrument_data_field_select.html", null ],
      [ "SipperFile.LogEntryViewer", "class_sipper_file_1_1_log_entry_viewer.html", null ],
      [ "SipperFile.PredictionBreakDownDisplay", "class_sipper_file_1_1_prediction_break_down_display.html", null ],
      [ "SipperFile.PredictionBreakDownDisplayDual", "class_sipper_file_1_1_prediction_break_down_display_dual.html", null ],
      [ "SipperFile.SaveRawCTDData", "class_sipper_file_1_1_save_raw_c_t_d_data.html", null ],
      [ "SipperFile.SelectAInstrumentDataField", "class_sipper_file_1_1_select_a_instrument_data_field.html", null ],
      [ "SipperFile.SelectAPicesClass", "class_sipper_file_1_1_select_a_pices_class.html", null ],
      [ "SipperFile.SipperFileDialog", "class_sipper_file_1_1_sipper_file_dialog.html", null ],
      [ "SipperFile.StationDialog", "class_sipper_file_1_1_station_dialog.html", null ],
      [ "SipperFile.TimePlot", "class_sipper_file_1_1_time_plot.html", null ],
      [ "SipperFile.TrainingModelMaintenance", "class_sipper_file_1_1_training_model_maintenance.html", null ],
      [ "SipperFile.TrainingModelStatus", "class_sipper_file_1_1_training_model_status.html", null ]
    ] ],
    [ "ImageExtractionManager::ExtractedImage", "class_image_extraction_manager_1_1_extracted_image.html", null ],
    [ "ImageExtractionManager::ExtractionManager", "class_image_extraction_manager_1_1_extraction_manager.html", null ],
    [ "ImageExtractionManager::ExtractionManagerStats", "class_image_extraction_manager_1_1_extraction_manager_stats.html", null ],
    [ "ImageExtractionManager::ExtractionParms", "class_image_extraction_manager_1_1_extraction_parms.html", null ],
    [ "ImageExtractionManager::ImageExtractionThread", "class_image_extraction_manager_1_1_image_extraction_thread.html", [
      [ "ImageExtractionManager::DataBaseUpdateThread", "class_image_extraction_manager_1_1_data_base_update_thread.html", null ],
      [ "ImageExtractionManager::FrameExtractorThread", "class_image_extraction_manager_1_1_frame_extractor_thread.html", null ],
      [ "ImageExtractionManager::FrameProcessorThread", "class_image_extraction_manager_1_1_frame_processor_thread.html", null ]
    ] ],
    [ "ImageExtractionManager::LogicalFrame", "class_image_extraction_manager_1_1_logical_frame.html", null ],
    [ "ImageExtractionManager::LogicalFrameBlob", "class_image_extraction_manager_1_1_logical_frame_blob.html", null ],
    [ "ImageExtractionManager::LogicalFrameQueue", "class_image_extraction_manager_1_1_logical_frame_queue.html", null ],
    [ "ImageExtractionManager::SipperImage", "class_image_extraction_manager_1_1_sipper_image.html", null ],
    [ "ImageExtractionManager::SipperThread", "class_image_extraction_manager_1_1_sipper_thread.html", null ],
    [ "JobManagment::Job", "class_job_managment_1_1_job.html", [
      [ "JobManagment::JobManager", "class_job_managment_1_1_job_manager.html", null ]
    ] ],
    [ "KKQueue", null, [
      [ "MLL::BitReduction::FeatureVarList", "class_bit_reduction_1_1_feature_var_list.html", null ],
      [ "JobManagment::JobList", "class_job_managment_1_1_job_list.html", null ],
      [ "JobManagment::JobManagerList", "class_job_managment_1_1_job_manager_list.html", null ],
      [ "KKU::BlobList", "class_k_k_u_1_1_blob_list.html", null ],
      [ "KKU::Configuration::ConfSectionList", "class_k_k_u_1_1_configuration_1_1_conf_section_list.html", null ],
      [ "KKU::Configuration::SettingList", "class_k_k_u_1_1_configuration_1_1_setting_list.html", null ],
      [ "KKU::KKStrList", "class_k_k_u_1_1_k_k_str_list.html", null ],
      [ "KKU::KKThreadList", "class_k_k_u_1_1_k_k_thread_list.html", null ],
      [ "KKU::PointList", "class_k_k_u_1_1_point_list.html", null ],
      [ "KKU::RasterList", "class_k_k_u_1_1_raster_list.html", null ],
      [ "KKU::RasterSipperList", "class_k_k_u_1_1_raster_sipper_list.html", null ],
      [ "MLL::AttributeList", "class_m_l_l_1_1_attribute_list.html", null ],
      [ "MLL::BinaryClassParmsList", "class_m_l_l_1_1_binary_class_parms_list.html", null ],
      [ "MLL::ClassProbList", "class_m_l_l_1_1_class_prob_list.html", null ],
      [ "MLL::ClassStatisticList", "class_m_l_l_1_1_class_statistic_list.html", null ],
      [ "MLL::ConfussionMatrix2List", "class_m_l_l_1_1_confussion_matrix2_list.html", null ],
      [ "MLL::DataBaseGpsDataList", "class_m_l_l_1_1_data_base_gps_data_list.html", null ],
      [ "MLL::DataBaseImageEntryList", "class_m_l_l_1_1_data_base_image_entry_list.html", null ],
      [ "MLL::DataBaseImageGroupEntryList", "class_m_l_l_1_1_data_base_image_group_entry_list.html", null ],
      [ "MLL::DataBaseImageGroupList", "class_m_l_l_1_1_data_base_image_group_list.html", null ],
      [ "MLL::DataBaseImageList", "class_m_l_l_1_1_data_base_image_list.html", null ],
      [ "MLL::DataBaseImageValidatedEntryList", "class_m_l_l_1_1_data_base_image_validated_entry_list.html", null ],
      [ "MLL::DataBaseLogEntryList", "class_m_l_l_1_1_data_base_log_entry_list.html", null ],
      [ "MLL::DataBaseServerList", "class_m_l_l_1_1_data_base_server_list.html", null ],
      [ "MLL::DuplicateImageList", "class_m_l_l_1_1_duplicate_image_list.html", null ],
      [ "MLL::FeatureEncoder2::FeatureVar2List", "class_m_l_l_1_1_feature_encoder2_1_1_feature_var2_list.html", null ],
      [ "MLL::FeatureVectorList", "class_m_l_l_1_1_feature_vector_list.html", [
        [ "MLL::ImageFeaturesList", "class_m_l_l_1_1_image_features_list.html", null ]
      ] ],
      [ "MLL::FileDescList", "class_m_l_l_1_1_file_desc_list.html", null ],
      [ "MLL::MLClassList", "class_m_l_l_1_1_m_l_class_list.html", null ],
      [ "MLL::TrainingClassList", "class_m_l_l_1_1_training_class_list.html", null ],
      [ "MLL::TrainingConfiguration2List", "class_m_l_l_1_1_training_configuration2_list.html", null ],
      [ "SipperHardware::GPSDataPointList", "class_sipper_hardware_1_1_g_p_s_data_point_list.html", null ],
      [ "SipperHardware::InstrumentDataList", "class_sipper_hardware_1_1_instrument_data_list.html", null ],
      [ "SipperHardware::InstrumentDataMeansList", "class_sipper_hardware_1_1_instrument_data_means_list.html", null ],
      [ "SipperHardware::SipperCruiseList", "class_sipper_hardware_1_1_sipper_cruise_list.html", null ],
      [ "SipperHardware::SipperDeploymentList", "class_sipper_hardware_1_1_sipper_deployment_list.html", null ],
      [ "SipperHardware::SipperFileList", "class_sipper_hardware_1_1_sipper_file_list.html", null ],
      [ "SipperHardware::SipperStationList", "class_sipper_hardware_1_1_sipper_station_list.html", null ],
      [ "MLL::SizeDistribution::ClassTotalsList", "class_size_distribution_1_1_class_totals_list.html", null ]
    ] ],
    [ "KKQueueConst", null, [
      [ "MLL::MLClassConstList", "class_m_l_l_1_1_m_l_class_const_list.html", null ]
    ] ],
    [ "KKU::KKStrList::StringComparison", "class_k_k_str_list_1_1_string_comparison.html", null ],
    [ "KKU::Application", "class_k_k_u_1_1_application.html", null ],
    [ "KKU::Atom", "class_k_k_u_1_1_atom.html", null ],
    [ "KKU::BITMAPFILEHEADER", "struct_k_k_u_1_1_b_i_t_m_a_p_f_i_l_e_h_e_a_d_e_r.html", null ],
    [ "KKU::BITMAPINFOHEADER", "struct_k_k_u_1_1_b_i_t_m_a_p_i_n_f_o_h_e_a_d_e_r.html", null ],
    [ "KKU::BitString", "class_k_k_u_1_1_bit_string.html", null ],
    [ "KKU::Blob", "class_k_k_u_1_1_blob.html", null ],
    [ "KKU::BmpImage", "class_k_k_u_1_1_bmp_image.html", null ],
    [ "KKU::Chart", "class_k_k_u_1_1_chart.html", null ],
    [ "KKU::Chart::PlotPoint", "class_k_k_u_1_1_chart_1_1_plot_point.html", null ],
    [ "KKU::Chart::Series", "class_k_k_u_1_1_chart_1_1_series.html", null ],
    [ "KKU::Chart::XLabel", "class_k_k_u_1_1_chart_1_1_x_label.html", null ],
    [ "KKU::CmdLineExpander", "class_k_k_u_1_1_cmd_line_expander.html", null ],
    [ "KKU::Compressor", "class_k_k_u_1_1_compressor.html", null ],
    [ "KKU::Configuration", "class_k_k_u_1_1_configuration.html", null ],
    [ "KKU::Configuration::ConfSection", "class_k_k_u_1_1_configuration_1_1_conf_section.html", null ],
    [ "KKU::Configuration::Setting", "class_k_k_u_1_1_configuration_1_1_setting.html", null ],
    [ "KKU::ContourFollower", "class_k_k_u_1_1_contour_follower.html", null ],
    [ "KKU::ConvexHull", "class_k_k_u_1_1_convex_hull.html", null ],
    [ "KKU::DateTime", "class_k_k_u_1_1_date_time.html", null ],
    [ "KKU::DateType", "class_k_k_u_1_1_date_type.html", null ],
    [ "KKU::GlobalGoalKeeper", "class_k_k_u_1_1_global_goal_keeper.html", null ],
    [ "KKU::GoalKeeper", "class_k_k_u_1_1_goal_keeper.html", null ],
    [ "KKU::HashTable< Entry >", "class_k_k_u_1_1_hash_table.html", null ],
    [ "KKU::Histogram", "class_k_k_u_1_1_histogram.html", null ],
    [ "KKU::HTMLReport", "class_k_k_u_1_1_h_t_m_l_report.html", null ],
    [ "KKU::ImageDirTree", "class_k_k_u_1_1_image_dir_tree.html", null ],
    [ "KKU::Iterator< Entry, CompareNodes, KeyType >", "class_k_k_u_1_1_iterator.html", null ],
    [ "KKU::KK_DFT< DftType >", "class_k_k_u_1_1_k_k___d_f_t.html", null ],
    [ "KKU::KK_DFT2D< DftType >", "class_k_k_u_1_1_k_k___d_f_t2_d.html", null ],
    [ "KKU::KKStr", "class_k_k_u_1_1_k_k_str.html", null ],
    [ "KKU::KKStrListIndexed", "class_k_k_u_1_1_k_k_str_list_indexed.html", null ],
    [ "KKU::KKStrMatrix", "class_k_k_u_1_1_k_k_str_matrix.html", null ],
    [ "KKU::KKStrParser", "class_k_k_u_1_1_k_k_str_parser.html", null ],
    [ "KKU::KKThread", "class_k_k_u_1_1_k_k_thread.html", [
      [ "KKU::KKThreadManager", "class_k_k_u_1_1_k_k_thread_manager.html", null ]
    ] ],
    [ "KKU::Matrix", "class_k_k_u_1_1_matrix.html", null ],
    [ "KKU::MovDir", "struct_k_k_u_1_1_mov_dir.html", null ],
    [ "KKU::MsgQueue", "class_k_k_u_1_1_msg_queue.html", null ],
    [ "KKU::PixelValue", "class_k_k_u_1_1_pixel_value.html", null ],
    [ "KKU::Point", "class_k_k_u_1_1_point.html", null ],
    [ "KKU::RandomNumGenerator", "class_k_k_u_1_1_random_num_generator.html", null ],
    [ "KKU::Raster", "class_k_k_u_1_1_raster.html", [
      [ "KKU::RasterSipper", "class_k_k_u_1_1_raster_sipper.html", null ]
    ] ],
    [ "KKU::RasterBuffer", "class_k_k_u_1_1_raster_buffer.html", null ],
    [ "KKU::RBnode< Entry >", "class_k_k_u_1_1_r_bnode.html", null ],
    [ "KKU::RBTree< Entry, CompareNodes, KeyType >", "class_k_k_u_1_1_r_b_tree.html", null ],
    [ "KKU::RGBQUAD", "struct_k_k_u_1_1_r_g_b_q_u_a_d.html", null ],
    [ "KKU::Row", "class_k_k_u_1_1_row.html", null ],
    [ "KKU::RunLog", "class_k_k_u_1_1_run_log.html", null ],
    [ "KKU::SegmentorOTSU", "class_k_k_u_1_1_segmentor_o_t_s_u.html", null ],
    [ "KKU::SimpleCompressor", "class_k_k_u_1_1_simple_compressor.html", null ],
    [ "KKU::Sobel", "class_k_k_u_1_1_sobel.html", null ],
    [ "KKU::TimeType", "class_k_k_u_1_1_time_type.html", null ],
    [ "KKU::TokenBuffer", "class_k_k_u_1_1_token_buffer.html", [
      [ "KKU::TokenBufferStr", "class_k_k_u_1_1_token_buffer_str.html", null ],
      [ "KKU::TokenBufferStream", "class_k_k_u_1_1_token_buffer_stream.html", null ]
    ] ],
    [ "KKU::Tokenizer", "class_k_k_u_1_1_tokenizer.html", null ],
    [ "KKU::WordFormat32Bits", "union_k_k_u_1_1_word_format32_bits.html", null ],
    [ "KKU::XmlAttribute", "class_k_k_u_1_1_xml_attribute.html", null ],
    [ "KKU::XmlStream", "class_k_k_u_1_1_xml_stream.html", null ],
    [ "KKU::XmlTag", "class_k_k_u_1_1_xml_tag.html", null ],
    [ "KKU::XmlToken", "class_k_k_u_1_1_xml_token.html", [
      [ "KKU::XmlContent", "class_k_k_u_1_1_xml_content.html", null ],
      [ "KKU::XmlElement", "class_k_k_u_1_1_xml_element.html", null ]
    ] ],
    [ "List", null, [
      [ "PicesInterface::CruiseList", "class_pices_interface_1_1_cruise_list.html", null ],
      [ "PicesInterface::PicesClassList", "class_pices_interface_1_1_pices_class_list.html", null ],
      [ "PicesInterface::PicesClassStatisticList", "class_pices_interface_1_1_pices_class_statistic_list.html", null ],
      [ "PicesInterface::PicesDataBaseImageGroupEntryList", "class_pices_interface_1_1_pices_data_base_image_group_entry_list.html", null ],
      [ "PicesInterface::PicesDataBaseImageGroupList", "class_pices_interface_1_1_pices_data_base_image_group_list.html", null ],
      [ "PicesInterface::PicesDataBaseImageList", "class_pices_interface_1_1_pices_data_base_image_list.html", null ],
      [ "PicesInterface::PicesDataBaseLogEntryList", "class_pices_interface_1_1_pices_data_base_log_entry_list.html", null ],
      [ "PicesInterface::PicesDataBaseServerList", "class_pices_interface_1_1_pices_data_base_server_list.html", null ],
      [ "PicesInterface::PicesFeatureVectorList", "class_pices_interface_1_1_pices_feature_vector_list.html", null ],
      [ "PicesInterface::PicesGPSDataPointList", "class_pices_interface_1_1_pices_g_p_s_data_point_list.html", null ],
      [ "PicesInterface::PicesInstrumentDataList", "class_pices_interface_1_1_pices_instrument_data_list.html", null ],
      [ "PicesInterface::PicesPointList", "class_pices_interface_1_1_pices_point_list.html", null ],
      [ "PicesInterface::PicesPredictionList", "class_pices_interface_1_1_pices_prediction_list.html", null ],
      [ "PicesInterface::PicesRasterList", "class_pices_interface_1_1_pices_raster_list.html", null ],
      [ "PicesInterface::PicesSipperCruiseList", "class_pices_interface_1_1_pices_sipper_cruise_list.html", null ],
      [ "PicesInterface::PicesSipperDeploymentList", "class_pices_interface_1_1_pices_sipper_deployment_list.html", null ],
      [ "PicesInterface::PicesSipperFileList", "class_pices_interface_1_1_pices_sipper_file_list.html", null ],
      [ "PicesInterface::PicesSipperStationList", "class_pices_interface_1_1_pices_sipper_station_list.html", null ],
      [ "PicesInterface::PicesTrainingClassList", "class_pices_interface_1_1_pices_training_class_list.html", null ],
      [ "PicesInterface::PicesVolumeSampledStatList", "class_pices_interface_1_1_pices_volume_sampled_stat_list.html", null ]
    ] ],
    [ "List< Blob >", null, [
      [ "SipperFile.BlobList", "class_sipper_file_1_1_blob_list.html", null ]
    ] ],
    [ "List< ClassTotals >", null, [
      [ "PicesCommander.ClassTotalsList", "class_pices_commander_1_1_class_totals_list.html", null ]
    ] ],
    [ "List< SipperFileControlBlock >", null, [
      [ "SipperDiskUtilities.SipperFileControlBlockList", "class_sipper_disk_utilities_1_1_sipper_file_control_block_list.html", null ]
    ] ],
    [ "map", null, [
      [ "MLL::ClassIndexList", "class_m_l_l_1_1_class_index_list.html", null ]
    ] ],
    [ "MLL::MLClassConstList::mlClassNameComparison", "class_m_l_class_const_list_1_1ml_class_name_comparison.html", null ],
    [ "MLL::MLClassList::mlClassNameComparison", "class_m_l_class_list_1_1ml_class_name_comparison.html", null ],
    [ "MLL::AbundanceCorrectionMatrix", "class_m_l_l_1_1_abundance_correction_matrix.html", null ],
    [ "MLL::Attribute", "class_m_l_l_1_1_attribute.html", null ],
    [ "MLL::BinaryClassParms", "class_m_l_l_1_1_binary_class_parms.html", null ],
    [ "MLL::BitReduction", "class_m_l_l_1_1_bit_reduction.html", null ],
    [ "MLL::ChainHash< T >", "class_m_l_l_1_1_chain_hash.html", null ],
    [ "MLL::ChainHashNode", "class_m_l_l_1_1_chain_hash_node.html", null ],
    [ "MLL::ClassificationBiasMatrix", "class_m_l_l_1_1_classification_bias_matrix.html", null ],
    [ "MLL::Classifier2", "class_m_l_l_1_1_classifier2.html", null ],
    [ "MLL::ClassProb", "class_m_l_l_1_1_class_prob.html", null ],
    [ "MLL::ClassStatistic", "class_m_l_l_1_1_class_statistic.html", null ],
    [ "MLL::CompressionStats", "struct_m_l_l_1_1_compression_stats.html", null ],
    [ "MLL::ConfusionMatrix2", "class_m_l_l_1_1_confusion_matrix2.html", null ],
    [ "MLL::CrossValidation", "class_m_l_l_1_1_cross_validation.html", null ],
    [ "MLL::CrossValidationMxN", "class_m_l_l_1_1_cross_validation_mx_n.html", null ],
    [ "MLL::CrossValidationThreeWay", "class_m_l_l_1_1_cross_validation_three_way.html", null ],
    [ "MLL::CrossValidationVoting", "class_m_l_l_1_1_cross_validation_voting.html", null ],
    [ "MLL::DataBase", "class_m_l_l_1_1_data_base.html", null ],
    [ "MLL::DataBaseGpsData", "class_m_l_l_1_1_data_base_gps_data.html", null ],
    [ "MLL::DataBaseImage", "class_m_l_l_1_1_data_base_image.html", null ],
    [ "MLL::DataBaseImageEntry", "class_m_l_l_1_1_data_base_image_entry.html", null ],
    [ "MLL::DataBaseImageGroup", "class_m_l_l_1_1_data_base_image_group.html", null ],
    [ "MLL::DataBaseImageGroupEntry", "class_m_l_l_1_1_data_base_image_group_entry.html", null ],
    [ "MLL::DataBaseImageValidatedEntry", "class_m_l_l_1_1_data_base_image_validated_entry.html", null ],
    [ "MLL::DataBaseLogEntry", "class_m_l_l_1_1_data_base_log_entry.html", null ],
    [ "MLL::DataBaseServer", "class_m_l_l_1_1_data_base_server.html", null ],
    [ "MLL::DataBaseUpdate", "class_m_l_l_1_1_data_base_update.html", null ],
    [ "MLL::DuplicateImage", "class_m_l_l_1_1_duplicate_image.html", null ],
    [ "MLL::DuplicateImages", "class_m_l_l_1_1_duplicate_images.html", null ],
    [ "MLL::ExtractFeatureData", "class_m_l_l_1_1_extract_feature_data.html", null ],
    [ "MLL::ExtractImageFileName", "class_m_l_l_1_1_extract_image_file_name.html", null ],
    [ "MLL::FeatureEncoder", "class_m_l_l_1_1_feature_encoder.html", null ],
    [ "MLL::FeatureEncoder2", "class_m_l_l_1_1_feature_encoder2.html", null ],
    [ "MLL::FeatureEncoder2::FeatureVar2", "struct_m_l_l_1_1_feature_encoder2_1_1_feature_var2.html", null ],
    [ "MLL::FeatureEncoder2::FeatureVarComparrison2", "class_m_l_l_1_1_feature_encoder2_1_1_feature_var_comparrison2.html", null ],
    [ "MLL::FeatureFileIO", "class_m_l_l_1_1_feature_file_i_o.html", [
      [ "MLL::FeatureFileIOArff", "class_m_l_l_1_1_feature_file_i_o_arff.html", null ],
      [ "MLL::FeatureFileIOC45", "class_m_l_l_1_1_feature_file_i_o_c45.html", null ],
      [ "MLL::FeatureFileIOColumn", "class_m_l_l_1_1_feature_file_i_o_column.html", null ],
      [ "MLL::FeatureFileIODstWeb", "class_m_l_l_1_1_feature_file_i_o_dst_web.html", null ],
      [ "MLL::FeatureFileIOPices", "class_m_l_l_1_1_feature_file_i_o_pices.html", null ],
      [ "MLL::FeatureFileIORoberts", "class_m_l_l_1_1_feature_file_i_o_roberts.html", null ],
      [ "MLL::FeatureFileIOSparse", "class_m_l_l_1_1_feature_file_i_o_sparse.html", null ],
      [ "MLL::FeatureFileIOUCI", "class_m_l_l_1_1_feature_file_i_o_u_c_i.html", null ]
    ] ],
    [ "MLL::FeatureNumList", "class_m_l_l_1_1_feature_num_list.html", null ],
    [ "MLL::FeatureVector", "class_m_l_l_1_1_feature_vector.html", [
      [ "MLL::ImageFeatures", "class_m_l_l_1_1_image_features.html", null ]
    ] ],
    [ "MLL::FileDesc", "class_m_l_l_1_1_file_desc.html", null ],
    [ "MLL::GPSDataPoint", "class_m_l_l_1_1_g_p_s_data_point.html", null ],
    [ "MLL::ImageDataTreeEntry", "class_m_l_l_1_1_image_data_tree_entry.html", null ],
    [ "MLL::ImageFeaturesList::const_iterator", "class_m_l_l_1_1_image_features_list_1_1const__iterator.html", null ],
    [ "MLL::ImageFeaturesList::iterator", "class_m_l_l_1_1_image_features_list_1_1iterator.html", null ],
    [ "MLL::ImageFeaturesNodeKey", "class_m_l_l_1_1_image_features_node_key.html", null ],
    [ "MLL::InstrumentDataList", "class_m_l_l_1_1_instrument_data_list.html", null ],
    [ "MLL::KArray< Entry >", "class_m_l_l_1_1_k_array.html", null ],
    [ "MLL::LogicalFrameBlob", "class_m_l_l_1_1_logical_frame_blob.html", null ],
    [ "MLL::MLClass", "class_m_l_l_1_1_m_l_class.html", null ],
    [ "MLL::Model", "class_m_l_l_1_1_model.html", [
      [ "MLL::ModelDual", "class_m_l_l_1_1_model_dual.html", null ],
      [ "MLL::ModelKnn", "class_m_l_l_1_1_model_knn.html", null ],
      [ "MLL::ModelOldSVM", "class_m_l_l_1_1_model_old_s_v_m.html", null ],
      [ "MLL::ModelSvmBase", "class_m_l_l_1_1_model_svm_base.html", null ],
      [ "MLL::ModelUsfCasCor", "class_m_l_l_1_1_model_usf_cas_cor.html", null ]
    ] ],
    [ "MLL::ModelParam", "class_m_l_l_1_1_model_param.html", [
      [ "MLL::ModelParamDual", "class_m_l_l_1_1_model_param_dual.html", null ],
      [ "MLL::ModelParamKnn", "class_m_l_l_1_1_model_param_knn.html", null ],
      [ "MLL::ModelParamOldSVM", "class_m_l_l_1_1_model_param_old_s_v_m.html", null ],
      [ "MLL::ModelParamSvmBase", "class_m_l_l_1_1_model_param_svm_base.html", null ],
      [ "MLL::ModelParamUsfCasCor", "class_m_l_l_1_1_model_param_usf_cas_cor.html", null ]
    ] ],
    [ "MLL::NormalizationParms", "class_m_l_l_1_1_normalization_parms.html", null ],
    [ "MLL::Orderings", "class_m_l_l_1_1_orderings.html", null ],
    [ "MLL::ProbNamePair", "class_m_l_l_1_1_prob_name_pair.html", null ],
    [ "MLL::SipperBlob", "class_m_l_l_1_1_sipper_blob.html", null ],
    [ "MLL::SipperExtractionImageManager", "class_m_l_l_1_1_sipper_extraction_image_manager.html", null ],
    [ "MLL::SipperExtractionImageManager::ImageEntry", "class_m_l_l_1_1_sipper_extraction_image_manager_1_1_image_entry.html", null ],
    [ "MLL::SipperExtractionImageManager::ManagedClass", "class_m_l_l_1_1_sipper_extraction_image_manager_1_1_managed_class.html", null ],
    [ "MLL::SipperExtractionImageManager::ManagedClasssesSortByClassName", "class_m_l_l_1_1_sipper_extraction_image_manager_1_1_managed_classses_sort_by_class_name.html", null ],
    [ "MLL::SizeDistribution", "class_m_l_l_1_1_size_distribution.html", null ],
    [ "MLL::svm_node_int", "struct_m_l_l_1_1svm__node__int.html", null ],
    [ "MLL::SVMModel", "class_m_l_l_1_1_s_v_m_model.html", null ],
    [ "MLL::SVMparam", "class_m_l_l_1_1_s_v_mparam.html", null ],
    [ "MLL::TrainingClass", "class_m_l_l_1_1_training_class.html", null ],
    [ "MLL::TrainingProcess2", "class_m_l_l_1_1_training_process2.html", null ],
    [ "MLL::UsfCasCor", "class_m_l_l_1_1_usf_cas_cor.html", null ],
    [ "MLL::UsfCasCor::parmentry", "struct_m_l_l_1_1_usf_cas_cor_1_1parmentry.html", null ],
    [ "MLL::VolumeSampledStat", "class_m_l_l_1_1_volume_sampled_stat.html", null ],
    [ "PicesCommander.ClassifierProcess", "class_pices_commander_1_1_classifier_process.html", null ],
    [ "PicesCommander.ClassStat", "class_pices_commander_1_1_class_stat.html", null ],
    [ "PicesCommander.ClassTotals", "class_pices_commander_1_1_class_totals.html", null ],
    [ "PicesCommander.DepthPlotDisplay", "class_pices_commander_1_1_depth_plot_display.html", null ],
    [ "PicesCommander.InstrumentStatsByDepth", "class_pices_commander_1_1_instrument_stats_by_depth.html", null ],
    [ "PicesCommander.PlanktonClassStatisticsLoader", "class_pices_commander_1_1_plankton_class_statistics_loader.html", null ],
    [ "PicesCommander.PlanktonDepthStatisticsLoader", "class_pices_commander_1_1_plankton_depth_statistics_loader.html", null ],
    [ "PicesCommander.PlanktonImageLoader", "class_pices_commander_1_1_plankton_image_loader.html", null ],
    [ "PicesCommander.PredictionResult", "class_pices_commander_1_1_prediction_result.html", null ],
    [ "PicesCommander.Program", "class_pices_commander_1_1_program.html", null ],
    [ "PicesCommander.SizeDistribution", "class_pices_commander_1_1_size_distribution.html", null ],
    [ "PicesInterface::Class1", "class_pices_interface_1_1_class1.html", null ],
    [ "PicesInterface::ClassificationBiasMatrix", "class_pices_interface_1_1_classification_bias_matrix.html", null ],
    [ "PicesInterface::Cruise", "class_pices_interface_1_1_cruise.html", null ],
    [ "PicesInterface::OSservices", "class_pices_interface_1_1_o_sservices.html", null ],
    [ "PicesInterface::ParsedImageFileName", "class_pices_interface_1_1_parsed_image_file_name.html", null ],
    [ "PicesInterface::PicesAbundanceCorrectionMatrix", "class_pices_interface_1_1_pices_abundance_correction_matrix.html", null ],
    [ "PicesInterface::PicesClass", "class_pices_interface_1_1_pices_class.html", null ],
    [ "PicesInterface::PicesClassStatistic", "class_pices_interface_1_1_pices_class_statistic.html", null ],
    [ "PicesInterface::PicesDataBase", "class_pices_interface_1_1_pices_data_base.html", null ],
    [ "PicesInterface::PicesDataBaseImage", "class_pices_interface_1_1_pices_data_base_image.html", null ],
    [ "PicesInterface::PicesDataBaseImageGroup", "class_pices_interface_1_1_pices_data_base_image_group.html", null ],
    [ "PicesInterface::PicesDataBaseImageGroupEntry", "class_pices_interface_1_1_pices_data_base_image_group_entry.html", null ],
    [ "PicesInterface::PicesDataBaseLogEntry", "class_pices_interface_1_1_pices_data_base_log_entry.html", null ],
    [ "PicesInterface::PicesDataBaseServer", "class_pices_interface_1_1_pices_data_base_server.html", null ],
    [ "PicesInterface::PicesFeatureFileIO", "class_pices_interface_1_1_pices_feature_file_i_o.html", null ],
    [ "PicesInterface::PicesFeatureVector", "class_pices_interface_1_1_pices_feature_vector.html", null ],
    [ "PicesInterface::PicesGoalKeeper", "class_pices_interface_1_1_pices_goal_keeper.html", null ],
    [ "PicesInterface::PicesGPSDataPoint", "class_pices_interface_1_1_pices_g_p_s_data_point.html", null ],
    [ "PicesInterface::PicesInstrumentData", "class_pices_interface_1_1_pices_instrument_data.html", null ],
    [ "PicesInterface::PicesInstrumentDataFileManager", "class_pices_interface_1_1_pices_instrument_data_file_manager.html", null ],
    [ "PicesInterface::PicesKKStr", "class_pices_interface_1_1_pices_k_k_str.html", null ],
    [ "PicesInterface::PicesMethods", "class_pices_interface_1_1_pices_methods.html", null ],
    [ "PicesInterface::PicesMsgQueue", "class_pices_interface_1_1_pices_msg_queue.html", null ],
    [ "PicesInterface::PicesPoint", "class_pices_interface_1_1_pices_point.html", null ],
    [ "PicesInterface::PicesPrediction", "class_pices_interface_1_1_pices_prediction.html", null ],
    [ "PicesInterface::PicesRaster", "class_pices_interface_1_1_pices_raster.html", null ],
    [ "PicesInterface::PicesRunLog", "class_pices_interface_1_1_pices_run_log.html", null ],
    [ "PicesInterface::PicesSipperCruise", "class_pices_interface_1_1_pices_sipper_cruise.html", null ],
    [ "PicesInterface::PicesSipperDeployment", "class_pices_interface_1_1_pices_sipper_deployment.html", null ],
    [ "PicesInterface::PicesSipperFile", "class_pices_interface_1_1_pices_sipper_file.html", null ],
    [ "PicesInterface::PicesSipperStation", "class_pices_interface_1_1_pices_sipper_station.html", null ],
    [ "PicesInterface::PicesSipperVariables", "class_pices_interface_1_1_pices_sipper_variables.html", null ],
    [ "PicesInterface::PicesTrainingClass", "class_pices_interface_1_1_pices_training_class.html", null ],
    [ "PicesInterface::PicesTrainingConfiguration", "class_pices_interface_1_1_pices_training_configuration.html", null ],
    [ "PicesInterface::PicesVolumeSampledStat", "class_pices_interface_1_1_pices_volume_sampled_stat.html", null ],
    [ "PicesInterface::ProbNamePair", "class_pices_interface_1_1_prob_name_pair.html", null ],
    [ "PicesInterface::TrainingModel2", "class_pices_interface_1_1_training_model2.html", null ],
    [ "RBTree", null, [
      [ "MLL::ImageFeaturesDataIndexed", "class_m_l_l_1_1_image_features_data_indexed.html", null ],
      [ "MLL::ImageFeaturesNameIndexed", "class_m_l_l_1_1_image_features_name_indexed.html", null ]
    ] ],
    [ "SipperHardware::SipperBuff4Bit::OpRec", "union_sipper_buff4_bit_1_1_op_rec.html", null ],
    [ "SipperHardware::SipperBuff4Bit::OpRecEndOfScanLine", "struct_sipper_buff4_bit_1_1_op_rec_end_of_scan_line.html", null ],
    [ "SipperHardware::SipperBuff4Bit::OpRecInstrumentDataWord1", "struct_sipper_buff4_bit_1_1_op_rec_instrument_data_word1.html", null ],
    [ "SipperHardware::SipperBuff4Bit::OpRecInstrumentDataWord2", "struct_sipper_buff4_bit_1_1_op_rec_instrument_data_word2.html", null ],
    [ "SipperHardware::SipperBuff4Bit::OpRecInstrumentDataWord3", "struct_sipper_buff4_bit_1_1_op_rec_instrument_data_word3.html", null ],
    [ "SipperHardware::SipperBuff4Bit::OpRecRaw1Pixel", "struct_sipper_buff4_bit_1_1_op_rec_raw1_pixel.html", null ],
    [ "SipperHardware::SipperBuff4Bit::OpRecRaw32Pixels", "struct_sipper_buff4_bit_1_1_op_rec_raw32_pixels.html", null ],
    [ "SipperHardware::SipperBuff4Bit::OpRecRaw513Pixels1", "struct_sipper_buff4_bit_1_1_op_rec_raw513_pixels1.html", null ],
    [ "SipperHardware::SipperBuff4Bit::OpRecRaw513Pixels2", "struct_sipper_buff4_bit_1_1_op_rec_raw513_pixels2.html", null ],
    [ "SipperHardware::SipperBuff4Bit::OpRecRun256Len1", "struct_sipper_buff4_bit_1_1_op_rec_run256_len1.html", null ],
    [ "SipperHardware::SipperBuff4Bit::OpRecRun256Len2", "struct_sipper_buff4_bit_1_1_op_rec_run256_len2.html", null ],
    [ "SipperHardware::SipperBuff4Bit::OpRecRunLen", "struct_sipper_buff4_bit_1_1_op_rec_run_len.html", null ],
    [ "SipperHardware::SipperBuff4Bit::OpRecTextBlock1", "struct_sipper_buff4_bit_1_1_op_rec_text_block1.html", null ],
    [ "SipperHardware::SipperBuff4Bit::OpRecTextBlock2", "struct_sipper_buff4_bit_1_1_op_rec_text_block2.html", null ],
    [ "SipperHardware::SipperBuff4Bit::RawPixelRec", "struct_sipper_buff4_bit_1_1_raw_pixel_rec.html", null ],
    [ "SipperHardware::SipperBuff::SipperRec", "struct_sipper_buff_1_1_sipper_rec.html", null ],
    [ "SipperHardware::SipperCruiseList::CruiseNameComparator", "class_sipper_cruise_list_1_1_cruise_name_comparator.html", null ],
    [ "SipperDiskUtilities.Constants", "class_sipper_disk_utilities_1_1_constants.html", null ],
    [ "SipperDiskUtilities.MasterBootRecord", "class_sipper_disk_utilities_1_1_master_boot_record.html", null ],
    [ "SipperDiskUtilities.ParseSipperLog", "class_sipper_disk_utilities_1_1_parse_sipper_log.html", null ],
    [ "SipperDiskUtilities.PartitionTable", "class_sipper_disk_utilities_1_1_partition_table.html", null ],
    [ "SipperDiskUtilities.PartitionTableEntry", "class_sipper_disk_utilities_1_1_partition_table_entry.html", null ],
    [ "SipperDiskUtilities.SipperDateStamp", "class_sipper_disk_utilities_1_1_sipper_date_stamp.html", null ],
    [ "SipperDiskUtilities.SipperDateTimeStamp", "class_sipper_disk_utilities_1_1_sipper_date_time_stamp.html", null ],
    [ "SipperDiskUtilities.SipperDisk", "class_sipper_disk_utilities_1_1_sipper_disk.html", null ],
    [ "SipperDiskUtilities.SipperFileControlBlock", "class_sipper_disk_utilities_1_1_sipper_file_control_block.html", null ],
    [ "SipperDiskUtilities.SipperPartitionSector", "class_sipper_disk_utilities_1_1_sipper_partition_sector.html", null ],
    [ "SipperDiskUtilities.SipperTimeStamp", "class_sipper_disk_utilities_1_1_sipper_time_stamp.html", null ],
    [ "SipperFile.ActiveTrainingLibraries", "class_sipper_file_1_1_active_training_libraries.html", null ],
    [ "SipperFile.Blob", "class_sipper_file_1_1_blob.html", null ],
    [ "SipperFile.BlobDetector", "class_sipper_file_1_1_blob_detector.html", null ],
    [ "SipperFile.DepthPlot2Parameters", "class_sipper_file_1_1_depth_plot2_parameters.html", null ],
    [ "SipperFile.Instrument", "class_sipper_file_1_1_instrument.html", [
      [ "SipperFile.InstrumentBatteryMeters", "class_sipper_file_1_1_instrument_battery_meters.html", null ],
      [ "SipperFile.InstrumentCTD", "class_sipper_file_1_1_instrument_c_t_d.html", null ],
      [ "SipperFile.InstrumentGPS", "class_sipper_file_1_1_instrument_g_p_s.html", null ],
      [ "SipperFile.InstrumentInclinationMeter", "class_sipper_file_1_1_instrument_inclination_meter.html", null ],
      [ "SipperFile.InstrumentOther", "class_sipper_file_1_1_instrument_other.html", null ]
    ] ],
    [ "SipperFile.InstrumentData", "class_sipper_file_1_1_instrument_data.html", null ],
    [ "SipperFile.InstrumentDataLogger", "class_sipper_file_1_1_instrument_data_logger.html", null ],
    [ "SipperFile.InstrumentDataManager", "class_sipper_file_1_1_instrument_data_manager.html", null ],
    [ "SipperFile.InstrumentDataReport", "class_sipper_file_1_1_instrument_data_report.html", [
      [ "SipperFile.InstrumentDataReportBatteryMeter", "class_sipper_file_1_1_instrument_data_report_battery_meter.html", null ],
      [ "SipperFile.InstrumentDataReportCTD", "class_sipper_file_1_1_instrument_data_report_c_t_d.html", null ],
      [ "SipperFile.InstrumentDataReportFlowMeter", "class_sipper_file_1_1_instrument_data_report_flow_meter.html", null ],
      [ "SipperFile.InstrumentDataReportGPS", "class_sipper_file_1_1_instrument_data_report_g_p_s.html", null ],
      [ "SipperFile.InstrumentDataReportIllumination", "class_sipper_file_1_1_instrument_data_report_illumination.html", null ],
      [ "SipperFile.InstrumentDataReportInclination", "class_sipper_file_1_1_instrument_data_report_inclination.html", null ],
      [ "SipperFile.InstrumentDataReportText", "class_sipper_file_1_1_instrument_data_report_text.html", null ]
    ] ],
    [ "SipperFile.PortAssignment", "class_sipper_file_1_1_port_assignment.html", null ],
    [ "SipperFile.Sipper2DecodeRec", "class_sipper_file_1_1_sipper2_decode_rec.html", null ],
    [ "SipperFile.Sipper3DecodeRec", "class_sipper_file_1_1_sipper3_decode_rec.html", null ],
    [ "SipperFile.SipperBaseFile", "class_sipper_file_1_1_sipper_base_file.html", [
      [ "SipperFile.Sipper2File", "class_sipper_file_1_1_sipper2_file.html", null ],
      [ "SipperFile.Sipper3File", "class_sipper_file_1_1_sipper3_file.html", null ],
      [ "SipperFile.SipperBuff4Bit", "class_sipper_file_1_1_sipper_buff4_bit.html", null ],
      [ "SipperFile.SipperFileSimple", "class_sipper_file_1_1_sipper_file_simple.html", null ]
    ] ],
    [ "SipperFile.SipperBuff4Bit.DecodeOpRec", "class_sipper_file_1_1_sipper_buff4_bit_1_1_decode_op_rec.html", null ],
    [ "SipperFile.SipperBuff4Bit.DecodeRawByte", "class_sipper_file_1_1_sipper_buff4_bit_1_1_decode_raw_byte.html", null ],
    [ "SipperFile.SipperClock", "class_sipper_file_1_1_sipper_clock.html", null ],
    [ "SipperFile.SipperConfigRec", "class_sipper_file_1_1_sipper_config_rec.html", null ],
    [ "SipperFile.SipperFileBuffered", "class_sipper_file_1_1_sipper_file_buffered.html", null ],
    [ "SipperFile.SipperFrame", "class_sipper_file_1_1_sipper_frame.html", null ],
    [ "SipperFile.SipperHeaderRec", "class_sipper_file_1_1_sipper_header_rec.html", null ],
    [ "SipperFile.TimePlotParameters", "class_sipper_file_1_1_time_plot_parameters.html", null ],
    [ "SipperFile.VolumeByDepth", "class_sipper_file_1_1_volume_by_depth.html", null ],
    [ "SipperHardware::CTD_Plus_Data", "class_sipper_hardware_1_1_c_t_d___plus___data.html", null ],
    [ "SipperHardware::GPSDataPoint", "class_sipper_hardware_1_1_g_p_s_data_point.html", null ],
    [ "SipperHardware::Instrument", "class_sipper_hardware_1_1_instrument.html", [
      [ "SipperHardware::InstrumentBatteryMeters", "class_sipper_hardware_1_1_instrument_battery_meters.html", null ],
      [ "SipperHardware::InstrumentCTD", "class_sipper_hardware_1_1_instrument_c_t_d.html", null ],
      [ "SipperHardware::InstrumentGPS", "class_sipper_hardware_1_1_instrument_g_p_s.html", null ],
      [ "SipperHardware::InstrumentInclinationMeter", "class_sipper_hardware_1_1_instrument_inclination_meter.html", null ],
      [ "SipperHardware::InstrumentOther", "class_sipper_hardware_1_1_instrument_other.html", null ]
    ] ],
    [ "SipperHardware::InstrumentData", "class_sipper_hardware_1_1_instrument_data.html", null ],
    [ "SipperHardware::InstrumentDataFileManager", "class_sipper_hardware_1_1_instrument_data_file_manager.html", null ],
    [ "SipperHardware::InstrumentDataManager", "class_sipper_hardware_1_1_instrument_data_manager.html", null ],
    [ "SipperHardware::InstrumentDataMeans", "class_sipper_hardware_1_1_instrument_data_means.html", null ],
    [ "SipperHardware::InstrumentDataReport", "class_sipper_hardware_1_1_instrument_data_report.html", [
      [ "SipperHardware::InstrumentDataBatteryMeter", "class_sipper_hardware_1_1_instrument_data_battery_meter.html", null ],
      [ "SipperHardware::InstrumentDataCTDplus", "class_sipper_hardware_1_1_instrument_data_c_t_dplus.html", null ],
      [ "SipperHardware::InstrumentDataFlowMeter1", "class_sipper_hardware_1_1_instrument_data_flow_meter1.html", null ],
      [ "SipperHardware::InstrumentDataGPS", "class_sipper_hardware_1_1_instrument_data_g_p_s.html", null ],
      [ "SipperHardware::InstrumentDataPitchAndRoll", "class_sipper_hardware_1_1_instrument_data_pitch_and_roll.html", null ],
      [ "SipperHardware::InstrumentDataUserMsgs", "class_sipper_hardware_1_1_instrument_data_user_msgs.html", null ]
    ] ],
    [ "SipperHardware::PortAssignment", "class_sipper_hardware_1_1_port_assignment.html", null ],
    [ "SipperHardware::Sipper3BitRec", "struct_sipper_hardware_1_1_sipper3_bit_rec.html", null ],
    [ "SipperHardware::Sipper3Rec", "struct_sipper_hardware_1_1_sipper3_rec.html", null ],
    [ "SipperHardware::SipperBinaryRec", "struct_sipper_hardware_1_1_sipper_binary_rec.html", null ],
    [ "SipperHardware::SipperBuff", "class_sipper_hardware_1_1_sipper_buff.html", [
      [ "SipperHardware::Sipper3Buff", "class_sipper_hardware_1_1_sipper3_buff.html", null ],
      [ "SipperHardware::Sipper3RevBuff", "class_sipper_hardware_1_1_sipper3_rev_buff.html", null ],
      [ "SipperHardware::SipperBuff3Bit", "class_sipper_hardware_1_1_sipper_buff3_bit.html", null ],
      [ "SipperHardware::SipperBuff4Bit", "class_sipper_hardware_1_1_sipper_buff4_bit.html", null ],
      [ "SipperHardware::SipperBuffBinary", "class_sipper_hardware_1_1_sipper_buff_binary.html", null ]
    ] ],
    [ "SipperHardware::SipperCruise", "class_sipper_hardware_1_1_sipper_cruise.html", null ],
    [ "SipperHardware::SipperDeployment", "class_sipper_hardware_1_1_sipper_deployment.html", null ],
    [ "SipperHardware::SipperFile", "class_sipper_hardware_1_1_sipper_file.html", null ],
    [ "SipperHardware::SipperFileOracle", "class_sipper_hardware_1_1_sipper_file_oracle.html", null ],
    [ "SipperHardware::SipperHeaderRec", "class_sipper_hardware_1_1_sipper_header_rec.html", null ],
    [ "SipperHardware::SipperStation", "class_sipper_hardware_1_1_sipper_station.html", null ],
    [ "SipperHardware::SipperVariables", "class_sipper_hardware_1_1_sipper_variables.html", null ],
    [ "SipperHardware::VolumeSampledStat", "class_sipper_hardware_1_1_volume_sampled_stat.html", null ],
    [ "MLL::SizeDistribution::ClassTotals", "class_size_distribution_1_1_class_totals.html", null ],
    [ "SortedList< String, ClassStat >", null, [
      [ "PicesCommander.ClassStatSortedList", "class_pices_commander_1_1_class_stat_sorted_list.html", null ]
    ] ],
    [ "SplitRec", "struct_split_rec.html", null ],
    [ "std::deque< T >", null, [
      [ "ImageExtractionManager::ExtractedImageQueue", "class_image_extraction_manager_1_1_extracted_image_queue.html", null ]
    ] ],
    [ "std::exception", null, [
      [ "KKU::KKStrException", "class_k_k_u_1_1_k_k_str_exception.html", null ]
    ] ],
    [ "std::map< K, T >", null, [
      [ "SipperHardware::VolumeSampledStatList", "class_sipper_hardware_1_1_volume_sampled_stat_list.html", null ]
    ] ],
    [ "std::multimap< K, T >", null, [
      [ "MLL::ClassAssignments", "class_m_l_l_1_1_class_assignments.html", null ]
    ] ],
    [ "Stream", null, [
      [ "SipperDiskUtilities.SipperDiskFile", "class_sipper_disk_utilities_1_1_sipper_disk_file.html", null ]
    ] ],
    [ "SVM233::Cache", "class_s_v_m233_1_1_cache.html", null ],
    [ "SVM233::decision_function", "struct_s_v_m233_1_1decision__function.html", null ],
    [ "SVM233::Kernel", "class_s_v_m233_1_1_kernel.html", [
      [ "SVM233::ONE_CLASS_Q", "class_s_v_m233_1_1_o_n_e___c_l_a_s_s___q.html", null ],
      [ "SVM233::SVC_Q", "class_s_v_m233_1_1_s_v_c___q.html", null ],
      [ "SVM233::SVR_Q", "class_s_v_m233_1_1_s_v_r___q.html", null ]
    ] ],
    [ "SVM233::Solver", "class_s_v_m233_1_1_solver.html", [
      [ "SVM233::Solver_NU", "class_s_v_m233_1_1_solver___n_u.html", null ]
    ] ],
    [ "SVM233::Solver::SolutionInfo", "struct_s_v_m233_1_1_solver_1_1_solution_info.html", null ],
    [ "SVM233::svm_model", "struct_s_v_m233_1_1svm__model.html", null ],
    [ "SVM233::svm_node", "struct_s_v_m233_1_1svm__node.html", null ],
    [ "SVM233::svm_parameter", "struct_s_v_m233_1_1svm__parameter.html", null ],
    [ "SVM233::svm_problem", "struct_s_v_m233_1_1svm__problem.html", null ],
    [ "SVM289_BFS::Cache", "class_s_v_m289___b_f_s_1_1_cache.html", null ],
    [ "SVM289_BFS::decision_function", "struct_s_v_m289___b_f_s_1_1decision__function.html", null ],
    [ "SVM289_BFS::QMatrix", "class_s_v_m289___b_f_s_1_1_q_matrix.html", [
      [ "SVM289_BFS::Kernel", "class_s_v_m289___b_f_s_1_1_kernel.html", [
        [ "SVM289_BFS::ONE_CLASS_Q", "class_s_v_m289___b_f_s_1_1_o_n_e___c_l_a_s_s___q.html", null ],
        [ "SVM289_BFS::SVC_Q", "class_s_v_m289___b_f_s_1_1_s_v_c___q.html", null ],
        [ "SVM289_BFS::SVR_Q", "class_s_v_m289___b_f_s_1_1_s_v_r___q.html", null ]
      ] ]
    ] ],
    [ "SVM289_BFS::Solver", "class_s_v_m289___b_f_s_1_1_solver.html", [
      [ "SVM289_BFS::Solver_NU", "class_s_v_m289___b_f_s_1_1_solver___n_u.html", null ]
    ] ],
    [ "SVM289_BFS::Solver::SolutionInfo", "struct_s_v_m289___b_f_s_1_1_solver_1_1_solution_info.html", null ],
    [ "SVM289_BFS::svm_model", "struct_s_v_m289___b_f_s_1_1svm__model.html", null ],
    [ "SVM289_BFS::svm_parameter", "struct_s_v_m289___b_f_s_1_1svm__parameter.html", null ],
    [ "SVM289_BFS::svm_problem", "struct_s_v_m289___b_f_s_1_1svm__problem.html", null ],
    [ "SVM289_MFS::Cache", "class_s_v_m289___m_f_s_1_1_cache.html", null ],
    [ "SVM289_MFS::decision_function", "struct_s_v_m289___m_f_s_1_1decision__function.html", null ],
    [ "SVM289_MFS::QMatrix", "class_s_v_m289___m_f_s_1_1_q_matrix.html", [
      [ "SVM289_MFS::Kernel", "class_s_v_m289___m_f_s_1_1_kernel.html", [
        [ "SVM289_MFS::ONE_CLASS_Q", "class_s_v_m289___m_f_s_1_1_o_n_e___c_l_a_s_s___q.html", null ],
        [ "SVM289_MFS::SVC_Q", "class_s_v_m289___m_f_s_1_1_s_v_c___q.html", null ],
        [ "SVM289_MFS::SVR_Q", "class_s_v_m289___m_f_s_1_1_s_v_r___q.html", null ]
      ] ]
    ] ],
    [ "SVM289_MFS::Solver", "class_s_v_m289___m_f_s_1_1_solver.html", [
      [ "SVM289_MFS::Solver_NU", "class_s_v_m289___m_f_s_1_1_solver___n_u.html", null ]
    ] ],
    [ "SVM289_MFS::Solver::SolutionInfo", "struct_s_v_m289___m_f_s_1_1_solver_1_1_solution_info.html", null ],
    [ "SVM289_MFS::svm_model", "struct_s_v_m289___m_f_s_1_1svm__model.html", null ],
    [ "SVM289_MFS::svm_parameter", "struct_s_v_m289___m_f_s_1_1svm__parameter.html", null ],
    [ "SVM289_MFS::svm_problem", "struct_s_v_m289___m_f_s_1_1svm__problem.html", null ],
    [ "IComparer", null, [
      [ "PicesInterface::PicesClassList::ClassNameComparitor", "class_pices_class_list_1_1_class_name_comparitor.html", null ],
      [ "PicesInterface::PicesFeatureVectorList::FeatureVectorComparitorByImageFileName", "class_pices_interface_1_1_pices_feature_vector_list_1_1_feature_vector_comparitor_by_image_file_name.html", null ],
      [ "PicesInterface::PicesPredictionList::SortPredictionsByProbability", "class_pices_prediction_list_1_1_sort_predictions_by_probability.html", null ],
      [ "PicesInterface::PicesPredictionList::SortPredictionsByVotes", "class_pices_prediction_list_1_1_sort_predictions_by_votes.html", null ]
    ] ],
    [ "Form", null, [
      [ "PicesInterface::FeatureFileNamePrompter", "class_pices_interface_1_1_feature_file_name_prompter.html", null ],
      [ "PicesInterface::PicesDataBaseServerPrompter", "class_pices_interface_1_1_pices_data_base_server_prompter.html", null ],
      [ "SipperFile.DepthPlot2", "class_sipper_file_1_1_depth_plot2.html", null ],
      [ "SipperFile.SipperConfigForm", "class_sipper_file_1_1_sipper_config_form.html", null ]
    ] ],
    [ "tagTHREADNAME_INFO", "structtag_t_h_r_e_a_d_n_a_m_e___i_n_f_o.html", null ],
    [ "TreeNode", null, [
      [ "SipperFile.TreeNodeCruise", "class_sipper_file_1_1_tree_node_cruise.html", null ],
      [ "SipperFile.TreeNodeDeployment", "class_sipper_file_1_1_tree_node_deployment.html", null ],
      [ "SipperFile.TreeNodeSipperFile", "class_sipper_file_1_1_tree_node_sipper_file.html", null ],
      [ "SipperFile.TreeNodeStation", "class_sipper_file_1_1_tree_node_station.html", null ]
    ] ]
];