Pices: D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/kku_fftw.cpp File Reference
kku_fftw.cpp File Reference
#include "FirstIncludes.h"
#include <stdlib.h>
#include <memory>
#include <math.h>
#include <complex>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>
#include "MemoryDebug.h"
#include "BasicTypes.h"
#include "GoalKeeper.h"
#include "kku_fftw.h"
Functions
void SWAP (float &a, float &b)
Variables
volatile KKU::GoalKeeperPtr fftwGoalKeeper = NULL
KK_DFT< float > x (100, true)
Function Documentation
void SWAP (float & a, float & b)
Definition at line 133 of file kku_fftw.cpp.
Referenced by KKU::FFT().
Variable Documentation
volatile KKU::GoalKeeperPtr fftwGoalKeeper = NULL
Definition at line 262 of file kku_fftw.cpp.
Referenced by KKU::fftwCreateOneDPlan(), KKU::fftwCreateTwoDPlan(), and KKU::fftwDestroyPlan().
KK_DFT<float> x(100, true)
Referenced by MLL::ConfusionMatrix2::AccuracyStr(), PicesCommander.SizeDistribution::Add(), PicesInterface::PicesClass::AddAChild(), MLL::FeatureNumList::AddFeature(), MLL::AbundanceCorrectionMatrix::AddIn(), SipperFile.Sipper2DecodeRec::AddToScanLine(), SipperFile.Sipper3DecodeRec::AddToScanLine(), SipperFile.InstrumentDataReportText::AllMessages(), KKU::KK_DFT2D< DftType >::AllocateAray(), MLL::FeatureVector::AllocateFeatureDataArray(), SipperFile.SipperBaseFile::AllocateFrame(), MLL::Model::AllocatePredictionVariables(), KKU::KKStr::Append(), JobManagment::JobList::AreAllJobsDone(), ArrayCommaDelimited(), ArrayToDelimitedDelimitedStr(), KKU::Raster::BinarizeByThreshold(), PicesInterface::TrainingModel2::BinaryProbailitiesForClass(), KKU::BitString::BitString(), KKU::GoalKeeper::BlockerThreadId(), KKU::BmpImage::BmpImage(), KKU::PointList::BoxCoordinites(), SipperFile.InstrumentData::BuildFieldNameList(), KKU::Raster::BuildGaussian2dKernel(), KKU::Raster::CalcAreaAndIntensityFeatures(), KKU::Raster::CalcAreaAndIntensityHistogram(), KKU::Raster::CalcAreaAndIntensityHistogramWhite(), KKU::CalcBQV(), KKU::Matrix::CalcCoFactorMatrix(), SipperFile.DataRowList::CalcMinMaxValues(), SipperFile.InstrumentDataList::CalcMinMaxValues(), KKU::CalcPQV(), KKU::PointList::CalculateCenterPoint(), MLL::DataBaseImageList::CalculateDensitesByQuadrat(), KKU::KKStr::CharInStr(), KKU::KKStr::ChopFirstChar(), KKU::SegmentorOTSU::ClassAverageRGB(), PicesCommander.ClassTotals::ClassTotals(), MLL::SizeDistribution::ClassTotals::ClassTotals(), SipperFile.TrainingModelStatus::CleanUpMemory(), SipperDiskUtilities.SipperDisk::CloseSipperDiskFile(), KKU::KKStr::Compare(), KKU::KKStr::CompareIgnoreCase(), MLL::ImageFeaturesNodeKey::CompareTwoImages(), MLL::FeatureNumList::Complement(), SipperHardware::InstrumentDataManager::CompReportLine(), MLL::BitReduction::CompressOneFeature(), MLL::ConfusionMatrix2::ComputeFundamentalStats(), PicesInterface::PicesPointList::ComputeSegmentLens(), MLL::AbundanceCorrectionMatrix::ComputeStatistics(), KKU::KKStr::Concat(), KKU::Configuration::Configuration(), MLL::FileDesc::CreateAAttributeTable(), MLL::FileDesc::CreateAttributeTypeTable(), MLL::FileDesc::CreateCardinalityTable(), KKU::Raster::CreateColorImageFromLabels(), KKU::SimpleCompressor::CreateCompressedBuffer(), SipperFile.InstrumentData::CreateCurrentFieldIndexList(), SipperHardware::InstrumentData::CreateDefaultFieldIndirectionList(), MLL::CrossValidationThreeWay::CreateDistanceReport(), MLL::FeatureEncoder2::CreateEncodedFileDesc(), MLL::FeatureEncoder::CreateEncodedFileDesc(), SipperHardware::InstrumentData::CreateFieldIndirectionVectorFromTabDelStr(), KKU::ContourFollower::CreateFourierDescriptorBySampling(), PicesInterface::PicesClassList::CreateFromCommaDelStr(), KKU::Histogram::CreateGraph(), KKU::Raster::CreateGrayScale(), KKU::Raster::CreateGrayScaleKLT(), PicesInterface::PicesFeatureVectorList::CreateListForAGivenLevel(), MLL::CrossValidationThreeWay::CreateProbabilityReport(), KKU::RasterList::CreateSmoothedFrame(), SipperHardware::CTD_Plus_Data::CTD_Plus_Data(), KKU::SegmentorOTSU::CumSum(), KKU::DateType::Days(), MLL::Model::DeAllocateSpace(), KKU::SimpleCompressor::Decompress(), MLL::UsfCasCor::Delete2DArray(), MLL::BitReduction::DeleteHistogram(), SipperFile.DepthPlot2::DepthPlot2(), SipperFile.DepthPlot2Parameters::DepthPlot2Parameters(), KKU::Matrix::DeterminantSlow(), SipperHardware::SipperBuff::DetermineCropSettings(), SipperFile.InstrumentDataManager::Dispose(), SipperFile.DataRowList::Dispose(), SipperFile.InstrumentDataList::Dispose(), MLL::ChainHash< T >::DoSomeStats(), KKU::Raster::DrawCircle(), KKU::Raster::DrawGrid(), KKU::Matrix::EigenVectors(), KKU::BmpImage::EliminateVerticalLines(), MLL::FeatureEncoder2::EncodeAExample(), MLL::FeatureEncoder::EncodeAImage(), KKU::Histogram::Equalized(), SipperFile.InstrumentData::Equals(), KKU::KKStr::ExtractChar(), MLL::MLClassConstList::ExtractHTMLTableHeader(), MLL::MLClassList::ExtractHTMLTableHeader(), PicesInterface::PicesClassList::ExtractThreeTitleLines(), MLL::MLClassConstList::ExtractTwoTitleLines(), MLL::MLClassList::ExtractTwoTitleLines(), MLL::ConfusionMatrix2::FactorCounts(), SipperFile.FeatureDataDisplay::FeatureDataDisplay(), MLL::FeatureEncoder::FeatureEncoder(), MLL::FeatureEncoder2::FeatureEncoder2(), MLL::FeatureNumList::FeatureNumList(), MLL::FeatureVector::FeatureVector(), SVM289_BFS::svm_problem::FileDesc(), SVM289_MFS::svm_problem::FileDesc(), SipperDiskUtilities.Constants::FillBuffer(), SipperDiskUtilities.SipperPartitionSector::FillBuffer(), SipperDiskUtilities.SipperFileControlBlock::FillBuffer(), MLL::UsfCasCor::FilterOutExtremeExamples(), SipperHardware::Instrument::FinalCleanUp(), MLL::DataBase::FinalCleanUp(), KKU::KKStr::Find(), MLL::CrossValidationThreeWay::FoldStr(), MLL::CrossValidationVoting::FoldStr(), KKU::ContourFollower::FollowContour(), KKU::ContourFollower::FollowContour2(), KKU::Raster::FourierExtractFeatures(), KKU::RasterSipper::FromCompressor(), KKU::SegmentorOTSU::GetClassClosestToTargetColor(), MLL::FeatureVectorList::GetClassStatistics(), SipperHardware::InstrumentDataFileManager::GetClosestInstrumentData(), SipperFile.SipperFileBuffered::GetDisplayRows(), SipperFile.InstrumentData::GetFieldNameIndex(), SipperHardware::InstrumentData::GetFieldNum(), SipperHardware::InstrumentData::GetFieldNumFromShortName(), MLL::FeatureFileIODstWeb::GetFileDesc(), PicesInterface::OSservices::GetListOfFiles(), PicesInterface::TrainingModel2::GetListOfTrainingModels(), SipperHardware::Sipper3RevBuff::GetNextLine(), SipperHardware::Sipper3Buff::GetNextLine(), SipperHardware::SipperBuff4Bit::GetNextLine(), MLL::MLClassList::GetNoiseClass(), KKU::Histogram::GetPeakAvgByHighestOrder(), KKU::Histogram::GetPeakByHighestOrder(), PicesCommander.PlanktonDepthStatisticsLoader::GetStatsAlreadyLoaded(), PicesCommander.PlanktonDepthStatisticsLoader::GetStatsAlreadyLoadedIfNew(), GrayScaleImage(), GreaterVotes(), KKU::HashTable< Entry >::HashTable(), KKU::HashTable< Entry >::HashValue(), SipperHardware::SipperHeaderRec::HeaderStr(), SipperFile.SipperHeaderRec::HeaderStr(), KKU::Histogram::Histogram(), KKU::Raster::Histogram(), KKU::ContourFollower::HistogramDistanceFromAPointOfEdge(), MLL::DataBase::ImageFullSizeSave(), PicesInterface::PicesDataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageGroupEntriesInsert(), MLL::DataBase::ImageInsert(), MLL::DuplicateImage::ImageWithSmallestScanLine(), SipperHardware::SipperHeaderRec::InclinationMeter(), SipperFile.SipperHeaderRec::InclinationMeter(), MLL::FeatureNumList::InList(), KKU::KKStr::InstancesOfChar(), SipperHardware::InstrumentData::InstrumentData(), SipperFile.InstrumentData::InstrumentData(), SipperHardware::InstrumentDataFlowMeter1::InstrumentDataFlowMeter1(), SipperHardware::InstrumentDataManager::InstrumentDataManager(), SipperFile.InstrumentDataReportFlowMeter::InstrumentDataReportFlowMeter(), SipperHardware::InstrumentDataReport::InstrumentName(), KKU::Histogram::IsBucketAPeak(), PicesInterface::PicesClass::IsInMySubTree(), SVM233::Kernel::k_function(), SVM233::Kernel::k_function_subspace(), k_ThinningSearchNeighbors(), KKU::KKStr::KKStr(), KKU::KKStrList::KKStrList(), SipperFile.SipperBuff4Bit::LengthNextScanLine(), KKU::BitString::ListOfSetBits16(), KKU::BitString::ListOfSetBits32(), KKU::LLoydsIndexOfPatchiness(), PicesInterface::Cruise::Load(), PicesInterface::TrainingModel2::LoadExistingTrainedModel(), MLL::FeatureFileIODstWeb::LoadFile(), PicesInterface::TrainingModel2::LoadTrainigLibrary(), PicesInterface::TrainingModel2::LoadTrainingModelForGivenLevel(), LocateEnvStrStart(), JobManagment::JobList::LocateOpenJob(), SVM289_BFS::svm_problem::Log(), SVM289_MFS::svm_problem::Log(), PicesInterface::PicesFeatureVectorList::LookUpByImageFileName(), PicesInterface::PicesClassList::LookUpByName(), SipperHardware::Instrument::LookUpByShortName(), SipperFile.Instrument::LookUpByShortName(), KKU::KKStr::Lower(), CrossValidationApp::Main(), MarineSnowReportDeployment(), SipperDiskUtilities.MasterBootRecord::MasterBootRecord(), KKU::McNemarsTest(), MemCompare(), MLL::UsfCasCor::MemoryConsumedEstimated(), MLL::SVMModel::MemoryConsumedEstimated(), MLL::MLClassList::MLClassList(), MLL::DataBase::MLClassLoadList(), SVM289_BFS::svm_model::NormalizeProbability(), SVM289_MFS::svm_model::NormalizeProbability(), KKU::GoalKeeper::NumBlockedThreads(), CImageExtractionWindowsDlg::OnPaint(), KKU::BitString::operator&=(), KKU::Matrix::operator*(), operator*(), KKU::Matrix::operator*=(), KKU::Matrix::operator+(), KKU::Matrix::operator+=(), KKU::Matrix::operator-(), KKU::operator-(), MLL::FeatureNumList::operator-(), operator-(), PicesInterface::operator<<(), SVM289_BFS::svm_parameter::operator=(), SVM289_MFS::svm_parameter::operator=(), KKU::KKStr::operator=(), KKU::BitString::operator=(), KKU::BitString::operator^(), KKU::BitString::operator^=(), KKU::BitString::operator|=(), KKU::osGetListOfDirectories(), KKU::osGetParentDirectoryOfDirPath(), KKU::osGetParentDirPath(), KKU::osParseFileName(), KKU::osSubstituteInEvironmentVariables(), MLL::ClassIndexList::ParseClassIndexList(), SipperHardware::SipperHeaderRec::ParseHeaderStr(), SipperFile.SipperHeaderRec::ParseHeaderStr(), SipperFile.InstrumentDataReportBatteryMeter::ParseTxtLine(), SipperDiskUtilities.PartitionTable::PartitionTable(), SipperFile.TimePlotParameters::PlotDataRow(), SipperFile.Instrument::PopulateComboBox(), KKU::BitString::PopulateVectorBool(), JobManagment::Job::PrerequisitesFromStr(), JobManagment::Job::PrerequisitesToStr(), KKU::BmpImage::Print(), PicesCommander.SizeDistribution::PrintByClassCollumns(), MLL::ConfusionMatrix2::PrintConfusionMatrix(), MLL::ConfusionMatrix2::PrintConfusionMatrixLatexTable(), MLL::ConfusionMatrix2::PrintConfusionMatrixNarrow(), MLL::AbundanceCorrectionMatrix::PrintConfusionMatrixTabDelimited(), MLL::ConfusionMatrix2::PrintConfusionMatrixTabDelimited(), MLL::ConfusionMatrix2::PrintErrorByProbByRows(), CrossValidationApp::PrintSizeHistogram(), KKU::Histogram::PrintTable(), MLL::ConfusionMatrix2::PrintTrueFalsePositivesTabDelimited(), MLL::ModelUsfCasCor::ProbabilitiesByClass(), MLL::SVMModel::ProbabilitiesByClass(), PicesInterface::PicesAbundanceCorrectionMatrix::ProbOfDetection(), PicesInterface::PicesAbundanceCorrectionMatrix::ProbOfFalseAlarm(), SipperHardware::InstrumentDataBatteryMeter::ProcessBatteryData(), KKU::Application::ProcessCmdLineParameters(), CrossValidationApp::ProcessCmdLineParameters(), MLL::TrainingConfiguration2::PromptForConfigurationFile(), PicesInterface::PicesFeatureVectorList::RandomizeOrder(), CrossValidationApp::RandomlySampleData(), CrossValidationApp::RandomlySelectedProcessResults(), MLL::FeatureNumList::RandomlySelectFeatures(), KKU::RBTree< Entry, CompareNodes, KeyType >::RBTree(), MLL::NormalizationParms::Read(), KKU::ReadImagePNG(), SipperFile.SipperFileSimple::ReadNextScanLine(), SipperFile.SipperBuff4Bit::ReadNextScanLine(), MLL::ModelDual::ReconcileProbAndVotes(), KKU::Raster::ReduceByFactor(), SipperHardware::InstrumentData::RefreshDataFields(), PicesInterface::PicesClass::RemoveAChild(), MLL::FeatureVectorList::RemoveEntriesWithMissingFeatures(), SipperFile.InstrumentDataReport::ReportData(), MLL::FeatureVector::ResetNumOfFeatures(), MLL::FeatureVectorList::ReSyncSymbolicData(), MLL::ModelDual::RetrieveCrossProbTable(), MLL::SVMModel::RetrieveCrossProbTable(), MLL::Model::RetrieveCrossProbTable(), KKU::Raster::ReverseImage(), KKU::KKStr::RightPad(), MLL::CrossValidation::RunCrossValidation(), MLL::CrossValidationVoting::RunCrossValidation(), SipperHardware::InstrumentDataList::Save(), KKU::Chart::Save(), SipperFile.SipperHeaderRec::Save(), SipperFile.DataRowList::Save(), SipperFile.InstrumentDataList::Save(), MLL::FeatureFileIORoberts::SaveFile(), MLL::FeatureFileIOUCI::SaveFile(), MLL::FeatureFileIOPices::SaveFile(), MLL::FeatureFileIOC45::SaveFile(), MLL::FeatureFileIOSparse::SaveFile(), KKU::BmpImage::SaveGrayscaleInverted4Bit(), KKU::BmpImage::SaveGrayscaleInverted8Bit(), KKU::SaveImagePNG(), SipperHardware::InstrumentDataManager::ScanLinesPerMeterDepth(), PicesInterface::PicesClass::SearchFamilyTree(), SearchStr(), PicesInterface::PicesClass::SearchTree(), KKU::SegmentorOTSU::SegmentImage(), KKU::SegmentorOTSU::SegmentMaskedImage(), MLL::ChainHashNode::SetSelectedFeatures(), KKU::Configuration::SettingList::SettingList(), KKU::RasterSipper::SimpleCompression(), SipperFile.Sipper3DecodeRec::Sipper3DecodeRec(), SipperDiskUtilities.SipperFileControlBlock::SipperFileControlBlock(), MLL::DataBase::SipperFileGetList(), SipperHardware::InstrumentDataFileManager::SipperFileRootNameFromSipperImageFileName(), SipperFile.SipperFrame::SipperFrame(), SipperHardware::SipperHeaderRec::SipperHeaderRec(), SipperDiskUtilities.SipperPartitionSector::SipperPartitionSector(), MLL::DataBaseImage::SizeCoordinates(), SplitImagesAmongstFolds(), MLL::FeatureVectorList::StratifyAmoungstClasses(), KKU::StrFormatDouble(), StripOutAnyComments(), StripOutInvalidLatexCaracters(), KKU::STRNICMP(), PicesInterface::PicesKKStr::StrToCharStar(), KKU::KKStr::StrWide(), KKU::KKStr::SubStrPart(), KKU::SegmentorOTSU::Sum(), SVM289_MFS::svm_load_model_XML_SupportVectorSection(), SVM289_BFS::svm_load_model_XML_SupportVectorSection(), SVM289_BFS::svm_parameter::svm_parameter(), SVM289_MFS::svm_parameter::svm_parameter(), MLL::SvmSaveModel(), SVM233::Swap(), KKU::Swap(), SVM289_BFS::swap(), SVM289_MFS::swap(), PicesInterface::PicesKKStr::SystemStringToKKStr(), PicesInterface::PicesKKStr::SystemStringToKKStrPtr(), MLL::BitReduction::TakeExampleGroups(), PicesInterface::ClassificationBiasMatrix::TestPaperResults(), KKU::Raster::ThinContour(), KKU::Raster::ThresholdInHSI(), MLL::FeatureNumList::ToBitString(), KKU::Raster::ToCompressor(), ToFloat(), MLL::FeatureNumList::ToString(), SVM233::svm_parameter::ToTabDelStr(), SVM289_BFS::svm_parameter::ToTabDelStr(), SVM289_MFS::svm_parameter::ToTabDelStr(), SipperHardware::InstrumentData::ToTabDelStr(), KKU::Raster::TotalBackgroundPixels(), MLL::FeatureVector::TotalOfFeatureData(), MLL::TrainingConfiguration2::TrainingConfiguration2(), KKU::KKStr::TrimLeft(), KKU::KKStr::TrimRight(), MLL::FeatureNumList::UnSet(), KKU::KKStr::Upper(), SipperDiskUtilities.SipperFileControlBlock::UserMessage(), SipperHardware::SipperCruise::ValidateCruiseName(), SipperFile.SipperBaseFile::ValidateFormat(), KKU::VectorToDelimitedStr(), MLL::AbundanceCorrectionMatrix::VectorToStr(), KKU::KKStr::Wide(), SipperFile.InstrumentData::WriteFieldList(), SipperFile.InstrumentData::WriteLine(), MLL::AbundanceCorrectionMatrix::WriteXml(), WriteXmlArrayFloat(), WriteXmlArrayInt(), KKU::SegmentorOTSU::ZeroOutNaN(), KKU::Chart::~Chart(), KKU::ImageDirTree::~ImageDirTree(), SipperHardware::InstrumentDataManager::~InstrumentDataManager(), SVM289_MFS::Kernel::~Kernel(), SVM289_BFS::Kernel::~Kernel(), SVM233::Kernel::~Kernel(), and MLL::SVMModel::~SVMModel().