Pices: KKU Namespace Reference
KKU Namespace Reference
KKU is a the namespace where all objects that belong to BaseLibrary are stored.
Classes
class Application
The base class for all standalone application.
class Atom
Base class of all other classes that is meant to be managed by 'BaseLibrary'.
struct BITMAPFILEHEADER
Windows bitmap header definition used for non-Windows systems.
struct BITMAPINFOHEADER
Windows bitmap information header definition used for non-Windows systems.
class BitString
Allows you to manage very long bit strings.
class Blob
Used by the Raster object to identify a distinct blob; where it is in the raster and its unique id.
class BlobList
Maintains a list of blobs.
class BmpImage
Used to encode and decode BMP Images.
class Chart
Used to Create chart's from defined series of data.
class CmdLineExpander
Expands command line parameters, by parsing for special parameters and expanding them to their full value.
class Compressor
Simple class that will compress and decompress specified buffers using the routines provided in zlib.
class Configuration
General purpose Configuration File manager class.
class ContourFollower
class ConvexHull
class DateTime
represents Date and Time, consists of two member classes DateType & TimeType.
class DateType
Represents a calendar date consisting of three fields, Year, Month, and Day.
class GlobalGoalKeeper
Maintains one instance of a GoalKeeper object that can be used anywhere in the application.
class GoalKeeper
Used to deal with issues related to thread synchronization issues when sharing the same variables.
class HashTable
class Histogram
Used to manage the construction of a Histogram.
class HTMLReport
class ImageDirTree
Creates a index of all images in a specified directory structure.
class Iterator
class KK_DFT
class KK_DFT2D
class KKStr
A string class providing safe runtime string management.
class KKStrException
class KKStrList
class KKStrListIndexed
Maintains a list of ordered KKStr instances that can be recalled by eithe string of index.
class KKStrMatrix
A two dimensional matrix of Strings.
class KKStrParser
Class that manages the extraction of tokens from a String without being destructive to the original string.
class KKThread
The base class to be used any thread.
class KKThreadList
class KKThreadManager
class Matrix
Supports two dimensional matrices.
struct MovDir
class MsgQueue
Will manage a buffer that will allow multiple threads to add and remove messages to a queue.
class PixelValue
Used by the Raster Class to represent the contents of one pixel.
class Point
Used by Raster class methods to denote a single pixel location in Raster image.
class PointList
Container object used to maintaining a list of pixel locations.
class RandomNumGenerator
Represents one single random number generator.
class Raster
A class that is used by to represent a single image in memory.
class RasterBuffer
Will manage a buffer that will allow multiple threads to add and remove instances of 'Raster' objects.
class RasterList
class RasterSipper
A class that is used by to represent a single Sipper Image in memory.
class RasterSipperList
class RBnode
class RBTree
struct RGBQUAD
RGBQUAD definition for non-windows systems.
class Row
class RunLog
Used for logging messages.
class SegmentorOTSU
class SimpleCompressor
class Sobel
class TimeType
Represents a Time, consisting of three fields, Hour, Minute, and Second.
class TokenBuffer
class TokenBufferStr
class TokenBufferStream
class Tokenizer
Class is meant to break down a stream into a set of logical tokens.
union WordFormat32Bits
Structure used to break 32 bit word into different formats;.
class XmlAttribute
class XmlContent
class XmlElement
class XmlStream
I created these Xml classes 2010-02-22 to someday simplify the reading and writing of objects to disk.
class XmlTag
class XmlToken
Typedefs
typedef struct
KKU::BITMAPFILEHEADER BITMAPFILEHEADER
typedef BitString * BitStringPtr
typedef BlobList * BlobListPtr
typedef Blob * BlobPtr
typedef BmpImage * BmpImagePtr
typedef unsigned char BYTE
typedef CmdLineExpander * CmdLineExpanderPtr
typedef Configuration * ConfigurationPtr
typedef char const *const *const ConstCharStarArray
typedef ConvexHull * ConvexHullPtr
typedef uint32 DWORD
typedef float FFLOAT
typedef GoalKeeper * GoalKeeperPtr
typedef HashEntry * HashEntryPtr
typedef Histogram * HistogramPtr
typedef HTMLReport::HTMLReportPtr HTMLReportPtr
typedef int16_t int16
16 bit signed integer.
typedef int32_t int32
typedef int64_t int64
typedef int8_t int8
8 bit signed integer.
typedef KK_DFT< double > KK_DFT1D_Double
typedef KK_DFT< float > KK_DFT1D_Float
typedef KK_DFT2D< double > KK_DFT2D_Double
typedef KK_DFT2D< float > KK_DFT2D_Float
typedef int8_t kkint8
8 bit signed integer.
typedef KKStr::KKStrConstPtr KKStrConstPtr
typedef KKStrList::KKStrListPtr KKStrListPtr
typedef KKStrMatrix::KKStrMatrixPtr KKStrMatrixPtr
typedef KKStr::KKStrPtr KKStrPtr
typedef KKThreadList * KKThreadListPtr
typedef KKThreadManager * KKThreadManagerPtr
typedef KKTHread * KKTHreadPtr
typedef KKThread::KKThreadPtr KKThreadPtr
typedef uint8_t kkuint8
8 bit unsigned integer.
typedef int32 LONG
typedef Matrix::MatrixPtr MatrixPtr
typedef MsgQueue::MsgQueuePtr MsgQueuePtr
typedef long long osFilePos
typedef PixelValue * PixelValuePtr
typedef PointList * PointListPtr
typedef Point * PointPtr
typedef
RasterBuffer::RasterBufferPtr RasterBufferPtr
typedef RasterList * RasterListPtr
typedef Raster * RasterPtr
typedef RasterSipperList * RasterSipperListPtr
typedef
RasterSipper::RasterSipperPtr RasterSipperPtr
typedef Row * RowPtr
typedef RunLog * RunLogPtr
typedef vector< SeriesPtr > SeriesList
typedef Chart::Series * SeriesPtr
typedef KKStrList::KKStrListPtr StringListPtr
For comparability with previous version.
typedef TokenBuffer * TokenBufferPtr
typedef TokenBufferStream * TokenBufferStreamPtr
typedef Tokenizer * TokenizerPtr
typedef unsigned char uchar
Unsigned character.
typedef unsigned int uint
Unsigned integer.
typedef uint16_t uint16
16 bit unsigned integer.
typedef uint32_t uint32
typedef uint64_t uint64
typedef uint8_t uint8
8 bit unsigned integer.
typedef unsigned long ulong
Unsigned long.
typedef unsigned short ushort
Unsigned short.
typedef std::vector< bool > VectorBool
typedef std::vector< char > VectorChar
typedef VectorChar * VectorCharPtr
typedef std::vector< double > VectorDouble
Vector of doubles.
typedef VectorDouble * VectorDoubletPtr
typedef std::vector< float > VectorFloat
typedef VectorFloat * VectorFloatPtr
typedef std::vector< int > VectorInt
typedef std::vector< int16 > VectorInt16
Vector of signed 16 bit integers.
typedef std::vector< int32 > VectorInt32
Vector of signed 16 bit integers.
typedef VectorInt * VectorIntPtr
typedef KKStr::VectorKKStr VectorKKStr
typedef vector< Point > VectorPoint
typedef std::vector< short > VectorShort
typedef VectorShort * VectorShortPtr
typedef std::vector< uchar > VectorUchar
typedef VectorUchar * VectorUcharPtr
typedef std::vector< uint > VectorUint
typedef std::vector< uint16 > VectorUint16
Vector of unsigned 16 bit integers.
typedef std::vector< uint32 > VectorUint32
Vector of unsigned 16 bit integers.
typedef std::vector< ulong > VectorUlong
typedef VectorUlong * VectorUlongPtr
typedef unsigned short WCHAR
typedef unsigned short WORD
typedef vector< XmlAttribute > XmlAttributeList
typedef XmlElement::XmlElementPtr XmlElementPtr
typedef XmlTag::XmlTagPtr XmlTagPtr
typedef XmlToken::XmlTokenPtr XmlTokenPtr
Enumerations
enum ColorChannels { RedChannel, GreenChannel, BlueChannel }
enum MaskTypes {
CROSS3 = 0, CROSS5 = 1, SQUARE3 = 2, SQUARE5 = 3,
SQUARE7 = 4, SQUARE9 = 5, SQUARE11 = 6
}
enum RBcolor { Red, Black }
Functions
template<typename T >
T Calc3TTLQC (const vector< T > &v, int32 b)
template<typename T >
T CalcBQV (const vector< T > &v, int32 blockSize)
template<typename T >
void CalcMeanAndStdDev (const vector< T > &v, T &mean, T &stdDev)
template<typename T >
T CalcPQV (const vector< T > &v, int32 distance)
template<typename T >
T CalcTTLQC (const vector< T > &v, int32 b)
template<typename T >
void CalcVectorStats (const vector< T > &v, T &total, T &mean, T &stdDev, T &min, T &max)
void DisplayImage (const Raster &raster, const KKStr &title)
void DisplayImage (const Raster &image)
HTMLReport & endl (HTMLReport &htmlReport)
void FFT (float data[], uint32 number_of_complex_samples, int32 isign)
fftwf_plan fftwCreateOneDPlan (int32 len, fftwf_complex *src, fftwf_complex *dest, int sign, int flag)
fftwf_plan fftwCreateTwoDPlan (int32 height, int32 width, fftwf_complex *src, fftwf_complex *dest, int sign, int flag)
void fftwDestroyPlan (fftwf_plan &plan)
bool IsFinite (const float &f)
bool IsFinite (const double &f)
bool IsNaN (const float &f)
bool IsNaN (const double &d)
float LLoydsIndexOfPatchiness (const KKU::VectorInt &bins)
float Log2 (float x)
int32 LRand48 ()
Returns a long int32 random value.
template<class T >
T Max (T a, T b)
generic Max function, Both parameters must be of the same type.
template<class T >
T Max (T a, T b, T c)
Generic Max function, that takes three parameters.
template<class T >
T Max (T a, T b, T c, T d)
Generic Max function, that takes four parameters.
float McNemarsTest (int32 size, const bool *classedCorrectly1, const bool *classedCorrectly2)
template<class T >
T Min (T a, T b)
Generic Min function, Both parameters must be of the same type.
template<class T >
T Min (T a, T b, T c)
Generic Min function, Both parameters must be of the same type.
KKStr operator+ (const char left, const KKStr &right)
KKStr operator+ (const char *left, const KKStr &right)
Matrix operator- (double left, const Matrix &right)
HTMLReport & operator<< (HTMLReport &htmlReport, HTMLReport &(*)(HTMLReport &))
HTMLReport & operator<< (HTMLReport &htmlReport, int32 right)
HTMLReport & operator<< (HTMLReport &htmlReport, uint32 right)
HTMLReport & operator<< (HTMLReport &htmlReport, long right)
HTMLReport & operator<< (HTMLReport &htmlReport, long long right)
HTMLReport & operator<< (HTMLReport &htmlReport, double right)
HTMLReport & operator<< (HTMLReport &htmlReport, unsigned long right)
HTMLReport & operator<< (HTMLReport &htmlReport, char right)
KKStr & operator<< (KKStr &left, const Point &right)
HTMLReport & operator<< (HTMLReport &htmlReport, const char *right)
std::ostream & operator<< (std::ostream &left, const Point &right)
HTMLReport & operator<< (HTMLReport &htmlReport, const KKStr &right)
HTMLReport & operator<< (HTMLReport &htmlReport, KKStrConstPtr right)
HTMLReport & operator<< (HTMLReport &htmlReport, const DateTime &right)
KKStr & operator<< (KKU::KKStr &left, const KKU::DateType &right)
std::ostream & operator<< (std::ostream &os, const KKU::DateType &right)
KKStr & operator<< (KKStr &left, const TimeType &right)
std::ostream & operator<< (std::ostream &os, const TimeType &right)
KKStr & operator<< (KKU::KKStr &left, const DateTime &right)
std::ostream & operator<< (std::ostream &os, const DateTime &right)
std::ostream & operator<< (std::ostream &os, const KKStr &str)
std::istream & operator>> (std::istream &os, KKStr &str)
void osAddLastSlash (KKStr &fileSpec)
Will add the appropriate Directory separator character to the end of fileSpec if one is not there already.
KKStr osAddSlash (const KKStr &fileSpec)
void osChangeDir (const KKStr &dirName, bool &successful)
bool osCopyFile (const KKStr &srcFileName, const KKStr &destFileName)
bool osCopyFileBetweenDirectories (const KKStr &_fileName, const KKStr &_srcDir, const KKStr &_destDir)
bool osCreateDirectory (const KKStr &dirName)
bool osCreateDirectoryPath (KKStr _pathName)
Will create the whole Directory Path not just the final part of the path.
KKStr osCreateUniqueFileName (KKStr fileName)
Get a unique file name based off file spec 'fileName'.
bool osDeleteFile (KKStr _fileName)
void osDisplayWarning (KKStr _message)
bool osFileExists (const KKStr &_fileName)
FILE * osFOPEN (const char *fileName, const char *mode)
KKStr osGetCurrentDirectory ()
KKStr osGetDirNameFromPath (KKStr dirPath)
Extracts the final sub-directory name of the fill directory specification.
char osGetDriveLetter (KKStr fileName)
Given a full drive with path and name return the drive letter specified.
KKStrPtr osGetEnvVariable (KKStr _varName)
KKStr osGetErrorNoDesc (int32 errorNo)
KKU::DateTime osGetFileDateTime (const KKStr &fileName)
KKStr osGetFileExtension (KKStr fullFileName)
KKStr osGetFileNamePartOfFile (KKStr fullFileName)
osGetFileNamePartOfFile, retrieves the file name part of the file spec.
int64 osGetFileSize (const KKStr &fileName)
KKStr osGetFullPathOfApplication ()
returns the name and path of th ecurrent running application.
KKStr osGetHostName ()
double osGetKernalTimeUsed ()
KKStrListPtr osGetListOfDirectories (KKStr fileSpec)
KKStrListPtr osGetListOfFiles (const KKStr &fileSpec)
Returns a list of files that match the provided file specification.
void osGetListOfFilesInDirectoryTree (const KKStr &rootDir, KKStr fileSpec, VectorKKStr &fileNames)
KKStrListPtr osGetListOfImageFiles (KKStr fileSpec)
KKU::DateTime osGetLocalDateTime ()
Returned the current local date and time.
int32 osGetNumberOfProcessors ()
returns the number of CPU's or number of simultaneous threads that you can have.
KKStr osGetParentDirectoryOfDirPath (KKStr path)
KKStr osGetParentDirPath (KKStr dirPath)
Returns the Parent directory path to 'dirPath'.
KKStr osGetPathPartOfFile (KKStr fullFileName)
Get the path part of a full file name specification.
int32 osGetProcessId ()
KKStr osGetProgName ()
KKStr osGetRootName (const KKStr &fullFileName)
KKStr osGetRootNameOfDirectory (KKStr fullDirName)
KKStr osGetRootNameWithExtension (const KKStr &fullFileName)
double osGetSystemTimeUsed ()
Returns the number of CPU seconds used by current process.
int32 osGetThreadId ()
KKStr osGetUserName ()
double osGetUserTimeUsed ()
template<class T >
T * osGrowAllocation (T *src, int32 origSize, int32 newSize)
bool osIsBackGroundProcess ()
int32 osLocateFirstSlashChar (const KKStr &fileSpec)
int32 osLocateLastSlashChar (const KKStr &fileSpec)
KKStr osLookForFile (const KKStr &fileName, const KKStr &srcDir)
Look for a specified file in a sub-directory structure.
KKStr osMakeFullFileName (const KKStr &_dirName, const KKStr &_fileName)
bool osMoveFileBetweenDirectories (const KKStr &_fileName, const KKStr &_srcDir, const KKStr &_destDir)
void osParseFileName (KKStr _fileName, KKStr &_dirPath, KKStr &_rootName, KKStr &_extension)
void osParseFileSpec (KKStr fullFileName, KKStr &driveLetter, KKStr &path, KKStr &root, KKStr &extension)
char * osReadNextLine (FILE *in)
Read the next line from the file and return a c-String(NULL terminated).
KKStr osReadNextQuotedStr (FILE *in, const char *whiteSpaceCharacters, bool &eof)
Read the next Quoted String from the file.
KKStr osReadNextToken (FILE *in, const char *delimiters, bool &eof, bool &eol)
Read the next logical token from a file using characters in 'delimiters' to separate tokens.
KKStr osReadNextToken (std::istream &in, const char *delimiters, bool &eof, bool &eol)
Read the next logical token from a file using characters in 'delimiters' to separate tokens.
KKStr osReadRestOfLine (std::istream &in, bool &eof)
KKStr osReadRestOfLine (FILE *in, bool &eof)
KKStr osRemoveExtension (const KKStr &_fullFileName)
bool osRenameFile (const KKStr &oldName, const KKStr &newName)
void osRunAsABackGroundProcess ()
void osSkipRestOfLine (FILE *in, bool &eof)
Skips rest of the characters in the current line in the file.
void osSkipRestOfLine (std::istream &in, bool &eof)
Skips rest of the characters in the current line in the input stream.
void osSleep (float numOfSecs)
VectorKKStr osSplitDirectoryPathIntoParts (const KKStr &path)
KKStr osSubstituteInEvironmentVariables (const KKStr &src)
Substitute in the value of the environment variables into 'src'.
bool osValidDirectory (KKStrConstPtr _name)
bool osValidDirectory (const KKStr &_name)
void osWaitForEnter ()
float PairedTTest (const KKU::VectorFloat &set1, const KKU::VectorFloat &set2)
RasterPtr ReadImage (const KKStr &imageFileName)
RasterPtr ReadImagePGM (const KKStr &imageFileName)
RasterPtr ReadImagePNG (const KKStr &imageFileName)
void SaveImage (const Raster &image, const KKStr &imageFileName)
void SaveImageGrayscaleInverted4Bit (const Raster &image, const KKStr &_fileName)
Saves image as BMP file using 4 bit compressed grayscale where Background = 255 and foreground = 0.
void SaveImageGrayscaleInverted8Bit (const Raster &image, const KKStr &_fileName)
Saves image as BMP using compressed grayscale where Background = 255 and foreground = 0.
void SaveImageInverted (Raster &raster, const KKStr &imageFileName)
void SaveImagePGM (const Raster &image, const KKStr &imageFileName)
void SaveImagePNG (const Raster &image, const KKStr &imageFileName)
RasterPtr SegmentPolutionImage (RasterPtr r, KKStr fileName)
int32 SPRINTF (char *buff, int32 buffSize, const char *formatSpec, int16 right)
int32 SPRINTF (char *buff, int32 buffSize, const char *formatSpec, uint16 right)
int32 SPRINTF (char *buff, int32 buffSize, const char *formatSpec, int32 right)
int32 SPRINTF (char *buff, int32 buffSize, const char *formatSpec, uint32 right)
int32 SPRINTF (char *buff, int32 buffSize, const char *formatSpec, int64 right)
int32 SPRINTF (char *buff, int32 buffSize, const char *formatSpec, uint64 right)
int32 SPRINTF (char *buff, int32 buffSize, const char *formatSpec, int32 precision, double d)
int32 SPRINTF (char *buff, int32 buffSize, char const *formatSpec, double d)
void SRand48 (int64 _seed)
Seeds the lrand48 functions with the parameters passed to it.
char * STRCAT (char *dest, int32 destSize, const char *src)
char * STRCOPY (char *dest, int32 destSize, const char *src)
char * STRCOPY (char *dest, uint16 destSize, const char *src)
char * STRDUP (const char *src)
KKStr StrFormatDouble (double val, const char *mask)
KKStr StrFormatInt (int32 val, const char *mask)
KKStr StrFormatInt64 (int64 val, const char *mask)
KKStr StrFromInt16 (int16 i)
KKStr StrFromInt32 (int32 i)
KKStr StrFromInt64 (int64 i)
KKStr StrFromUint16 (uint16 ui)
KKStr StrFromUint32 (uint32 ui)
KKStr StrFromUint64 (uint64 ui)
int32 STRICMP (const char *left, const char *right)
Comapares to string, case insensative, returning (-1 = less) (0 = equal), and (1 = greater).
int32 STRNICMP (const char *left, const char *right, int32 len)
bool SupportedImageFileFormat (const KKStr &imageFileName)
template<class T >
T Swap (T &x, T &y)
void tqli (int32 n, double *d, double *e, double z[2][2])
void Tred2 (int32 n, double a[2][2], double *d, double *e)
template<typename T >
KKStr VectorToDelimitedStr (std::vector< T > v, char delimiter)
Detailed Description
KKU is a the namespace where all objects that belong to BaseLibrary are stored.
Kurt Kramer Utilities (KKU) aka BaseLibrary.
Kurt Kramer Utilities This namespace is intended to gather BaseLibrary Classes together.
The idea is that any objects and functions that are not specific to any particular end application are placed in this namespace. Such as Raster for image processing, KKStr for string management, OSservices for operating specific function calls.
I started on this library in 1994 and have been adding to it incrementally as functionality was needed. For the last 5 years the main driving force has been my work on the SIPPER. project.
Author
Kurt Kramer, Ph.D. University of South Florida.
Kurt Kramer.
(mail : kurtkramer@gmail.com)
Author
Kurt Kramer.
(mail : kurtkramer@gmail.com)
Introduction
The BaseLibrary is my tool box of handy objects that I have been building since 1994. It contains classes for string management(KKStr), Floating point Matrix operations, Image Processing Routines, common operating system routines, Statistics, Histogramming, etc.
Platform Independence
All classes are meant to be Platform independent. That is from the outside there should be no need to worry about which O/S platform you are building for. All O/S specific code will be internal to BaseLibrary (KKU) classes. For the most part all functions that require O/S specific knowledge are implemented in OSServices.h. There are a couple of exceptions such as GoalKeeper and ImageIO.h.
Other Required Libraries
To use al the classes in this Library you are also going to need the outside libraries fftw and zlib123. "fftw" stands for "Fastest Fourier Transform in The West". It can be down loaded from http://www.fftw.org/. "zlib123" is a library that is used to compress and uncompress data. can be found at http://www.zlib.net/. It is used by the Compressor class.
KKQueue
I have a container template called KKQueue that is derived from the std::vector<> template. It is specifically meant to work with pointers to its contents and understands the concept of ownership. That is a instance of a KKQueue template either owns its contents or it does not. If it owns them it will call the individual destructors for each item that it contains when its destructor is called. Many classes that I have written use this template so it would be worth reading its documentation.
Image Processing
There are several classes that aid in Image Processing. The primary class is Raster which can handle both Grayscale and Color images. It supports various morphological operations as well as Connected Component Analysis, Fourier transform, etc. Other classes that work with Raster are Blob, BMPheader, BMPheader.h, ContourFollower, Histogram, ImageIO.h, PixelValue, Point, and Sobel.
Typedef Documentation
typedef struct KKU::BITMAPFILEHEADER KKU::BITMAPFILEHEADER
typedef BitString* KKU::BitStringPtr
Definition at line 159 of file BitString.h.
typedef BlobList * KKU::BlobListPtr
Definition at line 121 of file Blob.h.
typedef Blob * KKU::BlobPtr
Definition at line 67 of file Blob.h.
typedef BmpImage * KKU::BmpImagePtr
Definition at line 290 of file BMPImage.h.
typedef unsigned char KKU::BYTE
Definition at line 31 of file BMPheader.h.
typedef CmdLineExpander* KKU::CmdLineExpanderPtr
Definition at line 75 of file CmdLineExpander.h.
typedef Configuration* KKU::ConfigurationPtr
Definition at line 149 of file Configuration.h.
typedef char const* const* const KKU::ConstCharStarArray
Definition at line 129 of file BasicTypes.h.
typedef ConvexHull* KKU::ConvexHullPtr
Definition at line 89 of file ConvexHull.h.
typedef uint32 KKU::DWORD
Definition at line 29 of file BMPheader.h.
typedef float KKU::FFLOAT
Definition at line 153 of file BasicTypes.h.
typedef GoalKeeper * KKU::GoalKeeperPtr
Definition at line 14 of file GlobalGoalKeeper.h.
typedef HashEntry* KKU::HashEntryPtr
Definition at line 15 of file HashTable.h.
typedef Histogram * KKU::HistogramPtr
Definition at line 133 of file Histogram.h.
typedef HTMLReport::HTMLReportPtr KKU::HTMLReportPtr
Definition at line 63 of file HTMLReport.h.
typedef int16_t KKU::int16
16 bit signed integer.
Definition at line 112 of file BasicTypes.h.
typedef int32_t KKU::int32
Definition at line 115 of file BasicTypes.h.
typedef int64_t KKU::int64
Definition at line 117 of file BasicTypes.h.
typedef int8_t KKU::int8
8 bit signed integer.
Definition at line 108 of file BasicTypes.h.
typedef KK_DFT<double> KKU::KK_DFT1D_Double
Definition at line 172 of file kku_fftw.h.
typedef KK_DFT<float> KKU::KK_DFT1D_Float
Definition at line 171 of file kku_fftw.h.
typedef KK_DFT2D<double> KKU::KK_DFT2D_Double
Definition at line 220 of file kku_fftw.h.
typedef KK_DFT2D<float> KKU::KK_DFT2D_Float
Definition at line 219 of file kku_fftw.h.
typedef int8_t KKU::kkint8
8 bit signed integer.
Definition at line 109 of file BasicTypes.h.
typedef KKStr::KKStrConstPtr KKU::KKStrConstPtr
Definition at line 645 of file Str.h.
typedef KKStrList::KKStrListPtr KKU::KKStrListPtr
Definition at line 828 of file Str.h.
typedef KKStrMatrix::KKStrMatrixPtr KKU::KKStrMatrixPtr
Definition at line 963 of file Str.h.
typedef KKStr * KKU::KKStrPtr
Definition at line 644 of file Str.h.
typedef KKThreadList * KKU::KKThreadListPtr
Definition at line 15 of file KKThread.h.
typedef KKThreadManager * KKU::KKThreadManagerPtr
Definition at line 11 of file KKThread.h.
typedef KKTHread* KKU::KKTHreadPtr
Definition at line 16 of file KKThreadManager.h.
typedef KKThread::KKThreadPtr KKU::KKThreadPtr
Definition at line 138 of file KKThread.h.
typedef uint8_t KKU::kkuint8
8 bit unsigned integer.
Definition at line 111 of file BasicTypes.h.
typedef int32 KKU::LONG
Definition at line 30 of file BMPheader.h.
typedef Matrix * KKU::MatrixPtr
Definition at line 181 of file Matrix.h.
typedef MsgQueue * KKU::MsgQueuePtr
Definition at line 68 of file MsgQueue.h.
typedef long long KKU::osFilePos
Definition at line 21 of file OSservices.h.
typedef PixelValue* KKU::PixelValuePtr
Definition at line 28 of file BMPImage.h.
typedef PointList::PointListPtr KKU::PointListPtr
Definition at line 17 of file ContourFollower.h.
typedef Point * KKU::PointPtr
Definition at line 15 of file ContourFollower.h.
typedef RasterBuffer::RasterBufferPtr KKU::RasterBufferPtr
Definition at line 100 of file RasterBuffer.h.
typedef RasterList * KKU::RasterListPtr
Definition at line 73 of file Raster.h.
typedef Raster * KKU::RasterPtr
Definition at line 25 of file BMPImage.h.
typedef RasterSipperList * KKU::RasterSipperListPtr
Definition at line 33 of file RasterSipper.h.
typedef RasterSipper::RasterSipperPtr KKU::RasterSipperPtr
Definition at line 411 of file RasterSipper.h.
typedef Row* KKU::RowPtr
Definition at line 33 of file Matrix.h.
typedef RunLog* KKU::RunLogPtr
Definition at line 185 of file RunLog.h.
typedef vector<SeriesPtr> KKU::SeriesList
Definition at line 85 of file Chart.cpp.
typedef Chart::Series* KKU::SeriesPtr
Definition at line 83 of file Chart.cpp.
typedef KKStrList::KKStrListPtr KKU::StringListPtr
For comparability with previous version.
Definition at line 829 of file Str.h.
typedef TokenBuffer* KKU::TokenBufferPtr
Definition at line 29 of file TokenBuffer.h.
typedef TokenBufferStream* KKU::TokenBufferStreamPtr
Definition at line 79 of file TokenBuffer.h.
typedef Tokenizer* KKU::TokenizerPtr
Definition at line 82 of file Tokenizer.h.
typedef unsigned char KKU::uchar
Unsigned character.
Definition at line 75 of file BasicTypes.h.
typedef unsigned int KKU::uint
Unsigned integer.
Definition at line 76 of file BasicTypes.h.
typedef uint16_t KKU::uint16
16 bit unsigned integer.
Definition at line 113 of file BasicTypes.h.
typedef uint32_t KKU::uint32
Definition at line 116 of file BasicTypes.h.
typedef uint64_t KKU::uint64
Definition at line 118 of file BasicTypes.h.
typedef uint8_t KKU::uint8
8 bit unsigned integer.
Definition at line 110 of file BasicTypes.h.
typedef unsigned long KKU::ulong
Unsigned long.
Definition at line 78 of file BasicTypes.h.
typedef unsigned short KKU::ushort
Unsigned short.
Definition at line 77 of file BasicTypes.h.
typedef std::vector<bool> KKU::VectorBool
Definition at line 131 of file BasicTypes.h.
typedef std::vector<char> KKU::VectorChar
Definition at line 132 of file BasicTypes.h.
typedef VectorChar* KKU::VectorCharPtr
Definition at line 145 of file BasicTypes.h.
typedef std::vector<double> KKU::VectorDouble
Vector of doubles.
Definition at line 142 of file BasicTypes.h.
typedef VectorDouble* KKU::VectorDoubletPtr
Definition at line 150 of file BasicTypes.h.
typedef std::vector<float> KKU::VectorFloat
Definition at line 143 of file BasicTypes.h.
typedef VectorFloat* KKU::VectorFloatPtr
Definition at line 149 of file BasicTypes.h.
typedef std::vector<int> KKU::VectorInt
Definition at line 134 of file BasicTypes.h.
typedef std::vector<int16> KKU::VectorInt16
Vector of signed 16 bit integers.
Definition at line 136 of file BasicTypes.h.
typedef std::vector<int32> KKU::VectorInt32
Vector of signed 16 bit integers.
Definition at line 140 of file BasicTypes.h.
typedef VectorInt* KKU::VectorIntPtr
Definition at line 147 of file BasicTypes.h.
typedef KKStr::VectorKKStr KKU::VectorKKStr
Definition at line 648 of file Str.h.
typedef vector<Point> KKU::VectorPoint
Definition at line 67 of file Point.h.
typedef std::vector<short> KKU::VectorShort
Definition at line 138 of file BasicTypes.h.
typedef VectorShort* KKU::VectorShortPtr
Definition at line 151 of file BasicTypes.h.
typedef std::vector<uchar> KKU::VectorUchar
Definition at line 133 of file BasicTypes.h.
typedef VectorUchar* KKU::VectorUcharPtr
Definition at line 146 of file BasicTypes.h.
typedef std::vector<uint> KKU::VectorUint
Definition at line 135 of file BasicTypes.h.
typedef std::vector<uint16> KKU::VectorUint16
Vector of unsigned 16 bit integers.
Definition at line 137 of file BasicTypes.h.
typedef std::vector<uint32> KKU::VectorUint32
Vector of unsigned 16 bit integers.
Definition at line 141 of file BasicTypes.h.
typedef std::vector<ulong> KKU::VectorUlong
Definition at line 139 of file BasicTypes.h.
typedef VectorUlong* KKU::VectorUlongPtr
Definition at line 148 of file BasicTypes.h.
typedef unsigned short KKU::WCHAR
Definition at line 114 of file BasicTypes.h.
typedef unsigned short KKU::WORD
Definition at line 28 of file BMPheader.h.
typedef vector<XmlAttribute> KKU::XmlAttributeList
Definition at line 39 of file XmlStream.h.
typedef XmlElement::XmlElementPtr KKU::XmlElementPtr
Definition at line 109 of file XmlStream.h.
typedef XmlTag::XmlTagPtr KKU::XmlTagPtr
Definition at line 72 of file XmlStream.h.
typedef XmlToken::XmlTokenPtr KKU::XmlTokenPtr
Definition at line 91 of file XmlStream.h.
Enumeration Type Documentation
enum KKU::ColorChannels
Enumerator
RedChannel
GreenChannel
BlueChannel
Definition at line 70 of file Raster.h.
enum KKU::MaskTypes
Enumerator
CROSS3
CROSS5
SQUARE3
SQUARE5
SQUARE7
SQUARE9
SQUARE11
Definition at line 58 of file Raster.h.
enum KKU::RBcolor
Enumerator
Red
Black
Definition at line 30 of file RBTree.h.
Function Documentation
template<typename T > T KKU::Calc3TTLQC (const vector< T > & v, int32 b)
Definition at line 240 of file StatisticalFunctions.h.
template<typename T > T KKU::CalcBQV (const vector< T > & v, int32 blockSize)
Definition at line 119 of file StatisticalFunctions.h.
References x.
template<typename T > void KKU::CalcMeanAndStdDev (const vector< T > & v, T & mean, T & stdDev)
Definition at line 14 of file StatisticalFunctions.h.
Referenced by MLL::CrossValidation::RunCrossValidation(), MLL::CrossValidationMxN::RunTrainAndTest(), MLL::CrossValidation::RunValidationOnly(), and MLL::CrossValidationMxN::RunValidations().
template<typename T > T KKU::CalcPQV (const vector< T > & v, int32 distance)
Definition at line 169 of file StatisticalFunctions.h.
References x.
template<typename T > T KKU::CalcTTLQC (const vector< T > & v, int32 b)
Definition at line 201 of file StatisticalFunctions.h.
template<typename T > void KKU::CalcVectorStats (const vector< T > & v, T & total, T & mean, T & stdDev, T & min, T & max)
Definition at line 58 of file StatisticalFunctions.h.
void KKU::DisplayImage (const Raster & raster, const KKStr & title)
void KKU::DisplayImage (const Raster & image)
Definition at line 661 of file ImageIO.cpp.
References endl(), KKU::Raster::GetPixelValue(), KKU::Raster::Height(), and KKU::Raster::Width().
HTMLReport &__cdecl KKU::endl (HTMLReport & htmlReport)
Definition at line 235 of file HTMLReport.cpp.
References KKU::HTMLReport::Append().
Referenced by MLL::UsfCasCor::_load_training_example(), KKU::Chart::AddAValue(), MLL::FeatureNumList::AddFeature(), MLL::FeatureVector::AddFeatureData(), MLL::AbundanceCorrectionMatrix::AddIn(), MLL::ClassAssignments::AddMLClass(), MLL::MLClassConstList::AddMLClass(), MLL::MLClassList::AddMLClass(), KKU::MsgQueue::AddMsg(), ImageExtractionManager::ImageExtractionThread::AddMsg(), KKU::KKThread::AddMsg(), KKU::BmpImage::CodedPixels::AddPixel(), MLL::FeatureVectorList::AddQueue(), KKU::RasterBuffer::AddRaster(), MLL::AbundanceCorrectionMatrix::AdjustClassificationCounts(), MLL::UsfCasCor::allocate_network(), MLL::Model::AllocatePredictionVariables(), KKU::KKStr::Append(), MLL::FeatureFileIO::AppendToFile(), KKU::Histogram::AreaInRange(), KKU::Histogram::AverageOfMaxBucketExcludingRange(), KKU::Histogram::AverageOfMaxBucketInRange(), KKU::Histogram::AverageOfMinBucketInRange(), PicesInterface::TrainingModel2::BinaryProbailitiesForClass(), KKU::KKStrList::BinarySearch(), MLL::FeatureVectorList::BinarySearchByName(), KKU::BitString::BitString(), JobManagment::JobManager::Block(), KKU::BmpImage::BlueRow(), KKU::BmpImage::BmpImage(), KKU::Histogram::Bucket(), KKU::Matrix::BuildFromArray(), MLL::ConfusionMatrix2::BuildFromIstreamXML(), PicesInterface::TrainingModel2::BuildTrainingModel(), MLL::ModelParamOldSVM::C_Param(), MLL::SVMparam::C_Param(), KKU::Matrix::CalcCoFactorMatrix(), MLL::FeatureVectorList::CalcStatsForFeatureNum(), KKU::RBTree< Entry, CompareNodes, KeyType >::CalcTreeStats(), MLL::FileDesc::Cardinality(), MLL::MLClass::ChangeNameOfClass(), CrossValidationApp::CheckForDuplicates(), MLL::Classifier2::Classifier2(), MLL::FeatureVector::ClassName(), MLL::FeatureVectorList::ClassStatisticsStr(), CrossValidationApp::CmdLineHelp(), CompareTwoGroups(), SipperHardware::InstrumentDataManager::CompReportLine(), MLL::FeatureEncoder::Compress(), MLL::FeatureEncoder2::CompressExamples(), KKU::Matrix::Covariance(), KKU::GoalKeeper::Create(), KKU::GoalKeeper::CreateAndStartBlock(), CreateBfsFromMfs(), KKU::Compressor::CreateCompressedBuffer(), KKU::SimpleCompressor::CreateCompressedBuffer(), MLL::CrossValidationThreeWay::CreateDistanceReport(), MLL::FeatureEncoder2::CreateEncodedFileDesc(), MLL::FeatureEncoder::CreateEncodedFileDesc(), SipperHardware::InstrumentData::CreateFieldIndirectionVectorFromTabDelStr(), KKU::ContourFollower::CreateFourierDescriptorBySampling(), MLL::TrainingConfiguration2::CreateFromDirectoryStructure(), MLL::TrainingConfiguration2::CreateFromFeatureVectorList(), SipperHardware::InstrumentDataList::CreateFromSipperFile(), MLL::Model::CreateFromStream(), KKU::Histogram::CreateGraph(), KKU::Raster::CreateGrayScaleKLT(), KKU::Raster::CreateGrayScaleKLTOnMaskedArea(), MLL::ModelParam::CreateModelParam(), MLL::TrainingProcess2::CreateModelsFromTrainingData(), MLL::Orderings::CreateOrderingsObjFromFileIfAvaliable(), KKU::BmpImage::CodedPixels::CreatePixelDataStructure8Bit(), MLL::CrossValidationThreeWay::CreateProbabilityReport(), CrossValidationApp::CrossValidate(), MLL::DataBase::DataBase(), KKU::SimpleCompressor::Decompress(), KKU::Compressor::Decompress(), KKU::RBTree< Entry, CompareNodes, KeyType >::DeleteCurrentNode(), KKU::Matrix::DeterminantSlow(), DetermineCropSettings(), DetermineCropSettingsForDeployment(), MLL::FileDesc::DisplayAttributeMappings(), ImageExtractionManager::ExtractionParms::DisplayExampleCmdLine(), DisplayImage(), SipperHardware::SipperBuff::DisplaySipperRec(), MLL::SVMModel::DistanceFromDecisionBoundary(), CrossValidationApp::DistributesImagesRandomlyWithInFolds(), MLL::ChainHash< T >::DoSomeStats(), KKU::Raster::DrawLine(), KKU::Matrix::EigenVectors(), JobManagment::JobManager::EndBlock(), MLL::DataBase::ErrorLogMsg(), MLL::TrainingProcess2::ExtractTrainingClassFeatures(), KKU::Raster::FastFourier(), KKU::Raster::FastFourierKK(), MLL::FeatureNumList::FeatureAttributeType(), MLL::FeatureVector::FeatureData(), MLL::DataBase::FeatureDataCreateTable(), MLL::DataBase::FeatureDataForImageGroup(), MLL::DataBase::FeatureDataRecLoad(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::FeatureEncoder::FeatureEncoder(), MLL::FeatureEncoder2::FeatureEncoder2(), MLL::FeatureNumList::FeatureNumList(), SipperHardware::InstrumentData::FieldToStr(), MLL::DataBase::FinalCleanUp(), MLL::SVMModel::FindWorstSupportVectors(), MLL::SVMModel::FindWorstSupportVectors2(), MLL::SipperExtractionImageManager::Flush(), MLL::ConfusionMatrix2::FMeasure(), MLL::CrossValidationThreeWay::FoldAccuracy(), MLL::CrossValidation::FoldAccuracy(), MLL::CrossValidationVoting::FoldAccuracy(), MLL::CrossValidation::FoldAccuracysToStr(), KKU::ContourFollower::FollowContour(), KKU::ContourFollower::FollowContour2(), KKU::Raster::FourierExtractFeatures(), ImageExtractionManager::FrameExtractorThread::FrameExtractorThread(), KKU::RasterSipper::FromCompressor(), KKU::RasterSipper::FromSimpleCompression(), MLL::TrainingConfiguration2::GenerateAConfiguraionForAHierarchialLevel(), KKU::ContourFollower::GenerateContourList(), SipperHardware::InstrumentDataFileManager::GetClosestInstrumentData(), MLL::FeatureFileIODstWeb::GetFileDesc(), MLL::FeatureFileIORoberts::GetFileDesc(), MLL::FeatureFileIOC45::GetFileDesc(), MLL::FeatureFileIOColumn::GetFileDesc(), MLL::FeatureFileIOUCI::GetFileDesc(), MLL::FeatureFileIOPices::GetFileDesc(), MLL::FeatureFileIOSparse::GetFileDesc(), MLL::ClassAssignments::GetMLClassByIndex(), SipperHardware::Sipper3RevBuff::GetNextLine(), SipperHardware::SipperBuff3Bit::GetNextLine(), SipperHardware::SipperBuffBinary::GetNextLine(), SipperHardware::Sipper3Buff::GetNextLine(), MLL::Attribute::GetNominalValue(), KKU::Histogram::GetPeakAvgByHighestOrder(), KKU::Raster::GetPixelValue(), KKU::Raster::GetSubSet(), SipperHardware::InstrumentDataList::GetVolumePerMeterProfile(), MLL::ChainHash< T >::GroupExamples(), SipperHardware::SipperBuff::GuessFormatOfFile(), KKU::Histogram::Histogram(), KKU::Raster::HistogramEqualizedImage(), KKU::HTMLReport::HTMLReport(), MLL::DataBase::ImageFullSizeSave(), MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageGroupEntriesInsert(), MLL::DataBase::ImageGroupEntriesLoad(), MLL::DataBase::ImageGroupLoad(), MLL::DataBase::ImageLoad(), KKU::BmpImage::ImageRow(), MLL::DataBase::ImageUpdateInstrumentDataFields(), KKU::Histogram::Increment(), MLL::ConfusionMatrix2::Increment(), JobManagment::JobManager::InitilizeJobManager(), MLL::ChainHash< T >::insert(), MLL::DataBase::InsertCruise(), MLL::UsfCasCor::INSTALL_NEW_UNIT(), MLL::DataBase::InstrumentDataBinByMeterDepth(), MLL::DataBase::InstrumentDataGetVolumePerMeterDepth(), MLL::DataBase::InstrumentDataLoadAllSipperFiles(), SipperHardware::InstrumentDataManager::InstrumentDataManager(), MLL::DataBase::InstrumentDataReFreshSipperFile(), MLL::DataBase::InstrumentDataRetrieveGPSInfo(), KKU::Matrix::Inverse(), SVM289_MFS::Kernel::k_function(), SVM289_BFS::Kernel::k_function(), KKU::KKStr::KKStr(), KKU::KKStrException::KKStrException(), KKU::KKStr::LeftPad(), MLL::DuplicateImages::ListOfExamplesToDelete(), KKU::BitString::ListOfSetBits16(), MLL::ClassAssignments::Load(), MLL::DataBaseImageValidatedEntryList::Load(), MLL::SVMparam::Load(), MLL::FeatureNumList::Load(), MLL::MLClassConstList::Load(), MLL::Model::Load(), MLL::MLClassList::Load(), MLL::UsfCasCor::load_data(), PicesInterface::TrainingModel2::LoadExistingTrainedModel(), MLL::TrainingConfiguration2::LoadFeatureDataFromTrainingLibraries(), MLL::FeatureFileIOC45::LoadFeatureFile(), MLL::FeatureFileIO::LoadFeatureFile(), MLL::FeatureFileIODstWeb::LoadFile(), MLL::FeatureFileIORoberts::LoadFile(), MLL::FeatureFileIOColumn::LoadFile(), MLL::FeatureFileIOUCI::LoadFile(), MLL::FeatureFileIOPices::LoadFile(), MLL::FeatureFileIOC45::LoadFile(), MLL::FeatureFileIOSparse::LoadFile(), KKU::Configuration::LoadFile(), MLL::FeatureFileIOPices::LoadInSubDirectoryTree(), MLL::DataBaseUpdate::LoadSourceFile(), PicesInterface::TrainingModel2::LoadTrainigLibrary(), PicesInterface::TrainingModel2::LoadTrainingModelForGivenLevel(), MLL::DataBase::LogEntriesProcessEnd(), MLL::FeatureVectorList::LookUpByRootName(), CrossValidationApp::Main(), ImageExtractionManager::ExtractionManager::ManageTheExtraction(), MarineSnowReportDeployment(), KKU::Matrix::Matrix(), MLL::FileDesc::MergeSymbolicFields(), MLL::DataBase::MLClassLoad(), PicesInterface::PicesDataBase::MLClassLoadList(), MLL::DataBase::MLClassLoadList(), MLL::NormalizationParms::NormalizeImages(), SipperHardware::SipperBuff::Open(), KKU::KKStrMatrix::operator()(), KKU::Matrix::operator*(), MLL::FeatureNumList::operator*(), KKU::Matrix::operator+(), MLL::FeatureNumList::operator+(), MLL::ClassStatistic::operator+=(), KKU::Matrix::operator+=(), KKU::Matrix::operator-(), MLL::FeatureNumList::operator-(), KKU::KKStr::operator<<(), operator<<(), KKU::Matrix::operator[](), KKU::Row::operator[](), MLL::FeatureNumList::operator[](), KKU::KKStrMatrix::operator[](), MLL::Orderings::Orderings(), MLL::FeatureVectorList::OrderUsingNamesFromAFile(), osChangeDir(), osCopyFile(), osCopyFileBetweenDirectories(), osCreateDirectoryPath(), osDisplayWarning(), osMoveFileBetweenDirectories(), osRenameFile(), osSleep(), osWaitForEnter(), MLL::BitReduction::output_nominal_counts(), PairedTTest(), MLL::ModelOldSVM::Param(), ImageExtractionManager::ExtractionParms::ParseCmdLine(), MLL::ModelParam::ParseCmdLine(), MLL::ModelParamOldSVM::ParseCmdLine(), MLL::SVMparam::ParseCmdLineParameter(), MLL::FeatureFileIOPices::PlanktonFieldName(), CrossValidationApp::PostMisclassifiedImage(), MLL::ModelUsfCasCor::Predict(), MLL::ModelSvmBase::Predict(), MLL::ModelDual::Predict(), MLL::AbundanceCorrectionMatrix::Prediction(), KKU::BmpImage::Print(), MLL::ConfusionMatrix2::PrintAccuracyByProbByClassHTML(), MLL::FeatureVectorList::PrintClassStatistics(), MLL::FeatureVectorList::PrintClassStatisticsHTML(), MLL::ConfusionMatrix2::PrintConfusionMatrix(), MLL::ConfusionMatrix2::PrintConfusionMatrixAvgPredProbHTML(), MLL::ConfusionMatrix2::PrintConfusionMatrixLatexTable(), MLL::ConfusionMatrix2::PrintConfusionMatrixNarrow(), MLL::AbundanceCorrectionMatrix::PrintConfusionMatrixTabDelimited(), MLL::ConfusionMatrix2::PrintConfusionMatrixTabDelimited(), MLL::SizeDistribution::ClassTotals::PrintCSVLine(), MLL::ConfusionMatrix2::PrintErrorByProb(), MLL::ConfusionMatrix2::PrintErrorByProbByRows(), MLL::ConfusionMatrix2::PrintErrorBySize(), MLL::ConfusionMatrix2::PrintErrorBySizeByRows(), MLL::ConfusionMatrix2::PrintErrorBySizeReduced(), MLL::FeatureVectorList::PrintFeatureStatisticsByClass(), MLL::SizeDistribution::ClassTotals::PrintFormatedLine(), KKU::Configuration::PrintFormatErrors(), KKU::Raster::PrintOutListOfAllocatedrasterInstances(), MLL::ConfusionMatrix2::PrintProbDistributionTitle(), MLL::ConfusionMatrix2::PrintProbDistributionTotalCount(), MLL::ConfusionMatrix2::PrintProbDistributionTotalError(), MLL::ClassStatisticList::PrintReport(), MLL::SizeDistribution::ClassTotals::PrintTabDelLine(), KKU::Histogram::PrintTable(), MLL::ConfusionMatrix2::PrintTrueFalsePositivesTabDelimited(), MLL::ModelKnn::ProbabilitiesByClass(), MLL::ModelUsfCasCor::ProbabilitiesByClass(), MLL::ModelSvmBase::ProbabilitiesByClass(), MLL::ModelOldSVM::ProbabilitiesByClass(), MLL::ModelDual::ProbabilitiesByClass(), MLL::SVMModel::ProbabilitiesByClass(), MLL::ModelDual::ProbabilitiesByClassDual(), MLL::UsfCasCor::process_line(), CrossValidationApp::ProcessCmdLineParameter(), CrossValidationApp::ProcessCmdLineParameters(), JobManagment::Job::ProcessStatusField(), JobManagment::Job::ProcessStatusStr(), MLL::TrainingConfiguration2::PromptForConfigurationFile(), MLL::DuplicateImages::PurgeDuplicates(), MLL::MLClassConstList::PushOnBack(), JobManagment::JobList::PushOnBack(), MLL::MLClassList::PushOnBack(), MLL::FeatureVectorList::PushOnBack(), MLL::MLClassConstList::PushOnFront(), MLL::MLClassList::PushOnFront(), MLL::FeatureVectorList::PushOnFront(), MLL::DataBase::QueryStatement(), MLL::DataBase::QueryStatement2(), CrossValidationApp::RandomlySelectedProcessResults(), CrossValidationApp::RandomlySelectedResults(), MLL::FeatureNumList::RandomlySelectFeatures(), CrossValidationApp::RandomSplitsIntoTrainAndTest(), KKU::Raster::Raster(), MLL::NormalizationParms::Read(), MLL::TrainingProcess2::Read(), ReadImagePGM(), ReadImagePNG(), MLL::Model::ReadSkipToSection(), MLL::ModelParamKnn::ReadSpecificImplementationXML(), MLL::ModelParamDual::ReadSpecificImplementationXML(), MLL::ModelParamOldSVM::ReadSpecificImplementationXML(), MLL::ModelParamSvmBase::ReadSpecificImplementationXML(), MLL::ModelParamUsfCasCor::ReadSpecificImplementationXML(), MLL::ModelUsfCasCor::ReadSpecificImplementationXML(), MLL::ModelSvmBase::ReadSpecificImplementationXML(), MLL::ModelDual::ReadSpecificImplementationXML(), MLL::ModelOldSVM::ReadSpecificImplementationXML(), MLL::AbundanceCorrectionMatrix::ReadXml(), MLL::SVMparam::ReadXML(), MLL::Model::ReadXML(), MLL::ModelDual::ReconcilePredictions(), KKU::BmpImage::RedRow(), MLL::Model::ReduceTrainExamples(), KKU::XmlStream::RegisterXmlElementCreator(), CrossValidationApp::RemoveDuplicateImages(), MLL::FeatureVectorList::RemoveEntriesWithMissingFeatures(), CrossValidationApp::ReportCmdLineParameters(), CrossValidationApp::ReportConfigurationInfo(), MLL::DuplicateImages::ReportDuplicates(), ReportError(), SipperHardware::InstrumentDataBatteryMeter::ReportInstrumentData(), SipperHardware::InstrumentDataCTDplus::ReportInstrumentData(), SipperHardware::InstrumentDataPitchAndRoll::ReportInstrumentData(), SipperHardware::InstrumentDataFlowMeter1::ReportInstrumentData(), SipperHardware::InstrumentDataGPS::ReportInstrumentData(), SipperHardware::InstrumentDataReport::ReportInstrumentData(), SipperHardware::InstrumentDataManager::ReportInstrumentData(), MLL::SipperExtractionImageManager::ReportStatistics(), MLL::SipperExtractionImageManager::ReportStatsByDepth(), MLL::TrainingProcess2::ReportTraningClassStatistics(), KKU::BitString::ReSet(), SipperHardware::SipperBuff::ResetByteOffset(), MLL::FeatureVectorList::ResetFileDesc(), MLL::FeatureVector::ResetNumOfFeatures(), MLL::FeatureVectorList::ReSyncSymbolicData(), MLL::ModelDual::RetrieveCrossProbTable(), MLL::SVMModel::RetrieveCrossProbTable(), MLL::Model::RetrieveCrossProbTable(), KKU::KKStr::RightPad(), KKU::Row::Row(), KKU::KKThread::Run(), JobManagment::JobManager::Run(), MLL::CrossValidation::RunCrossValidation(), MLL::CrossValidationVoting::RunCrossValidation(), MLL::CrossValidation::RunValidationOnly(), MLL::CrossValidationVoting::RunValidationOnly(), MLL::CrossValidationThreeWay::RunValidationOnly(), MLL::FileDesc::SameExceptForSymbolicData(), SipperHardware::InstrumentDataList::Save(), KKU::Chart::Save(), KKU::HashTable< Entry >::Save(), MLL::DataBaseImageValidatedEntryList::Save(), MLL::ClassAssignments::Save(), MLL::SVMparam::Save(), KKU::Histogram::Save(), MLL::NormalizationParms::Save(), SipperHardware::SipperFileList::Save(), KKU::BmpImage::Save(), MLL::Orderings::Save(), MLL::TrainingConfiguration2::Save(), MLL::MLClassConstList::Save(), MLL::Model::Save(), MLL::SVMModel::Save(), MLL::MLClassList::Save(), saveData(), MLL::FeatureFileIO::SaveFeatureFile(), MLL::FeatureFileIODstWeb::SaveFile(), MLL::FeatureFileIOColumn::SaveFile(), MLL::FeatureFileIORoberts::SaveFile(), MLL::FeatureFileIOUCI::SaveFile(), MLL::FeatureFileIOPices::SaveFile(), MLL::FeatureFileIOC45::SaveFile(), MLL::FeatureFileIOSparse::SaveFile(), KKU::BmpImage::SaveGrayscaleInverted4Bit(), KKU::BmpImage::SaveGrayscaleInverted8Bit(), SaveImage(), SaveImageGrayscaleInverted4Bit(), SaveImageGrayscaleInverted8Bit(), SaveImagePGM(), SaveImagePNG(), MLL::FeatureVectorList::SaveOrderingOfImages(), MLL::TrainingProcess2::SaveResults(), KKU::SegmentorOTSU::SegmentImage(), KKU::SegmentorOTSU::SegmentMaskedImage(), KKU::BitString::Set(), MLL::TrainingConfiguration2::SetFeatureNums(), SetNineClassesTrainAndTest(), KKU::BmpImage::SetPaletteEntry(), KKU::BmpImage::SetPixelValue(), KKU::Raster::SetPixelValue(), JobManagment::JobManager::SetQuitRunningFlag(), MLL::UsfCasCor::setup_network(), SetUpJMLRDataSet(), MLL::DataBase::SipperCruiseInsert(), MLL::DataBase::SipperCruiseUpdate(), MLL::SipperExtractionImageManager::SipperExtractionImageManager(), MLL::DataBase::SipperFileGetList(), MLL::DataBase::SipperFileLoad(), MLL::DataBase::SipperFileUpdate(), MLL::DataBase::SipperStationLoad(), SipperHardware::SipperBuff::SkipOneByte(), SplitUpETPdataSet(), SplitUpForestData(), JobManagment::JobManager::StatusFileProcessLine(), JobManagment::JobManager::StatusFileProcessLineJobStatusChange(), MLL::FeatureVectorList::StratifyAmoungstClasses(), KKU::KKStr::StrReplace(), MLL::SVMModel::SupportVectorNames(), SVM289_MFS::svm_load_model_XML_SupportVectorSection(), SVM289_BFS::svm_load_model_XML_SupportVectorSection(), SVM233::svm_margin(), SVM233::Svm_Save_Model(), SVM289_BFS::svm_train_one(), SVM289_MFS::svm_train_one(), MLL::TrainingConfiguration2::SVMparamREF(), MLL::ModelParamOldSVM::SvmParamToString(), MLL::SVMparam::SvmParamToString(), MLL::FeatureVectorList::SynchronizeSymbolicData(), MLL::UsfCasCor::TEST_EPOCH(), KKU::Raster::ThinContour(), MLL::ModelParamDual::ToCmdLineStr(), MLL::ModelParamSvmBase::ToCmdLineStr(), MLL::ModelParam::ToCmdLineStr(), MLL::ModelParamOldSVM::ToCmdLineStr(), MLL::SVMparam::ToString(), tqli(), MLL::UsfCasCor::TRAIN(), MLL::UsfCasCor::train_network(), MLL::ModelKnn::TrainModel(), MLL::ModelUsfCasCor::TrainModel(), MLL::ModelSvmBase::TrainModel(), MLL::ModelOldSVM::TrainModel(), MLL::ModelDual::TrainModel(), MLL::Model::TrainModel(), MLL::UsfCasCor::TrainNewClassifier(), KKU::RBTree< Entry, CompareNodes, KeyType >::Validate(), CrossValidationApp::ValidationProcess(), MLL::NormalizationParms::Write(), MLL::SVMModel::Write(), CrossValidationApp::WriteABiasMatrix(), MLL::DataBaseServerList::WriteConfigFile(), MLL::ConfusionMatrix2::WriteSimpleConfusionMatrix(), MLL::ModelParamKnn::WriteSpecificImplementationXML(), MLL::ModelParamOldSVM::WriteSpecificImplementationXML(), MLL::ModelParamSvmBase::WriteSpecificImplementationXML(), MLL::ModelParamUsfCasCor::WriteSpecificImplementationXML(), MLL::ModelParamDual::WriteSpecificImplementationXML(), MLL::ModelKnn::WriteSpecificImplementationXML(), MLL::ModelUsfCasCor::WriteSpecificImplementationXML(), MLL::ModelSvmBase::WriteSpecificImplementationXML(), MLL::ModelOldSVM::WriteSpecificImplementationXML(), MLL::ModelDual::WriteSpecificImplementationXML(), MLL::AbundanceCorrectionMatrix::WriteXml(), MLL::SVMparam::WriteXML(), MLL::ModelParam::WriteXML(), MLL::ClassificationBiasMatrix::WriteXML(), MLL::ConfusionMatrix2::WriteXML(), MLL::BinaryClassParmsList::WriteXML(), MLL::MLClass::WriteXML(), MLL::MLClassConstList::WriteXML(), MLL::Model::WriteXML(), MLL::TrainingProcess2::WriteXml(), MLL::MLClassList::WriteXML(), WriteXmlArrayFloat(), WriteXmlArrayFloat2D(), WriteXmlArrayFloat2DVarying(), WriteXmlArrayInt(), SipperHardware::InstrumentDataBatteryMeter::~InstrumentDataBatteryMeter(), MLL::ModelOldSVM::~ModelOldSVM(), MLL::SVMModel::~SVMModel(), and MLL::TrainingProcess2::~TrainingProcess2().
void KKU::FFT (float data[], uint32 number_of_complex_samples, int32 isign)
Definition at line 146 of file kku_fftw.cpp.
References PIE, and SWAP().
fftwf_plan KKU::fftwCreateOneDPlan (int32 len, fftwf_complex * src, fftwf_complex * dest, int sign, int flag)
Definition at line 299 of file kku_fftw.cpp.
References KKU::GoalKeeper::EndBlock(), fftwGoalKeeper, and KKU::GoalKeeper::StartBlock().
Referenced by KKU::ContourFollower::CreateFourierDescriptorBySampling(), KKU::ContourFollower::FollowContour(), and KKU::ContourFollower::FollowContour2().
fftwf_plan KKU::fftwCreateTwoDPlan (int32 height, int32 width, fftwf_complex * src, fftwf_complex * dest, int sign, int flag)
Definition at line 265 of file kku_fftw.cpp.
References KKU::GoalKeeper::EndBlock(), fftwGoalKeeper, and KKU::GoalKeeper::StartBlock().
Referenced by KKU::Raster::BandPass(), and KKU::Raster::FastFourier().
void KKU::fftwDestroyPlan (fftwf_plan & plan)
Definition at line 286 of file kku_fftw.cpp.
References KKU::GoalKeeper::EndBlock(), fftwGoalKeeper, and KKU::GoalKeeper::StartBlock().
Referenced by KKU::Raster::BandPass(), KKU::ContourFollower::CreateFourierDescriptorBySampling(), KKU::Raster::FastFourier(), KKU::ContourFollower::FollowContour(), and KKU::ContourFollower::FollowContour2().
bool KKU::IsFinite (const float & f)
Definition at line 86 of file BasicTypes.cpp.
Referenced by MLL::DataBase::FeatureDataInsertRow().
bool KKU::IsFinite (const double & f)
Definition at line 92 of file BasicTypes.cpp.
bool KKU::IsNaN (const float & f)
Definition at line 72 of file BasicTypes.cpp.
Referenced by MLL::DataBase::FeatureDataInsertRow().
bool KKU::IsNaN (const double & d)
Definition at line 79 of file BasicTypes.cpp.
float KKU::LLoydsIndexOfPatchiness (const KKU::VectorInt & bins)
Definition at line 166 of file StatisticalFunctions.cpp.
References x.
float KKU::Log2 (float x)
Definition at line 253 of file kku_fftw.cpp.
int32 KKU::LRand48 ()
Returns a long int32 random value.
Can be called without first calling the SRand48 function, however, this is not recommended.
Definition at line 22 of file BasicTypes.cpp.
References _lrand48_sequence.
Referenced by MLL::UsfCasCor::random_weight(), and MLL::FeatureNumList::RandomlySelectFeatures().
template<class T > T KKU::Max (T a, T b)
generic Max function, Both parameters must be of the same type.
Definition at line 185 of file BasicTypes.h.
Referenced by KKU::Raster::ConnectedComponent8Conected(), KKU::Raster::ConnectedComponentOrig(), KKU::Raster::CreateSmoothedMediumImage(), KKU::RasterSipper::DeriveImageLength(), KKU::Raster::DrawDot(), KKU::Raster::ExtractBlobs(), SipperHardware::InstrumentDataFileManager::GetClosestInstrumentData(), KKU::ContourFollower::HistogramDistanceFromAPointOfEdge(), KKU::KKStr::MaxLen(), KKU::BlobList::MergeBlobIds(), KKU::BlobList::MergeIntoSingleBlob(), KKU::BitString::operator^(), KKU::BitString::operator^=(), KKU::KKStr::Tail(), and KKU::Raster::ThinContour().
template<class T > T KKU::Max (T a, T b, T c)
Generic Max function, that takes three parameters.
All three parameters must be of the same type.
Definition at line 199 of file BasicTypes.h.
template<class T > T KKU::Max (T a, T b, T c, T d)
Generic Max function, that takes four parameters.
All four parameters must be of the same type.
Definition at line 217 of file BasicTypes.h.
float KKU::McNemarsTest (int32 size, const bool * classedCorrectly1, const bool * classedCorrectly2)
Definition at line 109 of file StatisticalFunctions.cpp.
References x.
template<class T > T KKU::Min (T a, T b)
Generic Min function, Both parameters must be of the same type.
Definition at line 156 of file BasicTypes.h.
Referenced by KKU::Raster::BandPass(), KKU::KKStr::Compare(), KKU::KKStr::CompareIgnoreCase(), KKU::Raster::ConnectedComponent8Conected(), KKU::Raster::ConnectedComponentOrig(), KKU::Raster::CreateColorWithBlobsLabeldByColor(), KKU::Raster::CreateFromOrginalImageWithSpecifidBlobsOnly(), KKU::Histogram::CreateGraph(), KKU::Raster::CreateGrayScaleKLT(), KKU::Raster::CreateGrayScaleKLTOnMaskedArea(), KKU::Raster::CreateSmoothedMediumImage(), KKU::Raster::DrawDot(), KKU::Raster::ExtractBlobs(), KKU::Raster::FillBlob(), KKU::Raster::FillRectangle(), KKU::ContourFollower::HistogramDistanceFromAPointOfEdge(), KKU::BlobList::MergeBlobIds(), KKU::BlobList::MergeIntoSingleBlob(), KKU::BitString::operator&=(), KKU::BitString::operator^(), KKU::BitString::operator^=(), KKU::BitString::operator|=(), KKU::BmpImage::Print(), and KKU::Raster::ThinContour().
template<class T > T KKU::Min (T a, T b, T c)
Generic Min function, Both parameters must be of the same type.
Definition at line 168 of file BasicTypes.h.
KKStr KKU::operator+ (const char left, const KKStr & right)
Definition at line 3558 of file Str.cpp.
References KKU::KKStr::Append(), and KKU::KKStr::Len().
KKStr KKU::operator+ (const char * left, const KKStr & right)
Definition at line 3570 of file Str.cpp.
Matrix KKU::operator- (double left, const Matrix & right)
Definition at line 454 of file Matrix.cpp.
References KKU::Matrix::NumOfCols(), KKU::Matrix::NumOfRows(), and x.
HTMLReport& KKU::operator<< (HTMLReport & htmlReport, HTMLReport & *)(HTMLReport &)
HTMLReport & KKU::operator<< (HTMLReport & htmlReport, int32 right)
Definition at line 106 of file HTMLReport.cpp.
References KKU::HTMLReport::Append(), KKU::KKStr::Str(), and StrFormatInt().
HTMLReport & KKU::operator<< (HTMLReport & htmlReport, uint32 right)
Definition at line 118 of file HTMLReport.cpp.
References KKU::HTMLReport::Append(), KKU::KKStr::Str(), and StrFormatInt().
HTMLReport& KKU::operator<< (HTMLReport & htmlReport, long right)
HTMLReport& KKU::operator<< (HTMLReport & htmlReport, long long right)
HTMLReport & KKU::operator<< (HTMLReport & htmlReport, double right)
Definition at line 154 of file HTMLReport.cpp.
References KKU::HTMLReport::Append(), and SPRINTF().
HTMLReport& KKU::operator<< (HTMLReport & htmlReport, unsigned long right)
HTMLReport & KKU::operator<< (HTMLReport & htmlReport, char right)
Definition at line 166 of file HTMLReport.cpp.
References KKU::HTMLReport::Append().
KKStr & KKU::operator<< (KKStr & left, const Point & right)
Definition at line 270 of file Point.cpp.
References KKU::Point::Col(), and KKU::Point::Row().
HTMLReport & KKU::operator<< (HTMLReport & htmlReport, const char * right)
Definition at line 179 of file HTMLReport.cpp.
References KKU::HTMLReport::Append().
ostream & KKU::operator<< (std::ostream & left, const Point & right)
Definition at line 280 of file Point.cpp.
References KKU::Point::Col(), and KKU::Point::Row().
HTMLReport & KKU::operator<< (HTMLReport & htmlReport, const KKStr & right)
Definition at line 190 of file HTMLReport.cpp.
References KKU::HTMLReport::Append(), and KKU::KKStr::Str().
HTMLReport & KKU::operator<< (HTMLReport & htmlReport, KKStrConstPtr right)
Definition at line 201 of file HTMLReport.cpp.
References KKU::HTMLReport::Append().
HTMLReport & KKU::operator<< (HTMLReport & htmlReport, const DateTime & right)
Definition at line 212 of file HTMLReport.cpp.
References KKU::HTMLReport::Append(), KKU::DateTime::Date(), KKU::TimeType::HH_MM_SS(), KKU::KKStr::Str(), KKU::DateTime::Time(), and KKU::DateType::YYYY_MM_DD().
KKStr & KKU::operator<< (KKU::KKStr & left, const KKU::DateType & right)
Definition at line 742 of file DateTime.cpp.
References KKU::DateType::YYYY_MMM_DD().
ostream & KKU::operator<< (std::ostream & os, const KKU::DateType & right)
Definition at line 752 of file DateTime.cpp.
References KKU::DateType::YYYY_MMM_DD().
KKStr & KKU::operator<< (KKStr & left, const TimeType & right)
Definition at line 974 of file DateTime.cpp.
References KKU::TimeType::Hour(), KKU::TimeType::Minute(), KKU::TimeType::Second(), and StrFormatInt().
ostream & KKU::operator<< (std::ostream & os, const TimeType & right)
Definition at line 987 of file DateTime.cpp.
References KKU::TimeType::Hour(), KKU::TimeType::Minute(), KKU::TimeType::Second(), and StrFormatInt().
KKStr & KKU::operator<< (KKU::KKStr & left, const DateTime & right)
Definition at line 1306 of file DateTime.cpp.
References KKU::DateTime::Date(), and KKU::DateTime::Time().
ostream & KKU::operator<< (std::ostream & os, const DateTime & right)
Definition at line 1317 of file DateTime.cpp.
References KKU::DateTime::Date(), and KKU::DateTime::Time().
ostream & KKU::operator<< (std::ostream & os, const KKStr & str)
Definition at line 3877 of file Str.cpp.
References KKU::KKStr::Str(), and Test2().
std::istream & KKU::operator>> (std::istream & os, KKStr & str)
Definition at line 3888 of file Str.cpp.
References KKU::KKStr::TrimLeft(), and KKU::KKStr::TrimRight().
void KKU::osAddLastSlash (KKStr & fileSpec)
Will add the appropriate Directory separator character to the end of fileSpec if one is not there already.
Definition at line 856 of file OSservices.cpp.
References DS, and KKU::KKStr::LastChar().
Referenced by MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::FeatureFileIOPices::LoadInSubDirectoryTree(), osDirectoryList(), osGetListOfDirectories(), osGetListOfFiles(), osMakeFullFileName(), KKU::Raster::SegmentImage(), and SegmentPolutionImage().
KKStr KKU::osAddSlash (const KKStr & fileSpec)
Definition at line 866 of file OSservices.cpp.
References DS, and KKU::KKStr::LastChar().
Referenced by PicesInterface::TrainingModel2::AddClass(), MLL::SipperExtractionImageManager::ManagedClass::AddImage(), PicesInterface::TrainingModel2::AddImageToTrainingLibray(), MLL::SipperExtractionImageManager::ManagedClass::CloseOutCurDirectory(), MLL::TrainingConfiguration2::CreateFromDirectoryStructure(), ImageExtractionManager::DataBaseUpdateThread::DataBaseUpdateThread(), MLL::TrainingClass::ExpandedDirectory(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::SipperExtractionImageManager::Flush(), ImageExtractionManager::FrameExtractorThread::FrameExtractorThread(), MLL::TrainingConfiguration2::GetEffectiveConfigFileName(), PicesInterface::TrainingModel2::GetListOfTrainingModels(), SipperHardware::SipperVariables::InstrumentDataFilesDir(), SipperHardware::InstrumentDataManager::InstrumentDataManager(), SipperHardware::InstrumentDataReport::InstrumentDataReport(), SipperHardware::SipperVariables::InstrumentDataReportDir(), MLL::FeatureFileIOPices::LoadInSubDirectoryTree(), MLL::TrainingConfiguration2::LoadOtherClasssExamples(), osCreateUniqueFileName(), osGetListOfFilesInDirectoryTree(), osLookForFile(), SipperHardware::SipperVariables::PicesCmdLineProgDir(), SipperHardware::SipperVariables::PicesConfigurationDirectory(), SipperHardware::SipperVariables::PicesDataFileDirectory(), SipperHardware::SipperVariables::PicesDataFilesDirectory(), SipperHardware::SipperVariables::PicesReportDir(), SipperHardware::SipperVariables::PicesTempDirectory(), PicesInterface::PicesTrainingConfiguration::PicesTrainingConfiguration(), CrossValidationApp::PostMisclassifiedImage(), MLL::TrainingConfiguration2::PromptForConfigurationFile(), SipperHardware::SipperBuff::ReportInstrumentData(), ImageExtractionManager::DataBaseUpdateThread::Run(), PicesInterface::TrainingModel2::SaveConfiguration(), MLL::AbundanceCorrectionMatrix::SaveForConfigFileName(), MLL::SipperExtractionImageManager::ManagedClass::SaveFrame(), SipperHardware::SipperVariables::SipperConfigrationFileName(), SipperHardware::SipperVariables::SipperDirectoryListFileName(), SipperHardware::SipperVariables::SipperFilesDefaultDir(), SipperHardware::SipperVariables::SipperInterfaceDir(), SipperHardware::SipperVariables::SipperInterfaceLogDir(), MLL::SipperExtractionImageManager::ManagedClass::StartNewDirectory(), SipperHardware::SipperVariables::TrainingLibrariesDir(), PicesInterface::TrainingModel2::TrainingModel2(), SipperHardware::SipperVariables::TrainingModelsConfigurationDir(), SipperHardware::SipperVariables::TrainingModelsSaveFilesDir(), SipperHardware::SipperVariables::ValidationInfoDir(), and MLL::DataBaseServerList::WriteConfigFile().
void KKU::osChangeDir (const KKStr & dirName, bool & successful)
Definition at line 686 of file OSservices.cpp.
References endl(), and KKU::KKStr::Str().
bool KKU::osCopyFile (const KKStr & srcFileName, const KKStr & destFileName)
Definition at line 618 of file OSservices.cpp.
References endl(), and osWaitForEnter().
bool KKU::osCopyFileBetweenDirectories (const KKStr & _fileName, const KKStr & _srcDir, const KKStr & _destDir)
Definition at line 563 of file OSservices.cpp.
References endl(), and osWaitForEnter().
Referenced by CrossValidationApp::PostMisclassifiedImage().
bool KKU::osCreateDirectory (const KKStr & dirName)
Definition at line 768 of file OSservices.cpp.
References KKU::KKStr::Str().
Referenced by PicesInterface::OSservices::CreateDirectory(), and osCreateDirectoryPath().
bool KKU::osCreateDirectoryPath (KKStr _pathName)
Will create the whole Directory Path not just the final part of the path.
For example if you need a directory path "C:\Temp\Temple\DataFiles" created this function will create a directory in the specified path if they do not already exists.
Definition at line 718 of file OSservices.cpp.
References DS, DSchar, KKU::KKStr::Empty(), endl(), KKU::KKStr::ExtractToken(), KKU::KKStr::FirstChar(), KKU::KKStr::LastChar(), osCreateDirectory(), osValidDirectory(), and KKU::KKStr::SubStrPart().
Referenced by PicesInterface::TrainingModel2::AddClass(), PicesInterface::OSservices::CreateDirectoryPath(), ImageExtractionManager::DataBaseUpdateThread::DataBaseUpdateThread(), DetermineCropSettingsForDeployment(), SipperHardware::InstrumentDataFileManager::InstrumentDataFileManager(), SipperHardware::InstrumentDataManager::InstrumentDataManager(), SipperHardware::SipperVariables::PicesTempDirectory(), CrossValidationApp::PostMisclassifiedImage(), MLL::AbundanceCorrectionMatrix::SaveForConfigFileName(), KKU::Raster::SegmentImage(), SegmentPolutionImage(), MLL::SipperExtractionImageManager::ManagedClass::StartNewDirectory(), and MLL::DataBaseServerList::WriteConfigFile().
KKStr KKU::osCreateUniqueFileName (KKStr fileName)
Get a unique file name based off file spec 'fileName'.
Make sure that fileName is unique, if file name already is used will add a seq-num to the root part of the name, starting with 0 and incrementing until file name is unique.
Definition at line 2034 of file OSservices.cpp.
References KKU::KKStr::Empty(), osAddSlash(), osFileExists(), osParseFileName(), and StrFormatInt().
bool KKU::osDeleteFile (KKStr _fileName)
Definition at line 416 of file OSservices.cpp.
References KKU::KKStr::Str().
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
void KKU::osDisplayWarning (KKStr _message)
Definition at line 1956 of file OSservices.cpp.
References backGroundProcess, endl(), and osWaitForEnter().
Referenced by MLL::FeatureFileIO::AppendToFile(), MLL::FeatureVectorList::BinarySearchByName(), ImageExtractionSingleThreaded(), SipperHardware::SipperVariables::PicesHomeDir(), and MLL::FeatureVectorList::StratifyAmoungstClasses().
bool KKU::osFileExists (const KKStr & _fileName)
Definition at line 483 of file OSservices.cpp.
References KKU::KKStr::Str().
Referenced by PicesInterface::TrainingModel2::AddImageToTrainingLibray(), MLL::TrainingConfiguration2::ConfigFileExists(), MLL::TrainingConfiguration2::CreateFromDirectoryStructure(), MLL::TrainingConfiguration2::GetEffectiveConfigFileName(), JobManagment::JobManager::InitilizeJobManager(), MLL::FeatureFileIOC45::LoadFeatureFile(), osCreateUniqueFileName(), ImageExtractionManager::ExtractionParms::ParseCmdLine(), and CrossValidationApp::ProcessCmdLineParameters().
FILE * KKU::osFOPEN (const char * fileName, const char * mode)
Definition at line 68 of file OSservices.cpp.
Referenced by KKU::BmpImage::BmpImage(), SipperHardware::SipperBuff::GuessFormatOfFile(), MLL::ClassAssignments::Load(), MLL::SVMparam::Load(), MLL::FeatureNumList::Load(), MLL::MLClassConstList::Load(), MLL::MLClassList::Load(), KKU::Configuration::LoadFile(), MLL::DataBaseUpdate::LoadSourceFile(), SipperHardware::SipperBuff::Open(), MLL::FeatureVectorList::OrderUsingNamesFromAFile(), ReadImagePGM(), ReadImagePNG(), KKU::BmpImage::Save(), KKU::BmpImage::SaveGrayscaleInverted4Bit(), KKU::BmpImage::SaveGrayscaleInverted8Bit(), SaveImagePGM(), and SaveImagePNG().
KKStr KKU::osGetCurrentDirectory ()
Definition at line 319 of file OSservices.cpp.
Referenced by MLL::TrainingConfiguration2::GetEffectiveConfigFileName(), osDirectoryList(), osGetListOfFiles(), SipperHardware::SipperVariables::PicesHomeDir(), and SipperHardware::SipperBuff::ReportInstrumentData().
KKStr KKU::osGetDirNameFromPath (KKStr dirPath)
Extracts the final sub-directory name of the fill directory specification.
ex:Input                              Returns
   -----------------------            ----------------------
   c:\an\Example\FileSpec\Romeo       Romeo
   /usr/kkramer/Kinsey/Release_2      Release_2
   /usr/kkramer/Thesis/               Thesis
   /usr/kkramer/Thesis.dat/           Thesis.dat
Parameters
[in] dirPath Directory path to get dir name from .
Definition at line 892 of file OSservices.cpp.
References KKU::KKStr::ChopLastChar(), DSchar, KKU::KKStr::Empty(), KKU::KKStr::LastChar(), and osParseFileName().
char KKU::osGetDriveLetter (KKStr fileName)
Given a full drive with path and name return the drive letter specified.
If not on a Windows system returns x'00'= char(0)
Parameters
[in] fileName.
Returns
Drive Letter ('A' - 'Z').
If not on a Windows system returns x'00'= char(0).
Definition at line 266 of file OSservices.cpp.
References KKU::KKStr::Len().
KKStrPtr KKU::osGetEnvVariable (KKStr _varName)
Definition at line 810 of file OSservices.cpp.
References KKU::KKStr::Str().
Referenced by osGetHostName(), osGetNumberOfProcessors(), osSubstituteInEvironmentVariables(), SipperHardware::SipperVariables::PicesHomeDir(), SipperHardware::SipperVariables::SipperInterfaceDir(), and SipperHardware::SipperVariables::SubstituteInEvironmentVariables().
KKStr KKU::osGetErrorNoDesc (int32 errorNo)
Definition at line 39 of file OSservices.cpp.
DateTime KKU::osGetFileDateTime (const KKStr & fileName)
Definition at line 1875 of file OSservices.cpp.
References KKU::KKStr::Str().
Referenced by MLL::FeatureFileIOPices::FeatureDataReSink(), SipperHardware::InstrumentDataManager::InstrumentDataManager(), and CrossValidationApp::WriteABiasMatrix().
KKStr KKU::osGetFileExtension (KKStr fullFileName)
Definition at line 1136 of file OSservices.cpp.
References osParseFileName().
Referenced by MLL::TrainingConfiguration2::GetEffectiveConfigFileName(), PicesInterface::OSservices::GetFileExtension(), ReadImage(), MLL::FeatureFileIO::SaveFeatureFileMultipleParts(), SaveImage(), and SupportedImageFileFormat().
KKStr KKU::osGetFileNamePartOfFile (KKStr fullFileName)
osGetFileNamePartOfFile, retrieves the file name part of the file spec.
ex:  Input (fullFileName)                Returned
     --------------------------------    ---------------
     c:\Planktn\Libray\copepod.data      copepod.data
     /bin/usr/Plankton/Larvacean.data    Larvacean.data
     dataFile.data                       dataFile.data
Parameters
[in] fullFileName Sting that contains the full file name specification.
Returns
File Name.
Definition at line 1287 of file OSservices.cpp.
References DSchar, KKU::KKStr::LastChar(), KKU::KKStr::LocateCharacter(), osLocateLastSlashChar(), and KKU::KKStr::SubStrPart().
int64 KKU::osGetFileSize (const KKStr & fileName)
Definition at line 1918 of file OSservices.cpp.
References KKU::KKStr::Str().
Referenced by MLL::DataBaseUpdate::LoadSourceFile(), and ImageExtractionManager::ExtractionParms::ParseCmdLine().
KKStr KKU::osGetFullPathOfApplication ()
returns the name and path of th ecurrent running application.
Definition at line 2663 of file OSservices.cpp.
Referenced by SipperHardware::SipperVariables::PicesHomeDir().
KKStr KKU::osGetHostName ()
Definition at line 1167 of file OSservices.cpp.
References osGetEnvVariable().
Referenced by MLL::DataBase::LogEntriesProcessStart(), MarineSnowReportDeployment(), and MLL::DataBaseImageValidatedEntryList::Save().
double KKU::osGetKernalTimeUsed ()
Definition at line 1785 of file OSservices.cpp.
Referenced by CrossValidationApp::Main().
KKStrListPtr KKU::osGetListOfDirectories (KKStr fileSpec)
Definition at line 1619 of file OSservices.cpp.
References KKU::KKStr::LocateCharacter(), osAddLastSlash(), KKU::KKStr::Str(), KKU::KKStr::SubStrPart(), and x.
Referenced by MLL::FeatureFileIOPices::LoadInSubDirectoryTree(), osGetListOfFilesInDirectoryTree(), and osLookForFile().
KKStrListPtr KKU::osGetListOfFiles (const KKStr & fileSpec)
Returns a list of files that match the provided file specification.
You can provide any file specification including a directory path. If there is a failure will return NULL. The caller will be responsible for deleting the returned list. The file names returned will not include any directory path.
Definition at line 1432 of file OSservices.cpp.
References osAddLastSlash(), osDirectoryList(), osFileNameMatchesSearchFields(), osGetCurrentDirectory(), osLocateLastSlashChar(), osParseSearchSpec(), and KKU::KKStr::SubStrPart().
Referenced by MLL::FeatureFileIOPices::FeatureDataReSink(), PicesInterface::TrainingModel2::GetListOfTrainingModels(), osGetListOfFilesInDirectoryTree(), osGetListOfImageFiles(), osLookForFile(), and MLL::TrainingConfiguration2::PromptForConfigurationFile().
void KKU::osGetListOfFilesInDirectoryTree (const KKStr & rootDir, KKStr fileSpec, VectorKKStr & fileNames)
Definition at line 1487 of file OSservices.cpp.
References KKU::KKStr::Empty(), osAddSlash(), osGetListOfDirectories(), and osGetListOfFiles().
KKStrListPtr KKU::osGetListOfImageFiles (KKStr fileSpec)
Definition at line 1536 of file OSservices.cpp.
References osGetListOfFiles(), and SupportedImageFileFormat().
DateTime KKU::osGetLocalDateTime ()
Returned the current local date and time.
Definition at line 1820 of file OSservices.cpp.
Referenced by KKU::SimpleCompressor::CreateCompressedBuffer(), MLL::TrainingProcess2::CreateModelsFromTrainingData(), KKU::SimpleCompressor::Decompress(), MLL::DataBase::ErrorLogMsg(), MLL::FeatureFileIOPices::FeatureDataReSink(), SipperHardware::InstrumentDataManager::InstrumentDataManager(), CrossValidationApp::Main(), ImageExtractionManager::ExtractionManager::ManageTheExtraction(), MarineSnowReportDeployment(), CImageExtractionWindowsDlg::OnCancel(), MLL::DataBase::QueryStatement(), MLL::DataBase::QueryStatement2(), ImageExtractionManager::FrameExtractorThread::Run(), SipperHardware::InstrumentDataList::Save(), MLL::DataBaseImageValidatedEntryList::Save(), SipperHardware::SipperFileList::Save(), MLL::Orderings::Save(), MLL::FeatureFileIOC45::SaveFile(), MLL::FeatureVectorList::SaveOrderingOfImages(), SipperHardware::SipperDeployment::SipperDeployment(), CrossValidationApp::ValidationProcess(), MLL::SVMModel::Write(), CrossValidationApp::WriteABiasMatrix(), MLL::DataBaseServerList::WriteConfigFile(), and MLL::Model::WriteXML().
int32 KKU::osGetNumberOfProcessors ()
returns the number of CPU's or number of simultaneous threads that you can have.
Todo:
Need to implement 'osGetNumberOfProcessors' for linux.
Definition at line 1265 of file OSservices.cpp.
References osGetEnvVariable(), and KKU::KKStr::ToInt32().
Referenced by CImageExtractionWindowsDlg::ManageImageExtractionMultiThreaded().
KKStr KKU::osGetParentDirectoryOfDirPath (KKStr path)
Definition at line 1015 of file OSservices.cpp.
References KKU::KKStr::ChopLastChar(), DSchar, KKU::KKStr::LastChar(), KKU::KKStr::LocateLastOccurrence(), SVM289_MFS::Max(), KKU::KKStr::SubStrPart(), and x.
Referenced by PicesInterface::OSservices::GetParentDirectoryOfDirPath().
KKStr KKU::osGetParentDirPath (KKStr dirPath)
Returns the Parent directory path to 'dirPath'.
ex:Input                              Returns
   -----------------------            ----------------------
   c:\an\Example\FileSpec\Romeo       c:\an\Example\FileSpec
   /usr/kkramer/Kinsey/Release_2      /usr/kkramer/Kinsey
   /usr/kkramer/Thesis/               /usr/kkramer
   /usr/kkramer/Thesis.dat/           /usr/kkramer
Definition at line 1146 of file OSservices.cpp.
References KKU::KKStr::ChopLastChar(), KKU::KKStr::LastChar(), KKU::KKStr::LocateLastOccurrence(), SVM289_MFS::Max(), KKU::KKStr::SubStrPart(), and x.
Referenced by SipperHardware::SipperVariables::PicesHomeDir().
KKStr KKU::osGetPathPartOfFile (KKStr fullFileName)
Get the path part of a full file name specification.
ex:Input                              Returns
   -----------------------            ----------------------
   c:\an\Example\FileSpec\data.txt    c:\an\Example\FileSpec
   /usr/kkramer/Plankton/Relase_2     /usr/kkramer/Plankton
   /usr/kkramer/Thesis/               /usr/kkramer/Thesis
Parameters
[in] fullFileName The full file specification including directory path, rootname, and extension.
Returns
Path part of fullFileName.
Definition at line 1118 of file OSservices.cpp.
References KKU::KKStr::LocateLastOccurrence(), osLocateLastSlashChar(), and KKU::KKStr::SubStrPart().
Referenced by MLL::TrainingConfiguration2::GetEffectiveConfigFileName(), PicesInterface::OSservices::GetPathPartOfFile(), SipperHardware::SipperVariables::PicesHomeDir(), and SipperHardware::SipperBuff::ReportInstrumentData().
int32 KKU::osGetProcessId ()
Definition at line 2497 of file OSservices.cpp.
Referenced by GetProcessId().
KKStr KKU::osGetProgName ()
Definition at line 1215 of file OSservices.cpp.
Referenced by MarineSnowReportDeployment().
KKStr KKU::osGetRootName (const KKStr & fullFileName)
Definition at line 965 of file OSservices.cpp.
References KKU::KKStr::LocateLastOccurrence(), SVM289_MFS::Max(), osLocateLastSlashChar(), and KKU::KKStr::SubStrPart().
Referenced by PicesInterface::TrainingModel2::AddImageToTrainingLibray(), MLL::DuplicateImages::AddSingleImage(), MLL::FeatureEncoder::Compress(), SipperHardware::InstrumentDataList::CreateFromSipperFile(), MLL::TrainingProcess2::CreateModelsFromTrainingData(), CrossValidationApp::CrossValidate(), ImageExtractionManager::DataBaseUpdateThread::DataBaseUpdateThread(), MLL::ModelDual::Description(), KKU::Raster::ExtractChannel(), MLL::ExtractImageFileName::ExtractKey(), MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::DataBase::FeatureDataGetScanLinesPerMeterProfile(), MLL::DataBase::FeatureDataInsertRow(), MLL::DataBase::FeatureDataRecLoad(), MLL::DataBase::FeatureDataUpdate(), ImageExtractionManager::FrameExtractorThread::FrameExtractorThread(), ImageExtractionManager::FrameProcessorThread::FrameProcessorThread(), SipperHardware::InstrumentDataFileManager::GetClosestInstrumentData(), SipperHardware::InstrumentDataFileManager::GetInstrumentDataForSipperFile(), SipperHardware::SipperFileList::GetListOfSipperFilesWeCanFind(), SipperHardware::Sipper3Buff::GetNextLine(), MLL::DataBaseImage::GetOrigImageFromSipperFile(), PicesInterface::OSservices::GetRootName(), SipperHardware::InstrumentDataFileManager::GetScanLinesPerMeterProfile2(), SipperHardware::InstrumentDataFileManager::GetVolumePerMeterProfile2(), MLL::DataBaseImage::ImageFileName(), MLL::DataBase::ImageFullSizeLoad(), MLL::DataBase::ImageFullSizeSave(), MLL::DataBase::ImagesEraseSipperFile(), MLL::DataBase::ImagesEraseSipperFileSizeRange(), MLL::DataBase::ImagesRetrieveValidatedClass(), MLL::DuplicateImage::ImageWithSmallestScanLine(), MLL::DataBase::InstrumentDataGetVolumePerMeterDepth(), MLL::DataBase::InstrumentDataInsert(), MLL::DataBase::InstrumentDataLoadAllSipperFiles(), SipperHardware::InstrumentDataManager::InstrumentDataManager(), MLL::DataBase::InstrumentDataSaveListForOneSipperFile(), MLL::FeatureFileIODstWeb::LoadFile(), MLL::FeatureFileIOColumn::LoadFile(), MLL::FeatureFileIOUCI::LoadFile(), MLL::FeatureFileIOPices::LoadFile(), MLL::FeatureFileIOC45::LoadFile(), MLL::FeatureFileIOSparse::LoadFile(), MLL::DataBase::LogEntriesProcessStart(), MLL::FeatureVectorList::LookUpByRootName(), SipperHardware::SipperFileList::LookUpBySipperFileName(), MLL::FeatureVectorList::RootNameComparrisonReversed::operator()(), MLL::ModelDual::ReadSpecificImplementationXML(), SipperHardware::InstrumentDataFileManager::ReExtractInstrumentDataForSipperFile(), ImageExtractionManager::DataBaseUpdateThread::Run(), MLL::AbundanceCorrectionMatrix::SaveForConfigFileName(), MLL::TrainingProcess2::SaveResults(), KKU::Raster::SegmentImage(), SegmentPolutionImage(), MLL::DataBase::SipperFileRecLoad(), SipperHardware::InstrumentDataFileManager::SipperFileRootNameFromSipperImageFileName(), MLL::DataBase::SipperFilesUpdateExtractionStatus(), PicesInterface::TrainingModel2::TrainingModel2(), and CrossValidationApp::ValidationProcess().
KKStr KKU::osGetRootNameOfDirectory (KKStr fullDirName)
Definition at line 994 of file OSservices.cpp.
References KKU::KKStr::ChopLastChar(), DSchar, KKU::KKStr::LastChar(), KKU::KKStr::LocateLastOccurrence(), SVM289_MFS::Max(), osLocateLastSlashChar(), and KKU::KKStr::SubStrPart().
Referenced by MLL::TrainingConfiguration2::CreateFromDirectoryStructure(), MLL::SipperExtractionImageManager::Flush(), MLL::MLClass::GetClassNameFromDirName(), PicesInterface::OSservices::GetRootNameOfDirectory(), MLL::FeatureFileIOPices::LoadInSubDirectoryTree(), PicesInterface::PicesTrainingConfiguration::PicesTrainingConfiguration(), and PicesInterface::TrainingModel2::TrainingModel2().
KKStr KKU::osGetRootNameWithExtension (const KKStr & fullFileName)
Definition at line 1032 of file OSservices.cpp.
References KKU::KKStr::LocateLastOccurrence(), SVM289_MFS::Max(), osLocateLastSlashChar(), and KKU::KKStr::SubStrPart().
Referenced by CreateBfsFromMfs(), MLL::TrainingConfiguration2::GetEffectiveConfigFileName(), PicesInterface::OSservices::GetRootNameWithExtension(), PicesInterface::PicesTrainingConfiguration::ModelName(), and MLL::FeatureVectorList::RootNameComparrison::operator()().
double KKU::osGetSystemTimeUsed ()
Returns the number of CPU seconds used by current process.
This consists of both User and Kernel Time. When used to get timing data of some function, Call this method before and after running the function and use the difference.
Definition at line 1706 of file OSservices.cpp.
Referenced by MLL::BitReduction::compress(), MLL::FeatureEncoder2::CompressExamples(), CrossValidationApp::CrossValidate(), JobManagment::JobManager::InitilizeJobManager(), ImageExtractionManager::ExtractionManager::ManageTheExtraction(), CrossValidationApp::RandomlySampleData(), ImageExtractionManager::FrameExtractorThread::Run(), MLL::Model::TrainingTimeEnd(), MLL::Model::TrainingTimeStart(), MLL::Model::TrainModel(), and CrossValidationApp::ValidationProcess().
int32 KKU::osGetThreadId ()
Definition at line 2512 of file OSservices.cpp.
Referenced by KKU::GoalKeeper::BlockedByAnotherThread(), KKU::GoalKeeper::EndBlock(), MLL::DataBase::ErrorLogMsg(), MLL::DataBase::FinalCleanUp(), and KKU::GoalKeeper::StartBlock().
KKStr KKU::osGetUserName ()
Definition at line 1239 of file OSservices.cpp.
Referenced by MLL::DataBase::LogEntriesProcessStart(), and MarineSnowReportDeployment().
double KKU::osGetUserTimeUsed ()
Definition at line 1748 of file OSservices.cpp.
Referenced by CrossValidationApp::Main().
template<class T > T* KKU::osGrowAllocation (T * src, int32 origSize, int32 newSize) inline
Definition at line 427 of file OSservices.h.
Referenced by osReadNextLine().
bool KKU::osIsBackGroundProcess ()
Definition at line 1322 of file OSservices.cpp.
References backGroundProcess.
Referenced by MLL::FeatureVectorList::StratifyAmoungstClasses().
int32 KKU::osLocateFirstSlashChar (const KKStr & fileSpec)
Definition at line 838 of file OSservices.cpp.
References KKU::KKStr::LocateCharacter(), and Min().
int32 KKU::osLocateLastSlashChar (const KKStr & fileSpec)
Definition at line 828 of file OSservices.cpp.
References KKU::KKStr::LocateLastOccurrence(), and SVM289_MFS::Max().
Referenced by osGetFileNamePartOfFile(), osGetListOfFiles(), osGetPathPartOfFile(), osGetRootName(), osGetRootNameOfDirectory(), osGetRootNameWithExtension(), osParseFileName(), osParseFileSpec(), and osRemoveExtension().
KKStr KKU::osLookForFile (const KKStr & fileName, const KKStr & srcDir)
Look for a specified file in a sub-directory structure.
Parameters
[in] fileName Name of file we are looking for.
[in] srcDir Sub Directory tree we want to search.
Returns
Full directory path to where first occurrence of fileName is located. If not found will return back an empty string.
Definition at line 1980 of file OSservices.cpp.
References KKU::KKStr::Empty(), osAddSlash(), osGetListOfDirectories(), osGetListOfFiles(), KKU::KKStr::Str(), and KKU::KKStr::Upper().
Referenced by CrossValidationApp::LocateImageFileUsingConfigurationFile(), PicesInterface::OSservices::LookForFile(), and CrossValidationApp::PostMisclassifiedImage().
KKStr KKU::osMakeFullFileName (const KKStr & _dirName, const KKStr & _fileName)
Definition at line 877 of file OSservices.cpp.
References osAddLastSlash().
Referenced by ImageExtractionManager::ExtractionParms::ParseCmdLine().
bool KKU::osMoveFileBetweenDirectories (const KKStr & _fileName, const KKStr & _srcDir, const KKStr & _destDir)
Definition at line 502 of file OSservices.cpp.
References endl(), KKU::KKStr::LastChar(), osWaitForEnter(), and KKU::KKStr::Str().
void KKU::osParseFileName (KKStr _fileName, KKStr & _dirPath, KKStr & _rootName, KKStr & _extension)
Definition at line 908 of file OSservices.cpp.
References KKU::KKStr::LocateLastOccurrence(), osLocateLastSlashChar(), KKU::KKStr::SubStrPart(), and x.
Referenced by osCreateUniqueFileName(), osGetDirNameFromPath(), and osGetFileExtension().
void KKU::osParseFileSpec (KKStr fullFileName, KKStr & driveLetter, KKStr & path, KKStr & root, KKStr & extension)
Definition at line 1056 of file OSservices.cpp.
References DSchar, KKU::KKStr::LastChar(), KKU::KKStr::LocateCharacter(), KKU::KKStr::LocateLastOccurrence(), osLocateLastSlashChar(), and KKU::KKStr::SubStrPart().
Referenced by ImageExtractionManager::ExtractionParms::ParseCmdLine().
char * KKU::osReadNextLine (FILE * in)
Read the next line from the file and return a c-String(NULL terminated).
Will read in characters from 'in' until a line feed character is read. The caller will own the string returned and be responsible for deleting it.
Parameters
[in] in File to read from.
Returns
A dynamically allocated c-string (NULL Terminated) containing the next line in the file. If end-of-file reached will return a NULL pointer.
Todo:
This function has never be properly tested. Next time we use it we should debug through it to make sure that all is copacetic.
Definition at line 2072 of file OSservices.cpp.
References osGrowAllocation().
KKStr KKU::osReadNextQuotedStr (FILE * in, const char * whiteSpaceCharacters, bool & eof)
Read the next Quoted String from the file.
If the first non whitespace character is a quote (") character will read in rest of string until the next occurrence of a Quote character. Otherwise it will read in characters until another whitespace character occurs.
Parameters
[in] in File to read from.
[in] whiteSpaceCharacters c-string (NULL Terminated) list of white space characters.
[out] eof Will be set to true if we are at the end of file when you make the call.
Returns
A String containing the next String in the file.
Definition at line 2359 of file OSservices.cpp.
References KKU::KKStr::Append().
KKStr KKU::osReadNextToken (FILE * in, const char * delimiters, bool & eof, bool & eol)
Read the next logical token from a file using characters in 'delimiters' to separate tokens.
Use this function to read logical tokens from a file. It recognizes the concept of a line that is terminated by the line feed ('
') character. When end of line is reached it will return an empty string setting 'eol' to true; the very next call will return the first token on the next line. The leading whitespace characters ' ' and '' will be skipped before reading the next token. Tokens will be separated by any one of the characters specified in 'delimiters'. Two or more delimiters that occur consecutively will not be treated as one separator. You will need to call this method for each one.
ex: the string "Apple\tPeer\t\tGrape\t\n" with the delimiters = "\t" will generate the following tokens when "Apple", "Peer", "", "Grape", "", ""(eol = True)
Parameters
[in] in File handle to read from.
[in] delimiters c string listing delimiter characters.
[out] eof End of file flag. When this goes true so will eol, also no token will be returned.
[out] eol Will be set to true when the end-of-line is reached ('
'). No token will be returned. The next call to this method will start at the next line.
Returns
The next token read from the file. You must also monitor the 'eol' and 'eof' variables. If either one is true the no token will be returned.
Definition at line 2183 of file OSservices.cpp.
Referenced by MLL::AbundanceCorrectionMatrix::ReadArray(), ReadImagePGM(), ReadImagePNG(), MLL::AbundanceCorrectionMatrix::ReadVector(), MLL::AbundanceCorrectionMatrix::ReadXml(), SVM289_MFS::svm_load_model_XML_SupportVectorSection(), and SVM289_BFS::svm_load_model_XML_SupportVectorSection().
KKStr KKU::osReadNextToken (std::istream & in, const char * delimiters, bool & eof, bool & eol)
Read the next logical token from a file using characters in 'delimiters' to separate tokens.
Use this function to read logical tokens from a input stream. It recognizes the concept of a line that is terminated by the line feed ('
') character. When end of line is reached it will return an empty string setting 'eol' to true; the very next call will return the first token on the next line. The leading whitespace characters ' ' and '' will be skipped before reading the next token. Tokens will be separated by any one of the characters specified in 'delimiters'. Two or more delimiters that occur consecutively will not be treated as one separator. You will need to call this method for each one.
ex: the string "Apple\tPeer\t\tGrape\t\n" with the delimiters = "\t" will generate the following tokens when "Apple", "Peer", "", "Grape", "", ""(eol = True)
Parameters
[in] in Input Stream to read from.
[in] delimiters c string listing delimiter characters.
[out] eof End of file flag. When this goes true so will eol, also no token will be returned.
[out] eol Will be set to true when the end-of-line is reached ('
'). No token will be returned. The next call to this method will start at the next line.
Returns
The next token read from the file. You must also monitor the 'eol' and 'eof' variables. If either one is true the no token will be returned.
Definition at line 2110 of file OSservices.cpp.
KKStr KKU::osReadRestOfLine (std::istream & in, bool & eof)
Definition at line 2254 of file OSservices.cpp.
Referenced by MLL::DataBaseImageValidatedEntryList::Load(), and ReadImagePGM().
KKStr KKU::osReadRestOfLine (FILE * in, bool & eof)
Definition at line 2308 of file OSservices.cpp.
KKStr KKU::osRemoveExtension (const KKStr & _fullFileName)
Definition at line 947 of file OSservices.cpp.
References KKU::KKStr::LocateLastOccurrence(), osLocateLastSlashChar(), and KKU::KKStr::SubStrPart().
Referenced by MLL::ClassificationBiasMatrix::ClassificationBiasMatrix(), MLL::BitReduction::compress(), CreateBfsFromMfs(), MLL::Orderings::CreateOrderingsObjFromFileIfAvaliable(), MLL::TrainingConfiguration2::GetEffectiveConfigFileName(), MLL::Orderings::Orderings(), CrossValidationApp::ProcessCmdLineParameters(), PicesInterface::OSservices::RemoveExtension(), MLL::FeatureFileIO::SaveFeatureFileMultipleParts(), PicesInterface::PicesFeatureFileIO::SaveFeatureFileNormalized(), and CrossValidationApp::WriteABiasMatrix().
bool KKU::osRenameFile (const KKStr & oldName, const KKStr & newName)
Definition at line 661 of file OSservices.cpp.
References endl(), and KKU::KKStr::Str().
void KKU::osRunAsABackGroundProcess ()
Definition at line 1315 of file OSservices.cpp.
References backGroundProcess.
Referenced by ImageExtractionMultiThreaded(), ImageExtractionSingleThreaded(), CImageExtractionWindowsApp::InitInstance(), PicesInterface::PicesTrainingConfiguration::PicesTrainingConfiguration(), and PicesInterface::TrainingModel2::TrainingModel2().
void KKU::osSkipRestOfLine (FILE * in, bool & eof)
Skips rest of the characters in the current line in the file.
Will skip all characters in 'in' until a '
' is read or the end of file has been reached. It is meant be be used in conjunction with 'osReadNextToken'.
Parameters
[in] in File being read.
[out] eof Will be set to true if end of file is encountered.
Definition at line 2466 of file OSservices.cpp.
void KKU::osSkipRestOfLine (std::istream & in, bool & eof)
Skips rest of the characters in the current line in the input stream.
Will skip all characters in 'in' until a '
' is read or the end of file has been reached. It is meant be be used in conjunction with 'osReadNextToken'.
Parameters
[in] in File being read.
[out] eof Will be set to true if end of file is encountered.
Definition at line 2481 of file OSservices.cpp.
void KKU::osSleep (float numOfSecs)
Definition at line 2523 of file OSservices.cpp.
References endl().
Referenced by ImageExtractionManager::ExtractedImageQueue::AddExtractedImage(), JobManagment::JobManager::Block(), ImageExtractionManager::ExtractionManager::CancelProcessing(), CImageExtractionWindowsDlg::ManageImageExtractionMultiThreaded(), KKU::KKThreadManager::ManageThreads(), ImageExtractionManager::DataBaseUpdateThread::Run(), JobManagment::JobManager::Run(), KKU::KKThreadManager::ShutdownProcessing(), and KKU::GoalKeeper::StartBlock().
VectorKKStr KKU::osSplitDirectoryPathIntoParts (const KKStr & path)
Definition at line 2616 of file OSservices.cpp.
References KKU::KKStr::Len(), and KKU::KKStr::SubStrPart().
KKStr KKU::osSubstituteInEvironmentVariables (const KKStr & src)
Substitute in the value of the environment variables into 'src'.
Will scan the 'src' string for references to environment variables. The format would be $(env-var-name). These sub-strings in 'src' will be replaced by the the actual value of the environment variable. If no such environment variable exists the substring will be left as is. besides parentheses '{}' or '[]' can be uses, ex the string "${KinseyHomeDir}\\Reports" would be replaced by "c:\Kinsey\reports"
Parameters
[in] src String that you want to scan for environment variables.
Returns
'src' string with environment variables expanded.
Definition at line 2571 of file OSservices.cpp.
References KKU::KKStr::LocateCharacter(), LocateEnvStrStart(), osGetEnvVariable(), KKU::KKStr::SubStrPart(), and x.
bool KKU::osValidDirectory (KKStrConstPtr _name)
Definition at line 384 of file OSservices.cpp.
Referenced by PicesInterface::TrainingModel2::AddImageToTrainingLibray(), PicesInterface::OSservices::DirectoryExists(), osCreateDirectoryPath(), SipperHardware::SipperVariables::PicesTempDirectory(), and CrossValidationApp::ProcessCmdLineParameter().
bool KKU::osValidDirectory (const KKStr & _name)
Definition at line 397 of file OSservices.cpp.
References KKU::KKStr::Str().
void KKU::osWaitForEnter ()
Definition at line 1329 of file OSservices.cpp.
References backGroundProcess, and endl().
Referenced by MLL::FeatureVector::AddFeatureData(), KKU::Matrix::CalcCoFactorMatrix(), MLL::FileDesc::Cardinality(), CrossValidationApp::CheckForDuplicates(), MLL::FeatureEncoder2::CreateEncodedFileDesc(), MLL::FeatureEncoder::CreateEncodedFileDesc(), MLL::FeatureNumList::FeatureNumList(), MLL::CrossValidationThreeWay::FoldAccuracy(), MLL::CrossValidation::FoldAccuracy(), MLL::CrossValidationVoting::FoldAccuracy(), KKU::Raster::FourierExtractFeatures(), MLL::ClassAssignments::GetMLClassByIndex(), KKU::Raster::HistogramEqualizedImage(), MLL::ChainHash< T >::insert(), CrossValidationApp::Main(), MLL::NormalizationParms::NormalizeImages(), KKU::Row::operator[](), MLL::FeatureNumList::operator[](), MLL::Orderings::Ordering(), osCopyFile(), osCopyFileBetweenDirectories(), osDisplayWarning(), osMoveFileBetweenDirectories(), PairedTTest(), CrossValidationApp::ProcessCmdLineParameter(), CrossValidationApp::ProcessCmdLineParameters(), MLL::TrainingConfiguration2::PromptForConfigurationFile(), JobManagment::JobList::PushOnBack(), MLL::FeatureVectorList::PushOnBack(), MLL::FeatureVectorList::PushOnFront(), MLL::FeatureVectorList::ResetFileDesc(), MLL::FeatureVector::ResetNumOfFeatures(), MLL::FeatureVectorList::ReSyncSymbolicData(), MLL::Orderings::Save(), SetUpJMLRDataSet(), SplitUpETPdataSet(), SplitUpForestData(), JobManagment::JobManager::StatusFileProcessLineJobStatusChange(), MLL::FeatureVectorList::SynchronizeSymbolicData(), and CrossValidationApp::ValidationProcess().
float KKU::PairedTTest (const KKU::VectorFloat & set1, const KKU::VectorFloat & set2)
Definition at line 24 of file StatisticalFunctions.cpp.
References endl(), and osWaitForEnter().
RasterPtr KKU::ReadImage (const KKStr & imageFileName)
Definition at line 288 of file ImageIO.cpp.
References osGetFileExtension(), ReadImagePGM(), ReadImagePNG(), and KKU::KKStr::ToLower().
Referenced by KKU::Raster::Raster().
RasterPtr KKU::ReadImagePGM (const KKStr & imageFileName)
Definition at line 319 of file ImageIO.cpp.
References endl(), KKU::KKStr::FirstChar(), osFOPEN(), osReadNextToken(), osReadRestOfLine(), KKU::Raster::SetPixelValue(), KKU::KKStr::Str(), and KKU::KKStr::ToInt().
Referenced by ReadImage().
RasterPtr KKU::ReadImagePNG (const KKStr & imageFileName)
Definition at line 400 of file ImageIO.cpp.
References KKU::Raster::BlueArea(), endl(), KKU::KKStr::EqualIgnoreCase(), KKU::KKStr::ExtractTokenInt(), KKU::Raster::GreenArea(), osFOPEN(), osReadNextToken(), KKU::Raster::RedArea(), KKU::KKStr::Str(), KKU::KKStr::ToInt(), and x.
Referenced by ReadImage().
void KKU::SaveImage (const Raster & image, const KKStr & imageFileName)
Definition at line 501 of file ImageIO.cpp.
References endl(), osGetFileExtension(), KKU::BmpImage::Save(), SaveImagePGM(), SaveImagePNG(), and KKU::KKStr::Upper().
Referenced by PicesInterface::PicesRaster::Save(), KKU::Chart::SaveAsImage(), KKU::Histogram::SaveGraphImage(), SaveImageInverted(), KKU::Raster::SegmentImage(), and SegmentPolutionImage().
void KKU::SaveImageGrayscaleInverted4Bit (const Raster & image, const KKStr & _fileName)
Saves image as BMP file using 4 bit compressed grayscale where Background = 255 and foreground = 0.
If image is color will convert to grayscale 1st. Palette will be set to 0 = 255, 1 = 238, 2 = 221, 3 = 204... 255 = 0.
Definition at line 1010 of file ImageIO.cpp.
References endl(), and KKU::BmpImage::SaveGrayscaleInverted4Bit().
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run(), and PicesInterface::PicesRaster::Save().
void KKU::SaveImageGrayscaleInverted8Bit (const Raster & image, const KKStr & _fileName)
Saves image as BMP using compressed grayscale where Background = 255 and foreground = 0.
If image is color will convert to grayscale 1st. Palette will be set to 0 = 255, 1 = 254, 2 = 253, ... 255 = 0.
Definition at line 1045 of file ImageIO.cpp.
References endl(), and KKU::BmpImage::SaveGrayscaleInverted8Bit().
Referenced by PicesInterface::TrainingModel2::AddImageToTrainingLibray().
void KKU::SaveImageInverted (Raster & raster, const KKStr & imageFileName)
Definition at line 972 of file ImageIO.cpp.
References KKU::Raster::Blue(), KKU::Raster::Color(), KKU::Raster::Green(), KKU::Raster::Height(), KKU::Raster::Red(), SaveImage(), and KKU::Raster::Width().
void KKU::SaveImagePGM (const Raster & image, const KKStr & imageFileName)
Definition at line 559 of file ImageIO.cpp.
References KKU::Raster::Color(), KKU::Raster::CreateGrayScale(), endl(), KKU::Raster::GreenArea(), KKU::Raster::Height(), KKU::KKStr::Len(), osFOPEN(), KKU::KKStr::Str(), and KKU::Raster::Width().
Referenced by SaveImage().
void KKU::SaveImagePNG (const Raster & image, const KKStr & imageFileName)
Definition at line 597 of file ImageIO.cpp.
References KKU::Raster::BlueArea(), KKU::Raster::Color(), endl(), KKU::Raster::GreenArea(), KKU::Raster::Height(), KKU::KKStr::Len(), osFOPEN(), KKU::Raster::RedArea(), KKU::KKStr::Str(), KKU::Raster::Width(), and x.
Referenced by SaveImage().
RasterPtr KKU::SegmentPolutionImage (RasterPtr r, KKStr fileName)
Definition at line 1089 of file ImageIO.cpp.
References KKU::Raster::Color(), KKU::Raster::CreateGrayScale(), KKU::Raster::HistogramGrayscale(), osAddLastSlash(), osCreateDirectoryPath(), osGetRootName(), KKU::Histogram::Save(), KKU::Histogram::SaveGraphImage(), SaveImage(), and KKU::Histogram::Smooth().
int32 KKU::SPRINTF (char * buff, int32 buffSize, const char * formatSpec, int16 right)
Definition at line 154 of file Str.cpp.
Referenced by SipperHardware::InstrumentData::FieldToStr(), KKU::KKStr::KKStr(), KKU::KKStr::operator+(), operator<<(), KKU::RunLog::operator<<(), KKU::KKStr::operator<<(), KKU::KKStr::operator=(), StrFromInt16(), StrFromInt32(), StrFromInt64(), StrFromUint16(), StrFromUint32(), and StrFromUint64().
int32 KKU::SPRINTF (char * buff, int32 buffSize, const char * formatSpec, uint16 right)
Definition at line 169 of file Str.cpp.
int32 KKU::SPRINTF (char * buff, int32 buffSize, const char * formatSpec, int32 right)
Definition at line 185 of file Str.cpp.
int32 KKU::SPRINTF (char * buff, int32 buffSize, const char * formatSpec, uint32 right)
Definition at line 200 of file Str.cpp.
int32 KKU::SPRINTF (char * buff, int32 buffSize, const char * formatSpec, int64 right)
Definition at line 215 of file Str.cpp.
int32 KKU::SPRINTF (char * buff, int32 buffSize, const char * formatSpec, uint64 right)
Definition at line 231 of file Str.cpp.
int32 KKU::SPRINTF (char * buff, int32 buffSize, const char * formatSpec, int32 precision, double d)
Definition at line 247 of file Str.cpp.
int32 KKU::SPRINTF (char * buff, int32 buffSize, char const * formatSpec, double d)
Definition at line 263 of file Str.cpp.
void KKU::SRand48 (int64 _seed)
Seeds the lrand48 functions with the parameters passed to it.
Definition at line 35 of file BasicTypes.cpp.
References _lrand48_sequence.
Referenced by MLL::UsfCasCor::setup_network().
char * KKU::STRCAT (char * dest, int32 destSize, const char * src)
Definition at line 68 of file Str.cpp.
Referenced by MLL::DataBase::ImageFullSizeSave().
char * KKU::STRCOPY (char * dest, int32 destSize, const char * src)
Definition at line 41 of file Str.cpp.
Referenced by KKU::KKStr::EnterStr(), MLL::DataBase::ImageFullSizeSave(), KKU::KKStr::KKStr(), KKU::KKStr::operator=(), and KKU::KKStr::StrReplace().
char * KKU::STRCOPY (char * dest, uint16 destSize, const char * src)
Definition at line 26 of file Str.cpp.
char * KKU::STRDUP (const char * src)
Definition at line 56 of file Str.cpp.
Referenced by KKU::KKStrParser::KKStrParser(), and KKU::KKStrParser::TrimWhiteSpace().
KKStr KKU::StrFormatDouble (double val, const char * mask)
Definition at line 4227 of file Str.cpp.
References LocateLastOccurrence(), and x.
Referenced by MLL::ConfusionMatrix2::AccuracyStr(), SipperHardware::InstrumentDataManager::CompReportLine(), MLL::CrossValidationThreeWay::CreateDistanceReport(), MLL::CrossValidationThreeWay::CreateProbabilityReport(), CrossValidationApp::CrossValidate(), MLL::ChainHash< T >::DoSomeStats(), SipperHardware::InstrumentData::FieldToStr(), MLL::CrossValidation::FoldAccuracysToStr(), MLL::CrossValidationVoting::FoldAccuracysToStr(), MLL::DataBase::GpsDataInsert(), SipperHardware::SipperHeaderRec::HeaderStr(), MLL::DataBase::InstrumentDataBinByMeterDepth(), MLL::DataBase::InstrumentDataUpdateLatitudeAndLongitude(), SipperHardware::SipperVariables::LatitudeToStr(), SipperHardware::SipperVariables::LongitudeToStr(), CrossValidationApp::Main(), MLL::UsfCasCor::PRINT_SUMMARY(), MLL::ConfusionMatrix2::PrintAccuracyByProbByClassHTML(), MLL::ConfusionMatrix2::PrintConfusionMatrixAvgPredProbHTML(), MLL::ConfusionMatrix2::PrintConfusionMatrixLatexTable(), MLL::AbundanceCorrectionMatrix::PrintConfusionMatrixTabDelimited(), MLL::ConfusionMatrix2::PrintConfusionMatrixTabDelimited(), MLL::ConfusionMatrix2::PrintTrueFalsePositivesTabDelimited(), MLL::DataBase::SipperDeploymentInsert(), MLL::DataBase::SipperDeploymentUpdate(), StrFormatInt(), SipperHardware::CTD_Plus_Data::ToStrNoLabels(), CrossValidationApp::ValidationProcess(), MLL::ConfusionMatrix2::WriteSimpleConfusionMatrix(), and MLL::ClassificationBiasMatrix::WriteXML().
KKStr KKU::StrFormatInt (int32 val, const char * mask)
Definition at line 4412 of file Str.cpp.
References StrFormatDouble().
Referenced by SipperHardware::InstrumentDataManager::CompReportLine(), MLL::FeatureEncoder2::CreateEncodedFileDesc(), MLL::FeatureEncoder::CreateEncodedFileDesc(), SipperHardware::InstrumentDataList::CreateFromSipperFile(), KKU::Configuration::FormatErrorsWithLineNumbers(), MLL::FeatureFileIOColumn::GetFileDesc(), MLL::FeatureFileIOUCI::GetFileDesc(), MLL::FeatureFileIOSparse::GetFileDesc(), SipperHardware::SipperHeaderRec::HeaderStr(), KKU::TimeType::HH_MM_SS(), KKU::DateTime::HH_MM_SS(), KKU::TimeType::HHMMSS(), MLL::DataBaseImage::ImageFileName(), MLL::DataBase::ImageListOfImageFileNamesByScanLineRange(), MLL::DataBase::ImagesLocateClosestImage(), MLL::DataBase::ImagesQueryForScanLineRange(), MLL::DataBase::ImageUpdate(), MLL::DataBase::InstrumentDataGetByScanLine(), SipperHardware::InstrumentDataReport::InstrumentName(), SipperHardware::SipperVariables::LatitudeToStr(), MLL::FeatureFileIOColumn::LoadFile(), MLL::FeatureFileIOUCI::LoadFile(), MLL::FeatureFileIOPices::LoadFile(), MLL::FeatureFileIOC45::LoadFile(), MLL::FeatureFileIOSparse::LoadFile(), SipperHardware::SipperVariables::LongitudeToStr(), KKU::DateType::MM_DD_YY(), KKU::DateType::MMM_DD_YYYY(), MLL::FileDesc::NewContinuousDataOnly(), KKU::KKStrMatrix::operator()(), KKU::RunLog::operator<<(), operator<<(), KKU::KKStrMatrix::operator[](), osCreateUniqueFileName(), ImageExtractionManager::ExtractionParms::ParseCmdLine(), MLL::FeatureFileIOPices::PlanktonFieldName(), MLL::TrainingConfiguration2::PromptForConfigurationFile(), MLL::FeatureFileIO::SaveFeatureFileMultipleParts(), MLL::FeatureFileIOPices::SaveFile(), KKU::Raster::SegmentImage(), MLL::DataBase::SipperDeploymentInsert(), MLL::DataBase::SipperDeploymentUpdate(), MLL::SipperExtractionImageManager::ManagedClass::StartNewDirectory(), KKU::KKStr::StrReplace(), SVM233::svm_model::SupportVectorName(), MLL::ModelParamKnn::ToCmdLineStr(), KKU::PixelValue::ToStr(), KKU::DateType::YY_MM_DD(), KKU::DateType::YYYY_MM_DD(), KKU::DateType::YYYY_MMM_DD(), and KKU::DateType::YYYYMMDD().
KKStr KKU::StrFormatInt64 (int64 val, const char * mask)
Definition at line 4421 of file Str.cpp.
Referenced by KKU::RunLog::operator<<(), and KKU::KKStr::operator<<().
KKStr KKU::StrFromInt16 (int16 i)
Definition at line 4560 of file Str.cpp.
References SPRINTF().
KKStr KKU::StrFromInt32 (int32 i)
Definition at line 4583 of file Str.cpp.
References SPRINTF().
Referenced by SipperHardware::InstrumentData::FieldToStr().
KKStr KKU::StrFromInt64 (int64 i)
Definition at line 4606 of file Str.cpp.
References SPRINTF().
KKStr KKU::StrFromUint16 (uint16 ui)
Definition at line 4572 of file Str.cpp.
References SPRINTF().
KKStr KKU::StrFromUint32 (uint32 ui)
Definition at line 4595 of file Str.cpp.
References SPRINTF().
Referenced by SipperHardware::InstrumentData::FieldToStr(), and MLL::DataBase::ImagesEraseSipperFileSizeRange().
KKStr KKU::StrFromUint64 (uint64 ui)
Definition at line 4617 of file Str.cpp.
References SPRINTF().
Referenced by SipperHardware::InstrumentData::FieldToStr().
int32 KKU::STRICMP (const char * left, const char * right)
Comapares to string, case insensative, returning (-1 = less) (0 = equal), and (1 = greater).
Definition at line 84 of file Str.cpp.
Referenced by MLL::UsfCasCor::string_to_boolean(), MLL::UsfCasCor::string_to_type(), and KKU::KKStr::ToBool().
int32 KKU::STRNICMP (const char * left, const char * right, int32 len)
Definition at line 118 of file Str.cpp.
References x.
Referenced by KKU::KKStr::StartsWith().
bool KKU::SupportedImageFileFormat (const KKStr & imageFileName)
Definition at line 1074 of file ImageIO.cpp.
References osGetFileExtension(), and KKU::KKStr::Upper().
Referenced by MLL::FeatureFileIOPices::FeatureDataReSink(), and osGetListOfImageFiles().
template<class T > T KKU::Swap (T & x, T & y)
Definition at line 236 of file BasicTypes.h.
References x.
Referenced by KKU::KK_DFT< DftType >::TransformNR().
void KKU::tqli (int32 n, double * d, double * e, double z[2][2])
Definition at line 190 of file EigenVector.cpp.
References endl(), pythag(), and SIGN().
Referenced by KKU::Raster::CalcOrientationAndEigerRatio().
void KKU::Tred2 (int32 n, double a[2][2], double * d, double * e)
Definition at line 30 of file EigenVector.cpp.
Referenced by KKU::Raster::CalcOrientationAndEigerRatio().
template<typename T > KKStr KKU::VectorToDelimitedStr (std::vector< T > v, char delimiter)
Definition at line 765 of file Str.h.
References x.