Pices: MLL Namespace Reference
MLL Namespace Reference
Namespace for all Machine Learning and SIPPER specific code.
Classes
class AbundanceCorrectionMatrix
Confusion matrix used to compute adjustment vectors used to make adjustments to classification results.
class Attribute
describes a single Feature, Type and possible values.
class AttributeList
class BinaryClassParms
Machine Learning parameters to be used by a pair of classes.
class BinaryClassParmsList
class BitReduction
This class is responsible for performing tBit reduction compression of FeatureVector lists.
class ChainHash
class ChainHashNode
class ClassAssignments
Binds MLClass objects to the appropriate number that the Learning Algorithm expects.
class ClassificationBiasMatrix
Assists in adjusting a Classifiers output for the bias of a classifier.
class Classifier2
class ClassIndexList
Maintains a list of classes and their associated integer index.
class ClassProb
Used to record probability for a specified class; and a list of classes.
class ClassProbList
class ClassStatistic
Used by routines that retrieve Class statistics from FeatureVectorList instances.
class ClassStatisticList
struct CompressionStats
class ConfusionMatrix2
A confusion matrix object that is used to record the results from a CrossValidation.
class ConfussionMatrix2List
class CrossValidation
A class that is meant to manage a n-Fold Cross Validation.
class CrossValidationMxN
class CrossValidationThreeWay
class CrossValidationVoting
class DataBase
DataBase connection management object.
class DataBaseGpsData
class DataBaseGpsDataList
class DataBaseImage
class DataBaseImageEntry
class DataBaseImageEntryList
class DataBaseImageGroup
class DataBaseImageGroupEntry
class DataBaseImageGroupEntryList
class DataBaseImageGroupList
class DataBaseImageList
class DataBaseImageValidatedEntry
class DataBaseImageValidatedEntryList
class DataBaseLogEntry
class DataBaseLogEntryList
class DataBaseServer
Represents the parameters for a single Database Server.
class DataBaseServerList
class DataBaseUpdate
Routines used to update the MySql database to the curent version.
class DuplicateImage
class DuplicateImageList
class DuplicateImages
Detects duplicate images in a given FeaureVectorList objects.
class ExtractFeatureData
class ExtractImageFileName
class FeatureEncoder
class FeatureEncoder2
class FeatureFileIO
Base class for all FeatureFileIO classes.
class FeatureFileIOArff
Support the writting of ARFF Formated Feature Files.
class FeatureFileIOC45
Supports the reading and writting of feature data from C45 formated fearture files.
class FeatureFileIOColumn
Supports a simple Feature File format where each collumn represents a example and each row a feature value.
class FeatureFileIODstWeb
FeatureFileIODstWeb Sub-classed from FeatureFileIO.
class FeatureFileIOPices
Supports the reading and writting of feature data from and to Pices feature data files.
class FeatureFileIORoberts
Supports the writting of Feature Data to a file that can then be read by OpenDT.
class FeatureFileIOSparse
Supports the reading and writting of Sparse feature files similar to the ones libSVM use.
class FeatureFileIOUCI
Supports the reading and writting of Feature data from a file format commonly used by many datasets in the UCI repository.
class FeatureNumList
Keeps track of selected features.
class FeatureVector
Represents a Feature Vector of a single example, labeled or unlabele.
class FeatureVectorList
Container class for FeatureVector derived objects.
class FileDesc
Provides a detailed description of the attributes of a dataset.
class FileDescList
class GPSDataPoint
class ImageDataTreeEntry
class ImageFeatures
Specialized version of MLL::FeatureVector that will be used to represent the features of a SIPPER Plankton image.
class ImageFeaturesDataIndexed
class ImageFeaturesList
class ImageFeaturesNameIndexed
class ImageFeaturesNodeKey
class InstrumentDataList
class KArray
class LogicalFrameBlob
Used by the ImageExtractionManager to manage a single blob.
class MLClass
Represents a "Class" in the Machine Learnining Sense.
class MLClassConstList
class MLClassList
Maintains a list of MLClass instances.
class Model
Base class to all Learning Algorithms.
class ModelDual
Will implement the Dual Classifoer Model.
class ModelKnn
class ModelOldSVM
class ModelParam
Abstract Base class for Machine Learning parameters.
class ModelParamDual
                      Parameters used for the Dual Classifier.
class ModelParamKnn
class ModelParamOldSVM
this class encapsulates are the information neccesary to build a SVMModel class.
class ModelParamSvmBase
This class encapsulates general parameters that are common to all Machine Learning Models.
class ModelParamUsfCasCor
This class encapsulates are the information neccesary to build a UsfCasCor class.
class ModelSvmBase
class ModelUsfCasCor
class NormalizationParms
Normalization Parameters; calculation and implementation.
class Orderings
Used to maintain multiple orderings of a single list of FeatureVector objects.
class ProbNamePair
class SipperBlob
Used by SipperImageExtrtaction to manage a single blob.
class SipperExtractionImageManager
class SizeDistribution
struct svm_node_int
class SVMModel
class SVMparam
this class encapsulates are the information neccesary to build a SVMModel class.
class TrainingClass
class TrainingClassList
class TrainingConfiguration2
class TrainingConfiguration2List
class TrainingProcess2
class UsfCasCor
class VolumeSampledStat
Typedefs
typedef AbundanceCorrectionMatrix * AbundanceCorrectionMatrixPtr
typedef Attribute * AttributePtr
typedef std::vector
< AttributeType > AttributeTypeVector
typedef AttributeTypeVector * AttributeTypeVectorPtr
typedef
BinaryClassParmsList::BinaryClassParmsListPtr BinaryClassParmsListPtr
typedef
BinaryClassParms::BinaryClassParmsPtr BinaryClassParmsPtr
typedef ChainHashNode * ChainHashNodePtr
typedef ClassAssignments * ClassAssignmentsPtr
typedef
ClassificationBiasMatrix::ClassificationBiasMatrixPtr ClassificationBiasMatrixPtr
typedef Classifier2 * Classifier2Ptr
typedef
ClassIndexList::ClassIndexListPtr ClassIndexListPtr
typedef ClassProbList * ClassProbListPtr
typedef ClassProb * ClassProbPtr
typedef ClassStatisticList * ClassStatisticListPtr
typedef ClassStatistic * ClassStatisticPtr
typedef
ConfusionMatrix2::ConfusionMatrix2Ptr ConfusionMatrix2Ptr
typedef ConfussionMatrix2List * ConfussionMatrix2ListPtr
typedef CrossValidation * CrossValidationPtr
typedef CrossValidationThreeWay * CrossValidationThreeWayPtr
typedef CrossValidationVoting * CrossValidationVotingPtr
typedef
DataBaseGpsDataList::DataBaseGpsDataListPtr DataBaseGpsDataListPtr
typedef
DataBaseGpsData::DataBaseGpsDataPtr DataBaseGpsDataPtr
typedef
DataBaseImageEntryList::DataBaseImageEntryListPtr DataBaseImageEntryListPtr
typedef
DataBaseImageEntry::DataBaseImageEntryPtr DataBaseImageEntryPtr
typedef
DataBaseImageGroupEntryList::DataBaseImageGroupEntryListPtr DataBaseImageGroupEntryListPtr
typedef
DataBaseImageGroupEntry::DataBaseImageGroupEntryPtr DataBaseImageGroupEntryPtr
typedef
DataBaseImageGroupList::DataBaseImageGroupListPtr DataBaseImageGroupListPtr
typedef
DataBaseImageGroup::DataBaseImageGroupPtr DataBaseImageGroupPtr
typedef
DataBaseImageList::DataBaseImageListPtr DataBaseImageListPtr
typedef
DataBaseImage::DataBaseImagePtr DataBaseImagePtr
typedef
DataBaseImageValidatedEntryList::DataBaseImageValidatedEntryListPtr DataBaseImageValidatedEntryListPtr
typedef
DataBaseImageValidatedEntry::DataBaseImageValidatedEntryPtr DataBaseImageValidatedEntryPtr
typedef
DataBaseLogEntryList::DataBaseLogEntryListPtr DataBaseLogEntryListPtr
typedef
DataBaseLogEntry::DataBaseLogEntryPtr DataBaseLogEntryPtr
typedef DataBase::DataBasePtr DataBasePtr
typedef DataBaseServerList * DataBaseServerListPtr
typedef DataBaseServer * DataBaseServerPtr
typedef
DataBaseUpdate::DataBaseUpdatePtr DataBaseUpdatePtr
typedef DuplicateImageList * DuplicateImageListPtr
typedef DuplicateImage * DuplicateImagePtr
typedef DuplicateImages * DuplicateImagesPtr
typedef std::vector< double > Dvector
typedef
FeatureEncoder2::FeatureEncoder2Ptr FeatureEncoder2Ptr
typedef FeatureEncoder * FeatureEncoderPtr
typedef
FeatureFileIOC45::FeatureFileIOC45Ptr FeatureFileIOC45Ptr
typedef
FeatureFileIOPices::FeatureFileIOPicesPtr FeatureFileIOPicesPtr
typedef FeatureFileIO * FeatureFileIOPtr
typedef FeatureNumList * FeatureNumListPtr
typedef FeatureVectorList * FeatureVectorListPtr
typedef FeatureVector * FeatureVectorPtr
typedef FeWhatToDo * FeWhatToDoPtr
typedef FileDescList * FileDescListPtr
typedef FileDesc * FileDescPtr
typedef std::vector< float > Fvector
typedef ImageFeaturesDataIndexed * ImageFeaturesDataIndexedPtr
typedef ImageFeaturesList * ImageFeaturesListPtr
typedef ImageFeaturesNameIndexed * ImageFeaturesNameIndexedPtr
typedef ImageFeatures * ImageFeaturesPtr
typedef std::vector< int32 > Ivector
typedef MLClass const MLClassConst
typedef MLClassConstList * MLClassConstListPtr
typedef MLClass const * MLClassConstPtr
typedef MLClassList * MLClassListPtr
typedef MLClass * MLClassPtr
typedef ModelDual::ModelDualPtr ModelDualPtr
typedef ModelKnn::ModelKnnPtr ModelKnnPtr
typedef ModelOldSVM::ModelOldSVMPtr ModelOldSVMPtr
typedef ModelParamDual * ModelParamDualPtr
typedef
ModelParamKnn::ModelParamKnnPtr ModelParamKnnPtr
typedef ModelParamOldSVM * ModelParamOldSVMPtr
typedef ModelParam::ModelParamPtr ModelParamPtr
typedef
ModelParamSvmBase::ModelParamSvmBasePtr ModelParamSvmBasePtr
typedef ModelParamUsfCasCor * ModelParamUsfCasCorPtr
typedef Model::ModelPtr ModelPtr
typedef
ModelSvmBase::ModelSvmBasePtr ModelSvmBasePtr
typedef
ModelUsfCasCor::ModelUsfCasCorPtr ModelUsfCasCorPtr
typedef NormalizationParms * NormalizationParmsPtr
typedef Orderings * OrderingsPtr
typedef RunLog * RunLogPtr
typedef SipperBlob::SipperBlobPtr SipperBlobPtr
typedef
SipperExtractionImageManager * SipperExtractionImageManagerPtr
typedef SizeDistribution * SizeDistributionPtr
typedef SVMModel * SVMModelPtr
typedef SVMparam * SVMparamPtr
typedef TrainingClassList * TrainingClassListPtr
typedef TrainingClass * TrainingClassPtr
typedef
TrainingConfiguration2List * TrainingConfiguration2ListPtr
typedef TrainingConfiguration2 * TrainingConfiguration2Ptr
typedef
TrainingConfiguration2List * TrainingConfigurationList2Ptr
typedef TrainingProcess2 * TrainingProcess2Ptr
typedef UsfCasCor * UsfCasCorPtr
typedef
SipperBlob::VectorSipperBlob VectorSipperBlob
typedef struct svm_node * XSpacePtr
Enumerations
enum AttributeType {
IgnoreAttribute, NumericAttribute, NominalAttribute, OrdinalAttribute,
SymbolicAttribute, NULLAttribute
}
enum FeWhatToDo { FeAsIs, FeBinary, FeScale }
enum Learn_Type {
NORMAL, BAGGING, BOOSTING, SUBSPACE,
SAMPLESV
}
enum SVM_CompressionMethod {
BRNull, BRnoCompression, BRcompressionPost, BRcompressionPre,
BRunBalancedVariance, BRunBalancedSpecified
}
enum SVM_EncodingMethod { NoEncoding, BinaryEncoding, ScaledEncoding, Encoding_NULL }
enum SVM_KernalType { KT_Linear, KT_Polynomial, KT_RBF, KT_NULL }
enum SVM_MachineType {
MachineType_NULL, OneVsOne, OneVsAll, BinaryCombos,
BoostSVM
}
enum SVM_SelectionMethod { SelectionMethod_NULL, SelectByVoting, SelectByProbability }
Functions
KKStr AttributeTypeToStr (AttributeType type)
void CompareTwoSetsOfGroups (vector< vector< KKStr > > &groups1, vector< vector< KKStr > > &groups2, std::ostream &r)
SVM_CompressionMethod CompressionMethodFromStr (const KKStr &compressionMethodStr)
KKStr CompressionMethodStr (SVM_CompressionMethod compressionMethod)
void EncodeProblem (const struct svm_paramater &param, struct svm_problem &prob_in, struct svm_problem &prob_out)
SVM_EncodingMethod EncodingMethodFromStr (const KKStr &encodingMethodStr)
KKStr EncodingMethodToStr (SVM_EncodingMethod encodingMethod)
SVM_KernalType KernalTypeFromStr (const KKStr &kernalTypeStr)
KKStr KernalTypeToStr (SVM_KernalType kernalType)
SVM_MachineType MachineTypeFromStr (const KKStr &machineTypeStr)
KKStr MachineTypeToStr (SVM_MachineType machineType)
ostream & operator<< (ostream &o, const CompressionStats &stats)
std::ostream & operator<< (std::ostream &os, const MLClassConstList &classList)
std::ostream & operator<< (std::ostream &os, const FeatureNumList &features)
KKStr & operator<< (KKStr &str, const MLClassConstList &classList)
KKStr & operator<< (KKStr &left, TrainingConfiguration2::ModelTypes modelingMethod)
std::ostream & operator<< (std::ostream &os, TrainingConfiguration2::ModelTypes modelingMethod)
std::ostream & operator<< (std::ostream &os, const MLClassList &classList)
KKStr & operator<< (KKStr &str, const MLClassList &classList)
bool PairCompareOperator (ProbNamePair l, ProbNamePair r)
SVM_SelectionMethod SelectionMethodFromStr (const KKStr &selectionMethodStr)
KKStr SelectionMethodToStr (SVM_SelectionMethod selectionMethod)
void SvmDestroyModel (struct svm_model **subModel)
struct svm_model ** SvmLoadModel (const char *fileName)
struct svm_model ** SvmLoadModel (istream &f, RunLog &log)
void SvmPredictClass (SVMparam &svmParam, struct svm_model **subModel, const struct svm_node *unknownClassFeatureData, int32 *votes, double *probabilities, int32 knownClass, int32 &predClass1, int32 &predClass2, int32 &predClass1Votes, int32 &predClass2Votes, double &predClass1Prob, double &predClass2Prob, double &probOfKnownClass, double &compact, Ivector &winners, double **crossClassProbTable, double &breakTie)
int32 SvmPredictTwoClass (const struct svm_parameter &param, svm_model **submodel, const svm_node *unKnownData, int32 desired, double &dist, double &probability, int32 excludeSupportVectorIDX)
void SvmSaveModel (ostream &o, struct svm_model **model)
void SvmSaveModel (struct svm_model **subModel, const char *fileName, bool &successfull)
struct svm_model ** SvmTrainModel (const struct svm_parameter &param, struct svm_problem &subprob)
Variables
const char * FeatureDecriptions []
MLClassList globalClassList
Detailed Description
Namespace for all Machine Learning and SIPPER specific code.
Author
Kurt Krame * Date: 2009-04-16 *
A library of routines used for Machine Learning, building Classifiers, etc. It also includes code that is specific to PICES and SIPPER. At som point ion the future we need split this library into three libraries. MachineLearning, DataBase, and PicesRoutines.
This library covers three different areas that at some time in the future should be made into three seperate libraries.
1) Generic Machine Learning code.
2) Database Related Code.
3) Analysis.
4) PICES specific code that would be built onto of 1 and 2.
"Machine Learning Code"
"Feature Data"
There are several Feature Data formats supported. Each one has its own class that is derived from 'FeatureFileIO'. The decription of the data is managed by 'FileDesc'. For each type of dataset there will exist on one instance of a FileDesc class.
See Also
Attribute
FeatureNumList
FeatureFileIO
FeatureVector
FeatureVectorList
MLClass
BitReduction
FeatureEncoder
NormalizationParms
Orderings
"Learning Algorithms"
There are several learning algorithms implemented. The Learning algorithms are all subclassed from 'Model' and their related parameters are all subclassed from 'ModelParam'.
See Also
Model
ModelKnn
ModelOldSVM
ModelSvmBase
ModelParam
TrainingClass
TrainingProcess2
"Analysis Routines"
See Also
ConfusionMatrix2
CrossValidation
CrossValidationMxN
CrossValidationVoting
SizeDistribution
"Data Base"
See Also
DataBase
DataBaseServer
"PICES Specific"
This is code that is built on the SipperInstruments (aka SipperHardware Namespace), Machine Learning Code, Featuire Data Code
See Also
ImageFeatures
TrainingConfiguration2
DataBaseImage
DuplicateImages
SipperExtractionImageManager
Typedef Documentation
typedef AbundanceCorrectionMatrix* MLL::AbundanceCorrectionMatrixPtr
Definition at line 158 of file AbundanceCorrectionMatrix.h.
typedef Attribute* MLL::AttributePtr
Definition at line 123 of file Attribute.h.
typedef std::vector<AttributeType> MLL::AttributeTypeVector
Definition at line 46 of file Attribute.h.
typedef AttributeTypeVector* MLL::AttributeTypeVectorPtr
Definition at line 48 of file Attribute.h.
typedef BinaryClassParmsList * MLL::BinaryClassParmsListPtr
Definition at line 165 of file BinaryClassParms.h.
typedef BinaryClassParms * MLL::BinaryClassParmsPtr
Definition at line 100 of file BinaryClassParms.h.
typedef ChainHashNode * MLL::ChainHashNodePtr
Definition at line 25 of file ChainHash.h.
typedef ClassAssignments * MLL::ClassAssignmentsPtr
Definition at line 103 of file ClassAssignments.h.
typedef ClassificationBiasMatrix::ClassificationBiasMatrixPtr MLL::ClassificationBiasMatrixPtr
Definition at line 147 of file ClassificationBiasMatrix.h.
typedef Classifier2 * MLL::Classifier2Ptr
Definition at line 224 of file Classifier2.h.
typedef ClassIndexList::ClassIndexListPtr MLL::ClassIndexListPtr
Definition at line 528 of file MLClass.h.
typedef ClassProbList * MLL::ClassProbListPtr
Definition at line 19 of file Classifier2.h.
typedef ClassProb * MLL::ClassProbPtr
Definition at line 17 of file Classifier2.h.
typedef ClassStatisticList * MLL::ClassStatisticListPtr
Definition at line 15 of file AbundanceCorrectionMatrix.h.
typedef ClassStatistic * MLL::ClassStatisticPtr
Definition at line 13 of file AbundanceCorrectionMatrix.h.
typedef ConfusionMatrix2 * MLL::ConfusionMatrix2Ptr
Definition at line 309 of file ConfusionMatrix2.h.
typedef ConfussionMatrix2List* MLL::ConfussionMatrix2ListPtr
Definition at line 324 of file ConfusionMatrix2.h.
typedef CrossValidation * MLL::CrossValidationPtr
Definition at line 241 of file CrossValidation.h.
typedef CrossValidationThreeWay* MLL::CrossValidationThreeWayPtr
Definition at line 163 of file CrossValidationThreeWay.h.
typedef CrossValidationVoting* MLL::CrossValidationVotingPtr
Definition at line 167 of file CrossValidationVoting.h.
typedef DataBaseGpsDataList::DataBaseGpsDataListPtr MLL::DataBaseGpsDataListPtr
Definition at line 67 of file DataBaseGpsData.h.
typedef DataBaseGpsData::DataBaseGpsDataPtr MLL::DataBaseGpsDataPtr
Definition at line 52 of file DataBaseGpsData.h.
typedef DataBaseImageEntryList::DataBaseImageEntryListPtr MLL::DataBaseImageEntryListPtr
Definition at line 51 of file DataBaseImageEntry.h.
typedef DataBaseImageEntry::DataBaseImageEntryPtr MLL::DataBaseImageEntryPtr
Definition at line 36 of file DataBaseImageEntry.h.
typedef DataBaseImageGroupEntryList::DataBaseImageGroupEntryListPtr MLL::DataBaseImageGroupEntryListPtr
Definition at line 71 of file DataBaseImageGroupEntry.h.
typedef DataBaseImageGroupEntry::DataBaseImageGroupEntryPtr MLL::DataBaseImageGroupEntryPtr
Definition at line 51 of file DataBaseImageGroupEntry.h.
typedef DataBaseImageGroupList::DataBaseImageGroupListPtr MLL::DataBaseImageGroupListPtr
Definition at line 78 of file DataBaseImageGroup.h.
typedef DataBaseImageGroup::DataBaseImageGroupPtr MLL::DataBaseImageGroupPtr
Definition at line 60 of file DataBaseImageGroup.h.
typedef DataBaseImageList * MLL::DataBaseImageListPtr
Definition at line 180 of file DataBaseImage.h.
typedef DataBaseImage * MLL::DataBaseImagePtr
Definition at line 147 of file DataBaseImage.h.
typedef DataBaseImageValidatedEntryList::DataBaseImageValidatedEntryListPtr MLL::DataBaseImageValidatedEntryListPtr
Definition at line 110 of file DataBaseImageValidatedEntry.h.
typedef DataBaseImageValidatedEntry::DataBaseImageValidatedEntryPtr MLL::DataBaseImageValidatedEntryPtr
Definition at line 62 of file DataBaseImageValidatedEntry.h.
typedef DataBaseLogEntryList::DataBaseLogEntryListPtr MLL::DataBaseLogEntryListPtr
Definition at line 124 of file DataBaseLogEntry.h.
typedef DataBaseLogEntry::DataBaseLogEntryPtr MLL::DataBaseLogEntryPtr
Definition at line 104 of file DataBaseLogEntry.h.
typedef DataBase * MLL::DataBasePtr
Definition at line 1016 of file DataBase.h.
typedef DataBaseServerList * MLL::DataBaseServerListPtr
Definition at line 61 of file DataBase.h.
typedef DataBaseServer * MLL::DataBaseServerPtr
Definition at line 58 of file DataBase.h.
typedef DataBaseUpdate::DataBaseUpdatePtr MLL::DataBaseUpdatePtr
Definition at line 79 of file DataBaseUpdate.h.
typedef DuplicateImageList * MLL::DuplicateImageListPtr
Definition at line 26 of file DuplicateImages.h.
typedef DuplicateImage * MLL::DuplicateImagePtr
Definition at line 29 of file DuplicateImages.h.
typedef DuplicateImages* MLL::DuplicateImagesPtr
Definition at line 120 of file DuplicateImages.h.
typedef std::vector<double> MLL::Dvector
Definition at line 28 of file SvmWrapper.h.
typedef FeatureEncoder2 * MLL::FeatureEncoder2Ptr
Definition at line 119 of file FeatureEncoder2.h.
typedef FeatureEncoder * MLL::FeatureEncoderPtr
Definition at line 146 of file FeatureEncoder.h.
typedef FeatureFileIOC45::FeatureFileIOC45Ptr MLL::FeatureFileIOC45Ptr
Definition at line 119 of file FeatureFileIOC45.h.
typedef FeatureFileIOPices::FeatureFileIOPicesPtr MLL::FeatureFileIOPicesPtr
Definition at line 194 of file FeatureFileIOPices.h.
typedef FeatureFileIO * MLL::FeatureFileIOPtr
Definition at line 28 of file FeatureFileIO.h.
typedef FeatureNumList * MLL::FeatureNumListPtr
Definition at line 32 of file FeatureEncoder.h.
typedef FeatureVectorList * MLL::FeatureVectorListPtr
Definition at line 57 of file CrossValidationMxN.h.
typedef FeatureVector * MLL::FeatureVectorPtr
Definition at line 51 of file CrossValidationMxN.h.
typedef FeWhatToDo* MLL::FeWhatToDoPtr
Definition at line 41 of file FeatureEncoder.h.
typedef FileDescList * MLL::FileDescListPtr
Definition at line 52 of file FileDesc.h.
typedef FileDesc * MLL::FileDescPtr
Definition at line 78 of file CrossValidation.h.
typedef std::vector<float> MLL::Fvector
Definition at line 27 of file SvmWrapper.h.
typedef ImageFeaturesDataIndexed * MLL::ImageFeaturesDataIndexedPtr
Definition at line 35 of file DuplicateImages.h.
typedef ImageFeaturesList * MLL::ImageFeaturesListPtr
Definition at line 52 of file DataBase.h.
typedef ImageFeaturesNameIndexed * MLL::ImageFeaturesNameIndexedPtr
Definition at line 48 of file DuplicateImages.h.
typedef ImageFeatures * MLL::ImageFeaturesPtr
Definition at line 49 of file DataBase.h.
typedef std::vector<int32> MLL::Ivector
Definition at line 26 of file SvmWrapper.h.
typedef MLClass const MLL::MLClassConst
Definition at line 52 of file CrossValidation.h.
typedef MLClassConstList * MLL::MLClassConstListPtr
Definition at line 38 of file ClassAssignments.h.
typedef MLClassConst * MLL::MLClassConstPtr
Definition at line 37 of file BinaryClassParms.h.
typedef MLClassList * MLL::MLClassListPtr
Definition at line 32 of file ClassAssignments.h.
typedef MLClass * MLL::MLClassPtr
Definition at line 35 of file BinaryClassParms.h.
typedef ModelDual::ModelDualPtr MLL::ModelDualPtr
Definition at line 223 of file ModelDual.h.
typedef ModelKnn::ModelKnnPtr MLL::ModelKnnPtr
Definition at line 111 of file ModelKnn.h.
typedef ModelOldSVM * MLL::ModelOldSVMPtr
Definition at line 191 of file ModelOldSVM.h.
typedef ModelParamDual::ModelParamDualPtr MLL::ModelParamDualPtr
Definition at line 57 of file ModelDual.h.
typedef ModelParamKnn::ModelParamKnnPtr MLL::ModelParamKnnPtr
Definition at line 62 of file ModelParamKnn.h.
typedef ModelParamOldSVM * MLL::ModelParamOldSVMPtr
Definition at line 39 of file ModelOldSVM.h.
typedef ModelParam * MLL::ModelParamPtr
Definition at line 230 of file ModelParam.h.
typedef ModelParamSvmBase::ModelParamSvmBasePtr MLL::ModelParamSvmBasePtr
Definition at line 84 of file ModelParamSvmBase.h.
typedef ModelParamUsfCasCor* MLL::ModelParamUsfCasCorPtr
Definition at line 87 of file ModelParamUsfCasCor.h.
typedef Model::ModelPtr MLL::ModelPtr
Definition at line 425 of file Model.h.
typedef ModelSvmBase::ModelSvmBasePtr MLL::ModelSvmBasePtr
Definition at line 144 of file ModelSvmBase.h.
typedef ModelUsfCasCor::ModelUsfCasCorPtr MLL::ModelUsfCasCorPtr
Definition at line 135 of file ModelUsfCasCor.h.
typedef NormalizationParms * MLL::NormalizationParmsPtr
Definition at line 71 of file Model.h.
typedef Orderings::OrderingsPtr MLL::OrderingsPtr
Definition at line 63 of file CrossValidationMxN.h.
typedef RunLog * MLL::RunLogPtr
Definition at line 15 of file NormalizationParms.h.
typedef SipperBlob::SipperBlobPtr MLL::SipperBlobPtr
Definition at line 135 of file SipperBlob.h.
typedef SipperExtractionImageManager* MLL::SipperExtractionImageManagerPtr
Definition at line 109 of file SipperExtractionImageManager.h.
typedef SizeDistribution* MLL::SizeDistributionPtr
Definition at line 87 of file SizeDistribution.h.
typedef SVMModel* MLL::SVMModelPtr
Definition at line 599 of file SVMModel.h.
typedef SVMparam* MLL::SVMparamPtr
Definition at line 289 of file SVMparam.h.
typedef TrainingClassList* MLL::TrainingClassListPtr
Definition at line 150 of file TrainingClass.h.
typedef TrainingClass* MLL::TrainingClassPtr
Definition at line 111 of file TrainingClass.h.
typedef TrainingConfiguration2List* MLL::TrainingConfiguration2ListPtr
Definition at line 363 of file TrainingConfiguration2.h.
typedef TrainingConfiguration2 * MLL::TrainingConfiguration2Ptr
Definition at line 52 of file Classifier2.h.
typedef TrainingConfiguration2List* MLL::TrainingConfigurationList2Ptr
Definition at line 80 of file CrossValidationVoting.h.
typedef TrainingProcess2::TrainingProcess2Ptr MLL::TrainingProcess2Ptr
Definition at line 58 of file Classifier2.h.
typedef UsfCasCor * MLL::UsfCasCorPtr
Definition at line 600 of file UsfCasCor.h.
typedef SipperBlob::VectorSipperBlob MLL::VectorSipperBlob
Definition at line 136 of file SipperBlob.h.
typedef struct svm_node * MLL::XSpacePtr
Definition at line 37 of file FeatureEncoder.h.
Enumeration Type Documentation
enum MLL::AttributeType
Enumerator
IgnoreAttribute
NumericAttribute
NominalAttribute
OrdinalAttribute
SymbolicAttribute
Same as NominalAttribute, except the names file does not list all possible values.
They have to be determined from the data file.
NULLAttribute
Definition at line 32 of file Attribute.h.
enum MLL::FeWhatToDo
Enumerator
FeAsIs
FeBinary
FeScale
Definition at line 40 of file FeatureEncoder.h.
enum MLL::Learn_Type
Enumerator
NORMAL
BAGGING
BOOSTING
SUBSPACE
SAMPLESV
Definition at line 23 of file SvmWrapper.h.
enum MLL::SVM_CompressionMethod
Enumerator
BRNull
BRnoCompression
BRcompressionPost
BRcompressionPre
BRunBalancedVariance
BRunBalancedSpecified
Definition at line 37 of file SVMparam.h.
enum MLL::SVM_EncodingMethod
Enumerator
NoEncoding
BinaryEncoding
ScaledEncoding
Encoding_NULL
Definition at line 35 of file SVMparam.h.
enum MLL::SVM_KernalType
Enumerator
KT_Linear
KT_Polynomial
KT_RBF
KT_NULL
Definition at line 46 of file SVMparam.h.
enum MLL::SVM_MachineType
Enumerator
MachineType_NULL
OneVsOne
OneVsAll
BinaryCombos
BoostSVM
Definition at line 25 of file SVMparam.h.
enum MLL::SVM_SelectionMethod
Enumerator
SelectionMethod_NULL
SelectByVoting
SelectByProbability
Definition at line 33 of file SVMparam.h.
Function Documentation
KKStr MLL::AttributeTypeToStr (AttributeType type)
Definition at line 340 of file Attribute.cpp.
References NULLAttribute.
Referenced by MLL::FeatureVectorList::FeatureTypeStr(), MLL::Attribute::TypeStr(), and MLL::FileDesc::TypeStr().
void MLL::CompareTwoSetsOfGroups (vector< vector< KKStr > > & groups1, vector< vector< KKStr > > & groups2, std::ostream & r)
SVM_CompressionMethod MLL::CompressionMethodFromStr (const KKStr & compressionMethodStr)
Referenced by MLL::SVMparam::ParseCmdLineParameter().
KKStr MLL::CompressionMethodStr (SVM_CompressionMethod compressionMethod)
Definition at line 1111 of file SVMparam.cpp.
References BRcompressionPost, BRcompressionPre, BRnoCompression, BRNull, BRunBalancedSpecified, and BRunBalancedVariance.
Referenced by MLL::SVMparam::ToString().
void MLL::EncodeProblem (const struct svm_paramater & param, struct svm_problem & prob_in, struct svm_problem & prob_out)
SVM_EncodingMethod MLL::EncodingMethodFromStr (const KKStr & encodingMethodStr)
Referenced by MLL::SVMparam::ParseCmdLineParameter().
KKStr MLL::EncodingMethodToStr (SVM_EncodingMethod encodingMethod)
Definition at line 954 of file SVMparam.cpp.
References BinaryEncoding, and ScaledEncoding.
Referenced by MLL::SVMparam::ToString().
SVM_KernalType MLL::KernalTypeFromStr (const KKStr & kernalTypeStr)
KKStr MLL::KernalTypeToStr (SVM_KernalType kernalType)
Definition at line 986 of file SVMparam.cpp.
References KT_Linear, KT_Polynomial, and KT_RBF.
SVM_MachineType MLL::MachineTypeFromStr (const KKStr & machineTypeStr)
Referenced by MLL::SVMparam::ParseCmdLineParameter().
KKStr MLL::MachineTypeToStr (SVM_MachineType machineType)
Definition at line 1034 of file SVMparam.cpp.
References BinaryCombos, BoostSVM, OneVsAll, and OneVsOne.
Referenced by MLL::ModelOldSVM::Description(), MLL::SVMparam::ToString(), and MLL::SVMModel::Write().
ostream& MLL::operator<< (ostream & o, const CompressionStats & stats)
Definition at line 508 of file BitReduction.cpp.
References MLL::CompressionStats::compression_ratio, MLL::CompressionStats::num_images_after, and MLL::CompressionStats::num_images_before.
ostream & MLL::operator<< (std::ostream & os, const MLClassConstList & classList)
Definition at line 790 of file MLClassConstList.cpp.
References MLL::MLClassConstList::ToString().
std::ostream & MLL::operator<< (std::ostream & os, const FeatureNumList & features)
Definition at line 827 of file FeatureNumList.cpp.
References MLL::FeatureNumList::ToString().
KKStr& MLL::operator<< (KKStr & str, const MLClassConstList & classList)
KKStr& MLL::operator<< (KKStr & left, TrainingConfiguration2::ModelTypes modelingMethod)
ostream & MLL::operator<< (std::ostream & os, TrainingConfiguration2::ModelTypes modelingMethod)
Definition at line 1912 of file TrainingConfiguration2.cpp.
References MLL::TrainingConfiguration2::ModelTypeToStr().
ostream & MLL::operator<< (std::ostream & os, const MLClassList & classList)
Definition at line 1287 of file MLClass.cpp.
References MLL::MLClassList::ToString().
KKStr& MLL::operator<< (KKStr & str, const MLClassList & classList)
bool MLL::PairCompareOperator (ProbNamePair l, ProbNamePair r)
Definition at line 2204 of file SVMModel.cpp.
References MLL::ProbNamePair::probability.
Referenced by MLL::SVMModel::FindWorstSupportVectors(), and MLL::SVMModel::FindWorstSupportVectors2().
SVM_SelectionMethod MLL::SelectionMethodFromStr (const KKStr & selectionMethodStr)
Referenced by MLL::SVMparam::ParseCmdLineParameter().
KKStr MLL::SelectionMethodToStr (SVM_SelectionMethod selectionMethod)
Definition at line 1077 of file SVMparam.cpp.
References SelectByProbability, and SelectByVoting.
Referenced by MLL::ModelOldSVM::Description(), and MLL::SVMparam::ToString().
void MLL::SvmDestroyModel (struct svm_model ** subModel)
Definition at line 589 of file SvmWrapper.cpp.
References SVM233::svm_destroy_model().
Referenced by MLL::SVMModel::~SVMModel().
struct svm_model ** MLL::SvmLoadModel (const char * fileName)
Definition at line 554 of file SvmWrapper.cpp.
References SVM233::svm_load_model().
struct svm_model** MLL::SvmLoadModel (istream & f, RunLog & log)
void MLL::SvmPredictClass (SVMparam & svmParam, struct svm_model ** subModel, const struct svm_node * unknownClassFeatureData, int32 * votes, double * probabilities, int32 knownClass, int32 & predClass1, int32 & predClass2, int32 & predClass1Votes, int32 & predClass2Votes, double & predClass1Prob, double & predClass2Prob, double & probOfKnownClass, double & compact, Ivector & winners, double ** crossClassProbTable, double & breakTie)
Referenced by MLL::SVMModel::ProbabilitiesByClass().
int32 MLL::SvmPredictTwoClass (const struct svm_parameter & param, svm_model ** submodel, const svm_node * unKnownData, int32 desired, double & dist, double & probability, int32 excludeSupportVectorIDX)
void MLL::SvmSaveModel (ostream & o, struct svm_model ** model)
Referenced by MLL::SVMModel::Write().
void MLL::SvmSaveModel (struct svm_model ** subModel, const char * fileName, bool & successfull)
Definition at line 530 of file SvmWrapper.cpp.
References SVM233::svm_save_model(), and x.
struct svm_model ** MLL::SvmTrainModel (const struct svm_parameter & param, struct svm_problem & subprob)
Definition at line 380 of file SvmWrapper.cpp.
References BAGGING, BOOSTING, SVM233::svm_parameter::boosting, SVM233::svm_parameter::dimSelect, NORMAL, SVM233::svm_parameter::numSVM, SVM233::svm_parameter::sample, SAMPLESV, SVM233::svm_parameter::sampleSV, SUBSPACE, and SVM233::svm_train().
Variable Documentation
const char* MLL::FeatureDecriptions[]
MLClassList MLL::globalClassList
Referenced by MLL::MLClass::ResetAllParentsToAllClasses().