Pices: ImageExtractionManager Namespace Reference
ImageExtractionManager Namespace Reference
Classes
class DataBaseUpdateThread
class ExtractedImage
Represets particle that was extracted by 'LogicalFrame' with its related data.
class ExtractedImageQueue
class ExtractionManager
Manages the extraction of images from a single Sipper File utilizing multiple threads.
class ExtractionManagerStats
class ExtractionParms
class FrameExtractorThread
class FrameProcessorThread
class ImageExtractionThread
The base class to be used by all Extraction Manager threads.
class LogicalFrame
The Image extracion procedure will contain several threads perform various functions.
class LogicalFrameBlob
class LogicalFrameQueue
class SipperImage
class SipperThread
Typedefs
typedef DataBaseUpdateThread * DataBaseUpdateThreadPtr
typedef KKQueue< ExtractedImage > ExtractedImageList
typedef ExtractedImageList * ExtractedImageListPtr
typedef ExtractedImage * ExtractedImagePtr
typedef ExtractedImageQueue * ExtractedImageQueuePtr
typedef ExtractionManager * ExtractionManagerPtr
typedef ExtractionManagerStats * ExtractionManagerStatsPtr
typedef ExtractionParms * ExtractionParmsPtr
typedef FrameExtractorThread * FrameExtractorThreadPtr
typedef KKQueue
< FrameProcessorThread > FrameProcessorThreadList
typedef FrameProcessorThreadList * FrameProcessorThreadListPtr
typedef FrameProcessorThread * FrameProcessorThreadPtr
typedef KKQueue
< ImageExtractionThread > ImageExtractionThreadList
typedef ImageExtractionThreadList * ImageExtractionThreadListPtr
typedef ImageExtractionThread * ImageExtractionThreadPtr
typedef
LogicalFrameBlob::LogicalFrameBlobPtr LogicalFrameBlobPtr
typedef LogicalFrame * LogicalFramePtr
typedef LogicalFrameQueue * LogicalFrameQueuePtr
typedef SipperImage * SipperImagePtr
typedef vector< ExtractedImagePtr > VectorExtractedImage
typedef VectorExtractedImage * VectorExtractedImagePtr
typedef
LogicalFrameBlob::VectorLogicalFrameBlob VectorLogicalFrameBlob
typedef vector< SipperImagePtr > VectorSipperImage
typedef VectorSipperImage * VectorSipperImagePtr
Enumerations
enum ThreadStatus {
tsNotStarted, tsStarting, tsRunning, tsStopping,
tsStopped, tsNotStarted, tsStarting, tsRunning,
tsStopping, tsStoped
}
enum ThreadStatus {
tsNotStarted, tsStarting, tsRunning, tsStopping,
tsStopped, tsNotStarted, tsStarting, tsRunning,
tsStopping, tsStoped
}
The Image extracion procedure will contain several threads perform various functions.
enum ThreadTypes { ttFrameExtractor, ttFrameProcessor, ttDataBAseUpdater }
Functions
unsigned int ThreadStartCallBack (void *param)
Typedef Documentation
typedef DataBaseUpdateThread * ImageExtractionManager::DataBaseUpdateThreadPtr
Definition at line 78 of file DataBaseUpdateThread.h.
typedef KKQueue< ExtractedImage > ImageExtractionManager::ExtractedImageList
Definition at line 91 of file ExtractedImage.h.
typedef ExtractedImageList * ImageExtractionManager::ExtractedImageListPtr
Definition at line 92 of file ExtractedImage.h.
typedef ExtractedImage * ImageExtractionManager::ExtractedImagePtr
Definition at line 84 of file ExtractedImage.h.
typedef ExtractedImageQueue * ImageExtractionManager::ExtractedImageQueuePtr
Definition at line 118 of file ExtractedImage.h.
typedef ExtractionManager * ImageExtractionManager::ExtractionManagerPtr
Definition at line 160 of file ExtractionManager.h.
typedef ExtractionManagerStats* ImageExtractionManager::ExtractionManagerStatsPtr
Definition at line 51 of file PreDefinedClasses.h.
typedef ExtractionParms * ImageExtractionManager::ExtractionParmsPtr
Definition at line 179 of file ExtractionParms.h.
typedef FrameExtractorThread * ImageExtractionManager::FrameExtractorThreadPtr
Definition at line 124 of file FrameExtractorThread.h.
typedef KKQueue< FrameProcessorThread > ImageExtractionManager::FrameProcessorThreadList
Definition at line 79 of file FrameProcessorThread.h.
typedef FrameProcessorThreadList * ImageExtractionManager::FrameProcessorThreadListPtr
Definition at line 80 of file FrameProcessorThread.h.
typedef FrameProcessorThread * ImageExtractionManager::FrameProcessorThreadPtr
Definition at line 77 of file FrameProcessorThread.h.
typedef KKQueue< ImageExtractionThread > ImageExtractionManager::ImageExtractionThreadList
Definition at line 105 of file ImageExtractionThread.h.
typedef ImageExtractionThreadList * ImageExtractionManager::ImageExtractionThreadListPtr
Definition at line 106 of file ImageExtractionThread.h.
typedef ImageExtractionThread * ImageExtractionManager::ImageExtractionThreadPtr
Definition at line 104 of file ImageExtractionThread.h.
typedef LogicalFrameBlob * ImageExtractionManager::LogicalFrameBlobPtr
Definition at line 93 of file LogicalFrameBlob.h.
typedef LogicalFrame * ImageExtractionManager::LogicalFramePtr
Definition at line 141 of file LogicalFrame.h.
typedef LogicalFrameQueue* ImageExtractionManager::LogicalFrameQueuePtr
Definition at line 13 of file PreDefinedClasses.h.
typedef SipperImage::SipperImagePtr ImageExtractionManager::SipperImagePtr
Definition at line 57 of file PreDefinedClasses.h.
typedef vector< ExtractedImagePtr > ImageExtractionManager::VectorExtractedImage
Definition at line 86 of file ExtractedImage.h.
typedef VectorExtractedImage * ImageExtractionManager::VectorExtractedImagePtr
Definition at line 88 of file ExtractedImage.h.
typedef vector< LogicalFrameBlobPtr > ImageExtractionManager::VectorLogicalFrameBlob
Definition at line 94 of file LogicalFrameBlob.h.
typedef vector< SipperImage * > ImageExtractionManager::VectorSipperImage
Definition at line 59 of file PreDefinedClasses.h.
typedef VectorSipperImage * ImageExtractionManager::VectorSipperImagePtr
Definition at line 60 of file PreDefinedClasses.h.
Enumeration Type Documentation
enum ImageExtractionManager::ThreadStatus
Enumerator
tsNotStarted
tsStarting
tsRunning
tsStopping
tsStopped
tsNotStarted
tsStarting
tsRunning
tsStopping
tsStoped
Definition at line 12 of file ImageExtractionThread.h.
enum ImageExtractionManager::ThreadStatus
The Image extracion procedure will contain several threads perform various functions.
This will be the base class for each one of the different types of processing that Sipper Image processing will be done. Soem of threads will Extract logical frames from Sipper files,
Enumerator
tsNotStarted
tsStarting
tsRunning
tsStopping
tsStopped
tsNotStarted
tsStarting
tsRunning
tsStopping
tsStoped
Definition at line 25 of file SipperThread.h.
enum ImageExtractionManager::ThreadTypes
Enumerator
ttFrameExtractor
ttFrameProcessor
ttDataBAseUpdater
Definition at line 20 of file ImageExtractionThread.h.
Function Documentation
unsigned int ImageExtractionManager::ThreadStartCallBack (void * param)
Definition at line 179 of file KKThread.cpp.
References KKU::KKThread::Run(), ImageExtractionManager::ImageExtractionThread::Run(), KKU::KKThread::Status(), ImageExtractionManager::ImageExtractionThread::Status(), tsStarting, KKU::KKThread::tsStarting, tsStopped, and KKU::KKThread::tsStopped.
Referenced by ImageExtractionManager::ImageExtractionThread::Start(), and KKU::KKThread::Start().