Pices: SVM289_MFS Namespace Reference
SVM289_MFS Namespace Reference
This is a vesion 2.89 of "Chih-Chung Chang" and "Chih-Jen Lin" libSVM (Support Vector Machine) that selects different features per pair of classes.
Classes
class Cache
struct decision_function
class Kernel
class ONE_CLASS_Q
class QMatrix
class Solver
class Solver_NU
class SVC_Q
struct svm_model
struct svm_parameter
struct svm_problem
class SVR_Q
Typedefs
typedef float Qfloat
typedef signed char schar
Enumerations
enum Kernel_Type {
Kernel_NULL, LINEAR, POLY, RBF,
SIGMOID, PRECOMPUTED
}
enum SVM_Type {
SVM_NULL, C_SVC, NU_SVC, ONE_CLASS,
EPSILON_SVR, NU_SVR
}
Functions
template<class S , class T >
void clone (T *&dst, S *src, int32 n)
template<class T >
T * GrowAllocation (T *src, int32 origSize, int32 newSize)
Kernel_Type Kernel_Type_FromStr (KKStr s)
KKStr Kernel_Type_ToStr (Kernel_Type kernelType)
int32 Max (int32 x, int32 y)
long Max (long x, long y)
double Max (double x, double y)
float Max (float x, float y)
uint32 Max (uint32 x, uint32 y)
double Min (double x, double y)
int32 Min (int32 x, int32 y)
long Min (long x, long y)
float Min (float x, float y)
uint32 Min (uint32 x, uint32 y)
void multiclass_probability (int32 k, double **r, double *p)
double powi (double base, int32 times)
double powi (double base, int32 times)
void readline (FILE *input, char *&buff, int32 &buffLen, bool &eof)
double sigmoid_predict (double decision_value, double A, double B)
void sigmoid_train (int32 l, const double *dec_values, const double *labels, double &A, double &B)
void solve_c_svc (const svm_problem *prob, const svm_parameter *param, double *alpha, Solver::SolutionInfo *si, double Cp, double Cn, RunLog &_log)
void solve_epsilon_svr (const svm_problem *prob, const svm_parameter *param, double *alpha, Solver::SolutionInfo *si, RunLog &_log)
void solve_nu_svc (const svm_problem *prob, const svm_parameter *param, double *alpha, Solver::SolutionInfo *si, RunLog &_log)
void solve_one_class (const svm_problem *prob, const svm_parameter *param, double *alpha, Solver::SolutionInfo *si, RunLog &_log)
const char * svm_check_parameter (const struct svm_problem *prob, const struct svm_parameter *param)
int32 svm_check_probability_model (const struct svm_model *model)
void svm_cross_validation (const svm_problem &prob, const svm_parameter &param, int32 nr_fold, double *target, RunLog &log)
void svm_destroy_model (struct svm_model *&model)
void svm_destroy_param (struct svm_parameter *&param)
void svm_get_labels (const struct svm_model *model, int32 *label)
int32 svm_get_nr_class (const struct svm_model *model)
int32 svm_get_svm_type (const struct svm_model *model)
double svm_get_svr_probability (const struct svm_model *model)
svm_model * svm_load_model (const char *model_file_name)
svm_model * svm_load_model_XML (istream &i, FileDescPtr fileDesc, RunLog &log)
void svm_load_model_XML_SupportVectorSection (istream &in, FileDescPtr fileDesc, svm_model &model, bool &valid, RunLog &log)
double svm_predict (const struct svm_model *model, const FeatureVector &x)
double svm_predict_probability (svm_model *model, const FeatureVector &x, double *prob_estimates, int32 *votes)
void svm_predict_values (const svm_model *model, const FeatureVector &x, double *dec_values)
int32 svm_save_model (const char *model_file_name, const struct svm_model *model)
void svm_save_model_XML (ostream &o, const svm_model &model)
svm_model * svm_train (const svm_problem &prob, const svm_parameter &param, RunLog &log)
decision_function svm_train_one (const svm_problem &prob, const svm_parameter &param, double Cp, double Cn, RunLog &_log)
SVM_Type SVM_Type_FromStr (KKStr s)
KKStr SVM_Type_ToStr (SVM_Type svmType)
template<class T >
void swap (T &x, T &y)
Variables
int32 libsvm_version
void(* svm_print_string)(const char *) = &print_string_stdout
Detailed Description
This is a vesion 2.89 of "Chih-Chung Chang" and "Chih-Jen Lin" libSVM (Support Vector Machine) that selects different features per pair of classes.
Downloaded from "http://www.csie.ntu.edu.tw/~cjlin/libsvm/"
For each pair of classes a 'FeatureNumList" instance specifies which features are to be used during kernal computations.
Typedef Documentation
typedef float SVM289_MFS::Qfloat
Definition at line 293 of file svm2.h.
typedef signed char SVM289_MFS::schar
Definition at line 295 of file svm2.h.
Enumeration Type Documentation
enum SVM289_MFS::Kernel_Type
Enumerator
Kernel_NULL
LINEAR
POLY
RBF
SIGMOID
PRECOMPUTED
Definition at line 69 of file svm2.h.
enum SVM289_MFS::SVM_Type
Enumerator
SVM_NULL
C_SVC
NU_SVC
ONE_CLASS
EPSILON_SVR
NU_SVR
Definition at line 68 of file svm2.h.
Function Documentation
template<class S , class T > void SVM289_MFS::clone (T *& dst, S * src, int32 n) inline
Definition at line 298 of file svm2.h.
Referenced by SVM289_MFS::Solver::Solve(), SVM289_MFS::SVC_Q::SVC_Q(), and SVM289_MFS::svm_problem::svm_problem().
template<class T > T* SVM289_MFS::GrowAllocation (T * src, int32 origSize, int32 newSize) inline
Definition at line 90 of file svm2.cpp.
Referenced by readline(), and svm_check_parameter().
Kernel_Type SVM289_MFS::Kernel_Type_FromStr (KKStr s)
Referenced by svm_load_model().
KKStr SVM289_MFS::Kernel_Type_ToStr (Kernel_Type kernelType)
Definition at line 626 of file svm2.cpp.
References LINEAR, POLY, PRECOMPUTED, RBF, and SIGMOID.
Referenced by SVM289_MFS::svm_parameter::ToTabDelStr().
int32 SVM289_MFS::Max (int32 x, int32 y)
Definition at line 110 of file svm2.cpp.
Referenced by ImageExtractionManager::SipperImage::AddBlob(), SVM289_MFS::Cache::Cache(), SVM289_MFS::Solver::calculate_rho(), MLL::CrossValidationThreeWay::CreateDistanceReport(), MLL::CrossValidationThreeWay::CreateProbabilityReport(), PicesInterface::PicesMethods::DateTimeKKUtoSystem(), SipperHardware::SipperBuff::DetermineCropSettings(), ImageExtractionManager::LogicalFrameBlob::DialateBlob(), MLL::SipperBlob::DialateBlob(), MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::DataBase::FeatureDataRecLoad(), MLL::FeatureFileIOUCI::GetFileDesc(), MLL::DataBase::ImageFullSizeFind(), MLL::DataBase::ImageGroupEntriesInsert(), MLL::DataBase::ImageInsert(), MLL::DataBase::ImageUpdate(), multiclass_probability(), MLL::TrainingConfiguration2::NumHierarchialLevels(), MLL::MLClassConstList::NumHierarchialLevels(), MLL::MLClassList::NumHierarchialLevels(), KKU::osGetParentDirectoryOfDirPath(), KKU::osGetParentDirPath(), KKU::osGetRootName(), KKU::osGetRootNameOfDirectory(), KKU::osGetRootNameWithExtension(), KKU::osLocateLastSlashChar(), and ImageExtractionManager::SipperImage::SipperImage().
long SVM289_MFS::Max (long x, long y)
Definition at line 111 of file svm2.cpp.
double SVM289_MFS::Max (double x, double y)
Definition at line 112 of file svm2.cpp.
float SVM289_MFS::Max (float x, float y)
Definition at line 113 of file svm2.cpp.
uint32 SVM289_MFS::Max (uint32 x, uint32 y)
Definition at line 114 of file svm2.cpp.
double SVM289_MFS::Min (double x, double y)
Definition at line 104 of file svm2.cpp.
Referenced by SVM289_MFS::Solver::calculate_rho(), SVM289_MFS::Solver::Solve(), solve_nu_svc(), solve_nu_svr(), and svm_check_parameter().
int32 SVM289_MFS::Min (int32 x, int32 y)
Definition at line 105 of file svm2.cpp.
long SVM289_MFS::Min (long x, long y)
Definition at line 106 of file svm2.cpp.
float SVM289_MFS::Min (float x, float y)
Definition at line 107 of file svm2.cpp.
uint32 SVM289_MFS::Min (uint32 x, uint32 y)
Definition at line 108 of file svm2.cpp.
void SVM289_MFS::multiclass_probability (int32 k, double ** r, double * p)
Parameters
k Number of Classes.
r Pairwise Probabilites.
p Class Probability
Definition at line 3069 of file svm2.cpp.
References info(), and Max().
double SVM289_MFS::powi (double base, int32 times) inline
Definition at line 117 of file svm2.cpp.
Referenced by SVM289_MFS::Kernel::k_function().
double SVM289_MFS::powi (double base, int32 times) inline
void SVM289_MFS::readline (FILE * input, char *& buff, int32 & buffLen, bool & eof)
Definition at line 5289 of file svm2.cpp.
References GrowAllocation().
Referenced by svm_load_model().
double SVM289_MFS::sigmoid_predict (double decision_value, double A, double B)
Definition at line 3054 of file svm2.cpp.
void SVM289_MFS::sigmoid_train (int32 l, const double * dec_values, const double * labels, double & A, double & B)
Definition at line 2919 of file svm2.cpp.
References info().
Referenced by svm_binary_svc_probability().
void SVM289_MFS::solve_c_svc (const svm_problem * prob, const svm_parameter * param, double * alpha, Solver::SolutionInfo * si, double Cp, double Cn, RunLog & _log)
Definition at line 2471 of file svm2.cpp.
References SVM289_MFS::svm_parameter::eps, SVM289_MFS::svm_problem::l, SVM289_MFS::svm_parameter::shrinking, SVM289_MFS::Solver::Solve(), and SVM289_MFS::svm_problem::y.
Referenced by svm_train_one().
void SVM289_MFS::solve_epsilon_svr (const svm_problem * prob, const svm_parameter * param, double * alpha, Solver::SolutionInfo * si, RunLog & _log)
Definition at line 2670 of file svm2.cpp.
References SVM289_MFS::svm_parameter::C, SVM289_MFS::svm_parameter::eps, info(), SVM289_MFS::svm_problem::l, SVM289_MFS::svm_parameter::p, SVM289_MFS::svm_parameter::shrinking, SVM289_MFS::Solver::Solve(), and SVM289_MFS::svm_problem::y.
Referenced by svm_train_one().
void SVM289_MFS::solve_nu_svc (const svm_problem * prob, const svm_parameter * param, double * alpha, Solver::SolutionInfo * si, RunLog & _log)
Definition at line 2533 of file svm2.cpp.
References SVM289_MFS::svm_parameter::eps, info(), SVM289_MFS::svm_problem::l, Min(), SVM289_MFS::svm_parameter::nu, SVM289_MFS::Solver::SolutionInfo::obj, SVM289_MFS::Solver::SolutionInfo::r, SVM289_MFS::Solver::SolutionInfo::rho, SVM289_MFS::svm_parameter::shrinking, SVM289_MFS::Solver_NU::Solve(), SVM289_MFS::Solver::SolutionInfo::upper_bound_n, SVM289_MFS::Solver::SolutionInfo::upper_bound_p, and SVM289_MFS::svm_problem::y.
Referenced by svm_train_one().
void SVM289_MFS::solve_one_class (const svm_problem * prob, const svm_parameter * param, double * alpha, Solver::SolutionInfo * si, RunLog & _log)
Definition at line 2615 of file svm2.cpp.
References SVM289_MFS::svm_parameter::eps, SVM289_MFS::svm_problem::l, SVM289_MFS::svm_parameter::nu, SVM289_MFS::svm_parameter::shrinking, and SVM289_MFS::Solver::Solve().
Referenced by svm_train_one().
const char* SVM289_MFS::svm_check_parameter (const struct svm_problem * prob, const struct svm_parameter * param)
int32 SVM289_MFS::svm_check_probability_model (const struct svm_model * model)
void SVM289_MFS::svm_cross_validation (const svm_problem & prob, const svm_parameter & param, int32 nr_fold, double * target, RunLog & log)
Definition at line 3718 of file svm2.cpp.
References C_SVC, index(), SVM289_MFS::svm_problem::l, NU_SVC, SVM289_MFS::svm_parameter::probability, SVM289_MFS::svm_problem::SelFeatures(), svm_destroy_model(), svm_get_nr_class(), svm_group_classes(), svm_predict(), svm_predict_probability(), svm_train(), SVM289_MFS::svm_parameter::svm_type, swap(), SVM289_MFS::svm_problem::x, and SVM289_MFS::svm_problem::y.
Referenced by svm_svr_probability().
void SVM289_MFS::svm_destroy_model (struct svm_model *& model)
Definition at line 5539 of file svm2.cpp.
References SVM289_MFS::svm_model::SV, and SVM289_MFS::svm_model::weOwnSupportVectors.
Referenced by svm_cross_validation().
void SVM289_MFS::svm_destroy_param (struct svm_parameter *& param)
Definition at line 5555 of file svm2.cpp.
void SVM289_MFS::svm_get_labels (const struct svm_model * model, int32 * label)
int32 SVM289_MFS::svm_get_nr_class (const struct svm_model * model)
Referenced by svm_cross_validation().
int32 SVM289_MFS::svm_get_svm_type (const struct svm_model * model)
double SVM289_MFS::svm_get_svr_probability (const struct svm_model * model)
svm_model* SVM289_MFS::svm_load_model (const char * model_file_name)
svm_model* SVM289_MFS::svm_load_model_XML (istream & i, FileDescPtr fileDesc, RunLog & log)
Referenced by MLL::ModelSvmBase::ReadSpecificImplementationXML().
void SVM289_MFS::svm_load_model_XML_SupportVectorSection (istream & in, FileDescPtr fileDesc, svm_model & model, bool & valid, RunLog & log)
Definition at line 4353 of file svm2.cpp.
References KKU::endl(), KKU::KKStr::EqualIgnoreCase(), KKU::KKStr::ExtractToken2(), MLL::FeatureVector::FeatureData(), MLL::FeatureVector::ImageFileName(), SVM289_MFS::svm_parameter::kernel_type, SVM289_MFS::svm_model::l, KKU::KKStr::Len(), KKU::RunLog::Level(), MLL::FeatureVector::MLClass(), SVM289_MFS::svm_model::nr_class, MLL::FileDesc::NumOfFields(), KKU::osReadNextToken(), SVM289_MFS::svm_model::param, PRECOMPUTED, MLL::FeatureVectorList::PushOnBack(), KKU::KKStr::SubStrPart(), SVM289_MFS::svm_model::SV, SVM289_MFS::svm_model::sv_coef, KKU::KKStr::ToDouble(), KKU::KKStr::ToInt(), SVM289_MFS::svm_model::weOwnSupportVectors, and x.
double SVM289_MFS::svm_predict (const struct svm_model * model, const FeatureVector & x)
Referenced by MLL::ModelSvmBase::Predict(), and svm_cross_validation().
double SVM289_MFS::svm_predict_probability (svm_model * model, const FeatureVector & x, double * prob_estimates, int32 * votes)
Referenced by MLL::ModelSvmBase::ProbabilitiesByClass(), and svm_cross_validation().
void SVM289_MFS::svm_predict_values (const svm_model * model, const FeatureVector & x, double * dec_values)
Definition at line 3913 of file svm2.cpp.
References EPSILON_SVR, SVM289_MFS::Kernel::k_function(), SVM289_MFS::svm_model::l, SVM289_MFS::svm_model::nr_class, SVM289_MFS::svm_model::nSV, NU_SVR, ONE_CLASS, SVM289_MFS::svm_model::param, SVM289_MFS::svm_model::rho, SVM289_MFS::svm_model::selFeatures, SVM289_MFS::svm_model::SV, SVM289_MFS::svm_model::sv_coef, and SVM289_MFS::svm_parameter::svm_type.
Referenced by svm_binary_svc_probability().
int32 SVM289_MFS::svm_save_model (const char * model_file_name, const struct svm_model * model)
void SVM289_MFS::svm_save_model_XML (ostream & o, const svm_model & model)
Referenced by MLL::ModelSvmBase::WriteSpecificImplementationXML().
svm_model* SVM289_MFS::svm_train (const svm_problem & prob, const svm_parameter & param, RunLog & log)
Referenced by svm_binary_svc_probability(), svm_cross_validation(), and MLL::ModelSvmBase::TrainModel().
decision_function SVM289_MFS::svm_train_one (const svm_problem & prob, const svm_parameter & param, double Cp, double Cn, RunLog & _log)
Definition at line 2801 of file svm2.cpp.
References SVM289_MFS::decision_function::alpha, C_SVC, KKU::endl(), EPSILON_SVR, SVM289_MFS::Kernel::k_function(), SVM289_MFS::svm_problem::l, KKU::RunLog::Level(), NU_SVC, NU_SVR, ONE_CLASS, SVM289_MFS::Solver::SolutionInfo::rho, SVM289_MFS::decision_function::rho, SVM289_MFS::svm_problem::SelFeatures(), solve_c_svc(), solve_epsilon_svr(), solve_nu_svc(), solve_nu_svr(), solve_one_class(), SVM289_MFS::svm_parameter::svm_type, SVM289_MFS::Solver::SolutionInfo::upper_bound_n, SVM289_MFS::Solver::SolutionInfo::upper_bound_p, SVM289_MFS::svm_problem::x, and SVM289_MFS::svm_problem::y.
SVM_Type SVM289_MFS::SVM_Type_FromStr (KKStr s)
Referenced by svm_load_model().
KKStr SVM289_MFS::SVM_Type_ToStr (SVM_Type svmType)
Definition at line 586 of file svm2.cpp.
References C_SVC, EPSILON_SVR, NU_SVC, NU_SVR, ONE_CLASS, and SVM_NULL.
Referenced by SVM289_MFS::svm_parameter::ToTabDelStr().
template<class T > void SVM289_MFS::swap (T & x, T & y) inline
Definition at line 289 of file svm2.h.
References x.
Referenced by SVM289_MFS::Cache::get_data(), svm_binary_svc_probability(), svm_cross_validation(), SVM289_MFS::Cache::swap_index(), SVM289_MFS::Kernel::swap_index(), SVM289_MFS::Solver::swap_index(), SVM289_MFS::SVC_Q::swap_index(), SVM289_MFS::ONE_CLASS_Q::swap_index(), and SVM289_MFS::SVR_Q::swap_index().
Variable Documentation
int32 SVM289_MFS::libsvm_version
void(* SVM289_MFS::svm_print_string)(const char *) = &print_string_stdout
Definition at line 650 of file svm2.cpp.