Pices: KKB::Chart::PlotPoint Class Reference
KKB::Chart::PlotPoint Class Reference
Public Member Functions
PlotPoint (double _xVal, double _yVal)
PlotPoint (kkint32 _xVal, kkint32 _yVal)
double XVal () const
double YVal () const
Detailed Description
Definition at line 29 of file Chart.cpp.
Constructor & Destructor Documentation
KKB::Chart::PlotPoint::PlotPoint (double _xVal, double _yVal) inline
Definition at line 32 of file Chart.cpp.
KKB::Chart::PlotPoint::PlotPoint (kkint32 _xVal, kkint32 _yVal) inline
Definition at line 40 of file Chart.cpp.
Member Function Documentation
double KKB::Chart::PlotPoint::XVal () const inline
Definition at line 48 of file Chart.cpp.
Referenced by KKB::Chart::DefineAXLabel(), and KKB::Chart::Save().
double KKB::Chart::PlotPoint::YVal () const inline
Definition at line 49 of file Chart.cpp.
Referenced by KKB::Chart::DefineAXLabel(), and KKB::Chart::Save().
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Chart.cpp