Pices: FeatureSelectionApp::BinaryJob Class Reference
FeatureSelectionApp::BinaryJob Class Reference
#include <BinaryJob.h>
Public Types
typedef BinaryJob * BinaryJobPtr
Public Member Functions
BinaryJob (const BinaryJob &j)
BinaryJob (ProcessorPtr _processor, int _parentId, FeatureNumList _features, int _chgFeatureNum)
BinaryJob (ProcessorPtr _processor, int _parentId, FeatureNumList _features, int _chgFeatureNum, kkint32 _numOfRounds, double _cParm, double _gammaParm, float _aParm)
BinaryJob (ProcessorPtr _processor, KKStrParser statusLine)
BinaryJob (RunLog &_log, FileDescPtr _fileDesc)
virtual ~BinaryJob ()
float Accuracy () const
void Accuracy (float _accuracy)
float AccuracyNorm () const
void AccuracyNorm (float _accuracyNorm)
float AParm () const
void AParm (float _aParm)
float AParm ()
float AvgPredProb () const
void AvgPredProb (float _avgPredProb)
BinaryJobPtr CheckTwoListsForExitingJob (FeatureNumList &featuresToLookFor, BinaryJobListPtr exitingJobs1, BinaryJobListPtr exitingJobs2)
int ChgFeatureNum () const
double CParm () const
void CParm (double _cParm)
double CParm ()
float DecisiveProbMean () const
void DecisiveProbMean (float _decisiveProbMean)
float DecisiveProbStdDev () const
void DecisiveProbStdDev (float _decisiveProbStdDev)
float DeltaProbAccuracy () const
virtual void EvaluateNode ()
BinaryJobListPtr ExpandBestCaseBackward (BinaryJobListPtr exitingJobs1, BinaryJobListPtr exitingJobs2)
BinaryJobListPtr ExpandBestCaseForward (BinaryJobListPtr exitingJobs1, BinaryJobListPtr exitingJobs2)
BinaryJobListPtr ExpandBestCaseForward (BinaryJobListPtr exitingJobs)
int FeatureCount () const
const FeatureNumList & Features () const
void Features (const FeatureNumList &_features)
float FMeasure () const
void FMeasure (float _fMeasure)
double GammaParm () const
void GammaParm (double _gammaParm)
double GammaParm ()
float Grade () const
void Grade (float _grade)
int JobId () const
void JobId (int _jobId)
virtual JobTypes JobType () const
KKStr JobTypeStr () const
kkint32 NumOfRounds () const
void NumOfRounds (kkint32 _numOfRounds)
int ParentId () const
double ProcessingTime () const
void ProcessingTime (double _processingTime)
ProcessorPtr Processor () const
int RandomNum () const
virtual void ReFresh (BinaryJob &j)
KKStr ReportLine () const
KKStr ReportLineHTML () const
BinaryJobStatus Status () const
void Status (BinaryJobStatus _status)
KKStr StatusStr () const
float TestAccuracy () const
void TestAccuracy (float _testAccuracy)
float TestAccuracyNorm () const
void TestAccuracyNorm (float _testAccuracyNorm)
float TestAvgPredProb () const
void TestAvgPredProb (float _testAvgPredProb)
float TestDeltaProbAccuracy () const
float TestFMeasure () const
void TestFMeasure (float _testFMeasure)
float TestGrade () const
void TestGrade (float _testGrade)
int TestNumSVs () const
void TestNumSVs (int _testNumSVs)
virtual KKStr ToStatusStr ()
bool ValidateOnly () const
void ValidateOnly (bool _validateOnly)
Static Public Member Functions
static BinaryJobStatus BinaryJobStatusFromStr (KKStr statusStr)
static KKStr BinaryJobStatusToStr (BinaryJobStatus status)
static BinaryJobPtr CreateDuplicateJob (BinaryJob &j)
static BinaryJobPtr CreateTestJob (BinaryJobPtr sourceJob)
static KKStr ReportHeaderLine1 ()
static KKStr ReportHeaderLine2 ()
static KKStr ReportHeaderLineHTML ()
Protected Member Functions
void ProcessStatusField (const KKStr &fieldName, const KKStr &fieldValue)
void ProcessStatusStr (KKStrParser &statusStr)
Protected Attributes
float accuracy
float accuracyNorm
float aParm
float avgPredProb
int chgFeatureNum
double cParm
float decisiveProbMean
float decisiveProbStdDev
FeatureNumList features
float fMeasure
double gammaParm
float grade
int jobId
RunLog & log
kkint32 numOfRounds
int parentId
double processingTime
ProcessorPtr processor
int randomNum
BinaryJobStatus status
float testAccuracy
float testAccuracyNorm
float testAvgPredProb
float testFMeasure
float testGrade
int testNumSVs
bool validateOnly
Detailed Description
Definition at line 43 of file BinaryJob.h.
Member Typedef Documentation
typedef BinaryJob* FeatureSelectionApp::BinaryJob::BinaryJobPtr
Definition at line 47 of file BinaryJob.h.
Constructor & Destructor Documentation
BinaryJob::BinaryJob (const BinaryJob & j)
Definition at line 44 of file BinaryJob.cpp.
Referenced by CreateDuplicateJob(), CreateTestJob(), ExpandBestCaseBackward(), and ExpandBestCaseForward().
BinaryJob::BinaryJob (ProcessorPtr _processor, int _parentId, FeatureNumList _features, int _chgFeatureNum)
Definition at line 78 of file BinaryJob.cpp.
References KKB::endl().
BinaryJob::BinaryJob (ProcessorPtr _processor, int _parentId, FeatureNumList _features, int _chgFeatureNum, kkint32 _numOfRounds, double _cParm, double _gammaParm, float _aParm)
Definition at line 120 of file BinaryJob.cpp.
BinaryJob::BinaryJob (ProcessorPtr _processor, KKStrParser statusLine)
Definition at line 164 of file BinaryJob.cpp.
References ProcessStatusStr().
BinaryJob::BinaryJob (RunLog & _log, FileDescPtr _fileDesc)
Definition at line 201 of file BinaryJob.cpp.
BinaryJob::~BinaryJob () virtual
Definition at line 238 of file BinaryJob.cpp.
Member Function Documentation
float FeatureSelectionApp::BinaryJob::Accuracy () const inline
Definition at line 95 of file BinaryJob.h.
References accuracy.
Referenced by FeatureSelectionApp::FeatureImpact::FeatureImpact(), FeatureSelectionApp::Processor::FlagJobsForTesting(), FeatureSelectionApp::ParmSearchResultsProcessor::GetBestCandidates(), DeltaProbAccuarcyComparison::operator()(), AccuracyComparison::operator()(), and TestAccuracyComparison::operator()().
void FeatureSelectionApp::BinaryJob::Accuracy (float _accuracy) inline
Definition at line 127 of file BinaryJob.h.
References accuracy.
float FeatureSelectionApp::BinaryJob::AccuracyNorm () const inline
Definition at line 96 of file BinaryJob.h.
References accuracyNorm.
Referenced by FeatureSelectionApp::Processor::FlagJobsForTesting(), FeatureSelectionApp::BinaryJobList::GenrateSvmResponseSheet(), AccuracyNormComparison::operator()(), and TestAccuracyNormComparison::operator()().
void FeatureSelectionApp::BinaryJob::AccuracyNorm (float _accuracyNorm) inline
Definition at line 128 of file BinaryJob.h.
References accuracyNorm.
float FeatureSelectionApp::BinaryJob::AParm () const inline
Definition at line 97 of file BinaryJob.h.
References aParm.
Referenced by FeatureSelectionApp::BinaryJobList::ComputeMinAndMaxParmValues(), FeatureSelectionApp::BinaryJobList::CreateTestJobsForHighetsGradePerFeatureCount(), FeatureSelectionApp::BinaryJobList::FindNeighboringParameterValues(), FeatureSelectionApp::Processor::FlagJobsForTesting(), FeatureSelectionApp::Processor::GetBestParametersFromTestResults(), FeatureSelectionApp::BinaryJobList::LookUpByParameters(), FeatureSelectionApp::BinaryJobList::LowestDeltaAccuracyProbJob(), and SvmParmsComparison::operator()().
void FeatureSelectionApp::BinaryJob::AParm (float _aParm) inline
Definition at line 129 of file BinaryJob.h.
References aParm.
float FeatureSelectionApp::BinaryJob::AParm () inline
Definition at line 184 of file BinaryJob.h.
References aParm.
float FeatureSelectionApp::BinaryJob::AvgPredProb () const inline
Definition at line 98 of file BinaryJob.h.
References avgPredProb.
Referenced by FeatureSelectionApp::Processor::FlagJobsForTesting().
void FeatureSelectionApp::BinaryJob::AvgPredProb (float _avgPredProb) inline
Definition at line 130 of file BinaryJob.h.
References avgPredProb.
BinaryJobStatus BinaryJob::BinaryJobStatusFromStr (KKStr statusStr) static
Definition at line 369 of file BinaryJob.cpp.
References KKB::KKStr::Upper().
Referenced by ProcessStatusStr().
KKStr BinaryJob::BinaryJobStatusToStr (BinaryJobStatus status) static
Definition at line 349 of file BinaryJob.cpp.
Referenced by StatusStr(), and ToStatusStr().
BinaryJobPtr BinaryJob::CheckTwoListsForExitingJob (FeatureNumList & featuresToLookFor, BinaryJobListPtr exitingJobs1, BinaryJobListPtr exitingJobs2)
Definition at line 570 of file BinaryJob.cpp.
References FeatureSelectionApp::BinaryJobList::LookUpByFeatureNums().
Referenced by ExpandBestCaseBackward(), and ExpandBestCaseForward().
int FeatureSelectionApp::BinaryJob::ChgFeatureNum () const inline
Definition at line 99 of file BinaryJob.h.
References chgFeatureNum.
Referenced by FeatureSelectionApp::Processor::FlagJobsForTesting().
double FeatureSelectionApp::BinaryJob::CParm () const inline
Definition at line 100 of file BinaryJob.h.
References cParm.
Referenced by FeatureSelectionApp::BinaryJobList::ComputeMinAndMaxParmValues(), FeatureSelectionApp::BinaryJobList::CreateTestJobsForHighetsGradePerFeatureCount(), FeatureSelectionApp::BinaryJobList::ExtractJobsWithSmallestDeltaAccProbForEachSvmParameterSet(), FeatureSelectionApp::BinaryJobList::FindNeighboringParameterValues(), FeatureSelectionApp::Processor::FlagJobsForTesting(), FeatureSelectionApp::BinaryJobList::GenrateSvmResponseSheet(), FeatureSelectionApp::Processor::GetBestParametersFromTestResults(), FeatureSelectionApp::BinaryJobList::GetListOfUniqueCValues(), FeatureSelectionApp::BinaryJobList::LookUpByParameters(), and SvmParmsComparison::operator()().
void FeatureSelectionApp::BinaryJob::CParm (double _cParm) inline
Definition at line 131 of file BinaryJob.h.
References cParm.
double FeatureSelectionApp::BinaryJob::CParm () inline
Definition at line 182 of file BinaryJob.h.
References cParm.
BinaryJobPtr BinaryJob::CreateDuplicateJob (BinaryJob & j) static
Definition at line 245 of file BinaryJob.cpp.
References BinaryJob(), and JobType().
Referenced by FeatureSelectionApp::Processor::Run().
BinaryJobPtr BinaryJob::CreateTestJob (BinaryJobPtr sourceJob) static
Definition at line 282 of file BinaryJob.cpp.
References aParm, BinaryJob(), chgFeatureNum, cParm, features, gammaParm, JobId(), jobId, numOfRounds, processor, ReFresh(), Status(), and ValidateOnly().
Referenced by FeatureSelectionApp::BinaryJobList::CreateTestJobsForHighetsGradePerFeatureCount().
float FeatureSelectionApp::BinaryJob::DecisiveProbMean () const inline
Definition at line 101 of file BinaryJob.h.
References decisiveProbMean.
Referenced by FeatureSelectionApp::Processor::FlagJobsForTesting().
void FeatureSelectionApp::BinaryJob::DecisiveProbMean (float _decisiveProbMean) inline
Definition at line 132 of file BinaryJob.h.
References decisiveProbMean.
float FeatureSelectionApp::BinaryJob::DecisiveProbStdDev () const inline
Definition at line 102 of file BinaryJob.h.
References decisiveProbStdDev.
Referenced by FeatureSelectionApp::Processor::FlagJobsForTesting().
void FeatureSelectionApp::BinaryJob::DecisiveProbStdDev (float _decisiveProbStdDev) inline
Definition at line 133 of file BinaryJob.h.
References decisiveProbStdDev.
float BinaryJob::DeltaProbAccuracy () const
Definition at line 964 of file BinaryJob.cpp.
References accuracy, avgPredProb, and DeltaProb().
Referenced by FeatureSelectionApp::BinaryJobList::ExtractJobsWithSmallestDeltaAccProbForEachSvmParameterSet(), FeatureSelectionApp::BinaryJobList::ExtractLowDeltaProbAccuarcy(), FeatureSelectionApp::BinaryJobList::LowestDeltaAccuracyProbJob(), and DeltaProbAccuarcyComparison::operator()().
void BinaryJob::EvaluateNode () virtual
Reimplemented in FeatureSelectionApp::JobRandomSplit, and FeatureSelectionApp::JobValidation.
Definition at line 700 of file BinaryJob.cpp.
References KKMLL::TrainingConfiguration2::A_Param(), KKMLL::CrossValidation::Accuracy(), accuracy, KKMLL::CrossValidation::AccuracyNorm(), accuracyNorm, FeatureSelectionApp::Processor::AlreadyNormalized(), aParm, KKMLL::CrossValidation::AvgPredProb(), avgPredProb, KKMLL::TrainingConfiguration2::C_Param(), FeatureSelectionApp::Processor::ClassesThisProcess(), FeatureSelectionApp::Processor::Config(), KKMLL::CrossValidation::ConfussionMatrix(), cParm, KKB::endl(), features, FeatureSelectionApp::Processor::FileDesc(), KKMLL::ConfusionMatrix2::FMeasure(), fMeasure, KKMLL::TrainingConfiguration2::Gamma(), gammaParm, grade, FeatureSelectionApp::Processor::GradingMethod(), jobId, KKB::RunLog::Level(), log, KKMLL::TrainingConfiguration2::Number_of_rounds(), KKMLL::FeatureNumList::NumOfFeatures(), FeatureSelectionApp::Processor::NumOfFolds(), KKMLL::CrossValidation::NumOfFolds(), numOfRounds, KKMLL::CrossValidation::NumOfSupportVectors(), FeatureSelectionApp::Processor::PositiveClass(), processingTime, processor, KKMLL::CrossValidation::RunCrossValidation(), KKMLL::CrossValidation::RunValidationOnly(), KKMLL::TrainingConfiguration2::SetFeatureNums(), status, testAccuracy, testAccuracyNorm, testAvgPredProb, FeatureSelectionApp::Processor::TestData(), testFMeasure, testGrade, testNumSVs, KKMLL::CrossValidation::TestTimeTotal(), FeatureSelectionApp::Processor::TrainingData(), KKMLL::CrossValidation::TrainTimeTotal(), and validateOnly.
Referenced by FeatureSelectionApp::Processor::Run().
BinaryJobListPtr BinaryJob::ExpandBestCaseBackward (BinaryJobListPtr exitingJobs1, BinaryJobListPtr exitingJobs2)
Definition at line 589 of file BinaryJob.cpp.
References aParm, BinaryJob(), CheckTwoListsForExitingJob(), cParm, KKB::endl(), features, gammaParm, jobId, KKB::RunLog::Level(), log, KKMLL::FeatureNumList::NumOfFeatures(), numOfRounds, processor, FeatureSelectionApp::BinaryJobList::PushOnBack(), and ToStatusStr().
BinaryJobListPtr BinaryJob::ExpandBestCaseForward (BinaryJobListPtr exitingJobs1, BinaryJobListPtr exitingJobs2)
Definition at line 643 of file BinaryJob.cpp.
References aParm, BinaryJob(), CheckTwoListsForExitingJob(), cParm, KKB::endl(), features, gammaParm, FeatureSelectionApp::Processor::InitialFeatures(), KKMLL::FeatureNumList::InList(), jobId, KKB::RunLog::Level(), log, KKMLL::FeatureNumList::NumOfFeatures(), numOfRounds, processor, FeatureSelectionApp::BinaryJobList::PushOnBack(), and ToStatusStr().
BinaryJobListPtr FeatureSelectionApp::BinaryJob::ExpandBestCaseForward (BinaryJobListPtr exitingJobs)
int FeatureSelectionApp::BinaryJob::FeatureCount () const inline
Definition at line 169 of file BinaryJob.h.
References features, and KKMLL::FeatureNumList::NumOfFeatures().
Referenced by FeatureSelectionApp::Processor::GetCpuCyclesByFeatureCount(), FeatureSelectionApp::Processor::GetSmallestJobIdByFeatureCount(), and FeatureSelectionApp::BinaryJobList::SelectFeaturesByMostFeaturesWithHighestGrade().
const FeatureNumList& FeatureSelectionApp::BinaryJob::Features () const inline
Definition at line 108 of file BinaryJob.h.
References features.
Referenced by FeatureSelectionApp::BinaryJobList::CreateTestJobsForHighetsGradePerFeatureCount(), FeatureSelectionApp::BinaryJobList::ExtractJobsForAGivenFeatureCount(), FeatureSelectionApp::FeatureImpact::FeatureImpact(), FeatureSelectionApp::Processor::FlagJobsForTesting(), FeatureSelectionApp::Processor::GetFeaturesFromTestResults(), FeatureSelectionApp::BinaryJobList::LookUpByFeatureNums(), FeatureSelectionApp::BinaryJobList::LookUpByParameters(), FeatureSelectionApp::Processor::MergeKBestFeatureSelections(), GradeComparison::operator()(), AccuracyComparison::operator()(), AccuracyNormComparison::operator()(), TestGradeComparison::operator()(), TestAccuracyComparison::operator()(), TestAccuracyNormComparison::operator()(), and FeatureSelectionApp::BinaryJobList::SmallestNumberOfFeaturesExpanded().
void FeatureSelectionApp::BinaryJob::Features (const FeatureNumList & _features) inline
Definition at line 134 of file BinaryJob.h.
References features.
float FeatureSelectionApp::BinaryJob::FMeasure () const inline
Definition at line 104 of file BinaryJob.h.
References fMeasure.
Referenced by FeatureSelectionApp::FeatureImpact::FeatureImpact(), and FeatureSelectionApp::Processor::FlagJobsForTesting().
void FeatureSelectionApp::BinaryJob::FMeasure (float _fMeasure) inline
Definition at line 135 of file BinaryJob.h.
References fMeasure.
double FeatureSelectionApp::BinaryJob::GammaParm () const inline
Definition at line 105 of file BinaryJob.h.
References gammaParm.
Referenced by FeatureSelectionApp::BinaryJobList::ComputeMinAndMaxParmValues(), FeatureSelectionApp::BinaryJobList::CreateTestJobsForHighetsGradePerFeatureCount(), FeatureSelectionApp::BinaryJobList::ExtractJobsWithSmallestDeltaAccProbForEachSvmParameterSet(), FeatureSelectionApp::BinaryJobList::FindNeighboringParameterValues(), FeatureSelectionApp::Processor::FlagJobsForTesting(), FeatureSelectionApp::BinaryJobList::GenrateSvmResponseSheet(), FeatureSelectionApp::Processor::GetBestParametersFromTestResults(), FeatureSelectionApp::BinaryJobList::GetListOfUniqueGammaValues(), FeatureSelectionApp::BinaryJobList::LookUpByParameters(), and SvmParmsComparison::operator()().
void FeatureSelectionApp::BinaryJob::GammaParm (double _gammaParm) inline
Definition at line 136 of file BinaryJob.h.
References gammaParm.
double FeatureSelectionApp::BinaryJob::GammaParm () inline
Definition at line 183 of file BinaryJob.h.
References gammaParm.
float FeatureSelectionApp::BinaryJob::Grade () const inline
Definition at line 106 of file BinaryJob.h.
References grade.
Referenced by FeatureSelectionApp::BinaryJobList::CreateTestJobsForHighetsGradePerFeatureCount(), FeatureSelectionApp::BinaryJobList::ExtractHighestGrade(), FeatureSelectionApp::Processor::FlagJobsForTesting(), FeatureSelectionApp::BinaryJobList::HighestGradedJob(), FeatureSelectionApp::BinaryJobList::LowestDeltaAccuracyProbJob(), GradeComparison::operator()(), ProcessingTimeComparison::operator()(), SvmParmsComparison::operator()(), TestGradeComparison::operator()(), and FeatureSelectionApp::BinaryJobList::SelectFeaturesByMostFeaturesWithHighestGrade().
void FeatureSelectionApp::BinaryJob::Grade (float _grade) inline
Definition at line 137 of file BinaryJob.h.
References grade.
int FeatureSelectionApp::BinaryJob::JobId () const inline
Definition at line 109 of file BinaryJob.h.
References jobId.
Referenced by CreateTestJob(), FeatureSelectionApp::Processor::FlagJobsForTesting(), FeatureSelectionApp::BinaryJobList::PushOnBack(), FeatureSelectionApp::BinaryJobList::ReFresh(), and FeatureSelectionApp::Results::Results().
void FeatureSelectionApp::BinaryJob::JobId (int _jobId) inline
Definition at line 138 of file BinaryJob.h.
References jobId.
JobTypes BinaryJob::JobType () const virtual
Reimplemented in FeatureSelectionApp::JobRandomSplit, and FeatureSelectionApp::JobValidation.
Definition at line 261 of file BinaryJob.cpp.
Referenced by CreateDuplicateJob(), JobTypeStr(), FeatureSelectionApp::BinaryJobList::PushOnBack(), FeatureSelectionApp::JobValidation::ReFresh(), and FeatureSelectionApp::JobRandomSplit::ReFresh().
KKStr BinaryJob::JobTypeStr () const
Definition at line 267 of file BinaryJob.cpp.
References JobType().
Referenced by FeatureSelectionApp::Processor::FlagJobsForTesting(), and FeatureSelectionApp::Processor::ProcessRestart().
kkint32 FeatureSelectionApp::BinaryJob::NumOfRounds () const inline
Definition at line 110 of file BinaryJob.h.
References numOfRounds.
Referenced by FeatureSelectionApp::BinaryJobList::CreateTestJobsForHighetsGradePerFeatureCount(), FeatureSelectionApp::Processor::FlagJobsForTesting(), and FeatureSelectionApp::BinaryJobList::LookUpByParameters().
void FeatureSelectionApp::BinaryJob::NumOfRounds (kkint32 _numOfRounds) inline
Definition at line 139 of file BinaryJob.h.
References numOfRounds.
int FeatureSelectionApp::BinaryJob::ParentId () const inline
Definition at line 111 of file BinaryJob.h.
References parentId.
Referenced by FeatureSelectionApp::FeatureImpact::FeatureImpact().
double FeatureSelectionApp::BinaryJob::ProcessingTime () const inline
Definition at line 113 of file BinaryJob.h.
References processingTime.
Referenced by FeatureSelectionApp::BinaryJobList::ExtractByMinimumProcessintTime(), FeatureSelectionApp::BinaryJobList::ExtractFastestJobs(), FeatureSelectionApp::BinaryJobList::FastestJob(), FeatureSelectionApp::Processor::FlagJobsForTesting(), FeatureSelectionApp::BinaryJobList::GenrateSvmResponseSheet(), FeatureSelectionApp::ParmSearchResultsProcessor::GetBestCandidates(), FeatureSelectionApp::Processor::GetCpuCyclesByFeatureCount(), FeatureSelectionApp::BinaryJobList::HighestGradedJob(), FeatureSelectionApp::BinaryJobList::HighestGradedTestJob(), GradeComparison::operator()(), ProcessingTimeComparison::operator()(), TestGradeComparison::operator()(), TestAccuracyComparison::operator()(), TestAccuracyNormComparison::operator()(), and FeatureSelectionApp::BinaryJobList::TotalProcessingTime().
void FeatureSelectionApp::BinaryJob::ProcessingTime (double _processingTime) inline
Definition at line 140 of file BinaryJob.h.
References processingTime.
ProcessorPtr FeatureSelectionApp::BinaryJob::Processor () const inline
Definition at line 112 of file BinaryJob.h.
References processor.
void BinaryJob::ProcessStatusField (const KKStr & fieldName, const KKStr & fieldValue) protected
Definition at line 559 of file BinaryJob.cpp.
References KKB::endl(), KKB::RunLog::Level(), and log.
Referenced by ProcessStatusStr().
void BinaryJob::ProcessStatusStr (KKStrParser & statusStr) protected
Definition at line 449 of file BinaryJob.cpp.
References accuracy, accuracyNorm, aParm, avgPredProb, BinaryJobStatusFromStr(), chgFeatureNum, cParm, decisiveProbMean, decisiveProbStdDev, KKB::KKStr::Empty(), KKB::endl(), KKB::KKStr::EqualIgnoreCase(), features, fMeasure, gammaParm, KKB::KKStrParser::GetNextToken(), grade, jobId, KKB::RunLog::Level(), log, numOfRounds, parentId, processingTime, ProcessStatusField(), randomNum, status, KKB::KKStrParser::Str(), testAccuracy, testAccuracyNorm, testAvgPredProb, testFMeasure, testGrade, testNumSVs, KKB::KKStr::ToBool(), KKB::KKStr::ToDouble(), KKB::KKStr::ToFloat(), KKB::KKStr::ToInt(), KKB::KKStr::ToInt32(), KKB::KKStr::TrimLeft(), KKB::KKStr::TrimRight(), KKB::KKStr::Upper(), and validateOnly.
Referenced by BinaryJob().
int FeatureSelectionApp::BinaryJob::RandomNum () const inline
Definition at line 114 of file BinaryJob.h.
References randomNum.
Referenced by GradeComparison::operator()(), AccuracyComparison::operator()(), AccuracyNormComparison::operator()(), TestGradeComparison::operator()(), TestAccuracyComparison::operator()(), and TestAccuracyNormComparison::operator()().
void BinaryJob::ReFresh (BinaryJob & j) virtual
Reimplemented in FeatureSelectionApp::JobRandomSplit, and FeatureSelectionApp::JobValidation.
Definition at line 309 of file BinaryJob.cpp.
References accuracy, accuracyNorm, aParm, avgPredProb, chgFeatureNum, cParm, decisiveProbMean, decisiveProbStdDev, KKB::endl(), features, fMeasure, gammaParm, grade, jobId, KKB::RunLog::Level(), log, numOfRounds, parentId, processingTime, processor, randomNum, status, testAccuracy, testAccuracyNorm, testAvgPredProb, testFMeasure, testGrade, testNumSVs, and validateOnly.
Referenced by CreateTestJob(), FeatureSelectionApp::JobValidation::ReFresh(), FeatureSelectionApp::JobRandomSplit::ReFresh(), and FeatureSelectionApp::BinaryJobList::ReFresh().
KKStr BinaryJob::ReportHeaderLine1 () static
Definition at line 793 of file BinaryJob.cpp.
Referenced by FeatureSelectionApp::BinaryJobList::ReportResults().
KKStr BinaryJob::ReportHeaderLine2 () static
Definition at line 824 of file BinaryJob.cpp.
Referenced by FeatureSelectionApp::BinaryJobList::ReportResults().
KKStr BinaryJob::ReportHeaderLineHTML () static
Definition at line 880 of file BinaryJob.cpp.
Referenced by FeatureSelectionApp::BinaryJobList::ReportResultsHTML().
KKStr BinaryJob::ReportLine () const
Definition at line 852 of file BinaryJob.cpp.
References accuracy, accuracyNorm, aParm, avgPredProb, chgFeatureNum, cParm, features, fMeasure, gammaParm, jobId, numOfRounds, KKMLL::FeatureNumList::NumSelFeatures(), parentId, processingTime, KKB::StrFormatDouble(), testAccuracy, testAccuracyNorm, testAvgPredProb, testFMeasure, testNumSVs, and KKMLL::FeatureNumList::ToString().
Referenced by FeatureSelectionApp::BinaryJobList::ReportResults().
KKStr BinaryJob::ReportLineHTML () const
Definition at line 909 of file BinaryJob.cpp.
References accuracy, accuracyNorm, aParm, avgPredProb, chgFeatureNum, cParm, features, fMeasure, gammaParm, jobId, numOfRounds, KKMLL::FeatureNumList::NumSelFeatures(), parentId, processingTime, KKB::StrFormatDouble(), testAccuracy, testAccuracyNorm, testAvgPredProb, testFMeasure, testNumSVs, and KKMLL::FeatureNumList::ToString().
Referenced by FeatureSelectionApp::BinaryJobList::ReportResultsHTML().
BinaryJobStatus FeatureSelectionApp::BinaryJob::Status () const inline
Definition at line 115 of file BinaryJob.h.
References status.
Referenced by FeatureSelectionApp::BinaryJobList::AreAllJobsDone(), CreateTestJob(), FeatureSelectionApp::Processor::FlagJobsForTesting(), FeatureSelectionApp::BinaryJobList::JobsStillRunning(), FeatureSelectionApp::BinaryJobList::LocateOpenJob(), FeatureSelectionApp::Processor::ProcessRestart(), FeatureSelectionApp::BinaryJobList::SelectOneDoneJobAtRandomFromTop10Percent(), and FeatureSelectionApp::BinaryJobList::SmallestNumberOfFeaturesExpanded().
void FeatureSelectionApp::BinaryJob::Status (BinaryJobStatus _status) inline
Definition at line 141 of file BinaryJob.h.
References status.
KKStr BinaryJob::StatusStr () const
Definition at line 391 of file BinaryJob.cpp.
References BinaryJobStatusToStr(), and status.
float FeatureSelectionApp::BinaryJob::TestAccuracy () const inline
Definition at line 117 of file BinaryJob.h.
References testAccuracy.
Referenced by DeltaTestProbAccuarcyComparison::operator()(), and TestAccuracyComparison::operator()().
void FeatureSelectionApp::BinaryJob::TestAccuracy (float _testAccuracy) inline
Definition at line 142 of file BinaryJob.h.
References testAccuracy.
float FeatureSelectionApp::BinaryJob::TestAccuracyNorm () const inline
Definition at line 118 of file BinaryJob.h.
References testAccuracyNorm.
Referenced by TestAccuracyNormComparison::operator()().
void FeatureSelectionApp::BinaryJob::TestAccuracyNorm (float _testAccuracyNorm) inline
Definition at line 143 of file BinaryJob.h.
References testAccuracyNorm.
float FeatureSelectionApp::BinaryJob::TestAvgPredProb () const inline
Definition at line 119 of file BinaryJob.h.
References testAvgPredProb.
void FeatureSelectionApp::BinaryJob::TestAvgPredProb (float _testAvgPredProb) inline
Definition at line 144 of file BinaryJob.h.
References testAvgPredProb.
float BinaryJob::TestDeltaProbAccuracy () const
Definition at line 972 of file BinaryJob.cpp.
References DeltaProb(), testAccuracy, and testAvgPredProb.
Referenced by FeatureSelectionApp::BinaryJobList::LowestDeltaAccuracyProbTestJob(), and DeltaTestProbAccuarcyComparison::operator()().
float FeatureSelectionApp::BinaryJob::TestFMeasure () const inline
Definition at line 122 of file BinaryJob.h.
References testFMeasure.
void FeatureSelectionApp::BinaryJob::TestFMeasure (float _testFMeasure) inline
Definition at line 146 of file BinaryJob.h.
References testFMeasure.
float FeatureSelectionApp::BinaryJob::TestGrade () const inline
Definition at line 121 of file BinaryJob.h.
References testGrade.
Referenced by FeatureSelectionApp::BinaryJobList::ExtractHighestTestGrade(), FeatureSelectionApp::BinaryJobList::ExtractTestJobs(), FeatureSelectionApp::BinaryJobList::HighestGradedTestJob(), FeatureSelectionApp::BinaryJobList::LowestDeltaAccuracyProbTestJob(), and TestGradeComparison::operator()().
void FeatureSelectionApp::BinaryJob::TestGrade (float _testGrade) inline
Definition at line 145 of file BinaryJob.h.
References testGrade.
int FeatureSelectionApp::BinaryJob::TestNumSVs () const inline
Definition at line 123 of file BinaryJob.h.
References testNumSVs.
Referenced by DeltaTestProbAccuarcyComparison::operator()().
void FeatureSelectionApp::BinaryJob::TestNumSVs (int _testNumSVs) inline
Definition at line 147 of file BinaryJob.h.
References testNumSVs.
KKStr BinaryJob::ToStatusStr () virtual
Reimplemented in FeatureSelectionApp::JobRandomSplit, and FeatureSelectionApp::JobValidation.
Definition at line 399 of file BinaryJob.cpp.
References accuracy, accuracyNorm, aParm, avgPredProb, BinaryJobStatusToStr(), chgFeatureNum, cParm, decisiveProbMean, decisiveProbStdDev, features, fMeasure, gammaParm, grade, jobId, numOfRounds, parentId, processingTime, randomNum, status, KKB::StrFormatDouble(), KKB::StrFormatInt(), testAccuracy, testAccuracyNorm, testAvgPredProb, testFMeasure, testGrade, testNumSVs, KKMLL::FeatureNumList::ToString(), and validateOnly.
Referenced by ExpandBestCaseBackward(), ExpandBestCaseForward(), FeatureSelectionApp::Processor::FlagJobsForTesting(), FeatureSelectionApp::ParmSearchResultsProcessor::GetBestCandidates(), FeatureSelectionApp::Processor::ProcessRestart(), FeatureSelectionApp::BinaryJobList::PushOnBack(), FeatureSelectionApp::Processor::Run(), FeatureSelectionApp::BinaryJobList::Save(), FeatureSelectionApp::JobValidation::ToStatusStr(), and FeatureSelectionApp::JobRandomSplit::ToStatusStr().
bool FeatureSelectionApp::BinaryJob::ValidateOnly () const inline
Definition at line 124 of file BinaryJob.h.
References validateOnly.
Referenced by CreateTestJob(), FeatureSelectionApp::Processor::FlagJobsForTesting(), FeatureSelectionApp::BinaryJobList::LookUpByParameters(), FeatureSelectionApp::BinaryJobList::LowestDeltaAccuracyProbTestJob(), TestGradeComparison::operator()(), TestAccuracyComparison::operator()(), and TestAccuracyNormComparison::operator()().
void FeatureSelectionApp::BinaryJob::ValidateOnly (bool _validateOnly) inline
Definition at line 148 of file BinaryJob.h.
References validateOnly.
Member Data Documentation
float FeatureSelectionApp::BinaryJob::accuracy protected
Definition at line 209 of file BinaryJob.h.
Referenced by Accuracy(), DeltaProbAccuracy(), EvaluateNode(), ProcessStatusStr(), ReFresh(), ReportLine(), ReportLineHTML(), and ToStatusStr().
float FeatureSelectionApp::BinaryJob::accuracyNorm protected
Definition at line 210 of file BinaryJob.h.
Referenced by AccuracyNorm(), EvaluateNode(), ProcessStatusStr(), ReFresh(), ReportLine(), ReportLineHTML(), and ToStatusStr().
float FeatureSelectionApp::BinaryJob::aParm protected
Definition at line 236 of file BinaryJob.h.
Referenced by AParm(), CreateTestJob(), FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), EvaluateNode(), ExpandBestCaseBackward(), ExpandBestCaseForward(), ProcessStatusStr(), ReFresh(), ReportLine(), ReportLineHTML(), and ToStatusStr().
float FeatureSelectionApp::BinaryJob::avgPredProb protected
Definition at line 211 of file BinaryJob.h.
Referenced by AvgPredProb(), DeltaProbAccuracy(), EvaluateNode(), ProcessStatusStr(), ReFresh(), ReportLine(), ReportLineHTML(), and ToStatusStr().
int FeatureSelectionApp::BinaryJob::chgFeatureNum protected
Definition at line 212 of file BinaryJob.h.
Referenced by ChgFeatureNum(), CreateTestJob(), ProcessStatusStr(), ReFresh(), ReportLine(), ReportLineHTML(), and ToStatusStr().
double FeatureSelectionApp::BinaryJob::cParm protected
Definition at line 234 of file BinaryJob.h.
Referenced by CParm(), CreateTestJob(), FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), EvaluateNode(), ExpandBestCaseBackward(), ExpandBestCaseForward(), ProcessStatusStr(), ReFresh(), ReportLine(), ReportLineHTML(), and ToStatusStr().
float FeatureSelectionApp::BinaryJob::decisiveProbMean protected
Definition at line 213 of file BinaryJob.h.
Referenced by DecisiveProbMean(), ProcessStatusStr(), ReFresh(), and ToStatusStr().
float FeatureSelectionApp::BinaryJob::decisiveProbStdDev protected
Definition at line 214 of file BinaryJob.h.
Referenced by DecisiveProbStdDev(), ProcessStatusStr(), ReFresh(), and ToStatusStr().
FeatureNumList FeatureSelectionApp::BinaryJob::features protected
Definition at line 215 of file BinaryJob.h.
Referenced by CreateTestJob(), FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), EvaluateNode(), ExpandBestCaseBackward(), ExpandBestCaseForward(), FeatureCount(), Features(), ProcessStatusStr(), ReFresh(), ReportLine(), ReportLineHTML(), and ToStatusStr().
float FeatureSelectionApp::BinaryJob::fMeasure protected
Definition at line 216 of file BinaryJob.h.
Referenced by EvaluateNode(), FMeasure(), ProcessStatusStr(), ReFresh(), ReportLine(), ReportLineHTML(), and ToStatusStr().
double FeatureSelectionApp::BinaryJob::gammaParm protected
Definition at line 235 of file BinaryJob.h.
Referenced by CreateTestJob(), FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), EvaluateNode(), ExpandBestCaseBackward(), ExpandBestCaseForward(), GammaParm(), ProcessStatusStr(), ReFresh(), ReportLine(), ReportLineHTML(), and ToStatusStr().
float FeatureSelectionApp::BinaryJob::grade protected
Definition at line 217 of file BinaryJob.h.
Referenced by EvaluateNode(), Grade(), ProcessStatusStr(), ReFresh(), and ToStatusStr().
int FeatureSelectionApp::BinaryJob::jobId protected
Definition at line 219 of file BinaryJob.h.
Referenced by CreateTestJob(), FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), EvaluateNode(), ExpandBestCaseBackward(), ExpandBestCaseForward(), JobId(), ProcessStatusStr(), ReFresh(), ReportLine(), ReportLineHTML(), and ToStatusStr().
RunLog& FeatureSelectionApp::BinaryJob::log protected
Definition at line 218 of file BinaryJob.h.
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), EvaluateNode(), ExpandBestCaseBackward(), ExpandBestCaseForward(), ProcessStatusField(), ProcessStatusStr(), and ReFresh().
kkint32 FeatureSelectionApp::BinaryJob::numOfRounds protected
Definition at line 237 of file BinaryJob.h.
Referenced by CreateTestJob(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), EvaluateNode(), ExpandBestCaseBackward(), ExpandBestCaseForward(), NumOfRounds(), ProcessStatusStr(), ReFresh(), ReportLine(), ReportLineHTML(), and ToStatusStr().
int FeatureSelectionApp::BinaryJob::parentId protected
Definition at line 220 of file BinaryJob.h.
Referenced by ParentId(), ProcessStatusStr(), ReFresh(), ReportLine(), ReportLineHTML(), and ToStatusStr().
double FeatureSelectionApp::BinaryJob::processingTime protected
Definition at line 221 of file BinaryJob.h.
Referenced by EvaluateNode(), ProcessingTime(), ProcessStatusStr(), ReFresh(), ReportLine(), ReportLineHTML(), and ToStatusStr().
ProcessorPtr FeatureSelectionApp::BinaryJob::processor protected
Definition at line 222 of file BinaryJob.h.
Referenced by CreateTestJob(), FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), EvaluateNode(), ExpandBestCaseBackward(), ExpandBestCaseForward(), Processor(), and ReFresh().
int FeatureSelectionApp::BinaryJob::randomNum protected
Definition at line 223 of file BinaryJob.h.
Referenced by ProcessStatusStr(), RandomNum(), ReFresh(), and ToStatusStr().
BinaryJobStatus FeatureSelectionApp::BinaryJob::status protected
Definition at line 224 of file BinaryJob.h.
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), EvaluateNode(), ProcessStatusStr(), ReFresh(), Status(), StatusStr(), and ToStatusStr().
float FeatureSelectionApp::BinaryJob::testAccuracy protected
Definition at line 225 of file BinaryJob.h.
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), EvaluateNode(), ProcessStatusStr(), ReFresh(), ReportLine(), ReportLineHTML(), TestAccuracy(), TestDeltaProbAccuracy(), and ToStatusStr().
float FeatureSelectionApp::BinaryJob::testAccuracyNorm protected
Definition at line 226 of file BinaryJob.h.
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), EvaluateNode(), ProcessStatusStr(), ReFresh(), ReportLine(), ReportLineHTML(), TestAccuracyNorm(), and ToStatusStr().
float FeatureSelectionApp::BinaryJob::testAvgPredProb protected
Definition at line 227 of file BinaryJob.h.
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), EvaluateNode(), ProcessStatusStr(), ReFresh(), ReportLine(), ReportLineHTML(), TestAvgPredProb(), TestDeltaProbAccuracy(), and ToStatusStr().
float FeatureSelectionApp::BinaryJob::testFMeasure protected
Definition at line 228 of file BinaryJob.h.
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), EvaluateNode(), ProcessStatusStr(), ReFresh(), ReportLine(), ReportLineHTML(), TestFMeasure(), and ToStatusStr().
float FeatureSelectionApp::BinaryJob::testGrade protected
Definition at line 229 of file BinaryJob.h.
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), EvaluateNode(), ProcessStatusStr(), ReFresh(), TestGrade(), and ToStatusStr().
int FeatureSelectionApp::BinaryJob::testNumSVs protected
Definition at line 230 of file BinaryJob.h.
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), EvaluateNode(), ProcessStatusStr(), ReFresh(), ReportLine(), ReportLineHTML(), TestNumSVs(), and ToStatusStr().
bool FeatureSelectionApp::BinaryJob::validateOnly protected
Definition at line 239 of file BinaryJob.h.
Referenced by EvaluateNode(), ProcessStatusStr(), ReFresh(), ToStatusStr(), and ValidateOnly().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/Apps/FeatureSelection/BinaryJob.h
C:/Users/kurtk_000/GitHub/Pices/Apps/FeatureSelection/BinaryJob.cpp