Pices: PicesCommander.ChartSizeDepthDistribution Class Reference
PicesCommander.ChartSizeDepthDistribution Class Reference
Public Member Functions
ChartSizeDepthDistribution (String _cruise, String _station, String _deployment, PicesClass _classToPlot, bool _includeSubClasses, char _statistic, String _cast, PicesImageSizeDistribution _sizeDistribution, int _selectedSizeBucket)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Detailed Description
Definition at line 17 of file ChartSizeDepthDistribution.cs.
Constructor & Destructor Documentation
PicesCommander.ChartSizeDepthDistribution.ChartSizeDepthDistribution (String _cruise, String _station, String _deployment, PicesClass _classToPlot, bool _includeSubClasses, char _statistic, String _cast, PicesImageSizeDistribution _sizeDistribution, int _selectedSizeBucket) inline
Definition at line 57 of file ChartSizeDepthDistribution.cs.
References PicesInterface::PicesDataBase.Close(), PicesInterface::PicesImageSizeDistributionRow.Depth, PicesInterface::PicesImageSizeDistribution.DepthBinSize, PicesInterface::PicesImageSizeDistribution.DepthProfileForSizeBin(), PicesInterface::PicesImageSizeDistributionRow.Distribution(), PicesInterface::PicesGoalKeeper.EndBlock(), PicesInterface::PicesImageSizeDistribution.GetDepthBin(), PicesInterface::PicesDataBase.GetGlobalDatabaseManagerNewInstance(), PicesInterface::PicesImageSizeDistribution.GetSizeBucketStats(), PicesInterface::PicesDataBase.ImagesQueryDeploymentSizeRange(), PicesInterface::PicesClass.Name, PicesInterface::PicesImageSizeDistribution.NumDepthBins, PicesInterface::PicesImageSizeDistribution.NumSizeBuckets, PicesInterface::PicesImageSizeDistribution.SizeEndValues(), PicesInterface::PicesImageSizeDistribution.SizeStartValues(), PicesInterface::PicesGoalKeeper.StartBlock(), PicesInterface::PicesImageSizeDistribution.VolumeSampledByDepthBucket(), and PicesInterface::PicesRunLog.Writeln().
Member Function Documentation
override void PicesCommander.ChartSizeDepthDistribution.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file ChartSizeDepthDistribution.Designer.cs.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/ChartSizeDepthDistribution.cs
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/ChartSizeDepthDistribution.Designer.cs