Pices: PicesInterface::PicesDataBaseServer Class Reference
PicesInterface::PicesDataBaseServer Class Reference
#include <PicesDataBaseServer.h>
Public Member Functions
PicesDataBaseServer ()
PicesDataBaseServer (const DataBaseServerPtr server)
PicesDataBaseServer (PicesDataBaseServer^ picesServer)
void CleanUpMemory ()
DataBaseServerPtr Server ()
DataBaseServerPtr UnManagedClass ()
Protected Member Functions
~PicesDataBaseServer ()
Properties
String^ DataBaseName [get, set]
String^ Description [get, set]
String^ HostName [get, set]
String^ PassWord [get, set]
kkuint32 PortNum [get, set]
String^ UserName [get, set]
Detailed Description
Definition at line 19 of file PicesDataBaseServer.h.
Constructor & Destructor Documentation
PicesDataBaseServer::PicesDataBaseServer ()
Definition at line 35 of file PicesDataBaseServer.cpp.
Referenced by ~PicesDataBaseServer().
PicesDataBaseServer::PicesDataBaseServer (const DataBaseServerPtr server)
Definition at line 52 of file PicesDataBaseServer.cpp.
PicesDataBaseServer::PicesDataBaseServer (PicesDataBaseServer^ picesServer)
Definition at line 44 of file PicesDataBaseServer.cpp.
PicesDataBaseServer::~PicesDataBaseServer () protected
Definition at line 61 of file PicesDataBaseServer.cpp.
References MLL::DataBaseServer::DataBaseName(), MLL::DataBaseServer::Description(), MLL::DataBaseServer::HostName(), PicesInterface::PicesKKStr::KKStrToSystenStr(), MLL::DataBaseServer::PassWord(), PicesDataBaseServer(), MLL::DataBaseServer::PortNum(), PicesInterface::PicesKKStr::SystemStringToKKStr(), and MLL::DataBaseServer::UserName().
Member Function Documentation
void PicesDataBaseServer::CleanUpMemory ()
Definition at line 189 of file PicesDataBaseServer.cpp.
Referenced by PicesInterface::PicesDataBaseServerList::~PicesDataBaseServerList().
DataBaseServerPtr PicesInterface::PicesDataBaseServer::Server () inline
Definition at line 35 of file PicesDataBaseServer.h.
Referenced by PicesInterface::PicesDataBase::PicesDataBase().
DataBaseServerPtr PicesInterface::PicesDataBaseServer::UnManagedClass () inline
Definition at line 46 of file PicesDataBaseServer.h.
Referenced by PicesInterface::PicesDataBaseServerList::WriteConfigFile().
Property Documentation
String^ PicesInterface::PicesDataBaseServer::DataBaseName get set
Definition at line 42 of file PicesDataBaseServer.h.
Referenced by PicesCommander.InstrumentDataByDeploymentProfile::InstrumentDataByDeploymentProfile(), and PicesInterface::PicesDataBaseServerPrompter::~PicesDataBaseServerPrompter().
String^ PicesInterface::PicesDataBaseServer::Description get set
Definition at line 37 of file PicesDataBaseServer.h.
Referenced by PicesCommander.ImportGroupAssignments::ImportGroupAssignments(), PicesCommander.InstrumentDataByDeploymentProfile::InstrumentDataByDeploymentProfile(), PicesInterface::PicesDataBaseServerList::LookUpByDescription(), PicesCommander.ReconcileImagesToDataBase::ReconcileImagesToDataBase(), PicesCommander.PicesCommander::UpdateLastClassesValidated(), and PicesInterface::PicesDataBaseServerPrompter::~PicesDataBaseServerPrompter().
String^ PicesInterface::PicesDataBaseServer::HostName get set
Definition at line 38 of file PicesDataBaseServer.h.
Referenced by PicesCommander.ClassificationStatus::CleanUpMemory(), PicesCommander.ImportImagesIntoDeployment::ImportImagesIntoDeployment(), PicesCommander.ImportValidatdClass::ImportValidatdClass(), and PicesInterface::PicesDataBaseServerPrompter::~PicesDataBaseServerPrompter().
String^ PicesInterface::PicesDataBaseServer::PassWord get set
Definition at line 41 of file PicesDataBaseServer.h.
Referenced by PicesInterface::PicesDataBaseServerPrompter::~PicesDataBaseServerPrompter().
kkuint32 PicesInterface::PicesDataBaseServer::PortNum get set
Definition at line 39 of file PicesDataBaseServer.h.
Referenced by PicesInterface::PicesDataBaseServerPrompter::~PicesDataBaseServerPrompter().
String^ PicesInterface::PicesDataBaseServer::UserName get set
Definition at line 40 of file PicesDataBaseServer.h.
Referenced by PicesInterface::PicesDataBaseServerPrompter::~PicesDataBaseServerPrompter().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesDataBaseServer.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesDataBaseServer.cpp