Pices: C:/Users/kurtk_000/GitHub/KSquareLibraries/KKBase/BMPImage.cpp File Reference
BMPImage.cpp File Reference
#include "FirstIncludes.h"
#include <algorithm>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <string.h>
#include <string>
#include <vector>
#include <stdio.h>
#include "MemoryDebug.h"
#include "BMPImage.h"
#include "KKException.h"
#include "OSservices.h"
#include "Raster.h"
Classes
struct KKB::BmpImage::Bmp1BitRec
struct KKB::BmpImage::Bmp4BitRecs
struct KKB::BmpImage::BMP_24BitPixel
class KKB::BmpImage::CodedPixels
This object is used to help encode the data stored in BMPImage::image into 8 or 4 bit compressed formats used by BMP files.
struct KKB::BmpImage::CodePair
union KKB::BmpImage::DWordParts
union KKB::BmpImage::LongParts
class KKB::BmpImage::PalletBuilder
class KKB::BmpImage::PalletBuilder::RGBQUAD_Pred
union KKB::BmpImage::WordParts
Functions
bool GrayScaleImage (RGBQUAD *palette, kkint32 palletSize)
Returns true if palette is for a grayscale image.
void RotateDWORD (DWORD &w)
void RotateLONG (LONG &l)
void RotateWORD (WORD &w)
void WriteBYTE (FILE *outFile, BYTE b)
void WriteDWORD (FILE *outFile, DWORD dw)
void WriteLONG (FILE *outFile, LONG l)
void WriteWORD (FILE *outFile, WORD w)
Function Documentation
bool GrayScaleImage (RGBQUAD * palette, kkint32 palletSize)
Returns true if palette is for a grayscale image.
Definition at line 988 of file BMPImage.cpp.
References KKB::RGBQUAD::rgbGreen.
void RotateDWORD (DWORD & w)
Definition at line 89 of file BMPImage.cpp.
References KKB::BmpImage::DWordParts::c1, KKB::BmpImage::DWordParts::c2, KKB::BmpImage::DWordParts::c3, KKB::BmpImage::DWordParts::c4, and KKB::BmpImage::DWordParts::parts.
Referenced by WriteDWORD().
void RotateLONG (LONG & l)
Definition at line 104 of file BMPImage.cpp.
References KKB::BmpImage::LongParts::c1, KKB::BmpImage::LongParts::c2, KKB::BmpImage::LongParts::c3, KKB::BmpImage::LongParts::c4, and KKB::BmpImage::LongParts::parts.
Referenced by WriteLONG().
void RotateWORD (WORD & w)
Definition at line 76 of file BMPImage.cpp.
References KKB::BmpImage::WordParts::c1, KKB::BmpImage::WordParts::c2, and KKB::BmpImage::WordParts::parts.
Referenced by WriteWORD().
void WriteBYTE (FILE * outFile, BYTE b)
Definition at line 139 of file BMPImage.cpp.
void WriteDWORD (FILE * outFile, DWORD dw)
Definition at line 124 of file BMPImage.cpp.
References RotateDWORD().
void WriteLONG (FILE * outFile, LONG l)
Definition at line 132 of file BMPImage.cpp.
References RotateLONG().
void WriteWORD (FILE * outFile, WORD w)
Definition at line 117 of file BMPImage.cpp.
References RotateWORD().