Pices: MLL::PicesApplication Class Reference
MLL::PicesApplication Class Reference
Base class to All PICES applications.
#include <PicesApplication.h>
Public Member Functions
PicesApplication ()
Constructor for Application class that will start with a default logger(RunLog),.
PicesApplication (const PicesApplication &_application)
Copy Constructor for PicesApplication class.
PicesApplication (KKB::RunLog &_log)
Constructor for PicesApplication class with no parameters.
virtual ~PicesApplication ()
virtual const char * ApplicationName () const
Specify the name of the application.
PicesTrainingConfigurationPtr Config () const
const KKStr & ConfigFileFullPath () const
const KKStr & ConfigFileName () const
DataBasePtr DB ()
DataBaseServerPtr DbServer () const
FileDescPtr FileDesc () const
void FvFactoryProducer (FactoryFVProducerPtr _fvFactoryProducer)
virtual void InitalizeApplication (kkint32 argc, char **argv)
Initialized PicesApplication Instance; 1st method to be called after instance construction.
void PrintStandardHeaderInfo (ostream &o)
Public Member Functions inherited from KKB::Application
Application ()
Constructor for Application class that will start with a default logger(RunLog),.
Application (const Application &_application)
Copy Constructor for Application class.
Application (RunLog &_log)
Constructor for Application class where we already have an existing logger '_log'.
virtual ~Application ()
bool Abort ()
Returns 'true' if application has been aborted.
void Abort (bool _abort)
Used to specify that the application is been aborted.
virtual const char * ApplicationName ()
Specify the name of the application.
void AssignLog (RunLog &_log)
Replaces the Log file to write to.
virtual KKStr BuildDate () const
Protected Member Functions
void ConfigRequired (bool _configRequired)
A derived class would call this method in its version of 'InitalizeApplication' just before calling 'PicesApplication::InitalizeApplication' to let it know that the Training Model Configuration parameter is required.
void DataBaseRequired (bool _dataBaseRequired)
A derived class would call this method in its version of 'InitalizeApplication' just before calling 'PicesApplication::InitalizeApplication'.
void DisplayCommandLineParameters ()
Will display Command Lone parameters that the 'Application' class will manage.
virtual bool ProcessCmdLineParameter (const KKStr &parmSwitch, const KKStr &parmValue)
This method will get called once for each parameter specified in the command line.
Protected Attributes
PicesTrainingConfigurationPtr config
KKStr configFileFullPath
KKStr configFileName
FileDescPtr fileDesc
FactoryFVProducerPtr fvFactoryProducer
Additional Inherited Members
Public Attributes inherited from KKB::Application
RunLog & log
Detailed Description
Base class to All PICES applications.
The base class for all standalone applications.
Author
Kurt Kramer
This class is meant to be a general class that all standalone applications should be inherited from. If provides command line options that are common to all Pices Applications. Supported Command Options:
-Config <Model-Name> The training model configuration file; only the root part needs to be specified; these files can be found in the "$<PicesHomeDir>\Classifier\TrainingModels" directory.
-DataBase This 'Description' references the Description field in the MySQL.cfg file found in "${PicesHomeDir}\Configurations\" directory.
-LogFile <File-Name> File that logger messages (RunLog) are to be written to; if not specified will default to standard-out (cout).
-CmdFile <File-Name> A text file that will contain additional command line options; one of these options could be another "-CmdFile" option.
A derived class must implement the following methods:
ApplicationName Where you return the name of the derived application.
InitalizeApplication Where you implement the initialization code for the derived application. One of the tasks required by this method is to call the base class version of this method "PicesApplication::InitalizeApplication". If you find ant reason that the application may not be started; display an appropriate error message and set the abort field to true by calling "Abort (true)". If you want the base class to require the "-Config" or "-DataBase" parameter then call "ConfigRequired (true)" and/or "DataBaseRequired (true)" before calling "PicesApplication::InitalizeApplication" and check the "Abort()" flag to see if errors were detected.
ProcessCmdLineParameter This method will be called once for each command line parameter and its associated value. If it is one of your parameters you get to process it in this method. If you do not recognize the parameter call the base class version of this method "PicesApplication::ProcessCmdLineParameter".
Definition at line 71 of file PicesApplication.h.
Constructor & Destructor Documentation
PicesApplication::PicesApplication ()
Constructor for Application class that will start with a default logger(RunLog),.
After creating an instance of this class you initialize it by calling InitalizeApplication.
Definition at line 55 of file PicesApplication.cpp.
References MLL::PicesFVProducerFactory::Factory(), fileDesc, fvFactoryProducer, KKB::Application::log, and MLL::FeatureFileIOPices::NewPlanktonFile().
PicesApplication::PicesApplication (const PicesApplication & _application)
Copy Constructor for PicesApplication class.
Parameters
[in] _application PicesApplication instance to copy.
Definition at line 74 of file PicesApplication.cpp.
References config, KKB::Application::log, and MLL::DataBase::Server().
PicesApplication::PicesApplication (KKB::RunLog & _log)
Constructor for PicesApplication class with no parameters.
This constructor is not interested in any command line parameters.
Parameters
[in] _log A reference to a RunLog object.
Definition at line 36 of file PicesApplication.cpp.
References MLL::PicesFVProducerFactory::Factory(), fileDesc, fvFactoryProducer, MLL::PicesVariables::InitializeEnvironment(), KKB::Application::log, and MLL::FeatureFileIOPices::NewPlanktonFile().
PicesApplication::~PicesApplication () virtual
Definition at line 98 of file PicesApplication.cpp.
References config.
Member Function Documentation
const char * PicesApplication::ApplicationName () const virtual
Specify the name of the application.
Definition at line 167 of file PicesApplication.cpp.
Referenced by PrintStandardHeaderInfo().
PicesTrainingConfigurationPtr MLL::PicesApplication::Config () const inline
Definition at line 120 of file PicesApplication.h.
const KKStr& MLL::PicesApplication::ConfigFileFullPath () const inline
Definition at line 122 of file PicesApplication.h.
const KKStr& MLL::PicesApplication::ConfigFileName () const inline
Definition at line 121 of file PicesApplication.h.
void MLL::PicesApplication::ConfigRequired (bool _configRequired) inline protected
A derived class would call this method in its version of 'InitalizeApplication' just before calling 'PicesApplication::InitalizeApplication' to let it know that the Training Model Configuration parameter is required.
Definition at line 138 of file PicesApplication.h.
void MLL::PicesApplication::DataBaseRequired (bool _dataBaseRequired) inline protected
A derived class would call this method in its version of 'InitalizeApplication' just before calling 'PicesApplication::InitalizeApplication'.
If set to true will require that a database connection be established otherwise the application will abort.
Definition at line 147 of file PicesApplication.h.
DataBasePtr PicesApplication::DB ()
Definition at line 284 of file PicesApplication.cpp.
References KKB::Application::log.
DataBaseServerPtr MLL::PicesApplication::DbServer () const inline
Definition at line 123 of file PicesApplication.h.
void PicesApplication::DisplayCommandLineParameters () protected virtual
Will display Command Lone parameters that the 'Application' class will manage.
Derived classes that implement this method need to call their immediate base class version of this method to include these parameters.
Reimplemented from KKB::Application.
Definition at line 244 of file PicesApplication.cpp.
References KKB::endl().
FileDescPtr MLL::PicesApplication::FileDesc () const inline
Definition at line 124 of file PicesApplication.h.
void MLL::PicesApplication::FvFactoryProducer (FactoryFVProducerPtr _fvFactoryProducer) inline
Definition at line 126 of file PicesApplication.h.
void PicesApplication::InitalizeApplication (kkint32 argc, char ** argv) virtual
Initialized PicesApplication Instance; 1st method to be called after instance construction.
See Also
RunLog
ProcessCmdLineParameters
Parameters
[in] argc Number of arguments in argv.
[in] argv List of asciiz strings; one string for each argument.
Reimplemented from KKB::Application.
Definition at line 108 of file PicesApplication.cpp.
References KKB::Application::Abort(), config, configFileFullPath, configFileName, KKB::KKStr::Empty(), KKB::endl(), KKB::Configuration::FormatErrorsWithLineNumbers(), KKB::Configuration::FormatGood(), fvFactoryProducer, KKMLL::TrainingConfiguration2::FvFactoryProducer(), KKB::RunLog::Level(), MLL::PicesTrainingConfiguration::Load(), KKB::Application::log, MLL::DataBase::Server(), and MLL::DataBase::Valid().
void PicesApplication::PrintStandardHeaderInfo (ostream & o)
Definition at line 295 of file PicesApplication.cpp.
References ApplicationName(), KKB::Application::BuildDate(), config, configFileFullPath, configFileName, KKB::KKStr::Empty(), KKB::endl(), fvFactoryProducer, KKMLL::TrainingConfiguration2::ModelParameterCmdLine(), KKMLL::TrainingConfiguration2::ModelTypeStr(), KKMLL::FactoryFVProducer::Name(), KKMLL::TrainingConfiguration2::NumHierarchialLevels(), KKB::osGetFileDateTime(), KKB::osGetHostName(), KKB::osGetLocalDateTime(), KKB::osGetUserName(), KKMLL::TrainingConfiguration2::OtherClass(), and MLL::DataBase::ServerDescription().
bool PicesApplication::ProcessCmdLineParameter (const KKStr & parmSwitch, const KKStr & parmValue) protected virtual
This method will get called once for each parameter specified in the command line.
Derived classes should define this method to intercept parameters that they are interested in. Parameters are treated as pairs, Switched and Values where switches have a leading dash("-"). The CmdLineExpander class will be used to expand any "-CmdFile" parameters.
Parameters
[in] parmSwitch The fill switch parameter.
[in] parmValue Any value parameter that followed the switch parameter.
Reimplemented from KKB::Application.
Definition at line 175 of file PicesApplication.cpp.
References KKB::KKStr::EqualIgnoreCase().
Member Data Documentation
PicesTrainingConfigurationPtr MLL::PicesApplication::config protected
Definition at line 175 of file PicesApplication.h.
Referenced by InitalizeApplication(), PicesApplication(), PrintStandardHeaderInfo(), and ~PicesApplication().
KKStr MLL::PicesApplication::configFileFullPath protected
Definition at line 177 of file PicesApplication.h.
Referenced by InitalizeApplication(), and PrintStandardHeaderInfo().
KKStr MLL::PicesApplication::configFileName protected
Definition at line 176 of file PicesApplication.h.
Referenced by InitalizeApplication(), and PrintStandardHeaderInfo().
FileDescPtr MLL::PicesApplication::fileDesc protected
Definition at line 178 of file PicesApplication.h.
Referenced by PicesApplication().
FactoryFVProducerPtr MLL::PicesApplication::fvFactoryProducer protected
Definition at line 179 of file PicesApplication.h.
Referenced by InitalizeApplication(), PicesApplication(), and PrintStandardHeaderInfo().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/PicesApplication.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/PicesApplication.cpp