Pices: D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ChainHash.cpp File Reference
ChainHash.cpp File Reference
#include "FirstIncludes.h"
#include <fstream>
#include <iostream>
#include <list>
#include <string.h>
#include <string>
#include <vector>
#include "MemoryDebug.h"
#include "BasicTypes.h"
#include "ChainHash.h"
#include "FeatureNumList.h"
Functions
void CompareTwoGroups (vector< KKStr > &g1, vector< KKStr > &g2, std::ostream &r)
void CompareTwoSetsOfGroups (vector< vector< KKStr > > &groups1, vector< vector< KKStr > > &groups2, std::ostream &r)
vector< KKStr > GetGroupForExample (vector< vector< KKStr > > &groups, KKStr example)
int32 LookUpExampleInGroup (vector< KKStr > &g, KKStr i)
Function Documentation
void CompareTwoGroups (vector< KKStr > & g1, vector< KKStr > & g2, std::ostream & r)
Definition at line 252 of file ChainHash.cpp.
References KKU::endl(), and LookUpExampleInGroup().
Referenced by CompareTwoSetsOfGroups().
void CompareTwoSetsOfGroups (vector< vector< KKStr > > & groups1, vector< vector< KKStr > > & groups2, std::ostream & r)
Definition at line 289 of file ChainHash.cpp.
References CompareTwoGroups(), and GetGroupForExample().
vector<KKStr> GetGroupForExample (vector< vector< KKStr > > & groups, KKStr example)
Definition at line 212 of file ChainHash.cpp.
Referenced by CompareTwoSetsOfGroups().
int32 LookUpExampleInGroup (vector< KKStr > & g, KKStr i)
Definition at line 234 of file ChainHash.cpp.
Referenced by CompareTwoGroups().