Pices: D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/UsfCasCor_UsingDouble.cpp File Reference
UsfCasCor_UsingDouble.cpp File Reference
#include "FirstIncludes.h"
#include <stdarg.h>
#include <stdio.h>
#include <math.h>
#include <ctype.h>
#include <signal.h>
#include <time.h>
#include <string.h>
#include <stdlib.h>
#include <iostream>
#include <fstream>
#include "MemoryDebug.h"
#include "BasicTypes.h"
#include "OSservices.h"
#include "XmlStream.h"
#include "ImageClass.h"
#include "FeatureVector.h"
#include "ClassProb.h"
#include "UsfCasCor.h"
Macros
#define BEGIN_CONNECTION_STRING "# Connections\n"
#define BEGIN_INPUT_WEIGHTS_STRING "# Input Weights\n"
#define BEGIN_OUTPUT_WEIGHTS_STRING "# Output Weights\n"
#define BEGIN_PARAMETER_STRING "# Parameters\n"
#define END_CONNECTION_STRING "# End Connections\n"
#define END_INPUT_WEIGHTS_STRING "# End Input Weights\n"
#define END_OUTPUT_WEIGHTS_STRING "# End Output Weights\n"
#define END_PARAMETER_STRING "# End Parameters\n"
#define EOL '\0'
Functions
const char * _ (const char *str)
template<typename T >
ostream & ArrayCommaDelimited (ostream &o, T *a, int N)
void CHECK_INTERRUPT (void)
char * GetDsiplayableTime ()
long long GetLocalDateTime ()
KKU::int32 GetProcessId ()
char * index (char *str, int c)
XmlTagPtr ReadFloatArrayUntilEndTag (istream &i, double *A, int len)
XmlTagPtr ReadIntArrayUntilEndTag (istream &i, int *A, int len)
char ReadNextToken (istream &i, KKStr &token, const char *del)
void SkipToStartOfTag (istream &i)
void SkipWhiteSpace (istream &i)
void TRAP_CONTROL_C (int sig)
void WriteXmlArrayFloat (const char *name, ostream &o, int len, double *A)
void WriteXmlArrayFloat2D (const char *name, ostream &o, int height, int width, double **A)
void WriteXmlArrayFloat2DVarying (const char *name, ostream &o, int height, int *widths, double **A)
void WriteXmlArrayInt (const char *name, ostream &o, int len, int *A)
Variables
int daysYTDforMonth []
Macro Definition Documentation
#define BEGIN_CONNECTION_STRING "# Connections\n"
Definition at line 1458 of file UsfCasCor_UsingDouble.cpp.
#define BEGIN_INPUT_WEIGHTS_STRING "# Input Weights\n"
Definition at line 1460 of file UsfCasCor_UsingDouble.cpp.
#define BEGIN_OUTPUT_WEIGHTS_STRING "# Output Weights\n"
Definition at line 1462 of file UsfCasCor_UsingDouble.cpp.
#define BEGIN_PARAMETER_STRING "# Parameters\n"
Definition at line 1456 of file UsfCasCor_UsingDouble.cpp.
#define END_CONNECTION_STRING "# End Connections\n"
Definition at line 1459 of file UsfCasCor_UsingDouble.cpp.
#define END_INPUT_WEIGHTS_STRING "# End Input Weights\n"
Definition at line 1461 of file UsfCasCor_UsingDouble.cpp.
#define END_OUTPUT_WEIGHTS_STRING "# End Output Weights\n"
Definition at line 1463 of file UsfCasCor_UsingDouble.cpp.
#define END_PARAMETER_STRING "# End Parameters\n"
Definition at line 1457 of file UsfCasCor_UsingDouble.cpp.
#define EOL '\0'
Definition at line 1115 of file UsfCasCor_UsingDouble.cpp.
Function Documentation
const char* _ (const char * str)
Definition at line 225 of file UsfCasCor_UsingDouble.cpp.
template<typename T > ostream& ArrayCommaDelimited (ostream & o, T * a, int N)
Definition at line 1467 of file UsfCasCor_UsingDouble.cpp.
References x.
void CHECK_INTERRUPT (void)
Definition at line 1086 of file UsfCasCor_UsingDouble.cpp.
char* GetDsiplayableTime ()
long long GetLocalDateTime ()
KKU::int32 GetProcessId ()
char* index (char * str, int c)
XmlTagPtr ReadFloatArrayUntilEndTag (istream & i, double * A, int len)
Definition at line 1778 of file UsfCasCor_UsingDouble.cpp.
References ReadNextToken(), SkipWhiteSpace(), and KKU::KKStr::ToFloat().
XmlTagPtr ReadIntArrayUntilEndTag (istream & i, int * A, int len)
Definition at line 1817 of file UsfCasCor_UsingDouble.cpp.
References ReadNextToken(), SkipWhiteSpace(), and KKU::KKStr::ToInt().
char ReadNextToken (istream & i, KKStr & token, const char * del)
Will return token less leading and trailing white space. The chracter in 'del' that ended the token field will be consumed. If the start of a tag ('<') is detected will treat as end of line.
Returns
The delimiter chracter that terminated the token; or 0 of end of file or start of new tag detected.
Definition at line 1749 of file UsfCasCor_UsingDouble.cpp.
References KKU::KKStr::Append(), SkipWhiteSpace(), and KKU::KKStr::TrimRight().
void SkipToStartOfTag (istream & i)
Definition at line 1724 of file UsfCasCor_UsingDouble.cpp.
void SkipWhiteSpace (istream & i)
Definition at line 1735 of file UsfCasCor_UsingDouble.cpp.
void TRAP_CONTROL_C (int sig)
Definition at line 1099 of file UsfCasCor_UsingDouble.cpp.
void WriteXmlArrayFloat (const char * name, ostream & o, int len, double * A)
Definition at line 1480 of file UsfCasCor_UsingDouble.cpp.
References KKU::endl(), and x.
void WriteXmlArrayFloat2D (const char * name, ostream & o, int height, int width, double ** A)
Definition at line 1499 of file UsfCasCor_UsingDouble.cpp.
References KKU::endl().
void WriteXmlArrayFloat2DVarying (const char * name, ostream & o, int height, int * widths, double ** A)
Definition at line 1526 of file UsfCasCor_UsingDouble.cpp.
References KKU::endl().
void WriteXmlArrayInt (const char * name, ostream & o, int len, int * A)
Definition at line 1552 of file UsfCasCor_UsingDouble.cpp.
References KKU::endl(), and x.
Variable Documentation
int daysYTDforMonth[]
Initial value:
=
   {0,  31,  59,  90, 120, 151, 181, 212, 243, 273, 304, 334, 365}
Definition at line 3849 of file UsfCasCor_UsingDouble.cpp.