Pices: D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/UsfCasCor.cpp File Reference
UsfCasCor.cpp File Reference
#include "FirstIncludes.h"
#include <stdarg.h>
#include <stdio.h>
#include <math.h>
#include <ctype.h>
#include <signal.h>
#include <time.h>
#include <string.h>
#include <stdlib.h>
#include <iostream>
#include <fstream>
#include "MemoryDebug.h"
#include "BasicTypes.h"
#include "OSservices.h"
#include "XmlStream.h"
#include "MLClass.h"
#include "FeatureVector.h"
#include "ClassProb.h"
#include "UsfCasCor.h"
Macros
#define BEGIN_CONNECTION_STRING "# Connections\n"
#define BEGIN_INPUT_WEIGHTS_STRING "# Input Weights\n"
#define BEGIN_OUTPUT_WEIGHTS_STRING "# Output Weights\n"
#define BEGIN_PARAMETER_STRING "# Parameters\n"
#define END_CONNECTION_STRING "# End Connections\n"
#define END_INPUT_WEIGHTS_STRING "# End Input Weights\n"
#define END_OUTPUT_WEIGHTS_STRING "# End Output Weights\n"
#define END_PARAMETER_STRING "# End Parameters\n"
#define EOL '\0'
Functions
const char * _ (const char *str)
template<typename T >
ostream & ArrayCommaDelimited (ostream &o, T *a, int N)
void CHECK_INTERRUPT (void)
char * GetDsiplayableTime ()
long long GetLocalDateTime ()
KKU::int32 GetProcessId ()
char * index (char *str, int c)
XmlTagPtr ReadFloatArrayUntilEndTag (istream &i, float *A, int len)
XmlTagPtr ReadIntArrayUntilEndTag (istream &i, int *A, int len)
char ReadNextToken (istream &i, KKStr &token, const char *del)
void SkipToStartOfTag (istream &i)
void SkipWhiteSpace (istream &i)
void TRAP_CONTROL_C (int sig)
void WriteXmlArrayFloat (const char *name, ostream &o, int len, float *A)
void WriteXmlArrayFloat2D (const char *name, ostream &o, int height, int width, float **A)
void WriteXmlArrayFloat2DVarying (const char *name, ostream &o, int height, int *widths, float **A)
void WriteXmlArrayInt (const char *name, ostream &o, int len, int *A)
Variables
int daysYTDforMonth []
Macro Definition Documentation
#define BEGIN_CONNECTION_STRING "# Connections\n"
Definition at line 1493 of file UsfCasCor.cpp.
#define BEGIN_INPUT_WEIGHTS_STRING "# Input Weights\n"
Definition at line 1495 of file UsfCasCor.cpp.
#define BEGIN_OUTPUT_WEIGHTS_STRING "# Output Weights\n"
Definition at line 1497 of file UsfCasCor.cpp.
#define BEGIN_PARAMETER_STRING "# Parameters\n"
Definition at line 1491 of file UsfCasCor.cpp.
#define END_CONNECTION_STRING "# End Connections\n"
Definition at line 1494 of file UsfCasCor.cpp.
#define END_INPUT_WEIGHTS_STRING "# End Input Weights\n"
Definition at line 1496 of file UsfCasCor.cpp.
#define END_OUTPUT_WEIGHTS_STRING "# End Output Weights\n"
Definition at line 1498 of file UsfCasCor.cpp.
#define END_PARAMETER_STRING "# End Parameters\n"
Definition at line 1492 of file UsfCasCor.cpp.
#define EOL '\0'
Definition at line 1148 of file UsfCasCor.cpp.
Referenced by MLL::UsfCasCor::strdncase().
Function Documentation
const char* _ (const char * str)
Definition at line 225 of file UsfCasCor.cpp.
template<typename T > ostream& ArrayCommaDelimited (ostream & o, T * a, int N)
Definition at line 1502 of file UsfCasCor.cpp.
References x.
void CHECK_INTERRUPT (void)
Definition at line 1119 of file UsfCasCor.cpp.
char * GetDsiplayableTime ()
Definition at line 3934 of file UsfCasCor.cpp.
long long GetLocalDateTime ()
Definition at line 3889 of file UsfCasCor.cpp.
References daysYTDforMonth.
int GetProcessId ()
Definition at line 3876 of file UsfCasCor.cpp.
References KKU::osGetProcessId().
Referenced by MLL::UsfCasCor::setup_network().
char * index (char * str, int c)
Definition at line 3950 of file UsfCasCor.cpp.
Referenced by KKU::KKStrListIndexed::Add(), MLL::ClassIndexList::AddClass(), PicesCommander.ClassStatSortedList::AddCount(), PicesCommander.ClassStatSortedList::AddOne(), MLL::FeatureEncoder::CreateEncodedFeatureVector(), KKU::KKStrListIndexed::Delete(), MLL::ChainHash< T >::find(), SVM289_MFS::Cache::get_data(), SVM289_BFS::Cache::get_data(), SVM233::Cache::get_data(), SVM233::SVR_Q::get_Q(), SVM289_MFS::SVR_Q::get_Q(), SVM289_BFS::SVR_Q::get_Q(), MLL::ClassIndexList::GetClassIndex(), MLL::ChainHashNode::getIndex(), MLL::ChainHash< T >::insert(), PicesInterface::PicesClassList::LookUpIndex(), MLL::ClassIndexList::ParseClassIndexList(), MLL::FeatureVectorList::PrintClassStatistics(), MLL::FeatureVectorList::PrintClassStatisticsHTML(), MLL::ChainHash< T >::remove(), MLL::Orderings::Save(), SVM289_MFS::svm_cross_validation(), SVM289_BFS::svm_cross_validation(), SVM233::SVR_Q::SVR_Q(), SVM289_MFS::SVR_Q::SVR_Q(), SVM289_BFS::SVR_Q::SVR_Q(), SVM233::SVR_Q::swap_index(), SVM289_MFS::SVR_Q::swap_index(), SVM289_BFS::SVR_Q::swap_index(), SVM233::SVR_Q::~SVR_Q(), SVM289_MFS::SVR_Q::~SVR_Q(), and SVM289_BFS::SVR_Q::~SVR_Q().
XmlTagPtr ReadFloatArrayUntilEndTag (istream & i, float * A, int len)
Definition at line 1813 of file UsfCasCor.cpp.
References ReadNextToken(), SkipWhiteSpace(), and KKU::KKStr::ToFloat().
XmlTagPtr ReadIntArrayUntilEndTag (istream & i, int * A, int len)
Definition at line 1852 of file UsfCasCor.cpp.
References ReadNextToken(), SkipWhiteSpace(), and KKU::KKStr::ToInt().
char ReadNextToken (istream & i, KKStr & token, const char * del)
Will return token less leading and trailing white space. The chracter in 'del' that ended the token field will be consumed. If the start of a tag ('<') is detected will treat as end of line.
Returns
The delimiter chracter that terminated the token; or 0 of end of file or start of new tag detected.
Definition at line 1784 of file UsfCasCor.cpp.
References KKU::KKStr::Append(), SkipWhiteSpace(), and KKU::KKStr::TrimRight().
Referenced by ReadFloatArrayUntilEndTag(), and ReadIntArrayUntilEndTag().
void SkipToStartOfTag (istream & i)
Definition at line 1759 of file UsfCasCor.cpp.
void SkipWhiteSpace (istream & i)
Definition at line 1770 of file UsfCasCor.cpp.
Referenced by ReadFloatArrayUntilEndTag(), ReadIntArrayUntilEndTag(), and ReadNextToken().
void TRAP_CONTROL_C (int sig)
Definition at line 1132 of file UsfCasCor.cpp.
void WriteXmlArrayFloat (const char * name, ostream & o, int len, float * A)
Definition at line 1515 of file UsfCasCor.cpp.
References KKU::endl(), and x.
void WriteXmlArrayFloat2D (const char * name, ostream & o, int height, int width, float ** A)
Definition at line 1534 of file UsfCasCor.cpp.
References KKU::endl().
void WriteXmlArrayFloat2DVarying (const char * name, ostream & o, int height, int * widths, float ** A)
Definition at line 1561 of file UsfCasCor.cpp.
References KKU::endl().
void WriteXmlArrayInt (const char * name, ostream & o, int len, int * A)
Definition at line 1587 of file UsfCasCor.cpp.
References KKU::endl(), and x.
Variable Documentation
int daysYTDforMonth[]
Initial value:
=
   {0,  31,  59,  90, 120, 151, 181, 212, 243, 273, 304, 334, 365}
Definition at line 3883 of file UsfCasCor.cpp.
Referenced by KKU::DateType::DaysYTDforMonth(), and GetLocalDateTime().