var annotated_dup =
[
    [ "FeatureSelectionApp", "d2/d36/namespace_feature_selection_app.html", "d2/d36/namespace_feature_selection_app" ],
    [ "GradeTrainingModel", "dc/de5/namespace_grade_training_model.html", "dc/de5/namespace_grade_training_model" ],
    [ "ImageExtractionManager", "d0/d9d/namespace_image_extraction_manager.html", "d0/d9d/namespace_image_extraction_manager" ],
    [ "JobManagment", "df/ded/namespace_job_managment.html", "df/ded/namespace_job_managment" ],
    [ "KKB", "dc/d98/namespace_k_k_b.html", "dc/d98/namespace_k_k_b" ],
    [ "KKMLL", "d1/d5c/namespace_k_k_m_l_l.html", "d1/d5c/namespace_k_k_m_l_l" ],
    [ "MLL", "d7/dcc/namespace_m_l_l.html", "d7/dcc/namespace_m_l_l" ],
    [ "PicesCommander", "d7/d53/namespace_pices_commander.html", "d7/d53/namespace_pices_commander" ],
    [ "PicesInterface", "d3/d44/namespace_pices_interface.html", "d3/d44/namespace_pices_interface" ],
    [ "SipperDiskUtilities", "d0/dae/namespace_sipper_disk_utilities.html", "d0/dae/namespace_sipper_disk_utilities" ],
    [ "SipperFile", "dd/dd4/namespace_sipper_file.html", "dd/dd4/namespace_sipper_file" ],
    [ "SipperFileViewer", "d7/d8c/namespace_sipper_file_viewer.html", "d7/d8c/namespace_sipper_file_viewer" ],
    [ "SVM233", "de/da3/namespace_s_v_m233.html", "de/da3/namespace_s_v_m233" ],
    [ "SVM289_BFS", "dd/d33/namespace_s_v_m289___b_f_s.html", "dd/d33/namespace_s_v_m289___b_f_s" ],
    [ "SVM289_MFS", "d4/d6f/namespace_s_v_m289___m_f_s.html", "d4/d6f/namespace_s_v_m289___m_f_s" ],
    [ "AccuracyComparison", "de/dde/class_accuracy_comparison.html", "de/dde/class_accuracy_comparison" ],
    [ "AccuracyNormComparison", "dc/d51/class_accuracy_norm_comparison.html", "dc/d51/class_accuracy_norm_comparison" ],
    [ "CAboutDlg", "de/d70/class_c_about_dlg.html", "de/d70/class_c_about_dlg" ],
    [ "CImageExtractionWindowsApp", "d9/def/class_c_image_extraction_windows_app.html", "d9/def/class_c_image_extraction_windows_app" ],
    [ "CImageExtractionWindowsDlg", "d2/d9c/class_c_image_extraction_windows_dlg.html", "d2/d9c/class_c_image_extraction_windows_dlg" ],
    [ "DeltaProbAccuarcyComparison", "d6/d7d/class_delta_prob_accuarcy_comparison.html", "d6/d7d/class_delta_prob_accuarcy_comparison" ],
    [ "DeltaTestProbAccuarcyComparison", "dc/ddf/class_delta_test_prob_accuarcy_comparison.html", "dc/ddf/class_delta_test_prob_accuarcy_comparison" ],
    [ "GradeComparison", "d0/d3c/class_grade_comparison.html", "d0/d3c/class_grade_comparison" ],
    [ "ProcessingTimeComparison", "d8/d1e/class_processing_time_comparison.html", "d8/d1e/class_processing_time_comparison" ],
    [ "SplitRec", "db/d80/struct_split_rec.html", "db/d80/struct_split_rec" ],
    [ "SvmParmsComparison", "d6/d3c/class_svm_parms_comparison.html", "d6/d3c/class_svm_parms_comparison" ],
    [ "tagTHREADNAME_INFO", "d0/df5/structtag_t_h_r_e_a_d_n_a_m_e___i_n_f_o.html", "d0/df5/structtag_t_h_r_e_a_d_n_a_m_e___i_n_f_o" ],
    [ "TestAccuracyComparison", "db/d4d/class_test_accuracy_comparison.html", "db/d4d/class_test_accuracy_comparison" ],
    [ "TestAccuracyNormComparison", "dc/d72/class_test_accuracy_norm_comparison.html", "dc/d72/class_test_accuracy_norm_comparison" ],
    [ "TestGradeComparison", "dc/df5/class_test_grade_comparison.html", "dc/df5/class_test_grade_comparison" ],
    [ "Variables", "db/d18/class_variables.html", null ],
    [ "XmlFactoryModelOldSVM", "de/d8b/class_xml_factory_model_old_s_v_m.html", "de/d8b/class_xml_factory_model_old_s_v_m" ],
    [ "XmlFactoryTrainingClass", "de/d26/class_xml_factory_training_class.html", "de/d26/class_xml_factory_training_class" ]
];