Pices: PicesInterface::Cruise Class Reference
PicesInterface::Cruise Class Reference
#include <Cruise.h>
Public Types
typedef System::DateTime DateTime
Public Member Functions
Cruise ()
Cruise (String^ fileName)
void Load (String^ fileName)
void Save (String^ baseDir)
Properties
DateTime^ DateEnd [get, set]
DateTime^ DateStart [get, set]
String^ Location [get, set]
String^ Name [get, set]
String^ Notes [get, set]
String^ Objective [get, set]
String^ Principal [get, set]
String^ ResearchOrg [get, set]
Detailed Description
Definition at line 14 of file Cruise.h.
Member Typedef Documentation
typedef System::DateTime PicesInterface::Cruise::DateTime
Definition at line 17 of file Cruise.h.
Constructor & Destructor Documentation
Cruise::Cruise ()
Definition at line 29 of file Cruise.cpp.
Cruise::Cruise (String^ fileName)
Definition at line 42 of file Cruise.cpp.
References Load().
Member Function Documentation
void Cruise::Load (String^ fileName)
Definition at line 102 of file Cruise.cpp.
References x.
Referenced by Cruise().
void Cruise::Save (String^ baseDir)
Definition at line 62 of file Cruise.cpp.
References PicesInterface::OSservices::AddSlash(), and PicesInterface::OSservices::CreateDirectoryPath().
Property Documentation
DateTime^ PicesInterface::Cruise::DateEnd get set
Definition at line 29 of file Cruise.h.
DateTime^ PicesInterface::Cruise::DateStart get set
Definition at line 28 of file Cruise.h.
String^ PicesInterface::Cruise::Location get set
Definition at line 24 of file Cruise.h.
String^ PicesInterface::Cruise::Name get set
Definition at line 23 of file Cruise.h.
Referenced by PicesInterface::CruiseList::LookUpByName().
String^ PicesInterface::Cruise::Notes get set
Definition at line 30 of file Cruise.h.
String^ PicesInterface::Cruise::Objective get set
Definition at line 25 of file Cruise.h.
String^ PicesInterface::Cruise::Principal get set
Definition at line 26 of file Cruise.h.
String^ PicesInterface::Cruise::ResearchOrg get set
Definition at line 27 of file Cruise.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/Cruise.h
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/Cruise.cpp