Pices: MLL::ClassAssignments Class Reference
MLL::ClassAssignments Class Reference
Binds MLClass objects to the appropriate number that the Learning Algorithm expects.
#include <ClassAssignments.h>
Public Member Functions
ClassAssignments (RunLog &_log)
ClassAssignments (const MLClassConstList &classes, RunLog &_log)
Creates assignment for all classes in 'classes.
void AddMLClass (MLClassConstPtr mlClass, int16 num)
MLClassConstPtr GetMLClass (int16 num)
MLClassConstPtr GetMLClassByIndex (size_t idx)
MLClassList GetMLClasses (int16 num) const
int16 GetNumForClass (MLClassConstPtr mlClass) const
VectorShort GetUniqueListOfAssignments () const
void Load (const KKStr &fileName, bool &successful)
int32 MemoryConsumedEstimated () const
void ParseToString (const KKStr &_toString)
Loads class assignments from string that was originally generated by ToString.
void Save (const KKStr &fileName, bool &successful)
KKStr ToString () const
Additional Inherited Members
Public Attributes inherited from std::multimap< K, T >
T elements
STL member.
K keys
STL member.
Detailed Description
Binds MLClass objects to the appropriate number that the Learning Algorithm expects.
Author
Kurt Kramer
This class will bind MLClass objects to the appropriate num that the learning algorithm knows for this class. When originally implementing this system, this info was kept in the MLClass object. This would cause problems when doing multi-level classification. The same MLClass might be known to the L.A. as one number in one level and another number in a different level. This caused us to have to maintain a separate instantiation of these classes on the SvmModel objects.
It is sub-classed from multimap<int16, MLClassConstPtr>. This allows for fast lookup by number. There is also a secondary index by MLClass. This allows us to do a fast lookup by class.
Definition at line 44 of file ClassAssignments.h.
Constructor & Destructor Documentation
MLL::ClassAssignments::ClassAssignments (RunLog & _log)
Referenced by MemoryConsumedEstimated().
MLL::ClassAssignments::ClassAssignments (const MLClassConstList & classes, RunLog & _log)
Creates assignment for all classes in 'classes.
Constructs a list assigning a number to each class sequentially from 'classes'. Use this constructor if each class is treated uniquely by the learning algorithm.
Parameters
[in] classes,List of classes to make assignments for.
[in,out] _log,Run log to write messages to
Member Function Documentation
void ClassAssignments::AddMLClass (MLClassConstPtr mlClass, int16 num)
Definition at line 63 of file ClassAssignments.cpp.
References KKU::endl(), and KKU::RunLog::Level().
Referenced by Load(), and ParseToString().
MLClassConstPtr ClassAssignments::GetMLClass (int16 num)
Definition at line 87 of file ClassAssignments.cpp.
Referenced by MLL::SVMModel::ProbabilitiesByClass().
MLClassConstPtr ClassAssignments::GetMLClassByIndex (size_t idx)
Definition at line 150 of file ClassAssignments.cpp.
References KKU::endl(), and KKU::osWaitForEnter().
Referenced by MLL::SVMModel::Write().
MLClassList ClassAssignments::GetMLClasses (int16 num) const
Definition at line 100 of file ClassAssignments.cpp.
References MLL::MLClassList::PushOnBack().
int16 ClassAssignments::GetNumForClass (MLClassConstPtr mlClass) const
Definition at line 174 of file ClassAssignments.cpp.
Referenced by MLL::FeatureEncoder::Compress(), MLL::BitReduction::compress(), Load(), and MLL::SVMModel::RetrieveCrossProbTable().
VectorShort ClassAssignments::GetUniqueListOfAssignments () const
Definition at line 117 of file ClassAssignments.cpp.
void ClassAssignments::Load (const KKStr & fileName, bool & successful)
Definition at line 189 of file ClassAssignments.cpp.
References AddMLClass(), MLL::MLClass::CreateNewMLClass(), KKU::endl(), KKU::KKStr::ExtractToken2(), KKU::KKStr::ExtractTokenInt(), GetNumForClass(), KKU::RunLog::Level(), KKU::osFOPEN(), KKU::KKStr::Str(), KKU::KKStr::TrimLeft(), and KKU::KKStr::TrimRight().
int32 ClassAssignments::MemoryConsumedEstimated () const
Definition at line 53 of file ClassAssignments.cpp.
References ClassAssignments().
Referenced by MLL::ModelOldSVM::MemoryConsumedEstimated(), and MLL::SVMModel::MemoryConsumedEstimated().
void ClassAssignments::ParseToString (const KKStr & _toString)
Loads class assignments from string that was originally generated by ToString.
Parameters
[in] _toString,KKStr containing class assignments info, will expect to be formated the way ToString() creates them.
Definition at line 288 of file ClassAssignments.cpp.
References AddMLClass(), MLL::MLClass::CreateNewMLClass(), KKU::KKStr::Empty(), KKU::KKStr::ExtractToken(), and KKU::KKStr::ExtractTokenInt().
void ClassAssignments::Save (const KKStr & fileName, bool & successful)
Definition at line 244 of file ClassAssignments.cpp.
References KKU::endl(), KKU::RunLog::Level(), and KKU::KKStr::Str().
KKStr ClassAssignments::ToString () const
Definition at line 264 of file ClassAssignments.cpp.
Referenced by MLL::SVMModel::Write().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ClassAssignments.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ClassAssignments.cpp