Pices: SipperHardware::SipperHeaderRec Class Reference
SipperHardware::SipperHeaderRec Class Reference
#include <SipperHeaderRec.h>
Public Types
typedef SipperHeaderRec * SipperHeaderRecPtr
typedef KKU::uint32 uint32
Public Member Functions
SipperHeaderRec ()
SipperHeaderRec (const SipperHeaderRec &_headerRec)
~SipperHeaderRec ()
void AirTemp (KKStr _airTemp)
KKStr AirTemp () const
void CruiseDateEnd (DateType _cruiseDateEnd)
DateType CruiseDateEnd () const
void CruiseDateStart (DateType _cruiseDateStart)
DateType CruiseDateStart () const
void CruiseLocation (KKStr _cruiseLocation)
KKStr CruiseLocation () const
void CtdExt0Code (const KKStr &_ctdExt0Code)
KKStr CtdExt0Code () const
void CtdExt1Code (const KKStr &_ctdExt1Code)
KKStr CtdExt1Code () const
void CtdExt2Code (const KKStr &_ctdExt2Code)
KKStr CtdExt2Code () const
void CtdExt3Code (const KKStr &_ctdExt3Code)
KKStr CtdExt3Code () const
void DeploymentVehicle (KKStr _deploymentVehicle)
KKStr DeploymentVehicle () const
KKStr HeaderStr ()
InstrumentPtr InclinationMeter (uint32 inclinationSerailPort) const
void Latitude (double _latitude)
double Latitude () const
void Longitude (double _longitude)
double Longitude () const
void Objective (KKStr _objective)
KKStr Objective () const
SipperHeaderRec & operator= (const SipperHeaderRec &right)
void ParseHeaderStr (const KKStr &s)
const PortAssignmentList & PortAssignments () const
void Principal (KKStr _principal)
KKStr Principal () const
void ProcessNameAndDataStrings (const KKStr &fieldName, const KKStr &fieldValue, bool &found)
void ResearchOrg (KKStr _researchOrg)
KKStr ResearchOrg () const
void Save (ostream &w)
void ScanRate (int32 _scanRate)
int32 ScanRate () const
void SeaConditions (KKStr _seaConditions)
KKStr SeaConditions () const
InstrumentPtr SerialPortAssignment (uint32 serialPort) const
const KKStr & SerialPortDesc (uint32 serialPortNum) const
const KKStr & SerialPortShortName (uint32 serialPortNum) const
void SipperFileName (KKStr _sipperFileName)
KKStr SipperFileName () const
void WaveHeight (KKStr _waveHeight)
KKStr WaveHeight () const
void WeatherConditions (KKStr _weatherConditions)
KKStr WeatherConditions () const
Static Public Attributes
static const int32 MaxHeaderLen = 456
static const int32 MaxSipperFileNameLen = 30
Detailed Description
Definition at line 55 of file SipperHeaderRec.h.
Member Typedef Documentation
typedef SipperHeaderRec* SipperHardware::SipperHeaderRec::SipperHeaderRecPtr
Definition at line 58 of file SipperHeaderRec.h.
typedef KKU::uint32 SipperHardware::SipperHeaderRec::uint32
Definition at line 59 of file SipperHeaderRec.h.
Constructor & Destructor Documentation
SipperHeaderRec::SipperHeaderRec ()
Definition at line 80 of file SipperHeaderRec.cpp.
SipperHeaderRec::SipperHeaderRec (const SipperHeaderRec & _headerRec)
Definition at line 108 of file SipperHeaderRec.cpp.
References x.
SipperHeaderRec::~SipperHeaderRec ()
Definition at line 143 of file SipperHeaderRec.cpp.
Member Function Documentation
void SipperHardware::SipperHeaderRec::AirTemp (KKStr _airTemp) inline
Definition at line 98 of file SipperHeaderRec.h.
KKStr SipperHardware::SipperHeaderRec::AirTemp () const inline
Definition at line 120 of file SipperHeaderRec.h.
void SipperHardware::SipperHeaderRec::CruiseDateEnd (DateType _cruiseDateEnd) inline
Definition at line 93 of file SipperHeaderRec.h.
DateType SipperHardware::SipperHeaderRec::CruiseDateEnd () const inline
Definition at line 115 of file SipperHeaderRec.h.
void SipperHardware::SipperHeaderRec::CruiseDateStart (DateType _cruiseDateStart) inline
Definition at line 92 of file SipperHeaderRec.h.
DateType SipperHardware::SipperHeaderRec::CruiseDateStart () const inline
Definition at line 114 of file SipperHeaderRec.h.
void SipperHardware::SipperHeaderRec::CruiseLocation (KKStr _cruiseLocation) inline
Definition at line 88 of file SipperHeaderRec.h.
KKStr SipperHardware::SipperHeaderRec::CruiseLocation () const inline
Definition at line 110 of file SipperHeaderRec.h.
void SipperHardware::SipperHeaderRec::CtdExt0Code (const KKStr & _ctdExt0Code) inline
Definition at line 104 of file SipperHeaderRec.h.
KKStr SipperHardware::SipperHeaderRec::CtdExt0Code () const inline
Definition at line 126 of file SipperHeaderRec.h.
void SipperHardware::SipperHeaderRec::CtdExt1Code (const KKStr & _ctdExt1Code) inline
Definition at line 105 of file SipperHeaderRec.h.
KKStr SipperHardware::SipperHeaderRec::CtdExt1Code () const inline
Definition at line 127 of file SipperHeaderRec.h.
void SipperHardware::SipperHeaderRec::CtdExt2Code (const KKStr & _ctdExt2Code) inline
Definition at line 106 of file SipperHeaderRec.h.
KKStr SipperHardware::SipperHeaderRec::CtdExt2Code () const inline
Definition at line 128 of file SipperHeaderRec.h.
void SipperHardware::SipperHeaderRec::CtdExt3Code (const KKStr & _ctdExt3Code) inline
Definition at line 107 of file SipperHeaderRec.h.
KKStr SipperHardware::SipperHeaderRec::CtdExt3Code () const inline
Definition at line 129 of file SipperHeaderRec.h.
void SipperHardware::SipperHeaderRec::DeploymentVehicle (KKStr _deploymentVehicle) inline
Definition at line 94 of file SipperHeaderRec.h.
KKStr SipperHardware::SipperHeaderRec::DeploymentVehicle () const inline
Definition at line 116 of file SipperHeaderRec.h.
KKStr SipperHeaderRec::HeaderStr ()
Definition at line 195 of file SipperHeaderRec.cpp.
References KKU::StrFormatDouble(), KKU::StrFormatInt(), and x.
InstrumentPtr SipperHeaderRec::InclinationMeter (uint32 inclinationSerailPort) const
Definition at line 456 of file SipperHeaderRec.cpp.
References x.
void SipperHardware::SipperHeaderRec::Latitude (double _latitude) inline
Definition at line 99 of file SipperHeaderRec.h.
double SipperHardware::SipperHeaderRec::Latitude () const inline
Definition at line 121 of file SipperHeaderRec.h.
void SipperHardware::SipperHeaderRec::Longitude (double _longitude) inline
Definition at line 100 of file SipperHeaderRec.h.
double SipperHardware::SipperHeaderRec::Longitude () const inline
Definition at line 122 of file SipperHeaderRec.h.
void SipperHardware::SipperHeaderRec::Objective (KKStr _objective) inline
Definition at line 89 of file SipperHeaderRec.h.
KKStr SipperHardware::SipperHeaderRec::Objective () const inline
Definition at line 111 of file SipperHeaderRec.h.
SipperHeaderRec & SipperHeaderRec::operator= (const SipperHeaderRec & right)
Definition at line 478 of file SipperHeaderRec.cpp.
void SipperHeaderRec::ParseHeaderStr (const KKStr & s)
Definition at line 232 of file SipperHeaderRec.cpp.
References KKU::KKStr::LocateCharacter(), ProcessNameAndDataStrings(), KKU::KKStr::Split(), KKU::KKStr::SubStrPart(), KKU::KKStr::ToLower(), and x.
const PortAssignmentList& SipperHardware::SipperHeaderRec::PortAssignments () const inline
Definition at line 72 of file SipperHeaderRec.h.
void SipperHardware::SipperHeaderRec::Principal (KKStr _principal) inline
Definition at line 90 of file SipperHeaderRec.h.
KKStr SipperHardware::SipperHeaderRec::Principal () const inline
Definition at line 112 of file SipperHeaderRec.h.
void SipperHeaderRec::ProcessNameAndDataStrings (const KKStr & fieldName, const KKStr & fieldValue, bool & found)
Definition at line 270 of file SipperHeaderRec.cpp.
References KKU::KKStr::Split(), KKU::KKStr::ToDouble(), KKU::KKStr::ToInt(), and KKU::KKStr::ToLower().
Referenced by ParseHeaderStr().
void SipperHardware::SipperHeaderRec::ResearchOrg (KKStr _researchOrg) inline
Definition at line 91 of file SipperHeaderRec.h.
KKStr SipperHardware::SipperHeaderRec::ResearchOrg () const inline
Definition at line 113 of file SipperHeaderRec.h.
void SipperHardware::SipperHeaderRec::Save (ostream & w)
void SipperHardware::SipperHeaderRec::ScanRate (int32 _scanRate) inline
Definition at line 101 of file SipperHeaderRec.h.
int32 SipperHardware::SipperHeaderRec::ScanRate () const inline
Definition at line 123 of file SipperHeaderRec.h.
void SipperHardware::SipperHeaderRec::SeaConditions (KKStr _seaConditions) inline
Definition at line 95 of file SipperHeaderRec.h.
KKStr SipperHardware::SipperHeaderRec::SeaConditions () const inline
Definition at line 117 of file SipperHeaderRec.h.
InstrumentPtr SipperHeaderRec::SerialPortAssignment (uint32 serialPort) const
Definition at line 441 of file SipperHeaderRec.cpp.
Referenced by SipperHardware::InstrumentDataReport::CreateInstrumentDataReport().
const KKStr & SipperHeaderRec::SerialPortDesc (uint32 serialPortNum) const
Definition at line 428 of file SipperHeaderRec.cpp.
const KKStr & SipperHeaderRec::SerialPortShortName (uint32 serialPortNum) const
Definition at line 414 of file SipperHeaderRec.cpp.
void SipperHardware::SipperHeaderRec::SipperFileName (KKStr _sipperFileName) inline
Definition at line 102 of file SipperHeaderRec.h.
KKStr SipperHardware::SipperHeaderRec::SipperFileName () const inline
Definition at line 124 of file SipperHeaderRec.h.
void SipperHardware::SipperHeaderRec::WaveHeight (KKStr _waveHeight) inline
Definition at line 96 of file SipperHeaderRec.h.
KKStr SipperHardware::SipperHeaderRec::WaveHeight () const inline
Definition at line 118 of file SipperHeaderRec.h.
void SipperHardware::SipperHeaderRec::WeatherConditions (KKStr _weatherConditions) inline
Definition at line 97 of file SipperHeaderRec.h.
KKStr SipperHardware::SipperHeaderRec::WeatherConditions () const inline
Definition at line 119 of file SipperHeaderRec.h.
Member Data Documentation
const int32 SipperHardware::SipperHeaderRec::MaxHeaderLen = 456 static
Definition at line 61 of file SipperHeaderRec.h.
const int32 SipperHardware::SipperHeaderRec::MaxSipperFileNameLen = 30 static
Definition at line 62 of file SipperHeaderRec.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/SipperHeaderRec.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/SipperHeaderRec.cpp