Pices: MLL::FeatureFileIO Class Reference
MLL::FeatureFileIO Class Reference abstract
Base class for all FeatureFileIO classes.
#include <FeatureFileIO.h>
Public Types
typedef FeatureFileIO * FeatureFileIOPtr
typedef KKU::int32 int32
typedef KKU::uint32 uint32
Public Member Functions
FeatureFileIO (const KKStr &_driverName, bool _canRead, bool _canWrite)
virtual ~FeatureFileIO ()
void AppendToFile (const KKStr &_fileName, const FeatureNumList &_selFeatures, FeatureVectorList &_examples, uint32 &_numExamplesWritten, volatile const bool &_cancelFlag, bool &_successful, RunLog &log)
bool CanRead ()
bool CanWrite ()
const KKStr & DriverName ()
virtual FileDescPtr GetFileDesc (const KKStr &_fileName, std::istream &_in, MLClassConstListPtr _classes, int32 &_estSize, KKStr &_errorMessage, RunLog &_log)=0
Create a FileDesc object from the input stream '_in'.
virtual FeatureVectorListPtr LoadFeatureFile (const KKStr &_fileName, MLClassConstList &_mlClasses, long _maxCount, volatile const bool &_cancelFlag, bool &_successful, bool &_changesMade, RunLog &_log)
Loads the contents of a feature data file and returns a ImageFeaturesList container object.
virtual FeatureVectorListPtr LoadFile (const KKStr &_fileName, const FileDescPtr _fileDesc, MLClassConstList &_classes, std::istream &_in, long _maxCount, volatile const bool &_cancelFlag, bool &_changesMade, KKStr &_errorMessage, RunLog &_log)=0
To be implemented by derived classes; loads the contents of a feature data file and returns a ImageFeaturesList container object.
virtual void SaveFeatureFile (const KKStr &_fileName, const FeatureNumList &_selFeatures, FeatureVectorList &_examples, uint32 &_numExamplesWritten, volatile const bool &_cancelFlag, bool &_successful, RunLog &_log)
SaveFeatureFile.
void SaveFeatureFileMultipleParts (const KKStr &_fileName, const FeatureNumList &_selFeatures, FeatureVectorList &_examples, volatile const bool &_cancelFlag, bool &_successful, RunLog &_log)
Saves the feature file in multiple parts with no one single part larger that 64k examples.
virtual void SaveFile (FeatureVectorList &_data, const KKStr &_fileName, const FeatureNumList &_selFeatures, std::ostream &_out, uint32 &_numExamplesWritten, volatile const bool &_cancelFlag, bool &_successful, KKStr &_errorMessage, RunLog &_log)=0
To be implmenetd by derived classes; save examples to output stream '_out'.
Static Public Member Functions
static FeatureFileIOPtr FileFormatFromStr (const KKStr &_fileFormatStr)
static FeatureFileIOPtr FileFormatFromStr (const KKStr &_fileFormatStr, bool _canRead, bool _canWrite)
static KKStr FileFormatsReadAndWriteOptionsStr ()
static KKStr FileFormatsReadOptionsStr ()
static KKStr FileFormatsWrittenOptionsStr ()
static void FinalCleanUp ()
Before you terminate your application and after all FeatureFileIO activity is done call this method to destroy statically dynamically allocated data structures.
static VectorKKStr RegisteredDriverNames (bool canRead, bool canWrite)
Protected Member Functions
void GetLine (std::istream &_in, KKStr &_line, bool &_eof)
void GetToken (std::istream &_in, const char *_delimiters, KKStr &_token, bool &_eof, bool &_eol)
Will retrieve the next token from the input stream.
Detailed Description
Base class for all FeatureFileIO classes.
This is a abstract class. For each type of FeatureFile you will need to implement a separate class derivd from this class that supports the specific file format. You only bneed to implementthe puir virtual functions.
If you create a new FeatureFileIO class you will need to modify 'RegisterAllDrivers' methiod in FeatureFileIO.cpp.
Definition at line 45 of file FeatureFileIO.h.
Member Typedef Documentation
typedef FeatureFileIO* MLL::FeatureFileIO::FeatureFileIOPtr
Definition at line 48 of file FeatureFileIO.h.
typedef KKU::int32 MLL::FeatureFileIO::int32
Definition at line 50 of file FeatureFileIO.h.
typedef KKU::uint32 MLL::FeatureFileIO::uint32
Definition at line 51 of file FeatureFileIO.h.
Constructor & Destructor Documentation
FeatureFileIO::FeatureFileIO (const KKStr & _driverName, bool _canRead, bool _canWrite)
Definition at line 317 of file FeatureFileIO.cpp.
FeatureFileIO::~FeatureFileIO () virtual
Definition at line 330 of file FeatureFileIO.cpp.
Member Function Documentation
void FeatureFileIO::AppendToFile (const KKStr & _fileName, const FeatureNumList & _selFeatures, FeatureVectorList & _examples, uint32 & _numExamplesWritten, volatile const bool & _cancelFlag, bool & _successful, RunLog & log)
Definition at line 519 of file FeatureFileIO.cpp.
References KKU::endl(), MLL::FeatureVectorList::FileDesc(), KKU::RunLog::Level(), KKU::osDisplayWarning(), SaveFile(), and KKU::KKStr::Str().
bool MLL::FeatureFileIO::CanRead () inline
Definition at line 60 of file FeatureFileIO.h.
Referenced by FileFormatsReadOptionsStr(), and RegisteredDriverNames().
bool MLL::FeatureFileIO::CanWrite () inline
Definition at line 61 of file FeatureFileIO.h.
Referenced by FileFormatsReadAndWriteOptionsStr(), FileFormatsWrittenOptionsStr(), PicesInterface::PicesFeatureFileIO::LoadFeatureFile(), RegisteredDriverNames(), PicesInterface::PicesFeatureFileIO::SaveFeatureFile(), and PicesInterface::PicesFeatureFileIO::SaveFeatureFileNormalized().
const KKStr& MLL::FeatureFileIO::DriverName () inline
Definition at line 219 of file FeatureFileIO.h.
Referenced by FileFormatsReadAndWriteOptionsStr(), FileFormatsReadOptionsStr(), FileFormatsWrittenOptionsStr(), PicesInterface::PicesFeatureFileIO::LoadFeatureFile(), RegisteredDriverNames(), CrossValidationApp::ReportCmdLineParameters(), PicesInterface::PicesFeatureFileIO::SaveFeatureFile(), and PicesInterface::PicesFeatureFileIO::SaveFeatureFileNormalized().
static FeatureFileIOPtr MLL::FeatureFileIO::FileFormatFromStr (const KKStr & _fileFormatStr) static
static FeatureFileIOPtr MLL::FeatureFileIO::FileFormatFromStr (const KKStr & _fileFormatStr, bool _canRead, bool _canWrite) static
KKStr FeatureFileIO::FileFormatsReadAndWriteOptionsStr () static
Definition at line 244 of file FeatureFileIO.cpp.
References CanWrite(), DriverName(), and KKU::KKStr::Empty().
KKStr FeatureFileIO::FileFormatsReadOptionsStr () static
Definition at line 199 of file FeatureFileIO.cpp.
References CanRead(), DriverName(), and KKU::KKStr::Empty().
KKStr FeatureFileIO::FileFormatsWrittenOptionsStr () static
Definition at line 221 of file FeatureFileIO.cpp.
References CanWrite(), DriverName(), and KKU::KKStr::Empty().
void FeatureFileIO::FinalCleanUp () static
Before you terminate your application and after all FeatureFileIO activity is done call this method to destroy statically dynamically allocated data structures.
This metjod undoes everything that 'RegisterAllDrivers' does. Its primary usefullness is aid in tracking down memory leaks. This way the '_CrtSetDbgFlag' debuging functyionality will not report the memory allocated by the different feature FileIO drivers.
Definition at line 119 of file FeatureFileIO.cpp.
virtual FileDescPtr MLL::FeatureFileIO::GetFileDesc (const KKStr & _fileName, std::istream & _in, MLClassConstListPtr _classes, int32 & _estSize, KKStr & _errorMessage, RunLog & _log) pure virtual
Create a FileDesc object from the input stream '_in'.
All derived classes must implement this method. It is called by 'LoadFeatureFile' before it starts reading in the feature data.
Parameters
[in] _fileName Name of file to read top get FileDesc data from. Ex in c45 this wiould be the names file.
[in] _in Input Stream t read from.
[out] _classes Must be pointing to a valid MLClassList object. As class names are encountered add them to this list.
[out] _estSize If you cabn drive the number of examples in the feature file populate this parameter.
[out] _errorMessage If a error in processing occurs; place a description of th eerror in this parameter.
_log
void FeatureFileIO::GetLine (std::istream & _in, KKStr & _line, bool & _eof) protected
Definition at line 336 of file FeatureFileIO.cpp.
References KKU::KKStr::Append().
Referenced by MLL::FeatureFileIODstWeb::GetFileDesc(), MLL::FeatureFileIOC45::GetFileDesc(), MLL::FeatureFileIOUCI::GetFileDesc(), MLL::FeatureFileIODstWeb::LoadFile(), and MLL::FeatureFileIOUCI::LoadFile().
void FeatureFileIO::GetToken (std::istream & _in, const char * _delimiters, KKStr & _token, bool & _eof, bool & _eol) protected
Will retrieve the next token from the input stream.
Leading and trailing blank charaters will be skipped. A token will be seperated by any charater in '_delimiters' or 'EndOfLine', or 'EndOfFile'. If a 'EndOfLine' or 'EndOfFile' occur while reading in a token the respective flags '_eol' and '_eof' will be set to false but the following call to this function will set the resepective flag to true and return a empty token.
Parameters
[in] _in Stream to read from,
[in] _delimiters List of valid delimiter characters.
[out] _token token extracted from '_in'. If either '_eof' or '_eol' are set to true; then token will be empty.
[out] _eof Set true if at end of file;
[out] _eol Set true if at end of line.
Definition at line 380 of file FeatureFileIO.cpp.
References KKU::KKStr::Append().
Referenced by MLL::FeatureFileIOColumn::GetFileDesc(), MLL::FeatureFileIOSparse::GetFileDesc(), MLL::FeatureFileIOColumn::LoadFile(), MLL::FeatureFileIOPices::LoadFile(), and MLL::FeatureFileIOSparse::LoadFile().
FeatureVectorListPtr FeatureFileIO::LoadFeatureFile (const KKStr & _fileName, MLClassConstList & _mlClasses, long _maxCount, volatile const bool & _cancelFlag, bool & _successful, bool & _changesMade, RunLog & _log) virtual
Loads the contents of a feature data file and returns a ImageFeaturesList container object.
Parameters
[in] _fileName Feature file that is being syncronized.
[in,out] _mlClasses All classes encounterd during the loading of the feature file will be added to this list.
[in] _maxCount Maximum number of examples to load, -1 = load all
[in] _cancelFlag If this flag turns true the load will terminate and return to caller.
[out] _successful False will be returned if load failed.
[out] _changesMade If the routine hatloaded the feature data determined that it neeeded to make changes this flag will be set 'true'.
[in] _log Where to send diagnostic messages to.
Returns
A ImageFeaturesList container object; this object will own all the examples loaded.
Reimplemented in MLL::FeatureFileIOC45.
Definition at line 458 of file FeatureFileIO.cpp.
References KKU::endl(), MLL::FileDesc::GetExistingFileDesc(), KKU::RunLog::Level(), and KKU::KKStr::Str().
Referenced by PicesInterface::PicesFeatureFileIO::LoadFeatureFile(), and CrossValidationApp::ProcessCmdLineParameters().
virtual FeatureVectorListPtr MLL::FeatureFileIO::LoadFile (const KKStr & _fileName, const FileDescPtr _fileDesc, MLClassConstList & _classes, std::istream & _in, long _maxCount, volatile const bool & _cancelFlag, bool & _changesMade, KKStr & _errorMessage, RunLog & _log) pure virtual
To be implemented by derived classes; loads the contents of a feature data file and returns a ImageFeaturesList container object.
Parameters
[in] _fileName Feature file that is being loaded.
[in] _fileDesc Description of featyuire data that is to be loaded.
[in,out] _classes All classes encounterd during the loading of the feature file will be added to this list.
[in] _in input stream that feature data is to be loaded/read from.
[in] _maxCount Maximum number of examples to load, -1 = load all
[in] _cancelFlag If this flag turns true the load will terminate and return to caller.
[out] _changesMade If the routine hatloaded the feature data determined that it neeeded to make changes this flag will be set 'true'.
[out] _errorMessage If an error occurs during the loading a description iof this error will be placed here.
[in] _log Where to send diagnostic messages to.
Returns
A ImageFeaturesList container object; this object will own all the examples loaded; if an error occurs NULL will be returned.
Parameters
_maxCount Maximum # images to load.
VectorKKStr FeatureFileIO::RegisteredDriverNames (bool canRead, bool canWrite) static
Definition at line 267 of file FeatureFileIO.cpp.
References CanRead(), CanWrite(), and DriverName().
void FeatureFileIO::SaveFeatureFile (const KKStr & _fileName, const FeatureNumList & _selFeatures, FeatureVectorList & _examples, uint32 & _numExamplesWritten, volatile const bool & _cancelFlag, bool & _successful, RunLog & _log) virtual
SaveFeatureFile.
Save examples to 'fileName'
Parameters
[in] _fileName Name of file top same examples/images to.
[in] _selFeatures Specify specific features to save, typically all features.
[in] _examples Examples that are to be saved.
[in] _numExamplesWritten Will reflect the num examples written, caller will be able to monitor.
[in] _cancelFlag If this flag turns true the writting of data will terminate and return to caller.
[out] _successful False will be returned if the save failed.
[in] _log log file to send messages to.
Definition at line 563 of file FeatureFileIO.cpp.
References KKU::endl(), MLL::FeatureVectorList::FileDesc(), KKU::RunLog::Level(), SaveFile(), and KKU::KKStr::Str().
Referenced by MLL::SipperExtractionImageManager::ManagedClass::CloseOutCurDirectory(), CrossValidationApp::Main(), PicesInterface::PicesFeatureVectorList::Save(), PicesInterface::PicesFeatureFileIO::SaveFeatureFile(), SaveFeatureFileMultipleParts(), and PicesInterface::PicesFeatureFileIO::SaveFeatureFileNormalized().
void FeatureFileIO::SaveFeatureFileMultipleParts (const KKStr & _fileName, const FeatureNumList & _selFeatures, FeatureVectorList & _examples, volatile const bool & _cancelFlag, bool & _successful, RunLog & _log)
Saves the feature file in multiple parts with no one single part larger that 64k examples.
Same as 'SaveFeatureFile', if more than 64k examples will break into multiple files. If there are more than 64k examples, will save all images into 'fileName', but also a second copy of them into files with same name plust seq num with max of 64k eamples in each one.
Parameters
[in] _fileName Name of file top same examples/images to.
[in] _selFeatures Specify specific features to save, typically all features.
[in] _examples Examples that are to be saved.
[in] _cancelFlag If this flag turns true the writting of data will terminate and return to caller.
[out] _successful False will be returned if the save failed.
[in] _log log file to send messages to.
Definition at line 595 of file FeatureFileIO.cpp.
References MLL::FeatureVectorList::FileDesc(), KKU::osGetFileExtension(), KKU::osRemoveExtension(), MLL::FeatureVectorList::PushOnBack(), SaveFeatureFile(), and KKU::StrFormatInt().
Referenced by MLL::SipperExtractionImageManager::Flush().
virtual void MLL::FeatureFileIO::SaveFile (FeatureVectorList & _data, const KKStr & _fileName, const FeatureNumList & _selFeatures, std::ostream & _out, uint32 & _numExamplesWritten, volatile const bool & _cancelFlag, bool & _successful, KKStr & _errorMessage, RunLog & _log) pure virtual
To be implmenetd by derived classes; save examples to output stream '_out'.
Parameters
[in] _data Examples that are to be written to saved to the output stream.
[in] _fileName Name of file top same examples/images to.
[in] _selFeatures Specify specific features to save, typically all features.
[out] _out Output stream to save feature data to.
[out] _numExamplesWritten Will reflect the num examples written, caller will be able to monitor.
[in] _cancelFlag If this flag turns true the writting of data will terminate and return to caller.
[out] _successful False will be returned if the save failed.
[out] _errorMessage If the save fails (_successful == false) then a description of the error will be placed here.
[in] _log log file to send messages to.
Referenced by AppendToFile(), and SaveFeatureFile().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/FeatureFileIO.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/FeatureFileIO.cpp