Pices: MLL::FileDesc Class Reference
MLL::FileDesc Class Reference
Provides a detailed description of the attributes of a dataset.
#include <FileDesc.h>
Public Types
typedef FileDesc * FileDescPtr
typedef KKU::int32 int32
typedef KKU::uint32 uint32
typedef KKU::ulong ulong
Public Member Functions
FileDesc ()
void AddAAttribute (const KKU::KKStr &_name, MLL::AttributeType _type, bool &alreadyExists)
void AddAAttribute (const MLL::Attribute &attribute)
void AddANominalValue (int32 fieldNum, const KKStr &nominalValue, bool &alreadyExist, RunLog &log)
void AddANominalValue (const KKStr &nominalValue, bool &alreadyExist, RunLog &log)
void AddANominalValue (const KKStr &attributeName, const KKStr &nominalValue, bool &alreadyExist, RunLog &log)
void AddClasses (const MLClassConstList &classesToAdd)
bool AllFieldsAreNumeric () const
brief Allows the user to quicly detemine if there are no nominal fields.
const MLL::AttributeList & Attributes () const
const AttributeTypeVector & AttributeVector () const
int32 Cardinality (int32 fieldNum, RunLog &log) const
const VectorInt32 & CardinalityVector () const
const KKStr & ClassNameAttribute () const
ClassNameAttribute added to support dstWeb data files.
const MLL::AttributePtr * CreateAAttributeTable () const
Caller will be responsable for deleteing.
MLL::AttributeTypeVector CreateAttributeTypeTable () const
VectorInt32 CreateCardinalityTable () const
void DisplayAttributeMappings ()
const KKStr & FieldName (int32 fieldNum) const
const KKStr & FileName () const
const MLL::Attribute & GetAAttribute (int32 fieldNum) const
int32 GetFieldNumFromAttributeName (const KKStr &attributeName) const
MLClassConstPtr GetMLClassPtr (const KKStr &className)
const KKStr & GetNominalValue (int32 fieldNum, int32 code) const
const MLL::AttributePtr LookUpByName (const KKStr &attributeName) const
MLClassConstPtr LookUpMLClassByName (const KKStr &className)
int32 LookUpNominalCode (int32 fieldNum, const KKStr &nominalValue) const
MLClassConstPtr LookUpUnKnownMLClass ()
int32 MemoryConsumedEstimated () const
uint32 NumOfFields () const
bool operator!= (const FileDesc &rightSize) const
Returns true if file description on the right size is NOT identicle.
bool operator== (const FileDesc &rightSize) const
Returns true if file description on the right size is identicle.
bool SameExceptForSymbolicData (const FileDesc &otherFd, RunLog &log) const
void SparseMinFeatureNum (int32 _sparseMinFeatureNum)
int32 SparseMinFeatureNum () const
MLL::AttributeType Type (int32 fieldNum) const
KKStr TypeStr (int32 fieldNum) const
short Version () const
void Version (short _version)
Static Public Member Functions
static void FinalCleanUp ()
Clean up function, call just vefore exiting the application.
static bool FinalCleanUpRanAlready ()
static FileDescPtr GetExistingFileDesc (FileDescPtr fileDesc)
Returns a pointer to an existing instance of 'fileDesc' if it exists, otherwise will use one being passed in.
static FileDescPtr MergeSymbolicFields (const FileDesc &left, const FileDesc &right, RunLog &log)
Mergs the Symbolic fields of two different 'FileDesc' instances producing a new instance of a 'FileDesc'.
static FileDescPtr NewContinuousDataOnly (RunLog &_log, VectorKKStr &_fieldNames)
Creates a simple FileDesc that consists of continuous data only.
Protected Member Functions
~FileDesc ()
Friends
class KKQueue< FileDesc >
Detailed Description
Provides a detailed description of the attributes of a dataset.
Author
Kurt Kramer
***********************************************************************************
* Describes the different fields of a dataset. There will be one instance of this *
* class for each tyope of Dataset that you have in an application.  From this     *
* object you can get information such as number of attributes, Attribute types,   *
* weather they are nomainal, continuous.  If nomainal what are the accepted       *
* values.                                                                         *
*                                                                                 *
*  Never delete an instance of a FileDesc object.                                 *
*                                                                                 *
* Only one FileDesc object can exist for any Dataset.  Example the Forest Cover   *
* dataset.  You can split the data into many files and manage them seperately but *
* you will only have one instance of a FileDesc object that they will all refer   *
* to.  See "GetExistingFileDesc" method below.  You would initially create an     *
* instance of FileDesc and then use "GetExistingFileDesc" to make sure that it is *
* unique. This typically happens in the FeatureFileIO derived classes.            *
See Also
GetExistingFileDesc
FeatureVectorList
FeatureFileIo
Definition at line 88 of file FileDesc.h.
Member Typedef Documentation
typedef FileDesc* MLL::FileDesc::FileDescPtr
Definition at line 91 of file FileDesc.h.
typedef KKU::int32 MLL::FileDesc::int32
Definition at line 94 of file FileDesc.h.
typedef KKU::uint32 MLL::FileDesc::uint32
Definition at line 95 of file FileDesc.h.
typedef KKU::ulong MLL::FileDesc::ulong
Definition at line 93 of file FileDesc.h.
Constructor & Destructor Documentation
FileDesc::FileDesc ()
Definition at line 90 of file FileDesc.cpp.
Referenced by MemoryConsumedEstimated(), MergeSymbolicFields(), and NewContinuousDataOnly().
FileDesc::~FileDesc () protected
Definition at line 105 of file FileDesc.cpp.
Member Function Documentation
void FileDesc::AddAAttribute (const KKU::KKStr & _name, MLL::AttributeType _type, bool & alreadyExists)
Definition at line 166 of file FileDesc.cpp.
References INT_MAX, MLL::AttributeList::LookUpByName(), MLL::NumericAttribute, MLL::AttributeList::PushOnBack(), and MLL::Attribute::Type().
Referenced by MLL::FeatureEncoder2::CreateEncodedFileDesc(), MLL::FeatureEncoder::CreateEncodedFileDesc(), MLL::FeatureFileIODstWeb::GetFileDesc(), MLL::FeatureFileIOColumn::GetFileDesc(), MLL::FeatureFileIOUCI::GetFileDesc(), MLL::FeatureFileIOPices::GetFileDesc(), MLL::FeatureFileIOSparse::GetFileDesc(), MergeSymbolicFields(), NewContinuousDataOnly(), and MLL::FeatureFileIOPices::NewPlanktonFile().
void FileDesc::AddAAttribute (const MLL::Attribute & attribute)
Definition at line 151 of file FileDesc.cpp.
References MLL::NumericAttribute, MLL::AttributeList::PushOnBack(), and MLL::Attribute::Type().
void MLL::FileDesc::AddANominalValue (int32 fieldNum, const KKStr & nominalValue, bool & alreadyExist, RunLog & log)
Referenced by MLL::FeatureFileIODstWeb::GetFileDesc(), and MergeSymbolicFields().
void MLL::FileDesc::AddANominalValue (const KKStr & nominalValue, bool & alreadyExist, RunLog & log)
void MLL::FileDesc::AddANominalValue (const KKStr & attributeName, const KKStr & nominalValue, bool & alreadyExist, RunLog & log)
void FileDesc::AddClasses (const MLClassConstList & classesToAdd)
Definition at line 193 of file FileDesc.cpp.
References MLL::MLClassConstList::AddMLClass().
Referenced by MLL::FeatureFileIOC45::GetFileDesc().
bool FileDesc::AllFieldsAreNumeric () const
brief Allows the user to quicly detemine if there are no nominal fields.
Example use is in CrossValidation application, by using this method it can quickly determine if it is worth while using encoding.
Definition at line 717 of file FileDesc.cpp.
References MLL::IgnoreAttribute, MLL::NumericAttribute, NumOfFields(), and Type().
Referenced by MLL::FeatureVectorList::AllFieldsAreNumeric().
const MLL::AttributeList& MLL::FileDesc::Attributes () const inline
Definition at line 150 of file FileDesc.h.
Referenced by MLL::FeatureEncoder::FeatureEncoder().
const AttributeTypeVector & FileDesc::AttributeVector () const
Definition at line 812 of file FileDesc.cpp.
int32 FileDesc::Cardinality (int32 fieldNum, RunLog & log) const
Definition at line 341 of file FileDesc.cpp.
References MLL::Attribute::Cardinality(), KKU::endl(), MLL::IgnoreAttribute, INT_MAX, KKU::RunLog::Level(), MLL::NominalAttribute, MLL::NumericAttribute, KKU::osWaitForEnter(), MLL::SymbolicAttribute, and MLL::Attribute::Type().
Referenced by CreateCardinalityTable(), MLL::FeatureVectorList::FeatureCardinality(), MergeSymbolicFields(), MLL::ModelParam::NumOfFeaturesAfterEncoding(), MLL::SVMparam::NumOfFeaturesAfterEncoding(), MLL::BitReduction::output_nominal_counts(), and MLL::FeatureVectorList::ReSyncSymbolicData().
const VectorInt32& MLL::FileDesc::CardinalityVector () const inline
Definition at line 159 of file FileDesc.h.
const KKStr& MLL::FileDesc::ClassNameAttribute () const inline
ClassNameAttribute added to support dstWeb data files.
Definition at line 162 of file FileDesc.h.
Referenced by MLL::FeatureFileIODstWeb::LoadFile().
const AttributePtr * FileDesc::CreateAAttributeTable () const
Caller will be responsable for deleteing.
Definition at line 413 of file FileDesc.cpp.
References x.
Referenced by MLL::FeatureFileIODstWeb::LoadFile(), MLL::FeatureFileIOC45::LoadFile(), MLL::FeatureFileIORoberts::SaveFile(), and MLL::FeatureFileIOC45::SaveFile().
vector< AttributeType > FileDesc::CreateAttributeTypeTable () const
Definition at line 426 of file FileDesc.cpp.
References MLL::NULLAttribute, Type(), and x.
Referenced by MLL::BitReduction::compress(), and MLL::FeatureVectorList::CreateAttributeTypeTable().
VectorInt32 FileDesc::CreateCardinalityTable () const
Definition at line 437 of file FileDesc.cpp.
References Cardinality(), and x.
Referenced by MLL::BitReduction::compress(), and MLL::FeatureVectorList::CreateCardinalityTable().
void FileDesc::DisplayAttributeMappings ()
Definition at line 629 of file FileDesc.cpp.
References MLL::Attribute::Cardinality(), KKU::endl(), MLL::Attribute::GetNominalCode(), MLL::Attribute::GetNominalValue(), MLL::IgnoreAttribute, MLL::NominalAttribute, MLL::NULLAttribute, MLL::NumericAttribute, NumOfFields(), MLL::OrdinalAttribute, MLL::SymbolicAttribute, and MLL::Attribute::Type().
const KKStr & FileDesc::FieldName (int32 fieldNum) const
Definition at line 392 of file FileDesc.cpp.
Referenced by MLL::FeatureEncoder2::CreateEncodedFileDesc(), MLL::FeatureEncoder::CreateEncodedFileDesc(), MLL::FeatureVectorList::FieldName(), MergeSymbolicFields(), MLL::FeatureVectorList::ReSyncSymbolicData(), SameExceptForSymbolicData(), and MLL::FeatureFileIOPices::SaveFile().
const KKStr& MLL::FileDesc::FileName () const inline
Definition at line 173 of file FileDesc.h.
Referenced by SameExceptForSymbolicData().
void FileDesc::FinalCleanUp () static
Clean up function, call just vefore exiting the application.
*******************************************************************************
* Before you terminate your application you should call this method.  It will *
* clean up the FileDesc objects that were created during the runtime of your  *
* application.                                                                *
Definition at line 65 of file FileDesc.cpp.
Referenced by GetExistingFileDesc().
static bool MLL::FileDesc::FinalCleanUpRanAlready () inline static
Definition at line 110 of file FileDesc.h.
const Attribute & FileDesc::GetAAttribute (int32 fieldNum) const
Definition at line 207 of file FileDesc.cpp.
Referenced by MergeSymbolicFields().
FileDescPtr FileDesc::GetExistingFileDesc (FileDescPtr fileDesc) static
Returns a pointer to an existing instance of 'fileDesc' if it exists, otherwise will use one being passed in.
******************************* GetExistingFileDesc ******************************
*  Will look for a existing FileDesc that is the same as the 'fileDesc' being    *
*  passed in.                                                                    *
*  if  one is found   them                                                       *
*    fileDesc is deleted                                                         *
*    exiting one will be retuned.                                                *
*  else                                                                          *
*    fileDesc will be added to existinList (exisitingDescriptions) and returned. *
*    and returned.                                                               *
**********************************************************************************
Parameters
[in] fileDesc Pointer to a FileDesc object that you want to look and see if one that is identical already exists.
Returns
pointer to the 'FileDesc' instance that the caller should be using.
Definition at line 562 of file FileDesc.cpp.
References KKU::GoalKeeper::EndBlock(), FinalCleanUp(), and KKU::GoalKeeper::StartBlock().
Referenced by MLL::FeatureEncoder2::CreateEncodedFileDesc(), MLL::FeatureFileIOC45::LoadFeatureFile(), MLL::FeatureFileIO::LoadFeatureFile(), MergeSymbolicFields(), NewContinuousDataOnly(), and MLL::FeatureFileIOPices::NewPlanktonFile().
int32 FileDesc::GetFieldNumFromAttributeName (const KKStr & attributeName) const
Definition at line 702 of file FileDesc.cpp.
References MLL::Attribute::FieldNum(), and MLL::AttributeList::LookUpByName().
Referenced by MLL::FeatureFileIODstWeb::LoadFile().
MLClassConstPtr FileDesc::GetMLClassPtr (const KKStr & className)
Definition at line 297 of file FileDesc.cpp.
References MLL::MLClassConstList::GetMLClassPtr().
const KKStr & FileDesc::GetNominalValue (int32 fieldNum, int32 code) const
Definition at line 400 of file FileDesc.cpp.
Referenced by MLL::FeatureEncoder2::CreateEncodedFileDesc(), MLL::FeatureEncoder::CreateEncodedFileDesc(), MergeSymbolicFields(), and MLL::FeatureVectorList::ReSyncSymbolicData().
const AttributePtr FileDesc::LookUpByName (const KKStr & attributeName) const
Definition at line 694 of file FileDesc.cpp.
References MLL::AttributeList::LookUpByName().
MLClassConstPtr FileDesc::LookUpMLClassByName (const KKStr & className)
Definition at line 283 of file FileDesc.cpp.
References MLL::MLClassConstList::LookUpByName().
Referenced by MLL::FeatureFileIOC45::LoadFile().
int32 FileDesc::LookUpNominalCode (int32 fieldNum, const KKStr & nominalValue) const
Definition at line 323 of file FileDesc.cpp.
References MLL::Attribute::GetNominalCode(), MLL::NominalAttribute, MLL::SymbolicAttribute, and MLL::Attribute::Type().
Referenced by MergeSymbolicFields(), and MLL::FeatureVectorList::ReSyncSymbolicData().
MLClassConstPtr FileDesc::LookUpUnKnownMLClass ()
Definition at line 290 of file FileDesc.cpp.
References MLL::MLClassConstList::GetUnKnownClass().
Referenced by MLL::FeatureFileIOC45::LoadFile().
int32 FileDesc::MemoryConsumedEstimated () const
Definition at line 111 of file FileDesc.cpp.
References FileDesc(), MLL::AttributeList::MemoryConsumedEstimated(), MLL::MLClassConstList::MemoryConsumedEstimated(), and KKU::KKStr::MemoryConsumedEstimated().
FileDescPtr FileDesc::MergeSymbolicFields (const FileDesc & left, const FileDesc & right, RunLog & log) static
Mergs the Symbolic fields of two different 'FileDesc' instances producing a new instance of a 'FileDesc'.
This method will only work if both instances have the same number of fields, their names must be the same(NOT case sensative), and each field in both instances must be the same type. If all these constions are not 'true' will retirn NULL. The fields that are of 'SymbolicAttribute' will have their values merged together.
See Also
MLL:Attribute
Definition at line 736 of file FileDesc.cpp.
References AddAAttribute(), AddANominalValue(), Cardinality(), KKU::endl(), FieldName(), FileDesc(), GetAAttribute(), GetExistingFileDesc(), GetNominalValue(), KKU::RunLog::Level(), LookUpNominalCode(), NumOfFields(), SameExceptForSymbolicData(), MLL::SymbolicAttribute, and Type().
Referenced by MLL::FeatureVectorList::SynchronizeSymbolicData().
FileDescPtr FileDesc::NewContinuousDataOnly (RunLog & _log, VectorKKStr & _fieldNames) static
Creates a simple FileDesc that consists of continuous data only.
***************************************************************************
* Creates a file description that will consist of continuous fields only. *
* The vector '_fieldNames' will provide the list of ffield names.         *
***************************************************************************
Parameters
[in] _log Logging fille to use.
[in] _fieldNames Name of fields; one entry for each field.
Definition at line 125 of file FileDesc.cpp.
References AddAAttribute(), FileDesc(), GetExistingFileDesc(), MLL::NumericAttribute, and KKU::StrFormatInt().
Referenced by MLL::FeatureEncoder::FeatureEncoder().
uint32 MLL::FileDesc::NumOfFields () const inline
Definition at line 198 of file FileDesc.h.
Referenced by MLL::FeatureNumList::AddFeature(), MLL::FeatureNumList::AllFeaturesSelected(), AllFieldsAreNumeric(), MLL::FeatureNumList::Complement(), MLL::BitReduction::compress(), MLL::BitReduction::DeleteHistogram(), DisplayAttributeMappings(), MLL::FeatureNumList::ExtractFeatureNumsFromStr(), MLL::FeatureNumList::FeatureNumList(), MLL::FeatureNumList::Load(), MLL::FeatureFileIODstWeb::LoadFile(), MLL::FeatureFileIOColumn::LoadFile(), MLL::FeatureFileIOUCI::LoadFile(), MLL::FeatureFileIOC45::LoadFile(), MLL::FeatureFileIOSparse::LoadFile(), MLL::FeatureEncoder2::MemoryConsumedEstimated(), MergeSymbolicFields(), MLL::FeatureEncoder2::NumEncodedFeatures(), operator!=(), MLL::FeatureNumList::operator+(), MLL::FeatureNumList::operator+=(), MLL::FeatureNumList::operator-(), operator==(), MLL::BitReduction::output_nominal_counts(), MLL::NormalizationParms::Read(), MLL::FeatureVectorList::ResetFileDesc(), MLL::FeatureVectorList::ReSyncSymbolicData(), SameExceptForSymbolicData(), MLL::FeatureFileIOColumn::SaveFile(), MLL::FeatureNumList::SetAllFeatures(), svm_load_model(), SVM289_MFS::svm_load_model_XML_SupportVectorSection(), SVM289_BFS::svm_load_model_XML_SupportVectorSection(), and MLL::FeatureNumList::ToHexString().
bool FileDesc::operator!= (const FileDesc & rightSize) const
Returns true if file description on the right size is NOT identicle.
If both FileDesc instances have differnet number of fields, or any one of the fields has a different name(NOT case sensative), or one of the fields is of a different type.
Definition at line 463 of file FileDesc.cpp.
References NumOfFields(), and Version().
bool FileDesc::operator== (const FileDesc & rightSize) const
Returns true if file description on the right size is identicle.
Both FileDesc instances must have the same number of fields, the fields must have the same names(NOT case sensative), and the fields must have matching types(ex numericle, ordinal, etc).
Definition at line 450 of file FileDesc.cpp.
References NumOfFields(), and Version().
bool FileDesc::SameExceptForSymbolicData (const FileDesc & otherFd, RunLog & log) const
Definition at line 479 of file FileDesc.cpp.
References KKU::endl(), FieldName(), FileName(), KKU::RunLog::Level(), NumOfFields(), and Type().
Referenced by MergeSymbolicFields(), MLL::FeatureVectorList::SameExceptForSymbolicData(), and MLL::FeatureVectorList::SynchronizeSymbolicData().
void MLL::FileDesc::SparseMinFeatureNum (int32 _sparseMinFeatureNum) inline
Definition at line 204 of file FileDesc.h.
Referenced by MLL::FeatureFileIOSparse::GetFileDesc(), MLL::FeatureFileIOSparse::LoadFile(), and MLL::FeatureFileIOSparse::SaveFile().
int32 MLL::FileDesc::SparseMinFeatureNum () const inline
Definition at line 205 of file FileDesc.h.
AttributeType FileDesc::Type (int32 fieldNum) const
Definition at line 375 of file FileDesc.cpp.
Referenced by AllFieldsAreNumeric(), CreateAttributeTypeTable(), MLL::FeatureNumList::FeatureAttributeType(), MLL::FeatureVectorList::FeatureType(), MLL::FeatureVectorList::FeatureTypeStr(), MergeSymbolicFields(), MLL::ModelParam::NumOfFeaturesAfterEncoding(), MLL::SVMparam::NumOfFeaturesAfterEncoding(), MLL::BitReduction::output_nominal_counts(), MLL::FeatureVectorList::ReSyncSymbolicData(), SameExceptForSymbolicData(), MLL::FeatureNumList::SetAllFeatures(), and TypeStr().
KKStr FileDesc::TypeStr (int32 fieldNum) const
Definition at line 383 of file FileDesc.cpp.
References MLL::AttributeTypeToStr(), and Type().
Referenced by MLL::FeatureEncoder2::CreateEncodedFileDesc(), and MLL::FeatureEncoder::CreateEncodedFileDesc().
short MLL::FileDesc::Version () const inline
Definition at line 211 of file FileDesc.h.
Referenced by MLL::FeatureFileIOPices::GetFileDesc(), operator!=(), and operator==().
void MLL::FileDesc::Version (short _version) inline
Definition at line 213 of file FileDesc.h.
Friends And Related Function Documentation
friend class KKQueue< FileDesc > friend
Definition at line 135 of file FileDesc.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/FileDesc.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/FileDesc.cpp