Pices: SipperHardware::SipperStation Class Reference
SipperHardware::SipperStation Class Reference
#include <SipperStation.h>
Public Types
typedef SipperStation * SipperStationPtr
Public Member Functions
SipperStation ()
~SipperStation ()
const KKStr & CruiseName () const
void CruiseName (const KKStr &_cruiseName)
const KKU::DateTime & DateTimeStart () const
void DateTimeStart (const KKU::DateTime &_dateTimeStart)
const KKStr & Description () const
void Description (const KKStr &_description)
double Latitude () const
void Latitude (double _latitude)
double Longitude () const
void Longitude (double _longitude)
const KKStr & StationName () const
void StationName (const KKStr &_stationName)
Detailed Description
Definition at line 10 of file SipperStation.h.
Member Typedef Documentation
typedef SipperStation* SipperHardware::SipperStation::SipperStationPtr
Definition at line 13 of file SipperStation.h.
Constructor & Destructor Documentation
SipperStation::SipperStation ()
Definition at line 25 of file SipperStation.cpp.
SipperStation::~SipperStation ()
Definition at line 38 of file SipperStation.cpp.
Member Function Documentation
const KKStr& SipperHardware::SipperStation::CruiseName () const inline
Definition at line 18 of file SipperStation.h.
Referenced by PicesInterface::PicesSipperStation::PicesSipperStation(), MLL::DataBase::SipperStationInsert(), and MLL::DataBase::SipperStationUpdate().
void SipperHardware::SipperStation::CruiseName (const KKStr & _cruiseName) inline
Definition at line 25 of file SipperStation.h.
const KKU::DateTime& SipperHardware::SipperStation::DateTimeStart () const inline
Definition at line 23 of file SipperStation.h.
Referenced by MLL::DataBase::SipperStationInsert(), and MLL::DataBase::SipperStationUpdate().
void SipperHardware::SipperStation::DateTimeStart (const KKU::DateTime & _dateTimeStart) inline
Definition at line 30 of file SipperStation.h.
const KKStr& SipperHardware::SipperStation::Description () const inline
Definition at line 20 of file SipperStation.h.
Referenced by MLL::DataBase::SipperStationInsert(), and MLL::DataBase::SipperStationUpdate().
void SipperHardware::SipperStation::Description (const KKStr & _description) inline
Definition at line 27 of file SipperStation.h.
double SipperHardware::SipperStation::Latitude () const inline
Definition at line 21 of file SipperStation.h.
Referenced by MLL::DataBase::SipperStationInsert(), and MLL::DataBase::SipperStationUpdate().
void SipperHardware::SipperStation::Latitude (double _latitude) inline
Definition at line 28 of file SipperStation.h.
double SipperHardware::SipperStation::Longitude () const inline
Definition at line 22 of file SipperStation.h.
Referenced by MLL::DataBase::SipperStationInsert(), and MLL::DataBase::SipperStationUpdate().
void SipperHardware::SipperStation::Longitude (double _longitude) inline
Definition at line 29 of file SipperStation.h.
const KKStr& SipperHardware::SipperStation::StationName () const inline
Definition at line 19 of file SipperStation.h.
Referenced by DetermineCropSettings(), MLL::DataBase::SipperStationInsert(), and MLL::DataBase::SipperStationUpdate().
void SipperHardware::SipperStation::StationName (const KKStr & _stationName) inline
Definition at line 26 of file SipperStation.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/SipperStation.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/SipperStation.cpp