Pices: SipperHardware::InstrumentDataList Class Reference
SipperHardware::InstrumentDataList Class Reference
#include <InstrumentDataList.h>
Public Types
typedef InstrumentDataList * InstrumentDataListPtr
typedef KKU::int32 int32
typedef KKU::uint32 uint32
Public Member Functions
InstrumentDataList (bool _owner)
InstrumentDataList (const KKStr &_fileName, bool &_loadWasSucessfull, RunLog &_log)
~InstrumentDataList ()
VectorDouble FrameOffsetsInMeters (uint32 scanLinesPerFrame, float scanRate, float defaultFlowRate)
Calculates the offset, in meters, from the beginning of a SIPPER file for each frame.
VectorUlong GetScanLinesPerMeterProfile () const
VectorFloat GetVolumePerMeterProfile (SipperFilePtr sipperFile, volatile bool &cancelFlag, RunLog &log) const
void Save (const KKStr &fileName, RunLog &log) const
float ScanRate () const
void ScanRate (float _scanRate)
InstrumentDataPtr SearchForNearestScanLine (uint32 scanLine)
void SipperFileName (const KKStr &_sipperFileName)
const KKStr & SipperFileName () const
void ThereIsDepthData (bool _thereIsDepthData)
void ThereIsFlowRateData (bool _thereIsFlowRateData)
Static Public Member Functions
static InstrumentDataListPtr CreateFromSipperFile (const KKStr &fullSipperFileName, SipperFilePtr sipperFile, volatile const bool &cancelFlag, RunLog &log)
Detailed Description
Definition at line 28 of file InstrumentDataList.h.
Member Typedef Documentation
typedef InstrumentDataList* SipperHardware::InstrumentDataList::InstrumentDataListPtr
Definition at line 45 of file InstrumentDataList.h.
typedef KKU::int32 SipperHardware::InstrumentDataList::int32
Definition at line 31 of file InstrumentDataList.h.
typedef KKU::uint32 SipperHardware::InstrumentDataList::uint32
Definition at line 32 of file InstrumentDataList.h.
Constructor & Destructor Documentation
InstrumentDataList::InstrumentDataList (bool _owner)
Definition at line 34 of file InstrumentDataList.cpp.
Referenced by CreateFromSipperFile().
InstrumentDataList::InstrumentDataList (const KKStr & _fileName, bool & _loadWasSucessfull, RunLog & _log)
Definition at line 46 of file InstrumentDataList.cpp.
InstrumentDataList::~InstrumentDataList ()
Definition at line 64 of file InstrumentDataList.cpp.
Member Function Documentation
InstrumentDataListPtr InstrumentDataList::CreateFromSipperFile (const KKStr & fullSipperFileName, SipperFilePtr sipperFile, volatile const bool & cancelFlag, RunLog & log) static
Definition at line 71 of file InstrumentDataList.cpp.
References SipperHardware::InstrumentData::ByteOffset(), SipperHardware::SipperBuff::ByteOffset(), SipperHardware::InstrumentDataManager::CreateInstrumentData(), SipperHardware::SipperBuff::CreateSipperBuff(), SipperHardware::InstrumentData::CtdDate(), SipperHardware::SipperBuff::CurRow(), SipperHardware::SipperBuff::CurRowByteOffset(), SipperHardware::InstrumentData::Depth(), KKU::endl(), SipperHardware::SipperBuff::Eof(), SipperHardware::InstrumentData::FlowRate1(), SipperHardware::SipperBuff::GetNextLine(), InstrumentDataList(), KKU::RunLog::Level(), KKU::osGetRootName(), SipperHardware::InstrumentData::RefreshDataFields(), SipperHardware::InstrumentData::Salinity(), SipperHardware::InstrumentData::ScanLine(), SipperHardware::SipperFile::ScanRate(), ScanRate(), SipperHardware::sfUnKnown, SipperFileName(), KKU::StrFormatInt(), SipperHardware::InstrumentData::Temperature(), ThereIsDepthData(), ThereIsFlowRateData(), and KKU::DateTime::Year().
VectorDouble InstrumentDataList::FrameOffsetsInMeters (uint32 scanLinesPerFrame, float scanRate, float defaultFlowRate)
Calculates the offset, in meters, from the beginning of a SIPPER file for each frame.
Calculates the offset, in meters, from the beginning of a SIPPER file for each frame. Data will be assumed to be in scan line order. Flow-rate and Scan-rate will be used as part of the calculations.
Definition at line 433 of file InstrumentDataList.cpp.
References SipperHardware::InstrumentData::FlowRate1(), and SipperHardware::InstrumentData::ScanLine().
VectorUlong InstrumentDataList::GetScanLinesPerMeterProfile () const
Definition at line 632 of file InstrumentDataList.cpp.
References SipperHardware::InstrumentData::Depth().
Referenced by SipperHardware::InstrumentDataFileManager::GetScanLinesPerMeterProfile2().
VectorFloat InstrumentDataList::GetVolumePerMeterProfile (SipperFilePtr sipperFile, volatile bool & cancelFlag, RunLog & log) const
Definition at line 574 of file InstrumentDataList.cpp.
References SipperHardware::InstrumentData::Depth(), KKU::endl(), KKU::RunLog::Level(), and SipperHardware::SipperFile::ScanRate().
Referenced by SipperHardware::InstrumentDataFileManager::GetVolumePerMeterProfile2().
void InstrumentDataList::Save (const KKStr & fileName, RunLog & log) const
Definition at line 387 of file InstrumentDataList.cpp.
References SipperHardware::InstrumentData::CurrentFileVersion(), KKU::endl(), SipperHardware::InstrumentData::FieldName(), KKU::RunLog::Level(), SipperHardware::InstrumentData::NumFields(), KKU::osGetLocalDateTime(), KKU::KKStr::Str(), SipperHardware::InstrumentData::ToTabDelStr(), and x.
float SipperHardware::InstrumentDataList::ScanRate () const inline
Definition at line 88 of file InstrumentDataList.h.
Referenced by CreateFromSipperFile(), and MLL::DataBase::InstrumentDataLoad().
void SipperHardware::InstrumentDataList::ScanRate (float _scanRate) inline
Definition at line 89 of file InstrumentDataList.h.
InstrumentDataPtr InstrumentDataList::SearchForNearestScanLine (uint32 scanLine)
Definition at line 498 of file InstrumentDataList.cpp.
References SipperHardware::InstrumentData::ScanLine().
Referenced by MLL::DataBase::FeatureDataGetOneSipperFile(), and SipperHardware::InstrumentDataFileManager::GetClosestInstrumentData().
void SipperHardware::InstrumentDataList::SipperFileName (const KKStr & _sipperFileName) inline
Definition at line 73 of file InstrumentDataList.h.
Referenced by CreateFromSipperFile(), SipperHardware::InstrumentDataFileManager::GetClosestInstrumentData(), SipperHardware::InstrumentDataFileManager::GetScanLinesPerMeterProfile2(), and SipperHardware::InstrumentDataFileManager::GetVolumePerMeterProfile2().
const KKStr& SipperHardware::InstrumentDataList::SipperFileName () const inline
Definition at line 76 of file InstrumentDataList.h.
void SipperHardware::InstrumentDataList::ThereIsDepthData (bool _thereIsDepthData) inline
Definition at line 91 of file InstrumentDataList.h.
Referenced by CreateFromSipperFile().
void SipperHardware::InstrumentDataList::ThereIsFlowRateData (bool _thereIsFlowRateData) inline
Definition at line 92 of file InstrumentDataList.h.
Referenced by CreateFromSipperFile().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/InstrumentDataList.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/InstrumentDataList.cpp