Pices: SipperHardware::InstrumentData Class Reference
SipperHardware::InstrumentData Class Reference
#include <InstrumentData.h>
Public Types
typedef KKU::int32 int32
typedef KKU::int64 int64
typedef KKU::uint32 uint32
typedef KKU::uint64 uint64
Public Member Functions
InstrumentData ()
InstrumentData (const InstrumentData &id)
InstrumentData (KKStrParser &line, const VectorInt &fieldIndirections)
InstrumentData (uint32 _scanLine, uint32 _byteOffset, const KKU::DateTime &_ctdDate, char _activeBattery, double _latitude, double _longitude, float _ctdBattery, float _conductivity, float _density, float _depth, float _flowRate1, float _flowRate2, float _fluorescence, float _fluorescenceSensor, float _cdomFluorescence, float _cdomFluorescenceSensor, float _illumination, float _oxygen, float _oxygenSensor, float _pressure, float _recordRate, float _salinity, float _soundVelocity, float _temperature, float _transmisivity, float _transmisivitySensor, float _turbidity, float _turbiditySensor, float _pitch, float _roll, float _bat1Level, float _bat2Level, float _bat3Level, float _bat4Level)
~InstrumentData ()
int32 ActiveBattery () const
float Bat1Level () const
float Bat2Level () const
float Bat3Level () const
float Bat4Level () const
KKU::uint64 ByteOffset () const
void ByteOffset (uint64 _byteOffset)
float CdomFluorescence () const
void CdomFluorescence (float _cdomFluorescence)
float CdomFluorescenceSensor () const
void CdomFluorescenceSensor (float _cdomFluorescenceSensor)
float Conductivity () const
void Conductivity (float _conductivity)
float CTDBattery () const
void CTDBattery (float _ctdBattery)
const KKU::DateTime & CtdDate () const
void CtdDate (const KKU::DateTime &_ctdDate)
float Density () const
void Density (float _density)
float Depth () const
void Depth (float _depth)
KKStr FieldToStr (int32 fieldIndex) const
float FlowRate1 () const
void FlowRate1 (float _flowRate1)
float FlowRate2 () const
void FlowRate2 (float _flowRate2)
float Fluorescence () const
void Fluorescence (float _fluorescence)
float FluorescenceSensor () const
void FluorescenceSensor (float _fluorescenceSensor)
float Illumination () const
double Latitude () const
void Latitude (double _latitude)
double Longitude () const
void Longitude (double _longitude)
float Oxygen () const
void Oxygen (float _oxygen)
float OxygenSensor () const
void OxygenSensor (float _oxygenSensor)
float Pitch () const
void Pitch (float _pitch)
float Pressure () const
void Pressure (float _pressure)
float RecordRate () const
void RecordRate (float _recordRate)
void RefreshDataFields (const InstrumentData &id)
/brief refreshes data fields from another 'InstrumentData' instance.
float Roll () const
void Roll (float _roll)
float Salinity () const
void Salinity (float _salinity)
uint32 ScanLine () const
void ScanLine (uint32 _scanLine)
float SoundVelocity () const
void SoundVelocity (float _soundVelocity)
float Temperature () const
void Temperature (float _temperature)
KKStr ToTabDelStr () const
float Transmisivity () const
void Transmisivity (float _transmisivity)
float TransmisivitySensor () const
void TransmisivitySensor (float _transmisivitySensor)
float Turbidity () const
void Turbidity (float _turbidity)
float TurbiditySensor () const
void TurbiditySensor (float _turbiditySensor)
void UpdateFromCtdData (const CTD_Plus_Data &ctdData)
Static Public Member Functions
static KKStr CdomFluorescenceUnit ()
static VectorIntPtr CreateDefaultFieldIndirectionList ()
static VectorIntPtr CreateFieldIndirectionVectorFromTabDelStr (KKStrParser &s)
static int32 CurrentFileVersion ()
static KKStr DensityUnit ()
static const KKStr & FieldFormatStr (int32 fieldIndex)
static float FieldMinValue (int32 fieldIndex)
static const KKStr & FieldName (int32 fieldIndex)
static const KKStr & FieldUnitOfMeasure (int32 fieldIndex)
static void FinalCleanUp ()
static KKStr FluorescenceUnit ()
static int32 GetFieldNum (const KKStr &s)
static int32 GetFieldNumFromShortName (const KKStr &s)
static int32 NumFields ()
static KKStr OxygenUnit ()
static KKStr SalinityUnit ()
static const KKStr & ShortFieldName (int32 fieldIndex)
static KKStr TemperatureUnit ()
static KKStr TransmisivityUnit ()
static KKStr TurbidityUnit ()
Detailed Description
Definition at line 17 of file InstrumentData.h.
Member Typedef Documentation
typedef KKU::int32 SipperHardware::InstrumentData::int32
Definition at line 20 of file InstrumentData.h.
typedef KKU::int64 SipperHardware::InstrumentData::int64
Definition at line 22 of file InstrumentData.h.
typedef KKU::uint32 SipperHardware::InstrumentData::uint32
Definition at line 21 of file InstrumentData.h.
typedef KKU::uint64 SipperHardware::InstrumentData::uint64
Definition at line 23 of file InstrumentData.h.
Constructor & Destructor Documentation
InstrumentData::InstrumentData ()
Definition at line 27 of file InstrumentData.cpp.
InstrumentData::InstrumentData (const InstrumentData & id)
Definition at line 42 of file InstrumentData.cpp.
References x.
InstrumentData::InstrumentData (KKStrParser & line, const VectorInt & fieldIndirections)
Definition at line 70 of file InstrumentData.cpp.
References KKU::KKStrParser::GetNextToken(), and x.
InstrumentData::InstrumentData (uint32 _scanLine, uint32 _byteOffset, const KKU::DateTime & _ctdDate, char _activeBattery, double _latitude, double _longitude, float _ctdBattery, float _conductivity, float _density, float _depth, float _flowRate1, float _flowRate2, float _fluorescence, float _fluorescenceSensor, float _cdomFluorescence, float _cdomFluorescenceSensor, float _illumination, float _oxygen, float _oxygenSensor, float _pressure, float _recordRate, float _salinity, float _soundVelocity, float _temperature, float _transmisivity, float _transmisivitySensor, float _turbidity, float _turbiditySensor, float _pitch, float _roll, float _bat1Level, float _bat2Level, float _bat3Level, float _bat4Level)
Definition at line 100 of file InstrumentData.cpp.
InstrumentData::~InstrumentData ()
Definition at line 197 of file InstrumentData.cpp.
Member Function Documentation
int32 SipperHardware::InstrumentData::ActiveBattery () const inline
Definition at line 94 of file InstrumentData.h.
float SipperHardware::InstrumentData::Bat1Level () const inline
Definition at line 95 of file InstrumentData.h.
float SipperHardware::InstrumentData::Bat2Level () const inline
Definition at line 96 of file InstrumentData.h.
float SipperHardware::InstrumentData::Bat3Level () const inline
Definition at line 97 of file InstrumentData.h.
float SipperHardware::InstrumentData::Bat4Level () const inline
Definition at line 98 of file InstrumentData.h.
KKU::uint64 SipperHardware::InstrumentData::ByteOffset () const inline
Definition at line 90 of file InstrumentData.h.
Referenced by SipperHardware::InstrumentDataList::CreateFromSipperFile().
void SipperHardware::InstrumentData::ByteOffset (uint64 _byteOffset) inline
Definition at line 142 of file InstrumentData.h.
float SipperHardware::InstrumentData::CdomFluorescence () const inline
Definition at line 107 of file InstrumentData.h.
void SipperHardware::InstrumentData::CdomFluorescence (float _cdomFluorescence) inline
Definition at line 156 of file InstrumentData.h.
float SipperHardware::InstrumentData::CdomFluorescenceSensor () const inline
Definition at line 108 of file InstrumentData.h.
void SipperHardware::InstrumentData::CdomFluorescenceSensor (float _cdomFluorescenceSensor) inline
Definition at line 157 of file InstrumentData.h.
static KKStr SipperHardware::InstrumentData::CdomFluorescenceUnit () inline static
Definition at line 135 of file InstrumentData.h.
float SipperHardware::InstrumentData::Conductivity () const inline
Definition at line 100 of file InstrumentData.h.
void SipperHardware::InstrumentData::Conductivity (float _conductivity) inline
Definition at line 149 of file InstrumentData.h.
VectorIntPtr InstrumentData::CreateDefaultFieldIndirectionList () static
Definition at line 471 of file InstrumentData.cpp.
References NumFields(), and x.
VectorIntPtr InstrumentData::CreateFieldIndirectionVectorFromTabDelStr (KKStrParser & s) static
Definition at line 444 of file InstrumentData.cpp.
References KKU::endl(), GetFieldNum(), NumFields(), KKU::KKStrParser::Split(), and x.
float SipperHardware::InstrumentData::CTDBattery () const inline
Definition at line 99 of file InstrumentData.h.
void SipperHardware::InstrumentData::CTDBattery (float _ctdBattery) inline
Definition at line 148 of file InstrumentData.h.
const KKU::DateTime& SipperHardware::InstrumentData::CtdDate () const inline
Definition at line 92 of file InstrumentData.h.
Referenced by MLL::DataBaseImageList::CalculateDensitesByQuadrat(), and SipperHardware::InstrumentDataList::CreateFromSipperFile().
void SipperHardware::InstrumentData::CtdDate (const KKU::DateTime & _ctdDate) inline
Definition at line 140 of file InstrumentData.h.
static int32 SipperHardware::InstrumentData::CurrentFileVersion () inline static
Definition at line 86 of file InstrumentData.h.
Referenced by SipperHardware::InstrumentDataList::Save().
float SipperHardware::InstrumentData::Density () const inline
Definition at line 102 of file InstrumentData.h.
void SipperHardware::InstrumentData::Density (float _density) inline
Definition at line 151 of file InstrumentData.h.
static KKStr SipperHardware::InstrumentData::DensityUnit () inline static
Definition at line 128 of file InstrumentData.h.
float SipperHardware::InstrumentData::Depth () const inline
Definition at line 101 of file InstrumentData.h.
Referenced by SipperHardware::InstrumentDataList::CreateFromSipperFile(), MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::DataBase::FeatureDataUpdateInstrumentDataFields(), SipperHardware::InstrumentDataList::GetScanLinesPerMeterProfile(), SipperHardware::InstrumentDataList::GetVolumePerMeterProfile(), MLL::DataBase::ImageUpdateInstrumentDataFields(), and MLL::FeatureFileIOPices::LoadFile().
void SipperHardware::InstrumentData::Depth (float _depth) inline
Definition at line 150 of file InstrumentData.h.
const KKStr & InstrumentData::FieldFormatStr (int32 fieldIndex) static
Definition at line 356 of file InstrumentData.cpp.
References NumFields().
float InstrumentData::FieldMinValue (int32 fieldIndex) static
Definition at line 346 of file InstrumentData.cpp.
References NumFields().
const KKStr & InstrumentData::FieldName (int32 fieldIndex) static
Definition at line 317 of file InstrumentData.cpp.
References NumFields().
Referenced by SipperHardware::InstrumentDataList::Save().
KKStr InstrumentData::FieldToStr (int32 fieldIndex) const
Definition at line 484 of file InstrumentData.cpp.
References KKU::DateTime::Date(), KKU::endl(), KKU::TimeType::HH_MM_SS(), KKU::SPRINTF(), KKU::StrFormatDouble(), KKU::StrFromInt32(), KKU::StrFromUint32(), KKU::StrFromUint64(), KKU::DateTime::Time(), and KKU::DateType::YYYY_MM_DD().
Referenced by ToTabDelStr().
const KKStr & InstrumentData::FieldUnitOfMeasure (int32 fieldIndex) static
Definition at line 337 of file InstrumentData.cpp.
References NumFields().
void InstrumentData::FinalCleanUp () static
Definition at line 632 of file InstrumentData.cpp.
References KKU::GoalKeeper::EndBlock(), and KKU::GoalKeeper::StartBlock().
Referenced by GetFieldNum().
float SipperHardware::InstrumentData::FlowRate1 () const inline
Definition at line 103 of file InstrumentData.h.
Referenced by MLL::DataBaseImageList::CalculateDensitesByQuadrat(), SipperHardware::InstrumentDataList::CreateFromSipperFile(), MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::DataBase::FeatureDataUpdateInstrumentDataFields(), FlowRate(), SipperHardware::InstrumentDataList::FrameOffsetsInMeters(), MLL::DataBase::ImageUpdateInstrumentDataFields(), and MLL::FeatureFileIOPices::LoadFile().
void SipperHardware::InstrumentData::FlowRate1 (float _flowRate1) inline
Definition at line 152 of file InstrumentData.h.
float SipperHardware::InstrumentData::FlowRate2 () const inline
Definition at line 104 of file InstrumentData.h.
Referenced by MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::DataBase::FeatureDataUpdateInstrumentDataFields(), MLL::DataBase::ImageUpdateInstrumentDataFields(), and MLL::FeatureFileIOPices::LoadFile().
void SipperHardware::InstrumentData::FlowRate2 (float _flowRate2) inline
Definition at line 153 of file InstrumentData.h.
float SipperHardware::InstrumentData::Fluorescence () const inline
Definition at line 105 of file InstrumentData.h.
Referenced by MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::DataBase::FeatureDataUpdateInstrumentDataFields(), MLL::DataBase::ImageUpdateInstrumentDataFields(), and MLL::FeatureFileIOPices::LoadFile().
void SipperHardware::InstrumentData::Fluorescence (float _fluorescence) inline
Definition at line 154 of file InstrumentData.h.
float SipperHardware::InstrumentData::FluorescenceSensor () const inline
Definition at line 106 of file InstrumentData.h.
void SipperHardware::InstrumentData::FluorescenceSensor (float _fluorescenceSensor) inline
Definition at line 155 of file InstrumentData.h.
static KKStr SipperHardware::InstrumentData::FluorescenceUnit () inline static
Definition at line 129 of file InstrumentData.h.
int32 InstrumentData::GetFieldNum (const KKStr & s) static
Definition at line 381 of file InstrumentData.cpp.
References KKU::GoalKeeper::EndBlock(), FinalCleanUp(), NumFields(), KKU::GoalKeeper::StartBlock(), KKU::KKStr::ToUpper(), and x.
Referenced by CreateFieldIndirectionVectorFromTabDelStr().
int32 InstrumentData::GetFieldNumFromShortName (const KKStr & s) static
Definition at line 416 of file InstrumentData.cpp.
References NumFields(), KKU::KKStr::ToUpper(), and x.
float SipperHardware::InstrumentData::Illumination () const inline
Definition at line 109 of file InstrumentData.h.
double SipperHardware::InstrumentData::Latitude () const inline
Definition at line 112 of file InstrumentData.h.
Referenced by MLL::DataBase::FeatureDataGetOneSipperFile(), and MLL::FeatureFileIOPices::FeatureDataReSink().
void SipperHardware::InstrumentData::Latitude (double _latitude) inline
Definition at line 143 of file InstrumentData.h.
double SipperHardware::InstrumentData::Longitude () const inline
Definition at line 113 of file InstrumentData.h.
Referenced by MLL::DataBase::FeatureDataGetOneSipperFile(), and MLL::FeatureFileIOPices::FeatureDataReSink().
void SipperHardware::InstrumentData::Longitude (double _longitude) inline
Definition at line 144 of file InstrumentData.h.
int32 InstrumentData::NumFields () static
Definition at line 366 of file InstrumentData.cpp.
Referenced by CreateDefaultFieldIndirectionList(), CreateFieldIndirectionVectorFromTabDelStr(), FieldFormatStr(), FieldMinValue(), FieldName(), FieldUnitOfMeasure(), GetFieldNum(), GetFieldNumFromShortName(), SipperHardware::InstrumentDataList::Save(), ShortFieldName(), and ToTabDelStr().
float SipperHardware::InstrumentData::Oxygen () const inline
Definition at line 110 of file InstrumentData.h.
Referenced by MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::DataBase::FeatureDataUpdateInstrumentDataFields(), MLL::DataBase::ImageUpdateInstrumentDataFields(), and MLL::FeatureFileIOPices::LoadFile().
void SipperHardware::InstrumentData::Oxygen (float _oxygen) inline
Definition at line 159 of file InstrumentData.h.
float SipperHardware::InstrumentData::OxygenSensor () const inline
Definition at line 111 of file InstrumentData.h.
void SipperHardware::InstrumentData::OxygenSensor (float _oxygenSensor) inline
Definition at line 158 of file InstrumentData.h.
static KKStr SipperHardware::InstrumentData::OxygenUnit () inline static
Definition at line 130 of file InstrumentData.h.
float SipperHardware::InstrumentData::Pitch () const inline
Definition at line 125 of file InstrumentData.h.
void SipperHardware::InstrumentData::Pitch (float _pitch) inline
Definition at line 171 of file InstrumentData.h.
float SipperHardware::InstrumentData::Pressure () const inline
Definition at line 114 of file InstrumentData.h.
void SipperHardware::InstrumentData::Pressure (float _pressure) inline
Definition at line 160 of file InstrumentData.h.
float SipperHardware::InstrumentData::RecordRate () const inline
Definition at line 115 of file InstrumentData.h.
void SipperHardware::InstrumentData::RecordRate (float _recordRate) inline
Definition at line 161 of file InstrumentData.h.
void InstrumentData::RefreshDataFields (const InstrumentData & id)
/brief refreshes data fields from another 'InstrumentData' instance.
Definition at line 591 of file InstrumentData.cpp.
References x.
Referenced by SipperHardware::InstrumentDataList::CreateFromSipperFile().
float SipperHardware::InstrumentData::Roll () const inline
Definition at line 126 of file InstrumentData.h.
void SipperHardware::InstrumentData::Roll (float _roll) inline
Definition at line 172 of file InstrumentData.h.
float SipperHardware::InstrumentData::Salinity () const inline
Definition at line 116 of file InstrumentData.h.
Referenced by SipperHardware::InstrumentDataList::CreateFromSipperFile(), MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::DataBase::FeatureDataUpdateInstrumentDataFields(), MLL::DataBase::ImageUpdateInstrumentDataFields(), and MLL::FeatureFileIOPices::LoadFile().
void SipperHardware::InstrumentData::Salinity (float _salinity) inline
Definition at line 162 of file InstrumentData.h.
static KKStr SipperHardware::InstrumentData::SalinityUnit () inline static
Definition at line 131 of file InstrumentData.h.
uint32 SipperHardware::InstrumentData::ScanLine () const inline
Definition at line 117 of file InstrumentData.h.
Referenced by SipperHardware::InstrumentDataList::CreateFromSipperFile(), SipperHardware::InstrumentDataList::FrameOffsetsInMeters(), MLL::DataBase::InstrumentDataReFreshSipperFile(), and SipperHardware::InstrumentDataList::SearchForNearestScanLine().
void SipperHardware::InstrumentData::ScanLine (uint32 _scanLine) inline
Definition at line 145 of file InstrumentData.h.
const KKStr & InstrumentData::ShortFieldName (int32 fieldIndex) static
Definition at line 327 of file InstrumentData.cpp.
References NumFields().
float SipperHardware::InstrumentData::SoundVelocity () const inline
Definition at line 118 of file InstrumentData.h.
void SipperHardware::InstrumentData::SoundVelocity (float _soundVelocity) inline
Definition at line 163 of file InstrumentData.h.
float SipperHardware::InstrumentData::Temperature () const inline
Definition at line 119 of file InstrumentData.h.
Referenced by SipperHardware::InstrumentDataList::CreateFromSipperFile().
void SipperHardware::InstrumentData::Temperature (float _temperature) inline
Definition at line 164 of file InstrumentData.h.
static KKStr SipperHardware::InstrumentData::TemperatureUnit () inline static
Definition at line 132 of file InstrumentData.h.
KKStr InstrumentData::ToTabDelStr () const
Definition at line 573 of file InstrumentData.cpp.
References FieldToStr(), NumFields(), and x.
Referenced by SipperHardware::InstrumentDataList::Save().
float SipperHardware::InstrumentData::Transmisivity () const inline
Definition at line 120 of file InstrumentData.h.
void SipperHardware::InstrumentData::Transmisivity (float _transmisivity) inline
Definition at line 165 of file InstrumentData.h.
float SipperHardware::InstrumentData::TransmisivitySensor () const inline
Definition at line 121 of file InstrumentData.h.
void SipperHardware::InstrumentData::TransmisivitySensor (float _transmisivitySensor) inline
Definition at line 166 of file InstrumentData.h.
static KKStr SipperHardware::InstrumentData::TransmisivityUnit () inline static
Definition at line 133 of file InstrumentData.h.
float SipperHardware::InstrumentData::Turbidity () const inline
Definition at line 122 of file InstrumentData.h.
void SipperHardware::InstrumentData::Turbidity (float _turbidity) inline
Definition at line 167 of file InstrumentData.h.
float SipperHardware::InstrumentData::TurbiditySensor () const inline
Definition at line 123 of file InstrumentData.h.
void SipperHardware::InstrumentData::TurbiditySensor (float _turbiditySensor) inline
Definition at line 168 of file InstrumentData.h.
static KKStr SipperHardware::InstrumentData::TurbidityUnit () inline static
Definition at line 134 of file InstrumentData.h.
void InstrumentData::UpdateFromCtdData (const CTD_Plus_Data & ctdData)
Definition at line 608 of file InstrumentData.cpp.
References SipperHardware::CTD_Plus_Data::BatteryVoltage(), SipperHardware::CTD_Plus_Data::CdomFluorescence(), SipperHardware::CTD_Plus_Data::CdomFluorescenceSensor(), SipperHardware::CTD_Plus_Data::Conductivity(), SipperHardware::CTD_Plus_Data::Density(), SipperHardware::CTD_Plus_Data::Depth(), SipperHardware::CTD_Plus_Data::Fluorescence(), SipperHardware::CTD_Plus_Data::FluorescenceSensor(), SipperHardware::CTD_Plus_Data::Oxygen(), SipperHardware::CTD_Plus_Data::OxygenSensor(), SipperHardware::CTD_Plus_Data::Pressure(), SipperHardware::CTD_Plus_Data::Salinity(), SipperHardware::CTD_Plus_Data::SoundVelocity(), SipperHardware::CTD_Plus_Data::Temperature(), SipperHardware::CTD_Plus_Data::Transmisivity(), SipperHardware::CTD_Plus_Data::TransmisivitySensor(), SipperHardware::CTD_Plus_Data::Turbidity(), and SipperHardware::CTD_Plus_Data::TurbiditySensor().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/InstrumentData.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/InstrumentData.cpp