Pices: MLL::ModelParamOldSVM Class Reference
MLL::ModelParamOldSVM Class Reference
this class encapsulates are the information neccesary to build a SVMModel class.
#include <ModelParamOldSVM.h>
Public Types
typedef ModelParamOldSVM * ModelParamOldSVMPtr
typedef SVM233::svm_parameter svm_parameter
Public Types inherited from MLL::ModelParam
enum CompressionMethodType {
BRNull, BRnoCompression, BRcompressionPost, BRcompressionPre,
BRunBalancedVariance, BRunBalancedSpecified
}
enum EncodingMethodType { NoEncoding, BinaryEncoding, ScaledEncoding, Encoding_NULL }
typedef ModelParam * ModelParamPtr
enum ModelParamTypes {
mptNULL, mptDual, mptKNN, mptOldSVM,
mptSvmBase, mptUsfCasCor
}
Public Member Functions
ModelParamOldSVM (FileDescPtr _fileDesc, RunLog &_log)
ModelParamOldSVM (const ModelParamOldSVM &_param)
virtual ~ModelParamOldSVM ()
virtual float A_Param () const
virtual void A_Param (float _A)
void AddBinaryClassParms (BinaryClassParmsPtr binaryClassParms)
void AddBinaryClassParms (MLClassConstPtr class1, MLClassConstPtr class2, const svm_parameter &_param, const FeatureNumList &_selectedFeatures, float _weight)
Add a Binary parameters using svm_parametr cmd line str.
virtual float AvgMumOfFeatures ()
const BinaryClassParmsListPtr BinaryParmsList () const
virtual int32 BitsToReduceBy () const
virtual double C_Param () const
virtual double C_Param (MLClassConstPtr class1, MLClassConstPtr class2) const
virtual void C_Param (double _CC)
virtual void C_Param (MLClassConstPtr class1, MLClassConstPtr class2, double cParam)
virtual ModelParamOldSVMPtr Duplicate () const
virtual void EncodingMethod (SVM_EncodingMethod _encodingMethod)
virtual void EncodingMethod (EncodingMethodType _encodingMethod)
virtual double Gamma () const
virtual void Gamma (double _gamma)
virtual void Gamma_Param (double _gamma)
FeatureNumList GetFeatureNums (MLClassConstPtr class1, MLClassConstPtr class2) const
BinaryClassParmsPtr GetParamtersToUseFor2ClassCombo (MLClassConstPtr class1, MLClassConstPtr class2)
virtual SVM_KernalType KernalType () const
virtual void KernalType (SVM_KernalType _kernalType)
virtual SVM_MachineType MachineType () const
virtual void MachineType (SVM_MachineType _machineType)
virtual ModelParamTypes ModelParamType () const
virtual int32 NumOfFeaturesAfterEncoding () const
virtual const svm_parameter & Param () const
void ParseCmdLine (KKStr _cmdLineStr, bool &_validFormat)
void ReadSpecificImplementationXML (istream &i)
virtual float SamplingRate () const
virtual void SamplingRate (float _samplingRate)
virtual const FeatureNumList & SelectedFeatures () const
virtual void SelectedFeatures (const FeatureNumList &_selectedFeatures)
virtual SVM_SelectionMethod SelectionMethod () const
virtual void SelectionMethod (SVM_SelectionMethod _selectionMethod)
void SetBinaryClassFields (MLClassConstPtr class1, MLClassConstPtr class2, const svm_parameter &_param, const FeatureNumList &_features, float _weight)
void SetFeatureNums (MLClassConstPtr class1, MLClassConstPtr class2, const FeatureNumList &_features, float _weight=-1)
virtual SVMparamPtr SvmParameters () const
KKStr SvmParamToString (const svm_parameter &_param) const
Convert a svm_parameter struct to a cmdline str.
KKStr ToCmdLineStr () const
Convert all parameters to a command line string.
virtual int32 UnBalancedBits () const
virtual KKStr UnBalancedBitsStr () const
virtual bool UseProbabilityToBreakTies () const
virtual bool WeightBitReduction () const
virtual void WeightBitReduction (bool _weightBitReduction)
void WriteSpecificImplementationXML (std::ostream &o) const
Public Member Functions inherited from MLL::ModelParam
ModelParam (FileDescPtr _fileDesc, RunLog &_log)
ModelParam (const ModelParam &_param)
virtual ~ModelParam ()
virtual float AvgMumOfFeatures () const
virtual void BitsToReduceBy (int32 _bitsToReduceBy)
virtual CompressionMethodType CompressionMethod () const
virtual void CompressionMethod (CompressionMethodType _compMethod)
virtual KKStr CompressionMethodStr () const
virtual double Cost () const
virtual void Cost (double _cost)
virtual EncodingMethodType EncodingMethod () const
virtual KKStr EncodingMethodStr () const
virtual int32 ExamplesPerClass () const
virtual void ExamplesPerClass (int32 _examplesPerClass)
virtual const KKStr & FileName () const
virtual void FileName (const KKStr &_fileName)
virtual int32 MemoryConsumedEstimated () const
virtual KKStr ModelParamTypeStr () const
virtual bool NormalizeNominalFeatures () const
virtual void ParseCmdLinePost ()
Called after 'ParseCmdLine' is completed.
virtual float Prob () const
virtual void Prob (float _prob)
virtual void ReadXML (KKStr &_fileName, bool &_successful)
virtual void ReadXML (istream &i)
virtual void UnBalancedBits (int32 _unBalancedBits)
virtual void UnBalancedBitsStr (const KKStr &_unBalancedBitsStr)
virtual bool ValidParam () const
virtual void ValidParam (bool _validParam)
virtual void WriteXML (std::ostream &o) const
Additional Inherited Members
Static Public Member Functions inherited from MLL::ModelParam
static CompressionMethodType CompressionMethodFromStr (const KKStr &compressionMethodStr)
static KKStr CompressionMethodToStr (CompressionMethodType compressionMethod)
static ModelParamPtr CreateModelParam (istream &i, FileDescPtr _fileDesc, RunLog &_log)
static EncodingMethodType EncodingMethodFromStr (const KKStr &encodingMethodStr)
static KKStr EncodingMethodToStr (EncodingMethodType encodingMethod)
static ModelParamTypes ModelParamTypeFromStr (const KKStr &_modelParamTypeStr)
static KKStr ModelParamTypeToStr (ModelParamTypes _modelParamType)
Protected Attributes inherited from MLL::ModelParam
FileDescPtr fileDesc
RunLog & log
Detailed Description
this class encapsulates are the information neccesary to build a SVMModel class.
         *
See Also
ModelSVM
SVM233
BinaryClassParms
Definition at line 32 of file ModelParamOldSVM.h.
Member Typedef Documentation
typedef ModelParamOldSVM* MLL::ModelParamOldSVM::ModelParamOldSVMPtr
Definition at line 35 of file ModelParamOldSVM.h.
typedef SVM233::svm_parameter MLL::ModelParamOldSVM::svm_parameter
Definition at line 36 of file ModelParamOldSVM.h.
Constructor & Destructor Documentation
MLL::ModelParamOldSVM::ModelParamOldSVM (FileDescPtr _fileDesc, RunLog & _log)
Referenced by Duplicate().
ModelParamOldSVM::ModelParamOldSVM (const ModelParamOldSVM & _param)
Definition at line 48 of file ModelParamOldSVM.cpp.
ModelParamOldSVM::~ModelParamOldSVM () virtual
Definition at line 59 of file ModelParamOldSVM.cpp.
Member Function Documentation
float ModelParamOldSVM::A_Param () const virtual
Reimplemented from MLL::ModelParam.
Definition at line 249 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::A_Param().
void ModelParamOldSVM::A_Param (float _A) virtual
Reimplemented from MLL::ModelParam.
Definition at line 72 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::A_Param(), and MLL::ModelParam::A_Param().
void ModelParamOldSVM::AddBinaryClassParms (BinaryClassParmsPtr binaryClassParms)
Definition at line 519 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::AddBinaryClassParms().
Referenced by C_Param().
void ModelParamOldSVM::AddBinaryClassParms (MLClassConstPtr class1, MLClassConstPtr class2, const svm_parameter & _param, const FeatureNumList & _selectedFeatures, float _weight)
Add a Binary parameters using svm_parametr cmd line str.
Typically used by TrainingConfiguration.
Definition at line 567 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::AddBinaryClassParms().
float ModelParamOldSVM::AvgMumOfFeatures () virtual
Definition at line 527 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::AvgMumOfFeatures().
const BinaryClassParmsListPtr ModelParamOldSVM::BinaryParmsList () const
Definition at line 80 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::BinaryParmsList().
Referenced by C_Param(), and MLL::TrainingConfiguration2::Save().
int32 ModelParamOldSVM::BitsToReduceBy () const virtual
Reimplemented from MLL::ModelParam.
Definition at line 256 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::BitsToReduceBy().
double ModelParamOldSVM::C_Param () const virtual
Reimplemented from MLL::ModelParam.
Definition at line 263 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::C_Param().
Referenced by C_Param(), and MLL::TrainingConfiguration2::C_Param().
double ModelParamOldSVM::C_Param (MLClassConstPtr class1, MLClassConstPtr class2) const virtual
Definition at line 124 of file ModelParamOldSVM.cpp.
References BinaryParmsList(), MLL::BinaryClassParms::C(), KKU::endl(), and MLL::BinaryClassParmsList::LookUp().
void ModelParamOldSVM::C_Param (double _CC) virtual
Reimplemented from MLL::ModelParam.
Definition at line 86 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::C_Param(), and MLL::ModelParam::Cost().
void ModelParamOldSVM::C_Param (MLClassConstPtr class1, MLClassConstPtr class2, double cParam) virtual
Definition at line 95 of file ModelParamOldSVM.cpp.
References AddBinaryClassParms(), BinaryParmsList(), MLL::BinaryClassParms::C(), SVM233::svm_parameter::C, C_Param(), KKU::endl(), MLL::BinaryClassParmsList::LookUp(), Param(), and SelectedFeatures().
ModelParamOldSVMPtr ModelParamOldSVM::Duplicate () const virtual
Implements MLL::ModelParam.
Definition at line 66 of file ModelParamOldSVM.cpp.
References ModelParamOldSVM().
void ModelParamOldSVM::EncodingMethod (SVM_EncodingMethod _encodingMethod) virtual
Definition at line 155 of file ModelParamOldSVM.cpp.
References MLL::ModelParam::EncodingMethod(), and MLL::SVMparam::EncodingMethod().
void ModelParamOldSVM::EncodingMethod (EncodingMethodType _encodingMethod) virtual
Reimplemented from MLL::ModelParam.
Definition at line 163 of file ModelParamOldSVM.cpp.
References MLL::ModelParam::EncodingMethod(), and MLL::SVMparam::EncodingMethod().
double ModelParamOldSVM::Gamma () const virtual
Reimplemented from MLL::ModelParam.
Definition at line 271 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::Gamma().
void ModelParamOldSVM::Gamma (double _gamma) virtual
Reimplemented from MLL::ModelParam.
Definition at line 170 of file ModelParamOldSVM.cpp.
References MLL::ModelParam::Gamma(), and MLL::SVMparam::Gamma().
void ModelParamOldSVM::Gamma_Param (double _gamma) virtual
Definition at line 178 of file ModelParamOldSVM.cpp.
References MLL::ModelParam::Gamma(), and MLL::SVMparam::Gamma().
FeatureNumList ModelParamOldSVM::GetFeatureNums (MLClassConstPtr class1, MLClassConstPtr class2) const
Definition at line 509 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::GetFeatureNums().
Referenced by MLL::TrainingConfiguration2::GetFeatureNums().
BinaryClassParmsPtr ModelParamOldSVM::GetParamtersToUseFor2ClassCombo (MLClassConstPtr class1, MLClassConstPtr class2)
Definition at line 500 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::GetParamtersToUseFor2ClassCombo().
SVM_KernalType ModelParamOldSVM::KernalType () const virtual
Definition at line 278 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::KernalType().
void ModelParamOldSVM::KernalType (SVM_KernalType _kernalType) virtual
Definition at line 185 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::KernalType().
SVM_MachineType ModelParamOldSVM::MachineType () const virtual
Definition at line 285 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::MachineType().
Referenced by MLL::TrainingConfiguration2::MachineType().
void ModelParamOldSVM::MachineType (SVM_MachineType _machineType) virtual
Definition at line 200 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::MachineType().
virtual ModelParamTypes MLL::ModelParamOldSVM::ModelParamType () const inline virtual
Implements MLL::ModelParam.
Definition at line 51 of file ModelParamOldSVM.h.
int32 ModelParamOldSVM::NumOfFeaturesAfterEncoding () const virtual
Reimplemented from MLL::ModelParam.
Definition at line 193 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::NumOfFeaturesAfterEncoding().
const svm_parameter & ModelParamOldSVM::Param () const virtual
Definition at line 291 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::Param().
Referenced by C_Param().
void ModelParamOldSVM::ParseCmdLine (KKStr _cmdLineStr, bool & _validFormat) virtual
Reimplemented from MLL::ModelParam.
Definition at line 336 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::A_Param(), MLL::ModelParam::A_Param(), MLL::ModelParam::BitsToReduceBy(), MLL::SVMparam::BitsToReduceBy(), MLL::ModelParam::C_Param(), MLL::SVMparam::C_Param(), MLL::ModelParam::CompressionMethod(), MLL::SVMparam::CompressionMethod(), MLL::ModelParam::EncodingMethod(), MLL::SVMparam::EncodingMethod(), KKU::endl(), KKU::KKStr::ExtractToken(), MLL::ModelParam::Gamma(), MLL::SVMparam::Gamma(), KKU::KKStr::Len(), KKU::RunLog::Level(), MLL::ModelParam::log, KKU::KKStr::TrimLeft(), MLL::ModelParam::UnBalancedBits(), MLL::SVMparam::UnBalancedBits(), MLL::ModelParam::UnBalancedBitsStr(), MLL::SVMparam::UnBalancedBitsStr(), KKU::KKStr::Upper(), MLL::ModelParam::ValidParam(), MLL::ModelParam::WeightBitReduction(), and MLL::SVMparam::WeightBitReduction().
Referenced by MLL::TrainingConfiguration2::CreateFromDirectoryStructure().
void ModelParamOldSVM::ReadSpecificImplementationXML (istream & i) virtual
Implements MLL::ModelParam.
Definition at line 473 of file ModelParamOldSVM.cpp.
References KKU::endl(), KKU::KKStr::EqualIgnoreCase(), KKU::KKStr::ExtractQuotedStr(), KKU::RunLog::Level(), MLL::ModelParam::log, MLL::SVMparam::ReadXML(), and KKU::KKStr::Upper().
float ModelParamOldSVM::SamplingRate () const virtual
Definition at line 297 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::SamplingRate().
void ModelParamOldSVM::SamplingRate (float _samplingRate) virtual
Definition at line 207 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::SamplingRate().
const FeatureNumList & ModelParamOldSVM::SelectedFeatures () const virtual
Reimplemented from MLL::ModelParam.
Definition at line 220 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::SelectedFeatures().
Referenced by C_Param().
void ModelParamOldSVM::SelectedFeatures (const FeatureNumList & _selectedFeatures) virtual
Reimplemented from MLL::ModelParam.
Definition at line 213 of file ModelParamOldSVM.cpp.
References MLL::ModelParam::SelectedFeatures(), and MLL::SVMparam::SelectedFeatures().
SVM_SelectionMethod ModelParamOldSVM::SelectionMethod () const virtual
Definition at line 303 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::SelectionMethod().
Referenced by MLL::TrainingConfiguration2::SelectionMethod().
void ModelParamOldSVM::SelectionMethod (SVM_SelectionMethod _selectionMethod) virtual
Definition at line 226 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::SelectionMethod().
void ModelParamOldSVM::SetBinaryClassFields (MLClassConstPtr class1, MLClassConstPtr class2, const svm_parameter & _param, const FeatureNumList & _features, float _weight)
Definition at line 549 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::SetBinaryClassFields().
Referenced by MLL::TrainingConfiguration2::SetBinaryClassFields().
void ModelParamOldSVM::SetFeatureNums (MLClassConstPtr class1, MLClassConstPtr class2, const FeatureNumList & _features, float _weight = -1)
Definition at line 536 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::SetFeatureNums().
Referenced by MLL::TrainingConfiguration2::SetFeatureNums().
SVMparamPtr ModelParamOldSVM::SvmParameters () const virtual
Definition at line 242 of file ModelParamOldSVM.cpp.
Referenced by MLL::TrainingConfiguration2::SVMparamREF(), and MLL::ModelOldSVM::TrainModel().
KKStr ModelParamOldSVM::SvmParamToString (const svm_parameter & _param) const
Convert a svm_parameter struct to a cmdline str.
Definition at line 431 of file ModelParamOldSVM.cpp.
References KKU::endl(), KKU::RunLog::Level(), MLL::ModelParam::log, and SVM233::svm_parameter::ToCmdLineStr().
KKStr ModelParamOldSVM::ToCmdLineStr () const virtual
Convert all parameters to a command line string.
Reimplemented from MLL::ModelParam.
Definition at line 448 of file ModelParamOldSVM.cpp.
References KKU::endl(), KKU::RunLog::Level(), MLL::ModelParam::log, and MLL::SVMparam::ToString().
int32 ModelParamOldSVM::UnBalancedBits () const virtual
Reimplemented from MLL::ModelParam.
Definition at line 309 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::UnBalancedBits().
KKStr ModelParamOldSVM::UnBalancedBitsStr () const virtual
Reimplemented from MLL::ModelParam.
Definition at line 316 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::UnBalancedBitsStr().
bool ModelParamOldSVM::UseProbabilityToBreakTies () const virtual
Definition at line 323 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::UseProbabilityToBreakTies().
bool ModelParamOldSVM::WeightBitReduction () const virtual
Reimplemented from MLL::ModelParam.
Definition at line 329 of file ModelParamOldSVM.cpp.
References MLL::SVMparam::WeightBitReduction().
void ModelParamOldSVM::WeightBitReduction (bool _weightBitReduction) virtual
Reimplemented from MLL::ModelParam.
Definition at line 233 of file ModelParamOldSVM.cpp.
References MLL::ModelParam::WeightBitReduction(), and MLL::SVMparam::WeightBitReduction().
void ModelParamOldSVM::WriteSpecificImplementationXML (std::ostream & o) const virtual
Implements MLL::ModelParam.
Definition at line 461 of file ModelParamOldSVM.cpp.
References KKU::endl(), KKU::RunLog::Level(), MLL::ModelParam::log, and MLL::SVMparam::WriteXML().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ModelParamOldSVM.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ModelParamOldSVM.cpp