Pices: KKU::CmdLineExpander Class Reference
KKU::CmdLineExpander Class Reference
Expands command line parameters, by parsing for special parameters and expanding them to their full value.
#include <CmdLineExpander.h>
Public Member Functions
CmdLineExpander (const KKStr &_applicationName, RunLog &_log, int32 argc, char **argv)
Construct using the parameters passed through on the command line into main().
CmdLineExpander (const KKStr &_applicationName, RunLog &_log, const KKStr &_cmdLine)
Pass in the command line as a single string.
~CmdLineExpander ()
void ExpandCmdLine (int32 argc, char **argv)
const VectorKKStr & ExpandedParameters () const
const KKStr & LogFileName () const
bool ParmsGood () const
Detailed Description
Expands command line parameters, by parsing for special parameters and expanding them to their full value.
A couple of parameters are specifically searched for and processed. The "-log" and "-CmdFile" parameters. The "-log" parameter is processed for the log file. The "-CmdFile" parameter will expand into multiple parameters. This is done by reading in the text file specified by the "-CmdLine" parameter. Each line in the text file processed for parameters that are then added to the original cmdline in place of '-CmdFile'. The cmd line parameters in the text file can specify another -CmdFile" parameter as long as it does not cause a circular loop.
Author
Kurt Kramer
Definition at line 27 of file CmdLineExpander.h.
Constructor & Destructor Documentation
CmdLineExpander::CmdLineExpander (const KKStr & _applicationName, RunLog & _log, int32 argc, char ** argv)
Construct using the parameters passed through on the command line into main().
Definition at line 37 of file CmdLineExpander.cpp.
References ExpandCmdLine().
CmdLineExpander::CmdLineExpander (const KKStr & _applicationName, RunLog & _log, const KKStr & _cmdLine)
Pass in the command line as a single string.
Will parse first before processing.
Definition at line 53 of file CmdLineExpander.cpp.
References KKU::KKStr::Empty(), KKU::KKStr::ExtractQuotedStr(), KKU::KKStr::TrimLeft(), and KKU::KKStr::TrimRight().
CmdLineExpander::~CmdLineExpander ()
Definition at line 82 of file CmdLineExpander.cpp.
Member Function Documentation
void CmdLineExpander::ExpandCmdLine (int32 argc, char ** argv)
Definition at line 90 of file CmdLineExpander.cpp.
Referenced by CmdLineExpander().
const VectorKKStr& KKU::CmdLineExpander::ExpandedParameters () const inline
Definition at line 54 of file CmdLineExpander.h.
Referenced by ImageExtractionManager::ExtractionParms::ParseCmdLine(), KKU::Application::ProcessCmdLineParameters(), and CrossValidationApp::ProcessCmdLineParameters().
const KKStr& KKU::CmdLineExpander::LogFileName () const inline
Definition at line 55 of file CmdLineExpander.h.
Referenced by KKU::Application::ProcessCmdLineParameters().
bool KKU::CmdLineExpander::ParmsGood () const inline
Definition at line 56 of file CmdLineExpander.h.
Referenced by ImageExtractionManager::ExtractionParms::ExtractionParms(), KKU::Application::ProcessCmdLineParameters(), and CrossValidationApp::ProcessCmdLineParameters().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/CmdLineExpander.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/CmdLineExpander.cpp