Pices: MLL::CrossValidationVoting Class Reference
MLL::CrossValidationVoting Class Reference
#include <CrossValidationVoting.h>
Public Member Functions
CrossValidationVoting (TrainingConfigurationList2Ptr _configs, FeatureVectorListPtr _examples, MLClassConstListPtr _mlClasses, int32 _numOfFolds, bool _featuresAreAlreadyNormalized, FileDescPtr _fileDesc, RunLog &_log)
~CrossValidationVoting ()
float Accuracy ()
double ClassificationTime () const
ConfusionMatrix2Ptr ConfussionMatrix ()
float FoldAccuracy (int32 foldNum) const
KKStr FoldAccuracysToStr () const
KKStr FoldStr () const
int32 NumOfSupportVectors () const
int32 ReductionPostExampleCount () const
int32 ReductionPreExampleCount () const
float ReductionRatio () const
double ReductionTime () const
void RunCrossValidation ()
void RunValidationOnly (FeatureVectorListPtr validationData, bool *classedCorrectly=NULL)
double TrainingTime () const
Detailed Description
Definition at line 92 of file CrossValidationVoting.h.
Constructor & Destructor Documentation
CrossValidationVoting::CrossValidationVoting (TrainingConfigurationList2Ptr _configs, FeatureVectorListPtr _examples, MLClassConstListPtr _mlClasses, int32 _numOfFolds, bool _featuresAreAlreadyNormalized, FileDescPtr _fileDesc, RunLog & _log)
Definition at line 35 of file CrossValidationVoting.cpp.
CrossValidationVoting::~CrossValidationVoting ()
Definition at line 73 of file CrossValidationVoting.cpp.
Member Function Documentation
float CrossValidationVoting::Accuracy ()
Definition at line 498 of file CrossValidationVoting.cpp.
References MLL::ConfusionMatrix2::Accuracy().
double MLL::CrossValidationVoting::ClassificationTime () const inline
Definition at line 116 of file CrossValidationVoting.h.
ConfusionMatrix2Ptr MLL::CrossValidationVoting::ConfussionMatrix () inline
Definition at line 113 of file CrossValidationVoting.h.
float CrossValidationVoting::FoldAccuracy (int32 foldNum) const
Definition at line 527 of file CrossValidationVoting.cpp.
References KKU::endl(), KKU::RunLog::Level(), and KKU::osWaitForEnter().
KKStr CrossValidationVoting::FoldAccuracysToStr () const
Definition at line 509 of file CrossValidationVoting.cpp.
References KKU::StrFormatDouble().
KKStr CrossValidationVoting::FoldStr () const
Definition at line 559 of file CrossValidationVoting.cpp.
References x.
int32 MLL::CrossValidationVoting::NumOfSupportVectors () const inline
Definition at line 120 of file CrossValidationVoting.h.
int32 MLL::CrossValidationVoting::ReductionPostExampleCount () const inline
Definition at line 122 of file CrossValidationVoting.h.
int32 MLL::CrossValidationVoting::ReductionPreExampleCount () const inline
Definition at line 121 of file CrossValidationVoting.h.
float CrossValidationVoting::ReductionRatio () const
Definition at line 153 of file CrossValidationVoting.cpp.
double MLL::CrossValidationVoting::ReductionTime () const inline
Definition at line 124 of file CrossValidationVoting.h.
void CrossValidationVoting::RunCrossValidation ()
Definition at line 165 of file CrossValidationVoting.cpp.
References KKU::endl(), KKU::RunLog::Level(), MLL::FeatureVectorList::PushOnBack(), and x.
void CrossValidationVoting::RunValidationOnly (FeatureVectorListPtr validationData, bool * classedCorrectly = NULL)
Definition at line 241 of file CrossValidationVoting.cpp.
References KKU::endl(), and KKU::RunLog::Level().
double MLL::CrossValidationVoting::TrainingTime () const inline
Definition at line 125 of file CrossValidationVoting.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/CrossValidationVoting.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/CrossValidationVoting.cpp