Pices: SipperDiskUtilities.SipperDateStamp Class Reference
SipperDiskUtilities.SipperDateStamp Class Reference
Public Member Functions
SipperDateStamp (DateTime dt)
SipperDateStamp (byte[] buffer, ref int nextIntex)
SipperDateStamp (string dateStr)
void FillBuffer (byte[] buffer, ref int nextIndex)
bool Valid ()
Static Public Member Functions
static int BuffSpaceNeeded ()
Properties
int Day [get]
int Month [get]
int Year [get]
Detailed Description
Definition at line 9 of file SipperDateStamp.cs.
Constructor & Destructor Documentation
SipperDiskUtilities.SipperDateStamp.SipperDateStamp (DateTime dt) inline
Definition at line 17 of file SipperDateStamp.cs.
SipperDiskUtilities.SipperDateStamp.SipperDateStamp (byte[] buffer, ref int nextIntex) inline
Definition at line 27 of file SipperDateStamp.cs.
SipperDiskUtilities.SipperDateStamp.SipperDateStamp (string dateStr) inline
Definition at line 38 of file SipperDateStamp.cs.
References PicesInterface::PicesKKStr.StrToByte(), and PicesInterface::PicesKKStr.StrToUint().
Member Function Documentation
static int SipperDiskUtilities.SipperDateStamp.BuffSpaceNeeded () inline static
Definition at line 99 of file SipperDateStamp.cs.
Referenced by SipperDiskUtilities.SipperDateTimeStamp.BuffSpaceNeeded().
void SipperDiskUtilities.SipperDateStamp.FillBuffer (byte[] buffer, ref int nextIndex) inline
Definition at line 105 of file SipperDateStamp.cs.
Referenced by SipperDiskUtilities.SipperDateTimeStamp.FillBuffer().
bool SipperDiskUtilities.SipperDateStamp.Valid () inline
Definition at line 87 of file SipperDateStamp.cs.
Referenced by SipperDiskUtilities.SipperDateTimeStamp.Valid().
Property Documentation
int SipperDiskUtilities.SipperDateStamp.Day get
Definition at line 83 of file SipperDateStamp.cs.
int SipperDiskUtilities.SipperDateStamp.Month get
Definition at line 82 of file SipperDateStamp.cs.
int SipperDiskUtilities.SipperDateStamp.Year get
Definition at line 81 of file SipperDateStamp.cs.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperDiskUtilities/SipperDateStamp.cs