Pices: SipperHardware::SipperFile Class Reference
SipperHardware::SipperFile Class Reference
#include <SipperFile.h>
Public Types
typedef KKU::int32 int32
typedef KKU::int64 int64
typedef SipperFile * SipperFilePtr
typedef KKU::uint32 uint32
typedef KKU::uint64 uint64
Public Member Functions
SipperFile (const KKStr &_sipperFileName)
SipperFile (KKStrParser &str)
~SipperFile ()
void AssignCtdExternalInstruments (const KKStr &rootName)
const KKStr & CruiseName () const
void CruiseName (const KKStr &_cruiseName)
const KKStr & CtdExt0 () const
void CtdExt0 (const KKStr &_ctdExt0)
const KKStr & CtdExt1 () const
void CtdExt1 (const KKStr &_ctdExt1)
const KKStr & CtdExt2 () const
void CtdExt2 (const KKStr &_ctdExt2)
const KKStr & CtdExt3 () const
void CtdExt3 (const KKStr &_ctdExt3)
const KKU::DateTime & DateTimeStart () const
void DateTimeStart (const KKU::DateTime &_dateTimeStart)
const KKStr & DeploymentNum () const
void DeploymentNum (const KKStr &_deploymentNum)
float Depth () const
void Depth (float _depth)
const KKStr & Description () const
void Description (const KKStr &_description)
uint32 ExtractionScanLineEnd () const
void ExtractionScanLineEnd (uint32 _extractionScanLineEnd)
uint32 ExtractionScanLineStart () const
void ExtractionScanLineStart (uint32 _extractionScanLineStart)
char ExtractionStatus () const
void ExtractionStatus (char _extractionStatus)
double Latitude () const
void Latitude (double _latitude)
double Longitude () const
void Longitude (double _longitde)
uint32 NumScanLines () const
void NumScanLines (uint32 _numScanLines)
void ParseTabDelStr (KKStrParser &parser)
void ReFresh (const SipperFile &sf)
float ScanRate () const
void ScanRate (float _scanRate)
int32 SipperFileId () const
void SipperFileId (int32 _sipperFileId)
const KKStr & SipperFileName () const
void SipperFileName (const KKStr &_sipperFileName)
int64 SizeInBytes () const
void SizeInBytes (int64 _sizeInBytes)
const InstrumentPtr Sp0 () const
void Sp0 (const InstrumentPtr _sp0)
KKStr Sp0ShortName () const
const InstrumentPtr Sp1 () const
void Sp1 (const InstrumentPtr _sp1)
KKStr Sp1ShortName () const
const InstrumentPtr Sp2 () const
void Sp2 (const InstrumentPtr _sp2)
KKStr Sp2ShortName () const
const InstrumentPtr Sp3 () const
void Sp3 (const InstrumentPtr _sp3)
KKStr Sp3ShortName () const
const KKStr & StationName () const
void StationName (const KKStr &_stationName)
KKStr ToTabDelStr () const
Detailed Description
Definition at line 12 of file SipperFile.h.
Member Typedef Documentation
typedef KKU::int32 SipperHardware::SipperFile::int32
Definition at line 17 of file SipperFile.h.
typedef KKU::int64 SipperHardware::SipperFile::int64
Definition at line 19 of file SipperFile.h.
typedef SipperFile* SipperHardware::SipperFile::SipperFilePtr
Definition at line 15 of file SipperFile.h.
typedef KKU::uint32 SipperHardware::SipperFile::uint32
Definition at line 18 of file SipperFile.h.
typedef KKU::uint64 SipperHardware::SipperFile::uint64
Definition at line 20 of file SipperFile.h.
Constructor & Destructor Documentation
SipperHardware::SipperFile::SipperFile (const KKStr & _sipperFileName)
SipperHardware::SipperFile::SipperFile (KKStrParser & str)
SipperHardware::SipperFile::~SipperFile ()
Member Function Documentation
void SipperHardware::SipperFile::AssignCtdExternalInstruments (const KKStr & rootName)
Referenced by MLL::DataBase::InstrumentDataSaveListForOneSipperFile().
const KKStr& SipperHardware::SipperFile::CruiseName () const inline
Definition at line 34 of file SipperFile.h.
Referenced by MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
void SipperHardware::SipperFile::CruiseName (const KKStr & _cruiseName) inline
Definition at line 71 of file SipperFile.h.
const KKStr& SipperHardware::SipperFile::CtdExt0 () const inline
Definition at line 48 of file SipperFile.h.
Referenced by MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
void SipperHardware::SipperFile::CtdExt0 (const KKStr & _ctdExt0) inline
Definition at line 84 of file SipperFile.h.
const KKStr& SipperHardware::SipperFile::CtdExt1 () const inline
Definition at line 49 of file SipperFile.h.
Referenced by MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
void SipperHardware::SipperFile::CtdExt1 (const KKStr & _ctdExt1) inline
Definition at line 85 of file SipperFile.h.
const KKStr& SipperHardware::SipperFile::CtdExt2 () const inline
Definition at line 50 of file SipperFile.h.
Referenced by MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
void SipperHardware::SipperFile::CtdExt2 (const KKStr & _ctdExt2) inline
Definition at line 86 of file SipperFile.h.
const KKStr& SipperHardware::SipperFile::CtdExt3 () const inline
Definition at line 51 of file SipperFile.h.
Referenced by MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
void SipperHardware::SipperFile::CtdExt3 (const KKStr & _ctdExt3) inline
Definition at line 87 of file SipperFile.h.
const KKU::DateTime& SipperHardware::SipperFile::DateTimeStart () const inline
Definition at line 41 of file SipperFile.h.
Referenced by MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
void SipperHardware::SipperFile::DateTimeStart (const KKU::DateTime & _dateTimeStart) inline
Definition at line 77 of file SipperFile.h.
const KKStr& SipperHardware::SipperFile::DeploymentNum () const inline
Definition at line 36 of file SipperFile.h.
Referenced by MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
void SipperHardware::SipperFile::DeploymentNum (const KKStr & _deploymentNum) inline
Definition at line 73 of file SipperFile.h.
float SipperHardware::SipperFile::Depth () const inline
Definition at line 58 of file SipperFile.h.
Referenced by MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
void SipperHardware::SipperFile::Depth (float _depth) inline
Definition at line 94 of file SipperFile.h.
const KKStr& SipperHardware::SipperFile::Description () const inline
Definition at line 37 of file SipperFile.h.
Referenced by SipperHardware::SipperFileList::GetListOfSipperFilesWeCanFind(), MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
void SipperHardware::SipperFile::Description (const KKStr & _description) inline
Definition at line 74 of file SipperFile.h.
uint32 SipperHardware::SipperFile::ExtractionScanLineEnd () const inline
Definition at line 62 of file SipperFile.h.
Referenced by ImageExtractionManager::ExtractionParms::ParseCmdLine(), MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
void SipperHardware::SipperFile::ExtractionScanLineEnd (uint32 _extractionScanLineEnd) inline
Definition at line 98 of file SipperFile.h.
uint32 SipperHardware::SipperFile::ExtractionScanLineStart () const inline
Definition at line 61 of file SipperFile.h.
Referenced by ImageExtractionManager::ExtractionParms::ParseCmdLine(), MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
void SipperHardware::SipperFile::ExtractionScanLineStart (uint32 _extractionScanLineStart) inline
Definition at line 97 of file SipperFile.h.
char SipperHardware::SipperFile::ExtractionStatus () const inline
Definition at line 60 of file SipperFile.h.
Referenced by MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
void SipperHardware::SipperFile::ExtractionStatus (char _extractionStatus) inline
Definition at line 96 of file SipperFile.h.
double SipperHardware::SipperFile::Latitude () const inline
Definition at line 38 of file SipperFile.h.
Referenced by MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
void SipperHardware::SipperFile::Latitude (double _latitude) inline
Definition at line 75 of file SipperFile.h.
double SipperHardware::SipperFile::Longitude () const inline
Definition at line 39 of file SipperFile.h.
Referenced by MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
void SipperHardware::SipperFile::Longitude (double _longitde) inline
Definition at line 76 of file SipperFile.h.
uint32 SipperHardware::SipperFile::NumScanLines () const inline
Definition at line 54 of file SipperFile.h.
Referenced by MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
void SipperHardware::SipperFile::NumScanLines (uint32 _numScanLines) inline
Definition at line 90 of file SipperFile.h.
void SipperHardware::SipperFile::ParseTabDelStr (KKStrParser & parser)
void SipperHardware::SipperFile::ReFresh (const SipperFile & sf)
Referenced by SipperHardware::SipperFileList::Load().
float SipperHardware::SipperFile::ScanRate () const inline
Definition at line 56 of file SipperFile.h.
Referenced by SipperHardware::InstrumentDataList::CreateFromSipperFile(), SipperHardware::InstrumentDataList::GetVolumePerMeterProfile(), MLL::DataBase::InstrumentDataLoad(), MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
void SipperHardware::SipperFile::ScanRate (float _scanRate) inline
Definition at line 92 of file SipperFile.h.
int32 SipperHardware::SipperFile::SipperFileId () const inline
Definition at line 31 of file SipperFile.h.
Referenced by MLL::DataBase::SipperFileInsert().
void SipperHardware::SipperFile::SipperFileId (int32 _sipperFileId) inline
Definition at line 69 of file SipperFile.h.
const KKStr& SipperHardware::SipperFile::SipperFileName () const inline
Definition at line 33 of file SipperFile.h.
Referenced by SipperHardware::SipperFileOracle::AddSipperFileEntry(), DetermineCropSettingsForDeployment(), SipperHardware::SipperFileList::Load(), SipperHardware::SipperFileList::LookUpBySipperFileName(), MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
void SipperHardware::SipperFile::SipperFileName (const KKStr & _sipperFileName) inline
Definition at line 70 of file SipperFile.h.
int64 SipperHardware::SipperFile::SizeInBytes () const inline
Definition at line 53 of file SipperFile.h.
Referenced by MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
void SipperHardware::SipperFile::SizeInBytes (int64 _sizeInBytes) inline
Definition at line 89 of file SipperFile.h.
const InstrumentPtr SipperHardware::SipperFile::Sp0 () const inline
Definition at line 43 of file SipperFile.h.
void SipperHardware::SipperFile::Sp0 (const InstrumentPtr _sp0) inline
Definition at line 79 of file SipperFile.h.
KKStr SipperHardware::SipperFile::Sp0ShortName () const
Referenced by MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
const InstrumentPtr SipperHardware::SipperFile::Sp1 () const inline
Definition at line 44 of file SipperFile.h.
void SipperHardware::SipperFile::Sp1 (const InstrumentPtr _sp1) inline
Definition at line 80 of file SipperFile.h.
KKStr SipperHardware::SipperFile::Sp1ShortName () const
Referenced by MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
const InstrumentPtr SipperHardware::SipperFile::Sp2 () const inline
Definition at line 45 of file SipperFile.h.
void SipperHardware::SipperFile::Sp2 (const InstrumentPtr _sp2) inline
Definition at line 81 of file SipperFile.h.
KKStr SipperHardware::SipperFile::Sp2ShortName () const
Referenced by MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
const InstrumentPtr SipperHardware::SipperFile::Sp3 () const inline
Definition at line 46 of file SipperFile.h.
void SipperHardware::SipperFile::Sp3 (const InstrumentPtr _sp3) inline
Definition at line 82 of file SipperFile.h.
KKStr SipperHardware::SipperFile::Sp3ShortName () const
Referenced by MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
const KKStr& SipperHardware::SipperFile::StationName () const inline
Definition at line 35 of file SipperFile.h.
Referenced by MLL::DataBase::SipperFileInsert(), and MLL::DataBase::SipperFileUpdate().
void SipperHardware::SipperFile::StationName (const KKStr & _stationName) inline
Definition at line 72 of file SipperFile.h.
KKStr SipperHardware::SipperFile::ToTabDelStr () const
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/SipperFile.h