Pices: SipperFile.SipperBaseFile Class Reference
SipperFile.SipperBaseFile Class Reference
Public Member Functions
SipperBaseFile (Stream _stream, InstrumentDataManager _instrumentDataManager)
SipperBaseFile (string _fileName, InstrumentDataManager _instrumentDataManager)
byte[][] AllocateFrame ()
byte[][] CreateRatser (int scanLineStart, int numScanLines)
virtual void Dispose ()
bool Eof ()
bool EofReached ()
virtual long EstimatedNumberOfScanLines ()
long FileSizeInBytes ()
void FrameBytesOffsetsUpdateThreadStart (InstrumentDataList _history)
void FrameBytesOffsetsUpdateThreadTerminate ()
void FrameRead (int frameNum, SipperFrame frame, ref bool found)
int LargestKnowmFrameNum ()
long LargestKnownScanLine ()
virtual int LengthNextScanLine ()
void ReadNextFrame (byte[][] frame)
virtual void ReadNextScanLine (byte[] scanLine)
virtual int ScanLineSize ()
virtual void SkipNextScanLine ()
bool ValidateFormat ()
Public Attributes
const int PixelsPerScanLine = 4096
const int ScanLinesPerFrame = 4096
Protected Member Functions
byte[] GetNextBuff (uint buffLen)
byte GetNextByte ()
ushort GetNextRecord ()
uint GetNextUint ()
Protected Attributes
bool eof = false
InstrumentDataManager instrumentDataManager = null
long lastScanLineNum = 0
Detailed Description
Definition at line 11 of file SipperBaseFile.cs.
Constructor & Destructor Documentation
SipperFile.SipperBaseFile.SipperBaseFile (Stream _stream, InstrumentDataManager _instrumentDataManager) inline
Definition at line 56 of file SipperBaseFile.cs.
References SipperFile.SipperBaseFile.instrumentDataManager.
SipperFile.SipperBaseFile.SipperBaseFile (string _fileName, InstrumentDataManager _instrumentDataManager) inline
Definition at line 76 of file SipperBaseFile.cs.
References SipperFile.SipperBaseFile.instrumentDataManager.
Member Function Documentation
byte [][] SipperFile.SipperBaseFile.AllocateFrame () inline
Definition at line 334 of file SipperBaseFile.cs.
References SipperFile.SipperBaseFile.PixelsPerScanLine, SipperFile.SipperBaseFile.ScanLinesPerFrame, and x.
byte [][] SipperFile.SipperBaseFile.CreateRatser (int scanLineStart, int numScanLines) inline
Definition at line 707 of file SipperBaseFile.cs.
References SipperFile.SipperBaseFile.eof, SipperFile.SipperBaseFile.PixelsPerScanLine, and SipperFile.SipperBaseFile.ReadNextScanLine().
virtual void SipperFile.SipperBaseFile.Dispose () inline virtual
Reimplemented in SipperFile.SipperBuff4Bit, SipperFile.Sipper3File, SipperFile.Sipper2File, and SipperFile.SipperFileSimple.
Definition at line 101 of file SipperBaseFile.cs.
References SipperFile.SipperBaseFile.FrameBytesOffsetsUpdateThreadTerminate().
Referenced by SipperFile.SipperFileBuffered.Dispose().
bool SipperFile.SipperBaseFile.Eof () inline
Definition at line 44 of file SipperBaseFile.cs.
References SipperFile.SipperBaseFile.eof.
bool SipperFile.SipperBaseFile.EofReached () inline
Definition at line 45 of file SipperBaseFile.cs.
Referenced by SipperFile.SipperFileBuffered.GetScanLines().
virtual long SipperFile.SipperBaseFile.EstimatedNumberOfScanLines () inline virtual
Definition at line 122 of file SipperBaseFile.cs.
References SipperFile.SipperBaseFile.ScanLinesPerFrame.
Referenced by SipperFile.SipperFileBuffered.EstimatedNumberOfScanLines().
long SipperFile.SipperBaseFile.FileSizeInBytes () inline
Definition at line 46 of file SipperBaseFile.cs.
Referenced by SipperFile.SipperFileBuffered.FileSizeInBytes().
void SipperFile.SipperBaseFile.FrameBytesOffsetsUpdateThreadStart (InstrumentDataList _history) inline
Definition at line 550 of file SipperBaseFile.cs.
Referenced by SipperFile.SipperFileBuffered.FrameBytesOffsetsUpdateThreadStart().
void SipperFile.SipperBaseFile.FrameBytesOffsetsUpdateThreadTerminate () inline
Definition at line 567 of file SipperBaseFile.cs.
Referenced by SipperFile.SipperBaseFile.Dispose(), and SipperFile.SipperFileBuffered.FrameBytesOffsetsUpdateThreadTerminate().
void SipperFile.SipperBaseFile.FrameRead (int frameNum, SipperFrame frame, ref bool found) inline
Definition at line 346 of file SipperBaseFile.cs.
References SipperFile.SipperBaseFile.eof, SipperFile.SipperFrame.FrameNum, SipperFile.SipperBaseFile.lastScanLineNum, SipperFile.SipperBaseFile.ReadNextFrame(), SipperFile.SipperFrame.ScanLineFirst, SipperFile.SipperFrame.ScanLineLast, SipperFile.SipperFrame.ScanLines, and SipperFile.SipperBaseFile.ScanLinesPerFrame.
byte [] SipperFile.SipperBaseFile.GetNextBuff (uint buffLen) inline protected
Definition at line 244 of file SipperBaseFile.cs.
References SipperFile.SipperBaseFile.eof.
Referenced by SipperFile.SipperFileSimple.LengthNextScanLine(), SipperFile.SipperBuff4Bit.LengthNextScanLine(), SipperFile.SipperBuff4Bit.ReadNextScanLine(), and SipperFile.SipperFileSimple.SkipNextScanLine().
byte SipperFile.SipperBaseFile.GetNextByte () inline protected
Definition at line 208 of file SipperBaseFile.cs.
References SipperFile.SipperBaseFile.eof.
Referenced by SipperFile.SipperBuff4Bit.LengthNextScanLine(), SipperFile.SipperFileSimple.ReadNextScanLine(), and SipperFile.SipperBuff4Bit.ReadNextScanLine().
ushort SipperFile.SipperBaseFile.GetNextRecord () inline protected
Definition at line 267 of file SipperBaseFile.cs.
References SipperFile.SipperBaseFile.eof.
Referenced by SipperFile.Sipper2File.LengthNextScanLine(), SipperFile.Sipper3File.LengthNextScanLine(), SipperFile.Sipper2File.ReadNextScanLine(), SipperFile.Sipper3File.ReadNextScanLine(), SipperFile.Sipper3File.SaveRawCtdData(), SipperFile.Sipper2File.SkipNextScanLine(), and SipperFile.Sipper3File.SkipNextScanLine().
uint SipperFile.SipperBaseFile.GetNextUint () inline protected
Definition at line 226 of file SipperBaseFile.cs.
References SipperFile.SipperBaseFile.eof.
Referenced by SipperFile.SipperFileSimple.LengthNextScanLine(), SipperFile.SipperFileSimple.ReadNextScanLine(), and SipperFile.SipperFileSimple.SkipNextScanLine().
int SipperFile.SipperBaseFile.LargestKnowmFrameNum () inline
Definition at line 47 of file SipperBaseFile.cs.
Referenced by SipperFile.SipperFileBuffered.LargestKnowmFrameNum().
long SipperFile.SipperBaseFile.LargestKnownScanLine () inline
Definition at line 48 of file SipperBaseFile.cs.
Referenced by SipperFile.SipperFileBuffered.GetScanLines(), and SipperFile.SipperFileBuffered.LargestKnownScanLine().
virtual int SipperFile.SipperBaseFile.LengthNextScanLine () inline virtual
Reimplemented in SipperFile.SipperBuff4Bit, SipperFile.Sipper3File, SipperFile.Sipper2File, and SipperFile.SipperFileSimple.
Definition at line 315 of file SipperBaseFile.cs.
Referenced by SipperFile.SipperBaseFile.ValidateFormat().
void SipperFile.SipperBaseFile.ReadNextFrame (byte frame[][]) inline
Definition at line 460 of file SipperBaseFile.cs.
References SipperFile.SipperBaseFile.eof, SipperFile.SipperBaseFile.lastScanLineNum, and SipperFile.SipperBaseFile.ReadNextScanLine().
Referenced by SipperFile.SipperBaseFile.FrameRead().
virtual void SipperFile.SipperBaseFile.ReadNextScanLine (byte[] scanLine) inline virtual
Reimplemented in SipperFile.SipperBuff4Bit, SipperFile.Sipper3File, SipperFile.Sipper2File, and SipperFile.SipperFileSimple.
Definition at line 327 of file SipperBaseFile.cs.
Referenced by SipperFile.SipperBaseFile.CreateRatser(), and SipperFile.SipperBaseFile.ReadNextFrame().
virtual int SipperFile.SipperBaseFile.ScanLineSize () inline virtual
Definition at line 135 of file SipperBaseFile.cs.
Referenced by SipperFile.SipperFileBuffered.ScanLineSize().
virtual void SipperFile.SipperBaseFile.SkipNextScanLine () inline virtual
Reimplemented in SipperFile.SipperBuff4Bit, SipperFile.Sipper3File, SipperFile.Sipper2File, and SipperFile.SipperFileSimple.
Definition at line 321 of file SipperBaseFile.cs.
bool SipperFile.SipperBaseFile.ValidateFormat () inline
Definition at line 288 of file SipperBaseFile.cs.
References SipperFile.SipperBaseFile.eof, SipperFile.SipperBaseFile.lastScanLineNum, SipperFile.SipperBaseFile.LengthNextScanLine(), and x.
Member Data Documentation
bool SipperFile.SipperBaseFile.eof = false protected
Definition at line 17 of file SipperBaseFile.cs.
Referenced by SipperFile.SipperBaseFile.CreateRatser(), SipperFile.SipperBaseFile.Eof(), SipperFile.SipperBaseFile.FrameRead(), SipperFile.SipperBaseFile.GetNextBuff(), SipperFile.SipperBaseFile.GetNextByte(), SipperFile.SipperBaseFile.GetNextRecord(), SipperFile.SipperBaseFile.GetNextUint(), SipperFile.Sipper2File.LengthNextScanLine(), SipperFile.Sipper3File.LengthNextScanLine(), SipperFile.SipperBuff4Bit.LengthNextScanLine(), SipperFile.SipperBaseFile.ReadNextFrame(), SipperFile.Sipper2File.ReadNextScanLine(), SipperFile.Sipper3File.ReadNextScanLine(), SipperFile.SipperBuff4Bit.ReadNextScanLine(), SipperFile.Sipper3File.SaveRawCtdData(), SipperFile.Sipper2File.SkipNextScanLine(), SipperFile.Sipper3File.SkipNextScanLine(), and SipperFile.SipperBaseFile.ValidateFormat().
InstrumentDataManager SipperFile.SipperBaseFile.instrumentDataManager = null protected
Definition at line 32 of file SipperBaseFile.cs.
Referenced by SipperFile.Sipper3File.ReadNextScanLine(), SipperFile.SipperBaseFile.SipperBaseFile(), and SipperFile.Sipper3File.SkipNextScanLine().
long SipperFile.SipperBaseFile.lastScanLineNum = 0 protected
Definition at line 30 of file SipperBaseFile.cs.
Referenced by SipperFile.SipperBaseFile.FrameRead(), SipperFile.SipperBaseFile.ReadNextFrame(), SipperFile.Sipper3File.ReadNextScanLine(), SipperFile.Sipper3File.SkipNextScanLine(), and SipperFile.SipperBaseFile.ValidateFormat().
const int SipperFile.SipperBaseFile.PixelsPerScanLine = 4096
Definition at line 35 of file SipperBaseFile.cs.
Referenced by SipperFile.SipperBaseFile.AllocateFrame(), and SipperFile.SipperBaseFile.CreateRatser().
const int SipperFile.SipperBaseFile.ScanLinesPerFrame = 4096
Definition at line 34 of file SipperBaseFile.cs.
Referenced by SipperFile.SipperBaseFile.AllocateFrame(), SipperFile.SipperBaseFile.EstimatedNumberOfScanLines(), SipperFile.SipperBaseFile.FrameRead(), and SipperFile.SipperFrame.SipperFrame().
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperFile/SipperBaseFile.cs