Pices: PicesInterface::PicesDataBaseServerList Class Reference
PicesInterface::PicesDataBaseServerList Class Reference
#include <PicesDataBaseServer.h>
Public Member Functions
PicesDataBaseServerList (PicesRunLog^ _log)
PicesDataBaseServerList (const DataBaseServerListPtr _servers, PicesRunLog^ _log)
~PicesDataBaseServerList ()
void CleanUpMemory ()
PicesDataBaseServer^ GetDefaultServer ()
PicesDataBaseServer^ LookUpByDescription (String^ _description)
void WriteConfigFile ()
Properties
String^ DefaultServerDescription [get, set]
PicesRunLog^ Log [get]
Detailed Description
Definition at line 53 of file PicesDataBaseServer.h.
Constructor & Destructor Documentation
PicesDataBaseServerList::PicesDataBaseServerList (PicesRunLog^ _log)
Definition at line 178 of file PicesDataBaseServer.cpp.
References MLL::DataBaseServerList::DefaultServerDescription(), PicesInterface::PicesKKStr::KKStrToSystenStr(), and PicesInterface::PicesRunLog::Log().
PicesDataBaseServerList::PicesDataBaseServerList (const DataBaseServerListPtr _servers, PicesRunLog^ _log)
Definition at line 205 of file PicesDataBaseServer.cpp.
References MLL::DataBaseServerList::DefaultServerDescription(), and PicesInterface::PicesKKStr::KKStrToSystenStr().
PicesDataBaseServerList::~PicesDataBaseServerList ()
Definition at line 224 of file PicesDataBaseServer.cpp.
References CleanUpMemory().
Member Function Documentation
void PicesDataBaseServerList::CleanUpMemory ()
Definition at line 231 of file PicesDataBaseServer.cpp.
Referenced by ~PicesDataBaseServerList().
PicesDataBaseServer PicesDataBaseServerList::GetDefaultServer ()
Definition at line 238 of file PicesDataBaseServer.cpp.
References LookUpByDescription().
PicesDataBaseServer PicesDataBaseServerList::LookUpByDescription (String^ _description)
Definition at line 256 of file PicesDataBaseServer.cpp.
References PicesInterface::PicesDataBaseServer::Description.
Referenced by GetDefaultServer().
void PicesDataBaseServerList::WriteConfigFile ()
Definition at line 275 of file PicesDataBaseServer.cpp.
References PicesInterface::PicesRunLog::Log(), PicesInterface::PicesKKStr::SystemStringToKKStr(), and PicesInterface::PicesDataBaseServer::UnManagedClass().
Property Documentation
String^ PicesInterface::PicesDataBaseServerList::DefaultServerDescription get set
Definition at line 65 of file PicesDataBaseServer.h.
PicesRunLog^ PicesInterface::PicesDataBaseServerList::Log get
Definition at line 71 of file PicesDataBaseServer.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesDataBaseServer.h
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesDataBaseServer.cpp