Pices: KKU::KKStr Class Reference
KKU::KKStr Class Reference
A string class providing safe runtime string management.
#include <Str.h>
Public Types
typedef KKU::int16 int16
typedef KKU::int32 int32
typedef KKStr const * KKStrConstPtr
typedef KKU::uint16 KKStrInt
typedef KKStr * KKStrPtr
typedef KKU::uint16 uint16
typedef KKU::uint32 uint32
typedef std::vector< KKStr > VectorKKStr
Public Member Functions
KKStr ()
KKStr (const char *str)
KKStr (const KKStr &str)
Copy Constructor.
KKStr (const KKStrConstPtr &str)
Constructs a new KKStr from a pointer to a KKStr.
KKStr (int32 size)
Creates a KKStr object that preallocates space for 'size' characters.
KKStr (double d, int32 precision)
Initializes the string with a displayable version of 'd' with 'precision' decimal points.
KKStr (const std::string &s)
Constructs a KKStr instance form a stl::string instance.
KKStr (const char *src, uint32 startPos, uint32 endPos)
Constructs an instance from a substring of the ascii-z string 'src'.
~KKStr ()
void Append (const char *buff)
void Append (const char *buff, uint32 buffLen)
void Append (char ch)
void Append (const KKStr &str)
void Append (const std::string &str)
void AppendInt32 (int32 i)
void AppendUInt32 (uint32 i)
const char * c_str ()
bool CharInStr (char ch)
Determines if 'ch' occurs anywhere in the string.
void ChopFirstChar ()
Removes the first character from the string.
void ChopLastChar ()
Removes the last character from the string.
int32 Compare (const KKStr &s2) const
'-1' = less than 's2', '0' = Same as 's2', and '1' = Greater than 's2'.
int32 Compare (const std::string &s2) const
'-1' = less than 's2', '0' = Same as 's2', and '1' = Greater than 's2'.
int32 CompareIgnoreCase (const KKStr &s2) const
Compares with another KKStr, ignoring case.
int32 CompareIgnoreCase (const std::string &s2) const
Compares with STL string ignoring case.
int32 CompareIgnoreCase (const char *s2) const
Compares with ascii-z string ignoring case.
int32 CompareTo (const KKStr &s2) const
bool Contains (const KKStr &value)
bool Contains (const char *value)
const char * data ()
bool Empty () const
bool EndsWith (const KKStr &value)
bool EndsWith (const char *value)
bool EndsWith (const KKStr &value, bool ignoreCase)
bool EndsWith (const char *value, bool ignoreCase)
char EnterStr ()
bool EqualIgnoreCase (const KKStr &s2) const
bool EqualIgnoreCase (const char *s2) const
char ExtractChar ()
Removes the first character from the string and retuns it to the caller.
KKStr ExtractQuotedStr (const char *delChars, bool decodeEscapeCharacters)
Extracts the next string token; if the string starts with a quote(") will extract until the terminating quote.
KKStr ExtractToken (const char *delStr="\n\t\r ")
Extract first Token from the string.
KKStr ExtractToken2 (const char *delStr="\n\t\r ")
Extract first Token from the string.
bool ExtractTokenBool (const char *delStr)
Extract the next token from the string assuming that it is a logical True/False value.
double ExtractTokenDouble (const char *delStr)
int32 ExtractTokenInt (const char *delStr)
uint32 ExtractTokenUint (const char *delStr)
int32 Find (const KKStr &str, int32 pos=0) const
int32 Find (const char *s, int32 pos, int32 n) const
int32 Find (const char *s, int32 pos=0) const
int32 Find (char c, int32 pos=0) const
char FirstChar () const
Returns the first character in the string; if the string is empty returns 0.
KKStr GetNextToken2 (const char *delStr="\n\t\r ") const
Retrieves the first token in the string without removing any characters.
int32 InstancesOfChar (char ch) const
Returns the number of instances of 'ch' in the string.
char LastChar () const
Returns the last character in the string but if the string is empty returns 0.
void LeftPad (int32 width, uchar ch= ' ')
pads the string with enough 'ch' characters on the left side until the string is as long as 'width' characters.
int32 Len () const
Returns the number of characters in the string.
int32 LocateCharacter (char ch) const
Returns index of 1st occurrence of 'ch' otherwise -1.
int32 LocateLastOccurrence (char ch) const
Returns index of last occurrence of 'ch' otherwise -1.
int32 LocateLastOccurrence (const KKStr &s) const
Returns index of last occurrence of 's' otherwise -1.
int32 LocateStr (const KKStr &searchStr) const
Returns index of 1st occurrence of 'searchStr' otherwise -1.
void LopOff (int32 lastCharPos)
Trims off all characters after the 'lastCharPos' index; to make an empty string you would have to specify -1.
void Lower ()
Make all characters in the String into lower case.
KKStr MaxLen (int32 maxLen) const
int32 MemoryConsumedEstimated () const
bool operator!= (const KKStr &right) const
bool operator!= (const KKStrConstPtr &right) const
bool operator!= (const char *rtStr) const
bool operator!= (const std::string right) const
KKStr operator+ (const char *right) const
KKStr operator+ (const KKStr &right) const
KKStr operator+ (int16 right) const
KKStr operator+ (uint16 right) const
KKStr operator+ (int32 right) const
KKStr operator+ (uint32 right) const
KKStr operator+ (int64 right) const
KKStr operator+ (uint64 right) const
KKStr operator+ (float right) const
KKStr operator+ (double right) const
KKStr & operator+= (const char *right)
KKStr & operator+= (const KKStr &right)
KKStr & operator+= (int16 right)
KKStr & operator+= (uint16 right)
KKStr & operator+= (int32 right)
KKStr & operator+= (uint32 right)
KKStr & operator+= (int64 right)
KKStr & operator+= (uint64 right)
KKStr & operator+= (float right)
KKStr & operator+= (double right)
bool operator< (const KKStr &right) const
KKStr & operator<< (const char *right)
KKStr & operator<< (const KKStr &right)
KKStr & operator<< (char right)
KKStr & operator<< (int16 right)
KKStr & operator<< (uint16 right)
KKStr & operator<< (int32 right)
KKStr & operator<< (uint32 right)
KKStr & operator<< (int64 right)
KKStr & operator<< (uint64 right)
KKStr & operator<< (float right)
KKStr & operator<< (double right)
KKStr & operator<< (std::ostream &(*mf)(std::ostream &))
bool operator<= (const KKStr &right) const
KKStr & operator= (const KKStr &src)
KKStr & operator= (const char *src)
KKStr & operator= (int32 right)
KKStr & operator= (const std::vector< KKStr > &right)
bool operator== (const KKStr &right) const
bool operator== (const KKStrConstPtr &right) const
bool operator== (const char *rtStr) const
bool operator== (const std::string right) const
bool operator> (const KKStr &right) const
bool operator>= (const KKStr &right) const
char operator[] (int16 i) const
Returns back the character at position 'i', if i > length of KKStr then returns back 0.
char operator[] (uint16 i) const
Returns back the character at position 'i', if i > length of KKStr then returns back 0.
char operator[] (int32 i) const
Returns back the character at position 'i', if i > length of KKStr then returns back 0.
char operator[] (uint32 i) const
Returns back the character at position 'i', if i > length of KKStr then returns back 0.
VectorKKStr Parse (const char *delStr="\n\r\t, ") const
Will break up the contents of the string into tokens where one of the characters in 'delStr' separates each token.
KKStr QuotedStr () const
Returns a quoted version of string where special characters line Line Feed, Carriage Return, and Tab, are encoded as escape sequences.
void RightPad (int32 width, char ch= ' ')
Returns a string of spaces 'c' charaters long.
VectorKKStr Split (const char *delStr="\n\r\t, ") const
Breaks up the contents of the string into tokens where the characters in 'delStr' acts as separaters each token.
VectorKKStr Split (char del) const
Splits the string up into tokens using 'del' as the separator returning them in a vector.
bool StartsWith (const KKStr &value) const
bool StartsWith (const char *value) const
bool StartsWith (const KKStr &value, bool ignoreCase) const
bool StartsWith (const char *value, bool ignoreCase) const
const char * Str () const
Returns a pointer to a ascii string.
bool StrInStr (const KKStr &searchField) const
Searches for the occurrence of 'searchField' and where in the string.
void StrReplace (char **dest, const char *src)
Replaces the contents of *dest with *src.
wchar_t * StrWide () const
Returns a Wide Character version of the string.
KKStr SubStrPart (int32 firstChar) const
returns a SubString consisting of all characters starting at index 'firstChar' until the end of the string.
KKStr SubStrPart (int32 firstChar, int32 lastChar) const
returns a SubString consisting of all characters starting at index 'firstChar' and ending at 'lastIndex'
KKStr Tail (int32 tailLen) const
Return back the last 'tailLen' characters.
bool ToBool () const
Returns the bool equivalent of the string, ex 'Yes' = true, 'No' = false, 'True' = true, etc.
double ToDouble () const
float ToFloat () const
int32 ToInt () const
int16 ToInt16 () const
int32 ToInt32 () const
int64 ToInt64 () const
double ToLatitude () const
Processes string as if a standard latitude; ex: "15:32.2S" = -15.53833.
long ToLong () const
double ToLongitude () const
Processes string as if a standard longitude; ex: "95:32.2E" = 95.53833.
KKStr ToLower () const
float ToPercentage () const
uint32 ToUint () const
uint32 ToUint32 () const
uint64 ToUint64 () const
ulong ToUlong () const
KKStr ToUpper () const
void TrimLeft (const char *whiteSpaceChars="\n\r\t ")
KKStr & TrimRight (const char *whiteSpaceChars="\n\r\t ")
void TrimRightChar ()
void Upper ()
Converts all characters in string to their Upper case equivalents via 'toupper'.
bool ValidInt (int32 &value)
returns true if KKStr is formated as a valid integer otherwise false.
bool ValidMoney (float &value) const
bool ValidNum (double &value) const
Returns true if String is a valid number, ex 1.0 or -3.123, etc.
KKStr Wide (int32 width, char dir= 'R') const
Pads the string with spaces so that it is exactly 'width' characters long.
Static Public Member Functions
static int32 CompareStrings (const KKStr &s1, const KKStr &s2)
Compares to Strings and returns -1, 0, or 1, indicating if less than, equal, or greater.
static KKStr Concat (const char **values)
Concatenates the list of char* strings, stops at first one that is NULL details Iterates through values concatenating each one onto a result string.
static KKStr Concat (const VectorKKStr &values)
Concatenates the list of char* strings, stops at first one that is NULL.
static KKStr Concat (const std::vector< std::string > &values)
Concatenates the list of 'std::string' strings.
static const KKStr & EmptyStr ()
Static method that returns an Empty String.
static KKStr Spaces (int32 c)
static const char * Str (const char *s)
static void StrCapitalize (char *str)
static int32 StrCompareIgnoreCase (const char *s1, const char *s2)
static void StrDelete (char **str)
static bool StrEqual (const char *s1, const char *s2)
static bool StrEqualNoCase (const char *s1, const char *s2)
static bool StrInStr (const char *target, const char *searchStr)
Detailed Description
A string class providing safe runtime string management.
This String class was originally developed back in the early 90's. It is meant to make string management simple and easy. Strings can dynamically increase in size as needed. All methods make sure that there is no accessing outside of the bounds of the allocated string.
Todo:
Should subclass the class from the stl class 'string'.
Author
Kurt Kramer
Definition at line 44 of file Str.h.
Member Typedef Documentation
typedef KKU::int16 KKU::KKStr::int16
Definition at line 47 of file Str.h.
typedef KKU::int32 KKU::KKStr::int32
Definition at line 49 of file Str.h.
typedef KKStr const* KKU::KKStr::KKStrConstPtr
Definition at line 53 of file Str.h.
typedef KKU::uint16 KKU::KKStr::KKStrInt
Definition at line 51 of file Str.h.
typedef KKStr* KKU::KKStr::KKStrPtr
Definition at line 52 of file Str.h.
typedef KKU::uint16 KKU::KKStr::uint16
Definition at line 48 of file Str.h.
typedef KKU::uint32 KKU::KKStr::uint32
Definition at line 50 of file Str.h.
typedef std::vector<KKStr> KKU::KKStr::VectorKKStr
Definition at line 54 of file Str.h.
Constructor & Destructor Documentation
KKStr::KKStr ()
Definition at line 514 of file Str.cpp.
Referenced by ExtractToken2().
KKStr::~KKStr ()
Definition at line 819 of file Str.cpp.
KKStr::KKStr (const char * str)
Definition at line 524 of file Str.cpp.
References KKU::STRCOPY().
KKStr::KKStr (const KKStr & str)
Copy Constructor.
Definition at line 548 of file Str.cpp.
References KKU::endl().
KKStr::KKStr (const KKStrConstPtr & str)
Constructs a new KKStr from a pointer to a KKStr.
Definition at line 587 of file Str.cpp.
References KKU::endl(), and KKU::STRCOPY().
KKStr::KKStr (int32 size)
Creates a KKStr object that preallocates space for 'size' characters.
Creates a KKStr object that has 'size' charaters preallocatd; and set to empty string.
Definition at line 665 of file Str.cpp.
References KKU::endl().
KKStr::KKStr (double d, int32 precision)
Initializes the string with a displayable version of 'd' with 'precision' decimal points.
Creates a String that is populated with 'd' as displayable characters and precision of 'precision'.
Definition at line 627 of file Str.cpp.
References KKU::SPRINTF(), and KKU::STRCOPY().
KKStr::KKStr (const std::string & s)
Constructs a KKStr instance form a stl::string instance.
Definition at line 687 of file Str.cpp.
References x.
KKStr::KKStr (const char * src, uint32 startPos, uint32 endPos)
Constructs an instance from a substring of the ascii-z string 'src'.
Constructs a KKStr instance fomm a substr of 'src'.
Parameters
[in] src Source string to build new instance from.
[in] startPos First character in 'src' that we want to include in new instance.
[in] endPos Last character in 'src' that we want to include in new instance.
Definition at line 702 of file Str.cpp.
References KKU::endl().
Member Function Documentation
void KKStr::Append (const char * buff)
Definition at line 1690 of file Str.cpp.
References KKU::endl(), and x.
Referenced by Append(), AppendInt32(), AppendUInt32(), ArrayToDelimitedDelimitedStr(), Concat(), ExtractQuotedStr(), MLL::DataBase::FeatureDataForImageGroup(), MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::FeatureFileIO::GetLine(), KKU::KKStrParser::GetRestOfLine(), KKU::KKStrParser::GetRestOfStr(), MLL::FeatureFileIO::GetToken(), KKU::BitString::HexStr(), MLL::DataBase::ImageGetClassStatistics(), MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageInsert(), MLL::DataBase::ImagesQuery(), MLL::DataBase::ImagesQueryByGrouop(), MLL::DataBase::ImageUpdate(), operator+(), KKU::operator+(), PicesInterface::operator<<(), operator<<(), KKU::osReadNextQuotedStr(), MLL::DataBase::QueryStatement(), QuotedStr(), ReadNextToken(), ReadWholeTag(), MLL::ModelDual::ReconcilePredictions(), SipperHardware::InstrumentDataBatteryMeter::ReportInstrumentData(), SipperHardware::InstrumentDataUserMsgs::ReportInstrumentData(), SipperHardware::InstrumentDataCTDplus::ReportInstrumentData(), SipperHardware::InstrumentDataPitchAndRoll::ReportInstrumentData(), SipperHardware::InstrumentDataGPS::ReportInstrumentData(), SipperHardware::InstrumentDataReport::ReportInstrumentData(), MLL::DataBase::SipperFileInsert(), MLL::DataBase::SipperFileUpdate(), StripOutInvalidLatexCaracters(), KKU::KKStrParser::SubStrPart(), PicesInterface::PicesKKStr::SystemStringToKKStr(), PicesInterface::PicesKKStr::SystemStringToKKStrPtr(), and SipperHardware::SipperCruise::ValidateCruiseName().
void KKStr::Append (const char * buff, uint32 buffLen)
Definition at line 1728 of file Str.cpp.
References KKU::endl(), and x.
void KKStr::Append (char ch)
Definition at line 1771 of file Str.cpp.
References KKU::endl().
void KKStr::Append (const KKStr & str)
Definition at line 1795 of file Str.cpp.
References Append().
void KKStr::Append (const std::string & str)
Definition at line 1802 of file Str.cpp.
References Append().
void KKStr::AppendInt32 (int32 i)
Definition at line 1809 of file Str.cpp.
References Append().
Referenced by KKU::RunLog::operator<<(), and operator<<().
void KKStr::AppendUInt32 (uint32 i)
Definition at line 1848 of file Str.cpp.
References Append().
Referenced by KKU::RunLog::operator<<(), and operator<<().
const char* KKU::KKStr::c_str () inline
Definition at line 521 of file Str.h.
References Str().
bool KKStr::CharInStr (char ch)
Determines if 'ch' occurs anywhere in the string.
Definition at line 2547 of file Str.cpp.
References x.
void KKStr::ChopFirstChar ()
Removes the first character from the string.
Definition at line 1582 of file Str.cpp.
References x.
Referenced by KKU::PointList::FromDelStr(), ToLatitude(), and ToLongitude().
void KKStr::ChopLastChar ()
Removes the last character from the string.
Definition at line 1565 of file Str.cpp.
Referenced by MLL::FeatureFileIODstWeb::AttrDescLine::AttrDescLine(), MLL::FeatureFileIOC45::GetFileDesc(), MLL::FeatureFileIODstWeb::LoadFile(), KKU::osGetDirNameFromPath(), KKU::osGetParentDirectoryOfDirPath(), KKU::osGetParentDirPath(), KKU::osGetRootNameOfDirectory(), ToLatitude(), and ToLongitude().
int32 KKStr::Compare (const KKStr & s2) const
'-1' = less than 's2', '0' = Same as 's2', and '1' = Greater than 's2'.
Definition at line 830 of file Str.cpp.
References KKU::Min(), and x.
Referenced by CompareTo(), operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
int32 KKStr::Compare (const std::string & s2) const
'-1' = less than 's2', '0' = Same as 's2', and '1' = Greater than 's2'.
Compares with STL string.
Parameters
[in] s2 STL String std::string that we will compare with.
Returns
-1=less, 0=equal, 1=greater, -1, 0, or 1, indicating if less than, equal, or greater.
Definition at line 867 of file Str.cpp.
References KKU::Min(), and x.
int32 KKStr::CompareIgnoreCase (const KKStr & s2) const
Compares with another KKStr, ignoring case.
Parameters
[in] s2 Other String to compare with.
Returns
-1=less, 0=equal, 1=greater, -1, 0, or 1, indicating if less than, equal, or greater.
Definition at line 905 of file Str.cpp.
References KKU::Min(), and x.
Referenced by MLL::ConfusionMatrix2::BuildFromIstreamXML(), EqualIgnoreCase(), JobManagment::Job::JobStatusFromStr(), KKU::DateType::MonthFromStr(), SipperHardware::SipperCruiseList::CruiseNameComparator::operator()(), JobManagment::Job::PrerequisitesFromStr(), JobManagment::Job::ProcessStatusStr(), and JobManagment::JobManager::StatusFileProcessLine().
int32 KKStr::CompareIgnoreCase (const std::string & s2) const
Compares with STL string ignoring case.
Parameters
[in] s2 STL String std::string that we will compare with.
Returns
-1=less, 0=equal, 1=greater, -1, 0, or 1, indicating if less than, equal, or greater.
Definition at line 984 of file Str.cpp.
References KKU::Min(), and x.
int32 KKStr::CompareIgnoreCase (const char * s2) const
Compares with ascii-z string ignoring case.
Parameters
[in] s2 Ascii-z string to compare with.
Returns
-1=less, 0=equal, 1=greater, -1, 0, or 1, indicating if less than, equal, or greater.
Definition at line 941 of file Str.cpp.
References KKU::Min(), and x.
int32 KKStr::CompareStrings (const KKStr & s1, const KKStr & s2) static
Compares to Strings and returns -1, 0, or 1, indicating if less than, equal, or greater.
Definition at line 4122 of file Str.cpp.
Referenced by KKU::KKStrList::StringComparison::operator()().
int32 KKU::KKStr::CompareTo (const KKStr & s2) const inline
Definition at line 154 of file Str.h.
References Compare().
Referenced by PicesInterface::PicesDataBaseImage::CompareClass2(), and PicesInterface::PicesDataBaseImage::CompareSpatially().
KKStr KKStr::Concat (const char ** values) static
Concatenates the list of char* strings, stops at first one that is NULL details Iterates through values concatenating each one onto a result string.
Terminates when 'values[x] == NULL'.
Definition at line 1017 of file Str.cpp.
References Append(), and x.
KKStr KKStr::Concat (const VectorKKStr & values) static
Concatenates the list of char* strings, stops at first one that is NULL.
Iterates through values Concatenating each one onto a result string. Terminates when 'values[x] == NULL'.
Definition at line 1043 of file Str.cpp.
References Append(), and x.
KKStr KKStr::Concat (const std::vector< std::string > & values) static
Concatenates the list of 'std::string' strings.
Iterates through values concatenating each one onto a result string.
Iterates through values Concatenating each one onto a result string.
Definition at line 1068 of file Str.cpp.
References Append(), and x.
bool KKStr::Contains (const KKStr & value)
Definition at line 1089 of file Str.cpp.
References Empty(), and StrInStr().
bool KKStr::Contains (const char * value)
Definition at line 1098 of file Str.cpp.
References Find().
const char* KKU::KKStr::data () inline
Definition at line 523 of file Str.h.
References Str().
bool KKU::KKStr::Empty () const inline
Definition at line 215 of file Str.h.
Referenced by PicesInterface::TrainingModel2::AddClass(), PicesInterface::TrainingModel2::AddImageToTrainingLibray(), MLL::DuplicateImages::AddSingleImage(), KKU::Application::Application(), ImageExtractionManager::ExtractionParms::CmdLine(), KKU::CmdLineExpander::CmdLineExpander(), MLL::ModelParam::CompressionMethodFromStr(), Contains(), MLL::TrainingConfiguration2::CreateFromDirectoryStructure(), MLL::TrainingConfiguration2::CreateFromFeatureVectorList(), MLL::BinaryClassParms::CreateFromTabDelStr(), MLL::Orderings::CreateOrderingsObjFromFileIfAvaliable(), SipperHardware::CTD_Plus_Data::CTD_Plus_Data(), KKU::DateTime::DateTime(), DetermineCropSettingsForDeployment(), PicesInterface::PicesRunLog::DisplayWithNoteBook(), MLL::TrainingClass::ExpandedDirectory(), MLL::FeatureNumList::ExtractFeatureNumsFromStr(), PicesInterface::PicesClassList::ExtractThreeTitleLines(), MLL::DataBase::FeatureDataCreateTable(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::FeatureFileIO::FileFormatsReadAndWriteOptionsStr(), MLL::FeatureFileIO::FileFormatsReadOptionsStr(), MLL::FeatureFileIO::FileFormatsWrittenOptionsStr(), GetClassNameByHierarchyLevel(), MLL::TrainingConfiguration2::GetEffectiveConfigFileName(), MLL::FeatureFileIOC45::GetFileDesc(), MLL::FeatureFileIOUCI::GetFileDesc(), KKU::Tokenizer::GetNextTokens(), SipperHardware::InstrumentDataFileManager::GetOrigSipperImage(), MLL::DataBase::ImageGetClassStatistics(), MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImagesRetrieveValidatedClass(), PicesInterface::TrainingModel2::IncludesClass(), CImageExtractionWindowsApp::InitInstance(), MLL::DataBase::InstrumentDataGetSpecificFields(), SipperHardware::InstrumentDataManager::InstrumentDataManager(), SipperHardware::InstrumentDataReport::InstrumentDataReport(), MLL::FeatureFileIOUCI::LoadFile(), MLL::FeatureFileIOPices::LoadFile(), MLL::FeatureFileIOC45::LoadFile(), KKU::Configuration::LoadFile(), MLL::FeatureFileIOPices::LoadInSubDirectoryTree(), MLL::TrainingConfiguration2::LoadOtherClasssExamples(), CrossValidationApp::LocateImageFileUsingConfigurationFile(), CrossValidationApp::Main(), MLL::DataBase::MLClassLoad(), MLL::DataBase::MLClassLoadList(), MLL::CompressionStats::operator+=(), MLL::CompressionStats::operator=(), MLL::Orderings::Orderings(), KKU::osCreateDirectoryPath(), KKU::osCreateUniqueFileName(), osDirectoryList(), KKU::osGetDirNameFromPath(), KKU::osGetListOfFilesInDirectoryTree(), KKU::osLookForFile(), osParseSearchSpec(), Parse(), ImageExtractionManager::ExtractionParms::ParseCmdLine(), MLL::ModelParam::ParseCmdLine(), MLL::SVMparam::ParseCmdLineParameter(), MLL::ClassAssignments::ParseToString(), CrossValidationApp::PostMisclassifiedImage(), CrossValidationApp::ProcessCmdLineParameter(), KKU::Application::ProcessCmdLineParameters(), CrossValidationApp::ProcessCmdLineParameters(), MLL::MLClass::ProcessRawData(), CrossValidationApp::RandomlySelectedProcessResults(), MLL::NormalizationParms::Read(), MLL::AbundanceCorrectionMatrix::ReadXml(), MLL::Model::ReadXML(), MLL::ModelDual::ReconcilePredictions(), CrossValidationApp::ReportCmdLineParameters(), SipperHardware::InstrumentDataBatteryMeter::ReportInstrumentData(), SipperHardware::InstrumentDataUserMsgs::ReportInstrumentData(), SipperHardware::InstrumentDataCTDplus::ReportInstrumentData(), SipperHardware::InstrumentDataPitchAndRoll::ReportInstrumentData(), SipperHardware::InstrumentDataGPS::ReportInstrumentData(), SipperHardware::SipperBuff::ReportInstrumentData(), ImageExtractionManager::DataBaseUpdateThread::Run(), MLL::Orderings::Save(), MLL::TrainingConfiguration2::Save(), PicesInterface::TrainingModel2::SaveConfiguration(), PicesInterface::PicesDataBase::SipperFileGetFullPath(), MLL::DataBase::SipperFileGetList(), MLL::DataBase::SipperFileLoad(), MLL::DataBase::SipperStationLoad(), MLL::DataBaseImage::SizeCoordinates(), Split(), JobManagment::JobManager::StatusFileProcessLine(), MLL::ModelParamDual::ToCmdLineStr(), MLL::ModelParam::ToCmdLineStr(), MLL::ClassIndexList::ToCommaDelString(), MLL::SVMparam::ToString(), MLL::FeatureNumList::ToString(), MLL::CompressionStats::UpdateFromTabDelStr(), SipperHardware::SipperCruise::ValidateCruiseName(), PicesInterface::PicesSipperCruise::ValidateCruiseName(), CrossValidationApp::ValidationProcess(), and CrossValidationApp::WriteABiasMatrix().
const KKStr & KKStr::EmptyStr () static
Static method that returns an Empty String.
Returns
a empty String.
Definition at line 3179 of file Str.cpp.
Referenced by KKU::XmlTag::AttributeValue(), ExtractQuotedStr(), KKU::KKStrParser::GetNextToken(), KKU::KKStrParser::GetRestOfLine(), KKU::KKStrParser::GetRestOfStr(), KKU::XmlElement::Name(), and KKU::KKStrParser::SubStrPart().
bool KKStr::EndsWith (const KKStr & value)
Definition at line 1108 of file Str.cpp.
Referenced by EndsWith().
bool KKStr::EndsWith (const char * value)
Definition at line 1115 of file Str.cpp.
References EndsWith().
bool KKStr::EndsWith (const KKStr & value, bool ignoreCase)
Definition at line 1122 of file Str.cpp.
References Len(), StrEqual(), and StrEqualNoCase().
bool KKStr::EndsWith (const char * value, bool ignoreCase)
Definition at line 1141 of file Str.cpp.
References StrEqual(), and StrEqualNoCase().
char KKStr::EnterStr ()
Definition at line 2241 of file Str.cpp.
References EnterChar, EscapeChar, and KKU::STRCOPY().
bool KKStr::EqualIgnoreCase (const KKStr & s2) const
Definition at line 1231 of file Str.cpp.
References CompareIgnoreCase().
Referenced by CreateBfsFromMfs(), MLL::Model::CreateFromStream(), MLL::ModelParam::CreateModelParam(), MLL::DataBaseImageValidatedEntryList::Load(), SipperHardware::SipperFileList::Load(), KKU::Configuration::SettingList::LookUp(), KKU::Configuration::ConfSectionList::LookUp(), MLL::DataBaseServerList::LookUpByDescription(), SipperHardware::SipperFileList::LookUpBySipperFileName(), MLL::ModelParam::ModelParamTypeFromStr(), MLL::Model::ModelTypeFromStr(), ImageExtractionManager::ExtractionParms::ParseCmdLine(), MLL::TrainingProcess2::Read(), KKU::ReadImagePNG(), MLL::ModelParamKnn::ReadSpecificImplementationXML(), MLL::ModelParamDual::ReadSpecificImplementationXML(), MLL::ModelParamOldSVM::ReadSpecificImplementationXML(), MLL::ModelParamSvmBase::ReadSpecificImplementationXML(), MLL::ModelParamUsfCasCor::ReadSpecificImplementationXML(), MLL::ModelKnn::ReadSpecificImplementationXML(), MLL::ModelUsfCasCor::ReadSpecificImplementationXML(), MLL::ModelSvmBase::ReadSpecificImplementationXML(), MLL::ModelDual::ReadSpecificImplementationXML(), MLL::ModelOldSVM::ReadSpecificImplementationXML(), MLL::AbundanceCorrectionMatrix::ReadXml(), MLL::Model::ReadXML(), SearchFieldIdx(), SipperHardware::SipperFileFormatFromStr(), JobManagment::JobManager::StatusFileProcessLine(), SipperHardware::SipperVariables::SubstituteInEvironmentVariables(), SVM289_MFS::svm_load_model_XML_SupportVectorSection(), and SVM289_BFS::svm_load_model_XML_SupportVectorSection().
bool KKStr::EqualIgnoreCase (const char * s2) const
Definition at line 1238 of file Str.cpp.
References StrCompareIgnoreCase().
char KKStr::ExtractChar ()
Removes the first character from the string and retuns it to the caller.
If the String is already empty it will return 0.
Definition at line 2979 of file Str.cpp.
References x.
KKStr KKStr::ExtractQuotedStr (const char * delChars, bool decodeEscapeCharacters)
Extracts the next string token; if the string starts with a quote(") will extract until the terminating quote.
               ExtractQuotedStr ********************
    Will extract and decode a quoted string.       *
                                                   *
If first character starts with a Quote.            *
  a.  Extract all charaters until next Quote.      *
                                                   *
  b.  Translate                                    *
        "\n" -> '\n'                               *
        "\t" -> '\t'                               *
        "\r" -> '\r'                               *
        "\\" -> '\'                                *
        "\"" -> '"'                                *
        "\0" -> char(0)                            *
                                                   *
  c.  The start and ending Quotes will not be      *
      included in returned string.                 *
                                                   *
  d.  Following delimiter will be removed.         *
      '\n', '\t', '\r'.                            *
                                                   *
Else                                               *
  a. Extract all characters until delimiter.       *
      '\n', '\t', '\r'.                            *
Parameters
[in] delChars List of acceptable delimiter characters.
int32] decodeEscapeCharacters If true escape sequences will be decoded, that is characters that are preceded by the back slash ('\'). Ex: '' = Tab Character, '' = Carrage return, '\' = '\'.
Returns
Token String
Definition at line 3008 of file Str.cpp.
References Append(), and EmptyStr().
Referenced by KKU::CmdLineExpander::CmdLineExpander(), MLL::BinaryClassParms::CreateFromTabDelStr(), MLL::NormalizationParms::Read(), MLL::Model::ReadSkipToSection(), MLL::ModelParamKnn::ReadSpecificImplementationXML(), MLL::ModelParamDual::ReadSpecificImplementationXML(), MLL::ModelParamOldSVM::ReadSpecificImplementationXML(), MLL::ModelParamSvmBase::ReadSpecificImplementationXML(), MLL::ModelParamUsfCasCor::ReadSpecificImplementationXML(), MLL::ModelKnn::ReadSpecificImplementationXML(), MLL::ModelUsfCasCor::ReadSpecificImplementationXML(), MLL::ModelSvmBase::ReadSpecificImplementationXML(), MLL::ModelDual::ReadSpecificImplementationXML(), MLL::SVMparam::ReadXML(), MLL::Model::ReadXML(), and MLL::CompressionStats::UpdateFromTabDelStr().
KKStr KKStr::ExtractToken (const char * delStr = "\n\t\r ")
Extract first Token from the string.
Removes first Token from string and returns it skipping over any leading delimiters. Tokens will be terminated by end of string or the first occurrence of a delimiter character. If no more tokens left will return a Empty KKStr. Note if you do not want to skip over leading delimiter characters the use 'ExtractToken2'.
Parameters
[in] delStr List of delimiting characters.
Returns
Extracted Token.
See Also
ExtractToken2
Definition at line 2764 of file Str.cpp.
Referenced by MLL::FeatureFileIODstWeb::AttrDescLine::AttrDescLine(), KKU::DateType::DateType(), MLL::FeatureNumList::ExtractFeatureNumsFromStr(), PicesInterface::PicesClassList::ExtractThreeTitleLines(), GetClassNameByHierarchyLevel(), MLL::FeatureFileIOUCI::GetFileDesc(), MLL::FeatureFileIOSparse::GetFileDesc(), MLL::FeatureFileIODstWeb::LoadFile(), MLL::FeatureFileIOUCI::LoadFile(), MLL::FeatureFileIOSparse::LoadFile(), MLL::FeatureVectorList::OrderUsingNamesFromAFile(), KKU::osCreateDirectoryPath(), MLL::ModelParam::ParseCmdLine(), MLL::ModelParamOldSVM::ParseCmdLine(), MLL::ClassAssignments::ParseToString(), MLL::MLClass::ProcessRawData(), and KKU::TimeType::TimeType().
KKStr KKStr::ExtractToken2 (const char * delStr = "\n\t\r ")
Extract first Token from the string.
Removes first Token from string and returns it. Unlike 'ExtractToken' it will not skip over leading delimiters. If the first character is a delimiter it will return a empty string. Tokens will be terminated by end of string or the first occurrence of a delimiter character. If no more tokens left will return a Empty KKStr.
Parameters
[in] delStr List of delimiting characters.
Returns
Extracted Token.
See Also
ExtractToken
ExtractTokenInt
ExtractTokenDouble
ExtractTokenUint
ExtractTokenBool
Definition at line 2821 of file Str.cpp.
References KKStr().
Referenced by MLL::ConfusionMatrix2::BuildFromIstreamXML(), MLL::Model::CreateFromStream(), MLL::ModelParam::CreateModelParam(), ExtractTokenBool(), ExtractTokenDouble(), ExtractTokenInt(), ExtractTokenUint(), MLL::ClassAssignments::Load(), MLL::DataBaseImageValidatedEntryList::Load(), Parse(), MLL::ClassIndexList::ParseClassIndexList(), MLL::TrainingProcess2::Read(), MLL::ModelParamKnn::ReadSpecificImplementationXML(), MLL::ModelParamDual::ReadSpecificImplementationXML(), MLL::ModelParamUsfCasCor::ReadSpecificImplementationXML(), MLL::ModelOldSVM::ReadSpecificImplementationXML(), MLL::Model::ReadXML(), MLL::ModelDual::ReconcilePredictions(), Split(), JobManagment::JobManager::StatusFileProcessLine(), JobManagment::JobManager::StatusFileProcessLineJobStatusChange(), SVM289_MFS::svm_load_model_XML_SupportVectorSection(), SVM289_BFS::svm_load_model_XML_SupportVectorSection(), ToLatitude(), and ToLongitude().
bool KKStr::ExtractTokenBool (const char * delStr)
Extract the next token from the string assuming that it is a logical True/False value.
This function calls 'ExtractToken2' and then returns true if the string that it extracted is equal to "Y", "Yes", "True", "T", or "1" otherwise false.
Parameters
[in] List of delimiter characters.
Returns
True ot
Definition at line 2947 of file Str.cpp.
References ExtractToken2(), and Upper().
Referenced by MLL::NormalizationParms::Read(), MLL::ModelParamDual::ReadSpecificImplementationXML(), and MLL::Model::ReadXML().
double KKStr::ExtractTokenDouble (const char * delStr)
Definition at line 2962 of file Str.cpp.
References ExtractToken2(), Len(), and Str().
Referenced by MLL::NormalizationParms::Read(), MLL::Model::ReadXML(), and JobManagment::JobManager::StatusFileProcessLine().
int32 KKStr::ExtractTokenInt (const char * delStr)
Definition at line 2924 of file Str.cpp.
References ExtractToken2(), and Str().
Referenced by MLL::ConfusionMatrix2::BuildFromIstreamXML(), MLL::FeatureNumList::ExtractFeatureNumsFromStr(), KKU::PointList::FromDelStr(), MLL::ClassAssignments::Load(), MLL::ClassIndexList::ParseClassIndexList(), MLL::ClassAssignments::ParseToString(), MLL::NormalizationParms::Read(), KKU::ReadImagePNG(), MLL::ModelParamUsfCasCor::ReadSpecificImplementationXML(), JobManagment::JobManager::StatusFileProcessLine(), and JobManagment::JobManager::StatusFileProcessLineJobStatusChange().
KKU::uint32 KKStr::ExtractTokenUint (const char * delStr)
Definition at line 2936 of file Str.cpp.
References ExtractToken2(), and Str().
int32 KKStr::Find (const KKStr & str, int32 pos = 0) const
Todo:
Want to implement all the methods that the std::string class implements. this way people who are familiar with the std::string class will find using this class easier.
Definition at line 3525 of file Str.cpp.
References Len(), SearchStr(), and Str().
Referenced by Contains(), and KKU::PointList::FromDelStr().
int32 KKStr::Find (const char * s, int32 pos, int32 n) const
Definition at line 3532 of file Str.cpp.
References SearchStr().
int32 KKStr::Find (const char * s, int32 pos = 0) const
Definition at line 3539 of file Str.cpp.
References SearchStr().
int32 KKStr::Find (char c, int32 pos = 0) const
Definition at line 3546 of file Str.cpp.
References x.
char KKStr::FirstChar () const
Returns the first character in the string; if the string is empty returns 0.
Definition at line 1878 of file Str.cpp.
Referenced by KKU::PointList::FromDelStr(), MLL::FeatureFileIOPices::LoadFile(), KKU::Configuration::LoadFile(), MLL::CompressionStats::operator+=(), MLL::CompressionStats::operator=(), KKU::osCreateDirectoryPath(), KKU::ReadImagePGM(), ToLatitude(), and ToLongitude().
KKStr KKStr::GetNextToken2 (const char * delStr = "\n\t\r ") const
Retrieves the first token in the string without removing any characters.
Similar to 'ExtractToken2' except it does not remove characters from the string.
Returns
The first token in the string.
Definition at line 2884 of file Str.cpp.
References SubStrPart().
int32 KKStr::InstancesOfChar (char ch) const
Returns the number of instances of 'ch' in the string.
Definition at line 1923 of file Str.cpp.
References x.
Referenced by MLL::MLClass::NumHierarchialLevels().
char KKStr::LastChar () const
Returns the last character in the string but if the string is empty returns 0.
Definition at line 1889 of file Str.cpp.
Referenced by MLL::FeatureFileIOC45::GetFileDesc(), MLL::FeatureFileIODstWeb::LoadFile(), KKU::Configuration::LoadFile(), KKU::osAddLastSlash(), KKU::osAddSlash(), KKU::osCreateDirectoryPath(), KKU::osGetDirNameFromPath(), KKU::osGetFileNamePartOfFile(), KKU::osGetParentDirectoryOfDirPath(), KKU::osGetParentDirPath(), KKU::osGetRootNameOfDirectory(), KKU::osMoveFileBetweenDirectories(), KKU::osParseFileSpec(), ToLatitude(), ToLongitude(), and ToPercentage().
void KKStr::LeftPad (int32 width, uchar ch = ' ')
pads the string with enough 'ch' characters on the left side until the string is as long as 'width' characters.
if 'width' is less than the current length of the string then the string will have characters removed the beginning until its 'len' equals 'width'.
Todo:
Need to properly debug thru 'KKStr::LeftPad;
Definition at line 2159 of file Str.cpp.
References KKU::endl().
Referenced by MLL::ConfusionMatrix2::PrintConfusionMatrixNarrow(), MLL::SizeDistribution::ClassTotals::PrintFormatedLine(), and Wide().
int32 KKU::KKStr::Len () const inline
Returns the number of characters in the string.
Definition at line 355 of file Str.h.
Referenced by KKU::MsgQueue::AddMsg(), CreateBfsFromMfs(), KKU::TokenBufferStr::EndOfFile(), EndsWith(), ExtractAttribute(), ExtractTokenDouble(), Find(), KKU::PointList::FromDelStr(), KKU::BitString::FromHexStr(), MLL::MLClass::GetClassNameFromDirName(), MLL::FeatureFileIOC45::GetFileDesc(), KKU::TokenBufferStr::GetNextChar(), KKU::MsgQueue::GetNextMsg(), MLL::DataBase::ImagesUpdatePredictionsList(), MLL::DataBase::InsertCruise(), MLL::DataBase::InstrumentDataLoadAllSipperFiles(), KKU::Configuration::LoadFile(), LocateEnvStrStart(), LocateLastOccurrence(), MarineSnowReportDeployment(), KKU::operator+(), operator=(), osFileNameMatchesSearchFields(), KKU::osGetDriveLetter(), KKU::osSplitDirectoryPathIntoParts(), MLL::ModelParam::ParseCmdLine(), MLL::ModelParamOldSVM::ParseCmdLine(), MLL::DataBase::QueryStatement(), MLL::DataBase::QueryStatementKKStr(), QuotedStr(), MLL::ModelParamDual::ReadSpecificImplementationXML(), MLL::ModelParamSvmBase::ReadSpecificImplementationXML(), MLL::ModelParamUsfCasCor::ReadSpecificImplementationXML(), MLL::ModelOldSVM::ReadSpecificImplementationXML(), MLL::ModelDual::ReconcilePredictions(), SipperHardware::InstrumentDataCTDplus::ReportInstrumentData(), SipperHardware::InstrumentDataGPS::ReportInstrumentData(), SipperHardware::InstrumentDataReport::ReportInstrumentData(), KKU::SaveImagePGM(), KKU::SaveImagePNG(), StartsWith(), StripOutAnyComments(), StripOutInvalidLatexCaracters(), SVM289_MFS::svm_load_model_XML_SupportVectorSection(), SVM289_BFS::svm_load_model_XML_SupportVectorSection(), KKU::TimeType::TimeType(), ToFloat(), ToPercentage(), SipperHardware::SipperCruise::ValidateCruiseName(), and Wide().
int32 KKStr::LocateCharacter (char ch) const
Returns index of 1st occurrence of 'ch' otherwise -1.
Definition at line 1903 of file Str.cpp.
Referenced by MLL::FeatureNumList::ExtractFeatureNumsFromStr(), MLL::MLClassConstList::ExtractTwoTitleLines(), MLL::MLClassList::ExtractTwoTitleLines(), MLL::FeatureFileIODstWeb::GetFileDesc(), KKU::Configuration::LoadFile(), KKU::osGetFileNamePartOfFile(), KKU::osGetListOfDirectories(), KKU::osLocateFirstSlashChar(), KKU::osParseFileSpec(), KKU::osSubstituteInEvironmentVariables(), SipperHardware::SipperHeaderRec::ParseHeaderStr(), and SipperHardware::SipperVariables::SubstituteInEvironmentVariables().
int32 KKStr::LocateLastOccurrence (char ch) const
Returns index of last occurrence of 'ch' otherwise -1.
Returns the position of the last occurrence of the character 'ch'.
A return of -1 indicates that there is no occurrence of 'ch' in the string.
Definition at line 2000 of file Str.cpp.
Referenced by MLL::MLClass::GetClassNameFromDirName(), SipperHardware::InstrumentDataFileManager::GetClosestInstrumentData(), MLL::DuplicateImage::ImageWithSmallestScanLine(), MLL::FeatureFileIOC45::LoadFeatureFile(), KKU::osGetParentDirectoryOfDirPath(), KKU::osGetParentDirPath(), KKU::osGetPathPartOfFile(), KKU::osGetRootName(), KKU::osGetRootNameOfDirectory(), KKU::osGetRootNameWithExtension(), KKU::osLocateLastSlashChar(), KKU::osParseFileName(), KKU::osParseFileSpec(), KKU::osRemoveExtension(), CrossValidationApp::PostMisclassifiedImage(), and SipperHardware::InstrumentDataFileManager::SipperFileRootNameFromSipperImageFileName().
int32 KKStr::LocateLastOccurrence (const KKStr & s) const
Returns index of last occurrence of 's' otherwise -1.
Returns the position of the last occurrence of the string 's'.
A return of -1 indicates that there is no occurrence of 's' in the string.
Definition at line 2033 of file Str.cpp.
References Len().
int32 KKStr::LocateStr (const KKStr & searchStr) const
Returns index of 1st occurrence of 'searchStr' otherwise -1.
returns the position of the 1st occurrence of the string 'searchStr'.
A return of -1 indicates that there is no occurrence of 'searchStr' in the string.
Definition at line 1973 of file Str.cpp.
References MemCompare().
Referenced by MLL::TrainingClass::ExpandedDirectory().
void KKStr::LopOff (int32 lastCharPos)
Trims off all characters after the 'lastCharPos' index; to make an empty string you would have to specify -1.
Remove characters from the end of the string.
Removes characters from end of string starting at position 'lastCharPos'. If 'lastCharPos' is greater than length of string will do nothing. If 'lastCharPos' is less than or equal to '0' will delete all characters from string.
Parameters
[in] lastCharPos Will remove all characters starting at 'lastCharPos' from end of string.
Definition at line 2701 of file Str.cpp.
void KKStr::Lower ()
Make all characters in the String into lower case.
Converts all characters in string to their Lower case equivalents via 'tolower'.
See Also
ToLower
Definition at line 2329 of file Str.cpp.
References x.
Referenced by ToLower().
KKStr KKStr::MaxLen (int32 maxLen) const
Definition at line 2346 of file Str.cpp.
References KKU::Max(), and SubStrPart().
Referenced by MLL::DataBase::LogEntriesProcessStart().
int32 KKStr::MemoryConsumedEstimated () const
Definition at line 772 of file Str.cpp.
Referenced by KKU::KKStrListIndexed::Add(), KKU::KKStrListIndexed::Delete(), KKU::GoalKeeper::MemoryConsumedEstimated(), KKU::Configuration::MemoryConsumedEstimated(), MLL::ModelParam::MemoryConsumedEstimated(), MLL::NormalizationParms::MemoryConsumedEstimated(), MLL::Attribute::MemoryConsumedEstimated(), MLL::FeatureVector::MemoryConsumedEstimated(), KKU::RunLog::MemoryConsumedEstimated(), MLL::SVMparam::MemoryConsumedEstimated(), MLL::SVMModel::MemoryConsumedEstimated(), MLL::Model::MemoryConsumedEstimated(), MLL::FileDesc::MemoryConsumedEstimated(), MLL::TrainingProcess2::MemoryConsumedEstimated(), MLL::FeatureVectorList::MemoryConsumedEstimated(), and KKU::Raster::MemoryConsumedEstimated().
bool KKStr::operator!= (const KKStr & right) const
Definition at line 1474 of file Str.cpp.
References Compare().
bool KKStr::operator!= (const KKStrConstPtr & right) const
Definition at line 1493 of file Str.cpp.
References Compare().
bool KKStr::operator!= (const char * rtStr) const
Definition at line 1512 of file Str.cpp.
References StrEqual().
bool KKStr::operator!= (const std::string right) const
Definition at line 1527 of file Str.cpp.
References Compare().
KKStr KKStr::operator+ (const char * right) const
Definition at line 3580 of file Str.cpp.
References Append().
KKStr KKStr::operator+ (const KKStr & right) const
Definition at line 3592 of file Str.cpp.
References Append().
KKStr KKStr::operator+ (int16 right) const
Definition at line 3604 of file Str.cpp.
References Append(), and KKU::SPRINTF().
KKStr KKStr::operator+ (uint16 right) const
Definition at line 3616 of file Str.cpp.
References Append(), and KKU::SPRINTF().
KKStr KKStr::operator+ (int32 right) const
Definition at line 3630 of file Str.cpp.
References Append(), and KKU::SPRINTF().
KKStr KKStr::operator+ (uint32 right) const
Definition at line 3644 of file Str.cpp.
References Append(), and KKU::SPRINTF().
KKStr KKStr::operator+ (int64 right) const
Definition at line 3658 of file Str.cpp.
References Append(), and KKU::SPRINTF().
KKStr KKStr::operator+ (uint64 right) const
Definition at line 3672 of file Str.cpp.
References Append(), and KKU::SPRINTF().
KKStr KKStr::operator+ (float right) const
Definition at line 3686 of file Str.cpp.
References Append(), and KKU::SPRINTF().
KKStr KKStr::operator+ (double right) const
Definition at line 3702 of file Str.cpp.
References Append(), and KKU::SPRINTF().
KKStr& KKU::KKStr::operator+= (const char * right) inline
Definition at line 617 of file Str.h.
KKStr& KKU::KKStr::operator+= (const KKStr & right) inline
Definition at line 618 of file Str.h.
KKStr& KKU::KKStr::operator+= (int16 right) inline
Definition at line 619 of file Str.h.
KKStr& KKU::KKStr::operator+= (uint16 right) inline
Definition at line 620 of file Str.h.
KKStr& KKU::KKStr::operator+= (int32 right) inline
Definition at line 621 of file Str.h.
KKStr& KKU::KKStr::operator+= (uint32 right) inline
Definition at line 622 of file Str.h.
KKStr& KKU::KKStr::operator+= (int64 right) inline
Definition at line 623 of file Str.h.
KKStr& KKU::KKStr::operator+= (uint64 right) inline
Definition at line 624 of file Str.h.
KKStr& KKU::KKStr::operator+= (float right) inline
Definition at line 625 of file Str.h.
KKStr& KKU::KKStr::operator+= (double right) inline
Definition at line 626 of file Str.h.
bool KKStr::operator< (const KKStr & right) const
Definition at line 1551 of file Str.cpp.
References Compare().
KKStr & KKStr::operator<< (const char * right)
Definition at line 3724 of file Str.cpp.
References Append(), and KKU::endl().
KKStr & KKStr::operator<< (const KKStr & right)
Definition at line 3739 of file Str.cpp.
References Append(), and Str().
KKStr & KKStr::operator<< (char right)
Definition at line 3716 of file Str.cpp.
References Append().
KKStr & KKStr::operator<< (int16 right)
Definition at line 3747 of file Str.cpp.
References AppendInt32().
KKStr & KKStr::operator<< (uint16 right)
Definition at line 3755 of file Str.cpp.
References AppendUInt32().
KKStr & KKStr::operator<< (int32 right)
Definition at line 3763 of file Str.cpp.
References AppendInt32().
KKStr & KKStr::operator<< (uint32 right)
Definition at line 3771 of file Str.cpp.
References AppendUInt32().
KKStr & KKStr::operator<< (int64 right)
Definition at line 3779 of file Str.cpp.
References Append(), Str(), and KKU::StrFormatInt64().
KKStr & KKStr::operator<< (uint64 right)
Definition at line 3789 of file Str.cpp.
References Append(), Str(), and KKU::StrFormatInt64().
KKStr & KKStr::operator<< (float right)
Definition at line 3799 of file Str.cpp.
References Append(), and KKU::SPRINTF().
KKStr & KKStr::operator<< (double right)
Definition at line 3821 of file Str.cpp.
References Append(), and KKU::SPRINTF().
KKStr & KKStr::operator<< (std::ostream &(*)(std::ostream &) mf)
Definition at line 4627 of file Str.cpp.
References Append().
bool KKStr::operator<= (const KKStr & right) const
Definition at line 1558 of file Str.cpp.
References Compare().
KKStr & KKStr::operator= (const KKStr & src)
Definition at line 1311 of file Str.cpp.
KKStr & KKStr::operator= (const char * src)
Definition at line 1361 of file Str.cpp.
References KKU::STRCOPY().
KKStr & KKStr::operator= (int32 right)
Definition at line 1397 of file Str.cpp.
References KKU::SPRINTF(), and KKU::STRCOPY().
KKStr & KKStr::operator= (const std::vector< KKStr > & right)
Definition at line 1428 of file Str.cpp.
References Len(), Str(), and x.
bool KKStr::operator== (const KKStr & right) const
Definition at line 1466 of file Str.cpp.
References Compare().
bool KKStr::operator== (const KKStrConstPtr & right) const
Definition at line 1482 of file Str.cpp.
References Compare().
bool KKStr::operator== (const char * rtStr) const
Definition at line 1504 of file Str.cpp.
References StrEqual().
bool KKStr::operator== (const std::string right) const
Definition at line 1519 of file Str.cpp.
References Compare().
bool KKStr::operator> (const KKStr & right) const
Definition at line 1535 of file Str.cpp.
References Compare().
bool KKStr::operator>= (const KKStr & right) const
Definition at line 1543 of file Str.cpp.
References Compare().
char KKStr::operator[] (int16 i) const
Returns back the character at position 'i', if i > length of KKStr then returns back 0.
Definition at line 3105 of file Str.cpp.
char KKStr::operator[] (uint16 i) const
Returns back the character at position 'i', if i > length of KKStr then returns back 0.
Definition at line 3122 of file Str.cpp.
char KKStr::operator[] (int32 i) const
Returns back the character at position 'i', if i > length of KKStr then returns back 0.
Definition at line 3139 of file Str.cpp.
char KKStr::operator[] (uint32 i) const
Returns back the character at position 'i', if i > length of KKStr then returns back 0.
Definition at line 3156 of file Str.cpp.
VectorKKStr KKStr::Parse (const char * delStr = "\n\r\t, ") const
Will break up the contents of the string into tokens where one of the characters in 'delStr' separates each token.
Definition at line 3187 of file Str.cpp.
References Empty(), ExtractToken2(), TrimLeft(), and TrimRight().
Referenced by MLL::FeatureFileIOPices::LoadFile().
KKStr KKStr::QuotedStr () const
Returns a quoted version of string where special characters line Line Feed, Carriage Return, and Tab, are encoded as escape sequences.
string where 'Line Feed(
'), Carriage Returns(''), Tabs(''), and Quotes(") are coded as escape sequences "
", "", "t", or '\". It is then enclosed in quotes(").
Returns
Quoted String.
Definition at line 2725 of file Str.cpp.
References Append(), and Len().
Referenced by MLL::DataBase::FeatureDataForImageGroup(), MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::DataBase::FeatureDataGetScanLinesPerMeterProfile(), MLL::DataBase::FeatureDataInsertRow(), MLL::DataBase::FeatureDataRecLoad(), MLL::DataBase::FeatureDataUpdate(), MLL::DataBase::FeatureDataUpdateInstrumentDataFields(), MLL::DataBase::GpsDataDelete(), MLL::DataBase::GpsDataInsert(), MLL::DataBase::GpsDataQuery(), MLL::DataBase::ImageFullSizeDelete(), MLL::DataBase::ImageFullSizeLoad(), MLL::DataBase::ImageGetClassStatistics(), MLL::DataBase::ImageGetDepthStatistics(), MLL::DataBase::ImageGroupEntriesInsert(), MLL::DataBase::ImageGroupInsert(), MLL::DataBase::ImageGroupLoad(), MLL::DataBase::ImageInsert(), MLL::DataBase::ImageListOfImageFileNamesByScanLineRange(), MLL::DataBase::ImageLoad(), MLL::DataBase::ImageRemoveValidation(), MLL::DataBase::ImagesDeleteOneImage(), MLL::DataBase::ImagesEraseSipperFile(), MLL::DataBase::ImagesEraseSipperFileSizeRange(), MLL::DataBase::ImagesLocateClosestImage(), MLL::DataBase::ImagesQuery(), MLL::DataBase::ImagesQueryByGrouop(), MLL::DataBase::ImagesQueryForScanLineRange(), MLL::DataBase::ImagesRetrieveValidatedClass(), MLL::DataBase::ImagesUpdateImageSize(), MLL::DataBase::ImagesUpdatePredictions(), MLL::DataBase::ImagesUpdatePredictionsList(), MLL::DataBase::ImagesUpdateValidatedAndPredictClass(), MLL::DataBase::ImagesUpdateValidatedClass(), MLL::DataBase::ImageUpdate(), MLL::DataBase::ImageUpdateInstrumentDataFields(), MLL::DataBase::InsertCruise(), MLL::DataBase::InstrumentDataBinByMeterDepth(), MLL::DataBase::InstrumentDataGetByScanLine(), MLL::DataBase::InstrumentDataGetSpecificFields(), MLL::DataBase::InstrumentDataGetVolumePerMeterDepth(), MLL::DataBase::InstrumentDataInsert(), MLL::DataBase::InstrumentDataLoad(), MLL::DataBase::InstrumentDataRetrieveGPSInfo(), MLL::DataBase::InstrumentDataSaveListForOneSipperFile(), MLL::DataBase::LogEntriesProcessEnd(), MLL::DataBase::LogEntriesProcessStart(), MarineSnowReportDeployment(), MLL::DataBase::MLClassDelete(), MLL::DataBase::MLClassInsert(), MLL::DataBase::MLClassInsertReturn(), MLL::DataBase::MLClassLoad(), MLL::DataBase::MLClassUpdate(), MLL::DataBase::SipperCruiseDelete(), MLL::DataBase::SipperCruiseInsert(), MLL::DataBase::SipperCruiseLoad(), MLL::DataBase::SipperCruiseUpdate(), MLL::DataBase::SipperDeploymentDelete(), MLL::DataBase::SipperDeploymentInsert(), MLL::DataBase::SipperDeploymentLoad(), MLL::DataBase::SipperDeploymentUpdate(), MLL::DataBase::SipperFileGetList(), MLL::DataBase::SipperFileInsert(), MLL::DataBase::SipperFileLoad(), MLL::DataBase::SipperFileRecLoad(), MLL::DataBase::SipperFilesDelete(), MLL::DataBase::SipperFilesGetCTDDateTime(), MLL::DataBase::SipperFilesUpdateExtractionStatus(), MLL::DataBase::SipperFileUpdate(), MLL::DataBase::SipperFileUpdateFileSizeStats(), MLL::DataBase::SipperStationDelete(), MLL::DataBase::SipperStationInsert(), MLL::DataBase::SipperStationLoad(), MLL::DataBase::SipperStationUpdate(), MLL::SVMModel::Write(), MLL::SVMparam::WriteXML(), MLL::MLClass::WriteXML(), and MLL::Model::WriteXML().
void KKStr::RightPad (int32 width, char ch = ' ')
Returns a string of spaces 'c' charaters long.
Parameters
[in] c Number of space charaters to fill the string with.
Definition at line 2099 of file Str.cpp.
References KKU::endl(), and x.
Referenced by MLL::SizeDistribution::ClassTotals::PrintFormatedLine(), Spaces(), and Wide().
KKStr KKStr::Spaces (int32 c) static
Definition at line 3904 of file Str.cpp.
References RightPad().
Referenced by Wide().
VectorKKStr KKStr::Split (const char * delStr = "\n\r\t, ") const
Breaks up the contents of the string into tokens where the characters in 'delStr' acts as separaters each token.
Parameters
[in] delStr List of characters that where any one of them can be a delimiter.
Definition at line 3206 of file Str.cpp.
References Empty(), ExtractToken2(), TrimLeft(), and TrimRight().
Referenced by MLL::MLClassConstList::BuildListFromDelimtedStr(), MLL::MLClassList::BuildListFromDelimtedStr(), SipperHardware::CTD_Plus_Data::CTD_Plus_Data(), DelimitedStrToArray(), MLL::FeatureFileIOC45::GetFileDesc(), MLL::FeatureFileIOPices::GetFileDesc(), MLL::MLClass::MLClassForGivenHierarchialLevel(), MLL::ClassIndexList::ParseClassIndexList(), SipperHardware::SipperHeaderRec::ParseHeaderStr(), JobManagment::Job::PrerequisitesFromStr(), SipperHardware::InstrumentDataBatteryMeter::ProcessBatteryData(), SipperHardware::SipperHeaderRec::ProcessNameAndDataStrings(), JobManagment::Job::ProcessStatusStr(), and MLL::DataBaseImage::SizeCoordinates().
VectorKKStr KKStr::Split (char del) const
Splits the string up into tokens using 'del' as the separator returning them in a vector.
Definition at line 3226 of file Str.cpp.
References Empty(), ExtractToken2(), TrimLeft(), and TrimRight().
bool KKStr::StartsWith (const KKStr & value) const
Definition at line 1162 of file Str.cpp.
References Len().
Referenced by MLL::DataBaseImageValidatedEntryList::Load(), and MLL::TrainingConfiguration2::Save().
bool KKStr::StartsWith (const char * value) const
Definition at line 1172 of file Str.cpp.
bool KKStr::StartsWith (const KKStr & value, bool ignoreCase) const
Definition at line 1189 of file Str.cpp.
References Len(), and KKU::STRNICMP().
bool KKStr::StartsWith (const char * value, bool ignoreCase) const
Definition at line 1209 of file Str.cpp.
References KKU::STRNICMP().
const char* KKU::KKStr::Str () const inline
Returns a pointer to a ascii string.
Definition at line 403 of file Str.h.
Referenced by MLL::FeatureFileIO::AppendToFile(), KKU::RunLog::AttachFile(), KKU::RunLog::AttachFileAppend(), JobManagment::JobManager::Block(), KKU::BmpImage::BmpImage(), c_str(), MLL::ClassificationBiasMatrix::ClassificationBiasMatrix(), MLL::BinaryClassParms::CreateFromTabDelStr(), data(), KKU::DateType::DateType(), JobManagment::JobManager::EndBlock(), MLL::FeatureNumList::ExtractFeatureNumsFromStr(), ExtractTokenDouble(), ExtractTokenInt(), ExtractTokenUint(), Find(), MLL::FeatureFileIOSparse::GetFileDesc(), PicesInterface::TrainingModel2::GetListOfTrainingModels(), SipperHardware::SipperBuff::GuessFormatOfFile(), KKU::HashTable< Entry >::HashValue(), KKU::HTMLReport::HTMLReport(), MLL::DataBase::ImageGroupDelete(), MLL::DataBase::ImageGroupEntriesInsert(), MLL::DataBase::ImageGroupInsert(), MLL::DuplicateImage::ImageWithSmallestScanLine(), CImageExtractionWindowsApp::InitInstance(), MLL::DataBase::InsertCruise(), SipperHardware::InstrumentDataManager::InstrumentDataManager(), MLL::DataBase::InstrumentDataReFreshSipperFile(), SipperHardware::InstrumentDataReport::InstrumentDataReport(), PicesInterface::PicesKKStr::KKStrToSystenStr(), MLL::ClassAssignments::Load(), MLL::DataBaseImageValidatedEntryList::Load(), MLL::SVMparam::Load(), SipperHardware::SipperFileList::Load(), MLL::FeatureNumList::Load(), MLL::MLClassConstList::Load(), MLL::Model::Load(), MLL::MLClassList::Load(), MLL::FeatureFileIOC45::LoadFeatureFile(), MLL::FeatureFileIO::LoadFeatureFile(), MLL::FeatureFileIOColumn::LoadFile(), MLL::FeatureFileIOUCI::LoadFile(), MLL::FeatureFileIOPices::LoadFile(), MLL::FeatureFileIOSparse::LoadFile(), KKU::Configuration::LoadFile(), MLL::DataBaseUpdate::LoadSourceFile(), LocateEnvStrStart(), CrossValidationApp::Main(), MarineSnowReportDeployment(), SipperHardware::SipperBuff::Open(), KKU::operator<<(), KKU::RunLog::operator<<(), operator<<(), operator=(), MLL::FeatureVectorList::OrderUsingNamesFromAFile(), KKU::osChangeDir(), KKU::osCreateDirectory(), KKU::osDeleteFile(), osDirectoryList(), KKU::osFileExists(), osFileNameMatchesSearchFields(), KKU::osGetEnvVariable(), KKU::osGetFileDateTime(), KKU::osGetFileSize(), KKU::osGetListOfDirectories(), KKU::osLookForFile(), KKU::osMoveFileBetweenDirectories(), osParseSearchSpec(), KKU::osRenameFile(), KKU::osValidDirectory(), ImageExtractionManager::ExtractionParms::ParseCmdLine(), MLL::SVMparam::ParseCmdLineParameter(), KKU::KKStrList::ParseDelimitedString(), PicesInterface::PicesRunLog::PicesRunLog(), CrossValidationApp::ProcessCmdLineParameter(), JobManagment::Job::ProcessStatusStr(), MLL::DataBase::QueryStatement(), MLL::DataBase::QueryStatementKKStr(), KKU::ReadImagePGM(), KKU::ReadImagePNG(), KKU::RunLog::RunLog(), SipperHardware::InstrumentDataList::Save(), KKU::Chart::Save(), KKU::HashTable< Entry >::Save(), MLL::DataBaseImageValidatedEntryList::Save(), MLL::ClassAssignments::Save(), MLL::SVMparam::Save(), KKU::Histogram::Save(), MLL::NormalizationParms::Save(), SipperHardware::SipperFileList::Save(), KKU::BmpImage::Save(), MLL::Orderings::Save(), MLL::TrainingConfiguration2::Save(), MLL::MLClassConstList::Save(), MLL::Model::Save(), MLL::SVMModel::Save(), MLL::MLClassList::Save(), MLL::FeatureFileIO::SaveFeatureFile(), MLL::FeatureFileIORoberts::SaveFile(), MLL::FeatureFileIOC45::SaveFile(), MLL::AbundanceCorrectionMatrix::SaveForConfigFileName(), KKU::BmpImage::SaveGrayscaleInverted4Bit(), KKU::BmpImage::SaveGrayscaleInverted8Bit(), KKU::SaveImagePGM(), KKU::SaveImagePNG(), MLL::FeatureVectorList::SaveOrderingOfImages(), MLL::TrainingProcess2::SaveResults(), MLL::DataBase::SipperCruiseDelete(), MLL::DataBase::SipperCruiseInsert(), MLL::DataBase::SipperCruiseUpdate(), MLL::DataBase::SipperFileInsert(), MLL::DataBase::SipperFilesDelete(), MLL::DataBase::SipperFilesGetCTDDateTime(), MLL::DataBase::SipperFileUpdate(), MLL::DataBase::SipperFileUpdateFileSizeStats(), ImageExtractionManager::ImageExtractionThread::Start(), KKU::TimeType::TimeType(), KKU::TokenBufferStream::TokenBufferStream(), MLL::CompressionStats::UpdateFromTabDelStr(), CrossValidationApp::ValidationProcess(), KKU::KKStrException::what(), Wide(), MLL::SVMModel::Write(), CrossValidationApp::WriteABiasMatrix(), and MLL::DataBaseServerList::WriteConfigFile().
const char * KKStr::Str (const char * s) static
Definition at line 278 of file Str.cpp.
void KKStr::StrCapitalize (char * str) static
Definition at line 3913 of file Str.cpp.
Referenced by StrInStr().
int32 KKStr::StrCompareIgnoreCase (const char * s1, const char * s2) static
Definition at line 299 of file Str.cpp.
Referenced by EqualIgnoreCase().
void KKStr::StrDelete (char ** str) static
Definition at line 288 of file Str.cpp.
bool KKStr::StrEqual (const char * s1, const char * s2) static
Definition at line 354 of file Str.cpp.
Referenced by EndsWith(), operator!=(), and operator==().
bool KKStr::StrEqualNoCase (const char * s1, const char * s2) static
Definition at line 370 of file Str.cpp.
Referenced by EndsWith().
bool KKStr::StrInStr (const char * target, const char * searchStr) static
Definition at line 3929 of file Str.cpp.
References StrCapitalize().
Referenced by Contains(), MLL::FeatureFileIOPices::FeatureDataReSink(), and StrInStr().
bool KKStr::StrInStr (const KKStr & searchField) const
Searches for the occurrence of 'searchField' and where in the string.
If found will return 'true' otherwise 'false'.
Definition at line 2566 of file Str.cpp.
References StrInStr().
void KKStr::StrReplace (char ** dest, const char * src)
Replaces the contents of *dest with *src.
First deletes current *dest then allocates new a new string to **dest so no memory is lost.
Definition at line 398 of file Str.cpp.
References KKU::endl(), KKU::STRCOPY(), and KKU::StrFormatInt().
wchar_t * KKStr::StrWide () const
Returns a Wide Character version of the string.
The caller will be responsible for deleting this string.
Definition at line 1245 of file Str.cpp.
References x.
KKStr KKStr::SubStrPart (int32 firstChar) const
returns a SubString consisting of all characters starting at index 'firstChar' until the end of the string.
If the index 'firstChar' is past the end of the string a empty string will be returned.
Parameters
[in] firstChar First character in string to include in the sub-string.
Returns
Sub-string.
Definition at line 2615 of file Str.cpp.
Referenced by MLL::FeatureFileIODstWeb::AttrDescLine::AttrDescLine(), CreateBfsFromMfs(), ExtractAttribute(), MLL::MLClassConstList::ExtractTwoTitleLines(), MLL::MLClassList::ExtractTwoTitleLines(), MLL::FeatureFileIOPices::FeatureDataReSink(), KKU::PointList::FromDelStr(), MLL::MLClass::GetClassNameFromDirName(), SipperHardware::InstrumentDataFileManager::GetClosestInstrumentData(), MLL::FeatureFileIODstWeb::GetFileDesc(), MLL::FeatureFileIOC45::GetFileDesc(), MLL::FeatureFileIOUCI::GetFileDesc(), MLL::FeatureFileIOPices::GetFileDesc(), MLL::FeatureFileIOSparse::GetFileDesc(), GetNextToken2(), MLL::DuplicateImage::ImageWithSmallestScanLine(), MLL::DataBase::InsertCruise(), MLL::FeatureFileIOC45::LoadFeatureFile(), MLL::FeatureFileIODstWeb::LoadFile(), MLL::FeatureFileIOUCI::LoadFile(), MLL::FeatureFileIOPices::LoadFile(), MLL::FeatureFileIOSparse::LoadFile(), KKU::Configuration::LoadFile(), MaxLen(), MLL::FeatureVectorList::OrderUsingNamesFromAFile(), KKU::osCreateDirectoryPath(), KKU::osGetFileNamePartOfFile(), KKU::osGetListOfDirectories(), KKU::osGetListOfFiles(), KKU::osGetParentDirectoryOfDirPath(), KKU::osGetParentDirPath(), KKU::osGetPathPartOfFile(), KKU::osGetRootName(), KKU::osGetRootNameOfDirectory(), KKU::osGetRootNameWithExtension(), KKU::osParseFileName(), KKU::osParseFileSpec(), KKU::osRemoveExtension(), KKU::osSplitDirectoryPathIntoParts(), KKU::osSubstituteInEvironmentVariables(), SipperHardware::SipperHeaderRec::ParseHeaderStr(), CrossValidationApp::PostMisclassifiedImage(), MLL::ModelParamDual::ReadSpecificImplementationXML(), MLL::ModelParamSvmBase::ReadSpecificImplementationXML(), MLL::ModelParamUsfCasCor::ReadSpecificImplementationXML(), SipperHardware::InstrumentDataFileManager::SipperFileRootNameFromSipperImageFileName(), JobManagment::JobManager::StatusFileProcessLine(), StripOutAnyComments(), SipperHardware::SipperVariables::SubstituteInEvironmentVariables(), SVM289_MFS::svm_load_model_XML_SupportVectorSection(), SVM289_BFS::svm_load_model_XML_SupportVectorSection(), KKU::TimeType::TimeType(), and ToPercentage().
KKStr KKStr::SubStrPart (int32 firstChar, int32 lastChar) const
returns a SubString consisting of all characters starting at index 'firstChar' and ending at 'lastIndex'
If the index 'firstChar' is past the end of the string a empty string will be returned. If 'lastIndex is past the end of the string then will only include characters until the end of the string.
The length of the substring will be (lsastChar - firstChar) + 1.
Parameters
[in] firstChar First character in string to include in the sub-string.
[in] lsastChar Last character in include in the string.
Returns
Sub-string.
Definition at line 2637 of file Str.cpp.
References x.
KKStr KKStr::Tail (int32 tailLen) const
Return back the last 'tailLen' characters.
Returns a string consisting of the 'tailLen' characters from the end of the string.
ex:
   if  test = "Hello World.";
       test.Tail (2) will return "d.".
Definition at line 2682 of file Str.cpp.
References KKU::Max().
Referenced by CreateBfsFromMfs().
bool KKStr::ToBool () const
Returns the bool equivalent of the string, ex 'Yes' = true, 'No' = false, 'True' = true, etc.
Definition at line 3249 of file Str.cpp.
References KKU::STRICMP().
Referenced by KKU::KKStrParser::GetNextTokenBool(), ImageExtractionManager::ExtractionParms::ParseCmdLine(), MLL::ModelParam::ParseCmdLine(), and MLL::ModelParamUsfCasCor::ReadSpecificImplementationXML().
double KKStr::ToDouble () const
Definition at line 3267 of file Str.cpp.
Referenced by KKU::KKStrParser::GetNextTokenDouble(), MLL::SVMparam::ParseCmdLineParameter(), SipperHardware::SipperHeaderRec::ProcessNameAndDataStrings(), MLL::AbundanceCorrectionMatrix::ReadArray(), MLL::AbundanceCorrectionMatrix::ReadVector(), SVM289_MFS::svm_load_model_XML_SupportVectorSection(), SVM289_BFS::svm_load_model_XML_SupportVectorSection(), ToLatitude(), and ToLongitude().
float KKStr::ToFloat () const
Definition at line 3279 of file Str.cpp.
Referenced by KKU::KKStrParser::GetNextTokenFloat(), MLL::FeatureFileIOC45::LoadFile(), ReadFloatArrayUntilEndTag(), and ToPercentage().
int32 KKStr::ToInt () const
Definition at line 3291 of file Str.cpp.
Referenced by KKU::KKStrParser::GetNextTokenInt(), SipperHardware::SipperHeaderRec::ProcessNameAndDataStrings(), JobManagment::Job::ProcessStatusStr(), KKU::ReadImagePGM(), KKU::ReadImagePNG(), ReadIntArrayUntilEndTag(), MLL::ModelParamKnn::ReadSpecificImplementationXML(), MLL::AbundanceCorrectionMatrix::ReadXml(), JobManagment::JobManager::StatusFileProcessLine(), SVM289_MFS::svm_load_model_XML_SupportVectorSection(), and SVM289_BFS::svm_load_model_XML_SupportVectorSection().
int16 KKStr::ToInt16 () const
Definition at line 3302 of file Str.cpp.
int32 KKStr::ToInt32 () const
Definition at line 3313 of file Str.cpp.
Referenced by KKU::osGetNumberOfProcessors(), and ImageExtractionManager::ExtractionParms::ParseCmdLine().
KKU::int64 KKStr::ToInt64 () const
Definition at line 3324 of file Str.cpp.
Referenced by MLL::ModelParamUsfCasCor::ReadSpecificImplementationXML().
double KKStr::ToLatitude () const
Processes string as if a standard latitude; ex: "15:32.2S" = -15.53833.
Definition at line 3398 of file Str.cpp.
References ChopFirstChar(), ChopLastChar(), ExtractToken2(), FirstChar(), LastChar(), and ToDouble().
Referenced by PicesInterface::PicesKKStr::StrToLatitude().
long KKStr::ToLong () const
Definition at line 3337 of file Str.cpp.
Referenced by SipperHardware::InstrumentDataFileManager::GetClosestInstrumentData(), and KKU::KKStrParser::GetNextTokenLong().
double KKStr::ToLongitude () const
Processes string as if a standard longitude; ex: "95:32.2E" = 95.53833.
Definition at line 3450 of file Str.cpp.
References ChopFirstChar(), ChopLastChar(), ExtractToken2(), FirstChar(), LastChar(), and ToDouble().
Referenced by PicesInterface::PicesKKStr::StrToLongitude().
KKStr KKStr::ToLower () const
Definition at line 2369 of file Str.cpp.
References Lower().
Referenced by SipperHardware::SipperHeaderRec::ParseHeaderStr(), SipperHardware::SipperHeaderRec::ProcessNameAndDataStrings(), and KKU::ReadImage().
float KKStr::ToPercentage () const
Definition at line 3349 of file Str.cpp.
References LastChar(), Len(), SubStrPart(), and ToFloat().
Referenced by CrossValidationApp::ProcessCmdLineParameter().
KKU::uint32 KKStr::ToUint () const
Definition at line 3362 of file Str.cpp.
Referenced by KKU::KKStrParser::GetNextTokenUint().
KKU::uint32 KKStr::ToUint32 () const
Definition at line 3378 of file Str.cpp.
KKU::uint64 KKStr::ToUint64 () const
Definition at line 3386 of file Str.cpp.
KKU::ulong KKStr::ToUlong () const
Definition at line 3370 of file Str.cpp.
KKStr KKStr::ToUpper () const
Definition at line 2357 of file Str.cpp.
References Upper().
Referenced by MLL::MLClass::CreateNewMLClass(), MLL::ModelParam::EncodingMethodFromStr(), SipperHardware::InstrumentData::GetFieldNum(), SipperHardware::InstrumentData::GetFieldNumFromShortName(), MLL::FeatureFileIOPices::LoadFile(), MLL::MLClassConstList::LookUpByName(), MLL::MLClassList::LookUpByName(), SipperHardware::Instrument::LookUpByShortName(), and KKU::Application::ProcessCmdLineParameters().
void KKStr::TrimLeft (const char * whiteSpaceChars = "\n\r\t ")
Definition at line 1652 of file Str.cpp.
References x.
Referenced by MLL::FeatureFileIODstWeb::AttrDescLine::AttrDescLine(), MLL::ConfusionMatrix2::BuildFromIstreamXML(), KKU::CmdLineExpander::CmdLineExpander(), MLL::FeatureNumList::ExtractFeatureNumsFromStr(), PicesInterface::PicesClassList::ExtractThreeTitleLines(), KKU::PointList::FromDelStr(), MLL::FeatureFileIODstWeb::GetFileDesc(), MLL::FeatureFileIOUCI::GetFileDesc(), MLL::ClassAssignments::Load(), MLL::FeatureFileIOUCI::LoadFile(), KKU::Configuration::LoadFile(), MLL::DataBase::MLClassLoad(), KKU::operator>>(), Parse(), MLL::ModelParam::ParseCmdLine(), MLL::ModelParamOldSVM::ParseCmdLine(), MLL::MLClass::ProcessRawData(), JobManagment::Job::ProcessStatusStr(), MLL::TrainingProcess2::Read(), MLL::TrainingConfiguration2::Save(), Split(), JobManagment::JobManager::StatusFileProcessLine(), JobManagment::JobManager::StatusFileProcessLineJobStatusChange(), ToFloat(), and Wide().
KKStr & KKStr::TrimRight (const char * whiteSpaceChars = "\n\r\t ")
Definition at line 1601 of file Str.cpp.
References x.
Referenced by KKU::CmdLineExpander::CmdLineExpander(), PicesInterface::PicesClassList::ExtractThreeTitleLines(), MLL::FeatureFileIODstWeb::GetFileDesc(), MLL::FeatureFileIOUCI::GetFileDesc(), KKU::KKStrParser::GetRestOfLine(), KKU::KKStrParser::GetRestOfStr(), MLL::ClassAssignments::Load(), MLL::MLClassConstList::Load(), MLL::MLClassList::Load(), MLL::FeatureFileIOUCI::LoadFile(), MLL::FeatureFileIOPices::LoadFile(), KKU::Configuration::LoadFile(), MLL::DataBase::MLClassLoad(), KKU::operator>>(), Parse(), KKU::KKStrList::ParseDelimitedString(), MLL::MLClass::ProcessRawData(), JobManagment::Job::ProcessStatusStr(), MLL::TrainingProcess2::Read(), ReadNextToken(), MLL::TrainingConfiguration2::Save(), Split(), JobManagment::JobManager::StatusFileProcessLine(), JobManagment::JobManager::StatusFileProcessLineJobStatusChange(), ToFloat(), and Wide().
void KKStr::TrimRightChar ()
Definition at line 1630 of file Str.cpp.
void KKStr::Upper ()
Converts all characters in string to their Upper case equivalents via 'toupper'.
See Also
ToUpper
Definition at line 2308 of file Str.cpp.
References x.
Referenced by MLL::ModelParam::CompressionMethodFromStr(), MLL::BinaryClassParms::CreateFromTabDelStr(), MLL::FeatureNumList::ExtractFeatureNumsFromStr(), ExtractTokenBool(), MLL::FeatureFileIODstWeb::GetFileDesc(), MLL::FeatureFileIOPices::GetFileDesc(), MLL::DuplicateImage::ImageWithSmallestScanLine(), MLL::FeatureFileIOC45::LoadFeatureFile(), MLL::FeatureFileIODstWeb::LoadFile(), MLL::FeatureFileIOPices::LoadFile(), KKU::Configuration::LoadFile(), MLL::SizeDistribution::ClassTotalsList::LookUp(), MLL::AttributeList::LookUpByName(), KKU::osLookForFile(), ImageExtractionManager::ExtractionParms::ParseCmdLine(), MLL::ModelParam::ParseCmdLine(), MLL::ModelParamOldSVM::ParseCmdLine(), MLL::SVMparam::ParseCmdLineParameter(), CrossValidationApp::ProcessCmdLineParameter(), MLL::MLClass::ProcessRawData(), JobManagment::Job::ProcessStatusStr(), MLL::NormalizationParms::Read(), MLL::TrainingProcess2::Read(), MLL::Model::ReadSkipToSection(), MLL::ModelParamKnn::ReadSpecificImplementationXML(), MLL::ModelParamDual::ReadSpecificImplementationXML(), MLL::ModelParamOldSVM::ReadSpecificImplementationXML(), MLL::ModelParamSvmBase::ReadSpecificImplementationXML(), MLL::ModelParamUsfCasCor::ReadSpecificImplementationXML(), MLL::ModelKnn::ReadSpecificImplementationXML(), MLL::ModelUsfCasCor::ReadSpecificImplementationXML(), MLL::ModelSvmBase::ReadSpecificImplementationXML(), MLL::ModelDual::ReadSpecificImplementationXML(), MLL::SVMparam::ReadXML(), MLL::Model::ReadXML(), KKU::SaveImage(), SipperHardware::SipperFileFormatFromStr(), KKU::SupportedImageFileFormat(), ToUpper(), and MLL::CompressionStats::UpdateFromTabDelStr().
bool KKStr::ValidInt (int32 & value)
returns true if KKStr is formated as a valid integer otherwise false.
value = KKStr as interpreted as a integer.
Definition at line 2383 of file Str.cpp.
bool KKStr::ValidMoney (float & value) const
Definition at line 2429 of file Str.cpp.
bool KKStr::ValidNum (double & value) const
Returns true if String is a valid number, ex 1.0 or -3.123, etc.
Definition at line 2488 of file Str.cpp.
KKStr KKStr::Wide (int32 width, char dir = 'R') const
Pads the string with spaces so that it is exactly 'width' characters long.
Can pad either left, right, or center as specified by 'dir'. If KKStr Already greater than 'width' will truncate new string.
Parameters
[in] width Width of KKStr; Will pad KKStr with spaces until it is width long.
[in] dir 'L' - Pad on the left side, 'R' - Pad on the right side, 'C' - Pad on left and Right so that text is centered.
Definition at line 2063 of file Str.cpp.
References LeftPad(), Len(), RightPad(), Spaces(), Str(), TrimLeft(), TrimRight(), and x.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Str.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Str.cpp