Pices: SipperFile.ActiveTrainingLibraries Class Reference
SipperFile.ActiveTrainingLibraries Class Reference
A class that will consist of static metods only.
Public Member Functions
delegate void DoneLoadingEvent (TrainingModel2 model)
Static Public Member Functions
static void CancelLoads ()
Will cancel the loading of any models still loading.
static void CancelLoadWait (int maxMilliSecsToWait)
static void LoadConfiguration ()
static void LoadModels ()
static void MakePredictions (PicesRaster raster, InstrumentData instrumentData, String imageFileName, ref PicesPredictionList model1Predictions, ref PicesPredictionList model2Predictions, PicesRunLog runLog)
Using supplied 'Raster' data it will call each currently active model and return there predictions.
static void MakePredictions (PicesFeatureVector featureVector, ref PicesPredictionList model1Predictions, ref PicesPredictionList model2Predictions, PicesRunLog runLog)
static void MakePredictions (PicesFeatureVector featureVector, ref PicesPrediction model1Prediction1, ref PicesPrediction model1Prediction2, ref PicesPrediction model2Prediction1, ref PicesPrediction model2Prediction2, PicesRunLog runLog)
static void MakePredictions (PicesRaster raster, ref PicesPrediction model1Prediction1, ref PicesPrediction model1Prediction2, ref PicesPrediction model2Prediction1, ref PicesPrediction model2Prediction2, PicesRunLog runLog)
static TrainingModel2 Model1 ()
static PicesClassList Model1ListOfClasses ()
static TrainingModel2 Model2 ()
static bool ModelsAreAvailable ()
Indicates wheather tehre is at least one active Training Model fully loaded.
static bool ModelsAreLoading ()
static void SaveConfiguration ()
static void SetModel1 (String _model1Name, bool _forceRebuild, DoneLoadingEvent _doneLoadingEvent)
static void SetModel2 (String _model2Name, bool _forceRebuild, DoneLoadingEvent _doneLoadingEvent)
Properties
static String Model1Name [get]
static String Model2Name [get]
Detailed Description
A class that will consist of static metods only.
This is where we will keep track of the current active training libraries. Thios way we will not need to implement the code in each seperate application.
Once a model is loaded via "SetModel1" or "SetModel2" they will not be unloaded except by the Memory Manager. This way if a process is using a specific model that was retrieved by "Model1" or "Model2" they can continue to use it even if a new model is set by "SetModel1" or "SetModel2".
Definition at line 36 of file ActiveTrainingLibraries.cs.
Member Function Documentation
static void SipperFile.ActiveTrainingLibraries.CancelLoads () inline static
Will cancel the loading of any models still loading.
Call this method to stop any models that are currently loading. It does this by setting the cancel flag for each of them and then returns. TrainingModelStatus.CancelLoad
Definition at line 66 of file ActiveTrainingLibraries.cs.
References SipperFile.TrainingModelStatus.CancelLoad().
Referenced by SipperFile.ActiveTrainingLibraries.CancelLoadWait().
static void SipperFile.ActiveTrainingLibraries.CancelLoadWait (int maxMilliSecsToWait) inline static
Definition at line 632 of file ActiveTrainingLibraries.cs.
References SipperFile.ActiveTrainingLibraries.CancelLoads(), SipperFile.TrainingModelStatus.ForceCancelation(), and SipperFile.ActiveTrainingLibraries.ModelsAreLoading().
delegate void SipperFile.ActiveTrainingLibraries.DoneLoadingEvent (TrainingModel2 model)
static void SipperFile.ActiveTrainingLibraries.LoadConfiguration () inline static
Definition at line 392 of file ActiveTrainingLibraries.cs.
Referenced by SipperFile.ActiveTrainingLibraries.LoadModels(), and SipperFile.ActiveTrainingLibraries.ModelsAreAvailable().
static void SipperFile.ActiveTrainingLibraries.LoadModels () inline static
Definition at line 80 of file ActiveTrainingLibraries.cs.
References SipperFile.ActiveTrainingLibraries.LoadConfiguration(), SipperFile.ActiveTrainingLibraries.SetModel1(), and SipperFile.ActiveTrainingLibraries.SetModel2().
static void SipperFile.ActiveTrainingLibraries.MakePredictions (PicesRaster raster, InstrumentData instrumentData, String imageFileName, ref PicesPredictionList model1Predictions, ref PicesPredictionList model2Predictions, PicesRunLog runLog) inline static
Using supplied 'Raster' data it will call each currently active model and return there predictions.
Parameters
raster Raster of image to predict. .
instrumentData Instrument data that was recorded with the 'raster' .
imageFileName Name of the image file.
model1Predictions The model1 predictions.
model2Predictions The model2 predictions.
runLog The run log.
Definition at line 212 of file ActiveTrainingLibraries.cs.
References PicesInterface::PicesFeatureVector.AddInstrumentData(), PicesInterface::PicesDataBase.Close(), SipperFile.InstrumentData.Depth(), SipperFile.InstrumentData.Fluorescence(), PicesInterface::PicesDataBase.GetGlobalDatabaseManagerNewInstance(), PicesInterface::PicesDataBase.InstrumentDataGetByScanLine(), SipperFile.ActiveTrainingLibraries.ModelsAreAvailable(), SipperFile.InstrumentData.Oxygen(), PicesInterface::PicesFeatureVector.ParseImageFileName(), PicesInterface::TrainingModel2.PredictProbabilities(), SipperFile.InstrumentData.Salinity(), PicesInterface::ParsedImageFileName.scanLineNum, and PicesInterface::ParsedImageFileName.sipperFileName.
Referenced by SipperFile.ActiveTrainingLibraries.MakePredictions().
static void SipperFile.ActiveTrainingLibraries.MakePredictions (PicesFeatureVector featureVector, ref PicesPredictionList model1Predictions, ref PicesPredictionList model2Predictions, PicesRunLog runLog) inline static
Definition at line 262 of file ActiveTrainingLibraries.cs.
References SipperFile.ActiveTrainingLibraries.ModelsAreAvailable(), and PicesInterface::TrainingModel2.PredictProbabilities().
static void SipperFile.ActiveTrainingLibraries.MakePredictions (PicesFeatureVector featureVector, ref PicesPrediction model1Prediction1, ref PicesPrediction model1Prediction2, ref PicesPrediction model2Prediction1, ref PicesPrediction model2Prediction2, PicesRunLog runLog) inline static
Definition at line 285 of file ActiveTrainingLibraries.cs.
References PicesInterface::TrainingModel2.PredictClass().
static void SipperFile.ActiveTrainingLibraries.MakePredictions (PicesRaster raster, ref PicesPrediction model1Prediction1, ref PicesPrediction model1Prediction2, ref PicesPrediction model2Prediction1, ref PicesPrediction model2Prediction2, PicesRunLog runLog) inline static
Definition at line 311 of file ActiveTrainingLibraries.cs.
References PicesInterface::PicesFeatureVector.AddInstrumentData(), PicesInterface::PicesDataBase.Close(), PicesInterface::PicesRaster.FileName, PicesInterface::PicesDataBase.GetGlobalDatabaseManagerNewInstance(), PicesInterface::PicesDataBase.InstrumentDataGetByScanLine(), SipperFile.ActiveTrainingLibraries.MakePredictions(), PicesInterface::PicesFeatureVector.ParseImageFileName(), PicesInterface::ParsedImageFileName.scanLineNum, and PicesInterface::ParsedImageFileName.sipperFileName.
static TrainingModel2 SipperFile.ActiveTrainingLibraries.Model1 () inline static
Definition at line 169 of file ActiveTrainingLibraries.cs.
Referenced by PicesCommander.ClassificationStatus.ClassificationStatus().
static PicesClassList SipperFile.ActiveTrainingLibraries.Model1ListOfClasses () inline static
Definition at line 180 of file ActiveTrainingLibraries.cs.
References PicesInterface::TrainingModel2.MLClasses().
static TrainingModel2 SipperFile.ActiveTrainingLibraries.Model2 () inline static
Definition at line 190 of file ActiveTrainingLibraries.cs.
static bool SipperFile.ActiveTrainingLibraries.ModelsAreAvailable () inline static
Indicates wheather tehre is at least one active Training Model fully loaded.
Returns
Definition at line 109 of file ActiveTrainingLibraries.cs.
References SipperFile.ActiveTrainingLibraries.LoadConfiguration(), SipperFile.ActiveTrainingLibraries.SetModel1(), and SipperFile.ActiveTrainingLibraries.SetModel2().
Referenced by SipperFile.ActiveTrainingLibraries.MakePredictions().
static bool SipperFile.ActiveTrainingLibraries.ModelsAreLoading () inline static
Definition at line 157 of file ActiveTrainingLibraries.cs.
Referenced by SipperFile.ActiveTrainingLibraries.CancelLoadWait(), and PicesCommander.ClassificationStatus.ClassificationStatus().
static void SipperFile.ActiveTrainingLibraries.SaveConfiguration () inline static
Definition at line 441 of file ActiveTrainingLibraries.cs.
Referenced by SipperFile.ActiveTrainingLibraries.SetModel1(), and SipperFile.ActiveTrainingLibraries.SetModel2().
static void SipperFile.ActiveTrainingLibraries.SetModel1 (String _model1Name, bool _forceRebuild, DoneLoadingEvent _doneLoadingEvent) inline static
Definition at line 466 of file ActiveTrainingLibraries.cs.
References SipperFile.ActiveTrainingLibraries.SaveConfiguration().
Referenced by SipperFile.ActiveTrainingLibraries.LoadModels(), and SipperFile.ActiveTrainingLibraries.ModelsAreAvailable().
static void SipperFile.ActiveTrainingLibraries.SetModel2 (String _model2Name, bool _forceRebuild, DoneLoadingEvent _doneLoadingEvent) inline static
Definition at line 518 of file ActiveTrainingLibraries.cs.
References SipperFile.ActiveTrainingLibraries.SaveConfiguration().
Referenced by SipperFile.ActiveTrainingLibraries.LoadModels(), and SipperFile.ActiveTrainingLibraries.ModelsAreAvailable().
Property Documentation
String SipperFile.ActiveTrainingLibraries.Model1Name static get
Definition at line 350 of file ActiveTrainingLibraries.cs.
String SipperFile.ActiveTrainingLibraries.Model2Name static get
Definition at line 367 of file ActiveTrainingLibraries.cs.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperFile/ActiveTrainingLibraries.cs