Pices: SipperFile.BlobList Class Reference
SipperFile.BlobList Class Reference
Public Member Functions
BlobList (bool _owner)
void DeleteEntry (int blobId)
void Dispose ()
Blob LocateLargestBlob ()
Blob LookUpByBlobId (int blobId)
Blob MergeIntoSingleBlob (Blob blob1, int blob2Id, int[][] blobIds)
Blob NewBlob (int rowTop, int colLeft)
Detailed Description
Definition at line 7 of file BlobList.cs.
Constructor & Destructor Documentation
SipperFile.BlobList.BlobList (bool _owner) inline
Definition at line 15 of file BlobList.cs.
Member Function Documentation
void SipperFile.BlobList.DeleteEntry (int blobId) inline
Definition at line 128 of file BlobList.cs.
Referenced by SipperFile.BlobList.MergeIntoSingleBlob().
void SipperFile.BlobList.Dispose () inline
Definition at line 35 of file BlobList.cs.
Referenced by SipperFile.BlobDetector.ExtractBlobs().
Blob SipperFile.BlobList.LocateLargestBlob () inline
Definition at line 135 of file BlobList.cs.
References SipperFile.Blob.PixelCount.
Blob SipperFile.BlobList.LookUpByBlobId (int blobId) inline
Definition at line 22 of file BlobList.cs.
Referenced by SipperFile.BlobDetector.ExtractBlobs(), and SipperFile.BlobList.MergeIntoSingleBlob().
Blob SipperFile.BlobList.MergeIntoSingleBlob (Blob blob1, int blob2Id, int blobIds[][]) inline
Definition at line 69 of file BlobList.cs.
References SipperFile.Blob.ColLeft, SipperFile.Blob.ColLeftMaybe, SipperFile.Blob.ColRight, SipperFile.Blob.ColRightMaybe, SipperFile.BlobList.DeleteEntry(), SipperFile.Blob.Dispose(), SipperFile.Blob.Id, SipperFile.BlobList.LookUpByBlobId(), SipperFile.Blob.PixelCount, SipperFile.Blob.RowBot, SipperFile.Blob.RowBotMaybe, SipperFile.Blob.RowTop, and SipperFile.Blob.RowTopMaybe.
Referenced by SipperFile.BlobDetector.ExtractBlobs().
Blob SipperFile.BlobList.NewBlob (int rowTop, int colLeft) inline
Definition at line 54 of file BlobList.cs.
References SipperFile.Blob.ColLeft, SipperFile.Blob.ColRight, SipperFile.Blob.RowBot, and SipperFile.Blob.RowTop.
Referenced by SipperFile.BlobDetector.ExtractBlobs().
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperFile/BlobList.cs