Pices: MLL::DataBaseGpsData Class Reference
MLL::DataBaseGpsData Class Reference
#include <DataBaseGpsData.h>
Public Types
typedef DataBaseGpsData * DataBaseGpsDataPtr
Public Member Functions
DataBaseGpsData ()
DataBaseGpsData (const DataBaseGpsData &_gpsData)
DataBaseGpsData (const KKStr &_cruiseName, const KKU::DateTime &_utcDateTime, double _latitude, double _longitude, float _courseOverGround, float _speedOverGround)
~DataBaseGpsData ()
float CourseOverGround () const
const KKStr & CruiseName () const
double Latitude () const
double Longitude () const
float SpeedOverGround () const
KKStr ToTabStr () const
tab separated list of class contents; order specified by 'DataBaseGpsData::FieldList'.
KKU::DateTime UtcDateTime () const
Static Public Member Functions
static char const *const *const FieldList ()
Detailed Description
Definition at line 10 of file DataBaseGpsData.h.
Member Typedef Documentation
typedef DataBaseGpsData* MLL::DataBaseGpsData::DataBaseGpsDataPtr
Definition at line 13 of file DataBaseGpsData.h.
Constructor & Destructor Documentation
DataBaseGpsData::DataBaseGpsData ()
Definition at line 27 of file DataBaseGpsData.cpp.
DataBaseGpsData::DataBaseGpsData (const DataBaseGpsData & _gpsData)
Definition at line 39 of file DataBaseGpsData.cpp.
MLL::DataBaseGpsData::DataBaseGpsData (const KKStr & _cruiseName, const KKU::DateTime & _utcDateTime, double _latitude, double _longitude, float _courseOverGround, float _speedOverGround)
DataBaseGpsData::~DataBaseGpsData ()
Definition at line 69 of file DataBaseGpsData.cpp.
Member Function Documentation
float MLL::DataBaseGpsData::CourseOverGround () const inline
Definition at line 34 of file DataBaseGpsData.h.
Referenced by MLL::DataBase::GpsDataInsert().
const KKStr& MLL::DataBaseGpsData::CruiseName () const inline
Definition at line 30 of file DataBaseGpsData.h.
Referenced by MLL::DataBase::GpsDataInsert().
char const *const *const DataBaseGpsData::FieldList () static
Definition at line 80 of file DataBaseGpsData.cpp.
double MLL::DataBaseGpsData::Latitude () const inline
Definition at line 32 of file DataBaseGpsData.h.
Referenced by MLL::DataBase::GpsDataInsert().
double MLL::DataBaseGpsData::Longitude () const inline
Definition at line 33 of file DataBaseGpsData.h.
Referenced by MLL::DataBase::GpsDataInsert().
float MLL::DataBaseGpsData::SpeedOverGround () const inline
Definition at line 35 of file DataBaseGpsData.h.
Referenced by MLL::DataBase::GpsDataInsert().
KKStr MLL::DataBaseGpsData::ToTabStr () const
tab separated list of class contents; order specified by 'DataBaseGpsData::FieldList'.
KKU::DateTime MLL::DataBaseGpsData::UtcDateTime () const inline
Definition at line 31 of file DataBaseGpsData.h.
Referenced by MLL::DataBase::GpsDataInsert().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/DataBaseGpsData.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/DataBaseGpsData.cpp