Pices: MLL::MLClassConstList Class Reference
MLL::MLClassConstList Class Reference
#include <MLClassConstList.h>
Classes
class mlClassNameComparison
Public Types
typedef KKU::int32 int32
typedef MLClassConstList * MLClassConstListPtr
typedef KKU::uint32 uint32
Public Member Functions
MLClassConstList ()
MLClassConstList (const MLClassConstList &_mlClasses)
Copy constructor; will copy list but not own the contents.
MLClassConstList (const MLClassList &_mlClasses)
MLClassConstList (const KKStr &fileName, bool &successfull)
Construct a MLClassList object from the contents of a file.
virtual ~MLClassConstList ()
virtual void AddMLClass (MLClassConstPtr _mlClass)
virtual void Clear ()
Clears the contens of this list and updates nameIndex structure.
KKStr ExtractHTMLTableHeader () const
Will generate a HTML formated string that can be used in a HTML table.
MLClassConstListPtr ExtractListOfClassesForAGivenHierarchialLevel (int32 level) const
void ExtractThreeTitleLines (KKStr &titleLine1, KKStr &titleLine2, KKStr &titleLine3) const
Using the class names create three title lines where we split names by "_" characters between the three lines.
void ExtractThreeTitleLines (KKStr &titleLine1, KKStr &titleLine2, KKStr &titleLine3, int32 fieldWidth) const
void ExtractTwoTitleLines (KKStr &titleLine1, KKStr &titleLine2) const
Using the class names create two title lines where we split names by "_" characters between the two lines.
virtual MLClassConstPtr GetMLClassPtr (const KKStr &_name)
return pointer to instance with '_name'; if none exists, create one and add to list.
MLClassConstPtr GetNoiseClass () const
MLClassConstPtr GetUnKnownClass ()
Return a pointer to the MLClass object that represents the unknown Class in the list.
void Load (const KKStr &_fileName, bool &_successfull)
virtual MLClassConstPtr LookUpByClassId (int32 _classId) const
virtual MLClassConstPtr LookUpByName (const KKStr &_name) const
Returns a pointer of MLClass object with name (_name); if none in list will then return NULL.
int32 MemoryConsumedEstimated () const
KKU::uint16 NumHierarchialLevels () const
bool operator!= (const MLClassConstList &right) const
MLClassConstList & operator+= (const MLClassConstList &right)
add all classes that are in the 'right' parameter
MLClassConstList operator- (const MLClassConstList &right) const
remove all classes that in the 'right' parameter
MLClassConstList & operator-= (const MLClassConstList &right)
remove all classes that in the 'right' parameter
MLClassConstList & operator= (const MLClassConstList &right)
bool operator== (const MLClassConstList &right) const
virtual MLClassConstPtr PopFromBack ()
virtual MLClassConstPtr PopFromFront ()
virtual void PushOnBack (MLClassConstPtr mlClass)
virtual void PushOnFront (MLClassConstPtr mlClass)
void Save (KKStr _fileName, bool &_successfull)
void SortByName ()
KKStr ToCommaDelimitedStr () const
KKStr ToString () const
KKStr ToTabDelimitedStr () const
void WriteXML (std::ostream &o) const
Static Public Member Functions
static MLClassConstListPtr BuildListFromDelimtedStr (const KKStr &s, char delimiter)
static MLClassConstListPtr MergeClassList (const MLClassConstList &list1, const MLClassConstList &list2)
Detailed Description
Definition at line 97 of file MLClassConstList.h.
Member Typedef Documentation
typedef KKU::int32 MLL::MLClassConstList::int32
Definition at line 100 of file MLClassConstList.h.
typedef MLClassConstList* MLL::MLClassConstList::MLClassConstListPtr
Definition at line 103 of file MLClassConstList.h.
typedef KKU::uint32 MLL::MLClassConstList::uint32
Definition at line 101 of file MLClassConstList.h.
Constructor & Destructor Documentation
MLClassConstList::MLClassConstList ()
Definition at line 31 of file MLClassConstList.cpp.
Referenced by BuildListFromDelimtedStr(), ExtractListOfClassesForAGivenHierarchialLevel(), MemoryConsumedEstimated(), and MergeClassList().
MLClassConstList::MLClassConstList (const MLClassConstList & _mlClasses)
Copy constructor; will copy list but not own the contents.
Definition at line 40 of file MLClassConstList.cpp.
References PushOnBack().
MLClassConstList::MLClassConstList (const MLClassList & _mlClasses)
Definition at line 52 of file MLClassConstList.cpp.
References PushOnBack().
MLL::MLClassConstList::MLClassConstList (const KKStr & fileName, bool & successfull)
Construct a MLClassList object from the contents of a file.
MLClassConstList::~MLClassConstList () virtual
Definition at line 82 of file MLClassConstList.cpp.
Member Function Documentation
void MLClassConstList::AddMLClass (MLClassConstPtr _mlClass) virtual
Definition at line 190 of file MLClassConstList.cpp.
References KKU::endl().
Referenced by MLL::FileDesc::AddClasses(), ExtractListOfClassesForAGivenHierarchialLevel(), MLL::TrainingConfiguration2::ExtractListOfClassesForAGivenHierarchialLevel(), GetMLClassPtr(), Load(), and MergeClassList().
MLClassConstListPtr MLClassConstList::BuildListFromDelimtedStr (const KKStr & s, char delimiter) static
Definition at line 653 of file MLClassConstList.cpp.
References GetMLClassPtr(), MLClassConstList(), and KKU::KKStr::Split().
Referenced by MLL::Model::ReadXML().
void MLClassConstList::Clear () virtual
Clears the contens of this list and updates nameIndex structure.
Definition at line 97 of file MLClassConstList.cpp.
Referenced by operator=().
KKStr MLClassConstList::ExtractHTMLTableHeader () const
Will generate a HTML formated string that can be used in a HTML table.
Using the class names create one header line for a HTML table. The underscore character ("_") will be used to separate levels
Definition at line 580 of file MLClassConstList.cpp.
References x.
Referenced by MLL::ConfusionMatrix2::PrintConfusionMatrixAvgPredProbHTML().
MLClassConstListPtr MLClassConstList::ExtractListOfClassesForAGivenHierarchialLevel (int32 level) const
Definition at line 608 of file MLClassConstList.cpp.
References AddMLClass(), MLClassConstList(), and SortByName().
void MLL::MLClassConstList::ExtractThreeTitleLines (KKStr & titleLine1, KKStr & titleLine2, KKStr & titleLine3) const
Using the class names create three title lines where we split names by "_" characters between the three lines.
Referenced by MLL::CrossValidationThreeWay::CreateDistanceReport(), MLL::CrossValidationThreeWay::CreateProbabilityReport(), MLL::ConfusionMatrix2::PrintConfusionMatrix(), MLL::AbundanceCorrectionMatrix::PrintConfusionMatrixTabDelimited(), and MLL::ConfusionMatrix2::PrintConfusionMatrixTabDelimited().
void MLL::MLClassConstList::ExtractThreeTitleLines (KKStr & titleLine1, KKStr & titleLine2, KKStr & titleLine3, int32 fieldWidth) const
void MLClassConstList::ExtractTwoTitleLines (KKStr & titleLine1, KKStr & titleLine2) const
Using the class names create two title lines where we split names by "_" characters between the two lines.
Definition at line 420 of file MLClassConstList.cpp.
References KKU::KKStr::LocateCharacter(), KKU::KKStr::SubStrPart(), and x.
Referenced by MLL::ConfusionMatrix2::PrintTrueFalsePositivesTabDelimited().
MLClassConstPtr MLClassConstList::GetMLClassPtr (const KKStr & _name) virtual
return pointer to instance with '_name'; if none exists, create one and add to list.
Definition at line 296 of file MLClassConstList.cpp.
References AddMLClass(), MLL::MLClass::CreateNewMLClass(), and LookUpByName().
Referenced by BuildListFromDelimtedStr(), MLL::FeatureFileIODstWeb::GetFileDesc(), MLL::FeatureFileIOC45::GetFileDesc(), MLL::FeatureFileIOColumn::GetFileDesc(), MLL::FeatureFileIOUCI::GetFileDesc(), MLL::FeatureFileIOSparse::GetFileDesc(), MLL::FileDesc::GetMLClassPtr(), MLL::FeatureFileIODstWeb::LoadFile(), MLL::FeatureFileIOColumn::LoadFile(), MLL::FeatureFileIOUCI::LoadFile(), MLL::FeatureFileIOPices::LoadFile(), MLL::FeatureFileIOSparse::LoadFile(), and MLL::FeatureFileIOPices::LoadInSubDirectoryTree().
MLClassConstPtr MLClassConstList::GetNoiseClass () const
Definition at line 309 of file MLClassConstList.cpp.
Referenced by MLL::Classifier2::Classifier2(), and CrossValidationApp::ValidationProcess().
MLClassConstPtr MLClassConstList::GetUnKnownClass ()
Return a pointer to the MLClass object that represents the unknown Class in the list.
That is the one with the name 'UNKNOWN'. If none is found then one will be created and added to the list.
Definition at line 327 of file MLClassConstList.cpp.
References MLL::MLClass::CreateNewMLClass(), LookUpByName(), and PushOnBack().
Referenced by MLL::Classifier2::Classifier2(), MLL::FeatureFileIOPices::LoadInSubDirectoryTree(), and MLL::FileDesc::LookUpUnKnownMLClass().
void MLClassConstList::Load (const KKStr & _fileName, bool & _successfull)
Definition at line 119 of file MLClassConstList.cpp.
References AddMLClass(), KKU::endl(), KKU::osFOPEN(), KKU::KKStr::Str(), and KKU::KKStr::TrimRight().
MLClassConstPtr MLClassConstList::LookUpByClassId (int32 _classId) const virtual
Definition at line 278 of file MLClassConstList.cpp.
MLClassConstPtr MLClassConstList::LookUpByName (const KKStr & _name) const virtual
Returns a pointer of MLClass object with name (_name); if none in list will then return NULL.
Returns a pointer of MLClassConst object with name (_name); if none in list will then return NULL.
Parameters
[in] _name Name of MLClass to search for.
Returns
Pointer to MLClass or NULL if not Found.
Parameters
[in] _name Name of MLClassConst to search for.
Returns
Pointer to MLClassConst or NULL if not Found.
Definition at line 264 of file MLClassConstList.cpp.
References KKU::KKStr::ToUpper().
Referenced by GetMLClassPtr(), GetUnKnownClass(), MLL::FileDesc::LookUpMLClassByName(), MLL::DataBase::MLClassLoadList(), and operator==().
int32 MLClassConstList::MemoryConsumedEstimated () const
Definition at line 90 of file MLClassConstList.cpp.
References MLClassConstList().
Referenced by MLL::Classifier2::MemoryConsumedEstimated(), MLL::Model::MemoryConsumedEstimated(), MLL::FileDesc::MemoryConsumedEstimated(), and MLL::TrainingProcess2::MemoryConsumedEstimated().
MLClassConstListPtr MLClassConstList::MergeClassList (const MLClassConstList & list1, const MLClassConstList & list2) static
Definition at line 630 of file MLClassConstList.cpp.
References AddMLClass(), and MLClassConstList().
uint16 MLClassConstList::NumHierarchialLevels () const
Definition at line 106 of file MLClassConstList.cpp.
References SVM289_MFS::Max().
bool MLClassConstList::operator!= (const MLClassConstList & right) const
Definition at line 705 of file MLClassConstList.cpp.
MLClassConstList & MLClassConstList::operator+= (const MLClassConstList & right)
add all classes that are in the 'right' parameter
Definition at line 735 of file MLClassConstList.cpp.
References PushOnBack().
MLClassConstList MLClassConstList::operator- (const MLClassConstList & right) const
remove all classes that in the 'right' parameter
Definition at line 773 of file MLClassConstList.cpp.
References PushOnBack().
MLClassConstList & MLClassConstList::operator-= (const MLClassConstList & right)
remove all classes that in the 'right' parameter
Definition at line 713 of file MLClassConstList.cpp.
References PopFromBack().
MLClassConstList & MLClassConstList::operator= (const MLClassConstList & right)
Definition at line 754 of file MLClassConstList.cpp.
References Clear(), and PushOnBack().
bool MLClassConstList::operator== (const MLClassConstList & right) const
Definition at line 686 of file MLClassConstList.cpp.
References LookUpByName().
MLClassConstPtr MLClassConstList::PopFromBack () virtual
Definition at line 202 of file MLClassConstList.cpp.
Referenced by operator-=().
MLClassConstPtr MLClassConstList::PopFromFront () virtual
Definition at line 217 of file MLClassConstList.cpp.
void MLClassConstList::PushOnBack (MLClassConstPtr mlClass) virtual
Definition at line 232 of file MLClassConstList.cpp.
References KKU::endl().
Referenced by MLL::MLClass::BuildListOfDecendents(), MLL::CrossValidationThreeWay::CrossValidationThreeWay(), MLL::TrainingConfiguration2::ExtractClassList(), MLL::FeatureVectorList::ExtractMLClassConstList(), GetUnKnownClass(), MLClassConstList(), MLL::DataBase::MLClassLoadList(), operator+=(), operator-(), operator=(), MLL::AbundanceCorrectionMatrix::PrintConfusionMatrixTabDelimited(), and MLL::TrainingProcess2::Read().
void MLClassConstList::PushOnFront (MLClassConstPtr mlClass) virtual
Definition at line 245 of file MLClassConstList.cpp.
References KKU::endl().
void MLClassConstList::Save (KKStr _fileName, bool & _successfull)
Definition at line 158 of file MLClassConstList.cpp.
References KKU::endl(), and KKU::KKStr::Str().
void MLClassConstList::SortByName ()
Definition at line 361 of file MLClassConstList.cpp.
Referenced by PicesInterface::TrainingModel2::BuildTrainingModel(), CreateBfsFromMfs(), MLL::TrainingConfiguration2::CreateFromFeatureVectorList(), MLL::TrainingConfiguration2::ExtractClassList(), ExtractListOfClassesForAGivenHierarchialLevel(), MLL::UsfCasCor::load_namesfile(), CrossValidationApp::ProcessCmdLineParameters(), MLL::FeatureFileIORoberts::SaveFile(), MLL::ModelOldSVM::TrainModel(), MLL::Model::TrainModel(), and MLL::UsfCasCor::TrainNewClassifier().
KKStr MLClassConstList::ToCommaDelimitedStr () const
Definition at line 405 of file MLClassConstList.cpp.
Referenced by MLL::ClassificationBiasMatrix::WriteXML(), MLL::ConfusionMatrix2::WriteXML(), and MLL::Model::WriteXML().
KKStr MLClassConstList::ToString () const
Definition at line 372 of file MLClassConstList.cpp.
Referenced by MLL::operator<<().
KKStr MLClassConstList::ToTabDelimitedStr () const
Definition at line 390 of file MLClassConstList.cpp.
Referenced by MLL::TrainingProcess2::WriteXml().
void MLClassConstList::WriteXML (std::ostream & o) const
Definition at line 670 of file MLClassConstList.cpp.
References KKU::endl().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/MLClassConstList.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/MLClassConstList.cpp