Pices: ImageExtractionManager::FrameProcessorThread Class Reference
ImageExtractionManager::FrameProcessorThread Class Reference
#include <FrameProcessorThread.h>
Public Member Functions
FrameProcessorThread (ExtractionParms &_parms, ExtractionManagerPtr _extractionManager, const KKStr &_threadName, MsgQueuePtr _msgQueue, LogicalFrameQueuePtr _framePool, ExtractedImageQueuePtr _imagesAwaitingUpdate, bool &_successful)
virtual ~FrameProcessorThread ()
void GetRunTimeStats (uint32 &_framesProcessed, uint32 &_scanLinesProcessed, uint32 &_imagesFound, uint32 &_imagesClassified)
virtual void Run ()
virtual ThreadTypes ThreadType ()
Public Member Functions inherited from ImageExtractionManager::ImageExtractionThread
ImageExtractionThread (ExtractionParms &_parms, ExtractionManagerPtr _extractionManager, const KKStr &_threadName, MsgQueuePtr _msgQueue)
virtual ~ImageExtractionThread ()
volatile const bool & CancelFlag () const
void CancelThread ()
Call this method to have its thread stop right away and exit.
bool Crashed () const
void Crashed (bool _crashed)
void Start ()
Call this method to start thread; it will call the method "Run".
ThreadStatus Status () const
void Status (ThreadStatus _status)
void Stop ()
stop() stops the running thread and frees the thread handle
volatile const bool & TerminateFlag () const
void TerminateThread ()
Call this method to have its thread finish what ever is in the queue and then exit.
const KKStr & ThreadName () const
Additional Inherited Members
Protected Member Functions inherited from ImageExtractionManager::ImageExtractionThread
void AddMsg (KKStrPtr msg)
Taking ownership of 'msg' and will append to 'msgQueue'.
void AddMsg (const KKStr &msg)
A copy of the message 'msg' will be added to the end of msgQueue.
bool CancelOrTerminateRequested ()
Protected Attributes inherited from ImageExtractionManager::ImageExtractionThread
ExtractionManagerPtr extractionManager
Pointer to instance that manges all the threads.
ExtractionParms & parms
Detailed Description
Definition at line 31 of file FrameProcessorThread.h.
Constructor & Destructor Documentation
FrameProcessorThread::FrameProcessorThread (ExtractionParms & _parms, ExtractionManagerPtr _extractionManager, const KKStr & _threadName, MsgQueuePtr _msgQueue, LogicalFrameQueuePtr _framePool, ExtractedImageQueuePtr _imagesAwaitingUpdate, bool & _successful)
Definition at line 55 of file FrameProcessorThread.cpp.
References ImageExtractionManager::ImageExtractionThread::AddMsg(), KKU::osGetRootName(), ImageExtractionManager::ImageExtractionThread::parms, and ImageExtractionManager::ExtractionParms::SipperFileName().
FrameProcessorThread::~FrameProcessorThread () virtual
Definition at line 101 of file FrameProcessorThread.cpp.
References ImageExtractionManager::ImageExtractionThread::AddMsg().
Member Function Documentation
void FrameProcessorThread::GetRunTimeStats (uint32 & _framesProcessed, uint32 & _scanLinesProcessed, uint32 & _imagesFound, uint32 & _imagesClassified)
Definition at line 114 of file FrameProcessorThread.cpp.
Referenced by ImageExtractionManager::ExtractionManager::GetRunTimeStats().
void FrameProcessorThread::Run () virtual
Implements ImageExtractionManager::ImageExtractionThread.
Definition at line 331 of file FrameProcessorThread.cpp.
References ImageExtractionManager::ImageExtractionThread::AddMsg(), ImageExtractionManager::ImageExtractionThread::CancelFlag(), ImageExtractionManager::LogicalFrameQueue::FrameProcessed(), ImageExtractionManager::ImageExtractionThread::Status(), ImageExtractionManager::ImageExtractionThread::TerminateFlag(), ImageExtractionManager::ImageExtractionThread::ThreadName(), ImageExtractionManager::tsRunning, ImageExtractionManager::tsStarting, ImageExtractionManager::tsStopped, and ImageExtractionManager::tsStopping.
virtual ThreadTypes ImageExtractionManager::FrameProcessorThread::ThreadType () inline virtual
Implements ImageExtractionManager::ImageExtractionThread.
Definition at line 45 of file FrameProcessorThread.h.
References ImageExtractionManager::ttFrameProcessor.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperLibraries/ImageExtractionManager/FrameProcessorThread.h
D:/Users/kkramer/IEC/SipperSoftware/SipperLibraries/ImageExtractionManager/FrameProcessorThread.cpp