Pices: SipperDiskUtilities.SipperFileControlBlock Class Reference
SipperDiskUtilities.SipperFileControlBlock Class Reference
Public Member Functions
SipperFileControlBlock (byte[] buffer, ref int nextIndex)
SipperFileControlBlock ()
bool Equals (SipperFileControlBlock other)
void FillBuffer (byte[] buffer, ref int nextIndex)
void SetSipperDateTimeStamp (SipperDateTimeStamp _dateTimeStamp)
string UserMessage ()
void Write (FileStream fs)
Static Public Member Functions
static int BuffSpaceNeeded ()
static SipperFileControlBlock CreateFromFileStream (FileStream fs)
Public Attributes
const uint SIPPER_FILE_ALLOCATED = 0xFFFFFFFF
const uint SIPPER_FILE_CLOSED = 0
const uint SIPPER_FILE_FREE = 0
const uint SIPPER_FILE_OPEN = 1
Properties
UInt32 Allocated [get, set]
string Desccription [get]
bool DownLoaded [get, set]
uint EndSector [get, set]
int FcbIndex [get, set]
string FileName [get, set]
long FileSizeInBytes [get]
long FileSizeInSectores [get]
uint StartSector [get, set]
UInt32 Status [get, set]
DateTime TimeStamp [get]
Detailed Description
Definition at line 8 of file SipperFileControlBlock.cs.
Constructor & Destructor Documentation
SipperDiskUtilities.SipperFileControlBlock.SipperFileControlBlock (byte[] buffer, ref int nextIndex) inline
Definition at line 84 of file SipperFileControlBlock.cs.
References SipperDiskUtilities.Constants.LOGICAL_BLOCK_SIZE, and x.
SipperDiskUtilities.SipperFileControlBlock.SipperFileControlBlock () inline
Definition at line 138 of file SipperFileControlBlock.cs.
References SipperDiskUtilities.SipperFileControlBlock.SIPPER_FILE_CLOSED, SipperDiskUtilities.SipperFileControlBlock.SIPPER_FILE_FREE, and x.
Referenced by SipperDiskUtilities.SipperFileControlBlock.CreateFromFileStream().
Member Function Documentation
static int SipperDiskUtilities.SipperFileControlBlock.BuffSpaceNeeded () inline static
Definition at line 184 of file SipperFileControlBlock.cs.
References SipperDiskUtilities.Constants.LOGICAL_BLOCK_SIZE.
Referenced by SipperDiskUtilities.SipperFileControlBlock.CreateFromFileStream(), and SipperDiskUtilities.SipperFileControlBlock.Write().
static SipperFileControlBlock SipperDiskUtilities.SipperFileControlBlock.CreateFromFileStream (FileStream fs) inline static
Definition at line 123 of file SipperFileControlBlock.cs.
References SipperDiskUtilities.SipperFileControlBlock.BuffSpaceNeeded(), and SipperDiskUtilities.SipperFileControlBlock.SipperFileControlBlock().
Referenced by SipperDiskUtilities.SipperDisk.AreWeTheSameDrive().
bool SipperDiskUtilities.SipperFileControlBlock.Equals (SipperFileControlBlock other) inline
Definition at line 168 of file SipperFileControlBlock.cs.
Referenced by SipperDiskUtilities.SipperDisk.AreWeTheSameDrive().
void SipperDiskUtilities.SipperFileControlBlock.FillBuffer (byte[] buffer, ref int nextIndex) inline
Definition at line 191 of file SipperFileControlBlock.cs.
References SipperDiskUtilities.Constants.FillBuffer(), SipperDiskUtilities.SipperDateTimeStamp.FillBuffer(), SipperDiskUtilities.Constants.LOGICAL_BLOCK_SIZE, and x.
Referenced by SipperDiskUtilities.SipperFileControlBlock.Write().
void SipperDiskUtilities.SipperFileControlBlock.SetSipperDateTimeStamp (SipperDateTimeStamp _dateTimeStamp) inline
Definition at line 50 of file SipperFileControlBlock.cs.
string SipperDiskUtilities.SipperFileControlBlock.UserMessage () inline
Definition at line 242 of file SipperFileControlBlock.cs.
References SipperDiskUtilities.SipperDateTimeStamp.DotNetDateTime, and x.
void SipperDiskUtilities.SipperFileControlBlock.Write (FileStream fs) inline
Definition at line 275 of file SipperFileControlBlock.cs.
References SipperDiskUtilities.SipperFileControlBlock.BuffSpaceNeeded(), and SipperDiskUtilities.SipperFileControlBlock.FillBuffer().
Referenced by SipperDiskUtilities.SipperDisk.ResetSipperDirectory().
Member Data Documentation
const uint SipperDiskUtilities.SipperFileControlBlock.SIPPER_FILE_ALLOCATED = 0xFFFFFFFF
Definition at line 18 of file SipperFileControlBlock.cs.
const uint SipperDiskUtilities.SipperFileControlBlock.SIPPER_FILE_CLOSED = 0
Definition at line 19 of file SipperFileControlBlock.cs.
Referenced by SipperDiskUtilities.SipperDisk.ResetSipperDirectory(), and SipperDiskUtilities.SipperFileControlBlock.SipperFileControlBlock().
const uint SipperDiskUtilities.SipperFileControlBlock.SIPPER_FILE_FREE = 0
Definition at line 17 of file SipperFileControlBlock.cs.
Referenced by SipperDiskUtilities.SipperDisk.ResetSipperDirectory(), and SipperDiskUtilities.SipperFileControlBlock.SipperFileControlBlock().
const uint SipperDiskUtilities.SipperFileControlBlock.SIPPER_FILE_OPEN = 1
Definition at line 20 of file SipperFileControlBlock.cs.
Property Documentation
UInt32 SipperDiskUtilities.SipperFileControlBlock.Allocated get set
Definition at line 38 of file SipperFileControlBlock.cs.
Referenced by SipperDiskUtilities.SipperDisk.ResetSipperDirectory().
string SipperDiskUtilities.SipperFileControlBlock.Desccription get
Definition at line 41 of file SipperFileControlBlock.cs.
bool SipperDiskUtilities.SipperFileControlBlock.DownLoaded get set
Definition at line 42 of file SipperFileControlBlock.cs.
uint SipperDiskUtilities.SipperFileControlBlock.EndSector get set
Definition at line 43 of file SipperFileControlBlock.cs.
int SipperDiskUtilities.SipperFileControlBlock.FcbIndex get set
Definition at line 44 of file SipperFileControlBlock.cs.
Referenced by SipperDiskUtilities.SipperFileControlBlockList.LookUpByFcbIndex(), and SipperDiskUtilities.SipperDisk.ResetSipperDirectory().
string SipperDiskUtilities.SipperFileControlBlock.FileName get set
Definition at line 70 of file SipperFileControlBlock.cs.
Referenced by SipperDiskUtilities.SipperFileControlBlockList.LookUpByName(), and SipperDiskUtilities.SipperDiskFile.Read().
long SipperDiskUtilities.SipperFileControlBlock.FileSizeInBytes get
Definition at line 45 of file SipperFileControlBlock.cs.
Referenced by SipperDiskUtilities.SipperDiskFile.SipperDiskFile().
long SipperDiskUtilities.SipperFileControlBlock.FileSizeInSectores get
Definition at line 46 of file SipperFileControlBlock.cs.
Referenced by SipperDiskUtilities.SipperDiskFile.SipperDiskFile().
uint SipperDiskUtilities.SipperFileControlBlock.StartSector get set
Definition at line 47 of file SipperFileControlBlock.cs.
UInt32 SipperDiskUtilities.SipperFileControlBlock.Status get set
Definition at line 39 of file SipperFileControlBlock.cs.
Referenced by SipperDiskUtilities.SipperDisk.ResetSipperDirectory().
DateTime SipperDiskUtilities.SipperFileControlBlock.TimeStamp get
Definition at line 57 of file SipperFileControlBlock.cs.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperDiskUtilities/SipperFileControlBlock.cs