Pices: SipperFile.InstrumentDataManager Class Reference
SipperFile.InstrumentDataManager Class Reference
Summary description for InstrumentDataManager.
Public Member Functions
InstrumentDataManager (InstrumentDataLogger _dataLogger, PicesSipperFile _sipperFile, SipperConfigRec _configRec, InstrumentData _currentDataRow)
Initializes a new instance of the InstrumentDataManager class.
void AssignReporter (byte deviceID, InstrumentDataReport reporter)
Assigns the reporter.
SipperConfigRec ConmfigRec ()
InstrumentData CurrentDataRow ()
void Dispose ()
double Latitude ()
void LogTxtLine (byte deviceId, string txtLine)
void ReportData (byte deviceId, string txt)
void ReportData (byte deviceId, char ch)
void ReportData (Sipper3DecodeRec dataRec, int scanLine)
void ReportSerialPortData (byte portNum, string txt)
PicesSipperFile SipperFile ()
Detailed Description
Summary description for InstrumentDataManager.
Instrument data from sipper files will be directed to an instance of this class. then based off the DeviceId the data will be sent to the appropriate Instrtument derived class.
Definition at line 14 of file InstrumentDataManager.cs.
Constructor & Destructor Documentation
SipperFile.InstrumentDataManager.InstrumentDataManager (InstrumentDataLogger _dataLogger, PicesSipperFile _sipperFile, SipperConfigRec _configRec, InstrumentData _currentDataRow) inline
Initializes a new instance of the InstrumentDataManager class.
Parameters
_dataLogger The _data logger.
_sipperFile The _sipper file.
_configRec The _config rec.
_currentDataRow The _current data row.
Definition at line 48 of file InstrumentDataManager.cs.
References SipperFile.Instrument.CreateInstrumentDataReport(), SipperFile.SipperConfigRec.HeaderRec(), SipperFile.PortAssignment.Instrument(), SipperFile.SipperHeaderRec.PortAssignments(), PicesInterface::PicesSipperFile.Sp0, PicesInterface::PicesSipperFile.Sp1, PicesInterface::PicesSipperFile.Sp2, and PicesInterface::PicesSipperFile.Sp3.
Member Function Documentation
void SipperFile.InstrumentDataManager.AssignReporter (byte deviceID, InstrumentDataReport reporter) inline
Assigns the reporter.
Parameters
deviceID The device ID ccomming from the SIPPER file. See Sipper3 File Format. see Sipper3File.cs
reporter The reporter.
Definition at line 181 of file InstrumentDataManager.cs.
SipperConfigRec SipperFile.InstrumentDataManager.ConmfigRec () inline
Definition at line 35 of file InstrumentDataManager.cs.
Referenced by SipperFile.InstrumentDataReportCTD.InstrumentDataReportCTD().
InstrumentData SipperFile.InstrumentDataManager.CurrentDataRow () inline
Definition at line 37 of file InstrumentDataManager.cs.
Referenced by SipperFile.InstrumentDataReportBatteryMeter.ParseTxtLine(), SipperFile.InstrumentDataReportInclination.ParseTxtLine(), SipperFile.InstrumentDataReportCTD.ParseTxtLine(), SipperFile.InstrumentDataReportIllumination.ReportData(), and SipperFile.InstrumentDataReportFlowMeter.ReportData().
void SipperFile.InstrumentDataManager.Dispose () inline
Definition at line 113 of file InstrumentDataManager.cs.
References SipperFile.InstrumentDataReport.Dispose(), SipperFile.InstrumentDataLogger.Dispose(), and x.
double SipperFile.InstrumentDataManager.Latitude () inline
Definition at line 33 of file InstrumentDataManager.cs.
void SipperFile.InstrumentDataManager.LogTxtLine (byte deviceId, string txtLine) inline
Definition at line 256 of file InstrumentDataManager.cs.
References SipperFile.InstrumentDataLogger.LogInstrumentData().
Referenced by SipperFile.InstrumentDataReport.ReportData().
void SipperFile.InstrumentDataManager.ReportData (byte deviceId, string txt) inline
Definition at line 206 of file InstrumentDataManager.cs.
References SipperFile.InstrumentDataReport.ReportData().
Referenced by SipperFile.Sipper3File.ReadNextScanLine(), SipperFile.InstrumentDataManager.ReportSerialPortData(), and SipperFile.Sipper3File.SkipNextScanLine().
void SipperFile.InstrumentDataManager.ReportData (byte deviceId, char ch) inline
Definition at line 223 of file InstrumentDataManager.cs.
References SipperFile.InstrumentDataReport.ReportData().
void SipperFile.InstrumentDataManager.ReportData (Sipper3DecodeRec dataRec, int scanLine) inline
Definition at line 240 of file InstrumentDataManager.cs.
References SipperFile.InstrumentDataReport.ReportData(), SipperFile.Sipper3DecodeRec.SensorData(), SipperFile.Sipper3DecodeRec.SensorNum(), and SipperFile.Sipper3DecodeRec.Text().
void SipperFile.InstrumentDataManager.ReportSerialPortData (byte portNum, string txt) inline
Definition at line 196 of file InstrumentDataManager.cs.
References SipperFile.InstrumentDataManager.ReportData().
PicesSipperFile SipperFile.InstrumentDataManager.SipperFile () inline
Definition at line 34 of file InstrumentDataManager.cs.
Referenced by SipperFile.InstrumentDataReportCTD.InstrumentDataReportCTD().
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperFile/InstrumentDataManager.cs