Pices: MLL::DataBaseServerList Class Reference
MLL::DataBaseServerList Class Reference
#include <DataBaseServer.h>
Public Types
typedef DataBaseServerList * DataBaseServerListPtr
Public Member Functions
DataBaseServerList (RunLog &_log, bool _loadFromConfigFile=true)
DataBaseServerList (const DataBaseServerList &serverList)
~DataBaseServerList ()
const KKStr & DefaultServerDescription () const
void DefaultServerDescription (const KKStr &_defaultServerDescription)
DataBaseServerPtr GetDefaultServer ()
RunLog & Log ()
DataBaseServerPtr LookUpByDescription (const KKStr &_description)
void WriteConfigFile () const
Detailed Description
Definition at line 69 of file DataBaseServer.h.
Member Typedef Documentation
typedef DataBaseServerList* MLL::DataBaseServerList::DataBaseServerListPtr
Definition at line 72 of file DataBaseServer.h.
Constructor & Destructor Documentation
DataBaseServerList::DataBaseServerList (RunLog & _log, bool _loadFromConfigFile = true)
Definition at line 139 of file DataBaseServer.cpp.
DataBaseServerList::DataBaseServerList (const DataBaseServerList & serverList)
Definition at line 152 of file DataBaseServer.cpp.
DataBaseServerList::~DataBaseServerList ()
Definition at line 166 of file DataBaseServer.cpp.
Member Function Documentation
const KKStr& MLL::DataBaseServerList::DefaultServerDescription () const inline
Definition at line 83 of file DataBaseServer.h.
Referenced by PicesInterface::PicesDataBaseServerList::PicesDataBaseServerList().
void MLL::DataBaseServerList::DefaultServerDescription (const KKStr & _defaultServerDescription) inline
Definition at line 84 of file DataBaseServer.h.
DataBaseServerPtr DataBaseServerList::GetDefaultServer ()
Definition at line 306 of file DataBaseServer.cpp.
References LookUpByDescription().
Referenced by MLL::DataBase::GetDefaultServer().
RunLog& MLL::DataBaseServerList::Log () inline
Definition at line 94 of file DataBaseServer.h.
DataBaseServerPtr DataBaseServerList::LookUpByDescription (const KKStr & _description)
Definition at line 284 of file DataBaseServer.cpp.
References MLL::DataBaseServer::Description(), and KKU::KKStr::EqualIgnoreCase().
Referenced by GetDefaultServer(), and MLL::DataBase::GetServer().
void DataBaseServerList::WriteConfigFile () const
Definition at line 175 of file DataBaseServer.cpp.
References KKU::endl(), KKU::RunLog::Level(), KKU::osAddSlash(), KKU::osCreateDirectoryPath(), KKU::osGetLocalDateTime(), and KKU::KKStr::Str().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/DataBaseServer.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/DataBaseServer.cpp