Pices: KKU::RasterBuffer Class Reference
KKU::RasterBuffer Class Reference
Will manage a buffer that will allow multiple threads to add and remove instances of 'Raster' objects.
#include <RasterBuffer.h>
Public Types
typedef RasterBuffer * RasterBufferPtr
Public Member Functions
RasterBuffer (const KKStr &_name, int32 _maxNumOfBuffers)
Constructor.
~RasterBuffer ()
void AddRaster (RasterPtr raster)
Adds 'raster' to the end of the queue giving the queue ownership of the instance.
RasterPtr GetCopyOfLastImage ()
Returns a copy of the last Raster instance added to the queue; if buffer is empty will return NULL.
RasterPtr GetNextRaster ()
Removes from the buffer the oldest instance of 'Raster' and returns it to caller; if buffer is empty will return NULL.
int32 MaxNumOfBuffers () const
void MaxNumOfBuffers (int32 _maxNumOfBuffers)
int32 MemoryConsumedEstimated ()
Returns an estimate of the amount of memory consumed in bytes.
int32 NumAvailable () const
The number of entries that are left in the buffer before 'maxNumOfBuffers' is reached.
int32 NumPopulated () const
int32 RastersDropped () const
Returns the number of 'Raster' instances that had to be deleted because the size of the queue had reached 'maxNumOfBuffers'.
Detailed Description
Will manage a buffer that will allow multiple threads to add and remove instances of 'Raster' objects.
A 'GoalKeepeer' object 'gateKeeper' will be used to enforce integrity in the Multi-Threaded environment. It will guarantee that only one thread at a time can access the Raster Queue. This queue will take ownership of 'Raster' instances added to it via 'AddRaster'. It will pass ownership of the 'Raster' instances when it returns them in GetNextRaster. When a 'RasterBuffer' instance is deleted it will delete all the 'Raster' instances it still contains.
Definition at line 30 of file RasterBuffer.h.
Member Typedef Documentation
typedef RasterBuffer* KKU::RasterBuffer::RasterBufferPtr
Definition at line 33 of file RasterBuffer.h.
Constructor & Destructor Documentation
RasterBuffer::RasterBuffer (const KKStr & _name, int32 _maxNumOfBuffers)
Constructor.
Parameters
[in] _name Name of the buffer; this will be used by the associated 'GateKeeper' instance; should be unique.
[in] _maxNumOfBuffers The maximum number of raster instances that can be added to this buffer. When this limit has been reached the oldest entries in the list will be deleted when a new one is added (AddRaster).
Definition at line 36 of file RasterBuffer.cpp.
References KKU::GoalKeeper::MemoryConsumedEstimated().
RasterBuffer::~RasterBuffer ()
Definition at line 53 of file RasterBuffer.cpp.
Member Function Documentation
void RasterBuffer::AddRaster (RasterPtr raster)
Adds 'raster' to the end of the queue giving the queue ownership of the instance.
If the number of entries in the queue are already equal or greater than 'MaxNumOfBuffers' specified then the oldest instances in the queue(back of the queue) will be removed and deleted until the size of the queue is less than 'MaxNumOfBuffers' before adding this new instance.
Definition at line 101 of file RasterBuffer.cpp.
References KKU::GoalKeeper::EndBlock(), KKU::endl(), KKU::Raster::MemoryConsumedEstimated(), and KKU::GoalKeeper::StartBlock().
RasterPtr RasterBuffer::GetCopyOfLastImage ()
Returns a copy of the last Raster instance added to the queue; if buffer is empty will return NULL.
Caller will get ownership and be responsible for deleting it.
Definition at line 154 of file RasterBuffer.cpp.
References KKU::GoalKeeper::EndBlock(), and KKU::GoalKeeper::StartBlock().
RasterPtr RasterBuffer::GetNextRaster ()
Removes from the buffer the oldest instance of 'Raster' and returns it to caller; if buffer is empty will return NULL.
Definition at line 124 of file RasterBuffer.cpp.
References KKU::GoalKeeper::EndBlock(), KKU::Raster::MemoryConsumedEstimated(), and KKU::GoalKeeper::StartBlock().
int32 KKU::RasterBuffer::MaxNumOfBuffers () const inline
Definition at line 51 of file RasterBuffer.h.
void KKU::RasterBuffer::MaxNumOfBuffers (int32 _maxNumOfBuffers) inline
Definition at line 65 of file RasterBuffer.h.
int32 RasterBuffer::MemoryConsumedEstimated ()
Returns an estimate of the amount of memory consumed in bytes.
This will help managed objects keep track of how much memory they are using in the unmanaged world.
Definition at line 143 of file RasterBuffer.cpp.
References KKU::GoalKeeper::EndBlock(), and KKU::GoalKeeper::StartBlock().
int32 RasterBuffer::NumAvailable () const
The number of entries that are left in the buffer before 'maxNumOfBuffers' is reached.
Definition at line 89 of file RasterBuffer.cpp.
int32 RasterBuffer::NumPopulated () const
Definition at line 95 of file RasterBuffer.cpp.
int32 KKU::RasterBuffer::RastersDropped () const inline
Returns the number of 'Raster' instances that had to be deleted because the size of the queue had reached 'maxNumOfBuffers'.
Definition at line 49 of file RasterBuffer.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/RasterBuffer.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/RasterBuffer.cpp