Pices: PicesInterface::PicesClassStatisticList Class Reference
PicesInterface::PicesClassStatisticList Class Reference
#include <PicesClassStatistic.h>
Public Types
typedef KKU::uint uint
Public Member Functions
PicesClassStatisticList ()
PicesClassStatisticList (const ClassStatisticList &stats)
void Add (PicesClass^ mlClass, uint count)
void Add (PicesClassStatisticList^ stats)
PicesClassStatisticList^ RemoveNoiseClasses ()
void SortByClassName ()
PicesClassStatisticList^ Summarize (int hierarchyLevel)
PicesClassList^ ToPicesClassList ()
ClassStatisticListPtr ToUnmanagedClassStatisticList ()
Properties
uint CountTotal [get]
uint ImageCountTotal [get]
Detailed Description
Definition at line 44 of file PicesClassStatistic.h.
Member Typedef Documentation
typedef KKU::uint PicesInterface::PicesClassStatisticList::uint
Definition at line 47 of file PicesClassStatistic.h.
Constructor & Destructor Documentation
PicesInterface::PicesClassStatisticList::PicesClassStatisticList ()
Definition at line 63 of file PicesClassStatistic.cpp.
PicesInterface::PicesClassStatisticList::PicesClassStatisticList (const ClassStatisticList & stats)
Definition at line 69 of file PicesClassStatistic.cpp.
Member Function Documentation
void PicesInterface::PicesClassStatisticList::Add (PicesClass^ mlClass, uint count)
Definition at line 110 of file PicesClassStatistic.cpp.
References PicesInterface::PicesClassStatistic::Count, and PicesInterface::PicesClassStatistic::MLClass.
Referenced by PicesCommander.PlanktonClassStatisticsLoader::GetStatsAlreadyLoaded(), and PicesCommander.PlanktonClassStatisticsLoader::GetStatsAlreadyLoadedIfNew().
void PicesInterface::PicesClassStatisticList::Add (PicesClassStatisticList^ stats)
Definition at line 129 of file PicesClassStatistic.cpp.
References PicesInterface::PicesClassStatistic::Count, and PicesInterface::PicesClassStatistic::MLClass.
PicesClassStatisticList PicesInterface::PicesClassStatisticList::RemoveNoiseClasses ()
Definition at line 184 of file PicesClassStatistic.cpp.
References PicesInterface::PicesClassStatistic::ClassName.
void PicesInterface::PicesClassStatisticList::SortByClassName ()
Definition at line 102 of file PicesClassStatistic.cpp.
References PicesInterface::ComparePicesClassStatistic().
PicesClassStatisticList PicesInterface::PicesClassStatisticList::Summarize (int hierarchyLevel)
Definition at line 159 of file PicesClassStatistic.cpp.
References PicesInterface::PicesClassStatistic::Count, PicesInterface::PicesClassStatistic::MLClass, and PicesInterface::PicesClass::MLClassForGivenHierarchialLevel().
PicesClassList PicesInterface::PicesClassStatisticList::ToPicesClassList ()
Definition at line 217 of file PicesClassStatistic.cpp.
References PicesInterface::PicesClassStatistic::MLClass.
Referenced by PicesInterface::PicesAbundanceCorrectionMatrix::PrintAdjustedResults().
ClassStatisticListPtr PicesInterface::PicesClassStatisticList::ToUnmanagedClassStatisticList ()
Definition at line 203 of file PicesClassStatistic.cpp.
References PicesInterface::PicesClassStatistic::Count, PicesInterface::PicesClassStatistic::MLClass, and PicesInterface::PicesClass::UnmanagedMLClass().
Referenced by PicesInterface::PicesAbundanceCorrectionMatrix::AdjustClassificationCounts(), and PicesInterface::PicesAbundanceCorrectionMatrix::LumpCounts().
Property Documentation
uint PicesInterface::PicesClassStatisticList::CountTotal get
Definition at line 59 of file PicesClassStatistic.h.
uint PicesInterface::PicesClassStatisticList::ImageCountTotal get
Definition at line 61 of file PicesClassStatistic.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesClassStatistic.h
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesClassStatistic.cpp