Pices: SipperHardware::SipperFileList Class Reference
SipperHardware::SipperFileList Class Reference
#include <SipperFile.h>
Public Types
typedef SipperFileList * SipperFileListPtr
Public Member Functions
SipperFileList (bool _owner=true)
~SipperFileList ()
SipperFilePtr LookUpBySipperFileName (const KKStr &sipperFileName)
void Save (const KKStr &fileName)
Static Public Member Functions
static SipperFileListPtr GetListOfSipperFilesWeCanFind (RunLog &runLog)
static SipperFileListPtr Load (const KKStr &fileName)
Detailed Description
Definition at line 143 of file SipperFile.h.
Member Typedef Documentation
typedef SipperFileList* SipperHardware::SipperFileList::SipperFileListPtr
Definition at line 146 of file SipperFile.h.
Constructor & Destructor Documentation
SipperFileList::SipperFileList (bool _owner = true)
Definition at line 531 of file SipperFile.cpp.
Referenced by GetListOfSipperFilesWeCanFind(), and Load().
SipperFileList::~SipperFileList ()
Definition at line 537 of file SipperFile.cpp.
Member Function Documentation
SipperFileListPtr SipperFileList::GetListOfSipperFilesWeCanFind (RunLog & runLog) static
Definition at line 544 of file SipperFile.cpp.
References SipperHardware::SipperFile::Description(), SipperHardware::InstrumentDataFileManager::GetListOfSipperFiles(), KKU::osGetRootName(), and SipperFileList().
SipperFileListPtr SipperFileList::Load (const KKStr & fileName) static
Definition at line 602 of file SipperFile.cpp.
References KKU::KKStr::EqualIgnoreCase(), KKU::KKStrParser::GetNextToken(), LookUpBySipperFileName(), SipperHardware::SipperFile::ReFresh(), SipperFileList(), SipperHardware::SipperFile::SipperFileName(), KKU::KKStr::Str(), and KKU::KKStrParser::SubStrPart().
SipperFilePtr SipperFileList::LookUpBySipperFileName (const KKStr & sipperFileName)
Definition at line 585 of file SipperFile.cpp.
References KKU::KKStr::EqualIgnoreCase(), KKU::osGetRootName(), and SipperHardware::SipperFile::SipperFileName().
Referenced by Load().
void SipperFileList::Save (const KKStr & fileName)
Definition at line 565 of file SipperFile.cpp.
References KKU::endl(), KKU::osGetLocalDateTime(), and KKU::KKStr::Str().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/SipperFile.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/SipperFile.cpp