Pices: MLL::ModelParam Class Reference
MLL::ModelParam Class Reference abstract
Abstract Base class for Machine Learning parameters.
#include <ModelParam.h>
Public Types
enum CompressionMethodType {
BRNull, BRnoCompression, BRcompressionPost, BRcompressionPre,
BRunBalancedVariance, BRunBalancedSpecified
}
enum EncodingMethodType { NoEncoding, BinaryEncoding, ScaledEncoding, Encoding_NULL }
typedef ModelParam * ModelParamPtr
enum ModelParamTypes {
mptNULL, mptDual, mptKNN, mptOldSVM,
mptSvmBase, mptUsfCasCor
}
Public Member Functions
ModelParam (FileDescPtr _fileDesc, RunLog &_log)
ModelParam (const ModelParam &_param)
virtual ~ModelParam ()
virtual float A_Param () const
virtual void A_Param (float _prob)
virtual float AvgMumOfFeatures () const
virtual int32 BitsToReduceBy () const
virtual void BitsToReduceBy (int32 _bitsToReduceBy)
virtual double C_Param () const
virtual void C_Param (double _cost)
virtual CompressionMethodType CompressionMethod () const
virtual void CompressionMethod (CompressionMethodType _compMethod)
virtual KKStr CompressionMethodStr () const
virtual double Cost () const
virtual void Cost (double _cost)
virtual ModelParamPtr Duplicate () const =0
virtual EncodingMethodType EncodingMethod () const
virtual void EncodingMethod (EncodingMethodType _encodingMethod)
virtual KKStr EncodingMethodStr () const
virtual int32 ExamplesPerClass () const
virtual void ExamplesPerClass (int32 _examplesPerClass)
virtual const KKStr & FileName () const
virtual void FileName (const KKStr &_fileName)
virtual double Gamma () const
virtual void Gamma (double _gamma)
virtual int32 MemoryConsumedEstimated () const
virtual ModelParamTypes ModelParamType () const =0
virtual KKStr ModelParamTypeStr () const
virtual bool NormalizeNominalFeatures () const
virtual int32 NumOfFeaturesAfterEncoding () const
virtual void ParseCmdLine (KKStr _cmdLineStr, bool &_validFormat)
virtual void ParseCmdLinePost ()
Called after 'ParseCmdLine' is completed.
virtual float Prob () const
virtual void Prob (float _prob)
virtual void ReadSpecificImplementationXML (istream &i)=0
virtual void ReadXML (KKStr &_fileName, bool &_successful)
virtual void ReadXML (istream &i)
virtual const FeatureNumList & SelectedFeatures () const
virtual void SelectedFeatures (const FeatureNumList &_selectedFeatures)
virtual KKStr ToCmdLineStr () const
Creates a a Command Line String that represents these parameters.
virtual int32 UnBalancedBits () const
virtual void UnBalancedBits (int32 _unBalancedBits)
virtual KKStr UnBalancedBitsStr () const
virtual void UnBalancedBitsStr (const KKStr &_unBalancedBitsStr)
virtual bool ValidParam () const
virtual void ValidParam (bool _validParam)
virtual bool WeightBitReduction () const
virtual void WeightBitReduction (bool _weightBitReduction)
virtual void WriteSpecificImplementationXML (std::ostream &o) const =0
virtual void WriteXML (std::ostream &o) const
Static Public Member Functions
static CompressionMethodType CompressionMethodFromStr (const KKStr &compressionMethodStr)
static KKStr CompressionMethodToStr (CompressionMethodType compressionMethod)
static ModelParamPtr CreateModelParam (istream &i, FileDescPtr _fileDesc, RunLog &_log)
static EncodingMethodType EncodingMethodFromStr (const KKStr &encodingMethodStr)
static KKStr EncodingMethodToStr (EncodingMethodType encodingMethod)
static ModelParamTypes ModelParamTypeFromStr (const KKStr &_modelParamTypeStr)
static KKStr ModelParamTypeToStr (ModelParamTypes _modelParamType)
Protected Attributes
FileDescPtr fileDesc
RunLog & log
Detailed Description
Abstract Base class for Machine Learning parameters.
Author
Kurt Kramer
For each Machine Learning algorithm implemented you would create a specialization of this class to manage the parameters required by the algorithm. Specifically for each new class that you create that is derived from 'Model' you will new to create a class derived from 'ModelParam'. This class encapsulates general parameters that are common to all Machine Learning Models. *
See Also
Model
Definition at line 37 of file ModelParam.h.
Member Typedef Documentation
typedef ModelParam* MLL::ModelParam::ModelParamPtr
Definition at line 40 of file ModelParam.h.
Member Enumeration Documentation
enum MLL::ModelParam::CompressionMethodType
Enumerator
BRNull
BRnoCompression
BRcompressionPost
BRcompressionPre
BRunBalancedVariance
BRunBalancedSpecified
Definition at line 48 of file ModelParam.h.
enum MLL::ModelParam::EncodingMethodType
Enumerator
NoEncoding
BinaryEncoding
ScaledEncoding
Encoding_NULL
Definition at line 46 of file ModelParam.h.
enum MLL::ModelParam::ModelParamTypes
Enumerator
mptNULL
mptDual
mptKNN
mptOldSVM
mptSvmBase
mptUsfCasCor
Definition at line 42 of file ModelParam.h.
Constructor & Destructor Documentation
MLL::ModelParam::ModelParam (FileDescPtr _fileDesc, RunLog & _log)
Referenced by MemoryConsumedEstimated().
ModelParam::ModelParam (const ModelParam & _param)
Definition at line 71 of file ModelParam.cpp.
ModelParam::~ModelParam () virtual
Definition at line 95 of file ModelParam.cpp.
Member Function Documentation
float ModelParam::A_Param () const virtual
Reimplemented in MLL::ModelParamOldSVM.
Definition at line 244 of file ModelParam.cpp.
Referenced by MLL::TrainingConfiguration2::A_Param(), MLL::ModelParamOldSVM::A_Param(), and MLL::ModelParamOldSVM::ParseCmdLine().
void ModelParam::A_Param (float _prob) virtual
Reimplemented in MLL::ModelParamOldSVM.
Definition at line 273 of file ModelParam.cpp.
virtual float MLL::ModelParam::AvgMumOfFeatures () const inline virtual
Definition at line 125 of file ModelParam.h.
References MLL::FeatureNumList::NumOfFeatures().
Referenced by MLL::TrainingConfiguration2::AvgNumOfFeatures().
virtual int32 MLL::ModelParam::BitsToReduceBy () const inline virtual
Reimplemented in MLL::ModelParamOldSVM.
Definition at line 126 of file ModelParam.h.
Referenced by MLL::TrainingConfiguration2::BitsToReduceBy(), MLL::Model::BitsToReduceBy(), and MLL::ModelParamOldSVM::ParseCmdLine().
virtual void MLL::ModelParam::BitsToReduceBy (int32 _bitsToReduceBy) inline virtual
Definition at line 150 of file ModelParam.h.
double ModelParam::C_Param () const virtual
Reimplemented in MLL::ModelParamOldSVM.
Definition at line 249 of file ModelParam.cpp.
Referenced by MLL::TrainingConfiguration2::C_Param(), and MLL::ModelParamOldSVM::ParseCmdLine().
void ModelParam::C_Param (double _cost) virtual
Reimplemented in MLL::ModelParamOldSVM.
Definition at line 279 of file ModelParam.cpp.
virtual CompressionMethodType MLL::ModelParam::CompressionMethod () const inline virtual
Definition at line 127 of file ModelParam.h.
Referenced by MLL::TrainingConfiguration2::CompressionMethod(), MLL::ModelParamOldSVM::ParseCmdLine(), and MLL::Model::TrainModel().
virtual void MLL::ModelParam::CompressionMethod (CompressionMethodType _compMethod) inline virtual
Definition at line 151 of file ModelParam.h.
ModelParam::CompressionMethodType ModelParam::CompressionMethodFromStr (const KKStr & compressionMethodStr) static
Definition at line 783 of file ModelParam.cpp.
References BRcompressionPost, BRcompressionPre, BRnoCompression, BRNull, BRunBalancedSpecified, BRunBalancedVariance, KKU::KKStr::Empty(), and KKU::KKStr::Upper().
Referenced by ParseCmdLine().
virtual KKStr MLL::ModelParam::CompressionMethodStr () const inline virtual
Definition at line 128 of file ModelParam.h.
References CompressionMethodToStr().
Referenced by WriteXML().
KKStr ModelParam::CompressionMethodToStr (CompressionMethodType compressionMethod) static
Definition at line 758 of file ModelParam.cpp.
References BRcompressionPost, BRcompressionPre, BRnoCompression, BRNull, BRunBalancedSpecified, and BRunBalancedVariance.
Referenced by CompressionMethodStr(), and ToCmdLineStr().
double ModelParam::Cost () const virtual
Reimplemented in MLL::ModelParamSvmBase.
Definition at line 254 of file ModelParam.cpp.
Referenced by MLL::ModelParamOldSVM::C_Param(), MLL::ModelParamSvmBase::Cost(), and ParseCmdLine().
void ModelParam::Cost (double _cost) virtual
Reimplemented in MLL::ModelParamSvmBase.
Definition at line 285 of file ModelParam.cpp.
ModelParamPtr ModelParam::CreateModelParam (istream & i, FileDescPtr _fileDesc, RunLog & _log) static
Definition at line 111 of file ModelParam.cpp.
References KKU::endl(), KKU::KKStr::EqualIgnoreCase(), KKU::KKStr::ExtractToken2(), KKU::RunLog::Level(), ModelParamTypeFromStr(), mptDual, mptKNN, mptNULL, mptOldSVM, mptSvmBase, mptUsfCasCor, and ReadXML().
Referenced by MLL::Model::ReadXML().
virtual ModelParamPtr MLL::ModelParam::Duplicate () const pure virtual
Implemented in MLL::ModelParamDual, MLL::ModelParamOldSVM, MLL::ModelParamSvmBase, MLL::ModelParamUsfCasCor, and MLL::ModelParamKnn.
Referenced by MLL::Model::Model(), MLL::TrainingConfiguration2::ModelParameters(), MLL::TrainingConfiguration2::SetModelParameters(), and MLL::TrainingConfiguration2::TrainingConfiguration2().
virtual EncodingMethodType MLL::ModelParam::EncodingMethod () const inline virtual
Definition at line 129 of file ModelParam.h.
Referenced by MLL::ModelParamOldSVM::EncodingMethod(), MLL::TrainingConfiguration2::EncodingMethod(), MLL::Model::NormalizeNominalAttributes(), NumOfFeaturesAfterEncoding(), MLL::ModelParamOldSVM::ParseCmdLine(), and MLL::Model::TrainModel().
virtual void MLL::ModelParam::EncodingMethod (EncodingMethodType _encodingMethod) inline virtual
Reimplemented in MLL::ModelParamOldSVM.
Definition at line 152 of file ModelParam.h.
ModelParam::EncodingMethodType ModelParam::EncodingMethodFromStr (const KKStr & encodingMethodStr) static
Definition at line 739 of file ModelParam.cpp.
References BinaryEncoding, Encoding_NULL, NoEncoding, ScaledEncoding, and KKU::KKStr::ToUpper().
Referenced by ParseCmdLine().
virtual KKStr MLL::ModelParam::EncodingMethodStr () const inline virtual
Definition at line 130 of file ModelParam.h.
References EncodingMethodToStr().
Referenced by WriteXML().
KKStr ModelParam::EncodingMethodToStr (EncodingMethodType encodingMethod) static
Definition at line 723 of file ModelParam.cpp.
References BinaryEncoding, and ScaledEncoding.
Referenced by EncodingMethodStr(), and ToCmdLineStr().
virtual int32 MLL::ModelParam::ExamplesPerClass () const inline virtual
Definition at line 131 of file ModelParam.h.
Referenced by MLL::Model::ReduceTrainExamples(), and MLL::Model::TrainModel().
virtual void MLL::ModelParam::ExamplesPerClass (int32 _examplesPerClass) inline virtual
Definition at line 153 of file ModelParam.h.
virtual const KKStr& MLL::ModelParam::FileName () const inline virtual
Definition at line 132 of file ModelParam.h.
Referenced by MLL::ModelKnn::TrainModel(), MLL::ModelSvmBase::TrainModel(), and MLL::ModelDual::TrainModel().
virtual void MLL::ModelParam::FileName (const KKStr & _fileName) inline virtual
Definition at line 154 of file ModelParam.h.
double ModelParam::Gamma () const virtual
Reimplemented in MLL::ModelParamOldSVM, and MLL::ModelParamSvmBase.
Definition at line 259 of file ModelParam.cpp.
Referenced by MLL::ModelParamSvmBase::Gamma(), MLL::TrainingConfiguration2::Gamma(), MLL::ModelParamOldSVM::Gamma(), MLL::ModelParamOldSVM::Gamma_Param(), ParseCmdLine(), and MLL::ModelParamOldSVM::ParseCmdLine().
void ModelParam::Gamma (double _gamma) virtual
Reimplemented in MLL::ModelParamOldSVM, and MLL::ModelParamSvmBase.
Definition at line 291 of file ModelParam.cpp.
int32 ModelParam::MemoryConsumedEstimated () const virtual
Definition at line 100 of file ModelParam.cpp.
References MLL::FeatureNumList::MemoryConsumedEstimated(), KKU::KKStr::MemoryConsumedEstimated(), and ModelParam().
Referenced by MLL::Model::MemoryConsumedEstimated().
virtual ModelParamTypes MLL::ModelParam::ModelParamType () const pure virtual
Implemented in MLL::ModelParamOldSVM, MLL::ModelParamDual, MLL::ModelParamSvmBase, MLL::ModelParamUsfCasCor, and MLL::ModelParamKnn.
Referenced by ModelParamTypeStr(), MLL::TrainingConfiguration2::Number_of_rounds(), and MLL::ModelOldSVM::Param().
ModelParam::ModelParamTypes ModelParam::ModelParamTypeFromStr (const KKStr & _modelParamTypeStr) static
Definition at line 220 of file ModelParam.cpp.
References KKU::KKStr::EqualIgnoreCase(), mptDual, mptKNN, mptNULL, mptOldSVM, mptSvmBase, and mptUsfCasCor.
Referenced by CreateModelParam().
virtual KKStr MLL::ModelParam::ModelParamTypeStr () const inline virtual
Definition at line 123 of file ModelParam.h.
References ModelParamType(), and ModelParamTypeToStr().
Referenced by WriteXML().
KKStr ModelParam::ModelParamTypeToStr (ModelParamTypes _modelParamType) static
Definition at line 194 of file ModelParam.cpp.
References mptDual, mptKNN, mptNULL, mptOldSVM, mptSvmBase, and mptUsfCasCor.
Referenced by ModelParamTypeStr().
virtual bool MLL::ModelParam::NormalizeNominalFeatures () const inline virtual
Definition at line 133 of file ModelParam.h.
Referenced by MLL::TrainingConfiguration2::NormalizeNominalFeatures().
int32 ModelParam::NumOfFeaturesAfterEncoding () const virtual
Reimplemented in MLL::ModelParamOldSVM.
Definition at line 688 of file ModelParam.cpp.
References BinaryEncoding, MLL::FileDesc::Cardinality(), EncodingMethod(), fileDesc, log, NoEncoding, MLL::NominalAttribute, MLL::FeatureNumList::NumOfFeatures(), ScaledEncoding, MLL::SymbolicAttribute, and MLL::FileDesc::Type().
Referenced by MLL::TrainingConfiguration2::NumOfFeaturesAfterEncoding().
void ModelParam::ParseCmdLine (KKStr _cmdLineStr, bool & _validFormat) virtual
Reimplemented in MLL::ModelParamOldSVM.
Definition at line 306 of file ModelParam.cpp.
References CompressionMethodFromStr(), Cost(), KKU::KKStr::Empty(), EncodingMethodFromStr(), KKU::endl(), MLL::FeatureNumList::ExtractFeatureNumsFromStr(), KKU::KKStr::ExtractToken(), Gamma(), int32_max, KKU::KKStr::Len(), KKU::RunLog::Level(), log, ParseCmdLinePost(), KKU::KKStr::ToBool(), KKU::KKStr::TrimLeft(), and KKU::KKStr::Upper().
void ModelParam::ParseCmdLinePost () virtual
Called after 'ParseCmdLine' is completed.
Classed derived from 'ModelParam' can implement this method to do any processing that they want after the entire command line has been processed.
An example use of this is in 'ModelParamSvmBase' where the local 'ParseCmdLineParameter' routine processes parameters that 'Model' needs to be aware of.
Definition at line 469 of file ModelParam.cpp.
Referenced by ParseCmdLine().
float ModelParam::Prob () const virtual
Definition at line 264 of file ModelParam.cpp.
void ModelParam::Prob (float _prob) virtual
Definition at line 297 of file ModelParam.cpp.
virtual void MLL::ModelParam::ReadSpecificImplementationXML (istream & i) pure virtual
Implemented in MLL::ModelParamUsfCasCor, MLL::ModelParamSvmBase, MLL::ModelParamOldSVM, MLL::ModelParamDual, and MLL::ModelParamKnn.
virtual void MLL::ModelParam::ReadXML (KKStr & _fileName, bool & _successful) virtual
Referenced by CreateModelParam(), MLL::ModelParamKnn::ReadSpecificImplementationXML(), MLL::ModelParamDual::ReadSpecificImplementationXML(), MLL::ModelParamSvmBase::ReadSpecificImplementationXML(), and MLL::ModelParamUsfCasCor::ReadSpecificImplementationXML().
virtual void MLL::ModelParam::ReadXML (istream & i) virtual
virtual const FeatureNumList& MLL::ModelParam::SelectedFeatures () const inline virtual
Reimplemented in MLL::ModelParamOldSVM.
Definition at line 135 of file ModelParam.h.
Referenced by MLL::FeatureEncoder2::FeatureEncoder2(), MLL::Model::GetFeatureNums(), MLL::TrainingConfiguration2::GetFeatureNums(), MLL::TrainingConfiguration2::Save(), MLL::ModelParamOldSVM::SelectedFeatures(), MLL::Model::SelectedFeatures(), MLL::TrainingConfiguration2::SetFeatureNums(), and MLL::ModelSvmBase::TrainModel().
virtual void MLL::ModelParam::SelectedFeatures (const FeatureNumList & _selectedFeatures) inline virtual
Reimplemented in MLL::ModelParamOldSVM.
Definition at line 155 of file ModelParam.h.
KKStr ModelParam::ToCmdLineStr () const virtual
Creates a a Command Line String that represents these parameters.
Convert all parameters to a command line string.
All derived classes should implement this method. They should first call this method and then append there own parameters that are specific to their implementation.
Reimplemented in MLL::ModelParamOldSVM, MLL::ModelParamSvmBase, MLL::ModelParamUsfCasCor, MLL::ModelParamDual, and MLL::ModelParamKnn.
Definition at line 478 of file ModelParam.cpp.
References BRnoCompression, CompressionMethodToStr(), KKU::KKStr::Empty(), EncodingMethodToStr(), KKU::endl(), int32_max, KKU::RunLog::Level(), log, NoEncoding, and MLL::FeatureNumList::ToCommaDelStr().
Referenced by MLL::TrainingConfiguration2::ModelParameterCmdLine(), CrossValidationApp::ReportConfigurationInfo(), MLL::TrainingConfiguration2::Save(), MLL::ModelParamKnn::ToCmdLineStr(), MLL::ModelParamDual::ToCmdLineStr(), and MLL::ModelParamSvmBase::ToCmdLineStr().
virtual int32 MLL::ModelParam::UnBalancedBits () const inline virtual
Reimplemented in MLL::ModelParamOldSVM.
Definition at line 136 of file ModelParam.h.
Referenced by MLL::ModelParamOldSVM::ParseCmdLine(), and MLL::TrainingConfiguration2::UnBalancedBits().
virtual void MLL::ModelParam::UnBalancedBits (int32 _unBalancedBits) inline virtual
Definition at line 156 of file ModelParam.h.
virtual KKStr MLL::ModelParam::UnBalancedBitsStr () const inline virtual
Reimplemented in MLL::ModelParamOldSVM.
Definition at line 137 of file ModelParam.h.
Referenced by MLL::ModelParamOldSVM::ParseCmdLine().
virtual void MLL::ModelParam::UnBalancedBitsStr (const KKStr & _unBalancedBitsStr) inline virtual
Definition at line 157 of file ModelParam.h.
virtual bool MLL::ModelParam::ValidParam () const inline virtual
Definition at line 138 of file ModelParam.h.
Referenced by MLL::ModelParamOldSVM::ParseCmdLine(), MLL::ModelParamDual::ReadSpecificImplementationXML(), MLL::ModelParamSvmBase::ReadSpecificImplementationXML(), MLL::ModelParamUsfCasCor::ReadSpecificImplementationXML(), and MLL::Model::ReadXML().
virtual void MLL::ModelParam::ValidParam (bool _validParam) inline virtual
Definition at line 158 of file ModelParam.h.
virtual bool MLL::ModelParam::WeightBitReduction () const inline virtual
Reimplemented in MLL::ModelParamOldSVM.
Definition at line 139 of file ModelParam.h.
Referenced by MLL::ModelParamOldSVM::ParseCmdLine(), MLL::ModelParamOldSVM::WeightBitReduction(), and MLL::TrainingConfiguration2::WeightBitReduction().
virtual void MLL::ModelParam::WeightBitReduction (bool _weightBitReduction) inline virtual
Reimplemented in MLL::ModelParamOldSVM.
Definition at line 159 of file ModelParam.h.
virtual void MLL::ModelParam::WriteSpecificImplementationXML (std::ostream & o) const pure virtual
Implemented in MLL::ModelParamDual, MLL::ModelParamUsfCasCor, MLL::ModelParamSvmBase, MLL::ModelParamOldSVM, and MLL::ModelParamKnn.
Referenced by WriteXML().
void ModelParam::WriteXML (std::ostream & o) const virtual
Definition at line 516 of file ModelParam.cpp.
References CompressionMethodStr(), EncodingMethodStr(), KKU::endl(), KKU::RunLog::Level(), log, ModelParamTypeStr(), MLL::FeatureNumList::ToCommaDelStr(), and WriteSpecificImplementationXML().
Referenced by MLL::Model::WriteXML().
Member Data Documentation
FileDescPtr MLL::ModelParam::fileDesc protected
Definition at line 178 of file ModelParam.h.
Referenced by NumOfFeaturesAfterEncoding().
RunLog& MLL::ModelParam::log protected
Definition at line 180 of file ModelParam.h.
Referenced by NumOfFeaturesAfterEncoding(), ParseCmdLine(), MLL::ModelParamOldSVM::ParseCmdLine(), MLL::ModelParamKnn::ReadSpecificImplementationXML(), MLL::ModelParamDual::ReadSpecificImplementationXML(), MLL::ModelParamOldSVM::ReadSpecificImplementationXML(), MLL::ModelParamSvmBase::ReadSpecificImplementationXML(), MLL::ModelParamUsfCasCor::ReadSpecificImplementationXML(), MLL::ModelParamOldSVM::SvmParamToString(), MLL::ModelParamDual::ToCmdLineStr(), MLL::ModelParamSvmBase::ToCmdLineStr(), ToCmdLineStr(), MLL::ModelParamOldSVM::ToCmdLineStr(), MLL::ModelParamOldSVM::WriteSpecificImplementationXML(), MLL::ModelParamSvmBase::WriteSpecificImplementationXML(), MLL::ModelParamUsfCasCor::WriteSpecificImplementationXML(), MLL::ModelParamDual::WriteSpecificImplementationXML(), and WriteXML().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ModelParam.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ModelParam.cpp