Pices: SipperDiskUtilities.PartitionTableEntry Class Reference
SipperDiskUtilities.PartitionTableEntry Class Reference
Reprsents a single partition table enry.
Public Member Functions
PartitionTableEntry (byte[] buff, ref int nextIndex)
Constructs a Partition Table Entry from the contents of a buffer.
Int64 GetPartitionSectorByteOffset ()
Int64 GetSipperDirectoryByteOffset ()
Static Public Member Functions
static int BuffSpaceNeeded ()
Properties
long DiskSizeBytes [get]
UInt32 RelativeSector [get]
UInt32 TotalSectors [get]
Detailed Description
Reprsents a single partition table enry.
Author
Kurt Kramer
 Developer:  Kurt Kramer                                                  *
 Date:       2007-Sept-05                                                 *
                                                                          *
 This cde was inspired by the Sipper3DLL.c code written by  Jim Patten    *
--------------------------------------------------------------------------*
 Meant to support the reading of data off the SIPPER harddrive.  This     *
class in particular represents a single partition entry in a Partition    *
table off the Master Boot record.                                         *
Definition at line 27 of file PartitionTableEntry.cs.
Constructor & Destructor Documentation
SipperDiskUtilities.PartitionTableEntry.PartitionTableEntry (byte[] buff, ref int nextIndex) inline
Constructs a Partition Table Entry from the contents of a buffer.
Parameters
[in] buff Buffer to read data from.
[in,out] nextIndex Next byte from the bufer to be read. Constructor will increment this as it processes each character in the buff. The caller can use this as the starting point for the next partition table entry.
Definition at line 55 of file PartitionTableEntry.cs.
Member Function Documentation
static int SipperDiskUtilities.PartitionTableEntry.BuffSpaceNeeded () inline static
Definition at line 72 of file PartitionTableEntry.cs.
Referenced by SipperDiskUtilities.PartitionTable.BuffSpaceNeeded().
Int64 SipperDiskUtilities.PartitionTableEntry.GetPartitionSectorByteOffset () inline
Definition at line 79 of file PartitionTableEntry.cs.
References SipperDiskUtilities.Constants.LOGICAL_BLOCK_SIZE.
Referenced by SipperDiskUtilities.PartitionTable.GetPartitionSectorByteOffset().
Int64 SipperDiskUtilities.PartitionTableEntry.GetSipperDirectoryByteOffset () inline
Definition at line 87 of file PartitionTableEntry.cs.
References SipperDiskUtilities.SipperPartitionSector.BuffSpaceNeeded(), and SipperDiskUtilities.Constants.LOGICAL_BLOCK_SIZE.
Referenced by SipperDiskUtilities.PartitionTable.GetSipperDirectoryByteOffset().
Property Documentation
long SipperDiskUtilities.PartitionTableEntry.DiskSizeBytes get
Definition at line 45 of file PartitionTableEntry.cs.
UInt32 SipperDiskUtilities.PartitionTableEntry.RelativeSector get
Definition at line 41 of file PartitionTableEntry.cs.
Referenced by SipperDiskUtilities.SipperDisk.ResetSipperDirectory(), and SipperDiskUtilities.SipperPartitionSector.SipperPartitionSector().
UInt32 SipperDiskUtilities.PartitionTableEntry.TotalSectors get
Definition at line 42 of file PartitionTableEntry.cs.
Referenced by SipperDiskUtilities.SipperPartitionSector.SipperPartitionSector().
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperDiskUtilities/PartitionTableEntry.cs