Pices: KKU::RBTree< Entry, CompareNodes, KeyType > Class Template Reference
KKU::RBTree< Entry, CompareNodes, KeyType > Class Template Reference
#include <RBTree.h>
Public Types
typedef Entry * EntryPtr
typedef KKU::int32 int32
typedef Iterator< Entry,
CompareNodes, KeyType > * IteratorPtr
typedef RBnode< Entry > Node
typedef Node * NodePtr
typedef RBTree< Entry,
CompareNodes, KeyType > Tree
typedef Tree * TreePtr
typedef KKU::uint32 uint32
Public Member Functions
RBTree (CompareNodes &_comparator, bool _owner)
RBTree (RBTree &tree)
~RBTree ()
void CalcTreeStats ()
bool CompareToTree (TreePtr tree)
void DeleteCurrentNode ()
void DeleteEntry (EntryPtr e)
EntryPtr GetEqual (const KeyType &key)
EntryPtr GetFirst ()
EntryPtr GetGreater (const KeyType &key)
EntryPtr GetGreaterOrEqual (const KeyType &key)
EntryPtr GetLast ()
EntryPtr GetLess (const KeyType &key)
EntryPtr GetNext ()
EntryPtr GetPrev ()
EntryPtr Predeccessor ()
NodePtr RBInsert (EntryPtr e)
uint32 Size ()
EntryPtr Successor ()
bool Validate ()
void WalkTree ()
Friends
class Iterator< Entry, CompareNodes, KeyType >
Detailed Description
template<class Entry, class CompareNodes, typename KeyType>
class KKU::RBTree< Entry, CompareNodes, KeyType >
Definition at line 69 of file RBTree.h.
Member Typedef Documentation
template<class Entry, class CompareNodes, typename KeyType> typedef Entry* KKU::RBTree< Entry, CompareNodes, KeyType >::EntryPtr
Definition at line 122 of file RBTree.h.
template<class Entry, class CompareNodes, typename KeyType> typedef KKU::int32 KKU::RBTree< Entry, CompareNodes, KeyType >::int32
Definition at line 126 of file RBTree.h.
template<class Entry, class CompareNodes, typename KeyType> typedef Iterator<Entry,CompareNodes,KeyType>* KKU::RBTree< Entry, CompareNodes, KeyType >::IteratorPtr
Definition at line 179 of file RBTree.h.
template<class Entry, class CompareNodes, typename KeyType> typedef RBnode<Entry> KKU::RBTree< Entry, CompareNodes, KeyType >::Node
Definition at line 123 of file RBTree.h.
template<class Entry, class CompareNodes, typename KeyType> typedef Node* KKU::RBTree< Entry, CompareNodes, KeyType >::NodePtr
Definition at line 124 of file RBTree.h.
template<class Entry, class CompareNodes, typename KeyType> typedef RBTree<Entry,CompareNodes,KeyType> KKU::RBTree< Entry, CompareNodes, KeyType >::Tree
Definition at line 129 of file RBTree.h.
template<class Entry, class CompareNodes, typename KeyType> typedef Tree* KKU::RBTree< Entry, CompareNodes, KeyType >::TreePtr
Definition at line 131 of file RBTree.h.
template<class Entry, class CompareNodes, typename KeyType> typedef KKU::uint32 KKU::RBTree< Entry, CompareNodes, KeyType >::uint32
Definition at line 127 of file RBTree.h.
Constructor & Destructor Documentation
template<class Entry , class CompareNodes , typename KeyType > RBTree::RBTree (CompareNodes & _comparator, bool _owner)
Definition at line 299 of file RBTree.h.
References KKU::Black.
template<class Entry , class CompareNodes , typename KeyType > RBTree::RBTree (RBTree< Entry, CompareNodes, KeyType > & tree)
Definition at line 320 of file RBTree.h.
References KKU::Black, and x.
template<class Entry , class CompareNodes , typename KeyType > RBTree::~RBTree ()
Definition at line 371 of file RBTree.h.
Member Function Documentation
template<class Entry , class CompareNodes , typename KeyType > void RBTree::CalcTreeStats ()
Definition at line 1394 of file RBTree.h.
References KKU::endl(), and INT_MAX.
template<class Entry , class CompareNodes , typename KeyType > bool RBTree::CompareToTree (TreePtr tree)
Definition at line 410 of file RBTree.h.
template<class Entry , class CompareNodes , typename KeyType > void RBTree::DeleteCurrentNode ()
Definition at line 719 of file RBTree.h.
References KKU::RBnode< Entry >::Data(), and KKU::endl().
template<class Entry , class CompareNodes , typename KeyType > void RBTree::DeleteEntry (EntryPtr e)
Definition at line 1383 of file RBTree.h.
template<class Entry , class CompareNodes , typename KeyType > Entry * RBTree::GetEqual (const KeyType & key)
Definition at line 494 of file RBTree.h.
template<class Entry , class CompareNodes , typename KeyType > Entry * RBTree::GetFirst ()
Definition at line 764 of file RBTree.h.
template<class Entry , class CompareNodes , typename KeyType > Entry * RBTree::GetGreater (const KeyType & key)
Definition at line 599 of file RBTree.h.
template<class Entry , class CompareNodes , typename KeyType > Entry * RBTree::GetGreaterOrEqual (const KeyType & key)
Definition at line 609 of file RBTree.h.
template<class Entry , class CompareNodes , typename KeyType > Entry * RBTree::GetLast ()
Definition at line 777 of file RBTree.h.
template<class Entry , class CompareNodes , typename KeyType > Entry * RBTree::GetLess (const KeyType & key)
Definition at line 670 of file RBTree.h.
template<class Entry, class CompareNodes, typename KeyType> EntryPtr KKU::RBTree< Entry, CompareNodes, KeyType >::GetNext () inline
Definition at line 167 of file RBTree.h.
References KKU::RBTree< Entry, CompareNodes, KeyType >::Successor().
template<class Entry, class CompareNodes, typename KeyType> EntryPtr KKU::RBTree< Entry, CompareNodes, KeyType >::GetPrev () inline
Definition at line 169 of file RBTree.h.
References KKU::RBTree< Entry, CompareNodes, KeyType >::Predeccessor().
template<class Entry , class CompareNodes , typename KeyType > Entry * RBTree::Predeccessor ()
Definition at line 683 of file RBTree.h.
Referenced by KKU::RBTree< Entry, CompareNodes, KeyType >::GetPrev().
template<class Entry , class CompareNodes , typename KeyType > KKU::RBnode< Entry > * RBTree::RBInsert (EntryPtr e)
Definition at line 1112 of file RBTree.h.
References KKU::Black, KKU::RBnode< Entry >::Color(), KKU::RBnode< Entry >::Left(), KKU::RBnode< Entry >::Parent(), KKU::Red, and KKU::RBnode< Entry >::Right().
template<class Entry, class CompareNodes, typename KeyType> uint32 KKU::RBTree< Entry, CompareNodes, KeyType >::Size () inline
Definition at line 143 of file RBTree.h.
template<class Entry , class CompareNodes , typename KeyType > Entry * RBTree::Successor ()
Definition at line 701 of file RBTree.h.
Referenced by KKU::RBTree< Entry, CompareNodes, KeyType >::GetNext().
template<class Entry , class CompareNodes , typename KeyType > bool RBTree::Validate ()
Definition at line 1484 of file RBTree.h.
References KKU::endl().
template<class Entry, class CompareNodes, typename KeyType> void KKU::RBTree< Entry, CompareNodes, KeyType >::WalkTree () inline
Definition at line 145 of file RBTree.h.
References KKU::RBTree< Entry, CompareNodes, KeyType >::WalkTree().
Referenced by KKU::RBTree< Entry, CompareNodes, KeyType >::WalkTree().
Friends And Related Function Documentation
template<class Entry, class CompareNodes, typename KeyType> friend class Iterator< Entry, CompareNodes, KeyType > friend
Definition at line 133 of file RBTree.h.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/RBTree.h