var class_pices_interface_1_1_pices_feature_vector_list_1_1_feature_vector_comparitor_by_image_file_name =
[
    [ "Compare", "class_pices_interface_1_1_pices_feature_vector_list_1_1_feature_vector_comparitor_by_image_file_name.html#a49c84214c0b676ce5d9ae5d2fcce4e94", null ]
];