Pices: KKU::Matrix Class Reference
KKU::Matrix Class Reference
Supports two dimensional matrices.
#include <Matrix.h>
Public Types
typedef Matrix * MatrixPtr
Public Member Functions
Matrix ()
Matrix (int32 _numOfRows, int32 _numOfCols)
Matrix (const Matrix &_matrix)
Matrix (const VectorDouble &_v)
~Matrix ()
template<typename T >
MatrixPtr BuildFromArray (int32 numOfRows, int32 numOfCols, T **data)
Will create a new matrix using the 2dArray "data" for source.
MatrixPtr CalcCoFactorMatrix ()
MatrixPtr Covariance () const
Returns a Covariance matrix.
double **const Data () const
double Determinant ()
double DeterminantSlow ()
Recursive Implementation.
void EigenVectors (MatrixPtr &eigenVectors, VectorDouble *&eigenValues) const
Will derive the eigen vectors and values of the matrix.
void FindMaxValue (double &maxVal, int32 &row, int32 &col)
Locates the maximum value in a matrix along with the row and column that is is located.
VectorDouble GetCol (int32 col) const
Matrix Inverse ()
int32 NumOfCols () const
int32 NumOfRows () const
Matrix operator* (const Matrix &right)
Matrix operator* (double right)
Matrix & operator*= (double right)
Matrix operator+ (const Matrix &right)
Matrix operator+ (double right)
Matrix & operator+= (double right)
Matrix & operator+= (const Matrix &right)
Matrix operator- (const Matrix &right)
Matrix operator- (double right)
Matrix & operator= (const Matrix &right)
Matrix & operator= (const VectorDouble &right)
Row & operator[] (int32 rowIDX) const
void ReSize (int32 _numOfRows, int32 _numOfCols)
bool Symmetric () const
Returns true is the matrix is Symmetric.
Matrix Transpose ()
Static Public Member Functions
template<typename T >
static MatrixPtr BuildFromArray (int32 numOfRows, int32 numOfCols, T **data)
Friends
Matrix operator- (double left, const Matrix &right)
std::ostream & operator<< (std::ostream &os, const Matrix &matrix)
Detailed Description
Supports two dimensional matrices.
Developed for Machine Learning Project for support of Import Vector Machine. Handles two dimensional matrixes. Functions supported are matrix addition, subtraction multiplication, transpose, determinant, and inversion. Where appropriate arithmetic arithmetic operators +, -, * were overloaded. Addition, Subtraction and Multiplication can be done against either another matrix or scaler. Also Transpose and Determinant operations are supported.
Definition at line 46 of file Matrix.h.
Member Typedef Documentation
typedef Matrix* KKU::Matrix::MatrixPtr
Definition at line 49 of file Matrix.h.
Constructor & Destructor Documentation
Matrix::Matrix ()
Definition at line 92 of file Matrix.cpp.
Referenced by BuildFromArray(), CalcCoFactorMatrix(), Covariance(), and EigenVectors().
Matrix::Matrix (int32 _numOfRows, int32 _numOfCols)
Definition at line 106 of file Matrix.cpp.
References KKU::endl().
Matrix::Matrix (const Matrix & _matrix)
Definition at line 140 of file Matrix.cpp.
Matrix::Matrix (const VectorDouble & _v)
Definition at line 155 of file Matrix.cpp.
Matrix::~Matrix ()
Definition at line 171 of file Matrix.cpp.
Member Function Documentation
template<typename T > static MatrixPtr KKU::Matrix::BuildFromArray (int32 numOfRows, int32 numOfCols, T ** data) static
template<typename T > MatrixPtr KKU::Matrix::BuildFromArray (int32 numOfRows, int32 numOfCols, T ** data)
Will create a new matrix using the 2dArray "data" for source.
If any row in "data" is equal to NULL then the corresponding row in the returned matrix will be initialized to zeros.
Parameters
[in] numOfRows Number of rows in resultant matrix.
[in] numOfCols Number of cols if resultant matrix.
[in] data A two dimensional array.
Returns
A matrix that is initialized with the contents of "data".
Definition at line 188 of file Matrix.cpp.
References KKU::endl(), and Matrix().
MatrixPtr Matrix::CalcCoFactorMatrix ()
Definition at line 604 of file Matrix.cpp.
References Determinant(), KKU::endl(), Matrix(), KKU::osWaitForEnter(), and x.
Referenced by Inverse().
MatrixPtr Matrix::Covariance () const
Returns a Covariance matrix.
Each column represents a variable and each row represents an instance of each variable.
Returns
Returns a symmetric matrix that will be (numOfRows x numOfRows) where each element will represent the covariance between their respective variables.
Definition at line 1002 of file Matrix.cpp.
References KKU::endl(), and Matrix().
double** const KKU::Matrix::Data () const inline
Definition at line 106 of file Matrix.h.
double Matrix::Determinant ()
Returns
the determinant of mat
Definition at line 943 of file Matrix.cpp.
References DBL_EPSILON.
Referenced by CalcCoFactorMatrix(), and Inverse().
double Matrix::DeterminantSlow ()
Recursive Implementation.
Definition at line 284 of file Matrix.cpp.
References KKU::endl(), and x.
void Matrix::EigenVectors (MatrixPtr & eigenVectors, VectorDouble *& eigenValues) const
Will derive the eigen vectors and values of the matrix.
Will make use of routines from Numerical Recipes for c++, ex: Tred2 and Tqli.
Definition at line 766 of file Matrix.cpp.
References KKU::endl(), Matrix(), Symmetric(), and x.
Referenced by KKU::Raster::CreateGrayScaleKLT(), and KKU::Raster::CreateGrayScaleKLTOnMaskedArea().
void Matrix::FindMaxValue (double & maxVal, int32 & row, int32 & col)
Locates the maximum value in a matrix along with the row and column that is is located.
Definition at line 816 of file Matrix.cpp.
Referenced by KKU::SegmentorOTSU::SegmentImage(), and KKU::SegmentorOTSU::SegmentMaskedImage().
VectorDouble Matrix::GetCol (int32 col) const
Definition at line 889 of file Matrix.cpp.
Referenced by KKU::Raster::CreateGrayScaleKLT(), and KKU::Raster::CreateGrayScaleKLTOnMaskedArea().
Matrix Matrix::Inverse ()
Definition at line 729 of file Matrix.cpp.
References CalcCoFactorMatrix(), Determinant(), KKU::endl(), and Transpose().
int32 KKU::Matrix::NumOfCols () const inline
Definition at line 126 of file Matrix.h.
Referenced by KKU::operator-(), and operator<<().
int32 KKU::Matrix::NumOfRows () const inline
Definition at line 128 of file Matrix.h.
Referenced by KKU::operator-(), operator<<(), and MLL::ClassificationBiasMatrix::WriteXML().
Matrix Matrix::operator* (const Matrix & right)
Definition at line 476 of file Matrix.cpp.
References KKU::endl().
Matrix Matrix::operator* (double right)
Definition at line 528 of file Matrix.cpp.
References x.
Matrix & Matrix::operator*= (double right)
Definition at line 347 of file Matrix.cpp.
References x.
Matrix Matrix::operator+ (const Matrix & right)
Definition at line 367 of file Matrix.cpp.
References KKU::endl(), and x.
Matrix Matrix::operator+ (double right)
Definition at line 517 of file Matrix.cpp.
References x.
Matrix & Matrix::operator+= (double right)
Definition at line 357 of file Matrix.cpp.
References x.
Matrix & Matrix::operator+= (const Matrix & right)
Definition at line 394 of file Matrix.cpp.
References KKU::endl(), and x.
Matrix Matrix::operator- (const Matrix & right)
Definition at line 417 of file Matrix.cpp.
References KKU::endl(), and x.
Matrix Matrix::operator- (double right)
Definition at line 441 of file Matrix.cpp.
References x.
Matrix & Matrix::operator= (const Matrix & right)
Definition at line 327 of file Matrix.cpp.
References ReSize().
Matrix & Matrix::operator= (const VectorDouble & right)
Definition at line 335 of file Matrix.cpp.
References ReSize().
Row & Matrix::operator[] (int32 rowIDX) const
Definition at line 268 of file Matrix.cpp.
References KKU::endl().
void Matrix::ReSize (int32 _numOfRows, int32 _numOfCols)
Definition at line 222 of file Matrix.cpp.
Referenced by operator=().
bool Matrix::Symmetric () const
Returns true is the matrix is Symmetric.
Definition at line 686 of file Matrix.cpp.
Referenced by EigenVectors().
Matrix Matrix::Transpose ()
Definition at line 705 of file Matrix.cpp.
Referenced by Inverse().
Friends And Related Function Documentation
Matrix operator- (double left, const Matrix & right) friend
std::ostream& operator<< (std::ostream & os, const Matrix & matrix) friend
Definition at line 851 of file Matrix.cpp.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Matrix.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Matrix.cpp