Pices: SipperFile.SipperFileBuffered Class Reference
SipperFile.SipperFileBuffered Class Reference
Public Member Functions
SipperFileBuffered (SipperBaseFile _sipperFile)
SipperFileBuffered (string _fileName, InstrumentDataManager _dataManger)
SipperFileBuffered (Stream _stream, InstrumentDataManager _dataManger)
int CropColLeft ()
int CropColRight ()
void Dispose ()
long EstimatedNumberOfScanLines ()
long FileSizeInBytes ()
void FrameBytesOffsetsUpdateThreadStart (InstrumentDataList _history)
void FrameBytesOffsetsUpdateThreadTerminate ()
void GetDisplayRows (long displayRowStart, long displayRowEnd, byte[][] raster)
byte[][] GetScanLines (long scanLineStart, long scanLineEnd)
int LargestKnowmFrameNum ()
long LargestKnownScanLine ()
int PixelsPerDisLine ()
float Ratio ()
int ScanColumnFromDisplayCol (int displayColumn)
int ScanLineSize ()
void SetPixelsPerDisplayLine (int _pixelsPerDisLine, int _cropColLeft, int _cropClRight)
Properties
bool EofReached [get]
Detailed Description
Definition at line 10 of file SipperFileBuffered.cs.
Constructor & Destructor Documentation
SipperFile.SipperFileBuffered.SipperFileBuffered (SipperBaseFile _sipperFile) inline
Definition at line 69 of file SipperFileBuffered.cs.
SipperFile.SipperFileBuffered.SipperFileBuffered (string _fileName, InstrumentDataManager _dataManger) inline
Definition at line 79 of file SipperFileBuffered.cs.
SipperFile.SipperFileBuffered.SipperFileBuffered (Stream _stream, InstrumentDataManager _dataManger) inline
Definition at line 104 of file SipperFileBuffered.cs.
Member Function Documentation
int SipperFile.SipperFileBuffered.CropColLeft () inline
Definition at line 31 of file SipperFileBuffered.cs.
int SipperFile.SipperFileBuffered.CropColRight () inline
Definition at line 32 of file SipperFileBuffered.cs.
void SipperFile.SipperFileBuffered.Dispose () inline
Definition at line 121 of file SipperFileBuffered.cs.
References SipperFile.SipperBaseFile.Dispose().
long SipperFile.SipperFileBuffered.EstimatedNumberOfScanLines () inline
Definition at line 33 of file SipperFileBuffered.cs.
References SipperFile.SipperBaseFile.EstimatedNumberOfScanLines().
long SipperFile.SipperFileBuffered.FileSizeInBytes () inline
Definition at line 34 of file SipperFileBuffered.cs.
References SipperFile.SipperBaseFile.FileSizeInBytes().
void SipperFile.SipperFileBuffered.FrameBytesOffsetsUpdateThreadStart (InstrumentDataList _history) inline
Definition at line 54 of file SipperFileBuffered.cs.
References SipperFile.SipperBaseFile.FrameBytesOffsetsUpdateThreadStart().
void SipperFile.SipperFileBuffered.FrameBytesOffsetsUpdateThreadTerminate () inline
Definition at line 60 of file SipperFileBuffered.cs.
References SipperFile.SipperBaseFile.FrameBytesOffsetsUpdateThreadTerminate().
void SipperFile.SipperFileBuffered.GetDisplayRows (long displayRowStart, long displayRowEnd, byte raster[][]) inline
Definition at line 592 of file SipperFileBuffered.cs.
References SipperFile.SipperFileBuffered.GetScanLines(), and x.
byte [][] SipperFile.SipperFileBuffered.GetScanLines (long scanLineStart, long scanLineEnd) inline
Definition at line 512 of file SipperFileBuffered.cs.
References SipperFile.SipperBaseFile.EofReached(), SipperFile.SipperBaseFile.LargestKnownScanLine(), SipperFile.SipperFrame.ScanLineFirst, and SipperFile.SipperFrame.ScanLines.
Referenced by SipperFile.SipperFileBuffered.GetDisplayRows().
int SipperFile.SipperFileBuffered.LargestKnowmFrameNum () inline
Definition at line 35 of file SipperFileBuffered.cs.
References SipperFile.SipperBaseFile.LargestKnowmFrameNum().
long SipperFile.SipperFileBuffered.LargestKnownScanLine () inline
Definition at line 36 of file SipperFileBuffered.cs.
References SipperFile.SipperBaseFile.LargestKnownScanLine().
int SipperFile.SipperFileBuffered.PixelsPerDisLine () inline
Definition at line 37 of file SipperFileBuffered.cs.
float SipperFile.SipperFileBuffered.Ratio () inline
Definition at line 38 of file SipperFileBuffered.cs.
int SipperFile.SipperFileBuffered.ScanColumnFromDisplayCol (int displayColumn) inline
Definition at line 686 of file SipperFileBuffered.cs.
int SipperFile.SipperFileBuffered.ScanLineSize () inline
Definition at line 174 of file SipperFileBuffered.cs.
References SipperFile.SipperBaseFile.ScanLineSize().
void SipperFile.SipperFileBuffered.SetPixelsPerDisplayLine (int _pixelsPerDisLine, int _cropColLeft, int _cropClRight) inline
Definition at line 159 of file SipperFileBuffered.cs.
Property Documentation
bool SipperFile.SipperFileBuffered.EofReached get
Definition at line 43 of file SipperFileBuffered.cs.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperFile/SipperFileBuffered.cs