Pices: KKU::Tokenizer Class Reference
KKU::Tokenizer Class Reference
Class is meant to break down a stream into a set of logical tokens.
#include <Tokenizer.h>
Public Types
typedef KKU::uint32 uint32
Public Member Functions
Tokenizer (TokenBufferPtr _in)
Tokenizer (const KKStr &_str)
Tokenizer (const KKStr &_fileName, bool &_fileOpened)
~Tokenizer ()
bool EndOfFile ()
KKStrPtr GetNextToken ()
KKStrListPtr GetNextTokens (const KKStr &delToken)
Returns a list of tokens up to and including the first occurence of 'delToken'.
KKStrConstPtr operator[] (uint32 idx)
KKStrConstPtr Peek (uint32 idx)
Detailed Description
Class is meant to break down a stream into a set of logical tokens.
Author
Kurt Kramer
This class was originally created while taking Non Linear Systems. It breaks up a source KKStr or text file into logical tokens. You can create your own source of characters by creating a Class derived from MLL::TokenBuffer.
Definition at line 23 of file Tokenizer.h.
Member Typedef Documentation
typedef KKU::uint32 KKU::Tokenizer::uint32
Definition at line 26 of file Tokenizer.h.
Constructor & Destructor Documentation
Tokenizer::Tokenizer (TokenBufferPtr _in)
Definition at line 24 of file Tokenizer.cpp.
Tokenizer::Tokenizer (const KKStr & _str)
Definition at line 38 of file Tokenizer.cpp.
Tokenizer::Tokenizer (const KKStr & _fileName, bool & _fileOpened)
Definition at line 54 of file Tokenizer.cpp.
References KKU::TokenBuffer::Valid().
Tokenizer::~Tokenizer ()
Definition at line 77 of file Tokenizer.cpp.
Member Function Documentation
bool Tokenizer::EndOfFile ()
Definition at line 161 of file Tokenizer.cpp.
Referenced by KKU::XmlStream::GetNextToken().
KKStrPtr Tokenizer::GetNextToken ()
Definition at line 106 of file Tokenizer.cpp.
Referenced by GetNextTokens().
KKStrListPtr Tokenizer::GetNextTokens (const KKStr & delToken)
Returns a list of tokens up to and including the first occurence of 'delToken'.
Will return a list of tokens up to and including the first occurrence if 'delToken'.
Caller will take ownership of the returned tokens, and be responsable for deleting them.
Definition at line 120 of file Tokenizer.cpp.
References KKU::KKStr::Empty(), and GetNextToken().
Referenced by KKU::XmlTag::XmlTag().
KKStrConstPtr Tokenizer::operator[] (uint32 idx)
Definition at line 359 of file Tokenizer.cpp.
References Peek().
KKStrConstPtr Tokenizer::Peek (uint32 idx)
Definition at line 146 of file Tokenizer.cpp.
Referenced by KKU::XmlStream::GetNextToken(), and operator[]().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Tokenizer.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Tokenizer.cpp