Pices: MLL::SipperExtractionImageManager::ManagedClass Class Reference
MLL::SipperExtractionImageManager::ManagedClass Class Reference
Public Member Functions
ManagedClass (FileDescPtr _fileDesc, MLClassConstPtr _mlClass, const KKStr &_rootDir, bool _saveFeatureData, bool _countOnly, uint32 _imagesPerDirectory, RunLog &_log)
~ManagedClass ()
void AddImage (const KKStr &fileName, MLClassConstPtr predClass, int32 size, ImageFeaturesPtr example, RasterPtr raster, bool colorize)
const KKStr & ClassName () const
const KKStr & ClassNameUpper () const
void CloseOutCurDirectory ()
void Flush ()
int32 ImageCount () const
MLClassConstPtr MLClass () const
void SaveFrame (const KKStr &fileName, RasterPtr raster, bool colorize)
void StartNewDirectory ()
Detailed Description
Definition at line 59 of file SipperExtractionImageManager.cpp.
Constructor & Destructor Documentation
MLL::SipperExtractionImageManager::ManagedClass::ManagedClass (FileDescPtr _fileDesc, MLClassConstPtr _mlClass, const KKStr & _rootDir, bool _saveFeatureData, bool _countOnly, uint32 _imagesPerDirectory, RunLog & _log)
Definition at line 450 of file SipperExtractionImageManager.cpp.
MLL::SipperExtractionImageManager::ManagedClass::~ManagedClass ()
Definition at line 479 of file SipperExtractionImageManager.cpp.
References CloseOutCurDirectory().
Member Function Documentation
void MLL::SipperExtractionImageManager::ManagedClass::AddImage (const KKStr & fileName, MLClassConstPtr predClass, int32 size, ImageFeaturesPtr example, RasterPtr raster, bool colorize)
Definition at line 542 of file SipperExtractionImageManager.cpp.
References MLL::FeatureVector::ImageFileName(), KKU::osAddSlash(), KKU::BmpImage::Save(), KKU::BmpImage::SaveGrayscaleInverted4Bit(), and KKU::BmpImage::SetPaletteEntry().
Referenced by MLL::SipperExtractionImageManager::AddImage().
const KKStr & MLL::SipperExtractionImageManager::ManagedClass::ClassName () const
Definition at line 491 of file SipperExtractionImageManager.cpp.
const KKStr & MLL::SipperExtractionImageManager::ManagedClass::ClassNameUpper () const
Definition at line 501 of file SipperExtractionImageManager.cpp.
Referenced by MLL::SipperExtractionImageManager::ManagedClasssesSortByClassName::operator()().
void MLL::SipperExtractionImageManager::ManagedClass::CloseOutCurDirectory ()
Definition at line 609 of file SipperExtractionImageManager.cpp.
References MLL::FeatureFileIOPices::Driver(), MLL::FeatureVector::ImageFileName(), KKU::osAddSlash(), and MLL::FeatureFileIO::SaveFeatureFile().
Referenced by ~ManagedClass().
void MLL::SipperExtractionImageManager::ManagedClass::Flush ()
Definition at line 683 of file SipperExtractionImageManager.cpp.
int32 MLL::SipperExtractionImageManager::ManagedClass::ImageCount () const inline
Definition at line 76 of file SipperExtractionImageManager.cpp.
Referenced by MLL::SipperExtractionImageManager::ClassStats().
MLClassConstPtr MLL::SipperExtractionImageManager::ManagedClass::MLClass () const inline
Definition at line 75 of file SipperExtractionImageManager.cpp.
Referenced by MLL::SipperExtractionImageManager::ClassStats().
void MLL::SipperExtractionImageManager::ManagedClass::SaveFrame (const KKStr & fileName, RasterPtr raster, bool colorize)
Definition at line 655 of file SipperExtractionImageManager.cpp.
References KKU::osAddSlash(), KKU::BmpImage::Save(), and KKU::BmpImage::SetPaletteEntry().
Referenced by MLL::SipperExtractionImageManager::SaveFrame().
void MLL::SipperExtractionImageManager::ManagedClass::StartNewDirectory ()
Definition at line 513 of file SipperExtractionImageManager.cpp.
References KKU::osAddSlash(), KKU::osCreateDirectoryPath(), and KKU::StrFormatInt().
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/SipperExtractionImageManager.cpp