Pices: MLL::DataBaseImageValidatedEntry Class Reference
MLL::DataBaseImageValidatedEntry Class Reference
#include <DataBaseImageValidatedEntry.h>
Public Types
typedef
DataBaseImageValidatedEntry * DataBaseImageValidatedEntryPtr
Public Member Functions
DataBaseImageValidatedEntry (const KKStr &_imageFileName, PointListPtr _sizeCoordinates, MLClassConstPtr _validatedClass)
DataBaseImageValidatedEntry (const KKStr &_imageFileName, const KKStr &_sizeCoordinatesDelStr, MLClassConstPtr _validatedClass)
~DataBaseImageValidatedEntry ()
const KKStr & ImageFileName () const
float ImageSize (float heightFactor, float widthFactor) const
const PointListPtr SizeCoordinates () const
KKStr SizeCoordinatesDelStr () const
MLClassConstPtr ValidatedClass () const
const KKStr & ValidatedClassName () const
Detailed Description
Definition at line 25 of file DataBaseImageValidatedEntry.h.
Member Typedef Documentation
typedef DataBaseImageValidatedEntry* MLL::DataBaseImageValidatedEntry::DataBaseImageValidatedEntryPtr
Definition at line 28 of file DataBaseImageValidatedEntry.h.
Constructor & Destructor Documentation
MLL::DataBaseImageValidatedEntry::DataBaseImageValidatedEntry (const KKStr & _imageFileName, PointListPtr _sizeCoordinates, MLClassConstPtr _validatedClass)
Parameters
_sizeCoordinates Will take ownership of point list
MLL::DataBaseImageValidatedEntry::DataBaseImageValidatedEntry (const KKStr & _imageFileName, const KKStr & _sizeCoordinatesDelStr, MLClassConstPtr _validatedClass)
Parameters
_sizeCoordinatesDelStr Will take ownership of point list
DataBaseImageValidatedEntry::~DataBaseImageValidatedEntry ()
Definition at line 53 of file DataBaseImageValidatedEntry.cpp.
Member Function Documentation
const KKStr& MLL::DataBaseImageValidatedEntry::ImageFileName () const inline
Definition at line 45 of file DataBaseImageValidatedEntry.h.
Referenced by MLL::DataBaseImageValidatedEntryList::Save().
float DataBaseImageValidatedEntry::ImageSize (float heightFactor, float widthFactor) const
Definition at line 80 of file DataBaseImageValidatedEntry.cpp.
References KKU::PointList::ComputeSegmentLens().
const PointListPtr MLL::DataBaseImageValidatedEntry::SizeCoordinates () const inline
Definition at line 46 of file DataBaseImageValidatedEntry.h.
KKStr DataBaseImageValidatedEntry::SizeCoordinatesDelStr () const
Definition at line 70 of file DataBaseImageValidatedEntry.cpp.
References KKU::PointList::ToDelStr().
Referenced by MLL::DataBaseImageValidatedEntryList::Save().
MLClassConstPtr MLL::DataBaseImageValidatedEntry::ValidatedClass () const inline
Definition at line 48 of file DataBaseImageValidatedEntry.h.
const KKStr & DataBaseImageValidatedEntry::ValidatedClassName () const
Definition at line 60 of file DataBaseImageValidatedEntry.cpp.
Referenced by MLL::DataBaseImageValidatedEntryList::Save().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/DataBaseImageValidatedEntry.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/DataBaseImageValidatedEntry.cpp