Pices: MLL::BitReduction Class Reference
MLL::BitReduction Class Reference
This class is responsible for performing tBit reduction compression of FeatureVector lists.
#include <BitReduction.h>
Classes
struct FeatureVar
class FeatureVarComparrison
class FeatureVarList
Public Types
typedef KKU::uint32 uint32
typedef KKU::ulong ulong
Public Member Functions
BitReduction (const SVMparam &_param, FileDescPtr _fileDesc, const FeatureNumList &_selectedFeatures, RunLog &_log)
~BitReduction ()
CompressionStats compress (const FeatureVectorList &examples, FeatureVectorListPtr compressed_example_list, const ClassAssignments &classAssignments)
Performs compression of 'examples' using bit reduction.
float CompressOneFeature (VectorInt32 &featureData, int32 bits)
void DeleteHistogram ()
void output_nominal_counts ()
void ReportBitreductionByFeature (ostream &o)
vector< vector< KKStr > > * TakeExampleGroups ()
Detailed Description
This class is responsible for performing tBit reduction compression of FeatureVector lists.
See
Definition at line 57 of file BitReduction.h.
Member Typedef Documentation
typedef KKU::uint32 MLL::BitReduction::uint32
Definition at line 60 of file BitReduction.h.
typedef KKU::ulong MLL::BitReduction::ulong
Definition at line 61 of file BitReduction.h.
Constructor & Destructor Documentation
BitReduction::BitReduction (const SVMparam & _param, FileDescPtr _fileDesc, const FeatureNumList & _selectedFeatures, RunLog & _log)
Definition at line 25 of file BitReduction.cpp.
References MLL::SVMparam::EncodingMethod().
BitReduction::~BitReduction ()
Definition at line 55 of file BitReduction.cpp.
References DeleteHistogram().
Member Function Documentation
CompressionStats BitReduction::compress (const FeatureVectorList & examples, FeatureVectorListPtr compressed_example_list, const ClassAssignments & classAssignments)
Performs compression of 'examples' using bit reduction.
Parameters
[in] examples List of feature vectors that are to be compressed.
[out] compressed_example_list The feature vector list container to hold compressed examples.
[in] classAssignments A list of classes and how they are to be grouped.
Returns
The compression statistics.
Definition at line 170 of file BitReduction.cpp.
References MLL::CompressionStats::bitReductionByFeature, MLL::BRunBalancedSpecified, MLL::BRunBalancedVariance, MLL::CompressionStats::compression_ratio, MLL::SVMparam::CompressionMethod(), MLL::FileDesc::CreateAttributeTypeTable(), MLL::FileDesc::CreateCardinalityTable(), MLL::ChainHash< T >::DoSomeStats(), MLL::CompressionStats::elapsed_cpu_time, MLL::FeatureVectorList::FileDesc(), MLL::FeatureVectorList::FileName(), MLL::ChainHash< T >::getBucketList(), MLL::ClassAssignments::GetNumForClass(), MLL::ChainHash< T >::insert(), MLL::FeatureVector::MLClass(), MLL::CompressionStats::num_images_after, MLL::CompressionStats::num_images_before, MLL::FeatureNumList::NumOfFeatures(), MLL::FileDesc::NumOfFields(), KKU::osGetSystemTimeUsed(), KKU::osRemoveExtension(), MLL::FeatureVectorList::PushOnBack(), MLL::ChainHashNode::SetBitsToReduceByFeature(), MLL::ChainHashNode::SetFeatureTypes(), MLL::ChainHashNode::setHashSize(), MLL::ChainHashNode::setLength(), MLL::ChainHashNode::SetSelectedFeatures(), MLL::FeatureVector::TrainWeight(), and MLL::CompressionStats::unBalFeatures.
float BitReduction::CompressOneFeature (VectorInt32 & featureData, int32 bits)
Definition at line 923 of file BitReduction.cpp.
References x.
void BitReduction::DeleteHistogram ()
Definition at line 68 of file BitReduction.cpp.
References MLL::FileDesc::NumOfFields(), and x.
Referenced by ~BitReduction().
void BitReduction::output_nominal_counts ()
Definition at line 486 of file BitReduction.cpp.
References MLL::FileDesc::Cardinality(), KKU::endl(), MLL::NominalAttribute, MLL::FileDesc::NumOfFields(), MLL::SymbolicAttribute, and MLL::FileDesc::Type().
void MLL::BitReduction::ReportBitreductionByFeature (ostream & o)
vector< vector <KKStr > >* MLL::BitReduction::TakeExampleGroups () inline
Definition at line 90 of file BitReduction.h.
References x.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/BitReduction.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/BitReduction.cpp