Pices: PicesInterface::PicesPoint Class Reference
PicesInterface::PicesPoint Class Reference
#include <PicesPoint.h>
Public Member Functions
PicesPoint (PicesPoint^ p)
PicesPoint (int _row, int _col)
PicesPoint (PointPtr p)
PicesPoint (Drawing::Point^ p)
PicesPoint (const KKU::Point &p)
!PicesPoint ()
~PicesPoint ()
bool Equal (PicesPoint^ right)
bool NotEqual (PicesPoint^ right)
Properties
int Col [get, set]
int Row [get, set]
Detailed Description
Definition at line 19 of file PicesPoint.h.
Constructor & Destructor Documentation
PicesInterface::PicesPoint::PicesPoint (PicesPoint^ p)
Definition at line 40 of file PicesPoint.cpp.
Referenced by ~PicesPoint().
PicesInterface::PicesPoint::PicesPoint (int _row, int _col)
Definition at line 48 of file PicesPoint.cpp.
PicesInterface::PicesPoint::PicesPoint (PointPtr p)
Definition at line 57 of file PicesPoint.cpp.
References KKU::Point::Col(), and KKU::Point::Row().
PicesInterface::PicesPoint::PicesPoint (Drawing::Point^ p)
Definition at line 68 of file PicesPoint.cpp.
PicesInterface::PicesPoint::PicesPoint (const KKU::Point & p)
Definition at line 77 of file PicesPoint.cpp.
PicesInterface::PicesPoint::!PicesPoint ()
Definition at line 84 of file PicesPoint.cpp.
PicesInterface::PicesPoint::~PicesPoint ()
Definition at line 90 of file PicesPoint.cpp.
References PicesPoint().
Member Function Documentation
bool PicesInterface::PicesPoint::Equal (PicesPoint^ right)
Definition at line 96 of file PicesPoint.cpp.
bool PicesInterface::PicesPoint::NotEqual (PicesPoint^ right)
Definition at line 102 of file PicesPoint.cpp.
Property Documentation
int PicesInterface::PicesPoint::Col get set
Definition at line 41 of file PicesPoint.h.
Referenced by PicesInterface::PicesPointList::ComputeSegmentLens(), and PicesInterface::PicesPointList::ToUnmanaged().
int PicesInterface::PicesPoint::Row get set
Definition at line 40 of file PicesPoint.h.
Referenced by PicesInterface::PicesPointList::ComputeSegmentLens(), and PicesInterface::PicesPointList::ToUnmanaged().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesPoint.h
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesPoint.cpp