Pices: MLL::ModelSvmBase Class Reference
MLL::ModelSvmBase Class Reference
#include <ModelSvmBase.h>
Public Types
typedef ModelSvmBase * ModelSvmBasePtr
Public Types inherited from MLL::Model
typedef Model * ModelPtr
enum ModelTypes {
mtNULL = 0, mtOldSVM = 1, mtSvmBase = 2, mtKNN = 3,
mtUsfCasCor = 4, mtDual = 5
}
Public Member Functions
ModelSvmBase (FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
ModelSvmBase (const KKStr &_name, const ModelParamSvmBase &_param, FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
ModelSvmBase (const ModelSvmBase &_model)
virtual ~ModelSvmBase ()
Frees any memory allocated by, and owned by the ModelSvmBase.
virtual KKStr Description () const
Return short user readable description of model.
virtual ModelSvmBasePtr Duplicate () const
virtual int32 MemoryConsumedEstimated () const
virtual ModelTypes ModelType () const
virtual int32 NumOfSupportVectors () const
ModelParamSvmBasePtr Param ()
virtual MLClassConstPtr Predict (FeatureVectorPtr image)
virtual void Predict (FeatureVectorPtr example, MLClassConstPtr knownClass, MLClassConstPtr &predClass1, MLClassConstPtr &predClass2, int32 &predClass1Votes, int32 &predClass2Votes, double &probOfKnownClass, double &predClass1Prob, double &predClass2Prob, double &compact, int32 &numOfWinners, bool &knownClassOneOfTheWinners, double &breakTie)
virtual ClassProbListPtr ProbabilitiesByClass (FeatureVectorPtr example)
virtual void ProbabilitiesByClass (FeatureVectorPtr example, const MLClassConstList &_mlClasses, int32 *_votes, double *_probabilities)
virtual void ProbabilitiesByClass (FeatureVectorPtr _example, const MLClassConstList &_mlClasses, double *_probabilities)
Derives predicted probabilities by class.
virtual void ReadSpecificImplementationXML (istream &i, bool &_successful)
virtual void RetrieveCrossProbTable (MLClassConstList &classes, double **crossProbTable)
virtual void TrainModel (FeatureVectorListPtr _trainExamples, bool _alreadyNormalized, bool _takeOwnership)
Performs operations such as BitReduction, FeatureEncoding, and Normailization.
virtual void WriteSpecificImplementationXML (ostream &o)
Public Member Functions inherited from MLL::Model
Model (FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
Use this when you are planning on creating a empty model without parameters.
Model (const KKStr &_name, const ModelParam &_param, FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
Construct a instance of 'Model' using the parameters specified in '_param'.
Model (const Model &_madel)
Copy Constructor.
virtual ~Model ()
Frees any memory allocated by, and owned by the Model.
bool AlreadyNormalized () const
const KKStr & BitReductionByFeature () const
int32 BitsToReduceBy () const
const CompressionStats & Compression_Stats () const
const FeatureEncoder2 & Encoder () const
virtual const FeatureNumList & GetFeatureNums () const
void Load (const KKStr &_rootFileName, bool &_successful)
virtual KKStr ModelTypeStr () const
const KKStr & Name () const
void Name (const KKStr &_name)
virtual bool NormalizeNominalAttributes () const
Return true, if nominal fields need to be normalized.
ModelParamPtr Param () const
virtual FeatureVectorPtr PrepExampleForPrediction (FeatureVectorPtr fv, bool &newExampleCreated)
Every prediction method in every class that is inherited from this class should call this method before performing there prediction.
virtual void ProbabilitiesByClassDual (FeatureVectorPtr example, KKStr &classifier1Desc, KKStr &classifier2Desc, ClassProbListPtr &classifier1Results, ClassProbListPtr &classifier2Results)
Only applied to ModelDual classifier.
virtual void ReadXML (istream &i, bool &_successful)
Expects to read in the entire contents of a previously trainied model into this instance.
int32 ReductionPostExampleCount () const
int32 ReductionPreExampleCount () const
float ReductionRatio () const
double ReductionTime () const
const KKStr & RootFileName () const
void RootFileName (const KKStr &_rootFileName)
void Save (const KKStr &_rootFileName, bool &_successful)
virtual const FeatureNumList & SelectedFeatures () const
const KKU::DateTime & TimeSaved () const
double TrainingTime () const
void TrainingTimeEnd ()
Derived classes call this method to stop the clock for 'trainingTime'.
void TrainingTimeStart ()
Derived classes call this method to start the clock for 'trainingTime'.
double TrianingPrepTime () const
bool ValidModel () const
virtual void WriteXML (ostream &o)
Protected Attributes
ModelParamSvmBasePtr param
We will NOT own this instance.
SVM289_MFS::svm_model * svmModel
Protected Attributes inherited from MLL::Model
bool alreadyNormalized
volatile const bool & cancelFlag
MLClassConstListPtr classes
ClassIndexListPtr classesIndex
double * classProbs
CompressionStats compression_stats
double ** crossClassProbTable
Probabilities between Binary Classes From last Prediction.
int32 crossClassProbTableSize
FeatureEncoder2Ptr encoder
FileDescPtr fileDesc
RunLog & log
NormalizationParmsPtr normParms
int32 numOfClasses
Number of Classes defined in crossClassProbTable.
ModelParamPtr param
Will own this instance.
KKStr rootFileName
This is the root name to be used by all component objects; such as svm_model, mlClasses, and svmParam(including selected features).
FeatureVectorListPtr trainExamples
bool validModel
int32 * votes
bool weOwnTrainExamples
Indicates if we own the 'trainExamples'.
Additional Inherited Members
Static Public Member Functions inherited from MLL::Model
static ModelPtr CreateAModel (ModelTypes _modelType, const KKStr &_name, const ModelParam &_param, FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
A factory method that will instantiate the appropriate class of training model based off '_modelType'.
static ModelPtr CreateFromStream (istream &i, FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
A factory method that will instantiate the appropriate class of training model based off the contents of the istream "i".
static ModelTypes ModelTypeFromStr (const KKStr &_modelingTypeStr)
static KKStr ModelTypeToStr (ModelTypes _modelingType)
Protected Member Functions inherited from MLL::Model
void AllocatePredictionVariables ()
void DeAllocateSpace ()
void Read (istream &i, bool &_successful)
void ReadSkipToSection (istream &i, KKStr sectName, bool &sectionFound)
void ReduceTrainExamples ()
Reduces the Training Images down to the size dictated by the 'examplesPerClass' parameter.
Detailed Description
Definition at line 22 of file ModelSvmBase.h.
Member Typedef Documentation
typedef ModelSvmBase* MLL::ModelSvmBase::ModelSvmBasePtr
Definition at line 26 of file ModelSvmBase.h.
Constructor & Destructor Documentation
MLL::ModelSvmBase::ModelSvmBase (FileDescPtr _fileDesc, volatile const bool & _cancelFlag, RunLog & _log)
Referenced by Duplicate().
MLL::ModelSvmBase::ModelSvmBase (const KKStr & _name, const ModelParamSvmBase & _param, FileDescPtr _fileDesc, volatile const bool & _cancelFlag, RunLog & _log)
ModelSvmBase::ModelSvmBase (const ModelSvmBase & _model)
Definition at line 60 of file ModelSvmBase.cpp.
References MLL::Model::fileDesc, MLL::Model::log, param, MLL::Model::param, and svmModel.
ModelSvmBase::~ModelSvmBase () virtual
Frees any memory allocated by, and owned by the ModelSvmBase.
Definition at line 79 of file ModelSvmBase.cpp.
References SVM233::svm_destroy_model(), and svmModel.
Member Function Documentation
KKStr ModelSvmBase::Description () const virtual
Return short user readable description of model.
Reimplemented from MLL::Model.
Definition at line 112 of file ModelSvmBase.cpp.
References MLL::Model::Name(), param, and MLL::ModelParamSvmBase::SvmParam().
ModelSvmBasePtr ModelSvmBase::Duplicate () const virtual
Implements MLL::Model.
Definition at line 104 of file ModelSvmBase.cpp.
References ModelSvmBase().
int32 ModelSvmBase::MemoryConsumedEstimated () const virtual
Reimplemented from MLL::Model.
Definition at line 92 of file ModelSvmBase.cpp.
References SVM289_MFS::svm_model::MemoryConsumedEstimated(), MLL::Model::MemoryConsumedEstimated(), and svmModel.
virtual ModelTypes MLL::ModelSvmBase::ModelType () const inline virtual
Implements MLL::Model.
Definition at line 55 of file ModelSvmBase.h.
References MLL::Model::mtSvmBase.
int32 ModelSvmBase::NumOfSupportVectors () const virtual
Definition at line 653 of file ModelSvmBase.cpp.
References SVM289_MFS::svm_model::l, and svmModel.
ModelParamSvmBasePtr ModelSvmBase::Param ()
Definition at line 128 of file ModelSvmBase.cpp.
References param.
MLClassConstPtr ModelSvmBase::Predict (FeatureVectorPtr image) virtual
Implements MLL::Model.
Definition at line 242 of file ModelSvmBase.cpp.
References MLL::Model::classesIndex, KKU::endl(), MLL::ClassIndexList::GetMLClass(), KKU::RunLog::Level(), MLL::Model::log, MLL::Model::PrepExampleForPrediction(), SVM289_MFS::svm_predict(), and svmModel.
virtual void MLL::ModelSvmBase::Predict (FeatureVectorPtr example, MLClassConstPtr knownClass, MLClassConstPtr & predClass1, MLClassConstPtr & predClass2, int32 & predClass1Votes, int32 & predClass2Votes, double & probOfKnownClass, double & predClass1Prob, double & predClass2Prob, double & compact, int32 & numOfWinners, bool & knownClassOneOfTheWinners, double & breakTie) virtual
Implements MLL::Model.
ClassProbListPtr ModelSvmBase::ProbabilitiesByClass (FeatureVectorPtr example) virtual
Implements MLL::Model.
Definition at line 387 of file ModelSvmBase.cpp.
References MLL::Model::classesIndex, MLL::Model::classProbs, KKU::endl(), MLL::ClassIndexList::GetMLClass(), KKU::RunLog::Level(), MLL::Model::log, MLL::Model::numOfClasses, MLL::Model::PrepExampleForPrediction(), MLL::ClassProbList::SortByVotes(), SVM289_MFS::svm_predict_probability(), svmModel, and MLL::Model::votes.
virtual void MLL::ModelSvmBase::ProbabilitiesByClass (FeatureVectorPtr example, const MLClassConstList & _mlClasses, int32 * _votes, double * _probabilities) virtual
Implements MLL::Model.
void ModelSvmBase::ProbabilitiesByClass (FeatureVectorPtr _example, const MLClassConstList & _mlClasses, double * _probabilities) virtual
Derives predicted probabilities by class.
Will get the probabilities assigned to each class by the classifier. The '_mlClasses' parameter dictates the order of the classes. That is the probabilities for any goven index in '_probabilities' will be for the class specifid in the same index in '_mlClasses'.
Parameters
[in] _example FeatureVector object to calculate predivcted probabilities for.
[in] _mlClasses List image classes that caller is aware of. This should be the same list that was used when consttructing this Model object. The list must be the same but not nessasarily in the same order as when Model was 1st constructed.
[out] _probabilities An array that must be as big as the number of classes as in mlClasses. The probability of class in mlClasses[x] will be returned in probabilities[x].
Implements MLL::Model.
Definition at line 485 of file ModelSvmBase.cpp.
References MLL::Model::classesIndex, MLL::Model::classProbs, KKU::endl(), MLL::ClassIndexList::GetClassIndex(), KKU::RunLog::Level(), MLL::Model::log, MLL::Model::PrepExampleForPrediction(), SVM289_MFS::svm_predict_probability(), svmModel, and MLL::Model::votes.
void ModelSvmBase::ReadSpecificImplementationXML (istream & i, bool & _successful) virtual
Todo:
Make sure that 'param' != NULL
Implements MLL::Model.
Definition at line 570 of file ModelSvmBase.cpp.
References KKU::endl(), KKU::KKStr::EqualIgnoreCase(), KKU::KKStr::ExtractQuotedStr(), MLL::Model::fileDesc, KKU::RunLog::Level(), MLL::Model::log, param, MLL::Model::param, MLL::Model::ReadXML(), SVM289_MFS::svm_load_model_XML(), svmModel, KKU::KKStr::Upper(), and MLL::Model::validModel.
void ModelSvmBase::RetrieveCrossProbTable (MLClassConstList & classes, double ** crossProbTable) virtual
Reimplemented from MLL::Model.
Definition at line 532 of file ModelSvmBase.cpp.
References MLL::Model::classesIndex, MLL::ClassIndexList::GetClassIndex(), SVM289_MFS::svm_model::PairwiseProb(), and svmModel.
void ModelSvmBase::TrainModel (FeatureVectorListPtr _trainExamples, bool _alreadyNormalized, bool _takeOwnership) virtual
Performs operations such as BitReduction, FeatureEncoding, and Normailization.
The actual training of models occurs in the specific implementation of 'Model'.
Parameters
_takeOwnership Model will take ownership of these examples
Reimplemented from MLL::Model.
Definition at line 135 of file ModelSvmBase.cpp.
References MLL::Model::classesIndex, KKU::endl(), MLL::ModelParam::FileName(), MLL::ClassIndexList::GetClassIndex(), KKU::RunLog::Level(), MLL::Model::log, param, MLL::Model::rootFileName, MLL::ModelParam::SelectedFeatures(), SVM233::svm_destroy_model(), SVM289_MFS::svm_train(), svmModel, MLL::ModelParamSvmBase::SvmParam(), KKU::KKStrException::ToString(), MLL::Model::trainExamples, MLL::Model::TrainingTimeEnd(), MLL::Model::TrainingTimeStart(), MLL::Model::TrainModel(), and MLL::Model::validModel.
void ModelSvmBase::WriteSpecificImplementationXML (ostream & o) virtual
Implements MLL::Model.
Definition at line 637 of file ModelSvmBase.cpp.
References KKU::endl(), KKU::RunLog::Level(), MLL::Model::log, SVM289_MFS::svm_save_model_XML(), and svmModel.
Member Data Documentation
ModelParamSvmBasePtr MLL::ModelSvmBase::param protected
We will NOT own this instance.
It will point to same instance defined in parent class Model.
Definition at line 139 of file ModelSvmBase.h.
Referenced by Description(), ModelSvmBase(), Param(), ReadSpecificImplementationXML(), and TrainModel().
SVM289_MFS::svm_model* MLL::ModelSvmBase::svmModel protected
Definition at line 138 of file ModelSvmBase.h.
Referenced by MemoryConsumedEstimated(), ModelSvmBase(), NumOfSupportVectors(), Predict(), ProbabilitiesByClass(), ReadSpecificImplementationXML(), RetrieveCrossProbTable(), TrainModel(), WriteSpecificImplementationXML(), and ~ModelSvmBase().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ModelSvmBase.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ModelSvmBase.cpp