Pices: KKU::Compressor Class Reference
KKU::Compressor Class Reference
Simple class that will compress and decompress specified buffers using the routines provided in zlib.
#include <Compressor.h>
Static Public Member Functions
static void * CreateCompressedBuffer (void *source, uint32 sourceLen, uint32 &compressedBuffLen)
static void * Decompress (const void *compressedBuff, uint32 compressedBuffLen, uint32 &unCompressedLen)
Detailed Description
Simple class that will compress and decompress specified buffers using the routines provided in zlib.
Author
Kurt Kramer
Definition at line 17 of file Compressor.h.
Member Function Documentation
void * Compressor::CreateCompressedBuffer (void * source, uint32 sourceLen, uint32 & compressedBuffLen) static
Definition at line 21 of file Compressor.cpp.
References KKU::endl().
Referenced by KKU::Raster::ToCompressor().
void * Compressor::Decompress (const void * compressedBuff, uint32 compressedBuffLen, uint32 & unCompressedLen) static
Definition at line 137 of file Compressor.cpp.
References KKU::endl().
Referenced by KKU::RasterSipper::FromCompressor().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Compressor.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Compressor.cpp