Pices: KKU::Application Class Reference
KKU::Application Class Reference
The base class for all standalone application.
#include <Application.h>
Public Member Functions
Application (const Application &_application)
Copy Constructor for Application class.
Application (RunLog &_log)
Constructor for Application class with no parameters.
Application (int32 argc, char **argv)
Constructor for Application class that expects Command Line Parameters.
virtual ~Application ()
bool Abort ()
Returns 'true' if application has been aborted.
void Abort (bool _abort)
Used to specify that the application is been aborted.
virtual const char * ApplicationName ()
Specify the name of the application.
void AssignLog (RunLog &_log)
Replaces the Log file to write to.
KKStr BuildDate () const
virtual bool ProcessCmdLineParameter (char parmSwitchCode, KKStr parmSwitch, KKStr parmValue)
This method will get called once for each parameter specified in the command line.
void ProcessCmdLineParameters (int32 argc, char **argv)
Processes all the command line parameters; will also expand the -CmdFile option.
Public Attributes
RunLog & log
Detailed Description
The base class for all standalone application.
This class is meant to be a general class that all standalone applications should be inherited from. It supports command line processing, and logging facilities.
Definition at line 39 of file Application.h.
Constructor & Destructor Documentation
Application::Application (const Application & _application)
Copy Constructor for Application class.
Parameters
[in] _application Application instance to copy.
Definition at line 55 of file Application.cpp.
Application::Application (RunLog & _log)
Constructor for Application class with no parameters.
This constructor is not interested in any command line parameters.
Parameters
[in] _log A reference to a RunLog object.
Definition at line 27 of file Application.cpp.
Application::Application (int32 argc, char ** argv)
Constructor for Application class that expects Command Line Parameters.
This constructor will scan the command line parameters for the log file options (-L, -Log, or -LogFile) and use its parameter as the LogFile name. If none is provided it will assume the stdout as the Log File to write to. It will take ownership of this log file and delete it in its destructor. Right after calling this constructor you will need to call the method ProcessCmdLineParameters.
See Also
RunLog
ProcessCmdLineParameters
Parameters
[in] argc Number of arguments in argv.
[in] argv List of asciiz strings; one string for each argument.
Definition at line 37 of file Application.cpp.
References KKU::RunLog::AttachFile(), KKU::KKStr::Empty(), log, and ProcessCmdLineParameters().
Application::~Application () virtual
Definition at line 66 of file Application.cpp.
Member Function Documentation
bool KKU::Application::Abort () inline
Returns 'true' if application has been aborted.
You would typically call this method after you are done processing the command line to make sure that the application is to keep on running.
Definition at line 80 of file Application.h.
Referenced by ProcessCmdLineParameters().
void KKU::Application::Abort (bool _abort) inline
Used to specify that the application is been aborted.
If you have a reason to abort the processing of this application you would call this method to set the 'abort' flag to true.
Parameters
[in] _abort Abort status to set; if set to true you are telling the application that the program needs to be terminated.
Definition at line 88 of file Application.h.
const char * Application::ApplicationName () virtual
Specify the name of the application.
Definition at line 73 of file Application.cpp.
Referenced by ProcessCmdLineParameters().
void Application::AssignLog (RunLog & _log)
Replaces the Log file to write to.
Definition at line 80 of file Application.cpp.
References log.
KKStr Application::BuildDate () const
Definition at line 190 of file Application.cpp.
References KKU::TimeType::HH_MM_SS(), and KKU::DateType::YYYY_MM_DD().
bool Application::ProcessCmdLineParameter (char parmSwitchCode, KKStr parmSwitch, KKStr parmValue) virtual
This method will get called once for each parameter specified in the command line.
Derived classes should define this method to intercept parameters that they are interested in. Parameters are treated as pairs, Switched and Values where switches have a leading dash("-"). The CmdLineExpander class will be used to expand any "-CmdFile" parameters.
Parameters
[in] parmSwitchCode The first character of the switch parameter.
[in] parmSwitch The fill switch parameter.
[in] parmValue Any value parameter that followed the switch parameter.
Definition at line 179 of file Application.cpp.
Referenced by ProcessCmdLineParameters().
void Application::ProcessCmdLineParameters (int32 argc, char ** argv)
Processes all the command line parameters; will also expand the -CmdFile option.
This method assumes that the command line consists of pairs of Switches and Operands. Switches are proceeded by the dash character("-"). For each pair it will call the 'ProcessCmdLineParameter' method which should be implemented by the derived class. Before calling 'ProcessCmdLineParameter' though it will scan the parameters for the "-CmdFile" switch. This switch specifies a text file that is to be read for additional command parameters.
Parameters
[in] argc Number of parameters.
[in] argv The actual parameters.
Definition at line 94 of file Application.cpp.
References Abort(), ApplicationName(), KKU::KKStr::Empty(), KKU::CmdLineExpander::ExpandedParameters(), log, KKU::CmdLineExpander::LogFileName(), KKU::CmdLineExpander::ParmsGood(), ProcessCmdLineParameter(), KKU::KKStr::ToUpper(), and x.
Referenced by Application().
Member Data Documentation
RunLog& KKU::Application::log
Definition at line 153 of file Application.h.
Referenced by Application(), AssignLog(), and ProcessCmdLineParameters().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Application.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Application.cpp