Pices: PicesCommander.ClassificationStatus Class Reference
PicesCommander.ClassificationStatus Class Reference
Public Member Functions
ClassificationStatus (PicesCommander _manager, PicesDataBaseImageGroup _imageGroup, String _cruiseName, String _stationName, String _deploymentNum, String _sipperFileName, PicesClass _currentClass, char _classKeyToUse, int _sizeMin, int _sizeMax, float _depthMin, float _depthMax, float _probMin, float _probMax)
void CleanUpMemory ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Detailed Description
Developer: Kurt Kramer *
Date 2009-Jan *
*
My purpose in life is to Classify Images that meet specified criteria using *
the current active TrainingModel2. The user can opt to just generate the *
classification report using current class assignments. *
*
Validated Class always trumps Predicted Class. *
Definition at line 30 of file ClassificationStatus.cs.
Constructor & Destructor Documentation
PicesCommander.ClassificationStatus.ClassificationStatus (PicesCommander _manager, PicesDataBaseImageGroup _imageGroup, String _cruiseName, String _stationName, String _deploymentNum, String _sipperFileName, PicesClass _currentClass, char _classKeyToUse, int _sizeMin, int _sizeMax, float _depthMin, float _depthMax, float _probMin, float _probMax) inline
Definition at line 128 of file ClassificationStatus.cs.
References PicesInterface::PicesSipperVariables.AllowUpdates(), PicesInterface::TrainingModel2.ConfigFileName, PicesInterface::ClassificationBiasMatrix.DateTimeFileWritten, PicesInterface::PicesDataBase.GetGlobalDatabaseManagerNewInstance(), PicesInterface::TrainingModel2.MLClasses(), SipperFile.ActiveTrainingLibraries.Model1(), SipperFile.ActiveTrainingLibraries.ModelsAreLoading(), PicesInterface::PicesDataBaseImageGroup.Name, PicesInterface::PicesClass.Name, and PicesInterface::TrainingModel2.Valid.
Member Function Documentation
void PicesCommander.ClassificationStatus.CleanUpMemory () inline
Definition at line 245 of file ClassificationStatus.cs.
override void PicesCommander.ClassificationStatus.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file ClassificationStatus.Designer.cs.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/Apps/PicesCommander/ClassificationStatus.cs
D:/Users/kkramer/IEC/SipperSoftware/Apps/PicesCommander/ClassificationStatus.Designer.cs