Pices: SipperDiskUtilities.SipperDisk Class Reference
SipperDiskUtilities.SipperDisk Class Reference
SipperDisk is used for reading and writting to a SIPPER disk drive.
Public Member Functions
SipperDisk (bool _readDirFromLogFiles)
bool AreWeTheSameDrive ()
void BlockEnd ()
void BlockStart ()
void CloseSipperDiskFile (SipperDiskFile sdf)
void Dispose ()
int FSread (byte[] buff, int offSet, int count)
long FSseek (long diskPosition, SeekOrigin so)
PartitionTableEntry GetSipperPartitionTableEntry ()
SipperDiskFile OpenSipperDiskFile (string _fileName)
SipperDiskFile OpenSipperDiskFile (int fcbIndex)
void ResetSipperDirectory ()
SipperFileControlBlockList SipperFiles ()
int SipperFilesOpenedCount ()
Properties
long DiskSizeBytes [get]
long FSposition [get]
int PhysicalDriveNumber [get]
long TotalBytesUsed [get]
long TotalFreeDiskSectors [get]
long TotalSectorsUsed [get]
bool ValidSipperDrive [get]
Detailed Description
SipperDisk is used for reading and writting to a SIPPER disk drive.
The SIPPER disk has a very simple format who's details are described below. You read the Master Boot record and get the 1st sector from "Partition Entry 1". The SIPPER Partition will start with one Partition decriptive block followed by 2048 File Control Block, on efor each SIPPER file created. The File control blocks will be followed by the actual SIPPER data. SIPPER records data sequentially starting at the begiining of the drive until the end of the drive. There will be not fragmentation issues to deal with. Each SIPPER file will have a start and end sector that is specified in its corresponding File Control Block.
See Also
SipperDiskUtilities.PartitionTable
SipperDiskUtilities.SipperFileControlBlock
SipperDiskUtilities.SipperDiskFile
Sipper Disk Drive Layout
 Master Boot Record
  |Boot-Record-Code  (0-445)
  |
  |Partition-Table
  |  Partition-Entry-0            (446 - 461)
  |      Boot-Id           (446)
  |      Start-Head        (447)
  |      Start-Sector      (448)
  |      Start-Cylinder    (449)
  |      System-ID         (450)
  |      EndHead           (451)
  |      EndSector         (452)
  |      End-Cylinder      (453)
  |      Relative-Sector   (454 - 457)
  |      totalSectors      (458 - 461)
  |
  |  Partition-Entry-1            (462 - 477)     // Sipper will be partition "1".
  |  Partition-Entry-2            (478 - 493)
  |  Partition-Entry-3            (494 - 509)
  |
  |End-Of-Sector                  (510 - 511)
  (**********************************************************)
  (*  Start of Sipper Partition                             *)
  (*  The first sector will be the 'SipperPartitionSector'  *)
  (**********************************************************)
 Sipper-Partition-Sector    Starts at ('Partition-Entry-1'->'Relative-Sector') * 'Logical-Block-Size(512)'
  | Sipper-Id             ( 0 -  11)
  | Total-Sectors         (12 -  15)
  | File-Data-Sector      (16 -  19)
  | End-Sector            (20 -  23)
  | Next-Fcb-Sector       (24 -  27)
  | Next-File-Handle      (28 -  31)
  | Unused-Space          (32 - 511)
  (**********************************************************)
  (*  followed by 2048 'SipperFileControlBlock' sectors.    *)
  (*  where each one represents a single Sipper File.       *)
  (**********************************************************)
 Sipper-File-Control-Block
  | Allocated             ( 0 -  3)
  | Status                ( 4 -  7)     0=Closed,  1=Opened
  | Start-Sector          ( 8 - 11)
  | End-Sector            (12 - 15)
  | Current-Access-Sector (16 - 19)
  | File-Name             (20 - 49)
  |
  | filler                (50 - 51)      For some reason SIPPER is inserting 2 empty bytes here
  |                                      probably beciause it is accessing memory on 4-byte boundaries.
  |
  | Date-Time-Stamp       (52 - 59)
  |     Second                     (52)
  |     Minute                     (53)
  |     Hour                       (54)
  |     Unused                     (55)
  |     Day                        (56)
  |     Date                       (57)  (1 -> 31)
  |     Month                      (58)  (1 -> 12)
  |     Year                       (59)  (0 -> 99)   ex: 7 = 2007.
  |
  | Description           (60 - 364)
  |
  | UnUsed               (365 - 511)
  // Unused Space
Definition at line 111 of file SipperDisk.cs.
Constructor & Destructor Documentation
SipperDiskUtilities.SipperDisk.SipperDisk (bool _readDirFromLogFiles) inline
Definition at line 234 of file SipperDisk.cs.
References SipperDiskUtilities.SipperDisk.BlockEnd(), SipperDiskUtilities.SipperDisk.BlockStart(), and PicesInterface::PicesSipperVariables.SipperInterfaceLogDir().
Member Function Documentation
bool SipperDiskUtilities.SipperDisk.AreWeTheSameDrive () inline
Definition at line 839 of file SipperDisk.cs.
References SipperDiskUtilities.SipperDisk.BlockEnd(), SipperDiskUtilities.SipperDisk.BlockStart(), SipperDiskUtilities.SipperFileControlBlock.CreateFromFileStream(), SipperDiskUtilities.SipperPartitionSector.CreateFromFileStream(), SipperDiskUtilities.SipperPartitionSector.Equals(), SipperDiskUtilities.SipperFileControlBlock.Equals(), SipperDiskUtilities.MasterBootRecord.GetPartitionSectorByteOffset(), and SipperDiskUtilities.Constants.SIPPER_PARTITION.
void SipperDiskUtilities.SipperDisk.BlockEnd () inline
Definition at line 752 of file SipperDisk.cs.
Referenced by SipperDiskUtilities.SipperDisk.AreWeTheSameDrive(), SipperDiskUtilities.SipperDisk.CloseSipperDiskFile(), SipperDiskUtilities.SipperDisk.Dispose(), SipperDiskUtilities.SipperDisk.OpenSipperDiskFile(), SipperDiskUtilities.SipperDiskFile.Read(), SipperDiskUtilities.SipperDisk.SipperDisk(), and SipperDiskUtilities.SipperDisk.SipperFilesOpenedCount().
void SipperDiskUtilities.SipperDisk.BlockStart () inline
Definition at line 723 of file SipperDisk.cs.
Referenced by SipperDiskUtilities.SipperDisk.AreWeTheSameDrive(), SipperDiskUtilities.SipperDisk.CloseSipperDiskFile(), SipperDiskUtilities.SipperDisk.Dispose(), SipperDiskUtilities.SipperDisk.OpenSipperDiskFile(), SipperDiskUtilities.SipperDiskFile.Read(), SipperDiskUtilities.SipperDisk.SipperDisk(), and SipperDiskUtilities.SipperDisk.SipperFilesOpenedCount().
void SipperDiskUtilities.SipperDisk.CloseSipperDiskFile (SipperDiskFile sdf) inline
Definition at line 370 of file SipperDisk.cs.
References SipperDiskUtilities.SipperDisk.BlockEnd(), SipperDiskUtilities.SipperDisk.BlockStart(), and x.
Referenced by SipperDiskUtilities.SipperDiskFile.Close().
void SipperDiskUtilities.SipperDisk.Dispose () inline
Definition at line 275 of file SipperDisk.cs.
References SipperDiskUtilities.SipperDisk.BlockEnd(), SipperDiskUtilities.SipperDisk.BlockStart(), SipperDiskUtilities.SipperDiskFile.Close(), SipperDiskUtilities.SipperDiskFile.Dispose(), and SipperDiskUtilities.MasterBootRecord.Dispose().
int SipperDiskUtilities.SipperDisk.FSread (byte[] buff, int offSet, int count) inline
Definition at line 143 of file SipperDisk.cs.
Referenced by SipperDiskUtilities.SipperDiskFile.Read().
long SipperDiskUtilities.SipperDisk.FSseek (long diskPosition, SeekOrigin so) inline
Definition at line 135 of file SipperDisk.cs.
Referenced by SipperDiskUtilities.SipperDiskFile.Read().
PartitionTableEntry SipperDiskUtilities.SipperDisk.GetSipperPartitionTableEntry () inline
Definition at line 223 of file SipperDisk.cs.
References SipperDiskUtilities.MasterBootRecord.GetSipperPartitionTableEntry().
SipperDiskFile SipperDiskUtilities.SipperDisk.OpenSipperDiskFile (string _fileName) inline
Definition at line 308 of file SipperDisk.cs.
References SipperDiskUtilities.SipperDisk.BlockEnd(), SipperDiskUtilities.SipperDisk.BlockStart(), and SipperDiskUtilities.SipperFileControlBlockList.LookUpByName().
SipperDiskFile SipperDiskUtilities.SipperDisk.OpenSipperDiskFile (int fcbIndex) inline
Definition at line 329 of file SipperDisk.cs.
References SipperDiskUtilities.SipperDisk.BlockEnd(), SipperDiskUtilities.SipperDisk.BlockStart(), and SipperDiskUtilities.SipperFileControlBlockList.LookUpByFcbIndex().
void SipperDiskUtilities.SipperDisk.ResetSipperDirectory () inline
Definition at line 765 of file SipperDisk.cs.
References SipperDiskUtilities.SipperFileControlBlock.Allocated, SipperDiskUtilities.SipperFileControlBlock.FcbIndex, SipperDiskUtilities.SipperPartitionSector.FileDataSector, SipperDiskUtilities.MasterBootRecord.GetSipperDirectoryByteOffset(), SipperDiskUtilities.MasterBootRecord.GetSipperPartitionTableEntry(), SipperDiskUtilities.Constants.MAX_SIPPER_FILES, SipperDiskUtilities.SipperPartitionSector.NextFcbSector, SipperDiskUtilities.SipperPartitionSector.NextFileHandle, SipperDiskUtilities.PartitionTableEntry.RelativeSector, SipperDiskUtilities.SipperFileControlBlock.SIPPER_FILE_CLOSED, SipperDiskUtilities.SipperFileControlBlock.SIPPER_FILE_FREE, SipperDiskUtilities.SipperFileControlBlock.Status, and SipperDiskUtilities.SipperFileControlBlock.Write().
SipperFileControlBlockList SipperDiskUtilities.SipperDisk.SipperFiles () inline
Definition at line 189 of file SipperDisk.cs.
int SipperDiskUtilities.SipperDisk.SipperFilesOpenedCount () inline
Definition at line 192 of file SipperDisk.cs.
References SipperDiskUtilities.SipperDisk.BlockEnd(), and SipperDiskUtilities.SipperDisk.BlockStart().
Property Documentation
long SipperDiskUtilities.SipperDisk.DiskSizeBytes get
Definition at line 178 of file SipperDisk.cs.
long SipperDiskUtilities.SipperDisk.FSposition get
Definition at line 170 of file SipperDisk.cs.
Referenced by SipperDiskUtilities.SipperDiskFile.Read().
int SipperDiskUtilities.SipperDisk.PhysicalDriveNumber get
Definition at line 128 of file SipperDisk.cs.
long SipperDiskUtilities.SipperDisk.TotalBytesUsed get
Definition at line 220 of file SipperDisk.cs.
long SipperDiskUtilities.SipperDisk.TotalFreeDiskSectors get
Definition at line 207 of file SipperDisk.cs.
long SipperDiskUtilities.SipperDisk.TotalSectorsUsed get
Definition at line 216 of file SipperDisk.cs.
bool SipperDiskUtilities.SipperDisk.ValidSipperDrive get
Definition at line 228 of file SipperDisk.cs.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperDiskUtilities/SipperDisk.cs