Pices: KKU::RasterSipper Class Reference
KKU::RasterSipper Class Reference
A class that is used by to represent a single Sipper Image in memory.
#include <RasterSipper.h>
Public Types
typedef RasterSipper * RasterSipperPtr
Public Types inherited from KKU::Raster
typedef Raster * RasterPtr
Public Member Functions
RasterSipper ()
RasterSipper (const RasterSipper &_raster)
Copy Constructor.
RasterSipper (const Raster &_raster)
Copy Constructor.
RasterSipper (int32 _height, int32 _width)
Constructs a blank GrayScale image with given dimensions; all pixels will be initialized to 0.
RasterSipper (int32 _height, int32 _width, bool _color)
Constructs a blank image with given dimensions.
RasterSipper (const BmpImage &_bmpImage)
Constructs a RasterSipper from a BMP image loaded from disk.
RasterSipper (const RasterSipper &_raster, int32 _row, int32 _col, int32 _height, int32 _width)
Constructs a new RasterSipper using a subset of the specified RasterSipper as its source.
RasterSipper (const RasterSipper &_raster, MaskTypes _mask, int32 _row, int32 _col)
Constructs a RasterSipper that will be as large as the specified '_mask' at the point specified by '_row' and '_col'.
RasterSipper (const KKStr &fileName, bool &validFile)
Constructs a RasterSipper image from by reading an existing image File such as a BMP file.
RasterSipper (int32 _height, int32 _width, uchar *_grayScaleData, uchar **_grayScaleRows)
Construct a raster object that will utilize a image already in memory.
RasterSipper (int32 _height, int32 _width, const uchar *_grayScaleData)
Construct a Grayscale RasterSipper object using provided raw data,.
RasterSipper (int32 _height, int32 _width, const uchar *_redChannel, const uchar *_greenChannel, const uchar *_blueChannel)
Construct a Color RasterSipper object using provided raw data,.
virtual ~RasterSipper ()
virtual RasterPtr AllocateARasterInstance (int32 height, int32 width, bool color) const
virtual RasterPtr AllocateARasterInstance (const Raster &r) const
virtual RasterPtr AllocateARasterInstance (const Raster &_raster, int32 _row, int32 _col, int32 _height, int32 _width)
RasterSipperPtr BandPass (float lowerFreqBound, float upperFreqBound)
Returns a image that is the result of a BandPass using Fourier Transforms.
RasterSipperPtr BinarizeByThreshold (uchar min, uchar max)
RasterSipperPtr CreateColorImageFromLabels ()
RasterSipperPtr CreateColorWithBlobsLabeldByColor (BlobListPtr blobs)
Only useful if 'ExtractBlobs' was performed on this instance, the returned image will be color with each blob labeled a different color.
RasterSipperPtr CreateDialatedRaster () const
RasterSipperPtr CreateDialatedRaster (MaskTypes mask) const
RasterSipperPtr CreateErodedImage (MaskTypes mask) const
RasterSipperPtr CreateFromOrginalImageWithSpecifidBlobsOnly (RasterSipperPtr origImage, BlobListPtr blobs)
Returns a copy of 'origImage' where only the blobs specified in 'blobs' are copied over.
RasterSipperPtr CreateGaussianSmoothedImage (float sigma) const
RasterSipperPtr CreateGrayScale () const
RasterSipperPtr CreateGrayScaleKLT () const
Creates a grayscale image using a KLT Transform with the goal of weighting in favor the color channels with greatest amount of variance.
RasterSipperPtr CreateGrayScaleKLTOnMaskedArea (const RasterSipper &mask) const
Same as 'CreateGrayScaleKLT' except it will only take into account pixels specified by the 'mask' image.
RasterSipperPtr CreateSmoothedMediumImage (int32 maskSize) const
RasterSipperPtr CreateSmoothImage (int32 maskSize=3) const
PointListPtr DeriveImageLength () const
RasterSipperPtr ExtractABlob (const BlobPtr blob) const
Extracts a specified blob from this image; useful to extract individual detected blobs.
RasterSipperPtr ExtractABlobTightly (const BlobPtr blob, int32 padding) const
Extracts a specified blob from this image into a tightly bounded image.
RasterSipperPtr ExtractChannel (ColorChannels channel)
Will return a grayscale image consisting of the specified color channel only.
RasterSipperPtr FastFourier () const
RasterSipperPtr FastFourierKK () const
RasterSipperPtr HalfSize ()
RasterSipperPtr HistogramEqualizedImage () const
RasterSipperPtr HistogramEqualizedImage (HistogramPtr equalizedHistogram) const
RasterSipperPtr HistogramGrayscaleImage () const
RasterSipperPtr HistogramImage (ColorChannels channel) const
int32 MemoryConsumedEstimated () const
RasterSipperPtr Padded (int32 padding)
RasterSipperPtr ReduceByEvenMultiple (int32 multiple) const
RasterSipperPtr ReduceByFactor (float factor) const
RasterSipperPtr ReversedImage ()
RasterSipperPtr Rotate (float turnAngle)
RasterSipperPtr SegmentImage (bool save=false)
uchar * SimpleCompression (uint32 &buffLen) const
RasterSipperPtr SobelEdgeDetector ()
RasterSipperListPtr SplitImageIntoEqualParts (int32 numColSplits, int32 numRowSplits) const
RasterSipperPtr SwapQuadrants () const
RasterSipperPtr ThinContour ()
RasterSipperPtr ThresholdInHSI (float thresholdH, float thresholdS, float thresholdI, float distance, const PixelValue &flagValue)
Thresholds image in HSI space.
RasterSipperPtr TightlyBounded (uint32 borderPixels) const
RasterSipperPtr ToColor () const
Public Member Functions inherited from KKU::Raster
Raster ()
Raster (const Raster &_raster)
Copy Constructor.
Raster (int32 _height, int32 _width)
Constructs a blank GrayScale image with given dimensions; all pixels will be initialized to 0.
Raster (int32 _height, int32 _width, bool _color)
Constructs a blank image with given dimensions.
Raster (const BmpImage &_bmpImage)
Constructs a Raster from a BMP image loaded from disk.
Raster (const Raster &_raster, int32 _row, int32 _col, int32 _height, int32 _width)
Constructs a new Raster using a subset of the specified Raster as its source.
Raster (const Raster &_raster, MaskTypes _mask, int32 _row, int32 _col)
Constructs a Raster that will be as large as the specified '_mask' at the point specified by '_row' and '_col'.
Raster (const KKStr &fileName, bool &validFile)
Constructs a Raster image from by reading an existing image File such as a BMP file.
Raster (int32 _height, int32 _width, uchar *_grayScaleData, uchar **_grayScaleRows)
Construct a raster object that will utilize a image already in memory.
Raster (int32 _height, int32 _width, const uchar *_grayScaleData)
Construct a Grayscale Raster object using provided raw data,.
Raster (int32 _height, int32 _width, const uchar *_redChannel, const uchar *_greenChannel, const uchar *_blueChannel)
Construct a Color Raster object using provided raw data,.
virtual ~Raster ()
virtual RasterPtr AllocateARasterInstance (const Raster &_raster, int32 _row, int32 _col, int32 _height, int32 _width) const
uchar BackgroundPixelTH () const
void BackgroundPixelTH (uchar _backgroundPixelTH)
uchar BackgroundPixelValue () const
void BackgroundPixelValue (uchar _backgroundPixelValue)
RasterPtr BandPass (float lowerFreqBound, float upperFreqBound)
Returns a image that is the result of a BandPass using Fourier Transforms.
RasterPtr BinarizeByThreshold (uchar min, uchar max)
int32 BlobId (int32 row, int32 col) const
Return the ID of the blob that the specified pixel location belongs to.
uchar ** Blue () const
returns a pointer to two dimensional array for 'Blue' color channel.
uchar * BlueArea () const
int32 CalcArea ()
void CalcAreaAndIntensityFeatures (int32 &area, float &weighedSize, uint32 intensityHistBuckets[8], int32 &areaWithWhiteSpace, uint32 intensityHistBucketsWhiteSpace[8])
Calculates both Intensity Histograms, one not including internal background pixels and one with plus size and weighted size.
void CalcAreaAndIntensityFeatures (int32 &area, float &weighedSize, uint32 intensityHistBuckets[8])
Calculates both Intensity Histograms, one not including internal background pixels and one with plus size and weighted size.
void CalcAreaAndIntensityHistogram (int32 &area, uint32 intensityHistBuckets[8])
Calculates the occurrence of different intensity levels.
void CalcAreaAndIntensityHistogramWhite (int32 &area, uint32 intensityHistBuckets[8])
Calculates a Intensity Histogram including Background pixels in the image.
void CalcCentroid (int32 &size, int32 &weight, float &rowCenter, float &colCenter, float &rowCenterWeighted, float &colCenterWeighted)
void CalcOrientationAndEigerRatio (float &eigenRatio, float &orientationAngle)
float CalcWeightedArea () const
float CenMoment (int32 p, int32 q, float ew, float eh) const
float CenMomentWeighted (int32 p, int32 q, float ew, float eh) const
void CentralMoments (float features[9]) const
void CentralMomentsWeighted (float features[9]) const
float CentroidCol ()
float CentroidRow ()
void Closing ()
void Closing (MaskTypes mask)
bool Color () const
void ConnectedComponent (uchar connectedComponentDist)
void ConnectedComponent8Conected ()
void ConnectedComponentOrig ()
RasterPtr CreateColorImageFromLabels ()
Produces a color image using the 'greenArea' channel, assuming that each unique value will be assigned a unique color.
RasterPtr CreateColorWithBlobsLabeldByColor (BlobListPtr blobs)
Returns image where each blob is labeled with a different color.
RasterPtr CreateDialatedRaster () const
RasterPtr CreateDialatedRaster (MaskTypes mask) const
RasterPtr CreateErodedImage (MaskTypes mask) const
RasterPtr CreateFromOrginalImageWithSpecifidBlobsOnly (RasterPtr origImage, BlobListPtr blobs)
Returns a copy of 'origImage' where only the blobs specified in 'blobs' are copied over.
RasterPtr CreateGaussianSmoothedImage (float sigma) const
RasterPtr CreateGrayScale () const
RasterPtr CreateGrayScaleKLT () const
Creates a grayscale image using a KLT Transform with the goal of weighting in favor the color channels with greatest amount of variance.
RasterPtr CreateGrayScaleKLTOnMaskedArea (const Raster &mask) const
Same as 'CreateGrayScaleKLT' except it will only take into account pixels specified by the 'mask' image.
RasterPtr CreateSmoothedMediumImage (int32 maskSize) const
RasterPtr CreateSmoothImage (int32 maskSize=3) const
void Dialation ()
void Dialation (MaskTypes mask)
void DrawCircle (const Point &point, int32 radius, const PixelValue &color)
Draw a circle who's center is at 'point' and radius in pixels is 'radius'using color 'color'.
void DrawCircle (float centerRow, float centerCol, float radius, const PixelValue &pixelValue)
void DrawCircle (float centerRow, float centerCol, float radius, float startAngle, float endAngle, const PixelValue &pixelValue)
void DrawConnectedPointList (Point offset, const PointList &borderPixs, const PixelValue &pixelValue, const PixelValue &linePixelValue)
void DrawDot (const Point &point, const PixelValue &color, int32 size)
void DrawGrid (float pixelsPerMinor, uint32 minorsPerMajor, const PixelValue &hashColor, const PixelValue &gridColor)
void DrawLine (int32 bpRow, int32 bpCol, int32 epRow, int32 epCol)
void DrawLine (int32 bpRow, int32 bpCol, int32 epRow, int32 epCol, uchar pixelVal)
void DrawLine (const Point &beginPoint, const Point &endPoint, uchar pixelVal)
void DrawLine (const Point &beginPoint, const Point &endPoint, const PixelValue &pixelVal)
void DrawLine (int32 bpRow, int32 bpCol, int32 epRow, int32 epCol, uchar r, uchar g, uchar b)
void DrawLine (int32 bpRow, int32 bpCol, int32 epRow, int32 epCol, uchar r, uchar g, uchar b, float alpha)
void DrawLine (int32 bpRow, int32 bpCol, int32 epRow, int32 epCol, PixelValue pixelVal)
void DrawLine (int32 bpRow, int32 bpCol, int32 epRow, int32 epCol, PixelValue pixelVal, float alpha)
void DrawPointList (const PointList &borderPixs, const PixelValue &pixelValue)
void DrawPointList (Point offset, const PointList &borderPixs, const PixelValue &pixelValue)
void DrawPointList (const PointList &borderPixs, uchar redVal, uchar greenVal, uchar blueVal)
void DrawPointList (Point offset, const PointList &borderPixs, uchar redVal, uchar greenVal, uchar blueVal)
void Edge ()
reduces image to edge pixels only.
void ErodeSpurs ()
removes spurs from image.
void Erosion ()
void Erosion (MaskTypes mask)
void ErosionBoundary (MaskTypes mask, int32 blobrowstart, int32 blobrowend, int32 blobcolstart, int32 blobcolend)
void ErosionChanged (MaskTypes mask, int32 row, int32 col)
void ErosionChanged1 (MaskTypes mask, int32 row, int32 col)
RasterPtr ExtractABlob (const BlobPtr blob) const
Extracts a specified blob from this image; useful to extract individual detected blobs.
RasterPtr ExtractABlobTightly (const BlobPtr blob, int32 padding) const
Extracts a specified blob from this image into a tightly bounded image.
BlobListPtr ExtractBlobs (int32 dist)
Will extract a list of connected components from this instance.
RasterPtr ExtractChannel (ColorChannels channel)
Will return a grayscale image consisting of the specified color channel only.
RasterPtr FastFourier () const
RasterPtr FastFourierKK () const
const KKStr & FileName () const
void FileName (const KKStr &_fileName)
void FillBlob (RasterPtr origImage, BlobPtr blob, PixelValue color)
Will paint the specified blob with the specified color.
void FillHole ()
void FillRectangle (int32 tlRow, int32 tlCol, int32 brRow, int32 brCol, const PixelValue &fillColor)
void FindBoundingBox (int32 &tlRow, int32 &tlCol, int32 &brRow, int32 &brCol) const
bool ForegroundPixel (int32 row, int32 col) const
int32 ForegroundPixelCount () const
void ForegroundPixelCount (int32 _foregroundPixelCount)
uchar ForegroundPixelValue () const
void ForegroundPixelValue (uchar _foregroundPixelValue)
void FourierExtractFeatures (float fourierFeatures[5]) const
float * FourierMagArea () const
uchar GetPixelValue (int32 row, int32 col) const
void GetPixelValue (int32 row, int32 col, uchar &r, uchar &g, uchar &b) const
void GetPixelValue (int32 row, int32 col, PixelValue &p) const
uchar GetPixelValue (ColorChannels channel, int32 row, int32 col) const
uchar ** GetSubSet (uchar **_src, int32 _row, int32 _col, int32 _height, int32 _width) const
Returns back a two dimension array that is a copy of the specified region.
uchar ** Green () const
returns a pointer to two dimensional array for 'Green' color channel.
uchar * GreenArea () const
RasterPtr HalfSize ()
int32 Height () const
HistogramPtr Histogram (ColorChannels channel) const
RasterPtr HistogramEqualizedImage () const
RasterPtr HistogramEqualizedImage (HistogramPtr equalizedHistogram) const
HistogramPtr HistogramGrayscale () const
RasterPtr HistogramGrayscaleImage () const
RasterPtr HistogramImage (ColorChannels channel) const
void Initialize (int32 _height, int32 _width, uchar *_grayScaleData, uchar **_grayScaleRows, bool _takeOwnership)
Sets an existing instance to specific Raster data of a grayscale image.
void Initialize (int32 _height, int32 _width, uchar *_redArea, uchar **_red, uchar *_greenArea, uchar **_green, uchar *_blueArea, uchar **_blue, bool _takeOwnership)
uchar MaxPixVal () const
void MaxPixVal (uchar _maxPixVal)
int32 MemoryConsumedEstimated () const
void Opening ()
void Opening (MaskTypes mask)
RasterPtr Padded (int32 padding)
uchar ** Red () const
returns a pointer to two dimensional array for 'Red' color channel.
uchar * RedArea () const
RasterPtr ReduceByEvenMultiple (int32 multiple) const
RasterPtr ReduceByFactor (float factor) const
void ReduceToMostCompleteBlob (uchar connectedComponentDist)
Locates most complete blob; that is the one with the largest (Height x Width); and removes all other images from the blob.
RasterPtr ReversedImage ()
void ReverseImage ()
RasterPtr Rotate (float turnAngle)
uchar ** Rows () const
RasterPtr SegmentImage (bool save=false)
void SetPixelValue (const Point &point, const PixelValue &pixVal)
void SetPixelValue (int32 row, int32 col, uchar pixVal)
void SetPixelValue (int32 row, int32 col, const PixelValue &pixVal)
void SetPixelValue (int32 row, int32 col, uchar r, uchar g, uchar b)
void SetPixelValue (ColorChannels channel, int32 row, int32 col, uchar pixVal)
RasterPtr SobelEdgeDetector ()
RasterListPtr SplitImageIntoEqualParts (int32 numColSplits, int32 numRowSplits) const
RasterPtr SwapQuadrants () const
RasterPtr ThinContour ()
RasterPtr ThresholdInHSI (float thresholdH, float thresholdS, float thresholdI, float distance, const PixelValue &flagValue)
Thresholds image in HSI space.
RasterPtr TightlyBounded (uint32 borderPixels) const
RasterPtr ToColor () const
uchar * ToCompressor (uint32 &compressedBuffLen) const
Compresses the image in Raster using zlib library and returns a pointer to compressed data.
int32 TotalBackgroundPixels () const
int32 TotPixels () const
void WeOwnRasterData (bool _weOwnRasterData)
int32 Width () const
Static Public Member Functions
static float ComputeSegmentLens (const PointListPtr points, float heightFactor, float widthFactor)
static RasterSipperPtr CreatePaddedRaster (BmpImage &image, int32 padding)
static RasterSipperPtr FromCompressor (const uchar *compressedBuff, uint32 compressedBuffLen)
Creates a new instance of RasterSipper object from zLib compressed data.
static RasterSipperPtr FromSimpleCompression (const uchar *compressedBuff, uint32 compressedBuffLen)
Creates a raster from a compressedBuff created by 'SimpleCompression'.
static RasterSipperPtr TurnIntoSipperRasterPtr (RasterPtr &r)
Turn an instance of 'Raster' into 'RasterSipper'.
Static Public Member Functions inherited from KKU::Raster
static MatrixPtr BuildGaussian2dKernel (float sigma)
Builds a 2d Gaussian kernel.
static RasterPtr CreatePaddedRaster (BmpImage &image, int32 padding)
static void PrintOutListOfAllocatedrasterInstances ()
Additional Inherited Members
Static Protected Member Functions inherited from KKU::Raster
static void AddRasterInstance (const RasterPtr r)
static void FinalCleanUp ()
static void Initialize ()
static void RemoveRasterInstance (const RasterPtr r)
Protected Attributes inherited from KKU::Raster
uchar backgroundPixelTH
uchar backgroundPixelValue
int32 ** blobIds
uchar ** blue
uchar * blueArea
float centroidCol
float centroidRow
bool color
KKStr fileName
int32 foregroundPixelCount
uchar foregroundPixelValue
float ** fourierMag
Only used if image is result of a Fourier Transform.
float * fourierMagArea
Only used if image is result of a Fourier Transform.
uchar ** green
uchar * greenArea
int32 height
uchar maxPixVal
uchar ** red
uchar * redArea
int32 totPixels
bool weOwnRasterData
int32 width
Static Protected Attributes inherited from KKU::Raster
static std::map< RasterPtr,
RasterPtr > allocatedRasterInstances
static volatile GoalKeeperPtr goalKeeper = NULL
static volatile bool rasterInitialized = false
Detailed Description
A class that is used by to represent a single Sipper Image in memory.
A specialized RasterSipper object for managing Sipper Images.
See Also
Blob
ContourFollower
ConvexHull
PixelValue
Point
PointList
RasterSipperList()
Sobel
Definition at line 50 of file RasterSipper.h.
Member Typedef Documentation
typedef RasterSipper* KKU::RasterSipper::RasterSipperPtr
Definition at line 53 of file RasterSipper.h.
Constructor & Destructor Documentation
RasterSipper::RasterSipper ()
Definition at line 38 of file RasterSipper.cpp.
Referenced by AllocateARasterInstance(), FromCompressor(), FromSimpleCompression(), and TurnIntoSipperRasterPtr().
RasterSipper::RasterSipper (const RasterSipper & _raster)
Copy Constructor.
Definition at line 76 of file RasterSipper.cpp.
RasterSipper::RasterSipper (const Raster & _raster)
Copy Constructor.
Definition at line 83 of file RasterSipper.cpp.
RasterSipper::RasterSipper (int32 _height, int32 _width)
Constructs a blank GrayScale image with given dimensions; all pixels will be initialized to 0.
When working with Grayscale images pixel value of '0' = Background and '255'= foreground. The green channel will be used to represent the grayscale value. When these raster images are saved to a image file such as a BMP file the pixel value of 0 will point to the color value of (255, 255, 255) and pixel value 255 will point to the color value of (0, 0, 0). This way when displaying the image background will appear as white.
Definition at line 43 of file RasterSipper.cpp.
RasterSipper::RasterSipper (int32 _height, int32 _width, bool _color)
Constructs a blank image with given dimensions.
The third parameter determines whether it will be a color or grayscale image, If a Color image then all three color channel will be set to = 255 which stands for white. If Grayscale the green channel will be set to 0.
Definition at line 52 of file RasterSipper.cpp.
RasterSipper::RasterSipper (const BmpImage & _bmpImage)
Constructs a RasterSipper from a BMP image loaded from disk.
Constructs a RasterSipper from a BMP image loadded from disk.
If BMP Image is a grayscale value pixel values will be reversed. See description of grayscale constructor.
If BMP Image is a grayscale value pixel values will be reveresed. See description of grayscale constructor.
Definition at line 67 of file RasterSipper.cpp.
RasterSipper::RasterSipper (const RasterSipper & _raster, int32 _row, int32 _col, int32 _height, int32 _width)
Constructs a new RasterSipper using a subset of the specified RasterSipper as its source.
The dimensions of the resultant raster will be '_height', and '_width'
Parameters
_raster Source RasterSipper
_row Starting Row in '_raster' to copy from.
_col Starting Col in '_raster' to copy from.
_height Height of resultant raster. Will start from '_row'
_width Width of resultant raster.
Definition at line 90 of file RasterSipper.cpp.
RasterSipper::RasterSipper (const RasterSipper & _raster, MaskTypes _mask, int32 _row, int32 _col)
Constructs a RasterSipper that will be as large as the specified '_mask' at the point specified by '_row' and '_col'.
See Also
MaskTypes
Parameters
_mask
See Also
MaskTyps Generated 'RasterSipper' with be the of the mask.
Definition at line 102 of file RasterSipper.cpp.
RasterSipper::RasterSipper (const KKStr & _fileName, bool & validFile)
Constructs a RasterSipper image from by reading an existing image File such as a BMP file.
Constructs a raster object from a Image File.
Will read from the specified file (fileName) the existing image. If the load fails then the contents of this object will be undefined.
Parameters
[in] fileName Name of Image file to read.
[out] validFile If image successfully loaded will be set to 'True' otherwise 'False'.
If a color image the pixel values will be reveresed, see constructor for grayscale images.
Parameters
_fileName
fileName name of image file to load/
validFile
validFile will return true if image successfully loaded.
Definition at line 118 of file RasterSipper.cpp.
RasterSipper::RasterSipper (int32 _height, int32 _width, uchar * _grayScaleData, uchar ** _grayScaleRows)
Construct a raster object that will utilize a image already in memory.
This instance will not own the raster data. It will only point to it.
Definition at line 129 of file RasterSipper.cpp.
RasterSipper::RasterSipper (int32 _height, int32 _width, const uchar * _grayScaleData)
Construct a Grayscale RasterSipper object using provided raw data,.
Definition at line 141 of file RasterSipper.cpp.
RasterSipper::RasterSipper (int32 _height, int32 _width, const uchar * _redChannel, const uchar * _greenChannel, const uchar * _blueChannel)
Construct a Color RasterSipper object using provided raw data,.
Definition at line 150 of file RasterSipper.cpp.
RasterSipper::~RasterSipper () virtual
Definition at line 163 of file RasterSipper.cpp.
Member Function Documentation
RasterPtr RasterSipper::AllocateARasterInstance (int32 height, int32 width, bool color) const virtual
Reimplemented from KKU::Raster.
Definition at line 209 of file RasterSipper.cpp.
References RasterSipper().
RasterPtr RasterSipper::AllocateARasterInstance (const Raster & r) const virtual
Reimplemented from KKU::Raster.
Definition at line 219 of file RasterSipper.cpp.
References RasterSipper().
RasterPtr RasterSipper::AllocateARasterInstance (const Raster & _raster, int32 _row, int32 _col, int32 _height, int32 _width) virtual
Parameters
_raster Source Raster
_row Starting Row in '_raster' to copy from.
_col Starting Col in '_raster' to copy from.
_height Height of resultant raster. Will start from '_row'
_width Width of resultant raster.
Definition at line 227 of file RasterSipper.cpp.
References RasterSipper().
RasterSipperPtr RasterSipper::BandPass (float lowerFreqBound, float upperFreqBound)
Returns a image that is the result of a BandPass using Fourier Transforms.
A 2D Fourier transform is performed. The range specified is from 0.0 to 1.0 where range is determined from the center of the image to the farthest corner where the center is 0.0 and the farthest corner is 1.0. Pixels in the resultant 2D Transform that are "NOT" in the specified range are set to 0.0. A reverse transform is then performed and the resultant image is returned.
Parameters
[in] lowerFreqBound Lower range of frequencies to retain; between 0.0 and 1.0.
[in] upperFreqBound Upper range of frequencies to retain; between 0.0 and 1.0.
Returns
The result image.
Parameters
lowerFreqBound Number's between 0.0 and 1.0
upperFreqBound Represent fraction.
Definition at line 539 of file RasterSipper.cpp.
References KKU::Raster::BandPass().
Referenced by PicesInterface::PicesRaster::BandPass().
RasterSipperPtr RasterSipper::BinarizeByThreshold (uchar min, uchar max)
Definition at line 457 of file RasterSipper.cpp.
References KKU::Raster::BinarizeByThreshold().
Referenced by PicesInterface::PicesRaster::Binarize(), and PicesInterface::PicesRaster::BinarizeByThreshold().
float RasterSipper::ComputeSegmentLens (const PointListPtr points, float heightFactor, float widthFactor) static
Definition at line 466 of file RasterSipper.cpp.
References KKU::PointList::ComputeSegmentLens().
RasterSipperPtr RasterSipper::CreateColorImageFromLabels ()
Definition at line 787 of file RasterSipper.cpp.
References KKU::Raster::CreateColorImageFromLabels().
RasterSipperPtr RasterSipper::CreateColorWithBlobsLabeldByColor (BlobListPtr blobs)
Only useful if 'ExtractBlobs' was performed on this instance, the returned image will be color with each blob labeled a different color.
Returns image where each blob is labeled with a different color.
Only useful if 'ExtractBlobs' was performed on this instance.
Definition at line 289 of file RasterSipper.cpp.
References KKU::Raster::CreateColorWithBlobsLabeldByColor().
RasterSipperPtr RasterSipper::CreateDialatedRaster () const
Definition at line 260 of file RasterSipper.cpp.
References KKU::Raster::CreateDialatedRaster().
Referenced by PicesInterface::PicesRaster::CloseImage(), PicesInterface::PicesRaster::DialateImage(), and PicesInterface::PicesRaster::OpenImage().
RasterSipperPtr RasterSipper::CreateDialatedRaster (MaskTypes mask) const
Definition at line 268 of file RasterSipper.cpp.
References KKU::Raster::CreateDialatedRaster().
RasterSipperPtr RasterSipper::CreateErodedImage (MaskTypes mask) const
Definition at line 277 of file RasterSipper.cpp.
References KKU::Raster::CreateErodedImage().
Referenced by PicesInterface::PicesRaster::CloseImage(), DeriveImageLength(), PicesInterface::PicesRaster::ErodeImage(), and PicesInterface::PicesRaster::OpenImage().
RasterSipperPtr RasterSipper::CreateFromOrginalImageWithSpecifidBlobsOnly (RasterSipperPtr origImage, BlobListPtr blobs)
Returns a copy of 'origImage' where only the blobs specified in 'blobs' are copied over.
Example:
    origImage = image that we want to segment and get list of discrete blobs from.
    RasterSipperPtr  segmentedImage = origImage->SegmentImage ();
    BlobListPtr  blobs = segmentedImage->ExtractBlobs (1);
    RasterSipperPtr  imageWithBlobOnly = segmentedImage->CreateFromOrginalImageWithSpecifidBlobsOnly (blobs);
Parameters
[in] origImage Image that this instance was derived for, must have same dimensions.
[in] blobs Blobs that you want copied over from.
Returns
Image consisting of specified blobs only.
Definition at line 296 of file RasterSipper.cpp.
References KKU::Raster::CreateFromOrginalImageWithSpecifidBlobsOnly().
RasterSipperPtr RasterSipper::CreateGaussianSmoothedImage (float sigma) const
Definition at line 751 of file RasterSipper.cpp.
References KKU::Raster::CreateGaussianSmoothedImage().
RasterSipperPtr RasterSipper::CreateGrayScale () const
Definition at line 365 of file RasterSipper.cpp.
References KKU::Raster::CreateGrayScale().
RasterSipperPtr RasterSipper::CreateGrayScaleKLT () const
Creates a grayscale image using a KLT Transform with the goal of weighting in favor the color channels with greatest amount of variance.
The idea is to weight each color channel by the amount of variance. This is accomplished by producing a covariance matrix of the three color channels and then taking the Eigen vector with the largest Eigen value and using its components to derive weights for each channel for the conversion from RGB to grayscale.
Definition at line 772 of file RasterSipper.cpp.
References KKU::Raster::CreateGrayScaleKLT().
RasterSipperPtr RasterSipper::CreateGrayScaleKLTOnMaskedArea (const RasterSipper & mask) const
Same as 'CreateGrayScaleKLT' except it will only take into account pixels specified by the 'mask' image.
Parameters
[in] mask RasterSipper object where pixels that are greater than 'backgroundPixelTH' are to be considered.
Definition at line 780 of file RasterSipper.cpp.
References KKU::Raster::CreateGrayScaleKLTOnMaskedArea().
RasterSipperPtr RasterSipper::CreatePaddedRaster (BmpImage & image, int32 padding) static
Definition at line 243 of file RasterSipper.cpp.
References KKU::Raster::CreatePaddedRaster().
RasterSipperPtr RasterSipper::CreateSmoothedMediumImage (int32 maskSize) const
Definition at line 417 of file RasterSipper.cpp.
References KKU::Raster::CreateSmoothedMediumImage().
Referenced by PicesInterface::PicesRaster::SmoothMedium().
RasterSipperPtr RasterSipper::CreateSmoothImage (int32 maskSize = 3) const
Definition at line 408 of file RasterSipper.cpp.
References KKU::Raster::CreateSmoothImage().
Referenced by PicesInterface::PicesRaster::SmoothAveraging().
PointListPtr RasterSipper::DeriveImageLength () const
Definition at line 828 of file RasterSipper.cpp.
References KKU::Raster::CalcOrientationAndEigerRatio(), KKU::Raster::ConnectedComponent(), CreateErodedImage(), DerivePreRotatedPoint(), KKU::Raster::Erosion(), KKU::Raster::FillHole(), KKU::Raster::FindBoundingBox(), KKU::Raster::Green(), KKU::Raster::height, KKU::Max(), Rotate(), KKU::SQUARE3, KKU::SQUARE7, TwoPie, and KKU::Raster::width.
Referenced by PicesInterface::PicesRaster::DeriveImageLength().
RasterSipperPtr RasterSipper::ExtractABlob (const BlobPtr blob) const
Extracts a specified blob from this image; useful to extract individual detected blobs.
The 'ExtractBlobs' method needs to have been performed on this instance first. You would use this method after calling 'ExtractBlobs'. The extracted image will be of the same dimensions as the original image except it will extract the pixels that belong to the specified blob only.
// Example of processing extracted blobs
void  ProcessIndividulConectedComponents (RasterSipperPtr  image)
{
  BlobListPtr blobs = image->ExtractBlobs (3);
  BlobList::iterator  idx;
  for  (idx = blobs->begin ();  idx != end ();  ++idx)
  {
    RasterSipperPtr  individuleBlob = image->ExtractABlob (*idx);
    DoSomethingWithIndividuleBlob (individuleBlob);
    delete  individuleBlob;
    individuleBlob = NULL;
  )
  delete  blobs;
  blobs = NULL;
}
Definition at line 320 of file RasterSipper.cpp.
References KKU::Raster::ExtractABlob().
RasterSipperPtr RasterSipper::ExtractABlobTightly (const BlobPtr blob, int32 padding) const
Extracts a specified blob from this image into a tightly bounded image.
Similar to 'ExtractABlob' except that the returned image will have the dimension necessary to contain the specified blob with the specified number of padded row and columns.
Definition at line 307 of file RasterSipper.cpp.
References KKU::Raster::ExtractABlobTightly().
RasterSipperPtr RasterSipper::ExtractChannel (ColorChannels channel)
Will return a grayscale image consisting of the specified color channel only.
Definition at line 480 of file RasterSipper.cpp.
References KKU::Raster::ExtractChannel().
RasterSipperPtr RasterSipper::FastFourier () const
Definition at line 338 of file RasterSipper.cpp.
References KKU::Raster::FastFourier().
Referenced by PicesInterface::PicesRaster::FourierTransform().
RasterSipperPtr RasterSipper::FastFourierKK () const
Definition at line 329 of file RasterSipper.cpp.
References KKU::Raster::FastFourierKK().
RasterSipperPtr RasterSipper::FromCompressor (const uchar * compressedBuff, uint32 compressedBuffLen) static
Creates a new instance of RasterSipper object from zLib compressed data.
Performs the inverse operation of RasterSipper::ToCompressor.
Parameters
[in] compressedBuff Pointer to buffer area containing compressed data originally created by 'ToCompressor'.
[in] compressedBuffLen Length in bytes of 'compressedBuff'.
Returns
If successful a pointer to a new instance of 'RasterSipper'; if there is an error will return NULL.
See Also
ToCompressor
Definition at line 654 of file RasterSipper.cpp.
References KKU::Raster::BlueArea(), KKU::Raster::blueArea, KKU::Raster::color, KKU::Compressor::Decompress(), KKU::endl(), KKU::Raster::GreenArea(), KKU::Raster::greenArea, KKU::Raster::height, RasterSipper(), KKU::Raster::RedArea(), KKU::Raster::redArea, KKU::Raster::width, and x.
RasterSipperPtr RasterSipper::FromSimpleCompression (const uchar * compressedBuff, uint32 compressedBuffLen) static
Creates a raster from a compressedBuff created by 'SimpleCompression'.
Definition at line 572 of file RasterSipper.cpp.
References KKU::SimpleCompressor::Decompress(), KKU::endl(), KKU::Raster::GreenArea(), KKU::Raster::greenArea, KKU::Raster::height, RasterSipper(), and KKU::Raster::width.
RasterSipperPtr RasterSipper::HalfSize ()
Definition at line 425 of file RasterSipper.cpp.
References KKU::Raster::HalfSize().
RasterSipperPtr RasterSipper::HistogramEqualizedImage () const
Definition at line 374 of file RasterSipper.cpp.
References KKU::Raster::HistogramEqualizedImage().
RasterSipperPtr RasterSipper::HistogramEqualizedImage (HistogramPtr equalizedHistogram) const
Definition at line 383 of file RasterSipper.cpp.
References KKU::Raster::HistogramEqualizedImage().
RasterSipperPtr RasterSipper::HistogramGrayscaleImage () const
Definition at line 392 of file RasterSipper.cpp.
References KKU::Raster::HistogramGrayscaleImage().
RasterSipperPtr RasterSipper::HistogramImage (ColorChannels channel) const
Definition at line 399 of file RasterSipper.cpp.
References KKU::Raster::HistogramImage().
int32 RasterSipper::MemoryConsumedEstimated () const
Definition at line 169 of file RasterSipper.cpp.
References KKU::Raster::MemoryConsumedEstimated().
Referenced by ImageExtractionManager::ExtractedImage::MemoryConsumedEstimated(), and PicesInterface::PicesRaster::PicesRaster().
RasterSipperPtr RasterSipper::Padded (int32 padding)
Definition at line 744 of file RasterSipper.cpp.
References KKU::Raster::Padded().
RasterSipperPtr RasterSipper::ReduceByEvenMultiple (int32 multiple) const
Definition at line 434 of file RasterSipper.cpp.
References KKU::Raster::ReduceByEvenMultiple().
RasterSipperPtr RasterSipper::ReduceByFactor (float factor) const
Definition at line 441 of file RasterSipper.cpp.
References KKU::Raster::ReduceByFactor().
RasterSipperPtr RasterSipper::ReversedImage ()
Definition at line 252 of file RasterSipper.cpp.
References KKU::Raster::ReversedImage().
Referenced by PicesInterface::PicesRaster::ReversedImage().
RasterSipperPtr RasterSipper::Rotate (float turnAngle)
Definition at line 356 of file RasterSipper.cpp.
References KKU::Raster::Rotate(), and TurnIntoSipperRasterPtr().
Referenced by DeriveImageLength().
RasterSipperPtr RasterSipper::SegmentImage (bool save = false)
Definition at line 492 of file RasterSipper.cpp.
References KKU::Raster::SegmentImage().
uchar * RasterSipper::SimpleCompression (uint32 & buffLen) const
Definition at line 550 of file RasterSipper.cpp.
References KKU::SimpleCompressor::Add16BitInt(), KKU::SimpleCompressor::AddByte(), KKU::SimpleCompressor::CreateCompressedBuffer(), and x.
RasterSipperPtr RasterSipper::SobelEdgeDetector ()
Definition at line 449 of file RasterSipper.cpp.
References KKU::Raster::SobelEdgeDetector().
RasterSipperListPtr RasterSipper::SplitImageIntoEqualParts (int32 numColSplits, int32 numRowSplits) const
Definition at line 500 of file RasterSipper.cpp.
References KKU::Raster::SplitImageIntoEqualParts().
RasterSipperPtr RasterSipper::SwapQuadrants () const
Definition at line 346 of file RasterSipper.cpp.
References KKU::Raster::SwapQuadrants().
RasterSipperPtr RasterSipper::ThinContour ()
Definition at line 517 of file RasterSipper.cpp.
References KKU::Raster::ThinContour().
Referenced by PicesInterface::PicesRaster::Thinning().
RasterSipperPtr RasterSipper::ThresholdInHSI (float thresholdH, float thresholdS, float thresholdI, float distance, const PixelValue & flagValue)
Thresholds image in HSI space.
    Returns an image with only the pixels that are within a specified distance in HSI space to the
    supplied HSI parameters.  All pixels that are not within the specified distance will be set to
    'flagValue'.
Parameters
[in] thresholdH Hue in radians(0.0 <-> 2Pie).
[in] thresholdS Saturation (0.0 <-> 1.0).
[in] thresholdI Intensity (0.0 <-> 1.0).
[in] distance Threshold Distance (0.0 <-> 1.0) that a pixel must be within in HSI space to be included.
[in] flagValue PixelValue to set for pixels that are NOT within 'distance' of threshold.
Returns
A image where pixels that are within the threshold will retain their original pixel values and the ones that are not will be set to 'flagValue'.
Definition at line 759 of file RasterSipper.cpp.
References KKU::Raster::ThresholdInHSI().
RasterSipperPtr RasterSipper::TightlyBounded (uint32 borderPixels) const
Definition at line 525 of file RasterSipper.cpp.
References KKU::Raster::TightlyBounded().
RasterSipperPtr RasterSipper::ToColor () const
Definition at line 532 of file RasterSipper.cpp.
References KKU::Raster::ToColor().
Referenced by PicesInterface::PicesRaster::ToColor().
RasterSipperPtr RasterSipper::TurnIntoSipperRasterPtr (RasterPtr & r) static
Turn an instance of 'Raster' into 'RasterSipper'.
Will utilize the dynamically allocated raster data of the 'Raster' instance 'r' to build a new instance of a 'SipperRaster'.
Parameters
[in,out] r The raster data of 'r' will be given to the new instance of 'RasterSipper' and 'r' will then be deleted and set to NULL.
Definition at line 176 of file RasterSipper.cpp.
References KKU::Raster::Blue(), KKU::Raster::BlueArea(), KKU::Raster::Color(), KKU::Raster::Green(), KKU::Raster::GreenArea(), KKU::Raster::Height(), KKU::Raster::Initialize(), RasterSipper(), KKU::Raster::Red(), KKU::Raster::RedArea(), KKU::Raster::WeOwnRasterData(), and KKU::Raster::Width().
Referenced by Rotate().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/RasterSipper.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/RasterSipper.cpp