Pices: MLL::FeatureFileIORoberts Class Reference
MLL::FeatureFileIORoberts Class Reference
Supports the writting of Feature Data to a file that can then be read by OpenDT.
#include <FeatureFileIORoberts.h>
Public Types
typedef FeatureFileIORoberts * FeatureFileIORobertsPtr
Public Types inherited from MLL::FeatureFileIO
typedef FeatureFileIO * FeatureFileIOPtr
typedef KKU::int32 int32
typedef KKU::uint32 uint32
Public Member Functions
FeatureFileIORoberts ()
~FeatureFileIORoberts ()
virtual FileDescPtr GetFileDesc (const KKStr &_fileName, istream &_in, MLClassConstListPtr _classList, int32 &_estSize, KKStr &_errorMessage, RunLog &_log)
virtual FeatureVectorListPtr LoadFile (const KKStr &_fileName, const FileDescPtr _fileDesc, MLClassConstList &_classes, istream &_in, long _maxCount, volatile const bool &_cancelFlag, bool &_changesMade, KKStr &_errorMessage, RunLog &_log)
virtual void SaveFile (FeatureVectorList &_data, const KKStr &_fileName, const FeatureNumList &_selFeatures, ostream &_out, uint32 &_numExamplesWritten, volatile const bool &_cancelFlag, bool &_successful, KKStr &_errorMessage, RunLog &_log)
Public Member Functions inherited from MLL::FeatureFileIO
FeatureFileIO (const KKStr &_driverName, bool _canRead, bool _canWrite)
virtual ~FeatureFileIO ()
void AppendToFile (const KKStr &_fileName, const FeatureNumList &_selFeatures, FeatureVectorList &_examples, uint32 &_numExamplesWritten, volatile const bool &_cancelFlag, bool &_successful, RunLog &log)
bool CanRead ()
bool CanWrite ()
const KKStr & DriverName ()
virtual FileDescPtr GetFileDesc (const KKStr &_fileName, std::istream &_in, MLClassConstListPtr _classes, int32 &_estSize, KKStr &_errorMessage, RunLog &_log)=0
Create a FileDesc object from the input stream '_in'.
virtual FeatureVectorListPtr LoadFeatureFile (const KKStr &_fileName, MLClassConstList &_mlClasses, long _maxCount, volatile const bool &_cancelFlag, bool &_successful, bool &_changesMade, RunLog &_log)
Loads the contents of a feature data file and returns a ImageFeaturesList container object.
virtual FeatureVectorListPtr LoadFile (const KKStr &_fileName, const FileDescPtr _fileDesc, MLClassConstList &_classes, std::istream &_in, long _maxCount, volatile const bool &_cancelFlag, bool &_changesMade, KKStr &_errorMessage, RunLog &_log)=0
To be implemented by derived classes; loads the contents of a feature data file and returns a ImageFeaturesList container object.
virtual void SaveFeatureFile (const KKStr &_fileName, const FeatureNumList &_selFeatures, FeatureVectorList &_examples, uint32 &_numExamplesWritten, volatile const bool &_cancelFlag, bool &_successful, RunLog &_log)
SaveFeatureFile.
void SaveFeatureFileMultipleParts (const KKStr &_fileName, const FeatureNumList &_selFeatures, FeatureVectorList &_examples, volatile const bool &_cancelFlag, bool &_successful, RunLog &_log)
Saves the feature file in multiple parts with no one single part larger that 64k examples.
virtual void SaveFile (FeatureVectorList &_data, const KKStr &_fileName, const FeatureNumList &_selFeatures, std::ostream &_out, uint32 &_numExamplesWritten, volatile const bool &_cancelFlag, bool &_successful, KKStr &_errorMessage, RunLog &_log)=0
To be implmenetd by derived classes; save examples to output stream '_out'.
Static Public Member Functions
static FeatureFileIORobertsPtr Driver ()
Static Public Member Functions inherited from MLL::FeatureFileIO
static FeatureFileIOPtr FileFormatFromStr (const KKStr &_fileFormatStr)
static FeatureFileIOPtr FileFormatFromStr (const KKStr &_fileFormatStr, bool _canRead, bool _canWrite)
static KKStr FileFormatsReadAndWriteOptionsStr ()
static KKStr FileFormatsReadOptionsStr ()
static KKStr FileFormatsWrittenOptionsStr ()
static void FinalCleanUp ()
Before you terminate your application and after all FeatureFileIO activity is done call this method to destroy statically dynamically allocated data structures.
static VectorKKStr RegisteredDriverNames (bool canRead, bool canWrite)
Additional Inherited Members
Protected Member Functions inherited from MLL::FeatureFileIO
void GetLine (std::istream &_in, KKStr &_line, bool &_eof)
void GetToken (std::istream &_in, const char *_delimiters, KKStr &_token, bool &_eof, bool &_eol)
Will retrieve the next token from the input stream.
Detailed Description
Supports the writting of Feature Data to a file that can then be read by OpenDT.
************************************************************************************************
*  FeatureFileIOSRoberts  Sub-classed from FeatureFileIO.  It supports thwe writting of a file *
*  that can be read by OpenDT. http://opendt.sourceforge.net/.  This file format is similar to *
*  C45 except the contents of the names file are included in the data file.                    *
************************************************************************************************
See Also
FeatureFileIO
Definition at line 28 of file FeatureFileIORoberts.h.
Member Typedef Documentation
typedef FeatureFileIORoberts* MLL::FeatureFileIORoberts::FeatureFileIORobertsPtr
Definition at line 34 of file FeatureFileIORoberts.h.
Constructor & Destructor Documentation
FeatureFileIORoberts::FeatureFileIORoberts ()
Definition at line 36 of file FeatureFileIORoberts.cpp.
FeatureFileIORoberts::~FeatureFileIORoberts (void)
Definition at line 41 of file FeatureFileIORoberts.cpp.
Member Function Documentation
static FeatureFileIORobertsPtr MLL::FeatureFileIORoberts::Driver () inline static
Definition at line 36 of file FeatureFileIORoberts.h.
FileDescPtr FeatureFileIORoberts::GetFileDesc (const KKStr & _fileName, istream & _in, MLClassConstListPtr _classList, int32 & _estSize, KKStr & _errorMessage, RunLog & _log) virtual
Definition at line 47 of file FeatureFileIORoberts.cpp.
References KKU::endl(), and KKU::RunLog::Level().
FeatureVectorListPtr FeatureFileIORoberts::LoadFile (const KKStr & _fileName, const FileDescPtr _fileDesc, MLClassConstList & _classes, istream & _in, long _maxCount, volatile const bool & _cancelFlag, bool & _changesMade, KKStr & _errorMessage, RunLog & _log) virtual
Definition at line 67 of file FeatureFileIORoberts.cpp.
References KKU::endl(), and KKU::RunLog::Level().
void FeatureFileIORoberts::SaveFile (FeatureVectorList & _data, const KKStr & _fileName, const FeatureNumList & _selFeatures, ostream & _out, uint32 & _numExamplesWritten, volatile const bool & _cancelFlag, bool & _successful, KKStr & _errorMessage, RunLog & _log) virtual
Definition at line 88 of file FeatureFileIORoberts.cpp.
References MLL::Attribute::Cardinality(), MLL::FeatureVector::ClassName(), MLL::FileDesc::CreateAAttributeTable(), KKU::endl(), MLL::FeatureVectorList::ExtractMLClassConstList(), MLL::FeatureVector::FeatureData(), MLL::FeatureVectorList::FileDesc(), MLL::Attribute::GetNominalValue(), KKU::RunLog::Level(), MLL::NominalAttribute, MLL::FeatureNumList::NumOfFeatures(), MLL::MLClassConstList::SortByName(), KKU::KKStr::Str(), MLL::SymbolicAttribute, MLL::Attribute::Type(), and x.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/FeatureFileIORoberts.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/FeatureFileIORoberts.cpp