Pices: SVM289_MFS::Solver_NU Class Reference
SVM289_MFS::Solver_NU Class Reference
Public Member Functions
Solver_NU ()
void Solve (int32 l, QMatrix &Q, const double *p, const schar *y, double *alpha, double Cp, double Cn, double eps, SolutionInfo *si, int32 shrinking)
Public Member Functions inherited from SVM289_MFS::Solver
Solver ()
virtual ~Solver ()
void Solve (int32 l, QMatrix &Q, const double *p_, const schar *y_, double *alpha_, double Cp, double Cn, double eps, SolutionInfo *si, int32 shrinking)
Additional Inherited Members
Protected Types inherited from SVM289_MFS::Solver
enum { LOWER_BOUND, UPPER_BOUND, FREE }
Protected Member Functions inherited from SVM289_MFS::Solver
double get_C (int32 i)
bool is_free (int32 i)
bool is_lower_bound (int32 i)
bool is_upper_bound (int32 i)
void reconstruct_gradient ()
void swap_index (int32 i, int32 j)
void update_alpha_status (int32 i)
Protected Attributes inherited from SVM289_MFS::Solver
int32 * active_set
int32 active_size
double * alpha
char * alpha_status
double Cn
double Cp
double eps
double * G
double * G_bar
int32 l
double * p
QMatrix * Q
const Qfloat * QD
bool unshrink
schar * y
Detailed Description
Definition at line 1896 of file svm2.cpp.
Constructor & Destructor Documentation
SVM289_MFS::Solver_NU::Solver_NU () inline
Definition at line 1899 of file svm2.cpp.
Member Function Documentation
void SVM289_MFS::Solver_NU::Solve (int32 l, QMatrix & Q, const double * p, const schar * y, double * alpha, double Cp, double Cn, double eps, SolutionInfo * si, int32 shrinking) inline
Definition at line 1901 of file svm2.cpp.
References SVM289_MFS::Solver::Solve().
Referenced by SVM289_MFS::solve_nu_svc(), and solve_nu_svr().
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/svm2.cpp