Pices: MLL::NormalizationParms Class Reference
MLL::NormalizationParms Class Reference
Normalization Parameters; calculation and implementation.
#include <NormalizationParms.h>
Public Member Functions
NormalizationParms (bool _normalizeNominalFeatures, FeatureVectorList &_examples, RunLog &_log)
NormalizationParms (const ModelParam &_param, FeatureVectorList &_images, RunLog &_log)
NormalizationParms (TrainingConfiguration2Ptr _config, FeatureVectorList &_images, RunLog &_log)
NormalizationParms (FileDescPtr _fileDesc, KKStr _fileName, bool &_successfull, RunLog &_log)
NormalizationParms (FileDescPtr _fileDesc, FILE *_in, bool &_successfull, RunLog &_log)
NormalizationParms (FileDescPtr _fileDesc, istream &_in, bool &_successfull, RunLog &_log)
~NormalizationParms ()
double Mean (int32 i)
const double * Mean ()
int32 MemoryConsumedEstimated () const
void NormalizeAImage (FeatureVectorPtr image)
void NormalizeImages (FeatureVectorListPtr images)
int32 NumOfFeatures ()
void Read (FILE *i, bool &sucessful)
void Read (istream &i, bool &sucessful)
void Save (const KKStr &_fileName, bool &_successfull)
double Sigma (int32 i)
const double * Sigma ()
FeatureVectorPtr ToNormalized (FeatureVectorPtr example) const
void Write (std::ostream &o)
Detailed Description
Normalization Parameters; calculation and implementation.
Normalization parameters will be calculated for all features but when individual images are normalized, only the ones specified by '_featuresToNormalize' will be normalized.
Definition at line 56 of file NormalizationParms.h.
Constructor & Destructor Documentation
MLL::NormalizationParms::NormalizationParms (bool _normalizeNominalFeatures, FeatureVectorList & _examples, RunLog & _log)
Referenced by MemoryConsumedEstimated().
MLL::NormalizationParms::NormalizationParms (const ModelParam & _param, FeatureVectorList & _images, RunLog & _log)
MLL::NormalizationParms::NormalizationParms (TrainingConfiguration2Ptr _config, FeatureVectorList & _images, RunLog & _log)
MLL::NormalizationParms::NormalizationParms (FileDescPtr _fileDesc, KKStr _fileName, bool & _successfull, RunLog & _log)
MLL::NormalizationParms::NormalizationParms (FileDescPtr _fileDesc, FILE * _in, bool & _successfull, RunLog & _log)
MLL::NormalizationParms::NormalizationParms (FileDescPtr _fileDesc, istream & _in, bool & _successfull, RunLog & _log)
NormalizationParms::~NormalizationParms ()
Definition at line 212 of file NormalizationParms.cpp.
Member Function Documentation
double MLL::NormalizationParms::Mean (int32 i)
const double* MLL::NormalizationParms::Mean () inline
Definition at line 124 of file NormalizationParms.h.
int32 NormalizationParms::MemoryConsumedEstimated () const
Definition at line 220 of file NormalizationParms.cpp.
References KKU::KKStr::MemoryConsumedEstimated(), and NormalizationParms().
Referenced by MLL::Model::MemoryConsumedEstimated().
void NormalizationParms::NormalizeAImage (FeatureVectorPtr image)
Definition at line 676 of file NormalizationParms.cpp.
References MLL::FeatureVector::FeatureDataAlter().
Referenced by NormalizeImages().
void NormalizationParms::NormalizeImages (FeatureVectorListPtr images)
Definition at line 697 of file NormalizationParms.cpp.
References KKU::endl(), KKU::RunLog::Level(), NormalizeAImage(), MLL::FeatureVectorList::NumOfFeatures(), and KKU::osWaitForEnter().
Referenced by PicesInterface::PicesFeatureFileIO::SaveFeatureFileNormalized(), and MLL::Model::TrainModel().
int32 MLL::NormalizationParms::NumOfFeatures () inline
Definition at line 102 of file NormalizationParms.h.
void NormalizationParms::Read (FILE * i, bool & sucessful)
Definition at line 387 of file NormalizationParms.cpp.
References KKU::KKStr::Empty(), KKU::endl(), KKU::KKStr::ExtractQuotedStr(), KKU::KKStr::ExtractTokenBool(), KKU::KKStr::ExtractTokenDouble(), KKU::KKStr::ExtractTokenInt(), KKU::RunLog::Level(), MLL::FileDesc::NumOfFields(), KKU::KKStr::Upper(), and x.
void MLL::NormalizationParms::Read (istream & i, bool & sucessful)
void NormalizationParms::Save (const KKStr & _fileName, bool & _successfull)
Definition at line 328 of file NormalizationParms.cpp.
References KKU::endl(), KKU::RunLog::Level(), KKU::KKStr::Str(), and Write().
double MLL::NormalizationParms::Sigma (int32 i)
const double* MLL::NormalizationParms::Sigma () inline
Definition at line 125 of file NormalizationParms.h.
FeatureVectorPtr NormalizationParms::ToNormalized (FeatureVectorPtr example) const
Definition at line 721 of file NormalizationParms.cpp.
References MLL::FeatureVector::FeatureDataAlter().
Referenced by MLL::ModelOldSVM::PrepExampleForPrediction(), and MLL::Model::PrepExampleForPrediction().
void NormalizationParms::Write (std::ostream & o)
Definition at line 357 of file NormalizationParms.cpp.
References KKU::endl().
Referenced by Save(), and MLL::Model::WriteXML().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/NormalizationParms.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/NormalizationParms.cpp