Pices: KKU::SegmentorOTSU Class Reference
KKU::SegmentorOTSU Class Reference
#include <SegmentorOTSU.h>
Public Member Functions
SegmentorOTSU (RunLog &_log)
~SegmentorOTSU ()
PixelValue ClassAverageRGB (const RasterPtr origImage, const RasterPtr segmentedImage, uchar segmentedClass)
Will compute the average RGB values of the region indiacted by teh segmented image.
template<typename T >
vector< T > CumSum (const vector< T > &v)
Returns a vector that represents the accumulatd sum of the input vector.
template<typename T >
vector< T > FlipLeftRight (const vector< T > &v)
uchar GetClassClosestToTargetColor (const RasterPtr origImage, const RasterPtr segmentedImage, const PixelValue &targetColor)
Determines wich class in the segmented image is cloaset in RGB color space to the specified target color.
RasterPtr SegmentImage (RasterPtr srcImage, int32 numClasses, double &sep)
Segments image into 'numClasses'.
RasterPtr SegmentMaskedImage (RasterPtr srcImage, RasterPtr mask, int32 numClasses, double &sep)
Segments image into 'numClasses' taking into account only pixels indicated by 'mask' image.
template<typename T >
vector< T > SubSet (const vector< T > &P, int32 start, int32 end)
template<typename T >
T Sum (const vector< T > &v)
template<typename T >
T SumSubSet (const vector< T > &P, int32 start, int32 end)
template<typename T >
void ZeroOutNaN (vector< T > &v)
Detailed Description
Author
Kurt Kramer
                                  SegmentorOTSU                                  *
                                                                                 *
Will segment an image using an implementation of OTSU. Based on MatLab code I    *
found on the Internet.  http://www.biomecardio.com/matlab/otsu.html              *
by Otsu N,                                                                       *
   <a href="matlab:web('http://dx.doi.org/doi:10.1109/TSMC.1979.4310076')">      *
   A Threshold Selection Method from Gray-Level Histograms</a>,                  *
   IEEE Trans. Syst. Man Cybern. 9:62-66;1979                                    *
See Also
raster
Definition at line 36 of file SegmentorOTSU.h.
Constructor & Destructor Documentation
SegmentorOTSU::SegmentorOTSU (RunLog & _log)
Definition at line 29 of file SegmentorOTSU.cpp.
SegmentorOTSU::~SegmentorOTSU ()
Definition at line 37 of file SegmentorOTSU.cpp.
Member Function Documentation
PixelValue SegmentorOTSU::ClassAverageRGB (const RasterPtr origImage, const RasterPtr segmentedImage, uchar segmentedClass)
Will compute the average RGB values of the region indiacted by teh segmented image.
Parameters
[in] origImage The original image that 'SegmentImage' was performed on.
[in] segmentedImage The segmented image that was returned by either 'SegmentImage' or 'SegmentMaskedImage'.
[in] segmentedClass The class in 'segmentedImage' that we want to compute average RGB for.
Definition at line 1339 of file SegmentorOTSU.cpp.
References KKU::Raster::BlueArea(), KKU::Raster::Color(), KKU::Raster::GreenArea(), KKU::Raster::RedArea(), KKU::Raster::TotPixels(), and x.
template<typename T > vector<T> KKU::SegmentorOTSU::CumSum (const vector< T > & v)
Returns a vector that represents the accumulatd sum of the input vector.
Definition at line 109 of file SegmentorOTSU.cpp.
References x.
template<typename T > vector<T> KKU::SegmentorOTSU::FlipLeftRight (const vector< T > & v)
Definition at line 255 of file SegmentorOTSU.cpp.
uchar SegmentorOTSU::GetClassClosestToTargetColor (const RasterPtr origImage, const RasterPtr segmentedImage, const PixelValue & targetColor)
Determines wich class in the segmented image is cloaset in RGB color space to the specified target color.
Parameters
[in] origImage The original image that 'SegmentImage' was performed on.
[in] segmentedImage The segmented image that was returned by either 'SegmentImage' or 'SegmentMaskedImage'.
[in] targetColor RGB Color that we want the choosen class to close to. The class that has teh average RGB value closest to targetColor.
Definition at line 1383 of file SegmentorOTSU.cpp.
References KKU::PixelValue::b, KKU::Raster::BlueArea(), KKU::Raster::Color(), KKU::PixelValue::g, KKU::Raster::GreenArea(), KKU::PixelValue::r, KKU::Raster::RedArea(), KKU::Raster::TotPixels(), and x.
RasterPtr SegmentorOTSU::SegmentImage (RasterPtr srcImage, int32 numClasses, double & sep)
Segments image into 'numClasses'.
Parameters
[in] srcImage Image to segment. If it is a color image will be converted to Grayscale using 'CreateGrayScaleKLTOnMaskedArea'
[in] numClasses Number of classes to segment image into. Current only '2' and '3' are supported.
[out] sep
Returns
Labeled grayscale image where pixels will be labels into their respective class; between '1' and 'numClasses'.
Definition at line 686 of file SegmentorOTSU.cpp.
References KKU::Raster::Color(), KKU::Raster::CreateGrayScaleKLT(), KKU::endl(), KKU::Matrix::FindMaxValue(), KKU::Raster::GreenArea(), KKU::Raster::Height(), KKU::RunLog::Level(), KKU::Raster::TotPixels(), KKU::Raster::Width(), and x.
RasterPtr SegmentorOTSU::SegmentMaskedImage (RasterPtr srcImage, RasterPtr mask, int32 numClasses, double & sep)
Segments image into 'numClasses' taking into account only pixels indicated by 'mask' image.
Parameters
[in] srcImage Image to segment. If it is a color image will be converted to Grayscale using 'CreateGrayScaleKLTOnMaskedArea'
[in] mask Indicates which pixels to consider when thresholding image. Pixels that are not part of mask will be assigned label '0'.
[in] numClasses Number of classes to segment image into. Current only '2' and '3' are supported.
[out] sep
Returns
Labeled grayscale image where pixels will be label into their respective class; between '1' and 'numClasses'.
Parameters
[in] srcImage Image to segment. If it is a color image will be converted to Grayscale using 'CreateGrayScaleKLTOnMaskedArea'
[in] mask Indictes which pixels to consider when thresholding image. Pixels that are not part of mask will be assigned label '0'.
[in] numClasses Number of classes to segment image into. Curent only '2' and '3' are supported.
[out] sep
Returns
Labeled grayscal image where pixels will be labele into their respectice class; betwen '1' and 'numClasses'.
Definition at line 1061 of file SegmentorOTSU.cpp.
References KKU::Raster::BackgroundPixelTH(), KKU::Raster::Color(), KKU::Raster::CreateGrayScaleKLT(), KKU::Raster::CreateGrayScaleKLTOnMaskedArea(), KKU::endl(), KKU::Matrix::FindMaxValue(), KKU::Raster::GreenArea(), KKU::Raster::Height(), KKU::RunLog::Level(), KKU::Raster::TotalBackgroundPixels(), KKU::Raster::TotPixels(), KKU::Raster::Width(), and x.
template<typename T > vector<T> KKU::SegmentorOTSU::SubSet (const vector< T > & P, int32 start, int32 end)
Definition at line 536 of file SegmentorOTSU.cpp.
template<typename T > T KKU::SegmentorOTSU::Sum (const vector< T > & v)
Definition at line 475 of file SegmentorOTSU.cpp.
References x.
template<typename T > T KKU::SegmentorOTSU::SumSubSet (const vector< T > & P, int32 start, int32 end)
Definition at line 550 of file SegmentorOTSU.cpp.
template<typename T > void KKU::SegmentorOTSU::ZeroOutNaN (vector< T > & v)
Definition at line 563 of file SegmentorOTSU.cpp.
References _isnan(), and x.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/SegmentorOTSU.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/SegmentorOTSU.cpp