Pices: KKU::Configuration Class Reference
KKU::Configuration Class Reference
General purpose Configuration File manager class.
#include <Configuration.h>
Classes
class ConfSection
class ConfSectionList
class Setting
class SettingList
Public Member Functions
Configuration (const KKU::KKStr &_fileName, RunLog &_log)
Configuration (RunLog &_log)
Configuration (const Configuration &c)
~Configuration ()
const KKU::KKStr & FileName () const
const VectorKKStr & FormatErrors () const
void FormatErrorsAdd (int32 lineNum, const KKStr &error)
void FormatErrorsClear ()
Call this to vlear all format error messages.
VectorKKStr FormatErrorsWithLineNumbers () const
bool FormatGood ()
void FormatGood (bool _formatGood)
void GetSetting (const char *sectiopnName, int32 settingNum, KKStrConstPtr &name, KKStrConstPtr &value, int32 &lineNum)
void LoadFile ()
int32 MemoryConsumedEstimated () const
int32 NumOfSections ()
int32 NumOfSettings (const KKU::KKStr &sectionName)
int32 NumOfSettings (int32 sectionNum) const
Returns number of settings for the specified section,.
void PrintFormatErrors (ostream &o)
bool SectionDefined (const KKU::KKStr &sectionName) const
Returns true if the section is defined.
int32 SectionLineNum (int32 sectionNum) const
KKStrConstPtr SectionName (int32 sectionNum) const
Returns the name of the section for specified index, if index not defined will return NULL.
int32 SectionNum (const KKU::KKStr &sectionName) const
KKStrConstPtr SettingName (const KKU::KKStr &sectionName, int32 settingNum) const
KKStrConstPtr SettingName (int32 sectionNum, int32 settingNum) const
KKStrConstPtr SettingValue (const KKU::KKStr &sectionName, const KKU::KKStr &settingName, int32 &lineNum) const
KKStrConstPtr SettingValue (int32 sectionNum, const KKU::KKStr &settingName, int32 &lineNum) const
KKStrConstPtr SettingValue (int32 sectionNum, int32 settingNum, int32 &lineNum) const
Detailed Description
General purpose Configuration File manager class.
This class will read and write configuration files. It understands the concept of Logical Sections and Variables. You will be able to programmatically define Sections and Settings in these sections. Each Setting will have a related value stored with it.
Example Configuration File
===========================================================
 [Header]
 ClassifierType = SVM
 Parametrs = -K RBF  -S SVC -G 1.76 -C 12
 RootDir = ${PicesHmeDir}\TraningLibraries\SimpleLibrary\
 [Class]
 Name = Copepod
 [Class]
 Name = Larvacean
===========================================================
There are three sections defined in the example above; Header, Class, and Class. Note that Section names do not have to be unique. You can access sections by name or index. If the name is not unique the first instance will be returned. Index values start at the top of the file, that is the first section to appear in the file is section index 0. The Setting names are of the format "SettingName = Value". Again you will be able to access Setting by either name or index.
Definition at line 44 of file Configuration.h.
Constructor & Destructor Documentation
Configuration::Configuration (const KKU::KKStr & _fileName, RunLog & _log)
Definition at line 286 of file Configuration.cpp.
References LoadFile().
Referenced by MemoryConsumedEstimated().
Configuration::Configuration (RunLog & _log)
Definition at line 300 of file Configuration.cpp.
Configuration::Configuration (const Configuration & c)
Definition at line 312 of file Configuration.cpp.
References KKU::Configuration::ConfSectionList::AddConfSection(), and x.
Configuration::~Configuration ()
Definition at line 333 of file Configuration.cpp.
Member Function Documentation
const KKU::KKStr& KKU::Configuration::FileName () const inline
Definition at line 87 of file Configuration.h.
const VectorKKStr& KKU::Configuration::FormatErrors () const inline
Definition at line 61 of file Configuration.h.
void Configuration::FormatErrorsAdd (int32 lineNum, const KKStr & error)
Definition at line 710 of file Configuration.cpp.
void Configuration::FormatErrorsClear ()
Call this to vlear all format error messages.
Definition at line 721 of file Configuration.cpp.
VectorKKStr Configuration::FormatErrorsWithLineNumbers () const
Definition at line 729 of file Configuration.cpp.
References KKU::StrFormatInt().
bool KKU::Configuration::FormatGood () inline
Definition at line 57 of file Configuration.h.
Referenced by LoadFile().
void KKU::Configuration::FormatGood (bool _formatGood) inline
Definition at line 59 of file Configuration.h.
void Configuration::GetSetting (const char * sectiopnName, int32 settingNum, KKStrConstPtr & name, KKStrConstPtr & value, int32 & lineNum)
Definition at line 687 of file Configuration.cpp.
References KKU::Configuration::ConfSection::GetSettings(), and KKU::Configuration::ConfSectionList::LookUp().
void Configuration::LoadFile ()
Definition at line 396 of file Configuration.cpp.
References KKU::Configuration::ConfSectionList::AddConfSection(), KKU::Configuration::ConfSection::AddSetting(), KKU::KKStr::Empty(), KKU::endl(), KKU::KKStr::FirstChar(), FormatGood(), KKU::KKStr::LastChar(), KKU::KKStr::Len(), KKU::RunLog::Level(), KKU::KKStr::LocateCharacter(), KKU::osFOPEN(), KKU::KKStr::Str(), StripOutAnyComments(), KKU::KKStr::SubStrPart(), KKU::KKStr::TrimLeft(), KKU::KKStr::TrimRight(), and KKU::KKStr::Upper().
Referenced by Configuration().
int32 Configuration::MemoryConsumedEstimated () const
Definition at line 340 of file Configuration.cpp.
References Configuration(), KKU::Configuration::ConfSectionList::MemoryConsumedEstimated(), and KKU::KKStr::MemoryConsumedEstimated().
int32 Configuration::NumOfSections ()
Definition at line 525 of file Configuration.cpp.
int32 Configuration::NumOfSettings (const KKU::KKStr & sectionName)
Definition at line 532 of file Configuration.cpp.
References KKU::Configuration::ConfSectionList::LookUp(), and KKU::Configuration::ConfSection::NumOfSettings().
int32 Configuration::NumOfSettings (int32 sectionNum) const
Returns number of settings for the specified section,.
Definition at line 545 of file Configuration.cpp.
void Configuration::PrintFormatErrors (ostream & o)
Definition at line 383 of file Configuration.cpp.
References KKU::endl().
bool Configuration::SectionDefined (const KKU::KKStr & sectionName) const
Returns true if the section is defined.
Definition at line 558 of file Configuration.cpp.
References KKU::Configuration::ConfSectionList::LookUp().
int32 Configuration::SectionLineNum (int32 sectionNum) const
Definition at line 594 of file Configuration.cpp.
References KKU::Configuration::ConfSection::LineNum().
KKStrConstPtr Configuration::SectionName (int32 sectionNum) const
Returns the name of the section for specified index, if index not defined will return NULL.
Definition at line 566 of file Configuration.cpp.
References KKU::Configuration::ConfSection::Name().
int32 Configuration::SectionNum (const KKU::KKStr & sectionName) const
Definition at line 577 of file Configuration.cpp.
Referenced by SettingValue().
KKStrConstPtr Configuration::SettingName (const KKU::KKStr & sectionName, int32 settingNum) const
Definition at line 606 of file Configuration.cpp.
References KKU::Configuration::ConfSectionList::LookUp(), and KKU::Configuration::ConfSection::SettingName().
KKStrConstPtr Configuration::SettingName (int32 sectionNum, int32 settingNum) const
Definition at line 620 of file Configuration.cpp.
KKStrConstPtr Configuration::SettingValue (const KKU::KKStr & sectionName, const KKU::KKStr & settingName, int32 & lineNum) const
Definition at line 670 of file Configuration.cpp.
References SectionNum().
KKStrConstPtr Configuration::SettingValue (int32 sectionNum, const KKU::KKStr & settingName, int32 & lineNum) const
Definition at line 636 of file Configuration.cpp.
References KKU::Configuration::ConfSection::LookUpValue().
KKStrConstPtr Configuration::SettingValue (int32 sectionNum, int32 settingNum, int32 & lineNum) const
Definition at line 652 of file Configuration.cpp.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Configuration.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Configuration.cpp