Pices: SipperFile.InstrumentDataReport Class Reference
SipperFile.InstrumentDataReport Class Reference
Summary description for InstrumentDataReport.
Public Member Functions
InstrumentDataReport (InstrumentDataManager _manager, byte _deviceId)
string CurLine ()
void Dispose ()
InstrumentDataManager Manager ()
virtual void ParseTxtBlock (ref String curLine)
virtual void ParseTxtLine (string txtLine)
void ReportData (String txt)
void ReportData (char ch)
virtual void ReportData (bool text, char ch, int curScanLine)
Detailed Description
Summary description for InstrumentDataReport.
Definition at line 8 of file InstrumentDataReport.cs.
Constructor & Destructor Documentation
SipperFile.InstrumentDataReport.InstrumentDataReport (InstrumentDataManager _manager, byte _deviceId) inline
Definition at line 18 of file InstrumentDataReport.cs.
Member Function Documentation
string SipperFile.InstrumentDataReport.CurLine () inline
Definition at line 33 of file InstrumentDataReport.cs.
Referenced by SipperFile.InstrumentDataReportText.AllMessages().
void SipperFile.InstrumentDataReport.Dispose () inline
Definition at line 28 of file InstrumentDataReport.cs.
Referenced by SipperFile.InstrumentDataManager.Dispose().
InstrumentDataManager SipperFile.InstrumentDataReport.Manager () inline
Definition at line 15 of file InstrumentDataReport.cs.
Referenced by SipperFile.InstrumentDataReportBatteryMeter.ParseTxtLine(), SipperFile.InstrumentDataReportInclination.ParseTxtLine(), SipperFile.InstrumentDataReportCTD.ParseTxtLine(), SipperFile.InstrumentDataReportIllumination.ReportData(), and SipperFile.InstrumentDataReportFlowMeter.ReportData().
virtual void SipperFile.InstrumentDataReport.ParseTxtBlock (ref String curLine) inline virtual
Reimplemented in SipperFile.InstrumentDataReportCTD.
Definition at line 100 of file InstrumentDataReport.cs.
Referenced by SipperFile.InstrumentDataReport.ReportData().
virtual void SipperFile.InstrumentDataReport.ParseTxtLine (string txtLine) inline virtual
Reimplemented in SipperFile.InstrumentDataReportCTD, SipperFile.InstrumentDataReportInclination, SipperFile.InstrumentDataReportText, SipperFile.InstrumentDataReportBatteryMeter, and SipperFile.InstrumentDataReportGPS.
Definition at line 126 of file InstrumentDataReport.cs.
Referenced by SipperFile.InstrumentDataReport.ReportData().
void SipperFile.InstrumentDataReport.ReportData (String txt) inline
Definition at line 36 of file InstrumentDataReport.cs.
References x.
Referenced by SipperFile.InstrumentDataReport.ReportData(), and SipperFile.InstrumentDataManager.ReportData().
void SipperFile.InstrumentDataReport.ReportData (char ch) inline
Definition at line 45 of file InstrumentDataReport.cs.
References SipperFile.InstrumentDataManager.LogTxtLine(), SipperFile.InstrumentDataReport.ParseTxtBlock(), and SipperFile.InstrumentDataReport.ParseTxtLine().
virtual void SipperFile.InstrumentDataReport.ReportData (bool text, char ch, int curScanLine) inline virtual
Reimplemented in SipperFile.InstrumentDataReportFlowMeter, and SipperFile.InstrumentDataReportIllumination.
Definition at line 108 of file InstrumentDataReport.cs.
References SipperFile.InstrumentDataManager.LogTxtLine(), and SipperFile.InstrumentDataReport.ReportData().
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperFile/InstrumentDataReport.cs