Pices: KKU::GoalKeeper Class Reference
KKU::GoalKeeper Class Reference
Used to deal with issues related to thread synchronization issues when sharing the same variables.
#include <GoalKeeper.h>
Public Types
typedef GoalKeeper * GoalKeeperPtr
Public Member Functions
GoalKeeper (const KKStr &_name)
Constructs a GoalKeeper object; best to do this via the GoalKeeper::Create method.
~GoalKeeper ()
bool Blocked ()
Will return true if any thread lock on this instance of "GoalKeeper".
bool BlockedByAnotherThread ()
Returns true if a different thread has this instance of "GoalKeeper" locked.
int32 BlockerThreadId ()
ThreadId of thread that currently holds the Block -1 indicates no Block.
void EndBlock ()
Ends the block and allows other threads to pass through StatBlock.
int32 MemoryConsumedEstimated () const
const KKStr & Name () const
int32 NumBlockedThreads ()
Returns the number of threads that are waiting to establish a lock on this instance.
void StartBlock ()
Initiates a Block as long as another thread has not already locked this object.
Static Public Member Functions
static void Create (const KKStr &_name, volatile GoalKeeperPtr &_newGoalKeeper)
Create a GoalKeeper object and avoid a race condition doing it.
static void CreateAndStartBlock (const KKStr &_name, volatile GoalKeeperPtr &_newGoalKeeper, bool &_didNotExistYet)
Create a GoalKeeper object and avoid a race condition doing it.
Detailed Description
Used to deal with issues related to thread synchronization issues when sharing the same variables.
Use the GoalKeeper::Create method to create an instance of this class. The Create method will ensure that two different threads don't accidently create two different instances of the same GoalKeeper object.
GoalKeeper has a concept of levels of depth. That is a particular thread may call 'StartBlock' more than once, each time doing so it would be one level deeper. In this case it would have to call 'EndBlock' an equal number of times to actually release the block. Imagine that you have a function that Starts and Ends a Block but can be called from the middle of another function that also Starts and Ends a block on the same GoalKeeper object.
This class is meant to function the same under Windows or Linux
Todo:
Has not been debugged under Linux or Solaris yet.
Definition at line 34 of file GoalKeeper.h.
Member Typedef Documentation
typedef GoalKeeper* KKU::GoalKeeper::GoalKeeperPtr
Definition at line 37 of file GoalKeeper.h.
Constructor & Destructor Documentation
GoalKeeper::GoalKeeper (const KKStr & _name)
Constructs a GoalKeeper object; best to do this via the GoalKeeper::Create method.
Definition at line 29 of file GoalKeeper.cpp.
Referenced by Create(), and CreateAndStartBlock().
GoalKeeper::~GoalKeeper ()
Definition at line 45 of file GoalKeeper.cpp.
Member Function Documentation
bool GoalKeeper::Blocked ()
Will return true if any thread lock on this instance of "GoalKeeper".
Definition at line 64 of file GoalKeeper.cpp.
bool GoalKeeper::BlockedByAnotherThread ()
Returns true if a different thread has this instance of "GoalKeeper" locked.
GoalKeeper keeps track of which thread has a lock on this instance of 'GoalKeeper'. This way we know if the calling thread is not the one to have a lock on the thread.
Definition at line 71 of file GoalKeeper.cpp.
References KKU::osGetThreadId().
int32 GoalKeeper::BlockerThreadId ()
ThreadId of thread that currently holds the Block -1 indicates no Block.
Definition at line 356 of file GoalKeeper.cpp.
References x.
void GoalKeeper::Create (const KKStr & _name, volatile GoalKeeperPtr & _newGoalKeeper) static
Create a GoalKeeper object and avoid a race condition doing it.
In case two different threads try to create the same GoalKeeper at the same time you only want one of them to succeed and the other to use same GaolKeeper object.
Parameters
[in] _name Name of Goal Keeper object that you want to create.
[in,out] _newGoalKeeper You pass this in. Create will block out the critical region that creates the GoalKeeper object. If it was already created, that is != NULL will just return not changing its value. If it is still NULL in the critical section it will create a new instance and set this parameter to its address.
Definition at line 236 of file GoalKeeper.cpp.
References KKU::endl(), and GoalKeeper().
void GoalKeeper::CreateAndStartBlock (const KKStr & _name, volatile GoalKeeperPtr & _newGoalKeeper, bool & _didNotExistYet) static
Create a GoalKeeper object and avoid a race condition doing it.
Create a new instance of a GoalKeeper object if it has not already been done and locks it if we create it.
Similar to 'Create' except it will also call the StartBlock method. There is also an additional parameter that will let you know if your call was responsible for creating it.
In case two different threads try to create the same GoalKeeper at the same time you only want one of them to succeed and the other to use same GaolKeeper object.
Parameters
[in] _name Name of Goal Keeper object that you want to create.
[in,out] _newGoalKeeper You pass this in. Create will block out the critical region that creates the GoalKeeper object. If it was already created, that is != NULL will just return not changing its value. If it is still NULL in the critical section it will create a new instance and set this parameter to its address.
[out] _didNotExistYet Indicates if this call had to create the GoalKeeper instance; if it already existed will return as false.
[in] _name Name to be assigned to GoalKeeper object.
[in,out] _newGoalKeeper A pointer to the GoalKeeper that already exists or to new one that got created.
[out] _didNotExistYet Idicates if the call to 'CreateAndStartBlock' had to create a new instance.
Definition at line 285 of file GoalKeeper.cpp.
References KKU::endl(), GoalKeeper(), and StartBlock().
void GoalKeeper::EndBlock ()
Ends the block and allows other threads to pass through StatBlock.
Decrements the variable 'blockerDepth' by one. Once 'blockerDepth' is equal zero the Block on this instance is removed. The idea is that for each time in a row a Thread calls StartBlock it has to call EndBlock the same number of times.
Definition at line 185 of file GoalKeeper.cpp.
References KKU::osGetThreadId().
Referenced by ImageExtractionManager::LogicalFrameQueue::AddBackToAvailableFrames(), ImageExtractionManager::LogicalFrameQueue::AddBackToFramesAwaitingProcessing(), ImageExtractionManager::ExtractedImageQueue::AddExtractedImage(), ImageExtractionManager::ExtractedImageQueue::AddExtractedImages(), KKU::MsgQueue::AddMsg(), KKU::RasterBuffer::AddRaster(), MLL::DataBase::Close(), MLL::DataBase::DataBase(), KKU::fftwCreateOneDPlan(), KKU::fftwCreateTwoDPlan(), KKU::fftwDestroyPlan(), SipperHardware::InstrumentData::FinalCleanUp(), ImageExtractionManager::LogicalFrameQueue::FrameProcessed(), ImageExtractionManager::LogicalFrameQueue::FramesOnQueue(), SipperHardware::InstrumentDataFileManager::GetClosestInstrumentData(), KKU::RasterBuffer::GetCopyOfLastImage(), KKU::MsgQueue::GetCopyOfLastMsg(), MLL::DataBase::GetDefaultServer(), MLL::FileDesc::GetExistingFileDesc(), SipperHardware::InstrumentData::GetFieldNum(), SipperHardware::InstrumentDataFileManager::GetFullSipperFileName(), MLL::DataBase::GetListOfServers(), SipperHardware::InstrumentDataFileManager::GetListOfSipperFiles(), ImageExtractionManager::LogicalFrameQueue::GetNextAvailaleFrame(), ImageExtractionManager::ExtractedImageQueue::GetNextExtractedImage(), ImageExtractionManager::LogicalFrameQueue::GetNextFrameToProcess(), KKU::MsgQueue::GetNextMsg(), KKU::RasterBuffer::GetNextRaster(), MLL::DataBase::GetServer(), ImageExtractionManager::ExtractedImageQueue::ImagesOnQueue(), SipperHardware::InstrumentDataFileManager::InitializePop(), SipperHardware::InstrumentDataFileManager::InitializePush(), SipperHardware::InstrumentDataFileManager::InstrumentDataFileManager(), KKU::MsgQueue::MemoryConsumedEstimated(), KKU::RasterBuffer::MemoryConsumedEstimated(), ImageExtractionManager::ExtractedImageQueue::MemoryConsumedEstimated(), ImageExtractionManager::LogicalFrameQueue::QueueFrameToProcess(), MLL::DataBase::~DataBase(), ImageExtractionManager::ExtractedImageQueue::~ExtractedImageQueue(), and SipperHardware::InstrumentDataFileManager::~InstrumentDataFileManager().
int32 GoalKeeper::MemoryConsumedEstimated () const
Definition at line 57 of file GoalKeeper.cpp.
References KKU::KKStr::MemoryConsumedEstimated().
Referenced by KKU::MsgQueue::MsgQueue(), and KKU::RasterBuffer::RasterBuffer().
const KKStr& KKU::GoalKeeper::Name () const inline
Definition at line 71 of file GoalKeeper.h.
int32 GoalKeeper::NumBlockedThreads ()
Returns the number of threads that are waiting to establish a lock on this instance.
Definition at line 347 of file GoalKeeper.cpp.
References x.
void GoalKeeper::StartBlock ()
Initiates a Block as long as another thread has not already locked this object.
If it is already blocked processor will sleep and then try again. As long as the variable 'blockerDepth'is greater than zero this instance will be considered blocked. Once a thread has the instance blocked it will increment 'blockerDepth' and return to caller.
Definition at line 105 of file GoalKeeper.cpp.
References KKU::osGetThreadId(), and KKU::osSleep().
Referenced by ImageExtractionManager::LogicalFrameQueue::AddBackToAvailableFrames(), ImageExtractionManager::LogicalFrameQueue::AddBackToFramesAwaitingProcessing(), ImageExtractionManager::ExtractedImageQueue::AddExtractedImage(), ImageExtractionManager::ExtractedImageQueue::AddExtractedImages(), KKU::MsgQueue::AddMsg(), KKU::RasterBuffer::AddRaster(), MLL::DataBase::Close(), CreateAndStartBlock(), MLL::DataBase::DataBase(), KKU::fftwCreateOneDPlan(), KKU::fftwCreateTwoDPlan(), KKU::fftwDestroyPlan(), SipperHardware::InstrumentData::FinalCleanUp(), ImageExtractionManager::LogicalFrameQueue::FrameProcessed(), ImageExtractionManager::LogicalFrameQueue::FramesOnQueue(), SipperHardware::InstrumentDataFileManager::GetClosestInstrumentData(), KKU::RasterBuffer::GetCopyOfLastImage(), KKU::MsgQueue::GetCopyOfLastMsg(), MLL::DataBase::GetDefaultServer(), MLL::FileDesc::GetExistingFileDesc(), SipperHardware::InstrumentData::GetFieldNum(), SipperHardware::InstrumentDataFileManager::GetFullSipperFileName(), MLL::DataBase::GetListOfServers(), SipperHardware::InstrumentDataFileManager::GetListOfSipperFiles(), ImageExtractionManager::LogicalFrameQueue::GetNextAvailaleFrame(), ImageExtractionManager::ExtractedImageQueue::GetNextExtractedImage(), ImageExtractionManager::LogicalFrameQueue::GetNextFrameToProcess(), KKU::MsgQueue::GetNextMsg(), KKU::RasterBuffer::GetNextRaster(), MLL::DataBase::GetServer(), ImageExtractionManager::ExtractedImageQueue::ImagesOnQueue(), SipperHardware::InstrumentDataFileManager::InitializePop(), SipperHardware::InstrumentDataFileManager::InitializePush(), SipperHardware::InstrumentDataFileManager::InstrumentDataFileManager(), KKU::MsgQueue::MemoryConsumedEstimated(), KKU::RasterBuffer::MemoryConsumedEstimated(), ImageExtractionManager::ExtractedImageQueue::MemoryConsumedEstimated(), ImageExtractionManager::LogicalFrameQueue::QueueFrameToProcess(), MLL::DataBase::~DataBase(), ImageExtractionManager::ExtractedImageQueue::~ExtractedImageQueue(), and SipperHardware::InstrumentDataFileManager::~InstrumentDataFileManager().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/GoalKeeper.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/GoalKeeper.cpp