Pices: CImageExtractionWindowsApp Class Reference
CImageExtractionWindowsApp Class Reference
#include <ImageExtractionWindows.h>
Public Member Functions
CImageExtractionWindowsApp ()
~CImageExtractionWindowsApp ()
virtual BOOL InitInstance ()
Detailed Description
Definition at line 22 of file ImageExtractionWindows.h.
Constructor & Destructor Documentation
CImageExtractionWindowsApp::CImageExtractionWindowsApp ()
Definition at line 64 of file ImageExtractionWindows.cpp.
CImageExtractionWindowsApp::~CImageExtractionWindowsApp ()
Definition at line 77 of file ImageExtractionWindows.cpp.
Member Function Documentation
BOOL CImageExtractionWindowsApp::InitInstance () virtual
< 'dlg' will take ownership of 'imageExtractionParms'.
< 'dlg' will take ownership of 'multiThreadedExtractionParms'.
Definition at line 93 of file ImageExtractionWindows.cpp.
References KKU::KKStr::Empty(), CImageExtractionWindowsDlg::ImageExtractionParms(), CImageExtractionWindowsDlg::MultiTreadedExtractionParms(), KKU::osRunAsABackGroundProcess(), and KKU::KKStr::Str().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/Apps/ImageExtractionWindows/ImageExtractionWindows.h
D:/Users/kkramer/IEC/SipperSoftware/Apps/ImageExtractionWindows/ImageExtractionWindows.cpp