Pices: MLL::ModelUsfCasCor Class Reference
MLL::ModelUsfCasCor Class Reference
#include <ModelUsfCasCor.h>
Public Types
typedef ModelUsfCasCor * ModelUsfCasCorPtr
Public Types inherited from MLL::Model
typedef Model * ModelPtr
enum ModelTypes {
mtNULL = 0, mtOldSVM = 1, mtSvmBase = 2, mtKNN = 3,
mtUsfCasCor = 4, mtDual = 5
}
Public Member Functions
ModelUsfCasCor (FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
ModelUsfCasCor (const KKStr &_name, const ModelParamUsfCasCor &_param, FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
ModelUsfCasCor (const ModelUsfCasCor &_model)
virtual ~ModelUsfCasCor ()
Frees any memory allocated by, and owned by the ModelUsfCasCor.
virtual ModelUsfCasCorPtr Duplicate () const
virtual int32 MemoryConsumedEstimated () const
virtual ModelTypes ModelType () const
virtual int32 NumOfSupportVectors () const
ModelParamUsfCasCorPtr Param ()
virtual MLClassConstPtr Predict (FeatureVectorPtr image)
virtual void Predict (FeatureVectorPtr example, MLClassConstPtr knownClass, MLClassConstPtr &predClass1, MLClassConstPtr &predClass2, int32 &predClass1Votes, int32 &predClass2Votes, double &probOfKnownClass, double &predClass1Prob, double &predClass2Prob, double &compact, int32 &numOfWinners, bool &knownClassOneOfTheWinners, double &breakTie)
virtual ClassProbListPtr ProbabilitiesByClass (FeatureVectorPtr example)
virtual void ProbabilitiesByClass (FeatureVectorPtr example, const MLClassConstList &_mlClasses, int32 *_votes, double *_probabilities)
virtual void ProbabilitiesByClass (FeatureVectorPtr _example, const MLClassConstList &_mlClasses, double *_probabilities)
Derives predicted probabilities by class.
virtual void ReadSpecificImplementationXML (istream &i, bool &_successful)
virtual void TrainModel (FeatureVectorListPtr _trainExamples, bool _alreadyNormalized, bool _takeOwnership)
Performs operations such as BitReduction, FeatureEncoding, and Normailization.
virtual void WriteSpecificImplementationXML (ostream &o)
Public Member Functions inherited from MLL::Model
Model (FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
Use this when you are planning on creating a empty model without parameters.
Model (const KKStr &_name, const ModelParam &_param, FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
Construct a instance of 'Model' using the parameters specified in '_param'.
Model (const Model &_madel)
Copy Constructor.
virtual ~Model ()
Frees any memory allocated by, and owned by the Model.
bool AlreadyNormalized () const
const KKStr & BitReductionByFeature () const
int32 BitsToReduceBy () const
const CompressionStats & Compression_Stats () const
virtual KKStr Description () const
Return short user readable description of model.
const FeatureEncoder2 & Encoder () const
virtual const FeatureNumList & GetFeatureNums () const
void Load (const KKStr &_rootFileName, bool &_successful)
virtual KKStr ModelTypeStr () const
const KKStr & Name () const
void Name (const KKStr &_name)
virtual bool NormalizeNominalAttributes () const
Return true, if nominal fields need to be normalized.
ModelParamPtr Param () const
virtual void Predict (FeatureVectorPtr example, MLClassConstPtr knownClass, MLClassConstPtr &predClass1, MLClassConstPtr &predClass2, int32 &predClass1Votes, int32 &predClass2Votes, double &probOfKnownClass, double &predClass1Prob, double &predClass2Prob, double &compact, int32 &numOfWinners, bool &knownClassOneOfTheWinners, double &breakTie)=0
virtual FeatureVectorPtr PrepExampleForPrediction (FeatureVectorPtr fv, bool &newExampleCreated)
Every prediction method in every class that is inherited from this class should call this method before performing there prediction.
virtual void ProbabilitiesByClass (FeatureVectorPtr example, const MLClassConstList &_mlClasses, int32 *_votes, double *_probabilities)=0
virtual void ProbabilitiesByClassDual (FeatureVectorPtr example, KKStr &classifier1Desc, KKStr &classifier2Desc, ClassProbListPtr &classifier1Results, ClassProbListPtr &classifier2Results)
Only applied to ModelDual classifier.
virtual void ReadXML (istream &i, bool &_successful)
Expects to read in the entire contents of a previously trainied model into this instance.
int32 ReductionPostExampleCount () const
int32 ReductionPreExampleCount () const
float ReductionRatio () const
double ReductionTime () const
virtual void RetrieveCrossProbTable (MLClassConstList &classes, double **crossProbTable)
const KKStr & RootFileName () const
void RootFileName (const KKStr &_rootFileName)
void Save (const KKStr &_rootFileName, bool &_successful)
virtual const FeatureNumList & SelectedFeatures () const
const KKU::DateTime & TimeSaved () const
double TrainingTime () const
void TrainingTimeEnd ()
Derived classes call this method to stop the clock for 'trainingTime'.
void TrainingTimeStart ()
Derived classes call this method to start the clock for 'trainingTime'.
double TrianingPrepTime () const
bool ValidModel () const
virtual void WriteXML (ostream &o)
Protected Attributes
ModelParamUsfCasCorPtr param
We will NOT own this instance.
UsfCasCorPtr usfCasCorClassifier
Protected Attributes inherited from MLL::Model
bool alreadyNormalized
volatile const bool & cancelFlag
MLClassConstListPtr classes
ClassIndexListPtr classesIndex
double * classProbs
CompressionStats compression_stats
double ** crossClassProbTable
Probabilities between Binary Classes From last Prediction.
int32 crossClassProbTableSize
FeatureEncoder2Ptr encoder
FileDescPtr fileDesc
RunLog & log
NormalizationParmsPtr normParms
int32 numOfClasses
Number of Classes defined in crossClassProbTable.
ModelParamPtr param
Will own this instance.
KKStr rootFileName
This is the root name to be used by all component objects; such as svm_model, mlClasses, and svmParam(including selected features).
FeatureVectorListPtr trainExamples
bool validModel
int32 * votes
bool weOwnTrainExamples
Indicates if we own the 'trainExamples'.
Additional Inherited Members
Static Public Member Functions inherited from MLL::Model
static ModelPtr CreateAModel (ModelTypes _modelType, const KKStr &_name, const ModelParam &_param, FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
A factory method that will instantiate the appropriate class of training model based off '_modelType'.
static ModelPtr CreateFromStream (istream &i, FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
A factory method that will instantiate the appropriate class of training model based off the contents of the istream "i".
static ModelTypes ModelTypeFromStr (const KKStr &_modelingTypeStr)
static KKStr ModelTypeToStr (ModelTypes _modelingType)
Protected Member Functions inherited from MLL::Model
void AllocatePredictionVariables ()
void DeAllocateSpace ()
void Read (istream &i, bool &_successful)
void ReadSkipToSection (istream &i, KKStr sectName, bool &sectionFound)
void ReduceTrainExamples ()
Reduces the Training Images down to the size dictated by the 'examplesPerClass' parameter.
Detailed Description
Definition at line 23 of file ModelUsfCasCor.h.
Member Typedef Documentation
typedef ModelUsfCasCor* MLL::ModelUsfCasCor::ModelUsfCasCorPtr
Definition at line 27 of file ModelUsfCasCor.h.
Constructor & Destructor Documentation
ModelUsfCasCor::ModelUsfCasCor (FileDescPtr _fileDesc, volatile const bool & _cancelFlag, RunLog & _log)
Definition at line 35 of file ModelUsfCasCor.cpp.
Referenced by Duplicate().
ModelUsfCasCor::ModelUsfCasCor (const KKStr & _name, const ModelParamUsfCasCor & _param, FileDescPtr _fileDesc, volatile const bool & _cancelFlag, RunLog & _log)
Definition at line 46 of file ModelUsfCasCor.cpp.
References param, and MLL::Model::param.
ModelUsfCasCor::ModelUsfCasCor (const ModelUsfCasCor & _model)
Definition at line 62 of file ModelUsfCasCor.cpp.
References param, MLL::Model::param, and usfCasCorClassifier.
ModelUsfCasCor::~ModelUsfCasCor () virtual
Frees any memory allocated by, and owned by the ModelUsfCasCor.
Definition at line 78 of file ModelUsfCasCor.cpp.
References usfCasCorClassifier.
Member Function Documentation
ModelUsfCasCorPtr ModelUsfCasCor::Duplicate () const virtual
Implements MLL::Model.
Definition at line 101 of file ModelUsfCasCor.cpp.
References ModelUsfCasCor().
int32 ModelUsfCasCor::MemoryConsumedEstimated () const virtual
Reimplemented from MLL::Model.
Definition at line 90 of file ModelUsfCasCor.cpp.
References MLL::UsfCasCor::MemoryConsumedEstimated(), MLL::Model::MemoryConsumedEstimated(), and usfCasCorClassifier.
virtual ModelTypes MLL::ModelUsfCasCor::ModelType () const inline virtual
Implements MLL::Model.
Definition at line 50 of file ModelUsfCasCor.h.
References MLL::Model::mtUsfCasCor.
int32 ModelUsfCasCor::NumOfSupportVectors () const virtual
Definition at line 521 of file ModelUsfCasCor.cpp.
ModelParamUsfCasCorPtr ModelUsfCasCor::Param ()
Definition at line 108 of file ModelUsfCasCor.cpp.
References param.
MLClassConstPtr ModelUsfCasCor::Predict (FeatureVectorPtr image) virtual
Implements MLL::Model.
Definition at line 191 of file ModelUsfCasCor.cpp.
References KKU::endl(), KKU::RunLog::Level(), MLL::Model::log, MLL::UsfCasCor::PredictClass(), MLL::Model::PrepExampleForPrediction(), and usfCasCorClassifier.
void ModelUsfCasCor::Predict (FeatureVectorPtr example, MLClassConstPtr knownClass, MLClassConstPtr & predClass1, MLClassConstPtr & predClass2, int32 & predClass1Votes, int32 & predClass2Votes, double & probOfKnownClass, double & predClass1Prob, double & predClass2Prob, double & compact, int32 & numOfWinners, bool & knownClassOneOfTheWinners, double & breakTie) virtual
Definition at line 214 of file ModelUsfCasCor.cpp.
References MLL::Model::classes, KKU::endl(), KKU::RunLog::Level(), MLL::Model::log, MLL::UsfCasCor::PredictConfidences(), MLL::Model::PrepExampleForPrediction(), and usfCasCorClassifier.
ClassProbListPtr ModelUsfCasCor::ProbabilitiesByClass (FeatureVectorPtr example) virtual
Implements MLL::Model.
Definition at line 278 of file ModelUsfCasCor.cpp.
References KKU::endl(), KKU::RunLog::Level(), MLL::Model::log, MLL::UsfCasCor::PredictClassConfidences(), MLL::Model::PrepExampleForPrediction(), MLL::ClassProbList::SortByProbability(), and usfCasCorClassifier.
void ModelUsfCasCor::ProbabilitiesByClass (FeatureVectorPtr example, const MLClassConstList & _mlClasses, int32 * _votes, double * _probabilities) virtual
Definition at line 306 of file ModelUsfCasCor.cpp.
References KKU::endl(), KKU::RunLog::Level(), MLL::Model::log, MLL::UsfCasCor::PredictConfidences(), MLL::Model::PrepExampleForPrediction(), usfCasCorClassifier, MLL::Model::votes, and x.
void ModelUsfCasCor::ProbabilitiesByClass (FeatureVectorPtr _example, const MLClassConstList & _mlClasses, double * _probabilities) virtual
Derives predicted probabilities by class.
Will get the probabilities assigned to each class by the classifier. The '_mlClasses' parameter dictates the order of the classes. That is the probabilities for any goven index in '_probabilities' will be for the class specifid in the same index in '_mlClasses'.
Parameters
[in] _example FeatureVector object to calculate predivcted probabilities for.
[in] _mlClasses List image classes that caller is aware of. This should be the same list that was used when consttructing this Model object. The list must be the same but not nessasarily in the same order as when Model was 1st constructed.
[out] _probabilities An array that must be as big as the number of classes as in mlClasses. The probability of class in mlClasses[x] will be returned in probabilities[x].
Implements MLL::Model.
Definition at line 382 of file ModelUsfCasCor.cpp.
References KKU::endl(), KKU::RunLog::Level(), MLL::Model::log, MLL::UsfCasCor::PredictConfidences(), MLL::Model::PrepExampleForPrediction(), usfCasCorClassifier, and x.
void ModelUsfCasCor::ReadSpecificImplementationXML (istream & i, bool & _successful) virtual
Todo:
Make sure that 'param' != NULL
Implements MLL::Model.
Definition at line 442 of file ModelUsfCasCor.cpp.
References MLL::Model::cancelFlag, KKU::endl(), KKU::KKStr::EqualIgnoreCase(), KKU::KKStr::ExtractQuotedStr(), MLL::Model::fileDesc, KKU::RunLog::Level(), MLL::UsfCasCor::LoadExistingClassifier(), MLL::Model::log, param, MLL::Model::param, MLL::Model::ReadXML(), KKU::KKStr::Upper(), usfCasCorClassifier, and MLL::Model::validModel.
void ModelUsfCasCor::TrainModel (FeatureVectorListPtr _trainExamples, bool _alreadyNormalized, bool _takeOwnership) virtual
Performs operations such as BitReduction, FeatureEncoding, and Normailization.
The actual training of models occurs in the specific implementation of 'Model'.
Parameters
_takeOwnership Model will take ownership of these examples
Reimplemented from MLL::Model.
Definition at line 115 of file ModelUsfCasCor.cpp.
References MLL::Model::cancelFlag, KKU::endl(), MLL::Model::fileDesc, MLL::ModelParamUsfCasCor::In_limit(), KKU::RunLog::Level(), MLL::Model::log, MLL::Model::Name(), MLL::ModelParamUsfCasCor::Number_of_rounds(), MLL::ModelParamUsfCasCor::Number_of_trials(), MLL::ModelParamUsfCasCor::Out_limit(), param, MLL::ModelParamUsfCasCor::Random_seed(), MLL::Model::SelectedFeatures(), KKU::KKStrException::ToString(), MLL::Model::trainExamples, MLL::Model::TrainingTimeEnd(), MLL::Model::TrainingTimeStart(), MLL::Model::TrainModel(), MLL::UsfCasCor::TrainNewClassifier(), MLL::ModelParamUsfCasCor::UseCache(), usfCasCorClassifier, and MLL::Model::validModel.
void ModelUsfCasCor::WriteSpecificImplementationXML (ostream & o) virtual
Implements MLL::Model.
Definition at line 506 of file ModelUsfCasCor.cpp.
References KKU::endl(), KKU::RunLog::Level(), MLL::Model::log, usfCasCorClassifier, and MLL::UsfCasCor::WriteXML().
Member Data Documentation
ModelParamUsfCasCorPtr MLL::ModelUsfCasCor::param protected
We will NOT own this instance.
It will point to same instance defined in parent class Model.
Definition at line 130 of file ModelUsfCasCor.h.
Referenced by ModelUsfCasCor(), Param(), ReadSpecificImplementationXML(), and TrainModel().
UsfCasCorPtr MLL::ModelUsfCasCor::usfCasCorClassifier protected
Definition at line 129 of file ModelUsfCasCor.h.
Referenced by MemoryConsumedEstimated(), ModelUsfCasCor(), Predict(), ProbabilitiesByClass(), ReadSpecificImplementationXML(), TrainModel(), WriteSpecificImplementationXML(), and ~ModelUsfCasCor().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ModelUsfCasCor.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ModelUsfCasCor.cpp