Pices: SipperFile.SipperBuff4Bit Class Reference
SipperFile.SipperBuff4Bit Class Reference
Classes
class DecodeOpRec
class DecodeRawByte
Public Member Functions
SipperBuff4Bit (string _fileName, InstrumentDataManager _instrumentDataManager)
SipperBuff4Bit (Stream _stream, InstrumentDataManager _instrumentDataManager)
override void Dispose ()
override int LengthNextScanLine ()
override void ReadNextScanLine (byte[] scanLine)
override void SkipNextScanLine ()
Public Member Functions inherited from SipperFile.SipperBaseFile
SipperBaseFile (Stream _stream, InstrumentDataManager _instrumentDataManager)
SipperBaseFile (string _fileName, InstrumentDataManager _instrumentDataManager)
byte[][] AllocateFrame ()
byte[][] CreateRatser (int scanLineStart, int numScanLines)
bool Eof ()
bool EofReached ()
virtual long EstimatedNumberOfScanLines ()
long FileSizeInBytes ()
void FrameBytesOffsetsUpdateThreadStart (InstrumentDataList _history)
void FrameBytesOffsetsUpdateThreadTerminate ()
void FrameRead (int frameNum, SipperFrame frame, ref bool found)
int LargestKnowmFrameNum ()
long LargestKnownScanLine ()
void ReadNextFrame (byte[][] frame)
virtual int ScanLineSize ()
bool ValidateFormat ()
Additional Inherited Members
Public Attributes inherited from SipperFile.SipperBaseFile
const int PixelsPerScanLine = 4096
const int ScanLinesPerFrame = 4096
Protected Member Functions inherited from SipperFile.SipperBaseFile
byte[] GetNextBuff (uint buffLen)
byte GetNextByte ()
ushort GetNextRecord ()
uint GetNextUint ()
Protected Attributes inherited from SipperFile.SipperBaseFile
bool eof = false
InstrumentDataManager instrumentDataManager = null
long lastScanLineNum = 0
Detailed Description
Definition at line 14 of file SipperBuff4Bit.cs.
Constructor & Destructor Documentation
SipperFile.SipperBuff4Bit.SipperBuff4Bit (string _fileName, InstrumentDataManager _instrumentDataManager) inline
Definition at line 188 of file SipperBuff4Bit.cs.
SipperFile.SipperBuff4Bit.SipperBuff4Bit (Stream _stream, InstrumentDataManager _instrumentDataManager) inline
Definition at line 200 of file SipperBuff4Bit.cs.
Member Function Documentation
override void SipperFile.SipperBuff4Bit.Dispose () inline virtual
Reimplemented from SipperFile.SipperBaseFile.
Definition at line 213 of file SipperBuff4Bit.cs.
override int SipperFile.SipperBuff4Bit.LengthNextScanLine () inline virtual
Reimplemented from SipperFile.SipperBaseFile.
Definition at line 283 of file SipperBuff4Bit.cs.
References SipperFile.SipperBuff4Bit.DecodeOpRec.bytesToReadHighOrder, SipperFile.SipperBaseFile.eof, SipperFile.SipperBaseFile.GetNextBuff(), SipperFile.SipperBaseFile.GetNextByte(), SipperFile.SipperBuff4Bit.DecodeRawByte.lower4Bits, SipperFile.SipperBuff4Bit.DecodeOpRec.opCode, SipperFile.SipperBuff4Bit.DecodeOpRec.rawStringBytesToRead, SipperFile.SipperBuff4Bit.DecodeOpRec.rawStringLen, SipperFile.SipperBuff4Bit.DecodeOpRec.runLength, and x.
Referenced by SipperFile.SipperBuff4Bit.SkipNextScanLine().
override void SipperFile.SipperBuff4Bit.ReadNextScanLine (byte[] scanLine) inline virtual
Reimplemented from SipperFile.SipperBaseFile.
Definition at line 400 of file SipperBuff4Bit.cs.
References SipperFile.SipperBuff4Bit.DecodeOpRec.bytesToReadHighOrder, SipperFile.SipperBaseFile.eof, SipperFile.SipperBaseFile.GetNextBuff(), SipperFile.SipperBaseFile.GetNextByte(), SipperFile.SipperBuff4Bit.DecodeRawByte.lower4Bits, SipperFile.SipperBuff4Bit.DecodeOpRec.opCode, SipperFile.SipperBuff4Bit.DecodeRawByte.pixel1, SipperFile.SipperBuff4Bit.DecodeOpRec.rawPixel, SipperFile.SipperBuff4Bit.DecodeOpRec.rawStringBytesToRead, SipperFile.SipperBuff4Bit.DecodeOpRec.runLength, SipperFile.SipperBuff4Bit.DecodeOpRec.runLengthChar, and x.
override void SipperFile.SipperBuff4Bit.SkipNextScanLine () inline virtual
Reimplemented from SipperFile.SipperBaseFile.
Definition at line 393 of file SipperBuff4Bit.cs.
References SipperFile.SipperBuff4Bit.LengthNextScanLine().
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperFile/SipperBuff4Bit.cs