Pices: MLL::BinaryClassParmsList Class Reference
MLL::BinaryClassParmsList Class Reference
#include <BinaryClassParms.h>
Public Types
typedef BinaryClassParmsList * BinaryClassParmsListPtr
Public Member Functions
BinaryClassParmsList (bool _owner, int32 _size)
BinaryClassParmsList (const BinaryClassParmsList &binaryClassList, bool _owner)
~BinaryClassParmsList ()
BinaryClassParmsList * DuplicateListAndContents () const
float FeatureCountNet () const
Returns the Average number of selected features.
BinaryClassParmsPtr LookUp (MLClassConstPtr _class1, MLClassConstPtr _class2) const
int32 MemoryConsumedEstimated () const
void ReadXML (FILE *i, FileDescPtr fileDesc, RunLog &log)
void ReadXML (istream &i, FileDescPtr fileDesc, RunLog &log)
void WriteXML (ostream &o) const
Static Public Member Functions
static BinaryClassParmsListPtr CreateFromXML (istream &i, FileDescPtr fileDesc, RunLog &log)
static BinaryClassParmsListPtr CreateFromXML (FILE *i, FileDescPtr fileDesc, RunLog &log)
Detailed Description
Definition at line 104 of file BinaryClassParms.h.
Member Typedef Documentation
typedef BinaryClassParmsList* MLL::BinaryClassParmsList::BinaryClassParmsListPtr
Definition at line 107 of file BinaryClassParms.h.
Constructor & Destructor Documentation
MLL::BinaryClassParmsList::BinaryClassParmsList (bool _owner, int32 _size)
Referenced by DuplicateListAndContents(), and MemoryConsumedEstimated().
BinaryClassParmsList::BinaryClassParmsList (const BinaryClassParmsList & binaryClassList, bool _owner)
Definition at line 175 of file BinaryClassParms.cpp.
BinaryClassParmsList::~BinaryClassParmsList ()
Definition at line 184 of file BinaryClassParms.cpp.
Member Function Documentation
static BinaryClassParmsListPtr MLL::BinaryClassParmsList::CreateFromXML (istream & i, FileDescPtr fileDesc, RunLog & log) static
Referenced by MLL::SVMparam::ReadXML().
static BinaryClassParmsListPtr MLL::BinaryClassParmsList::CreateFromXML (FILE * i, FileDescPtr fileDesc, RunLog & log) static
BinaryClassParmsListPtr BinaryClassParmsList::DuplicateListAndContents () const
Definition at line 275 of file BinaryClassParms.cpp.
References BinaryClassParmsList().
Referenced by MLL::SVMparam::SVMparam().
float BinaryClassParmsList::FeatureCountNet () const
Returns the Average number of selected features.
Definition at line 224 of file BinaryClassParms.cpp.
References MLL::FeatureNumList::NumSelFeatures(), and MLL::BinaryClassParms::SelectedFeatures().
BinaryClassParmsPtr BinaryClassParmsList::LookUp (MLClassConstPtr _class1, MLClassConstPtr _class2) const
Definition at line 245 of file BinaryClassParms.cpp.
References MLL::BinaryClassParms::Class1(), and MLL::BinaryClassParms::Class2().
Referenced by MLL::ModelParamOldSVM::C_Param(), MLL::SVMparam::C_Param(), MLL::SVMparam::GetBinaryClassParms(), MLL::SVMparam::GetFeatureNums(), MLL::SVMparam::GetParamtersToUseFor2ClassCombo(), MLL::SVMparam::SetBinaryClassFields(), and MLL::SVMparam::SetFeatureNums().
int32 BinaryClassParmsList::MemoryConsumedEstimated () const
Definition at line 189 of file BinaryClassParms.cpp.
References BinaryClassParmsList().
Referenced by MLL::SVMparam::MemoryConsumedEstimated().
void MLL::BinaryClassParmsList::ReadXML (FILE * i, FileDescPtr fileDesc, RunLog & log)
void MLL::BinaryClassParmsList::ReadXML (istream & i, FileDescPtr fileDesc, RunLog & log)
void BinaryClassParmsList::WriteXML (ostream & o) const
Definition at line 291 of file BinaryClassParms.cpp.
References KKU::endl().
Referenced by MLL::SVMparam::WriteXML().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/BinaryClassParms.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/BinaryClassParms.cpp