Pices: MLL::DataBaseImageValidatedEntryList Class Reference
MLL::DataBaseImageValidatedEntryList Class Reference
#include <DataBaseImageValidatedEntry.h>
Public Types
typedef
DataBaseImageValidatedEntryList * DataBaseImageValidatedEntryListPtr
Public Member Functions
DataBaseImageValidatedEntryList (bool _owner=true)
DataBaseImageValidatedEntryList (const KKStr &_fileName, RunLog &log)
~DataBaseImageValidatedEntryList ()
void Load (const KKStr &_fileName, RunLog &log)
void Save (const KKStr &_fileName, RunLog &log)
Detailed Description
Definition at line 67 of file DataBaseImageValidatedEntry.h.
Member Typedef Documentation
typedef DataBaseImageValidatedEntryList* MLL::DataBaseImageValidatedEntryList::DataBaseImageValidatedEntryListPtr
Definition at line 70 of file DataBaseImageValidatedEntry.h.
Constructor & Destructor Documentation
DataBaseImageValidatedEntryList::DataBaseImageValidatedEntryList (bool _owner = true)
Definition at line 93 of file DataBaseImageValidatedEntry.cpp.
MLL::DataBaseImageValidatedEntryList::DataBaseImageValidatedEntryList (const KKStr & _fileName, RunLog & log)
DataBaseImageValidatedEntryList::~DataBaseImageValidatedEntryList ()
Definition at line 118 of file DataBaseImageValidatedEntry.cpp.
Member Function Documentation
void DataBaseImageValidatedEntryList::Load (const KKStr & _fileName, RunLog & log)
Definition at line 162 of file DataBaseImageValidatedEntry.cpp.
References MLL::MLClass::CreateNewMLClass(), KKU::endl(), KKU::KKStr::EqualIgnoreCase(), KKU::KKStr::ExtractToken2(), KKU::RunLog::Level(), KKU::osReadRestOfLine(), KKU::KKStr::StartsWith(), and KKU::KKStr::Str().
void DataBaseImageValidatedEntryList::Save (const KKStr & _fileName, RunLog & log)
Definition at line 124 of file DataBaseImageValidatedEntry.cpp.
References KKU::endl(), MLL::DataBaseImageValidatedEntry::ImageFileName(), KKU::RunLog::Level(), KKU::osGetHostName(), KKU::osGetLocalDateTime(), MLL::DataBaseImageValidatedEntry::SizeCoordinatesDelStr(), KKU::KKStr::Str(), and MLL::DataBaseImageValidatedEntry::ValidatedClassName().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/DataBaseImageValidatedEntry.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/DataBaseImageValidatedEntry.cpp