Pices: MLL::Orderings Class Reference
MLL::Orderings Class Reference
Used to maintain multiple orderings of a single list of FeatureVector objects.
#include <Orderings.h>
Public Types
typedef Orderings * OrderingsPtr
Public Member Functions
Orderings (const FeatureVectorListPtr _data, uint32 _numOfOrderings, uint32 _numOfFolds)
Constructs Orderings object from ImageFeatursList object.
Orderings (const KKStr &_featureFileName, FeatureFileIOPtr _driver, RunLog &_log, bool &cancelFlag)
Constructs Orderings of a FeatureVectorList from a previous construction that was saved in a data file.
Orderings (const FeatureVectorListPtr _data, const KKStr &_indexFileName, uint32 _numOfOrderings, uint32 _numOfFolds)
Constructs a Orderings object from a FeatureLectorList object.
Orderings (FeatureVectorListPtr _data)
Constructs a Orderings objects for a specified FeatureVectorList using a previously built Orderings data index file.
~Orderings ()
FeatureVectorListPtr Data () const
const KKStr & FeatureFileName () const
const FileDescPtr FileDesc () const
const KKStr & IndexFileName () const
RunLog & Log ()
const MLClassConstListPtr MLClasses () const
uint32 NumOfFolds () const
uint32 NumOfOrderings () const
const FeatureVectorListPtr Ordering (uint32 orderingIdx) const
void Save ()
void Save (const KKStr &_indexFileName)
uint32 Size () const
bool Valid () const
Static Public Member Functions
static OrderingsPtr CreateOrderingsObjFromFileIfAvaliable (const FeatureVectorListPtr _data, uint32 _numOfOrderings, uint32 _numOfFolds)
Constructs a Orderings object for a specified FeatureVectorList.
Detailed Description
Used to maintain multiple orderings of a single list of FeatureVector objects.
Author
Kurt Kramer
Will maintain multiple orderings of a single FeatureVectorList. These orderings will be saved in a text file for recall later. This will allow the user to beable to repeat experiments using the same ordering of data again. The Idea is that the 1st time this orderings is created the order will be randomly driven with Stratification by Class. This ordering will then be saved in data Files for future recall. More than one order can be maintained for a single list. An example of a good use of this is RandomSplits.
Definition at line 67 of file Orderings.h.
Member Typedef Documentation
typedef Orderings* MLL::Orderings::OrderingsPtr
Definition at line 71 of file Orderings.h.
Constructor & Destructor Documentation
Orderings::Orderings (const FeatureVectorListPtr _data, uint32 _numOfOrderings, uint32 _numOfFolds)
Constructs Orderings object from ImageFeatursList object.
Use this when an existing list does not exist. Will create 'numOfOrderings' seperate lists of 'data' that are randomly ordered and stratified by 'numOfFolds'.
Parameters
[in] _data ImagFeaturesList object,
[in] _numOfOrderings Number of seperate orderings of data neeed.
[in] _numOfFolds Used to help stratify data in each fold.
Definition at line 27 of file Orderings.cpp.
References KKU::KKStr::Empty(), MLL::FeatureVectorList::FileName(), and KKU::osRemoveExtension().
Referenced by CreateOrderingsObjFromFileIfAvaliable().
MLL::Orderings::Orderings (const KKStr & _featureFileName, FeatureFileIOPtr _driver, RunLog & _log, bool & cancelFlag)
Constructs Orderings of a FeatureVectorList from a previous construction that was saved in a data file.
Will load object from the Feature File '_featureFileName' and retrieve the different orderings from a separate index file whos name will be osExtention (FeatureFileName) + ".idx". The load routine will validate that all imageFeatures objects are accounted for in each ordering. If the index file does not exist it then the 'successful' flag will bet to false.
Parameters
[in] _featureFileName File to load FeatureVector' objects from. This will be used as master list for 'Orderings'.
[in] _driver Feature File driver toutilize.
[in] _log Log file to write messages to.
[in] v If flag tturns to 'TRUE' then will terminate the load process and return to caller.
MLL::Orderings::Orderings (const FeatureVectorListPtr _data, const KKStr & _indexFileName, uint32 _numOfOrderings, uint32 _numOfFolds)
Constructs a Orderings object from a FeatureLectorList object.
Will use 'data' as master list of FeatureVector objects.The orderings will be loaded from 'indexFileName'. It is expected that the size of the files will match. The load routine will validate that all FeatureVector objects are accounted for in each ordering.
Parameters
[in] _data Master List of Imagefeatures objects.
[in] _indexFileName File where orderings of 'data' are to be loaded from.
[in] _numOfOrderings
[in] _numOfFolds
Orderings::Orderings (FeatureVectorListPtr _data)
Constructs a Orderings objects for a specified FeatureVectorList using a previously built Orderings data index file.
Will use FileName from "data" parameter to derive both 'featureFileName' and 'indexFileName' using the 'FileName' method from FeatureVectorList. It is expected that a seperate index file by the name osDeletExtention (FeatureFileName) + ".idx" will exist. The orderings will be loaded from that file.
Parameters
[in] _data FeatureVectorList that we want different orderings of.
Definition at line 79 of file Orderings.cpp.
References KKU::KKStr::Empty(), KKU::endl(), MLL::FeatureVectorList::FileName(), KKU::RunLog::Level(), and KKU::osRemoveExtension().
Orderings::~Orderings ()
Definition at line 187 of file Orderings.cpp.
Member Function Documentation
OrderingsPtr Orderings::CreateOrderingsObjFromFileIfAvaliable (const FeatureVectorListPtr _data, uint32 _numOfOrderings, uint32 _numOfFolds) static
Constructs a Orderings object for a specified FeatureVectorList.
Will use FileName from "_data" parameter to derive both 'featureFileName' and 'indexFileName' using the 'FileName' method from FeatureVectorList. If a separate Index file does not exist it will randomly xcreate orderings and save the orderings in a new Index file.
Parameters
[in] _data FeatureVectorList that we want different orderings of.
[in] _numOfOrderings Expected number of orderings.
[in] _numOfFolds Number of folds each ordering should be straitified by.
Definition at line 195 of file Orderings.cpp.
References KKU::KKStr::Empty(), KKU::endl(), MLL::FeatureVectorList::FileName(), KKU::RunLog::Level(), MLL::FeatureVectorList::Log(), NumOfFolds(), NumOfOrderings(), Orderings(), KKU::osRemoveExtension(), Save(), and Valid().
FeatureVectorListPtr MLL::Orderings::Data () const inline
Definition at line 165 of file Orderings.h.
const KKStr& MLL::Orderings::FeatureFileName () const inline
Definition at line 166 of file Orderings.h.
const FileDescPtr MLL::Orderings::FileDesc () const inline
Definition at line 167 of file Orderings.h.
const KKStr& MLL::Orderings::IndexFileName () const inline
Definition at line 169 of file Orderings.h.
RunLog& MLL::Orderings::Log () inline
Definition at line 170 of file Orderings.h.
const MLClassConstListPtr MLL::Orderings::MLClasses () const inline
Definition at line 168 of file Orderings.h.
Referenced by MLL::CrossValidationMxN::RunTrainAndTest(), and MLL::CrossValidationMxN::RunValidations().
uint32 MLL::Orderings::NumOfFolds () const inline
Definition at line 171 of file Orderings.h.
Referenced by CreateOrderingsObjFromFileIfAvaliable().
uint32 MLL::Orderings::NumOfOrderings () const inline
Definition at line 172 of file Orderings.h.
Referenced by CreateOrderingsObjFromFileIfAvaliable().
const FeatureVectorListPtr Orderings::Ordering (uint32 orderingIdx) const
Definition at line 619 of file Orderings.cpp.
References KKU::RunLog::Level(), and KKU::osWaitForEnter().
Referenced by MLL::CrossValidationMxN::RunTrainAndTest(), and MLL::CrossValidationMxN::RunValidations().
void Orderings::Save ()
Definition at line 551 of file Orderings.cpp.
References KKU::KKStr::Empty(), KKU::endl(), index(), KKU::RunLog::Level(), KKU::osGetLocalDateTime(), KKU::osWaitForEnter(), and KKU::KKStr::Str().
Referenced by CreateOrderingsObjFromFileIfAvaliable().
void MLL::Orderings::Save (const KKStr & _indexFileName)
uint32 MLL::Orderings::Size () const inline
Definition at line 173 of file Orderings.h.
bool MLL::Orderings::Valid () const inline
Definition at line 174 of file Orderings.h.
Referenced by CreateOrderingsObjFromFileIfAvaliable().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/Orderings.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/Orderings.cpp