Pices: MLL::ModelParamKnn Class Reference
MLL::ModelParamKnn Class Reference
#include <ModelParamKnn.h>
Public Types
typedef ModelParamKnn * ModelParamKnnPtr
Public Types inherited from MLL::ModelParam
enum CompressionMethodType {
BRNull, BRnoCompression, BRcompressionPost, BRcompressionPre,
BRunBalancedVariance, BRunBalancedSpecified
}
enum EncodingMethodType { NoEncoding, BinaryEncoding, ScaledEncoding, Encoding_NULL }
typedef ModelParam * ModelParamPtr
enum ModelParamTypes {
mptNULL, mptDual, mptKNN, mptOldSVM,
mptSvmBase, mptUsfCasCor
}
Public Member Functions
ModelParamKnn (FileDescPtr _fileDesc, RunLog &_log)
ModelParamKnn (const ModelParamKnn &_param)
virtual ~ModelParamKnn ()
virtual ModelParamKnnPtr Duplicate () const
virtual ModelParamTypes ModelParamType () const
virtual void ReadSpecificImplementationXML (istream &i)
virtual KKStr ToCmdLineStr () const
Createsa a Command Line String that represents these parameters.
virtual void WriteSpecificImplementationXML (std::ostream &o) const
Public Member Functions inherited from MLL::ModelParam
ModelParam (FileDescPtr _fileDesc, RunLog &_log)
ModelParam (const ModelParam &_param)
virtual ~ModelParam ()
virtual float A_Param () const
virtual void A_Param (float _prob)
virtual float AvgMumOfFeatures () const
virtual int32 BitsToReduceBy () const
virtual void BitsToReduceBy (int32 _bitsToReduceBy)
virtual double C_Param () const
virtual void C_Param (double _cost)
virtual CompressionMethodType CompressionMethod () const
virtual void CompressionMethod (CompressionMethodType _compMethod)
virtual KKStr CompressionMethodStr () const
virtual double Cost () const
virtual void Cost (double _cost)
virtual EncodingMethodType EncodingMethod () const
virtual void EncodingMethod (EncodingMethodType _encodingMethod)
virtual KKStr EncodingMethodStr () const
virtual int32 ExamplesPerClass () const
virtual void ExamplesPerClass (int32 _examplesPerClass)
virtual const KKStr & FileName () const
virtual void FileName (const KKStr &_fileName)
virtual double Gamma () const
virtual void Gamma (double _gamma)
virtual int32 MemoryConsumedEstimated () const
virtual KKStr ModelParamTypeStr () const
virtual bool NormalizeNominalFeatures () const
virtual int32 NumOfFeaturesAfterEncoding () const
virtual void ParseCmdLine (KKStr _cmdLineStr, bool &_validFormat)
virtual void ParseCmdLinePost ()
Called after 'ParseCmdLine' is completed.
virtual float Prob () const
virtual void Prob (float _prob)
virtual void ReadXML (KKStr &_fileName, bool &_successful)
virtual void ReadXML (istream &i)
virtual const FeatureNumList & SelectedFeatures () const
virtual void SelectedFeatures (const FeatureNumList &_selectedFeatures)
virtual int32 UnBalancedBits () const
virtual void UnBalancedBits (int32 _unBalancedBits)
virtual KKStr UnBalancedBitsStr () const
virtual void UnBalancedBitsStr (const KKStr &_unBalancedBitsStr)
virtual bool ValidParam () const
virtual void ValidParam (bool _validParam)
virtual bool WeightBitReduction () const
virtual void WeightBitReduction (bool _weightBitReduction)
virtual void WriteXML (std::ostream &o) const
Additional Inherited Members
Static Public Member Functions inherited from MLL::ModelParam
static CompressionMethodType CompressionMethodFromStr (const KKStr &compressionMethodStr)
static KKStr CompressionMethodToStr (CompressionMethodType compressionMethod)
static ModelParamPtr CreateModelParam (istream &i, FileDescPtr _fileDesc, RunLog &_log)
static EncodingMethodType EncodingMethodFromStr (const KKStr &encodingMethodStr)
static KKStr EncodingMethodToStr (EncodingMethodType encodingMethod)
static ModelParamTypes ModelParamTypeFromStr (const KKStr &_modelParamTypeStr)
static KKStr ModelParamTypeToStr (ModelParamTypes _modelParamType)
Protected Attributes inherited from MLL::ModelParam
FileDescPtr fileDesc
RunLog & log
Detailed Description
Definition at line 8 of file ModelParamKnn.h.
Member Typedef Documentation
typedef ModelParamKnn* MLL::ModelParamKnn::ModelParamKnnPtr
Definition at line 11 of file ModelParamKnn.h.
Constructor & Destructor Documentation
MLL::ModelParamKnn::ModelParamKnn (FileDescPtr _fileDesc, RunLog & _log)
Referenced by Duplicate().
ModelParamKnn::ModelParamKnn (const ModelParamKnn & _param)
Definition at line 46 of file ModelParamKnn.cpp.
ModelParamKnn::~ModelParamKnn () virtual
Definition at line 54 of file ModelParamKnn.cpp.
Member Function Documentation
ModelParamKnnPtr ModelParamKnn::Duplicate () const virtual
Implements MLL::ModelParam.
Definition at line 61 of file ModelParamKnn.cpp.
References ModelParamKnn().
virtual ModelParamTypes MLL::ModelParamKnn::ModelParamType () const inline virtual
Implements MLL::ModelParam.
Definition at line 28 of file ModelParamKnn.h.
References MLL::ModelParam::mptKNN.
void ModelParamKnn::ReadSpecificImplementationXML (istream & i) virtual
Implements MLL::ModelParam.
Definition at line 112 of file ModelParamKnn.cpp.
References KKU::endl(), KKU::KKStr::EqualIgnoreCase(), KKU::KKStr::ExtractQuotedStr(), KKU::KKStr::ExtractToken2(), KKU::RunLog::Level(), MLL::ModelParam::log, MLL::ModelParam::ReadXML(), KKU::KKStr::ToInt(), and KKU::KKStr::Upper().
KKStr ModelParamKnn::ToCmdLineStr () const virtual
Createsa a Command Line String that represents these parameters.
Reimplemented from MLL::ModelParam.
Definition at line 69 of file ModelParamKnn.cpp.
References KKU::StrFormatInt(), and MLL::ModelParam::ToCmdLineStr().
void ModelParamKnn::WriteSpecificImplementationXML (std::ostream & o) const virtual
Implements MLL::ModelParam.
Definition at line 103 of file ModelParamKnn.cpp.
References KKU::endl().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ModelParamKnn.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ModelParamKnn.cpp