Pices: MLL::ModelParamDual Class Reference
MLL::ModelParamDual Class Reference
                      Parameters used for the Dual Classifier.
#include <ModelParamDual.h>
Public Types
typedef ModelParamDual * ModelParamDualPtr
Public Types inherited from MLL::ModelParam
enum CompressionMethodType {
BRNull, BRnoCompression, BRcompressionPost, BRcompressionPre,
BRunBalancedVariance, BRunBalancedSpecified
}
enum EncodingMethodType { NoEncoding, BinaryEncoding, ScaledEncoding, Encoding_NULL }
typedef ModelParam * ModelParamPtr
enum ModelParamTypes {
mptNULL, mptDual, mptKNN, mptOldSVM,
mptSvmBase, mptUsfCasCor
}
Public Member Functions
ModelParamDual (FileDescPtr _fileDesc, RunLog &_log)
ModelParamDual (FileDescPtr _fileDesc, const KKStr &_configFileName1, const KKStr &_configFileName2, bool _fullHierarchyMustMatch, RunLog &_log)
ModelParamDual (const ModelParamDual &_param)
virtual ~ModelParamDual ()
const KKStr & ConfigFileName1 () const
const KKStr & ConfigFileName2 () const
virtual ModelParamDualPtr Duplicate () const
bool FullHierarchyMustMatch () const
virtual ModelParamTypes ModelParamType () const
MLClassPtr OtherClass () const
void OtherClass (MLClassPtr _otherClass)
virtual void ReadSpecificImplementationXML (istream &i)
virtual KKStr ToCmdLineStr () const
Creates a Command Line String that represents these parameters.
virtual void WriteSpecificImplementationXML (std::ostream &o) const
Public Member Functions inherited from MLL::ModelParam
ModelParam (FileDescPtr _fileDesc, RunLog &_log)
ModelParam (const ModelParam &_param)
virtual ~ModelParam ()
virtual float A_Param () const
virtual void A_Param (float _prob)
virtual float AvgMumOfFeatures () const
virtual int32 BitsToReduceBy () const
virtual void BitsToReduceBy (int32 _bitsToReduceBy)
virtual double C_Param () const
virtual void C_Param (double _cost)
virtual CompressionMethodType CompressionMethod () const
virtual void CompressionMethod (CompressionMethodType _compMethod)
virtual KKStr CompressionMethodStr () const
virtual double Cost () const
virtual void Cost (double _cost)
virtual EncodingMethodType EncodingMethod () const
virtual void EncodingMethod (EncodingMethodType _encodingMethod)
virtual KKStr EncodingMethodStr () const
virtual int32 ExamplesPerClass () const
virtual void ExamplesPerClass (int32 _examplesPerClass)
virtual const KKStr & FileName () const
virtual void FileName (const KKStr &_fileName)
virtual double Gamma () const
virtual void Gamma (double _gamma)
virtual int32 MemoryConsumedEstimated () const
virtual KKStr ModelParamTypeStr () const
virtual bool NormalizeNominalFeatures () const
virtual int32 NumOfFeaturesAfterEncoding () const
virtual void ParseCmdLine (KKStr _cmdLineStr, bool &_validFormat)
virtual float Prob () const
virtual void Prob (float _prob)
virtual void ReadXML (KKStr &_fileName, bool &_successful)
virtual void ReadXML (istream &i)
virtual const FeatureNumList & SelectedFeatures () const
virtual void SelectedFeatures (const FeatureNumList &_selectedFeatures)
virtual int32 UnBalancedBits () const
virtual void UnBalancedBits (int32 _unBalancedBits)
virtual KKStr UnBalancedBitsStr () const
virtual void UnBalancedBitsStr (const KKStr &_unBalancedBitsStr)
virtual bool ValidParam () const
virtual void ValidParam (bool _validParam)
virtual bool WeightBitReduction () const
virtual void WeightBitReduction (bool _weightBitReduction)
virtual void WriteXML (std::ostream &o) const
Additional Inherited Members
Static Public Member Functions inherited from MLL::ModelParam
static CompressionMethodType CompressionMethodFromStr (const KKStr &compressionMethodStr)
static KKStr CompressionMethodToStr (CompressionMethodType compressionMethod)
static ModelParamPtr CreateModelParam (istream &i, FileDescPtr _fileDesc, RunLog &_log)
static EncodingMethodType EncodingMethodFromStr (const KKStr &encodingMethodStr)
static KKStr EncodingMethodToStr (EncodingMethodType encodingMethod)
static ModelParamTypes ModelParamTypeFromStr (const KKStr &_modelParamTypeStr)
static KKStr ModelParamTypeToStr (ModelParamTypes _modelParamType)
Protected Attributes inherited from MLL::ModelParam
FileDescPtr fileDesc
RunLog & log
Detailed Description
                      Parameters used for the Dual Classifier.
                        *
See Also
Model
Definition at line 17 of file ModelParamDual.h.
Member Typedef Documentation
typedef ModelParamDual* MLL::ModelParamDual::ModelParamDualPtr
Definition at line 20 of file ModelParamDual.h.
Constructor & Destructor Documentation
MLL::ModelParamDual::ModelParamDual (FileDescPtr _fileDesc, RunLog & _log)
Referenced by Duplicate().
MLL::ModelParamDual::ModelParamDual (FileDescPtr _fileDesc, const KKStr & _configFileName1, const KKStr & _configFileName2, bool _fullHierarchyMustMatch, RunLog & _log)
ModelParamDual::ModelParamDual (const ModelParamDual & _param)
Definition at line 68 of file ModelParamDual.cpp.
ModelParamDual::~ModelParamDual () virtual
Definition at line 79 of file ModelParamDual.cpp.
Member Function Documentation
const KKStr& MLL::ModelParamDual::ConfigFileName1 () const inline
Definition at line 38 of file ModelParamDual.h.
Referenced by MLL::ModelDual::ReadSpecificImplementationXML(), MLL::ModelDual::ReconcilePredictions(), and MLL::ModelDual::TrainModel().
const KKStr& MLL::ModelParamDual::ConfigFileName2 () const inline
Definition at line 39 of file ModelParamDual.h.
Referenced by MLL::ModelDual::ReadSpecificImplementationXML(), MLL::ModelDual::ReconcilePredictions(), and MLL::ModelDual::TrainModel().
ModelParamDualPtr ModelParamDual::Duplicate () const virtual
Implements MLL::ModelParam.
Definition at line 85 of file ModelParamDual.cpp.
References ModelParamDual().
bool MLL::ModelParamDual::FullHierarchyMustMatch () const inline
Definition at line 40 of file ModelParamDual.h.
Referenced by MLL::ModelDual::ReconcilePredictions().
virtual ModelParamTypes MLL::ModelParamDual::ModelParamType () const inline virtual
Implements MLL::ModelParam.
Definition at line 43 of file ModelParamDual.h.
References MLL::ModelParam::mptDual.
MLClassPtr MLL::ModelParamDual::OtherClass () const inline
Definition at line 41 of file ModelParamDual.h.
Referenced by CreateBfsFromMfs(), and MLL::ModelDual::ReconcilePredictions().
void MLL::ModelParamDual::OtherClass (MLClassPtr _otherClass) inline
Definition at line 45 of file ModelParamDual.h.
void ModelParamDual::ReadSpecificImplementationXML (istream & i) virtual
Implements MLL::ModelParam.
Definition at line 220 of file ModelParamDual.cpp.
References MLL::MLClass::CreateNewMLClass(), KKU::endl(), KKU::KKStr::EqualIgnoreCase(), KKU::KKStr::ExtractQuotedStr(), KKU::KKStr::ExtractToken2(), KKU::KKStr::ExtractTokenBool(), KKU::KKStr::Len(), KKU::RunLog::Level(), MLL::ModelParam::log, MLL::ModelParam::ReadXML(), KKU::KKStr::SubStrPart(), KKU::KKStr::Upper(), and MLL::ModelParam::ValidParam().
KKStr ModelParamDual::ToCmdLineStr () const virtual
Creates a Command Line String that represents these parameters.
Convert all parameters to a command line string.
All derived classes should implement this method. Thwy should first call this method and then append there own parameters that are specific to their implementation.
Reimplemented from MLL::ModelParam.
Definition at line 181 of file ModelParamDual.cpp.
References KKU::KKStr::Empty(), KKU::endl(), KKU::RunLog::Level(), MLL::ModelParam::log, and MLL::ModelParam::ToCmdLineStr().
void ModelParamDual::WriteSpecificImplementationXML (std::ostream & o) const virtual
Implements MLL::ModelParam.
Definition at line 205 of file ModelParamDual.cpp.
References KKU::endl(), KKU::RunLog::Level(), and MLL::ModelParam::log.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ModelParamDual.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ModelParamDual.cpp