Pices: MLL::TrainingClassList Class Reference
MLL::TrainingClassList Class Reference
#include <TrainingClass.h>
Public Member Functions
TrainingClassList (const KKStr &rootDir, bool owner=true, int32 initSize=5)
TrainingClassList (const TrainingClassList &tcl, bool _owner)
void AddTrainingClass (TrainingClassPtr trainingClass)
TrainingClassList * DuplicateListAndContents () const
TrainingClassPtr LocateByDirectory (const KKStr &directory)
TrainingClassPtr LocateByMLClass (MLClassConstPtr _mlClass) const
TrainingClassPtr LocateByMLClassName (const KKStr &className)
const KKStr & RootDir ()
void RootDir (const KKStr &_rootDir)
Detailed Description
Definition at line 114 of file TrainingClass.h.
Constructor & Destructor Documentation
MLL::TrainingClassList::TrainingClassList (const KKStr & rootDir, bool owner = true, int32 initSize = 5)
Referenced by DuplicateListAndContents().
TrainingClassList::TrainingClassList (const TrainingClassList & tcl, bool _owner)
Definition at line 106 of file TrainingClass.cpp.
Member Function Documentation
void TrainingClassList::AddTrainingClass (TrainingClassPtr trainingClass)
Definition at line 120 of file TrainingClass.cpp.
TrainingClassListPtr TrainingClassList::DuplicateListAndContents () const
Definition at line 178 of file TrainingClass.cpp.
References TrainingClassList().
Referenced by MLL::TrainingConfiguration2::CreateFromDirectoryStructure().
TrainingClassPtr TrainingClassList::LocateByDirectory (const KKStr & directory)
Definition at line 163 of file TrainingClass.cpp.
Referenced by MLL::TrainingConfiguration2::CreateFromDirectoryStructure().
TrainingClassPtr TrainingClassList::LocateByMLClass (MLClassConstPtr _mlClass) const
Definition at line 127 of file TrainingClass.cpp.
References MLL::TrainingClass::MLClass().
TrainingClassPtr TrainingClassList::LocateByMLClassName (const KKStr & className)
Definition at line 141 of file TrainingClass.cpp.
References MLL::TrainingClass::Name().
Referenced by MLL::TrainingConfiguration2::LocateByMLClassName().
const KKStr& MLL::TrainingClassList::RootDir () inline
Definition at line 131 of file TrainingClass.h.
void MLL::TrainingClassList::RootDir (const KKStr & _rootDir) inline
Definition at line 132 of file TrainingClass.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/TrainingClass.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/TrainingClass.cpp