Pices: PicesInterface::PicesSipperFile Class Reference
PicesInterface::PicesSipperFile Class Reference
#include <PicesSipperFile.h>
Public Types
typedef
SipperHardware::InstrumentPtr InstrumentPtr
typedef
SipperHardware::SipperFilePtr SipperFilePtr
Public Member Functions
PicesSipperFile (String^ _sipperFileName)
PicesSipperFile (SipperFilePtr _sipperFile)
void ReFresh (PicesSipperFile^ _right)
SipperFilePtr UnmanagedClass ()
Protected Member Functions
!PicesSipperFile ()
Properties
String^ CruiseName [get, set]
String^ CtdExt0 [get, set]
String^ CtdExt1 [get, set]
String^ CtdExt2 [get, set]
String^ CtdExt3 [get, set]
System::DateTime DateTimeStart [get, set]
String^ DeploymentNum [get, set]
float Depth [get, set]
String^ Description [get, set]
uint ExtractionScanLineEnd [get, set]
uint ExtractionScanLineStart [get, set]
char ExtractionStatus [get, set]
String^ GPSString [get]
double Latitude [get, set]
double Longitude [get, set]
uint NumScanLines [get, set]
float ScanRate [get, set]
String^ SipperFileName [get, set]
ulong SizeInBytes [get, set]
String^ Sp0 [get, set]
String^ Sp1 [get, set]
String^ Sp2 [get, set]
String^ Sp3 [get, set]
String^ StationName [get, set]
Detailed Description
Definition at line 19 of file PicesSipperFile.h.
Member Typedef Documentation
typedef SipperHardware::InstrumentPtr PicesInterface::PicesSipperFile::InstrumentPtr
Definition at line 23 of file PicesSipperFile.h.
typedef SipperHardware::SipperFilePtr PicesInterface::PicesSipperFile::SipperFilePtr
Definition at line 22 of file PicesSipperFile.h.
Constructor & Destructor Documentation
PicesInterface::PicesSipperFile::PicesSipperFile (String^ _sipperFileName)
Definition at line 39 of file PicesSipperFile.cpp.
PicesInterface::PicesSipperFile::PicesSipperFile (SipperFilePtr _sipperFile)
Definition at line 45 of file PicesSipperFile.cpp.
PicesInterface::PicesSipperFile::!PicesSipperFile () protected
Definition at line 59 of file PicesSipperFile.cpp.
Member Function Documentation
void PicesInterface::PicesSipperFile::ReFresh (PicesSipperFile^ _right)
Definition at line 141 of file PicesSipperFile.cpp.
References UnmanagedClass().
Referenced by SipperFile.SipperFileDialog::SipperFileDialog().
SipperFilePtr PicesInterface::PicesSipperFile::UnmanagedClass () inline
Definition at line 68 of file PicesSipperFile.h.
Referenced by PicesInterface::PicesDataBase::GetScanLinesPerMeterProfile(), PicesInterface::PicesDataBase::GetVolumePerMeterProfile(), PicesInterface::PicesInstrumentDataFileManager::ReExtractInstrumentDataForSipperFile(), ReFresh(), PicesInterface::PicesDataBase::SipperFileInsert(), and PicesInterface::PicesDataBase::SipperFileUpdate().
Property Documentation
String^ PicesInterface::PicesSipperFile::CruiseName get set
Definition at line 39 of file PicesSipperFile.h.
String^ PicesInterface::PicesSipperFile::CtdExt0 get set
Definition at line 58 of file PicesSipperFile.h.
Referenced by SipperFile.InstrumentDataReportCTD::InstrumentDataReportCTD().
String^ PicesInterface::PicesSipperFile::CtdExt1 get set
Definition at line 59 of file PicesSipperFile.h.
Referenced by SipperFile.InstrumentDataReportCTD::InstrumentDataReportCTD().
String^ PicesInterface::PicesSipperFile::CtdExt2 get set
Definition at line 60 of file PicesSipperFile.h.
Referenced by SipperFile.InstrumentDataReportCTD::InstrumentDataReportCTD().
String^ PicesInterface::PicesSipperFile::CtdExt3 get set
Definition at line 61 of file PicesSipperFile.h.
Referenced by SipperFile.InstrumentDataReportCTD::InstrumentDataReportCTD().
System:: DateTime PicesInterface::PicesSipperFile::DateTimeStart get set
Definition at line 51 of file PicesSipperFile.h.
Referenced by SipperFile.TreeNodeSipperFile::ToString().
String^ PicesInterface::PicesSipperFile::DeploymentNum get set
Definition at line 41 of file PicesSipperFile.h.
float PicesInterface::PicesSipperFile::Depth get set
Definition at line 46 of file PicesSipperFile.h.
String^ PicesInterface::PicesSipperFile::Description get set
Definition at line 42 of file PicesSipperFile.h.
uint PicesInterface::PicesSipperFile::ExtractionScanLineEnd get set
Definition at line 49 of file PicesSipperFile.h.
uint PicesInterface::PicesSipperFile::ExtractionScanLineStart get set
Definition at line 48 of file PicesSipperFile.h.
char PicesInterface::PicesSipperFile::ExtractionStatus get set
Definition at line 47 of file PicesSipperFile.h.
String^ PicesInterface::PicesSipperFile::GPSString get
Definition at line 66 of file PicesSipperFile.h.
double PicesInterface::PicesSipperFile::Latitude get set
Definition at line 43 of file PicesSipperFile.h.
double PicesInterface::PicesSipperFile::Longitude get set
Definition at line 44 of file PicesSipperFile.h.
uint PicesInterface::PicesSipperFile::NumScanLines get set
Definition at line 64 of file PicesSipperFile.h.
Referenced by SipperFile.TreeNodeSipperFile::ToString().
float PicesInterface::PicesSipperFile::ScanRate get set
Definition at line 45 of file PicesSipperFile.h.
String^ PicesInterface::PicesSipperFile::SipperFileName get set
Definition at line 37 of file PicesSipperFile.h.
Referenced by SipperFile.InstrumentDataReportCTD::InstrumentDataReportCTD(), SipperFile.SipperFileDialog::SipperFileDialog(), and SipperFile.TreeNodeSipperFile::ToString().
ulong PicesInterface::PicesSipperFile::SizeInBytes get set
Definition at line 63 of file PicesSipperFile.h.
String^ PicesInterface::PicesSipperFile::Sp0 get set
Definition at line 53 of file PicesSipperFile.h.
Referenced by SipperFile.InstrumentDataManager::InstrumentDataManager().
String^ PicesInterface::PicesSipperFile::Sp1 get set
Definition at line 54 of file PicesSipperFile.h.
Referenced by SipperFile.InstrumentDataManager::InstrumentDataManager().
String^ PicesInterface::PicesSipperFile::Sp2 get set
Definition at line 55 of file PicesSipperFile.h.
Referenced by SipperFile.InstrumentDataManager::InstrumentDataManager().
String^ PicesInterface::PicesSipperFile::Sp3 get set
Definition at line 56 of file PicesSipperFile.h.
Referenced by SipperFile.InstrumentDataManager::InstrumentDataManager().
String^ PicesInterface::PicesSipperFile::StationName get set
Definition at line 40 of file PicesSipperFile.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesSipperFile.h
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesSipperFile.cpp