Pices: KKU::BlobList Class Reference
KKU::BlobList Class Reference
Maintains a list of blobs.
#include <Blob.h>
Public Member Functions
BlobList (bool _owner)
~BlobList ()
BlobPtr LocateLargestBlob ()
Will return Blob with largest pixel count.
BlobPtr LocateMostComplete ()
Loactes the blob that covers the greatest part of the raster; that is the one who has the largest (Height x Width)
BlobPtr LookUpByBlobId (int32 blobId)
Will return pointer to blob with 'blobId'; if not found will return NULL.
void MergeBlobIds (BlobPtr blob, int32 blobId, int32 **blobIds)
Used by the Connected component analysis to merge two blobs together.
BlobPtr MergeIntoSingleBlob (BlobPtr blob1, int32 blob2Id, int32 **blobIds)
BlobPtr NewBlob (uint32 rowTop, uint32 colLeft)
void PushOnBack (BlobPtr blob)
void PushOnFront (BlobPtr blob)
Detailed Description
Maintains a list of blobs.
Definition at line 74 of file Blob.h.
Constructor & Destructor Documentation
BlobList::BlobList (bool _owner)
Definition at line 52 of file Blob.cpp.
BlobList::~BlobList ()
Definition at line 60 of file Blob.cpp.
Member Function Documentation
BlobPtr BlobList::LocateLargestBlob ()
Will return Blob with largest pixel count.
Definition at line 192 of file Blob.cpp.
References KKU::Blob::pixelCount.
Referenced by KKU::Raster::ConnectedComponent(), KKU::Raster::ConnectedComponent8Conected(), and KKU::Raster::ConnectedComponentOrig().
BlobPtr BlobList::LocateMostComplete ()
Loactes the blob that covers the greatest part of the raster; that is the one who has the largest (Height x Width)
Definition at line 214 of file Blob.cpp.
References KKU::Blob::Height(), and KKU::Blob::Width().
Referenced by KKU::Raster::ReduceToMostCompleteBlob().
BlobPtr BlobList::LookUpByBlobId (int32 blobId)
Will return pointer to blob with 'blobId'; if not found will return NULL.
Definition at line 41 of file Blob.cpp.
Referenced by KKU::Raster::ConnectedComponent8Conected(), KKU::Raster::ConnectedComponentOrig(), and KKU::Raster::ExtractBlobs().
void BlobList::MergeBlobIds (BlobPtr blob, int32 blobId, int32 ** blobIds)
Used by the Connected component analysis to merge two blobs together.
When the connected component discovers that two separate blobs are actually connected if will call this method to merge them together into a single blob.
Definition at line 83 of file Blob.cpp.
References KKU::Blob::colLeft, KKU::Blob::colRight, KKU::Blob::Id(), KKU::Max(), KKU::Min(), KKU::Blob::pixelCount, KKU::Blob::rowBot, and KKU::Blob::rowTop.
Referenced by KKU::Raster::ConnectedComponent8Conected(), and KKU::Raster::ConnectedComponentOrig().
BlobPtr BlobList::MergeIntoSingleBlob (BlobPtr blob1, int32 blob2Id, int32 ** blobIds)
Definition at line 125 of file Blob.cpp.
References KKU::Blob::colLeft, KKU::Blob::colRight, KKU::Blob::Id(), KKU::Max(), KKU::Min(), KKU::Blob::PixelCount(), KKU::Blob::pixelCount, KKU::Blob::rowBot, and KKU::Blob::rowTop.
Referenced by KKU::Raster::ExtractBlobs().
BlobPtr BlobList::NewBlob (uint32 rowTop, uint32 colLeft)
Definition at line 65 of file Blob.cpp.
References KKU::Blob::colLeft, KKU::Blob::colRight, PushOnBack(), KKU::Blob::rowBot, and KKU::Blob::rowTop.
Referenced by KKU::Raster::ConnectedComponent8Conected(), KKU::Raster::ConnectedComponentOrig(), and KKU::Raster::ExtractBlobs().
void BlobList::PushOnBack (BlobPtr blob)
Definition at line 241 of file Blob.cpp.
References KKU::Blob::Id().
Referenced by NewBlob().
void BlobList::PushOnFront (BlobPtr blob)
Definition at line 249 of file Blob.cpp.
References KKU::Blob::Id().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Blob.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Blob.cpp