Pices: PicesInterface::PicesDataBaseLogEntry Class Reference
PicesInterface::PicesDataBaseLogEntry Class Reference
#include <PicesDataBaseLogEntry.h>
Public Member Functions
PicesDataBaseLogEntry ()
PicesDataBaseLogEntry (String^ _progCode, String^ _progName, System::DateTime _dateTimeCompiled, String^ _cmdLine, String^ _compName, String^ _compUserName, String^ _sipperFileName)
PicesDataBaseLogEntry (DataBaseLogEntryPtr _dataBaseLogEntry)
Gives ownersip of UnManaged '_dataBaseLogEntry' to managed newly created 'PicesDataBaseLogEntry' instance.
MLL::DataBaseLogEntryPtr UnmanagedClass ()
Protected Member Functions
!PicesDataBaseLogEntry ()
Properties
String^ CmdLine [get, set]
String^ CompletionStatus [get, set]
String^ CompName [get, set]
String^ CompUserName [get, set]
float CpuTimeUsed [get, set]
String^ DataBaseUserName [get, set]
System::DateTime DateTimeCompiled [get, set]
System::DateTime DateTimeEnd [get, set]
System::DateTime DateTimeStart [get, set]
System::DateTime DateTimeStartUtc [get, set]
uint LogEntryId [get, set]
String^ ProgCode [get, set]
String^ ProgName [get, set]
String^ SipperFileName [get, set]
Detailed Description
Definition at line 15 of file PicesDataBaseLogEntry.h.
Constructor & Destructor Documentation
PicesInterface::PicesDataBaseLogEntry::PicesDataBaseLogEntry ()
Definition at line 34 of file PicesDataBaseLogEntry.cpp.
PicesInterface::PicesDataBaseLogEntry::PicesDataBaseLogEntry (String^ _progCode, String^ _progName, System::DateTime _dateTimeCompiled, String^ _cmdLine, String^ _compName, String^ _compUserName, String^ _sipperFileName)
Parameters
_sipperFileName Root name of Sipper File if Sipper File Specific.
Definition at line 47 of file PicesDataBaseLogEntry.cpp.
References PicesInterface::PicesMethods::DateTimeSystemToKKU(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
PicesInterface::PicesDataBaseLogEntry::PicesDataBaseLogEntry (DataBaseLogEntryPtr _dataBaseLogEntry)
Gives ownersip of UnManaged '_dataBaseLogEntry' to managed newly created 'PicesDataBaseLogEntry' instance.
PicesInterface::PicesDataBaseLogEntry::!PicesDataBaseLogEntry () protected
Definition at line 79 of file PicesDataBaseLogEntry.cpp.
Member Function Documentation
MLL::DataBaseLogEntryPtr PicesInterface::PicesDataBaseLogEntry::UnmanagedClass () inline
Definition at line 54 of file PicesDataBaseLogEntry.h.
Referenced by PicesInterface::PicesDataBase::LogEntriesProcessEnd().
Property Documentation
String^ PicesInterface::PicesDataBaseLogEntry::CmdLine get set
Definition at line 43 of file PicesDataBaseLogEntry.h.
String^ PicesInterface::PicesDataBaseLogEntry::CompletionStatus get set
Definition at line 51 of file PicesDataBaseLogEntry.h.
String^ PicesInterface::PicesDataBaseLogEntry::CompName get set
Definition at line 44 of file PicesDataBaseLogEntry.h.
String^ PicesInterface::PicesDataBaseLogEntry::CompUserName get set
Definition at line 46 of file PicesDataBaseLogEntry.h.
float PicesInterface::PicesDataBaseLogEntry::CpuTimeUsed get set
Definition at line 50 of file PicesDataBaseLogEntry.h.
String^ PicesInterface::PicesDataBaseLogEntry::DataBaseUserName get set
Definition at line 45 of file PicesDataBaseLogEntry.h.
System:: DateTime PicesInterface::PicesDataBaseLogEntry::DateTimeCompiled get set
Definition at line 42 of file PicesDataBaseLogEntry.h.
System:: DateTime PicesInterface::PicesDataBaseLogEntry::DateTimeEnd get set
Definition at line 49 of file PicesDataBaseLogEntry.h.
System:: DateTime PicesInterface::PicesDataBaseLogEntry::DateTimeStart get set
Definition at line 47 of file PicesDataBaseLogEntry.h.
System:: DateTime PicesInterface::PicesDataBaseLogEntry::DateTimeStartUtc get set
Definition at line 48 of file PicesDataBaseLogEntry.h.
uint PicesInterface::PicesDataBaseLogEntry::LogEntryId get set
Definition at line 39 of file PicesDataBaseLogEntry.h.
String^ PicesInterface::PicesDataBaseLogEntry::ProgCode get set
Definition at line 40 of file PicesDataBaseLogEntry.h.
String^ PicesInterface::PicesDataBaseLogEntry::ProgName get set
Definition at line 41 of file PicesDataBaseLogEntry.h.
String^ PicesInterface::PicesDataBaseLogEntry::SipperFileName get set
Definition at line 52 of file PicesDataBaseLogEntry.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesDataBaseLogEntry.h
D:/Users/kkramer/IEC/SipperSoftware/PicesInterface/PicesDataBaseLogEntry.cpp