Pices: KKU::ContourFollower Class Reference
KKU::ContourFollower Class Reference
#include <ContourFollower.h>
Public Member Functions
ContourFollower (Raster &_raster, RunLog &_log)
int32 CreateFourierDescriptorBySampling (int32 numOfBuckets, float *countourFreq, bool &successful)
int32 FollowContour (float *countourFreq, float fourierDescriptors[15], int32 totalPixels, bool &successful)
int32 FollowContour2 (float *countourFreq, bool &successful)
PointListPtr GenerateContourList ()
void HistogramDistanceFromAPointOfEdge (float pointRow, float pointCol, int32 numOfBuckets, int32 *buckets, float &minDistance, float &maxDistance, int32 &numOfEdgePixels)
Detailed Description
Definition at line 29 of file ContourFollower.h.
Constructor & Destructor Documentation
ContourFollower::ContourFollower (Raster & _raster, RunLog & _log)
Definition at line 43 of file ContourFollower.cpp.
Member Function Documentation
int32 ContourFollower::CreateFourierDescriptorBySampling (int32 numOfBuckets, float * countourFreq, bool & successful)
Definition at line 737 of file ContourFollower.cpp.
References KKU::Point::Col(), KKU::endl(), KKU::fftwCreateOneDPlan(), KKU::fftwDestroyPlan(), KKU::Point::Row(), and x.
int32 ContourFollower::FollowContour (float * countourFreq, float fourierDescriptors[15], int32 totalPixels, bool & successful)
Definition at line 213 of file ContourFollower.cpp.
References CalcMagnitude(), KKU::endl(), KKU::fftwCreateOneDPlan(), KKU::fftwDestroyPlan(), KKU::Raster::FileName(), KKU::RunLog::Level(), and x.
int32 ContourFollower::FollowContour2 (float * countourFreq, bool & successful)
Definition at line 483 of file ContourFollower.cpp.
References KKU::endl(), Fabs, KKU::fftwCreateOneDPlan(), KKU::fftwDestroyPlan(), and x.
PointListPtr ContourFollower::GenerateContourList ()
Definition at line 682 of file ContourFollower.cpp.
References KKU::endl().
Referenced by HistogramDistanceFromAPointOfEdge().
void ContourFollower::HistogramDistanceFromAPointOfEdge (float pointRow, float pointCol, int32 numOfBuckets, int32 * buckets, float & minDistance, float & maxDistance, int32 & numOfEdgePixels)
Definition at line 851 of file ContourFollower.cpp.
References KKU::Point::Col(), FFLOAT_MAX, FFLOAT_MIN, GenerateContourList(), KKU::Max(), KKU::Min(), KKU::Point::Row(), and x.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/ContourFollower.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/ContourFollower.cpp