Pices: SipperHardware::SipperDeployment Class Reference
SipperHardware::SipperDeployment Class Reference
#include <SipperDeployment.h>
Public Types
typedef SipperDeployment * SipperDeploymentPtr
Public Member Functions
SipperDeployment ()
~SipperDeployment ()
KKU::uint32 CropLeft () const
void CropLeft (KKU::uint32 _cropLeft)
KKU::uint32 CropRight () const
void CropRight (KKU::uint32 _cropRight)
const KKStr & CruiseName () const
void CruiseName (const KKStr &_cruiseName)
const KKU::DateTime & DateTimeEnd () const
void DateTimeEnd (const KKU::DateTime &_dateTimeEnd)
const KKU::DateTime & DateTimeStart () const
void DateTimeStart (const KKU::DateTime &_dateTimeStart)
const KKStr & DeploymentNum () const
void DeploymentNum (const KKStr &_deploymentNum)
const KKStr & Description () const
void Description (const KKStr &_description)
double Latitude () const
void Latitude (double _latitude)
double Longitude () const
void Longitude (double _longitude)
const KKStr & StationName () const
void StationName (const KKStr &_stationName)
const KKU::DateTime & SyncTimeStampActual () const
void SyncTimeStampActual (const KKU::DateTime &_syncTimeStampActual)
const KKU::DateTime & SyncTimeStampCTD () const
void SyncTimeStampCTD (const KKU::DateTime &_syncTimeStampCTD)
const KKU::DateTime & SyncTimeStampGPS () const
void SyncTimeStampGPS (const KKU::DateTime &_syncTimeStampGPS)
Detailed Description
Definition at line 11 of file SipperDeployment.h.
Member Typedef Documentation
typedef SipperDeployment* SipperHardware::SipperDeployment::SipperDeploymentPtr
Definition at line 14 of file SipperDeployment.h.
Constructor & Destructor Documentation
SipperDeployment::SipperDeployment ()
Definition at line 25 of file SipperDeployment.cpp.
References KKU::osGetLocalDateTime().
SipperDeployment::~SipperDeployment ()
Definition at line 50 of file SipperDeployment.cpp.
Member Function Documentation
KKU::uint32 SipperHardware::SipperDeployment::CropLeft () const inline
Definition at line 30 of file SipperDeployment.h.
Referenced by DetermineCropSettings(), DetermineCropSettingsForDeployment(), MLL::DataBase::SipperDeploymentInsert(), and MLL::DataBase::SipperDeploymentUpdate().
void SipperHardware::SipperDeployment::CropLeft (KKU::uint32 _cropLeft) inline
Definition at line 44 of file SipperDeployment.h.
KKU::uint32 SipperHardware::SipperDeployment::CropRight () const inline
Definition at line 31 of file SipperDeployment.h.
Referenced by DetermineCropSettings(), DetermineCropSettingsForDeployment(), MLL::DataBase::SipperDeploymentInsert(), and MLL::DataBase::SipperDeploymentUpdate().
void SipperHardware::SipperDeployment::CropRight (KKU::uint32 _cropRight) inline
Definition at line 45 of file SipperDeployment.h.
const KKStr& SipperHardware::SipperDeployment::CruiseName () const inline
Definition at line 19 of file SipperDeployment.h.
Referenced by DetermineCropSettingsForDeployment(), MarineSnowReportDeployment(), PicesInterface::PicesSipperDeployment::PicesSipperDeployment(), MLL::DataBase::SipperDeploymentInsert(), and MLL::DataBase::SipperDeploymentUpdate().
void SipperHardware::SipperDeployment::CruiseName (const KKStr & _cruiseName) inline
Definition at line 33 of file SipperDeployment.h.
const KKU::DateTime& SipperHardware::SipperDeployment::DateTimeEnd () const inline
Definition at line 26 of file SipperDeployment.h.
Referenced by MLL::DataBase::SipperDeploymentInsert(), and MLL::DataBase::SipperDeploymentUpdate().
void SipperHardware::SipperDeployment::DateTimeEnd (const KKU::DateTime & _dateTimeEnd) inline
Definition at line 40 of file SipperDeployment.h.
const KKU::DateTime& SipperHardware::SipperDeployment::DateTimeStart () const inline
Definition at line 25 of file SipperDeployment.h.
Referenced by DetermineCropSettings(), MLL::DataBase::SipperDeploymentInsert(), and MLL::DataBase::SipperDeploymentUpdate().
void SipperHardware::SipperDeployment::DateTimeStart (const KKU::DateTime & _dateTimeStart) inline
Definition at line 39 of file SipperDeployment.h.
const KKStr& SipperHardware::SipperDeployment::DeploymentNum () const inline
Definition at line 21 of file SipperDeployment.h.
Referenced by DetermineCropSettings(), DetermineCropSettingsForDeployment(), MarineSnowReportDeployment(), MLL::DataBase::SipperDeploymentInsert(), and MLL::DataBase::SipperDeploymentUpdate().
void SipperHardware::SipperDeployment::DeploymentNum (const KKStr & _deploymentNum) inline
Definition at line 35 of file SipperDeployment.h.
const KKStr& SipperHardware::SipperDeployment::Description () const inline
Definition at line 22 of file SipperDeployment.h.
Referenced by MLL::DataBase::SipperDeploymentInsert(), and MLL::DataBase::SipperDeploymentUpdate().
void SipperHardware::SipperDeployment::Description (const KKStr & _description) inline
Definition at line 36 of file SipperDeployment.h.
double SipperHardware::SipperDeployment::Latitude () const inline
Definition at line 23 of file SipperDeployment.h.
Referenced by MLL::DataBase::SipperDeploymentInsert(), and MLL::DataBase::SipperDeploymentUpdate().
void SipperHardware::SipperDeployment::Latitude (double _latitude) inline
Definition at line 37 of file SipperDeployment.h.
double SipperHardware::SipperDeployment::Longitude () const inline
Definition at line 24 of file SipperDeployment.h.
Referenced by MLL::DataBase::SipperDeploymentInsert(), and MLL::DataBase::SipperDeploymentUpdate().
void SipperHardware::SipperDeployment::Longitude (double _longitude) inline
Definition at line 38 of file SipperDeployment.h.
const KKStr& SipperHardware::SipperDeployment::StationName () const inline
Definition at line 20 of file SipperDeployment.h.
Referenced by DetermineCropSettingsForDeployment(), MarineSnowReportDeployment(), PicesInterface::PicesSipperDeployment::PicesSipperDeployment(), MLL::DataBase::SipperDeploymentInsert(), and MLL::DataBase::SipperDeploymentUpdate().
void SipperHardware::SipperDeployment::StationName (const KKStr & _stationName) inline
Definition at line 34 of file SipperDeployment.h.
const KKU::DateTime& SipperHardware::SipperDeployment::SyncTimeStampActual () const inline
Definition at line 27 of file SipperDeployment.h.
Referenced by MLL::DataBase::SipperDeploymentInsert(), and MLL::DataBase::SipperDeploymentUpdate().
void SipperHardware::SipperDeployment::SyncTimeStampActual (const KKU::DateTime & _syncTimeStampActual) inline
Definition at line 41 of file SipperDeployment.h.
const KKU::DateTime& SipperHardware::SipperDeployment::SyncTimeStampCTD () const inline
Definition at line 28 of file SipperDeployment.h.
Referenced by MLL::DataBase::SipperDeploymentInsert(), and MLL::DataBase::SipperDeploymentUpdate().
void SipperHardware::SipperDeployment::SyncTimeStampCTD (const KKU::DateTime & _syncTimeStampCTD) inline
Definition at line 42 of file SipperDeployment.h.
const KKU::DateTime& SipperHardware::SipperDeployment::SyncTimeStampGPS () const inline
Definition at line 29 of file SipperDeployment.h.
Referenced by MLL::DataBase::SipperDeploymentInsert(), and MLL::DataBase::SipperDeploymentUpdate().
void SipperHardware::SipperDeployment::SyncTimeStampGPS (const KKU::DateTime & _syncTimeStampGPS) inline
Definition at line 43 of file SipperDeployment.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/SipperDeployment.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/SipperDeployment.cpp