Pices: MLL::CrossValidation Class Reference
MLL::CrossValidation Class Reference
A class that is meant to manage a n-Fold Cross Validation.
#include <CrossValidation.h>
Public Member Functions
CrossValidation (TrainingConfiguration2Ptr _config, FeatureVectorListPtr _examples, MLClassConstListPtr _mlClasses, int32 _numOfFolds, bool _featuresAreAlreadyNormalized, FileDescPtr _fileDesc, RunLog &_log, bool &_cancelFlag)
~CrossValidation ()
const VectorFloat & Accuracies () const
float Accuracy ()
float AccuracyMean () const
float AccuracyNorm ()
float AccuracyStdDev () const
double AvgPredProb () const
const CompressionStats & CompStats () const
const ConfusionMatrix2Ptr ConfussionMatrix () const
int32 DuplicateTrainDataCount () const
const VectorFloat & FoldAccuracies () const
float FoldAccuracy (int32 foldNum) const
KKStr FoldAccuracysToStr () const
ConfusionMatrix2Ptr GiveMeOwnershipOfConfusionMatrix ()
void NumOfFolds (int32 _numOfFolds)
int32 NumOfSupportVectors () const
int32 NumSVs () const
int32 ReductionPostExampleCount () const
int32 ReductionPreExampleCount () const
float ReductionRatio () const
float ReductionRatioMean () const
const VectorFloat & ReductionRatios () const
float ReductionRatioStdDev () const
double ReductionTime () const
double ReductionTimeMean () const
const VectorDouble & ReductionTimes () const
double ReductionTimeStdDev () const
void RunCrossValidation ()
void RunValidationOnly (FeatureVectorListPtr validationData, bool *classedCorrectly=NULL)
const VectorFloat & SupportPoints () const
double SupportPointsMean () const
double SupportPointsStdDev () const
int32 SupportPointsTotal () const
double TestTimeMean () const
const VectorDouble & TestTimes () const
double TestTimeStdDev () const
double TestTimeTotal () const
int32 TotalNumSVs () const
double TrainTimeMean () const
const VectorDouble & TrainTimes () const
double TrainTimeStdDev () const
double TrainTimeTotal () const
Detailed Description
A class that is meant to manage a n-Fold Cross Validation.
Author
Kurt Kramer
                           CrossValidation                         *
                                                                   *
                                                                   *
                                                                   *
-------------------------------------------------------------------*
  History                                                          *
                                                                   *
    Date     Programmer   Description                              *
  ---------- -----------  -----------------------------------------*
  2004       Kurt Kramer  Origanol Development.                    *
                                                                   *
                                                                   *
  2005-01-07 Kurt Kramer  Added classedCorrectly parameter to      *
                          CrossValidate.  If not null it should    *
                          point to an array of bool that has as    *
                          many elemenst as there are in the        *
                          testImages list.  Each element reprsents *
                          weather the coresponding element in      *
                          testImages was classified correctly.     *
                                                                   *
Definition at line 83 of file CrossValidation.h.
Constructor & Destructor Documentation
CrossValidation::CrossValidation (TrainingConfiguration2Ptr _config, FeatureVectorListPtr _examples, MLClassConstListPtr _mlClasses, int32 _numOfFolds, bool _featuresAreAlreadyNormalized, FileDescPtr _fileDesc, RunLog & _log, bool & _cancelFlag)
Definition at line 36 of file CrossValidation.cpp.
References MLL::TrainingConfiguration2::ExamplesPerClass().
CrossValidation::~CrossValidation ()
Definition at line 110 of file CrossValidation.cpp.
Member Function Documentation
const VectorFloat& MLL::CrossValidation::Accuracies () const inline
Definition at line 132 of file CrossValidation.h.
float CrossValidation::Accuracy ()
Definition at line 519 of file CrossValidation.cpp.
References MLL::ConfusionMatrix2::Accuracy().
Referenced by CrossValidationSortByAccuracy::operator()(), CrossValidationApp::RandomlySelectedResults(), MLL::CrossValidationMxN::RunTrainAndTest(), and MLL::CrossValidationMxN::RunValidations().
float MLL::CrossValidation::AccuracyMean () const inline
Definition at line 133 of file CrossValidation.h.
float CrossValidation::AccuracyNorm ()
Definition at line 529 of file CrossValidation.cpp.
References MLL::ConfusionMatrix2::AccuracyNorm().
float MLL::CrossValidation::AccuracyStdDev () const inline
Definition at line 134 of file CrossValidation.h.
double MLL::CrossValidation::AvgPredProb () const inline
Definition at line 136 of file CrossValidation.h.
const CompressionStats& MLL::CrossValidation::CompStats () const inline
Definition at line 130 of file CrossValidation.h.
const ConfusionMatrix2Ptr MLL::CrossValidation::ConfussionMatrix () const inline
Definition at line 105 of file CrossValidation.h.
Referenced by MLL::CrossValidationMxN::RunTrainAndTest(), and MLL::CrossValidationMxN::RunValidations().
int32 MLL::CrossValidation::DuplicateTrainDataCount () const inline
Definition at line 109 of file CrossValidation.h.
const VectorFloat& MLL::CrossValidation::FoldAccuracies () const inline
Definition at line 115 of file CrossValidation.h.
float CrossValidation::FoldAccuracy (int32 foldNum) const
Definition at line 572 of file CrossValidation.cpp.
References KKU::endl(), KKU::RunLog::Level(), and KKU::osWaitForEnter().
KKStr CrossValidation::FoldAccuracysToStr () const
Definition at line 540 of file CrossValidation.cpp.
References KKU::endl(), KKU::RunLog::Level(), and KKU::StrFormatDouble().
ConfusionMatrix2Ptr CrossValidation::GiveMeOwnershipOfConfusionMatrix ()
Definition at line 592 of file CrossValidation.cpp.
void MLL::CrossValidation::NumOfFolds (int32 _numOfFolds) inline
Definition at line 112 of file CrossValidation.h.
int32 MLL::CrossValidation::NumOfSupportVectors () const inline
Definition at line 121 of file CrossValidation.h.
Referenced by CrossValidationSortBySupportPoints::operator()(), CrossValidationApp::RandomlySelectedResults(), MLL::CrossValidationMxN::RunTrainAndTest(), and MLL::CrossValidationMxN::RunValidations().
int32 MLL::CrossValidation::NumSVs () const inline
Definition at line 122 of file CrossValidation.h.
int32 MLL::CrossValidation::ReductionPostExampleCount () const inline
Definition at line 126 of file CrossValidation.h.
int32 MLL::CrossValidation::ReductionPreExampleCount () const inline
Definition at line 125 of file CrossValidation.h.
float CrossValidation::ReductionRatio () const
Definition at line 181 of file CrossValidation.cpp.
Referenced by MLL::CrossValidationMxN::RunTrainAndTest(), and MLL::CrossValidationMxN::RunValidations().
float MLL::CrossValidation::ReductionRatioMean () const inline
Definition at line 139 of file CrossValidation.h.
const VectorFloat& MLL::CrossValidation::ReductionRatios () const inline
Definition at line 138 of file CrossValidation.h.
float MLL::CrossValidation::ReductionRatioStdDev () const inline
Definition at line 140 of file CrossValidation.h.
double MLL::CrossValidation::ReductionTime () const inline
Definition at line 145 of file CrossValidation.h.
Referenced by MLL::CrossValidationMxN::RunTrainAndTest(), and MLL::CrossValidationMxN::RunValidations().
double MLL::CrossValidation::ReductionTimeMean () const inline
Definition at line 143 of file CrossValidation.h.
const VectorDouble& MLL::CrossValidation::ReductionTimes () const inline
Definition at line 142 of file CrossValidation.h.
double MLL::CrossValidation::ReductionTimeStdDev () const inline
Definition at line 144 of file CrossValidation.h.
void CrossValidation::RunCrossValidation ()
Definition at line 193 of file CrossValidation.cpp.
References KKU::CalcMeanAndStdDev(), KKU::endl(), KKU::RunLog::Level(), MLL::FeatureVectorList::PushOnBack(), and x.
Referenced by MLL::CrossValidationMxN::RunValidations().
void CrossValidation::RunValidationOnly (FeatureVectorListPtr validationData, bool * classedCorrectly = NULL)
Definition at line 289 of file CrossValidation.cpp.
References KKU::CalcMeanAndStdDev(), KKU::endl(), and KKU::RunLog::Level().
Referenced by MLL::CrossValidationMxN::RunTrainAndTest().
const VectorFloat& MLL::CrossValidation::SupportPoints () const inline
Definition at line 147 of file CrossValidation.h.
double MLL::CrossValidation::SupportPointsMean () const inline
Definition at line 148 of file CrossValidation.h.
double MLL::CrossValidation::SupportPointsStdDev () const inline
Definition at line 149 of file CrossValidation.h.
int32 MLL::CrossValidation::SupportPointsTotal () const inline
Definition at line 128 of file CrossValidation.h.
double MLL::CrossValidation::TestTimeMean () const inline
Definition at line 152 of file CrossValidation.h.
const VectorDouble& MLL::CrossValidation::TestTimes () const inline
Definition at line 151 of file CrossValidation.h.
double MLL::CrossValidation::TestTimeStdDev () const inline
Definition at line 153 of file CrossValidation.h.
double MLL::CrossValidation::TestTimeTotal () const inline
Definition at line 154 of file CrossValidation.h.
Referenced by CrossValidationApp::RandomlySelectedResults(), MLL::CrossValidationMxN::RunTrainAndTest(), and MLL::CrossValidationMxN::RunValidations().
int32 MLL::CrossValidation::TotalNumSVs () const inline
Definition at line 123 of file CrossValidation.h.
double MLL::CrossValidation::TrainTimeMean () const inline
Definition at line 157 of file CrossValidation.h.
const VectorDouble& MLL::CrossValidation::TrainTimes () const inline
Definition at line 156 of file CrossValidation.h.
double MLL::CrossValidation::TrainTimeStdDev () const inline
Definition at line 158 of file CrossValidation.h.
double MLL::CrossValidation::TrainTimeTotal () const inline
Definition at line 159 of file CrossValidation.h.
Referenced by CrossValidationSortByTrainTime::operator()(), CrossValidationApp::RandomlySelectedResults(), MLL::CrossValidationMxN::RunTrainAndTest(), and MLL::CrossValidationMxN::RunValidations().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/CrossValidation.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/CrossValidation.cpp