Pices: SVM289_MFS::Solver Class Reference
SVM289_MFS::Solver Class Reference
Classes
struct SolutionInfo
Public Member Functions
Solver ()
virtual ~Solver ()
void Solve (int32 l, QMatrix &Q, const double *p_, const schar *y_, double *alpha_, double Cp, double Cn, double eps, SolutionInfo *si, int32 shrinking)
Protected Types
enum { LOWER_BOUND, UPPER_BOUND, FREE }
Protected Member Functions
virtual double calculate_rho ()
virtual void do_shrinking ()
double get_C (int32 i)
bool is_free (int32 i)
bool is_lower_bound (int32 i)
bool is_upper_bound (int32 i)
void reconstruct_gradient ()
virtual int32 select_working_set (int32 &i, int32 &j)
void swap_index (int32 i, int32 j)
void update_alpha_status (int32 i)
Protected Attributes
int32 * active_set
int32 active_size
double * alpha
char * alpha_status
double Cn
double Cp
double eps
double * G
double * G_bar
int32 l
double * p
QMatrix * Q
const Qfloat * QD
bool unshrink
schar * y
Detailed Description
Definition at line 1183 of file svm2.cpp.
Member Enumeration Documentation
anonymous enum protected
Enumerator
LOWER_BOUND
UPPER_BOUND
FREE
Definition at line 1212 of file svm2.cpp.
Constructor & Destructor Documentation
SVM289_MFS::Solver::Solver () inline
Definition at line 1185 of file svm2.cpp.
virtual SVM289_MFS::Solver::~Solver () inline virtual
Definition at line 1186 of file svm2.cpp.
Member Function Documentation
double SVM289_MFS::Solver::calculate_rho () protected virtual
Definition at line 1845 of file svm2.cpp.
References INF, SVM289_MFS::Max(), and SVM289_MFS::Min().
void Solver::do_shrinking () protected virtual
Definition at line 1777 of file svm2.cpp.
References active_size, eps, G, INF, info(), is_lower_bound(), is_upper_bound(), l, reconstruct_gradient(), swap_index(), and unshrink.
double SVM289_MFS::Solver::get_C (int32 i) inline protected
Definition at line 1227 of file svm2.cpp.
bool SVM289_MFS::Solver::is_free (int32 i) inline protected
Definition at line 1247 of file svm2.cpp.
bool SVM289_MFS::Solver::is_lower_bound (int32 i) inline protected
Definition at line 1246 of file svm2.cpp.
Referenced by do_shrinking().
bool SVM289_MFS::Solver::is_upper_bound (int32 i) inline protected
Definition at line 1245 of file svm2.cpp.
Referenced by do_shrinking().
void SVM289_MFS::Solver::reconstruct_gradient () protected
Definition at line 1284 of file svm2.cpp.
References info().
Referenced by do_shrinking().
int32 SVM289_MFS::Solver::select_working_set (int32 & i, int32 & j) protected virtual
Definition at line 1636 of file svm2.cpp.
References INF, and TAU.
void SVM289_MFS::Solver::Solve (int32 l, QMatrix & Q, const double * p_, const schar * y_, double * alpha_, double Cp, double Cn, double eps, SolutionInfo * si, int32 shrinking)
Definition at line 1337 of file svm2.cpp.
References SVM289_MFS::clone(), SVM289_MFS::QMatrix::get_Q(), SVM289_MFS::QMatrix::get_QD(), info(), SVM289_MFS::Min(), SVM289_MFS::Solver::SolutionInfo::obj, SVM289_MFS::Solver::SolutionInfo::rho, TAU, SVM289_MFS::Solver::SolutionInfo::upper_bound_n, and SVM289_MFS::Solver::SolutionInfo::upper_bound_p.
Referenced by SVM289_MFS::Solver_NU::Solve(), SVM289_MFS::solve_c_svc(), SVM289_MFS::solve_epsilon_svr(), and SVM289_MFS::solve_one_class().
void SVM289_MFS::Solver::swap_index (int32 i, int32 j) protected
Definition at line 1270 of file svm2.cpp.
References SVM289_MFS::swap().
Referenced by do_shrinking().
void SVM289_MFS::Solver::update_alpha_status (int32 i) inline protected
Definition at line 1233 of file svm2.cpp.
Member Data Documentation
int32* SVM289_MFS::Solver::active_set protected
Definition at line 1221 of file svm2.cpp.
int32 SVM289_MFS::Solver::active_size protected
Definition at line 1209 of file svm2.cpp.
Referenced by do_shrinking().
double* SVM289_MFS::Solver::alpha protected
Definition at line 1214 of file svm2.cpp.
char* SVM289_MFS::Solver::alpha_status protected
Definition at line 1213 of file svm2.cpp.
double SVM289_MFS::Solver::Cn protected
Definition at line 1219 of file svm2.cpp.
double SVM289_MFS::Solver::Cp protected
Definition at line 1218 of file svm2.cpp.
double SVM289_MFS::Solver::eps protected
Definition at line 1217 of file svm2.cpp.
Referenced by do_shrinking().
double* SVM289_MFS::Solver::G protected
Definition at line 1211 of file svm2.cpp.
Referenced by do_shrinking().
double* SVM289_MFS::Solver::G_bar protected
Definition at line 1222 of file svm2.cpp.
int32 SVM289_MFS::Solver::l protected
Definition at line 1223 of file svm2.cpp.
Referenced by do_shrinking().
double* SVM289_MFS::Solver::p protected
Definition at line 1220 of file svm2.cpp.
QMatrix* SVM289_MFS::Solver::Q protected
Definition at line 1215 of file svm2.cpp.
const Qfloat* SVM289_MFS::Solver::QD protected
Definition at line 1216 of file svm2.cpp.
bool SVM289_MFS::Solver::unshrink protected
Definition at line 1224 of file svm2.cpp.
Referenced by do_shrinking().
schar* SVM289_MFS::Solver::y protected
Definition at line 1210 of file svm2.cpp.
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/svm2.cpp