Pices: KKU::PointList Class Reference
KKU::PointList Class Reference
Container object used to maintaining a list of pixel locations.
#include <Point.h>
Public Types
typedef PointList * PointListPtr
Public Member Functions
PointList (const PointList &pointList)
PointList (bool _owner)
void BoxCoordinites (int32 &minRow, int32 &minCol, int32 &maxRow, int32 &maxCol)
Point CalculateCenterPoint ()
float ComputeSegmentLens (float heightFactor, float widthFactor) const
KKStr ToDelStr (char del) const
Static Public Member Functions
static PointListPtr FromDelStr (const KKStr &s)
Detailed Description
Container object used to maintaining a list of pixel locations.
Definition at line 74 of file Point.h.
Member Typedef Documentation
typedef PointList* KKU::PointList::PointListPtr
Definition at line 77 of file Point.h.
Constructor & Destructor Documentation
PointList::PointList (const PointList & pointList)
Definition at line 93 of file Point.cpp.
Referenced by FromDelStr().
PointList::PointList (bool _owner)
Definition at line 105 of file Point.cpp.
Member Function Documentation
void PointList::BoxCoordinites (int32 & minRow, int32 & minCol, int32 & maxRow, int32 & maxCol)
Definition at line 113 of file Point.cpp.
References KKU::Point::Col(), KKU::Point::Row(), and x.
Point PointList::CalculateCenterPoint ()
Definition at line 140 of file Point.cpp.
References KKU::Point::Col(), KKU::Point::Row(), and x.
float PointList::ComputeSegmentLens (float heightFactor, float widthFactor) const
Definition at line 235 of file Point.cpp.
References KKU::Point::Col(), and KKU::Point::Row().
Referenced by KKU::RasterSipper::ComputeSegmentLens(), and MLL::DataBaseImageValidatedEntry::ImageSize().
PointListPtr PointList::FromDelStr (const KKStr & s) static
Definition at line 178 of file Point.cpp.
References KKU::KKStr::ChopFirstChar(), KKU::KKStr::ExtractTokenInt(), KKU::KKStr::Find(), KKU::KKStr::FirstChar(), KKU::KKStr::Len(), PointList(), KKU::KKStr::SubStrPart(), and KKU::KKStr::TrimLeft().
KKStr PointList::ToDelStr (char del) const
Definition at line 158 of file Point.cpp.
References KKU::Point::Col(), and KKU::Point::Row().
Referenced by MLL::DataBase::ImagesUpdateImageSize(), and MLL::DataBaseImageValidatedEntry::SizeCoordinatesDelStr().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Point.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/Point.cpp