Pices: ImageExtractionManager::ExtractedImage Class Reference
ImageExtractionManager::ExtractedImage Class Reference
Represets particle that was extracted by 'LogicalFrame' with its related data.
#include <ExtractedImage.h>
Public Member Functions
ExtractedImage (RasterSipperPtr _image, uint64 _byteOffsetFirstScanRow, uint32 _sipperFileScanRow, uint32 _sipperFileScanCol, uint32 _pixelCount, float _depth, MLClassPtr _predClass1, float _predClass1Prob, MLClassPtr _predClass2, float _predClass2Prob)
~ExtractedImage ()
uint64 ByteOffsetFirstScanRow () const
float Depth () const
void Depth (float _depth)
ImageFeaturesPtr FeatureVector () const
void FeatureVector (ImageFeaturesPtr _featureVector)
ImageFeaturesPtr FeatureVectorGiveOwnership ()
Turns over ownership of FeatureVector to the caller.
RasterSipperPtr Image () const
RasterSipperPtr ImageGiveOwnership ()
int32 MemoryConsumedEstimated () const
uint32 PixelCount () const
MLClassConstPtr PredClass1 () const
float PredClass1Prob () const
MLClassConstPtr PredClass2 () const
float PredClass2Prob () const
void Prediction (MLClassConstPtr _predClass1, float _predClass1Prob, MLClassConstPtr _predClass2, float _predClass2Prob)
uint32 SipperFileScanCol () const
uint32 SipperFileScanRow () const
Detailed Description
Represets particle that was extracted by 'LogicalFrame' with its related data.
Definition at line 24 of file ExtractedImage.h.
Constructor & Destructor Documentation
ExtractedImage::ExtractedImage (RasterSipperPtr _image, uint64 _byteOffsetFirstScanRow, uint32 _sipperFileScanRow, uint32 _sipperFileScanCol, uint32 _pixelCount, float _depth, MLClassPtr _predClass1, float _predClass1Prob, MLClassPtr _predClass2, float _predClass2Prob)
Definition at line 18 of file ExtractedImage.cpp.
ExtractedImage::~ExtractedImage ()
Definition at line 46 of file ExtractedImage.cpp.
Member Function Documentation
uint64 ImageExtractionManager::ExtractedImage::ByteOffsetFirstScanRow () const inline
Definition at line 43 of file ExtractedImage.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
float ImageExtractionManager::ExtractedImage::Depth () const inline
Definition at line 44 of file ExtractedImage.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
void ImageExtractionManager::ExtractedImage::Depth (float _depth) inline
Definition at line 56 of file ExtractedImage.h.
ImageFeaturesPtr ImageExtractionManager::ExtractedImage::FeatureVector () const inline
Definition at line 45 of file ExtractedImage.h.
void ExtractedImage::FeatureVector (ImageFeaturesPtr _featureVector)
Definition at line 68 of file ExtractedImage.cpp.
ImageFeaturesPtr ExtractedImage::FeatureVectorGiveOwnership ()
Turns over ownership of FeatureVector to the caller.
Definition at line 90 of file ExtractedImage.cpp.
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
RasterSipperPtr ImageExtractionManager::ExtractedImage::Image () const inline
Definition at line 46 of file ExtractedImage.h.
RasterSipperPtr ExtractedImage::ImageGiveOwnership ()
Definition at line 98 of file ExtractedImage.cpp.
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
int32 ExtractedImage::MemoryConsumedEstimated () const
Definition at line 54 of file ExtractedImage.cpp.
References KKU::RasterSipper::MemoryConsumedEstimated(), and MLL::ImageFeatures::MemoryConsumedEstimated().
Referenced by ImageExtractionManager::ExtractedImageQueue::MemoryConsumedEstimated().
uint32 ImageExtractionManager::ExtractedImage::PixelCount () const inline
Definition at line 47 of file ExtractedImage.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
MLClassConstPtr ImageExtractionManager::ExtractedImage::PredClass1 () const inline
Definition at line 48 of file ExtractedImage.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
float ImageExtractionManager::ExtractedImage::PredClass1Prob () const inline
Definition at line 49 of file ExtractedImage.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
MLClassConstPtr ImageExtractionManager::ExtractedImage::PredClass2 () const inline
Definition at line 50 of file ExtractedImage.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
float ImageExtractionManager::ExtractedImage::PredClass2Prob () const inline
Definition at line 51 of file ExtractedImage.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
void ExtractedImage::Prediction (MLClassConstPtr _predClass1, float _predClass1Prob, MLClassConstPtr _predClass2, float _predClass2Prob)
Definition at line 76 of file ExtractedImage.cpp.
uint32 ImageExtractionManager::ExtractedImage::SipperFileScanCol () const inline
Definition at line 53 of file ExtractedImage.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
uint32 ImageExtractionManager::ExtractedImage::SipperFileScanRow () const inline
Definition at line 52 of file ExtractedImage.h.
Referenced by ImageExtractionManager::DataBaseUpdateThread::Run().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperLibraries/ImageExtractionManager/ExtractedImage.h
D:/Users/kkramer/IEC/SipperSoftware/SipperLibraries/ImageExtractionManager/ExtractedImage.cpp