Pices: MLL::DataBaseServer Class Reference
MLL::DataBaseServer Class Reference
Represents the parameters for a single Database Server.
#include <DataBaseServer.h>
Public Types
typedef DataBaseServer * DataBaseServerPtr
Public Member Functions
DataBaseServer ()
DataBaseServer (const DataBaseServer &dataBaseServer)
DataBaseServer (const KKStr &parameterStr)
~DataBaseServer ()
const KKStr & DataBaseName () const
void DataBaseName (const KKStr &_dataBaseName)
const KKStr & Description () const
void Description (const KKStr &_description)
bool Embedded () const
void Embedded (bool _embedded)
const KKStr & HostName () const
void HostName (const KKStr &_hostName)
const KKStr & MySqlDataDir () const
void MySqlDataDir (const KKStr &_mySqlDataDir)
const KKStr & PassWord () const
void PassWord (const KKStr &_passWord)
KKStr ServerDescription () const
KKStr ToParameterStr () const
const KKStr & UserName () const
void UserName (const KKStr &_userName)
Detailed Description
Represents the parameters for a single Database Server.
Things like username, hostname, etc. The "DataBase" class will use one instance of this object to use as connection parameters.
Definition at line 20 of file DataBaseServer.h.
Member Typedef Documentation
typedef DataBaseServer* MLL::DataBaseServer::DataBaseServerPtr
Definition at line 23 of file DataBaseServer.h.
Constructor & Destructor Documentation
DataBaseServer::DataBaseServer ()
Definition at line 29 of file DataBaseServer.cpp.
DataBaseServer::DataBaseServer (const DataBaseServer & dataBaseServer)
Definition at line 42 of file DataBaseServer.cpp.
DataBaseServer::DataBaseServer (const KKStr & parameterStr)
Definition at line 55 of file DataBaseServer.cpp.
DataBaseServer::~DataBaseServer ()
Definition at line 69 of file DataBaseServer.cpp.
Member Function Documentation
const KKStr& MLL::DataBaseServer::DataBaseName () const inline
Definition at line 31 of file DataBaseServer.h.
void MLL::DataBaseServer::DataBaseName (const KKStr & _dataBaseName) inline
Definition at line 39 of file DataBaseServer.h.
const KKStr& MLL::DataBaseServer::Description () const inline
Definition at line 32 of file DataBaseServer.h.
Referenced by ImageExtractionManager::ExtractionParms::CmdLine(), ImageExtractionManager::ExtractionParms::DataBaseServerDesc(), PicesInterface::PicesDataBase::GetGlobalDatabaseManagerNewInstance(), MLL::DataBaseServerList::LookUpByDescription(), and ImageExtractionManager::ExtractionParms::ParseCmdLine().
void MLL::DataBaseServer::Description (const KKStr & _description) inline
Definition at line 40 of file DataBaseServer.h.
bool MLL::DataBaseServer::Embedded () const inline
Definition at line 33 of file DataBaseServer.h.
void MLL::DataBaseServer::Embedded (bool _embedded) inline
Definition at line 41 of file DataBaseServer.h.
const KKStr& MLL::DataBaseServer::HostName () const inline
Definition at line 34 of file DataBaseServer.h.
Referenced by PicesInterface::PicesDataBase::GetGlobalDatabaseManagerNewInstance().
void MLL::DataBaseServer::HostName (const KKStr & _hostName) inline
Definition at line 42 of file DataBaseServer.h.
const KKStr& MLL::DataBaseServer::MySqlDataDir () const inline
Definition at line 35 of file DataBaseServer.h.
void MLL::DataBaseServer::MySqlDataDir (const KKStr & _mySqlDataDir) inline
Definition at line 43 of file DataBaseServer.h.
const KKStr& MLL::DataBaseServer::PassWord () const inline
Definition at line 36 of file DataBaseServer.h.
void MLL::DataBaseServer::PassWord (const KKStr & _passWord) inline
Definition at line 44 of file DataBaseServer.h.
KKStr DataBaseServer::ServerDescription () const
Definition at line 76 of file DataBaseServer.cpp.
Referenced by MLL::DataBase::ServerDescription().
KKStr DataBaseServer::ToParameterStr () const
Definition at line 119 of file DataBaseServer.cpp.
const KKStr& MLL::DataBaseServer::UserName () const inline
Definition at line 37 of file DataBaseServer.h.
Referenced by PicesInterface::PicesDataBase::GetGlobalDatabaseManagerNewInstance().
void MLL::DataBaseServer::UserName (const KKStr & _userName) inline
Definition at line 45 of file DataBaseServer.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/DataBaseServer.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/DataBaseServer.cpp