Pices: MLL::TrainingConfiguration2 Class Reference
MLL::TrainingConfiguration2 Class Reference
#include <TrainingConfiguration2.h>
Public Types
typedef Model::ModelTypes ModelTypes
typedef TrainingConfiguration2 * TrainingConfiguration2Ptr
Public Member Functions
TrainingConfiguration2 (FileDescPtr _fileDesc, const KKStr &_configFileName, RunLog &_log, bool validateDirectories=true)
TrainingConfiguration2 (const TrainingConfiguration2 &tc)
TrainingConfiguration2 (FileDescPtr _fileDesc, MLClassConstListPtr _mlClasses, KKStr _parameterStr, RunLog &_log)
TrainingConfiguration2 (FileDescPtr _fileDesc, MLClassConstListPtr _mlClasses, ModelParamPtr _modelParameters, RunLog &_log)
~TrainingConfiguration2 ()
float A_Param () const
void A_Param (float _aParam)
void AddATrainingClass (TrainingClassPtr _trainClass)
Add a Training class to configuration Will take ownership of allocation.
void AddATrainingClass (MLClassConstPtr _newClass)
Will assume that images for this class will be saved off the RootDirectory using its own name for the subdirectory name.
float AvgNumOfFeatures () const
float AvgNumOfFeatures (FeatureVectorListPtr trainExamples) const
const BinaryClassParmsPtr BinaryClassParms (MLClassConstPtr class1, MLClassConstPtr class2) const
int32 BitsToReduceBy () const
void BitsToReduceBy (int32 bitReduction)
double C_Param () const
double C_Param (MLClassConstPtr class1, MLClassConstPtr class2) const
void C_Param (double _CCC)
void C_Param (MLClassConstPtr class1, MLClassConstPtr class2, double cParam)
SVM_CompressionMethod CompressionMethod () const
void CompressionMethod (SVM_CompressionMethod _compMethod)
const KKStr & ConfigFileNameSpecified () const
KKStr DirectoryPathForClass (MLClassConstPtr mlClass) const
void EmptyTrainingClasses ()
SVM_EncodingMethod EncodingMethod () const
void EncodingMethod (SVM_EncodingMethod _encodingMethod)
int32 ExamplesPerClass () const
void ExamplesPerClass (int32 _examplesPerClass)
MLClassConstListPtr ExtractClassList () const
Constructs new list of classes that caller will own.
MLClassConstListPtr ExtractListOfClassesForAGivenHierarchialLevel (uint32 level) const
FileDescPtr FileDesc () const
double Gamma () const
void Gamma (double _gamma)
TrainingConfiguration2Ptr GenerateAConfiguraionForAHierarchialLevel (uint32 level)
BinaryClassParmsPtr GetBinaryClassParms (MLClassConstPtr class1, MLClassConstPtr class2)
if BinaryClass parms exist for the two specified classes will return otherwise NULL.
FeatureNumList GetFeatureNums () const
FeatureNumList GetFeatureNums (MLClassConstPtr class1, MLClassConstPtr class2)
Returns feature nums that are assigned to the given class pair; If none were specified for that pair will return global feature nums.
int32 ImagesPerClass () const
void ImagesPerClass (int32 _imagesPerClass)
SVM_KernalType KernalType () const
void KernalType (SVM_KernalType _kernalType)
FeatureVectorListPtr LoadFeatureDataFromTrainingLibraries (KKU::DateTime &latestImageTimeStamp, bool &changesMadeToTrainingLibraries, bool &cancelFlag)
Load traning data from the trainig libraries.
FeatureVectorListPtr LoadOtherClasssExamples ()
TrainingClassPtr LocateByMLClassName (const KKStr &className)
SVM_MachineType MachineType () const
void MachineType (SVM_MachineType _machineType)
Model::ModelTypes ModelingMethod () const
KKStr ModelParameterCmdLine () const
ModelParamPtr ModelParameters () const
void ModelParameters (ModelParamPtr _modelParameters)
Model::ModelTypes ModelType () const
KKStr ModelTypeStr () const
int32 NoiseGuaranteedSize () const
MLClassConstPtr NoiseMLClass () const
const TrainingClassPtr NoiseTrainingClass () const
bool NormalizeNominalFeatures ()
int32 Number_of_rounds () const
void Number_of_rounds (int32 _number_of_rounds)
uint32 NumHierarchialLevels () const
returns back the number of hierarchail levels there are in the trainingClass that has the most.
int32 NumOfFeaturesAfterEncoding () const
int32 NumOfRounds () const
void NumOfRounds (int32 _numOfRounds)
MLClassConstPtr OtherClass () const
const KKStr & RootDir () const
void RootDir (const KKStr &_rootDir)
void Save (const KKStr &fileName)
SVM_SelectionMethod SelectionMethod () const
void SelectionMethod (SVM_SelectionMethod _selectionMethod)
void SetBinaryClassFields (MLClassConstPtr class1, MLClassConstPtr class2, const SVM233::svm_parameter &_param, const FeatureNumList &_features, float _weight)
void SetFeatureNums (const FeatureNumList &features)
void SetFeatureNums (MLClassConstPtr class1, MLClassConstPtr class2, const FeatureNumList &_features, float _weight=-1)
void SetModelParameters (ModelParamPtr _svmParanters, int32 _examplesPerClass)
void SetTrainingClasses (TrainingClassListPtr _trainingClasses)
const SVMparam & SVMparamREF () const
const TrainingClassList & TrainingClasses () const
int32 UnBalancedBits () const
void UnBalancedBits (int32 _unBalancedBits)
KKStr UnBalancedBitsStr () const
void UnBalancedBitsStr (const KKStr &_unBalancedBitsStr)
bool WeightBitReduction () const
void WeightBitReduction (bool _weightBitReduction)
Static Public Member Functions
static bool ConfigFileExists (const KKStr &_configFileName)
static TrainingConfiguration2 * CreateFromDirectoryStructure (FileDescPtr _fileDesc, const KKStr &_existingConfigFileName, const KKStr &_subDir, RunLog &_log, bool &_successful, KKStr &_errorMessage)
static TrainingConfiguration2 * CreateFromFeatureVectorList (FeatureVectorList &_examples, const KKStr &_parameterStr, RunLog &_log)
static KKStr GetEffectiveConfigFileName (const KKStr &configFileName)
Determine the correct csonfiguration file name.
static ModelTypes ModelTypeFromStr (const KKStr &_modelTypeStr)
static KKStr ModelTypeToStr (ModelTypes _modelType)
static TrainingConfiguration2Ptr PromptForConfigurationFile (RunLog &log)
Detailed Description
Definition at line 36 of file TrainingConfiguration2.h.
Member Typedef Documentation
typedef Model::ModelTypes MLL::TrainingConfiguration2::ModelTypes
Definition at line 39 of file TrainingConfiguration2.h.
typedef TrainingConfiguration2* MLL::TrainingConfiguration2::TrainingConfiguration2Ptr
Definition at line 41 of file TrainingConfiguration2.h.
Constructor & Destructor Documentation
MLL::TrainingConfiguration2::TrainingConfiguration2 (FileDescPtr _fileDesc, const KKStr & _configFileName, RunLog & _log, bool validateDirectories = true)
Referenced by GenerateAConfiguraionForAHierarchialLevel(), and PromptForConfigurationFile().
TrainingConfiguration2::TrainingConfiguration2 (const TrainingConfiguration2 & tc)
Definition at line 321 of file TrainingConfiguration2.cpp.
References MLL::ModelParam::Duplicate(), and x.
MLL::TrainingConfiguration2::TrainingConfiguration2 (FileDescPtr _fileDesc, MLClassConstListPtr _mlClasses, KKStr _parameterStr, RunLog & _log)
MLL::TrainingConfiguration2::TrainingConfiguration2 (FileDescPtr _fileDesc, MLClassConstListPtr _mlClasses, ModelParamPtr _modelParameters, RunLog & _log)
Parameters
_modelParameters Will take ownership of this instance.
TrainingConfiguration2::~TrainingConfiguration2 ()
Definition at line 568 of file TrainingConfiguration2.cpp.
Member Function Documentation
float TrainingConfiguration2::A_Param () const
Definition at line 911 of file TrainingConfiguration2.cpp.
References MLL::ModelParam::A_Param().
void TrainingConfiguration2::A_Param (float _aParam)
Definition at line 921 of file TrainingConfiguration2.cpp.
References MLL::ModelParam::A_Param().
void TrainingConfiguration2::AddATrainingClass (TrainingClassPtr _trainClass)
Add a Training class to configuration Will take ownership of allocation.
Definition at line 853 of file TrainingConfiguration2.cpp.
Referenced by AddATrainingClass(), PicesInterface::TrainingModel2::AddClass(), MLL::CrossValidationThreeWay::CrossValidationThreeWay(), GenerateAConfiguraionForAHierarchialLevel(), and SetTrainingClasses().
void TrainingConfiguration2::AddATrainingClass (MLClassConstPtr _newClass)
Will assume that images for this class will be saved off the RootDirectory using its own name for the subdirectory name.
Definition at line 861 of file TrainingConfiguration2.cpp.
References AddATrainingClass().
float TrainingConfiguration2::AvgNumOfFeatures () const
Definition at line 1225 of file TrainingConfiguration2.cpp.
References MLL::ModelParam::AvgMumOfFeatures().
float TrainingConfiguration2::AvgNumOfFeatures (FeatureVectorListPtr trainExamples) const
Definition at line 1235 of file TrainingConfiguration2.cpp.
References MLL::SVMparam::AvgNumOfFeatures().
const BinaryClassParmsPtr TrainingConfiguration2::BinaryClassParms (MLClassConstPtr class1, MLClassConstPtr class2) const
Definition at line 2340 of file TrainingConfiguration2.cpp.
References MLL::SVMparam::GetParamtersToUseFor2ClassCombo().
int32 TrainingConfiguration2::BitsToReduceBy () const
Definition at line 929 of file TrainingConfiguration2.cpp.
References MLL::ModelParam::BitsToReduceBy().
void MLL::TrainingConfiguration2::BitsToReduceBy (int32 bitReduction)
double TrainingConfiguration2::C_Param () const
Definition at line 967 of file TrainingConfiguration2.cpp.
References MLL::ModelParam::C_Param().
double TrainingConfiguration2::C_Param (MLClassConstPtr class1, MLClassConstPtr class2) const
Definition at line 1168 of file TrainingConfiguration2.cpp.
References MLL::ModelParamOldSVM::C_Param().
void TrainingConfiguration2::C_Param (double _CCC)
Definition at line 977 of file TrainingConfiguration2.cpp.
References MLL::ModelParam::C_Param().
void TrainingConfiguration2::C_Param (MLClassConstPtr class1, MLClassConstPtr class2, double cParam)
Definition at line 1182 of file TrainingConfiguration2.cpp.
References MLL::ModelParamOldSVM::C_Param().
SVM_CompressionMethod TrainingConfiguration2::CompressionMethod () const
Definition at line 1060 of file TrainingConfiguration2.cpp.
References MLL::BRnoCompression, and MLL::ModelParam::CompressionMethod().
void TrainingConfiguration2::CompressionMethod (SVM_CompressionMethod _compMethod)
Definition at line 1051 of file TrainingConfiguration2.cpp.
References MLL::ModelParam::CompressionMethod().
bool TrainingConfiguration2::ConfigFileExists (const KKStr & _configFileName) static
Definition at line 2197 of file TrainingConfiguration2.cpp.
References GetEffectiveConfigFileName(), and KKU::osFileExists().
Referenced by MLL::ModelDual::TrainModel().
const KKStr& MLL::TrainingConfiguration2::ConfigFileNameSpecified () const inline
Definition at line 97 of file TrainingConfiguration2.h.
Referenced by PicesInterface::PicesTrainingConfiguration::ModelName().
TrainingConfiguration2Ptr TrainingConfiguration2::CreateFromDirectoryStructure (FileDescPtr _fileDesc, const KKStr & _existingConfigFileName, const KKStr & _subDir, RunLog & _log, bool & _successful, KKStr & _errorMessage) static
Definition at line 667 of file TrainingConfiguration2.cpp.
References MLL::TrainingClassList::DuplicateListAndContents(), KKU::KKStr::Empty(), EmptyTrainingClasses(), KKU::endl(), MLL::TrainingClass::ExpandedDirectory(), MLL::TrainingClass::FeatureFileName(), Gamma(), ImagesPerClass(), KKU::RunLog::Level(), MLL::TrainingClassList::LocateByDirectory(), MLL::TrainingClass::MLClass(), ModelParameters(), MLL::FeatureFileIOPices::NewPlanktonFile(), KKU::osAddSlash(), KKU::osFileExists(), KKU::osGetRootNameOfDirectory(), MLL::ModelParamOldSVM::ParseCmdLine(), RootDir(), Save(), and TrainingClasses().
TrainingConfiguration2Ptr TrainingConfiguration2::CreateFromFeatureVectorList (FeatureVectorList & _examples, const KKStr & _parameterStr, RunLog & _log) static
Definition at line 612 of file TrainingConfiguration2.cpp.
References MLL::FeatureVectorList::AllFeatures(), KKU::KKStr::Empty(), KKU::endl(), MLL::FeatureVectorList::ExtractMLClassConstList(), MLL::FeatureVectorList::FileDesc(), KKU::RunLog::Level(), SetFeatureNums(), and MLL::MLClassConstList::SortByName().
KKStr TrainingConfiguration2::DirectoryPathForClass (MLClassConstPtr mlClass) const
Definition at line 380 of file TrainingConfiguration2.cpp.
References MLL::TrainingClass::ExpandedDirectory(), and MLL::TrainingClass::MLClass().
Referenced by PicesInterface::TrainingModel2::AddClass(), PicesInterface::TrainingModel2::AddImageToTrainingLibray(), PicesInterface::TrainingModel2::DirectoryPathForClass(), and PicesInterface::TrainingModel2::IncludesClass().
void TrainingConfiguration2::EmptyTrainingClasses ()
Definition at line 1873 of file TrainingConfiguration2.cpp.
Referenced by CreateFromDirectoryStructure(), MLL::CrossValidationThreeWay::CrossValidationThreeWay(), GenerateAConfiguraionForAHierarchialLevel(), and SetTrainingClasses().
SVM_EncodingMethod TrainingConfiguration2::EncodingMethod () const
Definition at line 1137 of file TrainingConfiguration2.cpp.
References MLL::SVMparam::EncodingMethod(), and MLL::NoEncoding.
void TrainingConfiguration2::EncodingMethod (SVM_EncodingMethod _encodingMethod)
Definition at line 1129 of file TrainingConfiguration2.cpp.
References MLL::ModelParam::EncodingMethod().
int32 TrainingConfiguration2::ExamplesPerClass () const
Definition at line 1320 of file TrainingConfiguration2.cpp.
Referenced by CreateBfsFromMfs(), MLL::CrossValidation::CrossValidation(), and ImagesPerClass().
void MLL::TrainingConfiguration2::ExamplesPerClass (int32 _examplesPerClass)
MLClassConstListPtr TrainingConfiguration2::ExtractClassList () const
Constructs new list of classes that caller will own.
Definition at line 644 of file TrainingConfiguration2.cpp.
References MLL::TrainingClass::MLClass(), MLL::MLClassConstList::PushOnBack(), and MLL::MLClassConstList::SortByName().
Referenced by CreateBfsFromMfs(), PicesInterface::PicesTrainingConfiguration::ExtractClassList(), PicesInterface::PicesTrainingConfiguration::PicesTrainingConfiguration(), CrossValidationApp::ProcessCmdLineParameters(), and PicesInterface::TrainingModel2::TrainingModel2().
MLClassConstListPtr TrainingConfiguration2::ExtractListOfClassesForAGivenHierarchialLevel (uint32 level) const
Definition at line 436 of file TrainingConfiguration2.cpp.
References MLL::MLClassConstList::AddMLClass().
Referenced by GenerateAConfiguraionForAHierarchialLevel().
FileDescPtr MLL::TrainingConfiguration2::FileDesc () const inline
Definition at line 100 of file TrainingConfiguration2.h.
double TrainingConfiguration2::Gamma () const
Definition at line 949 of file TrainingConfiguration2.cpp.
References MLL::ModelParam::Gamma().
Referenced by CreateFromDirectoryStructure().
void TrainingConfiguration2::Gamma (double _gamma)
Definition at line 959 of file TrainingConfiguration2.cpp.
References MLL::ModelParam::Gamma().
TrainingConfiguration2Ptr TrainingConfiguration2::GenerateAConfiguraionForAHierarchialLevel (uint32 level)
Definition at line 455 of file TrainingConfiguration2.cpp.
References AddATrainingClass(), MLL::TrainingClass::Directory(), EmptyTrainingClasses(), KKU::endl(), ExtractListOfClassesForAGivenHierarchialLevel(), KKU::RunLog::Level(), MLL::TrainingClass::MLClass(), and TrainingConfiguration2().
BinaryClassParmsPtr TrainingConfiguration2::GetBinaryClassParms (MLClassConstPtr class1, MLClassConstPtr class2)
if BinaryClass parms exist for the two specified classes will return otherwise NULL.
Definition at line 2355 of file TrainingConfiguration2.cpp.
References MLL::SVMparam::GetBinaryClassParms().
Referenced by CreateBfsFromMfs().
KKStr TrainingConfiguration2::GetEffectiveConfigFileName (const KKStr & configFileName) static
Determine the correct csonfiguration file name.
If no extension then add ".cfg" to end of file name.                                                 *
                                                                                                     *
If  Path Provided                                                                                    *
{                                                                                                    *
   Return name as submitted with added extension.                                                    *
}                                                                                                    *
else                                                                                                 *
{                                                                                                    *
   a. If file exists if default directory;  then return name with defalt directory path.             *
   b. If file exists in Training Model Directory  $(PicesHomeDir) + "\\DataFiles\\TrainingModels"    *
      then return with Training Model Directory.                                                     *
   c. Since not found then we will return name passed in with extension.                             *
}                                                                                                    *
Definition at line 2160 of file TrainingConfiguration2.cpp.
References KKU::KKStr::Empty(), KKU::osAddSlash(), KKU::osFileExists(), KKU::osGetCurrentDirectory(), KKU::osGetFileExtension(), KKU::osGetPathPartOfFile(), KKU::osGetRootNameWithExtension(), and KKU::osRemoveExtension().
Referenced by ConfigFileExists().
FeatureNumList TrainingConfiguration2::GetFeatureNums () const
Definition at line 1292 of file TrainingConfiguration2.cpp.
References MLL::ModelParam::SelectedFeatures().
Referenced by MLL::CrossValidationThreeWay::CreateDistanceReport(), MLL::CrossValidationThreeWay::CreateProbabilityReport(), and CrossValidationApp::ReportConfigurationInfo().
FeatureNumList TrainingConfiguration2::GetFeatureNums (MLClassConstPtr class1, MLClassConstPtr class2)
Returns feature nums that are assigned to the given class pair; If none were specified for that pair will return global feature nums.
Definition at line 1329 of file TrainingConfiguration2.cpp.
References MLL::FeatureNumList::AllFeatures(), and MLL::ModelParamOldSVM::GetFeatureNums().
int32 MLL::TrainingConfiguration2::ImagesPerClass () const inline
Definition at line 102 of file TrainingConfiguration2.h.
References ExamplesPerClass().
Referenced by CreateFromDirectoryStructure(), and CrossValidationApp::Main().
void MLL::TrainingConfiguration2::ImagesPerClass (int32 _imagesPerClass) inline
Definition at line 148 of file TrainingConfiguration2.h.
References ExamplesPerClass().
SVM_KernalType TrainingConfiguration2::KernalType () const
Definition at line 1247 of file TrainingConfiguration2.cpp.
References MLL::SVMparam::KernalType(), and MLL::KT_Linear.
void TrainingConfiguration2::KernalType (SVM_KernalType _kernalType)
Definition at line 1258 of file TrainingConfiguration2.cpp.
References MLL::SVMparam::KernalType().
FeatureVectorListPtr TrainingConfiguration2::LoadFeatureDataFromTrainingLibraries (KKU::DateTime & latestImageTimeStamp, bool & changesMadeToTrainingLibraries, bool & cancelFlag)
Load traning data from the trainig libraries.
Description:   Loads all the FeatureData from the Training Library.  The images in the     *
               subdirectoris sepecified by the 'TrainingClass' entries will be used as the *
               primary source.  Data from existing FeatureData files will be used unless   *
               they are out of date.  In that case the data will be recomputed from the    *
               original images.                                                            *
                                                                                           *
ImageFileName: This field that is in each 'ImageFeatures' object will reflect the sub-     *
               directory from where it was retrieved.  Bewteen that and the 'rootDir' field*
               you will be able to get the full path to then original image.               *
Parameters
[out] latestImageTimeStamp Timestamp of the most current image loaded.
[out] changesMadeToTrainingLibraries True if any image needed to have its features recalculated or images were removed or added to a training directory.
[in] cancelFlag Will monitior this flag. If it gets set to true will terminate the load and return.
Definition at line 1981 of file TrainingConfiguration2.cpp.
References MLL::FeatureVectorList::AddQueue(), KKU::endl(), MLL::TrainingClass::ExpandedDirectory(), KKU::RunLog::Level(), MLL::TrainingClass::Name(), and NoiseTrainingClass().
Referenced by PicesInterface::PicesTrainingConfiguration::LoadFeatureDataFromTrainingLibraries(), and CrossValidationApp::ProcessCmdLineParameters().
FeatureVectorListPtr TrainingConfiguration2::LoadOtherClasssExamples ()
Definition at line 1923 of file TrainingConfiguration2.cpp.
References KKU::KKStr::Empty(), MLL::FeatureFileIOPices::FeatureDataReSink(), and KKU::osAddSlash().
TrainingClassPtr TrainingConfiguration2::LocateByMLClassName (const KKStr & className)
Definition at line 1865 of file TrainingConfiguration2.cpp.
References MLL::TrainingClassList::LocateByMLClassName().
SVM_MachineType TrainingConfiguration2::MachineType () const
Definition at line 1039 of file TrainingConfiguration2.cpp.
References MLL::ModelParamOldSVM::MachineType(), and MLL::MachineType_NULL.
Referenced by CreateBfsFromMfs().
void TrainingConfiguration2::MachineType (SVM_MachineType _machineType)
Definition at line 1028 of file TrainingConfiguration2.cpp.
References MLL::ModelParamOldSVM::MachineType().
Model::ModelTypes MLL::TrainingConfiguration2::ModelingMethod () const inline
Definition at line 105 of file TrainingConfiguration2.h.
Referenced by MLL::TrainingProcess2::CreateModelsFromTrainingData(), and CrossValidationApp::ReportConfigurationInfo().
KKStr TrainingConfiguration2::ModelParameterCmdLine () const
Definition at line 599 of file TrainingConfiguration2.cpp.
References ModelParameters(), and MLL::ModelParam::ToCmdLineStr().
ModelParamPtr MLL::TrainingConfiguration2::ModelParameters () const inline
Definition at line 116 of file TrainingConfiguration2.h.
Referenced by CreateFromDirectoryStructure(), MLL::TrainingProcess2::CreateModelsFromTrainingData(), ModelParameterCmdLine(), and CrossValidationApp::ReportConfigurationInfo().
void TrainingConfiguration2::ModelParameters (ModelParamPtr _modelParameters)
Definition at line 591 of file TrainingConfiguration2.cpp.
References MLL::ModelParam::Duplicate().
Model::ModelTypes MLL::TrainingConfiguration2::ModelType () const inline
Definition at line 106 of file TrainingConfiguration2.h.
static ModelTypes MLL::TrainingConfiguration2::ModelTypeFromStr (const KKStr & _modelTypeStr) inline static
Definition at line 87 of file TrainingConfiguration2.h.
References MLL::Model::ModelTypeFromStr().
KKStr MLL::TrainingConfiguration2::ModelTypeStr () const inline
Definition at line 107 of file TrainingConfiguration2.h.
References MLL::Model::ModelTypeToStr().
Referenced by MLL::ModelDual::Description().
static KKStr MLL::TrainingConfiguration2::ModelTypeToStr (ModelTypes _modelType) inline static
Definition at line 86 of file TrainingConfiguration2.h.
References MLL::Model::ModelTypeToStr().
Referenced by MLL::operator<<(), and Save().
int32 MLL::TrainingConfiguration2::NoiseGuaranteedSize () const inline
Definition at line 110 of file TrainingConfiguration2.h.
MLClassConstPtr MLL::TrainingConfiguration2::NoiseMLClass () const inline
Definition at line 108 of file TrainingConfiguration2.h.
const TrainingClassPtr MLL::TrainingConfiguration2::NoiseTrainingClass () const inline
Definition at line 109 of file TrainingConfiguration2.h.
Referenced by MLL::TrainingProcess2::ExtractTrainingClassFeatures(), and LoadFeatureDataFromTrainingLibraries().
bool TrainingConfiguration2::NormalizeNominalFeatures ()
Definition at line 1886 of file TrainingConfiguration2.cpp.
References MLL::ModelParam::NormalizeNominalFeatures().
int32 TrainingConfiguration2::Number_of_rounds () const
Definition at line 985 of file TrainingConfiguration2.cpp.
References MLL::ModelParam::ModelParamType(), and MLL::ModelParam::mptUsfCasCor.
Referenced by NumOfRounds().
void MLL::TrainingConfiguration2::Number_of_rounds (int32 _number_of_rounds)
uint32 TrainingConfiguration2::NumHierarchialLevels () const
returns back the number of hierarchail levels there are in the trainingClass that has the most.
Definition at line 395 of file TrainingConfiguration2.cpp.
References SVM289_MFS::Max(), and MLL::TrainingClass::MLClass().
Referenced by PicesInterface::PicesTrainingConfiguration::NumHierarchialLevels().
int32 TrainingConfiguration2::NumOfFeaturesAfterEncoding () const
Definition at line 1303 of file TrainingConfiguration2.cpp.
References MLL::ModelParam::NumOfFeaturesAfterEncoding().
int32 MLL::TrainingConfiguration2::NumOfRounds () const inline
Definition at line 111 of file TrainingConfiguration2.h.
References Number_of_rounds().
void MLL::TrainingConfiguration2::NumOfRounds (int32 _numOfRounds) inline
Definition at line 152 of file TrainingConfiguration2.h.
References Number_of_rounds().
MLClassConstPtr MLL::TrainingConfiguration2::OtherClass () const inline
Definition at line 113 of file TrainingConfiguration2.h.
Referenced by PicesInterface::PicesTrainingConfiguration::OtherClass().
TrainingConfiguration2Ptr TrainingConfiguration2::PromptForConfigurationFile (RunLog & log) static
Definition at line 2206 of file TrainingConfiguration2.cpp.
References KKU::endl(), MLL::FeatureFileIOPices::NewPlanktonFile(), KKU::osAddSlash(), KKU::osGetListOfFiles(), KKU::osWaitForEnter(), KKU::StrFormatInt(), TrainingConfiguration2(), and x.
const KKStr& MLL::TrainingConfiguration2::RootDir () const inline
Definition at line 114 of file TrainingConfiguration2.h.
Referenced by PicesInterface::TrainingModel2::AddClass(), CreateBfsFromMfs(), CreateFromDirectoryStructure(), CrossValidationApp::LocateImageFileUsingConfigurationFile(), CrossValidationApp::ReportConfigurationInfo(), and PicesInterface::PicesTrainingConfiguration::RootDir().
void MLL::TrainingConfiguration2::RootDir (const KKStr & _rootDir)
void TrainingConfiguration2::Save (const KKStr & fileName)
Definition at line 481 of file TrainingConfiguration2.cpp.
References MLL::ModelParamOldSVM::BinaryParmsList(), MLL::BinaryClassParms::Class1Name(), MLL::BinaryClassParms::Class2Name(), MLL::TrainingClass::Directory(), KKU::KKStr::Empty(), KKU::endl(), ModelTypeToStr(), MLL::TrainingClass::Name(), MLL::BinaryClassParms::Param(), MLL::BinaryClassParms::SelectedFeatures(), MLL::ModelParam::SelectedFeatures(), KKU::KKStr::StartsWith(), KKU::KKStr::Str(), SVM233::svm_parameter::ToCmdLineStr(), MLL::ModelParam::ToCmdLineStr(), MLL::FeatureNumList::ToString(), KKU::KKStr::TrimLeft(), KKU::KKStr::TrimRight(), MLL::BinaryClassParms::Weight(), and MLL::TrainingClass::Weight().
Referenced by CreateBfsFromMfs(), CreateFromDirectoryStructure(), CrossValidationApp::ProcessCmdLineParameters(), PicesInterface::PicesTrainingConfiguration::Save(), PicesInterface::TrainingModel2::SaveConfiguration(), SetUpJMLRDataSet(), and SplitUpETPdataSet().
SVM_SelectionMethod TrainingConfiguration2::SelectionMethod () const
Definition at line 1080 of file TrainingConfiguration2.cpp.
References MLL::ModelParamOldSVM::SelectionMethod(), and MLL::SelectionMethod_NULL.
Referenced by CreateBfsFromMfs().
void TrainingConfiguration2::SelectionMethod (SVM_SelectionMethod _selectionMethod)
Definition at line 1071 of file TrainingConfiguration2.cpp.
References MLL::ModelParamOldSVM::SelectionMethod().
void TrainingConfiguration2::SetBinaryClassFields (MLClassConstPtr class1, MLClassConstPtr class2, const SVM233::svm_parameter & _param, const FeatureNumList & _features, float _weight)
Definition at line 1198 of file TrainingConfiguration2.cpp.
References MLL::ModelParamOldSVM::SetBinaryClassFields().
Referenced by CreateBfsFromMfs().
void TrainingConfiguration2::SetFeatureNums (const FeatureNumList & features)
Definition at line 1091 of file TrainingConfiguration2.cpp.
References KKU::endl(), MLL::FeatureNumList::FileDesc(), KKU::RunLog::Level(), and MLL::ModelParam::SelectedFeatures().
Referenced by CreateBfsFromMfs(), CreateFromFeatureVectorList(), and CrossValidationApp::RandomlySelectedProcessResults().
void TrainingConfiguration2::SetFeatureNums (MLClassConstPtr class1, MLClassConstPtr class2, const FeatureNumList & _features, float _weight = -1)
Definition at line 1112 of file TrainingConfiguration2.cpp.
References MLL::ModelParamOldSVM::SetFeatureNums().
void TrainingConfiguration2::SetModelParameters (ModelParamPtr _svmParanters, int32 _examplesPerClass)
Definition at line 1344 of file TrainingConfiguration2.cpp.
References MLL::ModelParam::Duplicate().
void TrainingConfiguration2::SetTrainingClasses (TrainingClassListPtr _trainingClasses)
Definition at line 1213 of file TrainingConfiguration2.cpp.
References AddATrainingClass(), and EmptyTrainingClasses().
const SVMparam & TrainingConfiguration2::SVMparamREF () const
Definition at line 875 of file TrainingConfiguration2.cpp.
References KKU::endl(), KKU::RunLog::Level(), and MLL::ModelParamOldSVM::SvmParameters().
const TrainingClassList& MLL::TrainingConfiguration2::TrainingClasses () const inline
Definition at line 115 of file TrainingConfiguration2.h.
Referenced by CreateFromDirectoryStructure(), MLL::TrainingProcess2::ExtractTrainingClassFeatures(), CrossValidationApp::LocateImageFileUsingConfigurationFile(), CrossValidationApp::ReportConfigurationInfo(), and PicesInterface::PicesTrainingConfiguration::TrainingClasses().
int32 TrainingConfiguration2::UnBalancedBits () const
Definition at line 1268 of file TrainingConfiguration2.cpp.
References MLL::ModelParam::UnBalancedBits().
void MLL::TrainingConfiguration2::UnBalancedBits (int32 _unBalancedBits)
KKStr TrainingConfiguration2::UnBalancedBitsStr () const
Definition at line 1279 of file TrainingConfiguration2.cpp.
References MLL::SVMparam::UnBalancedBitsStr().
void MLL::TrainingConfiguration2::UnBalancedBitsStr (const KKStr & _unBalancedBitsStr)
bool TrainingConfiguration2::WeightBitReduction () const
Definition at line 1157 of file TrainingConfiguration2.cpp.
References MLL::ModelParam::WeightBitReduction().
void TrainingConfiguration2::WeightBitReduction (bool _weightBitReduction)
Definition at line 1149 of file TrainingConfiguration2.cpp.
References MLL::ModelParam::WeightBitReduction().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/TrainingConfiguration2.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/TrainingConfiguration2.cpp