Pices: KKU::SimpleCompressor Class Reference
KKU::SimpleCompressor Class Reference
#include <SimpleCompressor.h>
Public Member Functions
SimpleCompressor (uint32 estimatedMaxBuffSize)
SimpleCompressor (uchar *compressdBuff)
~SimpleCompressor ()
void Add16BitInt (uint32 i)
void AddByte (uchar b)
uchar * CreateCompressedBuffer (uint32 &compressedBuffserSize)
Static Public Member Functions
static uchar * Decompress (const uchar *compressedBuff, uint32 compressedBuffLen, uint32 &unCompressedSize)
Detailed Description
Definition at line 10 of file SimpleCompressor.h.
Constructor & Destructor Documentation
SimpleCompressor::SimpleCompressor (uint32 estimatedMaxBuffSize)
Definition at line 23 of file SimpleCompressor.cpp.
KKU::SimpleCompressor::SimpleCompressor (uchar * compressdBuff)
SimpleCompressor::~SimpleCompressor ()
Definition at line 36 of file SimpleCompressor.cpp.
Member Function Documentation
void SimpleCompressor::Add16BitInt (uint32 i)
Definition at line 44 of file SimpleCompressor.cpp.
Referenced by KKU::RasterSipper::SimpleCompression().
void SimpleCompressor::AddByte (uchar b)
Definition at line 52 of file SimpleCompressor.cpp.
Referenced by KKU::RasterSipper::SimpleCompression().
uchar * SimpleCompressor::CreateCompressedBuffer (uint32 & compressedBuffserSize)
Definition at line 171 of file SimpleCompressor.cpp.
References KKU::endl(), KKU::osGetLocalDateTime(), and x.
Referenced by KKU::RasterSipper::SimpleCompression().
uchar * SimpleCompressor::Decompress (const uchar * compressedBuff, uint32 compressedBuffLen, uint32 & unCompressedSize) static
Definition at line 254 of file SimpleCompressor.cpp.
References KKU::endl(), KKU::osGetLocalDateTime(), and x.
Referenced by KKU::RasterSipper::FromSimpleCompression().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/SimpleCompressor.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/SimpleCompressor.cpp