Pices: MLL::ModelOldSVM Class Reference
MLL::ModelOldSVM Class Reference
#include <ModelOldSVM.h>
Public Types
typedef ModelOldSVM * ModelOldSVMPtr
Public Types inherited from MLL::Model
typedef Model * ModelPtr
enum ModelTypes {
mtNULL = 0, mtOldSVM = 1, mtSvmBase = 2, mtKNN = 3,
mtUsfCasCor = 4, mtDual = 5
}
Public Member Functions
ModelOldSVM (FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
ModelOldSVM (const KKStr &_name, const ModelParamOldSVM &_param, FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
ModelOldSVM (const ModelOldSVM &_madel)
virtual ~ModelOldSVM ()
Frees any memory allocated by, and owned by the ModelOldSVM.
const ClassAssignments & Assignments () const
virtual KKStr Description () const
Return short user readable description of model.
virtual ModelOldSVMPtr Duplicate () const
vector< ProbNamePair > FindWorstSupportVectors (FeatureVectorPtr example, int32 numToFind, MLClassConstPtr c1, MLClassConstPtr c2)
For a given two class pair return the names of the 'numToFind' worst S/V's.
vector< ProbNamePair > FindWorstSupportVectors2 (FeatureVectorPtr example, int32 numToFind, MLClassConstPtr c1, MLClassConstPtr c2)
For a given two class pair return the names of the 'numToFind' worst S/V's.
const FeatureNumList & GetFeatureNums () const
FeatureNumList GetFeatureNums (MLClassConstPtr class1, MLClassConstPtr class2)
virtual KKU::int32 MemoryConsumedEstimated () const
virtual ModelTypes ModelType () const
virtual bool NormalizeNominalAttributes () const
Return true, if nominal fields need to be normalized.
int32 NumOfSupportVectors () const
ModelParamOldSVMPtr Param () const
virtual MLClassConstPtr Predict (FeatureVectorPtr image)
virtual void Predict (FeatureVectorPtr example, MLClassConstPtr knownClass, MLClassConstPtr &predClass1, MLClassConstPtr &predClass2, int32 &predClass1Votes, int32 &predClass2Votes, double &probOfKnownClass, double &predClass1Prob, double &predClass2Prob, double &compact, int32 &numOfWinners, bool &knownClassOneOfTheWinners, double &breakTie)
virtual FeatureVectorPtr PrepExampleForPrediction (FeatureVectorPtr fv, bool &newExampleCreated)
ModelOldSVM Specific 'PrepExampleForPrediction' will only normalize data.
virtual ClassProbListPtr ProbabilitiesByClass (FeatureVectorPtr example)
virtual void ProbabilitiesByClass (FeatureVectorPtr example, const MLClassConstList &_mlClasses, int32 *_votes, double *_probabilities)
virtual void ProbabilitiesByClass (FeatureVectorPtr _example, const MLClassConstList &_mlClasses, double *_probabilities)
Will get the probabilities assigned to each class.
virtual void ReadSpecificImplementationXML (istream &i, bool &_successful)
void RetrieveCrossProbTable (MLClassConstList &classes, double **crossProbTable)
SVM_SelectionMethod SelectionMethod () const
vector< KKStr > SupportVectorNames () const
vector< KKStr > SupportVectorNames (MLClassConstPtr c1, MLClassConstPtr c2) const
void SupportVectorStatistics (int32 &numSVs, int32 &totalNumSVs)
SVMModelPtr SvmModel () const
virtual void TrainModel (FeatureVectorListPtr _trainExamples, bool _alreadyNormalized, bool _takeOwnership)
Use given traiing data to create a trained Model that can be used for classifying examples.
virtual void WriteSpecificImplementationXML (ostream &o)
Public Member Functions inherited from MLL::Model
Model (FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
Use this when you are planning on creating a empty model without parameters.
Model (const KKStr &_name, const ModelParam &_param, FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
Construct a instance of 'Model' using the parameters specified in '_param'.
Model (const Model &_madel)
Copy Constructor.
virtual ~Model ()
Frees any memory allocated by, and owned by the Model.
bool AlreadyNormalized () const
const KKStr & BitReductionByFeature () const
int32 BitsToReduceBy () const
const CompressionStats & Compression_Stats () const
const FeatureEncoder2 & Encoder () const
void Load (const KKStr &_rootFileName, bool &_successful)
virtual KKStr ModelTypeStr () const
const KKStr & Name () const
void Name (const KKStr &_name)
ModelParamPtr Param () const
virtual void ProbabilitiesByClassDual (FeatureVectorPtr example, KKStr &classifier1Desc, KKStr &classifier2Desc, ClassProbListPtr &classifier1Results, ClassProbListPtr &classifier2Results)
Only applied to ModelDual classifier.
virtual void ReadXML (istream &i, bool &_successful)
Expects to read in the entire contents of a previously trainied model into this instance.
int32 ReductionPostExampleCount () const
int32 ReductionPreExampleCount () const
float ReductionRatio () const
double ReductionTime () const
const KKStr & RootFileName () const
void RootFileName (const KKStr &_rootFileName)
void Save (const KKStr &_rootFileName, bool &_successful)
virtual const FeatureNumList & SelectedFeatures () const
const KKU::DateTime & TimeSaved () const
double TrainingTime () const
void TrainingTimeEnd ()
Derived classes call this method to stop the clock for 'trainingTime'.
void TrainingTimeStart ()
Derived classes call this method to start the clock for 'trainingTime'.
double TrianingPrepTime () const
bool ValidModel () const
virtual void WriteXML (ostream &o)
Additional Inherited Members
Static Public Member Functions inherited from MLL::Model
static ModelPtr CreateAModel (ModelTypes _modelType, const KKStr &_name, const ModelParam &_param, FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
A factory method that will instantiate the appropriate class of training model based off '_modelType'.
static ModelPtr CreateFromStream (istream &i, FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
A factory method that will instantiate the appropriate class of training model based off the contents of the istream "i".
static ModelTypes ModelTypeFromStr (const KKStr &_modelingTypeStr)
static KKStr ModelTypeToStr (ModelTypes _modelingType)
Protected Member Functions inherited from MLL::Model
void AllocatePredictionVariables ()
void DeAllocateSpace ()
void Read (istream &i, bool &_successful)
void ReadSkipToSection (istream &i, KKStr sectName, bool &sectionFound)
void ReduceTrainExamples ()
Reduces the Training Images down to the size dictated by the 'examplesPerClass' parameter.
Protected Attributes inherited from MLL::Model
bool alreadyNormalized
volatile const bool & cancelFlag
MLClassConstListPtr classes
ClassIndexListPtr classesIndex
double * classProbs
CompressionStats compression_stats
double ** crossClassProbTable
Probabilities between Binary Classes From last Prediction.
int32 crossClassProbTableSize
FeatureEncoder2Ptr encoder
FileDescPtr fileDesc
RunLog & log
NormalizationParmsPtr normParms
int32 numOfClasses
Number of Classes defined in crossClassProbTable.
ModelParamPtr param
Will own this instance.
KKStr rootFileName
This is the root name to be used by all component objects; such as svm_model, mlClasses, and svmParam(including selected features).
FeatureVectorListPtr trainExamples
bool validModel
int32 * votes
bool weOwnTrainExamples
Indicates if we own the 'trainExamples'.
Detailed Description
                         ModelOldSVM                               *
                                                                   *
This is a specialization of 'Model'.  It is meant to Wrap the      *
original version of 'SvmModel'.  This class will allow us to use   *
the original implementation using version 2.39 of LibSVM.          *
                                                                   *
Definition at line 44 of file ModelOldSVM.h.
Member Typedef Documentation
typedef ModelOldSVM* MLL::ModelOldSVM::ModelOldSVMPtr
Definition at line 47 of file ModelOldSVM.h.
Constructor & Destructor Documentation
MLL::ModelOldSVM::ModelOldSVM (FileDescPtr _fileDesc, volatile const bool & _cancelFlag, RunLog & _log)
Referenced by Duplicate().
MLL::ModelOldSVM::ModelOldSVM (const KKStr & _name, const ModelParamOldSVM & _param, FileDescPtr _fileDesc, volatile const bool & _cancelFlag, RunLog & _log)
ModelOldSVM::ModelOldSVM (const ModelOldSVM & _madel)
Definition at line 82 of file ModelOldSVM.cpp.
ModelOldSVM::~ModelOldSVM () virtual
Frees any memory allocated by, and owned by the ModelOldSVM.
Definition at line 96 of file ModelOldSVM.cpp.
References KKU::endl(), KKU::RunLog::Level(), MLL::Model::log, and MLL::Model::rootFileName.
Member Function Documentation
const ClassAssignments & ModelOldSVM::Assignments () const
Definition at line 141 of file ModelOldSVM.cpp.
References MLL::SVMModel::Assignments().
KKStr ModelOldSVM::Description () const virtual
Return short user readable description of model.
Reimplemented from MLL::Model.
Definition at line 126 of file ModelOldSVM.cpp.
References MLL::SVMparam::MachineType(), MLL::MachineTypeToStr(), MLL::Model::Name(), MLL::SVMparam::SelectionMethod(), MLL::SelectionMethodToStr(), and MLL::SVMModel::SVMParameters().
ModelOldSVMPtr ModelOldSVM::Duplicate () const virtual
Implements MLL::Model.
Definition at line 120 of file ModelOldSVM.cpp.
References ModelOldSVM().
vector< ProbNamePair > ModelOldSVM::FindWorstSupportVectors (FeatureVectorPtr example, int32 numToFind, MLClassConstPtr c1, MLClassConstPtr c2)
For a given two class pair return the names of the 'numToFind' worst S/V's.
This method will iterate through all the S/V's removing them one at a time and recompute the decision boundary and probability. It will then return the S/V's that when removed improve the probability in 'c1's the most.
Parameters
[in] example Example that was classified incorrectly.
[in] numToFind The number of teh worst examples you are looking for.
[in] c1 Class that the 'example; parameter should have been classed as.
[in] c2 Class that it was classified as.
Definition at line 485 of file ModelOldSVM.cpp.
References MLL::SVMModel::FindWorstSupportVectors().
vector< ProbNamePair > ModelOldSVM::FindWorstSupportVectors2 (FeatureVectorPtr example, int32 numToFind, MLClassConstPtr c1, MLClassConstPtr c2)
For a given two class pair return the names of the 'numToFind' worst S/V's.
This method will iterate through all the S/V's removing them one at a time and retraining a new SVM and then comparing with the new prediction results.
Parameters
[in] example Example that was classified incorrectly.
[in] numToFind The number of teh worst examples you are looking for.
[in] c1 Class that the 'example; parameter should have been classed as.
[in] c2 Class that it was classified as.
Definition at line 506 of file ModelOldSVM.cpp.
References MLL::SVMModel::FindWorstSupportVectors2().
const FeatureNumList & ModelOldSVM::GetFeatureNums () const virtual
Reimplemented from MLL::Model.
Definition at line 158 of file ModelOldSVM.cpp.
References MLL::SVMModel::GetFeatureNums().
FeatureNumList ModelOldSVM::GetFeatureNums (MLClassConstPtr class1, MLClassConstPtr class2)
Definition at line 148 of file ModelOldSVM.cpp.
References MLL::SVMModel::GetFeatureNums().
KKU::int32 ModelOldSVM::MemoryConsumedEstimated () const virtual
Reimplemented from MLL::Model.
Definition at line 108 of file ModelOldSVM.cpp.
References MLL::ClassAssignments::MemoryConsumedEstimated(), MLL::SVMModel::MemoryConsumedEstimated(), and MLL::Model::MemoryConsumedEstimated().
virtual ModelTypes MLL::ModelOldSVM::ModelType () const inline virtual
Implements MLL::Model.
Definition at line 68 of file ModelOldSVM.h.
References MLL::Model::mtOldSVM.
bool ModelOldSVM::NormalizeNominalAttributes () const virtual
Return true, if nominal fields need to be normalized.
Reimplemented from MLL::Model.
Definition at line 519 of file ModelOldSVM.cpp.
References MLL::SVMModel::NormalizeNominalAttributes().
int32 ModelOldSVM::NumOfSupportVectors () const
Definition at line 165 of file ModelOldSVM.cpp.
References MLL::SVMModel::NumOfSupportVectors().
Referenced by MLL::TrainingProcess2::NumOfSupportVectors().
ModelParamOldSVMPtr ModelOldSVM::Param () const
Definition at line 180 of file ModelOldSVM.cpp.
References KKU::endl(), KKU::RunLog::Level(), MLL::Model::log, MLL::ModelParam::ModelParamType(), MLL::ModelParam::mptOldSVM, and MLL::Model::param.
Referenced by TrainModel().
MLClassConstPtr ModelOldSVM::Predict (FeatureVectorPtr image) virtual
Implements MLL::Model.
Definition at line 326 of file ModelOldSVM.cpp.
References MLL::SVMModel::Predict(), and PrepExampleForPrediction().
virtual void MLL::ModelOldSVM::Predict (FeatureVectorPtr example, MLClassConstPtr knownClass, MLClassConstPtr & predClass1, MLClassConstPtr & predClass2, int32 & predClass1Votes, int32 & predClass2Votes, double & probOfKnownClass, double & predClass1Prob, double & predClass2Prob, double & compact, int32 & numOfWinners, bool & knownClassOneOfTheWinners, double & breakTie) virtual
Implements MLL::Model.
FeatureVectorPtr ModelOldSVM::PrepExampleForPrediction (FeatureVectorPtr fv, bool & newExampleCreated) virtual
ModelOldSVM Specific 'PrepExampleForPrediction' will only normalize data.
Parameters
[in] fv Feature vector of example that needs to be prepared.
[out] newExampleCreated Indicates if either Feature Encoding and/or Normalization needed to be done. If neither then the original instance is returned. If Yes then a new instance which the caller will have to be delete will be returned.
Reimplemented from MLL::Model.
Definition at line 614 of file ModelOldSVM.cpp.
References MLL::Model::alreadyNormalized, MLL::Model::normParms, and MLL::NormalizationParms::ToNormalized().
Referenced by Predict(), and ProbabilitiesByClass().
ClassProbListPtr ModelOldSVM::ProbabilitiesByClass (FeatureVectorPtr example) virtual
Implements MLL::Model.
Definition at line 344 of file ModelOldSVM.cpp.
References MLL::Model::classes, MLL::Model::classProbs, KKU::endl(), KKU::RunLog::Level(), MLL::Model::log, MLL::Model::numOfClasses, PrepExampleForPrediction(), MLL::SVMModel::ProbabilitiesByClass(), MLL::SelectByVoting, MLL::SVMparam::SelectionMethod(), MLL::ClassProbList::SortByProbability(), MLL::ClassProbList::SortByVotes(), MLL::SVMModel::SVMParameters(), and MLL::Model::votes.
virtual void MLL::ModelOldSVM::ProbabilitiesByClass (FeatureVectorPtr example, const MLClassConstList & _mlClasses, int32 * _votes, double * _probabilities) virtual
Implements MLL::Model.
void ModelOldSVM::ProbabilitiesByClass (FeatureVectorPtr _example, const MLClassConstList & _mlClasses, double * _probabilities) virtual
Will get the probabilities assigned to each class.
Parameters
[in] example unknown example that we want to get predicted probabilities for.
[in] _mlClasses List classes that caller is aware of. This should be the same list that was used when consttructing this ModelOldSVM object. The list must be the same but not nessasarily in the same order as when ModelOldSVM was 1st constructed.
[out] _probabilities An array that must be as big as the number of classes in _mlClasses. The probability of class in _mlClasses[x] will be returned in _probabilities[x].
Implements MLL::Model.
Definition at line 395 of file ModelOldSVM.cpp.
References PrepExampleForPrediction(), MLL::SVMModel::ProbabilitiesByClass(), and MLL::Model::votes.
void ModelOldSVM::ReadSpecificImplementationXML (istream & i, bool & _successful) virtual
Implements MLL::Model.
Definition at line 224 of file ModelOldSVM.cpp.
References MLL::Model::cancelFlag, KKU::endl(), KKU::KKStr::EqualIgnoreCase(), KKU::KKStr::ExtractToken2(), MLL::Model::fileDesc, KKU::KKStr::Len(), KKU::RunLog::Level(), MLL::Model::log, and MLL::Model::validModel.
void ModelOldSVM::RetrieveCrossProbTable (MLClassConstList & classes, double ** crossProbTable) virtual
Reimplemented from MLL::Model.
Definition at line 527 of file ModelOldSVM.cpp.
References MLL::SVMModel::RetrieveCrossProbTable().
SVM_SelectionMethod ModelOldSVM::SelectionMethod () const
Definition at line 201 of file ModelOldSVM.cpp.
References MLL::SVMModel::SelectionMethod().
Referenced by MLL::Classifier2::SelectionMethod().
vector< KKStr > ModelOldSVM::SupportVectorNames () const
Definition at line 464 of file ModelOldSVM.cpp.
References MLL::SVMModel::SupportVectorNames().
vector< KKStr > ModelOldSVM::SupportVectorNames (MLClassConstPtr c1, MLClassConstPtr c2) const
Definition at line 451 of file ModelOldSVM.cpp.
References MLL::SVMModel::SupportVectorNames().
void ModelOldSVM::SupportVectorStatistics (int32 & numSVs, int32 & totalNumSVs)
Definition at line 172 of file ModelOldSVM.cpp.
References MLL::SVMModel::SupportVectorStatistics().
Referenced by MLL::TrainingProcess2::SupportVectorStatistics().
SVMModelPtr MLL::ModelOldSVM::SvmModel () const inline
Definition at line 97 of file ModelOldSVM.h.
Referenced by MLL::Classifier2::Classifier2(), and MLL::TrainingProcess2::Model3().
void ModelOldSVM::TrainModel (FeatureVectorListPtr _trainExamples, bool _alreadyNormalized, bool _takeOwnership) virtual
Use given traiing data to create a trained Model that can be used for classifying examples.
Parameters
[in] _trainExamples The example data we will be building the model from.
[in] _alreadyNormalized Specifies weather the training data has already been normalized.
[in] _takeOwnership If true this instance will take ownership of '_trainExamples' and delete it when done with it.
Parameters
_takeOwnership Model will take ownership of these examples
Reimplemented from MLL::Model.
Definition at line 543 of file ModelOldSVM.cpp.
References MLL::Model::cancelFlag, MLL::Model::classes, MLL::SVMModel::Compression_Stats(), MLL::Model::compression_stats, KKU::endl(), MLL::FeatureVectorList::ExtractMLClassConstList(), MLL::Model::fileDesc, KKU::RunLog::Level(), MLL::Model::log, MLL::Model::numOfClasses, Param(), MLL::Model::rootFileName, MLL::MLClassConstList::SortByName(), MLL::ModelParamOldSVM::SvmParameters(), MLL::Model::trainExamples, MLL::Model::TrainingTimeEnd(), MLL::Model::TrainingTimeStart(), MLL::Model::TrainModel(), MLL::Model::validModel, and MLL::Model::weOwnTrainExamples.
void ModelOldSVM::WriteSpecificImplementationXML (ostream & o) virtual
Implements MLL::Model.
Definition at line 209 of file ModelOldSVM.cpp.
References KKU::endl(), KKU::RunLog::Level(), MLL::Model::log, MLL::Model::rootFileName, and MLL::SVMModel::Write().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ModelOldSVM.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/ModelOldSVM.cpp