Pices: PicesCommander.ClassTotals Class Reference
PicesCommander.ClassTotals Class Reference
Public Member Functions
ClassTotals (String _name, int _bucketCount, int _bucketSize)
void AddIn (ClassTotals classTotals)
int BucketCount (int idx)
void CleaUpMemory ()
void Increment (int size)
void PrintCSVLine (System.IO.StreamWriter o)
void PrintFormatedLine (System.IO.StreamWriter o)
void PrintTabDelLine (System.IO.StreamWriter o)
Properties
String Name [get]
String NameUpper [get]
Detailed Description
Definition at line 15 of file SizeDistribution.cs.
Constructor & Destructor Documentation
PicesCommander.ClassTotals.ClassTotals (String _name, int _bucketCount, int _bucketSize) inline
Definition at line 25 of file SizeDistribution.cs.
References x.
Member Function Documentation
void PicesCommander.ClassTotals.AddIn (ClassTotals classTotals) inline
Definition at line 66 of file SizeDistribution.cs.
Referenced by PicesCommander.SizeDistribution.Add(), PicesCommander.SizeDistribution.PrintCSVDistributionMatrix(), PicesCommander.SizeDistribution.PrintFormatedDistributionMatrix(), and PicesCommander.SizeDistribution.PrintTabDelDistributionMatrix().
int PicesCommander.ClassTotals.BucketCount (int idx) inline
Definition at line 78 of file SizeDistribution.cs.
Referenced by PicesCommander.SizeDistribution.PrintByClassCollumns().
void PicesCommander.ClassTotals.CleaUpMemory () inline
Definition at line 42 of file SizeDistribution.cs.
Referenced by PicesCommander.ClassTotalsList.CleanUpMemory().
void PicesCommander.ClassTotals.Increment (int size) inline
Definition at line 51 of file SizeDistribution.cs.
Referenced by PicesCommander.SizeDistribution.Increment().
void PicesCommander.ClassTotals.PrintCSVLine (System.IO.StreamWriter o) inline
Definition at line 106 of file SizeDistribution.cs.
Referenced by PicesCommander.SizeDistribution.PrintCSVDistributionMatrix().
void PicesCommander.ClassTotals.PrintFormatedLine (System.IO.StreamWriter o) inline
Definition at line 86 of file SizeDistribution.cs.
Referenced by PicesCommander.SizeDistribution.PrintFormatedDistributionMatrix().
void PicesCommander.ClassTotals.PrintTabDelLine (System.IO.StreamWriter o) inline
Definition at line 122 of file SizeDistribution.cs.
Referenced by PicesCommander.SizeDistribution.PrintTabDelDistributionMatrix().
Property Documentation
String PicesCommander.ClassTotals.Name get
Definition at line 47 of file SizeDistribution.cs.
Referenced by PicesCommander.SizeDistribution.Add().
String PicesCommander.ClassTotals.NameUpper get
Definition at line 49 of file SizeDistribution.cs.
Referenced by PicesCommander.ClassTotalsList.LookUp().
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/PicesCommander/SizeDistribution.cs