Pices: MLL::Model Class Reference
MLL::Model Class Reference abstract
Base class to all Learning Algorithms.
#include <Model.h>
Public Types
typedef Model * ModelPtr
enum ModelTypes {
mtNULL = 0, mtOldSVM = 1, mtSvmBase = 2, mtKNN = 3,
mtUsfCasCor = 4, mtDual = 5
}
Public Member Functions
Model (FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
Use this when you are planning on creating a empty model without parameters.
Model (const KKStr &_name, const ModelParam &_param, FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
Construct a instance of 'Model' using the parameters specified in '_param'.
Model (const Model &_madel)
Copy Constructor.
virtual ~Model ()
Frees any memory allocated by, and owned by the Model.
bool AlreadyNormalized () const
const KKStr & BitReductionByFeature () const
int32 BitsToReduceBy () const
const CompressionStats & Compression_Stats () const
virtual KKStr Description () const
Return short user readable description of model.
virtual ModelPtr Duplicate () const =0
const FeatureEncoder2 & Encoder () const
virtual const FeatureNumList & GetFeatureNums () const
void Load (const KKStr &_rootFileName, bool &_successful)
virtual KKU::int32 MemoryConsumedEstimated () const
virtual ModelTypes ModelType () const =0
virtual KKStr ModelTypeStr () const
const KKStr & Name () const
void Name (const KKStr &_name)
virtual bool NormalizeNominalAttributes () const
Return true, if nominal fields need to be normalized.
ModelParamPtr Param () const
virtual MLClassConstPtr Predict (FeatureVectorPtr image)=0
virtual void Predict (FeatureVectorPtr example, MLClassConstPtr knownClass, MLClassConstPtr &predClass1, MLClassConstPtr &predClass2, int32 &predClass1Votes, int32 &predClass2Votes, double &probOfKnownClass, double &predClass1Prob, double &predClass2Prob, double &compact, int32 &numOfWinners, bool &knownClassOneOfTheWinners, double &breakTie)=0
virtual FeatureVectorPtr PrepExampleForPrediction (FeatureVectorPtr fv, bool &newExampleCreated)
Every prediction method in every class that is inherited from this class should call this method before performing there prediction.
virtual ClassProbListPtr ProbabilitiesByClass (FeatureVectorPtr example)=0
virtual void ProbabilitiesByClass (FeatureVectorPtr example, const MLClassConstList &_mlClasses, int32 *_votes, double *_probabilities)=0
virtual void ProbabilitiesByClass (FeatureVectorPtr _example, const MLClassConstList &_mlClasses, double *_probabilities)=0
Derives predicted probabilities by class.
virtual void ProbabilitiesByClassDual (FeatureVectorPtr example, KKStr &classifier1Desc, KKStr &classifier2Desc, ClassProbListPtr &classifier1Results, ClassProbListPtr &classifier2Results)
Only applied to ModelDual classifier.
virtual void ReadSpecificImplementationXML (istream &i, bool &_successful)=0
virtual void ReadXML (istream &i, bool &_successful)
Expects to read in the entire contents of a previously trainied model into this instance.
int32 ReductionPostExampleCount () const
int32 ReductionPreExampleCount () const
float ReductionRatio () const
double ReductionTime () const
virtual void RetrieveCrossProbTable (MLClassConstList &classes, double **crossProbTable)
const KKStr & RootFileName () const
void RootFileName (const KKStr &_rootFileName)
void Save (const KKStr &_rootFileName, bool &_successful)
virtual const FeatureNumList & SelectedFeatures () const
const KKU::DateTime & TimeSaved () const
double TrainingTime () const
void TrainingTimeEnd ()
Derived classes call this method to stop the clock for 'trainingTime'.
void TrainingTimeStart ()
Derived classes call this method to start the clock for 'trainingTime'.
virtual void TrainModel (FeatureVectorListPtr _trainExamples, bool _alreadyNormalized, bool _takeOwnership)
Performs operations such as BitReduction, FeatureEncoding, and Normailization.
double TrianingPrepTime () const
bool ValidModel () const
virtual void WriteSpecificImplementationXML (ostream &o)=0
virtual void WriteXML (ostream &o)
Static Public Member Functions
static ModelPtr CreateAModel (ModelTypes _modelType, const KKStr &_name, const ModelParam &_param, FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
A factory method that will instantiate the appropriate class of training model based off '_modelType'.
static ModelPtr CreateFromStream (istream &i, FileDescPtr _fileDesc, volatile const bool &_cancelFlag, RunLog &_log)
A factory method that will instantiate the appropriate class of training model based off the contents of the istream "i".
static ModelTypes ModelTypeFromStr (const KKStr &_modelingTypeStr)
static KKStr ModelTypeToStr (ModelTypes _modelingType)
Protected Member Functions
void AllocatePredictionVariables ()
void DeAllocateSpace ()
void Read (istream &i, bool &_successful)
void ReadSkipToSection (istream &i, KKStr sectName, bool &sectionFound)
void ReduceTrainExamples ()
Reduces the Training Images down to the size dictated by the 'examplesPerClass' parameter.
Protected Attributes
bool alreadyNormalized
volatile const bool & cancelFlag
MLClassConstListPtr classes
ClassIndexListPtr classesIndex
double * classProbs
CompressionStats compression_stats
double ** crossClassProbTable
Probabilities between Binary Classes From last Prediction.
int32 crossClassProbTableSize
FeatureEncoder2Ptr encoder
FileDescPtr fileDesc
RunLog & log
NormalizationParmsPtr normParms
int32 numOfClasses
Number of Classes defined in crossClassProbTable.
ModelParamPtr param
Will own this instance.
KKStr rootFileName
This is the root name to be used by all component objects; such as svm_model, mlClasses, and svmParam(including selected features).
FeatureVectorListPtr trainExamples
bool validModel
int32 * votes
bool weOwnTrainExamples
Indicates if we own the 'trainExamples'.
Detailed Description
Base class to all Learning Algorithms.
Author
Kurt Kramer
Base class to be used by all Learning Algorithm Models. The idea is that all learning algorithms all follow the same basic flow. The two obvious functions that they all support are Training from supplied labeled examples(List of FeatureVector objects), Prediction of an unlabeled example.
Definition at line 77 of file Model.h.
Member Typedef Documentation
typedef Model* MLL::Model::ModelPtr
Definition at line 80 of file Model.h.
Member Enumeration Documentation
enum MLL::Model::ModelTypes
Enumerator
mtNULL
mtOldSVM
mtSvmBase
mtKNN
mtUsfCasCor
mtDual
Definition at line 82 of file Model.h.
Constructor & Destructor Documentation
MLL::Model::Model (FileDescPtr _fileDesc, volatile const bool & _cancelFlag, RunLog & _log)
Use this when you are planning on creating a empty model without parameters.
Referenced by MemoryConsumedEstimated().
MLL::Model::Model (const KKStr & _name, const ModelParam & _param, FileDescPtr _fileDesc, volatile const bool & _cancelFlag, RunLog & _log)
Construct a instance of 'Model' using the parameters specified in '_param'.
Parameters
[in] _param Parameters for learning algorithm; we will create a duplicate copy.
[in] _fileDesc Description of the dataset that will be used to train the classifier and examples that will be classified.
[in] _cancelFlag Will monitor; if at any point it turns true this instance is to terminate and return to caller.
[in,out] _log Logging file.
Model::Model (const Model & _madel)
Copy Constructor.
Definition at line 47 of file Model.cpp.
References AllocatePredictionVariables(), classes, classesIndex, MLL::ModelParam::Duplicate(), encoder, numOfClasses, and param.
Model::~Model () virtual
Frees any memory allocated by, and owned by the Model.
Definition at line 177 of file Model.cpp.
References classes, classesIndex, DeAllocateSpace(), encoder, normParms, param, trainExamples, and weOwnTrainExamples.
Member Function Documentation
void Model::AllocatePredictionVariables () protected
Definition at line 446 of file Model.cpp.
References classes, classProbs, crossClassProbTable, crossClassProbTableSize, DeAllocateSpace(), KKU::endl(), KKU::RunLog::Level(), log, numOfClasses, validModel, votes, and x.
Referenced by Model(), ReadXML(), and TrainModel().
bool MLL::Model::AlreadyNormalized () const inline
Definition at line 158 of file Model.h.
References alreadyNormalized.
const KKStr& MLL::Model::BitReductionByFeature () const inline
Definition at line 163 of file Model.h.
References MLL::CompressionStats::bitReductionByFeature, and compression_stats.
Referenced by MLL::TrainingProcess2::BitReductionByFeature().
int32 Model::BitsToReduceBy () const
Definition at line 509 of file Model.cpp.
References MLL::ModelParam::BitsToReduceBy(), and param.
const CompressionStats& MLL::Model::Compression_Stats () const inline
Definition at line 162 of file Model.h.
References compression_stats.
Referenced by MLL::TrainingProcess2::CompStats().
ModelPtr Model::CreateAModel (ModelTypes _modelType, const KKStr & _name, const ModelParam & _param, FileDescPtr _fileDesc, volatile const bool & _cancelFlag, RunLog & _log) static
A factory method that will instantiate the appropriate class of training model based off '_modelType'.
This method is used to construct a model that is going to be built from training data.
Parameters
[in] _modelType Type of model to be created; ex: mtOldSVM, mtSvmBase, or mtKNN.
[in] _param Parameters used to drive the creating of the model.
[in] _fileDesc Description of the dataset that will be used to train the classifier and examples that will be classified.
[in] _cancelFlag Will monitor; if at any point it turns true this instance is to terminate and return to caller.
[in,out] _log Logging file.
Parameters
_param Will make a duplicate copy of
Definition at line 389 of file Model.cpp.
References mtDual, mtKNN, mtOldSVM, mtSvmBase, and mtUsfCasCor.
Referenced by MLL::TrainingProcess2::CreateModelsFromTrainingData().
ModelPtr Model::CreateFromStream (istream & i, FileDescPtr _fileDesc, volatile const bool & _cancelFlag, RunLog & _log) static
A factory method that will instantiate the appropriate class of training model based off the contents of the istream "i".
This method is used to construct a model that has already been built and saved to disk.
Parameters
[in] i Input stream where previously built model has been saved.
[in] _param Parameter used to drive the creating of the model.
[in] _fileDesc Description of the dataset that will be used to train the classifier and examples that will be classified.
[in] _cancelFlag Will monitor; if at any point it turns true this instance is to terminate and return to caller.
[in,out] _log Logging file.
Definition at line 224 of file Model.cpp.
References KKU::endl(), KKU::KKStr::EqualIgnoreCase(), KKU::KKStr::ExtractToken2(), KKU::RunLog::Level(), ModelTypeFromStr(), mtDual, mtKNN, mtNULL, mtOldSVM, mtSvmBase, mtUsfCasCor, ReadXML(), and KKU::KKStrException::ToString().
Referenced by MLL::TrainingProcess2::Read().
void Model::DeAllocateSpace () protected
Definition at line 486 of file Model.cpp.
References classProbs, crossClassProbTable, numOfClasses, votes, and x.
Referenced by AllocatePredictionVariables(), and ~Model().
KKStr Model::Description () const virtual
Return short user readable description of model.
Reimplemented in MLL::ModelDual, MLL::ModelOldSVM, and MLL::ModelSvmBase.
Definition at line 217 of file Model.cpp.
References ModelTypeStr(), and Name().
Referenced by MLL::TrainingProcess2::ModelDescription(), and ProbabilitiesByClassDual().
virtual ModelPtr MLL::Model::Duplicate () const pure virtual
Implemented in MLL::ModelDual, MLL::ModelOldSVM, MLL::ModelUsfCasCor, MLL::ModelSvmBase, and MLL::ModelKnn.
const FeatureEncoder2 & Model::Encoder () const
Definition at line 518 of file Model.cpp.
References encoder.
const FeatureNumList & Model::GetFeatureNums () const virtual
Reimplemented in MLL::ModelOldSVM.
Definition at line 527 of file Model.cpp.
References param, and MLL::ModelParam::SelectedFeatures().
void Model::Load (const KKStr & _rootFileName, bool & _successful)
Definition at line 575 of file Model.cpp.
References KKU::endl(), KKU::RunLog::Level(), log, ReadXML(), rootFileName, and KKU::KKStr::Str().
KKU::int32 Model::MemoryConsumedEstimated () const virtual
Reimplemented in MLL::ModelDual, MLL::ModelOldSVM, MLL::ModelSvmBase, and MLL::ModelUsfCasCor.
Definition at line 197 of file Model.cpp.
References classes, classesIndex, classProbs, crossClassProbTable, encoder, MLL::FeatureEncoder2::MemoryConsumedEstimated(), MLL::ModelParam::MemoryConsumedEstimated(), MLL::NormalizationParms::MemoryConsumedEstimated(), MLL::MLClassConstList::MemoryConsumedEstimated(), KKU::KKStr::MemoryConsumedEstimated(), MLL::FeatureVectorList::MemoryConsumedEstimated(), MLL::ClassIndexList::MemoryConsumedEstimated(), Model(), normParms, numOfClasses, param, rootFileName, trainExamples, votes, and weOwnTrainExamples.
Referenced by MLL::ModelUsfCasCor::MemoryConsumedEstimated(), MLL::ModelSvmBase::MemoryConsumedEstimated(), MLL::ModelOldSVM::MemoryConsumedEstimated(), MLL::ModelDual::MemoryConsumedEstimated(), and MLL::TrainingProcess2::MemoryConsumedEstimated().
virtual ModelTypes MLL::Model::ModelType () const pure virtual
Implemented in MLL::ModelDual, MLL::ModelOldSVM, MLL::ModelSvmBase, MLL::ModelUsfCasCor, and MLL::ModelKnn.
Referenced by MLL::Classifier2::Classifier2(), MLL::TrainingProcess2::ModelType(), ModelTypeStr(), MLL::TrainingProcess2::OldSVMModel(), MLL::TrainingProcess2::TrainingProcessLeft(), and MLL::TrainingProcess2::TrainingProcessRight().
Model::ModelTypes Model::ModelTypeFromStr (const KKStr & _modelingTypeStr) static
Definition at line 365 of file Model.cpp.
References KKU::KKStr::EqualIgnoreCase(), mtDual, mtKNN, mtNULL, mtOldSVM, mtSvmBase, and mtUsfCasCor.
Referenced by CreateFromStream(), and MLL::TrainingConfiguration2::ModelTypeFromStr().
virtual KKStr MLL::Model::ModelTypeStr () const inline virtual
Definition at line 182 of file Model.h.
References ModelType(), and ModelTypeToStr().
Referenced by Description(), MLL::TrainingProcess2::ModelTypeStr(), and WriteXML().
KKStr Model::ModelTypeToStr (ModelTypes _modelingType) static
Definition at line 338 of file Model.cpp.
References mtDual, mtKNN, mtNULL, mtOldSVM, mtSvmBase, and mtUsfCasCor.
Referenced by MLL::TrainingConfiguration2::ModelTypeStr(), ModelTypeStr(), and MLL::TrainingConfiguration2::ModelTypeToStr().
const KKStr& MLL::Model::Name () const inline
Definition at line 184 of file Model.h.
Referenced by MLL::ModelSvmBase::Description(), MLL::ModelOldSVM::Description(), MLL::ModelDual::Description(), Description(), ReadXML(), MLL::ModelUsfCasCor::TrainModel(), TrainModel(), and WriteXML().
void MLL::Model::Name (const KKStr & _name) inline
Definition at line 185 of file Model.h.
bool Model::NormalizeNominalAttributes () const virtual
Return true, if nominal fields need to be normalized.
Reimplemented in MLL::ModelOldSVM.
Definition at line 535 of file Model.cpp.
References MLL::ModelParam::EncodingMethod(), MLL::ModelParam::NoEncoding, and param.
ModelParamPtr MLL::Model::Param () const inline
Definition at line 190 of file Model.h.
References param.
Referenced by MLL::TrainingProcess2::Parameters().
virtual MLClassConstPtr MLL::Model::Predict (FeatureVectorPtr image) pure virtual
Implemented in MLL::ModelDual, MLL::ModelOldSVM, MLL::ModelSvmBase, MLL::ModelUsfCasCor, and MLL::ModelKnn.
virtual void MLL::Model::Predict (FeatureVectorPtr example, MLClassConstPtr knownClass, MLClassConstPtr & predClass1, MLClassConstPtr & predClass2, int32 & predClass1Votes, int32 & predClass2Votes, double & probOfKnownClass, double & predClass1Prob, double & predClass2Prob, double & compact, int32 & numOfWinners, bool & knownClassOneOfTheWinners, double & breakTie) pure virtual
Implemented in MLL::ModelDual, MLL::ModelOldSVM, MLL::ModelSvmBase, and MLL::ModelKnn.
FeatureVectorPtr Model::PrepExampleForPrediction (FeatureVectorPtr fv, bool & newExampleCreated) virtual
Every prediction method in every class that is inherited from this class should call this method before performing there prediction.
Such things as Normalization and Feature Encoding.
Parameters
[in] fv Feature vector of example that needs to be prepared.
[out] newExampleCreated Indicates if either Feature Encoding and/or Normalization needed to be done. If neither then the original instance is returned. If Yes then a new instance which the caller will have to be delete will be returned.
Reimplemented in MLL::ModelOldSVM.
Definition at line 977 of file Model.cpp.
References alreadyNormalized, MLL::FeatureEncoder2::EncodeAExample(), encoder, normParms, and MLL::NormalizationParms::ToNormalized().
Referenced by MLL::ModelUsfCasCor::Predict(), MLL::ModelSvmBase::Predict(), MLL::ModelDual::Predict(), MLL::ModelKnn::ProbabilitiesByClass(), MLL::ModelUsfCasCor::ProbabilitiesByClass(), MLL::ModelSvmBase::ProbabilitiesByClass(), MLL::ModelDual::ProbabilitiesByClass(), and MLL::ModelDual::ProbabilitiesByClassDual().
virtual ClassProbListPtr MLL::Model::ProbabilitiesByClass (FeatureVectorPtr example) pure virtual
Implemented in MLL::ModelDual, MLL::ModelOldSVM, MLL::ModelSvmBase, MLL::ModelUsfCasCor, and MLL::ModelKnn.
Referenced by MLL::Classifier2::ProbabilitiesByClass(), and ProbabilitiesByClassDual().
virtual void MLL::Model::ProbabilitiesByClass (FeatureVectorPtr example, const MLClassConstList & _mlClasses, int32 * _votes, double * _probabilities) pure virtual
Implemented in MLL::ModelDual, MLL::ModelOldSVM, MLL::ModelSvmBase, and MLL::ModelKnn.
virtual void MLL::Model::ProbabilitiesByClass (FeatureVectorPtr _example, const MLClassConstList & _mlClasses, double * _probabilities) pure virtual
Derives predicted probabilities by class.
Will get the probabilities assigned to each class by the classifier. The '_mlClasses' parameter dictates the order of the classes. That is the probabilities for any given index in '_probabilities' will be for the class Specified in the same index in '_mlClasses'.
Parameters
[in] _example FeatureVector object to calculate predicted probabilities for.
[in] _mlClasses List of image classes that caller is aware of. This should be the same list that was used when constructing this Model object. The list must be the same but not necessarily in the same order as when Model was 1st constructed. The ordering of this list will dictate the order that '_probabilities' will be populated.
[out] _probabilities An array that must be as big as the number of classes in '_mlClasses'. The probability of class in '_mlClasses[x]' will be returned in probabilities[x].
Implemented in MLL::ModelDual, MLL::ModelOldSVM, MLL::ModelSvmBase, MLL::ModelUsfCasCor, and MLL::ModelKnn.
void Model::ProbabilitiesByClassDual (FeatureVectorPtr example, KKStr & classifier1Desc, KKStr & classifier2Desc, ClassProbListPtr & classifier1Results, ClassProbListPtr & classifier2Results) virtual
Only applied to ModelDual classifier.
Reimplemented in MLL::ModelDual.
Definition at line 1195 of file Model.cpp.
References Description(), and ProbabilitiesByClass().
Referenced by MLL::Classifier2::ProbabilitiesByClassDual().
void MLL::Model::Read (istream & i, bool & _successful) protected
void Model::ReadSkipToSection (istream & i, KKStr sectName, bool & sectionFound) protected
Definition at line 816 of file Model.cpp.
References KKU::endl(), KKU::KKStr::ExtractQuotedStr(), KKU::RunLog::Level(), log, and KKU::KKStr::Upper().
virtual void MLL::Model::ReadSpecificImplementationXML (istream & i, bool & _successful) pure virtual
Implemented in MLL::ModelOldSVM, MLL::ModelDual, MLL::ModelSvmBase, MLL::ModelUsfCasCor, and MLL::ModelKnn.
Referenced by ReadXML().
void Model::ReadXML (istream & i, bool & _successful) virtual
Expects to read in the entire contents of a previously trainied model into this instance.
One of the first lines to be read will contain the specific type of model to be read. To update the fields taht are particular to the specioalized class the method 'ReadSpecificImplementationXML' will be called.
Definition at line 670 of file Model.cpp.
References AllocatePredictionVariables(), alreadyNormalized, MLL::MLClassConstList::BuildListFromDelimtedStr(), classes, classesIndex, compression_stats, MLL::ModelParam::CreateModelParam(), KKU::KKStr::Empty(), KKU::endl(), KKU::KKStr::EqualIgnoreCase(), KKU::KKStr::ExtractQuotedStr(), KKU::KKStr::ExtractToken2(), KKU::KKStr::ExtractTokenBool(), KKU::KKStr::ExtractTokenDouble(), fileDesc, KKU::RunLog::Level(), log, Name(), normParms, numOfClasses, param, MLL::ClassIndexList::ParseClassIndexList(), ReadSpecificImplementationXML(), MLL::CompressionStats::UpdateFromTabDelStr(), KKU::KKStr::Upper(), validModel, and MLL::ModelParam::ValidParam().
Referenced by CreateFromStream(), Load(), MLL::ModelKnn::ReadSpecificImplementationXML(), MLL::ModelUsfCasCor::ReadSpecificImplementationXML(), MLL::ModelSvmBase::ReadSpecificImplementationXML(), and MLL::ModelDual::ReadSpecificImplementationXML().
void Model::ReduceTrainExamples () protected
Reduces the Training Images down to the size dictated by the 'examplesPerClass' parameter.
Definition at line 1016 of file Model.cpp.
References MLL::FeatureVectorList::AddQueue(), classes, KKU::endl(), MLL::ModelParam::ExamplesPerClass(), fileDesc, MLL::FeatureVectorList::GetClassStatistics(), int32_max, KKU::RunLog::Level(), log, param, MLL::FeatureVectorList::PushOnBack(), trainExamples, validModel, and weOwnTrainExamples.
Referenced by TrainModel().
int32 MLL::Model::ReductionPostExampleCount () const inline
Definition at line 166 of file Model.h.
References compression_stats, and MLL::CompressionStats::num_images_after.
Referenced by MLL::TrainingProcess2::ReductionPostExampleCount().
int32 MLL::Model::ReductionPreExampleCount () const inline
Definition at line 165 of file Model.h.
References compression_stats, and MLL::CompressionStats::num_images_before.
Referenced by MLL::TrainingProcess2::ReductionPreExampleCount().
float MLL::Model::ReductionRatio () const inline
Definition at line 167 of file Model.h.
References MLL::CompressionStats::compression_ratio, and compression_stats.
Referenced by MLL::TrainingProcess2::ReductionRatio().
double MLL::Model::ReductionTime () const inline
Definition at line 164 of file Model.h.
References compression_stats, and MLL::CompressionStats::elapsed_cpu_time.
Referenced by MLL::TrainingProcess2::ReductionTime().
void Model::RetrieveCrossProbTable (MLClassConstList & classes, double ** crossProbTable) virtual
Reimplemented in MLL::ModelDual, MLL::ModelOldSVM, and MLL::ModelSvmBase.
Definition at line 1122 of file Model.cpp.
References classesIndex, crossClassProbTableSize, KKU::endl(), MLL::ClassIndexList::GetClassIndex(), KKU::RunLog::Level(), log, and x.
Referenced by MLL::Classifier2::RetrieveCrossProbTable().
const KKStr& MLL::Model::RootFileName () const inline
Definition at line 195 of file Model.h.
References rootFileName.
Referenced by MLL::TrainingProcess2::SaveResults().
void MLL::Model::RootFileName (const KKStr & _rootFileName) inline
Definition at line 208 of file Model.h.
References rootFileName.
void Model::Save (const KKStr & _rootFileName, bool & _successful)
Definition at line 599 of file Model.cpp.
References KKU::endl(), KKU::RunLog::Level(), log, rootFileName, KKU::KKStr::Str(), and WriteXML().
const FeatureNumList & Model::SelectedFeatures () const virtual
Definition at line 548 of file Model.cpp.
References param, and MLL::ModelParam::SelectedFeatures().
Referenced by MLL::ModelUsfCasCor::TrainModel().
const KKU::DateTime& MLL::Model::TimeSaved () const inline
Definition at line 197 of file Model.h.
double MLL::Model::TrainingTime () const inline
Definition at line 199 of file Model.h.
Referenced by MLL::TrainingProcess2::TrainingTime().
void Model::TrainingTimeEnd ()
Derived classes call this method to stop the clock for 'trainingTime'.
Definition at line 564 of file Model.cpp.
References KKU::osGetSystemTimeUsed().
Referenced by MLL::ModelUsfCasCor::TrainModel(), MLL::ModelSvmBase::TrainModel(), MLL::ModelOldSVM::TrainModel(), and MLL::ModelDual::TrainModel().
void Model::TrainingTimeStart ()
Derived classes call this method to start the clock for 'trainingTime'.
Definition at line 557 of file Model.cpp.
References KKU::osGetSystemTimeUsed().
Referenced by MLL::ModelUsfCasCor::TrainModel(), MLL::ModelSvmBase::TrainModel(), MLL::ModelOldSVM::TrainModel(), and MLL::ModelDual::TrainModel().
void Model::TrainModel (FeatureVectorListPtr _trainExamples, bool _alreadyNormalized, bool _takeOwnership) virtual
Performs operations such as BitReduction, FeatureEncoding, and Normailization.
The actual training of models occurs in the specific implementation of 'Model'.
Parameters
_takeOwnership Model will take ownership of these examples
Reimplemented in MLL::ModelDual, MLL::ModelOldSVM, MLL::ModelSvmBase, MLL::ModelUsfCasCor, and MLL::ModelKnn.
Definition at line 855 of file Model.cpp.
References AllocatePredictionVariables(), alreadyNormalized, MLL::ModelParam::BRnoCompression, MLL::ModelParam::BRNull, classes, classesIndex, MLL::FeatureEncoder2::CompressExamples(), compression_stats, MLL::ModelParam::CompressionMethod(), MLL::FeatureEncoder2::EncodeAllExamples(), encoder, MLL::ModelParam::Encoding_NULL, MLL::ModelParam::EncodingMethod(), KKU::endl(), MLL::ModelParam::ExamplesPerClass(), MLL::FeatureVectorList::ExtractMLClassConstList(), fileDesc, int32_max, KKU::RunLog::Level(), log, Name(), MLL::ModelParam::NoEncoding, MLL::NormalizationParms::NormalizeImages(), normParms, KKU::osGetSystemTimeUsed(), param, ReduceTrainExamples(), MLL::MLClassConstList::SortByName(), trainExamples, and weOwnTrainExamples.
Referenced by MLL::TrainingProcess2::CreateModelsFromTrainingData(), MLL::ModelKnn::TrainModel(), MLL::ModelUsfCasCor::TrainModel(), MLL::ModelSvmBase::TrainModel(), MLL::ModelOldSVM::TrainModel(), and MLL::ModelDual::TrainModel().
double MLL::Model::TrianingPrepTime () const inline
Definition at line 201 of file Model.h.
bool MLL::Model::ValidModel () const inline
Definition at line 203 of file Model.h.
References validModel.
Referenced by MLL::Classifier2::Classifier2(), and MLL::TrainingProcess2::CreateModelsFromTrainingData().
virtual void MLL::Model::WriteSpecificImplementationXML (ostream & o) pure virtual
Implemented in MLL::ModelDual, MLL::ModelOldSVM, MLL::ModelSvmBase, MLL::ModelUsfCasCor, and MLL::ModelKnn.
Referenced by WriteXML().
void Model::WriteXML (ostream & o) virtual
Definition at line 630 of file Model.cpp.
References alreadyNormalized, classes, classesIndex, compression_stats, KKU::endl(), KKU::RunLog::Level(), log, ModelTypeStr(), Name(), normParms, KKU::osGetLocalDateTime(), param, KKU::KKStr::QuotedStr(), rootFileName, MLL::MLClassConstList::ToCommaDelimitedStr(), MLL::ClassIndexList::ToCommaDelString(), MLL::CompressionStats::ToTabDelString(), MLL::NormalizationParms::Write(), WriteSpecificImplementationXML(), and MLL::ModelParam::WriteXML().
Referenced by Save(), and MLL::TrainingProcess2::WriteXml().
Member Data Documentation
bool MLL::Model::alreadyNormalized protected
Definition at line 368 of file Model.h.
Referenced by AlreadyNormalized(), MLL::ModelOldSVM::PrepExampleForPrediction(), PrepExampleForPrediction(), ReadXML(), TrainModel(), and WriteXML().
volatile const bool& MLL::Model::cancelFlag protected
Definition at line 370 of file Model.h.
Referenced by MLL::ModelUsfCasCor::ReadSpecificImplementationXML(), MLL::ModelDual::ReadSpecificImplementationXML(), MLL::ModelOldSVM::ReadSpecificImplementationXML(), MLL::ModelUsfCasCor::TrainModel(), MLL::ModelOldSVM::TrainModel(), and MLL::ModelDual::TrainModel().
MLClassConstListPtr MLL::Model::classes protected
Definition at line 372 of file Model.h.
Referenced by AllocatePredictionVariables(), MemoryConsumedEstimated(), Model(), MLL::ModelUsfCasCor::Predict(), MLL::ModelOldSVM::ProbabilitiesByClass(), MLL::ModelDual::ProbabilitiesByClass(), ReadXML(), MLL::ModelDual::ReconcileProbAndVotes(), ReduceTrainExamples(), MLL::ModelOldSVM::TrainModel(), TrainModel(), WriteXML(), and ~Model().
ClassIndexListPtr MLL::Model::classesIndex protected
Definition at line 374 of file Model.h.
Referenced by MemoryConsumedEstimated(), Model(), MLL::ModelSvmBase::Predict(), MLL::ModelKnn::ProbabilitiesByClass(), MLL::ModelSvmBase::ProbabilitiesByClass(), ReadXML(), MLL::ModelSvmBase::RetrieveCrossProbTable(), RetrieveCrossProbTable(), MLL::ModelSvmBase::TrainModel(), TrainModel(), WriteXML(), and ~Model().
double* MLL::Model::classProbs protected
Definition at line 376 of file Model.h.
Referenced by AllocatePredictionVariables(), DeAllocateSpace(), MemoryConsumedEstimated(), MLL::ModelSvmBase::ProbabilitiesByClass(), and MLL::ModelOldSVM::ProbabilitiesByClass().
CompressionStats MLL::Model::compression_stats protected
Definition at line 378 of file Model.h.
Referenced by BitReductionByFeature(), Compression_Stats(), ReadXML(), ReductionPostExampleCount(), ReductionPreExampleCount(), ReductionRatio(), ReductionTime(), MLL::ModelOldSVM::TrainModel(), TrainModel(), and WriteXML().
double** MLL::Model::crossClassProbTable protected
Probabilities between Binary Classes From last Prediction.
Definition at line 380 of file Model.h.
Referenced by AllocatePredictionVariables(), DeAllocateSpace(), and MemoryConsumedEstimated().
int32 MLL::Model::crossClassProbTableSize protected
Definition at line 382 of file Model.h.
Referenced by AllocatePredictionVariables(), and RetrieveCrossProbTable().
FeatureEncoder2Ptr MLL::Model::encoder protected
Definition at line 384 of file Model.h.
Referenced by Encoder(), MemoryConsumedEstimated(), Model(), PrepExampleForPrediction(), TrainModel(), and ~Model().
FileDescPtr MLL::Model::fileDesc protected
Definition at line 386 of file Model.h.
Referenced by MLL::ModelSvmBase::ModelSvmBase(), MLL::ModelUsfCasCor::ReadSpecificImplementationXML(), MLL::ModelSvmBase::ReadSpecificImplementationXML(), MLL::ModelDual::ReadSpecificImplementationXML(), MLL::ModelOldSVM::ReadSpecificImplementationXML(), ReadXML(), ReduceTrainExamples(), MLL::ModelUsfCasCor::TrainModel(), MLL::ModelOldSVM::TrainModel(), MLL::ModelDual::TrainModel(), and TrainModel().
RunLog& MLL::Model::log protected
Definition at line 388 of file Model.h.
Referenced by AllocatePredictionVariables(), Load(), MLL::ModelSvmBase::ModelSvmBase(), MLL::ModelOldSVM::Param(), MLL::ModelUsfCasCor::Predict(), MLL::ModelSvmBase::Predict(), MLL::ModelDual::Predict(), MLL::ModelKnn::ProbabilitiesByClass(), MLL::ModelUsfCasCor::ProbabilitiesByClass(), MLL::ModelSvmBase::ProbabilitiesByClass(), MLL::ModelOldSVM::ProbabilitiesByClass(), MLL::ModelDual::ProbabilitiesByClass(), MLL::ModelDual::ProbabilitiesByClassDual(), ReadSkipToSection(), MLL::ModelUsfCasCor::ReadSpecificImplementationXML(), MLL::ModelSvmBase::ReadSpecificImplementationXML(), MLL::ModelDual::ReadSpecificImplementationXML(), MLL::ModelOldSVM::ReadSpecificImplementationXML(), ReadXML(), MLL::ModelDual::ReconcilePredictions(), ReduceTrainExamples(), MLL::ModelDual::RetrieveCrossProbTable(), RetrieveCrossProbTable(), Save(), MLL::ModelKnn::TrainModel(), MLL::ModelUsfCasCor::TrainModel(), MLL::ModelSvmBase::TrainModel(), MLL::ModelOldSVM::TrainModel(), MLL::ModelDual::TrainModel(), TrainModel(), MLL::ModelKnn::WriteSpecificImplementationXML(), MLL::ModelUsfCasCor::WriteSpecificImplementationXML(), MLL::ModelSvmBase::WriteSpecificImplementationXML(), MLL::ModelOldSVM::WriteSpecificImplementationXML(), MLL::ModelDual::WriteSpecificImplementationXML(), WriteXML(), and MLL::ModelOldSVM::~ModelOldSVM().
NormalizationParmsPtr MLL::Model::normParms protected
Definition at line 390 of file Model.h.
Referenced by MemoryConsumedEstimated(), MLL::ModelOldSVM::PrepExampleForPrediction(), PrepExampleForPrediction(), ReadXML(), TrainModel(), WriteXML(), and ~Model().
int32 MLL::Model::numOfClasses protected
Number of Classes defined in crossClassProbTable.
Definition at line 392 of file Model.h.
Referenced by AllocatePredictionVariables(), DeAllocateSpace(), MemoryConsumedEstimated(), Model(), MLL::ModelKnn::ProbabilitiesByClass(), MLL::ModelSvmBase::ProbabilitiesByClass(), MLL::ModelOldSVM::ProbabilitiesByClass(), ReadXML(), and MLL::ModelOldSVM::TrainModel().
ModelParamPtr MLL::Model::param protected
Will own this instance.
Definition at line 394 of file Model.h.
Referenced by BitsToReduceBy(), GetFeatureNums(), MemoryConsumedEstimated(), Model(), MLL::ModelDual::ModelDual(), MLL::ModelKnn::ModelKnn(), MLL::ModelSvmBase::ModelSvmBase(), MLL::ModelUsfCasCor::ModelUsfCasCor(), NormalizeNominalAttributes(), MLL::ModelOldSVM::Param(), Param(), MLL::ModelUsfCasCor::ReadSpecificImplementationXML(), MLL::ModelSvmBase::ReadSpecificImplementationXML(), MLL::ModelDual::ReadSpecificImplementationXML(), ReadXML(), ReduceTrainExamples(), SelectedFeatures(), TrainModel(), WriteXML(), and ~Model().
KKStr MLL::Model::rootFileName protected
This is the root name to be used by all component objects; such as svm_model, mlClasses, and svmParam(including selected features).
Each one will have the same rootName with a different suffix.
mlClasses  "<rootName>.image_classes"
svmParam      "<rootName>.svm_parm"
model         "<rootName>"
Definition at line 396 of file Model.h.
Referenced by Load(), MemoryConsumedEstimated(), RootFileName(), Save(), MLL::ModelSvmBase::TrainModel(), MLL::ModelOldSVM::TrainModel(), MLL::ModelOldSVM::WriteSpecificImplementationXML(), WriteXML(), and MLL::ModelOldSVM::~ModelOldSVM().
FeatureVectorListPtr MLL::Model::trainExamples protected
Definition at line 406 of file Model.h.
Referenced by MemoryConsumedEstimated(), ReduceTrainExamples(), MLL::ModelUsfCasCor::TrainModel(), MLL::ModelSvmBase::TrainModel(), MLL::ModelOldSVM::TrainModel(), MLL::ModelDual::TrainModel(), TrainModel(), and ~Model().
bool MLL::Model::validModel protected
Definition at line 410 of file Model.h.
Referenced by AllocatePredictionVariables(), MLL::ModelKnn::ReadSpecificImplementationXML(), MLL::ModelUsfCasCor::ReadSpecificImplementationXML(), MLL::ModelSvmBase::ReadSpecificImplementationXML(), MLL::ModelDual::ReadSpecificImplementationXML(), MLL::ModelOldSVM::ReadSpecificImplementationXML(), ReadXML(), ReduceTrainExamples(), MLL::ModelKnn::TrainModel(), MLL::ModelUsfCasCor::TrainModel(), MLL::ModelSvmBase::TrainModel(), MLL::ModelOldSVM::TrainModel(), MLL::ModelDual::TrainModel(), and ValidModel().
int32* MLL::Model::votes protected
Definition at line 408 of file Model.h.
Referenced by AllocatePredictionVariables(), DeAllocateSpace(), MemoryConsumedEstimated(), MLL::ModelSvmBase::ProbabilitiesByClass(), MLL::ModelUsfCasCor::ProbabilitiesByClass(), MLL::ModelOldSVM::ProbabilitiesByClass(), MLL::ModelDual::ProbabilitiesByClass(), and MLL::ModelDual::ReconcileProbAndVotes().
bool MLL::Model::weOwnTrainExamples protected
Indicates if we own the 'trainExamples'.
This does not mean that we own its contents. That is determined by 'trainExamples->Owner ()'.
Definition at line 412 of file Model.h.
Referenced by MemoryConsumedEstimated(), ReduceTrainExamples(), MLL::ModelOldSVM::TrainModel(), TrainModel(), and ~Model().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/Model.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/Model.cpp