Pices: MLL::SVMModel Class Reference
MLL::SVMModel Class Reference
#include <SVMModel.h>
Public Types
typedef KKU::uint32 uint32
typedef KKU::ulong ulong
Public Member Functions
SVMModel (const KKStr &_rootFileName, bool &_successful, FileDescPtr _fileDesc, RunLog &_log, volatile const bool &_cancelFlag)
Loads an SVM model from disk.
SVMModel (istream &_in, bool &_successful, FileDescPtr _fileDesc, RunLog &_log, volatile const bool &_cancelFlag)
Loads an SVM model from disk.
SVMModel (SVMparam &_svmParam, FeatureVectorList &_examples, ClassAssignments &_assignments, FileDescPtr _fileDesc, RunLog &_log, volatile const bool &_cancelFlag)
Constructor that will create a svmlib training model using the features and classes for training purposes.
virtual ~SVMModel ()
Frees any memory allocated by, and owned by the SVMModel.
const ClassAssignments & Assignments () const
const KKStr & BitReductionByFeature () const
const CompressionStats & Compression_Stats () const
double DistanceFromDecisionBoundary (FeatureVectorPtr example, MLClassConstPtr class1, MLClassConstPtr class2)
vector< ProbNamePair > FindWorstSupportVectors (FeatureVectorPtr example, int32 numToFind, MLClassConstPtr c1, MLClassConstPtr c2)
For a given two class pair return the names of the 'numToFind' worst S/V's.
vector< ProbNamePair > FindWorstSupportVectors2 (FeatureVectorPtr example, int32 numToFind, MLClassConstPtr c1, MLClassConstPtr c2)
For a given two class pair return the names of the 'numToFind' worst S/V's.
const FeatureNumList & GetFeatureNums () const
const FeatureNumList & GetFeatureNums (MLClassConstPtr class1, MLClassConstPtr class2) const
int32 MemoryConsumedEstimated () const
virtual bool NormalizeNominalAttributes ()
int32 NumOfClasses () const
int32 NumOfSupportVectors () const
MLClassConstPtr Predict (FeatureVectorPtr example)
void Predict (FeatureVectorPtr example, MLClassConstPtr knownClass, MLClassConstPtr &predClass1, MLClassConstPtr &predClass2, int32 &predClass1Votes, int32 &predClass2Votes, double &probOfKnownClass, double &predClassProb, double &predClass2Prob, double &compact, int32 &numOfWinners, bool &knownClassOneOfTheWinners, double &breakTie)
Will predict the two most likely classes of 'example'.
void ProbabilitiesByClass (FeatureVectorPtr example, const MLClassConstList &_mlClasses, int32 *_votes, double *_probabilities)
Will get the probabilities assigned to each class.
int32 ReductionPostExampleCount () const
int32 ReductionPreExampleCount () const
float ReductionRatio () const
double ReductionTime () const
void RetrieveCrossProbTable (MLClassConstList &classes, double **crossProbTable)
Will return the probabilities for all pairs of the classes listed in 'classes'.
const KKStr & RootFileName () const
void Save (const KKStr &_rootFileName, bool &_successful)
SVM_SelectionMethod SelectionMethod () const
vector< KKStr > SupportVectorNames () const
vector< KKStr > SupportVectorNames (MLClassConstPtr c1, MLClassConstPtr c2) const
void SupportVectorStatistics (int32 &numSVs, int32 &totalNumSVs)
const SVMparam & SVMParameters () const
double TrainingTime () const
void Write (ostream &o, const KKStr &rootFileName, bool &_successful)
Detailed Description
Definition at line 76 of file SVMModel.h.
Member Typedef Documentation
typedef KKU::uint32 MLL::SVMModel::uint32
Definition at line 79 of file SVMModel.h.
typedef KKU::ulong MLL::SVMModel::ulong
Definition at line 80 of file SVMModel.h.
Constructor & Destructor Documentation
MLL::SVMModel::SVMModel (const KKStr & _rootFileName, bool & _successful, FileDescPtr _fileDesc, RunLog & _log, volatile const bool & _cancelFlag)
Loads an SVM model from disk.
Parameters
[in] _rootFileName The filename for the model; without an extension.
[out] _successful Set to true if the model is succesfulyl loaded, false otherwise
[in] _fileDesc A description of the training data that was used to train the classifier.
[in] _log A logfile stream. All important events will be ouput to this stream
[in] _cancelFlag If set to true any process running in SVMModel will terminate.
Referenced by MemoryConsumedEstimated().
MLL::SVMModel::SVMModel (istream & _in, bool & _successful, FileDescPtr _fileDesc, RunLog & _log, volatile const bool & _cancelFlag)
Loads an SVM model from disk.
The '_cancelFlag' parameter is meant to allow another thread to cancel processing by a different thread in SVMmodel. Ex: If one thread is building a new SVM for this instance of SVMmodel, that thread will periodcaly monitor '_cancelFlag', if it is set to true it will terminate its processing.
Parameters
[in] _in A file stream to read and build SVMModel from.
[out] _successful Set to true if the model is succesfulyl loaded, false otherwise
[in] _fileDesc A description of the data file. I'm not sure this is needed for this function.
[in] _log A logfile stream. All important events will be ouput to this stream
[in] _cancelFlag If set to true any process running in SVMModel will terminate.
MLL::SVMModel::SVMModel (SVMparam & _svmParam, FeatureVectorList & _examples, ClassAssignments & _assignments, FileDescPtr _fileDesc, RunLog & _log, volatile const bool & _cancelFlag)
Constructor that will create a svmlib training model using the features and classes for training purposes.
Parameters
[in] _svmParam Specifies the parameters to be used for trainig. These are the same parameters that you would specify in the command line to svm_train. Plus the feature nums to be used.
[in] _examples Training data for the classifier.
[in] _assignments List of classes and there assovciated number ti be used by the SVM. You can merge 1 or more classes by assigning them the same number. This nummber will be used by the SVM. When predictions are done by SVM it return a number, _assignments will then be used to map backto the correct class.
[in] _fileDesc ile Description thaty describes the training data.
[out] _log Log file to log messages to.
[in] _cancelFlag The training process will monitor this flag; if it goes true it return to caller.
SVMModel::~SVMModel () virtual
Frees any memory allocated by, and owned by the SVMModel.
Definition at line 405 of file SVMModel.cpp.
References KKU::endl(), KKU::RunLog::Level(), MLL::SvmDestroyModel(), and x.
Member Function Documentation
const ClassAssignments& MLL::SVMModel::Assignments () const inline
Definition at line 157 of file SVMModel.h.
Referenced by MLL::ModelOldSVM::Assignments().
const KKStr& MLL::SVMModel::BitReductionByFeature () const inline
Definition at line 175 of file SVMModel.h.
References MLL::CompressionStats::bitReductionByFeature.
const CompressionStats& MLL::SVMModel::Compression_Stats () const inline
Definition at line 181 of file SVMModel.h.
Referenced by MLL::ModelOldSVM::TrainModel().
double SVMModel::DistanceFromDecisionBoundary (FeatureVectorPtr example, MLClassConstPtr class1, MLClassConstPtr class2)
Definition at line 1369 of file SVMModel.cpp.
References MLL::BinaryCombos, MLL::FeatureEncoder::Class1(), MLL::FeatureEncoder::Class2(), MLL::FeatureEncoder::EncodeAImage(), KKU::endl(), KKU::RunLog::Level(), MLL::SVMparam::MachineType(), and SVM233::svm_predictTwoClasses().
vector< ProbNamePair > SVMModel::FindWorstSupportVectors (FeatureVectorPtr example, int32 numToFind, MLClassConstPtr c1, MLClassConstPtr c2)
For a given two class pair return the names of the 'numToFind' worst S/V's.
This method will iterate through all the S/V's removing them one at a time and recompute the decision boundary and probability. It will then return the S/V's that when removed improve the probability in 'c1's the most.
Parameters
[in] example Example that was classified incorrectly.
[in] numToFind The number of teh worst examples you are looking for.
[in] c1 Class that the 'example; parameter should have been classed as.
[in] c2 Class that it was classified as.
Definition at line 2289 of file SVMModel.cpp.
References SVM233::svm_parameter::A, AdjProb(), MLL::BinaryCombos, MLL::BinaryClassParms::Class1(), MLL::BinaryClassParms::Class2(), MLL::FeatureEncoder::EncodeAImage(), KKU::endl(), SVM233::svm_model::l, KKU::RunLog::Level(), MLL::SVMparam::MachineType(), MLL::PairCompareOperator(), MLL::BinaryClassParms::Param(), SVM233::svm_model::SupportVectorName(), and SVM233::svm_predictTwoClasses().
Referenced by MLL::Classifier2::FindWorstSupportVectors(), and MLL::ModelOldSVM::FindWorstSupportVectors().
vector< ProbNamePair > SVMModel::FindWorstSupportVectors2 (FeatureVectorPtr example, int32 numToFind, MLClassConstPtr c1, MLClassConstPtr c2)
For a given two class pair return the names of the 'numToFind' worst S/V's.
This method will iterate through all the S/V's removing them one at a time and retraining a new SVM and then comparing with the new prediction results.
Parameters
[in] example Example that was classified incorrectly.
[in] numToFind The number of teh worst examples you are looking for.
[in] c1 Class that the 'example; parameter should have been classed as.
[in] c2 Class that it was classified as.
Definition at line 2382 of file SVMModel.cpp.
References SVM233::svm_parameter::A, AdjProb(), MLL::BinaryCombos, MLL::BinaryClassParms::Class1(), MLL::BinaryClassParms::Class2(), SVM233::svm_model::Dispose(), MLL::FeatureEncoder::EncodeAImage(), KKU::endl(), SVM233::svm_model::l, KKU::RunLog::Level(), MLL::SVMparam::MachineType(), SVM233::svm_parameter::nr_class, MLL::PairCompareOperator(), MLL::BinaryClassParms::Param(), SVM233::svm_model::param, SVM233::svm_model::SupportVectorName(), SVM233::svm_BuildProbFromTwoClassModel(), SVM233::svm_predictTwoClasses(), and SVM233::svm_train().
Referenced by MLL::Classifier2::FindWorstSupportVectors2(), and MLL::ModelOldSVM::FindWorstSupportVectors2().
const FeatureNumList & SVMModel::GetFeatureNums () const
Definition at line 763 of file SVMModel.cpp.
References MLL::SVMparam::GetFeatureNums().
Referenced by MLL::ModelOldSVM::GetFeatureNums().
const FeatureNumList & SVMModel::GetFeatureNums (MLClassConstPtr class1, MLClassConstPtr class2) const
Definition at line 752 of file SVMModel.cpp.
References MLL::SVMparam::GetFeatureNums().
int32 SVMModel::MemoryConsumedEstimated () const
Definition at line 500 of file SVMModel.cpp.
References MLL::ClassAssignments::MemoryConsumedEstimated(), MLL::FeatureEncoder::MemoryConsumedEstimated(), MLL::SVMparam::MemoryConsumedEstimated(), SVM233::svm_model::MemoryConsumedEstimated(), KKU::KKStr::MemoryConsumedEstimated(), SVMModel(), and x.
Referenced by MLL::ModelOldSVM::MemoryConsumedEstimated().
bool SVMModel::NormalizeNominalAttributes () virtual
Definition at line 2954 of file SVMModel.cpp.
References MLL::SVMparam::EncodingMethod(), and MLL::NoEncoding.
Referenced by MLL::ModelOldSVM::NormalizeNominalAttributes().
int32 MLL::SVMModel::NumOfClasses () const inline
Definition at line 167 of file SVMModel.h.
int32 SVMModel::NumOfSupportVectors () const
Definition at line 1924 of file SVMModel.cpp.
References MLL::BinaryCombos, MLL::SVMparam::MachineType(), and SupportVectorNames().
Referenced by MLL::ModelOldSVM::NumOfSupportVectors(), and SupportVectorStatistics().
MLClassConstPtr SVMModel::Predict (FeatureVectorPtr example)
Definition at line 1749 of file SVMModel.cpp.
Referenced by MLL::ModelOldSVM::Predict().
void MLL::SVMModel::Predict (FeatureVectorPtr example, MLClassConstPtr knownClass, MLClassConstPtr & predClass1, MLClassConstPtr & predClass2, int32 & predClass1Votes, int32 & predClass2Votes, double & probOfKnownClass, double & predClassProb, double & predClass2Prob, double & compact, int32 & numOfWinners, bool & knownClassOneOfTheWinners, double & breakTie)
Will predict the two most likely classes of 'example'.
Parameters
[in] example Example to predict on.
[in] knownClass Class that we already no the example to be; can be pointing to NULL indicating that you do not know.
[out] predClass1 Most likely class; depending on classifier paraketers this could be by number of votes or probability.
[out] predClass2 Second most likely class.
[out] predClass1Votes Number votes 'predClass1' received.
[out] predClass2Votes Number votes 'predClass2' received.
[out] probOfKnownClass Probability of 'knownClass' if specified.
[out] predClassProb Probability of 'predClass1' if specified.
[out] predClass2Prob Probability of 'predClass2' if specified.
[out] compact Minus log likilihood of known class (-log (probabilities[knownClassNum]));
[out] numOfWinners Number of classes that had the sam enumber of votes as the winning class.
[out] knownClassOneOfTheWinners Will return true if the known class was one of the classes that had the highest numberof votes.
[out] breakTie The difference in probability between the classes with thetwo hiest probabilities.
void SVMModel::ProbabilitiesByClass (FeatureVectorPtr example, const MLClassConstList & _mlClasses, int32 * _votes, double * _probabilities)
Will get the probabilities assigned to each class.
Parameters
[in] example unknown example that we want to get predicted probabilities for.
[in] _mlClasses List classes that caller is aware of. This should be the same list that was used when consttructing this SVMModel object. The list must be the same but not nessasarily in the same order as when SVMModel was 1st constructed.
[out] _votes An array that must be as big as the number of classes in _mlClasses.
[out] _probabilities An array that must be as big as the number of classes in _mlClasses. The probability of class in _mlClasses[x] will be returned in _probabilities[x].
Definition at line 1974 of file SVMModel.cpp.
References MLL::BinaryCombos, MLL::FeatureEncoder::EncodeAImage(), KKU::endl(), MLL::ClassAssignments::GetMLClass(), KKU::RunLog::Level(), MLL::SVMparam::MachineType(), MLL::SvmPredictClass(), and x.
Referenced by MLL::ModelOldSVM::ProbabilitiesByClass().
int32 MLL::SVMModel::ReductionPostExampleCount () const inline
Definition at line 178 of file SVMModel.h.
References MLL::CompressionStats::num_images_after.
int32 MLL::SVMModel::ReductionPreExampleCount () const inline
Definition at line 177 of file SVMModel.h.
References MLL::CompressionStats::num_images_before.
float MLL::SVMModel::ReductionRatio () const inline
Definition at line 179 of file SVMModel.h.
References MLL::CompressionStats::compression_ratio.
double MLL::SVMModel::ReductionTime () const inline
Definition at line 176 of file SVMModel.h.
References MLL::CompressionStats::elapsed_cpu_time.
void SVMModel::RetrieveCrossProbTable (MLClassConstList & classes, double ** crossProbTable)
Will return the probabilities for all pairs of the classes listed in 'classes'.
Parameters
[in] classes Classes that you wish to get class pair probabilities for; the order will dictate how the two dimensional matrix 'crossProbTable' will be populated.
[out] crossProbTable Will contain the probabilities of all the class pairs that can be formed from the list of classes in 'classes'. 'crossProbTable' will be a two dimension square matrix size will be dictated by the number of classes in 'classes'. Ex: Entry[3][2] will have the contain the probability between classes[3] and classes[2].
Definition at line 2973 of file SVMModel.cpp.
References KKU::endl(), MLL::ClassAssignments::GetNumForClass(), KKU::RunLog::Level(), and x.
Referenced by MLL::ModelOldSVM::RetrieveCrossProbTable().
const KKStr& MLL::SVMModel::RootFileName () const inline
Definition at line 185 of file SVMModel.h.
void SVMModel::Save (const KKStr & _rootFileName, bool & _successful)
Definition at line 770 of file SVMModel.cpp.
References KKU::endl(), KKU::RunLog::Level(), KKU::KKStr::Str(), and Write().
SVM_SelectionMethod MLL::SVMModel::SelectionMethod () const inline
Definition at line 188 of file SVMModel.h.
References MLL::SVMparam::SelectionMethod().
Referenced by MLL::ModelOldSVM::SelectionMethod().
vector< KKStr > SVMModel::SupportVectorNames () const
Definition at line 2254 of file SVMModel.cpp.
References MLL::BinaryCombos, SVM233::svm_model::l, MLL::SVMparam::MachineType(), and SVM233::svm_model::SupportVectorName().
Referenced by NumOfSupportVectors(), MLL::ModelOldSVM::SupportVectorNames(), and MLL::Classifier2::SupportVectorNames().
vector< KKStr > SVMModel::SupportVectorNames (MLClassConstPtr c1, MLClassConstPtr c2) const
Definition at line 2212 of file SVMModel.cpp.
References MLL::BinaryCombos, MLL::BinaryClassParms::Class1(), MLL::BinaryClassParms::Class2(), KKU::endl(), SVM233::svm_model::l, KKU::RunLog::Level(), MLL::SVMparam::MachineType(), and SVM233::svm_model::SupportVectorName().
void SVMModel::SupportVectorStatistics (int32 & numSVs, int32 & totalNumSVs)
Definition at line 1948 of file SVMModel.cpp.
References MLL::BinaryCombos, SVM233::svm_model::l, MLL::SVMparam::MachineType(), NumOfSupportVectors(), and SVM233::svm_GetSupportVectorStatistics().
Referenced by MLL::ModelOldSVM::SupportVectorStatistics().
const SVMparam& MLL::SVMModel::SVMParameters () const inline
Definition at line 183 of file SVMModel.h.
Referenced by MLL::ModelOldSVM::Description(), and MLL::ModelOldSVM::ProbabilitiesByClass().
double MLL::SVMModel::TrainingTime () const inline
Definition at line 190 of file SVMModel.h.
void SVMModel::Write (ostream & o, const KKStr & rootFileName, bool & _successful)
Definition at line 791 of file SVMModel.cpp.
References MLL::BinaryCombos, MLL::BinaryClassParms::Class1Name(), MLL::BinaryClassParms::Class2Name(), KKU::endl(), MLL::ClassAssignments::GetMLClassByIndex(), KKU::RunLog::Level(), MLL::SVMparam::MachineType(), MLL::MachineTypeToStr(), MLL::OneVsAll, MLL::OneVsOne, KKU::osGetLocalDateTime(), KKU::KKStr::QuotedStr(), KKU::KKStr::Str(), MLL::SvmSaveModel(), MLL::ClassAssignments::ToString(), MLL::FeatureNumList::ToString(), MLL::CompressionStats::ToTabDelString(), and MLL::SVMparam::WriteXML().
Referenced by Save(), and MLL::ModelOldSVM::WriteSpecificImplementationXML().
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/SVMModel.h
D:/Users/kkramer/IEC/SipperSoftware/PicesLibrary/SVMModel.cpp