Pices: KKU::KKStrException Class Reference
KKU::KKStrException Class Reference
#include <Str.h>
Public Member Functions
KKStrException ()
KKStrException (const KKStrException &_exception)
KKStrException (const KKStr &_exceptionStr)
KKStrException (const KKStr &_exceptionStr, const std::exception &_innerException)
KKStrException (const char *_exceptionStr)
KKStrException (const char *_exceptionStr, const std::exception &_innerException)
virtual ~KKStrException () throw ()
virtual const KKStr & ToString () const
virtual const char * what () const throw ()
Detailed Description
Definition at line 980 of file Str.h.
Constructor & Destructor Documentation
KKStrException::KKStrException ()
Definition at line 4636 of file Str.cpp.
References KKStrException().
Referenced by KKStrException().
KKStrException::KKStrException (const KKStrException & _exception)
Definition at line 4642 of file Str.cpp.
References KKU::KKStr::KKStr(), and KKStrException().
Referenced by KKStrException().
KKStrException::KKStrException (const KKStr & _exceptionStr)
Definition at line 4656 of file Str.cpp.
References KKU::KKStr::KKStr(), and KKStrException().
Referenced by MLL::FeatureNumList::AddFeature(), MLL::AbundanceCorrectionMatrix::AddIn(), KKU::MsgQueue::AddMsg(), KKU::RasterBuffer::AddRaster(), MLL::Classifier2::Classifier2(), MLL::Model::CreateAModel(), KKU::BmpImage::CodedPixels::CreatePixelDataStructure8Bit(), KKU::Matrix::DeterminantSlow(), MLL::FeatureNumList::FeatureAttributeType(), MLL::SVMModel::FindWorstSupportVectors(), MLL::SVMModel::FindWorstSupportVectors2(), KKU::RasterSipper::FromCompressor(), MLL::DataBase::ImageFullSizeFind(), KKU::Matrix::Inverse(), KKStrException(), KKU::BitString::ListOfSetBits16(), KKU::Matrix::Matrix(), KKU::Matrix::operator*(), MLL::FeatureNumList::operator*(), KKU::Matrix::operator+(), MLL::FeatureNumList::operator+(), KKU::Matrix::operator+=(), KKU::Matrix::operator-(), MLL::FeatureNumList::operator-(), KKU::Matrix::operator[](), MLL::ModelOldSVM::Param(), MLL::ModelUsfCasCor::Predict(), MLL::ModelKnn::ProbabilitiesByClass(), MLL::ModelUsfCasCor::ProbabilitiesByClass(), MLL::ModelSvmBase::ProbabilitiesByClass(), MLL::ModelOldSVM::ProbabilitiesByClass(), KKU::Raster::Raster(), MLL::Model::ReadXML(), KKU::XmlStream::RegisterXmlElementCreator(), KKU::Row::Row(), KKU::BmpImage::Save(), KKU::BmpImage::SaveGrayscaleInverted4Bit(), KKU::BmpImage::SaveGrayscaleInverted8Bit(), KKU::SaveImage(), KKU::SaveImageGrayscaleInverted4Bit(), KKU::SaveImageGrayscaleInverted8Bit(), KKU::SaveImagePNG(), MLL::TrainingConfiguration2::SetFeatureNums(), SVM289_MFS::svm_train_one(), SVM289_BFS::svm_train_one(), MLL::TrainingConfiguration2::SVMparamREF(), MLL::ModelUsfCasCor::TrainModel(), MLL::ModelSvmBase::TrainModel(), MLL::ModelOldSVM::TrainModel(), MLL::ModelDual::TrainModel(), and MLL::Model::TrainModel().
KKStrException::KKStrException (const KKStr & _exceptionStr, const std::exception & _innerException)
Definition at line 4663 of file Str.cpp.
References KKU::KKStr::KKStr(), and KKStrException().
Referenced by KKStrException(), KKU::SaveImage(), KKU::SaveImageGrayscaleInverted4Bit(), KKU::SaveImageGrayscaleInverted8Bit(), MLL::ModelUsfCasCor::TrainModel(), MLL::ModelSvmBase::TrainModel(), and MLL::ModelDual::TrainModel().
KKStrException::KKStrException (const char * _exceptionStr)
Definition at line 4649 of file Str.cpp.
References KKU::KKStr::KKStr(), and KKStrException().
Referenced by MLL::Model::BitsToReduceBy(), MLL::Classifier2::Classifier2(), MLL::Model::CreateAModel(), MLL::Model::Encoder(), MLL::Model::GetFeatureNums(), MLL::DataBase::ImageFullSizeFind(), KKU::Raster::Initialize(), KKStrException(), MLL::Model::NormalizeNominalAttributes(), KKU::KKStr::operator<<(), KKU::RasterSipperList::RasterSipperList(), MLL::Model::SelectedFeatures(), ImageExtractionManager::ImageExtractionThread::Start(), KKU::KKThread::Start(), and SVM233::svm_model::svm_model().
KKStrException::KKStrException (const char * _exceptionStr, const std::exception & _innerException)
Definition at line 4675 of file Str.cpp.
Referenced by MLL::Model::CreateAModel(), and MLL::DataBase::ImageFullSizeFind().
KKStrException::~KKStrException () throw () virtual
Definition at line 4685 of file Str.cpp.
Member Function Documentation
const KKStr & KKStrException::ToString () const virtual
Definition at line 4690 of file Str.cpp.
Referenced by MLL::Model::CreateFromStream(), MLL::TrainingProcess2::CreateModelsFromTrainingData(), MLL::DataBase::ImageFullSizeFind(), MLL::TrainingProcess2::Read(), MLL::ModelUsfCasCor::TrainModel(), MLL::ModelSvmBase::TrainModel(), MLL::ModelDual::TrainModel(), and MLL::TrainingProcess2::WriteXml().
const char * KKStrException::what () const throw () virtual
Definition at line 4696 of file Str.cpp.
References KKU::KKStr::Str().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/IEC/SipperSoftware/BaseLibrary/Str.h
C:/Users/kurtk_000/IEC/SipperSoftware/BaseLibrary/Str.cpp