Pices: SipperHardware::InstrumentDataGPS Class Reference
SipperHardware::InstrumentDataGPS Class Reference
#include <InstrumentDataGPS.h>
Public Member Functions
InstrumentDataGPS (InstrumentDataManagerPtr _manager, const KKStr &_reportDir, bool _text, int32 _instrumentId)
virtual ~InstrumentDataGPS ()
virtual void ReportInstrumentData (uint32 curScanLine, uchar sensorData)
Public Member Functions inherited from SipperHardware::InstrumentDataReport
InstrumentDataReport (InstrumentDataManagerPtr _manager, const KKStr &_reportDir, bool _text, int32 _instrumentId, bool _useReportWithLineNumbers)
virtual ~InstrumentDataReport ()
const KKStr & CurTextLine ()
const KKStr & LastTextLine ()
Additional Inherited Members
Public Types inherited from SipperHardware::InstrumentDataReport
typedef InstrumentDataReport * InstrumentDataReportPtr
typedef KKU::int32 int32
typedef KKU::uint32 uint32
Static Public Member Functions inherited from SipperHardware::InstrumentDataReport
static InstrumentDataReportPtr CreateInstrumentDataReport (InstrumentDataManagerPtr _manager, const KKStr &_reportDir, bool _text, int32 _instrumentId)
A virtual Constructor for InstrumentDataReport.
Protected Member Functions inherited from SipperHardware::InstrumentDataReport
KKStr InstrumentName ()
Protected Attributes inherited from SipperHardware::InstrumentDataReport
KKStr curTextLine
Used where "text == true", Every time a character is read via 'ReportInstrumentData' will append to end of string.
int32 instrumentId
uint32 lastScanLineReported
KKStr lastTextLine
Used where "text == true", will keep an instance of last complete text line read.
InstrumentDataManagerPtr manager
ofstream report
KKStr reportFileName
KKStr reportFileNameWLN
ofstream reportWLN
bool text
bool useReportWithLineNumbers
Static Protected Attributes inherited from SipperHardware::InstrumentDataReport
static const char * InstrumentNames []
Detailed Description
Definition at line 17 of file InstrumentDataGPS.h.
Constructor & Destructor Documentation
InstrumentDataGPS::InstrumentDataGPS (InstrumentDataManagerPtr _manager, const KKStr & _reportDir, bool _text, int32 _instrumentId)
Definition at line 25 of file InstrumentDataGPS.cpp.
InstrumentDataGPS::~InstrumentDataGPS () virtual
Definition at line 40 of file InstrumentDataGPS.cpp.
References SipperHardware::InstrumentDataReport::report.
Member Function Documentation
void InstrumentDataGPS::ReportInstrumentData (uint32 curScanLine, uchar sensorData) virtual
Reimplemented from SipperHardware::InstrumentDataReport.
Definition at line 116 of file InstrumentDataGPS.cpp.
References KKU::KKStr::Append(), KKU::KKStr::Empty(), KKU::endl(), KKU::KKStr::Len(), and SipperHardware::InstrumentDataReport::report.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/InstrumentDataGPS.h
D:/Users/kkramer/IEC/SipperSoftware/SipperInstruments/InstrumentDataGPS.cpp