Pices: KKU::BitString Class Reference
KKU::BitString Class Reference
Allows you to manage very long bit strings.
#include <BitString.h>
Public Member Functions
BitString (uint32 _bitLen)
Construct a bit string of length _binLen with all bits set to '0'.
BitString (const BitString &b)
Copy constructor.
BitString (uint32 _bitLen, uint16 *_bitNums, uint32 _bitNumsLen)
Construct a BitString of length _bitLen with bits indicated by '_bitNums' set to '1'.
~BitString ()
uint32 BitLen () const
Returns the length of the bit-string.
uint32 Count () const
Returns number of bits set to '1'.
KKStr HexStr () const
Returns a Hex-String representation.
void ListOfSetBits16 (VectorUint16 &setBits) const
Get Bit positions that are set to '1'.
void ListOfSetBits32 (VectorUint32 &setBits) const
Get Bit positions that are set to '1'.
bool operator!= (const BitString &right) const
BitString & operator&= (const BitString &right)
Performs a bitwise AND against the left operand.
BitString & operator*= (const BitString &right)
Performs a bitwise AND against the left operand.
BitString & operator+= (const BitString &right)
Performs a bitwise OR against the left operand.
bool operator< (const BitString &right) const
bool operator<= (const BitString &right) const
BitString & operator= (const BitString &right)
bool operator== (const BitString &right) const
bool operator> (const BitString &right) const
bool operator>= (const BitString &right) const
BitString operator^ (const BitString &right)
Performs a bitwise XOR between two operands returning a new BitString.
BitString & operator^= (const BitString &right)
Performs a bitwise XOR against the left operand.
BitString & operator|= (const BitString &right)
Performs a bitwise OR against the left operand.
void PopulateVectorBool (VectorBool &boolVector) const
Populates a boolean vector where each element reflects whether the corresponding bit is set.
void ReSet ()
Set all bits to '0'.
void ReSet (uint32 bitNum)
Set the bit indicated by 'bitNum' to '0'.
void Set ()
Set all bits to '1'.
void Set (uint32 bitNum)
Set the bit indicated by 'bitNum' to '1'.
bool Test (uint32 bitNum) const
Returns true if bit indicated by 'bitNum' is set to '1'.
Static Public Member Functions
static BitString FromHexStr (const KKStr &hexStr, bool &validHexStr)
Create a bit-string from a Hex String.
Detailed Description
Allows you to manage very long bit strings.
Author
Kurt Kramer
Useful when you need to deal with very large yes/no decisions. For example performing Feature Selection on a DNA dataset where you can have 50,000+ features. You need to keep a list of which feature combinations have been tried. You can use a BitString to do this where a particular bit indicates a particular feature. In the feature selection case you may want to track several thousand feature combinations. If you did this using arrays you would require very large amount of memory to accomplish this. With BitString's the memory requirement is reduced to 1/8'th allowing for more efficient use of memory.
This class will manage Bit-Strings up to UINT_MAX in length. Logical operations such as bitwise AND, OR, and NOT are supported plus others. An example of where this class is used is in PicesLibrary MLL::FeatureNumList.
Definition at line 29 of file BitString.h.
Constructor & Destructor Documentation
BitString::BitString (uint32 _bitLen)
Construct a bit string of length _binLen with all bits set to '0'.
Parameters
[in] _bitLen Length of bit string to allocate.
Definition at line 356 of file BitString.cpp.
BitString::BitString (const BitString & b)
Copy constructor.
Definition at line 369 of file BitString.cpp.
References x.
BitString::BitString (uint32 _bitLen, uint16 * _bitNums, uint32 _bitNumsLen)
Construct a BitString of length _bitLen with bits indicated by '_bitNums' set to '1'.
Parameters
[in] _binLen Length of bit string.
[in] _bitNums List if bit positions to set to '1'.
[in] _bitNumsLen Size of '_bitNums' array.
Definition at line 383 of file BitString.cpp.
References KKU::endl(), Set(), and x.
BitString::~BitString ()
Definition at line 417 of file BitString.cpp.
Member Function Documentation
uint32 KKU::BitString::BitLen () const inline
Returns the length of the bit-string.
Definition at line 59 of file BitString.h.
KKU::uint32 BitString::Count () const
Returns number of bits set to '1'.
Definition at line 435 of file BitString.cpp.
BitString BitString::FromHexStr (const KKStr & hexStr, bool & validHexStr) static
Create a bit-string from a Hex String.
Will convert the Hex String stored in the parameter 'hexStr' and create a bit string from it.
ex: "A189" will be converted into "1010000110001001"
Parameters
[in] hexStr String containing hex characters '0' - '9', 'A' - 'F'
[out] validHexStr returns 'TRUE' if no invalid characters.
Returns
BitString with the appropriate bits set to represent the hex number in 'hexStr'.
Definition at line 692 of file BitString.cpp.
References KKU::KKStr::Len().
KKStr BitString::HexStr () const
Returns a Hex-String representation.
ex: "1110 0000 0101 1011" would return "E09B".
Definition at line 654 of file BitString.cpp.
References KKU::KKStr::Append().
void BitString::ListOfSetBits16 (VectorUint16 & setBits) const
Get Bit positions that are set to '1'.
The parameter 'setBits' will be populated with the list of bits that are set to '1' for bit strings that are up to 2^16-1 bits long.
ex: Bit String "001200110011" will produce a vector <2, 3, 6, 7, 10, 11>
Parameters
[out] Will be populated with all bits that are set to '1', will be cleared first.
Definition at line 559 of file BitString.cpp.
References KKU::endl(), and x.
void BitString::ListOfSetBits32 (VectorUint32 & setBits) const
Get Bit positions that are set to '1'.
The parameter 'setBits' will be populated with the list of bits that are set to '1' for bit strings that are up to 2^32-1 bits long.
ex: Bit String "001200110011" will produce a vector <2, 3, 6, 7, 10, 11>
Parameters
[out] Will be populated with all bits that are set to '1', will be cleared first.
Definition at line 610 of file BitString.cpp.
References x.
bool BitString::operator!= (const BitString & right) const
Definition at line 845 of file BitString.cpp.
BitString & BitString::operator&= (const BitString & right)
Performs a bitwise AND against the left operand.
Definition at line 777 of file BitString.cpp.
References KKU::Min(), and x.
Referenced by operator*=().
BitString & BitString::operator*= (const BitString & right)
Performs a bitwise AND against the left operand.
Definition at line 797 of file BitString.cpp.
References operator&=().
BitString & BitString::operator+= (const BitString & right)
Performs a bitwise OR against the left operand.
Definition at line 768 of file BitString.cpp.
References operator|=().
bool BitString::operator< (const BitString & right) const
Definition at line 866 of file BitString.cpp.
bool KKU::BitString::operator<= (const BitString & right) const
BitString & BitString::operator= (const BitString & right)
Definition at line 734 of file BitString.cpp.
References x.
bool BitString::operator== (const BitString & right) const
Definition at line 838 of file BitString.cpp.
bool BitString::operator> (const BitString & right) const
Definition at line 852 of file BitString.cpp.
bool BitString::operator>= (const BitString & right) const
Definition at line 859 of file BitString.cpp.
BitString BitString::operator^ (const BitString & right)
Performs a bitwise XOR between two operands returning a new BitString.
Definition at line 891 of file BitString.cpp.
References KKU::Max(), KKU::Min(), and x.
BitString & BitString::operator^= (const BitString & right)
Performs a bitwise XOR against the left operand.
Definition at line 873 of file BitString.cpp.
References KKU::Max(), KKU::Min(), and x.
BitString & BitString::operator|= (const BitString & right)
Performs a bitwise OR against the left operand.
Definition at line 752 of file BitString.cpp.
References KKU::Min(), and x.
Referenced by operator+=().
void BitString::PopulateVectorBool (VectorBool & boolVector) const
Populates a boolean vector where each element reflects whether the corresponding bit is set.
Parameters
[out] boolVector Vector to be populated reflecting which bits are set to '1'.
Definition at line 532 of file BitString.cpp.
References x.
void BitString::ReSet ()
Set all bits to '0'.
Definition at line 500 of file BitString.cpp.
Referenced by MLL::FeatureNumList::ToBitString().
void BitString::ReSet (uint32 bitNum)
Set the bit indicated by 'bitNum' to '0'.
Definition at line 508 of file BitString.cpp.
References KKU::endl().
void BitString::Set ()
Set all bits to '1'.
Definition at line 466 of file BitString.cpp.
Referenced by BitString(), and MLL::FeatureNumList::ToBitString().
void BitString::Set (uint32 bitNum)
Set the bit indicated by 'bitNum' to '1'.
Definition at line 475 of file BitString.cpp.
References KKU::endl().
bool BitString::Test (uint32 bitNum) const
Returns true if bit indicated by 'bitNum' is set to '1'.
Definition at line 451 of file BitString.cpp.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/BitString.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/BitString.cpp