Pices: KKU::TimeType Class Reference
KKU::TimeType Class Reference
Represents a Time, consisting of three fields, Hour, Minute, and Second.
#include <DateTime.h>
Public Member Functions
TimeType ()
TimeType (const TimeType &time)
TimeType (uchar _hour, uchar _minute, uchar _second)
TimeType (int32 seconds)
TimeType (KKStr s)
KKStr HH_MM_SS () const
KKStr HHMMSS () const
uchar Hour () const
void Hour (uchar _hour)
uchar Minute () const
void Minute (uchar _minute)
bool operator!= (const TimeType &right) const
TimeType operator+ (const TimeType &right) const
Add one day.
TimeType operator- (const TimeType &right) const
Subtract one day.
bool operator< (const TimeType &right) const
bool operator<= (const TimeType &right) const
TimeType & operator= (const TimeType &right)
bool operator== (const TimeType &right) const
bool operator> (const TimeType &right) const
bool operator>= (const TimeType &right) const
uchar Second () const
void Second (uchar _second)
uint32 Seconds () const
double ToHours () const
double ToMinutes () const
Friends
class DateTime
Detailed Description
Represents a Time, consisting of three fields, Hour, Minute, and Second.
Definition at line 156 of file DateTime.h.
Constructor & Destructor Documentation
TimeType::TimeType ()
Definition at line 762 of file DateTime.cpp.
Referenced by operator+(), and operator-().
TimeType::TimeType (const TimeType & time)
Definition at line 771 of file DateTime.cpp.
TimeType::TimeType (uchar _hour, uchar _minute, uchar _second)
Definition at line 779 of file DateTime.cpp.
TimeType::TimeType (int32 seconds)
Definition at line 790 of file DateTime.cpp.
TimeType::TimeType (KKStr s)
Definition at line 807 of file DateTime.cpp.
References KKU::KKStr::ExtractToken(), KKU::KKStr::Len(), KKU::KKStr::Str(), and KKU::KKStr::SubStrPart().
Member Function Documentation
KKStr TimeType::HH_MM_SS () const
Definition at line 846 of file DateTime.cpp.
References KKU::StrFormatInt().
Referenced by KKU::Application::BuildDate(), SipperHardware::InstrumentData::FieldToStr(), KKU::operator<<(), and KKU::DateTime::YYYY_MM_DD_HH_MM_SS().
KKStr TimeType::HHMMSS () const
Definition at line 852 of file DateTime.cpp.
References KKU::StrFormatInt().
Referenced by KKU::DateTime::YYYYMMDDHHMMSS().
uchar KKU::TimeType::Hour () const inline
Definition at line 172 of file DateTime.h.
Referenced by KKU::DateTime::AddHours(), PicesInterface::PicesMethods::DateTimeKKUtoSystem(), KKU::DateTime::HH_MM_SS(), KKU::operator<<(), and PicesInterface::PicesMethods::TimeTypeKKUtoSystem().
void KKU::TimeType::Hour (uchar _hour) inline
Definition at line 180 of file DateTime.h.
uchar KKU::TimeType::Minute () const inline
Definition at line 173 of file DateTime.h.
Referenced by KKU::DateTime::AddMinutes(), PicesInterface::PicesMethods::DateTimeKKUtoSystem(), KKU::DateTime::HH_MM_SS(), KKU::operator<<(), and PicesInterface::PicesMethods::TimeTypeKKUtoSystem().
void KKU::TimeType::Minute (uchar _minute) inline
Definition at line 181 of file DateTime.h.
bool TimeType::operator!= (const TimeType & right) const
Definition at line 902 of file DateTime.cpp.
TimeType TimeType::operator+ (const TimeType & right) const
Add one day.
Definition at line 951 of file DateTime.cpp.
References Seconds(), and TimeType().
TimeType TimeType::operator- (const TimeType & right) const
Subtract one day.
Definition at line 958 of file DateTime.cpp.
References Seconds(), and TimeType().
bool TimeType::operator< (const TimeType & right) const
Definition at line 924 of file DateTime.cpp.
bool TimeType::operator<= (const TimeType & right) const
Definition at line 966 of file DateTime.cpp.
TimeType & TimeType::operator= (const TimeType & right)
Definition at line 884 of file DateTime.cpp.
bool TimeType::operator== (const TimeType & right) const
Definition at line 895 of file DateTime.cpp.
bool TimeType::operator> (const TimeType & right) const
Definition at line 910 of file DateTime.cpp.
bool TimeType::operator>= (const TimeType & right) const
Definition at line 917 of file DateTime.cpp.
uchar KKU::TimeType::Second () const inline
Definition at line 174 of file DateTime.h.
Referenced by KKU::DateTime::AddSeconds(), PicesInterface::PicesMethods::DateTimeKKUtoSystem(), KKU::DateTime::HH_MM_SS(), KKU::operator<<(), and PicesInterface::PicesMethods::TimeTypeKKUtoSystem().
void KKU::TimeType::Second (uchar _second) inline
Definition at line 182 of file DateTime.h.
KKU::uint32 TimeType::Seconds () const
Definition at line 930 of file DateTime.cpp.
Referenced by operator+(), KKU::DateTime::operator+(), operator-(), KKU::DateTime::operator-(), KKU::DateTime::Seconds(), and KKU::DateTime::ToSeconds().
double TimeType::ToHours () const
Definition at line 936 of file DateTime.cpp.
Referenced by KKU::DateTime::ToHours().
double TimeType::ToMinutes () const
Definition at line 942 of file DateTime.cpp.
Friends And Related Function Documentation
friend class DateTime friend
Definition at line 199 of file DateTime.h.
The documentation for this class was generated from the following files:
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/DateTime.h
D:/Users/kkramer/IEC/SipperSoftware/BaseLibrary/DateTime.cpp