Pices: SipperFile.Sipper3File Class Reference
SipperFile.Sipper3File Class Reference
Public Member Functions
Sipper3File (string _fileName, InstrumentDataManager _instrumentDataManager)
Sipper3File (Stream _stream, InstrumentDataManager _instrumentDataManager)
override void Dispose ()
override int LengthNextScanLine ()
override void ReadNextScanLine (byte[] scanLine)
void SaveRawCtdData (StreamWriter sw, PicesMsgQueue msgQueue, ref bool successful)
override void SkipNextScanLine ()
Public Member Functions inherited from SipperFile.SipperBaseFile
SipperBaseFile (Stream _stream, InstrumentDataManager _instrumentDataManager)
SipperBaseFile (string _fileName, InstrumentDataManager _instrumentDataManager)
byte[][] AllocateFrame ()
byte[][] CreateRatser (int scanLineStart, int numScanLines)
bool Eof ()
bool EofReached ()
virtual long EstimatedNumberOfScanLines ()
long FileSizeInBytes ()
void FrameBytesOffsetsUpdateThreadStart (InstrumentDataList _history)
void FrameBytesOffsetsUpdateThreadTerminate ()
void FrameRead (int frameNum, SipperFrame frame, ref bool found)
int LargestKnowmFrameNum ()
long LargestKnownScanLine ()
void ReadNextFrame (byte[][] frame)
virtual int ScanLineSize ()
bool ValidateFormat ()
Additional Inherited Members
Public Attributes inherited from SipperFile.SipperBaseFile
const int PixelsPerScanLine = 4096
const int ScanLinesPerFrame = 4096
Protected Member Functions inherited from SipperFile.SipperBaseFile
byte[] GetNextBuff (uint buffLen)
byte GetNextByte ()
ushort GetNextRecord ()
uint GetNextUint ()
Protected Attributes inherited from SipperFile.SipperBaseFile
bool eof = false
InstrumentDataManager instrumentDataManager = null
long lastScanLineNum = 0
Detailed Description
Definition at line 13 of file Sipper3File.cs.
Constructor & Destructor Documentation
SipperFile.Sipper3File.Sipper3File (string _fileName, InstrumentDataManager _instrumentDataManager) inline
Definition at line 19 of file Sipper3File.cs.
SipperFile.Sipper3File.Sipper3File (Stream _stream, InstrumentDataManager _instrumentDataManager) inline
Definition at line 29 of file Sipper3File.cs.
Member Function Documentation
override void SipperFile.Sipper3File.Dispose () inline virtual
Reimplemented from SipperFile.SipperBaseFile.
Definition at line 41 of file Sipper3File.cs.
override int SipperFile.Sipper3File.LengthNextScanLine () inline virtual
Reimplemented from SipperFile.SipperBaseFile.
Definition at line 59 of file Sipper3File.cs.
References SipperFile.SipperBaseFile.eof, SipperFile.Sipper3DecodeRec.Eol(), SipperFile.SipperBaseFile.GetNextRecord(), SipperFile.Sipper3DecodeRec.ImageData(), and SipperFile.Sipper3DecodeRec.PixelSpaceNeeded().
override void SipperFile.Sipper3File.ReadNextScanLine (byte[] scanLine) inline virtual
Reimplemented from SipperFile.SipperBaseFile.
Definition at line 122 of file Sipper3File.cs.
References SipperFile.Sipper3DecodeRec.AddToScanLine(), SipperFile.SipperBaseFile.eof, SipperFile.Sipper3DecodeRec.Eol(), SipperFile.SipperBaseFile.GetNextRecord(), SipperFile.Sipper3DecodeRec.GrayScale(), SipperFile.Sipper3DecodeRec.ImageData(), SipperFile.SipperBaseFile.instrumentDataManager, SipperFile.SipperBaseFile.lastScanLineNum, and SipperFile.InstrumentDataManager.ReportData().
void SipperFile.Sipper3File.SaveRawCtdData (StreamWriter sw, PicesMsgQueue msgQueue, ref bool successful) inline
Definition at line 183 of file Sipper3File.cs.
References PicesInterface::PicesMsgQueue.AddMsg(), SipperFile.SipperBaseFile.eof, SipperFile.SipperBaseFile.GetNextRecord(), SipperFile.Sipper3DecodeRec.ImageData(), SipperFile.Sipper3DecodeRec.SensorData(), SipperFile.Sipper3DecodeRec.SensorNum(), and SipperFile.Sipper3DecodeRec.Text().
override void SipperFile.Sipper3File.SkipNextScanLine () inline virtual
Reimplemented from SipperFile.SipperBaseFile.
Definition at line 93 of file Sipper3File.cs.
References SipperFile.SipperBaseFile.eof, SipperFile.Sipper3DecodeRec.Eol(), SipperFile.SipperBaseFile.GetNextRecord(), SipperFile.Sipper3DecodeRec.ImageData(), SipperFile.SipperBaseFile.instrumentDataManager, SipperFile.SipperBaseFile.lastScanLineNum, and SipperFile.InstrumentDataManager.ReportData().
The documentation for this class was generated from the following file:
D:/Users/kkramer/IEC/SipperSoftware/Apps/SipperFile/Sipper3File.cs