Pices: SipperHardware Namespace Reference
SipperHardware Namespace Reference
Contains Classes that are specific to SIPPER's physical characteristics such as Instrument Data.
Classes
class CTD_Plus_Data
class GPSDataPoint
class GPSDataPointList
class Instrument
class InstrumentBatteryMeters
class InstrumentCTD
class InstrumentData
class InstrumentDataBatteryMeter
class InstrumentDataCTDplus
class InstrumentDataFileManager
class InstrumentDataFlowMeter1
class InstrumentDataGPS
class InstrumentDataList
class InstrumentDataManager
data supplied by SipperBuff classes forwarding to appropriate 'InstrumentDataReport' derived objects.
class InstrumentDataMeans
class InstrumentDataMeansList
class InstrumentDataPitchAndRoll
class InstrumentDataReport
class InstrumentDataUserMsgs
class InstrumentGPS
class InstrumentInclinationMeter
class InstrumentOther
class PortAssignment
struct Sipper3BitRec
class Sipper3Buff
struct Sipper3Rec
class Sipper3RevBuff
struct SipperBinaryRec
class SipperBuff
to be used for all the different Sipper File Formats.
class SipperBuff3Bit
class SipperBuff4Bit
Implements the KKLSC (Kurt Kramer Line-Scanner 4biit format).
class SipperBuffBinary
class SipperCruise
class SipperCruiseList
class SipperDeployment
class SipperDeploymentList
class SipperFile
class SipperFileList
class SipperFileOracle
Will maintain a global list of all sipper files encountered.
class SipperHeaderRec
class SipperStation
class SipperStationList
class SipperVariables
Variables that specify where we can locate SIPPER and PICES directories and files are grouped here.
class VolumeSampledStat
class VolumeSampledStatList
Typedefs
typedef
GPSDataPointList::GPSDataPointListPtr GPSDataPointListPtr
typedef
GPSDataPoint::GPSDataPointPtr GPSDataPointPtr
typedef
InstrumentDataBatteryMeter::InstrumentDataBatteryMeterPtr InstrumentDataBatteryMeterPtr
typedef InstrumentDataCTDplus * InstrumentDataCTDplusPtr
typedef InstrumentDataFlowMeter1 * InstrumentDataFlowMeter1Ptr
typedef InstrumentDataList * InstrumentDataListPtr
typedef InstrumentDataManager * InstrumentDataManagerPtr
typedef InstrumentDataMeansList * InstrumentDataMeansListPtr
typedef InstrumentDataMeans * InstrumentDataMeansPtr
typedef
InstrumentDataPitchAndRoll::InstrumentDataPitchAndRollPtr InstrumentDataPitchAndRollPtr
typedef InstrumentData * InstrumentDataPtr
typedef InstrumentDataReport * InstrumentDataReportPtr
typedef InstrumentDataGPS * InstrumentDataSerialPort0Ptr
typedef
InstrumentDataUserMsgs::InstrumentDataUserMsgsPtr InstrumentDataUserMsgsPtr
typedef Instrument::InstrumentPtr InstrumentPtr
typedef vector< PortAssignmentPtr > PortAssignmentList
typedef
PortAssignment::PortAssignmentPtr PortAssignmentPtr
typedef Sipper3BitRec * Sipper3BitRecPtr
typedef Sipper3Buff::Sipper3BuffPtr Sipper3BuffPtr
typedef Sipper3Rec * Sipper3RecPtr
typedef Sipper3RevBuff * Sipper3RevBuffPtr
typedef SipperBinaryRec * SipperBinaryRecPtr
typedef SipperBuff3Bit * SipperBuff3BitPtr
typedef
SipperBuff4Bit::SipperBuff4BitPtr SipperBuff4BitPtr
typedef SipperBuffBinary * SipperBuffBinaryPtr
typedef SipperBuff::SipperBuffPtr SipperBuffPtr
typedef
SipperCruiseList::SipperCruiseListPtr SipperCruiseListPtr
typedef
SipperCruise::SipperCruisePtr SipperCruisePtr
typedef
SipperDeploymentList::SipperDeploymentListPtr SipperDeploymentListPtr
typedef
SipperDeployment::SipperDeploymentPtr SipperDeploymentPtr
typedef SipperFileList * SipperFileListPtr
typedef SipperFile * SipperFilePtr
typedef SipperHeaderRec * SipperHeaderRecPtr
typedef
SipperStationList::SipperStationListPtr SipperStationListPtr
typedef
SipperStation::SipperStationPtr SipperStationPtr
typedef
VolumeSampledStatList::VolumeSampledStatListPtr VolumeSampledStatListPtr
typedef
VolumeSampledStat::VolumeSampledStatPtr VolumeSampledStatPtr
Enumerations
enum SipperFileFormat {
sfBinary, sf3Bit, sfSipper3, sfSipper3Rev,
sfSipper4Bit, sfUnKnown
}
Functions
KKStr SipperFileAvailableOptions ()
SipperFileFormat SipperFileFormatFromStr (KKStr fileFormatStr)
KKStr SipperFileFormatToStr (SipperFileFormat fileFormat)
Detailed Description
Contains Classes that are specific to SIPPER's physical characteristics such as Instrument Data.
Classes that represent Instruments, SIPPER File Formats, Cruises, Stations, and Deployments are grouped here. The PICES software installation specifics are also dealt within this namespace.
Typedef Documentation
typedef GPSDataPointList::GPSDataPointListPtr SipperHardware::GPSDataPointListPtr
Definition at line 84 of file GPSDataPoint.h.
typedef GPSDataPoint::GPSDataPointPtr SipperHardware::GPSDataPointPtr
Definition at line 65 of file GPSDataPoint.h.
typedef InstrumentDataBatteryMeter::InstrumentDataBatteryMeterPtr SipperHardware::InstrumentDataBatteryMeterPtr
Definition at line 43 of file InstrumentDataBatteryMeter.h.
typedef InstrumentDataCTDplus * SipperHardware::InstrumentDataCTDplusPtr
Definition at line 11 of file InstrumentDataCTDplus.h.
typedef InstrumentDataFlowMeter1 * SipperHardware::InstrumentDataFlowMeter1Ptr
Definition at line 11 of file InstrumentDataFlowMeter1.h.
typedef InstrumentDataList::InstrumentDataListPtr SipperHardware::InstrumentDataListPtr
Definition at line 74 of file InstrumentDataFileManager.h.
typedef InstrumentDataManager * SipperHardware::InstrumentDataManagerPtr
Definition at line 19 of file Instrument.h.
typedef InstrumentDataMeansList* SipperHardware::InstrumentDataMeansListPtr
Definition at line 71 of file InstrumentDataMeans.h.
typedef InstrumentDataMeans* SipperHardware::InstrumentDataMeansPtr
Definition at line 57 of file InstrumentDataMeans.h.
typedef InstrumentDataPitchAndRoll::InstrumentDataPitchAndRollPtr SipperHardware::InstrumentDataPitchAndRollPtr
Definition at line 45 of file InstrumentDataPitchAndRoll.h.
typedef InstrumentData * SipperHardware::InstrumentDataPtr
Definition at line 267 of file InstrumentData.h.
typedef InstrumentDataReport::InstrumentDataReportPtr SipperHardware::InstrumentDataReportPtr
Definition at line 13 of file Instrument.h.
typedef InstrumentDataGPS * SipperHardware::InstrumentDataSerialPort0Ptr
Definition at line 13 of file InstrumentDataGPS.h.
typedef InstrumentDataUserMsgs::InstrumentDataUserMsgsPtr SipperHardware::InstrumentDataUserMsgsPtr
Definition at line 40 of file InstrumentDataUserMsgs.h.
typedef Instrument::InstrumentPtr SipperHardware::InstrumentPtr
Definition at line 70 of file Instrument.h.
typedef vector<PortAssignmentPtr> SipperHardware::PortAssignmentList
Definition at line 51 of file SipperHeaderRec.h.
typedef PortAssignment::PortAssignmentPtr SipperHardware::PortAssignmentPtr
Definition at line 48 of file SipperHeaderRec.h.
typedef Sipper3BitRec* SipperHardware::Sipper3BitRecPtr
Definition at line 77 of file SipperBuff3Bit.h.
typedef Sipper3Buff::Sipper3BuffPtr SipperHardware::Sipper3BuffPtr
Definition at line 186 of file Sipper3Buff.h.
typedef Sipper3Rec* SipperHardware::Sipper3RecPtr
Definition at line 106 of file Sipper3Buff.h.
typedef Sipper3RevBuff* SipperHardware::Sipper3RevBuffPtr
Definition at line 72 of file Sipper3RevBuff.h.
typedef SipperBinaryRec* SipperHardware::SipperBinaryRecPtr
Definition at line 80 of file SipperBuffBinary.h.
typedef SipperBuff3Bit* SipperHardware::SipperBuff3BitPtr
Definition at line 133 of file SipperBuff3Bit.h.
typedef SipperBuff4Bit::SipperBuff4BitPtr SipperHardware::SipperBuff4BitPtr
Definition at line 260 of file SipperBuff4Bit.h.
typedef SipperBuffBinary* SipperHardware::SipperBuffBinaryPtr
Definition at line 147 of file SipperBuffBinary.h.
typedef SipperBuff::SipperBuffPtr SipperHardware::SipperBuffPtr
Definition at line 189 of file SipperBuff.h.
typedef SipperCruiseList::SipperCruiseListPtr SipperHardware::SipperCruiseListPtr
Definition at line 78 of file SipperCruise.h.
typedef SipperCruise::SipperCruisePtr SipperHardware::SipperCruisePtr
Definition at line 59 of file SipperCruise.h.
typedef SipperDeploymentList::SipperDeploymentListPtr SipperHardware::SipperDeploymentListPtr
Definition at line 80 of file SipperDeployment.h.
typedef SipperDeployment::SipperDeploymentPtr SipperHardware::SipperDeploymentPtr
Definition at line 65 of file SipperDeployment.h.
typedef SipperFileList::SipperFileListPtr SipperHardware::SipperFileListPtr
Definition at line 87 of file InstrumentDataFileManager.h.
typedef SipperFile::SipperFilePtr SipperHardware::SipperFilePtr
Definition at line 85 of file InstrumentDataFileManager.h.
typedef SipperHeaderRec::SipperHeaderRecPtr SipperHardware::SipperHeaderRecPtr
Definition at line 40 of file InstrumentDataManager.h.
typedef SipperStationList::SipperStationListPtr SipperHardware::SipperStationListPtr
Definition at line 57 of file SipperStation.h.
typedef SipperStation::SipperStationPtr SipperHardware::SipperStationPtr
Definition at line 42 of file SipperStation.h.
typedef VolumeSampledStatList::VolumeSampledStatListPtr SipperHardware::VolumeSampledStatListPtr
Definition at line 83 of file VolumeSampledStat.h.
typedef VolumeSampledStat::VolumeSampledStatPtr SipperHardware::VolumeSampledStatPtr
Definition at line 54 of file VolumeSampledStat.h.
Enumeration Type Documentation
enum SipperHardware::SipperFileFormat
Enumerator
sfBinary
sf3Bit
sfSipper3
sfSipper3Rev
sfSipper4Bit
sfUnKnown
Definition at line 50 of file SipperBuff.h.
Function Documentation
KKStr SipperHardware::SipperFileAvailableOptions ()
Definition at line 740 of file SipperBuff.cpp.
SipperFileFormat SipperHardware::SipperFileFormatFromStr (KKStr fileFormatStr)
Definition at line 716 of file SipperBuff.cpp.
References KKU::KKStr::EqualIgnoreCase(), sf3Bit, sfBinary, sfSipper3, sfSipper3Rev, sfSipper4Bit, sfUnKnown, and KKU::KKStr::Upper().
Referenced by ImageExtractionManager::ExtractionParms::ParseCmdLine().
KKStr SipperHardware::SipperFileFormatToStr (SipperFileFormat fileFormat)
Definition at line 694 of file SipperBuff.cpp.
References sf3Bit, sfBinary, sfSipper3, sfSipper3Rev, and sfSipper4Bit.
Referenced by ImageExtractionManager::ExtractionParms::CmdLine().