Pices: PicesCommander.SaveImagesToDisk2 Class Reference
PicesCommander.SaveImagesToDisk2 Class Reference
Public Member Functions
SaveImagesToDisk2 (PicesDataBase _dbConn, PicesDataBaseImageList _images, PicesDataBaseImageGroup _group, String _cruise, String _station, String _deployment, String _sipperFileName, PicesClass _mlClass, char _classKeyToUse, float _probMin, float _probMax, int _sizeMin, int _sizeMax, float _depthMin, float _depthMax)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Detailed Description
Definition at line 15 of file SaveImagesToDisk2.cs.
Constructor & Destructor Documentation
PicesCommander.SaveImagesToDisk2.SaveImagesToDisk2 (PicesDataBase _dbConn, PicesDataBaseImageList _images, PicesDataBaseImageGroup _group, String _cruise, String _station, String _deployment, String _sipperFileName, PicesClass _mlClass, char _classKeyToUse, float _probMin, float _probMax, int _sizeMin, int _sizeMax, float _depthMin, float _depthMax) inline
Definition at line 62 of file SaveImagesToDisk2.cs.
References PicesInterface::OSservices.AddSlash(), PicesInterface::PicesDataBaseImage.Class1Name, PicesInterface::PicesClassStatistic.Count, PicesInterface::OSservices.CreateDirectoryPath(), PicesInterface::PicesSipperFile.CruiseName, PicesInterface::PicesSipperFile.DeploymentNum, PicesInterface::PicesDataBaseImage.Depth, PicesCommander.PlanktonClassStatisticsLoader.DoneLoading, PicesInterface::OSservices.GetParentDirectoryOfDirPath(), PicesCommander.PlanktonClassStatisticsLoader.GetStatsAlreadyLoaded(), PicesInterface::PicesSipperVariables.HomeDir(), PicesInterface::PicesDataBaseImage.ImageFileName, PicesInterface::PicesDataBase.ImageFullSizeFind(), PicesInterface::PicesDataBase.ImagesQuery(), PicesInterface::PicesDataBase.ImagesQueryByGrouop(), PicesInterface::PicesDataBaseImageGroup.Name, PicesInterface::PicesRaster.Save(), PicesInterface::PicesDataBase.SipperFileLoad(), PicesInterface::PicesSipperFile.SipperFileName, PicesInterface::PicesDataBase.SipperFileRecLoad(), PicesInterface::PicesDataBaseImageList.Sort(), PicesInterface::PicesSipperFile.StationName, PicesInterface::PicesKKStr.StrToInt(), PicesInterface::PicesDataBase.ThreadEnd(), PicesInterface::PicesDataBase.ThreadInit(), and PicesInterface::PicesDataBaseImage.ValidatedClassName.
Member Function Documentation
override void PicesCommander.SaveImagesToDisk2.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file SaveImagesToDisk2.Designer.cs.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/SaveImagesToDisk2.cs
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/SaveImagesToDisk2.Designer.cs