Pices: MLL::PicesFVProducerFactory Class Reference
MLL::PicesFVProducerFactory Class Reference
#include <PicesFVProducer.h>
Public Member Functions
virtual FeatureFileIOPtr DefaultFeatureFileIO () const
virtual const type_info * FeatureVectorListTypeId () const
Returns the 'type_info' of the FeatureVectorList that this instance of 'FactoryFVProducer' will create.
virtual const type_info * FeatureVectorTypeId () const
Returns the 'type_info' of the FeatureVector that this instance of 'FactoryFVProducer' works with.
virtual FileDescPtr FileDesc () const
virtual PicesFVProducerPtr ManufactureInstance (RunLog &runLog)
virtual ImageFeaturesListPtr ManufacturFeatureVectorList (bool owner, RunLog &runLog)
Manufactures a instance of a 'ImageFeaturesList' class that will own its contents.
virtual TrainingConfiguration2Ptr ManufacturTrainingConfiguration ()
Returns a 'TrainingConfiguration2' derived instance.
Public Member Functions inherited from KKMLL::FactoryFVProducer
FactoryFVProducer (const KKStr &_name, const KKStr &_fvClassName, const KKStr &_description)
const KKStr & Description () const
const KKStr & FvClassName () const
virtual FeatureVectorProducerPtr ManufactureInstance (RunLog &runLog)=0
Derived classes will instantiate appropriate instances of 'FeatureVectorProducer'.
virtual FeatureVectorPtr ManufacturFeatureVector (kkint32 numOfFeatires, RunLog &runLog)
Manufactures a instance of a derived 'FeatureVector' class that is appropriate for containing instances of FeatureVectors produced by the associated FeatureVectorProducer.
virtual FeatureVectorListPtr ManufacturFeatureVectorList (bool owner, RunLog &runLog)
Manufactures a instance of a derived 'FeatureVectorList' class that is appropriate for containing instances of FeatureVectors produced by the associated FeatureVectorProducer.
const KKStr & Name () const
Static Public Member Functions
static PicesFVProducerFactory * Factory (RunLog *runLog)
Returns instance of "PicesFVProducerFactory" that is registered with "FactoryFVProducer::RegisterFactory".
Static Public Member Functions inherited from KKMLL::FactoryFVProducer
static FactoryFVProducerPtr LookUpFactory (const KKStr &name)
Returns pointer to existing instance of 'FactoryFVProducer' that was previously registered with 'name'.
static FeatureVectorProducerPtr ManufactureInstance (const KKStr &name, RunLog &runLog)
Will instantiate a new instance of the appropriate 'FeatureVectorProducer' class given the supplied name.
static void RegisterFactory (FactoryFVProducerPtr factory, RunLog *runLog)
This is where you register newly instantiated instances of 'FactoryFVProducer' derived classes.
Protected Member Functions
virtual ~PicesFVProducerFactory ()
A Factory can never be deleted until the application terminates; the atexit method will perform the deletes.
Protected Member Functions inherited from KKMLL::FactoryFVProducer
virtual ~FactoryFVProducer ()
A Factory can near be deleted until the application terminates; the atexit method will perform the deletes.
Additional Inherited Members
Public Types inherited from KKMLL::FactoryFVProducer
typedef FactoryFVProducer * FactoryFVProducerPtr
Detailed Description
Definition at line 76 of file PicesFVProducer.h.
Constructor & Destructor Documentation
PicesFVProducerFactory::~PicesFVProducerFactory () protected virtual
A Factory can never be deleted until the application terminates; the atexit method will perform the deletes.
Definition at line 197 of file PicesFVProducer.cpp.
Member Function Documentation
FeatureFileIOPtr PicesFVProducerFactory::DefaultFeatureFileIO () const virtual
Implements KKMLL::FactoryFVProducer.
Definition at line 203 of file PicesFVProducer.cpp.
References MLL::FeatureFileIOPices::Driver().
PicesFVProducerFactory * PicesFVProducerFactory::Factory (RunLog * runLog) static
Returns instance of "PicesFVProducerFactory" that is registered with "FactoryFVProducer::RegisterFactory".
If instance does not exist yet out will create an instance and register it.
Definition at line 260 of file PicesFVProducer.cpp.
Referenced by MLL::PicesTrainingConfiguration::DefaultFeatureVectorProducer(), and MLL::PicesApplication::PicesApplication().
const type_info * PicesFVProducerFactory::FeatureVectorListTypeId () const virtual
Returns the 'type_info' of the FeatureVectorList that this instance of 'FactoryFVProducer' will create.
Implements KKMLL::FactoryFVProducer.
Definition at line 216 of file PicesFVProducer.cpp.
const type_info * PicesFVProducerFactory::FeatureVectorTypeId () const virtual
Returns the 'type_info' of the FeatureVector that this instance of 'FactoryFVProducer' works with.
Implements KKMLL::FactoryFVProducer.
Definition at line 209 of file PicesFVProducer.cpp.
FileDescPtr PicesFVProducerFactory::FileDesc () const virtual
Implements KKMLL::FactoryFVProducer.
Definition at line 223 of file PicesFVProducer.cpp.
References MLL::PicesFVProducer::DefineFileDescStatic().
PicesFVProducerPtr PicesFVProducerFactory::ManufactureInstance (RunLog & runLog) virtual
Definition at line 230 of file PicesFVProducer.cpp.
ImageFeaturesListPtr PicesFVProducerFactory::ManufacturFeatureVectorList (bool owner, RunLog & runLog) virtual
Manufactures a instance of a 'ImageFeaturesList' class that will own its contents.
Definition at line 238 of file PicesFVProducer.cpp.
References MLL::PicesFVProducer::DefineFileDescStatic().
TrainingConfiguration2Ptr PicesFVProducerFactory::ManufacturTrainingConfiguration () virtual
Returns a 'TrainingConfiguration2' derived instance.
Reimplemented from KKMLL::FactoryFVProducer.
Definition at line 247 of file PicesFVProducer.cpp.
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/PicesFVProducer.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/PicesFVProducer.cpp