Pices: SipperFileViewer.SipperFileViewerParameters Class Reference
SipperFileViewer.SipperFileViewerParameters Class Reference
Public Member Functions
SipperFileViewerParameters (Panel _panel)
void AddUserSpecifiedBlob (int tlCol, int tlRow, int brCol, int brRow)
int BlobMinSize ()
void BlobMinSize (int _blobMinSize)
void ClearBobs ()
uint[] ColHistogram ()
void ComputeParameters ()
int CropColemnLeft ()
int CropColemnRight ()
long DisplayRowBot ()
int DisplayRowsToDisplay ()
long DisplayRowTop ()
void Dispose ()
bool ExtractBlobs ()
void ExtractBlobs (bool _extractBlobs)
byte[][] ExtractImageFromSipper (Blob blob, ref long firstScanLine, ref int colLeft)
void PaintAllBlobs ()
void PaintFromBuffer ()
void PaintTemporayRectangle (Color lineColor, int x1, int y1, int x2, int y2)
void PaintWholePanel ()
float Ratio ()
void ScrollRows2 (int numRows)
Blob SelectedBlob (int col, int row)
void SetCropColumnLeft (int _cropColumnLeft)
void SetCropColumnRight (int _cropColumnRight)
void SetDataBase (PicesDataBase _dbConn)
void SetNewDisplayRowTop (long _displayRowTop)
void SetSipperFile (SipperFileBuffered _sipperFile, PicesSipperFile _dbSipperFile, PicesDataBase _dbConn)
Static Public Member Functions
static bool PaintARow2 (Bitmap b, int row, byte[] rowData)
static bool ScrollUp (Bitmap b, int numRows)
Properties
bool Colorize [get, set]
Detailed Description
Definition at line 15 of file SipperFileViewerParameters.cs.
Constructor & Destructor Documentation
SipperFileViewer.SipperFileViewerParameters.SipperFileViewerParameters (Panel _panel) inline
Definition at line 87 of file SipperFileViewerParameters.cs.
References SipperFileViewer.SipperFileViewerParameters.ComputeParameters().
Member Function Documentation
void SipperFileViewer.SipperFileViewerParameters.AddUserSpecifiedBlob (int tlCol, int tlRow, int brCol, int brRow) inline
Definition at line 661 of file SipperFileViewerParameters.cs.
int SipperFileViewer.SipperFileViewerParameters.BlobMinSize () inline
Definition at line 62 of file SipperFileViewerParameters.cs.
void SipperFileViewer.SipperFileViewerParameters.BlobMinSize (int _blobMinSize) inline
Definition at line 70 of file SipperFileViewerParameters.cs.
void SipperFileViewer.SipperFileViewerParameters.ClearBobs () inline
Definition at line 523 of file SipperFileViewerParameters.cs.
References SipperFile.BlobList.Dispose().
Referenced by SipperFileViewer.SipperFileViewerParameters.PaintWholePanel().
uint [] SipperFileViewer.SipperFileViewerParameters.ColHistogram () inline
Definition at line 84 of file SipperFileViewerParameters.cs.
void SipperFileViewer.SipperFileViewerParameters.ComputeParameters () inline
Definition at line 220 of file SipperFileViewerParameters.cs.
References SipperFile.SipperBaseFile.PixelsPerScanLine, SipperFile.SipperFileBuffered.Ratio(), SipperFileViewer.SipperFileViewerParameters.SetNewDisplayRowTop(), and SipperFile.SipperFileBuffered.SetPixelsPerDisplayLine().
Referenced by SipperFileViewer.SipperFileViewerParameters.SetCropColumnLeft(), SipperFileViewer.SipperFileViewerParameters.SetCropColumnRight(), SipperFileViewer.SipperFileViewerParameters.SetSipperFile(), and SipperFileViewer.SipperFileViewerParameters.SipperFileViewerParameters().
int SipperFileViewer.SipperFileViewerParameters.CropColemnLeft () inline
Definition at line 63 of file SipperFileViewerParameters.cs.
int SipperFileViewer.SipperFileViewerParameters.CropColemnRight () inline
Definition at line 64 of file SipperFileViewerParameters.cs.
long SipperFileViewer.SipperFileViewerParameters.DisplayRowBot () inline
Definition at line 67 of file SipperFileViewerParameters.cs.
int SipperFileViewer.SipperFileViewerParameters.DisplayRowsToDisplay () inline
Definition at line 65 of file SipperFileViewerParameters.cs.
long SipperFileViewer.SipperFileViewerParameters.DisplayRowTop () inline
Definition at line 68 of file SipperFileViewerParameters.cs.
void SipperFileViewer.SipperFileViewerParameters.Dispose () inline
Definition at line 98 of file SipperFileViewerParameters.cs.
bool SipperFileViewer.SipperFileViewerParameters.ExtractBlobs () inline
Definition at line 66 of file SipperFileViewerParameters.cs.
void SipperFileViewer.SipperFileViewerParameters.ExtractBlobs (bool _extractBlobs) inline
Definition at line 71 of file SipperFileViewerParameters.cs.
byte [][] SipperFileViewer.SipperFileViewerParameters.ExtractImageFromSipper (Blob blob, ref long firstScanLine, ref int colLeft) inline
Definition at line 766 of file SipperFileViewerParameters.cs.
References SipperFile.Blob.ColLeft, SipperFile.Blob.ColRight, SipperFile.SipperFileBuffered.CropColLeft(), SipperFile.SipperFileBuffered.GetScanLines(), SipperFile.SipperFileBuffered.Ratio(), SipperFile.Blob.RowBot, SipperFile.Blob.RowTop, and SipperFile.SipperFileBuffered.ScanLineSize().
void SipperFileViewer.SipperFileViewerParameters.PaintAllBlobs () inline
Definition at line 705 of file SipperFileViewerParameters.cs.
static bool SipperFileViewer.SipperFileViewerParameters.PaintARow2 (Bitmap b, int row, byte[] rowData) inline static
Definition at line 391 of file SipperFileViewerParameters.cs.
void SipperFileViewer.SipperFileViewerParameters.PaintFromBuffer () inline
Definition at line 695 of file SipperFileViewerParameters.cs.
References SipperFileViewer.SipperFileViewerParameters.PaintWholePanel().
void SipperFileViewer.SipperFileViewerParameters.PaintTemporayRectangle (Color lineColor, int x1, int y1, int x2, int y2) inline
Definition at line 741 of file SipperFileViewerParameters.cs.
void SipperFileViewer.SipperFileViewerParameters.PaintWholePanel () inline
Definition at line 431 of file SipperFileViewerParameters.cs.
References SipperFileViewer.SipperFileViewerParameters.ClearBobs(), and SipperFile.SipperFileBuffered.GetDisplayRows().
Referenced by SipperFileViewer.SipperFileViewerParameters.PaintFromBuffer(), SipperFileViewer.SipperFileViewerParameters.SetCropColumnLeft(), and SipperFileViewer.SipperFileViewerParameters.SetCropColumnRight().
float SipperFileViewer.SipperFileViewerParameters.Ratio () inline
Definition at line 75 of file SipperFileViewerParameters.cs.
References SipperFile.SipperFileBuffered.Ratio().
void SipperFileViewer.SipperFileViewerParameters.ScrollRows2 (int numRows) inline
Definition at line 607 of file SipperFileViewerParameters.cs.
References SipperFile.Blob.Scroll(), SipperFileViewer.SipperFileViewerParameters.ScrollUp(), and SipperFileViewer.SipperFileViewerParameters.SetNewDisplayRowTop().
static bool SipperFileViewer.SipperFileViewerParameters.ScrollUp (Bitmap b, int numRows) inline static
Definition at line 561 of file SipperFileViewerParameters.cs.
Referenced by SipperFileViewer.SipperFileViewerParameters.ScrollRows2().
Blob SipperFileViewer.SipperFileViewerParameters.SelectedBlob (int col, int row) inline
Definition at line 676 of file SipperFileViewerParameters.cs.
References SipperFile.Blob.ColLeft, SipperFile.Blob.ColRight, SipperFile.Blob.RowBot, and SipperFile.Blob.RowTop.
void SipperFileViewer.SipperFileViewerParameters.SetCropColumnLeft (int _cropColumnLeft) inline
Definition at line 858 of file SipperFileViewerParameters.cs.
References SipperFileViewer.SipperFileViewerParameters.ComputeParameters(), SipperFileViewer.SipperFileViewerParameters.PaintWholePanel(), and SipperFile.SipperFileBuffered.PixelsPerDisLine().
void SipperFileViewer.SipperFileViewerParameters.SetCropColumnRight (int _cropColumnRight) inline
Definition at line 906 of file SipperFileViewerParameters.cs.
References SipperFileViewer.SipperFileViewerParameters.ComputeParameters(), SipperFileViewer.SipperFileViewerParameters.PaintWholePanel(), and SipperFile.SipperFileBuffered.PixelsPerDisLine().
void SipperFileViewer.SipperFileViewerParameters.SetDataBase (PicesDataBase _dbConn) inline
Definition at line 319 of file SipperFileViewerParameters.cs.
void SipperFileViewer.SipperFileViewerParameters.SetNewDisplayRowTop (long _displayRowTop) inline
Definition at line 271 of file SipperFileViewerParameters.cs.
Referenced by SipperFileViewer.SipperFileViewerParameters.ComputeParameters(), and SipperFileViewer.SipperFileViewerParameters.ScrollRows2().
void SipperFileViewer.SipperFileViewerParameters.SetSipperFile (SipperFileBuffered _sipperFile, PicesSipperFile _dbSipperFile, PicesDataBase _dbConn) inline
Definition at line 293 of file SipperFileViewerParameters.cs.
References SipperFileViewer.SipperFileViewerParameters.ComputeParameters(), SipperFile.SipperFileBuffered.CropColLeft(), and SipperFile.SipperFileBuffered.CropColRight().
Property Documentation
bool SipperFileViewer.SipperFileViewerParameters.Colorize get set
Definition at line 281 of file SipperFileViewerParameters.cs.
The documentation for this class was generated from the following file:
E:/Users/kkramer/ProgProjects/Pices/Apps/SipperFileViewer/SipperFileViewerParameters.cs