Pices: PicesInterface::OSservices Class Reference
PicesInterface::OSservices Class Reference
The Managed version of the OSServices methods defined in BaseLibrary.
#include <PicesOSservices.h>
Public Member Functions
OSservices ()
Static Public Member Functions
static String^ AddSlash (String^ s)
static bool CreateDirectory (String^ dirName)
static bool CreateDirectoryPath (String^ _pathName)
Will create the whole Directory Path, not just the final part of the path.
static bool DirectoryExists (String^ dirName)
static String^ GetFileExtension (String^ fullFileName)
static cli::array< String^ >^ GetListOfFiles (String^ dirPath, String^ fileSpec)
static String^ GetParentDirectoryOfDirPath (String^ path)
static String^ GetPathPartOfFile (String^ fullFileName)
static String^ GetRootName (String^ fileName)
static String^ GetRootNameOfDirectory (String^ path)
static String^ GetRootNameWithExtension (String^ fullFileName)
static long HexStrToLong (String^ argument)
summary> Look for a specified file in a subdirectory structure.
static System::DateTime KKuDateTimeToSystemDateTime (const KKB::DateTime &dateTime)
static String^ LookForFile (String^ fileName, String^ srcDir)
static String^ RemoveExtension (String^ fileName)
static void RenameFile (String^ oldFileName, String^ newFileName)
static KKB::DateTime SystemDateTimeToKKuDateTime (System::DateTime sytemDateTime)
Detailed Description
The Managed version of the OSServices methods defined in BaseLibrary.
remarks> This class is the managed equivelent to the functions defined in OSservices in BaseLibrary. In some cases we implement the code in the unmanaged world in others we encapsulate the Unmanaged call. /remarks>
Definition at line 26 of file PicesOSservices.h.
Constructor & Destructor Documentation
OSservices::OSservices (void)
Definition at line 32 of file PicesOSservices.cpp.
Member Function Documentation
String OSservices::AddSlash (String^ s) static
Definition at line 38 of file PicesOSservices.cpp.
Referenced by PicesInterface::TrainingModel2::AttachMsgQueueToRunLog(), PicesCommander.ChartAbundanceByDeployment::ChartAbundanceByDeployment(), PicesCommander.ChartAbundancePredictedAndValidated::ChartAbundancePredictedAndValidated(), PicesCommander.ChartDistribution::ChartDistribution(), PicesCommander.ChartGPS::ChartGPS(), PicesCommander.ChartGPSByStation::ChartGPSByStation(), PicesCommander.ChartHorizontalProfile::ChartHorizontalProfile(), PicesCommander.ChartSizeDistribution::ChartSizeDistribution(), PicesCommander.ClassDepthProfileChart::ClassDepthProfileChart(), PicesCommander.ClassificationStatus::ClassificationStatus(), PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets(), PicesInterface::PicesRunLog::CreateRunLog(), PicesInterface::PicesClass::DeleteFromDisk(), SipperFile.DepthPlot2::DepthPlot2(), SipperFile.DisplayPicesImages::DisplayPicesImages(), GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters(), SipperFile.DisplayPicesImages::GetThumbnailImageAbort(), SipperFile.ImageViewer::ImageViewer(), PicesCommander.ImportGroupAssignments::ImportGroupAssignments(), PicesCommander.ImportImagesIntoDeployment::ImportImagesIntoDeployment(), PicesCommander.InstrumentDataByDeploymentProfile::InstrumentDataByDeploymentProfile(), PicesInterface::TrainingModel2::LastRunLogTextLine(), GradeTrainingModel.ImageListDisplay::LoadImageGrid(), PicesCommander.PicesCommander::PicesCommander(), PicesCommander.ReconcileImagesToDataBase::ReconcileImagesToDataBase(), PicesInterface::Cruise::Save(), PicesInterface::PicesClass::Save(), PicesCommander.SaveActiveTrainingModelFeatureData::SaveActiveTrainingModelFeatureData(), PicesCommander.SaveFeatureData::SaveFeatureData(), PicesCommander.SaveImagesToDisk::SaveImagesToDisk(), PicesCommander.SaveImagesToDisk2::SaveImagesToDisk2(), PicesCommander.SavePlanktonData::SavePlanktonData(), SipperFile.SelectAPicesClass::SelectAPicesClass(), SipperFile.InstrumentDataList::StartNewDataFile(), GradeTrainingModel.ImageListDisplay::ThumbnailCallback(), PicesCommander.PicesCommander::ThumbnailDataGridView_CellContentDoubleClick(), SipperFile.TimePlot::TimePlot(), PicesCommander.TrainingModelCreateFromDirectory::TrainingModelCreateFromDirectory(), and PicesCommander.PicesCommander::UpdateLastClassesValidated().
bool OSservices::CreateDirectory (String^ dirName) static
Definition at line 61 of file PicesOSservices.cpp.
References KKB::osCreateDirectory(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by SipperFile.SipperConfigRec::SipperConfigRec(), SipperFile.InstrumentDataList::StartNewDataFile(), and SipperFile.TimePlot::TimePlot().
bool OSservices::CreateDirectoryPath (String^ _pathName) static
Will create the whole Directory Path, not just the final part of the path.
Definition at line 69 of file PicesOSservices.cpp.
References KKB::osCreateDirectoryPath(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by PicesInterface::TrainingModel2::AttachMsgQueueToRunLog(), PicesCommander.ClassificationStatus::ClassificationStatus(), PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets(), PicesInterface::PicesRunLog::CreateRunLog(), PicesCommander.InstrumentDataByDeploymentProfile::InstrumentDataByDeploymentProfile(), PicesCommander.ReconcileImagesToDataBase::ReconcileImagesToDataBase(), PicesInterface::Cruise::Save(), PicesCommander.SaveFeatureData::SaveFeatureData(), PicesCommander.SaveImagesToDisk::SaveImagesToDisk(), PicesCommander.SaveImagesToDisk2::SaveImagesToDisk2(), PicesCommander.SavePlanktonData::SavePlanktonData(), and PicesCommander.PicesCommander::ThumbnailDataGridView_CellContentDoubleClick().
bool OSservices::DirectoryExists (String^ dirName) static
Definition at line 52 of file PicesOSservices.cpp.
References KKB::osValidDirectory(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
String OSservices::GetFileExtension (String^ fullFileName) static
Definition at line 169 of file PicesOSservices.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr(), KKB::osGetFileExtension(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by PicesCommander.ChartSizeDistribution::ChartSizeDistribution(), PicesCommander.ImportGroupAssignments::ImportGroupAssignments(), PicesCommander.ImportImagesIntoDeployment::ImportImagesIntoDeployment(), PicesCommander.ImportValidatdClass::ImportValidatdClass(), PicesCommander.ReconcileImagesToDataBase::ReconcileImagesToDataBase(), PicesInterface::PicesRaster::Save(), and GradeTrainingModel.ConfusionMatrix::TallyPredictions().
array< String^ > OSservices::GetListOfFiles (String^ dirPath, String^ fileSpec) static
Definition at line 265 of file PicesOSservices.cpp.
String OSservices::GetParentDirectoryOfDirPath (String^ path) static
Definition at line 185 of file PicesOSservices.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr(), KKB::osGetParentDirectoryOfDirPath(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by PicesCommander.ImportGroupAssignments::ImportGroupAssignments(), PicesCommander.ImportImagesIntoDeployment::ImportImagesIntoDeployment(), PicesCommander.ImportValidatdClass::ImportValidatdClass(), PicesCommander.SaveImagesToDisk::SaveImagesToDisk(), and PicesCommander.SaveImagesToDisk2::SaveImagesToDisk2().
String OSservices::GetPathPartOfFile (String^ fullFileName) static
Definition at line 177 of file PicesOSservices.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr(), KKB::osGetPathPartOfFile(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by PicesCommander.ChartSizeDistribution::ChartSizeDistribution(), SipperFile.DisplayPicesImages::GetThumbnailImageAbort(), PicesCommander.ReconcileImagesToDataBase::ReconcileImagesToDataBase(), PicesCommander.SaveActiveTrainingModelFeatureData::SaveActiveTrainingModelFeatureData(), PicesCommander.SaveFeatureData::SaveFeatureData(), and PicesCommander.SavePlanktonData::SavePlanktonData().
String OSservices::GetRootName (String^ fileName) static
Definition at line 156 of file PicesOSservices.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr(), KKB::osGetRootName(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by PicesInterface::TrainingModel2::AttachMsgQueueToRunLog(), PicesCommander.ClassificationStatus::CleanUpMemory(), PicesInterface::PicesFeatureVectorList::FeatureVectorComparitorByImageFileName::Compare(), PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets(), SipperFile.DeploymentDialog::DeploymentDialog(), SipperFile.DisplayPicesImages::GetThumbnailImageAbort(), PicesCommander.ImportGroupAssignments::ImportGroupAssignments(), PicesCommander.ImportImagesIntoDeployment::ImportImagesIntoDeployment(), PicesCommander.ImportValidatdClass::ImportValidatdClass(), SipperFile.InstrumentDataReportCTD::InstrumentDataReportCTD(), PicesInterface::TrainingModel2::LastRunLogTextLine(), GradeTrainingModel.ImageListDisplay::LoadImageGrid(), PicesInterface::PicesFeatureVectorList::LookUpByImageFileName(), PicesCommander.PicesCommander::PicesCommander(), PicesCommander.ReconcileImagesToDataBase::ReconcileImagesToDataBase(), PicesCommander.SaveActiveTrainingModelFeatureData::SaveActiveTrainingModelFeatureData(), PicesCommander.SaveFeatureData::SaveFeatureData(), PicesCommander.SavePlanktonData::SavePlanktonData(), SipperFileViewer.SipperFileViewer::SipperFileViewerRegionAroundImage(), PicesCommander.ClassifierProcess::StartThread(), GradeTrainingModel.ConfusionMatrix::TallyPredictions(), GradeTrainingModel.ImageListDisplay::ThumbnailCallback(), PicesCommander.PicesCommander::ThumbnailDataGridView_CellContentDoubleClick(), and SipperFileViewer.SipperFileViewer::WndProc().
String OSservices::GetRootNameOfDirectory (String^ path) static
Definition at line 195 of file PicesOSservices.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr(), KKB::osGetRootNameOfDirectory(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by SipperFile.DisplayPicesImages::DisplayPicesImages(), SipperFile.DisplayPicesImages::GetThumbnailImageAbort(), PicesCommander.ReconcileImagesToDataBase::ReconcileImagesToDataBase(), and PicesCommander.TrainingModelCreateFromDirectory::TrainingModelCreateFromDirectory().
String OSservices::GetRootNameWithExtension (String^ fullFileName) static
Definition at line 162 of file PicesOSservices.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr(), KKB::osGetRootNameWithExtension(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by PicesCommander.ReconcileImagesToDataBase::ReconcileImagesToDataBase(), PicesCommander.SaveActiveTrainingModelFeatureData::SaveActiveTrainingModelFeatureData(), PicesCommander.SaveFeatureData::SaveFeatureData(), and PicesCommander.SavePlanktonData::SavePlanktonData().
long OSservices::HexStrToLong (String^ argument) static
summary> Look for a specified file in a subdirectory structure.
param name='fileName'> Name of file we are looking for.
param name='srcDir'> Sub Directory tree we want to search.
returns> Full directory path to where first occurance of fileName is located; if not found will return back nullptr.
Definition at line 78 of file PicesOSservices.cpp.
Referenced by SipperDiskUtilities.ParseSipperLog::ParseSipperLog().
System::DateTime OSservices::KKuDateTimeToSystemDateTime (const KKB::DateTime & dateTime) static
Definition at line 221 of file PicesOSservices.cpp.
References KKB::DateTime::Date(), and KKB::DateTime::Time().
Referenced by PicesInterface::TrainingModel2::LastRunLogTextLine(), and PicesInterface::PicesKKStr::StrToDateTime().
String OSservices::LookForFile (String^ fileName, String^ srcDir) static
Definition at line 251 of file PicesOSservices.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr(), KKB::osLookForFile(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by SipperFile.DisplayPicesImages::GetThumbnailImageAbort(), GradeTrainingModel.ImageListDisplay::LoadImageGrid(), and GradeTrainingModel.ImageListDisplay::ThumbnailCallback().
String OSservices::RemoveExtension (String^ fileName) static
Definition at line 147 of file PicesOSservices.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr(), KKB::osRemoveExtension(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by PicesCommander.ChartSizeDistribution::ChartSizeDistribution(), PicesInterface::ClassificationBiasMatrix::ClassificationBiasMatrix(), SipperFile.SipperConfigRec::Save(), and SipperFile.SaveRawCTDData::SaveRawCTDData().
void OSservices::RenameFile (String^ oldFileName, String^ newFileName) static
Definition at line 103 of file PicesOSservices.cpp.
Referenced by PicesCommander.ReconcileImagesToDataBase::ReconcileImagesToDataBase(), and SipperFile.SipperConfigRec::Save().
KKB::DateTime OSservices::SystemDateTimeToKKuDateTime (System::DateTime sytemDateTime) static
Definition at line 208 of file PicesOSservices.cpp.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesOSservices.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesOSservices.cpp