Pices: PicesInterface::PicesFeatureFileIO Class Reference
PicesInterface::PicesFeatureFileIO Class Reference
#include <PicesFeatureFileIO.h>
Public Member Functions
PicesFeatureFileIO (String^ driverName)
PicesFeatureVectorList^ LoadFeatureFile (String^ _fileName, PicesClassList^ _classes, PicesRunLog^ _runLog)
void SaveFeatureFile (String^ _fileName, PicesFeatureVectorList^ _examples, PicesRunLog^ _runLog)
void SaveFeatureFileNormalized (String^ _fileName, PicesFeatureVectorList^ _examples, PicesRunLog^ _runLog)
Static Public Member Functions
static array< String^ >^ RegisteredDriverNames (bool canRead, bool canWrite)
Returns list of registered feature data file drivers; you will be able to filter for the drivers that you want using the two provided parameters.
static bool ValidDriverName (String^ _driverName)
Protected Member Functions
!PicesFeatureFileIO ()
Properties
bool CancelLoad [get, set]
bool CanRead [get]
bool CanWrite [get]
bool ChangesMade [get]
String^ DriverName [get]
uint NumExamplesWritten [get]
bool Successful [get]
bool Valid [get]
Detailed Description
Definition at line 6 of file PicesFeatureFileIO.h.
Constructor & Destructor Documentation
PicesInterface::PicesFeatureFileIO::PicesFeatureFileIO (String^ driverName)
Definition at line 45 of file PicesFeatureFileIO.cpp.
References PicesInterface::PicesKKStr::SystemStringToKKStr().
PicesInterface::PicesFeatureFileIO::!PicesFeatureFileIO () protected
Definition at line 77 of file PicesFeatureFileIO.cpp.
Member Function Documentation
PicesFeatureVectorList PicesInterface::PicesFeatureFileIO::LoadFeatureFile (String^ _fileName, PicesClassList^ _classes, PicesRunLog^ _runLog)
Definition at line 286 of file PicesFeatureFileIO.cpp.
References KKMLL::FeatureFileIO::CanWrite(), KKMLL::FeatureFileIO::DriverName(), PicesInterface::PicesKKStr::KKStrToSystenStr(), KKMLL::FeatureFileIO::LoadFeatureFile(), PicesInterface::PicesRunLog::Log(), KKB::KKQueue< Entry >::Owner(), PicesInterface::PicesKKStr::SystemStringToKKStr(), and PicesInterface::PicesRunLog::Writeln().
array< String^ > PicesInterface::PicesFeatureFileIO::RegisteredDriverNames (bool canRead, bool canWrite) static
Returns list of registered feature data file drivers; you will be able to filter for the drivers that you want using the two provided parameters.
Parameters
canRead Indicates in included drivers must be able to read a feature-data-file.
canWrite Indicates if driver can write a feature-data-file.
Definition at line 87 of file PicesFeatureFileIO.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr().
Referenced by PicesCommander.SaveActiveTrainingModelFeatureData::SaveActiveTrainingModelFeatureData(), and PicesCommander.SaveFeatureData::SaveFeatureData().
void PicesInterface::PicesFeatureFileIO::SaveFeatureFile (String^ _fileName, PicesFeatureVectorList^ _examples, PicesRunLog^ _runLog)
Definition at line 205 of file PicesFeatureFileIO.cpp.
References KKMLL::FeatureVectorList::AllFeatures(), KKMLL::FeatureFileIO::CanWrite(), KKMLL::FeatureFileIO::DriverName(), PicesInterface::PicesKKStr::KKStrToSystenStr(), PicesInterface::PicesRunLog::Log(), KKMLL::FeatureFileIO::SaveFeatureFile(), PicesInterface::PicesKKStr::SystemStringToKKStr(), PicesInterface::PicesFeatureVectorList::ToFeatureVectorList(), and PicesInterface::PicesRunLog::Writeln().
Referenced by PicesCommander.SaveFeatureData::SaveFeatureData().
void PicesInterface::PicesFeatureFileIO::SaveFeatureFileNormalized (String^ _fileName, PicesFeatureVectorList^ _examples, PicesRunLog^ _runLog)
Definition at line 241 of file PicesFeatureFileIO.cpp.
References KKMLL::FeatureVectorList::AllFeatures(), KKMLL::FeatureFileIO::CanWrite(), KKMLL::FeatureFileIO::DriverName(), PicesInterface::PicesKKStr::KKStrToSystenStr(), PicesInterface::PicesRunLog::Log(), KKMLL::NormalizationParms::NormalizeExamples(), KKB::osRemoveExtension(), KKMLL::FeatureFileIO::SaveFeatureFile(), PicesInterface::PicesKKStr::SystemStringToKKStr(), PicesInterface::PicesFeatureVectorList::ToFeatureVectorList(), and PicesInterface::PicesRunLog::Writeln().
Referenced by PicesCommander.SaveFeatureData::SaveFeatureData().
bool PicesInterface::PicesFeatureFileIO::ValidDriverName (String^ _driverName) static
Definition at line 108 of file PicesFeatureFileIO.cpp.
References KKMLL::FeatureFileIO::CanRead(), KKMLL::FeatureFileIO::CanWrite(), KKMLL::FeatureFileIO::DriverName(), PicesInterface::PicesKKStr::KKStrToSystenStr(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by PicesCommander.SaveActiveTrainingModelFeatureData::SaveActiveTrainingModelFeatureData(), and PicesCommander.SaveFeatureData::SaveFeatureData().
Property Documentation
bool PicesInterface::PicesFeatureFileIO::CancelLoad get set
Definition at line 28 of file PicesFeatureFileIO.h.
Referenced by PicesCommander.SaveFeatureData::SaveFeatureData(), and PicesCommander.SavePlanktonData::SavePlanktonData().
bool PicesInterface::PicesFeatureFileIO::CanRead get
Definition at line 29 of file PicesFeatureFileIO.h.
bool PicesInterface::PicesFeatureFileIO::CanWrite get
Definition at line 30 of file PicesFeatureFileIO.h.
Referenced by PicesCommander.SaveFeatureData::SaveFeatureData().
bool PicesInterface::PicesFeatureFileIO::ChangesMade get
Definition at line 31 of file PicesFeatureFileIO.h.
String^ PicesInterface::PicesFeatureFileIO::DriverName get
Definition at line 32 of file PicesFeatureFileIO.h.
uint PicesInterface::PicesFeatureFileIO::NumExamplesWritten get
Definition at line 33 of file PicesFeatureFileIO.h.
Referenced by PicesCommander.SaveFeatureData::SaveFeatureData().
bool PicesInterface::PicesFeatureFileIO::Successful get
Definition at line 34 of file PicesFeatureFileIO.h.
bool PicesInterface::PicesFeatureFileIO::Valid get
Definition at line 35 of file PicesFeatureFileIO.h.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesFeatureFileIO.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesFeatureFileIO.cpp