Pices: FeatureSelectionApp::FeatureSelection Class Reference
FeatureSelectionApp::FeatureSelection Class Reference
#include <FeatureSelection.h>
Public Types
typedef KKB::uint uint
Public Member Functions
FeatureSelection (int argc, char **argv)
~FeatureSelection ()
MLClassPtr AddingAClass () const
bool AlreadyNormalized () const
int BeamSize () const
void Block ()
void BuildResultConfigFile (const KKStr &prevConfigFileName, double &totalCpuTimeUsed, FeatureCriteriaType featureCriteria)
KKStr CommandLineStr ()
TrainingConfiguration2Ptr Config () const
const KKStr & ConfigFileName () const
void DisplayCommandUsage ()
void EndBlock ()
int ExpansionLimit () const
bool FeatureCountPrefSmall () const
FeatureCriteriaType FeatureCriteria () const
GradingMethodType GradingMethod () const
const KKStr & HostName () const
const FeatureNumList & InitialFeatures () const
bool JustGettingStats () const
void LoadFeatureData ()
RunLog & Log ()
MajorSteps MajorStep () const
int MinTrainExamples () const
MLClassListPtr MLClasses () const
int NextProcessorId () const
int NumJobsAtATime () const
int NumOfFolds () const
int NumProcPerCombo () const
JobSelectionCriteria ParamSelCriteria () const
MLClassPtr PositiveClass () const
void ProcessCmdLine (int argc, char **argv)
ProcessingOrders ProcessingOrder () const
void ProcessStatusFile (int argc, char **argv)
FeatureVectorListPtr RandomSplit (int splitNum)
int RandomSplitsNum () const
const KKStr & ResultConfigFileName () const
void Run ()
SearchTypes SearchType () const
FeatureVectorListPtr TestData () const
const KKStr & TestDataFileName () const
FeatureVectorListPtr TrainingData () const
const KKStr & TrainingDataFileName () const
FeatureVectorListPtr ValidationData ()
const KKStr & ValidationDataFileName () const
Detailed Description
Definition at line 100 of file FeatureSelection.h.
Member Typedef Documentation
typedef KKB::uint FeatureSelectionApp::FeatureSelection::uint
Definition at line 103 of file FeatureSelection.h.
Constructor & Destructor Documentation
FeatureSelection::FeatureSelection (int argc, char ** argv)
Definition at line 175 of file FeatureSelection.cpp.
References FeatureSelectionApp::Accuracy, FeatureSelectionApp::BestTestSet, KKB::endl(), KKB::RunLog::Level(), FeatureSelectionApp::MfsParmTuningPre, FeatureSelectionApp::MostAccurate, KKB::osGetCurrentDirectory(), KKB::osGetHostName(), KKB::osGetProcessId(), FeatureSelectionApp::ParameterSearch, ProcessStatusFile(), and FeatureSelectionApp::Standard.
FeatureSelection::~FeatureSelection ()
Definition at line 242 of file FeatureSelection.cpp.
Member Function Documentation
MLClassPtr FeatureSelectionApp::FeatureSelection::AddingAClass () const inline
Definition at line 112 of file FeatureSelection.h.
bool FeatureSelectionApp::FeatureSelection::AlreadyNormalized () const inline
Definition at line 113 of file FeatureSelection.h.
Referenced by FeatureSelectionApp::Processor::Processor().
int FeatureSelectionApp::FeatureSelection::BeamSize () const inline
Definition at line 114 of file FeatureSelection.h.
Referenced by FeatureSelectionApp::Processor::Processor().
void FeatureSelection::Block ()
Definition at line 460 of file FeatureSelection.cpp.
References KKB::endl(), KKB::RunLog::Level(), KKB::osSleep(), and KKB::KKStr::Str().
Referenced by ProcessStatusFile().
void FeatureSelection::BuildResultConfigFile (const KKStr & prevConfigFileName, double & totalCpuTimeUsed, FeatureCriteriaType featureCriteria)
Definition at line 3764 of file FeatureSelection.cpp.
References SVM233::svm_parameter::A, KKMLL::TrainingConfiguration2::A_Param(), FeatureSelectionApp::Processor::ByBinaryClasses(), SVM233::svm_parameter::C, KKMLL::TrainingConfiguration2::C_Param(), FeatureSelectionApp::BinaryClass::Class1(), FeatureSelectionApp::BinaryClass::Class2(), KKB::endl(), SVM233::svm_parameter::gamma, KKMLL::TrainingConfiguration2::Gamma(), FeatureSelectionApp::Processor::GetBestParametersFromTestResults(), KKMLL::TrainingConfiguration2::GetFeatureNums(), KKMLL::SVMparam::GetParamtersToUseFor2ClassCombo(), KKB::KKQueue< Entry >::IdxToPtr(), InitialFeatures(), KKB::RunLog::Level(), KKMLL::TrainingConfiguration2::Load(), KKMLL::TrainingConfiguration2::MachineType(), KKMLL::TrainingConfiguration2::ModelParameters(), KKMLL::ModelParam::ModelParamType(), KKMLL::FeatureVectorList::NumEntriesOfAGivenClass(), KKMLL::FeatureNumList::NumSelFeatures(), KKB::osWaitForEnter(), KKB::KKQueue< Entry >::QueueSize(), FeatureSelectionApp::BinaryClass::ResultType(), KKMLL::TrainingConfiguration2::Save(), FeatureSelectionApp::Processor::SelectBestFeatures(), KKMLL::TrainingConfiguration2::SetBinaryClassFields(), KKMLL::TrainingConfiguration2::SetFeatureNums(), and FeatureSelectionApp::Processor::TotalCpuTimeUsed().
KKStr FeatureSelectionApp::FeatureSelection::CommandLineStr ()
TrainingConfiguration2Ptr FeatureSelectionApp::FeatureSelection::Config () const inline
Definition at line 116 of file FeatureSelection.h.
Referenced by FeatureSelectionApp::Processor::Processor().
const KKStr& FeatureSelectionApp::FeatureSelection::ConfigFileName () const inline
Definition at line 115 of file FeatureSelection.h.
void FeatureSelection::DisplayCommandUsage ()
Definition at line 532 of file FeatureSelection.cpp.
References KKB::endl().
Referenced by ProcessCmdLine(), and ProcessStatusFile().
void FeatureSelection::EndBlock ()
Definition at line 484 of file FeatureSelection.cpp.
References KKB::endl(), KKB::RunLog::Level(), and KKB::KKStr::Str().
Referenced by LoadFeatureData(), ProcessCmdLine(), and ProcessStatusFile().
int FeatureSelectionApp::FeatureSelection::ExpansionLimit () const inline
Definition at line 117 of file FeatureSelection.h.
Referenced by FeatureSelectionApp::Processor::Processor().
bool FeatureSelectionApp::FeatureSelection::FeatureCountPrefSmall () const inline
Definition at line 119 of file FeatureSelection.h.
Referenced by FeatureSelectionApp::Processor::GetBestParametersFromTestResults(), FeatureSelectionApp::Processor::GetFeaturesFromTestResults(), and FeatureSelectionApp::Processor::MergeKBestFeatureSelections().
FeatureCriteriaType FeatureSelectionApp::FeatureSelection::FeatureCriteria () const inline
Definition at line 118 of file FeatureSelection.h.
Referenced by FeatureSelectionApp::Processor::SelectBestFeatures().
GradingMethodType FeatureSelectionApp::FeatureSelection::GradingMethod () const inline
Definition at line 120 of file FeatureSelection.h.
Referenced by FeatureSelectionApp::Processor::GradingMethod().
const KKStr& FeatureSelectionApp::FeatureSelection::HostName () const inline
Definition at line 123 of file FeatureSelection.h.
const FeatureNumList & FeatureSelection::InitialFeatures () const
Definition at line 344 of file FeatureSelection.cpp.
References KKB::endl(), and KKMLL::TrainingConfiguration2::GetFeatureNums().
Referenced by BuildResultConfigFile(), FeatureSelectionApp::Processor::InitialFeatures(), and FeatureSelectionApp::Processor::Processor().
bool FeatureSelectionApp::FeatureSelection::JustGettingStats () const inline
Definition at line 121 of file FeatureSelection.h.
Referenced by FeatureSelectionApp::Processor::Processor().
void FeatureSelection::LoadFeatureData ()
Definition at line 1686 of file FeatureSelection.cpp.
References KKMLL::FeatureVectorList::AddQueue(), KKB::KKStr::Empty(), EndBlock(), KKB::endl(), KKMLL::FeatureVectorList::FileDesc(), KKB::RunLog::Level(), KKMLL::FeatureFileIO::LoadFeatureFile(), KKB::osWaitForEnter(), and KKMLL::FeatureVectorList::StratifyAmoungstClasses().
RunLog& FeatureSelectionApp::FeatureSelection::Log () inline
Definition at line 122 of file FeatureSelection.h.
MajorSteps FeatureSelectionApp::FeatureSelection::MajorStep () const inline
Definition at line 126 of file FeatureSelection.h.
Referenced by FeatureSelectionApp::Processor::Processor().
int FeatureSelectionApp::FeatureSelection::MinTrainExamples () const inline
Definition at line 127 of file FeatureSelection.h.
MLClassListPtr FeatureSelectionApp::FeatureSelection::MLClasses () const inline
Definition at line 124 of file FeatureSelection.h.
Referenced by FeatureSelectionApp::Processor::Processor().
int FeatureSelectionApp::FeatureSelection::NextProcessorId () const inline
Definition at line 128 of file FeatureSelection.h.
int FeatureSelectionApp::FeatureSelection::NumJobsAtATime () const inline
Definition at line 129 of file FeatureSelection.h.
Referenced by FeatureSelectionApp::Processor::Processor().
int FeatureSelectionApp::FeatureSelection::NumOfFolds () const inline
Definition at line 131 of file FeatureSelection.h.
Referenced by FeatureSelectionApp::Processor::Processor().
int FeatureSelectionApp::FeatureSelection::NumProcPerCombo () const inline
Definition at line 130 of file FeatureSelection.h.
JobSelectionCriteria FeatureSelectionApp::FeatureSelection::ParamSelCriteria () const inline
Definition at line 132 of file FeatureSelection.h.
Referenced by FeatureSelectionApp::Processor::GetBestParametersFromTestResults().
MLClassPtr FeatureSelectionApp::FeatureSelection::PositiveClass () const inline
Definition at line 133 of file FeatureSelection.h.
Referenced by FeatureSelectionApp::Processor::PositiveClass().
void FeatureSelection::ProcessCmdLine (int argc, char ** argv)
Definition at line 950 of file FeatureSelection.cpp.
References DisplayCommandUsage(), KKB::KKStr::Empty(), EndBlock(), KKB::endl(), KKB::KKStr::EqualIgnoreCase(), FeatureSelectionApp::FeatureCriteriaFromStr(), FeatureSelectionApp::GradingMethodFromStr(), FeatureSelectionApp::JobSelectionCriteriaFromStr(), KKB::RunLog::Level(), KKB::osFileExists(), KKB::osWaitForEnter(), FeatureSelectionApp::ProcessingOrderFromStr(), FeatureSelectionApp::SearchTypeFromStr(), KKB::KKStr::Str(), KKB::KKStr::ToBool(), KKB::KKStr::ToInt(), and KKB::KKStr::Upper().
ProcessingOrders FeatureSelectionApp::FeatureSelection::ProcessingOrder () const inline
Definition at line 134 of file FeatureSelection.h.
Referenced by FeatureSelectionApp::Processor::Processor().
void FeatureSelection::ProcessStatusFile (int argc, char ** argv)
Definition at line 2501 of file FeatureSelection.cpp.
References AllBinaryClassesAreDone(), Block(), DisplayCommandUsage(), EndBlock(), KKB::endl(), KKB::KKStr::EqualIgnoreCase(), KKB::RunLog::Level(), KKB::osFOPEN(), KKB::osRemoveExtension(), KKB::KKStr::Str(), and KKB::KKStr::Upper().
Referenced by FeatureSelection().
FeatureVectorListPtr FeatureSelection::RandomSplit (int splitNum)
Definition at line 313 of file FeatureSelection.cpp.
References KKB::endl(), KKB::RunLog::Level(), and KKMLL::Orderings::Ordering().
Referenced by FeatureSelectionApp::Processor::RandomSplit().
int FeatureSelectionApp::FeatureSelection::RandomSplitsNum () const inline
Definition at line 135 of file FeatureSelection.h.
const KKStr& FeatureSelectionApp::FeatureSelection::ResultConfigFileName () const inline
Definition at line 171 of file FeatureSelection.h.
void FeatureSelection::Run ()
Definition at line 3712 of file FeatureSelection.cpp.
References KKB::endl(), KKB::RunLog::Level(), FeatureSelectionApp::MajorStepToStr(), FeatureSelectionApp::Processor::Run(), and FeatureSelectionApp::Processor::Status().
Referenced by main().
SearchTypes FeatureSelectionApp::FeatureSelection::SearchType () const inline
Definition at line 136 of file FeatureSelection.h.
Referenced by FeatureSelectionApp::Processor::SelectBestFeatures().
FeatureVectorListPtr FeatureSelectionApp::FeatureSelection::TestData () const inline
Definition at line 137 of file FeatureSelection.h.
Referenced by FeatureSelectionApp::Processor::Processor(), and FeatureSelectionApp::Processor::TestData().
const KKStr& FeatureSelectionApp::FeatureSelection::TestDataFileName () const inline
Definition at line 138 of file FeatureSelection.h.
FeatureVectorListPtr FeatureSelectionApp::FeatureSelection::TrainingData () const inline
Definition at line 139 of file FeatureSelection.h.
Referenced by FeatureSelectionApp::Processor::Processor().
const KKStr& FeatureSelectionApp::FeatureSelection::TrainingDataFileName () const inline
Definition at line 140 of file FeatureSelection.h.
FeatureVectorListPtr FeatureSelection::ValidationData ()
Definition at line 263 of file FeatureSelection.cpp.
Referenced by FeatureSelectionApp::Processor::ValidationData().
const KKStr& FeatureSelectionApp::FeatureSelection::ValidationDataFileName () const inline
Definition at line 141 of file FeatureSelection.h.
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/Apps/FeatureSelection/FeatureSelection.h
C:/Users/kurtk_000/GitHub/Pices/Apps/FeatureSelection/FeatureSelection.cpp