Pices: MLL::Sipper3RevBuff Class Reference
MLL::Sipper3RevBuff Class Reference
#include <Sipper3RevBuff.h>
Public Member Functions
Sipper3RevBuff (InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
Sipper3RevBuff (const KKStr &_fileName, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
~Sipper3RevBuff ()
bool FileFormatGood ()
virtual void GetNextLine (uchar *lineBuff, kkuint32 lineBuffSize, kkuint32 &lineSize, kkuint32 colCount[], kkuint32 &pixelsInRow, bool &flow)
Public Member Functions inherited from MLL::SipperBuff
SipperBuff (InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
SipperBuff (const KKStr &_fileName, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
virtual ~SipperBuff ()
kkuint64 ByteOffset () const
kkuint32 BytesDropped () const
kkuint32 CurRow () const
kkuint64 CurRowByteOffset () const
void DetermineCropSettings (kkuint32 &cropLeft, kkuint32 &cropRght)
bool Eof () const
const KKStr & FileName () const
void InvalidLine (bool _invalidLine)
bool InvalidLine () const
virtual kkint32 LineWidth () const
Returns the width in pixels of the associated scanner file.
void Open (const KKStr &_fileName)
bool Opened () const
kkuint32 RecCount () const
void ReportInstrumentData (uchar sensorId, bool text, uchar sensorData)
void Reset ()
void ResetByteOffset (kkuint32 _byteOffset)
kkint32 ScanRate () const
void SkipOneByte ()
virtual void SkipToScanLine (kkuint32 scanLine)
virtual void SkipToScanLine (kkuint32 _scanLine, kkuint64 _byteOffset)
Additional Inherited Members
Public Types inherited from MLL::SipperBuff
typedef KKB::kkint32 kkint32
typedef KKB::kkuint32 kkuint32
typedef SipperBuff * SipperBuffPtr
Static Public Member Functions inherited from MLL::SipperBuff
static SipperBuffPtr CreateSipperBuff (SipperFileFormat _format, KKStr _fileName, kkint32 _cameraNum, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
static SipperBuffPtr CreateSipperBuff (KKStr _fileName, kkint32 _cameraNum, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
static SipperFileFormat GuessFormatOfFile (const KKStr &_fileName, kkint32 _cameraNum, RunLog &_log)
Protected Member Functions inherited from MLL::SipperBuff
void AssignSerialPorts (const SipperHeaderRecPtr sipperHeaderRec)
Static Protected Member Functions inherited from MLL::SipperBuff
static void DisplaySipperRec (SipperBuff::SipperRec &sr)
static SipperFileFormat GuessFormatOfNextLine (FILE *in, kkint32 _cameraNum, RunLog &_log)
Protected Attributes inherited from MLL::SipperBuff
kkuint64 byteOffset
kkuint32 bytesDropped
kkuint32 curRow
kkuint64 curRowByteOffset
bool eof
KKStr fileName
FILE * inFile
InstrumentDataManagerPtr instrumentDataManager
bool invalidLine
Set to true if invalid data is detected on a scan line.
bool iOwnInstrumentDataManager
RunLog & log
bool opened
kkuint32 recCount
Detailed Description
Definition at line 10 of file Sipper3RevBuff.h.
Constructor & Destructor Documentation
Sipper3RevBuff::Sipper3RevBuff (InstrumentDataManagerPtr _instrumentDataManager, RunLog & _log)
Definition at line 44 of file Sipper3RevBuff.cpp.
References MLL::SipperBuff::byteOffset.
Sipper3RevBuff::Sipper3RevBuff (const KKStr & _fileName, InstrumentDataManagerPtr _instrumentDataManager, RunLog & _log)
Definition at line 54 of file Sipper3RevBuff.cpp.
References MLL::SipperBuff::byteOffset.
Sipper3RevBuff::~Sipper3RevBuff ()
Definition at line 69 of file Sipper3RevBuff.cpp.
References MLL::SipperBuff::byteOffset, MLL::SipperBuff::curRowByteOffset, MLL::SipperBuff::eof, MLL::Sipper3Rec::eol, MLL::Sipper3Rec::grayScale, MLL::Sipper3Rec::imageData, MLL::SipperBuff::inFile, MLL::Sipper3Rec::pix0, MLL::Sipper3Rec::pix1, MLL::Sipper3Rec::pix10, MLL::Sipper3Rec::pix11, MLL::Sipper3Rec::pix2, MLL::Sipper3Rec::pix3, MLL::Sipper3Rec::pix4, MLL::Sipper3Rec::pix5, MLL::Sipper3Rec::pix6, MLL::Sipper3Rec::pix7, MLL::Sipper3Rec::pix8, MLL::Sipper3Rec::pix9, MLL::Sipper3Rec::raw, SIPPERRECSIZE, and MLL::SipperBuff::~SipperBuff().
Member Function Documentation
bool Sipper3RevBuff::FileFormatGood ()
Definition at line 442 of file Sipper3RevBuff.cpp.
References MLL::SipperBuff::Eof(), MLL::SipperBuff::Opened(), and MLL::SipperBuff::Reset().
void Sipper3RevBuff::GetNextLine (uchar * lineBuff, kkuint32 lineBuffSize, kkuint32 & lineSize, kkuint32 colCount[], kkuint32 & pixelsInRow, bool & flow) virtual
Implements MLL::SipperBuff.
Definition at line 178 of file Sipper3RevBuff.cpp.
References MLL::SipperBuff::curRow, KKB::endl(), and MLL::SipperBuff::eof.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/Sipper3RevBuff.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/Sipper3RevBuff.cpp