Pices: PicesInterface::PicesTrainingConfigManaged Class Reference
PicesInterface::PicesTrainingConfigManaged Class Reference
#include <PicesTrainingConfigManaged.h>
Public Member Functions
PicesTrainingConfigManaged (PicesRunLog^ _log)
PicesTrainingConfigManaged (String^ _configFileName, PicesRunLog^ _log)
PicesTrainingConfigManaged (DirectoryInfo^ di, PicesRunLog^ log)
void CancelLoad ()
PicesTrainingConfigurationPtr Config ()
PicesClassList^ ExtractClassList ()
PicesFeatureVectorList^ LoadFeatureDataFromTrainingLibraries (bool^ changesMadeToTrainingLibraries)
String^ LoadLogStream ()
String^ ModelName ()
uint NumHierarchialLevels ()
PicesClass^ OtherClass ()
String^ RootDir ()
The root directory where Training library images are stored.
String^ RootDirExpanded ()
The same as RootDir except any environment variables will be expanded.
void Save (String^ configFileName)
PicesTrainingClassList^ TrainingClasses ()
Boolean Valid ()
Static Public Member Functions
static String^ GetEffectiveConfigFileName (String^ configFileName)
Determine the correct configuration file name utilizing TrainingConfiguration2::GetEffectiveConfigFileName.
Protected Member Functions
!PicesTrainingConfigManaged ()
Detailed Description
Definition at line 20 of file PicesTrainingConfigManaged.h.
Constructor & Destructor Documentation
PicesInterface::PicesTrainingConfigManaged::PicesTrainingConfigManaged (PicesRunLog^ _log)
Definition at line 39 of file PicesTrainingConfigManaged.cpp.
Referenced by PicesTrainingConfigManaged().
PicesInterface::PicesTrainingConfigManaged::PicesTrainingConfigManaged (String^ _configFileName, PicesRunLog^ _log)
Definition at line 54 of file PicesTrainingConfigManaged.cpp.
References KKB::Configuration::FormatGood(), MLL::PicesTrainingConfiguration::Load(), PicesInterface::PicesRunLog::Log(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
PicesInterface::PicesTrainingConfigManaged::PicesTrainingConfigManaged (DirectoryInfo^ di, PicesRunLog^ log)
Definition at line 78 of file PicesTrainingConfigManaged.cpp.
References KKMLL::TrainingConfiguration2::ExtractClassList(), PicesInterface::PicesRunLog::Log(), KKB::osAddSlash(), KKB::osGetRootNameOfDirectory(), KKB::osRunAsABackGroundProcess(), PicesTrainingConfigManaged(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
PicesInterface::PicesTrainingConfigManaged::!PicesTrainingConfigManaged () protected
Definition at line 130 of file PicesTrainingConfigManaged.cpp.
References KKB::Configuration::MemoryConsumedEstimated(), and KKMLL::MLClassList::MemoryConsumedEstimated().
Member Function Documentation
void PicesInterface::PicesTrainingConfigManaged::CancelLoad ()
Definition at line 160 of file PicesTrainingConfigManaged.cpp.
Referenced by PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets(), GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters(), and PicesCommander.SaveActiveTrainingModelFeatureData::SaveActiveTrainingModelFeatureData().
PicesTrainingConfigurationPtr PicesInterface::PicesTrainingConfigManaged::Config () inline
Definition at line 41 of file PicesTrainingConfigManaged.h.
Referenced by PicesInterface::TrainingModel2::TrainingModel2().
PicesClassList PicesInterface::PicesTrainingConfigManaged::ExtractClassList ()
Definition at line 210 of file PicesTrainingConfigManaged.cpp.
References KKMLL::TrainingConfiguration2::ExtractClassList().
Referenced by GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters().
String PicesInterface::PicesTrainingConfigManaged::GetEffectiveConfigFileName (String^ configFileName) static
Determine the correct configuration file name utilizing TrainingConfiguration2::GetEffectiveConfigFileName.
See also
KKMLL::TrainingConfiguration2::GetEffectiveConfigFileName
If  no extension then add ".cfg" to end of file name.
if  Path Provided
{
   Return name as submitted with added extension.
}
else
{
   a. If file exists in default directory; then return name with default directory path.
   b. If file exists in Training Model Directory  $(HomeDir) + "\\DataFiles\\TrainingModels"
      then return with Training Model Directory.
   c. Since not found then we will return name passed in with extension.
}
Definition at line 245 of file PicesTrainingConfigManaged.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters().
PicesFeatureVectorList PicesInterface::PicesTrainingConfigManaged::LoadFeatureDataFromTrainingLibraries (bool^ changesMadeToTrainingLibraries)
Definition at line 268 of file PicesTrainingConfigManaged.cpp.
References KKMLL::TrainingConfiguration2::LoadFeatureDataFromTrainingLibraries(), PicesInterface::PicesRunLog::Log(), KKB::KKQueue< Entry >::Owner(), and KKMLL::DuplicateImages::PurgeDuplicates().
Referenced by GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters().
String ^ PicesInterface::PicesTrainingConfigManaged::LoadLogStream () inline
Definition at line 48 of file PicesTrainingConfigManaged.h.
Referenced by GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters().
String PicesInterface::PicesTrainingConfigManaged::ModelName ()
Definition at line 183 of file PicesTrainingConfigManaged.cpp.
References KKMLL::TrainingConfiguration2::ConfigFileNameSpecified(), PicesInterface::PicesKKStr::KKStrToSystenStr(), and KKB::osGetRootNameWithExtension().
uint PicesInterface::PicesTrainingConfigManaged::NumHierarchialLevels ()
Definition at line 200 of file PicesTrainingConfigManaged.cpp.
References KKMLL::TrainingConfiguration2::NumHierarchialLevels().
Referenced by GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters().
PicesClass PicesInterface::PicesTrainingConfigManaged::OtherClass ()
Definition at line 253 of file PicesTrainingConfigManaged.cpp.
References PicesInterface::PicesClassList::GetUniqueClass(), and KKMLL::TrainingConfiguration2::OtherClass().
Referenced by GradeTrainingModel.ConfusionMatrix::ConfusionMatrix(), and GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters().
String PicesInterface::PicesTrainingConfigManaged::RootDir ()
The root directory where Training library images are stored.
Definition at line 168 of file PicesTrainingConfigManaged.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr(), and KKMLL::TrainingConfiguration2::RootDir().
Referenced by GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters(), and PicesCommander.TrainingModelCreateFromDirectory::TrainingModelCreateFromDirectory().
String PicesInterface::PicesTrainingConfigManaged::RootDirExpanded ()
The same as RootDir except any environment variables will be expanded.
Definition at line 176 of file PicesTrainingConfigManaged.cpp.
References PicesInterface::PicesKKStr::KKStrToSystenStr(), and KKMLL::TrainingConfiguration2::RootDirExpanded().
Referenced by GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters().
void PicesInterface::PicesTrainingConfigManaged::Save (String^ configFileName)
Definition at line 339 of file PicesTrainingConfigManaged.cpp.
References MLL::PicesTrainingConfiguration::Save(), and PicesInterface::PicesKKStr::SystemStringToKKStr().
Referenced by PicesCommander.TrainingModelCreateFromDirectory::TrainingModelCreateFromDirectory().
PicesTrainingClassList PicesInterface::PicesTrainingConfigManaged::TrainingClasses ()
Definition at line 321 of file PicesTrainingConfigManaged.cpp.
References KKMLL::TrainingConfiguration2::TrainingClasses().
Referenced by PicesCommander.TrainingModelCreateFromDirectory::TrainingModelCreateFromDirectory().
System::Boolean PicesInterface::PicesTrainingConfigManaged::Valid ()
Definition at line 193 of file PicesTrainingConfigManaged.cpp.
Referenced by PicesCommander.CreateFeatureSelectionDataSets::CreateFeatureSelectionDataSets(), GradeTrainingModel.GetRunTimeParameters::GetRunTimeParameters(), PicesCommander.SaveActiveTrainingModelFeatureData::SaveActiveTrainingModelFeatureData(), and PicesCommander.TrainingModelCreateFromDirectory::TrainingModelCreateFromDirectory().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesTrainingConfigManaged.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesTrainingConfigManaged.cpp