Pices: C:/Users/Kurt/GitHub/Pices/Apps/FeatureSelection/Processor.cpp File Reference
Processor.cpp File Reference
#include "FirstIncludes.h"
#include <fcntl.h>
#include <math.h>
#include <stdlib.h>
#include <stdio.h>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <string>
#include <vector>
#include "MemoryDebug.h"
#include <sys/types.h>
#include <io.h>
#include <windows.h>
#include "KKBaseTypes.h"
#include "KKQueue.h"
#include "OSservices.h"
#include "RunLog.h"
#include "KKStr.h"
#include "MLClass.h"
#include "TrainingProcess2.h"
#include "Processor.h"
#include "BinaryJob.h"
#include "BinaryJobList.h"
#include "FeatureImpact.h"
#include "FeatureSelection.h"
#include "FeatureSelectionTypes.h"
#include "JobRandomSplit.h"
Macros
#define MaxCParmValue 20
Functions
float CalcGrowthRate (double minValue, double maxValue, int numDivisions)
Macro Definition Documentation
#define MaxCParmValue 20
Definition at line 28 of file Processor.cpp.
Referenced by CalcGrowthRate(), and FeatureSelectionApp::Processor::EndBlock().
Function Documentation
float CalcGrowthRate (double minValue, double maxValue, int numDivisions)
Definition at line 1870 of file Processor.cpp.
References FeatureSelectionApp::BinaryJob::AParm(), FeatureSelectionApp::Beam, FeatureSelectionApp::BestCaseNext, FeatureSelectionApp::BruitForce, FeatureSelectionApp::Processor::Class1Name(), FeatureSelectionApp::Processor::Class2Name(), FeatureSelectionApp::BinaryJobList::ComputeMinAndMaxParmValues(), FeatureSelectionApp::FeatureSelection::Config(), FeatureSelectionApp::BinaryJob::CParm(), FeatureSelectionApp::BinaryJobList::CreateTestJobsForHighetsGradePerFeatureCount(), KKB::endl(), FeatureSelectionApp::BinaryJobList::ExtractByMinimumProcessintTime(), FeatureSelectionApp::BinaryJobList::ExtractHighestGrade(), FeatureSelectionApp::BinaryJobList::ExtractTestJobs(), FeatureSelectionApp::BinaryJobList::FastestJob(), FeatureSelectionApp::FeatureSelection::FeatureCountPrefSmall(), FeatureSelectionApp::BinaryJob::Features(), FeatureSelectionApp::FeatureSelectionSearch, FeatureSelectionApp::BinaryJobList::FindNeighboringParameterValues(), FeatureSelectionApp::Processor::FlagJobsForTesting(), FeatureSelectionApp::BinaryJob::GammaParm(), FeatureSelectionApp::GenerateBruitSvmSearch, FeatureSelectionApp::FeatureSelection::GradingMethod(), FeatureSelectionApp::GradingMethodToStr(), FeatureSelectionApp::Grid, FeatureSelectionApp::BinaryJobList::HighestGradedJob(), FeatureSelectionApp::BinaryJobList::HighestGradedTestJob(), KKB::KKQueue< Entry >::IdxToPtr(), FeatureSelectionApp::BinaryJob::JobId(), FeatureSelectionApp::JobSelectionCriteriaToStr(), FeatureSelectionApp::BinaryJob::JobTypeStr(), KKB::RunLog::Level(), FeatureSelectionApp::BinaryJobList::LookUpByParameters(), FeatureSelectionApp::BinaryJobList::LowestDeltaAccuracyProbJob(), FeatureSelectionApp::BinaryJobList::LowestDeltaAccuracyProbTestJob(), FeatureSelectionApp::FeatureSelection::MajorStep(), KKB::Max(), MaxCParmValue, KKMLL::TrainingConfiguration2::ModelParameterCmdLine(), KKMLL::TrainingConfiguration2::ModelType(), KKMLL::TrainingConfiguration2::ModelTypeStr(), FeatureSelectionApp::MostAccurate, FeatureSelectionApp::BinaryJobList::NoError, FeatureSelectionApp::BinaryJob::NumOfRounds(), FeatureSelectionApp::OnePassOnly, KKB::osGetLocalDateTime(), KKB::KKQueue< Entry >::Owner(), FeatureSelectionApp::FeatureSelection::ParamSelCriteria(), FeatureSelectionApp::PickTheBest, KKMLL::FeatureVectorList::PrintClassStatistics(), FeatureSelectionApp::BinaryJob::ProcessingTime(), FeatureSelectionApp::BinaryJobList::PushOnBack(), KKB::KKQueue< Entry >::QueueSize(), FeatureSelectionApp::FeatureImpact::Report(), FeatureSelectionApp::FeatureImpact::ReportHTML(), FeatureSelectionApp::BinaryJobList::ReportResults(), FeatureSelectionApp::SearchMethodToStr(), FeatureSelectionApp::BinaryJobList::SortByGrade(), FeatureSelectionApp::BinaryJobList::SortByTestGrade(), FeatureSelectionApp::BinaryJobList::SortDeltaProbAccuarcy(), KKB::KKStr::Str(), FeatureSelectionApp::FeatureSelection::TestDataFileName(), FeatureSelectionApp::TestResults, FeatureSelectionApp::BinaryJob::ToStatusStr(), FeatureSelectionApp::Processor::TotalCpuTimeUsed(), and FeatureSelectionApp::FeatureSelection::TrainingDataFileName().