Pices: MLL::SipperHeaderRec Class Reference
MLL::SipperHeaderRec Class Reference
Header info stored in the beginning of each sipper file.
#include <SipperHeaderRec.h>
Public Types
typedef KKB::kkuint32 kkuint32
typedef SipperHeaderRec * SipperHeaderRecPtr
Public Member Functions
SipperHeaderRec ()
SipperHeaderRec (const SipperHeaderRec &_headerRec)
~SipperHeaderRec ()
void AirTemp (KKStr _airTemp)
KKStr AirTemp () const
void CruiseDateEnd (DateType _cruiseDateEnd)
DateType CruiseDateEnd () const
void CruiseDateStart (DateType _cruiseDateStart)
DateType CruiseDateStart () const
void CruiseLocation (KKStr _cruiseLocation)
KKStr CruiseLocation () const
void CtdExt0Code (const KKStr &_ctdExt0Code)
KKStr CtdExt0Code () const
void CtdExt1Code (const KKStr &_ctdExt1Code)
KKStr CtdExt1Code () const
void CtdExt2Code (const KKStr &_ctdExt2Code)
KKStr CtdExt2Code () const
void CtdExt3Code (const KKStr &_ctdExt3Code)
KKStr CtdExt3Code () const
void DeploymentVehicle (KKStr _deploymentVehicle)
KKStr DeploymentVehicle () const
KKStr HeaderStr ()
InstrumentPtr InclinationMeter (kkuint32 inclinationSerailPort) const
void Latitude (double _latitude)
double Latitude () const
void Longitude (double _longitude)
double Longitude () const
void Objective (KKStr _objective)
KKStr Objective () const
SipperHeaderRec & operator= (const SipperHeaderRec &right)
void ParseHeaderStr (const KKStr &s)
const PortAssignmentList & PortAssignments () const
void Principal (KKStr _principal)
KKStr Principal () const
void ProcessNameAndDataStrings (const KKStr &fieldName, const KKStr &fieldValue, bool &found)
void ResearchOrg (KKStr _researchOrg)
KKStr ResearchOrg () const
void Save (ostream &w)
void ScanRate (kkint32 _scanRate)
kkint32 ScanRate () const
void SeaConditions (KKStr _seaConditions)
KKStr SeaConditions () const
InstrumentPtr SerialPortAssignment (kkuint32 serialPort) const
const KKStr & SerialPortDesc (kkuint32 serialPortNum) const
const KKStr & SerialPortShortName (kkuint32 serialPortNum) const
void SipperFileName (KKStr _sipperFileName)
KKStr SipperFileName () const
void WaveHeight (KKStr _waveHeight)
KKStr WaveHeight () const
void WeatherConditions (KKStr _weatherConditions)
KKStr WeatherConditions () const
Static Public Attributes
static const kkint32 MaxHeaderLen = 456
static const kkint32 MaxSipperFileNameLen = 30
Detailed Description
Header info stored in the beginning of each sipper file.
This 'class' is meant to deal with the header info at the start of each Sipper File. This header info is in the form of a User Text message encoded as instrument data. The 'InstrumentDataUserMsgs' object is responsible for extracting this text. This text can then be processed by the 'ParseHeaderStr' method. There is a corresponding c# class in the 'SipperFile' library.
Definition at line 59 of file SipperHeaderRec.h.
Member Typedef Documentation
typedef KKB::kkuint32 MLL::SipperHeaderRec::kkuint32
Definition at line 63 of file SipperHeaderRec.h.
typedef SipperHeaderRec* MLL::SipperHeaderRec::SipperHeaderRecPtr
Definition at line 62 of file SipperHeaderRec.h.
Constructor & Destructor Documentation
SipperHeaderRec::SipperHeaderRec ()
Definition at line 75 of file SipperHeaderRec.cpp.
SipperHeaderRec::SipperHeaderRec (const SipperHeaderRec & _headerRec)
Definition at line 103 of file SipperHeaderRec.cpp.
SipperHeaderRec::~SipperHeaderRec ()
Definition at line 138 of file SipperHeaderRec.cpp.
References KKB::DateTime::Date(), and KKB::osGetLocalDateTime().
Member Function Documentation
void MLL::SipperHeaderRec::AirTemp (KKStr _airTemp) inline
Definition at line 102 of file SipperHeaderRec.h.
KKStr MLL::SipperHeaderRec::AirTemp () const inline
Definition at line 124 of file SipperHeaderRec.h.
void MLL::SipperHeaderRec::CruiseDateEnd (DateType _cruiseDateEnd) inline
Definition at line 97 of file SipperHeaderRec.h.
DateType MLL::SipperHeaderRec::CruiseDateEnd () const inline
Definition at line 119 of file SipperHeaderRec.h.
void MLL::SipperHeaderRec::CruiseDateStart (DateType _cruiseDateStart) inline
Definition at line 96 of file SipperHeaderRec.h.
DateType MLL::SipperHeaderRec::CruiseDateStart () const inline
Definition at line 118 of file SipperHeaderRec.h.
void MLL::SipperHeaderRec::CruiseLocation (KKStr _cruiseLocation) inline
Definition at line 92 of file SipperHeaderRec.h.
KKStr MLL::SipperHeaderRec::CruiseLocation () const inline
Definition at line 114 of file SipperHeaderRec.h.
void MLL::SipperHeaderRec::CtdExt0Code (const KKStr & _ctdExt0Code) inline
Definition at line 108 of file SipperHeaderRec.h.
KKStr MLL::SipperHeaderRec::CtdExt0Code () const inline
Definition at line 130 of file SipperHeaderRec.h.
void MLL::SipperHeaderRec::CtdExt1Code (const KKStr & _ctdExt1Code) inline
Definition at line 109 of file SipperHeaderRec.h.
KKStr MLL::SipperHeaderRec::CtdExt1Code () const inline
Definition at line 131 of file SipperHeaderRec.h.
void MLL::SipperHeaderRec::CtdExt2Code (const KKStr & _ctdExt2Code) inline
Definition at line 110 of file SipperHeaderRec.h.
KKStr MLL::SipperHeaderRec::CtdExt2Code () const inline
Definition at line 132 of file SipperHeaderRec.h.
void MLL::SipperHeaderRec::CtdExt3Code (const KKStr & _ctdExt3Code) inline
Definition at line 111 of file SipperHeaderRec.h.
KKStr MLL::SipperHeaderRec::CtdExt3Code () const inline
Definition at line 133 of file SipperHeaderRec.h.
void MLL::SipperHeaderRec::DeploymentVehicle (KKStr _deploymentVehicle) inline
Definition at line 98 of file SipperHeaderRec.h.
KKStr MLL::SipperHeaderRec::DeploymentVehicle () const inline
Definition at line 120 of file SipperHeaderRec.h.
KKStr SipperHeaderRec::HeaderStr ()
Definition at line 190 of file SipperHeaderRec.cpp.
References KKB::StrFormatDouble(), and KKB::StrFormatInt().
InstrumentPtr SipperHeaderRec::InclinationMeter (kkuint32 inclinationSerailPort) const
Definition at line 451 of file SipperHeaderRec.cpp.
void MLL::SipperHeaderRec::Latitude (double _latitude) inline
Definition at line 103 of file SipperHeaderRec.h.
double MLL::SipperHeaderRec::Latitude () const inline
Definition at line 125 of file SipperHeaderRec.h.
void MLL::SipperHeaderRec::Longitude (double _longitude) inline
Definition at line 104 of file SipperHeaderRec.h.
double MLL::SipperHeaderRec::Longitude () const inline
Definition at line 126 of file SipperHeaderRec.h.
void MLL::SipperHeaderRec::Objective (KKStr _objective) inline
Definition at line 93 of file SipperHeaderRec.h.
KKStr MLL::SipperHeaderRec::Objective () const inline
Definition at line 115 of file SipperHeaderRec.h.
SipperHeaderRec & SipperHeaderRec::operator= (const SipperHeaderRec & right)
Definition at line 473 of file SipperHeaderRec.cpp.
void SipperHeaderRec::ParseHeaderStr (const KKStr & s)
Definition at line 227 of file SipperHeaderRec.cpp.
References KKB::KKStr::LocateCharacter(), ProcessNameAndDataStrings(), KKB::KKStr::Split(), and KKB::KKStr::SubStrPart().
Referenced by MLL::Sipper3Buff::FileFormatGood().
const PortAssignmentList& MLL::SipperHeaderRec::PortAssignments () const inline
Definition at line 76 of file SipperHeaderRec.h.
References MLL::PortAssignment::HeaderStr().
void MLL::SipperHeaderRec::Principal (KKStr _principal) inline
Definition at line 94 of file SipperHeaderRec.h.
KKStr MLL::SipperHeaderRec::Principal () const inline
Definition at line 116 of file SipperHeaderRec.h.
void SipperHeaderRec::ProcessNameAndDataStrings (const KKStr & fieldName, const KKStr & fieldValue, bool & found)
Definition at line 265 of file SipperHeaderRec.cpp.
References KKB::KKStr::Empty(), KKB::endl(), MLL::PortAssignment::HeaderStr(), Save(), KKB::KKStr::Split(), KKB::StrFormatDouble(), KKB::StrFormatInt(), KKB::KKStr::ToDouble(), KKB::KKStr::ToInt(), and KKB::KKStr::ToLower().
Referenced by ParseHeaderStr().
void MLL::SipperHeaderRec::ResearchOrg (KKStr _researchOrg) inline
Definition at line 95 of file SipperHeaderRec.h.
KKStr MLL::SipperHeaderRec::ResearchOrg () const inline
Definition at line 117 of file SipperHeaderRec.h.
void MLL::SipperHeaderRec::Save (ostream & w)
Referenced by ProcessNameAndDataStrings().
void MLL::SipperHeaderRec::ScanRate (kkint32 _scanRate) inline
Definition at line 105 of file SipperHeaderRec.h.
kkint32 MLL::SipperHeaderRec::ScanRate () const inline
Definition at line 127 of file SipperHeaderRec.h.
void MLL::SipperHeaderRec::SeaConditions (KKStr _seaConditions) inline
Definition at line 99 of file SipperHeaderRec.h.
KKStr MLL::SipperHeaderRec::SeaConditions () const inline
Definition at line 121 of file SipperHeaderRec.h.
InstrumentPtr SipperHeaderRec::SerialPortAssignment (kkuint32 serialPort) const
Definition at line 436 of file SipperHeaderRec.cpp.
Referenced by MLL::InstrumentDataReport::CreateInstrumentDataReport().
const KKStr & SipperHeaderRec::SerialPortDesc (kkuint32 serialPortNum) const
Definition at line 423 of file SipperHeaderRec.cpp.
const KKStr & SipperHeaderRec::SerialPortShortName (kkuint32 serialPortNum) const
Definition at line 409 of file SipperHeaderRec.cpp.
void MLL::SipperHeaderRec::SipperFileName (KKStr _sipperFileName) inline
Definition at line 106 of file SipperHeaderRec.h.
KKStr MLL::SipperHeaderRec::SipperFileName () const inline
Definition at line 128 of file SipperHeaderRec.h.
void MLL::SipperHeaderRec::WaveHeight (KKStr _waveHeight) inline
Definition at line 100 of file SipperHeaderRec.h.
KKStr MLL::SipperHeaderRec::WaveHeight () const inline
Definition at line 122 of file SipperHeaderRec.h.
void MLL::SipperHeaderRec::WeatherConditions (KKStr _weatherConditions) inline
Definition at line 101 of file SipperHeaderRec.h.
KKStr MLL::SipperHeaderRec::WeatherConditions () const inline
Definition at line 123 of file SipperHeaderRec.h.
Member Data Documentation
const kkint32 MLL::SipperHeaderRec::MaxHeaderLen = 456 static
Definition at line 65 of file SipperHeaderRec.h.
const kkint32 MLL::SipperHeaderRec::MaxSipperFileNameLen = 30 static
Definition at line 66 of file SipperHeaderRec.h.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/SipperHeaderRec.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/SipperHeaderRec.cpp