Pices: KKB::MorphOpErosion Class Reference
KKB::MorphOpErosion Class Reference
#include <MorphOpErosion.h>
Public Member Functions
MorphOpErosion (StructureType _structure, kkuint16 _structureSize)
virtual ~MorphOpErosion ()
kkint32 MemoryConsumedEstimated ()
virtual OperationType Operation () const
virtual RasterPtr PerformOperation (RasterConstPtr _image)
Public Member Functions inherited from KKB::MorphOpStruct
MorphOpStruct (StructureType _structure, kkuint16 _structureSize)
virtual ~MorphOpStruct ()
void BackgroundCountTH (kkint32 _backgroundCountTH)
void ForegroundCountTH (kkint32 _foregroundCountTH)
kkint32 MemoryConsumedEstimated ()
Public Member Functions inherited from KKB::MorphOp
MorphOp ()
virtual ~MorphOp ()
OperationType OperationTypeFromStr (const KKB::KKStr &_operationStr)
KKB::KKStr OperationTypeToStr (OperationType _operation)
virtual RasterPtr PerformOperation (Raster const *_image)=0
Additional Inherited Members
Public Types inherited from KKB::MorphOp
enum MaskTypes : int {
MaskTypes::CROSS3 = 0, MaskTypes::CROSS5 = 1, MaskTypes::SQUARE3 = 2, MaskTypes::SQUARE5 = 3,
MaskTypes::SQUARE7 = 4, MaskTypes::SQUARE9 = 5, MaskTypes::SQUARE11 = 6
}
enum OperationType {
OperationType::Null, OperationType::Binarize, OperationType::BmiFiltering, OperationType::ConvexHull,
OperationType::Dilation, OperationType::Erosion, OperationType::MaskExclude, OperationType::SobelEdgeDetection,
OperationType::Stretcher
}
enum StructureType : int { StructureType::Null, StructureType::stCross, StructureType::stSquare }
Static Public Member Functions inherited from KKB::MorphOp
static kkint32 Biases (MaskTypes mt)
static StructureType MaskShapes (MaskTypes mt)
Protected Member Functions inherited from KKB::MorphOpStruct
bool Fit (kkint32 row, kkint32 col) const
bool FitBackgroundCount (kkint32 row, kkint32 col) const
uchar HitForegroundCount (kkint32 row, kkint32 col) const
Protected Member Functions inherited from KKB::MorphOp
bool BackgroundPixel (uchar pixel) const
bool BackgroundPixel (kkint32 row, kkint32 col) const
bool ForegroundPixel (uchar pixel) const
bool ForegroundPixel (kkint32 row, kkint32 col) const
void SetSrcRaster (RasterConstPtr _srcRaster)
Protected Attributes inherited from KKB::MorphOpStruct
kkint32 backgroundCountTH
If greater than zero; then pixel must have at least that many neighbors to be considered a fit.
kkint32 foregroundCountTH
StructureType structure
kkuint16 structureSize
Protected Attributes inherited from KKB::MorphOp
uchar backgroundPixelTH
uchar backgroundPixelValue
uchar *const * srcBlue
uchar const * srcBlueArea
bool srcColor
uchar *const * srcGreen
uchar const * srcGreenArea
kkint32 srcHeight
RasterConstPtr srcRaster
uchar *const * srcRed
uchar const * srcRedArea
kkint32 srcWidth
Static Protected Attributes inherited from KKB::MorphOp
static kkint32 biases []
static StructureType maskShapes []
Detailed Description
Definition at line 24 of file MorphOpErosion.h.
Constructor & Destructor Documentation
MorphOpErosion::MorphOpErosion (StructureType _structure, kkuint16 _structureSize)
Definition at line 22 of file MorphOpErosion.cpp.
MorphOpErosion::~MorphOpErosion () virtual
Definition at line 31 of file MorphOpErosion.cpp.
Member Function Documentation
kkint32 MorphOpErosion::MemoryConsumedEstimated ()
Definition at line 37 of file MorphOpErosion.cpp.
Referenced by Operation().
virtual OperationType KKB::MorphOpErosion::Operation () const inline virtual
Reimplemented from KKB::MorphOpStruct.
Definition at line 33 of file MorphOpErosion.h.
References KKB::MorphOp::Erosion, MemoryConsumedEstimated(), and PerformOperation().
RasterPtr MorphOpErosion::PerformOperation (RasterConstPtr _image) virtual
Implements KKB::MorphOpStruct.
Definition at line 46 of file MorphOpErosion.cpp.
References KKB::MorphOpStruct::backgroundCountTH, KKB::MorphOp::backgroundPixelValue, KKB::MorphOpStruct::Fit(), KKB::MorphOpStruct::FitBackgroundCount(), KKB::MorphOp::ForegroundPixel(), KKB::Raster::ForegroundPixelCount(), KKB::Raster::Green(), KKB::MorphOp::SetSrcRaster(), KKB::MorphOp::srcGreen, KKB::MorphOp::srcHeight, KKB::MorphOp::srcRaster, and KKB::MorphOp::srcWidth.
Referenced by KKB::Raster::Erosion(), and Operation().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/MorphOpErosion.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/MorphOpErosion.cpp