Pices: MLL::GPSDataPoint Class Reference
MLL::GPSDataPoint Class Reference
Represents a single GPS data-point entry (GMT DateTime, Latitude and Longitude) from a imported GPS data source provided by the research Vessels that SIPPER is deployed on.
#include <GPSDataPoint.h>
Public Types
typedef KKB::DateTime DateTime
typedef GPSDataPoint * GPSDataPointPtr
typedef KKB::kkint32 kkint32
typedef KKB::kkuint32 kkuint32
typedef KKB::TimeType TimeType
Public Member Functions
GPSDataPoint ()
GPSDataPoint (const GPSDataPoint &_dataPoint)
GPSDataPoint (DateTime _gpsUtcTime, double _latitude, double _longitude, float _courseOverGround, float _speedOverGround)
~GPSDataPoint ()
float CourseOverGround () const
DateTime GpsUtcTime () const
double Latitude () const
double Longitude () const
float SpeedOverGround () const
Detailed Description
Represents a single GPS data-point entry (GMT DateTime, Latitude and Longitude) from a imported GPS data source provided by the research Vessels that SIPPER is deployed on.
Research vessels will record GPS data into text files throughout the length of their cruises. Temporal granularity will range from a couple seconds to a minute. This data is imported into the PICES database via the ImportGPSDataApp application. The data is kept in the GpsData table of the PICES database.
Definition at line 22 of file GPSDataPoint.h.
Member Typedef Documentation
typedef KKB::DateTime MLL::GPSDataPoint::DateTime
Definition at line 27 of file GPSDataPoint.h.
typedef GPSDataPoint* MLL::GPSDataPoint::GPSDataPointPtr
Definition at line 29 of file GPSDataPoint.h.
typedef KKB::kkint32 MLL::GPSDataPoint::kkint32
Definition at line 25 of file GPSDataPoint.h.
typedef KKB::kkuint32 MLL::GPSDataPoint::kkuint32
Definition at line 26 of file GPSDataPoint.h.
typedef KKB::TimeType MLL::GPSDataPoint::TimeType
Definition at line 28 of file GPSDataPoint.h.
Constructor & Destructor Documentation
GPSDataPoint::GPSDataPoint ()
Definition at line 23 of file GPSDataPoint.cpp.
GPSDataPoint::GPSDataPoint (const GPSDataPoint & _dataPoint)
Definition at line 33 of file GPSDataPoint.cpp.
GPSDataPoint::GPSDataPoint (DateTime _gpsUtcTime, double _latitude, double _longitude, float _courseOverGround, float _speedOverGround)
Definition at line 44 of file GPSDataPoint.cpp.
GPSDataPoint::~GPSDataPoint ()
Definition at line 60 of file GPSDataPoint.cpp.
Member Function Documentation
float MLL::GPSDataPoint::CourseOverGround () const inline
Definition at line 47 of file GPSDataPoint.h.
Referenced by MLL::DataBase::GpsDataInsert().
DateTime MLL::GPSDataPoint::GpsUtcTime () const inline
Definition at line 44 of file GPSDataPoint.h.
Referenced by MLL::DataBase::GpsDataInsert().
double MLL::GPSDataPoint::Latitude () const inline
Definition at line 45 of file GPSDataPoint.h.
Referenced by MLL::DataBase::GpsDataInsert().
double MLL::GPSDataPoint::Longitude () const inline
Definition at line 46 of file GPSDataPoint.h.
Referenced by MLL::DataBase::GpsDataInsert().
float MLL::GPSDataPoint::SpeedOverGround () const inline
Definition at line 48 of file GPSDataPoint.h.
Referenced by MLL::DataBase::GpsDataInsert().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/GPSDataPoint.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/GPSDataPoint.cpp