Pices: MLL::SipperBuff Class Reference
MLL::SipperBuff Class Reference abstract
Base class to be used for all the different Sipper File Formats.
#include <SipperBuff.h>
Classes
struct SipperRec
Public Types
typedef KKB::kkint32 kkint32
typedef KKB::kkuint32 kkuint32
typedef SipperBuff * SipperBuffPtr
Public Member Functions
SipperBuff (InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
SipperBuff (const KKStr &_fileName, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
virtual ~SipperBuff ()
kkuint64 ByteOffset () const
kkuint32 BytesDropped () const
kkuint32 CurRow () const
kkuint64 CurRowByteOffset () const
void DetermineCropSettings (kkuint32 &cropLeft, kkuint32 &cropRght)
bool Eof () const
const KKStr & FileName () const
virtual void GetNextLine (uchar *lineBuff, kkuint32 lineBuffSize, kkuint32 &lineSize, kkuint32 colCount[], kkuint32 &pixelsInRow, bool &flow)=0
void InvalidLine (bool _invalidLine)
bool InvalidLine () const
virtual kkint32 LineWidth () const
Returns the width in pixels of the associated scanner file.
void Open (const KKStr &_fileName)
bool Opened () const
kkuint32 RecCount () const
void ReportInstrumentData (uchar sensorId, bool text, uchar sensorData)
void Reset ()
void ResetByteOffset (kkuint32 _byteOffset)
kkint32 ScanRate () const
void SkipOneByte ()
virtual void SkipToScanLine (kkuint32 scanLine)
virtual void SkipToScanLine (kkuint32 _scanLine, kkuint64 _byteOffset)
Static Public Member Functions
static SipperBuffPtr CreateSipperBuff (SipperFileFormat _format, KKStr _fileName, kkint32 _cameraNum, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
static SipperBuffPtr CreateSipperBuff (KKStr _fileName, kkint32 _cameraNum, InstrumentDataManagerPtr _instrumentDataManager, RunLog &_log)
static SipperFileFormat GuessFormatOfFile (const KKStr &_fileName, kkint32 _cameraNum, RunLog &_log)
Protected Member Functions
void AssignSerialPorts (const SipperHeaderRecPtr sipperHeaderRec)
Static Protected Member Functions
static void DisplaySipperRec (SipperBuff::SipperRec &sr)
static SipperFileFormat GuessFormatOfNextLine (FILE *in, kkint32 _cameraNum, RunLog &_log)
Protected Attributes
kkuint64 byteOffset
kkuint32 bytesDropped
kkuint32 curRow
kkuint64 curRowByteOffset
bool eof
KKStr fileName
FILE * inFile
InstrumentDataManagerPtr instrumentDataManager
bool invalidLine
Set to true if invalid data is detected on a scan line.
bool iOwnInstrumentDataManager
RunLog & log
bool opened
kkuint32 recCount
Detailed Description
Base class to be used for all the different Sipper File Formats.
Each derived sub-class needs to implement 'GetNextSipperRec' and 'FileFormatGood'.
See also
InstrumentDataManager
Definition at line 44 of file SipperBuff.h.
Member Typedef Documentation
typedef KKB::kkint32 MLL::SipperBuff::kkint32
Definition at line 48 of file SipperBuff.h.
typedef KKB::kkuint32 MLL::SipperBuff::kkuint32
Definition at line 49 of file SipperBuff.h.
typedef SipperBuff* MLL::SipperBuff::SipperBuffPtr
Definition at line 47 of file SipperBuff.h.
Constructor & Destructor Documentation
SipperBuff::SipperBuff (InstrumentDataManagerPtr _instrumentDataManager, RunLog & _log)
Definition at line 37 of file SipperBuff.cpp.
SipperBuff::SipperBuff (const KKStr & _fileName, InstrumentDataManagerPtr _instrumentDataManager, RunLog & _log)
Definition at line 59 of file SipperBuff.cpp.
References fileName, and Open().
SipperBuff::~SipperBuff () virtual
Definition at line 83 of file SipperBuff.cpp.
References inFile, instrumentDataManager, iOwnInstrumentDataManager, and opened.
Referenced by MLL::Sipper3RevBuff::~Sipper3RevBuff(), MLL::SipperBuff3Bit::~SipperBuff3Bit(), and MLL::SipperBuffBinary::~SipperBuffBinary().
Member Function Documentation
void SipperBuff::AssignSerialPorts (const SipperHeaderRecPtr sipperHeaderRec) protected
Definition at line 114 of file SipperBuff.cpp.
References MLL::InstrumentDataManager::AssignSerialPorts(), and instrumentDataManager.
Referenced by MLL::Sipper3Buff::FileFormatGood().
kkuint64 MLL::SipperBuff::ByteOffset () const inline
Definition at line 70 of file SipperBuff.h.
Referenced by MLL::InstrumentDataList::CreateFromSipperFile(), ImageExtractionManager::FrameExtractorThread::GetRunTimeStats(), and ImageExtractionManager::FrameExtractorThread::Run().
kkuint32 MLL::SipperBuff::BytesDropped () const inline
Definition at line 69 of file SipperBuff.h.
SipperBuffPtr SipperBuff::CreateSipperBuff (SipperFileFormat _format, KKStr _fileName, kkint32 _cameraNum, InstrumentDataManagerPtr _instrumentDataManager, RunLog & _log) static
Definition at line 531 of file SipperBuff.cpp.
References GuessFormatOfFile(), Opened(), MLL::sf3Bit, MLL::sfBinary, MLL::sfSipper3, MLL::sfSipper3Rev, MLL::sfSipper4Bit, and MLL::sfUnKnown.
Referenced by MLL::InstrumentDataList::CreateFromSipperFile(), CreateSipperBuff(), and MLL::InstrumentDataFileManager::GetOrigSipperImage().
SipperBuffPtr SipperBuff::CreateSipperBuff (KKStr _fileName, kkint32 _cameraNum, InstrumentDataManagerPtr _instrumentDataManager, RunLog & _log) static
Definition at line 517 of file SipperBuff.cpp.
References CreateSipperBuff(), and GuessFormatOfFile().
kkuint32 MLL::SipperBuff::CurRow () const inline
Definition at line 72 of file SipperBuff.h.
Referenced by MLL::InstrumentDataList::CreateFromSipperFile(), MLL::Sipper3Buff::GetNextLine(), MLL::InstrumentDataFileManager::GetOrigSipperImage(), and ImageExtractionManager::FrameExtractorThread::GetRunTimeStats().
kkuint64 MLL::SipperBuff::CurRowByteOffset () const inline
Definition at line 73 of file SipperBuff.h.
Referenced by MLL::InstrumentDataList::CreateFromSipperFile().
void SipperBuff::DetermineCropSettings (kkuint32 & cropLeft, kkuint32 & cropRght)
Definition at line 576 of file SipperBuff.cpp.
References eof, GetNextLine(), and KKB::Max().
void SipperBuff::DisplaySipperRec (SipperBuff::SipperRec & sr) static protected
Definition at line 298 of file SipperBuff.cpp.
References MLL::SipperBuff::SipperRec::cameraNum, KKB::endl(), MLL::SipperBuff::SipperRec::eol, MLL::SipperBuff::SipperRec::flow, MLL::SipperBuff::SipperRec::pix0, MLL::SipperBuff::SipperRec::pix1, MLL::SipperBuff::SipperRec::pix10, MLL::SipperBuff::SipperRec::pix11, MLL::SipperBuff::SipperRec::pix2, MLL::SipperBuff::SipperRec::pix3, MLL::SipperBuff::SipperRec::pix4, MLL::SipperBuff::SipperRec::pix5, MLL::SipperBuff::SipperRec::pix6, MLL::SipperBuff::SipperRec::pix7, MLL::SipperBuff::SipperRec::pix8, MLL::SipperBuff::SipperRec::pix9, and MLL::SipperBuff::SipperRec::raw.
bool MLL::SipperBuff::Eof () const inline
Definition at line 74 of file SipperBuff.h.
Referenced by MLL::InstrumentDataList::CreateFromSipperFile(), MLL::Sipper3RevBuff::FileFormatGood(), MLL::Sipper3Buff::FileFormatGood(), MLL::SipperBuff4Bit::FileFormatGood(), and MLL::InstrumentDataFileManager::GetOrigSipperImage().
const KKStr& MLL::SipperBuff::FileName () const inline
Definition at line 61 of file SipperBuff.h.
Referenced by MLL::Sipper3Buff::GetNextLine().
virtual void MLL::SipperBuff::GetNextLine (uchar * lineBuff, kkuint32 lineBuffSize, kkuint32 & lineSize, kkuint32 colCount[], kkuint32 & pixelsInRow, bool & flow) pure virtual
Implemented in MLL::SipperBuff4Bit, MLL::Sipper3Buff, MLL::SipperBuffBinary, MLL::SipperBuff3Bit, and MLL::Sipper3RevBuff.
Referenced by MLL::InstrumentDataList::CreateFromSipperFile(), DetermineCropSettings(), MLL::InstrumentDataFileManager::GetOrigSipperImage(), ImageExtractionManager::FrameExtractorThread::GetRunTimeStats(), and SkipToScanLine().
SipperFileFormat SipperBuff::GuessFormatOfFile (const KKStr & _fileName, kkint32 _cameraNum, RunLog & _log) static
Definition at line 415 of file SipperBuff.cpp.
References KKB::endl(), MLL::Sipper3Buff::FileFormatGood(), MLL::SipperBuff4Bit::FileFormatGood(), GuessFormatOfNextLine(), Opened(), KKB::osFOPEN(), MLL::sfSipper3, MLL::sfSipper4Bit, MLL::sfUnKnown, and KKB::KKStr::Str().
Referenced by CreateSipperBuff().
SipperFileFormat SipperBuff::GuessFormatOfNextLine (FILE * in, kkint32 _cameraNum, RunLog & _log) static protected
Definition at line 337 of file SipperBuff.cpp.
References MLL::SipperBuff::SipperRec::cameraNum, MLL::SipperBuff::SipperRec::eol, MLL::SipperBuff::SipperRec::pix0, MLL::SipperBuff::SipperRec::pix1, MLL::SipperBuff::SipperRec::pix10, MLL::SipperBuff::SipperRec::pix11, MLL::SipperBuff::SipperRec::pix2, MLL::SipperBuff::SipperRec::pix3, MLL::SipperBuff::SipperRec::pix4, MLL::SipperBuff::SipperRec::pix5, MLL::SipperBuff::SipperRec::pix6, MLL::SipperBuff::SipperRec::pix7, MLL::SipperBuff::SipperRec::pix8, MLL::SipperBuff::SipperRec::pix9, MLL::SipperBuff::SipperRec::raw, MLL::sf3Bit, MLL::sfBinary, MLL::sfUnKnown, and SIPPERRECSIZE.
Referenced by GuessFormatOfFile().
void MLL::SipperBuff::InvalidLine (bool _invalidLine) inline
Definition at line 65 of file SipperBuff.h.
bool MLL::SipperBuff::InvalidLine () const inline
Definition at line 75 of file SipperBuff.h.
Referenced by MLL::Sipper3Buff::GetNextLine().
virtual kkint32 MLL::SipperBuff::LineWidth () const inline virtual
Returns the width in pixels of the associated scanner file.
Definition at line 81 of file SipperBuff.h.
References MAXLINELEN.
void SipperBuff::Open (const KKStr & _fileName)
Definition at line 123 of file SipperBuff.cpp.
References KKB::endl(), eof, fileName, inFile, opened, KKB::osFOPEN(), and KKB::KKStr::Str().
Referenced by SipperBuff().
bool MLL::SipperBuff::Opened () const inline
Definition at line 76 of file SipperBuff.h.
Referenced by CreateSipperBuff(), MLL::Sipper3RevBuff::FileFormatGood(), MLL::Sipper3Buff::FileFormatGood(), MLL::SipperBuff4Bit::FileFormatGood(), GuessFormatOfFile(), and MLL::Sipper3Buff::Sipper3Buff().
kkuint32 MLL::SipperBuff::RecCount () const inline
Definition at line 77 of file SipperBuff.h.
void SipperBuff::ReportInstrumentData (uchar sensorId, bool text, uchar sensorData)
Definition at line 668 of file SipperBuff.cpp.
References curRow, KKB::KKStr::Empty(), fileName, instrumentDataManager, iOwnInstrumentDataManager, log, KKB::osAddSlash(), KKB::osGetCurrentDirectory(), KKB::osGetPathPartOfFile(), MLL::PicesVariables::ReportDir(), and MLL::InstrumentDataManager::ReportInstrumentData().
Referenced by MLL::Sipper3Buff::~Sipper3Buff().
void SipperBuff::Reset ()
Definition at line 100 of file SipperBuff.cpp.
References bytesDropped, curRow, eof, inFile, opened, and recCount.
Referenced by MLL::Sipper3RevBuff::FileFormatGood(), and MLL::Sipper3Buff::FileFormatGood().
void SipperBuff::ResetByteOffset (kkuint32 _byteOffset)
Definition at line 144 of file SipperBuff.cpp.
References byteOffset, KKB::endl(), and inFile.
kkint32 MLL::SipperBuff::ScanRate () const inline
Definition at line 78 of file SipperBuff.h.
void SipperBuff::SkipOneByte ()
Definition at line 165 of file SipperBuff.cpp.
References byteOffset, KKB::endl(), and inFile.
void SipperBuff::SkipToScanLine (kkuint32 scanLine) virtual
Definition at line 183 of file SipperBuff.cpp.
References curRow, and GetNextLine().
Referenced by MLL::InstrumentDataFileManager::GetOrigSipperImage().
void SipperBuff::SkipToScanLine (kkuint32 _scanLine, kkuint64 _byteOffset) virtual
Definition at line 206 of file SipperBuff.cpp.
References byteOffset, curRow, eof, and inFile.
Member Data Documentation
kkuint64 MLL::SipperBuff::byteOffset protected
Definition at line 151 of file SipperBuff.h.
Referenced by MLL::Sipper3Buff::GetNextLine(), ResetByteOffset(), MLL::Sipper3Buff::Sipper3Buff(), MLL::Sipper3RevBuff::Sipper3RevBuff(), MLL::SipperBuff3Bit::SipperBuff3Bit(), MLL::SipperBuffBinary::SipperBuffBinary(), SkipOneByte(), SkipToScanLine(), MLL::Sipper3Buff::~Sipper3Buff(), and MLL::Sipper3RevBuff::~Sipper3RevBuff().
kkuint32 MLL::SipperBuff::bytesDropped protected
Definition at line 150 of file SipperBuff.h.
Referenced by MLL::SipperBuff3Bit::GetNextLine(), and Reset().
kkuint32 MLL::SipperBuff::curRow protected
Definition at line 152 of file SipperBuff.h.
Referenced by MLL::SipperBuff4Bit::FileFormatGood(), MLL::Sipper3RevBuff::GetNextLine(), MLL::SipperBuff3Bit::GetNextLine(), MLL::SipperBuffBinary::GetNextLine(), MLL::Sipper3Buff::GetNextLine(), ReportInstrumentData(), Reset(), and SkipToScanLine().
kkuint64 MLL::SipperBuff::curRowByteOffset protected
Definition at line 153 of file SipperBuff.h.
Referenced by MLL::Sipper3Buff::GetNextLine(), and MLL::Sipper3RevBuff::~Sipper3RevBuff().
bool MLL::SipperBuff::eof protected
Definition at line 154 of file SipperBuff.h.
Referenced by DetermineCropSettings(), MLL::SipperBuff4Bit::FileFormatGood(), MLL::Sipper3RevBuff::GetNextLine(), MLL::SipperBuff3Bit::GetNextLine(), MLL::SipperBuffBinary::GetNextLine(), MLL::Sipper3Buff::GetNextLine(), Open(), Reset(), SkipToScanLine(), MLL::Sipper3Buff::~Sipper3Buff(), and MLL::Sipper3RevBuff::~Sipper3RevBuff().
KKStr MLL::SipperBuff::fileName protected
Definition at line 155 of file SipperBuff.h.
Referenced by Open(), ReportInstrumentData(), and SipperBuff().
FILE* MLL::SipperBuff::inFile protected
Definition at line 157 of file SipperBuff.h.
Referenced by MLL::Sipper3Buff::FileFormatGood(), MLL::SipperBuff4Bit::FileFormatGood(), Open(), Reset(), ResetByteOffset(), SkipOneByte(), SkipToScanLine(), MLL::Sipper3Buff::~Sipper3Buff(), MLL::Sipper3RevBuff::~Sipper3RevBuff(), and ~SipperBuff().
InstrumentDataManagerPtr MLL::SipperBuff::instrumentDataManager protected
Definition at line 158 of file SipperBuff.h.
Referenced by AssignSerialPorts(), ReportInstrumentData(), and ~SipperBuff().
bool MLL::SipperBuff::invalidLine protected
Set to true if invalid data is detected on a scan line.
Such as exceeding line length.
Definition at line 159 of file SipperBuff.h.
bool MLL::SipperBuff::iOwnInstrumentDataManager protected
Definition at line 156 of file SipperBuff.h.
Referenced by ReportInstrumentData(), and ~SipperBuff().
RunLog& MLL::SipperBuff::log protected
Definition at line 162 of file SipperBuff.h.
Referenced by ReportInstrumentData().
bool MLL::SipperBuff::opened protected
Definition at line 163 of file SipperBuff.h.
Referenced by Open(), Reset(), and ~SipperBuff().
kkuint32 MLL::SipperBuff::recCount protected
Definition at line 164 of file SipperBuff.h.
Referenced by Reset().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/SipperBuff.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/SipperBuff.cpp