Pices: MLL::ImageFeatures Class Reference
MLL::ImageFeatures Class Reference
Specialized version of MLL::FeatureVector that will be used to represent the features of a SIPPER Plankton image.
#include <ImageFeatures.h>
Public Types
typedef ImageFeatures * ImageFeaturesPtr
typedef KKB::kkint32 kkint32
typedef KKB::kkuint32 kkuint32
Public Types inherited from KKMLL::FeatureVector
typedef FeatureVector * FeatureVectorPtr
typedef float FVFloat
Public Member Functions
ImageFeatures (kkint32 _numOfFeatures)
ImageFeatures (const ImageFeatures &_image)
ImageFeatures (RasterSipper &_raster, MLClassPtr _mlClass, RasterSipperListPtr _saveImages, RunLog &_log)
ImageFeatures (const BmpImage &_image, MLClassPtr _mlClass, RasterSipperListPtr _saveImages, RunLog &_log)
ImageFeatures (KKStr _fileName, MLClassPtr _mlClass, bool &_successfull, RasterSipperListPtr _saveImages, RunLog &_log)
ImageFeatures (const FeatureVector &featureVector)
Smart copy constructor that will detect the underlying type of the source instance.
virtual ~ImageFeatures ()
void AreaMMSquare (float _areaMMSquare)
float AreaMMSquare () const
void CalcFeatures (RasterSipper &srcRaster, RasterSipperListPtr saveImages, RunLog &log)
void CentroidCol (FVFloat _centroidCol)
float CentroidCol () const
Centroid column with respect to image.
void CentroidRow (FVFloat _centroidRow)
float CentroidRow () const
Centroid row with respect to image.
void CtdDateTime (const KKB::DateTime &_ctdDateTime)
KKB::DateTime CtdDateTime () const
void Depth (FVFloat _depth)
FVFloat Depth () const
virtual ImageFeaturesPtr Duplicate () const
FVFloat FilledArea () const
void FlowRate1 (FVFloat _flowRate1)
FVFloat FlowRate1 () const
void FlowRate2 (FVFloat _flowRate2)
FVFloat FlowRate2 () const
void Fluorescence (FVFloat _fluorescence)
FVFloat Fluorescence () const
void Latitude (double _laditude)
double Latitude () const
FVFloat Length () const
void Longitude (double _longitude)
double Longitude () const
virtual kkint32 MemoryConsumedEstimated () const
void NumOfEdgePixels (kkint32 _numOfEdgePixels)
kkint32 NumOfEdgePixels () const
void Oxygen (FVFloat _oxygen)
FVFloat Oxygen () const
void ResetVersion (short newVersion)
void Salinity (FVFloat _salinity)
FVFloat Salinity () const
void SfCentroidCol (FVFloat _SfCentroidCol)
float SfCentroidCol () const
Centroid column with respect to whole Sipper File.
void SfCentroidRow (double _SfCentroidRow)
double SfCentroidRow () const
Centroid row with respect to whole Sipper File.
void Version (short _version)
short Version () const
FVFloat Width () const
Public Member Functions inherited from KKMLL::FeatureVector
FeatureVector (kkint32 _numOfFeatures)
FeatureVector (const FeatureVector &_example)
virtual ~FeatureVector ()
void AddFeatureData (kkint32 _featureNum, float _featureData)
void BreakTie (float _breakTie)
Update the BreakTie value.
float BreakTie () const
The difference in probability between the two most likely classes.
const KKStr & ClassName () const
Name of class that this example is assigned to.
void ExampleFileName (const KKStr &_exampleFileName)
Name of source of feature vector, ex: file name of image that the feature vector was computed from.
const KKStr & ExampleFileName () const
Name of file that this FeatureVector was computed from.
void FeatureData (kkint32 _featureNum, float _featureValue)
Assign a value to a specific feature number for the feature vector.
float FeatureData (kkint32 featureNum) const
const float * FeatureData () const
Returns as a pointer to the feature data itself.
float * FeatureDataAlter ()
Same as 'FeatureData() except you can modify the data.
const float * FeatureDataConst () const
bool FeatureDataValid ()
void MissingData (bool _missingData)
True indicates that not all the feature data was present when this example was loaded from a data file.
bool MissingData () const
True indicates that one or more features were missing.
void MLClass (MLClassPtr _mlClass)
Assign a class to this example.
MLClassPtr MLClass () const
Class that is example is assigned to.
const KKStr & MLClassName () const
Name of class that this example is assigned to.
kkint32 NumOfFeatures () const
Number of features in this FeatureVector.
bool operator== (FeatureVector &other_example) const
void OrigSize (float _origSize)
The value of Feature[0] before normalization.
float OrigSize () const
The value of Feature[0] before normalization.
void PredictedClass (MLClassPtr _predictedClass)
MLClassPtr PredictedClass () const
const KKStr & PredictedClassName () const
void Probability (float _probability)
Assign a prediction probability to this example.
float Probability () const
The probability assigned by classifier to the predicted class.
void ResetNumOfFeatures (kkint32 newNumOfFeatures)
Used to reallocate memory for feature data.
float TotalOfFeatureData () const
Returns the total of all Feature Attributes for this feature vector.
void TrainWeight (float _trainWeight)
Assign a specific example a higher weight for training purposes.
float TrainWeight () const
void Validated (bool _validated)
Indicated whether an expert has validated the class assignment.
bool Validated () const
void Version (kkint16 _version)
kkint16 Version () const
Static Public Attributes
static kkint32 FirstInstrumentDataField = 84
The first feature field that we get from a separate instrument data field.
static kkint32 NumSeperateInstrumentDataFields = 4
The number of features that come from Instrument data, ex: Oxygen or Depth.
Additional Inherited Members
Protected Member Functions inherited from KKMLL::FeatureVector
void AllocateFeatureDataArray ()
Used by container classes such as 'FeatureVectorList'.
Protected Attributes inherited from KKMLL::FeatureVector
float * featureData
kkint32 numOfFeatures
Detailed Description
Specialized version of MLL::FeatureVector that will be used to represent the features of a SIPPER Plankton image.
Author
Kurt Kramer
Used for the representation of a Single Plankton Image. You create an instance of this object for each single image you need to keep track of. There is a specialized version of MLL::FeatureFileIO called MLL::FeatureFileIOPices that is used to write and read feature Data files. What makes this class of MLL::FeatureVector special are the additional fields that are Plankton specific such as centroidCol, centroidRow, latitude, longitude, numOfEdgePixels, Centroid within SIPPEER file sfCentroidCol, sfCentroidRow and version.
The version number field is supposed to indicate which feature calculation routines were used. This way if there are changes the way features are calculated it can be detected during runtime if the features are up to date they need to be recomputed.
Definition at line 84 of file ImageFeatures.h.
Member Typedef Documentation
typedef ImageFeatures* MLL::ImageFeatures::ImageFeaturesPtr
Definition at line 87 of file ImageFeatures.h.
typedef KKB::kkint32 MLL::ImageFeatures::kkint32
Definition at line 89 of file ImageFeatures.h.
typedef KKB::kkuint32 MLL::ImageFeatures::kkuint32
Definition at line 90 of file ImageFeatures.h.
Constructor & Destructor Documentation
ImageFeatures::ImageFeatures (kkint32 _numOfFeatures)
Definition at line 170 of file ImageFeatures.cpp.
Referenced by Duplicate().
ImageFeatures::ImageFeatures (const ImageFeatures & _image)
Definition at line 187 of file ImageFeatures.cpp.
ImageFeatures::ImageFeatures (RasterSipper & _raster, MLClassPtr _mlClass, RasterSipperListPtr _saveImages, RunLog & _log)
Definition at line 235 of file ImageFeatures.cpp.
References CalcFeatures(), KKB::endl(), KKMLL::FeatureVector::ExampleFileName(), KKB::Raster::FileName(), KKMLL::FeatureVector::MLClass(), and KKB::osGetRootName().
ImageFeatures::ImageFeatures (const BmpImage & _image, MLClassPtr _mlClass, RasterSipperListPtr _saveImages, RunLog & _log)
Definition at line 206 of file ImageFeatures.cpp.
References CalcFeatures(), KKMLL::FeatureVector::ExampleFileName(), KKB::BmpImage::FileName(), and KKMLL::FeatureVector::MLClass().
ImageFeatures::ImageFeatures (KKStr _fileName, MLClassPtr _mlClass, bool & _successfull, RasterSipperListPtr _saveImages, RunLog & _log)
Definition at line 269 of file ImageFeatures.cpp.
References KKB::BmpImage::AreThereEdgePixels(), CalcFeatures(), KKB::Raster::ConnectedComponent(), KKB::endl(), KKMLL::FeatureVector::ExampleFileName(), KKMLL::FeatureVector::featureData, KKMLL::FeatureVector::MLClass(), KKMLL::FeatureVector::NumOfFeatures(), KKB::osGetFileExtension(), KKB::BmpImage::ReAllocateForBiggerScreen(), KKB::BmpImage::Save(), and KKB::KKStr::Upper().
ImageFeatures::ImageFeatures (const FeatureVector & featureVector)
Smart copy constructor that will detect the underlying type of the source instance.
This constructor will detect what the underlying type of 'featureVector' is.     *
If (underlying type is a 'ImageFeatures' object)  then                           *
  | Information that is particular to a 'ImageFeatures' object will be extracted *
  | from the 'FeatureVector' object.                                             *
else                                                                             *
  | Info that is particular to a 'ImageFeatures' object will be set to default   *
  | values.                                                                      *
Definition at line 340 of file ImageFeatures.cpp.
References AreaMMSquare(), CentroidCol(), CentroidRow(), CtdDateTime(), Latitude(), Longitude(), NumOfEdgePixels(), SfCentroidCol(), SfCentroidRow(), and Version().
ImageFeatures::~ImageFeatures () virtual
Definition at line 374 of file ImageFeatures.cpp.
Member Function Documentation
void MLL::ImageFeatures::AreaMMSquare (float _areaMMSquare) inline
Definition at line 142 of file ImageFeatures.h.
Referenced by ImageFeatures().
float MLL::ImageFeatures::AreaMMSquare () const inline
Definition at line 162 of file ImageFeatures.h.
void ImageFeatures::CalcFeatures (RasterSipper & srcRaster, RasterSipperListPtr saveImages, RunLog & log)
Definition at line 455 of file ImageFeatures.cpp.
References KKMLL::FeatureVector::AllocateFeatureDataArray(), KKB::Raster::BackgroundPixelValue(), KKB::Raster::CalcArea(), KKB::Raster::CalcAreaAndIntensityFeatures(), KKB::Raster::CalcOrientationAndEigerRatio(), KKB::Raster::CentralMoments(), KKB::Raster::CentralMomentsWeighted(), KKB::Raster::CentroidCol(), KKB::Raster::CentroidRow(), KKB::Raster::Closing(), KKB::ConvexHull::ConvexArea(), CurrentFeatureFileVersionNum, KKB::Raster::Dilation(), KKB::Raster::DrawPointList(), KKB::Raster::Edge(), KKB::KKStr::Empty(), KKB::endl(), KKB::Raster::Erosion(), KKMLL::FeatureVector::ExampleFileName(), MLL::RasterSipper::FastFourier(), KKMLL::FeatureVector::featureData, KKB::Raster::FillHole(), KKB::ConvexHull::Filter(), KKB::Raster::FindBoundingBox(), KKB::ContourFollower::FollowContour(), KKB::Raster::ForegroundPixelCount(), KKB::Raster::ForegroundPixelValue(), KKB::Raster::FourierExtractFeatures(), KKB::ContourFollower::GenerateContourList(), KKB::Raster::Green(), KKB::Raster::Height(), KKB::Min(), KKMLL::FeatureVector::NumOfFeatures(), KKMLL::FeatureVector::numOfFeatures, KKB::Raster::Opening(), KKMLL::FeatureVector::OrigSize(), KKB::osParseFileSpec(), MLL::PicesVariables::ParseImageFileName(), MLL::FeatureFileIOPices::PlanktonMaxNumOfFields(), KKMLL::FeatureVector::Probability(), MLL::RasterSipper::ReduceByEvenMultiple(), MLL::RasterSipper::ReversedImage(), MLL::RasterSipper::Rotate(), KKB::StrFormatDouble(), KKB::StrFormatInt(), MLL::RasterSipper::ThinContour(), MLL::RasterSipper::TurnIntoSipperRasterPtr(), TwoPie, and KKB::Raster::Width().
Referenced by ImageFeatures(), and MLL::ImageFeaturesList::RecalcFeatureValuesFromImagesInDirTree().
void MLL::ImageFeatures::CentroidCol (FVFloat _centroidCol) inline
Definition at line 143 of file ImageFeatures.h.
Referenced by MLL::ImageFeaturesList::FixSipperFileScanLineAndColFields(), ImageFeatures(), MLL::FeatureFileIOPices::LoadFile(), ImageExtractionManager::DataBaseUpdateThread::Run(), and MLL::FeatureFileIOPices::SaveFile().
float MLL::ImageFeatures::CentroidCol () const inline
Centroid column with respect to image.
Definition at line 163 of file ImageFeatures.h.
void MLL::ImageFeatures::CentroidRow (FVFloat _centroidRow) inline
Definition at line 144 of file ImageFeatures.h.
Referenced by MLL::ImageFeaturesList::FixSipperFileScanLineAndColFields(), ImageFeatures(), MLL::FeatureFileIOPices::LoadFile(), ImageExtractionManager::DataBaseUpdateThread::Run(), and MLL::FeatureFileIOPices::SaveFile().
float MLL::ImageFeatures::CentroidRow () const inline
Centroid row with respect to image.
Definition at line 164 of file ImageFeatures.h.
void MLL::ImageFeatures::CtdDateTime (const KKB::DateTime & _ctdDateTime) inline
Definition at line 145 of file ImageFeatures.h.
Referenced by ImageFeatures().
KKB::DateTime MLL::ImageFeatures::CtdDateTime () const inline
Definition at line 166 of file ImageFeatures.h.
void MLL::ImageFeatures::Depth (FVFloat _depth) inline
Definition at line 146 of file ImageFeatures.h.
Referenced by PicesInterface::PicesFeatureVector::AddInstrumentData(), MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::DataBase::FeatureDataRecLoad(), MLL::FeatureFileIOPices::FeatureDataReSink(), MLL::FeatureFileIOPices::LoadFile(), and ImageExtractionManager::DataBaseUpdateThread::Run().
FVFloat MLL::ImageFeatures::Depth () const inline
Definition at line 165 of file ImageFeatures.h.
ImageFeaturesPtr ImageFeatures::Duplicate () const virtual
Reimplemented from KKMLL::FeatureVector.
Definition at line 392 of file ImageFeatures.cpp.
References ImageFeatures().
FVFloat MLL::ImageFeatures::FilledArea () const inline
Definition at line 167 of file ImageFeatures.h.
void MLL::ImageFeatures::FlowRate1 (FVFloat _flowRate1) inline
Definition at line 148 of file ImageFeatures.h.
Referenced by PicesInterface::PicesFeatureVector::AddInstrumentData(), MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::DataBase::FeatureDataRecLoad(), MLL::FeatureFileIOPices::FeatureDataReSink(), and MLL::FeatureFileIOPices::LoadFile().
FVFloat MLL::ImageFeatures::FlowRate1 () const inline
Definition at line 169 of file ImageFeatures.h.
void MLL::ImageFeatures::FlowRate2 (FVFloat _flowRate2) inline
Definition at line 149 of file ImageFeatures.h.
Referenced by PicesInterface::PicesFeatureVector::AddInstrumentData(), MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::DataBase::FeatureDataRecLoad(), MLL::FeatureFileIOPices::FeatureDataReSink(), and MLL::FeatureFileIOPices::LoadFile().
FVFloat MLL::ImageFeatures::FlowRate2 () const inline
Definition at line 170 of file ImageFeatures.h.
void MLL::ImageFeatures::Fluorescence (FVFloat _fluorescence) inline
Definition at line 147 of file ImageFeatures.h.
Referenced by PicesInterface::PicesFeatureVector::AddInstrumentData(), MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::DataBase::FeatureDataRecLoad(), MLL::FeatureFileIOPices::FeatureDataReSink(), and MLL::FeatureFileIOPices::LoadFile().
FVFloat MLL::ImageFeatures::Fluorescence () const inline
Definition at line 168 of file ImageFeatures.h.
void MLL::ImageFeatures::Latitude (double _laditude) inline
Definition at line 150 of file ImageFeatures.h.
Referenced by MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::DataBase::FeatureDataRecLoad(), MLL::FeatureFileIOPices::FeatureDataReSink(), ImageFeatures(), MLL::FeatureFileIOPices::LoadFile(), MLL::FeatureFileIOPices::LoadInSubDirectoryTree(), and MLL::FeatureFileIOPices::SaveFile().
double MLL::ImageFeatures::Latitude () const inline
Definition at line 171 of file ImageFeatures.h.
FVFloat MLL::ImageFeatures::Length () const inline
Definition at line 172 of file ImageFeatures.h.
void MLL::ImageFeatures::Longitude (double _longitude) inline
Definition at line 151 of file ImageFeatures.h.
Referenced by MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::DataBase::FeatureDataRecLoad(), MLL::FeatureFileIOPices::FeatureDataReSink(), ImageFeatures(), MLL::FeatureFileIOPices::LoadFile(), MLL::FeatureFileIOPices::LoadInSubDirectoryTree(), and MLL::FeatureFileIOPices::SaveFile().
double MLL::ImageFeatures::Longitude () const inline
Definition at line 173 of file ImageFeatures.h.
kkint32 ImageFeatures::MemoryConsumedEstimated () const virtual
Reimplemented from KKMLL::FeatureVector.
Definition at line 379 of file ImageFeatures.cpp.
Referenced by ImageExtractionManager::ExtractedImage::MemoryConsumedEstimated().
void MLL::ImageFeatures::NumOfEdgePixels (kkint32 _numOfEdgePixels) inline
Definition at line 152 of file ImageFeatures.h.
Referenced by ImageFeatures(), MLL::FeatureFileIOPices::LoadFile(), and MLL::FeatureFileIOPices::SaveFile().
kkint32 MLL::ImageFeatures::NumOfEdgePixels () const inline
Definition at line 174 of file ImageFeatures.h.
void MLL::ImageFeatures::Oxygen (FVFloat _oxygen) inline
Definition at line 153 of file ImageFeatures.h.
Referenced by PicesInterface::PicesFeatureVector::AddInstrumentData(), MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::DataBase::FeatureDataRecLoad(), MLL::FeatureFileIOPices::FeatureDataReSink(), and MLL::FeatureFileIOPices::LoadFile().
FVFloat MLL::ImageFeatures::Oxygen () const inline
Definition at line 175 of file ImageFeatures.h.
void ImageFeatures::ResetVersion (short newVersion)
Definition at line 399 of file ImageFeatures.cpp.
References Version().
void MLL::ImageFeatures::Salinity (FVFloat _salinity) inline
Definition at line 154 of file ImageFeatures.h.
Referenced by PicesInterface::PicesFeatureVector::AddInstrumentData(), MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::DataBase::FeatureDataRecLoad(), MLL::FeatureFileIOPices::FeatureDataReSink(), and MLL::FeatureFileIOPices::LoadFile().
FVFloat MLL::ImageFeatures::Salinity () const inline
Definition at line 176 of file ImageFeatures.h.
void MLL::ImageFeatures::SfCentroidCol (FVFloat _SfCentroidCol) inline
Definition at line 156 of file ImageFeatures.h.
Referenced by MLL::ImageFeaturesList::FixSipperFileScanLineAndColFields(), ImageFeatures(), MLL::FeatureFileIOPices::LoadFile(), and MLL::FeatureFileIOPices::SaveFile().
float MLL::ImageFeatures::SfCentroidCol () const inline
Centroid column with respect to whole Sipper File.
Definition at line 177 of file ImageFeatures.h.
void MLL::ImageFeatures::SfCentroidRow (double _SfCentroidRow) inline
Definition at line 157 of file ImageFeatures.h.
Referenced by MLL::ImageFeaturesList::CalculateDensitesByQuadrat(), MLL::ImageFeaturesList::ExtractPositionsByMeter(), MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::DataBase::FeatureDataRecLoad(), MLL::ImageFeaturesList::FixSipperFileScanLineAndColFields(), ImageFeatures(), MLL::FeatureFileIOPices::LoadFile(), and MLL::FeatureFileIOPices::SaveFile().
double MLL::ImageFeatures::SfCentroidRow () const inline
Centroid row with respect to whole Sipper File.
Definition at line 178 of file ImageFeatures.h.
void MLL::ImageFeatures::Version (short _version) inline
Definition at line 159 of file ImageFeatures.h.
Referenced by ImageFeatures(), and MLL::FeatureFileIOPices::LoadFile().
short MLL::ImageFeatures::Version () const inline
Definition at line 179 of file ImageFeatures.h.
Referenced by ResetVersion().
FVFloat MLL::ImageFeatures::Width () const inline
Definition at line 180 of file ImageFeatures.h.
Member Data Documentation
kkint32 ImageFeatures::FirstInstrumentDataField = 84 static
The first feature field that we get from a separate instrument data field.
see 'NumSeperateInstrumentDataFields' below.
Definition at line 194 of file ImageFeatures.h.
kkint32 ImageFeatures::NumSeperateInstrumentDataFields = 4 static
The number of features that come from Instrument data, ex: Oxygen or Depth.
This is the number of fields that are not going to be stored in the regular feature file but in separate instrument data files that will be accessed by SiperFile name and scan line number.
Definition at line 196 of file ImageFeatures.h.
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/ImageFeatures.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/ImageFeatures.cpp