Pices: MLL::Instrument Class Reference
MLL::Instrument Class Reference abstract
#include <Instrument.h>
Public Types
typedef Instrument * InstrumentPtr
typedef KKB::kkint32 kkint32
typedef KKB::kkint64 kkint64
typedef KKB::kkuint32 kkuint32
typedef KKB::kkuint64 kkuint64
Public Member Functions
Instrument (const KKStr &_shortName, const KKStr &_description)
virtual ~Instrument ()
virtual InstrumentDataReportPtr CreateInstrumentDataReporter (InstrumentDataManagerPtr _manager, const KKStr &_reportDir, kkint32 _instrumentId)=0
const KKStr & Description () const
virtual bool Other () const
const KKStr & ShortName () const
Static Public Member Functions
static void FinalCleanUp ()
Deletes objects pointed to by 'instruments[]'; this way the don't confuse the memory dump that occurs at the end of a program in Debug Mode.
static InstrumentPtr LookUpByShortName (const KKStr &_shortName)
static InstrumentPtr OtherInstrument ()
Detailed Description
Definition at line 24 of file Instrument.h.
Member Typedef Documentation
typedef Instrument* MLL::Instrument::InstrumentPtr
Definition at line 32 of file Instrument.h.
typedef KKB::kkint32 MLL::Instrument::kkint32
Definition at line 27 of file Instrument.h.
typedef KKB::kkint64 MLL::Instrument::kkint64
Definition at line 29 of file Instrument.h.
typedef KKB::kkuint32 MLL::Instrument::kkuint32
Definition at line 28 of file Instrument.h.
typedef KKB::kkuint64 MLL::Instrument::kkuint64
Definition at line 30 of file Instrument.h.
Constructor & Destructor Documentation
Instrument::Instrument (const KKStr & _shortName, const KKStr & _description)
Definition at line 43 of file Instrument.cpp.
Instrument::~Instrument () virtual
Definition at line 53 of file Instrument.cpp.
Member Function Documentation
virtual InstrumentDataReportPtr MLL::Instrument::CreateInstrumentDataReporter (InstrumentDataManagerPtr _manager, const KKStr & _reportDir, kkint32 _instrumentId) pure virtual
Implemented in MLL::InstrumentOther, MLL::InstrumentBatteryMeters, MLL::InstrumentInclinationMeter, MLL::InstrumentGPS, and MLL::InstrumentCTD.
Referenced by MLL::InstrumentDataReport::CreateInstrumentDataReport().
const KKStr& MLL::Instrument::Description () const inline
Definition at line 41 of file Instrument.h.
void Instrument::FinalCleanUp () static
Deletes objects pointed to by 'instruments[]'; this way the don't confuse the memory dump that occurs at the end of a program in Debug Mode.
Definition at line 95 of file Instrument.cpp.
Referenced by MLL::InstrumentOther::InstrumentOther().
InstrumentPtr Instrument::LookUpByShortName (const KKStr & _shortName) static
Definition at line 66 of file Instrument.cpp.
References ShortName(), and KKB::KKStr::ToUpper().
Referenced by OtherInstrument(), MLL::PortAssignment::PortAssignment(), SearchFieldIdx(), and MLL::DataBase::SipperDeploymentDelete().
bool Instrument::Other () const virtual
Definition at line 59 of file Instrument.cpp.
Referenced by MLL::PortAssignment::HeaderStr().
InstrumentPtr Instrument::OtherInstrument () static
Definition at line 88 of file Instrument.cpp.
References LookUpByShortName().
const KKStr& MLL::Instrument::ShortName () const inline
Definition at line 40 of file Instrument.h.
Referenced by PicesInterface::PicesSipperFile::!PicesSipperFile(), MLL::PortAssignment::HeaderStr(), LookUpByShortName(), and MLL::PortAssignment::ShortName().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/Instrument.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/Instrument.cpp