Pices: KKMLL::ClassProbList Class Reference
KKMLL::ClassProbList Class Reference
#include <ClassProb.h>
Classes
class ProbabilityComparer
class VotesComparer
Public Types
typedef ClassProbList * ClassProbListPtr
Public Types inherited from KKB::KKQueue< ClassProb >
typedef std::vector< ClassProb * >
::const_iterator const_iterator
typedef std::vector< ClassProb * >
::iterator iterator
Public Member Functions
ClassProbList ()
ClassProbList (bool owner)
ClassProbList (const ClassProbList &pairList)
void AddIn (const ClassProbListPtr otherPredictions)
Adds the contents of 'otherPredictions' to this list.
virtual void DeleteEntry (ClassProbPtr cp)
virtual void DeleteEntry (kkuint32 idx)
const ClassProbPtr LookUp (MLClassPtr targetClass) const
kkint32 LookUpPlace (MLClassPtr targetClass) const
Returns the position that 'targetClass' has in the order; good time to use would be after sorting by probability.
kkint32 MemoryConsumedEstimated () const
void MergeIn (const ClassProbPtr cp)
Adds the Prediction in 'cp' into this list.
void MergeIn (MLClassPtr target, double probability, float votes)
Adds the prediction of 'target' with 'probability' into this list.
void MergeIn (MLClassPtr target, const ClassProbListPtr subPredictions)
Merges in the predictions in 'subPredictions' by replacing the entry in our list with label 'target' with contents of 'subPredictions'.
void NormalizeToOne ()
Will normalize the list of predictions such that the total probability will equal 1.0 and total votes will = (N)(N-1)/2 where N = number of predictions.
virtual void PushOnBack (ClassProbPtr cp)
virtual void PushOnFront (ClassProbPtr cp)
void ReadXML (XmlStream &s, XmlTagConstPtr tag, RunLog &log)
void SortByClassName ()
void SortByProbability (bool highToLow=true)
void SortByVotes (bool highToLow=true)
void WriteXML (const KKStr &varName, ostream &o) const
Public Member Functions inherited from KKB::KKQueue< ClassProb >
KKQueue (bool _owner=true)
KKQueue (const KKQueue &q, bool _owner)
Constructor, similar to the Copy Constructor except that you can control whether it duplicates the contents.
virtual ~KKQueue ()
void Add (EntryPtr _entry)
same as PushOnBack
void AddFirst (EntryPtr _entry)
same as PushOnFront
virtual void AddQueue (const KKQueue &q)
EntryPtr BackOfQueue () const
Returns pointer of last element in the container without removing it.
void Compress ()
No longer does anything.
void DeleteContents ()
Empties the container, if 'owner' is set to true will call the destructor on each element.
void DeleteEntry (EntryPtr _entry)
Removes from KKQueue the entry who's pointer = '_entry'.
void DeleteEntry (kkuint32 _idx)
Removes from KKQueue the entry who's index = '_idx'.
KKQueue * DuplicateListAndContents () const
Creates a new container including duplicating the contents, which also makes the new instance the owner of those contents.
kkuint32 FindTheKthElement (kkuint32 k, Functor pred)
EntryPtr FrontOfQueue () const
Returns a pointer to the element that is at from of the queue with out removing it from the queue.
EntryPtr GetFirst () const
EntryPtr GetLast () const
EntryPtr IdxToPtr (kkuint32 idx) const
Returns back a pointer to the element who's index is 'idx'.
kkint32 LocateEntry (EntryConstPtr _entry) const
Returns the index of the element who's address is '_entry'.
EntryPtr LookAtBack () const
Returns pointer to element at Back of container with out removing it from the container.
EntryPtr LookAtFront () const
Returns pointer to element at Front of container with out removing it from the container.
bool operator!= (const KKQueue< ClassProb > &rightSide) const
returns False if NOT every entry in both containers point to the same elements
KKQueue & operator= (const KKQueue &q)
Assignment Operator.
bool operator== (const KKQueue< ClassProb > &rightSide) const
Returns True if every entry in both containers point to the same elements.
ClassProb & operator[] (kkuint32 i) const
Returns a reference to element indexed by 'i'.
bool Owner () const
void Owner (bool _owner)
You can specify who owns the contents of the container.
virtual EntryPtr PopFromBack ()
Removes the last element in the container and returns its pointer.
virtual EntryPtr PopFromFront ()
Removes the first element in the container and returns its pointer.
kkint32 PtrToIdx (EntryConstPtr _entry) const
returns the index of the 'entry' that has the same pointer as '_entry', if none found returns -1
virtual void PushOnBack (EntryPtr _entry)
Adds '_entry' to the End of the container.
virtual void PushOnFront (EntryPtr _entry)
Adds '_entry' to the Front of the container.
kkint32 QueueSize () const
Same as calling vector<>::size().
void RandomizeOrder ()
void RandomizeOrder (kkint64 seed)
void RandomizeOrder (RandomNumGenerator &randomVariable)
EntryPtr RemoveFirst ()
same as PopFromFront
EntryPtr RemoveLast ()
same as PopFromBack
void SetIdxToPtr (kkuint32 _idx, ClassProb *_ptr)
void SwapIndexes (size_t idx1, size_t idx2)
Static Public Member Functions
static ClassProbListPtr CreateFromXMLStream (istream &i)
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Protected Member Functions inherited from KKB::KKQueue< ClassProb >
KKQueue (const KKQueue &q)
Copy Constructor, will create a new instance.
Detailed Description
Definition at line 46 of file ClassProb.h.
Member Typedef Documentation
typedef ClassProbList* KKMLL::ClassProbList::ClassProbListPtr
Definition at line 49 of file ClassProb.h.
Constructor & Destructor Documentation
ClassProbList::ClassProbList ()
Definition at line 42 of file ClassProb.cpp.
Referenced by CreateFromXMLStream().
ClassProbList::ClassProbList (bool owner)
Definition at line 48 of file ClassProb.cpp.
ClassProbList::ClassProbList (const ClassProbList & pairList)
Definition at line 55 of file ClassProb.cpp.
References KKB::KKQueue< ClassProb >::Owner(), and PushOnBack().
Member Function Documentation
void ClassProbList::AddIn (const ClassProbListPtr otherPredictions)
Adds the contents of 'otherPredictions' to this list.
there os not assumption that this list or 'otherPredictions' sum up to "1.0".
Definition at line 246 of file ClassProb.cpp.
References MergeIn().
Referenced by KKMLL::ModelDual::ProbabilitiesByClass().
ClassProbListPtr ClassProbList::CreateFromXMLStream (istream & i) static
Definition at line 362 of file ClassProb.cpp.
References ClassProbList(), KKMLL::MLClass::CreateNewMLClass(), KKB::KKStr::Empty(), KKB::KKStr::ExtractToken2(), KKB::KKStr::ExtractTokenDouble(), KKB::osReadRestOfLine(), PushOnBack(), and KKB::KKStr::StartsWith().
void ClassProbList::DeleteEntry (ClassProbPtr cp) virtual
Definition at line 187 of file ClassProb.cpp.
References KKMLL::ClassProb::classLabel.
Referenced by DeleteEntry(), and MergeIn().
void ClassProbList::DeleteEntry (kkuint32 idx) virtual
Definition at line 198 of file ClassProb.cpp.
References DeleteEntry(), KKB::endl(), KKB::KKQueue< ClassProb >::IdxToPtr(), and KKB::StrFormatInt().
const ClassProbPtr ClassProbList::LookUp (MLClassPtr targetClass) const
Definition at line 160 of file ClassProb.cpp.
Referenced by MergeIn(), KKMLL::ModelDual::ProbabilitiesByClass(), and KKMLL::Classifier2::ProbabilitiesByClass().
kkint32 ClassProbList::LookUpPlace (MLClassPtr targetClass) const
Returns the position that 'targetClass' has in the order; good time to use would be after sorting by probability.
Definition at line 174 of file ClassProb.cpp.
References KKMLL::ClassProb::classLabel, and KKB::KKQueue< ClassProb >::IdxToPtr().
kkint32 ClassProbList::MemoryConsumedEstimated () const
Definition at line 68 of file ClassProb.cpp.
Referenced by KKMLL::TrainingProcess2::MemoryConsumedEstimated().
void ClassProbList::MergeIn (const ClassProbPtr cp)
Adds the Prediction in 'cp' into this list.
If the class indicated by 'cp->classLabel' already exist in this list will then add to existing entry otherwise will create a new entry for the class.
Definition at line 268 of file ClassProb.cpp.
References KKMLL::ClassProb::classLabel, KKMLL::ClassProb::probability, and KKMLL::ClassProb::votes.
Referenced by AddIn(), MergeIn(), and KKMLL::ModelDual::ProbabilitiesByClass().
void ClassProbList::MergeIn (MLClassPtr target, double probability, float votes)
Adds the prediction of 'target' with 'probability' into this list.
If the class indicated by 'target' already exist in this list will then add to existing entry otherwise will create a new entry for the class.
Definition at line 276 of file ClassProb.cpp.
References LookUp(), KKMLL::ClassProb::probability, PushOnBack(), and KKMLL::ClassProb::votes.
void ClassProbList::MergeIn (MLClassPtr target, const ClassProbListPtr subPredictions)
Merges in the predictions in 'subPredictions' by replacing the entry in our list with label 'target' with contents of 'subPredictions'.
It is assumed that the sum of probabilities of 'subPredictions' is equal to 1.0.
Definition at line 301 of file ClassProb.cpp.
References KKMLL::ClassProb::classLabel, DeleteEntry(), LookUp(), MergeIn(), KKMLL::ClassProb::probability, and KKMLL::ClassProb::votes.
void ClassProbList::NormalizeToOne ()
Will normalize the list of predictions such that the total probability will equal 1.0 and total votes will = (N)(N-1)/2 where N = number of predictions.
Definition at line 336 of file ClassProb.cpp.
References KKMLL::ClassProb::probability, and KKMLL::ClassProb::votes.
Referenced by KKMLL::ModelDual::ProbabilitiesByClass().
void ClassProbList::PushOnBack (ClassProbPtr cp) virtual
Definition at line 212 of file ClassProb.cpp.
References KKMLL::ClassProb::classLabel, and KKB::endl().
Referenced by ClassProbList(), CreateFromXMLStream(), KKMLL::FeatureVectorList::GetClassDistribution(), MergeIn(), KKMLL::ModelKnn::ProbabilitiesByClass(), KKMLL::ModelSvmBase::ProbabilitiesByClass(), KKMLL::ModelOldSVM::ProbabilitiesByClass(), and ReadXML().
void ClassProbList::PushOnFront (ClassProbPtr cp) virtual
Definition at line 229 of file ClassProb.cpp.
References KKMLL::ClassProb::classLabel, and KKB::endl().
void ClassProbList::ReadXML (XmlStream & s, XmlTagConstPtr tag, RunLog & log)
Definition at line 423 of file ClassProb.cpp.
References KKB::XmlContent::Content(), KKMLL::MLClass::CreateNewMLClass(), KKB::KKStr::Empty(), KKB::endl(), KKB::KKStrParser::GetNextToken(), KKB::XmlStream::GetNextToken(), KKB::KKStrParser::GetNextTokenDouble(), KKB::KKStrParser::GetNextTokenFloat(), KKB::RunLog::Level(), PushOnBack(), and KKB::KKStrParser::TrimWhiteSpace().
void ClassProbList::SortByClassName ()
Definition at line 84 of file ClassProb.cpp.
void ClassProbList::SortByProbability (bool highToLow = true)
Definition at line 143 of file ClassProb.cpp.
Referenced by KKMLL::ModelUsfCasCor::ProbabilitiesByClass(), and KKMLL::ModelOldSVM::ProbabilitiesByClass().
void ClassProbList::SortByVotes (bool highToLow = true)
Definition at line 151 of file ClassProb.cpp.
Referenced by KKMLL::ModelSvmBase::ProbabilitiesByClass(), and KKMLL::ModelOldSVM::ProbabilitiesByClass().
void ClassProbList::WriteXML (const KKStr & varName, ostream & o) const
Definition at line 400 of file ClassProb.cpp.
References KKB::XmlTag::AddAtribute(), KKMLL::ClassProb::classLabel, KKB::KKStr::Empty(), KKB::endl(), KKMLL::ClassProb::probability, KKMLL::ClassProb::votes, and KKB::XmlTag::WriteXML().
Referenced by KKMLL::TrainingProcess2::WriteXML().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/KSquareLibraries/KKMachineLearning/ClassProb.h
C:/Users/kurtk_000/GitHub/KSquareLibraries/KKMachineLearning/ClassProb.cpp