Pices: PicesCommander.ChartSizeDistribution Class Reference
PicesCommander.ChartSizeDistribution Class Reference
Public Member Functions
ChartSizeDistribution (String _cruise, String _station, String _deployment, PicesClass _classToPlot, PicesClassList _classes, PicesClassList _activeClasses, String _rootDir)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Detailed Description
Definition at line 17 of file ChartSizeDistribution.cs.
Constructor & Destructor Documentation
PicesCommander.ChartSizeDistribution.ChartSizeDistribution (String _cruise, String _station, String _deployment, PicesClass _classToPlot, PicesClassList _classes, PicesClassList _activeClasses, String _rootDir) inline
Definition at line 77 of file ChartSizeDistribution.cs.
References PicesInterface::PicesImageSizeDistribution.AddIn(), PicesInterface::PicesMsgQueue.AddMsg(), PicesInterface::OSservices.AddSlash(), PicesInterface::PicesDataBase.CancelFlag, PicesInterface::PicesClass.Children, PicesInterface::PicesDataBase.Close(), PicesInterface::PicesSipperVariables.ConfigurationDirectory(), PicesInterface::PicesSipperDeployment.DeploymentNum, PicesInterface::PicesImageSizeDistributionRow.Depth, PicesInterface::PicesImageSizeDistribution.DepthBinSize, PicesInterface::PicesSipperDeployment.Description, PicesInterface::PicesImageSizeDistributionRow.Distribution(), PicesInterface::PicesGoalKeeper.EndBlock(), PicesInterface::PicesImageSizeDistribution.GetDepthBin(), PicesInterface::OSservices.GetFileExtension(), PicesInterface::PicesDataBase.GetGlobalDatabaseManagerNewInstance(), PicesInterface::PicesMsgQueue.GetNextMsg(), PicesInterface::OSservices.GetPathPartOfFile(), PicesInterface::PicesImageSizeDistribution.GetSizeBucketStats(), PicesInterface::PicesClassList.GetUniqueClass(), PicesInterface::PicesImageSizeDistribution.IdentifySizeBucket(), PicesInterface::PicesImageSizeDistributionRow.ImageCount, PicesInterface::PicesDataBase.ImagesQueryDeploymentSizeRange(), PicesInterface::PicesDataBase.ImagesSizeDistributionByDepth(), PicesInterface::PicesImageSizeDistribution.IntegratedDensityDistribution(), PicesInterface::PicesClass.Name, PicesInterface::PicesImageSizeDistribution.NumDepthBins, PicesInterface::PicesImageSizeDistribution.NumSizeBuckets, PicesInterface::PicesSipperVariables.PicesReportDir(), PicesInterface::OSservices.RemoveExtension(), SipperFile.SelectAPicesClass.SelectedClass, SipperFile.SelectAPicesClass.SelectionMade, PicesInterface::PicesImageSizeDistribution.SizeEndValues(), PicesInterface::PicesImageSizeDistribution.SizeStartValues(), PicesInterface::PicesGoalKeeper.StartBlock(), PicesInterface::PicesSipperDeployment.StationName, PicesInterface::PicesKKStr.StrToBool(), PicesInterface::PicesKKStr.StrToFloat(), PicesInterface::PicesKKStr.StrToInt(), PicesInterface::PicesDataBase.ThreadEnd(), PicesInterface::PicesDataBase.ThreadInit(), PicesInterface::PicesImageSizeDistributionRow.TotalFilledArea, PicesInterface::PicesImageSizeDistributionRow.TotalPixels, PicesInterface::PicesImageSizeDistributionRow.VolumneSampled, and PicesInterface::PicesRunLog.Writeln().
Member Function Documentation
override void PicesCommander.ChartSizeDistribution.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file ChartSizeDistribution.Designer.cs.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/ChartSizeDistribution.cs
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/ChartSizeDistribution.Designer.cs