Pices: KKMLL::BinaryClassParmsList Class Reference
KKMLL::BinaryClassParmsList Class Reference
#include <BinaryClassParms.h>
Public Types
typedef BinaryClassParmsList * BinaryClassParmsListPtr
Public Types inherited from KKB::KKQueue< BinaryClassParms >
typedef std::vector< BinaryClassParms * >::const_iterator const_iterator
typedef std::vector< BinaryClassParms * >::iterator iterator
Public Member Functions
BinaryClassParmsList ()
BinaryClassParmsList (bool _owner)
BinaryClassParmsList (const BinaryClassParmsList &binaryClassList, bool _owner)
~BinaryClassParmsList ()
BinaryClassParmsList * DuplicateListAndContents () const
float FeatureCountNet (FileDescPtr fileDesc) const
Returns the Average number of selected features.
BinaryClassParmsPtr LookUp (MLClassPtr _class1, MLClassPtr _class2) const
kkint32 MemoryConsumedEstimated () const
virtual void PushOnBack (BinaryClassParmsPtr binaryParms)
virtual void PushOnFront (BinaryClassParmsPtr binaryParms)
void ReadXML (FILE *i, FileDescPtr fileDesc, RunLog &log)
void ReadXML (std::istream &i, FileDescPtr fileDesc, RunLog &log)
virtual void ReadXML (XmlStream &s, XmlTagConstPtr tag, VolConstBool &cancelFlag, RunLog &log)
void WriteXML (std::ostream &o) const
virtual void WriteXML (const KKStr &varName, std::ostream &o) const
Public Member Functions inherited from KKB::KKQueue< BinaryClassParms >
KKQueue (bool _owner=true)
KKQueue (const KKQueue &q, bool _owner)
Constructor, similar to the Copy Constructor except that you can control whether it duplicates the contents.
virtual ~KKQueue ()
Virtual destructor; if owns its contents will also call the destructor on each one entry that it contains.
virtual void Add (EntryPtr _entry)
same as PushOnBack
virtual void AddFirst (EntryPtr _entry)
same as PushOnFront
virtual void AddQueue (const KKQueue &q)
Add the contents of a separate KKQueue container to this container.
EntryPtr BackOfQueue () const
Returns pointer of last element in the container without removing it.
void DeleteContents ()
Empties the container, if 'owner' is set to true will call the destructor on each element.
void DeleteEntry (EntryPtr _entry)
Removes from KKQueue the entry who's pointer = '_entry'.
void DeleteEntry (kkuint32 _idx)
Removes from KKQueue the entry who's index = '_idx'.
KKQueue * DuplicateListAndContents () const
Creates a new container including duplicating the contents, which also makes the new instance the owner of those contents.
kkuint32 FindTheKthElement (kkuint32 k, Functor pred)
EntryPtr FrontOfQueue () const
Returns a pointer to the element that is at from of the queue with out removing it from the queue.
EntryPtr GetFirst () const
Same as FrontOfQueue.
EntryPtr GetLast () const
Same as BackOfQueue.
EntryPtr IdxToPtr (kkuint32 idx) const
Returns back a pointer to the element who's index is 'idx'.
kkint32 LocateEntry (EntryConstPtr _entry) const
Returns the index of the element who's address is '_entry'.
EntryPtr LookAtBack () const
Same as BackOfQueue.
EntryPtr LookAtFront () const
Same as FrontOfQueue.
bool operator!= (const KKQueue< BinaryClassParms > &rightSide) const
returns False if NOT every entry in both containers point to the same elements
KKQueue & operator= (const KKQueue &q)
Assignment Operator.
bool operator== (const KKQueue< BinaryClassParms > &rightSide) const
Returns True if every entry in both containers point to the same elements.
BinaryClassParms & operator[] (kkuint32 i) const
Returns a reference to element indexed by 'i'; similar to IdxToPtr except tat it returns a reference rather than a pointer.0.
bool Owner () const
void Owner (bool _owner)
You can specify who owns the contents of the container.
virtual EntryPtr PopFromBack ()
Removes the last element in the container and returns its pointer.
virtual EntryPtr PopFromFront ()
Removes the first element in the container and returns its pointer.
kkint32 PtrToIdx (EntryConstPtr _entry) const
returns the index of the 'entry' that has the same pointer as '_entry', if none found returns -1
virtual void PushOnBack (EntryPtr _entry)
Adds '_entry' to the End of the container.
virtual void PushOnFront (EntryPtr _entry)
Adds '_entry' to the Front of the container.
kkint32 QueueSize () const
Same as calling vector<>::size(); returns the number of elements in KKQueue.
void RandomizeOrder ()
Randomizes the order of the vector.
void RandomizeOrder (kkint64 seed)
void RandomizeOrder (RandomNumGenerator &randomVariable)
Randomizes the order of the vector.
virtual EntryPtr RemoveFirst ()
same as PopFromFront
virtual EntryPtr RemoveLast ()
same as PopFromBack
void SetIdxToPtr (kkuint32 _idx, BinaryClassParms *_ptr)
void SwapIndexes (size_t idx1, size_t idx2)
Static Public Member Functions
static BinaryClassParmsListPtr CreateFromXML (std::istream &i, FileDescPtr fileDesc, RunLog &log)
static BinaryClassParmsListPtr CreateFromXML (std::FILE *i, FileDescPtr fileDesc, RunLog &log)
Additional Inherited Members
Protected Member Functions inherited from KKB::KKQueue< BinaryClassParms >
KKQueue (const KKQueue &q)
Copy Constructor creating new instance; including duplicating contents if owner set to true.
Detailed Description
Definition at line 124 of file BinaryClassParms.h.
Member Typedef Documentation
typedef BinaryClassParmsList* KKMLL::BinaryClassParmsList::BinaryClassParmsListPtr
Definition at line 127 of file BinaryClassParms.h.
Constructor & Destructor Documentation
BinaryClassParmsList::BinaryClassParmsList ()
Definition at line 197 of file BinaryClassParms.cpp.
Referenced by BinaryClassParmsList(), CreateFromXML(), DuplicateListAndContents(), and MemoryConsumedEstimated().
BinaryClassParmsList::BinaryClassParmsList (bool _owner)
Definition at line 204 of file BinaryClassParms.cpp.
References BinaryClassParmsList().
BinaryClassParmsList::BinaryClassParmsList (const BinaryClassParmsList & binaryClassList, bool _owner)
Definition at line 218 of file BinaryClassParms.cpp.
BinaryClassParmsList::~BinaryClassParmsList ()
Definition at line 227 of file BinaryClassParms.cpp.
Member Function Documentation
BinaryClassParmsListPtr BinaryClassParmsList::CreateFromXML (std::istream & i, FileDescPtr fileDesc, RunLog & log) static
Definition at line 256 of file BinaryClassParms.cpp.
References BinaryClassParmsList(), and ReadXML().
Referenced by MemoryConsumedEstimated().
static BinaryClassParmsListPtr KKMLL::BinaryClassParmsList::CreateFromXML (std::FILE * i, FileDescPtr fileDesc, RunLog & log) static
BinaryClassParmsListPtr BinaryClassParmsList::DuplicateListAndContents () const
Definition at line 316 of file BinaryClassParms.cpp.
References BinaryClassParmsList(), and PushOnBack().
Referenced by KKMLL::SVMparam::SVMparam().
float BinaryClassParmsList::FeatureCountNet (FileDescPtr fileDesc) const
Returns the Average number of selected features.
Definition at line 272 of file BinaryClassParms.cpp.
References KKMLL::BinaryClassParms::NumOfFeatures().
Referenced by KKMLL::SVMparam::AvgMumOfFeatures().
BinaryClassParmsPtr BinaryClassParmsList::LookUp (MLClassPtr _class1, MLClassPtr _class2) const
Definition at line 293 of file BinaryClassParms.cpp.
Referenced by KKMLL::ModelParamOldSVM::C_Param(), KKMLL::SVMparam::C_Param(), KKMLL::SVMparam::GetBinaryClassParms(), KKMLL::SVMparam::GetFeatureNums(), KKMLL::SVMparam::GetParamtersToUseFor2ClassCombo(), KKMLL::SVMparam::ProbClassPairsInitialize(), PushOnBack(), PushOnFront(), KKMLL::SVMparam::SetBinaryClassFields(), and KKMLL::SVMparam::SetFeatureNums().
kkint32 BinaryClassParmsList::MemoryConsumedEstimated () const
Definition at line 233 of file BinaryClassParms.cpp.
References BinaryClassParmsList(), CreateFromXML(), and ReadXML().
Referenced by KKMLL::SVMparam::MemoryConsumedEstimated().
void BinaryClassParmsList::PushOnBack (BinaryClassParmsPtr binaryParms) virtual
Definition at line 416 of file BinaryClassParms.cpp.
References KKMLL::BinaryClassParms::Class1(), KKMLL::BinaryClassParms::Class1Name(), KKMLL::BinaryClassParms::Class2(), KKMLL::BinaryClassParms::Class2Name(), KKB::endl(), and LookUp().
Referenced by KKMLL::SVMparam::AddBinaryClassParms(), DuplicateListAndContents(), KKMLL::SVMparam::GetParamtersToUseFor2ClassCombo(), and ReadXML().
void BinaryClassParmsList::PushOnFront (BinaryClassParmsPtr binaryParms) virtual
Definition at line 436 of file BinaryClassParms.cpp.
References KKMLL::BinaryClassParms::Class1(), KKMLL::BinaryClassParms::Class1Name(), KKMLL::BinaryClassParms::Class2(), KKMLL::BinaryClassParms::Class2Name(), KKB::endl(), and LookUp().
void BinaryClassParmsList::ReadXML (FILE * i, FileDescPtr fileDesc, RunLog & log)
Definition at line 351 of file BinaryClassParms.cpp.
References KKMLL::BinaryClassParms::CreateFromTabDelStr(), KKB::KKQueue< BinaryClassParms >::DeleteContents(), KKB::KKStr::ExtractQuotedStr(), PushOnBack(), and KKB::KKStr::Upper().
Referenced by CreateFromXML(), and MemoryConsumedEstimated().
void BinaryClassParmsList::ReadXML (std::istream & i, FileDescPtr fileDesc, RunLog & log)
Definition at line 383 of file BinaryClassParms.cpp.
References KKMLL::BinaryClassParms::CreateFromTabDelStr(), KKB::KKQueue< BinaryClassParms >::DeleteContents(), KKB::KKStr::ExtractQuotedStr(), PushOnBack(), and KKB::KKStr::Upper().
void BinaryClassParmsList::ReadXML (XmlStream & s, XmlTagConstPtr tag, VolConstBool & cancelFlag, RunLog & log) virtual
Definition at line 516 of file BinaryClassParms.cpp.
References KKB::XmlContent::Content(), KKMLL::BinaryClassParms::CreateFromTabDelStr(), KKB::KKQueue< BinaryClassParms >::DeleteContents(), KKB::XmlStream::GetNextToken(), PushOnBack(), KKB::XmlToken::TokenType(), and XmlFactoryMacro.
void BinaryClassParmsList::WriteXML (std::ostream & o) const
Definition at line 332 of file BinaryClassParms.cpp.
References KKB::endl().
Referenced by KKMLL::SVMparam::WriteXML().
void BinaryClassParmsList::WriteXML (const KKStr & varName, std::ostream & o) const virtual
Definition at line 490 of file BinaryClassParms.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::endl(), and KKB::XmlTag::WriteXML().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/BinaryClassParms.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/BinaryClassParms.cpp