Pices: C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesInterface/PicesKKStr.cpp File Reference
PicesKKStr.cpp File Reference
#include "StdAfx.h"
#include "FirstIncludes.h"
#include <stdio.h>
#include <math.h>
#include <ctype.h>
#include <time.h>
#include <fstream>
#include <iostream>
#include <ostream>
#include <string>
#include <vector>
#include "MemoryDebug.h"
#include "KKBaseTypes.h"
#include "PicesOSservices.h"
#include "PicesKKStr.h"
Functions
String^ StripOutCommas (String^ s)
Function Documentation
String ^ StripOutCommas (String^ s)
Definition at line 113 of file PicesKKStr.cpp.
Referenced by PicesInterface::PicesKKStr::StrToDouble(), PicesInterface::PicesKKStr::StrToFloat(), PicesInterface::PicesKKStr::StrToInt(), PicesInterface::PicesKKStr::StrToInt64(), PicesInterface::PicesKKStr::StrToLong(), PicesInterface::PicesKKStr::StrToUint(), and PicesInterface::PicesKKStr::StrToUInt64().