Pices: MLL::FeatureFileIOPices Class Reference
MLL::FeatureFileIOPices Class Reference
Supports the reading and writing of feature data from and to Pices feature data files.
#include <FeatureFileIOPices.h>
Public Types
typedef FeatureFileIOPices * FeatureFileIOPicesPtr
typedef KKB::kkuint32 kkuint32
Public Types inherited from KKMLL::FeatureFileIO
typedef FeatureFileIO * FeatureFileIOPtr
Public Member Functions
FeatureFileIOPices ()
virtual ~FeatureFileIOPices ()
virtual ImageFeaturesListPtr FeatureDataReSink (FactoryFVProducerPtr _fvProducerFactory, const KKStr &_dirName, const KKStr &_fileName, MLClassPtr _unknownClass, bool _useDirectoryNameForClassName, DataBasePtr _dataBase, MLClassList &_mlClasses, VolConstBool &_cancelFlag, bool &_changesMade, KKB::DateTime &_timeStamp, RunLog &_log)
FeatureDataReSink.
virtual ImageFeaturesListPtr FeatureDataReSink (FactoryFVProducerPtr _fvProducerFactory, const KKStr &_dirName, const KKStr &_fileName, MLClassPtr _unknownClass, bool _useDirectoryNameForClassName, MLClassList &_mlClasses, VolConstBool &_cancelFlag, bool &_changesMade, KKB::DateTime &_timeStamp, RunLog &_log)
Same as 'FeatureDataReSink' except does not include '_dataBase'; will call above method passing in NULL for '_dataBase'.
virtual FileDescPtr GetFileDesc (const KKStr &_fileName, std::istream &_in, MLClassListPtr _classes, kkint32 &_estSize, KKStr &_errorMessage, RunLog &_runLog)
Create a FileDesc object from the input stream '_in'.
virtual ImageFeaturesListPtr LoadFile (const KKStr &_fileName, const FileDescPtr _fileDesc, MLClassList &_classes, std::istream &_in, kkint32 _maxCount, VolConstBool &_cancelFlag, bool &_changesMade, KKStr &_errorMessage, RunLog &_log)
To be implemented by derived classes; loads the contents of a feature data file and returns a ImageFeaturesList container object.
virtual ImageFeaturesListPtr LoadInSubDirectoryTree (FactoryFVProducerPtr _fvProducerFactory, KKStr _rootDir, MLClassList &_mlClasses, bool _useDirectoryNameForClassName, DataBasePtr _dataBase, VolConstBool &_cancelFlag, bool _rewiteRootFeatureFile, RunLog &_log)
LoadInSubDirectoryTree.
virtual ImageFeaturesListPtr LoadInSubDirectoryTree (FactoryFVProducerPtr _fvProducerFactory, KKStr _rootDir, MLClassList &_mlClasses, bool _useDirectoryNameForClassName, VolConstBool &_cancelFlag, bool _rewiteRootFeatureFile, RunLog &_log)
virtual void SaveFile (FeatureVectorList &_data, const KKStr &_fileName, const FeatureNumList &_selFeatures, std::ostream &_out, kkuint32 &_numExamplesWritten, VolConstBool &_cancelFlag, bool &_successful, KKStr &_errorMessage, RunLog &_log)
Public Member Functions inherited from KKMLL::FeatureFileIO
FeatureFileIO (const KKStr &_driverName, bool _canRead, bool _canWrite)
virtual ~FeatureFileIO ()
void AppendToFile (const KKStr &_fileName, FeatureNumListConst &_selFeatures, FeatureVectorList &_examples, kkuint32 &_numExamplesWritten, VolConstBool &_cancelFlag, bool &_successful, RunLog &log)
bool CanRead ()
bool CanWrite ()
const KKStr & DriverName ()
virtual FeatureVectorListPtr LoadFeatureFile (const KKStr &_fileName, MLClassList &_mlClasses, kkint32 _maxCount, VolConstBool &_cancelFlag, bool &_successful, bool &_changesMade, RunLog &_log)
Loads the contents of a feature data file and returns a ImageFeaturesList container object.
FeatureVectorListPtr LoadInSubDirectoryTree (FactoryFVProducerPtr _fvProducerFactory, KKStr _rootDir, MLClassList &_mlClasses, bool _useDirectoryNameForClassName, VolConstBool &_cancelFlag, bool _rewiteRootFeatureFile, RunLog &_log)
LoadInSubDirectoryTree.
virtual void SaveFeatureFile (const KKStr &_fileName, FeatureNumListConst &_selFeatures, FeatureVectorList &_examples, kkuint32 &_numExamplesWritten, VolConstBool &_cancelFlag, bool &_successful, RunLog &_log)
SaveFeatureFile.
void SaveFeatureFileMultipleParts (const KKStr &_fileName, FeatureNumListConst &_selFeatures, FeatureVectorList &_examples, VolConstBool &_cancelFlag, bool &_successful, RunLog &_log)
Saves the feature file in multiple parts with no one single part larger that 64k examples.
virtual void SaveFile (FeatureVectorList &_data, const KKStr &_fileName, FeatureNumListConst &_selFeatures, std::ostream &_out, kkuint32 &_numExamplesWritten, VolConstBool &_cancelFlag, bool &_successful, KKStr &_errorMessage, RunLog &_log)=0
To be implemented by derived classes; save examples to output stream '_out'.
Static Public Member Functions
static FeatureFileIOPicesPtr Driver ()
static FileDescPtr NewPlanktonFile ()
static KKStr PlanktonFieldName (kkint32 fieldNum)
static kkint32 PlanktonMaxNumOfFields ()
Static Public Member Functions inherited from KKMLL::FeatureFileIO
static FeatureFileIOPtr FileFormatFromStr (const KKStr &_fileFormatStr)
static FeatureFileIOPtr FileFormatFromStr (const KKStr &_fileFormatStr, bool _canRead, bool _canWrite)
static KKStr FileFormatsReadAndWriteOptionsStr ()
static KKStr FileFormatsReadOptionsStr ()
static KKStr FileFormatsWrittenOptionsStr ()
static void FinalCleanUp ()
Before you terminate your application and after all FeatureFileIO activity is done call this method to destroy statically dynamically allocated data structures.
static VectorKKStr RegisteredDriverNames (bool canRead, bool canWrite)
static void RegisterFeatureFileIODriver (FeatureFileIOPtr _driver)
For each feature file format register the appropriate driver through this static method.
Additional Inherited Members
Protected Member Functions inherited from KKMLL::FeatureFileIO
void GetLine (std::istream &_in, KKStr &_line, bool &_eof)
void GetToken (std::istream &_in, const char *_delimiters, KKStr &_token, bool &_eof, bool &_eol)
Will retrieve the next token from the input stream.
Static Protected Member Functions inherited from KKMLL::FeatureFileIO
static void RegisterDriver (FeatureFileIOPtr driver)
Detailed Description
Supports the reading and writing of feature data from and to Pices feature data files.
*************************************************************************************************
*  The PICES feature data file is a very simple format where the first few rows contain a       *
*  description of the rest of the data file.  Any row that starts with "//" will be treated as  *
*  comment line.                                                                                *
*  First Row:  Identifies the file as a feature Data File.  An example on the next line.        *
*              "FEATURE_DATA_FILE Version  51  NumOfFeatures  88  NumOfImages  258"             *
*              Each field will be separated by a tab character.  This line says that the        *
*              version number is 51. There are 88 features and 258 examples or feature vectors. *
*              The version number gets incremented when ever there is a change in the way       *
*              that feature data is computed.                                                   *
*                                                                                               *
*  Second Row: List all the fields in the feature data file.  The first fields are feature      *
*              data.  The first non feature field will be: "ClassName".  There are several no   *
*              feature data fields.  See the SipperSoftware documentation for details.          *
*************************************************************************************************
See also
FeatureFileIO
Definition at line 43 of file FeatureFileIOPices.h.
Member Typedef Documentation
typedef FeatureFileIOPices* MLL::FeatureFileIOPices::FeatureFileIOPicesPtr
Definition at line 46 of file FeatureFileIOPices.h.
typedef KKB::kkuint32 MLL::FeatureFileIOPices::kkuint32
Definition at line 48 of file FeatureFileIOPices.h.
Constructor & Destructor Documentation
FeatureFileIOPices::FeatureFileIOPices ()
Definition at line 59 of file FeatureFileIOPices.cpp.
FeatureFileIOPices::~FeatureFileIOPices () virtual
Definition at line 69 of file FeatureFileIOPices.cpp.
References KKB::KKStr::Empty(), KKB::KKStr::ExtractToken(), KKB::KKStr::Str(), and KKB::KKStr::ToUpper().
Member Function Documentation
static FeatureFileIOPicesPtr MLL::FeatureFileIOPices::Driver () inline static
Definition at line 86 of file FeatureFileIOPices.h.
Referenced by MLL::SipperExtractionImageManager::ManagedClass::CloseOutCurDirectory(), MLL::PicesFVProducerFactory::DefaultFeatureFileIO(), MLL::ImageFeaturesList::FeatureExtraction(), and MLL::SipperExtractionImageManager::Flush().
ImageFeaturesListPtr FeatureFileIOPices::FeatureDataReSink (FactoryFVProducerPtr _fvProducerFactory, const KKStr & _dirName, const KKStr & _fileName, MLClassPtr _unknownClass, bool _useDirectoryNameForClassName, DataBasePtr _dataBase, MLClassList & _mlClasses, VolConstBool & _cancelFlag, bool & _changesMade, KKB::DateTime & _timeStamp, RunLog & _log) virtual
FeatureDataReSink.
Synchronizes the contents of a feature data file with a directory of images.
Used with plankton applications to verify that feature file is up-to-date. Was specifically meant to work with training libraries, to account for images being added and deleted from training library. If there are no changes, then function will run very quickly.
A change in feature file version number would also cause all entries in the feature file to be recomputed. The feature file version number gets incremented whenever we change the feature file computation routine.
Parameters
[in] _dirName Directory where source images are located.
[in] _fileName Feature file that is being synchronized.
[in] _unknownClass Class to be used when class is unknown
[in] _useDirectoryNameForClassName if true then class name of each entry will be set to directory name.
[in] _database If not NULL retrieves Instrument data from the PICES database table InstrumentData.
[in] _mlClasses List of classes
[in] _cancelFlag Boolean variable that will be monitored; if it goes True then will terminate processing right away and return to caller.
[out] _changesMade If returns as true then there were changes made to the feature file 'fileName'. If set to false, then no changes were made.
[out] _timeStamp Timestamp of feature file.
[in] _log where to send diagnostic messages to.
Returns
- A ImageFeaturesList container object. This object will own all the examples loaded
Parameters
_cancelFlag will be monitored, if set to True Load will terminate.
Definition at line 1133 of file FeatureFileIOPices.cpp.
References MLL::ImageFeaturesList::BinarySearchByName(), KKMLL::FeatureVectorProducer::ComputeFeatureVectorFromImage(), CurrentFeatureFileVersionNum, KKB::KKQueue< Entry >::DeleteEntry(), MLL::InstrumentData::Depth(), MLL::ImageFeatures::Depth(), KKB::KKStr::Empty(), KKB::endl(), KKMLL::FeatureVector::ExampleFileName(), KKMLL::FactoryFVProducer::FileDesc(), KKMLL::FeatureVectorList::FileDesc(), MLL::InstrumentData::FlowRate1(), MLL::ImageFeatures::FlowRate1(), MLL::InstrumentData::FlowRate2(), MLL::ImageFeatures::FlowRate2(), MLL::InstrumentData::Fluorescence(), MLL::ImageFeatures::Fluorescence(), MLL::InstrumentDataFileManager::GetClosestInstrumentData(), MLL::InstrumentDataFileManager::InitializePop(), MLL::InstrumentDataFileManager::InitializePush(), MLL::DataBase::InstrumentDataGetByScanLine(), MLL::InstrumentData::Latitude(), MLL::ImageFeatures::Latitude(), KKB::RunLog::Level(), KKMLL::FeatureFileIO::LoadFeatureFile(), MLL::InstrumentData::Longitude(), MLL::ImageFeatures::Longitude(), KKMLL::FactoryFVProducer::ManufactureInstance(), KKMLL::FactoryFVProducer::ManufacturFeatureVectorList(), KKMLL::FeatureVector::MLClass(), KKMLL::FeatureVector::OrigSize(), KKB::osAddSlash(), KKB::osGetFileDateTime(), KKB::osGetListOfFiles(), KKB::osGetLocalDateTime(), MLL::InstrumentData::Oxygen(), MLL::ImageFeatures::Oxygen(), MLL::PicesVariables::ParseImageFileName(), KKMLL::FeatureVectorList::PushOnBack(), KKB::KKQueue< Entry >::QueueSize(), MLL::InstrumentData::Salinity(), MLL::ImageFeatures::Salinity(), KKMLL::FeatureFileIO::SaveFeatureFile(), KKB::KKStrList::Sort(), KKMLL::FeatureVectorList::SortByRootName(), KKB::KKStr::StrInStr(), KKB::KKStr::SubStrPart(), KKB::SupportedImageFileFormat(), KKB::KKException::ToString(), and MLL::ImageFeaturesList::Version().
Referenced by FeatureDataReSink(), and LoadInSubDirectoryTree().
ImageFeaturesListPtr FeatureFileIOPices::FeatureDataReSink (FactoryFVProducerPtr _fvProducerFactory, const KKStr & _dirName, const KKStr & _fileName, MLClassPtr _unknownClass, bool _useDirectoryNameForClassName, MLClassList & _mlClasses, VolConstBool & _cancelFlag, bool & _changesMade, KKB::DateTime & _timeStamp, RunLog & _log) virtual
Same as 'FeatureDataReSink' except does not include '_dataBase'; will call above method passing in NULL for '_dataBase'.
Reimplemented from KKMLL::FeatureFileIO.
Definition at line 1488 of file FeatureFileIOPices.cpp.
References FeatureDataReSink().
FileDescPtr FeatureFileIOPices::GetFileDesc (const KKStr & _fileName, std::istream & _in, MLClassListPtr _classes, kkint32 & _estSize, KKStr & _errorMessage, RunLog & _log) virtual
Create a FileDesc object from the input stream '_in'.
All derived classes must implement this method. It is called by 'LoadFeatureFile' before it starts reading in the feature data.
Parameters
[in] _fileName Name of file to read top get FileDesc data from. Ex in c45 this would be the names file.
[in] _in Input Stream t read from.
[out] _classes Must be pointing to a valid MLClassList object. As class names are encountered add them to this list.
[out] _estSize If you can drive the number of examples in the feature file populate this parameter.
[out] _errorMessage If a error in processing occurs; place a description of the error in this parameter.
_log
Implements KKMLL::FeatureFileIO.
Definition at line 186 of file FeatureFileIOPices.cpp.
References KKMLL::FileDesc::AddAAttribute(), KKB::endl(), KKB::RunLog::Level(), KKB::KKStr::Split(), KKB::KKStr::SubStrPart(), KKB::KKStr::Upper(), and KKMLL::FileDesc::Version().
ImageFeaturesListPtr FeatureFileIOPices::LoadFile (const KKStr & _fileName, const FileDescPtr _fileDesc, MLClassList & _classes, std::istream & _in, kkint32 _maxCount, VolConstBool & _cancelFlag, bool & _changesMade, KKStr & _errorMessage, RunLog & _log) virtual
To be implemented by derived classes; loads the contents of a feature data file and returns a ImageFeaturesList container object.
Parameters
[in] _fileName Feature file that is being loaded.
[in] _fileDesc Description of feature data that is to be loaded.
[in,out] _classes All classes encountered during the loading of the feature file will be added to this list.
[in] _in input stream that feature data is to be loaded/read from.
[in] _maxCount Maximum number of examples to load, -1 = load all
[in] _cancelFlag If this flag turns true the load will terminate and return to caller.
[out] _changesMade If the routine had loaded the feature data determined that it needed to make changes this flag will be set 'true'.
[out] _errorMessage If an error occurs during the loading a description of this error will be placed here.
[in] _log Where to send diagnostic messages to.
Returns
A ImageFeaturesList container object; this object will own all the examples loaded; if an error occurs NULL will be returned.
Implements KKMLL::FeatureFileIO.
Definition at line 277 of file FeatureFileIOPices.cpp.
References KKMLL::FeatureVector::AddFeatureData(), KKMLL::FeatureVector::BreakTie(), MLL::ImageFeatures::CentroidCol(), MLL::ImageFeatures::CentroidRow(), MLL::InstrumentData::Depth(), MLL::ImageFeatures::Depth(), KKB::KKStr::Empty(), KKB::endl(), KKMLL::FeatureVector::ExampleFileName(), KKMLL::FeatureVector::FeatureData(), KKB::KKStr::FirstChar(), KKB::FloatMax, MLL::InstrumentData::FlowRate1(), MLL::ImageFeatures::FlowRate1(), MLL::InstrumentData::FlowRate2(), MLL::ImageFeatures::FlowRate2(), MLL::InstrumentData::Fluorescence(), MLL::ImageFeatures::Fluorescence(), KKB::RunLog::Flush(), MLL::InstrumentDataFileManager::GetClosestInstrumentData(), KKMLL::MLClassList::GetMLClassPtr(), KKMLL::FeatureFileIO::GetToken(), MLL::InstrumentDataFileManager::InitializePop(), MLL::InstrumentDataFileManager::InitializePush(), MLL::ImageFeatures::Latitude(), KKB::RunLog::Level(), MLL::ImageFeatures::Longitude(), KKMLL::FeatureVector::MLClass(), MLL::ImageFeatures::NumOfEdgePixels(), KKMLL::FeatureVector::OrigSize(), KKB::osGetRootName(), MLL::InstrumentData::Oxygen(), MLL::ImageFeatures::Oxygen(), KKB::KKStr::Parse(), KKMLL::FeatureVector::PredictedClass(), KKMLL::FeatureVector::Probability(), KKMLL::FeatureVectorList::PushOnBack(), MLL::InstrumentData::Salinity(), MLL::ImageFeatures::Salinity(), MLL::ImageFeatures::SfCentroidCol(), MLL::ImageFeatures::SfCentroidRow(), KKB::KKStr::Str(), KKB::StrFormatInt(), KKB::KKStr::SubStrPart(), KKB::KKStr::ToUpper(), KKB::KKStr::TrimRight(), KKB::KKStr::Upper(), MLL::ImageFeatures::Version(), and MLL::ImageFeaturesList::Version().
ImageFeaturesListPtr FeatureFileIOPices::LoadInSubDirectoryTree (FactoryFVProducerPtr _fvProducerFactory, KKStr _rootDir, MLClassList & _mlClasses, bool _useDirectoryNameForClassName, DataBasePtr _dataBase, VolConstBool & _cancelFlag, bool _rewiteRootFeatureFile, RunLog & _log) virtual
LoadInSubDirectoryTree.
Loads in the contents of a sub-directory tree.
Meant to work with SIPPER plankton images, it starts at a specified subdirectory and transverses all subdirectories. It makes use of FeatureDataReSink for each specific sub-directory.
Parameters
[in] _rootDir Starting directory.
[in,out] _mlClasses List of classes, any new classes in fileName will be added.
[in] _useDirectoryNameForClassName if true set class names to sub-directory name. This happens because the user may manually move images between directories using the sub-directory name as the class name.
[in] _dataBase If not null retrieve Instrument data from the Instruments database table.
[in] _cancelFlag Will be monitored; if set to True Load will terminate.
[in] _rewiteRootFeatureFile If true rewrite the feature file in the specified 'rootDir'. This feature file will contain all entries from all sub-directories below it.
[in,out] _log Logger where messages are to be written to.
Returns
- A ImageFeaturesList container object that will own all the examples loaded.
Definition at line 901 of file FeatureFileIOPices.cpp.
References MLL::ImageFeaturesList::AddQueue(), KKMLL::FeatureVectorList::AllFeatures(), MLL::InstrumentData::Depth(), MLL::ImageFeatures::Depth(), KKB::KKStr::Empty(), KKB::endl(), KKMLL::FeatureVector::ExampleFileName(), FeatureDataReSink(), MLL::InstrumentData::FlowRate1(), MLL::ImageFeatures::FlowRate1(), MLL::InstrumentData::FlowRate2(), MLL::ImageFeatures::FlowRate2(), MLL::InstrumentData::Fluorescence(), MLL::ImageFeatures::Fluorescence(), MLL::InstrumentDataFileManager::GetClosestInstrumentData(), KKMLL::MLClassList::GetMLClassPtr(), KKMLL::MLClassList::GetUnKnownClass(), MLL::DataBase::ImagesGetGpsData(), MLL::DataBase::InstrumentDataGetByScanLine(), MLL::InstrumentData::Latitude(), MLL::ImageFeatures::Latitude(), KKB::RunLog::Level(), MLL::InstrumentData::Longitude(), MLL::ImageFeatures::Longitude(), KKMLL::FeatureVector::MLClass(), NewPlanktonFile(), KKB::osAddLastSlash(), KKB::osAddSlash(), KKB::osGetListOfDirectories(), KKB::osGetRootName(), KKB::osGetRootNameOfDirectory(), KKB::KKQueue< Entry >::Owner(), MLL::InstrumentData::Oxygen(), MLL::ImageFeatures::Oxygen(), MLL::PicesVariables::ParseImageFileName(), MLL::InstrumentData::Salinity(), MLL::ImageFeatures::Salinity(), and KKMLL::FeatureFileIO::SaveFeatureFile().
Referenced by LoadInSubDirectoryTree(), and PlanktonMaxNumOfFields().
ImageFeaturesListPtr FeatureFileIOPices::LoadInSubDirectoryTree (FactoryFVProducerPtr _fvProducerFactory, KKStr _rootDir, MLClassList & _mlClasses, bool _useDirectoryNameForClassName, VolConstBool & _cancelFlag, bool _rewiteRootFeatureFile, RunLog & _log) virtual
Definition at line 879 of file FeatureFileIOPices.cpp.
References LoadInSubDirectoryTree().
FileDescPtr FeatureFileIOPices::NewPlanktonFile () static
Definition at line 1519 of file FeatureFileIOPices.cpp.
References KKMLL::FileDesc::AddAAttribute(), and PlanktonFieldName().
Referenced by MLL::PicesFVProducer::DefineFileDescStatic(), LoadInSubDirectoryTree(), LookUpFeatureDataField(), and MLL::PicesApplication::PicesApplication().
KKStr FeatureFileIOPices::PlanktonFieldName (kkint32 fieldNum) static
Definition at line 851 of file FeatureFileIOPices.cpp.
References KKB::endl(), and KKB::StrFormatInt().
Referenced by MLL::DataBase::FeatureDataCreateTable(), MLL::DataBase::FeatureDataUpdate(), LookUpFeatureDataField(), and NewPlanktonFile().
kkint32 FeatureFileIOPices::PlanktonMaxNumOfFields () static
Definition at line 871 of file FeatureFileIOPices.cpp.
References LoadInSubDirectoryTree().
Referenced by MLL::ImageFeatures::CalcFeatures(), MLL::DataBase::FeatureDataCreateTable(), LookUpFeatureDataField(), and MLL::PicesFVProducer::MaxNumOfFeatures().
void FeatureFileIOPices::SaveFile (FeatureVectorList & _data, const KKStr & _fileName, const FeatureNumList & _selFeatures, std::ostream & _out, kkuint32 & _numExamplesWritten, VolConstBool & _cancelFlag, bool & _successful, KKStr & _errorMessage, RunLog & _log) virtual
Definition at line 592 of file FeatureFileIOPices.cpp.
References KKMLL::MLClassIndexList::AddClassIndexAssignment(), KKMLL::FeatureVector::BreakTie(), MLL::ImageFeatures::CentroidCol(), MLL::ImageFeatures::CentroidRow(), KKMLL::FeatureVector::ClassName(), KKMLL::ClassStatistic::Count(), CurrentFeatureFileVersionNum, KKB::endl(), KKMLL::FeatureVector::ExampleFileName(), KKMLL::FeatureVector::FeatureData(), KKMLL::FileDesc::FieldName(), KKMLL::FeatureVectorList::FileDesc(), KKMLL::MLClassIndexList::GetClassIndex(), KKMLL::FeatureVectorList::GetClassStatistics(), MLL::ImageFeaturesList::IdxToPtr(), MLL::ImageFeatures::Latitude(), MLL::ImageFeatures::Longitude(), KKMLL::ClassStatistic::MLClass(), KKMLL::FeatureVector::MLClass(), KKMLL::ClassStatistic::Name(), MLL::ImageFeatures::NumOfEdgePixels(), KKMLL::FeatureNumList::NumOfFeatures(), KKMLL::FeatureVector::OrigSize(), KKMLL::FeatureVector::PredictedClass(), KKMLL::FeatureVector::PredictedClassName(), KKMLL::FeatureVector::Probability(), KKB::KKQueue< Entry >::QueueSize(), MLL::ImageFeatures::SfCentroidCol(), MLL::ImageFeatures::SfCentroidRow(), KKB::StrFormatInt(), and MLL::ImageFeaturesList::Version().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/FeatureFileIOPices.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/FeatureFileIOPices.cpp