Pices: PicesCommander.SizeDistribution2.ClassTotals2 Class Reference
PicesCommander.SizeDistribution2.ClassTotals2 Class Reference
Public Member Functions
ClassTotals2 (String _name, float _sizeInitial, float _sizeGrowthFactor, float _sizeEndRange, int _bucketCount, float[] _sizeBucketStart, float[] _sizeBucketEnd)
void AddIn (ClassTotals2 classTotals)
int BucketCount (int idx)
void Increment (float areaMM)
void PrintTabDelLine (System.IO.StreamWriter o, float volume)
Properties
String Name [get]
String NameUpper [get]
float SizeEndRange [get]
float SizeGrowthFactor [get]
float SizeInitial [get]
Detailed Description
Definition at line 23 of file SizeDistribution2.cs.
Constructor & Destructor Documentation
PicesCommander.SizeDistribution2.ClassTotals2.ClassTotals2 (String _name, float _sizeInitial, float _sizeGrowthFactor, float _sizeEndRange, int _bucketCount, float[] _sizeBucketStart, float[] _sizeBucketEnd) inline
Definition at line 38 of file SizeDistribution2.cs.
Referenced by PicesCommander.SizeDistribution2.Add(), PicesCommander.SizeDistribution2.Increment(), PicesCommander.SizeDistribution2.InitiateClass(), PicesCommander.SizeDistribution2.PrintTabDelDistributionMatrix(), and PicesCommander.SizeDistribution2.SummarizeFamilyOfClasses().
Member Function Documentation
void PicesCommander.SizeDistribution2.ClassTotals2.AddIn (ClassTotals2 classTotals) inline
Definition at line 99 of file SizeDistribution2.cs.
Referenced by PicesCommander.SizeDistribution2.Add(), PicesCommander.SizeDistribution2.PrintTabDelDistributionMatrix(), and PicesCommander.SizeDistribution2.SummarizeFamilyOfClasses().
int PicesCommander.SizeDistribution2.ClassTotals2.BucketCount (int idx) inline
Definition at line 111 of file SizeDistribution2.cs.
void PicesCommander.SizeDistribution2.ClassTotals2.Increment (float areaMM) inline
Definition at line 70 of file SizeDistribution2.cs.
Referenced by PicesCommander.SizeDistribution2.Increment().
void PicesCommander.SizeDistribution2.ClassTotals2.PrintTabDelLine (System.IO.StreamWriter o, float volume) inline
Definition at line 120 of file SizeDistribution2.cs.
References PicesCommander.SizeDistribution2.ClassTotals2.Name, and PicesCommander.SizeDistribution2.ClassTotals2.NameUpper.
Referenced by PicesCommander.SizeDistribution2.PrintTabDelDistributionMatrix().
Property Documentation
String PicesCommander.SizeDistribution2.ClassTotals2.Name get
Definition at line 63 of file SizeDistribution2.cs.
Referenced by PicesCommander.SizeDistribution2.Add(), PicesCommander.SizeDistribution2.PrintTabDelDistributionMatrixesForSummaryClasses(), and PicesCommander.SizeDistribution2.ClassTotals2.PrintTabDelLine().
String PicesCommander.SizeDistribution2.ClassTotals2.NameUpper get
Definition at line 64 of file SizeDistribution2.cs.
Referenced by PicesCommander.SizeDistribution2.ClassTotals2.PrintTabDelLine().
float PicesCommander.SizeDistribution2.ClassTotals2.SizeEndRange get
Definition at line 65 of file SizeDistribution2.cs.
Referenced by PicesCommander.SizeDistribution2.Add().
float PicesCommander.SizeDistribution2.ClassTotals2.SizeGrowthFactor get
Definition at line 66 of file SizeDistribution2.cs.
Referenced by PicesCommander.SizeDistribution2.Add().
float PicesCommander.SizeDistribution2.ClassTotals2.SizeInitial get
Definition at line 67 of file SizeDistribution2.cs.
Referenced by PicesCommander.SizeDistribution2.Add().
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/SizeDistribution2.cs