Pices: PicesInterface::PicesDataBase Class Reference
PicesInterface::PicesDataBase Class Reference
All access to the MySQL database is done through this class.
#include <PicesDataBase.h>
Public Member Functions
PicesDataBase (PicesRunLog^ _runLog)
PicesDataBase (PicesDataBaseServer^ _server, PicesRunLog^ _log)
void Close ()
bool DuplicateKey ()
PicesFeatureVectorList^ FeatureDataForImageGroup (PicesDataBaseImageGroup^ imageGroup, PicesClass^ mlClass, System::Char classKeyToUse)
summary> Updates an existing Feature-Data-Vector in the database.
PicesFeatureVectorList^ FeatureDataGetOneSipperFile (String^ sipperFileName, PicesClass^ mlClass, System::Char classKeyToUse, bool reExtractInstrumentData)
void FeatureDataInsertRow (String^ _sipperFileName, PicesFeatureVector^ _example)
PicesFeatureVector^ FeatureDataRecLoad (String^ imageFileName)
PicesFeatureVector^ FeatureDataRecLoad (PicesDataBaseImage^ image)
void FeatureDataUpdate (PicesDataBaseImage^ databaseImage, PicesFeatureVector^ example)
List< ulong >^ GetScanLinesPerMeterProfile (String^ sipperFileName, PicesSipperFile^ sipperFile)
List< float >^ GetVolumePerMeterProfile (String^ sipperFileName, PicesSipperFile^ sipperFile)
PicesGPSDataPointList^ GpsDataQuery (String^ cruiseName, System::DateTime utcStart, System::DateTime utcEnd)
PicesGPSDataPointList^ GpsDataQueryByIntervals (String^ cruiseName, System::DateTime utcStart, System::DateTime utcEndk, int timeInterval)
PicesRaster^ ImageFullSizeFind (String^ imageFileName)
Will locate a original size version of the image; it will try in order 3 diferent sources.
PicesRaster^ ImageFullSizeLoad (String^ imageFileName)
void ImageFullSizeSave (String^ imageFileName, PicesRaster^ raster)
PicesClassStatisticList^ ImageGetClassStatistics (PicesDataBaseImageGroup^ imageGroup, String^ sipperFileName, PicesClass^ mlClass, System::Char classKeyToUse, float minProb, float maxProb, int minSize, int maxSize, float minDepth, float maxDepth)
PicesClassStatisticList^ ImageGetClassStatistics (PicesDataBaseImageGroup^ imageGroup, String^ cruiseName, String^ stationName, String^ deploymentNum, PicesClass^ mlClass, System::Char classKeyToUse, float minProb, float maxProb, int minSize, int maxSize, float minDepth, float maxDepth)
array< uint >^ ImageGetDepthStatistics (PicesDataBaseImageGroup^ imageGroup, String^ sipperFileName, float depthIncrements, PicesClass^ mlClass, System::Char classKeyToUse, float minProb, float maxProb, int minSize, int maxSize)
array< uint >^ ImageGetDepthStatistics (PicesDataBaseImageGroup^ imageGroup, String^ cruiseName, String^ stationName, String^ deploymentNum, float depthIncrements, PicesClass^ mlClass, System::Char classKeyToUse, float probMin, float probMax, int sizeMin, int sizeMax)
void ImageGroupDelete (int imageGroupId)
void ImageGroupEntriesInsert (PicesDataBaseImageGroupEntry^ imageGroupEntry)
void ImageGroupEntriesInsert (PicesDataBaseImageGroupEntryList^ imageGroupList)
array< array< String^ >^ >^ ImageGroupEntriesInsert (int groupId, List< String^ >^imageFileNames)
Adds multiple images to a specified GroupId; the update is done in one MySql call to improve performance.
array< array< String^ >^ >^ ImageGroupEntriesInsert (int groupId, PicesDataBaseImageList^ images)
Adds multiple images to a specified GroupId; the update is done in one MySql call to improve performance.
PicesDataBaseImageGroupEntryList^ ImageGroupEntriesLoad (int groupId)
void ImageGroupInsert (PicesDataBaseImageGroup^ imageGroup)
PicesDataBaseImageGroupList^ ImageGroupLoad ()
PicesDataBaseImageGroup^ ImageGroupLoad (String^ name)
void ImageInsert (PicesRaster^ image, String^ imageFileName, String^ supperFileName, kkuint64 byteOffset, kkuint32 topLeftRow, kkuint32 topLeftCol, kkuint32 height, kkuint32 width, kkuint32 pixelCount, uchar connectedPixelDist, kkuint32 extractionLogEntryId, kkuint32 classLogEntryId, kkuint32 centroidRow, kkuint32 centroidCol, PicesClass^ class1, float class1Prob, PicesClass^ class2, float class2Prob, PicesClass^ validatedClass, float depth, float imageSize, PicesPointList^ sizeCoordinates, kkint32% imageId, bool% successful)
PicesDataBaseImage^ ImageLoad (uint imageId)
PicesDataBaseImage^ ImageLoad (String^ imageFileName)
void ImageRemoveValidation (String^ imageFileName)
void ImagesDeleteOneImage (String^ imageFileName)
PicesDataBaseImageList^ ImagesQuery (PicesDataBaseImageGroup^ group, bool includeThumbnail)
PicesDataBaseImageList^ ImagesQuery (PicesDataBaseImageGroup^ imageGroup, String^ sipperFileName, PicesClass^ mlClass, System::Char classKeyToUse, float probMin, float probMax, int sizeMin, int sizeMax, float depthMin, float depthMax, uint restartImageId, int limit, bool includeThumbnail)
PicesDataBaseImageList^ ImagesQuery (PicesDataBaseImageGroup^ imageGroup, String^ cruiseName, String^ stationName, String^ deploymentNum, PicesClass^ mlClass, System::Char classKeyToUse, float probMin, float probMax, int sizeMin, int sizeMax, float depthMin, float depthMax, uint restartImageId, int limit, bool includeThumbnail)
PicesDataBaseImageList^ ImagesQueryByGrouop (PicesDataBaseImageGroup^ imageGroup, String^ cruiseName, String^ stationName, String^ deploymentNum, String^ sipperFileName, PicesClass^ mlClass, System::Char classKeyToUse, float probMin, float probMax, int sizeMin, int sizeMax, float depthMin, float depthMax, uint restartImageId, int limit, bool includeThumbnail)
PicesDataBaseImageList^ ImagesQueryDeploymentSizeRange (String^ cruiseName, String^ stationName, String^ deploymentNum, PicesClass^ mlClass, System::Char cast, System::Char statistic, float sizeStart, float sizeEnd, float depthMin, float depthMax, int sampleQty, bool includeChildren)
void ImagesSizeDistributionByDepth (String^ cruiseName, String^ stationName, String^ deploymentNum, String^ className, float depthBinSize, char statistic, float initialValue, float growthRate, float endValue, PicesImageSizeDistribution^ %downCast, PicesImageSizeDistribution^ %upCast)
void ImagesUpdateImageSize (String^ imageFileName, PicesPointList^ sizeCoordinates, float imageSize)
void ImagesUpdatePredictions (String^ imageFileName, PicesClass^ class1Pred, float class1Prob, PicesClass^ class2Pred, float class2Prob, uint logEntryId)
void ImagesUpdatePredictionsList (uint _logEntryId, String^ _predictionList)
Updates prediction on multiple images at one time.
void ImagesUpdateValidatedAndPredictClass (String^ imageFileName, PicesClass^ mlClass, float class1Prob)
void ImagesUpdateValidatedClass (String^ imageFileName, PicesClass^ mlClass)
void ImageUpdateInstrumentDataFields (PicesInstrumentData^ instumentData, String^ sipperFileName, uint scanLineStart, uint scanLineEnd)
PicesInstrumentData^ InstrumentDataGetByScanLine (String^ sipperFileName, uint scanLine)
Retrieves instrument data that is closest to the specified scan-line.
List< String^ >^ InstrumentDataGetFieldNames ()
Get the names of individual field names; used by applications that will query InstrumentData table allowing users to select fields to query and display.
array< float, 2 >^ InstrumentDataGetSpecificFields (String^ sipperFileName, List< String^ >^fieldNames, System::DateTime dateTimeStart, System::DateTime dateTimeEnd)
Returns 2d array consisting of the specific data fields from the Instrument data file for the specified SipperFile.
array< float, 2 >^ InstrumentDataGetSpecificFields (String^ cruiseName, String^ stationName, String^ deploymentNum, List< String^ >^fieldNames, System::DateTime dateTimeStart, System::DateTime dateTimeEnd)
PicesVolumeSampledStatList^ InstrumentDataGetVolumePerMeterDepth (String^ siperFileName, float depthBinSize)
Returns volume of water sampled, in cubic meters, by depth for a given sipper file.
PicesVolumeSampledStatList^ InstrumentDataGetVolumePerMeterDepth (String^ cruiseName, String^ stationName, String^ deploymentNum, float depthBinSize)
PicesInstrumentDataList^ InstrumentDataLoad (String^ sipperFileName)
PicesInstrumentDataList^ InstrumentDataLoad (String^ cruiseName, String^ stationName, String^ deploymentNum)
PicesGPSDataPointList^ InstrumentDataRetrieveGPSInfo (String^ cruiseName, String^ stationName, String^ deploymentNum, kkint32 timeInterval)
void InstrumentDataSaveListForOneSipperFile (String^ sipperFileName, PicesInstrumentDataList^ data)
String^ LastErrorDesc ()
void LogEntriesProcessEnd (PicesDataBaseLogEntry^ logEntry, float cpuTimeUsed, String^ completionResult)
PicesDataBaseLogEntry^ LogEntriesProcessStart (String^ progCode, String^ progName, System::DateTime dateTimeCompiled, String^ cmdLine, String^ sipperFileName)
PicesDataBaseLogEntry^ LogEntriesSelect (uint _logEntryId)
void MLClassDelete (String^ className)
void MLClassInsert (PicesClass^ picesClass)
void MLClassInsertReturn (PicesClass^ mlClass, bool% successful)
PicesClass^ MLClassLoad (String^ className)
Load instance on PicesClass with name = "ClassName" if not in database will return nullptr.
PicesClassList^ MLClassLoadList ()
void MLClassUpdate (String^ oldClassName, PicesClass^ picesClass)
array< array< String^ >^ >^ QueryStatement (String^ statement, array< String^ >^colsToReturn)
A general purpose SQL calling method; It will execute the command in 'statement' with the understanding that 'colsToReturn' will contain a list of columns in the result set that are to be returned.
String^ ServerDescription ()
void SipperCruiseDelete (String^ cruiseName)
void SipperCruiseInsert (PicesSipperCruise^ cruise)
PicesSipperCruise^ SipperCruiseLoad (String^ cruiseName)
PicesSipperCruiseList^ SipperCruiseLoadAllCruises ()
void SipperCruiseUpdate (PicesSipperCruise^ cruise)
void SipperDeploymentDelete (String^ cruiseName, String^ stationName, String^ deploymentNum)
void SipperDeploymentInsert (PicesSipperDeployment^ deployment)
PicesSipperDeploymentList^ SipperDeploymentLoad (String^ cruiseName, String^ stationName)
PicesSipperDeployment^ SipperDeploymentLoad (String^ cruiseName, String^ stationName, String^ deploymentNum)
PicesSipperDeploymentList^ SipperDeploymentLoadByStation (String^ stationName)
void SipperDeploymentUpdate (PicesSipperDeployment^ deployment)
String^ SipperFileGetFullPath (String^ _sipperFileName)
array< String^ >^ SipperFileGetList (String^ cruiseName, String^ stationName, String^ deploymentNum)
void SipperFileInsert (PicesSipperFile^ sipperFile)
PicesSipperFileList^ SipperFileLoad (String^ cruiseName, String^ stationName, String^ deploymentNum)
void SipperFileLoadOracle ()
PicesSipperFile^ SipperFileRecLoad (String^ _sipperFileName)
void SipperFileUpdate (PicesSipperFile^ sipperFile)
void SipperStationDelete (String^ cruiseName, String^ stationName)
void SipperStationInsert (PicesSipperStation^ station)
PicesSipperStationList^ SipperStationLoad (String^ cruiseName)
PicesSipperStation^ SipperStationLoad (String^ cruiseName, String^ stationName)
PicesSipperStationList^ SipperStationsLoadByGpsRange (double latitudeMin, double latitudeMax, double longitudeMin, double longitudeMax)
void SipperStationUpdate (PicesSipperStation^ station)
bool Successful ()
bool Valid ()
Static Public Member Functions
static void CloseGlobalDbConn ()
static bool EmbeddedServerRunning ()
static void FinalCleanUp ()
static PicesDataBase^ GetGlobalDatabaseManagerNewInstance (PicesRunLog^ _runLog)
static void Initialization ()
static PicesDataBase^ SelectNewDataBaseServer (PicesRunLog^ _runLog)
static void ThreadEnd ()
Call just before thread terminates.
static bool ThreadInit ()
Call at start of new thread.
Static Public Attributes
static PicesDataBaseServer^ defaultGlobalServer = nullptr
static PicesDataBase^ globaDbConn = nullptr
Protected Member Functions
!PicesDataBase ()
Properties
bool CancelFlag [get, set]
bool LastOpSuccessful [get]
PicesDataBaseServer^ Server [get]
Detailed Description
All access to the MySQL database is done through this class.
Each one of these methods calls the matching method in the unmanaged class DataBase in the PicesLibrary.
Definition at line 36 of file PicesDataBase.h.
Constructor & Destructor Documentation
PicesInterface::PicesDataBase::PicesDataBase (PicesRunLog^ _runLog)
Definition at line 64 of file PicesDataBase.cpp.
PicesInterface::PicesDataBase::PicesDataBase (PicesDataBaseServer^ _server, PicesRunLog^ _log)
Definition at line 75 of file PicesDataBase.cpp.
References PicesInterface::PicesDataBaseServer::Server().
PicesInterface::PicesDataBase::!PicesDataBase () protected
Definition at line 102 of file PicesDataBase.cpp.
Member Function Documentation
void PicesInterface::PicesDataBase::Close ()
Definition at line 119 of file PicesDataBase.cpp.
Referenced by SipperFile.ActiveTrainingLibraries::MakePredictions(), SipperFile.PredictionBreakDownDisplayDual::PredictionBreakDownDisplayDual(), and SipperFileViewer.SipperFileViewer::SipperFileViewerRegionAroundImage().
void PicesInterface::PicesDataBase::CloseGlobalDbConn () static
Definition at line 161 of file PicesDataBase.cpp.
bool PicesInterface::PicesDataBase::DuplicateKey () inline
Definition at line 93 of file PicesDataBase.h.
References MLL::DataBase::DuplicateKey().
bool PicesInterface::PicesDataBase::EmbeddedServerRunning () static
Definition at line 57 of file PicesDataBase.cpp.
PicesFeatureVectorList PicesInterface::PicesDataBase::FeatureDataForImageGroup (PicesDataBaseImageGroup^ imageGroup, PicesClass^ mlClass, System::Char classKeyToUse)
summary> Updates an existing Feature-Data-Vector in the database.
/summary> param name="databaseImage">Specifies that image in the database that the Feature-Vector was computed for; if points to nullptr will attempt to locate via 'ImageFileName' in the example' parameter.
param name="example">The Feature-Vector to update the existing Feature-Vector in the database with.
Definition at line 408 of file PicesDataBase.cpp.
References PicesInterface::ClassKeyToUse(), KKB::KKQueue< Entry >::Owner(), PicesInterface::PicesDataBaseImageGroup::UnManagedClass(), and PicesInterface::PicesClass::UnmanagedMLClass().
PicesFeatureVectorList PicesInterface::PicesDataBase::FeatureDataGetOneSipperFile (String^ sipperFileName, PicesClass^ mlClass, System::Char classKeyToUse, bool reExtractInstrumentData)
Definition at line 376 of file PicesDataBase.cpp.
References PicesInterface::ClassKeyToUse(), KKB::KKQueue< Entry >::Owner(), and PicesInterface::PicesClass::UnmanagedMLClass().
void PicesInterface::PicesDataBase::FeatureDataInsertRow (String^ _sipperFileName, PicesFeatureVector^ _example)
Definition at line 324 of file PicesDataBase.cpp.
References PicesInterface::PicesFeatureVector::Features().
PicesFeatureVector PicesInterface::PicesDataBase::FeatureDataRecLoad (String^ imageFileName)
Definition at line 346 of file PicesDataBase.cpp.
Referenced by SipperFile.PredictionBreakDownDisplay::PredictionBreakDownDisplay(), and SipperFile.PredictionBreakDownDisplayDual::PredictionBreakDownDisplayDual().
PicesFeatureVector PicesInterface::PicesDataBase::FeatureDataRecLoad (PicesDataBaseImage^ image)
Definition at line 364 of file PicesDataBase.cpp.
References PicesInterface::PicesDataBaseImage::UnManagedDataBaseImage().
void PicesInterface::PicesDataBase::FeatureDataUpdate (PicesDataBaseImage^ databaseImage, PicesFeatureVector^ example)
Definition at line 441 of file PicesDataBase.cpp.
References PicesInterface::PicesFeatureVector::UnManagedClass(), and PicesInterface::PicesDataBaseImage::UnManagedDataBaseImage().
void PicesInterface::PicesDataBase::FinalCleanUp () static
Definition at line 51 of file PicesDataBase.cpp.
PicesDataBase PicesInterface::PicesDataBase::GetGlobalDatabaseManagerNewInstance (PicesRunLog^ _runLog) static
Definition at line 173 of file PicesDataBase.cpp.
References MLL::DataBaseServer::Description(), MLL::DataBaseServer::HostName(), and MLL::DataBaseServer::UserName().
Referenced by PicesCommander.AssignSelectedImagesToGroup::AssignSelectedImagesToGroup(), PicesCommander.ChartAbundanceByDeployment::ChartAbundanceByDeployment(), PicesCommander.ChartAbundancePredictedAndValidated::ChartAbundancePredictedAndValidated(), PicesCommander.ChartDistribution::ChartDistribution(), PicesCommander.ChartGPS::ChartGPS(), PicesCommander.ChartGPSByStation::ChartGPSByStation(), PicesCommander.ChartHorizontalProfile::ChartHorizontalProfile(), PicesCommander.ChartSizeDepthDistribution::ChartSizeDepthDistribution(), PicesCommander.ChartSizeDistribution::ChartSizeDistribution(), PicesCommander.ClassDepthProfileChart::ClassDepthProfileChart(), PicesCommander.ClassificationStatus::ClassificationStatus(), PicesCommander.Harvester::Harvester(), SipperFile.ImageViewer::ImageViewer(), PicesCommander.ImportGroupAssignments::ImportGroupAssignments(), PicesCommander.ImportImagesIntoDeployment::ImportImagesIntoDeployment(), PicesCommander.ImportValidatdClass::ImportValidatdClass(), SipperFile.ActiveTrainingLibraries::MakePredictions(), SipperFile.PredictionBreakDownDisplayDual::PredictionBreakDownDisplayDual(), and SipperFileViewer.SipperFileViewer::SipperFileViewerRegionAroundImage().
List< ulong > PicesInterface::PicesDataBase::GetScanLinesPerMeterProfile (String^ sipperFileName, PicesSipperFile^ sipperFile)
Definition at line 1729 of file PicesDataBase.cpp.
References PicesInterface::PicesSipperFile::UnmanagedClass().
List< float > PicesInterface::PicesDataBase::GetVolumePerMeterProfile (String^ sipperFileName, PicesSipperFile^ sipperFile)
Definition at line 1751 of file PicesDataBase.cpp.
References PicesInterface::PicesSipperFile::UnmanagedClass().
PicesGPSDataPointList PicesInterface::PicesDataBase::GpsDataQuery (String^ cruiseName, System::DateTime utcStart, System::DateTime utcEnd)
/summary> param name ="cruiseName"> Cruse to retrieve GPS data for.
param name ="utcStart">Start Date-Time to collect data for; nullptr indicates to start with 1st entry for cruise..
param name ="utcEnd">End Date-Time to collect data for; nullptr indicates to start with 1st entry for cruise..
summary> Returns Summary GPSData for a specified Cruies and time range. Each entry returned will be the avareage values for the range of entries that are with in 'timeInterval' seconds. This is done by grouping by using the function "Floor(Unix_Time(GpsUtcTime) / timeInterval)" /summary>
Definition at line 1885 of file PicesDataBase.cpp.
PicesGPSDataPointList PicesInterface::PicesDataBase::GpsDataQueryByIntervals (String^ cruiseName, System::DateTime utcStart, System::DateTime utcEndk, int timeInterval)
Definition at line 1908 of file PicesDataBase.cpp.
PicesRaster PicesInterface::PicesDataBase::ImageFullSizeFind (String^ imageFileName)
Will locate a original size version of the image; it will try in order 3 diferent sources.
1) ThumbNail in Images Table. 2) FullSizeImage in ImagesFullSize table 3) will go to SipperFile
Definition at line 1229 of file PicesDataBase.cpp.
References KKB::KKException::ToString().
Referenced by SipperFile.PredictionBreakDownDisplay::PredictionBreakDownDisplay(), and SipperFile.PredictionBreakDownDisplayDual::PredictionBreakDownDisplayDual().
PicesRaster PicesInterface::PicesDataBase::ImageFullSizeLoad (String^ imageFileName)
Definition at line 1205 of file PicesDataBase.cpp.
void PicesInterface::PicesDataBase::ImageFullSizeSave (String^ imageFileName, PicesRaster^ raster)
Definition at line 1217 of file PicesDataBase.cpp.
References PicesInterface::PicesRaster::UnmanagedClass().
PicesClassStatisticList PicesInterface::PicesDataBase::ImageGetClassStatistics (PicesDataBaseImageGroup^ imageGroup, String^ sipperFileName, PicesClass^ mlClass, System::Char classKeyToUse, float minProb, float maxProb, int minSize, int maxSize, float minDepth, float maxDepth)
Definition at line 851 of file PicesDataBase.cpp.
References PicesInterface::ClassKeyToUse(), PicesInterface::PicesDataBaseImageGroup::UnManagedClass(), and PicesInterface::PicesClass::UnmanagedMLClass().
PicesClassStatisticList PicesInterface::PicesDataBase::ImageGetClassStatistics (PicesDataBaseImageGroup^ imageGroup, String^ cruiseName, String^ stationName, String^ deploymentNum, PicesClass^ mlClass, System::Char classKeyToUse, float minProb, float maxProb, int minSize, int maxSize, float minDepth, float maxDepth)
Definition at line 894 of file PicesDataBase.cpp.
References PicesInterface::ClassKeyToUse(), PicesInterface::PicesDataBaseImageGroup::UnManagedClass(), and PicesInterface::PicesClass::UnmanagedMLClass().
array< uint > PicesInterface::PicesDataBase::ImageGetDepthStatistics (PicesDataBaseImageGroup^ imageGroup, String^ sipperFileName, float depthIncrements, PicesClass^ mlClass, System::Char classKeyToUse, float minProb, float maxProb, int minSize, int maxSize)
Definition at line 940 of file PicesDataBase.cpp.
References PicesInterface::ClassKeyToUse(), PicesInterface::PicesDataBaseImageGroup::UnManagedClass(), and PicesInterface::PicesClass::UnmanagedMLClass().
array< uint > PicesInterface::PicesDataBase::ImageGetDepthStatistics (PicesDataBaseImageGroup^ imageGroup, String^ cruiseName, String^ stationName, String^ deploymentNum, float depthIncrements, PicesClass^ mlClass, System::Char classKeyToUse, float probMin, float probMax, int sizeMin, int sizeMax)
Definition at line 988 of file PicesDataBase.cpp.
References PicesInterface::ClassKeyToUse(), PicesInterface::PicesDataBaseImageGroup::UnManagedClass(), and PicesInterface::PicesClass::UnmanagedMLClass().
void PicesInterface::PicesDataBase::ImageGroupDelete (int imageGroupId)
Definition at line 1461 of file PicesDataBase.cpp.
void PicesInterface::PicesDataBase::ImageGroupEntriesInsert (PicesDataBaseImageGroupEntry^ imageGroupEntry)
Definition at line 1474 of file PicesDataBase.cpp.
References PicesInterface::PicesDataBaseImageGroupEntry::UnManagedClass().
void PicesInterface::PicesDataBase::ImageGroupEntriesInsert (PicesDataBaseImageGroupEntryList^ imageGroupList)
Definition at line 1482 of file PicesDataBase.cpp.
References PicesInterface::PicesDataBaseImageGroupEntry::UnManagedClass().
array< array< String^ >^ > PicesInterface::PicesDataBase::ImageGroupEntriesInsert (int groupId, List< String^ >^ imageFileNames)
Adds multiple images to a specified GroupId; the update is done in one MySql call to improve performance.
Returns
Two dimensional string matrix with one row for each update failure, 1st column "ImageFileName", 2nd column Eerror description.
Definition at line 1498 of file PicesDataBase.cpp.
References KKB::KKStrMatrix::NumRows(), and KKB::KKQueue< Entry >::QueueSize().
array< array< String^ >^ > PicesInterface::PicesDataBase::ImageGroupEntriesInsert (int groupId, PicesDataBaseImageList^ images)
Adds multiple images to a specified GroupId; the update is done in one MySql call to improve performance.
Returns
Two dimensional string matrix with one row for each update failure, 1st column "ImageFileName", 2nd column Eerror description.
Definition at line 1538 of file PicesDataBase.cpp.
References PicesInterface::PicesDataBaseImage::ImageFileName.
PicesDataBaseImageGroupEntryList PicesInterface::PicesDataBase::ImageGroupEntriesLoad (int groupId)
Definition at line 1551 of file PicesDataBase.cpp.
References KKB::KKQueue< Entry >::Owner().
void PicesInterface::PicesDataBase::ImageGroupInsert (PicesDataBaseImageGroup^ imageGroup)
Definition at line 1435 of file PicesDataBase.cpp.
References PicesInterface::PicesDataBaseImageGroup::UnManagedClass().
PicesDataBaseImageGroupList PicesInterface::PicesDataBase::ImageGroupLoad ()
Definition at line 1443 of file PicesDataBase.cpp.
PicesDataBaseImageGroup PicesInterface::PicesDataBase::ImageGroupLoad (String^ name)
Definition at line 1426 of file PicesDataBase.cpp.
void PicesInterface::PicesDataBase::ImageInsert (PicesRaster^ image, String^ imageFileName, String^ supperFileName, kkuint64 byteOffset, kkuint32 topLeftRow, kkuint32 topLeftCol, kkuint32 height, kkuint32 width, kkuint32 pixelCount, uchar connectedPixelDist, kkuint32 extractionLogEntryId, kkuint32 classLogEntryId, kkuint32 centroidRow, kkuint32 centroidCol, PicesClass^ class1, float class1Prob, PicesClass^ class2, float class2Prob, PicesClass^ validatedClass, float depth, float imageSize, PicesPointList^ sizeCoordinates, kkint32% imageId, bool% successful)
Parameters
byteOffset byteOffset of SipperRow containing TopLeftRow
Definition at line 462 of file PicesDataBase.cpp.
References PicesInterface::PicesPoint::Col, KKB::KKQueue< Entry >::PushOnBack(), PicesInterface::PicesPoint::Row, PicesInterface::PicesRaster::UnmanagedClass(), and PicesInterface::PicesClass::UnmanagedMLClass().
PicesDataBaseImage PicesInterface::PicesDataBase::ImageLoad (uint imageId)
Definition at line 549 of file PicesDataBase.cpp.
Referenced by SipperFile.PredictionBreakDownDisplay::PredictionBreakDownDisplay(), and SipperFile.PredictionBreakDownDisplayDual::PredictionBreakDownDisplayDual().
PicesDataBaseImage PicesInterface::PicesDataBase::ImageLoad (String^ imageFileName)
Definition at line 561 of file PicesDataBase.cpp.
void PicesInterface::PicesDataBase::ImageRemoveValidation (String^ imageFileName)
Definition at line 1125 of file PicesDataBase.cpp.
void PicesInterface::PicesDataBase::ImagesDeleteOneImage (String^ imageFileName)
Definition at line 1132 of file PicesDataBase.cpp.
PicesDataBaseImageList PicesInterface::PicesDataBase::ImagesQuery (PicesDataBaseImageGroup^ group, bool includeThumbnail)
Definition at line 581 of file PicesDataBase.cpp.
References KKB::KKQueue< Entry >::Owner(), and PicesInterface::PicesDataBaseImageGroup::UnManagedClass().
PicesDataBaseImageList PicesInterface::PicesDataBase::ImagesQuery (PicesDataBaseImageGroup^ imageGroup, String^ sipperFileName, PicesClass^ mlClass, System::Char classKeyToUse, float probMin, float probMax, int sizeMin, int sizeMax, float depthMin, float depthMax, uint restartImageId, int limit, bool includeThumbnail)
Definition at line 600 of file PicesDataBase.cpp.
References PicesInterface::ClassKeyToUse(), KKB::KKQueue< Entry >::Owner(), PicesInterface::PicesDataBaseImageGroup::UnManagedClass(), and PicesInterface::PicesClass::UnmanagedMLClass().
PicesDataBaseImageList PicesInterface::PicesDataBase::ImagesQuery (PicesDataBaseImageGroup^ imageGroup, String^ cruiseName, String^ stationName, String^ deploymentNum, PicesClass^ mlClass, System::Char classKeyToUse, float probMin, float probMax, int sizeMin, int sizeMax, float depthMin, float depthMax, uint restartImageId, int limit, bool includeThumbnail)
Definition at line 661 of file PicesDataBase.cpp.
References PicesInterface::ClassKeyToUse(), KKB::KKQueue< Entry >::Owner(), PicesInterface::PicesDataBaseImageGroup::UnManagedClass(), and PicesInterface::PicesClass::UnmanagedMLClass().
PicesDataBaseImageList PicesInterface::PicesDataBase::ImagesQueryByGrouop (PicesDataBaseImageGroup^ imageGroup, String^ cruiseName, String^ stationName, String^ deploymentNum, String^ sipperFileName, PicesClass^ mlClass, System::Char classKeyToUse, float probMin, float probMax, int sizeMin, int sizeMax, float depthMin, float depthMax, uint restartImageId, int limit, bool includeThumbnail)
Definition at line 727 of file PicesDataBase.cpp.
References PicesInterface::ClassKeyToUse(), KKB::KKQueue< Entry >::Owner(), PicesInterface::PicesDataBaseImageGroup::UnManagedClass(), and PicesInterface::PicesClass::UnmanagedMLClass().
PicesDataBaseImageList PicesInterface::PicesDataBase::ImagesQueryDeploymentSizeRange (String^ cruiseName, String^ stationName, String^ deploymentNum, PicesClass^ mlClass, System::Char cast, System::Char statistic, float sizeStart, float sizeEnd, float depthMin, float depthMax, int sampleQty, bool includeChildren)
Parameters
cast 'U' = UpCast, 'D' = DownCast, 'B' = Both'
statistic '0' = Area mm^2, '1' = Diameter, '2' = Spheroid Volume and '3' = EBv ((4/3)(Pie)(Major/2)(Minor/2)^2)
Definition at line 778 of file PicesDataBase.cpp.
References KKB::KKQueue< Entry >::Owner(), and PicesInterface::PicesClass::UnmanagedMLClass().
void PicesInterface::PicesDataBase::ImagesSizeDistributionByDepth (String^ cruiseName, String^ stationName, String^ deploymentNum, String^ className, float depthBinSize, char statistic, float initialValue, float growthRate, float endValue, PicesImageSizeDistribution^ % downCast, PicesImageSizeDistribution^ % upCast)
Definition at line 1157 of file PicesDataBase.cpp.
void PicesInterface::PicesDataBase::ImagesUpdateImageSize (String^ imageFileName, PicesPointList^ sizeCoordinates, float imageSize)
Definition at line 1111 of file PicesDataBase.cpp.
References PicesInterface::PicesPointList::ToUnmanaged().
void PicesInterface::PicesDataBase::ImagesUpdatePredictions (String^ imageFileName, PicesClass^ class1Pred, float class1Prob, PicesClass^ class2Pred, float class2Prob, uint logEntryId)
Definition at line 1063 of file PicesDataBase.cpp.
References PicesInterface::PicesClass::UnmanagedMLClass().
void PicesInterface::PicesDataBase::ImagesUpdatePredictionsList (uint _logEntryId, String^ _predictionList)
Updates prediction on multiple images at one time.
Parameters
[in] _logEntryId Log id of process that is doing the classification.
[in] _predictionList A tab delimited string that will contain the list of predictions. Each image will be separated by linefeed ('
') characters while each field for each image will be separated by "tabs('\t')". So if there are two images with predictions the string will look like "<ImageFileRootName><\t><Class1Name><\t><Class1Prob><\t><Class2Name><\t><Class2Prob><\n><ImageFileRootName><\t><Class1Name><\t><Class1Prob><\t><Class2Name><\t><Class2Prob>"
Definition at line 1089 of file PicesDataBase.cpp.
void PicesInterface::PicesDataBase::ImagesUpdateValidatedAndPredictClass (String^ imageFileName, PicesClass^ mlClass, float class1Prob)
Definition at line 1140 of file PicesDataBase.cpp.
References PicesInterface::PicesClass::UnmanagedMLClass().
void PicesInterface::PicesDataBase::ImagesUpdateValidatedClass (String^ imageFileName, PicesClass^ mlClass)
Definition at line 1099 of file PicesDataBase.cpp.
References PicesInterface::PicesClass::UnmanagedMLClass().
void PicesInterface::PicesDataBase::ImageUpdateInstrumentDataFields (PicesInstrumentData^ instumentData, String^ sipperFileName, uint scanLineStart, uint scanLineEnd)
Definition at line 1043 of file PicesDataBase.cpp.
References PicesInterface::PicesInstrumentData::UnmanagedClass().
void PicesInterface::PicesDataBase::Initialization () static
Definition at line 45 of file PicesDataBase.cpp.
PicesInstrumentData PicesInterface::PicesDataBase::InstrumentDataGetByScanLine (String^ sipperFileName, uint scanLine)
Retrieves instrument data that is closest to the specified scan-line.
Definition at line 1602 of file PicesDataBase.cpp.
Referenced by SipperFile.ImageViewer::ImageViewer(), SipperFile.ActiveTrainingLibraries::MakePredictions(), SipperFile.PredictionBreakDownDisplay::PredictionBreakDownDisplay(), SipperFile.PredictionBreakDownDisplayDual::PredictionBreakDownDisplayDual(), and SipperFileViewer.SipperFileViewer::SipperFileViewerRegionAroundImage().
List< String^ > PicesInterface::PicesDataBase::InstrumentDataGetFieldNames ()
Get the names of individual field names; used by applications that will query InstrumentData table allowing users to select fields to query and display.
Definition at line 1584 of file PicesDataBase.cpp.
array< float, 2 > PicesInterface::PicesDataBase::InstrumentDataGetSpecificFields (String^ sipperFileName, List< String^ >^ fieldNames, System::DateTime dateTimeStart, System::DateTime dateTimeEnd)
Returns 2d array consisting of the specific data fields from the Instrument data file for the specified SipperFile.
Returns
2D float array where each row will represent a Instrument row and each column will represent a field specified in 'fieldNames'.
Definition at line 1774 of file PicesDataBase.cpp.
array< float, 2 > PicesInterface::PicesDataBase::InstrumentDataGetSpecificFields (String^ cruiseName, String^ stationName, String^ deploymentNum, List< String^ >^ fieldNames, System::DateTime dateTimeStart, System::DateTime dateTimeEnd)
Definition at line 1812 of file PicesDataBase.cpp.
PicesVolumeSampledStatList PicesInterface::PicesDataBase::InstrumentDataGetVolumePerMeterDepth (String^ siperFileName, float depthBinSize)
Returns volume of water sampled, in cubic meters, by depth for a given sipper file.
Definition at line 1663 of file PicesDataBase.cpp.
PicesVolumeSampledStatList PicesInterface::PicesDataBase::InstrumentDataGetVolumePerMeterDepth (String^ cruiseName, String^ stationName, String^ deploymentNum, float depthBinSize)
Definition at line 1681 of file PicesDataBase.cpp.
PicesInstrumentDataList PicesInterface::PicesDataBase::InstrumentDataLoad (String^ sipperFileName)
Definition at line 1617 of file PicesDataBase.cpp.
References KKB::KKQueue< Entry >::Owner().
PicesInstrumentDataList PicesInterface::PicesDataBase::InstrumentDataLoad (String^ cruiseName, String^ stationName, String^ deploymentNum)
Definition at line 1638 of file PicesDataBase.cpp.
References KKB::KKQueue< Entry >::Owner().
PicesGPSDataPointList PicesInterface::PicesDataBase::InstrumentDataRetrieveGPSInfo (String^ cruiseName, String^ stationName, String^ deploymentNum, kkint32 timeInterval)
Parameters
timeInterval Interval in seconds
Definition at line 1854 of file PicesDataBase.cpp.
void PicesInterface::PicesDataBase::InstrumentDataSaveListForOneSipperFile (String^ sipperFileName, PicesInstrumentDataList^ data)
Definition at line 1707 of file PicesDataBase.cpp.
References PicesInterface::PicesInstrumentData::UnmanagedClass().
String PicesInterface::PicesDataBase::LastErrorDesc ()
Definition at line 234 of file PicesDataBase.cpp.
void PicesInterface::PicesDataBase::LogEntriesProcessEnd (PicesDataBaseLogEntry^ logEntry, float cpuTimeUsed, String^ completionResult)
Definition at line 1957 of file PicesDataBase.cpp.
References PicesInterface::PicesDataBaseLogEntry::UnmanagedClass().
PicesDataBaseLogEntry PicesInterface::PicesDataBase::LogEntriesProcessStart (String^ progCode, String^ progName, System::DateTime dateTimeCompiled, String^ cmdLine, String^ sipperFileName)
Definition at line 1937 of file PicesDataBase.cpp.
PicesDataBaseLogEntry PicesInterface::PicesDataBase::LogEntriesSelect (uint _logEntryId)
Definition at line 1967 of file PicesDataBase.cpp.
Referenced by SipperFile.ImageViewer::ImageViewer().
void PicesInterface::PicesDataBase::MLClassDelete (String^ className)
Definition at line 1372 of file PicesDataBase.cpp.
void PicesInterface::PicesDataBase::MLClassInsert (PicesClass^ picesClass)
Definition at line 1401 of file PicesDataBase.cpp.
References PicesInterface::PicesClass::UnmanagedMLClass().
void PicesInterface::PicesDataBase::MLClassInsertReturn (PicesClass^ mlClass, bool% successful)
Definition at line 1410 of file PicesDataBase.cpp.
References PicesInterface::PicesClass::UnmanagedMLClass().
PicesClass PicesInterface::PicesDataBase::MLClassLoad (String^ className)
Load instance on PicesClass with name = "ClassName" if not in database will return nullptr.
Parameters
className Load instance on PicesClass with name = "ClassName" if not in database will return nullptr
Definition at line 1248 of file PicesDataBase.cpp.
References PicesInterface::PicesClass::Description, KKMLL::MLClass::Description(), PicesInterface::PicesClass::Mandatory, KKMLL::MLClass::Mandatory(), PicesInterface::PicesClass::Parent, KKMLL::MLClass::Parent(), PicesInterface::PicesClass::Summarize, and KKMLL::MLClass::Summarize().
PicesClassList PicesInterface::PicesDataBase::MLClassLoadList ()
Definition at line 1287 of file PicesDataBase.cpp.
References PicesInterface::PicesClass::AddAChild(), KKB::endl(), PicesInterface::PicesClassList::LookUpByUnmanagedClass(), PicesInterface::PicesClass::Mandatory, KKMLL::MLClass::Mandatory(), PicesInterface::PicesClass::Parent, KKMLL::MLClass::Parent(), PicesInterface::PicesClassList::RootNode, PicesInterface::PicesClass::Summarize, and KKMLL::MLClass::Summarize().
void PicesInterface::PicesDataBase::MLClassUpdate (String^ oldClassName, PicesClass^ picesClass)
Definition at line 1380 of file PicesDataBase.cpp.
References PicesInterface::PicesClass::Name, and PicesInterface::PicesClass::UnmanagedMLClass().
array< array< String^ >^ > PicesInterface::PicesDataBase::QueryStatement (String^ statement, array< String^ >^ colsToReturn)
A general purpose SQL calling method; It will execute the command in 'statement' with the understanding that 'colsToReturn' will contain a list of columns in the result set that are to be returned.
/summary> param name="statement"> SQL Statement that is to be executed.
param name="colsToReturn"> A list of the columns from the results set that are to be returned The order that is specified will control the order in the returned results that they will appear.
returns>If successful will return a two dimensional array of strings where each row represents a single row from the results set. The columns will correspond to the names in 'colsToReturn'. /returns>
Definition at line 262 of file PicesDataBase.cpp.
References KKB::KKStrMatrix::NumRows(), and KKB::KKQueue< Entry >::QueueSize().
PicesDataBase PicesInterface::PicesDataBase::SelectNewDataBaseServer (PicesRunLog^ _runLog) static
Definition at line 198 of file PicesDataBase.cpp.
References PicesInterface::PicesDataBaseServerPrompter::SelectedServer.
String PicesInterface::PicesDataBase::ServerDescription ()
Definition at line 223 of file PicesDataBase.cpp.
void PicesInterface::PicesDataBase::SipperCruiseDelete (String^ cruiseName)
Definition at line 1981 of file PicesDataBase.cpp.
void PicesInterface::PicesDataBase::SipperCruiseInsert (PicesSipperCruise^ cruise)
Definition at line 1989 of file PicesDataBase.cpp.
References PicesInterface::PicesSipperCruise::UnmanagedSipperCruise().
PicesSipperCruise PicesInterface::PicesDataBase::SipperCruiseLoad (String^ cruiseName)
Definition at line 2000 of file PicesDataBase.cpp.
Referenced by SipperFile.CruiseDialog::CruiseDialog().
PicesSipperCruiseList PicesInterface::PicesDataBase::SipperCruiseLoadAllCruises ()
Definition at line 2012 of file PicesDataBase.cpp.
References KKB::KKQueue< Entry >::Owner().
void PicesInterface::PicesDataBase::SipperCruiseUpdate (PicesSipperCruise^ cruise)
Definition at line 2029 of file PicesDataBase.cpp.
References PicesInterface::PicesSipperCruise::UnmanagedSipperCruise().
void PicesInterface::PicesDataBase::SipperDeploymentDelete (String^ cruiseName, String^ stationName, String^ deploymentNum)
Definition at line 2116 of file PicesDataBase.cpp.
void PicesInterface::PicesDataBase::SipperDeploymentInsert (PicesSipperDeployment^ deployment)
Definition at line 2099 of file PicesDataBase.cpp.
References PicesInterface::PicesSipperDeployment::UnManagedClass().
PicesSipperDeploymentList PicesInterface::PicesDataBase::SipperDeploymentLoad (String^ cruiseName, String^ stationName)
Definition at line 2044 of file PicesDataBase.cpp.
References KKB::KKQueue< Entry >::Owner().
Referenced by PicesCommander.ClassificationStatus::ClassificationStatus().
PicesSipperDeployment PicesInterface::PicesDataBase::SipperDeploymentLoad (String^ cruiseName, String^ stationName, String^ deploymentNum)
Definition at line 2063 of file PicesDataBase.cpp.
PicesSipperDeploymentList PicesInterface::PicesDataBase::SipperDeploymentLoadByStation (String^ stationName)
Definition at line 2083 of file PicesDataBase.cpp.
References KKB::KKQueue< Entry >::Owner().
void PicesInterface::PicesDataBase::SipperDeploymentUpdate (PicesSipperDeployment^ deployment)
Definition at line 2107 of file PicesDataBase.cpp.
References PicesInterface::PicesSipperDeployment::UnManagedClass().
String PicesInterface::PicesDataBase::SipperFileGetFullPath (String^ _sipperFileName)
Definition at line 2258 of file PicesDataBase.cpp.
References KKB::KKStr::Empty().
Referenced by SipperFileViewer.SipperFileViewer::SipperFileViewerRegionAroundImage().
array< String^ > PicesInterface::PicesDataBase::SipperFileGetList (String^ cruiseName, String^ stationName, String^ deploymentNum)
Definition at line 2136 of file PicesDataBase.cpp.
void PicesInterface::PicesDataBase::SipperFileInsert (PicesSipperFile^ sipperFile)
Definition at line 2213 of file PicesDataBase.cpp.
References PicesInterface::PicesSipperFile::UnmanagedClass().
PicesSipperFileList PicesInterface::PicesDataBase::SipperFileLoad (String^ cruiseName, String^ stationName, String^ deploymentNum)
Definition at line 2168 of file PicesDataBase.cpp.
References KKB::KKQueue< Entry >::Owner().
void PicesInterface::PicesDataBase::SipperFileLoadOracle ()
Definition at line 2192 of file PicesDataBase.cpp.
PicesSipperFile PicesInterface::PicesDataBase::SipperFileRecLoad (String^ _sipperFileName)
Definition at line 2200 of file PicesDataBase.cpp.
Referenced by SipperFile.ImageViewer::ImageViewer(), PicesCommander.ImportValidatdClass::ImportValidatdClass(), and SipperFile.SipperFileDialog::SipperFileDialog().
void PicesInterface::PicesDataBase::SipperFileUpdate (PicesSipperFile^ sipperFile)
Definition at line 2236 of file PicesDataBase.cpp.
References PicesInterface::PicesSipperFile::UnmanagedClass().
void PicesInterface::PicesDataBase::SipperStationDelete (String^ cruiseName, String^ stationName)
Definition at line 2351 of file PicesDataBase.cpp.
void PicesInterface::PicesDataBase::SipperStationInsert (PicesSipperStation^ station)
Definition at line 2328 of file PicesDataBase.cpp.
References PicesInterface::PicesSipperStation::UnmanagedClass().
PicesSipperStationList PicesInterface::PicesDataBase::SipperStationLoad (String^ cruiseName)
Definition at line 2276 of file PicesDataBase.cpp.
PicesSipperStation PicesInterface::PicesDataBase::SipperStationLoad (String^ cruiseName, String^ stationName)
Definition at line 2291 of file PicesDataBase.cpp.
PicesSipperStationList PicesInterface::PicesDataBase::SipperStationsLoadByGpsRange (double latitudeMin, double latitudeMax, double longitudeMin, double longitudeMax)
Definition at line 2308 of file PicesDataBase.cpp.
void PicesInterface::PicesDataBase::SipperStationUpdate (PicesSipperStation^ station)
Definition at line 2340 of file PicesDataBase.cpp.
References PicesInterface::PicesSipperStation::UnmanagedClass().
bool PicesInterface::PicesDataBase::Successful () inline
Definition at line 99 of file PicesDataBase.h.
void PicesInterface::PicesDataBase::ThreadEnd () static
Call just before thread terminates.
Definition at line 256 of file PicesDataBase.cpp.
bool PicesInterface::PicesDataBase::ThreadInit () static
Call at start of new thread.
Definition at line 249 of file PicesDataBase.cpp.
bool PicesInterface::PicesDataBase::Valid ()
Definition at line 240 of file PicesDataBase.cpp.
Member Data Documentation
PicesDataBaseServer ^ PicesInterface::PicesDataBase::defaultGlobalServer = nullptr static
Definition at line 46 of file PicesDataBase.h.
PicesDataBase ^ PicesInterface::PicesDataBase::globaDbConn = nullptr static
Definition at line 44 of file PicesDataBase.h.
Property Documentation
bool PicesInterface::PicesDataBase::CancelFlag get set
Definition at line 86 of file PicesDataBase.h.
bool PicesInterface::PicesDataBase::LastOpSuccessful get
Definition at line 88 of file PicesDataBase.h.
PicesDataBaseServer^ PicesInterface::PicesDataBase::Server get
Definition at line 90 of file PicesDataBase.h.
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesInterface/PicesDataBase.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesInterface/PicesDataBase.cpp