Pices: MLL::InstrumentDataFlowMeter1 Class Reference
MLL::InstrumentDataFlowMeter1 Class Reference
#include <InstrumentDataFlowMeter1.h>
Public Member Functions
InstrumentDataFlowMeter1 (InstrumentDataManagerPtr _manager, const KKStr &_reportDir, bool _text, kkint32 _instrumentId)
virtual ~InstrumentDataFlowMeter1 ()
virtual void ReportInstrumentData (kkuint32 curScanLine, uchar sensorData)
Public Member Functions inherited from MLL::InstrumentDataReport
InstrumentDataReport (InstrumentDataManagerPtr _manager, const KKStr &_reportDir, bool _text, kkint32 _instrumentId, bool _useReportWithLineNumbers)
virtual ~InstrumentDataReport ()
const KKStr & CurTextLine ()
const KKStr & LastTextLine ()
Additional Inherited Members
Public Types inherited from MLL::InstrumentDataReport
typedef InstrumentDataReport * InstrumentDataReportPtr
typedef KKB::kkint32 kkint32
typedef KKB::kkuint32 kkuint32
Static Public Member Functions inherited from MLL::InstrumentDataReport
static InstrumentDataReportPtr CreateInstrumentDataReport (InstrumentDataManagerPtr _manager, const KKStr &_reportDir, bool _text, kkint32 _instrumentId)
A virtual Constructor for InstrumentDataReport instances.
Protected Member Functions inherited from MLL::InstrumentDataReport
KKStr InstrumentName ()
Protected Attributes inherited from MLL::InstrumentDataReport
KKStr curTextLine
Used where "text == true", Every time a character is read via 'ReportInstrumentData' will append to end of string.
kkint32 instrumentId
kkuint32 lastScanLineReported
KKStr lastTextLine
Used where "text == true", will keep an instance of last complete text line read.
InstrumentDataManagerPtr manager
ofstream report
KKStr reportFileName
KKStr reportFileNameWLN
ofstream reportWLN
bool text
bool useReportWithLineNumbers
Static Protected Attributes inherited from MLL::InstrumentDataReport
static const char * InstrumentNames []
Detailed Description
Definition at line 18 of file InstrumentDataFlowMeter1.h.
Constructor & Destructor Documentation
InstrumentDataFlowMeter1::InstrumentDataFlowMeter1 (InstrumentDataManagerPtr _manager, const KKStr & _reportDir, bool _text, kkint32 _instrumentId)
Definition at line 24 of file InstrumentDataFlowMeter1.cpp.
References NumTurnSignalsToTrack, and MLL::InstrumentDataReport::text.
InstrumentDataFlowMeter1::~InstrumentDataFlowMeter1 () virtual
Definition at line 50 of file InstrumentDataFlowMeter1.cpp.
Member Function Documentation
void InstrumentDataFlowMeter1::ReportInstrumentData (kkuint32 curScanLine, uchar sensorData) virtual
Reimplemented from MLL::InstrumentDataReport.
Definition at line 58 of file InstrumentDataFlowMeter1.cpp.
References KKB::endl(), MLL::InstrumentDataReport::manager, MLL::InstrumentDataManager::Meter1FlowRate(), MLL::InstrumentDataManager::Meter2FlowRate(), NumTurnSignalsToTrack, MLL::InstrumentDataReport::report, ScanLinesPerSecond, and MLL::InstrumentDataReport::text.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/InstrumentDataFlowMeter1.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/InstrumentDataFlowMeter1.cpp