Pices: KKMLL::ClassStatistic Class Reference
KKMLL::ClassStatistic Class Reference
Used by routines that retrieve Class statistics from FeatureVectorList instances.
#include <ClassStatistic.h>
Public Member Functions
ClassStatistic (const ClassStatistic &right)
ClassStatistic (MLClassPtr _mlClass, kkuint32 _count)
kkuint32 Count () const
void Increment ()
MLClassPtr MLClass () const
const KKStr & Name () const
const ClassStatistic & operator+= (const ClassStatistic &right)
Detailed Description
Used by routines that retrieve Class statistics from FeatureVectorList instances.
Definition at line 14 of file ClassStatistic.h.
Constructor & Destructor Documentation
ClassStatistic::ClassStatistic (const ClassStatistic & right)
Definition at line 22 of file ClassStatistic.cpp.
ClassStatistic::ClassStatistic (MLClassPtr _mlClass, kkuint32 _count)
Definition at line 29 of file ClassStatistic.cpp.
Member Function Documentation
kkuint32 KKMLL::ClassStatistic::Count () const inline
Definition at line 23 of file ClassStatistic.h.
Referenced by MLL::AbundanceCorrectionMatrix::AdjustClassificationCounts(), KKMLL::SVMparam::AvgNumOfFeatures(), KKMLL::FeatureVectorList::ClassStatisticsStr(), KKMLL::FeatureVectorList::GetClassDistribution(), MLL::AbundanceCorrectionMatrix::LumpCounts(), KKMLL::FeatureVectorList::MajorityClassFraction(), KKMLL::ClassStatisticList::ClassStatSortByCount::operator()(), operator+=(), PicesInterface::PicesClassStatistic::PicesClassStatistic(), KKMLL::FeatureVectorList::PrintClassStatisticsHTML(), KKMLL::ClassStatisticList::PrintReport(), KKMLL::Model::ReduceTrainExamples(), KKMLL::FeatureFileIOC45::SaveFile(), and MLL::FeatureFileIOPices::SaveFile().
void KKMLL::ClassStatistic::Increment () inline
Definition at line 26 of file ClassStatistic.h.
Referenced by KKMLL::FeatureVectorList::GetClassStatistics().
MLClassPtr KKMLL::ClassStatistic::MLClass () const inline
Definition at line 24 of file ClassStatistic.h.
Referenced by MLL::AbundanceCorrectionMatrix::AdjustClassificationCounts(), KKMLL::SVMparam::AvgNumOfFeatures(), KKMLL::FeatureVectorList::GetClassDistribution(), MLL::AbundanceCorrectionMatrix::LumpCounts(), KKMLL::ClassStatisticList::ClassStatisticSortComparrison::operator()(), KKMLL::ClassStatisticList::ClassStatSortByCount::operator()(), operator+=(), KKMLL::ClassStatisticList::operator+=(), PicesInterface::PicesClassStatistic::PicesClassStatistic(), KKMLL::ClassStatisticList::PushOnBack(), KKMLL::ClassStatisticList::PushOnFront(), and MLL::FeatureFileIOPices::SaveFile().
const KKStr & ClassStatistic::Name () const
Definition at line 38 of file ClassStatistic.cpp.
Referenced by KKMLL::FeatureVectorList::ClassStatisticsStr(), operator+=(), KKMLL::FeatureVectorList::PrintClassStatisticsHTML(), KKMLL::ClassStatisticList::PrintReport(), KKMLL::FeatureFileIOC45::SaveFile(), and MLL::FeatureFileIOPices::SaveFile().
const ClassStatistic & ClassStatistic::operator+= (const ClassStatistic & right)
Definition at line 48 of file ClassStatistic.cpp.
References Count(), KKB::endl(), MLClass(), and Name().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/KSquareLibraries/KKMachineLearning/ClassStatistic.h
C:/Users/kurtk_000/GitHub/KSquareLibraries/KKMachineLearning/ClassStatistic.cpp