Pices: MLL::SipperVariables Class Reference
MLL::SipperVariables Class Reference
Variables that specify where we can locate SIPPER and PICES directories and files are grouped here.
#include <SipperVariables_TEMP.h>
Public Types
typedef KKB::kkint32 kkint32
typedef KKB::kkint64 kkint64
typedef KKB::kkuint32 kkuint32
typedef KKB::kkuint64 kkuint64
Public Member Functions
SipperVariables ()
~SipperVariables ()
Static Public Member Functions
static bool AllowUpdates ()
'True' indicates that user is allowed to perform updates.
static void FinalCleanUp ()
static KKB::KKStr InstrumentDataFilesDir ()
Directory where Instrument Data files are stored.
static KKB::KKStr InstrumentDataReportDir ()
Directory where Instrument Data Reports are written to.
static KKB::KKStr LatitudeToStr (double latitude)
static KKB::KKStr LongitudeToStr (double longitude)
static void ParseImageFileName (const KKB::KKStr &fullFileName, KKB::KKStr &sipperFileName, KKB::kkuint32 &scanLineNum, KKB::kkuint32 &scanCol)
Will parse the name of a Image that was extracted from a SIPPER file into SipperFileName, ScanLineNum, and ScanCol.
static KKB::KKStr PicesCmdLineProgDir ()
Directory where you can Command Line programs such as "CrossValidation.exe".
static KKB::KKStr PicesConfigurationDirectory ()
Where application configuration files go; NOT training models.
static KKB::KKStr PicesDataFileDirectory ()
static KKB::KKStr PicesDataFilesDirectory ()
static KKB::KKStr PicesHomeDir ()
Pices Home Directory.
static KKB::KKStr PicesReportDir ()
static KKB::KKStr PicesTempDirectory ()
static void SetPicesHomeDir (const KKB::KKStr &_picesHomeDir)
static KKB::KKStr SipperConfigrationFileName ()
static KKB::KKStr SipperDirectoryListFileName ()
Specifies the file where we can list directories that containing Sipper Files.
static KKB::KKStr SipperFilesDefaultDir ()
static KKB::KKStr SipperInterfaceDir ()
static KKB::KKStr SipperInterfaceLogDir ()
Where the SipperInterface program will write its log files to.
static KKB::KKStr SubstituteInEvironmentVariables (const KKB::KKStr &src)
Expands the supplied string by substituting in Environment variable values.
static KKB::KKStr TrainingLibrariesDir ()
Directory where training library directories will be under.
static KKB::KKStr TrainingModelsConfigurationDir ()
Directory where all Training Model Configuration files are stored.
static KKB::KKStr TrainingModelsSaveFilesDir ()
Directory where all built trained models are stored.
static KKB::KKStr ValidationInfoDir ()
Directory where Validated Image File Names are stored during image extraction.
Static Public Attributes
static KKB::GoalKeeperPtr blocker = NULL
static KKB::KKStrPtr picesHomeDir = NULL
Detailed Description
Variables that specify where we can locate SIPPER and PICES directories and files are grouped here.
All methods and applications are to use these variables to locate files and directories that they need. This way all the knowledge or where to locate things is kept in this one class.
Definition at line 23 of file SipperVariables_TEMP.h.
Member Typedef Documentation
typedef KKB::kkint32 MLL::SipperVariables::kkint32
Definition at line 26 of file SipperVariables_TEMP.h.
typedef KKB::kkint64 MLL::SipperVariables::kkint64
Definition at line 28 of file SipperVariables_TEMP.h.
typedef KKB::kkuint32 MLL::SipperVariables::kkuint32
Definition at line 27 of file SipperVariables_TEMP.h.
typedef KKB::kkuint64 MLL::SipperVariables::kkuint64
Definition at line 29 of file SipperVariables_TEMP.h.
Constructor & Destructor Documentation
SipperVariables::SipperVariables ()
Definition at line 25 of file SipperVariables_TEMP.cpp.
SipperVariables::~SipperVariables ()
Definition at line 31 of file SipperVariables_TEMP.cpp.
Member Function Documentation
bool SipperVariables::AllowUpdates () static
'True' indicates that user is allowed to perform updates.
Definition at line 402 of file SipperVariables_TEMP.cpp.
void SipperVariables::FinalCleanUp () static
Definition at line 37 of file SipperVariables_TEMP.cpp.
KKStr SipperVariables::InstrumentDataFilesDir () static
Directory where Instrument Data files are stored.
Definition at line 141 of file SipperVariables_TEMP.cpp.
References KKB::osAddSlash().
KKStr SipperVariables::InstrumentDataReportDir () static
Directory where Instrument Data Reports are written to.
Definition at line 149 of file SipperVariables_TEMP.cpp.
References KKB::osAddSlash().
KKStr SipperVariables::LatitudeToStr (double latitude) static
Definition at line 345 of file SipperVariables_TEMP.cpp.
References KKB::StrFormatDouble(), and KKB::StrFormatInt().
KKStr SipperVariables::LongitudeToStr (double longitude) static
Definition at line 374 of file SipperVariables_TEMP.cpp.
References KKB::StrFormatDouble(), and KKB::StrFormatInt().
void SipperVariables::ParseImageFileName (const KKB::KKStr & fullFileName, KKB::KKStr & sipperFileName, KKB::kkuint32 & scanLineNum, KKB::kkuint32 & scanCol) static
Will parse the name of a Image that was extracted from a SIPPER file into SipperFileName, ScanLineNum, and ScanCol.
Parameters
[in] fullFileName Name of file that was assigned by the SIPPER image extraction program. from this name the three fields SipperFileName, ScanLineNum, and ScanCol can be extracted.
[in] sipperFileName Name of SIPPERfile that the image was originally extracted from.
[in] scanLineNum The scan line with respect to the SIPPER file where the first row in the image was extracted.
[in] scanCol The left most column in the original SIPPER file that this image was extracted.
Definition at line 412 of file SipperVariables_TEMP.cpp.
References KKB::KKStr::Empty(), KKB::KKStr::LocateLastOccurrence(), KKB::osGetRootName(), KKB::KKStr::Str(), and KKB::KKStr::SubStrPart().
KKStr SipperVariables::PicesCmdLineProgDir () static
Directory where you can Command Line programs such as "CrossValidation.exe".
Definition at line 132 of file SipperVariables_TEMP.cpp.
References KKB::osAddSlash().
KKStr SipperVariables::PicesConfigurationDirectory () static
Where application configuration files go; NOT training models.
Definition at line 177 of file SipperVariables_TEMP.cpp.
References KKB::osAddSlash().
KKStr SipperVariables::PicesDataFileDirectory () static
Definition at line 251 of file SipperVariables_TEMP.cpp.
References KKB::osAddSlash().
KKStr SipperVariables::PicesDataFilesDirectory () static
Definition at line 193 of file SipperVariables_TEMP.cpp.
References KKB::osAddSlash().
KKStr SipperVariables::PicesHomeDir () static
Pices Home Directory.
All other directories will be off this directory.
Definition at line 63 of file SipperVariables_TEMP.cpp.
References KKB::osDisplayWarning(), KKB::osGetCurrentDirectory(), KKB::osGetEnvVariable(), KKB::osGetFullPathOfApplication(), KKB::osGetParentDirPath(), and KKB::osGetPathPartOfFile().
KKStr SipperVariables::PicesReportDir () static
Definition at line 244 of file SipperVariables_TEMP.cpp.
References KKB::osAddSlash().
KKStr SipperVariables::PicesTempDirectory () static
Definition at line 258 of file SipperVariables_TEMP.cpp.
References KKB::osAddSlash(), KKB::osCreateDirectoryPath(), and KKB::osValidDirectory().
void SipperVariables::SetPicesHomeDir (const KKB::KKStr & _picesHomeDir) static
Definition at line 125 of file SipperVariables_TEMP.cpp.
KKStr SipperVariables::SipperConfigrationFileName () static
Definition at line 185 of file SipperVariables_TEMP.cpp.
References KKB::osAddSlash().
KKStr SipperVariables::SipperDirectoryListFileName () static
Specifies the file where we can list directories that containing Sipper Files.
Definition at line 200 of file SipperVariables_TEMP.cpp.
References KKB::osAddSlash().
KKStr SipperVariables::SipperFilesDefaultDir () static
Definition at line 208 of file SipperVariables_TEMP.cpp.
References KKB::osAddSlash().
KKStr SipperVariables::SipperInterfaceDir () static
Definition at line 155 of file SipperVariables_TEMP.cpp.
References KKB::osAddSlash(), and KKB::osGetEnvVariable().
KKStr SipperVariables::SipperInterfaceLogDir () static
Where the SipperInterface program will write its log files to.
Definition at line 167 of file SipperVariables_TEMP.cpp.
References KKB::osAddSlash().
KKStr SipperVariables::SubstituteInEvironmentVariables (const KKB::KKStr & src) static
Expands the supplied string by substituting in Environment variable values.
Similar to the 'osSubstituteInEvironmentVariables' method defined in 'osServices' except that there is some special processing for 'PicesHomeDir'. If 'PicesHomeDir' is not defined then the default location "C:\\Pices" will be used. If a environment variable other than "PicesHomeDir" is not defined then the original string will be returned.
ex: "$(PicesHomeDir)\WFS\Copepod" will expand to: "c:\Pices\WFS\Copepod".
Parameters
[in] src String that is to be search for environment variables and expanded.
Returns
The expanded string.
Definition at line 296 of file SipperVariables_TEMP.cpp.
References KKB::KKStr::EqualIgnoreCase(), KKB::KKStr::LocateCharacter(), KKB::osGetEnvVariable(), and KKB::KKStr::SubStrPart().
KKStr SipperVariables::TrainingLibrariesDir () static
Directory where training library directories will be under.
Definition at line 231 of file SipperVariables_TEMP.cpp.
References KKB::osAddSlash().
KKStr SipperVariables::TrainingModelsConfigurationDir () static
Directory where all Training Model Configuration files are stored.
Definition at line 216 of file SipperVariables_TEMP.cpp.
References KKB::osAddSlash().
KKStr SipperVariables::TrainingModelsSaveFilesDir () static
Directory where all built trained models are stored.
Definition at line 223 of file SipperVariables_TEMP.cpp.
References KKB::osAddSlash().
KKStr SipperVariables::ValidationInfoDir () static
Directory where Validated Image File Names are stored during image extraction.
Definition at line 237 of file SipperVariables_TEMP.cpp.
References KKB::osAddSlash().
Member Data Documentation
KKB::GoalKeeperPtr SipperVariables::blocker = NULL static
Definition at line 35 of file SipperVariables_TEMP.h.
KKB::KKStrPtr SipperVariables::picesHomeDir = NULL static
Definition at line 34 of file SipperVariables_TEMP.h.
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/SipperVariables_TEMP.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/SipperVariables_TEMP.cpp