Pices: MLL::DataBaseImageGroupEntry Class Reference
MLL::DataBaseImageGroupEntry Class Reference
#include <DataBaseImageGroupEntry.h>
Public Types
typedef DataBaseImageGroupEntry * DataBaseImageGroupEntryPtr
Public Member Functions
DataBaseImageGroupEntry (const DataBaseImageGroupEntry &imageGroupEntry)
DataBaseImageGroupEntry (kkint32 _imageGroupId, const KKStr &_imageFileName)
~DataBaseImageGroupEntry ()
const KKStr & ImageFileName () const
void ImageFileName (const KKStr &_imageFileName)
kkint32 ImageGroupId () const
void ImageGroupId (kkint32 _imageGroupId)
Detailed Description
Definition at line 20 of file DataBaseImageGroupEntry.h.
Member Typedef Documentation
typedef DataBaseImageGroupEntry* MLL::DataBaseImageGroupEntry::DataBaseImageGroupEntryPtr
Definition at line 23 of file DataBaseImageGroupEntry.h.
Constructor & Destructor Documentation
DataBaseImageGroupEntry::DataBaseImageGroupEntry (const DataBaseImageGroupEntry & imageGroupEntry)
Definition at line 23 of file DataBaseImageGroupEntry.cpp.
DataBaseImageGroupEntry::DataBaseImageGroupEntry (kkint32 _imageGroupId, const KKStr & _imageFileName)
Definition at line 30 of file DataBaseImageGroupEntry.cpp.
DataBaseImageGroupEntry::~DataBaseImageGroupEntry ()
Definition at line 39 of file DataBaseImageGroupEntry.cpp.
Member Function Documentation
const KKStr& MLL::DataBaseImageGroupEntry::ImageFileName () const inline
Definition at line 35 of file DataBaseImageGroupEntry.h.
Referenced by PicesInterface::PicesDataBaseImageGroupEntry::!PicesDataBaseImageGroupEntry(), and MLL::DataBase::ImageGroupEntriesInsert().
void MLL::DataBaseImageGroupEntry::ImageFileName (const KKStr & _imageFileName) inline
Definition at line 38 of file DataBaseImageGroupEntry.h.
kkint32 MLL::DataBaseImageGroupEntry::ImageGroupId () const inline
Definition at line 34 of file DataBaseImageGroupEntry.h.
Referenced by PicesInterface::PicesDataBaseImageGroupEntry::!PicesDataBaseImageGroupEntry(), and MLL::DataBase::ImageGroupEntriesInsert().
void MLL::DataBaseImageGroupEntry::ImageGroupId (kkint32 _imageGroupId) inline
Definition at line 37 of file DataBaseImageGroupEntry.h.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/DataBaseImageGroupEntry.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/DataBaseImageGroupEntry.cpp