Pices: PicesCommander.SizeDistribution Class Reference
PicesCommander.SizeDistribution Class Reference
Classes
class ClassTotals
Public Member Functions
SizeDistribution (int _bucketCount, int _bucketSize)
void Add (SizeDistribution x)
Will add in the contents of another SizeDistribution instance into this instance.
void Increment (PicesClass mlClass, int size)
void InitiateClass (PicesClass mlClass)
Method used to guarantee that the specified class is included; even if none occur.
void PrintByClassCollumns (System.IO.StreamWriter o, List< uint > scanLinesPerMeterDepth, List< InstrumentStatsByDepth > volumePerMeterDepth, bool printDensity, PicesClassList summarizeClasses)
void PrintCSVDistributionMatrix (System.IO.StreamWriter o)
void PrintFormatedDistributionMatrix (System.IO.StreamWriter o)
void PrintTabDelDistributionMatrix (System.IO.StreamWriter o)
ClassTotals SumUpFamilyOfClasses (PicesClass ancestor)
Returns an instance of 'ClassTotals' that contains a summary of the classes that are decedent of 'ancestor'.
int SumUpFamilyOfClassesForBucket (PicesClass ancestor, int bucketIdx)
Returns an instance of 'ClassTotals' that contains a summary of the classes that are decedent of 'ancestor'.
Detailed Description
Definition at line 18 of file SizeDistribution.cs.
Constructor & Destructor Documentation
PicesCommander.SizeDistribution.SizeDistribution (int _bucketCount, int _bucketSize) inline
Definition at line 205 of file SizeDistribution.cs.
Member Function Documentation
void PicesCommander.SizeDistribution.Add (SizeDistribution x) inline
Will add in the contents of another SizeDistribution instance into this instance.
Parameters
x The other 'SizeDistribution' instance to be accumulated to this instance.
Definition at line 288 of file SizeDistribution.cs.
References PicesCommander.SizeDistribution.ClassTotals.AddIn(), PicesCommander.SizeDistribution.ClassTotals.ClassTotals(), and PicesCommander.SizeDistribution.ClassTotals.Name.
Referenced by PicesCommander.ClassifierProcess.UpdateClassificationStats().
void PicesCommander.SizeDistribution.Increment (PicesClass mlClass, int size) inline
Definition at line 333 of file SizeDistribution.cs.
References PicesCommander.SizeDistribution.ClassTotals.ClassTotals(), PicesInterface::PicesClassList.GetUnKnownClassStatic(), PicesCommander.SizeDistribution.ClassTotals.Increment(), and PicesInterface::PicesClass.Name.
Referenced by PicesCommander.ClassifierProcess.StartThread().
void PicesCommander.SizeDistribution.InitiateClass (PicesClass mlClass) inline
Method used to guarantee that the specified class is included; even if none occur.
Parameters
mlClass Class to add
Definition at line 316 of file SizeDistribution.cs.
References PicesCommander.SizeDistribution.ClassTotals.ClassTotals(), PicesInterface::PicesClassList.GetUnKnownClassStatic(), and PicesInterface::PicesClass.Name.
Referenced by PicesCommander.ClassificationStatus.CleanUpMemory().
void PicesCommander.SizeDistribution.PrintByClassCollumns (System.IO.StreamWriter o, List< uint > scanLinesPerMeterDepth, List< InstrumentStatsByDepth > volumePerMeterDepth, bool printDensity, PicesClassList summarizeClasses) inline
Parameters
printDensity Indicates to print density rather than counts.
summarizeClasses List of classes that we need to print summary columns for.
Definition at line 429 of file SizeDistribution.cs.
References PicesCommander.InstrumentStatsByDepth.Add(), PicesCommander.SizeDistribution.ClassTotals.BucketCount(), PicesCommander.InstrumentStatsByDepth.cdomFluorescenceMean, PicesInterface::PicesInstrumentData.CdomFluorescenceUnit, PicesCommander.InstrumentStatsByDepth.ComputeMean(), PicesCommander.InstrumentStatsByDepth.densityMean, PicesInterface::PicesInstrumentData.DensityUnit, PicesInterface::PicesClassList.ExtractThreeTitleLines(), PicesInterface::PicesClassList.ExtractTwoTitleLines(), PicesCommander.InstrumentStatsByDepth.fluorescenceMean, PicesCommander.InstrumentStatsByDepth.fluorescenceSensorMean, PicesInterface::PicesInstrumentData.FluorescenceUnit, PicesInterface::PicesClassList.GetUniqueClass(), PicesInterface::PicesClass.Name, PicesCommander.SizeDistribution.ClassTotals.Name, PicesCommander.InstrumentStatsByDepth.Oxygen_molPerKg, PicesCommander.InstrumentStatsByDepth.oxygenMean, PicesInterface::PicesInstrumentData.OxygenUnit, PicesCommander.InstrumentStatsByDepth.salinityMean, PicesInterface::PicesInstrumentData.SalinityUnit, PicesInterface::PicesClassList.SortByName(), PicesCommander.SizeDistribution.SumUpFamilyOfClassesForBucket(), PicesCommander.InstrumentStatsByDepth.temperatureMean, PicesInterface::PicesInstrumentData.TemperatureUnit, PicesCommander.InstrumentStatsByDepth.transmisivityMean, PicesInterface::PicesInstrumentData.TransmisivityUnit, PicesCommander.InstrumentStatsByDepth.turbidityMean, and PicesInterface::PicesInstrumentData.TurbidityUnit.
Referenced by PicesCommander.ClassificationStatus.CleanUpMemory().
void PicesCommander.SizeDistribution.PrintCSVDistributionMatrix (System.IO.StreamWriter o) inline
Definition at line 377 of file SizeDistribution.cs.
References PicesCommander.SizeDistribution.ClassTotals.AddIn(), PicesCommander.SizeDistribution.ClassTotals.ClassTotals(), and PicesCommander.SizeDistribution.ClassTotals.PrintCSVLine().
void PicesCommander.SizeDistribution.PrintFormatedDistributionMatrix (System.IO.StreamWriter o) inline
Definition at line 352 of file SizeDistribution.cs.
References PicesCommander.SizeDistribution.ClassTotals.AddIn(), PicesCommander.SizeDistribution.ClassTotals.ClassTotals(), and PicesCommander.SizeDistribution.ClassTotals.PrintFormatedLine().
void PicesCommander.SizeDistribution.PrintTabDelDistributionMatrix (System.IO.StreamWriter o) inline
Definition at line 404 of file SizeDistribution.cs.
References PicesCommander.SizeDistribution.ClassTotals.AddIn(), PicesCommander.SizeDistribution.ClassTotals.ClassTotals(), and PicesCommander.SizeDistribution.ClassTotals.PrintTabDelLine().
ClassTotals PicesCommander.SizeDistribution.SumUpFamilyOfClasses (PicesClass ancestor) inline
Returns an instance of 'ClassTotals' that contains a summary of the classes that are decedent of 'ancestor'.
The newly instantiated instance will point to the same instances of 'ClassTotals' that this instance points to. As a result you should only call this method after you are done accumulating data.
Parameters
ancestor
Returns
Definition at line 254 of file SizeDistribution.cs.
References PicesCommander.SizeDistribution.ClassTotals.AddIn(), PicesInterface::PicesClass.Children, PicesCommander.SizeDistribution.ClassTotals.ClassTotals(), and PicesInterface::PicesClass.Name.
int PicesCommander.SizeDistribution.SumUpFamilyOfClassesForBucket (PicesClass ancestor, int bucketIdx) inline
Returns an instance of 'ClassTotals' that contains a summary of the classes that are decedent of 'ancestor'.
The newly instantiated instance will point to the same instances of 'ClassTotals' that this instance points to. As a result you should only call this method after you are done accumulating data.
Parameters
ancestor
Returns
Definition at line 226 of file SizeDistribution.cs.
References PicesCommander.SizeDistribution.ClassTotals.BucketCount(), PicesInterface::PicesClass.Children, and PicesInterface::PicesClass.Name.
Referenced by PicesCommander.SizeDistribution.PrintByClassCollumns().
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/Pices/Apps/PicesCommander/SizeDistribution.cs