Pices: MLL::InstrumentDataFileManager Class Reference
MLL::InstrumentDataFileManager Class Reference
#include <InstrumentDataFileManager.h>
Public Types
typedef KKB::kkint32 kkint32
typedef KKB::kkint64 kkint64
typedef KKB::kkuint32 kkuint32
typedef KKB::kkuint64 kkuint64
Public Member Functions
InstrumentDataFileManager ()
~InstrumentDataFileManager ()
void GetClosestInstrumentData (const KKStr &imageFileName, InstrumentDataPtr &instrumentData, VolConstBool &cancelFlag, RunLog &log)
VectorUlong GetScanLinesPerMeterProfile2 (const KKStr &sipperFileName, SipperFilePtr sipperFile, VolConstBool &cancelFlag, RunLog &log)
VectorFloat GetVolumePerMeterProfile2 (const KKStr &sipperFileName, SipperFilePtr sipperFile, VolConstBool &cancelFlag, RunLog &log)
Static Public Member Functions
static void FinalCleanUp ()
static InstrumentDataPtr GetClosestInstrumentData (const KKStr &imageFileName, VolConstBool &cancelFlag, RunLog &log)
static KKStr GetFullSipperFileName (const KKStr &rootName)
static InstrumentDataListPtr GetInstrumentDataForSipperFile (const KKStr &sipperFileName, SipperFilePtr sipperFile, bool forceReExtract, VolConstBool &cancelFlag, RunLog &log)
static VectorKKStr GetListOfSipperFiles (RunLog &log)
Returns a list of all known SIPPER files on the local PC; each entry includes the file path.
static RasterSipperPtr GetOrigSipperImage (const KKStr &sipperFileRootName, KKB::kkuint64 byteOffset, kkuint32 topLeftRow, kkuint32 tooLeftCol, kkuint32 height, kkuint32 width, KKB::uchar connectedComponentDist, RunLog &log)
static VectorUlong GetScanLinesPerMeterProfile (const KKStr &sipperFileName, SipperFilePtr sipperFile, VolConstBool &cancelFlag, RunLog &log)
static VectorFloat GetVolumePerMeterProfile (const KKStr &sipperFileName, SipperFilePtr sipperFile, VolConstBool &cancelFlag, RunLog &log)
static void Initialize ()
static bool Initialized ()
static void InitializePop ()
static void InitializePush ()
static InstrumentDataListPtr ReExtractInstrumentDataForSipperFile (const KKStr &sipperFileName, SipperFilePtr sipperFile, VolConstBool &cancelFlag, RunLog &log)
static KKStr SipperFileRootNameFromSipperImageFileName (const KKStr &sipperFileName)
Detailed Description
Author
Kurt Kramer
 @author Kurt Kramer                                                                                        *
                                                                                                            *
 Developer:   Kurt Kramer                                                                                   *
 Date:        2007-10                                                                                       *
 Place:       Eastern Tropical Pacific (ETP)  aboard the Seward Johnson.                                    *
                                                                                                            *
 Purpose                                                                                                    *
 =======                                                                                                    *
 My purpose in life is to provide a means for getting instrument data for a specified Plankton image. Given *
 an image file name we can derive the original SIPPER file that it came from and the scan line from within  *
 this file where the image was extracted from.                                                              *
                                                                                                            *
 I will maintain InstrumentDataList objects; one for each SIPPER file that I am queried about.  When I get  *
 an image to look up If I do not already have its related 'InstrumentDataList' object I will:               *
    1) Look to see if a InstrumentData file already exists with this data.                                  *
    2) If no file available I will then go to the Original SIPPER file for the data and build a file that    *
       can be used the next time rather than scanning the whole SIPPER file.                                *
                                                                                                            *
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - *
                                                                                                            *
 HOW TO USE:                                                                                                *
 "InitializePush" -  Before using any functions call this static method.  It will create the necessary data *
                   structures needed.  Then for each SIPPER image file that you need Instrument data for    *
                   call the static method "GetClosestInstrumentData".                                       *
                                                                                                            *
 "InitializePop"  -  Before the application terminates call this static method to free up allocated memory. *
                                                                                                            *
 "GetClosestInstrumentData" - Call this static method to get the instrument data that is closest to the     *
                   SIPPER image file provided.                                                              *
                                                                                                            *
 "InitializePush"  and  "IniailizePop" replace "Initialize" and "CleanUp" respectively.   The "Push" and    *
                   "Pop" describe the additional functionality provided.  This way you no longer need to    *
                   worry if a caller has already initialized "IntrumenDdataFileNamager".                    *
                                                                                                            *
                                                                                                            *
 Sipper File Directories.                                                                                   *
 ========================                                                                                   *
 This module will automatically look in a default directory "%PicesHomeDir%\SipperFiles".  If you want it   *
 to search other directories for SipperFiles you need to create a text file "SipperDirectoryList.txt"       *
 in "%PicesHomeDir%\DataFiles\".  Create one text line for each additional SubDirectory structure that you  *
 want this module to search for SipperFiles.                                                                *
                                                                                                            *
Definition at line 95 of file InstrumentDataFileManager.h.
Member Typedef Documentation
typedef KKB::kkint32 MLL::InstrumentDataFileManager::kkint32
Definition at line 98 of file InstrumentDataFileManager.h.
typedef KKB::kkint64 MLL::InstrumentDataFileManager::kkint64
Definition at line 100 of file InstrumentDataFileManager.h.
typedef KKB::kkuint32 MLL::InstrumentDataFileManager::kkuint32
Definition at line 99 of file InstrumentDataFileManager.h.
typedef KKB::kkuint64 MLL::InstrumentDataFileManager::kkuint64
Definition at line 101 of file InstrumentDataFileManager.h.
Constructor & Destructor Documentation
InstrumentDataFileManager::InstrumentDataFileManager ()
Definition at line 42 of file InstrumentDataFileManager.cpp.
References KKB::GoalKeeper::EndBlock(), MLL::PicesVariables::HomeDir(), MLL::PicesVariables::InstrumentDataFilesDir(), KKB::osCreateDirectoryPath(), and KKB::GoalKeeper::StartBlock().
Referenced by InitializePush().
InstrumentDataFileManager::~InstrumentDataFileManager ()
Definition at line 67 of file InstrumentDataFileManager.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
Member Function Documentation
void InstrumentDataFileManager::FinalCleanUp () static
Definition at line 109 of file InstrumentDataFileManager.cpp.
References InitializePop().
void InstrumentDataFileManager::GetClosestInstrumentData (const KKStr & imageFileName, InstrumentDataPtr & instrumentData, VolConstBool & cancelFlag, RunLog & log)
Definition at line 258 of file InstrumentDataFileManager.cpp.
References KKB::GoalKeeper::EndBlock(), KKB::Max(), MLL::PicesVariables::ParseImageFileName(), MLL::InstrumentDataList::SearchForNearestScanLine(), MLL::InstrumentDataList::SipperFileName(), and KKB::GoalKeeper::StartBlock().
Referenced by MLL::DataBaseImageList::CalculateDensitesByQuadrat(), MLL::ImageFeaturesList::CalculateDensitesByQuadrat(), MLL::FeatureFileIOPices::FeatureDataReSink(), GetClosestInstrumentData(), and MLL::FeatureFileIOPices::LoadFile().
InstrumentDataPtr InstrumentDataFileManager::GetClosestInstrumentData (const KKStr & imageFileName, VolConstBool & cancelFlag, RunLog & log) static
Definition at line 242 of file InstrumentDataFileManager.cpp.
References GetClosestInstrumentData().
KKStr InstrumentDataFileManager::GetFullSipperFileName (const KKStr & rootName) static
Definition at line 168 of file InstrumentDataFileManager.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
InstrumentDataListPtr InstrumentDataFileManager::GetInstrumentDataForSipperFile (const KKStr & sipperFileName, SipperFilePtr sipperFile, bool forceReExtract, VolConstBool & cancelFlag, RunLog & log) static
Definition at line 411 of file InstrumentDataFileManager.cpp.
References Initialize(), and KKB::osGetRootName().
VectorKKStr InstrumentDataFileManager::GetListOfSipperFiles (RunLog & log) static
Returns a list of all known SIPPER files on the local PC; each entry includes the file path.
Definition at line 198 of file InstrumentDataFileManager.cpp.
References KKB::GoalKeeper::EndBlock(), Initialize(), and KKB::GoalKeeper::StartBlock().
Referenced by MLL::SipperFileList::GetListOfSipperFilesWeCanFind(), and MLL::DataBase::InstrumentDataLoadAllSipperFiles().
RasterSipperPtr InstrumentDataFileManager::GetOrigSipperImage (const KKStr & sipperFileRootName, KKB::kkuint64 byteOffset, kkuint32 topLeftRow, kkuint32 tooLeftCol, kkuint32 height, kkuint32 width, KKB::uchar connectedComponentDist, RunLog & log) static
Parameters
byteOffset Byte offset into SipperFile where Scan-Line 'topLeftRow' starts.
topLeftRow Top left scan-line where the Sipper-Image resides.
tooLeftCol Top left column where the Sipper-Image resides.
height Height
width Width
connectedComponentDist Size of structure used by Connected Component Analysis to locate in Sipper-Image.
log Where logging messages are sent.
Definition at line 625 of file InstrumentDataFileManager.cpp.
References MLL::SipperBuff::CreateSipperBuff(), MLL::SipperBuff::CurRow(), KKB::KKStr::Empty(), MLL::SipperBuff::Eof(), MLL::SipperBuff::GetNextLine(), KKB::Raster::Green(), Initialize(), KKB::Raster::ReduceToMostCompleteBlob(), and MLL::SipperBuff::SkipToScanLine().
Referenced by MLL::DataBaseImage::GetOrigImageFromSipperFile().
VectorUlong InstrumentDataFileManager::GetScanLinesPerMeterProfile (const KKStr & sipperFileName, SipperFilePtr sipperFile, VolConstBool & cancelFlag, RunLog & log) static
Definition at line 609 of file InstrumentDataFileManager.cpp.
References GetScanLinesPerMeterProfile2(), and Initialize().
VectorUlong InstrumentDataFileManager::GetScanLinesPerMeterProfile2 (const KKStr & sipperFileName, SipperFilePtr sipperFile, VolConstBool & cancelFlag, RunLog & log)
Definition at line 566 of file InstrumentDataFileManager.cpp.
References MLL::InstrumentDataList::GetScanLinesPerMeterProfile(), KKB::osGetRootName(), and MLL::InstrumentDataList::SipperFileName().
Referenced by GetScanLinesPerMeterProfile().
VectorFloat InstrumentDataFileManager::GetVolumePerMeterProfile (const KKStr & sipperFileName, SipperFilePtr sipperFile, VolConstBool & cancelFlag, RunLog & log) static
Definition at line 594 of file InstrumentDataFileManager.cpp.
References GetVolumePerMeterProfile2(), and Initialize().
VectorFloat InstrumentDataFileManager::GetVolumePerMeterProfile2 (const KKStr & sipperFileName, SipperFilePtr sipperFile, VolConstBool & cancelFlag, RunLog & log)
Definition at line 538 of file InstrumentDataFileManager.cpp.
References MLL::InstrumentDataList::GetVolumePerMeterProfile(), KKB::osGetRootName(), MLL::InstrumentDataList::SipperFileName(), and VectorFloat.
Referenced by GetVolumePerMeterProfile().
void InstrumentDataFileManager::Initialize () static
Definition at line 102 of file InstrumentDataFileManager.cpp.
References InitializePush().
Referenced by GetInstrumentDataForSipperFile(), GetListOfSipperFiles(), GetOrigSipperImage(), GetScanLinesPerMeterProfile(), GetVolumePerMeterProfile(), and ReExtractInstrumentDataForSipperFile().
bool InstrumentDataFileManager::Initialized () static
Definition at line 121 of file InstrumentDataFileManager.cpp.
void InstrumentDataFileManager::InitializePop () static
Definition at line 149 of file InstrumentDataFileManager.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
Referenced by MLL::DataBaseImageList::CalculateDensitesByQuadrat(), MLL::ImageFeaturesList::CalculateDensitesByQuadrat(), MLL::FeatureFileIOPices::FeatureDataReSink(), FinalCleanUp(), and MLL::FeatureFileIOPices::LoadFile().
void InstrumentDataFileManager::InitializePush () static
Definition at line 128 of file InstrumentDataFileManager.cpp.
References KKB::GoalKeeper::EndBlock(), InstrumentDataFileManager(), and KKB::GoalKeeper::StartBlock().
Referenced by MLL::DataBaseImageList::CalculateDensitesByQuadrat(), MLL::ImageFeaturesList::CalculateDensitesByQuadrat(), MLL::FeatureFileIOPices::FeatureDataReSink(), Initialize(), and MLL::FeatureFileIOPices::LoadFile().
InstrumentDataListPtr InstrumentDataFileManager::ReExtractInstrumentDataForSipperFile (const KKStr & sipperFileName, SipperFilePtr sipperFile, VolConstBool & cancelFlag, RunLog & log) static
Definition at line 430 of file InstrumentDataFileManager.cpp.
References Initialize(), and KKB::osGetRootName().
Referenced by MLL::DataBase::FeatureDataGetOneSipperFile(), MLL::DataBase::InstrumentDataLoadAllSipperFiles(), and MLL::DataBase::InstrumentDataReFreshSipperFile().
KKStr InstrumentDataFileManager::SipperFileRootNameFromSipperImageFileName (const KKStr & sipperFileName) static
Definition at line 222 of file InstrumentDataFileManager.cpp.
References KKB::KKStr::LocateLastOccurrence(), KKB::osGetRootName(), and KKB::KKStr::SubStrPart().
Referenced by MLL::DataBase::FeatureDataRecLoad().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/InstrumentDataFileManager.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/InstrumentDataFileManager.cpp