Pices: MLL::PicesFVProducer Class Reference
MLL::PicesFVProducer Class Reference
#include <PicesFVProducer.h>
Public Member Functions
PicesFVProducer (FactoryFVProducerPtr factory)
virtual ~PicesFVProducer ()
virtual ImageFeaturesPtr ComputeFeatureVector (const Raster &srcImage, const MLClassPtr knownClass, RasterListPtr intermediateImages, float priorReductionFactor, RunLog &runLog)
Compute a FeatureVector for the supplied 'image'.
virtual ImageFeaturesPtr ComputeFeatureVectorFromImage (const KKStr &fileName, const MLClassPtr knownClass, RasterListPtr intermediateImages, RunLog &runLog)
Compute a FeatureVector from the image file specified by 'fileName'.
virtual const type_info * FeatureVectorListTypeId () const
Returns the 'type_info' of the FeatureVectorList derived class that can contain instances in 'FeatureVector' instances created by this producer.
virtual const type_info * FeatureVectorTypeId () const
Returns the 'type_info' of the Feature Vector that this instance of 'FeatureComputer' creates.
virtual FeatureVectorListPtr ManufacturFeatureVectorList (bool owner, RunLog &runLog) const
Manufactures a instance of a derived 'FeatureVectorList' class that is appropriate for containing instances of FeatureVectors by this FeatureVectorProducer.
virtual kkint16 Version () const
The version number of the FeatureVector that is going to be computed.
Public Member Functions inherited from KKMLL::FeatureVectorProducer
FeatureVectorProducer (const KKStr &_name, FactoryFVProducerPtr _factory)
virtual ~FeatureVectorProducer ()
FactoryFVProducerPtr Factory () const
Returns pointer to factory that instantiated this instance.
kkuint32 FeatureCount () const
const KKStr & FeatureName (kkuint32 fieldNum) const
FileDescConstPtr FileDesc () const
Returns back a "FileDesc" instance that describes the features that this instance of 'FeatureVectorProducer' creates.
kkuint32 MaxNumOfFeatures ()
Same as FeatureCount.
const KKStr & Name () const
Returns a kkint16 description of the FeatureVector which can be used as part/all of a File or Directory name.
Static Public Member Functions
static FileDescPtr DefineFileDescStatic ()
static kkint32 MaxNumOfFeatures ()
Protected Member Functions
virtual FileDescPtr DefineFileDesc () const
Additional Inherited Members
Public Types inherited from KKMLL::FeatureVectorProducer
typedef FeatureVectorProducer * FeatureVectorProducerPtr
Detailed Description
Definition at line 22 of file PicesFVProducer.h.
Constructor & Destructor Documentation
PicesFVProducer::PicesFVProducer (FactoryFVProducerPtr factory)
Definition at line 43 of file PicesFVProducer.cpp.
Referenced by MLL::PicesFVProducerFactory::ManufactureInstance().
PicesFVProducer::~PicesFVProducer () virtual
Definition at line 53 of file PicesFVProducer.cpp.
Member Function Documentation
ImageFeaturesPtr PicesFVProducer::ComputeFeatureVector (const Raster & image, const MLClassPtr knownClass, RasterListPtr intermediateImages, float priorReductionFactor, RunLog & runLog) virtual
Compute a FeatureVector for the supplied 'image'.
Parameters
[in] image
[in] knownClass The class label that will be assigned to this Feature vector.
[in,out] intermediateImages If not NULL will save a copy of the intermediate images created during Feature Computation; the call will own the list and its contents.
[in] priorReductionFactor The reduction that was done to the image prior to calling this routine; if no size change was made then set this field to 1.0. The FeaureVector computation routines will use this field to adjust SizeDependent features appropriately. the value of this parameter represents the number of pixels that were reduced to 1 pixel. A value of 3 indicates (3 x 3) pixels were reduced to 1 pixel.
[in] log Logging file.
Returns
The resultant Feature vector computed.
Implements KKMLL::FeatureVectorProducer.
Definition at line 60 of file PicesFVProducer.cpp.
References KKB::endl(), KKB::Raster::FileName(), KKB::RunLog::Level(), and KKB::KKQueue< Entry >::PushOnBack().
Referenced by ComputeFeatureVectorFromImage().
ImageFeaturesPtr PicesFVProducer::ComputeFeatureVectorFromImage (const KKStr & fileName, const MLClassPtr knownClass, RasterListPtr intermediateImages, RunLog & runLog) virtual
Compute a FeatureVector from the image file specified by 'fileName'.
Parameters
[in] image
[in] knownClass The class label that will be assigned to this Feature vector.
[in,out] intermediateImages If not NULL will save a copy of the intermediate images created during Feature Computation; the call will own the list and its contents.
[in] log Logging file.
Returns
The resultant Feature vector computed.
Reimplemented from KKMLL::FeatureVectorProducer.
Definition at line 107 of file PicesFVProducer.cpp.
References ComputeFeatureVector(), KKB::endl(), and KKB::RunLog::Level().
FileDescPtr PicesFVProducer::DefineFileDesc () const protected virtual
Implements KKMLL::FeatureVectorProducer.
Definition at line 162 of file PicesFVProducer.cpp.
References DefineFileDescStatic().
FileDescPtr PicesFVProducer::DefineFileDescStatic () static
Definition at line 170 of file PicesFVProducer.cpp.
References MLL::FeatureFileIOPices::NewPlanktonFile().
Referenced by DefineFileDesc(), MLL::PicesFVProducerFactory::FileDesc(), and MLL::PicesFVProducerFactory::ManufacturFeatureVectorList().
const type_info * PicesFVProducer::FeatureVectorListTypeId () const virtual
Returns the 'type_info' of the FeatureVectorList derived class that can contain instances in 'FeatureVector' instances created by this producer.
Implements KKMLL::FeatureVectorProducer.
Definition at line 148 of file PicesFVProducer.cpp.
const type_info * PicesFVProducer::FeatureVectorTypeId () const virtual
Returns the 'type_info' of the Feature Vector that this instance of 'FeatureComputer' creates.
Implements KKMLL::FeatureVectorProducer.
Definition at line 141 of file PicesFVProducer.cpp.
FeatureVectorListPtr PicesFVProducer::ManufacturFeatureVectorList (bool owner, RunLog & runLog) const virtual
Manufactures a instance of a derived 'FeatureVectorList' class that is appropriate for containing instances of FeatureVectors by this FeatureVectorProducer.
Implements KKMLL::FeatureVectorProducer.
Definition at line 178 of file PicesFVProducer.cpp.
kkint32 PicesFVProducer::MaxNumOfFeatures () static
Definition at line 155 of file PicesFVProducer.cpp.
References MLL::FeatureFileIOPices::PlanktonMaxNumOfFields().
virtual kkint16 MLL::PicesFVProducer::Version () const inline virtual
The version number of the FeatureVector that is going to be computed.
Implements KKMLL::FeatureVectorProducer.
Definition at line 60 of file PicesFVProducer.h.
References _PicesFVProducer_VersionNum_.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/PicesFVProducer.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/PicesFVProducer.cpp