Pices: ImageExtractionManager::LogicalFrameBlob Class Reference
ImageExtractionManager::LogicalFrameBlob Class Reference
Used by the ImageExtractionManager to manage a single blob.
#include <LogicalFrameBlob.h>
Public Types
typedef LogicalFrameBlob * LogicalFrameBlobPtr
typedef map< kkint32, LogicalFrameBlobPtr > NeighborsList
typedef vector< LogicalFrameBlobPtr > VectorLogicalFrameBlob
Public Member Functions
LogicalFrameBlob (kkuint32 _maxFrameHeight, kkuint32 _maxFrameWidth)
~LogicalFrameBlob ()
void AddNeighbor (LogicalFrameBlobPtr _neighbor)
kkuint32 ColLeft ()
kkuint32 ColRight ()
void DialateBlob (uchar **frame, kkint32 **blobIds, kkint32 size)
bool Explored () const
void Explored (bool _explored)
kkuint32 Height ()
kkint32 Id ()
NeighborsList & Neighbors ()
kkuint32 PixelCount ()
kkuint32 RowBot ()
kkuint32 RowTop ()
kkuint32 Width ()
Public Attributes
kkuint32 colLeft
kkuint32 colRight
bool explored
kkint32 id
kkuint32 maxFrameHeight
kkuint32 maxFrameWidth
kkint32 neighborIdLastAdded
NeighborsList neighbors
kkuint32 pixelCount
kkuint32 rowBot
kkuint32 rowTop
Detailed Description
Used by the ImageExtractionManager to manage a single blob.
Author
Kurt Kramer
Used by ImageExtractionManager to keep track of an individual connected *
components in a sipper frame. We call these connected components blobs. *
The fields rowTop, rowBot, colLeft, colRight indicate a tight bounding  *
box around the blob.                                                    *
Definition at line 29 of file LogicalFrameBlob.h.
Member Typedef Documentation
typedef LogicalFrameBlob* ImageExtractionManager::LogicalFrameBlob::LogicalFrameBlobPtr
Definition at line 33 of file LogicalFrameBlob.h.
typedef map<kkint32, LogicalFrameBlobPtr> ImageExtractionManager::LogicalFrameBlob::NeighborsList
Definition at line 36 of file LogicalFrameBlob.h.
typedef vector<LogicalFrameBlobPtr> ImageExtractionManager::LogicalFrameBlob::VectorLogicalFrameBlob
Definition at line 34 of file LogicalFrameBlob.h.
Constructor & Destructor Documentation
LogicalFrameBlob::LogicalFrameBlob (kkuint32 _maxFrameHeight, kkuint32 _maxFrameWidth)
Definition at line 21 of file LogicalFrameBlob.cpp.
LogicalFrameBlob::~LogicalFrameBlob ()
Definition at line 40 of file LogicalFrameBlob.cpp.
References neighbors.
Member Function Documentation
void LogicalFrameBlob::AddNeighbor (LogicalFrameBlobPtr _neighbor)
Definition at line 148 of file LogicalFrameBlob.cpp.
References Id(), neighborIdLastAdded, and neighbors.
Referenced by ImageExtractionManager::LogicalFrame::MemoryConsumedEstimated().
kkuint32 ImageExtractionManager::LogicalFrameBlob::ColLeft () inline
Definition at line 47 of file LogicalFrameBlob.h.
Referenced by ImageExtractionManager::SipperImage::AddBlob(), and ImageExtractionManager::SipperImage::GetRaster().
kkuint32 ImageExtractionManager::LogicalFrameBlob::ColRight () inline
Definition at line 48 of file LogicalFrameBlob.h.
Referenced by ImageExtractionManager::SipperImage::AddBlob(), and ImageExtractionManager::SipperImage::GetRaster().
void LogicalFrameBlob::DialateBlob (uchar ** frame, kkint32 ** blobIds, kkint32 size)
Definition at line 47 of file LogicalFrameBlob.cpp.
References colLeft, colRight, id, KKB::Max(), maxFrameHeight, maxFrameWidth, Min(), pixelCount, rowBot, and rowTop.
Referenced by ImageExtractionManager::SipperImage::Dialate().
bool ImageExtractionManager::LogicalFrameBlob::Explored () const inline
Definition at line 58 of file LogicalFrameBlob.h.
Referenced by ImageExtractionManager::SipperImage::Explore(), ImageExtractionManager::LogicalFrame::MemoryConsumedEstimated(), and ImageExtractionManager::SipperImage::SipperImage().
void ImageExtractionManager::LogicalFrameBlob::Explored (bool _explored) inline
Definition at line 60 of file LogicalFrameBlob.h.
kkuint32 ImageExtractionManager::LogicalFrameBlob::Height () inline
Definition at line 62 of file LogicalFrameBlob.h.
kkint32 ImageExtractionManager::LogicalFrameBlob::Id () inline
Definition at line 45 of file LogicalFrameBlob.h.
Referenced by AddNeighbor(), and ImageExtractionManager::SipperImage::GetRaster().
NeighborsList& ImageExtractionManager::LogicalFrameBlob::Neighbors () inline
Definition at line 64 of file LogicalFrameBlob.h.
Referenced by ImageExtractionManager::SipperImage::Explore(), and ImageExtractionManager::SipperImage::SipperImage().
kkuint32 ImageExtractionManager::LogicalFrameBlob::PixelCount () inline
Definition at line 71 of file LogicalFrameBlob.h.
Referenced by ImageExtractionManager::SipperImage::AddBlob().
kkuint32 ImageExtractionManager::LogicalFrameBlob::RowBot () inline
Definition at line 66 of file LogicalFrameBlob.h.
Referenced by ImageExtractionManager::SipperImage::AddBlob(), and ImageExtractionManager::SipperImage::GetRaster().
kkuint32 ImageExtractionManager::LogicalFrameBlob::RowTop () inline
Definition at line 67 of file LogicalFrameBlob.h.
Referenced by ImageExtractionManager::SipperImage::AddBlob(), and ImageExtractionManager::SipperImage::GetRaster().
kkuint32 ImageExtractionManager::LogicalFrameBlob::Width () inline
Definition at line 69 of file LogicalFrameBlob.h.
Member Data Documentation
kkuint32 ImageExtractionManager::LogicalFrameBlob::colLeft
Definition at line 79 of file LogicalFrameBlob.h.
Referenced by DialateBlob(), ImageExtractionManager::LogicalFrame::MemoryConsumedEstimated(), and ImageExtractionManager::SipperImage::SipperImage().
kkuint32 ImageExtractionManager::LogicalFrameBlob::colRight
Definition at line 80 of file LogicalFrameBlob.h.
Referenced by DialateBlob(), ImageExtractionManager::LogicalFrame::MemoryConsumedEstimated(), and ImageExtractionManager::SipperImage::SipperImage().
bool ImageExtractionManager::LogicalFrameBlob::explored
Definition at line 75 of file LogicalFrameBlob.h.
Referenced by ImageExtractionManager::LogicalFrame::MemoryConsumedEstimated(), and ImageExtractionManager::SipperImage::SipperImage().
kkint32 ImageExtractionManager::LogicalFrameBlob::id
Definition at line 73 of file LogicalFrameBlob.h.
Referenced by DialateBlob(), and ImageExtractionManager::LogicalFrame::MemoryConsumedEstimated().
kkuint32 ImageExtractionManager::LogicalFrameBlob::maxFrameHeight
Definition at line 85 of file LogicalFrameBlob.h.
Referenced by DialateBlob().
kkuint32 ImageExtractionManager::LogicalFrameBlob::maxFrameWidth
Definition at line 86 of file LogicalFrameBlob.h.
Referenced by DialateBlob().
kkint32 ImageExtractionManager::LogicalFrameBlob::neighborIdLastAdded
Definition at line 82 of file LogicalFrameBlob.h.
Referenced by AddNeighbor(), and ImageExtractionManager::LogicalFrame::MemoryConsumedEstimated().
NeighborsList ImageExtractionManager::LogicalFrameBlob::neighbors
Definition at line 83 of file LogicalFrameBlob.h.
Referenced by AddNeighbor(), ImageExtractionManager::LogicalFrame::MemoryConsumedEstimated(), and ~LogicalFrameBlob().
kkuint32 ImageExtractionManager::LogicalFrameBlob::pixelCount
Definition at line 88 of file LogicalFrameBlob.h.
Referenced by DialateBlob(), ImageExtractionManager::LogicalFrame::MemoryConsumedEstimated(), and ImageExtractionManager::SipperImage::SipperImage().
kkuint32 ImageExtractionManager::LogicalFrameBlob::rowBot
Definition at line 77 of file LogicalFrameBlob.h.
Referenced by DialateBlob(), ImageExtractionManager::LogicalFrame::MemoryConsumedEstimated(), and ImageExtractionManager::SipperImage::SipperImage().
kkuint32 ImageExtractionManager::LogicalFrameBlob::rowTop
Definition at line 78 of file LogicalFrameBlob.h.
Referenced by DialateBlob(), ImageExtractionManager::LogicalFrame::MemoryConsumedEstimated(), and ImageExtractionManager::SipperImage::SipperImage().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/ImageExtractionManager/LogicalFrameBlob.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/ImageExtractionManager/LogicalFrameBlob.cpp