Pices: SipperFile.Instrument Class Reference
SipperFile.Instrument Class Reference
Summary description for Instrument.
Public Member Functions
Instrument (string _shortName, string _description)
virtual InstrumentDataReport CreateInstrumentDataReport (InstrumentDataManager manager, byte deviceId)
string Description ()
virtual bool Other ()
string ShortName ()
Static Public Member Functions
static Instrument LookUpByShortName (string _shortName)
static Instrument OtherInstrument ()
static void PopulateComboBox (System.Windows.Forms.ComboBox comboBox)
Detailed Description
Summary description for Instrument.
Definition at line 10 of file Instrument.cs.
Constructor & Destructor Documentation
SipperFile.Instrument.Instrument (string _shortName, string _description) inline
Definition at line 12 of file Instrument.cs.
Member Function Documentation
virtual InstrumentDataReport SipperFile.Instrument.CreateInstrumentDataReport (InstrumentDataManager manager, byte deviceId) inline virtual
Reimplemented in SipperFile.InstrumentOther, SipperFile.InstrumentBatteryMeters, SipperFile.InstrumentInclinationMeter, SipperFile.InstrumentGPS, and SipperFile.InstrumentCTD.
Definition at line 24 of file Instrument.cs.
Referenced by SipperFile.InstrumentDataManager.InstrumentDataManager().
string SipperFile.Instrument.Description () inline
Definition at line 21 of file Instrument.cs.
Referenced by SipperFile.SipperConfigForm.Dispose(), and SipperFile.PortAssignment.PortAssignment().
static Instrument SipperFile.Instrument.LookUpByShortName (string _shortName) inline static
Definition at line 70 of file Instrument.cs.
References SipperFile.Instrument.ShortName().
Referenced by SipperFile.SipperConfigForm.Dispose(), SipperFile.Instrument.OtherInstrument(), SipperFile.PortAssignment.PortAssignment(), and SipperFile.SipperFileDialog.SipperFileDialog().
virtual bool SipperFile.Instrument.Other () inline virtual
Reimplemented in SipperFile.InstrumentOther.
Definition at line 97 of file Instrument.cs.
Referenced by SipperFile.SipperConfigForm.Dispose().
static Instrument SipperFile.Instrument.OtherInstrument () inline static
Definition at line 91 of file Instrument.cs.
References SipperFile.Instrument.LookUpByShortName().
Referenced by SipperFile.PortAssignment.PortAssignment().
static void SipperFile.Instrument.PopulateComboBox (System.Windows.Forms.ComboBox comboBox) inline static
Definition at line 100 of file Instrument.cs.
References SipperFile.Instrument.ShortName().
Referenced by SipperFile.SipperConfigForm.Dispose().
string SipperFile.Instrument.ShortName () inline
Definition at line 20 of file Instrument.cs.
Referenced by SipperFile.PortAssignment.HeaderStr(), SipperFile.Instrument.LookUpByShortName(), SipperFile.Instrument.PopulateComboBox(), SipperFile.PortAssignment.PortAssignment(), and SipperFile.PortAssignment.ShortName().
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/SipperFile/Instrument.cs