Pices: MLL::InstrumentDataBatteryMeter Class Reference
MLL::InstrumentDataBatteryMeter Class Reference
#include <InstrumentDataBatteryMeter.h>
Public Types
typedef
InstrumentDataBatteryMeter * InstrumentDataBatteryMeterPtr
Public Types inherited from MLL::InstrumentDataReport
typedef InstrumentDataReport * InstrumentDataReportPtr
typedef KKB::kkint32 kkint32
typedef KKB::kkuint32 kkuint32
Public Member Functions
InstrumentDataBatteryMeter (InstrumentDataManagerPtr _manager, const KKStr &_reportDir, bool _text, kkint32 _instrumentId)
virtual ~InstrumentDataBatteryMeter ()
virtual void ReportInstrumentData (kkuint32 curScanLine, uchar sensorData)
Public Member Functions inherited from MLL::InstrumentDataReport
InstrumentDataReport (InstrumentDataManagerPtr _manager, const KKStr &_reportDir, bool _text, kkint32 _instrumentId, bool _useReportWithLineNumbers)
virtual ~InstrumentDataReport ()
const KKStr & CurTextLine ()
const KKStr & LastTextLine ()
Protected Member Functions
void ProcessBatteryData (const KKStr &txt)
Protected Member Functions inherited from MLL::InstrumentDataReport
KKStr InstrumentName ()
Protected Attributes
VectorFloat batteryLevels
KKStr curTextLine
kkint32 curTextLineStartScanLine
KKStr lastTextLine
kkuint32 numOfBatteries
char prevEolChar
Protected Attributes inherited from MLL::InstrumentDataReport
KKStr curTextLine
Used where "text == true", Every time a character is read via 'ReportInstrumentData' will append to end of string.
kkint32 instrumentId
kkuint32 lastScanLineReported
KKStr lastTextLine
Used where "text == true", will keep an instance of last complete text line read.
InstrumentDataManagerPtr manager
ofstream report
KKStr reportFileName
KKStr reportFileNameWLN
ofstream reportWLN
bool text
bool useReportWithLineNumbers
Additional Inherited Members
Static Public Member Functions inherited from MLL::InstrumentDataReport
static InstrumentDataReportPtr CreateInstrumentDataReport (InstrumentDataManagerPtr _manager, const KKStr &_reportDir, bool _text, kkint32 _instrumentId)
A virtual Constructor for InstrumentDataReport instances.
Static Protected Attributes inherited from MLL::InstrumentDataReport
static const char * InstrumentNames []
Detailed Description
Definition at line 12 of file InstrumentDataBatteryMeter.h.
Member Typedef Documentation
typedef InstrumentDataBatteryMeter* MLL::InstrumentDataBatteryMeter::InstrumentDataBatteryMeterPtr
Definition at line 15 of file InstrumentDataBatteryMeter.h.
Constructor & Destructor Documentation
InstrumentDataBatteryMeter::InstrumentDataBatteryMeter (InstrumentDataManagerPtr _manager, const KKStr & _reportDir, bool _text, kkint32 _instrumentId)
Definition at line 23 of file InstrumentDataBatteryMeter.cpp.
References batteryLevels, and numOfBatteries.
InstrumentDataBatteryMeter::~InstrumentDataBatteryMeter () virtual
Definition at line 44 of file InstrumentDataBatteryMeter.cpp.
References curTextLine, KKB::endl(), and MLL::InstrumentDataReport::report.
Member Function Documentation
void InstrumentDataBatteryMeter::ProcessBatteryData (const KKStr & txt) protected
Definition at line 52 of file InstrumentDataBatteryMeter.cpp.
References MLL::InstrumentDataManager::BatteryData(), batteryLevels, curTextLineStartScanLine, MLL::InstrumentDataReport::manager, numOfBatteries, KKB::KKStr::Split(), and ToFloat().
Referenced by ReportInstrumentData().
void InstrumentDataBatteryMeter::ReportInstrumentData (kkuint32 curScanLine, uchar sensorData) virtual
Reimplemented from MLL::InstrumentDataReport.
Definition at line 77 of file InstrumentDataBatteryMeter.cpp.
References KKB::KKStr::Append(), curTextLine, curTextLineStartScanLine, KKB::KKStr::Empty(), KKB::endl(), lastTextLine, prevEolChar, ProcessBatteryData(), and MLL::InstrumentDataReport::report.
Member Data Documentation
VectorFloat MLL::InstrumentDataBatteryMeter::batteryLevels protected
Definition at line 34 of file InstrumentDataBatteryMeter.h.
Referenced by InstrumentDataBatteryMeter(), and ProcessBatteryData().
KKStr MLL::InstrumentDataBatteryMeter::curTextLine protected
Definition at line 35 of file InstrumentDataBatteryMeter.h.
Referenced by ReportInstrumentData(), and ~InstrumentDataBatteryMeter().
kkint32 MLL::InstrumentDataBatteryMeter::curTextLineStartScanLine protected
Definition at line 36 of file InstrumentDataBatteryMeter.h.
Referenced by ProcessBatteryData(), and ReportInstrumentData().
KKStr MLL::InstrumentDataBatteryMeter::lastTextLine protected
Definition at line 37 of file InstrumentDataBatteryMeter.h.
Referenced by ReportInstrumentData().
kkuint32 MLL::InstrumentDataBatteryMeter::numOfBatteries protected
Definition at line 38 of file InstrumentDataBatteryMeter.h.
Referenced by InstrumentDataBatteryMeter(), and ProcessBatteryData().
char MLL::InstrumentDataBatteryMeter::prevEolChar protected
Definition at line 39 of file InstrumentDataBatteryMeter.h.
Referenced by ReportInstrumentData().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/InstrumentDataBatteryMeter.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/InstrumentDataBatteryMeter.cpp