Pices: MLL::SipperStation Class Reference
MLL::SipperStation Class Reference
#include <SipperStation.h>
Public Types
typedef SipperStation * SipperStationPtr
Public Member Functions
SipperStation ()
~SipperStation ()
const KKStr & CruiseName () const
void CruiseName (const KKStr &_cruiseName)
const KKB::DateTime & DateTimeStart () const
void DateTimeStart (const KKB::DateTime &_dateTimeStart)
const KKStr & Description () const
void Description (const KKStr &_description)
double Latitude () const
void Latitude (double _latitude)
double Longitude () const
void Longitude (double _longitude)
const KKStr & StationName () const
void StationName (const KKStr &_stationName)
Detailed Description
Definition at line 10 of file SipperStation.h.
Member Typedef Documentation
typedef SipperStation* MLL::SipperStation::SipperStationPtr
Definition at line 13 of file SipperStation.h.
Constructor & Destructor Documentation
SipperStation::SipperStation ()
Definition at line 22 of file SipperStation.cpp.
SipperStation::~SipperStation ()
Definition at line 35 of file SipperStation.cpp.
Member Function Documentation
const KKStr& MLL::SipperStation::CruiseName () const inline
Definition at line 18 of file SipperStation.h.
Referenced by PicesInterface::PicesSipperStation::PicesSipperStation(), MLL::DataBase::SipperFilesDelete(), MLL::DataBase::SipperStationInsert(), MLL::DataBase::SipperStationUpdate(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void MLL::SipperStation::CruiseName (const KKStr & _cruiseName) inline
Definition at line 25 of file SipperStation.h.
const KKB::DateTime& MLL::SipperStation::DateTimeStart () const inline
Definition at line 23 of file SipperStation.h.
Referenced by PicesInterface::PicesSipperStation::!PicesSipperStation(), MLL::DataBase::SipperFilesDelete(), MLL::DataBase::SipperStationInsert(), MLL::DataBase::SipperStationUpdate(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void MLL::SipperStation::DateTimeStart (const KKB::DateTime & _dateTimeStart) inline
Definition at line 30 of file SipperStation.h.
const KKStr& MLL::SipperStation::Description () const inline
Definition at line 20 of file SipperStation.h.
Referenced by MLL::DataBase::SipperFilesDelete(), MLL::DataBase::SipperStationInsert(), MLL::DataBase::SipperStationUpdate(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void MLL::SipperStation::Description (const KKStr & _description) inline
Definition at line 27 of file SipperStation.h.
double MLL::SipperStation::Latitude () const inline
Definition at line 21 of file SipperStation.h.
Referenced by PicesInterface::PicesSipperStation::!PicesSipperStation(), MLL::DataBase::SipperFilesDelete(), MLL::DataBase::SipperStationInsert(), MLL::DataBase::SipperStationUpdate(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void MLL::SipperStation::Latitude (double _latitude) inline
Definition at line 28 of file SipperStation.h.
double MLL::SipperStation::Longitude () const inline
Definition at line 22 of file SipperStation.h.
Referenced by PicesInterface::PicesSipperStation::!PicesSipperStation(), MLL::DataBase::SipperFilesDelete(), MLL::DataBase::SipperStationInsert(), MLL::DataBase::SipperStationUpdate(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void MLL::SipperStation::Longitude (double _longitude) inline
Definition at line 29 of file SipperStation.h.
const KKStr& MLL::SipperStation::StationName () const inline
Definition at line 19 of file SipperStation.h.
Referenced by MLL::DataBase::SipperFilesDelete(), MLL::DataBase::SipperStationInsert(), MLL::DataBase::SipperStationUpdate(), and ImageExtractionManager::ExtractionManager::TerminateProcessing().
void MLL::SipperStation::StationName (const KKStr & _stationName) inline
Definition at line 26 of file SipperStation.h.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/SipperStation.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/SipperStation.cpp