Pices: SipperFileViewer.SelectAInstrumentDataField Class Reference
SipperFileViewer.SelectAInstrumentDataField Class Reference
Public Member Functions
SelectAInstrumentDataField (string _selectedDataField, bool _includeNonDataFields)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
string SelectedDataField [get, set]
Detailed Description
Definition at line 12 of file SelectAInstrumentDataField.cs.
Constructor & Destructor Documentation
SipperFileViewer.SelectAInstrumentDataField.SelectAInstrumentDataField (string _selectedDataField, bool _includeNonDataFields) inline
Definition at line 19 of file SelectAInstrumentDataField.cs.
References SipperFile.InstrumentData.FieldName(), SipperFile.InstrumentData.NumDataFields(), SipperFile.InstrumentData.NumOfFields(), and SipperFileViewer.SelectAInstrumentDataField.SelectedDataField.
Member Function Documentation
override void SipperFileViewer.SelectAInstrumentDataField.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file SelectAInstrumentDataField.Designer.cs.
Property Documentation
string SipperFileViewer.SelectAInstrumentDataField.SelectedDataField get set
Definition at line 62 of file SelectAInstrumentDataField.cs.
Referenced by SipperFileViewer.SipperFileViewer.CancelLoadingModels(), SipperFileViewer.SelectAInstrumentDataField.SelectAInstrumentDataField(), and SipperFileViewer.SipperFileViewer.WndProc().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/Apps/SipperFileViewer/SelectAInstrumentDataField.cs
C:/Users/Kurt/GitHub/Pices/Apps/SipperFileViewer/SelectAInstrumentDataField.Designer.cs