Pices: FeatureSelectionApp::Results Class Reference
FeatureSelectionApp::Results Class Reference
#include <Results.h>
Public Types
typedef Results * ResultsPtr
Public Member Functions
Results (RunLog &_log)
Results (FinalResultType _resultType, TrainingConfiguration2Ptr _config, CrossValidationPtr _crossValidation, FeatureVectorListPtr _trainData, const KKStr &_hostName, BinaryJobPtr _job, RunLog &_log)
virtual ~Results ()
float Accuracy () const
VectorFloat AccuracyByClass () const
float AccuracyNorm () const
const KKStr & ConfigFileName () const
ConfusionMatrix2Ptr ConfusionMatrix () const
KKStr Description () const
const KKStr & HostName () const
int JobId () const
SVM_MachineType MachineType () const
KKStr MachineTypeStr () const
MLClassListPtr MLClasses () const
Creates a List of Classes from associated Confusion Matrix.
double NumFeatures () const
float NumFeaturesWeighted () const
double NumSupportVectors () const
double NumSVs () const
Results & operator+= (const Results &right)
Results & operator/= (float divisor)
Results & operator/= (int divisor)
FinalResultType ResultType () const
KKStr ResultTypeStr () const
SVM_SelectionMethod SelectionMethod () const
KKStr SelectionMethodStr () const
KKStr SvmParameters () const
double TestTime () const
double TotalNumSVs () const
double TrainingTime () const
virtual void Write (ostream &o)
Static Public Member Functions
static ResultsPtr ConstructFromStream (istream &i, RunLog &log)
Protected Member Functions
virtual void Read (istream &i)
Detailed Description
Definition at line 24 of file Results.h.
Member Typedef Documentation
typedef Results* FeatureSelectionApp::Results::ResultsPtr
Definition at line 27 of file Results.h.
Constructor & Destructor Documentation
Results::Results (RunLog & _log)
Definition at line 49 of file Results.cpp.
References Null.
Referenced by ConstructFromStream().
Results::Results (FinalResultType _resultType, TrainingConfiguration2Ptr _config, CrossValidationPtr _crossValidation, FeatureVectorListPtr _trainData, const KKStr & _hostName, BinaryJobPtr _job, RunLog & _log)
Definition at line 69 of file Results.cpp.
References KKMLL::TrainingConfiguration2::AvgNumOfFeatures(), KKMLL::CrossValidation::ConfussionMatrix(), KKB::Configuration::FileName(), FeatureSelectionApp::BinaryJob::JobId(), KKMLL::TrainingConfiguration2::MachineType(), KKMLL::CrossValidation::NumSVs(), KKMLL::TrainingConfiguration2::SelectionMethod(), KKMLL::TrainingConfiguration2::SVMparamREF(), KKMLL::CrossValidation::TestTimeTotal(), KKMLL::SVMparam::ToString(), KKMLL::CrossValidation::TotalNumSVs(), and KKMLL::CrossValidation::TrainTimeTotal().
Results::~Results () virtual
Definition at line 112 of file Results.cpp.
Member Function Documentation
float Results::Accuracy () const
Definition at line 140 of file Results.cpp.
References KKMLL::ConfusionMatrix2::Accuracy().
Referenced by FeatureSelectionApp::FinalResults::RandomSplitAccuracies().
VectorFloat Results::AccuracyByClass () const
Definition at line 151 of file Results.cpp.
References KKMLL::ConfusionMatrix2::AccuracyByClass(), and VectorFloat.
Referenced by FeatureSelectionApp::FinalResults::RandomSplitAccuracyByClass(), and FeatureSelectionApp::FinalResults::ValidationAccuracyByClass().
float Results::AccuracyNorm () const
Definition at line 161 of file Results.cpp.
References KKMLL::ConfusionMatrix2::AccuracyNorm().
const KKStr& FeatureSelectionApp::Results::ConfigFileName () const inline
Definition at line 51 of file Results.h.
Referenced by FeatureSelectionApp::FinalResults::FinalResults(), and FeatureSelectionApp::FinalResults::LinkName().
ConfusionMatrix2Ptr FeatureSelectionApp::Results::ConfusionMatrix () const inline
Definition at line 52 of file Results.h.
Referenced by FeatureSelectionApp::FinalResults::ConfusionMatrix(), operator+=(), FeatureSelectionApp::FinalResults::ToHTMLStr(), and FeatureSelectionApp::FinalResults::ValidationConfusionMatrix().
ResultsPtr Results::ConstructFromStream (istream & i, RunLog & log) static
Definition at line 279 of file Results.cpp.
References Read(), and Results().
KKStr Results::Description () const
Definition at line 172 of file Results.cpp.
References MachineTypeStr(), ResultTypeStr(), and SelectionMethodStr().
Referenced by FeatureSelectionApp::FinalResults::Description(), and FeatureSelectionApp::FinalResults::ToHTMLStr().
const KKStr& FeatureSelectionApp::Results::HostName () const inline
Definition at line 54 of file Results.h.
int FeatureSelectionApp::Results::JobId () const inline
Definition at line 56 of file Results.h.
SVM_MachineType FeatureSelectionApp::Results::MachineType () const inline
Definition at line 57 of file Results.h.
KKStr Results::MachineTypeStr () const
Definition at line 119 of file Results.cpp.
References KKMLL::MachineTypeToStr().
Referenced by Description(), FeatureSelectionApp::FinalResults::ToHTMLStr(), and Write().
MLClassListPtr Results::MLClasses () const
Creates a List of Classes from associated Confusion Matrix.
caller will be responsible for deleting this list.
Definition at line 395 of file Results.cpp.
References KKMLL::ConfusionMatrix2::MLClasses().
Referenced by FeatureSelectionApp::FinalResults::MLClasses().
double FeatureSelectionApp::Results::NumFeatures () const inline
Definition at line 59 of file Results.h.
Referenced by FeatureSelectionApp::FinalResults::ToHTMLStr().
float FeatureSelectionApp::Results::NumFeaturesWeighted () const inline
Definition at line 60 of file Results.h.
Referenced by FeatureSelectionApp::FinalResults::ToHTMLStr().
double FeatureSelectionApp::Results::NumSupportVectors () const inline
Definition at line 61 of file Results.h.
double FeatureSelectionApp::Results::NumSVs () const inline
Definition at line 62 of file Results.h.
Referenced by FeatureSelectionApp::FinalResults::ToHTMLStr().
Results & Results::operator+= (const Results & right)
Definition at line 292 of file Results.cpp.
References KKMLL::ConfusionMatrix2::AddIn(), ConfusionMatrix(), KKB::KKStr::Empty(), and KKB::KKStr::EqualIgnoreCase().
Results & Results::operator/= (float divisor)
Definition at line 349 of file Results.cpp.
References KKMLL::ConfusionMatrix2::FactorCounts().
Results & Results::operator/= (int divisor)
Definition at line 370 of file Results.cpp.
References KKMLL::ConfusionMatrix2::FactorCounts().
void Results::Read (istream & i) protected virtual
Definition at line 206 of file Results.cpp.
References KKB::KKStr::EqualIgnoreCase(), KKB::KKStr::ExtractToken2(), KKB::KKStr::ExtractTokenDouble(), KKB::KKStr::ExtractTokenInt(), FeatureSelectionApp::FinalResultTypeFromStr(), KKMLL::MachineTypeFromStr(), and KKMLL::SelectionMethodFromStr().
Referenced by ConstructFromStream().
FinalResultType FeatureSelectionApp::Results::ResultType () const inline
Definition at line 63 of file Results.h.
KKStr Results::ResultTypeStr () const
Definition at line 132 of file Results.cpp.
References FeatureSelectionApp::FinalResultTypeToStr().
Referenced by Description().
SVM_SelectionMethod FeatureSelectionApp::Results::SelectionMethod () const inline
Definition at line 65 of file Results.h.
KKStr Results::SelectionMethodStr () const
Definition at line 126 of file Results.cpp.
References KKMLL::SelectionMethodToStr().
Referenced by Description(), FeatureSelectionApp::FinalResults::LinkName(), FeatureSelectionApp::FinalResults::ToHTMLStr(), and Write().
KKStr FeatureSelectionApp::Results::SvmParameters () const inline
Definition at line 67 of file Results.h.
double FeatureSelectionApp::Results::TestTime () const inline
Definition at line 68 of file Results.h.
Referenced by FeatureSelectionApp::FinalResults::ToHTMLStr().
double FeatureSelectionApp::Results::TotalNumSVs () const inline
Definition at line 69 of file Results.h.
Referenced by FeatureSelectionApp::FinalResults::ToHTMLStr().
double FeatureSelectionApp::Results::TrainingTime () const inline
Definition at line 70 of file Results.h.
Referenced by FeatureSelectionApp::FinalResults::ToHTMLStr().
void Results::Write (ostream & o) virtual
Reimplemented in FeatureSelectionApp::ValidationResults, and FeatureSelectionApp::RandomSplitResults.
Definition at line 182 of file Results.cpp.
References KKB::endl(), FeatureSelectionApp::FinalResultTypeToStr(), MachineTypeStr(), SelectionMethodStr(), and KKMLL::ConfusionMatrix2::WriteXML().
Referenced by FeatureSelectionApp::RandomSplitResults::Write(), and FeatureSelectionApp::ValidationResults::Write().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/Apps/FeatureSelection/Results.h
C:/Users/kurtk_000/GitHub/Pices/Apps/FeatureSelection/Results.cpp