Pices: FeatureSelectionApp::BinaryJobList Class Reference
FeatureSelectionApp::BinaryJobList Class Reference
#include <BinaryJobList.h>
Public Types
typedef BinaryJobList * BinaryJobListPtr
enum ErrorCodes { ErrorCodes::NoError, ErrorCodes::DuplicateJobId, ErrorCodes::DuplicateParameters }
typedef KKB::uint uint
Public Types inherited from KKB::KKQueue< BinaryJob >
typedef std::vector< BinaryJob * >
::const_iterator const_iterator
typedef std::vector< BinaryJob * >
::iterator iterator
Public Member Functions
BinaryJobList (ProcessorPtr _processor)
BinaryJobList (ProcessorPtr _processor, KKStr _fileName)
virtual ~BinaryJobList ()
bool AreAllJobsDone ()
void ComputeMinAndMaxParmValues (double &cMin, double &cMax, double &gammaMin, double &gammaMax, float &aMin, float &aMax)
BinaryJobListPtr CreateTestJobsForHighetsGradePerFeatureCount ()
BinaryJobListPtr ExtractByMinimumProcessintTime (double maxProcessingTime)
BinaryJobListPtr ExtractFastestJobs (double minTime, float topPercentage)
BinaryJobListPtr ExtractHighestGrade (int numToExtract)
BinaryJobListPtr ExtractHighestGrade (float topPercentage, int minNumOfJobs)
BinaryJobListPtr ExtractHighestGrade (float percentageFromTop)
Get all jobs who's grade is within 'percentageFromTop' of the highest grade.
BinaryJobListPtr ExtractHighestTestGrade (float acceptableDelta, bool featureCountPrefSmall)
BinaryJobListPtr ExtractJobsForAGivenFeatureCount (int featureCount)
BinaryJobListPtr ExtractJobsWithSmallestDeltaAccProbForEachSvmParameterSet ()
BinaryJobListPtr ExtractLowDeltaProbAccuarcy (float topPercentage)
BinaryJobListPtr ExtractTestJobs ()
BinaryJobPtr FastestJob ()
FileDescPtr FileDesc ()
void FindNeighboringParameterValues (BinaryJobPtr targetJob, double &cMin, double &cMax, float cMaxGrowthFactor, double &gammaMin, double &gammaMax, float gammaMaxGrowthFactor, float &aMin, float &aMax, float aMaxGrowthFactor)
void GenrateSvmResponseSheet (ostream &r)
map< double, int > * GetListOfUniqueCValues ()
map< double, int > * GetListOfUniqueGammaValues ()
BinaryJobPtr HighestGradedJob ()
BinaryJobPtr HighestGradedTestJob ()
bool JobsStillRunning ()
void Load ()
BinaryJobPtr LocateOpenJob ()
RunLog & Log ()
BinaryJobPtr LookUpByFeatureNums (const FeatureNumList &_features)
BinaryJobPtr LookUpByJobId (int jobId)
BinaryJobListPtr LookUpByParameters (double minC, double maxC, double minGamma, double maxGamma)
BinaryJobPtr LookUpByParameters (const FeatureNumList &features, kkint32 numOfRounds, double cParm, double gamma, float aParm, bool validationOnly)
BinaryJobPtr LowestDeltaAccuracyProbJob ()
Will locate the job in the list that has the smallest 'DeltaProbAccuracy'.
BinaryJobPtr LowestDeltaAccuracyProbTestJob ()
void PushOnBack (BinaryJobPtr j, ErrorCodes &result)
void ReFresh ()
void ReportResults (ostream &r)
void ReportResultsHTML (ostream &r)
void Save ()
FeatureNumList SelectFeaturesByMostFeaturesWithHighestGrade () const
BinaryJobPtr SelectOneDoneJobAtRandomFromTop10Percent ()
int SmallestNumberOfFeaturesExpanded () const
void SortByAccuracy ()
void SortByAccuracyNorm ()
void SortByGrade ()
void SortByProcessingTime ()
void SortBySvmParameters ()
void SortByTestAccuracy ()
void SortByTestAccuracyNorm ()
void SortByTestGrade (bool featureCountPrefSmall)
void SortDeltaProbAccuarcy ()
void SortDeltaTestProbAccuarcy ()
double TotalProcessingTime () const
Public Member Functions inherited from KKB::KKQueue< BinaryJob >
KKQueue (bool _owner=true)
KKQueue (const KKQueue &q, bool _owner)
Constructor, similar to the Copy Constructor except that you can control whether it duplicates the contents.
virtual ~KKQueue ()
void Add (EntryPtr _entry)
same as PushOnBack
void AddFirst (EntryPtr _entry)
same as PushOnFront
virtual void AddQueue (const KKQueue &q)
EntryPtr BackOfQueue () const
Returns pointer of last element in the container without removing it.
void Compress ()
No longer does anything.
void DeleteContents ()
Empties the container, if 'owner' is set to true will call the destructor on each element.
void DeleteEntry (EntryPtr _entry)
Removes from KKQueue the entry who's pointer = '_entry'.
void DeleteEntry (kkuint32 _idx)
Removes from KKQueue the entry who's index = '_idx'.
KKQueue * DuplicateListAndContents () const
Creates a new container including duplicating the contents, which also makes the new instance the owner of those contents.
kkuint32 FindTheKthElement (kkuint32 k, Functor pred)
EntryPtr FrontOfQueue () const
Returns a pointer to the element that is at from of the queue with out removing it from the queue.
EntryPtr GetFirst () const
EntryPtr GetLast () const
EntryPtr IdxToPtr (kkuint32 idx) const
Returns back a pointer to the element who's index is 'idx'.
kkint32 LocateEntry (EntryConstPtr _entry) const
Returns the index of the element who's address is '_entry'.
EntryPtr LookAtBack () const
Returns pointer to element at Back of container with out removing it from the container.
EntryPtr LookAtFront () const
Returns pointer to element at Front of container with out removing it from the container.
bool operator!= (const KKQueue< BinaryJob > &rightSide) const
returns False if NOT every entry in both containers point to the same elements
KKQueue & operator= (const KKQueue &q)
Assignment Operator.
bool operator== (const KKQueue< BinaryJob > &rightSide) const
Returns True if every entry in both containers point to the same elements.
BinaryJob & operator[] (kkuint32 i) const
Returns a reference to element indexed by 'i'.
bool Owner () const
void Owner (bool _owner)
You can specify who owns the contents of the container.
virtual EntryPtr PopFromBack ()
Removes the last element in the container and returns its pointer.
virtual EntryPtr PopFromFront ()
Removes the first element in the container and returns its pointer.
kkint32 PtrToIdx (EntryConstPtr _entry) const
returns the index of the 'entry' that has the same pointer as '_entry', if none found returns -1
virtual void PushOnBack (EntryPtr _entry)
Adds '_entry' to the End of the container.
virtual void PushOnFront (EntryPtr _entry)
Adds '_entry' to the Front of the container.
kkint32 QueueSize () const
Same as calling vector<>::size().
void RandomizeOrder ()
void RandomizeOrder (kkint64 seed)
void RandomizeOrder (RandomNumGenerator &randomVariable)
EntryPtr RemoveFirst ()
same as PopFromFront
EntryPtr RemoveLast ()
same as PopFromBack
void SetIdxToPtr (kkuint32 _idx, BinaryJob *_ptr)
void SwapIndexes (size_t idx1, size_t idx2)
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Protected Member Functions inherited from KKB::KKQueue< BinaryJob >
KKQueue (const KKQueue &q)
Copy Constructor, will create a new instance.
Detailed Description
Definition at line 21 of file BinaryJobList.h.
Member Typedef Documentation
typedef BinaryJobList* FeatureSelectionApp::BinaryJobList::BinaryJobListPtr
Definition at line 26 of file BinaryJobList.h.
typedef KKB::uint FeatureSelectionApp::BinaryJobList::uint
Definition at line 24 of file BinaryJobList.h.
Member Enumeration Documentation
enum FeatureSelectionApp::BinaryJobList::ErrorCodes strong
Enumerator
NoError
DuplicateJobId
DuplicateParameters
Definition at line 28 of file BinaryJobList.h.
Constructor & Destructor Documentation
BinaryJobList::BinaryJobList (ProcessorPtr _processor)
Definition at line 44 of file BinaryJobList.cpp.
Referenced by CreateTestJobsForHighetsGradePerFeatureCount(), ExtractByMinimumProcessintTime(), ExtractHighestGrade(), ExtractHighestTestGrade(), ExtractJobsForAGivenFeatureCount(), ExtractJobsWithSmallestDeltaAccProbForEachSvmParameterSet(), ExtractLowDeltaProbAccuarcy(), ExtractTestJobs(), and LookUpByParameters().
BinaryJobList::BinaryJobList (ProcessorPtr _processor, KKStr _fileName)
Definition at line 62 of file BinaryJobList.cpp.
References Load().
BinaryJobList::~BinaryJobList () virtual
Definition at line 81 of file BinaryJobList.cpp.
Member Function Documentation
bool BinaryJobList::AreAllJobsDone ()
Definition at line 438 of file BinaryJobList.cpp.
References KKB::KKQueue< BinaryJob >::IdxToPtr(), KKB::KKQueue< BinaryJob >::QueueSize(), and FeatureSelectionApp::BinaryJob::Status().
Referenced by FeatureSelectionApp::Processor::AreAllJobsDone().
void BinaryJobList::ComputeMinAndMaxParmValues (double & cMin, double & cMax, double & gammaMin, double & gammaMax, float & aMin, float & aMax)
Definition at line 1469 of file BinaryJobList.cpp.
References FeatureSelectionApp::BinaryJob::AParm(), FeatureSelectionApp::BinaryJob::CParm(), FeatureSelectionApp::BinaryJob::GammaParm(), KKB::Max(), and KKB::Min().
BinaryJobListPtr BinaryJobList::CreateTestJobsForHighetsGradePerFeatureCount ()
Definition at line 1709 of file BinaryJobList.cpp.
References FeatureSelectionApp::BinaryJob::AParm(), BinaryJobList(), FeatureSelectionApp::BinaryJob::CParm(), FeatureSelectionApp::BinaryJob::CreateTestJob(), ExtractJobsForAGivenFeatureCount(), FeatureSelectionApp::BinaryJob::Features(), KKB::KKQueue< Entry >::FrontOfQueue(), FeatureSelectionApp::BinaryJob::GammaParm(), FeatureSelectionApp::BinaryJob::Grade(), FeatureSelectionApp::Processor::InitialFeatures(), LookUpByParameters(), KKMLL::FeatureNumList::NumOfFeatures(), FeatureSelectionApp::BinaryJob::NumOfRounds(), KKB::KKQueue< Entry >::Owner(), PushOnBack(), KKB::KKQueue< Entry >::QueueSize(), and SortByGrade().
BinaryJobListPtr BinaryJobList::ExtractByMinimumProcessintTime (double maxProcessingTime)
Definition at line 1291 of file BinaryJobList.cpp.
References BinaryJobList(), KKB::KKQueue< Entry >::Owner(), FeatureSelectionApp::BinaryJob::ProcessingTime(), PushOnBack(), and KKB::KKQueue< BinaryJob >::QueueSize().
Referenced by ExtractFastestJobs().
BinaryJobListPtr BinaryJobList::ExtractFastestJobs (double minTime, float topPercentage)
Definition at line 1380 of file BinaryJobList.cpp.
References KKB::KKQueue< BinaryJob >::BackOfQueue(), ExtractByMinimumProcessintTime(), KKB::KKQueue< BinaryJob >::FrontOfQueue(), FeatureSelectionApp::BinaryJob::ProcessingTime(), and SortByProcessingTime().
BinaryJobListPtr BinaryJobList::ExtractHighestGrade (int numToExtract)
Definition at line 1173 of file BinaryJobList.cpp.
References BinaryJobList(), KKB::endl(), KKB::RunLog::Level(), KKB::KKQueue< Entry >::Owner(), PushOnBack(), KKB::KKQueue< BinaryJob >::QueueSize(), KKB::KKQueue< Entry >::QueueSize(), and SortByGrade().
BinaryJobListPtr BinaryJobList::ExtractHighestGrade (float topPercentage, int minNumOfJobs)
Definition at line 1234 of file BinaryJobList.cpp.
References BinaryJobList(), KKB::KKQueue< BinaryJob >::FrontOfQueue(), FeatureSelectionApp::BinaryJob::Grade(), KKB::KKQueue< Entry >::Owner(), PushOnBack(), KKB::KKQueue< BinaryJob >::QueueSize(), KKB::KKQueue< Entry >::QueueSize(), and SortByGrade().
BinaryJobListPtr BinaryJobList::ExtractHighestGrade (float percentageFromTop)
Get all jobs who's grade is within 'percentageFromTop' of the highest grade.
Definition at line 1205 of file BinaryJobList.cpp.
References BinaryJobList(), KKB::KKQueue< BinaryJob >::FrontOfQueue(), FeatureSelectionApp::BinaryJob::Grade(), KKB::KKQueue< Entry >::Owner(), PushOnBack(), KKB::KKQueue< BinaryJob >::QueueSize(), and SortByGrade().
BinaryJobListPtr BinaryJobList::ExtractHighestTestGrade (float acceptableDelta, bool featureCountPrefSmall)
Definition at line 1313 of file BinaryJobList.cpp.
References BinaryJobList(), KKB::KKQueue< BinaryJob >::FrontOfQueue(), KKB::KKQueue< Entry >::Owner(), PushOnBack(), KKB::KKQueue< BinaryJob >::QueueSize(), SortByTestGrade(), and FeatureSelectionApp::BinaryJob::TestGrade().
Referenced by FeatureSelectionApp::Processor::GetBestParametersFromTestResults().
BinaryJobListPtr BinaryJobList::ExtractJobsForAGivenFeatureCount (int featureCount)
Definition at line 1688 of file BinaryJobList.cpp.
References BinaryJobList(), FeatureSelectionApp::BinaryJob::Features(), KKMLL::FeatureNumList::NumOfFeatures(), KKB::KKQueue< Entry >::Owner(), and PushOnBack().
Referenced by CreateTestJobsForHighetsGradePerFeatureCount().
BinaryJobListPtr BinaryJobList::ExtractJobsWithSmallestDeltaAccProbForEachSvmParameterSet ()
Definition at line 1401 of file BinaryJobList.cpp.
References BinaryJobList(), FeatureSelectionApp::BinaryJob::CParm(), FeatureSelectionApp::BinaryJob::DeltaProbAccuracy(), FeatureSelectionApp::BinaryJob::GammaParm(), KKB::KKQueue< Entry >::Owner(), PushOnBack(), KKB::KKQueue< BinaryJob >::QueueSize(), and SortBySvmParameters().
BinaryJobListPtr BinaryJobList::ExtractLowDeltaProbAccuarcy (float topPercentage)
Definition at line 1269 of file BinaryJobList.cpp.
References BinaryJobList(), FeatureSelectionApp::BinaryJob::DeltaProbAccuracy(), KKB::KKQueue< Entry >::Owner(), PushOnBack(), and KKB::KKQueue< BinaryJob >::QueueSize().
BinaryJobListPtr BinaryJobList::ExtractTestJobs ()
Definition at line 1449 of file BinaryJobList.cpp.
References BinaryJobList(), KKB::KKQueue< Entry >::Owner(), PushOnBack(), and FeatureSelectionApp::BinaryJob::TestGrade().
Referenced by FeatureSelectionApp::Processor::GetBestParametersFromTestResults(), and FeatureSelectionApp::Processor::GetFeaturesFromTestResults().
BinaryJobPtr BinaryJobList::FastestJob ()
Definition at line 399 of file BinaryJobList.cpp.
References FeatureSelectionApp::BinaryJob::ProcessingTime().
FileDescPtr BinaryJobList::FileDesc ()
Definition at line 88 of file BinaryJobList.cpp.
References FeatureSelectionApp::Processor::FileDesc().
Referenced by FeatureSelectionApp::FeatureImpact::FeatureImpact().
void BinaryJobList::FindNeighboringParameterValues (BinaryJobPtr targetJob, double & cMin, double & cMax, float cMaxGrowthFactor, double & gammaMin, double & gammaMax, float gammaMaxGrowthFactor, float & aMin, float & aMax, float aMaxGrowthFactor)
Definition at line 1775 of file BinaryJobList.cpp.
References FeatureSelectionApp::BinaryJob::AParm(), FeatureSelectionApp::BinaryJob::CParm(), FeatureSelectionApp::BinaryJob::GammaParm(), KKB::Max(), and KKB::Min().
void BinaryJobList::GenrateSvmResponseSheet (ostream & r)
Definition at line 1593 of file BinaryJobList.cpp.
References FeatureSelectionApp::BinaryJob::AccuracyNorm(), FeatureSelectionApp::BinaryJob::CParm(), KKB::endl(), FeatureSelectionApp::BinaryJob::GammaParm(), GetListOfUniqueCValues(), GetListOfUniqueGammaValues(), and FeatureSelectionApp::BinaryJob::ProcessingTime().
map< double, int > * BinaryJobList::GetListOfUniqueCValues ()
Definition at line 1539 of file BinaryJobList.cpp.
References FeatureSelectionApp::BinaryJob::CParm().
Referenced by GenrateSvmResponseSheet().
map< double, int > * BinaryJobList::GetListOfUniqueGammaValues ()
Definition at line 1566 of file BinaryJobList.cpp.
References FeatureSelectionApp::BinaryJob::GammaParm().
Referenced by GenrateSvmResponseSheet().
BinaryJobPtr BinaryJobList::HighestGradedJob ()
Definition at line 339 of file BinaryJobList.cpp.
References FeatureSelectionApp::BinaryJob::Grade(), FeatureSelectionApp::BinaryJob::ProcessingTime(), and KKB::KKQueue< BinaryJob >::QueueSize().
BinaryJobPtr BinaryJobList::HighestGradedTestJob ()
Definition at line 368 of file BinaryJobList.cpp.
References FeatureSelectionApp::BinaryJob::ProcessingTime(), KKB::KKQueue< BinaryJob >::QueueSize(), and FeatureSelectionApp::BinaryJob::TestGrade().
bool BinaryJobList::JobsStillRunning ()
Definition at line 1158 of file BinaryJobList.cpp.
References FeatureSelectionApp::BinaryJob::Status().
Referenced by FeatureSelectionApp::Processor::Run().
void BinaryJobList::Load ()
Definition at line 95 of file BinaryJobList.cpp.
References KKB::endl(), KKB::RunLog::Level(), KKB::osFOPEN(), PushOnBack(), and KKB::KKStr::Str().
Referenced by BinaryJobList().
BinaryJobPtr BinaryJobList::LocateOpenJob ()
Definition at line 229 of file BinaryJobList.cpp.
References KKB::KKQueue< BinaryJob >::IdxToPtr(), KKB::KKQueue< BinaryJob >::QueueSize(), and FeatureSelectionApp::BinaryJob::Status().
RunLog& FeatureSelectionApp::BinaryJobList::Log () inline
Definition at line 124 of file BinaryJobList.h.
BinaryJobPtr BinaryJobList::LookUpByFeatureNums (const FeatureNumList & _features)
Definition at line 173 of file BinaryJobList.cpp.
References FeatureSelectionApp::BinaryJob::Features(), KKB::KKQueue< BinaryJob >::IdxToPtr(), and KKB::KKQueue< BinaryJob >::QueueSize().
Referenced by FeatureSelectionApp::BinaryJob::CheckTwoListsForExitingJob().
BinaryJobPtr BinaryJobList::LookUpByJobId (int jobId)
Definition at line 217 of file BinaryJobList.cpp.
Referenced by FeatureSelectionApp::FeatureImpact::FeatureImpact(), and ReFresh().
BinaryJobListPtr BinaryJobList::LookUpByParameters (double minC, double maxC, double minGamma, double maxGamma)
Definition at line 1347 of file BinaryJobList.cpp.
References BinaryJobList(), FeatureSelectionApp::BinaryJob::CParm(), FeatureSelectionApp::BinaryJob::GammaParm(), KKB::KKQueue< Entry >::Owner(), PushOnBack(), and KKB::KKQueue< BinaryJob >::QueueSize().
Referenced by CreateTestJobsForHighetsGradePerFeatureCount(), and FeatureSelectionApp::Processor::FlagJobsForTesting().
BinaryJobPtr BinaryJobList::LookUpByParameters (const FeatureNumList & features, kkint32 numOfRounds, double cParm, double gamma, float aParm, bool validationOnly)
Definition at line 191 of file BinaryJobList.cpp.
References FeatureSelectionApp::BinaryJob::AParm(), FeatureSelectionApp::BinaryJob::CParm(), FeatureSelectionApp::BinaryJob::Features(), FeatureSelectionApp::BinaryJob::GammaParm(), FeatureSelectionApp::BinaryJob::NumOfRounds(), and FeatureSelectionApp::BinaryJob::ValidateOnly().
BinaryJobPtr BinaryJobList::LowestDeltaAccuracyProbJob ()
Will locate the job in the list that has the smallest 'DeltaProbAccuracy'.
If two jobs If two jobs have the same 'DeltaProbAccuracy' then the one that has the highest'Grade' will be selected. After the 1st 2 criteria we will select the job with the smallest
'AParam'.
1) Smallest 'DeltaProbAccuracy';
2) Largest  'Grade'
3) Smallest 'AParm'
Definition at line 290 of file BinaryJobList.cpp.
References FeatureSelectionApp::BinaryJob::AParm(), FeatureSelectionApp::BinaryJob::DeltaProbAccuracy(), FeatureSelectionApp::BinaryJob::Grade(), and KKB::KKQueue< BinaryJob >::QueueSize().
BinaryJobPtr BinaryJobList::LowestDeltaAccuracyProbTestJob ()
Definition at line 244 of file BinaryJobList.cpp.
References KKB::KKQueue< BinaryJob >::QueueSize(), FeatureSelectionApp::BinaryJob::TestDeltaProbAccuracy(), FeatureSelectionApp::BinaryJob::TestGrade(), and FeatureSelectionApp::BinaryJob::ValidateOnly().
void BinaryJobList::PushOnBack (BinaryJobPtr j, ErrorCodes & result)
Definition at line 1048 of file BinaryJobList.cpp.
References KKB::endl(), FeatureSelectionApp::BinaryJob::JobId(), FeatureSelectionApp::BinaryJob::JobType(), KKB::RunLog::Level(), and FeatureSelectionApp::BinaryJob::ToStatusStr().
Referenced by CreateTestJobsForHighetsGradePerFeatureCount(), FeatureSelectionApp::BinaryJob::ExpandBestCaseBackward(), FeatureSelectionApp::BinaryJob::ExpandBestCaseForward(), ExtractByMinimumProcessintTime(), ExtractHighestGrade(), ExtractHighestTestGrade(), ExtractJobsForAGivenFeatureCount(), ExtractJobsWithSmallestDeltaAccProbForEachSvmParameterSet(), ExtractLowDeltaProbAccuarcy(), ExtractTestJobs(), FeatureSelectionApp::Processor::FlagJobsForTesting(), FeatureSelectionApp::ParmSearchResultsProcessor::GetBestCandidates(), Load(), LookUpByParameters(), ReFresh(), and FeatureSelectionApp::Processor::Run().
void BinaryJobList::ReFresh ()
Definition at line 1107 of file BinaryJobList.cpp.
References KKB::endl(), FeatureSelectionApp::BinaryJob::JobId(), KKB::RunLog::Level(), LookUpByJobId(), KKB::osFOPEN(), PushOnBack(), FeatureSelectionApp::BinaryJob::ReFresh(), and KKB::KKStr::Str().
void BinaryJobList::ReportResults (ostream & r)
Definition at line 1501 of file BinaryJobList.cpp.
References KKB::endl(), FeatureSelectionApp::BinaryJob::ReportHeaderLine1(), FeatureSelectionApp::BinaryJob::ReportHeaderLine2(), and FeatureSelectionApp::BinaryJob::ReportLine().
void BinaryJobList::ReportResultsHTML (ostream & r)
Definition at line 1518 of file BinaryJobList.cpp.
References KKB::endl(), FeatureSelectionApp::BinaryJob::ReportHeaderLineHTML(), and FeatureSelectionApp::BinaryJob::ReportLineHTML().
void BinaryJobList::Save ()
Definition at line 131 of file BinaryJobList.cpp.
References KKB::endl(), KKB::KKQueue< BinaryJob >::IdxToPtr(), KKB::RunLog::Level(), KKB::osAddSlash(), KKB::osDeleteFile(), KKB::osParseFileName(), KKB::osRenameFile(), KKB::osWaitForEnter(), KKB::KKQueue< BinaryJob >::QueueSize(), KKB::KKStr::Str(), and FeatureSelectionApp::BinaryJob::ToStatusStr().
FeatureNumList BinaryJobList::SelectFeaturesByMostFeaturesWithHighestGrade () const
Definition at line 981 of file BinaryJobList.cpp.
References FeatureSelectionApp::BinaryJob::FeatureCount(), FeatureSelectionApp::Processor::FileDesc(), FeatureSelectionApp::BinaryJob::Grade(), and KKB::LRand48().
BinaryJobPtr BinaryJobList::SelectOneDoneJobAtRandomFromTop10Percent ()
Definition at line 454 of file BinaryJobList.cpp.
References KKB::endl(), KKB::KKQueue< BinaryJob >::IdxToPtr(), KKB::RunLog::Level(), KKB::Max(), KKB::KKQueue< BinaryJob >::QueueSize(), SortByGrade(), and FeatureSelectionApp::BinaryJob::Status().
int BinaryJobList::SmallestNumberOfFeaturesExpanded () const
Definition at line 963 of file BinaryJobList.cpp.
References FeatureSelectionApp::BinaryJob::Features(), INT_MAX, KKB::Min(), KKMLL::FeatureNumList::NumSelFeatures(), and FeatureSelectionApp::BinaryJob::Status().
void BinaryJobList::SortByAccuracy ()
Definition at line 740 of file BinaryJobList.cpp.
Referenced by FeatureSelectionApp::ParmSearchResultsProcessor::GetBestCandidates().
void BinaryJobList::SortByAccuracyNorm ()
Definition at line 779 of file BinaryJobList.cpp.
void BinaryJobList::SortByGrade ()
Definition at line 555 of file BinaryJobList.cpp.
Referenced by CreateTestJobsForHighetsGradePerFeatureCount(), ExtractHighestGrade(), and SelectOneDoneJobAtRandomFromTop10Percent().
void BinaryJobList::SortByProcessingTime ()
Definition at line 585 of file BinaryJobList.cpp.
Referenced by ExtractFastestJobs().
void BinaryJobList::SortBySvmParameters ()
Definition at line 700 of file BinaryJobList.cpp.
Referenced by ExtractJobsWithSmallestDeltaAccProbForEachSvmParameterSet().
void BinaryJobList::SortByTestAccuracy ()
Definition at line 894 of file BinaryJobList.cpp.
void BinaryJobList::SortByTestAccuracyNorm ()
Definition at line 955 of file BinaryJobList.cpp.
void BinaryJobList::SortByTestGrade (bool featureCountPrefSmall)
Definition at line 833 of file BinaryJobList.cpp.
Referenced by ExtractHighestTestGrade(), FeatureSelectionApp::Processor::GetFeaturesFromTestResults(), and FeatureSelectionApp::Processor::MergeKBestFeatureSelections().
void BinaryJobList::SortDeltaProbAccuarcy ()
Definition at line 620 of file BinaryJobList.cpp.
Referenced by FeatureSelectionApp::ParmSearchResultsProcessor::GetBestCandidates().
void BinaryJobList::SortDeltaTestProbAccuarcy ()
Definition at line 664 of file BinaryJobList.cpp.
Referenced by FeatureSelectionApp::Processor::GetBestParametersFromTestResults().
double BinaryJobList::TotalProcessingTime () const
Definition at line 1872 of file BinaryJobList.cpp.
References FeatureSelectionApp::BinaryJob::ProcessingTime().
Referenced by FeatureSelectionApp::Processor::TotalProcessingTime().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/Apps/FeatureSelection/BinaryJobList.h
C:/Users/kurtk_000/GitHub/Pices/Apps/FeatureSelection/BinaryJobList.cpp