Pices: KKMLL::GrayScaleImagesFVProducerFactory Class Reference
KKMLL::GrayScaleImagesFVProducerFactory Class Reference
#include <GrayScaleImagesFVProducer.h>
Public Member Functions
virtual FeatureFileIOPtr DefaultFeatureFileIO () const
virtual const type_info * FeatureVectorListTypeId () const
Returns the 'type_info' of the FeatureVectorList that this instance of 'FactoryFVProducer' will create.
virtual const type_info * FeatureVectorTypeId () const
Returns the 'type_info' of the FeatureVector that this instance of 'FactoryFVProducer' works with.
virtual FileDescPtr FileDesc () const
virtual GrayScaleImagesFVProducerPtr ManufactureInstance (RunLog &runLog)
virtual FeatureVectorListPtr ManufacturFeatureVectorList (bool owner, RunLog &runLog) const
Manufactures a instance of a 'LarcosFeatureVectorList' class that will own its contents.
Public Member Functions inherited from KKMLL::FactoryFVProducer
FactoryFVProducer (const KKStr &_name, const KKStr &_fvClassName, const KKStr &_description)
const KKStr & Description () const
const KKStr & FvClassName () const
virtual FeatureVectorProducerPtr ManufactureInstance (RunLog &runLog)=0
Derived classes will instantiate appropriate instances of 'FeatureVectorProducer'.
virtual FeatureVectorPtr ManufacturFeatureVector (kkint32 numOfFeatires, RunLog &runLog)
Manufactures a instance of a derived 'FeatureVector' class that is appropriate for containing instances of FeatureVectors produced by the associated FeatureVectorProducer.
virtual FeatureVectorListPtr ManufacturFeatureVectorList (bool owner, RunLog &runLog) const
Manufactures a instance of a derived 'FeatureVectorList' class that is appropriate for containing instances of FeatureVectors produced by the associated FeatureVectorProducer.
virtual TrainingConfiguration2Ptr ManufacturTrainingConfiguration () const
Returns a 'TrainingConfiguration2' derived instance.
const KKStr & Name () const
Static Public Member Functions
static GrayScaleImagesFVProducerFactory * Factory (RunLog *runLog)
Returns instance of "GrayScaleImagesFVProducerFactory" that is registered with "FactoryFVProducer::RegisterFactory".
Static Public Member Functions inherited from KKMLL::FactoryFVProducer
static FactoryFVProducerPtr LookUpFactory (const KKStr &name)
Returns pointer to existing instance of 'FactoryFVProducer' that was previously registered with 'name'.
static FeatureVectorProducerPtr ManufactureInstance (const KKStr &name, RunLog &runLog)
Will instantiate a new instance of the appropriate 'FeatureVectorProducer' class given the supplied name.
static void RegisterFactory (FactoryFVProducerPtr factory, RunLog *runLog)
This is where you register newly instantiated instances of 'FactoryFVProducer' derived classes.
Protected Member Functions
virtual ~GrayScaleImagesFVProducerFactory ()
A Factory can never be deleted until the application terminates; the atexit method will perform the deletes.
Protected Member Functions inherited from KKMLL::FactoryFVProducer
virtual ~FactoryFVProducer ()
A Factory can near be deleted until the application terminates; the atexit method will perform the deletes.
Additional Inherited Members
Public Types inherited from KKMLL::FactoryFVProducer
typedef FactoryFVProducer * FactoryFVProducerPtr
Detailed Description
Definition at line 166 of file GrayScaleImagesFVProducer.h.
Constructor & Destructor Documentation
GrayScaleImagesFVProducerFactory::~GrayScaleImagesFVProducerFactory () protected virtual
A Factory can never be deleted until the application terminates; the atexit method will perform the deletes.
Definition at line 716 of file GrayScaleImagesFVProducer.cpp.
Member Function Documentation
FeatureFileIOPtr GrayScaleImagesFVProducerFactory::DefaultFeatureFileIO () const virtual
Implements KKMLL::FactoryFVProducer.
Definition at line 722 of file GrayScaleImagesFVProducer.cpp.
References KKMLL::FeatureFileIOC45::Driver().
GrayScaleImagesFVProducerFactory * GrayScaleImagesFVProducerFactory::Factory (RunLog * runLog) static
Returns instance of "GrayScaleImagesFVProducerFactory" that is registered with "FactoryFVProducer::RegisterFactory".
If instance does not exist yet out will create an instance and register it.
Definition at line 772 of file GrayScaleImagesFVProducer.cpp.
References KKMLL::FactoryFVProducer::RegisterFactory().
Referenced by KKMLL::TrainingConfiguration2::DefaultFeatureVectorProducer(), and KKMLL::TrainingConfiguration2::ExtractFullHierachyOfClasses().
const type_info * GrayScaleImagesFVProducerFactory::FeatureVectorListTypeId () const virtual
Returns the 'type_info' of the FeatureVectorList that this instance of 'FactoryFVProducer' will create.
Implements KKMLL::FactoryFVProducer.
Definition at line 735 of file GrayScaleImagesFVProducer.cpp.
const type_info * GrayScaleImagesFVProducerFactory::FeatureVectorTypeId () const virtual
Returns the 'type_info' of the FeatureVector that this instance of 'FactoryFVProducer' works with.
Implements KKMLL::FactoryFVProducer.
Definition at line 728 of file GrayScaleImagesFVProducer.cpp.
FileDescPtr GrayScaleImagesFVProducerFactory::FileDesc () const virtual
Implements KKMLL::FactoryFVProducer.
Definition at line 742 of file GrayScaleImagesFVProducer.cpp.
References KKMLL::GrayScaleImagesFVProducer::DefineFileDescStatic().
GrayScaleImagesFVProducerPtr GrayScaleImagesFVProducerFactory::ManufactureInstance (RunLog & runLog) virtual
Definition at line 749 of file GrayScaleImagesFVProducer.cpp.
References KKMLL::GrayScaleImagesFVProducer::GrayScaleImagesFVProducer().
FeatureVectorListPtr GrayScaleImagesFVProducerFactory::ManufacturFeatureVectorList (bool owner, RunLog & runLog) const virtual
Manufactures a instance of a 'LarcosFeatureVectorList' class that will own its contents.
Definition at line 757 of file GrayScaleImagesFVProducer.cpp.
References KKMLL::GrayScaleImagesFVProducer::DefineFileDescStatic(), and KKMLL::FeatureVectorProducer::Factory().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/GrayScaleImagesFVProducer.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/GrayScaleImagesFVProducer.cpp