Pices: MLL::InstrumentDataList Class Reference
MLL::InstrumentDataList Class Reference
#include <InstrumentDataList.h>
Public Types
typedef InstrumentDataList * InstrumentDataListPtr
typedef KKB::kkint32 kkint32
typedef KKB::kkuint32 kkuint32
Public Types inherited from KKB::KKQueue< InstrumentData >
typedef std::vector< InstrumentData * >::const_iterator const_iterator
typedef std::vector< InstrumentData * >::iterator iterator
Public Member Functions
InstrumentDataList (bool _owner)
InstrumentDataList (const KKStr &_fileName, bool &_loadWasSucessfull, RunLog &_log)
~InstrumentDataList ()
VectorDouble FrameOffsetsInMeters (kkuint32 scanLinesPerFrame, float scanRate, float defaultFlowRate)
Calculates the offset, in meters, from the beginning of a SIPPER file for each frame.
VectorUlong GetScanLinesPerMeterProfile () const
VectorFloat GetVolumePerMeterProfile (SipperFilePtr sipperFile, VolConstBool &cancelFlag, RunLog &log) const
void Save (const KKStr &fileName, RunLog &log) const
float ScanRate () const
void ScanRate (float _scanRate)
InstrumentDataPtr SearchForNearestScanLine (kkuint32 scanLine)
void SipperFileName (const KKStr &_sipperFileName)
const KKStr & SipperFileName () const
void ThereIsDepthData (bool _thereIsDepthData)
void ThereIsFlowRateData (bool _thereIsFlowRateData)
Public Member Functions inherited from KKB::KKQueue< InstrumentData >
KKQueue (bool _owner=true)
KKQueue (const KKQueue &q, bool _owner)
Constructor, similar to the Copy Constructor except that you can control whether it duplicates the contents.
virtual ~KKQueue ()
Virtual destructor; if owns its contents will also call the destructor on each one entry that it contains.
virtual void Add (EntryPtr _entry)
same as PushOnBack
virtual void AddFirst (EntryPtr _entry)
same as PushOnFront
virtual void AddQueue (const KKQueue &q)
Add the contents of a separate KKQueue container to this container.
EntryPtr BackOfQueue () const
Returns pointer of last element in the container without removing it.
void DeleteContents ()
Empties the container, if 'owner' is set to true will call the destructor on each element.
void DeleteEntry (EntryPtr _entry)
Removes from KKQueue the entry who's pointer = '_entry'.
void DeleteEntry (kkuint32 _idx)
Removes from KKQueue the entry who's index = '_idx'.
KKQueue * DuplicateListAndContents () const
Creates a new container including duplicating the contents, which also makes the new instance the owner of those contents.
kkuint32 FindTheKthElement (kkuint32 k, Functor pred)
EntryPtr FrontOfQueue () const
Returns a pointer to the element that is at from of the queue with out removing it from the queue.
EntryPtr GetFirst () const
Same as FrontOfQueue.
EntryPtr GetLast () const
Same as BackOfQueue.
EntryPtr IdxToPtr (kkuint32 idx) const
Returns back a pointer to the element who's index is 'idx'.
kkint32 LocateEntry (EntryConstPtr _entry) const
Returns the index of the element who's address is '_entry'.
EntryPtr LookAtBack () const
Same as BackOfQueue.
EntryPtr LookAtFront () const
Same as FrontOfQueue.
bool operator!= (const KKQueue< InstrumentData > &rightSide) const
returns False if NOT every entry in both containers point to the same elements
KKQueue & operator= (const KKQueue &q)
Assignment Operator.
bool operator== (const KKQueue< InstrumentData > &rightSide) const
Returns True if every entry in both containers point to the same elements.
InstrumentData & operator[] (kkuint32 i) const
Returns a reference to element indexed by 'i'; similar to IdxToPtr except tat it returns a reference rather than a pointer.0.
bool Owner () const
void Owner (bool _owner)
You can specify who owns the contents of the container.
virtual EntryPtr PopFromBack ()
Removes the last element in the container and returns its pointer.
virtual EntryPtr PopFromFront ()
Removes the first element in the container and returns its pointer.
kkint32 PtrToIdx (EntryConstPtr _entry) const
returns the index of the 'entry' that has the same pointer as '_entry', if none found returns -1
virtual void PushOnBack (EntryPtr _entry)
Adds '_entry' to the End of the container.
virtual void PushOnFront (EntryPtr _entry)
Adds '_entry' to the Front of the container.
kkint32 QueueSize () const
Same as calling vector<>::size(); returns the number of elements in KKQueue.
void RandomizeOrder ()
Randomizes the order of the vector.
void RandomizeOrder (kkint64 seed)
void RandomizeOrder (RandomNumGenerator &randomVariable)
Randomizes the order of the vector.
virtual EntryPtr RemoveFirst ()
same as PopFromFront
virtual EntryPtr RemoveLast ()
same as PopFromBack
void SetIdxToPtr (kkuint32 _idx, InstrumentData *_ptr)
void SwapIndexes (size_t idx1, size_t idx2)
Static Public Member Functions
static InstrumentDataListPtr CreateFromSipperFile (const KKStr &fullSipperFileName, SipperFilePtr sipperFile, VolConstBool &cancelFlag, RunLog &log)
Additional Inherited Members
Protected Member Functions inherited from KKB::KKQueue< InstrumentData >
KKQueue (const KKQueue &q)
Copy Constructor creating new instance; including duplicating contents if owner set to true.
Detailed Description
Manages all the instrument data for one single Sipper File. 'InstrumentDataFileManager' is responsible for managing all the 'InstrumentDataList' objects. The data comes from the SipperFiles where it is embedded. *
Author
Kurt Kramer
Definition at line 28 of file InstrumentDataList.h.
Member Typedef Documentation
typedef InstrumentDataList* MLL::InstrumentDataList::InstrumentDataListPtr
Definition at line 45 of file InstrumentDataList.h.
typedef KKB::kkint32 MLL::InstrumentDataList::kkint32
Definition at line 31 of file InstrumentDataList.h.
typedef KKB::kkuint32 MLL::InstrumentDataList::kkuint32
Definition at line 32 of file InstrumentDataList.h.
Constructor & Destructor Documentation
InstrumentDataList::InstrumentDataList (bool _owner)
Definition at line 34 of file InstrumentDataList.cpp.
Referenced by CreateFromSipperFile().
InstrumentDataList::InstrumentDataList (const KKStr & _fileName, bool & _loadWasSucessfull, RunLog & _log)
Definition at line 46 of file InstrumentDataList.cpp.
InstrumentDataList::~InstrumentDataList ()
Definition at line 64 of file InstrumentDataList.cpp.
Member Function Documentation
InstrumentDataListPtr InstrumentDataList::CreateFromSipperFile (const KKStr & fullSipperFileName, SipperFilePtr sipperFile, VolConstBool & cancelFlag, RunLog & log) static
Definition at line 71 of file InstrumentDataList.cpp.
References MLL::SipperBuff::ByteOffset(), MLL::InstrumentData::ByteOffset(), MLL::InstrumentData::CreateDefaultFieldIndirectionList(), MLL::InstrumentData::CreateFieldIndirectionVectorFromTabDelStr(), MLL::InstrumentDataManager::CreateInstrumentData(), MLL::SipperBuff::CreateSipperBuff(), MLL::InstrumentData::CTDBattery(), MLL::InstrumentData::CtdDate(), MLL::InstrumentData::CurrentFileVersion(), MLL::SipperBuff::CurRow(), MLL::SipperBuff::CurRowByteOffset(), MLL::InstrumentData::Depth(), KKB::endl(), MLL::SipperBuff::Eof(), MLL::InstrumentData::FlowRate1(), KKB::KKQueue< Entry >::FrontOfQueue(), MLL::SipperBuff::GetNextLine(), KKB::KKStrParser::GetNextToken(), KKB::KKStrParser::GetNextTokenDouble(), KKB::KKStrParser::GetNextTokenInt(), KKB::KKQueue< Entry >::IdxToPtr(), InstrumentDataList(), KKB::RunLog::Level(), KKB::osFOPEN(), KKB::osGetRootName(), KKB::KKQueue< Entry >::PushOnBack(), KKB::KKQueue< InstrumentData >::PushOnBack(), KKB::KKQueue< Entry >::PushOnFront(), KKB::KKQueue< Entry >::QueueSize(), KKB::KKQueue< InstrumentData >::QueueSize(), MLL::InstrumentData::RefreshDataFields(), MLL::InstrumentData::Salinity(), Save(), MLL::InstrumentData::ScanLine(), MLL::SipperFile::ScanRate(), ScanRate(), MLL::sfUnKnown, SipperFileName(), KKB::KKStr::Str(), KKB::StrFormatInt(), MLL::InstrumentData::Temperature(), ThereIsDepthData(), ThereIsFlowRateData(), KKB::KKStr::ToLower(), KKB::KKStr::TrimRight(), and KKB::DateTime::Year().
Referenced by MLL::InstrumentDataFileManager::ReExtractInstrumentDataForSipperFile().
VectorDouble InstrumentDataList::FrameOffsetsInMeters (kkuint32 scanLinesPerFrame, float scanRate, float defaultFlowRate)
Calculates the offset, in meters, from the beginning of a SIPPER file for each frame.
Calculates the offset, in meters, from the beginning of a SIPPER file for each frame. Data will be assumed to be in scan line order. Flow-rate and Scan-rate will be used as part of the calculations.
Definition at line 431 of file InstrumentDataList.cpp.
References MLL::InstrumentData::FlowRate1(), and MLL::InstrumentData::ScanLine().
Referenced by MLL::ImageFeaturesList::ExtractPositionsByMeter().
VectorUlong InstrumentDataList::GetScanLinesPerMeterProfile () const
Definition at line 630 of file InstrumentDataList.cpp.
References MLL::SipperFile::Depth(), MLL::InstrumentData::Depth(), MLL::InstrumentData::FlowRate1(), MLL::InstrumentData::FlowRate2(), KKB::KKQueue< InstrumentData >::IdxToPtr(), and KKB::KKQueue< InstrumentData >::QueueSize().
Referenced by MLL::InstrumentDataFileManager::GetScanLinesPerMeterProfile2().
VectorFloat InstrumentDataList::GetVolumePerMeterProfile (SipperFilePtr sipperFile, VolConstBool & cancelFlag, RunLog & log) const
Definition at line 572 of file InstrumentDataList.cpp.
References MLL::InstrumentData::Depth(), KKB::endl(), KKB::RunLog::Level(), and MLL::SipperFile::ScanRate().
Referenced by MLL::InstrumentDataFileManager::GetVolumePerMeterProfile2().
void InstrumentDataList::Save (const KKStr & fileName, RunLog & log) const
Definition at line 385 of file InstrumentDataList.cpp.
References MLL::InstrumentData::CurrentFileVersion(), KKB::endl(), MLL::InstrumentData::FieldName(), KKB::RunLog::Level(), MLL::InstrumentData::NumFields(), KKB::osGetLocalDateTime(), KKB::KKQueue< InstrumentData >::QueueSize(), KKB::KKStr::Str(), and MLL::InstrumentData::ToTabDelStr().
Referenced by CreateFromSipperFile(), and MLL::InstrumentDataFileManager::ReExtractInstrumentDataForSipperFile().
float MLL::InstrumentDataList::ScanRate () const inline
Definition at line 88 of file InstrumentDataList.h.
Referenced by CreateFromSipperFile(), and MLL::DataBase::InstrumentDataLoad().
void MLL::InstrumentDataList::ScanRate (float _scanRate) inline
Definition at line 89 of file InstrumentDataList.h.
InstrumentDataPtr InstrumentDataList::SearchForNearestScanLine (kkuint32 scanLine)
Definition at line 496 of file InstrumentDataList.cpp.
References KKB::KKQueue< InstrumentData >::IdxToPtr(), KKB::KKQueue< InstrumentData >::QueueSize(), and MLL::InstrumentData::ScanLine().
Referenced by MLL::ImageFeaturesList::ExtractPositionsByMeter(), MLL::DataBase::FeatureDataGetOneSipperFile(), and MLL::InstrumentDataFileManager::GetClosestInstrumentData().
void MLL::InstrumentDataList::SipperFileName (const KKStr & _sipperFileName) inline
Definition at line 73 of file InstrumentDataList.h.
Referenced by CreateFromSipperFile(), MLL::InstrumentDataFileManager::GetClosestInstrumentData(), MLL::InstrumentDataFileManager::GetScanLinesPerMeterProfile2(), and MLL::InstrumentDataFileManager::GetVolumePerMeterProfile2().
const KKStr& MLL::InstrumentDataList::SipperFileName () const inline
Definition at line 76 of file InstrumentDataList.h.
void MLL::InstrumentDataList::ThereIsDepthData (bool _thereIsDepthData) inline
Definition at line 91 of file InstrumentDataList.h.
Referenced by CreateFromSipperFile().
void MLL::InstrumentDataList::ThereIsFlowRateData (bool _thereIsFlowRateData) inline
Definition at line 92 of file InstrumentDataList.h.
Referenced by CreateFromSipperFile().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/InstrumentDataList.h
C:/Users/Kurt/GitHub/Pices/PicesLibraries/PicesLibrary/InstrumentDataList.cpp