Pices: KKB::RBnode< Entry > Class Template Reference
KKB::RBnode< Entry > Class Template Reference
#include <RBTree.h>
Public Member Functions
RBnode (RBnodePtr _parent, RBnodePtr _left, RBnodePtr _right, RBcolor _color, EntryPtr _entry)
RBcolor Color ()
void Color (RBcolor _color)
EntryPtr Data ()
void Data (EntryPtr _data)
RBnodePtr Left ()
void Left (RBnodePtr _left)
RBnodePtr Parent ()
void Parent (RBnodePtr _parent)
RBnodePtr Right ()
void Right (RBnodePtr _right)
Detailed Description
template<class Entry>
class KKB::RBnode< Entry >
Definition at line 33 of file RBTree.h.
Constructor & Destructor Documentation
template<class Entry > KKB::RBnode< Entry >::RBnode (RBnodePtr _parent, RBnodePtr _left, RBnodePtr _right, RBcolor _color, EntryPtr _entry)
Definition at line 281 of file RBTree.h.
Member Function Documentation
template<class Entry> RBcolor KKB::RBnode< Entry >::Color () inline
Definition at line 47 of file RBTree.h.
Referenced by KKB::RBTree< Entry, CompareNodes, KeyType >::RBInsert(), KKB::RBTree< Entry, CompareNodes, KeyType >::RBTree(), and KKB::RBTree< Entry, CompareNodes, KeyType >::Validate().
template<class Entry> void KKB::RBnode< Entry >::Color (RBcolor _color) inline
Definition at line 53 of file RBTree.h.
template<class Entry> EntryPtr KKB::RBnode< Entry >::Data () inline
Definition at line 48 of file RBTree.h.
Referenced by KKB::RBTree< Entry, CompareNodes, KeyType >::CompareToTree(), KKB::RBTree< Entry, CompareNodes, KeyType >::DeleteCurrentNode(), KKB::Iterator< Entry, CompareNodes, KeyType >::GetEqual(), KKB::RBTree< Entry, CompareNodes, KeyType >::GetEqual(), KKB::Iterator< Entry, CompareNodes, KeyType >::GetFirst(), KKB::RBTree< Entry, CompareNodes, KeyType >::GetFirst(), KKB::Iterator< Entry, CompareNodes, KeyType >::GetGreater(), KKB::RBTree< Entry, CompareNodes, KeyType >::GetGreater(), KKB::Iterator< Entry, CompareNodes, KeyType >::GetGreaterOrEqual(), KKB::RBTree< Entry, CompareNodes, KeyType >::GetGreaterOrEqual(), KKB::Iterator< Entry, CompareNodes, KeyType >::GetLast(), KKB::RBTree< Entry, CompareNodes, KeyType >::GetLast(), KKB::RBTree< Entry, CompareNodes, KeyType >::GetLess(), KKB::Iterator< Entry, CompareNodes, KeyType >::GetNext(), KKB::Iterator< Entry, CompareNodes, KeyType >::GetPrev(), KKB::RBTree< Entry, CompareNodes, KeyType >::Predecessor(), KKB::RBTree< Entry, CompareNodes, KeyType >::RBInsert(), KKB::RBTree< Entry, CompareNodes, KeyType >::RBTree(), KKB::RBTree< Entry, CompareNodes, KeyType >::Successor(), KKB::RBTree< Entry, CompareNodes, KeyType >::Validate(), and KKB::RBTree< Entry, CompareNodes, KeyType >::~RBTree().
template<class Entry> void KKB::RBnode< Entry >::Data (EntryPtr _data) inline
Definition at line 54 of file RBTree.h.
template<class Entry> RBnodePtr KKB::RBnode< Entry >::Left () inline
Definition at line 49 of file RBTree.h.
Referenced by KKB::RBTree< Entry, CompareNodes, KeyType >::CalcTreeStats(), KKB::RBTree< Entry, CompareNodes, KeyType >::CompareToTree(), KKB::RBTree< Entry, CompareNodes, KeyType >::GetEqual(), KKB::RBTree< Entry, CompareNodes, KeyType >::GetGreaterOrEqual(), KKB::RBTree< Entry, CompareNodes, KeyType >::GetLast(), KKB::RBTree< Entry, CompareNodes, KeyType >::RBInsert(), KKB::RBTree< Entry, CompareNodes, KeyType >::RBTree(), KKB::RBTree< Entry, CompareNodes, KeyType >::Validate(), and KKB::RBTree< Entry, CompareNodes, KeyType >::~RBTree().
template<class Entry> void KKB::RBnode< Entry >::Left (RBnodePtr _left) inline
Definition at line 55 of file RBTree.h.
template<class Entry> RBnodePtr KKB::RBnode< Entry >::Parent () inline
Definition at line 50 of file RBTree.h.
Referenced by KKB::RBTree< Entry, CompareNodes, KeyType >::GetLast(), KKB::RBTree< Entry, CompareNodes, KeyType >::RBInsert(), and KKB::RBTree< Entry, CompareNodes, KeyType >::Validate().
template<class Entry> void KKB::RBnode< Entry >::Parent (RBnodePtr _parent) inline
Definition at line 56 of file RBTree.h.
template<class Entry> RBnodePtr KKB::RBnode< Entry >::Right () inline
Definition at line 51 of file RBTree.h.
Referenced by KKB::RBTree< Entry, CompareNodes, KeyType >::CalcTreeStats(), KKB::RBTree< Entry, CompareNodes, KeyType >::CompareToTree(), KKB::RBTree< Entry, CompareNodes, KeyType >::GetEqual(), KKB::RBTree< Entry, CompareNodes, KeyType >::GetGreaterOrEqual(), KKB::RBTree< Entry, CompareNodes, KeyType >::GetLast(), KKB::RBTree< Entry, CompareNodes, KeyType >::RBInsert(), KKB::RBTree< Entry, CompareNodes, KeyType >::RBTree(), KKB::RBTree< Entry, CompareNodes, KeyType >::Validate(), and KKB::RBTree< Entry, CompareNodes, KeyType >::~RBTree().
template<class Entry> void KKB::RBnode< Entry >::Right (RBnodePtr _right) inline
Definition at line 57 of file RBTree.h.
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/RBTree.h