Pices: FeatureSelectionApp::Processor Class Reference
FeatureSelectionApp::Processor Class Reference
#include <Processor.h>
Public Member Functions
Processor (FeatureSelectionPtr _featureSelection, bool _byBinaryClasses, int _processorId, FileDescPtr _fileDesc, SearchTypes _searchType, MLClassPtr _class1, MLClassPtr _class2, SearchMethod _searchMethod, ProcessorStatus _status)
Processor constructor for managing search jobs, either feature selection or parameter search.
Processor (FeatureSelectionPtr _featureSelection, int _processorId, BinaryClassPtr _bnaryClass, FileDescPtr _fileDesc, ProcessorStatus _status)
Processor Constructor for managing FinalResults jobs.
~Processor ()
int AllocateNextJobId ()
bool AlreadyNormalized () const
bool AreAllJobsDone ()
int BeamSearchFeatureCount () const
float BestA () const
double BestC () const
double BestGamma () const
kkint32 BestNumOfRounds () const
BinaryJobListPtr BinaryJobs ()
void Block ()
bool ByBinaryClasses () const
MLClassPtr Class1 () const
const KKStr & Class1Name () const
MLClassPtr Class2 () const
const KKStr & Class2Name () const
MLClassListPtr ClassesThisProcess () const
TrainingConfiguration2Ptr Config () const
const ProcessorCycles & CpuCyclesByProcId () const
const DateTime & DateTimeEnded () const
const DateTime & DateTimeStarted () const
void EndBlock ()
FeatureSelectionPtr FeatureSelection () const
FileDescPtr FileDesc () const
void FlagJobsForTesting (ofstream *statusFile, BinaryJobListPtr candidats)
void GetBestParametersFromTestResults (double &cParm, double &gammaParm, float &aParm)
VectorDouble GetCpuCyclesByFeatureCount ()
Return the Number CPU processed for each FeatureCount.
FeatureImpactPtr GetFeatureImpact ()
FeatureNumList GetFeaturesFromTestResults ()
FeatureNumList GetFeaturesRemoveHurtFul ()
VectorInt GetSmallestJobIdByFeatureCount ()
Return the smallest Job Id that processed for given featuerCounts.
GradingMethodType GradingMethod () const
const FeatureNumList & InitialFeatures () const
RunLog & Log () const
FeatureNumList MergeKBestFeatureSelections (int k, int minNumOfFeatures)
MLClassListPtr MLClasses () const
int NextJobId () const
int NumOfFolds () const
MLClassPtr PositiveClass () const
int ProcessorId () const
void ProcessRestart ()
bool QuitRunning () const
FeatureVectorListPtr RandomSplit (int splitNum)
const KKStr & ResultFileName () const
FinalResultType ResultType () const
void Run ()
FeatureNumList SelectBestFeatures ()
SVM_SelectionMethod SelectionMethod () const
void SetQuitRunningFlag ()
ProcessorStatus Status () const
const KKStr & SummaryResultsFileName () const
FeatureVectorListPtr TestData ()
double TotalCpuTimeUsed () const
double TotalProcessingTime () const
FeatureVectorListPtr TrainingData () const
void Update (ProcessorPtr p)
FeatureVectorListPtr ValidationData ()
Detailed Description
Definition at line 53 of file Processor.h.
Constructor & Destructor Documentation
Processor::Processor (FeatureSelectionPtr _featureSelection, bool _byBinaryClasses, int _processorId, FileDescPtr _fileDesc, SearchTypes _searchType, MLClassPtr _class1, MLClassPtr _class2, SearchMethod _searchMethod, ProcessorStatus _status)
Processor constructor for managing search jobs, either feature selection or parameter search.
Definition at line 188 of file Processor.cpp.
References KKMLL::TrainingConfiguration2::A_Param(), KKMLL::TrainingConfiguration2::AddATrainingClass(), FeatureSelectionApp::FeatureSelection::AlreadyNormalized(), FeatureSelectionApp::FeatureSelection::BeamSize(), Block(), KKMLL::TrainingConfiguration2::C_Param(), Class1Name(), Class2Name(), FeatureSelectionApp::FeatureSelection::Config(), KKMLL::TrainingConfiguration2::EmptyTrainingClasses(), EndBlock(), KKB::endl(), FeatureSelectionApp::FeatureSelection::ExpansionLimit(), KKMLL::TrainingConfiguration2::Gamma(), FeatureSelectionApp::FeatureSelection::InitialFeatures(), FeatureSelectionApp::FeatureSelection::JustGettingStats(), KKB::RunLog::Level(), KKMLL::TrainingConfiguration2::MachineType(), FeatureSelectionApp::FeatureSelection::MajorStep(), FeatureSelectionApp::MajorStepToStr(), FeatureSelectionApp::FeatureSelection::MLClasses(), KKMLL::TrainingConfiguration2::ModelingMethod(), KKMLL::TrainingConfiguration2::ModelParameterCmdLine(), KKMLL::TrainingConfiguration2::Number_of_rounds(), FeatureSelectionApp::FeatureSelection::NumJobsAtATime(), FeatureSelectionApp::FeatureSelection::NumOfFolds(), KKMLL::FeatureNumList::NumSelFeatures(), KKB::osFileExists(), KKB::osGetLocalDateTime(), KKB::osGetProcessId(), KKB::osGetSystemTimeUsed(), FeatureSelectionApp::FeatureSelection::ProcessingOrder(), FeatureSelectionApp::ProcessingOrderToStr(), KKMLL::MLClassList::PushOnBack(), FeatureSelectionApp::FeatureSelection::TestData(), and FeatureSelectionApp::FeatureSelection::TrainingData().
Processor::Processor (FeatureSelectionPtr _featureSelection, int _processorId, BinaryClassPtr _binaryClass, FileDescPtr _fileDesc, ProcessorStatus _status)
Processor Constructor for managing FinalResults jobs.
Make sure the _summaryResultsFileName is deleted before we start processing.
Definition at line 58 of file Processor.cpp.
References FeatureSelectionApp::FeatureSelection::AlreadyNormalized(), Block(), FeatureSelectionApp::BinaryClass::ConfigFileName(), EndBlock(), KKB::endl(), FeatureSelectionApp::BinaryClass::FinalResultsFileName(), FeatureSelectionApp::FinalResultTypeToStr(), FeatureSelectionApp::FeatureSelection::JustGettingStats(), KKB::RunLog::Level(), KKMLL::TrainingConfiguration2::Load(), KKMLL::TrainingConfiguration2::MachineType(), FeatureSelectionApp::FeatureSelection::MLClasses(), KKMLL::TrainingConfiguration2::ModelParameterCmdLine(), Null, FeatureSelectionApp::FeatureSelection::NumJobsAtATime(), FeatureSelectionApp::OnePassOnly, KKB::osFileExists(), KKB::osGetLocalDateTime(), KKB::osGetProcessId(), KKB::osGetRootName(), KKB::osGetSystemTimeUsed(), FeatureSelectionApp::BinaryClass::ResultType(), FeatureSelectionApp::BinaryClass::SelectionMethod(), KKMLL::TrainingConfiguration2::SelectionMethod(), FeatureSelectionApp::FeatureSelection::TestData(), and FeatureSelectionApp::FeatureSelection::TrainingData().
Processor::~Processor ()
Definition at line 411 of file Processor.cpp.
References KKB::endl(), and KKB::RunLog::Level().
Member Function Documentation
int Processor::AllocateNextJobId ()
Definition at line 1628 of file Processor.cpp.
bool FeatureSelectionApp::Processor::AlreadyNormalized () const inline
Definition at line 87 of file Processor.h.
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), and FeatureSelectionApp::BinaryJob::EvaluateNode().
bool Processor::AreAllJobsDone ()
Definition at line 3089 of file Processor.cpp.
References FeatureSelectionApp::BinaryJobList::AreAllJobsDone().
int FeatureSelectionApp::Processor::BeamSearchFeatureCount () const inline
Definition at line 88 of file Processor.h.
float FeatureSelectionApp::Processor::BestA () const inline
Definition at line 89 of file Processor.h.
double FeatureSelectionApp::Processor::BestC () const inline
Definition at line 90 of file Processor.h.
double FeatureSelectionApp::Processor::BestGamma () const inline
Definition at line 91 of file Processor.h.
kkint32 FeatureSelectionApp::Processor::BestNumOfRounds () const inline
Definition at line 92 of file Processor.h.
BinaryJobListPtr Processor::BinaryJobs ()
Definition at line 524 of file Processor.cpp.
Referenced by FeatureSelectionApp::ParmSearchResultsProcessor::GetBestCandidates().
void Processor::Block ()
Definition at line 611 of file Processor.cpp.
References KKB::endl(), KKB::RunLog::Level(), KKB::osSleep(), and KKB::KKStr::Str().
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), Processor(), ProcessRestart(), Run(), and SetQuitRunningFlag().
bool FeatureSelectionApp::Processor::ByBinaryClasses () const inline
Definition at line 93 of file Processor.h.
Referenced by FeatureSelectionApp::FeatureSelection::BuildResultConfigFile().
MLClassPtr FeatureSelectionApp::Processor::Class1 () const inline
Definition at line 94 of file Processor.h.
const KKStr & Processor::Class1Name () const
Definition at line 539 of file Processor.cpp.
Referenced by Processor().
MLClassPtr FeatureSelectionApp::Processor::Class2 () const inline
Definition at line 95 of file Processor.h.
const KKStr & Processor::Class2Name () const
Definition at line 548 of file Processor.cpp.
Referenced by Processor().
MLClassListPtr FeatureSelectionApp::Processor::ClassesThisProcess () const inline
Definition at line 104 of file Processor.h.
Referenced by FeatureSelectionApp::BinaryJob::EvaluateNode().
TrainingConfiguration2Ptr FeatureSelectionApp::Processor::Config () const inline
Definition at line 96 of file Processor.h.
Referenced by FeatureSelectionApp::JobRandomSplit::EvaluateNode(), and FeatureSelectionApp::BinaryJob::EvaluateNode().
const ProcessorCycles& FeatureSelectionApp::Processor::CpuCyclesByProcId () const inline
Definition at line 97 of file Processor.h.
const DateTime& FeatureSelectionApp::Processor::DateTimeEnded () const inline
Definition at line 98 of file Processor.h.
const DateTime& FeatureSelectionApp::Processor::DateTimeStarted () const inline
Definition at line 99 of file Processor.h.
void Processor::EndBlock ()
Definition at line 649 of file Processor.cpp.
References KKB::endl(), KKB::RunLog::Level(), and KKB::KKStr::Str().
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), GetBestParametersFromTestResults(), GetFeaturesFromTestResults(), Processor(), ProcessRestart(), Run(), and SetQuitRunningFlag().
FeatureSelectionPtr FeatureSelectionApp::Processor::FeatureSelection () const inline
Definition at line 100 of file Processor.h.
Referenced by FeatureSelectionApp::ParmSearchResultsProcessor::ParmSearchResultsProcessor().
FileDescPtr FeatureSelectionApp::Processor::FileDesc () const inline
Definition at line 101 of file Processor.h.
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), FeatureSelectionApp::BinaryJob::EvaluateNode(), FeatureSelectionApp::BinaryJobList::FileDesc(), and FeatureSelectionApp::BinaryJobList::SelectFeaturesByMostFeaturesWithHighestGrade().
void Processor::FlagJobsForTesting (ofstream * statusFile, BinaryJobListPtr candidats)
Definition at line 1315 of file Processor.cpp.
References FeatureSelectionApp::BinaryJob::Accuracy(), FeatureSelectionApp::BinaryJob::AccuracyNorm(), FeatureSelectionApp::BinaryJob::AParm(), FeatureSelectionApp::BinaryJob::AvgPredProb(), FeatureSelectionApp::BinaryJob::ChgFeatureNum(), FeatureSelectionApp::BinaryJob::CParm(), FeatureSelectionApp::BinaryJob::DecisiveProbMean(), FeatureSelectionApp::BinaryJob::DecisiveProbStdDev(), KKB::endl(), FeatureSelectionApp::BinaryJob::Features(), FeatureSelectionApp::BinaryJob::FMeasure(), FeatureSelectionApp::BinaryJob::GammaParm(), FeatureSelectionApp::BinaryJob::Grade(), FeatureSelectionApp::BinaryJob::JobId(), FeatureSelectionApp::BinaryJob::JobTypeStr(), KKB::RunLog::Level(), FeatureSelectionApp::BinaryJobList::LookUpByParameters(), FeatureSelectionApp::BinaryJob::NumOfRounds(), FeatureSelectionApp::BinaryJob::ProcessingTime(), FeatureSelectionApp::BinaryJobList::PushOnBack(), FeatureSelectionApp::BinaryJob::Status(), FeatureSelectionApp::BinaryJob::ToStatusStr(), and FeatureSelectionApp::BinaryJob::ValidateOnly().
void Processor::GetBestParametersFromTestResults (double & cParm, double & gammaParm, float & aParm)
Definition at line 3285 of file Processor.cpp.
References FeatureSelectionApp::BinaryJob::AParm(), FeatureSelectionApp::BinaryJob::CParm(), EndBlock(), KKB::endl(), FeatureSelectionApp::BinaryJobList::ExtractHighestTestGrade(), FeatureSelectionApp::BinaryJobList::ExtractTestJobs(), FeatureSelectionApp::FeatureSelection::FeatureCountPrefSmall(), KKB::KKQueue< Entry >::FrontOfQueue(), FeatureSelectionApp::BinaryJob::GammaParm(), KKB::RunLog::Level(), KKB::osWaitForEnter(), FeatureSelectionApp::FeatureSelection::ParamSelCriteria(), KKB::KKQueue< Entry >::QueueSize(), and FeatureSelectionApp::BinaryJobList::SortDeltaTestProbAccuarcy().
Referenced by FeatureSelectionApp::FeatureSelection::BuildResultConfigFile().
VectorDouble Processor::GetCpuCyclesByFeatureCount ()
Return the Number CPU processed for each FeatureCount.
Definition at line 468 of file Processor.cpp.
References FeatureSelectionApp::BinaryJob::FeatureCount(), KKMLL::FileDesc::NumOfFields(), and FeatureSelectionApp::BinaryJob::ProcessingTime().
FeatureImpactPtr Processor::GetFeatureImpact ()
Definition at line 2702 of file Processor.cpp.
FeatureNumList Processor::GetFeaturesFromTestResults ()
Definition at line 3248 of file Processor.cpp.
References EndBlock(), KKB::endl(), FeatureSelectionApp::BinaryJobList::ExtractTestJobs(), FeatureSelectionApp::FeatureSelection::FeatureCountPrefSmall(), FeatureSelectionApp::BinaryJob::Features(), KKB::KKQueue< Entry >::FrontOfQueue(), KKB::RunLog::Level(), KKB::osWaitForEnter(), KKB::KKQueue< Entry >::QueueSize(), and FeatureSelectionApp::BinaryJobList::SortByTestGrade().
Referenced by SelectBestFeatures().
FeatureNumList Processor::GetFeaturesRemoveHurtFul ()
Definition at line 3275 of file Processor.cpp.
References FeatureSelectionApp::FeatureImpact::FeatureThatDontHurt().
Referenced by SelectBestFeatures().
VectorInt Processor::GetSmallestJobIdByFeatureCount ()
Return the smallest Job Id that processed for given featuerCounts.
Definition at line 440 of file Processor.cpp.
References FeatureSelectionApp::BinaryJob::FeatureCount(), and KKMLL::FileDesc::NumOfFields().
GradingMethodType FeatureSelectionApp::Processor::GradingMethod () const inline
Definition at line 102 of file Processor.h.
References FeatureSelectionApp::FeatureSelection::GradingMethod().
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), and FeatureSelectionApp::BinaryJob::EvaluateNode().
const FeatureNumList & Processor::InitialFeatures () const
Definition at line 424 of file Processor.cpp.
References FeatureSelectionApp::FeatureSelection::InitialFeatures().
Referenced by FeatureSelectionApp::BinaryJobList::CreateTestJobsForHighetsGradePerFeatureCount(), and FeatureSelectionApp::BinaryJob::ExpandBestCaseForward().
RunLog& FeatureSelectionApp::Processor::Log () const inline
Definition at line 106 of file Processor.h.
FeatureNumList Processor::MergeKBestFeatureSelections (int k, int minNumOfFeatures)
Definition at line 3207 of file Processor.cpp.
References KKB::endl(), FeatureSelectionApp::FeatureSelection::FeatureCountPrefSmall(), FeatureSelectionApp::BinaryJob::Features(), KKB::KKQueue< Entry >::IdxToPtr(), KKMLL::FeatureNumList::IsSubSet(), KKB::RunLog::Level(), KKMLL::FeatureNumList::NumOfFeatures(), and FeatureSelectionApp::BinaryJobList::SortByTestGrade().
Referenced by SelectBestFeatures().
MLClassListPtr FeatureSelectionApp::Processor::MLClasses () const inline
Definition at line 103 of file Processor.h.
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode(), and FeatureSelectionApp::JobRandomSplit::EvaluateNode().
int FeatureSelectionApp::Processor::NextJobId () const inline
Definition at line 107 of file Processor.h.
int FeatureSelectionApp::Processor::NumOfFolds () const inline
Definition at line 108 of file Processor.h.
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), and FeatureSelectionApp::BinaryJob::EvaluateNode().
MLClassPtr Processor::PositiveClass () const
Definition at line 431 of file Processor.cpp.
References FeatureSelectionApp::FeatureSelection::PositiveClass().
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode(), FeatureSelectionApp::JobRandomSplit::EvaluateNode(), and FeatureSelectionApp::BinaryJob::EvaluateNode().
int FeatureSelectionApp::Processor::ProcessorId () const inline
Definition at line 110 of file Processor.h.
void Processor::ProcessRestart ()
Definition at line 2883 of file Processor.cpp.
References Block(), EndBlock(), KKB::endl(), FeatureSelectionApp::BinaryJob::JobTypeStr(), KKB::RunLog::Level(), FeatureSelectionApp::ProcessorStatusToStr(), FeatureSelectionApp::BinaryJob::Status(), and FeatureSelectionApp::BinaryJob::ToStatusStr().
bool FeatureSelectionApp::Processor::QuitRunning () const inline
Definition at line 111 of file Processor.h.
FeatureVectorListPtr Processor::RandomSplit (int splitNum)
Definition at line 497 of file Processor.cpp.
References FeatureSelectionApp::FeatureSelection::RandomSplit().
const KKStr& FeatureSelectionApp::Processor::ResultFileName () const inline
Definition at line 112 of file Processor.h.
FinalResultType FeatureSelectionApp::Processor::ResultType () const inline
Definition at line 113 of file Processor.h.
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode(), and FeatureSelectionApp::JobRandomSplit::EvaluateNode().
void Processor::Run ()
Definition at line 3105 of file Processor.cpp.
References Block(), FeatureSelectionApp::BinaryJob::CreateDuplicateJob(), EndBlock(), KKB::endl(), FeatureSelectionApp::BinaryJob::EvaluateNode(), FeatureSelectionApp::BinaryJobList::JobsStillRunning(), KKB::RunLog::Level(), KKB::osSleep(), KKB::KKQueue< Entry >::Owner(), FeatureSelectionApp::ProcessorStatusToStr(), FeatureSelectionApp::BinaryJobList::PushOnBack(), and FeatureSelectionApp::BinaryJob::ToStatusStr().
Referenced by FeatureSelectionApp::FeatureSelection::Run().
FeatureNumList Processor::SelectBestFeatures ()
Definition at line 3349 of file Processor.cpp.
References FeatureSelectionApp::FeatureSelection::FeatureCriteria(), GetFeaturesFromTestResults(), GetFeaturesRemoveHurtFul(), MergeKBestFeatureSelections(), and FeatureSelectionApp::FeatureSelection::SearchType().
Referenced by FeatureSelectionApp::FeatureSelection::BuildResultConfigFile().
SVM_SelectionMethod FeatureSelectionApp::Processor::SelectionMethod () const inline
Definition at line 114 of file Processor.h.
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode(), and FeatureSelectionApp::JobRandomSplit::EvaluateNode().
void Processor::SetQuitRunningFlag ()
Definition at line 2921 of file Processor.cpp.
References Block(), EndBlock(), and KKB::endl().
ProcessorStatus FeatureSelectionApp::Processor::Status () const inline
Definition at line 115 of file Processor.h.
Referenced by FeatureSelectionApp::FeatureSelection::Run().
const KKStr& FeatureSelectionApp::Processor::SummaryResultsFileName () const inline
Definition at line 116 of file Processor.h.
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode(), and FeatureSelectionApp::JobRandomSplit::EvaluateNode().
FeatureVectorListPtr Processor::TestData ()
Definition at line 507 of file Processor.cpp.
References FeatureSelectionApp::FeatureSelection::TestData().
Referenced by FeatureSelectionApp::BinaryJob::EvaluateNode().
double FeatureSelectionApp::Processor::TotalCpuTimeUsed () const inline
Definition at line 117 of file Processor.h.
Referenced by FeatureSelectionApp::FeatureSelection::BuildResultConfigFile().
double Processor::TotalProcessingTime () const
Definition at line 3338 of file Processor.cpp.
References FeatureSelectionApp::BinaryJobList::TotalProcessingTime().
FeatureVectorListPtr FeatureSelectionApp::Processor::TrainingData () const inline
Definition at line 118 of file Processor.h.
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode(), and FeatureSelectionApp::BinaryJob::EvaluateNode().
void Processor::Update (ProcessorPtr p)
Definition at line 1638 of file Processor.cpp.
FeatureVectorListPtr Processor::ValidationData ()
Definition at line 516 of file Processor.cpp.
References FeatureSelectionApp::FeatureSelection::ValidationData().
Referenced by FeatureSelectionApp::JobValidation::EvaluateNode().
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/Apps/FeatureSelection/Processor.h
C:/Users/kurtk_000/GitHub/Pices/Apps/FeatureSelection/Processor.cpp