Pices: MLL::VolumeSampledStat Class Reference
MLL::VolumeSampledStat Class Reference
#include <VolumeSampledStat.h>
Public Types
typedef KKB::kkint32 kkint32
typedef VolumeSampledStat * VolumeSampledStatPtr
Public Member Functions
VolumeSampledStat ()
VolumeSampledStat (const VolumeSampledStat &_stat)
VolumeSampledStat (kkint32 _binId, float _binDepth, float _volumeSampled)
~VolumeSampledStat ()
void AddToVolumeSampled (float _volumeSampled)
float BinDepth () const
void BinDepth (float _binDepth)
kkint32 BinId () const
void BinId (kkint32 _binId)
float VolumeSampled () const
void VolumeSampled (float _volumeSampled)
Detailed Description
Used to Pass Volume of water sampled per (depth in meters) groupings. Each instance keeps track of binId, binDepth, and volumeSampled.
Author
Kurt Kramer
Definition at line 22 of file VolumeSampledStat.h.
Member Typedef Documentation
typedef KKB::kkint32 MLL::VolumeSampledStat::kkint32
Definition at line 25 of file VolumeSampledStat.h.
typedef VolumeSampledStat* MLL::VolumeSampledStat::VolumeSampledStatPtr
Definition at line 26 of file VolumeSampledStat.h.
Constructor & Destructor Documentation
VolumeSampledStat::VolumeSampledStat ()
Definition at line 21 of file VolumeSampledStat.cpp.
VolumeSampledStat::VolumeSampledStat (const VolumeSampledStat & _stat)
Definition at line 29 of file VolumeSampledStat.cpp.
VolumeSampledStat::VolumeSampledStat (kkint32 _binId, float _binDepth, float _volumeSampled)
Definition at line 37 of file VolumeSampledStat.cpp.
VolumeSampledStat::~VolumeSampledStat ()
Definition at line 51 of file VolumeSampledStat.cpp.
Member Function Documentation
void VolumeSampledStat::AddToVolumeSampled (float _volumeSampled)
Definition at line 57 of file VolumeSampledStat.cpp.
Referenced by MLL::VolumeSampledStatList::Give().
float MLL::VolumeSampledStat::BinDepth () const inline
Definition at line 40 of file VolumeSampledStat.h.
Referenced by MLL::DataBase::InstrumentDataGetVolumePerMeterDepth().
void MLL::VolumeSampledStat::BinDepth (float _binDepth) inline
Definition at line 44 of file VolumeSampledStat.h.
kkint32 MLL::VolumeSampledStat::BinId () const inline
Definition at line 39 of file VolumeSampledStat.h.
Referenced by MLL::VolumeSampledStatList::Add(), MLL::VolumeSampledStatList::Give(), and MLL::DataBase::InstrumentDataGetVolumePerMeterDepth().
void MLL::VolumeSampledStat::BinId (kkint32 _binId) inline
Definition at line 43 of file VolumeSampledStat.h.
float MLL::VolumeSampledStat::VolumeSampled () const inline
Definition at line 41 of file VolumeSampledStat.h.
Referenced by MLL::VolumeSampledStatList::Add(), MLL::VolumeSampledStatList::Give(), MLL::DataBase::ImagesSizeDistributionByDepth(), and MLL::DataBase::InstrumentDataGetVolumePerMeterDepth().
void MLL::VolumeSampledStat::VolumeSampled (float _volumeSampled) inline
Definition at line 45 of file VolumeSampledStat.h.
The documentation for this class was generated from the following files:
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/VolumeSampledStat.h
C:/Users/kurtk_000/GitHub/Pices/PicesLibraries/PicesLibrary/VolumeSampledStat.cpp