Pices: PicesCommander.SizeDistribution.ClassTotals Class Reference
PicesCommander.SizeDistribution.ClassTotals Class Reference
Public Member Functions
ClassTotals (String _name, int _bucketCount, int _bucketSize)
void AddIn (ClassTotals classTotals)
int BucketCount (int idx)
void CleaUpMemory ()
void Increment (int size)
void PrintCSVLine (System.IO.StreamWriter o)
void PrintFormatedLine (System.IO.StreamWriter o)
void PrintTabDelLine (System.IO.StreamWriter o)
Properties
String Name [get]
String NameUpper [get]
Detailed Description
Definition at line 20 of file SizeDistribution.cs.
Constructor & Destructor Documentation
PicesCommander.SizeDistribution.ClassTotals.ClassTotals (String _name, int _bucketCount, int _bucketSize) inline
Definition at line 30 of file SizeDistribution.cs.
Member Function Documentation
void PicesCommander.SizeDistribution.ClassTotals.AddIn (ClassTotals classTotals) inline
Definition at line 71 of file SizeDistribution.cs.
Referenced by PicesCommander.SizeDistribution.Add(), PicesCommander.SizeDistribution.PrintCSVDistributionMatrix(), PicesCommander.SizeDistribution.PrintFormatedDistributionMatrix(), and PicesCommander.SizeDistribution.PrintTabDelDistributionMatrix().
int PicesCommander.SizeDistribution.ClassTotals.BucketCount (int idx) inline
Definition at line 83 of file SizeDistribution.cs.
Referenced by PicesCommander.SizeDistribution.PrintByClassCollumns(), and PicesCommander.SizeDistribution.SumUpFamilyOfClassesForBucket().
void PicesCommander.SizeDistribution.ClassTotals.CleaUpMemory () inline
Definition at line 47 of file SizeDistribution.cs.
void PicesCommander.SizeDistribution.ClassTotals.Increment (int size) inline
Definition at line 56 of file SizeDistribution.cs.
Referenced by PicesCommander.SizeDistribution.Increment().
void PicesCommander.SizeDistribution.ClassTotals.PrintCSVLine (System.IO.StreamWriter o) inline
Definition at line 111 of file SizeDistribution.cs.
Referenced by PicesCommander.SizeDistribution.PrintCSVDistributionMatrix().
void PicesCommander.SizeDistribution.ClassTotals.PrintFormatedLine (System.IO.StreamWriter o) inline
Definition at line 91 of file SizeDistribution.cs.
Referenced by PicesCommander.SizeDistribution.PrintFormatedDistributionMatrix().
void PicesCommander.SizeDistribution.ClassTotals.PrintTabDelLine (System.IO.StreamWriter o) inline
Definition at line 127 of file SizeDistribution.cs.
Referenced by PicesCommander.SizeDistribution.PrintTabDelDistributionMatrix().
Property Documentation
String PicesCommander.SizeDistribution.ClassTotals.Name get
Definition at line 52 of file SizeDistribution.cs.
Referenced by PicesCommander.SizeDistribution.Add().
String PicesCommander.SizeDistribution.ClassTotals.NameUpper get
Definition at line 54 of file SizeDistribution.cs.
The documentation for this class was generated from the following file:
C:/Users/kurtk_000/GitHub/Pices/Apps/PicesCommander/SizeDistribution.cs